### ISSUE TITLE
Can you add multiple files support?

### ISSUE THREAD

**Issue by XiangruiCAI** [James-Yu/LaTeX-Workshop#1]
For writing a long document, multiple files is a good way to construct a tex project. Several famous editors support a tex project with multiple tex files.
[sublime latextools](http://tex.stackexchange.com/questions/174886/how-to-set-main-file-in-latextools-with-sublime-text-3-editor)
[emacs auctex](https://www.gnu.org/software/auctex/manual/auctex/Multifile.html)
[vim latex-suite](http://vim-latex.sourceforge.net/documentation/latex-suite/latex-project.html)
Could you please add this feature to latex-workshop plugin?

**Comment by James-Yu** [comment]
Sure it was on the top of my TODO list.

**Comment by XiangruiCAI** [comment]
Great! Looking forward to the new features.

**Comment by James-Yu** [comment]
Implemented. The commit should be 14f1020e5c2377d7cc2c312aac62930bc3615d22

Now it checks if the current document is tex-able. If not, it will search through the root folder of the opened workspace.

**Comment by sheep94lion** [comment]
It won't work when multiple files are in the same directory.

**Comment by jlelong** [comment]
For sure, it does. If you face a problem with this, please open a new issue with an example to reproduce.
