### ISSUE TITLE
Intellisense opening at an inoppurtune time

### ISSUE THREAD

**Issue by wondermike221** [James-Yu/LaTeX-Workshop#10]
I use latex to typeset my math homework and I use \\ alot to get new lines but the intellisense pops up after this is typed and then I hit enter which puts the first intellisense option in.
I feel that this should be an exception to the intellisense opening, or it should open after a letter is typed after the backslash.

**Comment by James-Yu** [comment]
What about this: the first suggestion for backslash is a newline command when no prefix given. Therefore when hit enter the newline is inserted.

Will check if it is doable shortly.

**Comment by wondermike221** [comment]
That sounds like a good solution if it can be done.
I like the way microsofts language support extension handles it if that helps. I would use it but your extension handles everything else much better.

**Comment by James-Yu** [comment]
New version `0.2.13` published to implement the said feature.
