### ISSUE TITLE
Cannot find LaTeX root file.

### ISSUE THREAD

**Issue by melgu** [James-Yu/LaTeX-Workshop#100]
LaTeX-Workshop doesn't find the root file when I use the _Magic comment_ method. Using the absolute instead of the relative path doesn't help either.

<img width="1094" alt="screencap" src="https://cloud.githubusercontent.com/assets/9601403/24838431/fd6d39e0-1d47-11e7-88ce-79579ae72475.png">

**Comment by James-Yu** [comment]
Please try `TEX` instead of `TeX`. The bug was fixed in the repo but not released to the marketplace. Please confirm if it works or not.

**Comment by melgu** [comment]
It works, thank you so much!
