### ISSUE TITLE
We should provide a user documentation

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1007]
The extension has grown up a lot over the last months with a lot new features, which is super great.

I think we should put some efforts to provide a documentation describing all this. In particular, a lot of configuration variables have been introduced to tweak the behavior of the extension and it is only a little described in [package.json](https://github.com/James-Yu/LaTeX-Workshop/blob/master/package.json). This would also spare us a lot of false bug reports.

What is your feeling about it? Any idea, suggestion?

**Comment by James-Yu** [comment]
I absolutely agree with you. The readme was inherited from the ancient pre-1,0 time. How do you suggest we should rearrange it?

**Comment by jlelong** [comment]
A brief sketch of what I had in mind

## Hosting the manual

We can create a GitHub Pages to have an online manual. The manual would be generated directly from `.md` files using Jekyll and we would have a fine control of the overall rendering. Several templates are already available. For instance, this is the approach used by vscode itself or Bootstrap.
@James-Yu as the owner of the project, you are the only who can create and configure a GitHub Page.

## Content of the manual

Here is a proposal of a TOC

1. Installation and basic settings
1. Compiling
1. Viewing & synctex
1. Linters
1. Muti file projects
    - Auto detection of the "main" file.
    - Setting the main file manually
1. Intellisense
    - `cite`
    - `label` 
    - filenames
1. Snippets and shortcuts
    - Inserting greek letters
    - Handy mathematical snippets
    - Font shorcuts
    - Some shortcuts coming from vim-latex
    - Surround text with a command
1. FAQ and common issues

Inside each item, we can use the format suggested by @tecosaur.

I will edit this post with the propositions from the coming discussion.

**Comment by James-Yu** [comment]
I will create a Page and see how it works. I'd like to re-write it soon, but I will have a IRL family vacation from the next week. Will see how I can contribute to the page.

**Comment by tecosaur** [comment]
To help with the workload i I'd be happy to write out the bits for the functionality I know about :)

**Comment by James-Yu** [comment]
The [page](https://james-yu.github.io/LaTeX-Workshop/) is created and it seems that currently the README.md is parsed and converted. I also created a `docs` folder, but I'm not sure which source is better.

**Comment by jlelong** [comment]
One thing to keep in mind: the Visual Studio Marketplace only displays the README. So to start, I would suggest to keep the README as it is and just add a link to the documentation.

> The page is created and it seems that currently the README.md is parsed and converted. I also created a docs folder, but I'm not sure which source is better.

I cannot see the setting pane of the project but normally there is setting to set the source to build the Page and you have to choose `master branch/docs`. Once this is fixed, we have to choose a good theme for a documentation page. Something like the [Just the docs theme](https://github.com/pmarsceill/just-the-docs) would match our needs I guess. Any other suggestion is welcome. Then, I can make the setup and create the general structure and we will be ready to welcome contributions.

**Comment by tecosaur** [comment]
Sorry to add this a bit late, but have you considered a Github wiki? It seems like it would be perfect for this sort of thing.

**Comment by jlelong** [comment]
@tecosaur I had thought of it at the beginning but I had the feeling it was not really nice looking. Thanks to your comment, I have done a bit more googling and it seems more configurable than I thought, see [here](https://help.github.com/articles/about-github-wikis/).
@James-Yu can you activate the wiki so that we can start playing a bit and see if it matches our needs?

**Comment by James-Yu** [comment]
No problem!

**Comment by jlelong** [comment]
I have started putting the general structure of the documentation based on my previous posts. Now, we have to fill the blanks.
