### ISSUE TITLE
Bundle windows binary of synctex with the extension

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#1008]
**Is your feature request related to a problem? Please describe.**
MikTeX does not ship synctex, which leads to many issue reports in the repository.

**Describe the solution you'd like**
It seems that only two small binary files, i.e., an `exe` and a `dll` is required for the functionality. We may bundle them in the package and include the directory in `cp.spawn` path env.

**Describe alternatives you've considered**
Hmm... Letting LaTeX newcomers to know that MikTeX does not have synctex is actually unnecessary.

**Additional context**
However, all my testing PCs are equipped with TeXLive. I may need some volunteer to test a potential implementation/PR. Also, whether we should bind them is still an open question, though I am a bit inclined to do so. Discussions welcomed.

**Comment by tamuratak** [comment]
There is a parser [tdurieux/synctex-js](https://github.com/tdurieux/synctex-js) for *.synctex files written in JavaScript by @tdurieux. So, we might be able to implement the synctex command as a function in TypeScript. This allows us to execute the synctex command synchronously. By using this function, we might be able to implement a synchronous scroll although I am not a fan of the synchronous scroll.

**Comment by tdurieux** [comment]
Technically it is completely possible I implemented this feature for BlueLatex.
I am also not a big fan of synchronous scroll.
What I did that I found pretty useful is to highlight the current line in the PDF.

**Comment by tecosaur** [comment]
Jumping in on synchronous scroll, simply put I think some like it some don't. This seems like the sort of thing where some sort of setting would be a good idea ;)

**Comment by jlelong** [comment]
I guess this issue has been outdated by @tamurak's [PR](#1030).
Set  `latex-workshop.synctex.synctexjs.enabled` to `true`.
