### ISSUE TITLE
LaTeX Workshop Activity Bar opens without being called

### ISSUE THREAD

**Issue by kjshen** [James-Yu/LaTeX-Workshop#1009]
Hello, recently started using this extensions with VSCode for LaTeX and like it very much. This is my first bug report:

**Describe the bug and Steps to reproduce the behavior:**
Just got the 5.17.2 update and the following behavior started:

When the Activity Bar is closed (Ctrl + B), the LaTeX Activity Bar opens when:
- using SyncTex from pdf to code (Ctrl + left click)
- opening the pdf-Previewer (Ctrl + Alt + V) when pdf-Previewer is not yet opened
- selecting already opened Settings Tab with left click
- selecting already opened pdf-Previewer Tab with left click after another tab was selected

**Expected behavior**
Before, the LaTeX Activity Bar never opened up without being called. I usually like it closed to have more area on the screen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.29.1
 - Extension version: 5.17.2

![demonstration](https://user-images.githubusercontent.com/45091615/48909107-a95b1f00-ee6c-11e8-9251-5e0de234cb0d.gif)

**Comment by jlelong** [comment]
This is related to [1006](https://github.com/James-Yu/LaTeX-Workshop/issues/1006#issuecomment-440570698). You can set `"latex-workshop.view.autoActivateLatex.enabled": false` to fix the issue.

**Comment by James-Yu** [comment]
emmm... Never expected that executing the command would un-collapse the sidebar. Will set the default value to `false`.

**Comment by kjshen** [comment]
Thank you for you quick replies! That fixed it.

**Comment by zhyiyu** [comment]
It seems like setting `latex-workshop.view.autoActivateLatex.enabled` is no longer available. I would like this feature for the following reasons

1. my activity bar is kept open
2. I would like to be able to access compilation without having to manually click into the side bar of latex workshop

Also, it is just as great if the compilation button is available in the status bar at the bottom or anywhere that is available outside the extension.

Thanks!

**Comment by tamuratak** [comment]
Please open a new issue.
