### ISSUE TITLE
\cite{} intellisense doesn't work in subfolder

### ISSUE THREAD

**Issue by skamoen** [James-Yu/LaTeX-Workshop#101]
When I have my chapter .tex files in a subfolder `/chapters/chapter1.tex`, the intellisense autocomplete for the `\cite{}` command doesn't work anymore. When I move the same file from the subfolder to the root folder, it works again.

**Comment by James-Yu** [comment]
I cannot reproduce the problem. Can you please provide your log when the source file is in root and subfolder?

**Comment by skamoen** [comment]
Thanks for the extremely fast response!

I think I found the issue. There was another tex file in the root, which was selected as the root document. As there was no bibliography in there, there was nothing to display. By using the magic comment in the chapter file, it found the right root file and it worked again. 

Not sure why the move to root worked last time...

Anyway, is there a better way to disqualify a file as root, or set the root as a workspace setting? The comment in each chapter is an acceptable solution, but a single place to define the root seems better :)

**Comment by James-Yu** [comment]
Thanks for the info. Originally (<version 1.0) there was a workspace configuration defining the root file. It was accidentally removed and never added back. Will consider adding it back soon.

**Comment by skamoen** [comment]
Cool. I'll use the magic comment for now. Thanks again and keep up the great work, I really like the extension!
