### ISSUE TITLE
Disable Minted/Pygmentize warning when compile document over a docker-container

### ISSUE THREAD

**Issue by volker-raschek** [James-Yu/LaTeX-Workshop#1010]
**Describe the bug**
I use my own docker container to compile my latex document. I have in my latex code some julia or r-code content which I highlight with minted. But on my own PC I don't have installed latex neither nor minted.

So I get in visual studio code every time an error when I use source code which I want to highlight. 
It's would be nice, if there is a setting to disable minted warnings when I compile my document with a docker container.

**To Reproduce**
1. Go to settings
2. Set this settings:
```json
{
  "latex-workshop.docker.enabled": true,
  "latex-workshop.docker.image.latex": "volkerraschek/docker-latex:latest",
}
```
3. Make sure that no minted or pygmentize is installed
3. Compile a document with source code content over your docker container
4. See error in visual studio code like this one
```
Package minted: You must invoke LaTeX with the -shell-escape flag.
Package minted: You must have `pygmentize' installed to use this package.
```

**Comment by James-Yu** [comment]
'latex-workshop.message.latexlog.exclude' config can use regexpr to exclude log messages.
