### ISSUE TITLE
Switching tabs from a non-tex file to a tex file and using synctex opens sidebar

### ISSUE THREAD

**Issue by Festbawi** [James-Yu/LaTeX-Workshop#1011]
**Describe the bug**
Causes that I've found:
1. Select a non-tex file as the active tab, switch to a tab with a tex file
2. Ctrl+Click in the pdf viewer (I use the VS Code tab), do any other click within the pdf.
Effect: Sidebar of LaTeX Workshop opens

I am unsure if this is the intended behavior, because it didn't do this before.

**To Reproduce**
1. Select a non-tex file as the active tab, switch to a tab with a tex file or Ctrl+Click in the pdf viewer (I use the VS Code tab), then do any other click within the pdf (sometimes it does not require another click)
3. Sidebar of LaTeX Workshop opens

**Expected behavior**
The sidebar will not open

**Logs**
No logs in the OUTPUT tab show up when the side bar opens when I switch tabs or through synctex. There are also no suspicious console log messages, only these:

![image](https://user-images.githubusercontent.com/8520418/48927303-c98fea00-ef0f-11e8-8903-488bbb7cbec3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.29.1
 - Extension version: 5.17.2

**Comment by James-Yu** [comment]
#1009 Fixed in next release.
