### ISSUE TITLE
Lualatex not working with option -lualatex

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1019]
**Describe the bug**
The tool that I defined to use lualatex with option ```-lualatex``` uses ```pdflatex```.

**To Reproduce**
```
  "latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-lualatex",
        "-pdf",
        "%DOC%"
      ]
    }
]
```

**Expected behavior**
I would like that the lualatex engine would be used, using ```-pdflatex=lualatex``` messes up with my ```.latexmkrc``` file.

**Logs**
With 
```
[16:23:12] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-lualatex,-pdf,/***
```
I obtain 
```
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
```
and
```
=== TeX engine is 'pdfTeX'
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS high sierra 
 - VS Code version: 1.29.1
 - Extension version: 5.17.3

**Additional context**
It works when I call lualatex in the terminal so I guess it is an issue with parsing the arguments.

**Comment by PierreMarchand20** [comment]
Ok, it works when I use both ```-pdflatex=lualatex``` and ```-lualatex``` options. It is a workaround for now.

**Comment by James-Yu** [comment]
You can't have `-pdf` and `-lualatex` at the same time. This is the rule of `latexmk`.
