### ISSUE TITLE
PDF viewer keyboard shortcuts?

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#1022]
Are there any working keyboard shortcuts to control the PDF preview window? Or does everything have to happen with a mouse?

I'm especially thinking about:

- Show/hide bookmarks / tabel of contents
- Zoom to fit page
- Zoom to fit width
- Zoom 100%
- Goto page
- Next page
- Previous page

**Comment by zoehneto** [comment]
The PDF viewer uses pdf.js internally, the shortcuts supported by pdf.js are documented [here](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts). These definitely work when you open the viewer in the browser, I haven't tested them inside vs code.

**Comment by GandalfSaxe** [comment]
Thanks, exactly what I was looking for. Perhaps provide link in documentation for LaTeX-Workshop in the readme?
