### ISSUE TITLE
Contribute to the wiki

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1029]
This is not a Bug Report but a call for contributions to the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki), which will serve a detailed documentation for the extension, see #1007.

**Comment by tecosaur** [comment]
(Among other things) Thanks for reminding me about my earlier promise.

**Comment by jlelong** [comment]
@tecosaur you are right there is no straightforward way to make a PR on a github wiki.
I have just set up a new [github repo](https://github.com/jlelong/LaTeX-Workshop-wiki) containing the wiki content that can be forked. Then you can make PR and I will take care of the merge into the [true wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki).
I have added a link at the bottom of every page to contribute.

**Comment by James-Yu** [comment]
Hmm I don't think there is a wiki entry in the resource section, nor did I find anything related in package.json. @jlelong any idea?

**Comment by jlelong** [comment]
I thought I had seen extensions with a documentation entry in the resources list but I cannot find it anymore. Ok, let's forget it. Anyway, I have added a link to the wiki at the beginning of the README.

**Comment by jlelong** [comment]
I have started a section on hovering features in the wiki. @tamuratak, could you help use with documenting hovering for maths and references?

**Comment by jlelong** [comment]
The section on formatting also needs some contribution...
More generally, we need help to double read the wiki and point out missing stuff.

**Comment by tamuratak** [comment]
@jlelong, sure. How do we add new screenshots?

**Comment by jlelong** [comment]
There are two approaches:
1. Upload the screenshots to [LaTeX-Workshop/demo_media](https://github.com/James-Yu/LaTeX-Workshop/tree/master/demo_media) and refer to them using a full url link. As they are part of LaTeX-Workshop's repo, they can be used in the README.
1. Create a `demo_file` directory in [wiki git](https://github.com/jlelong/LaTeX-Workshop-wiki) and upload the screenshots there. Then, you can use relative links.

In both cases, you will add to use [wiki git](https://github.com/jlelong/LaTeX-Workshop-wiki) to add the links and associated explanations. 
Hope this helps.

**Comment by jlelong** [comment]
@James-Yu, I have just come across what I was looking for concerning the _Resources_ section on marketplace. If you add a `homepage` entry in `package.json`, you will get a new item named _Homepage_ in the _Resources_ section.
See [Cmake package.json](https://github.com/twxs/vs.language.cmake/blob/master/package.json#L18) and [CMake Marketplace](https://marketplace.visualstudio.com/items?itemName=twxs.cmake).

**Comment by jlelong** [comment]
Even though the wiki still needs to be updated, I am closing this issue.
