### ISSUE TITLE
Can't open PDF when setting output directory

### ISSUE THREAD

**Issue by fsonntag** [James-Yu/LaTeX-Workshop#103]
When I set the output directory in the latex toolchain, the produced PDF doesn't open anymore.

E.g.:
```
"latex-workshop.latex.toolchain": [
    {
      "command": "latexmk",
      "args": [
        "-outdir=output",
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "%DOC%"
      ]
    }
  ]
```

I find this really handy to separate the output files and the rest, but not being able open the PDF then is kind of a deal breaker.

Anyway thanks for this great plugin, I appreciate all the work done!

**Comment by James-Yu** [comment]
There is no way for the extension to detect the output file path (imagine someone `mv` files after building projects to another folder)

Do you have any idea on how to achieve the feature?

**Comment by James-Yu** [comment]
The change will be release soon.

**Comment by fsonntag** [comment]
That was fast, thanks!

**Comment by 3rfan** [comment]
Thank you so much @fsonntag. The part with `-outdir=output` was the missing piece I have needed. Was sitting there for over 3 hours without any clue 🙈 

@James-Yu please add an example of how to set the `-outdir` for `latexmk`. The example you will find on google doesn't work with Latex-Workshop. Additionally I think that the naming of `latex-workshop.latex.outputDir` is confusing. Would suggest something like `existingOutputDir`. It's not a fancy name but imo it's more explicit. 

Btw. thank you for your effort on making this awesome extension! ❤️
