### ISSUE TITLE
autocite snippet improvement

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1033]
Among citation snippets, `autocite` snippet is not completely implemented. When I type `\au` I see `autocite` being suggested. But when I select that suggestion (using `tab` or `enter` key), only `\autocite` gets autocompleted and not `\autocite{<cursor-here>}` .

This suggests that `autocite` might not have been implemented. (I might be getting it in my suggestions probably because I have already used this command in other places within the tex file). 

Would it be possible to implement it similar to other citation snippets. For example, `textcite` and `cite` suggestions, I get `\textcite{$1}$2`.

PS - for `autocite`, I do get bibkey autocomplete suggestions once I type `{}`

**Comment by werunom** [comment]
Just to refer to related discussions, autocompletion for `textcite` was brought up during [this discussion](https://github.com/James-Yu/LaTeX-Workshop/issues/744#issuecomment-415865769).

**Comment by jlelong** [comment]
The `autocite` command is provided by the `biblatex` package. You have to include this package in your tex file to make the `\autocite{}` snippet available.

**Comment by werunom** [comment]
I had included `biblatex-chicago` ...but found that it does not have `autocite`. 

Anyways, thanks for pointing how generally snippets are made available by the extension. Is this info available in the package description? I quickly went through it and did not find it. Can you please add this?

**Comment by jlelong** [comment]
A documentation of the extension will be available soon, but for now this rather new feature is not documented yet.

Concerning your issue, the problem is that the `biblatex-chicago` package is actually a wrapper around the `biblatex` package with specific options. The internal mechanism has no knowledge of this and does not include `biblatex` commands to intellisense.

**Comment by werunom** [comment]
related to your analysis of the issue, I am bit confused. I also thought that `biblatex-chicago` should inherit all the options from its parent. But when I checked its `package-documentation` (available [here](https://ctan.org/pkg/biblatex-chicago?lang=en)), it clearly mentions (in page 52) that `autocite` is not implemented. Does not this imply that its not straightforward (or obvious) whether wrapper package  would have all the options of its parent?

**Comment by jlelong** [comment]
Hum, I have just tested it and I confirm that `bilatex-chicago` does provide `autocite`.

Anyway, we just provide more items for intellisense. If you provide a few items that should not be, it may not be that much of a problem.

**Comment by werunom** [comment]
> Hum, I have just tested it and I confirm that `bilatex-chicago` does provide `autocite`.

Do you mean autocite is available in biblatex-chicago in general or the suggestion is available through the latex-workshop package?

Because, after you mentioned, I checked in vscode two scenarios - one by using `\usepackage{biblatex}` and the other by using `\usepackage{biblatex-chicago}`. Only for the former, I was given `\autocite` suggestion.

**Comment by werunom** [comment]
Gotcha! Thanks for opening the right issue and working on it. Will wait :)

**Comment by jlelong** [comment]
Just fixed #1034. Should work now!
