### ISSUE TITLE
citation suggestions not getting updated

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1035]
In my current setup, I am getting citation suggestions for latex cite commands (like `autocite{}` and `textcite{}`) from the bib-file. I have configured the extension to work with this bib file by specifying the path to this in `latex-workshop.latex.additionalBib`.

However, whenever I update the bib file (using zotero) with new citation keys, these keys are not available in the suggestions I get. Only when I restart vscode, I get the suggestions. This suggests that the suggestion citekeys are not updated when the bib-file is updated at the back. 

This issue is not observed with the extension [pandoc-citer](https://marketplace.visualstudio.com/items?itemName=notZaki.pandocciter) which uses latex-workshop logic for providing the citation keys for markdown files. Upon updating the bib-file, I do get the updated citekeys in the suggestions for markdown files.

**Comment by jlelong** [comment]
Cannot reproduce this issue.

When loading the extension, the files listed in `latex-workshop.latex.additionalBib` are set up for watching if they exist and then thanks to the watching process any modification to these files are visible inside the extension. No need to restart/reload vscode.

Can you have a look at the _Output_ pane and tell us if there are lines like
```
Bib file watcher - responding to change in 
Parsing ???? .bib entries 
```

**Comment by werunom** [comment]
I have encountered the above mentioned issue couple of times. However, I havent figured out the exact steps to reproduce. As of now, I will close this issue and will keep an eye for encountering this issue again.

**Comment by mnchsmn** [comment]
I am experiencing a similar issue. However I am just using a regular .bib file in the root directory of my project. Whenever this is updated, the citation browser doesn't register the changes. Cleaning aux files does not help. I can copy the citation key by hand and cite it and it will build just fine, however even after that, the citation browser doesn't find the citation. What helps is executing the VS Code "Developer: Reload Window" command.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#auto-build-does-not-work-sometimes
