### ISSUE TITLE
Modifying the citation related snippets

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1036]
At present, the citation snippets like `\textcite`, `\cite` have the following structure --- `\cite{$1}$2`. 

This is fine if citation commands in latex only take bibkeys as input. However this is not the case. According to the bibtex package, the generalized structure of citation keys usually has this structure 
`\cite[prenote][postnote]{key}` where `prenote` and `postnote` are optional parameters. 
In regular use, citation commands also include page-numbers. For instance, an usual citation command would look like `\cite[92]{werunom2018}`. 

Given this, I think a balance can be struck between bare autocomplete (which is presently implemented) and the general structure of these commands (as mentioned in the biblatex documentation). One of the ways of striking the balance would be to have this structure --- `\cite$2{$1}$3`. By this, if the user can carry out the following sequences when `tab` is pressed:
1. entering required bibkey 
2. enter post/pre note parameters (like relevant page-number, page-range, etc.) 
3. and continuing with further writing. 

The above suggestion is just one way of improvising.

**Comment by jlelong** [comment]
Not sure this optional argument of `\cite` is widely used.  If it is your case, you can always define your own snippet with the optional argument.

Using `\cite$2{$1}$3` for all citation snippets is quite a heavy work since they are provided by different packages and we automatically build our snippets from `.cwl` files. See #992.

**Comment by jlelong** [comment]
OK, I will investigate how to generate snippets for the different versions of a command, with and without the optional arguments.

**Comment by jlelong** [comment]
See #850 and [609](https://github.com/James-Yu/LaTeX-Workshop/issues/609#issuecomment-387953870) for a discussion on why we changed from `\($1\)$0` to `\($0\)`.

**Comment by werunom** [comment]
Thanks for pointing those related discussions. Nice to see that there have been some discussions and justified reasons provided for the same. 

If the whole issue of tabbing out was removed in order to allow nesting snippets, then would not the same reason apply for not allowing `\cite$2{$1}$3`? I am just curious now why you thought of entertaining what I suggested in the first place :)

**Comment by jlelong** [comment]
With `\cite`, you do not nest snippets so there is no problem.

**Comment by werunom** [comment]
Oh! Silly of me not to think of that.
