### ISSUE TITLE
Set default bibliography directory

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#1042]
**Is your feature request related to a problem? Please describe.**
The `"latex-workshop.latex.additionalBib"` option seems useful. But when I build my `.tex` file I still need to `\bibliography{/path/to/mybib}`.
Is there a way to define a default bibliography folder (externally), and every time I can just call `\bibliography{mybib}`?

**Describe the solution you'd like**
An option to set the default bibliography folder.
Plus, it would be good to have some tutorial for `addtionalBib` in README file.

**Additional context**
Sorry if it's a dumb question.

**Comment by jlelong** [comment]
> Is there a way to define a default bibliography folder (externally), and every time I can just call \bibliography{mybib}?

This is not related to the extension but rather a LaTeX question.
Actually, in your example, the `mybib` file is looked up in every folder listed in the environment variable `BIBINPUTS` if it is defined or in the current directory otherwise.

**Comment by ShuCaiMonkaS** [comment]
> > Is there a way to define a default bibliography folder (externally), and every time I can just call \bibliography{mybib}?
> 
> This is not related to the extension but rather a LaTeX question.
> Actually, in your example, the `mybib` file is looked up in every folder listed in the environment variable `BIBINPUTS` if it is defined or in the current directory otherwise.

After setting this up, it works in my terminal, but not working with recipes. It's weird

**Comment by ShuCaiMonkaS** [comment]
> > Is there a way to define a default bibliography folder (externally), and every time I can just call \bibliography{mybib}?
> 
> This is not related to the extension but rather a LaTeX question.
> Actually, in your example, the `mybib` file is looked up in every folder listed in the environment variable `BIBINPUTS` if it is defined or in the current directory otherwise.

I added to the
