### ISSUE TITLE
Problem with environment variable BIBINPUTS and recipe

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#1044]
**Describe the bug**
I have a main.tex file with `\bibliography{references}` in it.

After set up environment variable BIBINPUTS=/path/to/folder, whenever it use `bibtex main`, it will correctly load bib file "/path/to/folder/references.bib".

How ever, if I use latex recipe `bibtex` defined as
```
{
      "name": "bibtex",
      "tools": [
          "bibtex"
      ]
}
```

I will not work.
 
**To Reproduce**

1.  File setup
main.tex 
```
\documentclass{article}

\title{Test}
\begin{document}

\bibliographystyle{plain}
\bibliography{references}

\end{document}
```
Environment variable from terminal
```
$BIBINPUTS = /path/to/folder/
```
Bib file `/path/to/folder/references.bib`.

2. If manually execute
```
pdflatex main.tex
bibtex main
pdflatex main.tex
pdflatex main.tex
```
it will work and produce a pdf with reference empty.

3. If use latex.recipes `"pdflatex->biblatex->pdflatex*2"`, there will be error (like the one shows in the logs).

**Expected behavior**
Should have log output
```
This is BibTeX, Version 0.99d (TeX Live 2018)
The top-level auxiliary file: main.aux
The style file: plain.bst
Database file #1: references.bib
(There was 1 error message)
```
with output main.bbl
```
\begin{thebibliography}{}

\end{thebibliography}
```
**Logs**
```
This is BibTeX, Version 0.99d (TeX Live 2018)
The top-level auxiliary file: main.aux
The style file: plain.bst
I couldn't open database file references.bib
---line 3 of file main.aux
 : \bibdata{references
 :                    }
I'm skipping whatever remains of this command
I found no \citation commands---while reading file main.aux
I found no database files---while reading file main.aux
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1
 - VS Code version: Version 1.29.1
 - Extension version: 5.17.3

**Additional context**
If I define a tool 
```
{
      "name": "echo",
      "command": "echo",
      "args": [
        "$BIBINPUTS"
      ]
    }
```
when I tried it, the output window is just 
```
$BIBINPUTS
```

#169 also seems to have problem with BIBINPUTS

**Comment by jlelong** [comment]
This is related to the way vscode handles environment variables. I guess vscode inherits environment variables from its father process. So to make sure BIBINPUTS is defined, set it in the terminal and then launch vscode from this terminal. This has nothing to with the extension.

The quotes around `"$BIBINPUTS"` in your extra tool should probably be removed.

**Comment by ShuCaiMonkaS** [comment]
That's means I have to open from terminal everytime. Sometimes, I open it from app in Mac.

Is there a way around it?

**Comment by jlelong** [comment]
Yes, you have to open it from the terminal. No workaround.

**Comment by ShuCaiMonkaS** [comment]
Thanks, I will try if that works.

**Comment by ShuCaiMonkaS** [comment]
> Yes, you have to open it from the terminal. No workaround.

I tried VSCode option `Install 'code' command in PATH`.
Afterward, both launch from the terminal and directly open it from app solves the problem.

Both `$BIBINPUTS` and `"$BIBINPUTS` will not give the desired output (it doesn't matter now since the problem is solved).
