### ISSUE TITLE
Syntax highlighting is wrong after setting esacpeinside in listings package.

### ISSUE THREAD

**Issue by Leoongithub** [James-Yu/LaTeX-Workshop#1046]
**Describe the bug**
When I use package "listings" and set escapeinside, then the syntax highlighting seems to be wrong.

**To Reproduce**
A minimum tex file to reproduce this bug. It may relate to unclosed quote `'.
```
\documentclass{article}
\usepackage{listings}
\lstset{escapeinside=``}
\begin{document}
Something here %this line's highlighting
\end{document}
```

**Expected behavior**
Right syntax highlighting.

**Logs**
Unrelated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.29.1
 - Extension version: 5.17.3

**Comment by sjiang95** [comment]
The same problem encountered when using package `minted`.

```tex
\documentclass{article}
\usepackage{algorithm}
\usepackage{minted}
\usepackage{lipsum}
\begin{document}

\begin{algorithm}
\begin{minted}[escapeinside=||]{python}
	def func(a=|$\alpha$|): % escape $alpha$ to print the Greek alphabet
        pass
\end{minted}
\end{algorithm}

\lipsum

\end{document}
```

## Screen shot

### Editor

<img width="469" alt="image" src="https://user-images.githubusercontent.com/51251025/229703256-4b4dc68c-9f49-42ac-9e8b-d74b34e8e957.png">

### PDF

Compiled by `pdflatex`.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/51251025/229703738-b89d3407-e580-4fe7-a968-dd0d81201662.png">

- Operating System: Ubuntu 22.04.2 LTS
- Visual Studio Code Version: 1.77.0
- LaTeX Workshop Version: 9.8.2
- TeX Distribution Version: TeX Live 2023

**Comment by jlelong** [comment]
Unfortunately, the grammars used by VS Code are purely static. There is no way to make it aware of escape characters.

**Comment by sjiang95** [comment]
> Unfortunately, the grammars used by VS Code are purely static. There is no way to make it aware of escape characters.

Thank you. But it's so sad.😔
