### ISSUE TITLE
Compilation broken by --tex-option in the README's texify toolchain

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#105]
Since 2.0.0, compilation is only successful with the `texify` toolchain if I delete the line `"--tex-option=\"-interaction=nonstopmode -file-line-error\""`.

Not being very familiar with texify or this particular option, I can't tell if the issue is on my end - but this toolchain did work in the previous version.

The latexmk toolchain does work as expected.

**Comment by jose-a-sa** [comment]
I have a similar problem. when having a multi-tex setup, with all the `% !TEX root` commands setup up. It was working in the previous version but now it gives this log (Finds root Paper.tex, but builds main.tex)

```
[21:42:23] BUILD command invoked.
[21:42:23] Found root file from active editor: d:\Jose\MEGA\University\5th YEAR\Dissertation\Paper\Paper.tex
[21:42:23] Root file remains unchanged from: d:\Jose\MEGA\University\5th YEAR\Dissertation\Paper\Paper.tex.
[21:42:23] Building root file: d:\Jose\MEGA\University\5th YEAR\Dissertation\Paper\Paper.tex
[21:42:23] Build root file d:\Jose\MEGA\University\5th YEAR\Dissertation\Paper\Paper.tex
[21:42:23] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,d:\Jose\MEGA\University\5th YEAR\Dissertation\Thesis\main
[21:42:24] LaTeX log parsed with 3 messages.
[21:42:24] Toolchain returns with error. Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(d:/Jose/MEGA/University/5th YEAR/Dissertation/Thesis/main.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.

! LaTeX Error: File `Thesis.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
d:/Jose/MEGA/University/5th YEAR/Dissertation/Thesis/main.tex:10: Emergency sto
p.
<read *> 
         
l.10 ^^M
        
d:/Jose/MEGA/University/5th YEAR/Dissertation/Thesis/main.tex:10:  ==> Fatal er
ror occurred, no output PDF file produced!
Transcript written on main.log.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
```

**Comment by James-Yu** [comment]
@zachjweiner I personally do not use `texify` and doesn't have an installation. Can you please suggest a proper tool chain of it? If it won't work for any configuration, I will remove the section in readme.

@jose-a-sa Your log shows that it's a problem with your latex style file, not extension related.

**Comment by James-Yu** [comment]
@jose-a-sa got what you mean. Will look into it.

**Comment by zachjweiner** [comment]
@James-Yu I will look into it soon!

**Comment by James-Yu** [comment]
@jose-a-sa I can confirm this bug. Patch on the way.

**Comment by zachjweiner** [comment]
@James-Yu I found that breaking up the two options passed to `--tex-option` works, as such:

`"latex-workshop.latex.toolchain": [
		{
			"command": "texify",
			"args": [
			"--synctex",
			"--tex-option=\"-interaction=nonstopmode\"",
			"--tex-option=\"-file-line-error\"",
			"--pdf",
			"%DOC%.tex"
			]
		}
	]`

**Comment by James-Yu** [comment]
Thanks a lot! Will change the readme accordingly.

**Comment by zachjweiner** [comment]
I'll also note that I'm seeing a lot more warnings (but no errors) using `texify `vs. `latexmk`, which I don't believe was the case before. I do not know if this is a function of the `--tex-option` stuff or `texify `itself. Sticking with `latexmk `for the time being
