### ISSUE TITLE
Add bibitems to citation intellisense

### ISSUE THREAD

**Issue by starship863** [James-Yu/LaTeX-Workshop#1051]
Does the intellisense support citations defined by _thebibliography_ environment included in the main tex file?

Usually, we (physists) write papar with direct usage of _thebibliography_ environment without using the bibtex tool and bib files, as
```latex
\documentclass[11pt]{article}

\begin{document}
Main text \cite{key}.

\begin{thebibliography}{99}
\bibitem{key} Some reference.
\end{thebibliography}

\end{document}
```

However, it seems that the intellisense of **\cite{}** command does not support the usage of this _thebibliography_ environment. When I invode suggestions with shortcut, the intellisense does not show any suggestions of keys for the references defined in _thebibliography_ environment.

As a comparison, the intellisense works nicely for the **\ref{}** command.

Is it some problem that only I am experiencing, or is it some feature that is current not included in this extension?

Besides, thank you so much for the excellent extension.

**Comment by jlelong** [comment]
You are right _ thebibliography_ environments are not use for `\cite` intellisense.
I turn the issue into a feature-request.

**Comment by starship863** [comment]
> You are right _ thebibliography_ environments are not use for `\cite` intellisense.
> I turn the issue into a feature-request.

Thank you! Looking forward to this new feature.
