### ISSUE TITLE
Respect "Resize to Page With" option with page trimming enabled in PDF viewer

### ISSUE THREAD

**Issue by antifermion** [James-Yu/LaTeX-Workshop#1052]
If the PDF viewer is in the "Page Width" mode and I enable page trimming, I would like the automatic resizing to pagewidth to still occur.
Currently I have to manually adjust the zoom if page trimming is enabled and I change the width of the PDF viewer.

**Comment by James-Yu** [comment]
You are mis-understanding the trimming mode, which tries to hide the white spaces by enlarging the pdf. This contradicts with page-width.
