### ISSUE TITLE
Add $1 to jump out of snippets?

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#1059]
https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/latex.json#L475

In many of current snippets it is impossible to jump to the next scope once you've triggered the snippet. For example \( snippet expands to \( … \), but once you are done with typing … you want to move on by leaving \(\). I've observed this to be the case with many other snippets. Thoughts about reworking it?

@jlelong @tecosaur

**Comment by jlelong** [comment]
See the discussion in [609](https://github.com/James-Yu/LaTeX-Workshop/issues/609#issuecomment-387953870). The problem basically comes from the ability to nest snippets.

**Comment by Astrantia** [comment]
@jlelong So what was the final decision regarding this? Leaving it up to vscode? Also the issue referenced to vscode is about adding priorities to snippets. So if I understand correctly to have all issues with snippets will be gone when vscode adds priorities to snippets?

**Comment by jlelong** [comment]
@Astrantia there is currently an issue with some snippets and I cannot figure out why it is not working. I have posted an [issue on vscode repo](https://github.com/Microsoft/vscode/issues/64818). Hopefully, I will get some insights there and then return to our issue.

**Comment by Astrantia** [comment]
@jlelong I think we found a solution in your issue.

**Comment by jlelong** [comment]
I am playing a bit with the `wordPattern` regex and it does indeed solve our issue. Once this is done, I add back the jump out of snippets feature. I will do some further tests before pushing a fix.

**Comment by jlelong** [comment]
To have intellisense automatically triggered inside snippets, set `"editor.suggest.snippetsPreventQuickSuggestions": false`.

**Comment by lonelykid** [comment]
Is this feature implemented? seems not working for me.

**Comment by jlelong** [comment]
Yes. For which snippets, is not working?
