### ISSUE TITLE
Synctex and MikTeX

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#106]
With the ability to set the synctex path, I think I inched closer to getting synctex to work with LaTeX Workshop with a MikTeX installation, in that I get a different error now :)

First, I downloaded `synctex.exe` and `kpathsea622.dll` and placed them according to the second comment to [this answer](http://tex.stackexchange.com/a/338117/78245).

Then, sensibly, I set `"latex-workshop.synctex.path": "C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\synctex.exe"`.

Now, attempting to synctex in either direction produces the error `Cannot synctex, code: 3221225781`, which differs from errors thrown by being unable to find `synctex.exe`. Googling fails me at this point, but I thought I'd crowdsource, since it'd be nice to have a setup for MikTeX+LaTeX Workshop users.

**Comment by James-Yu** [comment]
Does it work well from command line? You may try executing the same command from cmd and see if problem persists.

**Comment by zachjweiner** [comment]
Thanks for the suggestion, @James-Yu! The command line had better errors that lead me to the issue.

I needed `msvcr100.dll`. Downloading and placing this file itself does not work. If anyone happens upon this, just download both versions of Microsoft Visual C++ 2010 (32 and 64 bit - but I think 32 bit did the trick?) a la [here](https://www.faqforge.com/windows/fix-the-program-cant-start-because-msvcr100-dll-is-missing-from-your-computer-error-on-windows/). Then, viola!

**Comment by zachjweiner** [comment]
Followup question: is there any way to set, say, double clicking on the pdf to trigger synctex?

**Comment by James-Yu** [comment]
There is. The problem is, `ctrl`+`lclick` is almost a 'standard' for reverse SyncTeX. There is not much incentive for this extension to 'break' the convention.

**Comment by zachjweiner** [comment]
Ok, good to know. (I'm used to double clicking in ShareLaTeX.) Yea don't change it on your end, was just wondering if there was a setting or whatnot. Thanks.

**Comment by GitHubRulesOK** [comment]
SumatraPDF & PDF file with valid .synctex(.gz) will run its inverse command to open almost ANY valid editor with tex (editor needs a  form of command line call to not open fresh instance)
