### ISSUE TITLE
Declare xltabular envs as tabulars: highlight '&' and format 

### ISSUE THREAD

**Issue by fornuftig** [James-Yu/LaTeX-Workshop#1060]
**Describe the bug**
Latex code with xltabular formatted tabulars is not formatted like tabularx tabulars are.
The table columns do not get aligned and the '&' symbols between columns are not displayed in a different color.

**To Reproduce**
Right click in the editor > Format document

Example code:

\begin{table}
	\caption{xltabular example}
	\begin{xltabular}[c]{\linewidth}{XXXX}
		\toprule
		\textbf{X}            & \textbf{Y}          & \textbf{Z}    & \textbf{ZZ} \\
		\midrule
		aa & aa & aa     & aa \\
		bb   & bb     & bb & bb \\
		cc          & cc & cc & cc \\
		\bottomrule
	\end{xltabular}
\end{table}
\begin{table}
	\caption{xltabular example}
	\begin{tabularx}{\linewidth}{XXXX}
		\toprule
		\textbf{X} & \textbf{Y} & \textbf{Z} & \textbf{ZZ} \\
		\midrule
		aa         & aa         & aa         & aa          \\
		bb         & bb         & bb         & bb          \\
		cc         & cc         & cc         & cc          \\
		\bottomrule
	\end{tabularx}
\end{table}

See above.

**Expected behavior**
See above.

**Logs**
[11:56:49] Formatting with arguments -c,/home/mark/repo/fluxtl-test/TS/systemTest/tex/,/home/mark/repo/fluxtl-test/TS/systemTest/tex/__latexindent_temp.tex,-y="defaultIndent: '  '"
[11:56:49] Formatted /home/mark/repo/fluxtl-test/TS/systemTest/tex/chapter-MockServerReference.tex

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>
console.ts:134 [Extension Host] (node:1925) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:437
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
</details>

**Screenshots**
![latex-workshop-format-document](https://user-images.githubusercontent.com/45788359/49796800-f597d180-fd3d-11e8-8b14-829da3b9ae3f.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04.1 LTS
 - VS Code version: 1.29.1
 - Extension version: 5.18.0

**Additional context**

**Comment by jlelong** [comment]
This is related to `latexindent`, not to the extension. Look up `lookForAlignDelims`  [there](https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html).

**Comment by fornuftig** [comment]
Thanks for the quick answer. 
I got the indentation to work with a latexindent yaml file.
The syntax highlighting still doesn't change the color of the '&' separator however.
From what I read, that functionality is provided by the LaTeX-Workshop plugin but I couldn't find a way to alter it.

**Comment by jlelong** [comment]
Will fix the `&` issue.

Maybe, you can post your yaml config in case it helps other.

**Comment by fornuftig** [comment]
Thanks again.
For reference, I created the following 2 files to configure latexindent.pl
~/.indentconfig.yaml [attached as indentconfig.yaml.txt]
~/.latexindent-settings/my-latexindent-settings.yaml [attached as my-latexindent-settings.yaml.txt]

[indentconfig.yaml.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2672299/indentconfig.yaml.txt)
[my-latexindent-settings.yaml.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2672300/my-latexindent-settings.yaml.txt)
