### ISSUE TITLE
Root file not found when building from sty file

### ISSUE THREAD

**Issue by DidgeriFab** [James-Yu/LaTeX-Workshop#1062]
Hi.

My root file is located in the root workspace folder (it is named `foo.tex`).
It contains an `\input{sub/bar.tex}` between `\begin{document}` and `\end{document}` and a `\usepackage{ext/baz}`.
When building from `foo.tex` or from `bar.tex` (inside `sub` subfolder), no problem! But when I build from the `baz.sty` file, I get the following messages:

> [16:11:38] BUILD command invoked.
> [16:11:38] Try root file in root directory: c:\test\foo.tex
> [16:11:38] Parsing c:\test\foo.tex
> [16:11:38] Parsing c:\test\sub\bar.tex
> [16:11:38] Cannot find LaTeX root file.

If it is the normal behaviour, would it be possible to compile the root document even from an extension file ?

Thx in advance for your help.

**Comment by jlelong** [comment]
Yes, this is the normal behavior. 
You could define the magic comment `!TEX root` on `baz.sty`, see [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#multi-file-projects)

**Comment by DidgeriFab** [comment]
Hi.

In fact, I thought about it,  but I can't use the magic comment on the package file. I gave the example above in order to show the problem but packages I actually use are not bounded to the project.

Indeed, in every project, I add my texmf directory to the workspace in order to have direct access to my own packages. The idea was to be able to compile any project's latex file even when I am working on one of the packages the file uses, without having to go back to the latex file tab, even if the latex file is not opened.

Thanks for your answer.

**Comment by jlelong** [comment]
Unfortunately we cannot do much about it.

**Comment by DidgeriFab** [comment]
I was afraid of that...
I even tried to modify the `latex-workshop.latex.tools` option with latexmk and the latex filename _hard-coded_ but still not working... Maybe I'll give a try to VS Code tasks...

Thanks again for your responses.
