### ISSUE TITLE
multiple recipes problem

### ISSUE THREAD

**Issue by zq-97** [James-Yu/LaTeX-Workshop#1064]
```json
  "latex-workshop.latex.recipes": [
    {
      "name": "compile -> copy",
      "tools": [
        "compile",
        "copypdf"
      ]
    },
    {
      "name": "compile",
      "tools": [
        "compile"
      ]
    },
  ],
  
  "latex-workshop.latex.tools": [{
      "name": "compile",
      "command": "xelatex",
      "args": [
        "-interaction=nonstopmode",
        "-synctex=-1",
        "-output-directory=./latex_output",
        "%DOC%.tex"
      ]
    },
    {
      "name": "copypdf",
      "command": "cp",
      "args": [
        "./latex_output/%DOCFILE%.pdf",
        "%DOCFILE%.pdf"
      ]
    }
  ]
```

I defined my recipes as above, as you can see, I wish to have two recipes:
- `compile` for usual usage, it only compile the latex file to pdf
- `compile -> copy` for final build, which will copy the compiled pdf to cuurent directory

However, when I click `compile` recipe for build, it also call `copypdf` tool , may I know the reason?

**Comment by jlelong** [comment]
Cannot reproduce. It works properly for me.

**Comment by oerpli** [comment]
What I think could be a problem is that (afaik) LaTeX Workshop not only has an option to build by selecting a recipe but also a `build document` where it chooses the first defined recipe. If an error occurs during build, it will rerun the build using that command which would result in `compile -> copy` in your case. 

What I would suggest is therefore to change the order of the two recipes in the settings, i.e.:

```
  "latex-workshop.latex.recipes": [
    {
      "name": "compile",
      "tools": [
        "compile"
      ]
    },{
      "name": "compile -> copy",
      "tools": [
        "compile",
        "copypdf"
      ]
   }
  ],
```
