### ISSUE TITLE
A setting for tab size

### ISSUE THREAD

**Issue by jonathan-dilorenzo** [James-Yu/LaTeX-Workshop#1066]
**Is your feature request related to a problem? Please describe.**
I prefer a certain size for my tabs (2 spaces) and get annoyed by constantly having to manually change the tabs because LaTeX-Workshop does not respect the default editor tab size.

**Describe the solution you'd like**
- The ideal solution would be a LaTeX specific setting for tab size with an option for respecting the default.
- Second best would be just a LaTeX specific setting sans the 'respect default' option. 
- Third best would be just following the default.

**Describe alternatives you've considered**
I haven't really considered alternatives. I'd love to hear them if there are good ones.

**Additional context**
That should be pretty clear without additional context I think?

**Comment by jlelong** [comment]
Actually, you can set the tab size for latex files specifically by adding to your `settings.json` file
```
"[latex]": {
   "editor.tabSize": 2
}
```
For more information on how tab size is handled in vscode, read [this thread](https://stackoverflow.com/questions/29972396/how-to-set-tab-space-style).

**Comment by inferiorhumanorgans** [comment]
@jlelong This does not work for me with v8.4.1.  If I have:

```
    "[latex]": {
        "editor.tabSize": 2
    },
```

In my settings.json I see that the tab width is initially set to '2' when I open a TeX file.  Nearly immediately after it's switched to the global setting of '4'.  If I set the global `editor.tabSize` to '2' my TeX documents are configured to use a tab width of '2'.

**Comment by jlelong** [comment]
This is not related to the extension. I bet you have `"editor.detectIndentation": true` and there the indentation is automatically detected from the file content, which is why the tab size is brought by to `4`. Can you check that?

**Comment by inferiorhumanorgans** [comment]
See above.
