### ISSUE TITLE
Syntax highlighting of quotes missing?

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1068]
In the latest release, the text within double or single (latex) quotes is not getting highlighted. I am using the `Light+ (default light)` theme and I remember seeing the quoted text getting highlighted until the latest update.
I might be wrong; but thought of mentioning in case this feature inadvertently got affected by some other fix.

**Comment by jlelong** [comment]
LaTeX uses ` ``...'' ` to delimit strings. Unfortunately ` `` ` may be used without the balancing `''` (see #1046), which completely destroys syntax highlighting. As it is not possible to only match a begin pattern if the end pattern is present, we might get stuck. Then, we have decided to stop matching quoted text as most LaTeX editors do.
