### ISSUE TITLE
PDF preview tab not horizontally centered on document and unscrollable

### ISSUE THREAD

**Issue by OlliSaarikivi** [James-Yu/LaTeX-Workshop#107]
When opening a PDF to the preview tab it is not centered on the document. In the picture below the document is opened with the Automatic Zoom setting, which causes it to be clipped from the right (the zoom does correctly position the left edge of the document). The PDF view is also not horizontally scrollable in this instance (probably because the PDF viewer is in the mode of "everything visible, nothing to scroll"), so on this zoom setting part of the document is unaccessible.

![default_zoom](https://cloud.githubusercontent.com/assets/588204/24897947/9a304f72-1ea3-11e7-81c8-4fcbaaf80067.png)

The following picture illustrates the situation with a zoom of 80%, in which case the whole document is visible, but at the cost of a significant empty are at the left.

![zoomed_out](https://cloud.githubusercontent.com/assets/588204/24897951/9d644c52-1ea3-11e7-9d95-75d6556a2e5a.png)

The window was maximized for the screenshots on a 3000x2000 screen with UI scaling in Windows set to 200%, but these issues do not seem to be window size or resolution dependent.

**Comment by James-Yu** [comment]
How is it working with browser viewer? @zachjweiner iirc you have a sp4 running at a similar resolution, can you please have a check if you also get the problem? Thanks a lot.

**Comment by James-Yu** [comment]
Just noticed your pdf viewer is zoomed in. There should be some buttons on the right of the toolbar, which is not shown.
This is an issue with vscode, the original issue is here: https://github.com/Microsoft/vscode/issues/5745
I would suggest you have a check on your browser global zooming settings. Before vscode fix the bug, nothing can be done from the extension side.

**Comment by James-Yu** [comment]
The toolbar should actually be like this:
![image](https://cloud.githubusercontent.com/assets/4210342/24901452/b6217e96-1ed9-11e7-809d-b6b49535c64b.png)

**Comment by OlliSaarikivi** [comment]
Indeed the global zoom was the issue and returning it to the original fixed this for me. Thank you very much for the help!

**Comment by James-Yu** [comment]
Glad it works for you! Actually may I know how to adjust that zooming level? I have been checking if some sort of 'dirty' hack may fix the problem before vscode officially done that, but not able to reproduce the problem 😢
