### ISSUE TITLE
Provide a MathJax Macros file for custom commands for the math preview

### ISSUE THREAD

**Issue by stakaz** [James-Yu/LaTeX-Workshop#1071]
Hello, when using MathJax for the preview of the math equations, how difficult would it be to also pass a custom macros file with something like this:

```js
MathJax.Hub.Config({
  TeX: {
    Macros: {
      RR: "{\\bf R}",
      bold: ["{\\bf #1}",1]
    }
  }
});
```

taken from http://docs.mathjax.org/en/latest/tex.html to have custom commands in the mathjax preview?

This would be a very handy feature and the only thing one really needs to implement is a custom file and an option for that in the package settings. This would also in the long run make it possible to include all newcommands from a project to the preview without the need to hover over each of them.

Thanks.

**Comment by James-Yu** [comment]
Now the extension looks for `\newcommand` and its variants in the document, and register them automatically. If you found something strange, or have a new use case that does not fit into the above, please elaborate.

**Comment by Astrantia** [comment]
@James-Yu Does that mean the hover provider resolves newcommands to their definitions? If that's the case it's not working. Write `\newcommand*{\R}{\ensuremath{\mathds{R}}}` in the start of the document and then $\R$, you will see that the Hover previews `\R`

**Comment by James-Yu** [comment]
This fix should make it work again. The bug was introduced when refactoring the hover code to support ref link. @tamuratak please take a look and confirm the change does not break what you implemented.

**Comment by Astrantia** [comment]
@James-Yu I can confirm your fix worked.

**Comment by tamuratak** [comment]
I confirm too.

**Comment by Astrantia** [comment]
@tamuratak @James-Yu @jlelong Happy new year guys and thank you for your fantastic work on this extension

**Comment by stakaz** [comment]
So basically this does not work if you use `\input` for a file and the new commands are stored there...

Probably the best way would really to allow for a custom MathJax settings file where anyone could store all the commands...

**Comment by jrs65** [comment]
@stakaz did you ever figure a way around this one? I'm in a similar boat to you, I keep all my custom math definitions in a separate file and then `\input{mathdef}` them.
