### ISSUE TITLE
External pdf viewer default command is wrong for linux/macos

### ISSUE THREAD

**Issue by L0g4n** [James-Yu/LaTeX-Workshop#1077]
**Describe the bug**
Trying to open the PDF with an external viewer on linux/macos does not open it.
**To Reproduce**
Click the "Open PDF" button in the editor with the tex file opened.
**Expected behavior**
The pdf is opened in the user's preferred PDF viewer.
**Additional context**
I do not provide logs since I think I know what the problem is. The specified command for opening the file in the external pdf viewer tries to open a specific windows PDF viewer with the file.
To fix this on linux and macos you have to overwrite this command:
`"latex-workshop.view.pdf.external.command": {  
        "command": "xdg-open", // for macOS you have to use open  
        "args": [  
            "%PDF%"  
        ]  
    }`  
So you could change the default setting for the command in the source code to "xdg-open" on linux or "open" on macOS respectively.

**Comment by L0g4n** [comment]
I offer to fix that myself, but since I am not a JS/TS guy and not  familar with writing VSCode extensions I did not know where to look.

**Comment by jlelong** [comment]
The variable `latex-workshop.view.pdf.external.command` is defined in [package.json](https://github.com/James-Yu/LaTeX-Workshop/blob/master/package.json#L654), but unfortunately I do not think you can have the default value depend on the OS. 

I guess the best we can do is to test if `latex-workshop.view.pdf.external.command` is non empty in [viewer.ts](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/viewer.ts#L140) and then tweak the command depending on the os.

**Comment by L0g4n** [comment]
@jlelong if that is the case you can ignore my PR #1078. I thought since you can use those labels for OS specific tasks you could use them in package.json.

**Comment by L0g4n** [comment]
@jlelong The thing is, how do other VSCode extensions realize OS specific default commands?

**Comment by jlelong** [comment]
Do you have an example of such an extension?

**Comment by L0g4n** [comment]
https://github.com/Microsoft/vscode-python/blob/master/package.json
