### ISSUE TITLE
Citation browser/intellisense

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#108]
A couple of questions/comments about the citation related stuff:

1) Is the citation browser supposed to be fixed to be searchable only by title?

2) Author search in intellisense seems to have an issue recognizing anything other than the first author name in the list for lists such as "Smith, John and Jones, Tom," i.e. it will only recognize "smith" but not "john" or "jones" or "tom."

3) Is it possible for the intellisense and/or citation browser to search all fields, or at least title and author? I.e. I may remember a reference's title, but not authors, or vice-versa.

Thanks!

**Comment by James-Yu** [comment]
1. Yes, and that is limited by how quick menu of vscode works.
2. I cannot reproduce the problem. I searched my name and the non-first authored papers appear in the intellisense. I use `title` in the settings.
3. Intellisense natively supports searching with both title and author names.

**Comment by zachjweiner** [comment]
For 2), How is your author list formatted? A single "string," as I have?

For 3) Ah, yes, correct, I wasn't looking closely enough. Great!

**Comment by James-Yu** [comment]
This is **random** snippet from my `bib`:
```
@article{ye_multi-objective_2015,
  title = {Multi-{{Objective Optimal Power Flow Considering Transient Stability Based}} on {{Parallel NSGA}}-{{II}}},
  volume = {30},
  number = {2},
  journal = {IEEE Trans. Power Syst.},
  author = {Ye, Cheng-Jin and Huang, Min-Xiang},
  month = mar,
  year = {2015},
  pages = {857--866}
}
```
And you can see
![image](https://cloud.githubusercontent.com/assets/4210342/24941083/42b6bf6a-1f7a-11e7-8d26-a25cd05e9a34.png)

**Comment by jabooth** [comment]
@zachjweiner if you could share a bibtex entry that you know isn't working along with the search term you were trying to complete that wound be great!

**Comment by zachjweiner** [comment]
@jabooth, I think @James-Yu's example will work - I cannot replicate the behavior he demonstrated. I put his entry in my `bib` and attempted to `\cite{min}` or `\cite{Huang}`, etc., and the reference didn't appear.

I assume this is entirely independent of what compiler one uses for bibliographies? Could it be some setting within VSC, rather than the extension?

**Comment by James-Yu** [comment]
I have no idea on why your extension won't provide the item. Can you please share a part of your bibtex file that won't work?

**Comment by zachjweiner** [comment]
@James-Yu I could, but I was saying that the example you include does not work for me in the exact same way. But, as another example:

`@article{Kogut:1974ag,
      author         = "Kogut, John B. and Susskind, Leonard",
      title          = "{Hamiltonian Formulation of Wilson's Lattice Gauge
                        Theories}",
      journal        = "Phys. Rev.",
      volume         = "D11",
      year           = "1975",
      pages          = "395-408",
      doi            = "10.1103/PhysRevD.11.395",
      reportNumber   = "Print-74-1186 (CORNELL)",
      SLACcitation   = "%%CITATION = PHRVA,D11,395;%%"
}`

Trying to `\cite{suss}` doesn't work.

**Comment by James-Yu** [comment]
Can you please give a screenshot on the info displayed for this entry after typing `kogut` and press ctrl+space?

In addition, the 'correct' way of using bibtex is to use brackets instead of double quotes. I am pretty sure the quotes in your example will cause trouble.

**Comment by James-Yu** [comment]
This is mine
![image](https://cloud.githubusercontent.com/assets/4210342/24988813/f1fbc57c-203a-11e7-91ad-16f56ae6bd7b.png)
You can see the authors are not parsed due to those quotes.

**Comment by zachjweiner** [comment]
![image](https://cloud.githubusercontent.com/assets/19390728/24988862/4cbbf30a-1fce-11e7-8d2d-a842263d2179.png)

Right about the brackets vs. quotes... I just never write this myself, I pull all citations from the inspireHEP database automatically.

**Comment by James-Yu** [comment]
Here is a reference on the 'standard' `bibtex`: [link](https://www.economics.utoronto.ca/osborne/latex/BIBTEX.HTM).
There are also many, and it is really hard to adapt to double quotes while does not influence the bracket people.

**Comment by zachjweiner** [comment]
Yes, I'm now seeing that that is the issue. Of course i'm not gonna ask you to adapt for that :) I'll do some find and replacing. Thanks for ironing that out for me.

**Comment by jabooth** [comment]
Hmm actually I think quotes as outer delimiters are perfectly valid, so many users will have them:

http://tex.stackexchange.com/a/109070

As with what you were saying @zachjweiner, people will have automated systems for generating bibtex entires so it's not so easy to promote 'good' style even if the consensus is {} > "".

Maybe it's worth figuring out if we can support both?

**Comment by James-Yu** [comment]
Did not know it is also valid. Will check how to adapt to this format.

**Comment by James-Yu** [comment]
Will publish to marketplace, @zachjweiner please have a test.

**Comment by zachjweiner** [comment]
Looks perfect. Thanks so much for taking the time to do this!
