### ISSUE TITLE
mathjax preview 

### ISSUE THREAD

**Issue by franklinsu** [James-Yu/LaTeX-Workshop#1080]
why my workshop cant causes a mathjax preview to pop up.

**Comment by franklinsu** [comment]
![image](https://user-images.githubusercontent.com/37546448/50374824-15c56b80-062f-11e9-8ba9-919f56451ac2.png)

**Comment by franklinsu** [comment]
![image](https://user-images.githubusercontent.com/37546448/50374957-cd0eb200-0630-11e9-9f81-5c8d931fbd3f.png)
![sz5f aa_wf_s k0__veox](https://user-images.githubusercontent.com/37546448/50374961-f16a8e80-0630-11e9-814e-4e29e099dcb2.png)

my versions of VSCode, LaTeX workshop

**Comment by tamuratak** [comment]
The reason is that your username includes Chinese characters. Please change it.

**Comment by franklinsu** [comment]
ok thank you very much.
