### ISSUE TITLE
Breaks markdown files when "latex" string is present

### ISSUE THREAD

**Issue by poteat** [James-Yu/LaTeX-Workshop#1082]
**Describe the bug**
When this extension is enabled, and you have a markdown file open with embedded javascript, the javascript code ceases to render correctly after the word "latex" appears.  How did I find this bug...? Long story.

This still occurs when LaTeX Workshop is the only enabled extension.

**To Reproduce**
1. Open the attached [foob.md](https://github.com/James-Yu/LaTeX-Workshop/files/2705710/foob.zip) file in Visual Studio Code with extension enabled.
2. You will need to extract from .zip because I cannot upload .md files
3. See that the coloring is broken.

**Expected behavior**
Markdown files should not be affected by the presence of this extension.

**Logs**
There are none.

**Screenshots**
With extension:
![image](https://user-images.githubusercontent.com/7668446/50380386-c3d31480-0633-11e9-8db1-e4e6257e38f2.png)

Without extension:
![image](https://user-images.githubusercontent.com/7668446/50380375-81a9d300-0633-11e9-83c4-b9eb64c61556.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.30.1
 - Extension version: 5.19.0

**Additional Notes**
Thanks for developing LaTeX workshop.  This isn't a critical issue (for me at least), but I thought you guys might appreciate knowing about this regardless.  You are a good person for working on open-source.

**Comment by jlelong** [comment]
I was and thanks for reporting this tricky issue.
I fixed this in 0164f0c.
