### ISSUE TITLE
Unimath symbol have disappeared 

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1087]
**Describe the bug**
I do not have the uni-math symbol as I used to:
![image](https://user-images.githubusercontent.com/15056323/50489139-598cec00-0a06-11e9-97f2-a3b130c29ae8.png)

I noticed this option that seems related to the feature:
![image](https://user-images.githubusercontent.com/15056323/50489166-79bcab00-0a06-11e9-9ed8-7b5517a11b5d.png)
but with ou without it, it does not change anything

**To Reproduce**
Tape any math symbol in latex

**Expected behavior**
I am expecting something like #84

**Comment by PierreMarchand20** [comment]
I am on macOS 10.14.2, but I tried on the computer of a friend I have converted to VScode and who is using Ubuntu 16.04, it is the same problem.

**Comment by jlelong** [comment]
Actually they have not disappeared provided that `latex-workshop.intellisense.unimathsymbols.enabled` is set to `true`. The only real change is that intellisense sort is now case sensitive (this is related to package completion, see PR #992). Type `\Bbb` and you should see the completions from uni-maths. Only part of the description has been accidentally removed but I will fix.

**Comment by PierreMarchand20** [comment]
I am suppose to see something in this example ? 
![image](https://user-images.githubusercontent.com/15056323/50518736-72a1a580-0ab7-11e9-8013-9755565df98a.png)

**Comment by PierreMarchand20** [comment]
mmmm ok I think I misunderstood something, what I am missing is the little picture showing a small preview of the symbol. It is what I called (wrongly ?) unimath symbol, I am not looking for having all the command like `\Bbb` in the dropdown selector.
