### ISSUE TITLE
Autobuild with Latex subfiles package only builds subfile

### ISSUE THREAD

**Issue by L0GL0G** [James-Yu/LaTeX-Workshop#1088]
If you have the latex subfiles package included, you get asked when building the project, which root file you want to use (the current or the subfile main one), but you cannot choose in an recipe for autobuild

1. Have a file "main.tex" with `\usepackage{subfiles}`
2. Have a file "sub.tex" with `\documentclass[main.tex]{subfiles}`
3. Change the user settings to 
`"latex-workshop.latex.recipes": [
        {
            "name": "pdflatex",
            "tools": [
                "pdflatex"
            ]
        },
        {
            "name": "latexmk",
            "tools": [
                "latexmk"
            ]
        },
        {
            "name": "pdflatex -> bibtex -> pdflatex*2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        }
    ],`
4. Have Build-on-save enabled
5. Save sub.tex
6. sub.tex gets compiled

What should have happened: 
- main.tex gets compiled

Logs are unrelated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.30.1
 - Extension version: 5.19.0

**Comment by jlelong** [comment]
This is the intended behavior for the `subfiles` package. From the package documentation

> LATEXing either the main or the subordinate file produces the following results:
> • If the subfile is typeset by itself, it takes as preamble the one of the main file (including its \documentclass). The rest is typeset normally.
> • If the subordinated file was \subfile’d, it ignores everything before and including \begin{document}, and then ignores \end{document} too. (The body of the file, nothing else, is effectively \input.)

If you always want to run `latex` on the main file, just remove `\documentclass[main.tex]{subfiles}` from the subfile
