### ISSUE TITLE
Mouse cursor changes to a mouse arrow with a plus at the top right

### ISSUE THREAD

**Issue by DFelten** [James-Yu/LaTeX-Workshop#109]
I'm not sure if this is a problem of LaTeX-Workshop, but it appears in the moment only on LaTeX files. When writing, the mouse cursor changes permanently. Instead of a simple cursor, the cursor changes to the mouse arrow with a plus at the top right. 

I'm not sure why this happens and not how I change the cursor again. Only after closing Visual Studio Code the cursor is normal again. But it changes again after a while (through certain actions?).

![arrow-plus](https://cloud.githubusercontent.com/assets/1169185/24954859/56d71c40-1f81-11e7-8d9a-1337a8cc24db.jpg)

**Comment by James-Yu** [comment]
No we do not control the cursor, nor does vscode allow us to. In addition, we did not receive any similar issues like this, so I suppose this might be a local problem. Sorry I totally have no idea what is going on with the cursor.

**Comment by DFelten** [comment]
Ok, thanks for the answer. I thought this could be an extension problem because I read [here](http://stackoverflow.com/questions/33886941/changing-the-cursor-appearance-in-visual-studio-code-via-extension-api) that it's possible to change the cursor.

**Comment by DFelten** [comment]
It's a general problem of Visual Studio Code: https://github.com/Microsoft/vscode/issues/24602
