### ISSUE TITLE
PDF view in latex-workshop doesn't run successfully

### ISSUE THREAD

**Issue by mxd2816** [James-Yu/LaTeX-Workshop#1091]
When i use latex in vs code, it shows that the XeLaTeX is successfully done but the generated pdf file can not be viewed by latex-workshop preview. However, when I open the generated pdf by Adobe Reader, it can be viewed successfully. 
![image](https://user-images.githubusercontent.com/44053571/50544657-b7a11580-0c38-11e9-9735-86584ec3a89c.png)
![image](https://user-images.githubusercontent.com/44053571/50544663-dd2e1f00-0c38-11e9-8e29-df405a8551df.png)
![image](https://user-images.githubusercontent.com/44053571/50544664-ef0fc200-0c38-11e9-90d1-3da5271f3c46.png)

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is not helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by mxd2816** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Takashi:
           Thanks for contacting me. I am sorry for not telling your that my operating system is windows 10 (1803) rather than Mac Os. And my vs code version is 1.30-2018, LaTeX workshop version is v.5.19.0, and I am using TextLive 2018.   Also, thanks for give me these tips. But after I finished these steps, there is still a blank PDF in Vs code tab, and here is my log:and here are my extensions:I have Reinstall Vs Code for several times, but is doesn't work for me. But the XeLaTeX shows that the PDF has be built successfully like this. So I don't know what happened. Looking forward to hearing from you. Thanks a again for contact me and happy New Year!
    
        
            
        
    
    
        
        

        
    

    On 12/30/2018 20:19，Takashi Tamura<notifications@github.com> wrote： 


Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word latest is not helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.

1 Please change the theme of VSCode to the default one, and check that you still see this issue.
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.
Then please do the followings.

Open the command palette.
Enter Developer: Toggle Developer Tools and press enter.
Show us messages in the console.




Thank you for your cooperation.

**Comment by tamuratak** [comment]
I cannot read your log messages. Plese post your message via github.com, not via e-mail.

**Comment by mxd2816** [comment]
> Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is not helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.
> 
> ![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)
> 
> 1 Please change the theme of VSCode to the default one, and check that you still see this issue.
> 2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.
> 3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.
> 
> Then please do the followings.
> 
> 1. Open the command palette.
> 2. Enter `Developer: Toggle Developer Tools` and press enter.
> 3. Show us messages in the console.
> 
> ![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)
> 
> ![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)
> 
> ![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)
> 
> Thank you for your cooperation.



> I cannot read your log messages. Plese post your message via github.com, not via e-mail.

**Comment by mxd2816** [comment]
> I cannot read your log messages. Plese post your message via github.com, not via e-mail.
Dear Takashi:
   Thanks for contacting me. I am sorry for not telling your that my operating system is windows 10 (1803) rather than Mac Os. And my vs code version is 1.30-2018, LaTeX workshop version is v.5.19.0, and I am using TextLive 2018.
   Also, thanks for give me these tips. But after I finished these steps, there is still a blank PDF in Vs code tab, and here is my log:
![image](https://user-images.githubusercontent.com/44053571/50553286-394b7e80-0cdf-11e9-91b2-62b3546dde04.png)
![image](https://user-images.githubusercontent.com/44053571/50553288-3fd9f600-0cdf-11e9-9b7b-2d3e27621d33.png)
and here are my extensions:
![image](https://user-images.githubusercontent.com/44053571/50553295-4b2d2180-0cdf-11e9-8a99-d745178bf5ad.png)
![image](https://user-images.githubusercontent.com/44053571/50553296-4ff1d580-0cdf-11e9-93f7-7aab70fdfe88.png)
I have Reinstall Vs Code for several times, but is doesn't work for me. But the XeLaTeX shows that the PDF has be built successfully like this. So I don't know what happened. 
Looking forward to hearing from you. Thanks a again for contact me and happy New Year!
![image](https://user-images.githubusercontent.com/44053571/50553313-5ed88800-0cdf-11e9-9dd8-f2d4bbebbda7.png)
![image](https://user-images.githubusercontent.com/44053571/50553315-61d37880-0cdf-11e9-99e8-fcd744da3e01.png)

**Comment by mxd2816** [comment]
> I cannot read your log messages. Plese post your message via github.com, not via e-mail.
Excuse me. dear Takashi, this morning I ran my vs code again and the latex-workshop extension log shows:
[09:31:11] Initializing LaTeX Workshop.
[09:31:11] Creating LaTeX Workshop http and websocket server.
[09:31:11] LaTeX Workshop initialized.
[09:31:11] Found root file from active editor: c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:31:11] Root file changed from: undefined. Find all dependencies.
[09:31:11] Instatiating new file watcher for c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:31:11] Parsing c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:31:11] Server created on 127.0.0.1:1792
[09:31:11] LaTeX Workshop version: 5.19.0
[09:31:11] Snippet data loaded.
[09:35:48] ACTIONS command invoked.
[09:35:49] RECIPES command invoked.
[09:35:50] BUILD command invoked.
[09:35:50] Found root file from active editor: c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:35:50] Root file remains unchanged from: c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex.
[09:35:50] Building root file: c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:35:50] Build root file c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:35:50] Found TeX program by magic comment: xelatex
[09:35:50] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,c:/Users/Wu Tianhao/Desktop/Latex/testmylaytex
[09:35:51] LaTeX log parsed with 0 messages.
[09:35:51] Recipe of length 1 finished.
[09:35:51] Successfully built c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:35:51] No PDF viewer connected for c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.pdf
[09:35:56] VIEW command invoked.
[09:35:56] Found root file from active editor: c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex
[09:35:56] Root file remains unchanged from: c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.tex.
[09:35:56] No PDF viewer connected for c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.pdf
[09:35:56] Serving PDF file at http://127.0.0.1:1792/viewer.html?file=/pdf:c%25253A%25255CUsers%25255CWu%252520Tianhao%25255CDesktop%25255CLatex%25255Ctestmylaytex.pdf
[09:35:56] Open PDF tab for c:\Users\Wu Tianhao\Desktop\Latex\testmylaytex.pdf
[09:35:59] LOG command invoked.
---------------
And the Latex compiler log shows:
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(c:/Users/Wu Tianhao/Desktop/Latex/testmylaytex.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 8 language(s) loaded.
(d:/TexLive 2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(d:/TexLive 2018/texmf-dist/tex/latex/base/size10.clo)) (./testmylaytex.aux) [1] (./testmylaytex.aux) )
Output written on testmylaytex.pdf (1 page).
SyncTeX written on testmylaytex.synctex.gz.

Transcript written on testmylaytex.log.
 Thanks for helping me!

**Comment by mxd2816** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Sorry for my mistake, I have replied to your email in Github~
    
    
        
        

        
    

    On 12/30/2018 21:57，Takashi Tamura<notifications@github.com> wrote： 


I cannot read your log messages. Plese post your message via github.com, not via e-mail.

**Comment by tamuratak** [comment]
It seems that LaTeX Workshop works fine. The cause may be the firewall on your PC. Please check the settings of your PC.

**Comment by tamuratak** [comment]
PLEASE DO the followings. You have not.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

It seems that LaTeX Workshop works fine. The cause may be the firewall on your PC. Please check the settings of your PC.

**Comment by mxd2816** [comment]
![image](https://user-images.githubusercontent.com/44053571/50557350-6586ef80-0d1f-11e9-959b-36398324135a.png)

**Comment by mxd2816** [comment]
Sorry....It is my first time to use Github and vs code....Please forgive me for my ignorance....
![image](https://user-images.githubusercontent.com/44053571/50557595-ada71180-0d21-11e9-8a90-c7112b8fe2cc.png)
![image](https://user-images.githubusercontent.com/44053571/50557599-b861a680-0d21-11e9-83de-51d975917301.png)

**Comment by tamuratak** [comment]
The line, `ERR Cannot find module 'toush-cookie'`, says that a file included in LaTeX Workshop is not found. It seems that your installation of the extension is incomplete. Please remove `C:\Users\Wu Tianhao\.vscode\extensions\james-yu.latex-workshop-5.19.0`, then reinstall the extension, not VS Code. 

The `tough-cookie` module must be in `C:\Users\Wu Tianhao\.vscode\extensions\james-yu.latex-workshop-5.19.0\node_modules\tough-cookie`

**Comment by tamuratak** [comment]
I have no idea. I cannot help you, sorry.

**Comment by mxd2816** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Oh, thanks a lot, you have already helped me so much! I will try again later! Here In my country, it's only 4 hours left for the last 2018, so Happy New Year for you! and have a nice day! Thanks for helping me so much :)
        
    
        
            
        
    
    
        
        

        
    

    On 12/31/2018 19:03，Takashi Tamura<notifications@github.com> wrote： 


I have no idea. I cannot help you, sorry.

**Comment by mxd2816** [comment]
Oh, How surprising it is! Your suggestion works!
The reasons why the Latex-workshop works is due to the update progress. I installed the Latex-workshop 5.18.0 and somehow it is automatically updated to 5.19.0 so I get two version of this type of extensions like this.
![image](https://user-images.githubusercontent.com/44053571/50560721-9296ca80-0d3e-11e9-8fa6-25eb886e8baa.png)
No wander how I try to reinstall the extension it doesn't works. But after remove the two, I reinstall it and the PDF can be shown successfully. which ascribed to your suggestion. 
Thanks very very much! 👍 
![image](https://user-images.githubusercontent.com/44053571/50560759-eef9ea00-0d3e-11e9-9278-f938c9f346cf.png)
