### ISSUE TITLE
Preview for "because" ?!

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1092]
**Describe the bug**
Saw a strange bug (or feature?) - when the mouse is hovered over `because` word, the preview pops up. See the below gif.

![because preview](https://user-images.githubusercontent.com/24664855/50544797-1a89b100-0c27-11e9-98c8-79b6a4ad2fec.gif)

As can be seen, only when `because` text is present somewhere in the middle of the sentence (line no. 9) the preview pops up. In other places, (like line no. 7 & 11), there is no preview.

**Desktop (please complete the following information):**
 - OS: Linux
 - VS Code version: 1.30.1
 - Extension version: 5.19.0

**Comment by Astrantia** [comment]
@werunom are you sure its not because of …next to it?
