### ISSUE TITLE
Feature request: No clearance of compiler log before recipe is finished

### ISSUE THREAD

**Issue by bananadium** [James-Yu/LaTeX-Workshop#1096]
**Is your feature request related to a problem? Please describe.**
when using recipe with N "tool"s, compiler log is cleared N-1 times.
so I cannot check compiler log except last one

**Describe alternatives you've considered**
compiler log should be cleared only once ~~after all "tool"s are executed~~ right before the next recipe is started

**Comment by jlelong** [comment]
This is not so clear. For instance, if the recipe consists in calling `pdflatex` twice, we actually do not care about the log of the first call to `pdflatex`.
I guess a configuration variable for this would be welcome. On it.

**Comment by bananadium** [comment]
Thanks for your reply. I use a recipe like "uplatex * 2 + dvipdfmx" for two reason. First, pdflatex, which does not deal with non-ascii letters well, is not popular in my country. Second, scripts (latexmk and ptex2pdf) are also not good at non-ascii because they are written in perl and lua, respectively.
> I guess a configuration variable for this would be welcome. On it.
Do you maen "I'm working on it" ?

**Comment by jlelong** [comment]
> Do you mean "I'm working on it" ?

Yes, I will do it by the end of the day.

**Comment by bananadium** [comment]
>Yes, I will do it by the end of the day.

Thank you so much!

**Comment by jlelong** [comment]
The default is to clear the compiler logs before invoking every tool of
a recipe. If you wish to keep the logs from all the tools, set

    latex-workshop.latex.build.clearLog.everyRecipeStep.enabled

to true.
