### ISSUE TITLE
[Feature Query] Rich text mode with webview?

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1097]
I'll keep this short and sweet.

Would it be possible to create a 'rich text' mode using VS Code's support of webviews? I'm thinking something along the lines of what overleaf has implemented.

Considering learning the VS Code Extension API,

tecosaur.

**Comment by Astrantia** [comment]
@tecosaur What do you mean exactly?

**Comment by James-Yu** [comment]
Unfortunately, it is not possible without huge effort, almost equivalent to creating a new javascript-based text editor. It is far beyond replacing characters with others. I'll close this for now until substantial work has been developed by other communities.

**Comment by tecosaur** [comment]
@Astrantia Well, with the `visual text substitution` (or similar name) extension I can make it so that many replacements are made that make it easier to read the LaTeX and see what's going on at a glance, however it's slow, buggy, missing a few important features, and there are some parts of the VS Code that can not be changed (such as font size and inline image/math previews). 

I was hoping that using the webview it may be possible to produce a 'rich text' version of this document as it were and have it so that edits are sent back to the editor.

As a demo here's a (outdated) small example of how I use visual substitutions to make things easier to read. I also have substitutions for:

- common super/sub scripts
- lists
- references
- getting rid of all curly braces with exceptions
- and more

But I don't have recent screenshot, or my computer, on hand.

![image](https://user-images.githubusercontent.com/20903656/50729776-5ea11800-1137-11e9-96e3-c3f080ecbcd1.png)
