### ISSUE TITLE
can only build when editor is active for main.tex

### ISSUE THREAD

**Issue by gutouyu** [James-Yu/LaTeX-Workshop#1098]
# Description
I have c2.tex and main.tex file.  And in main.tex , there is `\inlcude\c2.tex` . Autobuild on save enable. 
When I change main.tex, everything is fine, I get the update. 
But when I change c2.tex and save file, it fails to compile.  I have to change to file main.tex and the build will run successfully.

# Problem
When I change c2.tex, I  must change to main.tex to build.

# Should
Is there anyway, I can chang c2.tex, save file and wait for the autobuild? Without change to main.tex file.

# Environment
* mac
* latexworkshop [5.19.0] - 2018-12-21

**Comment by jlelong** [comment]
I cannot reproduce the issue. Do you confirm you use `\include{c2.tex}` (the curly braces are needed)?
If yes, please provide the logs from the extension.

**Comment by gutouyu** [comment]
It'k ok. I found the problem.
In c2.tex I use documentclass{standalone} and it cause latexworkshop regard it as a root file. Just remove it, then it works.
