### ISSUE TITLE
Mention TeX Live because of Synctex

### ISSUE THREAD

**Issue by christianmalek** [James-Yu/LaTeX-Workshop#11]
Hi,

This is no problem at all. But I think it would be a good idea to mention that *TeX Live* is necessary because of the Synctex binary.

**Comment by James-Yu** [comment]
Thanks for the suggestion. Though I do not want to reject the usage of other distributions, e.g. MikTeX. For such distros, only synctex related features are disabled. The compiling and previewing should still work fine.

I will add a line in the readme about missing synctex in MikTeX.
