### ISSUE TITLE
How to use ChkTex in LaTex Workshop?

### ISSUE THREAD

**Issue by xiaoFine** [James-Yu/LaTeX-Workshop#110]
Hi, I just rephrase my problem. I want to implement the "Linting with ChkTex" as shown in Features.

I have a simple demo with a obvious error( missing 'd') :
( I have to paste the link cause the image-upload is down)
[error](http://i1.piimg.com/567571/bc21314468df4bb3.png)

with Problem Pane showing the log as
[log](http://i1.piimg.com/567571/d4f32df8177ee416.png)

the entire log is 
[en-log](http://i1.piimg.com/567571/d36e401dec1f0f05.png)

I can build the .pdf if I correct it.
My configuration is :（Windows)

```
{
    "latex-workshop.latex.toolchain": [
        {
            "command": "texify",
            "args": [
                "--synctex",
                "--pdf",
                "%DOC%.tex"
            ]
        }
    ],
    "latex-workshop.chktex.enabled": true,
    "latex-workshop.chktex.path": "C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\chktex",
    "latex-workshop.synctex.path": "C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\synctex",

    
    "latex-workshop.chktex.args.active": [
        "-wall",
        "-n22",
        "-n30",
        "-e16",
        "-q"
    ]
}
```

**Comment by zachjweiner** [comment]
I actually am having the exact same problem, with an identical setup - Windows, MikTeX, same `chktex.path` and even `synctex.path`. And synctex works for me. But no linting, same error as you.

**Comment by James-Yu** [comment]
You can try add the path to your system PATH first, and see what's going on.

Also, as I have suggested, I cannot see the problem with the log, as no error message was given by `chktex`. I highly recommend you try the same command from `cmd` and see what's the error message. From the log it seems that the extension is working correctly, and `chktex` is throwing error.

**Comment by jabooth** [comment]
The full LaTeX workshop log is really required to debug this - see https://github.com/James-Yu/LaTeX-Workshop/issues/69#issuecomment-293525823 for details on how to see it.

If you can paste us a complete log we can figure this out.

**Comment by James-Yu** [comment]
@jabooth This might be a miktex-related problem. I'll find a computer with that and do some research tomorrow.

**Comment by jabooth** [comment]
@James-Yu this is exactly the kind of issue I think we can avoid with this:

https://github.com/latexjs/latexjs

More info on the README now. Will have a working beta soon to test, current works for Mac and Linux!

**Comment by James-Yu** [comment]
Got it.

The chktex shipped with MikTeX **sometimes** returns error code `1` but with complete and correct `stdout`. Weird.

Have no idea how to handle this difference. It seems not possible to tell if the executable is from MikTeX or TeXLive.

I hate MikTeX.

**Comment by jabooth** [comment]
Sweet. :|

Euuurghh that's really gross to start adding edge cases for...

@James-Yu did you find a link with this info online or just tried it yourself?

**Comment by James-Yu** [comment]
@jabooth By myself, it seems not recorded elsewhere. I will check the source code of chktex tmr and make sure error code 1 is harmless or not. \meh\

**Comment by zachjweiner** [comment]
Yea, I wanted to run `chktex` from `cmd`, since that was how I figured out how to get `synctex` to work, but I wasn't sure how to do so - I'd be happy to try if someone could point this noob in the right direction :)

Sorry MikTeX is causing headaches, but I hope I can help iron issues out!

**Comment by xiaoFine** [comment]
@James-Yu @jabooth ChkTex works in cmd
[cmd log](http://i2.muimg.com/567571/7b978e0fbd83b051.png)

```
\documentclass[UTF8]{ctexart}
  %blabla
\title{hello world}
\author{xiaoFine}
\date{\today}

\begin{document}
\tableofcontents
\maketitle

\begin{equation}
x=\sum{a_i^i}
\en{equation}

\end{document}

```

**Comment by James-Yu** [comment]
A dirty hack to solve the problem. Will re-open on any problem.

**Comment by xiaoFine** [comment]
@James-Yu Great && Thanks!
And... one more silly question --how can I apply this update or I just wait for the next version? 
Cause when I clone the repository to `\.vscode\extensions`, the .tex file has highlight but in the OUTPUT I have [nothing ](http://i2.muimg.com/567571/3a954b665e5f76f1.png), and a update( to 2.1.1) tip as well

**Comment by zachjweiner** [comment]
@xiaoFine it takes a little tome for the update to be pushed to the marketplace, I think. I just performed the updated via VSC and `chktex` is working!

**Comment by xiaoFine** [comment]
@zachjweiner Could you please teach me how to update the extension via VSCode? cause I don't know what to do with this linter.ts
