### ISSUE TITLE
Unable to view PDF

### ISSUE THREAD

**Issue by SeakyLuo** [James-Yu/LaTeX-Workshop#1104]
**Describe the bug**
Unable to view the pdf of latex under any circumstances.

**To Reproduce**
3. See error

**Expected behavior**
I clicked "view LaTeX pdf" -> "view in vs code tab" and get a pdf of latex in vs code.

**Logs**
Please paste the log messages here. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/25042708/50882423-99a28600-1399-11e9-956c-6f173f4966e4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.20.0]
 - Extension version: [e.g. 5.0.0]

**Additional context**

**Comment by James-Yu** [comment]
See the last line. The extension cannot find the pdf file. Is there any problem with the PDF?

**Comment by SeakyLuo** [comment]
Should I do anything to generate a pdf file?
What I did is that I simply installed the extension with a latex file open. And then I started trying to view the pdf of that file.

**Comment by James-Yu** [comment]
Yes. Try build your latex project to generate the PDF first. This can be done by finding the build command or using the sidebar icon and locate `build`.

**Comment by SeakyLuo** [comment]
So I should click Build LaTex Project -> latexmk, right?
![image](https://user-images.githubusercontent.com/25042708/50882933-4e897280-139b-11e9-9d15-dd0bd45be6ba.png)
Is this done? These 4 lines are generated very fast but it doesn't seem to generate a pdf file. And the indicator on the left corner seems to rotate forever.

**Comment by James-Yu** [comment]
If this is shown when the indicator rotates, something unexpected happened. If so, please share your project or at least a minimal working example, along with your `settings.json` of vscode.

**Comment by SeakyLuo** [comment]
[folder.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2739781/folder.zip)

**Comment by James-Yu** [comment]
The compilation works correctly on my PC. In your settings, the viewer is set to `external`, without telling the extension which external program to call. You may want to check [this link](https://github.com/James-Yu/LaTeX-Workshop/wiki/View).

**Comment by SeakyLuo** [comment]
I have tried to "tab", "browser" and "none". The indicator still rotates forever.
![image](https://user-images.githubusercontent.com/25042708/50884580-1c2e4400-13a0-11e9-9bac-71fff234d65a.png)

**Comment by James-Yu** [comment]
Sorry but I cannot reproduce the rotator issue. Need other's help.

**Comment by SeakyLuo** [comment]
<img width="871" alt="2019-01-08 23 55 21" src="https://user-images.githubusercontent.com/25042708/50884914-14bb6a80-13a1-11e9-8eca-33cfa48d1469.png">
This is what I got from my Mac when I tried to build.

**Comment by SeakyLuo** [comment]
Sorry for not reading the installation instruction first.
![image](https://user-images.githubusercontent.com/25042708/50885173-d7a3a800-13a1-11e9-9139-dbbfb38cda58.png)
I notice that I don't have LaTeX distribution installed. Would this be the main problem?

**Comment by James-Yu** [comment]
Definitely. A TeX toolset is required to generate the pdf.

**Comment by SeakyLuo** [comment]
Thank you so much! I got it working.
