### ISSUE TITLE
Trying to figure out direct and reverse SyncTeX

### ISSUE THREAD

**Issue by financialphysician** [James-Yu/LaTeX-Workshop#1105]
Disclaimer: I'm new to this so please forgive me for being quite incompetent haha.

I'm trying to figure out how to work the SyncTex feature and am struggling. I thought command-L alt-B would ping where text I highlight appears on my document but it says the command wasn't found. 

I'd also like to be able to see from he pdf back to my code.

It also looks like I'm not able to see the output on the fly. I've just been using TexMaker before this.

![screen shot 2019-01-09 at 10 29 13 am](https://user-images.githubusercontent.com/46356881/50917065-e6b64480-13f9-11e9-9d19-2c749036efa2.png)

**Comment by jlelong** [comment]
The documentation on synctex: [https://github.com/James-Yu/LaTeX-Workshop/wiki/View#synctex](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#synctex). See also the [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-use-ctrlalt-in-a-shortcut). The alternative shortcut is `Cmd+L alt+j`.

**Comment by financialphysician** [comment]
Yeah I saw that and when I try doing that it just says "The key combination Cmd+L alt+j is not a command." (the bottom of screenshot in original post)

**Comment by jlelong** [comment]
Your screenshot mentions `cmd+L alt+v`. 

The default shortcut for synctex is `cmd+alt+j`. As explained in the [FAQ](latex-workshop.bind.altKeymap.enabled), the alternative shortcut `cmd+l alt+j` is only defined when `latex-workshop.bind.altKeymap.enabled` is set to `true`.

**Comment by financialphysician** [comment]
It's working! Thank you so much!
