### ISSUE TITLE
Preview when typing math

### ISSUE THREAD

**Issue by littlecatheart** [James-Yu/LaTeX-Workshop#1107]
Workshop currently supports the following feature, i.e., when cursor in $$, the preview will show near that place:
![image](https://user-images.githubusercontent.com/43427550/51007442-7981eb00-1582-11e9-8623-f98981227112.png)

Can workshop support the following feature?

Real-time display when typing words in $$.
![image](https://user-images.githubusercontent.com/43427550/51007407-4e979700-1582-11e9-8fd0-cfb193a7e31d.png)

**Comment by Astrantia** [comment]
No, go over closed issues before creating a new one

**Comment by tecosaur** [comment]
See https://github.com/Microsoft/vscode/issues/41775#event-1429967275
