### ISSUE TITLE
AUCTEX-style bracket completions on _ and ^

### ISSUE THREAD

**Issue by alha02** [James-Yu/LaTeX-Workshop#111]
Would it be possible to implement completion of brackets on _ and ^ like in AUCTEX for emacs?

What happens when _ or ^ are pressed is that {} are automatically inserted after and the cursor is placed within the brackets. Then, after typing within the brackets, you jump directly out of the brackets with TAB. If that which you typed within the brackets is a single char, then the brackets are even removed when you use TAB. It is a real timesaver.

**Comment by James-Yu** [comment]
AFAIK, vscode does not provide low-level manipulations upon keypress. So it is not possible for the current API provided by vscode.
