### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by zoehneto** [James-Yu/LaTeX-Workshop#1110]
@James-Yu A lot of great features and bugfixes have been added in the last month (also the wiki is now ready for general use and has seen many additions). It would be great if you could release a new version.

**Comment by James-Yu** [comment]
Seems that I was terribly wrong. Thought there were not much to release. Will do so tmr.

**Comment by tecosaur** [comment]
What are the major things that have been added since the last release out of interest?

**Comment by zoehneto** [comment]
-Support for building with an output directory out of the box
-Support for multiple viewers for the same document
-Synctex fixes / improvements
-Synctexjs by default

-Plenty of bug fixes

-Wiki ready for general use (releasing a new version means the wiki is advertised in the vscode store)

**Comment by jlelong** [comment]
- Intellisense is local to the current LaTeX project
- Equivalent of `BIBINPUTS` for the extension to find `.bib` files
