### ISSUE TITLE
Build Latex Project fails after OS upgrade

### ISSUE THREAD

**Issue by sklrsn** [James-Yu/LaTeX-Workshop#1111]
Hello @James-Yu, @jlelong,

My issue:
After OS upgrade (Ubuntu 18.04 -> 18.10). I notice Build Latex Project fails to rebuild the changes.

My solution:
remove.sh
#!/bin/bash
rm -rf *.aux
rm -rf *.bbl
rm -rf *.blg
rm -rf *.fdb_*
rm -rf *.fls
rm -rf *.lof
rm -rf *.log
rm -rf *.out
rm -rf *.pdf
rm -rf *.sync*
rm -rf *.toc
rm -rf *.xmpi

Then it works. I couldn't verify this in other machines. 

Thanks
Kalai

**Comment by jlelong** [comment]
Good to know. I will keep an eye on this.

**Comment by sklrsn** [comment]
Thanks
