### ISSUE TITLE
synctexjs fails with package animate

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#1112]
After the new patch, now synctex won't work.
Error message:
`parse error at line 37064. Any new element is not allowed here.`
Pretty sure I didn't change other stuff.

By the way, the clean.fileType will no longer clean the corresponding files even when clean.enabled is `true`. 

Update:
These problems happen when I have `\animategraphics` in my .tex file.

**Comment by jlelong** [comment]
Can you provide a minimal example to reproduce the synctex issue?

**Comment by tamuratak** [comment]
Please disable syntexjs which is enabled by default since LaTeX Workshop 5.20. See [link](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopsynctexsynctexjsenabled).

**Comment by ShuCaiMonkaS** [comment]
> Please disable syntexjs which is enabled by default since LaTeX Workshop 5.20. See [link](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopsynctexsynctexjsenabled).

Yes, disenabling synctexjs solves the problem.
Thanks.

**Comment by ShuCaiMonkaS** [comment]
Here is my synctex.gz when error happens.
[test.synctex.gz](https://github.com/James-Yu/LaTeX-Workshop/files/2762426/test.synctex.gz)

Besides, below is a sample code generating the error `parse error...`.
When synctexjs is enabled, synctex won't work and even disable some pdf viewer related shortcut bug (like open pdf viewer shortcut malfunction).

```
\documentclass[12pt,letterpaper]{report}
\usepackage[dvips]{graphicx}
\usepackage{pgf}
\usepackage{animate}

\begin{document}
\title{Test}
\author{test}
\maketitle

\begin{figure}
    \centering
    \animategraphics[width=\textwidth]{5}{img/foo}{1}{10}
    \caption{Test}
\end{figure}

\end{document}
```
Just provide `img/foo0.pdf`, ..., `img/foo10.pdf` (or make it simpler).

Disable synctexjs will also solve this problem.

**Comment by ShuCaiMonkaS** [comment]
> @ShuCaiMonkaS Just a comment for your code. I think that both `\title` and `\author` must be before `\begin{document}`

Sorry, I made the example in a haste, didn't check that, it's a bad habit.
Thanks for the comment.

**Comment by Juanpam** [comment]
I'm getting this error as well, I'm trying to generate some figures using the K-Framework auto generated documentation. Will try with disabling the syntexjs option

**Comment by James-Yu** [comment]
@tamuratak any idea?
