### ISSUE TITLE
How to configure the behavior of 'Build LaTeX project'?

### ISSUE THREAD

**Issue by Tedxz** [James-Yu/LaTeX-Workshop#1113]
**Is your feature request related to a problem? Please describe.**
I have no idea what 'Build LaTeX project' actually do and how to configure it. The default 'Build LaTeX project' command does not work well in my case and I wonder if I can assign a recipe to it, so that I can use the shortcut 'ctrl-alt-B'.

Currently, I have to choose my recipe in command palette or side bar.

**Describe the solution you'd like**
Is there some way to set the recipe used by 'ctrl-alt-B'? If not, it would be nice to have a variable in the setting to configure it. Using the first recipe when calling 'Build LaTeX project' would be fine too.

**Comment by Astrantia** [comment]
Did you read the wiki? https://github.com/James-Yu/LaTeX-Workshop/wiki

**Comment by Tedxz** [comment]
Found my answer. Sorry for bothering. Thanks!
