### ISSUE TITLE
Endless parsing

### ISSUE THREAD

**Issue by elliottzhou** [James-Yu/LaTeX-Workshop#1116]
Keep showing parsing... Can not build the .tex file
![screenshot from 2019-01-16 23-26-05](https://user-images.githubusercontent.com/39450973/51295617-7190d380-19e6-11e9-9ea9-f348d1e92360.png)

**Comment by jlelong** [comment]
Can you provide a minimal example and precisely describe what the problem is? 
I cannot see anything wrong from the logs.

**Comment by jlelong** [comment]
For sure, you need a working LaTeX installation on your computer.
What do you mean by the navigation is not working on ubuntu?

**Comment by elliottzhou** [comment]
Emmm, I remembered last time I used this excellent vscode extension in window, it could jump to corresponding code when click on pdf, this time it didn't work. But i am not sure lol , maybe before i used sublime+latex to do that...

**Comment by jlelong** [comment]
Use `ctrl+click` in the `pdf` file. You may also have a look at the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki).
