### ISSUE TITLE
Reload pdf file when additional folders were added to workspace to aviod synctex problem

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [James-Yu/LaTeX-Workshop#1118]
**Is your feature request related to a problem? Please describe.**
When an additional folder is added to current workspace, synctex will stop working unless you open the pdf once again (which will show up in another tab). I suspect this has something to do with pdf viewer parameters. While this can be solved by manually reopening, I need to close the original pdf tab and open another one which is very annoying. I was hoping that an automatic mechanism can be implanted to do the job for me. 

**Describe the solution you'd like**
Anything without manual operations. 

**Describe alternatives you've considered**
Automatically reload pdf file when additional folders were added to workspace (internal viewer). 

**Additional context**
BTW, this might be inappropriate but with multiple folders I experience pdf tab spawning problem. Click on `view pdf` will create another tab instead of replace the existing one.

**Comment by zoehneto** [comment]
Regarding your additional context: clicking on `view pdf` will always create a new viewer tab starting with version 5.20.0 to allow multiple viewers at different document positions of the same document.

**Comment by James-Yu** [comment]
@zoehneto We may need to rethink how the button works. A new button/command to open in new for example?

@Turgon-Aran-Gondolin What do you mean by an additional folder in workspace? Add a new folder to the root of an existing workspace or add a new folder to the opened folder in a workspace environment? A screencast can be helpful.

**Comment by zoehneto** [comment]
@James-Yu it depends on the cause of the problem. Adding a folder should really not break synctex and if it didn't there would be no need to change the button behaviour.

**Comment by James-Yu** [comment]
The problem is, we actually removed a feature, i.e., reveal the corresponding pdf viewer. May possibly adda new command for opening pdf in a new tab.

**Comment by zoehneto** [comment]
I would suggest doing it the other way round (add a new command for revealing the corresponding pdf viewer) since it will only work in vs code but not in external viewers or the browser. Independent of that whatever causes the synctex issue also needs to be fixed or reveal pdf viewer will still be useless for that case.

**Comment by James-Yu** [comment]
Back to the topic. @Turgon-Aran-Gondolin All extensions are reloaded when a workspace is created. So the extension lose track of all the viewers connected. There is no easy way to work around.

@zoehneto I have checked the multi-viewer implementation in details, and found it a bit hard to trace down. I am implementing a new one and replicate the features added in the previous PR. Though this might not be directly related to this particular issue.

**Comment by Turgon-Aran-Gondolin** [comment]
@James-Yu This is the screencast you want. Sorry I couldn't give more details. As shown in the gif, I had a workspace with one folder, I open the pdf preview, then I added another folder via the File menu. After that, I can't synctex in the existing pdf tab anymore. 

(http://g.recordit.co/QQ3BH4ADYr.gif)

**Comment by James-Yu** [comment]
@Turgon-Aran-Gondolin Please refer to my explanation above.
