### ISSUE TITLE
PDF Viewer: Switch Default `Text Selection Tool` to `Hand Tool`

### ISSUE THREAD

**Issue by cortner** [James-Yu/LaTeX-Workshop#1124]
**Is your feature request related to a problem? Please describe.**

When I start a new inline PDF viewer (the standard Latex-Workshop viewer) the setting always seems to be `Text Selection Tool`, which I think is unnatural when using it to view the latex output. Every time I try to move the text, or just reverse-sync, some text gets highlighted which I find mildly irritating (more so over time). I then always have to manually go and click on `Hand Tool`.

**Describe the solution you'd like**

Make `Hand Tool` the default setting.

**Comment by zoehneto** [comment]
I personally prefer the text selection tool. It might be better if you set the default to hand tool in your local settings as described in the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfhand).

**Comment by cortner** [comment]
I was looking for this but didn't find it. thanks - I will try.
