### ISSUE TITLE
Cannot copy the text on left side of the diff window

### ISSUE THREAD

**Issue by yoshimotomasahir** [James-Yu/LaTeX-Workshop#1125]
Hello. I use this extension for a long time and this is very beneficial. First thanks.

Then, I try to select the text on the left side of the diff window in the image below.

![image](https://user-images.githubusercontent.com/18530814/51429476-d00dba00-1c51-11e9-9451-09ba607ca0f9.png)

When I disable this LaTeX-Workshop extension, I can select the text of the left side.
Why does this problem occur?

**Comment by jlelong** [comment]
I have tried to reproduce the problem using the built-in `git diff` but I could not.
Can you give more details on how to reproduce?

**Comment by James-Yu** [comment]
Cannot reproduce +1.

**Comment by yoshimotomasahir** [comment]
I am using VSCode 1.30.2 (user setup) and LaTeX Workshop 5.20.2.
I am also using Japanese Language Pack, C/C++, C# and Python extension.

My explanation is not enough.
Selecting the text on the left window is possible.
As the image I have shown, the 13th line ( `-\usepackage brabra` ) was selected.
But I tried to copy the line (Ctrl+C or right button of the mouse), I could not copy the line.

**Comment by jlelong** [comment]
I can copy the selected text using `ctrl+c`.
The thing you cannot do is **paste** as the `diff` buffer is read-only.

**Comment by yoshimotomasahir** [comment]
I know I can not paste on the **left** side window (`diff` buffer).
I checked the clipboard after I used `ctrl+c`, but the selected text is not in the clipboard.

If you can not reproduce, there is a problem in my environment.
I will continue the investigation for a while.

**Comment by James-Yu** [comment]
This is 99.9% a local config-related problem. You may try reinstalling the extension/vscode and see if things change. I still cannot reproduce the problem with all means.

**Comment by yoshimotomasahir** [comment]
I tried reinstalling VSCode and LaTeX Workshop, but I could not copy the text. 
When I disable LaTeX Workshop, I can copy it.
This is most likely caused by my environment. So please let me know if anyone experiences a similar situation.
