### ISSUE TITLE
[Feature Request] ChkTeX Code Action

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1129]
This is something that's been rattling around in my head for a while, and all the ChkTeX discussion in #1117 has finally prompted me to air the idea.

Quite a few extensions such as https://github.com/bartosz-antosik/vscode-spellright offer inline code actions (see below for screenshot). I frequently have the problems pane open just so I can ctrl+click and 'apply fix' (or similar wording).

![image](https://user-images.githubusercontent.com/20903656/51443405-3e995900-1ce0-11e9-94eb-d1bd6365490d.png)

It would be really nice to be able to do this inline via code actions :smiley: 
If nobody picks this up I may attempt it as my second VS Code extension 'thing' (sub-project?)

**Comment by jlelong** [comment]
I am not sure to understand what you mean as a code action mechanism already exists for `chktex`, have a look at [codeactions.ts](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/codeactions.ts). Actions are available through the yellow light as for the spell extension. When there is no such light, it means that no code action is available for the given error.

It is true that more actions should be added. PRs are welcome.

**Comment by tecosaur** [comment]
Ooops. If this is just the result of my fat fingers pressing the wrong keyboard combo and mentally assigning that feature to the 'nice idea but not yet implemented' bin then I'll be most embarrassed :fearful: 

I'll have a look when I next get a few minutes spare and check my mental picture lines up with reality :stuck_out_tongue: 
(warning, may not be till the weekend)
