### ISSUE TITLE
Zoom with PDF tab open

### ISSUE THREAD

**Issue by dbwz8** [James-Yu/LaTeX-Workshop#113]
When you zoom the editor, the PDF window shrinks (instead of zooming) and vice versa. It appears to be backwards from the desired result.

**Comment by James-Yu** [comment]
This is an upstream (vscode) behavior. I believe reopen the tab will solve the problem.

**Comment by dbwz8** [comment]
Not true. The zoom within the PDF viewer works. The problem is that as you zoom VSCode, it shrinks or grows the extent of the window that you're drawing into (bounding box). This means that if you zoom your editing text, the size of the displayed window for PDF gets smaller and smaller (even though the rendered font size is the same). This is completely broken. Has nothing to do with reopening the tab (consistent in all modes).

**Comment by James-Yu** [comment]
Please provide screenshots.

**Comment by dbwz8** [comment]
At standard zoom:
![image](https://cloud.githubusercontent.com/assets/10551465/25068570/8fd29612-221c-11e7-94d8-ce27f490ec2a.png)
Zooming twice (Ctrl-+ Ctrl-+):
![image](https://cloud.githubusercontent.com/assets/10551465/25068571/b54fde0e-221c-11e7-9054-e3e20bb67a11.png)
If I go in the other direction, the window starts clipping:
![image](https://cloud.githubusercontent.com/assets/10551465/25068577/d21d2fc8-221c-11e7-8144-8c99368834a6.png)
Here's 4 zoom-ins. Note that the Control bar HAS zoomed... but the document font is the same size and the window has shrunk way down:
![image](https://cloud.githubusercontent.com/assets/10551465/25068586/0eacf05e-221d-11e7-990b-641972ef9c64.png)

Thanks for looking into this. Those of use with poor eyesight really appreciate it.

**Comment by James-Yu** [comment]
Duplicate with #107 and https://github.com/Microsoft/vscode/issues/5745

**Comment by dbwz8** [comment]
Got it. Thanks! I'll use one of the workarounds for now
