### ISSUE TITLE
Disable the feature of opening the pdf figure automatic when the cursor hover on the filename and ctrl key is down

### ISSUE THREAD

**Issue by xiaoyaoE** [James-Yu/LaTeX-Workshop#1132]
I often use the cursor to select the filename in the \includegraphics command and press ctrl+c to copy the text. In such condition, the latexworkshop close the tex file and open the pdf figure automatic automatic, which is annoying. Moreover, when the tex file I am editing is in unsave status, vscode will pop up the window asking me "Do you want to save the changes you made in xxx.tex?". Please, I just want to copy the text but not close the file or open the figure.
I try to figure out what's the probem.
When the cursor in hover on the filename and ctrl key is down, it will  trigger this problem.  I even not click the left mouse button.

I think a more resonable logic is that press the ctrl key down and click the  the left mouse button, then open the file.

Please tell me how to disable this feauter.

Thanks.

**Comment by jlelong** [comment]
This is related to [Peek Definition](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition), which is fired up using different approaches : `alt+F12` or `ctrl+hover`. To actually go to the definition, you can use `ctrl+click` or `F12`. 
It turns out that for `.pdf` files, _peek definition_ opens the file in the current editor tab. I do not think it can disabled for `pdf` files only.

**Comment by xiaoyaoE** [comment]
@James-Yu
The problem seems can not be reproduced by any pdf figure.
Please see the attachment for an example files, in which, the fig1 would raise the problem but fig2 not.
[latex-workshop-bug-reproduce.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2781515/latex-workshop-bug-reproduce.zip)

**Comment by jlelong** [comment]
The difference between `fig1` and `fig2` is mostly related to #1050.
I can open `fig1.pdf` directly by clicking on the filename in the Explorer pane but it does not work for `fig2.pdf`.

@James-Yu, I suggest to remove the definition provider for file extensions related to graphics files `.pdf, .eps, .jpeg, .jpg, .JPG, .JPEG`. What do you think of it?

**Comment by James-Yu** [comment]
I agree with that @jlelong . Can you please help make the change? I am on identifying a `path.join` problem w.r.t. another issue. Thx!

**Comment by jlelong** [comment]
For sure, I will do it in the coming hours.
