### ISSUE TITLE
Clicking structure header in split view opens new tab

### ISSUE THREAD

**Issue by LonMcGregor** [James-Yu/LaTeX-Workshop#1133]
**Describe the bug**
When you have a .tex file and another file (not a PDF) open in split view (side by side), if the focus is in the non-tex file, and you click an entry in the structure panel, the extension opens a new tab for the .tex file instead of using the existing one.

**To Reproduce**
1. Open a .tex file
2. Open a 2nd unrelated file in that directory (e.g. a regular .txt file)
3. split the view
4. Have the focus in the .tex file
5. Open the extension side panel, and select an entry in the structure panel
6. See the tex editor focus that section
7. Have the focus in the other file
8. Select an entry in the structure panel

**Expected behavior**
The .tex file moves to the selected location.

**What actually happens**
A new tab for the .tex file opens instead of changing the already open one

**Logs**
[13:53:54] GOTOSECTION command invoked. Target c:\path\to\file.tex, line 821

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.30.2
 - Extension version: 5.20.2

**Additional context**

**Comment by jlelong** [comment]
I cannot reproduce. Can you show us a screencast?

**Comment by James-Yu** [comment]
@LonMcGregor You mean the `tex` was re-opened in the new pane right? This is the expected behavior of vscode. Each pane is individual. If vscode cannot find the file in the focused pane, a new editor is created instead of searching for it in other panes.

**Comment by LonMcGregor** [comment]
Ah, that's unfortunate.

I would have though it would be possible for the extension to be able to view all panes, and if the tex file that the side panel's structure tree points to is open, then it would focus that existing tab and move to the selected position.

If that's not possible due to a limitation in vs code, then nothing to be done.

Thanks for checking on this.
