### ISSUE TITLE
Cannot find root file when \begin{document} is in another file

### ISSUE THREAD

**Issue by pgadient** [James-Yu/LaTeX-Workshop#1138]
**Describe the bug**
When including a file that contains the \begin{document} tag, then LW won't be able to compile the LaTeX file that included the file containing the begin tag.

**To Reproduce**
Create two LaTeX files, namely:

- thesis.tex including the lines below:
\documentclass[oneside,openany,a4paper,12pt]{book}
\input{preamble}
\end{document}

- preamble.tex including the line below:
\begin{document}

**Expected behavior**
The compilation of thesis.tex should work without throwing an error.

<details>
<summary>LaTeX Workshop Output</summary>

[19:26:34] ACTIONS command invoked.
[19:26:35] RECIPES command invoked.
[19:26:36] BUILD command invoked.
[19:26:36] Cannot find LaTeX root file.
</details>

**Desktop environment:**
 - OS: Windows 10 Pro 1809 (x64)
 - VS Code version: 1.30.2
 - Extension version: 5.20.2

**Comment by jlelong** [comment]
See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects) page on multi file projects. In your case, `preamble.tex` is a good candidate for being the root file but it does not include `thesis.tex`, it is actually the other way round. This is against the logic of the extension.

You can either move `\begin{document}` to `thesis.tex` or add the magic comment `% !TEX root = thesis.tex` to the very top of `thesis.tex`.
