### ISSUE TITLE
Does the extension include the "Go to source" function. 

### ISSUE THREAD

**Issue by HawkTom** [James-Yu/LaTeX-Workshop#1139]
Hello, does the extension include the function as navigating the location from pdf file to tex file, like the "Go to source" function in TexStudio. It is too trouble when you find an error in the pdf file and then locate to the error position to revise the error in the source code in the tex file, especially when the tex file is very long.

**Comment by James-Yu** [comment]
You may refer to the synctex functionalities of LaTeX.
