### ISSUE TITLE
"latex-workshop.latex.clean" doesn't delete files in sub-directories 

### ISSUE THREAD

**Issue by ZibanPirate** [James-Yu/LaTeX-Workshop#114]
for example, files on "_chapitres_" sub-directory are still there, and that's really annoying

![image](https://cloud.githubusercontent.com/assets/20110076/25059928/51e9d778-2188-11e7-95c9-e8e6481de8c2.png)

i suggest to add "latex-workshop.latex.clean.**subdirsfiles**" option, that asks to delete sub-directories files, it would be a very handy addition.

**Comment by James-Yu** [comment]
Now cleaning project should also consider files in latex.outputDir config.

**Comment by h41xy** [comment]
Sadly this still does not work for the windows version.

**Comment by h41xy** [comment]
Cleaning subdirectories works if the path is changed to "./*" but opening the pdf now throws the error:
Cannot find PDF file c:\<path to rep>\*\<document>.pdf

**Comment by h41xy** [comment]
For anyone still struggeling with this, if you work with MiKTeX 2.9 and compile with `texify,` pass the `--clean` option to your `latex-workshop.latex.toolchain` command.

**Comment by JacobEberhardt** [comment]
Still at problem on OSX!

**Comment by pjnr1** [comment]
If anyone, like me, came here for a quick fix to quickly get rid of the `*.aux` files generated in the subfolders, one could just add the following to `settings.json`:

``"latex-workshop.latex.clean.fileTypes": [
        "*/*.aux",  ... ]``

Goes without saying that this of course should be used with some precaution !
