### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by zoehneto** [James-Yu/LaTeX-Workshop#1145]
I wanted to edit a wiki page by forking https://github.com/jlelong/LaTeX-Workshop-wiki , but it seems the change I wanted to make has already been made yesterday (see [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/View)) despite the latest commit in the repo being 12 days old. Where can I find and contribute to the current version of the wiki?

**Comment by jlelong** [comment]
Github lacks an easy way to contribute to a wiki. For instance, it is not possible to directly make a PR. The standard approach to circumvent this missing feature is to have a separate git repo (in our case [https://github.com/jlelong/LaTeX-Workshop-wiki](https://github.com/jlelong/LaTeX-Workshop-wiki)) in which anyone can make a PR and then @James-Yu or I can merge this repo with the true wiki, as it is also powered by `git` but only maintainers have write access. I hope this is clearer.

I plead guilty for not pushing the latest updates to [https://github.com/jlelong/LaTeX-Workshop-wiki](https://github.com/jlelong/LaTeX-Workshop-wiki). This is fixed.
