### ISSUE TITLE
--shell-escape flag (once again)

### ISSUE THREAD

**Issue by abarajithan11** [James-Yu/LaTeX-Workshop#1147]
I cannot get the minted package working in VScode via LaTeX Workshop (it works in texmaker). I have checked the previous issues, stack-overflow pages and tried the remedies. Kindly help me with this

**Here's my User Settings JSON file:**

>
>"latex-workshop.latex.tools": [
>        {
>            "name": "latexmk",
>            "command": "latexmk",
>            "args": [
>                "--shell-escape", // added arg to default
>                "-synctex=1",
>                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOC%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "--shell-escape", // added arg to default
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        },
        {
            "name": "texify",
            "command": "texify",
            "args": [
                "--synctex",
                "--pdf",
                "--tex-option=\"-interaction=nonstopmode\"",
                "--tex-option=\"-file-line-error\"",
                "%DOC%.tex"
            ]
        }
    ],

**And here is my compile report:**

>This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6880 64-bit)
entering extended mode
("d:/Users/Aba/Desktop/Schrodinger Project/Report/0_main.tex"
LaTeX2e <2018-04-01> patch level 5
("C:\Program Files\MiKTeX 2.9\tex\latex\base\report.cls"
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex\latex\base\size11.clo"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\inputenc.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\jknappen\mathrsfs.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\mathtools\mathtools.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\tools\calc.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\mathtools\mhsetup.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amstext.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsopn.sty")))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amsfonts.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\tools\array.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amssymb.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\lscape.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-cfg\graphics.cfg")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-def\pdftex.def")))
("C:\Program Files\MiKTeX 2.9\tex\latex\booktabs\booktabs.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\multirow\multirow.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifvtex.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.cfg"))
("C:\Program Files\MiKTeX 2.9\tex\latex\wrapfig\wrapfig.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\lipsum\lipsum.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\l3kernel\expl3.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\l3kernel\expl3-code.tex")
("C:\Program Files\MiKTeX 2.9\tex\latex\l3kernel\l3pdfmode.def"))
("C:\Program Files\MiKTeX 2.9\tex\latex\l3packages\xparse\xparse.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\subfig\subfig.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\caption\caption.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\caption\caption3.sty")))
("C:\Program Files\MiKTeX 2.9\tex\latex\float\float.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\pdfpages\pdfpages.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ifthen.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\eso-pic\eso-pic.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\atbegshi.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\infwarerr.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ltxcmds.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\xcolor\xcolor.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-cfg\color.cfg")))
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\pdfpages\pppdftex.def"))
("C:\Program Files\MiKTeX 2.9\tex\latex\enumitem\enumitem.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\adjustbox\adjustbox.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\xkeyval\xkeyval.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\xkeyval\xkeyval.tex"
("C:\Program Files\MiKTeX 2.9\tex\generic\xkeyval\xkvutils.tex")))
("C:\Program Files\MiKTeX 2.9\tex\latex\adjustbox\adjcalc.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\adjustbox\trimclip.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\collectbox\collectbox.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\adjustbox\tc-pdftex.def"))
("C:\Program Files\MiKTeX 2.9\tex\latex\ifoddpage\ifoddpage.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\varwidth\varwidth.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\minted\minted.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\kvoptions.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\kvsetkeys.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\etexcmds.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifluatex.sty"))))
("C:\Program Files\MiKTeX 2.9\tex\latex\fvextra\fvextra.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\etoolbox\etoolbox.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\fancyvrb\fancyvrb.sty"
Style option: `fancyvrb' v3.1a <2018/11/20> (tvz))
("C:\Program Files\MiKTeX 2.9\tex\latex\upquote\upquote.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\lineno\lineno.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\tools\shellesc.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\ifplatform\ifplatform.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\pdftexcmds.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\catchfile.sty")

Package ifplatform Warning: 
    shell escape is disabled, so I can only detect \ifwindows.

) ("C:\Program Files\MiKTeX 2.9\tex\latex\xstring\xstring.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\xstring\xstring.tex"))
("C:\Program Files\MiKTeX 2.9\tex\latex\framed\framed.sty"))

d:/Users/Aba/Desktop/Schrodinger Project/Report/0_main.tex:25: Package minted E
rror: You must invoke LaTeX with the -shell-escape flag.

See the minted package documentation for explanation.
Type  H <return>  for immediate help
("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\hyperref.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\hobsub-hyperref.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\hobsub-generic.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\auxhook.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\pd1enc.def")
("C:\Program Files\MiKTeX 2.9\tex\latex\00miktex\hyperref.cfg")
("C:\Program Files\MiKTeX 2.9\tex\latex\url\url.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\hyperref\hpdftex.def"
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\rerunfilecheck.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\fontenc.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1enc.def"))
("C:\Program Files\MiKTeX 2.9\tex\latex\titlesec\titlesec.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\blindtext\blindtext.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\tools\xspace.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\textcomp.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.def"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.dfu")))

Sorry, but "MiKTeX Compiler Driver" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\abara\AppData\Local\MiKTeX\2.9\miktex\log\texify.log

**Comment by tecosaur** [comment]
I'm not sure, but does MikTeX use `--write18`?

**Comment by jlelong** [comment]
See #1043. Use the following config
```
"latex-workshop.latex.tools": [
       {
           "name": "latexmk",
           "command": "latexmk",
           "args ": [
               "-pdf",
               "-pdflatex=\"pdflatex --shell-escape %O %S\""
           ]
       }
   ]
```

**Comment by jlelong** [comment]
Looking at the output of `latexmk -showextraoptions`, you can pass the `-shell-escape` option to `latexmk`. Note the single `-`.  
```
"latex-workshop.latex.tools": [
   {
        "name": "latexmk",
        "command": "latexmk",
        "args": [
             "-shell-escape",
             "-synctex=1",
             "-interaction=nonstopmode",
             "-file-line-error",
             "-pdf",
             "%DOC%"
       ]
   }
]
```

**Comment by jlelong** [comment]
I have just added a new entry for this problem in the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk).

**Comment by abarajithan11** [comment]
Hi,

I still had the issue after taking all the steps. Finally I solved it by removing the "texify" part in the User settings file. Looks like that recipe was clashing.

**Comment by abarajithan11** [comment]
I did everything mentioned. But still I get the same issue. I have defined a recipe called "texify" (according to a tutorial) and use Ctrl+Alt+B to build. Looks like it is not using latexmk/pdflatex. How can I change that behavior?

**Comment by jlelong** [comment]
This is not related to the extension but rather to how to pass `--shell-escape` to `texify`.
From [stackoverflow](https://tex.stackexchange.com/questions/187276/how-to-do-shell-escape-in-texworks), you need to add `--tex-option=--shell-escape` to `args` in your `texify` tool.
