### ISSUE TITLE
Unable to launch PDF view or build the project from a file in a subdirectory

### ISSUE THREAD

**Issue by cailloumajor** [James-Yu/LaTeX-Workshop#1149]
**Describe the bug**
Since update to version 5.21.0, I'm unable to launch the integrated PDF viewer or to build the project when editing a file in a subdirectory.
Doing a `git bisect` shows 8dd06def151053ceecfec4bd90547863885a090b as the commit introducing the bug.

**To Reproduce**
1. Open a file in a subdirectory of the project
2. Try to launch PDF view or to build the project
3. Nothing happens

**Expected behavior**
As of before version 5.21.0, PDF viewer starts or project builds.

**Logs**
<details>
<summary>LaTeX Workshop Output</summary>

[21:09:33] Try root file in root directory: /home/nono/Documents/echanges_lcls/Echanges_Infos_LCLS.tex
[21:09:33] Parsing /home/nono/Documents/echanges_lcls/Echanges_Infos_LCLS.tex
[21:09:37] VIEW command invoked.
[21:09:37] Try root file in root directory: /home/nono/Documents/echanges_lcls/Echanges_Infos_LCLS.tex
[21:09:37] Parsing /home/nono/Documents/echanges_lcls/Echanges_Infos_LCLS.tex
[21:09:37] Cannot find LaTeX root PDF to view.
</details>

<details>
<summary>Developer Tools Console</summary>

Nothing relevant here.
</details>

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster (testing) / Windows 7 SP1
 - VS Code version: 1.30.2
 - Extension version: 5.21.0

**Additional context**

**Comment by cailloumajor** [comment]
Sure, see VSCode tree screenshot below. The `img` directories are not developed, they contains only images.

![project tree](https://user-images.githubusercontent.com/8583146/51800543-c3c8c480-2230-11e9-88d2-96916eece248.png)

**Comment by jlelong** [comment]
I also need the relation between the `.tex` files in terms of inclusion.
From the logs, the extension complains about not finding the root file associated to `Echanges_Infos_LCLS.tex `. Which is it?

**Comment by jlelong** [comment]
> but I admit I don't understand the meaning of “the root file associated to” it.

Have a look at the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects). Any TeX file is associated to a root file, which ca be itself. Can you show the content of `Echanges_Infos_LCLS.tex` to understand why it is not recognized as the root file?

**Comment by cailloumajor** [comment]
I undertook to debug this problem and I think I have found something interesting.
In the process of resolving root file from a file in a subdirectory, when going through the `findDependentFiles` method, the call to `path.resolve` (only called when using `\subimport` command) returns an absolute path, relative to the extension directory (`/home/nono/LaTeX-Workshop/materiel/index` in my case) !
https://github.com/James-Yu/LaTeX-Workshop/blob/49611377f7f85fa102154ff8a88f3db636613804/src/components/manager.ts#L307-L308
This obviously breaks the resolving process.

As I said, this bug was introduced by commit 8dd06def151053ceecfec4bd90547863885a090b, before which the use of `path.join` kept the path relative (`materiel/index` in my case) and all worked well.
https://github.com/James-Yu/LaTeX-Workshop/blob/47897c481d79c7416fef5c35d2401c8b2333b31b/src/components/manager.ts#L307-L308

In the debugging context, after simply replacing `path.resolve` by `path.join` and compiling, everything works as expected.

**Comment by James-Yu** [comment]
Nice catch. This was caused by a previous batch change from `join` to `resolve`. However, in `subimport`, both `result[1]` and `result[2]` are relative paths, which will be resolved to an absolute one using the extension root folder. This commit fix the problem.
