### ISSUE TITLE
Add a placeholder for the root directory name

### ISSUE THREAD

**Issue by aplowman** [James-Yu/LaTeX-Workshop#1151]
I like to keep compilation output completely separate from TeX source. In theses cases, it would be useful to enable an additional placeholder, perhaps called `%DIRNAME%`, to represent the name of the directory in which the root file resides (i.e. just the final path element of the existing placeholder `%DIR%`). In particular, consider these example user settings, where we might choose to store output from multiple LaTeX projects in a single parent directory:

```json
 "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-output-directory=C:\\latex_output\\%DIRNAME%",
                "%DOC%"
            ]
        },
    ],   
    "latex-workshop.latex.outDir": "C:\\latex_output\\%DIRNAME%",
```

This would be useful if we store LaTeX project source code on desktop-synchronised cloud storage (e,g, Dropbox), since, although we would like the source code itself to be synchronised, we might prefer output and auxilliary files to not be synchronised.

**Comment by aplowman** [comment]
I understand I can specify the output directory in _Workspace Settings_. I'd prefer to do it in _User Settings_ using a placeholder, so I don't need to set it for every single Latex project.

> Note that latexmk automatically outputs all files to the directory defined by latex-workshop.latex.outDir.

OK, thanks!

**Comment by jlelong** [comment]
I understand your request but it is very difficult to provide a general extension that can adapt easily. The _output_ mechanism is already quite complicated and I have the feeling that it does not make sense to add one more placeholder related to a specific part of path. 
I am closing this issue but I will keep in mind your point and see if i can come up with a more general way to provide the feature.
