### ISSUE TITLE
[Idea] Progress Bar

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1152]
## Progress

 - [x] Simple Regex
 - [ ] Robust Regex
 - [x] Intercept stdout and get page no.
 - [x] Adding status bar
 - [x] Get total pages
 - [x] Visual refinement
 - [ ] Track speed of page-generation
 - [ ] Generate ETA

## Background

There's something deeply unsatisfying about having no idea when my latex compilation is soon to finish.

Should I make myself a cup of coffee or just wait an extra 20s?
Who knows?

I had previously searched for such a thing at not had much luck, and as such dismissed the idea as two-hard-to-do.
However I recently came across this page stackexchange answer: https://tex.stackexchange.com/a/211572/167605 that made me realise that as pages are completed, that info is sent to the stdout!

## Idea

1. Get total page count from compiled PDF
2. When compiling pass output through a function that identifies page-complete-info (I think it's something like `[[5]]` from memory, need to check)
3. Keep track of last created page
4. Set progress = last created page / total pages
5. Update progress bar

## Issues

This only works when:
. (a) There's a PDF
. (b) The change doesn't intoduce too many page numbers

Also page compilation time varies a fair bit...

### However

I think this is better than nothing, and for documents with > 20 pages I imagine it could be relatively handy.

## Need to do

1. Find more spare time
2. Locate example method of:
  (a) Intercepting the latexmk stdout **⟵ HelpWanted No.1**
  (b) Adding a progress bar (or similar element) to the the bottom vscode bar **⟵ HelpWanted No.2**
3. Code it up

@James-Yu, @jlelong, @tamuratak -  I'd be interested in hearing your thoughts.

**Comment by tecosaur** [comment]
Hmm. Well it looks like a good first step would be to see if I can get regex that works for ***all*** cases. To that end would you be able to point me to any good example documents / logs with those sorts of things so I can be more confident I'm no missing several out?

**Comment by tecosaur** [comment]
Well, so far I have made modifications that work for a simple case (the single 12 page document I have happen on hand atm).

Having tried this... I like it. I ***really*** like it.

![image](https://user-images.githubusercontent.com/20903656/51872839-bd326e00-2352-11e9-938f-55336d418e71.png)

I've added a second `vscode.StatusBarItem` (to the right) that atm just shows what page it is at.
The regex I've used is quite simple, but for this document, it works. Further testing is absolutely needed.

The main things I could do with help on ATM are:
**(1)** Finding a way to get pagecount of pdf
**(2)** Getting test cases for page regex

**Comment by tecosaur** [comment]
### I've now got a branch
https://github.com/tecosaur/LaTeX-Workshop/tree/compilation-progress

**Comment by tecosaur** [comment]
@James-Yu, @jlelong - I don't suppose you'd have any ideas regarding getting the page count for the relevant pdf? It's the aspect I would benefit the most from assistance on (I'm quite uncertain).

**Comment by jlelong** [comment]
From [stackoverflow](https://stackoverflow.com/questions/10253669/how-to-get-the-number-of-pages-of-a-pdf-uploaded-by-user), the `pdfjs-ditst` module, which is already required by the extension, provides a way to count the number of pages in a `.pdf` file.

```
const pdfjsLib = require('pdfjs-dist');
...
pdfjsLib.getDocument(pdfPath).then(function (doc) {
    var numPages = doc.numPages;
    console.log('# Document Loaded');
    console.log('Number of Pages: ' + numPages);
}
```

**Comment by tecosaur** [comment]
Thanks  jlelong! I know it seems a bit lazy but I was wasn't sure how pdfjs was used, and whether there was anything already in the extension that I may want to reference instead. There were a lot of search results for pdfjs so I figured asking you guys would be the best way.

My current plan is to track down the view pdf function, copy some of that to get the pdf pagecount if it exists. Since I'm mixing a few things together I'm considering creating a new component fille., if that seems a bit excessive I'll have the main code in `logger.ts`.

**Comment by tecosaur** [comment]
Moved to PR, since it's now in a just-about-usable state.

**Comment by yzhang-gh** [comment]
This is a nice feature indeed.

However, all of the `runIconType` look strange (in terms of the size).

https://github.com/James-Yu/LaTeX-Workshop/blob/78e070392db9052e95106bb50b91bbff6bd67598/package.json#L1151-L1165

Why not just using plain text `Step 1`, `Step 2`? 😳

A problem might be having too much text in the status bar.
Actually, a message of the overall percentage progress (like, `34%`) should be enough. (I rarely care about the page numbers and the compilation time. They introduce too many visual distractions)
Shall we have an option for that?

Many thanks for the effort you made.

**Comment by rschinkoeth** [comment]
why has this been removed in later versions? i really want this useful feature back!

**Comment by tamuratak** [comment]
See #2652
