### ISSUE TITLE
Allow to override build magic

### ISSUE THREAD

**Issue by nafur** [James-Yu/LaTeX-Workshop#1155]
I'm working of a somewhat larger project (think book, thesis project, ...) and need need to integrate other stuff in my build process (collection and processing of data, building of externalized tikz pictures, ...). The whole build process is defined in a Makefile and I can build my project just fine by running `make` in the project root folder. Now I'd like to have my stuff build whenever I save a file, so I made `make` issue an incremental build which is reasonably fast. Then I created a *tool* called `make` and a recipe called `make` and overwrite the existing tools in this particular workspace.

This mostly worked, but I still had to work around some issues, mostly because the extension would be unable to determine the root file and then not start the build (for example for externalized tikz pictures or local packages and classes) so I had to add a hint for the proper main file to make that work at all. This sometimes also fails for other files, sometimes I'm not even sure why. Altogether this makes the whole thing pretty fragile and I spend a lot of time figuring out why the automatic build does not work.

Now for my actual proposal:
Please add a setting `latex-workshop.latex.buildCommand` and (if the setting is set) whenever any file that this extension feels responsible for is saved we run this command instead of this whole other magic.

**Comment by jlelong** [comment]
See the external build command section in the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#external-build-command).

**Comment by nafur** [comment]
Thank you very much!

**Comment by smtrat** [comment]
I finally got to use this "in production" after the last release and unfortunately found an issue when the build is triggered by a file within a subfolder. The command is executed with cwd set to the folder of the "triggering file" (as set [here](https://github.com/James-Yu/LaTeX-Workshop/commit/6c04fffd57d06932a2bca55d437f17c0e2aae214#diff-c7f5bd618dbb862973c3204edf8120d6R41)). In addition the variables (like `%DIR%`) do not seem to work here, hence I have not been able to craft arguments that reliably direct `make` to the proper Makefile in the projects root folder.

My suggestion would be to simply change the cwd to the projects root directory (not necessarily `%DIR%`). This kind of aligns with the general intention of this whole setting, at least in my mind.

**Comment by nafur** [comment]
Sorry for using the wrong account...

My colleague just made me aware of [tasks within vs code](https://code.visualstudio.com/docs/editor/tasks) and it somehow seems like reinventing the wheel here. Maybe we could simply execute a task instead?

[This extension](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave) seems to essentially do the job (though I have not tested it yet)...

**Comment by jlelong** [comment]
The purpose of the external build command is to bypass all the internal mechanism which tries to discover the root file and then triggers the recipe. It does not try to detect the root file but directly run the script from the current file directory as this is the only directory we have at hand. We could use the workspace directory instead but I cannot see any other choice.

For sure, you can directly use tasks, which is somehow similar to setting the cwd to the workspace directory.

**Comment by nafur** [comment]
That's correct, I guess, we can either use the directory of the current file or the workspace dir. The first option feels weird to me as it runs the command in *some* directory and there is no easy option (as far as I can see) to obtain a "canonical" path for this project to locate the Makefile or main file or whatever we want to do. The workspace dir would however be such a "canonical" path for every project.

Using tasks would be cool, however I'd still like to provide the output to LaTeX workshop to show problems, run it on save, etc. Optimally the build command would have a variant or option to not run an external binary but instead trigger a task...

**Comment by jlelong** [comment]
OK, I will change the cwd to use workspace dir.
