### ISSUE TITLE
Cursor-follow not happening in outline

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1156]
**Describe the bug**
The outline of the latex document that appears either in (default) explorer-panel or the latex-panel (`ctrl+alt+x`) does not "follow the cursor". That is, if the cursor in the editor shifts from one section to the other, the corresponding section-titles in the outline does not get highlighted.

This `cursor-follow` feature works fine in explorer-panel for markdown files. And I still remember, when dedicated latex-panel was introduced, the section-titles were getting highlighted in the outline. But somehow, in the last few releases, this is not happening in both the outlines (explorer and latex-panel).

**Comment by werunom** [comment]
I found that cursor follow fails in the outline only for `subsection` and `subsubsection`. When the cursor moves within `section`, the outline accordingly gets highlighted. See below.

![cursor-follow](https://user-images.githubusercontent.com/24664855/52188206-77e0d580-2857-11e9-9976-0d44078cf74f.gif)

**Comment by jlelong** [comment]
Now, the structure provided in the LaTeX panel follow the cursor position. It can be deactivated using the context menu of the structure panel.

Unfortunately, I did not mange to improve the outline in the Explorer panel.
