### ISSUE TITLE
Cursor appears

### ISSUE THREAD

**Issue by joelgenter** [James-Yu/LaTeX-Workshop#1158]
**Describe the bug**
Cursor appears when previewing equations.

**To Reproduce**
1. Create a formatted equation.
e.g.
```latex
\begin{align}
\sigma'(z) = \frac{\partial \sigma}{\partial z}\frac{1}{1 + e^{-z}}
\end{align}
```
2. Highlight text in the equation
3. Hover your cursor over `\begin{align}` so that the preview appears
4. You should observe the occurrence of a strange character in the preview where the cursor left off after highlighting.
e.g.
![image](https://user-images.githubusercontent.com/14948437/52023650-829c1300-24c3-11e9-819f-2471e0b57d29.png)

**Expected behavior**
I would expect the cursor not to appear in the preview. However, there may be a use-case for this in which case this ticket can be closed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - VS Code version: 1.30.2
 - Extension version: 5.21.0

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewcursorenabled.
