### ISSUE TITLE
Improve SyncTex accuracy

### ISSUE THREAD

**Issue by zoehneto** [James-Yu/LaTeX-Workshop#1159]
**Is your feature request related to a problem? Please describe.**
SyncTex only provides line level accuracy (because column information is not stored by Tex). This makes revising documents by looking at the pdf and the synctexing to the source file very cumbersome, as you always have to search where in the highlighted line you wanted to edit.

**Describe the solution you'd like**
Other latex editors work around this issue by combining the cursor position (which can be used to get the correct line using SyncTex) with the surrounding text to match an exact location. See [this](https://tex.stackexchange.com/a/59822) Tex Stackexchange answer for a more detailed description.

**Comment by tamuratak** [comment]
Keeping each line short, less than 100 characters, in a tex file solves this issue. So, I am not interested. 

It is possible to get the text contents of a pdf file with pdf.js through `<div class="textLayer">` although the contents are wholly split with lots of div elements, which makes implementation difficult.

**Comment by zoehneto** [comment]
@tamuratak keeping lines shorter than 100 characters reduces the issue, but then you are wasting a lot of screen real estate (I'm currently using a limit of 150 characters).

I might look into implementing this myself when I have time, just wanted to post this since I came across the issue.
