### ISSUE TITLE
Citation intellisense pop words in tex file instead of references

### ISSUE THREAD

**Issue by praenubilus** [James-Yu/LaTeX-Workshop#1160]
**Describe the bug**
I've tried several days to make the citation intellisense work. In my current setting, I have latest version of vscode and the extension. Every time I input cite{}, the intellisense works, but the popup content are words appeared in my tex file, not the actual references I want. If I manually copy and paste the key from the bib file, the project compile and got the correct output. I uploaded the project to overleaf, it can also pop the correct reference intellisense.

**To Reproduce**
see the attached project package. In the main.tex file.

[thesis.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2819997/thesis.zip)

**Expected behavior**
intellisense will pop the keys of reference in the bib/sample.bib

**Screenshots**
![screenshot from 2019-01-31 22-39-10](https://user-images.githubusercontent.com/547418/52101326-23183300-25a9-11e9-9ccc-e0e74fa3b6b4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - VS Code version: 1.30.2
 - Extension version: 5.21.0

**Comment by jlelong** [comment]
This is because of the space in `\bibliography {bib/sample}`.

**Comment by praenubilus** [comment]
> This is because of the space in `\bibliography {bib/sample}`.

That fix the problem, thanks.
