### ISSUE TITLE
Replace latexmk with DiCy?

### ISSUE THREAD

**Issue by amca01** [James-Yu/LaTeX-Workshop#1163]
Hello,

I am somewhat new to the world of LaTeX editing in Windows, having been a linux user up until quite recently.  (I'd still use linux for preference, but it's simply become too difficult in my workplace.)  LaTeX Workshop + VSCode looks like an excellent solution for Windows, but I do have one elementary issue: is it possible to replace latexmk with DiCy?  To use latexmk I need to install Perl, whereas DiCy uses JavaScript.  Anyway, if I could be pointed in the direction of how to do this I'd be very grateful!

As an aside, might it be possible to include DiCy as an option in a later version of LaTeX Workshop?

Thank you very much,
Alasdair

**Comment by jlelong** [comment]
You can add a DiCy recipe yourself, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes). It seems that `dicy` cannot output raw LaTeX log and therefore no error/warning will be reported to vscode Problem pane.

**Comment by amca01** [comment]
OK - thanks very much!  I've ended up downloading Perl to run latexmk anyway.  But while I'm here - are there snippets for using TiKZ?

**Comment by jlelong** [comment]
There are no snippets for TiKZ yet. If you feel like contributing some, I would be delighted to add them.
