### ISSUE TITLE
Sometimes, the build action lasting very, very long time and it can not end. When I restart the VScode, it can work well.

### ISSUE THREAD

**Issue by DRjy** [James-Yu/LaTeX-Workshop#1166]
It seems that after I modified the tex file and build the tex file several times, the problem will occur. There is no error to report. And the state of build represent it is building now, but it can not end successfully. After I restart the VScode, it can build well again. 
OS: win10
VScod:1.31.0
latex-workshop:5.21.0

Now, What can I do for fixing the problem?
Besides, What can I do for stop the building task? Thanks very much in advance.

**Comment by jlelong** [comment]
It is more likely that your tex compiler is hanging around rather than a problem from the extension.

> Besides, What can I do for stop the building task?

From the command palette, call _Kill LaTeX compiler process_.

**Comment by DRjy** [comment]
In what case, the tex compiler will be hanging? Now, I do not know what I do to trigger the hanging of tex compiler? Thank you very much.

**Comment by jlelong** [comment]
> In what case, the tex compiler will be hanging?

I do not exactly but it has already happened to me a few times. It seems to get stuck in some kind of infinite loop eating a lot of CPU.

**Comment by xiaoyaoE** [comment]
I encounter this problem and Neither the command `Kill LaTeX compiler process`  nor `Kill the active terminal instance` work for me to stop the proceess. What can I do is to restart the vscode.

**Comment by DRjy** [comment]
Yeah, the `kill` command also does not work for me. Sometimes, I feel the frequency of the problem is very large.

**Comment by SevenIsPrime** [comment]
fwiw: this happens to me now, too. After the latest patch to VSC 1.31.0/LW 5.21.0 building latex files always hangs on my macOS machine (10.12.6), seemingly in an endless loop. It is not showing the *Build* message, just the rotating circle icon spinning. There is zero load and the tex command completes nicely, however, this is not detected by LW. The only way to recover is to restart VSC.

It does work exactly once to compile a new file, right after start. The second compile run always fails with the behavior described above.

Any advice? This is seriously annoying.

**Comment by tamuratak** [comment]
I have an idea to fix this issue. But I am not sure it does. If you find reproducible steps, please tell us. It greatly helps us.

**Comment by jlelong** [comment]
@SevenIsPrime, can you give us an example of such a file leading to a hanging build. Can you also post the logs from both the extension and the LaTeX compiler?

**Comment by DRjy** [comment]
unfortunately, there is no logs generated when the problem occurred. 
the following is the log file generated from the last successful time.
[Thesis.log](https://github.com/James-Yu/LaTeX-Workshop/files/2863504/Thesis.log)

The latex template used is [here](https://github.com/mohuangrui/ucasthesis)

**Comment by denniseffing** [comment]
Could you please reopen this issue? I am experiencing the same problems. 
I can not tell you the steps to reproduce this issue because it doesn't happen all the time, I will update this comment if I find out more. I will also add LaTeX Compiler and Extension logs as soon as it happens again.

**Comment by jlelong** [comment]
Do you confirm that you have "build on save" set on? When you save the document for the second time, is the first build finished ?

**Comment by denniseffing** [comment]
Yes, build on save is turned on. I think it was a coincidence, that the bug occured when I saved twice in a small timeframe. I experienced the same issue over and over again and I had to restart VS Code several times to keep working. It also occured when only saving once.

**Comment by jlelong** [comment]
I cannot manage to reproduce so I try to understand if you have anything specific in your configuration and/or workflow. What are the values of the following variables ?
```
latex-workshop.latex.autoBuild.onTexChange.enabled
latex-workshop.synctex.afterBuild.enabled
latex-workshop.latex.autoBuild.cleanAndRetry.enabled
latex-workshop.latex.clean.enabled
```

From your logs
```
[13:37:21] Build root file c:\Users\Dennis\Documents\Latex\Paper\main.tex
[13:37:21] Kill previous process.
[13:37:22] File watcher: responding to change in c:\Users\Dennis\Documents\Latex\Paper\Projektverlauf\Projektverlauf.tex
```
I can see that the second build was initiated before the first one actually finished. This may explain part of the problem.

**Comment by simon123h** [comment]
I experienced the same issue when I set `"latex-workshop.synctex.afterBuild.enabled": true`. Setting it back to false (default) fixed the problem for me.

Other settings:
```
latex-workshop.latex.autoBuild.onTexChange.enabled: false
latex-workshop.latex.autoBuild.cleanAndRetry.enabled: false
latex-workshop.latex.clean.enabled: false
```

**Comment by tamuratak** [comment]
The cause is that `ChildProcess.kill` is used to terminate a current latex processing. Immediately after calling it, we restart a new latex processing. Because we don't wait for the killing process to finish, this issue occurs.

I will submit a PR later.

**Comment by jlelong** [comment]
@simon123h I can't manage to reproduce the issue even when setting `"latex-workshop.synctex.afterBuild.enabled": true` and i can't see the link between calling `synctex` and the `kill` issue. I will try to investigate the kill problem.
