### ISSUE TITLE
VSCode for ubuntu. Problems with compiling when saving sub file

### ISSUE THREAD

**Issue by thygesteffensen** [James-Yu/LaTeX-Workshop#1167]
**Describe the bug**
First, I do not know if this belongs here, but I'm going to fill out a report and see where this takes me.

So, my problem is when I want to compile my .tex pdf. I'm using a structure where I have a main document with the preamble and inputs, e.g. `\input{weeks/week2.tex}`. Then all the content of my document, is in a sub file.
When I'm in a subfile and hit ctrl + s, it saves the file and it should also compile the pdf, but it does not compile the pdf... As weel, when hitting the latex toolbar in the bottom bar, it wont show the compiled pdf nor will it compile when hitting that option.

**To Reproduce**
1. Create a project with input files in a sub folder.
2. Input the files in main.tex as `\input{weeks/week2.tex}`
3. Edit in the sub files and press ctrl + s.

**Expected behavior**
 It should save file and then compile the document.

**Logs**
I do not think a log is necessary, as there are no log? It does not try to compile, nor succes or fail.

**Screenshots**
No screen shots.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - VS Code version: 1.30.1
 - Extension version: 5.21.0

**Comment by jlelong** [comment]
It does work the way you expect it so the problem must be on your side and not in the extension.
Have a close look at the extension logs in the bottom Output panel.

**Comment by thygesteffensen** [comment]
Hi,

After a little more messing around, I found out that I have to open the root directory i vs code, for it to find out what it is working on.

**Comment by jlelong** [comment]
I have just added a new entry in the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#I-cannot-build-from-a-subfile).
