### ISSUE TITLE
What can I do the setting for preview the images in the tex source file?

### ISSUE THREAD

**Issue by DRjy** [James-Yu/LaTeX-Workshop#1168]
For the formula surrounding by the symbol $$ or the reference defined by the command \citep{}，when the mouse hover over the formula or reference，a corresponding preview will display. Now, I want to preview the image defined by the command \includegrphpics. The existing version of latex-workshop supports the feature?  If it can, how do I set to use the feature?

**Comment by jlelong** [comment]
Currently, the extension does not provide image previewing. This is the very last preview feature missing to close #602.
