### ISSUE TITLE
Output directory config not respected

### ISSUE THREAD

**Issue by jdumas** [James-Yu/LaTeX-Workshop#117]
Hi,

I have set my `outputDir` config option to the following:

    "latex-workshop.latex.outputDir": "./build/"

However, the temporary files and the output .pdf still appear in the same directory as the root file, and it clutters everything. Am I missing something there? I am running `vscode` on Archlinux, for what it's worth.

**Comment by James-Yu** [comment]
This only specifies the folder where vscode should look for the generated files. You need to use latex commands to redirect your latex workflow.

**Comment by jdumas** [comment]
Then the documentation of the option should be updated, because it is a bit ambiguous as it is.
That being said, it would be nice to be able to specify a build folder more easily. If one has to tweak latexmk's options to do it, I suggest documenting the proper way to do it in the extension's README.
