### ISSUE TITLE
Adding -xelatex argument to latexmk

### ISSUE THREAD

**Issue by raptoni** [James-Yu/LaTeX-Workshop#1170]
I added the following to my config file. The problem is that latexmk does not use xelatex but pdflatex instead. However wenn I execute the following command in the terminal latexmk is using xelatex and compilation is successful  

` latexmk -xelatex -synctex=1 -interaction=nonstopmode -file-line-error  main.tex  `

How can I make latexmk use xelatex?

My config:
`    "latex-workshop.latex.recipes": [
      {
        "name": "latexmk 🔃",
        "tools": [
          "latexmk"
        ]
      }
]
    "latex-workshop.latex.tools": [
      {
        "name": "latexmk",
        "command": "latexmk",
        "args": [
          "-xelatex",
          "-synctex=1",
          "-interaction=nonstopmode",
          "-file-line-error",
          "-pdf",
          "-outdir=%OUTDIR%",
          "%DOC%"
        ],
        "env": {}
      },
      {
        "name": "xelatex",
        "command": "xelatex",
        "args": [
          "-synctex=1",
          "-interaction=nonstopmode",
          "-file-line-error",
          "%DOC%"
        ],
        "env": {}
      },
      {
        "name": "bibtex",
        "command": "bibtex",
        "args": [
          "%DOCFILE%"
        ],
        "env": {}
      }
    ]
}`

**Comment by James-Yu** [comment]
`-pdf`

**Comment by cscherrer** [comment]
@James-Yu I'm having this problem as well. Your response is a bit cryptic, can you please elaborate?

**Comment by jlelong** [comment]
In the `latexmk` command args, replace `-pdf` by `-xelatex`. See the default configuration
https://github.com/James-Yu/LaTeX-Workshop/blob/003efb4b68b91d531b23c4b2cbabe38b44779fd3/package.json#L674-L689

**Comment by cscherrer** [comment]
That does it, thank you @jlelong !
