### ISSUE TITLE
Normal key bindings deactivated when PDF preview has the focus

### ISSUE THREAD

**Issue by Nabav** [James-Yu/LaTeX-Workshop#1172]
As soon as the focus is on the PDF preview tab, the normal key bindings are deactivated. For example, I switch from editor group 1 to 2 with Ctrl+2 and navigate through the PDF document. However, I cannot return to editor group 1 by Ctrl+1. I think this happened with the latest Visual Studio Code update to version 1.31.1.

**Comment by jlelong** [comment]
We have not touched this part for a while. If something changed, it is more like on vscode side.

**Comment by lamBOOO** [comment]
I can confirm this issue using VSCode 1.31.0 and LaTeX-Workshop 5.21.0. I downgraded to VSCode 1.30.2 and it is working again.

**Comment by jlelong** [comment]
I guess you could open an issue in VSCode repo, but the difficulty is to reproduce the issue without using LW extension. This might be related to [#68225](https://github.com/Microsoft/vscode/issues/68225).

**Comment by Nabav** [comment]
Yes, I will follow the issue there. Thanks.
