### ISSUE TITLE
External build command setting [v 5.21.0]

### ISSUE THREAD

**Issue by buggymcbugfix** [James-Yu/LaTeX-Workshop#1175]
Thanks for the awesome package.

The README suggests using the following for an external build command (I need `make`):

```js
"latex-workshop.latex.external.build.command": {
  "command": "",
  "args": [
    ""
  ]
}
```

However VS Code is giving me an `Unknown configuration setting` warning and I can't see `make` being run by LW.

**Comment by jlelong** [comment]
The external build command feature has been introduced after the release of the last version. I am afraid you have to wait until a new release to use this feature. It will come soon.
