### ISSUE TITLE
[Wiki] Editor Feature Parity

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1177]
In my fork of the wiki, I've recently added a page [`Features.md`](https://github.com/tecosaur/LaTeX-Workshop-wiki/blob/master/Features.md).

The purpose is twofold.
 1. To make it clearer to prospective users what we have to offer how we stack up compared to other common editors
 2. To provide developmental direction, by making it clear what features we lack compared to other common editors

At the moment the page is quite incomplete, and probably somewhat incorrect; but it's a starting point. There are already a few features such as Overleaf's suggestion smart ranking that I can see being implemented to good effect.

**Comment by jlelong** [comment]
I agree that it would nice to a fair comparison with some other well-known editors or extensions/plugins. However, it is not easy to precisely say what features a given editor provides and I do not feel at ease with making such comparisons. Maybe, we could just sick to a list of features provided by LaTeX-Workshop and add links to the relevant wiki page.

Going through the feature list, I have a few questions/remarks

- `Goto definition` on references/citations works in LW using VSCode's native `Go to Definition` function. 
- There is no clear separation between declaration and definition in LaTeX, so I don't understand what the `Goto declaration` item mean.
- What does the `Rename` feature means? Isn't it related to VSCode's `Change All Occurrences` function?
- What does `Find references` means?
- As LaTeX-Workshop is not an editor, Spell check cannot be directly provided by the extension but many spell check extensions exist for VSCode. I suggest you turn the ❌into ✔️while keeping the footnote.

**Comment by tecosaur** [comment]
I'll respond to your dot points with dot points :smiley: 

 - I'll update the cross to a tick with a footnote that it only works for references/citations
 - That item (and some others that TBH I don't completely understand) are from the [texLab page](https://texlab.netlify.com/) I'm removing the ones I don't understand but initially I just copy-pasted all the items. I believe the next two dot points refer to the options seen in the following screenshot.

![image](https://user-images.githubusercontent.com/20903656/52984145-2e80b080-3429-11e9-8786-b05ef0131048.png)

 - Good suggestion, I'll do that.

**Comment by jlelong** [comment]
I am closing this issue but when you are ready make a PR on the [wiki](https://github.com/jlelong/LaTeX-Workshop-wiki) and we can continue the discussion there if need be.

**Comment by tecosaur** [comment]
Sounds good
