### ISSUE TITLE
Better Logo

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1179]
As has been stated previously (#947) a logo rework couldn't hurt.

To that end, I've whipped up a different take on the icon. Feel free to use it.

![latex-workshop-new-logo](https://user-images.githubusercontent.com/20903656/52933626-ef058600-338e-11e9-8c87-4eb7a931bad4.png)

**Comment by James-Yu** [comment]
I always agree that we need a better logo, but I am never a design person. The previous one was drawn with inkscape 🤣 I'm a bit conservative on the above one, as I thought it would be better to have some sort of TeX or LaTeX element in the logo. Any other comments or idea?

**Comment by tecosaur** [comment]
Well, I wanted some sort of TeX element in there too, so I started off looking for what could be done with that. The issue I came up against is that it seems impossible to both have a smart, clean, memorable design and _also_ incorporate any part of the LaTeX logo.

The main way I can see incorporating _TeX_ can be done is like TeXstudio or TexMaker:

<img src="https://user-images.githubusercontent.com/20903656/52983701-4ce5ac80-3427-11e9-9f4d-baf2bb4db2f4.png" alt="image" width="100rem">
<img src="https://user-images.githubusercontent.com/20903656/52983726-71da1f80-3427-11e9-968d-e83af2306f98.png" alt="image" width="100rem">

Other editors have gone with a different approach, omitting _TeX_ from their logos

<img src="https://user-images.githubusercontent.com/20903656/52983751-8cac9400-3427-11e9-9bea-a9daee53d389.png" alt="image" width="100rem">
<img src="https://user-images.githubusercontent.com/20903656/52983786-acdc5300-3427-11e9-9a58-7a0507b562df.png" alt="image" width="100rem">
<img src="https://user-images.githubusercontent.com/20903656/52983803-bb2a6f00-3427-11e9-9995-612e97f48a25.png" alt="image" width="100rem">

Of the two approaches I find the logos of the second group to be more visually striking, and so ended up going in that diretion. However this was based on the assumption that the only TeX avalible to use was the stylised _LaTeX_/_TeX_, however if theres something else I'm unaware of that could be used to make the logo clearly TeX related I'd love it if youcould bring it to my attention.

**Comment by James-Yu** [comment]
Let's have a try!
