### ISSUE TITLE
[Proposal] add code formatter to latex-workshop

### ISSUE THREAD

**Issue by jose-a-sa** [James-Yu/LaTeX-Workshop#118]
A nice feature would be a code formatter with autoindents in latex and .bib files,

For exemple, for .bib files, with pretty columns
```
@article{CiteKey,
	author         = {{...}},
	title          = {{...}},
	journal        = {Phys. Rev.},
        (...)
}
```

Thank you for your awesome extension @James-Yu 👍 
Regards, Jose

**Comment by jose-a-sa** [comment]
I was thinking if was possible, besides `\begin{env}` indentation, to work on a formatter that
- maintained inline command like 
```
\cmd1{stuff}
```
- indented if they are multiline, i.e. 
```
\cmd2{
    stuff
}
```

**Comment by nfode** [comment]
@jose-a-sa 
Check this out: [latex-formatter](https://marketplace.visualstudio.com/items?itemName=nickfode.latex-formatter)
It is a basic latex-formatter for vscode using latexindent.pl, it may already have some features you need.

**Comment by James-Yu** [comment]
@jose-a-sa that extension does a good job.

@nfode I checked your extension and it is awesome! I would like to make a suggestion on integrating the feature/codebase into LaTeX Workshop. How do you think of that? Do you prefer to maintain it as a standalone one?

**Comment by nfode** [comment]
If I get latex LaTeX Workshop running with my setup there speaks nothing against it. 😄

**Comment by AllanWang** [comment]
Bump :). Would be awesome if the two can be integrated

**Comment by nfode** [comment]
@AllanWang you wanna do it by yourself or should I take a look and create a PR?

**Comment by AllanWang** [comment]
@nfode I personally just started using visual studio and haven't had much experience with extensions. Would be great if you can take a look! As of now I'm using both extensions side by side.

**Comment by jlelong** [comment]
There is already one available in the extension, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Format).
