### ISSUE TITLE
Occult temporary files in explorer

### ISSUE THREAD

**Issue by deividrvale** [James-Yu/LaTeX-Workshop#1181]
**Is your feature request related to a problem? Please describe.**
The file explorer shows all files in the folder you are working on. For example, files with extensions like *.fls, *.log, synctex.gz and so on. But this type of files usually is not needed for someone that is working on a normal latex project. 
(Perhaps you will open the log and temporary files for development purposes). 

**Describe the solution you'd like**
Many latex editors, for example, TexStudio has this feature. They don't show temporary files in the file structure. I do like the fact that in the VSCode file explorer we see the actual files of the project, TexStudio does not show all files as VSCode do.

**Describe alternatives you've considered**
You could also give some options in settings for the user to enable all files in explorer or to not show temporary files.

**Additional context**
Here's some print of some project. This is a simple one, if you have some more complex projects the temporary files will begin to be annoying because you want to find your working files, not temporary ones. 
![screenshot from 2019-02-19 22-44-34](https://user-images.githubusercontent.com/5068803/53060114-0bd9b080-3498-11e9-9987-c7f7a0b09498.png)

**Comment by jlelong** [comment]
Use the `files.exclude` setting to hide files from the _Files Explorer_.

**Comment by deividrvale** [comment]
I manage to hide the log files. Thanks!
Its possible to the extension automatically add these files to the exclude settings?
