### ISSUE TITLE
why xelatex receip is not available in the popup?

### ISSUE THREAD

**Issue by amirj** [James-Yu/LaTeX-Workshop#1183]
Hi,

This is my settings.json file:

> {
>   "window.zoomLevel": 0,
>   "editor.fontSize": 17,
>   "python.linting.pylintEnabled": false,
>   "python.linting.pep8Enabled": true,
>   "python.linting.enabled": true,
>   "python.pythonPath": "python3",
>   "editor.minimap.enabled": true,
>   "latex-workshop.view.pdf.viewer": "external",
>   "[latex]": {
>     "editor.wordWrap": "on",
>     "latex-workshop.latex.tools": [
>       {
>         "name": "latexmk",
>         "command": "latexmk",
>         "args": [
>           "-xelatex",
>           "-synctex=1",
>           "-interaction=nonstopmode",
>           "-file-line-error",
>           "-pdf",
>           "-outdir=%OUTDIR%",
>           "%DOC%"
>         ]
>       },
>       {
>         "name": "pdflatex",
>         "command": "pdflatex",
>         "args": [
>           "-synctex=1",
>           "-interaction=nonstopmode",
>           "-file-line-error",
>           "%DOC%"
>         ]
>       },
>       {
>         "name": "xelatex",
>         "command": "xelatex",
>         "args": [
>           "-synctex=1",
>           "-interaction=nonstopmode",
>           "-file-line-error",
>           "%DOC%"
>         ]
>       },
>       {
>         "name": "bibtex",
>         "command": "bibtex",
>         "args": [
>           "%DOCFILE%"
>         ]
>       }
>     ],
>     "latex-workshop.latex.recipes": [
>       {
>         "name": "latexmk",
>         "tools": [
>           "latexmk"
>         ]
>       },
>       {
>         "name": "xelatex -> bibtex -> xelatex*2",
>         "tools": [
>           "xelatex",
>           "bibtex",
>           "xelatex",
>           "xelatex"
>         ]
>       }
>     ]
>   },
>   "latex-workshop.latex.autoBuild.onSave.enabled": false,
>   "editor.formatOnSave": true,
>   "editor.wordWrap": "wordWrapColumn",
>   "editor.wordWrapColumn": 120,
>   "git.inputValidationLength": 120,
>   "python.linting.pep8Enabled": true,
>   "python.linting.pep8Args": [
>     "--max-line-length=120"
>   ],
>   "latex-workshop.latex.autoBuild.run": "never"
> }
> 

when I'm trying to compile using ctrl+alt+b it always use pdflatex, but I want to use xelatex instead. If I'm using ctrl+shift+p and run "Latex Workshop: Build with Recipe" only these items are available:

- latexmk with up and down array
- pdflatex -> bibtex -> pdflatex*2

It seems that my settings presented in *settings.json* have not been applied!

**Comment by tecosaur** [comment]
If you add a magic comment such as 

```
%!TEX TS-program = xelatex
```

to the start of your document and compile via `ctrl`+`alt`+`L` `B`
***or*** use the `latexmk` recipie
***or*** activate the default 'build on save' action (latexmk)

That should use xelatex.

**Comment by tecosaur** [comment]
Another thought, try putting the latex tools and recipes outside of the `[latex]` block,
```
"[latex]": {
    ...
}
```

Quite a few vscode setting's don't work inside language scope blocks (whatever they're called).
The orange squiggly line I see if usually a good indication

![image](https://user-images.githubusercontent.com/20903656/53093148-992d0b80-3551-11e9-99d1-e529adabe29d.png)

**Comment by amirj** [comment]
putting latex tools and recipes inside the `[latex]` block was the problem. Thanks @tecosaur
