### ISSUE TITLE
Chinese section garbled on the structure box

### ISSUE THREAD

**Issue by zhenlingcn** [James-Yu/LaTeX-Workshop#1184]
Chinese section shows garbled characters on the structure box.Please fix it, thanks.

![image](https://user-images.githubusercontent.com/18747119/53098007-acde6f00-355d-11e9-85f7-5d56779a762c.png)

**Comment by jlelong** [comment]
This works. There must be an encoding issue. Please provide a minimal example.

**Comment by jlelong** [comment]
I close the issue but feel free to post any new information to reproduce the problem if any.

**Comment by zhenlingcn** [comment]
I repeated the problem through trial and error, UTF-8 encoding can display Chinese normally, but GBK encoding will produce garbled characters.

**Comment by jlelong** [comment]
Good to know. I do not think we can do much on this.
