### ISSUE TITLE
Incorrect highlighting for mathematics delimiters

### ISSUE THREAD

**Issue by simon-nicholls** [James-Yu/LaTeX-Workshop#1185]
The math delimiters `$` and `$$` are being matched across semantically mismatched sections of text, leading to scoping and highlighting problems.

For example an opening `$` can be matched within inline code, and the closing `$` in a nested code block:

```latex
A Haskell type definition for \(\mathbb{N}\), and testing \inlinecode{<$>}

\begin{code}
  data Nat = Zero | Succ Nat
  test = (++"...gnom!") <$> ["pizza", "ljubljanska"]
\end{code}
```

which will incorrectly set a scope of `support.class.math.block.tex` for

```latex
$>}

\begin{code}
  data Nat = Zero | Succ Nat
  test = (++"...gnom!") <$
```

I initially raised the issue on JustusAdam/language-haskell#82

I would instead expect `$` matching to only be done within same-semantic chunks of text, and beyond that I'd like to disable matching inside code environments if possible.

MacOS 10.14.3, VS Code 1.31.1, Workshop 6.0.0

**Comment by simon-nicholls** [comment]
Wow, that was quick, thanks!

As per details in https://wiki.haskell.org/Literate_programming, can we also add `spec` as a verbatim code block? Where `code` will be compiled by the Haskell compiler, `spec` is a block that will be treated as Haskell code, but that shouldn't be compiled as part of the module (it's better for example code snippets, or Bird-Meertens style equational reasoning).

When it comes to typesetting, `code` and `spec` are implemented in terms of `minted` or `listings` for example, but `code` and `spec` are the repeated content tags expected for LaTeX unliteral processing in Haskell, so are great to have.

I used `\inlinecode` in my example, but there doesn't appear to be a standard for that. In fact, going by the `lstinline` you already had in your pattern match, and noting that minted uses `mintinline`, I think `codeinline` would be a more fitting name.

Thanks again. I'll look into how I can test repo versions of extensions, so I can have a play myself.

**Comment by jlelong** [comment]
@simon-nicholls can you be more specific.

I can declare the `code` and `spec` as verbatim. Easy. Are these related to Haskell? I could also declare as them embedded Haskell code and it would get highlighted as so.

`\inlinecode` is already considered as verbatim

Testing the new syntax highlighting is easy. Just download [`LaTeX.plist`](https://github.com/James-Yu/LaTeX-Workshop/blob/65fb1325e88aa3a9e1f3bd3f2e5de9b0f1095c97/syntax/LaTeX.plist) and copy it to `.vscode/extensions/james-yu.latex-workshop-6.0.0/syntax`

**Comment by simon-nicholls** [comment]
I'll download that file for testing, thanks.

Yes, `code` is specifically expected by the standard `unlit` preprocessor of Haskell's compiler, and `spec` is an associated convention.

It would be ideal for me personally if `code` and `spec` were declared as embedded Haskell code whilst in LaTeX Workshop mode, but I realise that for users that don't program in Haskell, they might use a `code` tag for say Clojure.

The most important thing for me is that `$` matching doesn't cross blocks of different semantics. Markdown All in One appears to require `$` on the same line, and `$$` on newlines, as a different approach https://github.com/yzhang-gh/vscode-markdown/blob/master/syntaxes/math_inline.markdown.tmLanguage.json

For me, I need to use mathematics alongside Haskell operators alongside currency, so these `$` are tricky blighters.

So you know my overall use, I open a `.lhs` (literate haskell) file in VSC, and the JustusAdam/language-haskell extension fires up. I can code away, using a language server protocol hook-up for flycheck etc, but I'll switch back-and-forth so that I can use LaTeX Workshop features in LaTeX heavy areas of the document.

That Haskell extension uses `text.tex.latex.haskell` as the scope for the overall LaTeX document. Which LaTeX Workshop then handles the highlighting for, by matching `text.tex.latex`.

Ideally, when my cursor is in embedded Haskell, I would get the JustusAdam/language-haskell extension features, but when I move the cursor out into LaTeX portions of the document, shabang, I am getting LaTeX Workshop features. Dreaming?

Here are the active scopes, as seen when in Literate Haskell mode:

![code](https://user-images.githubusercontent.com/287472/53164112-6b82a980-35c7-11e9-9aa6-d6ed3b38b270.png)

**Comment by simon-nicholls** [comment]
I just added

```plist
			<key>contentName</key>
			<string>source.haskell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
```

to the `LaTeX.plist` for `code`, and sure enough, highlighting appears.

However, it doesn't stop the `$` matching from spanning into inappropriate areas. This also happens if I use a `pycode` environment, so it appears to be a general problem of greedy `$` matching.

**Comment by jlelong** [comment]
I cannot reproduce your problem with `$`. Can you post a complete example?

I am afraid it would be a bit disturbing to declare the `code` content as embedded Haskell. Could it be possible to use `hscode` or something like that? For Python, we use `pycode`.

> Ideally, when my cursor is in embedded Haskell, I would get the JustusAdam/language-haskell extension features, but when I move the cursor out into LaTeX portions of the document, shabang, I am getting LaTeX Workshop features. Dreaming?

This is precisely the way it is expected to work.

**Comment by simon-nicholls** [comment]
Well, a very happy start to the day! Creating a fresh minimal example, I couldn't reproduce the `$` issue either! Eh, a reboot does wonders sometimes.

`code` is important for literate Haskell programming to work out of the box, but yes, I too think that it's a generic name that shouldn't be fixed as embedded Haskell.

It would be nice if VSCode highlighting was configurable at some point in the future, so people could pick their own content type for these situations. I tried setting the `contentName` to generic names like `source` and `source.generic`, rather than `source.haskell`, but this again throws the highlighting.

So unless there is a **safe** generic source type to choose, the way you have it is the right step I think. When in Literate Haskell mode, the highlighting from LaTeX Workshop and Literate Haskell work well together. When in LaTeX Workshop, the code is neutral verbatim.

I very much like the `hscode` idea in addition, for people who use their own preprocessors on `.lhs` files, set to be `source.haskell`. I can submit something later today if that's ok.

Regarding `spec`, `hsspec`, `hsinline` etc, I'm going to put some feelers out on the Haskell side.
