### ISSUE TITLE
[Feature Request] equation preview with extra math packages

### ISSUE THREAD

**Issue by garylavayou** [James-Yu/LaTeX-Workshop#1187]
**Is your feature request related to a problem? Please describe.**
The preview environment seems not to support the commands `\bm` and `\mathclap`, which are in the package `bm` and `mathtools`. 
    ![img](https://user-images.githubusercontent.com/25133690/53139608-1d6ca680-35c5-11e9-8ccb-b1bdaad5070b.png)`

**Describe the solution you'd like**
As `latextools` does, an option could be added to the LaTeX Workshop, so that users can add extra math related packages that are also used in their `tex` files.
In this way, the preview should be correctly rendered.

**Describe alternatives you've considered**
Or the requested packages could be included in the built-in preview settings.

**Comment by jlelong** [comment]
From [stackoverflow](https://stackoverflow.com/questions/21192606/can-i-add-latex-packages-to-mathjax)

> You can not simply drop a LaTeX package into MathJax. The packages that MathJax supports have to be re-implemented in javascript, which is difficult for non-trivial packages

Mathtools is not supported by mathjax, see [mathjax repo](https://github.com/mathjax/MathJax/issues/1582)

**Comment by xinleiyu** [comment]
`\bm` is recommended by some as the best option for LaTeX, but not supported by MathJax.

Can we change the config as follows to replace `\bm` with `\boldsymbol` in preview?

```
TeX: {
  Macros: {
    bm: ["\\boldsymbol{#1}",1],
  }
}
```

From [the issue of MathJax: LaTeX input: add support for bm package](https://github.com/mathjax/MathJax/issues/1219)

**Comment by tamuratak** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandnewcommandFile
