### ISSUE TITLE
Two warnings appear after update and settings cannot be changed anymore

### ISSUE THREAD

**Issue by jhmenke** [James-Yu/LaTeX-Workshop#1190]
After starting VS Code a few days ago - i guess an extension update happened - every time i open my latex project two identical warnings appear:

> `latex-workshop.latex.clean.enabled` and `latex-workshop.latex.clean.onFailBuild.enabled` have been replaced by `latex-workshop.latex.autoClean.run`, which is set to `onFileChange`. See the wiki.

Apart from that, the setting for "Auto Build -> Run" has been changed to `onFileChange`. I would rather have `onSave`, which is marked as default. If i change the setting, it works for the current session, but after restarting it is changed back to `onFileChange`. I did not make any modifications regarding latex in my project's settings.json

I guess custom settings, among them a deprecated one, are parsed, but i do not know where from.

**To Reproduce**
I am unsure how to reproduce this. I did uninstall and reinstall the extension several times, which did not help.

**Expected behavior**
Settings should be saved even after restarts.

**Desktop (please complete the following information):**
 - OS: ElementaryOS
 - VS Code version: 1.31.1
 - Extension version: 6.0.0

**Comment by James-Yu** [comment]
Please remove the deprecated settings in your config.json. It is not possible to auto remove them from the extension side.

**Comment by jhmenke** [comment]
Okay i got rid of the warnings that way.

But the other issue is still real. I set the following in the global settings.json:

`    "latex-workshop.latex.autoBuild.run": "onSave"`

When i restart VS Code, it is automatically set to:

`    "latex-workshop.latex.autoBuild.run": "onFileChange"`

It doesn't matter whether i use VS Code to change the setting or use an external editor to modify settings.json

**Comment by James-Yu** [comment]
You can just remove this config. It defaults to `onSave`.

**Comment by James-Yu** [comment]
Also, remove all deprecated config items.
