### ISSUE TITLE
Intellisense and bibDirs not working in 6.0.0

### ISSUE THREAD

**Issue by nbeckers** [James-Yu/LaTeX-Workshop#1194]
After updating to 6.0.0 the citation browser/Intellisense is not working anymore. My `.bib` file is in a different location as the source code, but setting `latex-workshop.latex.bibDirs` to that folder (absolute path) does not solve the problem.

The citation browser was working in 5.21.0 just fine (here I also set `latex-workshop.latex.additionalBib` to the `.bib` file (absolute path)).

Thanks!

**Comment by jlelong** [comment]
I confirm that it does work. 
Post the relevant part of your `.tex` file along with the value of `latex-workshop.latex.bibDirs` and the logs of the extension.

**Comment by nbeckers** [comment]
I got it working now too. 
The problem seemed to be that I didn't call `\bibliography` directly in my main `.tex` file, but through a custom command which then called `\bibliography`.

My apologies if this issue was unnecessary, but I thought it was odd that the Intellisense/citation browser worked fine in 5.21.0 with my own original `.tex`files, but not in 6.0.0 with `latex-workshop.latex.bibDirs`. My guess is that this worked because I specifically specified the `bib` file I needed in `latex-workshop.latex.additionalBib` and the new `bibDirs` functionality only selects the `.bib` file that it found in the `\bibliography` command?

Thanks!

**Comment by jlelong** [comment]
> My guess is that this worked because I specifically specified the `bib` file I needed in `latex-workshop.latex.additionalBib` and the new `bibDirs` functionality only selects the `.bib` file that it found in the `\bibliography` command?

You are right. I am working on a new mechanism using the last compilation to detect files that are through non standard macros.
