### ISSUE TITLE
Problems not displayed when using out-dir and aux-dir with MikTeX

### ISSUE THREAD

**Issue by itzsimpl** [James-Yu/LaTeX-Workshop#1195]
**Describe the bug**
My toolchain is based on the latest MikTeX, and I am using a custom latexmkrc in combination with latexmk in order to build my project. I have a folder structure where auxiliary files are put into the subfolder 'int/' and the output files into the subfolder 'out/.' Currently the LaTeX workshop provides only the ability to set the output directory. However, problems do not get caught even if the aux and out folders are one and the same, equal to output directory as set in LaTeX workshop settings.

**To Reproduce**
Custom `.latexmkrc`
```
$out_dir = 'out/';
$aux_dir = 'int/';

$ENV{'TEXINPUTS'}='../:int/:out/:';
$ENV{'BSTINPUTS'}='../:int/:out/:';
$ENV{'OPENTYPEFONTS'}='.:../:';
$ENV{'TTFONTS'}='.:../:';

$bibtex_fudge=0;
# force using xelatex without xdv
$pdf_mode=1;
$pdflatex="xelatex %O %P";
```

Custom `.vscode/settings.json`
```
{
    "latex-workshop.latex.recipes":[
        {
            "name": "latexmk 🔃",
            "tools": [
                "latexmk"
            ]
        }
    ],
    "latex-workshop.latex.tools":[
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",            
                "%DOC%"
            ],
            "env": {}
        }
    ],
    "latex-workshop.latex.outDir": "out/"
}
```

**Expected behavior**
Catch problems and show them in problems pane.

**Logs**
I did not find anything suspicious in the logs.
 
**Desktop (please complete the following information):**
 - OS: [MacOS Mojave 10.14.2]
 - VS Code version: [1.31.1]
 - Extension version: [6.0.0]

**Additional context**
out/*.log file contains 
Overfull \hbox (2.63443pt too wide) in paragraph at lines 188--197

**Comment by jlelong** [comment]
Problems are directly caught from the standard output of the compiler so I would really be surprise if the `out-dir` and `aux-dir` options had something to do with this. I would rather bet that this is related the `--max-print-line`, see #866.

Can you check that `latex-workshop.latex.option.maxPrintLine.enabled` is set to `true`?
Can you post the extension logs related to the build step and the raw output from the LaTeX compiler?

**Comment by itzsimpl** [comment]
Yes, `latex-workshop.latex.option.maxPrintLine.enabled` is set to `true`. 

[LaTeX Workshop Output.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2897302/LaTeX.Workshop.Output.txt)
[LaTeX Compiler raw.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2897303/LaTeX.Compiler.raw.txt)

**Comment by itzsimpl** [comment]
Yes, updating `latex-workshop.latex.tools` to
```
"latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-max-print-line=200",
                "%DOC%"
            ],
            "env": {}
        }
]
```
resolves the issue, however, I had to manually add the `-max-print-line` option, regardless the state of `latex-workshop.latex.option.maxPrintLine.enabled` and the question is what would an appropriate `N` be (is 200 enough for all cases).

**Comment by jlelong** [comment]
In the extension, we set `N=10000` but a much smaller value should be fine most of the time.

The `-max-print-line` should be automatically when `latex-workshop.latex.option.maxPrintLine.enabled` is set and you are using MiKTeX. Sofar, we only did this for Windows. It should not be fixed. 

If you know how to test the github version of the extension, can you try removing ` "-max-print-line=200",` from `latex-workshop.latex.tools` and tell me if everything works as expected?
