### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ararunaufc** [James-Yu/LaTeX-Workshop#1196]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.0.0`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

[James-Yu.latex-workshop-unresponsive.cpuprofile.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2898172/James-Yu.latex-workshop-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jlelong** [comment]
I can't reproduce. Probably relates to some incompatible extensions, see [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions).

**Comment by ararunaufc** [comment]
I'm sorry I can't provide any more details, because this is the automatic report the VSCode instructed me to send.

I looked into the list of incompatible extensions. I have none of them installed, but I have a similar one, Code Spell Checker. Maybe this is it.

Is there anything I can do to help zero in the problem?

**Comment by jlelong** [comment]
Try to disable all extensions and see if the problem persists. Reenable extensions one by one to find the culprit... Hopefully.

Code Spell Checker is fine, I use it myself.

**Comment by maaaaadn** [comment]
same here.
The extension is suddenly lagging and CPU load is going up to 100%

I disabled everything except Latex-Workshop and tried system update and reboot, still the same behavior...

My current system:
OS:
Ubuntu 18.04.2 LTS

VSC: v 1.31.1

LatexWorkshop: v6.0.0

**Comment by jlelong** [comment]
@maaaaadn SpellRight is known to be incompatible with LaTeX Workshop, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#Known-incompatible-extensions). You can use Code Spell Checker instead.

**Comment by maaaaadn** [comment]
> @maaaaadn SpellRight is known to be incompatible with LaTeX Workshop, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#Known-incompatible-extensions). You can use Code Spell Checker instead.

I see,
strange, cause I was using both of them simultaneously for about 2 months without notable issues. Then I feel a bit sorry for issuing around on that!

thanks a lot for your answer and your effort!

**Comment by werunom** [comment]
Just to mention that I too got the warning message from vscode. This was soon after the last release. I just overlooked it. 

Havent come across this warning again. Will update here if I notice something...

**Comment by jlelong** [comment]
I close but will keep track of any new information. In particular, if new extensions are found to be incompatible, I will add them to the list on the wiki.

**Comment by werunom** [comment]
Saw the notification in vscode again about Latex extension taking more time to load. 

- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.0.0`
- OS Version: `Linux x64 4.19.24-1-MANJARO`
- VSCode version: `1.31.1`

[James-Yu.latex-workshop-unresponsive.cpuprofile.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2923996/James-Yu.latex-workshop-unresponsive.cpuprofile.txt)

If its of relevance --- when I started the vscode, the editor had only two tex files opened from last session. Since vscode loads only those extensions that are necessary, probably the other extensions were not yet actualised. In any case, here is the list of extensions installed in my instance

```
darkriszty.markdown-table-prettify
EdgardMessias.clipboard-manager
fabiospampinato.vscode-highlight
heyimfuzz.banner-comments
James-Yu.latex-workshop
kirozen.wordcounter
notZaki.pandocciter
rambit.highlight-counter
robertohuertasm.vscode-icons
streetsidesoftware.code-spell-checker
yzhang.markdown-all-in-one

```

**Comment by jlelong** [comment]
From the `cpuprofile`, most of the time is taken for simply loading the code and not executing it. Can you confirm that
1. You have installed the extension from the marketplace and that you are not using the `master` version from GitHub.
1. Your home directory is not a remote filesystem such as `nfs`.
1. You do not have a `~/node_modules/` directory.

**Comment by werunom** [comment]
Its `no` for all the three questions.
