### ISSUE TITLE
Snippets such as "@vs" can't work

### ISSUE THREAD

**Issue by allenryb** [James-Yu/LaTeX-Workshop#1197]
**Describe the bug**
Snippets such as `@ve, @vs, @vf, @vq` can't be auto-completed after hitting `TAB`.
But the following cases work well:
1. suggestions of `@ve` after hitting `ctrl+space` is right;
2. the `TAB` auto-completions of other snippets such as `@a, @r` work well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.31.1
 - Extension version: 6.0.0

**Comment by jlelong** [comment]
I can't reproduce. Snippets such as `@ve` are automatically `TAB` completed without manual triggering using `ctrl+space`. Does it happen only in a specific context?

This is mostly related to your vscode settings. Can you share your configuration with us?

**Comment by jlelong** [comment]
This culprit looks to be `editor.quickSuggestions`. I use the standard value, which is
```
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
      }
```
and everything works fine.
