### ISSUE TITLE
Problem Building with Latexmk

### ISSUE THREAD

**Issue by abstract64** [James-Yu/LaTeX-Workshop#1198]
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  --max-print-line=10000 -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="c:/Users/jhuan/Desktop/test"  "c:\Users\jhuan\Desktop\test\test.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6930 64-bit)
entering extended mode
(c:/Users/jhuan/Desktop/test/test.tex
LaTeX2e <2018-12-01>
("C:\Users\jhuan\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
("C:\Users\jhuan\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size10.clo")) (c:/Users\jhuan\Desktop\test\test.aux) [1{C:/Users/jhuan/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}])
Runaway argument?
{Subparagraph) \par Even more text. \par \section {Another section} \par \ETC.
! File ended while scanning use of \@xdblarg
! Emergency stop
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on c:/Users\jhuan\Desktop\test\test.log.
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'c:/Users/jhuan/Desktop/test/test.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets

Steps to reproduce:

Build latex project > Recipe: latexmk

**Comment by James-Yu** [comment]
Your LaTeX code has some problem

**Comment by abstract64** [comment]
Thank you! It worked. I originally thought that I hadn't installed latexmk
properly as this is my first time using the extension.

**Comment by mj05516** [comment]
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets

Hey,  I am having the same issue, My file have no errors but it does have some warnings, and those warnings are causing the compile to stop. It keeps showing to add "-f " to options of latexmk to ignore the warnings, but I don't know how to do that since I'm new to all this.

Please Help

**Comment by great-prophet** [comment]
I don't think this is the right place. My issue was that I had an error in the latex code itself. It had nothing to do with the extension.

**Comment by tamuratak** [comment]
Ask at https://tex.stackexchange.com/
