### ISSUE TITLE
Multiple documents in one window unsupported

### ISSUE THREAD

**Issue by Willian-Zhang** [James-Yu/LaTeX-Workshop#12]
### Reproduce

1. open a directory in VSCode
2. open document A
3. click `show preview` and wait after compile
4. open document B on the file panel
5. try `show preview` it or save document B
it compiles document A rather than B

**Comment by James-Yu** [comment]
LaTeX-Workshop, or rather VS Code, are designed with the concept of "project". Usually if two different PDFs should be generated, it is recommended to open two VS Code projects for ease of management.
I am not sure on multi-document support within one project. If possible, can you please give an example on the use cases?

**Comment by Willian-Zhang** [comment]
Homework,

It's actually my case of usage.

**Comment by James-Yu** [comment]
Then I would suggest opening multiple projects.

This is mainly because of the dilemma. LaTeX projects can have multiple .tex files, and only the root one can be compiled. If preview is designed to be previewing the currently opened one, it will get confused if the document is a root one or not.

**Comment by James-Yu** [comment]
BTW, you may also use "build from here" feature on different .tex root files in the same project. The default shortcut is [CTRL+L CTRL+H], or, hold down CTRL key and press L and H.
