### ISSUE TITLE
Activating Extension failed

### ISSUE THREAD

**Issue by xiaoyaoE** [James-Yu/LaTeX-Workshop#1201]
Hi.

I am sorry but I cannot exactly describe this problem. It occurs frequently in these few days.
The Latex-workshop seems stuck at some process. It is normal a few days ago.

I try to manual click the activate icon ’√‘ at the left status bar of vscode and It shows `Activating Extension...` and then re-show ’√‘ after a few second.

I try to click the extension icon of the left bar. It shows like this:
![latex-workshop](https://user-images.githubusercontent.com/12393719/53463780-e42fad00-3a82-11e9-9d31-b9778a18f4e1.png)

It seems the extension stuck when paring the structure of tex files.

My tex dir tree is as follows:
thesis.tex(root file,\input{Tex/chap1},\input{Tex/chap1}...)
--- Tex
--- --- chap1
--- --- chap2
--- --- chap3...

I try to install and reinstall the extension a few times but the problem can not solved.
If I restart the vscode and the extension works again. But it can not figure out when the problem occurs again.

*
**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - VS Code version: 1.31.1
 - Extension version: 6.0.0

**Comment by jlelong** [comment]
Please provide the extension logs available from the Command Palette _Show LaTeX Workshop messages_.

**Comment by xiaoyaoE** [comment]
Hi, jlelong.

Thanks for your reply.
The extension has been stuck and the the Command Palette _Show LaTeX Workshop messages_ do works for me.

I have no idea how to debug these problem now.

I will update this if I could get more info.

**Comment by jlelong** [comment]
Without the logs, I cannot help. I think about two things
1. Could that be related to the [node_modules issue](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#The-directory-node_modules-may-cause-errors)?
1. Have you tried completely removing the extension (ie, delete `.vscode/extensions/james-yu.latex-workshop-6.0.0`) and installing it again?

**Comment by FrancescoSaverioZuppichini** [comment]
Same problem here

**Comment by FrancescoSaverioZuppichini** [comment]
![image](https://user-images.githubusercontent.com/15908060/59208920-6d8a6b80-8baa-11e9-9e83-2391592356a5.png)

**Comment by FrancescoSaverioZuppichini** [comment]
I reinstalled vs code from scratch and still the same problem

**Comment by jlelong** [comment]
We can't do much without logs and a minimal working example to reproduce the issue.

**Comment by FrancescoSaverioZuppichini** [comment]
I cannot get the logs, the command is stuck. I really don't know what to do, the weird thing is that with another project it is working!

**Comment by FrancescoSaverioZuppichini** [comment]
@jlelong I really would like to provide a working example but I have no idea how to do so. I was working perfectly, then it stops. Maybe it is trying to loading something?

**Comment by jlelong** [comment]
Try to close the outline pane before loading the project. It seems that there is an infinite loop while scanning all the files of your project. Would mind sharing your whole project? This may be related to #1298.

**Comment by FrancescoSaverioZuppichini** [comment]
Sure :) It is my Master Thesis actually 

https://github.com/FrancescoSaverioZuppichini/Master-Thesis/tree/master/papers/Thesis

Thank you in advance

**Comment by FrancescoSaverioZuppichini** [comment]
- *Try to close the outline pane before loading the project.* Same problem

**Comment by FrancescoSaverioZuppichini** [comment]
I commented out each chapter and the problen is in chapter 4

https://github.com/FrancescoSaverioZuppichini/Master-Thesis/blob/master/papers/Thesis/tex/chapter4.tex

but I really don't understand why

**Comment by jlelong** [comment]
There is a [catastrophic backtrack](https://www.regular-expressions.info/catastrophic.html) in the regex we use to scan captions. I am on it.

**Comment by FrancescoSaverioZuppichini** [comment]
Well, mystery solved 👍 Thank you

**Comment by clsmt** [comment]
I have I believe to be the same issue here.

I am running latext vscode, with latex workshop 7.1.0. 

Everything works fine, till the extension suddenly hangs. Then after I restarted vscode, the extension can't load for the same project. Then I tried re-install the extension, doesn't work either.

It's weird that, if I restart vscode, and load another project, the extension does load. But it may fail again suddenly, then the extension remembers that the second project is also sentenced to hang. 

The above fix is released in 7.1.0 right?

**Comment by jlelong** [comment]
I cannot manage to reproduce any issue with your example even after uncommenting the last part.

**Comment by clsmt** [comment]
> I cannot manage to reproduce any issue with your example even after uncommenting the last part.

How about change the folder name to `SU(4)`, and make the file longer by duplicating from `\section{test`}` to the end?

**Comment by jlelong** [comment]
I have managed to reproduce the issue. This is again a catastrophic backtracking.
I will try to fix tonight.

**Comment by clsmt** [comment]
Thanks for fixing it. Is there any way for me to test this before it's released?

**Comment by jlelong** [comment]
@James-Yu I guess we could make a new release.

**Comment by Mark-htmlgogogo** [comment]
Almost exact same issue happened to me.

**Comment by jlelong** [comment]
@Mark-htmlgogogo please open a new issue and post the logs.
