### ISSUE TITLE
Make auto build aware of all the dependencies

### ISSUE THREAD

**Issue by xu-cheng** [James-Yu/LaTeX-Workshop#1202]
Currently, the auto build feature only works if you update the main tex source (i.e., the root tex source file). It would be nice if the real auto build can be supported. That is it will auto build if any dependency files are updated. Here are some example of such files:

*  tex file included by `\input{...}`
* custom package `.sty` or class `.cls`.
* bib file

Noted that this feature is built in `latexmk` when invoking `latexmk -pvc <main.tex>`. Alternatively, it can be done by parsing the output of `latexmk -deps` to get the list of all the dependency files and watching the changes of these files.

**Comment by Astrantia** [comment]
This already works

**Comment by xu-cheng** [comment]
> This already works

I don't think so. For example, I have to manually compile the main source file if I only update the class file `.cls`.

**Comment by Astrantia** [comment]
@xu-cheng \input{...} tex file works. Can you confirm it doesn't? I'm not sure about .sty or .cls

**Comment by xu-cheng** [comment]
\input does work. But not for these:
* .sty .cls
* .bib
* image files
* source file included by listing. 

I would suggest to use latexmk -deps to get proper dependency list.

**Comment by jlelong** [comment]
The difficulty is that files with non `.tex` extensions are not handled by the LaTeX mode of this extension. I started working on detecting any `.tex` or `.bib` dependencies, see PR #1199. 

I will try to add support for any other dependency. You can keep up with the developments directly in PR #1199.

**Comment by jlelong** [comment]
Closed by PR #1199.
