### ISSUE TITLE
[Feature Request] Add platform-specific recipes

### ISSUE THREAD

**Issue by GeeLaw** [James-Yu/LaTeX-Workshop#1203]
## Problem

I use both Windows and macOS. On Windows, I can use `texify` with no problem. On macOS, however, I need to use `bash --login -c testify ...`, because GUI programs doesn't get `PATH` added in profiles, and the only `PATH` the spawned subprocess seem to get is `/bin:/usr/bin:/sbin:/usr/sbin`, which are protected locations and cannot be written to (thus impossible to link `texify` to `/usr/bin` without turning off SIP). I use recipes like this:

```json
{
"latex-workshop.latex.recipes": [
    { "name": "Windows", "tools": ["texify-win32"] },
    { "name": "macOS", "tools": ["texify-macos"] }
],
"latex-workshop.latex.tools": [
    {
        "name": "texify-win32",
        "command": "texify",
        "args": [
            "--pdf", "--synctex", "--clean=1",
            "--tex-option=-interaction=nonstopmode",
            "--tex-option=-file-line-error",
            "%DOC%.tex"
        ],
        "env": {}
    },
    {
        "name": "texify-macos",
        "command": "bash",
        "args": [
            "--login", "-c",
            "texify --pdf --synctex=1 --clean --tex-option=-interaction=nonstopmode --tex-option=-file-line-error $0",
            "%DOC%.tex"
        ],
        "env": {}
    }
]
}
```

The problem is that I need to manually pick the recipe on one of the platforms, otherwise one of `Ctrl`/`Command`+`Alt`+`B` will complain.

## Proposed Solution

There are multiple ways:

1. Add a property to recipes that restricts the platform it is available on.
2. Allow one recipe to have different sets of tools on different platforms.
3. Add a setting that specifies the default recipes for each the platform.

## Alternatives

Use Python on both platforms. But this is highly unnecessary and inelegant.

**Comment by jlelong** [comment]
This is unlikely to be implemented as it is not in the spirit of recipes and anyway it is not the solution to your problem. To have `PATH` setup properly, there are 2 solutions

1. Set the `PATH` variable in your `rcfile`, probably `.basrhc` or `.zhsrc` and not directly in any `profile` file.
2. In `/etc/paths.d/`, create a new file containing the path you want to add to `PATH`.

You may need to logout and login for all this to be taken into account.

**Comment by GeeLaw** [comment]
I don't understand how `.bashrc` or `/etc/paths.d/` would help with the issue. Plus, editing `/etc/paths.d/` would essentially make your OS **single-user** (which is an unacceptable solution for any modern OS), even if it worked. As far as I can tell, `bash` and other shells get this in `PATH` because they call `/usr/libexec/path_helper` and process profiles/RC files.

- Windows doesn't have `bash`.
- macOS doesn't give nice `PATH` to Finder-launched processes, making the spawned processes (including `texify`) have equally bad `PATH`. The trick is to use `bash` to regain `PATH` before spawning `texify`.
- The point of this issue is to eliminate the need to use different commands.
- Moreover, it is generally a bad practice to set `PATH` in RC file, because by default RC file is processed each time a sub-shell is spawned, whereas `.profile` is only processed for log-in shells. The best practice is to use `.bash_profile` to dot-source `.bashrc` and `.profile`, and set `PATH` in `.profile`.

**Proof of `PATH` problem** If you set the recipe to

```json
{
"latex-workshop.latex.recipes": [
    {
        "name": "printenv",
        "tools": ["printenv"]
    }
],
"latex-workshop.latex.tools": [
    {
        "name": "printenv",
        "command": "printenv",
        "args": [
            "PATH"
        ],
        "env": {}
    }
]
}
```

Build a LaTeX file and see the output window for "LaTeX Compiler", you will see `/usr/bin:/bin:/usr/sbin:/sbin`. This holds even if I set `PATH` in RC file.

**Comment by tamuratak** [comment]
Please show us your `~/.profile` and `~/.bash_profile`.  Setting `PATH` in `~/.profile` works for me on macOS.

The following is the output of your recipe on my mac:
```
/Users/tamura/.cargo/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/Users/tamura/bin:/local/bin:/Users/tamura/Library/Python/3.6/bin:/opt/local/bin:/opt/local/sbin
```

**Comment by GeeLaw** [comment]
Sorry. Upon further investigation, the reason is Automator app is skipping the profile when running a shell script, which resets the `PATH` of any spawned subprocess to the default `/etc/libexec/path_helper` version. The fix would be making the Automator script call `/bin/bash --login` or otherwise restore the `PATH` before spawning Code.

Please code this issue as external.

**Comment by tamuratak** [comment]
Good. Never mind.
