### ISSUE TITLE
auto-formatter breaks pycode

### ISSUE THREAD

**Issue by Cre3per** [James-Yu/LaTeX-Workshop#1204]
**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug**
The auto-formatter formats pycode (Probably also pyconsole) environments (From pythontex). Since python is whitespace-sensitive, this breaks the code.

**To Reproduce**
1.
```
\documentclass{article}

\usepackage{pythontex}

\begin{document}
\begin{pycode}
print('hello world!')
\end{pycode}
\end{document}
```
This builds fine.

2. Format:
```
\documentclass{article}

\usepackage{pythontex}

\begin{document}
\begin{pycode}
  print('hello world!')
\end{pycode}
\end{document}
```
Causes an IndentationError, because ```print``` is indented.

**Expected behavior**
pycode environments should be ignored when formatting. Just like lstlisting does already.

**Logs**
Unrelated

<details>
<summary>LaTeX Workshop Output</summary>
```
[16:33:46] Formatting with arguments -c,-snip-,-snip-/__latexindent_temp.tex,-y=defaultIndent: '  '
[16:33:46] Formatted -snip-/test.tex
```
</details>

**Desktop (please complete the following information):**
 - OS: Debian testing buster
 - VS Code version: 1.31.1
 - Extension version: 6.0.0

**Comment by jlelong** [comment]
LW uses `latex_indent.pl` to indent `.tex` files. Please refer to [latex_indent manual](http://ctan.tetaneutral.net/support/latexindent/documentation/latexindent.pdf) and in particular look up `verbatimEnvironments`.
