### ISSUE TITLE
Unable to install in Visual Studio 2017

### ISSUE THREAD

**Issue by darshanmshsha** [James-Yu/LaTeX-Workshop#1205]
It is failed to install in Visual Studio 2017. Attached error details.   

![latexworkshp_installationerror_in vs 2017](https://user-images.githubusercontent.com/7643979/53579669-fcb5cb00-3b47-11e9-8392-0bca301ab8d4.png)

**Comment by Bno93** [comment]
@darshanmshsha Hi,
You try to install a Visual Studio Code Extension in Visual Studio...
