### ISSUE TITLE
Highlight footnote text

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1208]
**Is your feature request related to a problem? Please describe.**
In humanities academic paper (and probably in sciences too), often in the middle of a big paragraph, there are several footnotes, each being quite lengthy. In the latex file, this kind of writing ends up being huge chunk of textbody (the main paragraph, along with several footnotes) where it becomes difficult to visually distinguish the main text from the text of footnotes. 

**Describe the solution you'd like**
Given this, would be possible to give a particular syntax highlighting for footnote text? 

**Describe alternatives you've considered**
I thought of custom defining it in my `settings.json` for latex files by providing syntax color for `support.function.general.tex`. But this did not highlight the colour of the text withing the braces; merely the colour of the `footnote` changed. 

**Additional context**
No

**Comment by jlelong** [comment]
This is not easy as we have stopped capturing `{...}` since 
 c10ca0c as it was causing too many issues with unbalanced expressions. However, there are a few exceptions to this rule and I will investigate if we can add one more for `\footnote`.

**Comment by jlelong** [comment]
I have just had a closer look and good news the content of the footnote is already captured. The scope used to be `meta.footnote.latex` and I have just changed it for `entity.name.footnote.latex`.

**Comment by werunom** [comment]
Thanks for working on this! 

So, when the release is made, I just need to assign a syntax colour for `entity.name.footnote.latex` in `settings.json`...right?

**Comment by jlelong** [comment]
Yes and meanwhile you can assign a colour to `meta.footnote.latex`.

**Comment by werunom** [comment]
Just tried with `meta.footnote.latex`; but nothing happened with it --- the footnote text was as it is. To reiterate, I added the below `textMateRules` under `editor.tokenColorCustomizations`

```
                 {
                     "scope": "meta.footnote.latex",
                     "settings":{
                         //"foreground": "#af9d00",
                         "fontStyle": "bold"
                     },                    
                 }
```
In any case, will wait for the release to see the changes...

**Comment by jlelong** [comment]
It works with the following
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "meta.footnote.latex",
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    }
```
Depending on the font you use, the `fontStyle` attribute may not work. For instance, on macOS, the `monaco` font does not have a bold variant.

**Comment by werunom** [comment]
My bad; I had written `\foonote` instead of "foot..." :)
