### ISSUE TITLE
Excluding some files in "clean up auxiliary files"

### ISSUE THREAD

**Issue by tamuhey** [James-Yu/LaTeX-Workshop#1209]
Thanks for this great extension!

I want to use "clean up auxiliary files" with configuring to exclude some files.
Is there any way to do that?

**Comment by jlelong** [comment]
Unfortunately no. You can only configure the extensions to remove in `latex-workshop.latex.clean.fileTypes` and if it is done recursively `latex-workshop.latex.clean.subfolder.enabled`. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#cleaning-generated-files).
