### ISSUE TITLE
Minor issue with autocompletion of reference

### ISSUE THREAD

**Issue by angan06** [James-Yu/LaTeX-Workshop#121]
Dear James, 

When I want to use the auto-completion with a reference, for instance:  \ref{s:Title section}, 
I usually start writing "\ref{s:T " then select my reference in the list appearing and press enter. 

However, when doing like that, code studio completes by \ref{s: s:Title section}. I guess that it is an issue with the " : ".  
Is there a workaround that allow to keep the same notation for my reference ?

Best regards.

**Comment by James-Yu** [comment]
This should be an upstream problem with vscode. The extension cannot control or modify the intellisense behavior. I suppose the only "workaround" is to avoid using characters that has special meanings, e.g., `,.:'`. Or just type `\ref{sT` for the said entry.

Hope that can answer your question. Sorry no solution we can add to the extension.

**Comment by angan06** [comment]
Thanks for the answer.
