### ISSUE TITLE
File path in diagnostics is broken when the path contains umlauts

### ISSUE THREAD

**Issue by lrabe** [James-Yu/LaTeX-Workshop#1211]
**Expected behavior:** When clicking a diagnostic entry in the "Problems" tab, the editor should jump to the indicated location in the file. 

**Actual behavior:** The editor fails to open the file if the path contains a German umlaut (e.g. ö, ü, ä). The behavior also differs between LaTeX errors and linter warnings: When clicking a LaTeX error, everything after the umlaut is removed from the path. When clicking a linter warning, the umlaut is replaced by a question mark symbol. 

**Example:**

![vscode_edit](https://user-images.githubusercontent.com/9059119/53758845-2d3a9380-3ebf-11e9-87ba-7a421a5dce10.jpg)

I suspect that this might be related to the following lines: 
https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/parser.ts#L281
https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/parser.ts#L228

- OS: Windows 10
- VS Code version: 1.31.1
- Extension version: 6.0.0

**Comment by jlelong** [comment]
The truncation issue is fixed for LaTeX errors.

> When clicking a linter warning, the umlaut is replaced by a question mark symbol.

This is an encoding issue. vscode expects uft8 encoded paths whereas it is probably not your default system encoding.

**Comment by lrabe** [comment]
@jlelong Thanks. Could you explain what you mean by the "default system encoding"?
I've never had an issue like this in any other program, so I'm not sure if this really is the case. 

The only related setting I could find is the following (which is unchecked by default).

![](https://i.imgur.com/WvUmZIB.png)

**Comment by jlelong** [comment]
I don't use Windows so I am afraid I cannot help much but it seems that Windows uses `UTF-16` for filename encoding and not `UTF-8`. Maybe other users can help...

**Comment by tamuratak** [comment]
Please show us log messages.  Tell us which TeX distribution you are using. Which LaTeX engine and linter. Exact versions of all these programs.

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

Thank you for your cooperation.

**Comment by lrabe** [comment]
Sure, here you go: 

<details>
<summary>LaTeX Workshop Output</summary>
[14:36:58] Initializing LaTeX Workshop.
[14:36:58] Creating LaTeX Workshop http and websocket server.
[14:36:58] LaTeX Workshop initialized.
[14:36:58] Linter for root file started.
[14:37:00] Server created on 127.0.0.1:56610
[14:37:00] Snippet data loaded.
[14:37:00] LaTeX Workshop version: 6.1.0
[14:37:00] Try root file in root directory: d:\Lukas\Documents\Persönliche Dokumente\mydocument.tex
[14:39:57] LOG command invoked.
</details>

<details>
<summary>LaTeX compiler log</summary>
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'd:/Lukas/Documents/Pers�nliche Dokumente/mydocument.tex'
      'mydocument.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="d:/Lukas/Documents/Pers�nliche Dokumente"  "d:\Lukas\Documents\Pers�nliche Dokumente\mydocument.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.tex
LaTeX2e <2018-12-01>
(d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncv.cls
Document Class: moderncv 2015/07/28 v2.0.0 modern curriculum vitae and letter document class
(d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/base/size11.clo) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/etoolbox/etoolbox.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/base/ifthen.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/xcolor/xcolor.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics-cfg/color.cfg) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics-def/pdftex.def) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/colortbl/colortbl.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/tools/array.sty))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/ifxetex/ifxetex.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/oberdiek/ifluatex.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/base/fontenc.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/base/t1enc.def)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/lmodern.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/url/url.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics/graphicx.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics/keyval.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics/graphics.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics/trig.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/graphics-cfg/graphics.cfg))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/tweaklist.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/tools/calc.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/l3packages/xparse/xparse.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/l3kernel/expl3.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/l3kernel/expl3-code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/l3kernel/l3pdfmode.def))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/microtype/microtype.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/microtype/microtype-pdftex.def) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/microtype/microtype.cfg)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncvcollection.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncvcompatibility.sty)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/base/inputenc.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/geometry/geometry.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/oberdiek/ifpdf.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/oberdiek/ifvtex.sty)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/babel/babel.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/babel/switch.def) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/babel-german/ngerman.ldf (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/babel-german/ngermanb.ldf (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/babel/babel.def (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/babel/txtbabel.def))))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/csquotes/csquotes.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/csquotes/csquotes.def) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/csquotes/csquotes.cfg)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/relsize/relsize.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncvstyleclassic.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncviconsmarvosym.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/ms/everyshi.sty)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/pgf.revision.tex))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-pdftex.def (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/utilities/pgffor.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/pgf/math/pgfmath.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex)
(d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex)))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncvheadi.sty

LaTeX Warning: You have requested package `moderncvheadi',
               but the package provides `moderncvheadi'.

) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncvbodyi.sty

LaTeX Warning: You have requested package `moderncvbodyi',
               but the package provides `moderncvbodyi'.

(d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/marvosym/umvs.fd))) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/moderncv/moderncvcolorblue.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/hyperref/hyperref.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/oberdiek/auxhook.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/oberdiek/kvoptions.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/hyperref/pd1enc.def) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/latexconfig/hyperref.cfg) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/hyperref/puenc.def)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/hyperref/hpdftex.def (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)) (d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.aux) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/t1lmr.fd) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/oberdiek/grfext.sty) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg)) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/microtype/mt-cmr.cfg) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/t1lmss.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
ABD: EveryShipout initializing macros (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/hyperref/nameref.sty (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/generic/oberdiek/gettitlestring.sty)) (d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.out) (d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.out) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/ot1lmr.fd) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/omllmm.fd) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/omslmsy.fd) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/lm/omxlmex.fd) (d:/Program Files (x86)/texlive/2018/texmf-dist/tex/latex/microtype/mt-mvs.cfg)
Underfull \hbox (badness 10000) in paragraph at lines 34--34

[1{d:/Program Files (x86)/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] [2 <d:/Lukas/Documents/Pers�nliche Dokumente/image.png>] (d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.aux) )
(see the transcript file for additional information){d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/enc/dvips/lm/lm-ec.enc}<d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/type1/public/lm/lmss10.pfb><d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/type1/public/lm/lmss12.pfb><d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/type1/public/lm/lmss17.pfb><d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/type1/public/lm/lmssbx10.pfb><d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/type1/public/lm/lmsso10.pfb><d:/Program Files (x86)/texlive/2018/texmf-dist/fonts/type1/public/marvosym/marvosym.pfb>
Output written on "d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.pdf" (2 pages, 179909 bytes).
SyncTeX written on d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.synctex.gz.
Transcript written on "d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.log".
Latexmk: Log file says output to 'mydocument.pdf'
=== TeX engine is 'pdfTeX'
Latexmk: All targets (d:/Lukas/Documents/Pers�nliche Dokumente/mydocument.pdf) are up-to-date
</details>

- Latex: pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX)
- Linter: ChkTeX v1.7.6

Anything else you need to know?

**Comment by lrabe** [comment]
After reading through https://tug.org/pipermail/tex-live/2014-July/035646.html it seems that this is a bug in TeX Live that only affects Windows.

**Comment by tamuratak** [comment]
What is the character encoding of your TeX file?

<img width="1125" alt="スクリーンショット 2019-03-11 10 56 03" src="https://user-images.githubusercontent.com/10665499/54095953-10391f80-43ed-11e9-9c08-ab674df22915.png">

**Comment by lrabe** [comment]
Also UTF-8:

![](https://i.imgur.com/68X3czt.png)

**Comment by tamuratak** [comment]
The cause is that the encoding of the output message of pdflatex is not utf-8. Latin-1? If you use xelatex and xdvipdfmx, this problem may be solved, I guess.
I cannot find other solutions.

I find a newer [thread](https://tug.org/pipermail/tex-live/2018-May/thread.html#41669) on filenames in the TeX Live maling list.  

I hope the transition to utf-8 in TeX Live will be complete in the near future.

**Comment by lrabe** [comment]
I already tried lualatex and xelatex without success. I can check xdvipdfmx if that changes anything. 
I'll read through the thread later.

**Comment by jlelong** [comment]
I just want to point out that the encoding issue is happening with `chktex`.

**Comment by tamuratak** [comment]
@jlelong, I missed that point.
