### ISSUE TITLE
6.1.0 breaks docker usage

### ISSUE THREAD

**Issue by padok** [James-Yu/LaTeX-Workshop#1212]
**Describe the bug**
Just updated to version 6.1.0 and the extension doesn't work anymore. 
The console output of the developer options looks as follows 
```
Activating extension 'James-Yu.latex-workshop' failed: Command failed: pdflatex --version
/bin/sh: pdflatex: command not found
```
Since I use latex workshop exclusively with docker I did not install any latex packages and therefore `pdflatex` is missing as well.

**To Reproduce**
1. Uninstall any latex packages including `pdflatex`
2. Install VS Code and Latex-Workshop version 6.1.0
3. Extension failes to load

**Expected behavior**
The extension should handle missing binarys like `pdflatex` like the previous version

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.0.0-arch1-1-ARCH)
 - VS Code version: 1.31.1
 - Extension version: 6.1.0

**Workaround**
In the Extension tab at latex workshop open the gear menu and under "Install Another Version..." select the extension version `6.0.0`. After reloading vs code the extension works again.

----
Thanks a lot for the great extension!

**Comment by James-Yu** [comment]
@jlelong Shall we have a fallback mechanism for this?
