### ISSUE TITLE
Inconsistency in bibtex command using BIBINPUTS

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#1214]
### Issue
This issue is a follow up of issue #1044 .

Environment: 
- MacOS 10.14.3
- VSCode 1.31.1
- LaTeX Workshop 6.1.0

After set the environment variable`BIBINPUTS`, `echo $BIBINPUTS` returns the correct directory in Mac terminal and VSCode bash terminal (assuming `~/.bash_profile` has BIBINPUTS defined).

Then, run `bibtex %DOCFILE%` command (for example `bibtex main`) in Mac terminal or VSCode bash terminal will give the correct output .bbl file.

However, when running latex-workshop recipes containing bibtex (bibtex defined in `latex-workshop.latex.tools` by default). It cannot find the .bib file.

My guess is latex-workshop recipes do not read user defined environment variables in `~/.bash_profile` and both Mac terminal and VSCode bash terminal recognize those variables.

### My Solution
Redefined `"latex-workshop.latex.tools"`, modify bibtex to
```
{
        "name": "bibtex",
        "command": "bibtex",
        "args": [
            "%DOCFILE%"
        ],
        "env": {
            "BIBINPUTS": "your_bib_dir"
        }
}
```
After this, latex-workshop toole bibtex will find the correct bib file under "your_bib_dir".

**Comment by tamuratak** [comment]
Please show us your `~/.profile` and `~/.bash_profile`.  Make sure also that your login shell is bash. See [link](https://superuser.com/questions/362372/how-to-change-the-login-shell-on-mac-os-x-from-bash-to-zsh#363555).

After editing  `~/.bash_profile`, you have to reboot your Mac.

**Comment by jlelong** [comment]
> After editing ~/.bash_profile, you have to reboot your Mac.

Logging out of your user session and then logging in should be enough.

**Comment by ShuCaiMonkaS** [comment]
Thank, logging out is enough.
