### ISSUE TITLE
keyboard shortcut problem (maybe the problem is me)

### ISSUE THREAD

**Issue by maaaaadn** [James-Yu/LaTeX-Workshop#1215]
just a very quick issue, 
since LatexWorkshop is not recognizing changes in figure files I have to manually build the project repeatedly (no critics, I love the plugin anyhow). 

But I am not able to trigger a build using the keyboard shortcut CTRL+L, ALT+B as you see in the attached screenshot.

![vscode_shortcut](https://user-images.githubusercontent.com/4591716/53946708-97705580-40c4-11e9-91ed-b096e61384ca.png)

Currently I don't see what I'm doing wrong and would be thankful if someone could tell me.

**Comment by jlelong** [comment]
> since LatexWorkshop is not recognizing changes in figure files I have to manually build the project repeatedly (no critics, I love the plugin anyhow).

This will be solved by PR #1190. I still need a bit of time before merging it.

> But I am not able to trigger a build using the keyboard shortcut `CTRL+L`, `ALT+B` as you see in the attached screenshot.

The standard shortcut for building is `ctrl+alt+b`. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#building-the-document) and [there](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#I-cannot-use-ctrlalt-in-a-shortcut) for more details on shortcuts.

**Comment by Orkim3355hart0336** [comment]
Same here and no fix yet.

**Comment by jlelong** [comment]
@Orkim3355hart0336 Please open a new issue and fill the template if you want to report a problem.
