### ISSUE TITLE
Hover over equation doesn't work

### ISSUE THREAD

**Issue by rpkvt** [James-Yu/LaTeX-Workshop#1216]
Hello,
When I first started my paper the hover over equation worked and it was a feature that I really enjoyed. Somehow, something changed and now all it says is "Loading.....".

![image](https://user-images.githubusercontent.com/33731793/53965784-1cbe2f00-40f2-11e9-8f71-3b6ba7338b04.png)

The other previews still seem to work. Here's a citation:
![image](https://user-images.githubusercontent.com/33731793/53965860-411a0b80-40f2-11e9-8d0a-b5e9031b358c.png)

The only errors I found when I hover over the equation are these:

![image](https://user-images.githubusercontent.com/33731793/53965904-5858f900-40f2-11e9-8a7b-b9c1b1918ae4.png)

However, the script compiles into a PDF OK so I don't think there's a missing brace somewhere. I did try removing most of the code and Is till had the same issue.  Any help is appreciated.

Thanks,
Rich

**Comment by jlelong** [comment]
I cannot reproduce the issue, so please provide a minimal example.

**Comment by rpkvt** [comment]
I was working off an IEEE template and I think I've narrowed it down to one line, which I have commented out below. Even commented out, it seems to break the feature. If I delete the return and make it one line, the problem disapears.

\documentclass[12pt]{article}
%This thing seems to be the issue... 
%\def\BibTeX{{\rm B\kern-.05em{\sc i\kern-.025em b}\kern-.08em
%    T\kern-.1667em\lower.7ex\hbox{E}\kern-.125emX}}


\begin{document}
Hello world!
$Hello world!$ %math mode 

\begin{equation}
    \delta_k=\sigma_y
\end{equation}

\end{document}

![image](https://user-images.githubusercontent.com/33731793/54017227-a3701c00-4185-11e9-8407-42a5bab3a016.png)

\documentclass[12pt]{article}
%This thing seems to be the issue... 
%\def\BibTeX{{\rm B\kern-.05em{\sc i\kern-.025em b}\kern-.08em T\kern-.1667em\lower.7ex\hbox{E}\kern-.125emX}}


\begin{document}
Hello world!
$Hello world!$ %math mode 

\begin{equation}
    \delta_k=\sigma_y
\end{equation}

\end{document}

![image](https://user-images.githubusercontent.com/33731793/54017252-b7b41900-4185-11e9-8df2-fd536ee7db6c.png)

Removing that line altogether also fixes it.

**Comment by jlelong** [comment]
New commands and definitions are injected into `mathjax` to build preview so they have to be valid definitions and because of parsing restrictions, the complete command must be on a single line.

Commented lines are now ignored.

**Comment by rpkvt** [comment]
Ah, gotcha. Thanks for looking into this.
