### ISSUE TITLE
Redefining math command messes up syntax highlighting

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1221]
I think this image sums up the issue quite effectively.

![output_BhUIpF](https://user-images.githubusercontent.com/20903656/54079642-39897b00-431b-11e9-9512-dadf2ccf649c.gif)

This isn't a major problem for me, and I could imagine this being more trouble than it's worth, but if it is easy to fix that would be nice :)

Here some stuff to copy and paste for your convenience

```tex
\documentclass{article}

\title{Title}
\author{author}

\usepackage{eltoolbox}
\renewrobustcmd{\(}{test}


\begin{document}

\maketitle

\end{document}
```

**Comment by jlelong** [comment]
I could quite easily fix the issue for the line `\renewrobustcmd` but there is no way to take into account that further uses of `\(` do not start math mode.

**Comment by tecosaur** [comment]
I'm not sure what you mean by 'further uses' do you mean after `\renewrobustcmd{\(}{...` `\(` won't work as it should?

Given you said it could be fixed quiet easily for `\renewrobustcmd` would it be worth going through the common definition commands and applying that fix? It's just a tad annoying when half my document is highlighted differetly. Once again not a deal breaker though.

**Comment by jlelong** [comment]
I mean that `\renewrobustcmd{\(}{...` will not change the syntax highlighting for `\(`. So `\(` will be interpreted the syntax highlighter as the beginning of math mode, which should not be as far as I understand.

**Comment by jlelong** [comment]
Does it help?

**Comment by tecosaur** [comment]
Seems to work in `.tex` files but not for `.cls` files (I did set up a language association). Given it **does** work for `.tex` filkes I think that's an issue my end though.

Thanks!

![image](https://user-images.githubusercontent.com/20903656/54097066-76bc3e80-43e9-11e9-90a7-e50885c00f20.png)
![image](https://user-images.githubusercontent.com/20903656/54097078-8176d380-43e9-11e9-9118-1d7c36bcc028.png)

**Comment by jlelong** [comment]
In your second screenshot, the problem comes from the `$` sign and unfortunately there is not much we can do about it. In `\renewrobustcmd{...}{...}` we do not match the second pair `{...}`because it would require to match opening and closing pairs of braces over the whole document, which causes far too much trouble.

The only I can think of that could help when the whole `\renewrobustcmd{...}{...}` is on a **single** line is to use the following regex `\\renewrobustcmd{([^}]*)}(.*)$` and only highlight macros in the second group. It would not change the current behaviour when writing
```
\renewrobustcmd{...}{%
   ...
}
```
but would really help in your situation to keep a consistent syntax highlighting over the reste of the document.

**Comment by tecosaur** [comment]
That could be good, I'm just trying to keep wary of changing things that fix my use case but may make things generally less robust etc. 
In my particular case though that could be helpful since I've got a good few hundred lines after that point.

I'll defer to your better judgement.

**Comment by tecosaur** [comment]
Re: my particular situation it's much better now thanks to defining another command with `$` in it.

![image](https://user-images.githubusercontent.com/20903656/54122911-561bd500-4439-11e9-8451-5fedff9ea3b6.png)

**Comment by jlelong** [comment]
@tecosaur for the moment I will just keep things as they are concerning the highlighting of `\newcomands` & co. Playing with the syntax file often comes with quite many side effects...
