### ISSUE TITLE
Vscode 1.32 already uses Ctrl+L

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1222]
A few releases back, we introduced many new keybindings all starting with `Ctrl+L`. Since vscode 1.32, `Ctrl+L` is used to expand line selection, see [here](https://code.visualstudio.com/updates/v1_32#_default-keybinding-change-for-expandlineselection).

This means that in LaTeX mode, there is no shortcut for expanding line selection. 
Vote +1 if you feel this a major issue and we should pick up a new chord leader.

**Comment by tecosaur** [comment]
This may prove useful

### VSCode <kbd>Ctrl</kbd>+<kbd>&nbsp;</kbd> shortcuts
| <kbd>Ctrl</kbd>+<kbd>&nbsp;</kbd> | (Main) Action |
|---|---|
| <kbd>A</kbd> | `editor.action.selectAll` |
| <kbd>B</kbd> | `workbench.action.toggleSidebarVisibility` |
| <kbd>C</kbd> | `editor.action.clipboardCopyAction` |
| <kbd>D</kbd> | `editor.action.addSelectionToNextFindMatch` |
| <kbd>E</kbd> | `workbench.action.quickOpen` |
| <kbd>F</kbd> | `actions.find` |
| <kbd>G</kbd> | `workbench.action.gotoLine` |
| <kbd>H</kbd> | `editor.action.startFindReplaceAction` |
| <kbd>I</kbd> | **AVAILABLE for ^1.32** |
| <kbd>J</kbd> | `workbench.action.togglePanel`|
| <kbd>K</kbd> | Chord |
| <kbd>L</kbd> | `expandLineSelection` |
| <kbd>M</kbd> | `editor.action.toggleTabFocusMode` |
| <kbd>N</kbd> | `workbench.action.files.newUntitledFile` |
| <kbd>O</kbd> | `workbench.action.files.openFile` |
| <kbd>P</kbd> | `workbench.action.quickOpen` |
| <kbd>Q</kbd> | `workbench.action.quit` |
| <kbd>R</kbd> | `workbench.action.openRecent` |
| <kbd>S</kbd> | `workbench.action.files.save` |
| <kbd>T</kbd> | `workbench.action.showAllSymbols` |
| <kbd>U</kbd> | `cursorUndo` |
| <kbd>V</kbd> | `editor.action.clipboardPasteAction` |
| <kbd>W</kbd> | `workbench.action.closeWindow` |
| <kbd>X</kbd> | `editor.action.clipboardCutAction` |
| <kbd>Y</kbd> | `redo` |
| <kbd>Z</kbd> | `undo` |

**Comment by jlelong** [comment]
@tecosaur I have edited your previous to add some more (*). Hope you won't mind.

More seriously, I think we could get away with by simply defining a new keybinding `Ctrl+L` `Ctrl+L` for `expandLineSelection`. This approach will not disrupt people already used to our `Ctrl+L` keybindings, and no need to differentiate between vscode's version.

**Comment by tecosaur** [comment]
I don't mind in the slightest :)
What you have done with `Ctrl+L` `Ctrl+L` seems to be the best solution. VSCode seems to like the idea of gobbling up all the available simple keybindings.

Further to this, perhaps we should do the same with `Ctrl+M` (currently used for math snippets)
