### ISSUE TITLE
Two different keybindings for "View in external viewer" and "View in VSCode tab" 

### ISSUE THREAD

**Issue by kenNash** [James-Yu/LaTeX-Workshop#1223]

**Comment by tecosaur** [comment]
They are two different things, I fail to see the issue...

**Comment by kenNash** [comment]
Hi all!

Second day for me with VSC, so... maybe the question is silly. (I apologise for that.)

Can I assign two different keybindings, say alt-cmd-v and ctrl-cmd-v, for "View in external viewer" and "View in VSCode tab" respectively?

If yes, how?

Many thanks in advance for any help.
--
kN

**Comment by kenNash** [comment]
> On 10 Mar 2019, at 17:01, tecosaur <notifications@github.com> wrote:
> 
> They are two different things, I fail to see the issue...
> 


Thank you for your response, tecosaur.

I’m so sorry for such a silly question. Actually this is my second day on VSC, and I’m trying to figure out how to assign two different keybindings, say alt-cmd-v and ctrl-cmd-v, for "View in external viewer" and "View in VSCode tab” respectively.

I tried

// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+cmd+v",
        "mac": "ctrl+cmd+v",
        "command": "latex-workshop.view",
        "args": {
            "arguments": ["external"]
        },
        "when": "editorTextFocus && !latex-workshop:altkeymap"
    },
]

in my keybindings,json, but it doesn’t work.

I’m trying to read the (huge) documentation available, but I've not found my way yet.

Any help would be immensely appreciated.

—
kN

**Comment by jlelong** [comment]
See [vscode's documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_customizing-shortcuts).

By the way, there is an alternate keybinding for "View in VScode tab" if you have trouble with `Ctrl+Alt`: see [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-use-ctrlalt-in-a-shortcut).

**Comment by kenNash** [comment]
> On 10 Mar 2019, at 20:25, Jerome Lelong <notifications@github.com> wrote:
> 
> See vscode's documentation <https://code.visualstudio.com/docs/getstarted/keybindings#_customizing-shortcuts>.
> 
> By the way, there is an alternate keybinding for "View in VScode tab" if you have trouble with Ctrl+Alt: see here <https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-use-ctrlalt-in-a-shortcut>.
> 
> 


Thank you Jerome.

My problem actually is how to pass an argument to a command.
I tried the following syntax, but apparently it doesn’t work.

// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+cmd+v",
        "mac": "ctrl+cmd+v",
        "command": "latex-workshop.view",
        "args": {
            "arguments": ["external"]
        },
        "when": "editorTextFocus && !latex-workshop:altkeymap"
    },
]


Cheers.
—
kN

**Comment by jlelong** [comment]
This is not possible to pass arguments to keybindings.

**Comment by kenNash** [comment]
> On 10 Mar 2019, at 21:13, Jerome Lelong <notifications@github.com> wrote:
> 
> This is not possible to pass arguments to keybindings.
> 

I’m not sure the problem is this.

As far as I can undestand, “view in tab” and “view in external viewer” are the same command, latex-workshop.view, referring the status of latex-workshop.view.pdf.viewer.
Then:
• if latex-workshop.view.pdf.viewer = “tab”, then “view in tab” is issued;
• if latex-workshop.view.pdf.viewer = “external”, then “view in external viewer” is issued.

So one solution could be the definition of two new commands, say latex-workshop.view.tab and latex-workshop.view.ext such that each of them
1. sets latex-workshop.view.pdf.viewer to be “tab” or “external”, respectively,
2. runs latex-workshop.view.

Do you agree?

Thank you so much for your help.
—
silvio
