### ISSUE TITLE
is it possible to use the ext without Latex installed?

### ISSUE THREAD

**Issue by lonelykid** [James-Yu/LaTeX-Workshop#1225]
**Is your feature request related to a problem? Please describe.**
I don't feel like installing Latex on my computer since it's huge. But it's possible for me to write a script to build remotely. I just need autocomplete, highlighting and pdfview with synctex. Do these features indeed require a latex installation?

synctex is built in. pdf viewer is built in. It seems a lot can be done without latex installation.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by James-Yu** [comment]
No. Otherwise this extension will be at least 2GB large. If you want small TeX distribution, try MikTeX on all platform or TinyTeX afaik on Mac.
