### ISSUE TITLE
allow file-relative path completion for \input and add \subimport to path-completion

### ISSUE THREAD

**Issue by stakaz** [James-Yu/LaTeX-Workshop#1227]
Hello, I wounder if it could be possible to have an option on how to complete paths in commands like `\include`, `\input` and `\import`. In particular I would like to have paths relative to the file and not the root of the project as my figures and tables are located per-file wise. Currently it is inconsistent anyway as I get the file-relative path for `\include` but root-relative for `\includegraphics` and  `\input`.

In this context it would also be great to have completion of paths for `\subimport` and the other commands from this family.

**Comment by jlelong** [comment]
I agree the current behaviour is not consistent. 
To make it clear, file completion for `\include`, `\input` and `\includegraphics` should be root-relative by default, except when these commands are used inside an `\import` or `\subimport` file, in which case file completion should be relative to the current file directory. 

To be complete, the `import` package also defines : `\inputfrom`, `\subinputfrom`, `\includefrom`, `\subincludefrom` and their `*` variants.

The completion for `\includegraphics` is a bit more delicate as we should also take into account paths defined by `\graphicspath`, see  #1237.

I will work on this and make a PR in due course and keep this post updated.

**Comment by jlelong** [comment]
New entry in the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#files)
