### ISSUE TITLE
Non-existing file in fls causing trouble in auto build

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#1228]
**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug**
Sometimes, `.fls` file includes non-existing files due to unknown bug, e.g., `INPUT c:\some\path\to\project\nul:.tex`. This will throw a promise rejection and prevent all dependencies being watched.

**To Reproduce**
1. Add a line like above to the `.fls` file manually
2. Open the project, make some edits, save, nothing happened

**Expected behavior**
As described above

**Logs**
Not related, as logs are suppressed by the rejection.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.23.1
 - Extension version: 6.2.0

**Additional context**

**Comment by James-Yu** [comment]
I'm working on it. An `existSync` check should be enough.

**Comment by James-Yu** [comment]
@jlelong Off-topic chat. I noticed the use of `micromatch`. Is it better than the current `glob`? If so, may we switch all `import glob` to `micromatch` and make other related changes?

**Comment by jlelong** [comment]
The `glob` module aims at providing the list of files matching a given glob pattern. For the matching part, it uses `minimatch` internally. The `micromatch` module basically takes an array of strings and an array of patterns and return the matches. The documentation of `micromatch` says : "Highly optimized wildcard and glob matching library. Faster, drop-in replacement to minimatch and multimatch." The main advantage of `micormatch` over `minimatch` it supports arrays of glob patterns.

I do not think `glob` can be replaced by `micromatch` as it would require running something like `ls ** | micromatch...`.
