### ISSUE TITLE
footnote syntax highlighting in minimap

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1229]
**Describe the bug**

This bug is related to the [feature request 1208](https://github.com/James-Yu/LaTeX-Workshop/issues/1208) - where I had requested to provide a `scope` for footnote so that the users can provide a synatx colour for visual distinction. As a solution, the scope of footnote was changed from `meta.footnote.latex` to `entity.name.footnote.latex`.

However, with this new scope, the syntax colour of footnotes are no longer visible in minimap. This was not the case before with `meta.footnote.latex` --- the syntax colour of the footnotes were visible both in the main editor and the minimap.

When the main editor and minimap looks similar (with similar syntax highlighting), visual grepping in long documents becomes easier. For instance, the syntax colours of other commands (like `\cite{}`, `\textit{}`, etc. are visible both in the editor and minimap. Any mismatch creates dissonance. 

Is there any workaround for overcoming this?

**Comment by jlelong** [comment]
I cannot reproduce the issue. I use the _One Monokai_ theme and the footnotes are similarly highlighted in the editor and in the minimap using the color defined by `entity.name.footnote.latex`. 

I guess the problem is related to the theme you use.

**Comment by werunom** [comment]
you are right --- the colour I had assigned was not suitable for the theme I was using. I changed the value slightly and now its fine. 

Thanks for the help!
