### ISSUE TITLE
SyncTeX with CTRL+Click

### ISSUE THREAD

**Issue by rscircus** [James-Yu/LaTeX-Workshop#123]
First of all, @James-Yu, thank you for this awesome extension. :blush:

I have an issue, when `CTRL+Left-Clicking` into my *.tex document while having the pdf open in a `new tab`. Basically, SyncTeX doesn't work in this way (Forward?). However, it does, when `CTRL+Left-Clicking` into the pdf document. Is it possible to add this? I tried via the keyboard mappings, but they don't allow me to add click events.

Best,
R

**Comment by jose-a-sa** [comment]
@rscircus  u have to assign a key shortcut to the command `latex-workshop.synctex` and then TEX->PDF synctex will be easier for you. Synctex is working both sides. Other way you can do this is mouse right-click and the `SyncTeX from cursor`.

**Comment by rscircus** [comment]
Thanks. Right-click is good enough.
