### ISSUE TITLE
Save scroll position for preview

### ISSUE THREAD

**Issue by jplatte** [James-Yu/LaTeX-Workshop#1232]
In long documents, it is annoying to have to scroll back to the position you were edition after closing and re-opening the preview / the whole editor / your OS. It would be nice if the scroll position of a document could be persisted.

**Comment by jcyap4** [comment]
It is such a hassle to scroll back to where you last edit especially in long document. The preview should behave like texstudio where it brings you to where you last edit after building it.

**Comment by ngyeatjeng** [comment]
Agree, I would prefer that the viewer behaves similarly like TeXstudio, where the viewer automatically scrolls to the line corresponding to the cursor in the editor.

**Comment by jlelong** [comment]
@ngyeatjeng see  #379.

@jcyap4 you can use vscode's command _Go to Last Edit Location_ and then call _Synctex from cursor_.
