### ISSUE TITLE
Save Without Building

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1234]
I'll give the template a shot for a change :stuck_out_tongue: 

**Is your feature request related to a problem? Please describe.**
I find it vaguely frustrating that there is no way to save without building, as a one of thing. 

E.g. I may usualy want to build on save, and so have the settings file appropriately configued, but be in the middle of writing a macro and have to get up, and in such a situation
 - I want to save the file
 - without building
 - and changing the autobuild setting would not be appropriate

**Describe the solution you'd like**
An equivalent to `Save Without Formatting` (`Save Without Building`) would be nice, with an associated shortcut (perhaps `ctrl`+`K`+`shift`+`S`)

**Comment by jlelong** [comment]
`Save Without Formatting` is provide by vscode itself not by the extension. The difficulty is that the build is triggered by a file watcher and I cannot see how it can be bypassed.
I will think of it a bit to see if I can come up with a simple solution.

**Comment by jlelong** [comment]
It was actually easier than I thought. Search for `Save without Building` in the _Command Palette_. You can assign your own shortcut using the _Keyboard Shortcuts Preferences_.

**Comment by tecosaur** [comment]
Thanks @jlelong :smiley:
