### ISSUE TITLE
Choice to compile current file vs project

### ISSUE THREAD

**Issue by a5a** [James-Yu/LaTeX-Workshop#1236]
I am writing a larger text with multiple chapters, each of which takes a significant time to compile. When writing, it would be sufficient to compile the currently-open .tex file, rather than the complete project.

I would like to see two build commands -- one for the project (as is already implemented) and one for the currently-open file. Making a file compilable on its own, as well as via the project's main file is trivially achieved via a if-statement at the top of the file being edited, so I believe this functionality would be very useful.

**Comment by jlelong** [comment]
See #671. I guess [`subfiles`](https://ctan.org/pkg/subfiles) is what you are looking for.
