### ISSUE TITLE
Support default path for graphics in IntelliSense

### ISSUE THREAD

**Issue by cgolde** [James-Yu/LaTeX-Workshop#1237]
**Is your feature request related to a problem? Please describe.**
Hi,
Thanks for the great extension. 
I normally store my graphics in a central graphics folder and use `\graphicspath{{./img/}}` for easier referencing of graphics. The path can be omitted when using the `\includegraphics` command. Currently I have to navigate the full folder tree.

**Describe the solution you'd like**
I would really love to see a support inside IntelliSense for the graphics when using `\graphicspath`.

Kind regards

**Comment by jlelong** [comment]
New entry in the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#files)
