### ISSUE TITLE
Ability to cancel build

### ISSUE THREAD

**Issue by Izuzusama** [James-Yu/LaTeX-Workshop#1244]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

TLDR; Add ability to cancel a build

On older machine and long document build will take a long time. Sometime I notice a mistake too late and wanted to make a small change. 
Waiting for the mistake build to finish and rebuilding again is a problem.

**Comment by jlelong** [comment]
Just call the `Kill LaTeX compiler process` command from the  _Command Palette_ or the `Terminate current compilation` command from the TeX badge in the _Build LaTeX project_ item.

**Comment by alexreg** [comment]
i get this when I kill the compiler process:

<img width="1374" alt="Screenshot 2021-01-16 at 01 04 29" src="https://user-images.githubusercontent.com/67036/104792598-c9f63980-5796-11eb-9ed0-ad1eb6141d20.png">

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template.
