### ISSUE TITLE
Support Chinese path...again?

### ISSUE THREAD

**Issue by zzj0311** [James-Yu/LaTeX-Workshop#1245]
**Is your feature request related to a problem? Please describe.**
I'm stuck on compile .tex file under path contains Chinese path under v6.2.2. As it works fine with path in Chinese before (last time I checked, around one to two months before), may you please support it again so I do not need to rename all my dirs... much thanks!

**Additional context**
Logs attached
```
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex 2019.2.17)  23 MAR 2019 21:29
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**"e:/OneDrive - zju.edu.cn/zzj/Ґ¾¿ʺ/͹ԅ»¯/طҵ/HW2/HW2"

! Emergency stop.
<*> ...rive - zju.edu.cn/zzj/Ґ¾¿ʺ/͹ԅ»¯/طҵ/HW2/HW2"
                                                  
*** (job aborted, file error in nonstop mode)
```

**Comment by jlelong** [comment]
This is related to #1239. The building tools use absolute paths by default, see #1137 and #1070 for problems arising when using relative paths. However, I think this is the reason it used to worked in your case. 

If you want to use relative path, just use

```
    "latex-workshop.latex.tools": [
        {
          "name": "latexmk",
          "command": "latexmk",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdf",
            "-outdir=./",
            "%DOCFILE%"
          ],
          "env": {}
        }
  ]
```

and everything should work fine as when the build command is spawn the current working directory is set to the `dirname` of the rootFile (=`%DOCFILE%`)

**Comment by zzj0311** [comment]
@jlelong Thanks for your help, I'll try it later. And one question though, as I remember, the plugin seems to use absolute path before (when it worked) according to the log file. It also contains nonsense characters in file path and it worked... So is there a better way to deal with those codec things?

**Comment by jlelong** [comment]
This is the solution we propose in the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#Path-containing-Chinese-characters).
I do not think we can do better.

**Comment by wj-c** [comment]
I provide another solution related to Chinese path issue: change the Windows system encoding to UTF-8 in the language setting. Then everything works fine without changing the default setting of the extension.
