### ISSUE TITLE
Ligatures not working for LaTeX files

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1248]
Hi,

I've created a ligaturized version of IBM Plex (it's a work in progress), and for some reason it works with non-latex files as expected, but not for latex files...

### Demo

Some text in a latex file
![image](https://user-images.githubusercontent.com/20903656/54881700-68602f00-4e8d-11e9-9a45-c6c0d21d1644.png)

The same text in a markdown file, with the same font
![image](https://user-images.githubusercontent.com/20903656/54881708-8a59b180-4e8d-11e9-9936-877ddbabaa57.png)

Here's the font file:

[TexifiedIBMPlexSans.zip](https://github.com/James-Yu/LaTeX-Workshop/files/3000523/TexifiedIBMPlexSans.zip)

It would be great if this could be figured out :smiley:

**Comment by tecosaur** [comment]
@James-Yu Would this be an upstream issue?

**Comment by jlelong** [comment]
I have no idea why it is not working with LW. I do not think we do anything special regarding fonts.
I really can't help on this 😕.

**Comment by tecosaur** [comment]
I think I've found this issue. VS Code only applies a ligature if all of the 'relevant characters' are within the same syntax block. I tried modifying the font to remove the backslashes and this is what I found:

![image](https://user-images.githubusercontent.com/20903656/55201868-f1fe5c80-51ff-11e9-9645-e06b619c262e.png)

Do you know of any way I could put math commands and subscripts in the same syntax block?

**Comment by jlelong** [comment]
The syntax blocks are defined in [`syntax/LaTeX.plist`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX.plist). I don't think we can much without redefining the whole syntax file...

**Comment by tecosaur** [comment]
Yea, seems like you're in a bind. Oh well - switch to emacs?* :wink: 

*I'm going to create an issue on vs-code and see how that goes
