### ISSUE TITLE
Citation Browser Doesn't Search By Author

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#125]
Searching by title appears to work; searching by author does not seem to work.

**Comment by James-Yu** [comment]
I just tested and it works for author search. However, the order of surname and given name matters.

For example, if the author is "Surname, Given Name", `givensurname` won't show the entry. `surgiven` will do.

This is the limitation of the fussy search provided by vscode.

**Comment by jsinglet** [comment]
This is what I get when trying to locate a paper by Hoare. Note that I cannot get the paper by the author Hoare, but I get the paper with the title Hoare. 

<img width="617" alt="screen shot 2017-04-26 at 11 19 38 pm" src="https://cloud.githubusercontent.com/assets/1062841/25466478/e24ecd3a-2ad6-11e7-8bf0-a1df776269fc.png">
<img width="613" alt="screen shot 2017-04-26 at 11 19 26 pm" src="https://cloud.githubusercontent.com/assets/1062841/25466477/e24d9050-2ad6-11e7-9709-55fedf926ee8.png">

**Comment by James-Yu** [comment]
Ahh did not notice the citation browser keyword. Will return in minutes.

**Comment by James-Yu** [comment]
This is a limitation of [vscode quickpickitem](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namequickpickitemaspan-classcodeitem-id448quickpickitemspan). Only the strings in `label` are index-able. The author information must be in the title for searching with author, but that will look quite bad. What do you think?

**Comment by jsinglet** [comment]
That is rough. Is it possible to put the text there, but use CSS to make it invisible (and take no space?) Something like a display: none?

**Comment by James-Yu** [comment]
That's another limitation by vscode: no css for vscode components can be controlled directly by extension.

I'm thinking of another option. What about adding a new config item controlling which information to display in the title? Users prefer author search can add the information, while others keep the original style.

**Comment by jsinglet** [comment]
I created the above issue to raise this point to the VSCode team. Maybe they have an idea of how to get around this problem.

**Comment by jsinglet** [comment]
Honestly, without both it's sometimes hard. Sometimes I am thinking of a particular author, sometimes the title of a specific paper. It would be great to just be able to use both...

**Comment by James-Yu** [comment]
Let me implement a prototype and see how it works. Will keep you updated.

**Comment by jsinglet** [comment]
Great! Thanks for all your work! Love your extension.

**Comment by James-Yu** [comment]
#128 provides a temporary solution. Discussion is always welcomed.

**Comment by jsinglet** [comment]
Please see the comment by the vscode team for a potential solution: https://github.com/Microsoft/vscode/issues/25504#issuecomment-297639115
