### ISSUE TITLE
Build on save with % ! TeX magic no longer works

### ISSUE THREAD

**Issue by sheljohn** [James-Yu/LaTeX-Workshop#1255]
## Problem description

Build on save no longer works from files with `% !TEX` magic if the main TeX file defines relative input paths. If I had to guess, I would say something has changed recently with how this LaTeX extension changes directory before build (in accordance with the dirname of the `root` defined on the "magic" header).

## How to reproduce

I am using the LaTeX Workshop 6.2.2 with VSCode 1.32.3 on Linux (Ubuntu 16.04) and OSX.

Create a project with the following structure:
```
main.tex
tex/
  foo.tex
```
with file `main.tex`:
```
\documentclass[11pt,a4paper]{article}

%--------------------------------
% Working version:
% \begin{document}
%     \input{./tex/foo}
% \end{document}

%--------------------------------
% Broken version:
\makeatletter
\providecommand*{\input@path}{}
\g@addto@macro\input@path{{./tex/}}% append
\makeatother

\begin{document}
    \input{foo}
\end{document}
```
and file `foo.tex`:
```
% !TEX root = ../main.tex

Hello world! My name is Placeholder.

```

With this setup:

1. Edit and save the file `main.tex` (e.g. add `chicken` after the `\input` line). This should build fine.
2. Edit and save the file `foo.tex` (e.g. replace `Placeholder` with your name). Nothing should happen.
3. Comment the broken version, and uncomment the working version in `main.tex`. Now edit and save `foo.tex` again, and it should build.

## Additional details

I am a bit puzzled by the fact that _nothing_ happens in the broken case, so I should mention that I setup the LaTeX Workshop plugin to output files to a separate folder `_out` with the following arguments in my preferences:
```
    ...
    "-aux-directory=./_out",
    "-output-directory=./_out"
    ...
```

This might not be relevant or needed to reproduce. But I am adding this because if it is indeed an issue with changing directories, then perhaps the fact that folder `tex/_out` does not exist somehow prevents the build altogether, instead of making it fail (in which case I would expect an error notice).

**Comment by jlelong** [comment]
This is not related to TeX magic comments.

In your _broken version_, there is no way to detect dependencies without running a latex compiler because you tweak `input@path`. Detecting such tricky dependencies is achieved by inspecting the generated `.fls` file, which is placed into `./out` because of your configuration and we have no way to know it. If you need to specify `aux` and `output` directories, you should stick to the default `latexmk` recipe and set `latex-workshop.latex.outDir` to `%DIR%/_out`. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshoplatexoutdir).

**Comment by sheljohn** [comment]
@jlelong Thanks for your reply. If I understand correctly, you seem to think this is an issue of "dependencies not found" because of the change of `input@path`. If that were the case, the build should fail no matter what file it is initiated from; however in reality, the build works fine if it is initiated from `main.tex`, and it even runs fine if I run it manually from any of the dependent file (i.e. using Ctrl+P and selecting the build command). So I think your assessment might be wrong.

> there is no way to detect dependencies without running a latex compiler

It's unclear to me why would you need to detect these dependencies at all? The only important thing is that the LaTeX compiler finds them, and it does.

> which is placed into `./out` because of your configuration and we have no way to know it

Well, it is specified in the recipe, so you _do_ have a way to know it. But again, it is unclear to me how this relates to the problem I'm having with save and build.

**Comment by sheljohn** [comment]
Problem was fixed by replacing arguments in the tools defined under `latex-workshop.latex.tools`:
```
    ...
    "-aux-directory=./_out",
    "-output-directory=./_out"
    ...
```
with 
```
    ...
    "-aux-directory=%DIR%/_out",
    "-output-directory=%DIR%/_out"
    ...
```
and the arguments of `bibtex` and `biber` tools to `%DIR%/_out/%DOCFILE%`.

_Basically, replacing all `./` in paths with `%DIR%/` instead._

Note that setting `"latex-workshop.latex.outDir": "%DIR%/_out"` had no effect (it actually doesn't seem to work with `latexmk`, but that's another problem).

**Comment by jlelong** [comment]
> Note that setting `"latex-workshop.latex.outDir": "%DIR%/_out"` had no effect (it actually doesn't seem to work with `latexmk`, but that's another problem).

It works when you pass ` "-outdir=%OUTDIR%"` to `latexmk`, which is what we do in the default recipe. See [there](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes).
