### ISSUE TITLE
Build command fails because environment is not defined

### ISSUE THREAD

**Issue by jerryqhyu** [James-Yu/LaTeX-Workshop#1256]
When I'm trying to build my project, latex workshop gives 

> [09:05:04] LaTeX build process spawned. PID: undefined.
> [09:05:04] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
> [09:05:04] Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin

and I was wondering why my PATH is like that. Could you take a look at

https://github.com/James-Yu/LaTeX-Workshop/blob/814e41783231703c778ff17a935962172d159d2a/src/components/builder.ts#L230
and make sure the envVars in
`this.currentProcess = cp.spawn(command, [], {cwd: path.dirname(rootFile), env: envVars, shell: true})`

is properly defined? I'm thinking if a async forEach could be fucking up the environment variable you pass into the child process.

**Comment by jlelong** [comment]
Your value for PATH is the basic one on a Linux/Unix system (even though I would have expected `/usr/local/bin` also). What is your OS? What does the command `which latexmk` return?

**Comment by jerryqhyu** [comment]
I'm on MacOS Mojave 10.14.4. 
`which latexmk` gives `/Library/TeX/texbin/latexmk`
and `echo $PATH` gives `/Library/TeX/texbin:/usr/local/bin:/Users/xxx/bin:/Users/xxx/Library/Python/2.7/bin:/Users/xxx/Library/Python/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/xxx/bin:/Users/xxx/Library/Python/2.7/bin:/Users/xxx/Library/Python/3.7/bin`

**Comment by jlelong** [comment]
I guess this is related to  #1203. Have a look at the last comments in particular.

**Comment by jerryqhyu** [comment]
Seems to be an external issue and out of your control. Is it possible that you could give the option to set absolute path to latexmk and pdflatex just like you do with chktex?

**Comment by jlelong** [comment]
You can set absolute paths in `latex-workshop.latex.tools`. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes).
Anyway, I a quite confident that you could fix your path issue. I also run MacOS Mojave 10.14.4. and I do not have any problem.

**Comment by jerryqhyu** [comment]
Thanks, setting absolute path worked. Still not sure why by default it doesn't work for me. When I first installed it seemed to be fine.

**Comment by mlettau** [comment]
I have the same issues as jerryqhyu.  How can I set the absolute path to the latex executables in /Library/TeX/texbin using latex-workshop.latex.tools?
