### ISSUE TITLE
Reverse synctex not working with external synctex

### ISSUE THREAD

**Issue by lonelykid** [James-Yu/LaTeX-Workshop#1257]
**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug**
Synctex from pdf to tex is not working with external synctex and internal pdf viewer.
with the builtin synctex, it's working well.

**To Reproduce**
1. "latex-workshop.synctex.path": "synctex.exe",
2. click somewhere in the pdf, nothing happened in the editor
Executing synctex with args edit,-o,30:149.45054945054946:395.2087912087911:c:\Users\xxx\main.pdf
3. Ctrl+alt+j synctex from tex to pdf is working though.

I tried manually run synctex
$ synctex edit -o 25:153.93406593406593:414.6373626373625:c:\Users\xxx\main.pdf
This is SyncTeX command line utility, version 1.5
SyncTeX result begin
Output:c:\Users\xxx\main.pdf
Input:c:/Users\xxx\main.tex
Line:846
Column:-1
Offset:0
Context:
SyncTeX result end
Synctex is installed with choco, but other versions behave the same

**Expected behavior**

**Logs**
Please paste the log messages here. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.20.0]
 - Extension version: [e.g. 5.0.0]

**Additional context**

**Comment by tamuratak** [comment]
> Synctex from pdf to tex is not working with external synctex and internal pdf viewer.
> with the builtin synctex, it's working well.

Please use the builtin synctex. Why do you want to use the external synctex command? Is there a specific reason?

**Comment by lonelykid** [comment]
@tamuratak 
The builtin synctex or synctex on Windows won't work if I build with texlive in WSL. I made a wrapper batch script to parse the path between linux format and windows format; and use it as the synctex. 

I just realized there's a better way,  by converting the  path format in the .synctex file every time I build pdf. 

I no longer need this feature for now. But this still seems like a bug. maybe you want to fix it.

**Comment by tamuratak** [comment]
Synctex with TeX on WSL is not officially supported. We won't fix it.

**Comment by lonelykid** [comment]
@tamuratak I mean, it won't work with any external synctex, including the native synctex on Windows. I've tried it. Only synctex from source to pdf; pdf to source sync is not working. Also the script I use produce exactly the same results as a native synctex on windows. It also only work for sync from source to pdf.

**Comment by tamuratak** [comment]
Duplicate of #1240.

**Comment by lonelykid** [comment]
Sorry. I didn't check existing issues carefully. I would wait for new versions pushed to marketplace

**Comment by tamuratak** [comment]
Never mind.
