### ISSUE TITLE
Missing packages when building on LaTeX-Workshop

### ISSUE THREAD

**Issue by Blitzman** [James-Yu/LaTeX-Workshop#1258]
**Describe the bug**
Certain LaTeX packages cannot be found when building any .tex file with the tool pdflatex - bibtex - pdflatex - pdflatex. For instance: acronym.sty or xpatch.sty. The packages are properly installed in the system and there is only one TeXlive installation which is able to compile the document using the same commands outside LaTeX Workshop in VSCode (even in the very same VSCode terminal).

**To Reproduce**
1. Create a .tex document.
2. Use for instance \usepackage{acronym}
3. Build with pdflatex-bibtex-pdflatex-pdflatex tool.

**Expected behavior**
No error since compiling outside of Code environment with the same commands (pdflatex, bibtex, pdflatex, pdflatex) works flawlessly (the packages are installed and verified).

**Logs**
Please paste the log messages here. It is very important to identify problems. If you think the logs are unrelated, please say so.

! LaTeX Error: File `acronym.sty' not found.

**Screenshots**

See image.
![Screenshot from 2019-03-28 13-48-35](https://user-images.githubusercontent.com/3442329/55158964-67b2eb80-5160-11e9-8893-a4eaff9d2e34.png)

Compiling in the very same terminal finds acronyms:

![Screenshot from 2019-03-28 13-51-39](https://user-images.githubusercontent.com/3442329/55159140-b5c7ef00-5160-11e9-89fd-e539e6af0091.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (Linux x64 4.15.0-46 -generic)
 - VS Code version: 1.32.3
 - Extension version: 6.2.2

**Comment by jlelong** [comment]
I cannot reproduce. If it compiles from the command line, it must also compile from the extension.
Have a look at the logs of the extension and the output of the LaTeX compiler inside the _Output_ pane.

**Comment by Blitzman** [comment]
The output log is this:

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(/home/agarcia/Workspace/3dpl/papers/paper-2019-cvpr-3dsg/egpaper_final.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)) (./cvpr.sty (./eso-pic.sty (./cvpr_eso.sty

LaTeX Warning: You have requested package `eso-pic',
               but the package provides `everyshi'.

) (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)) (/usr/share/texlive/texmf-dist/tex/latex/tools/xspace.sty)
CVPR 8.5 x 11-Inch Proceedings Style `cvpr.sty'.
) (/usr/share/texlive/texmf-dist/tex/latex/psnfss/times.sty) (/usr/share/texlive/texmf-dist/tex/latex/graphics/epsfig.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty) (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))

! LaTeX Error: File `acronym.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
/home/agarcia/Workspace/3dpl/papers/paper-2019-cvpr-3dsg/egpaper_final.tex:10: Emergency stop.
<read *> 
         
l.10 ^^M
        
/home/agarcia/Workspace/3dpl/papers/paper-2019-cvpr-3dsg/egpaper_final.tex:10:  ==> Fatal error occurred, no output PDF file produced!
Transcript written on egpaper_final.log.

---

Nothing else, as you can observe in the screenshots, it compiles properly when issuing pdflatex from command line and it is exactly the same version ( 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian).

Does that help?

And by the way, thank you for such amazing plugin. Forgot to say that in the first message :+1:

**Comment by jlelong** [comment]
There is something strange in your logs. When calling `pdflatex` from the command line you use the texlive distribution located in `/usr/local/texlive/2018/texmf-dist/`, while compiling from the extension you use the texlive distribution located in `/usr/share/texlive/texmf-dist/`. This is probably the cause of your problem as the extension has nothing to do in your problem. All this is probably related to your PATH

**Comment by Blitzman** [comment]
Actually, the issue was deeper than expected. I am using i3 (window manager) with a custom launcher (dmenu) for the applications. Turns out that when launching Visual Studio Code from that launcher the PATH variables are not sourced neither from bashrc, nor profile, nor environment leading to the use of the "bad" TeX distro. If Visual Studio Code is launched from a terminal, PATH variables are properly sourced (for obvious reasons) and it makes use of the proper TeX distro with all the packages.

At the moment, I see no way to change this behavior from i3 (lack of knowledge) or from Visual Studio Code. Just leaving this message here in case anyone faces the same issue.

For the record, it might be useful to include a Setting for the plugin that lets you pick your TeX distro PATH maybe?

Thanks for the answers!

**Comment by Chen-Song** [comment]
@jlelong Have you solved this problem? I miss the same problem as you.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).
