### ISSUE TITLE
Idea: Make Citation Browser Triggered by \cite Commands

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#126]
I greatly prefer the citation browser to the auto complete menu. It would be great to have an option to make the citation browser triggered by a \cite{} command. This (incidentally) mirrors the behavior of AUCTex.

**Comment by James-Yu** [comment]
According to [vscode API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namecompletionitemaspan-classcodeitem-id774completionitemspan), there is no way for an extension to provide a callback after intellisense is triggered. So it seems not quite possible.

**Comment by jsinglet** [comment]
What about just adding a key listener, waiting until you see \cite and then executing the command?

**Comment by James-Yu** [comment]
#128 Provides a configuration item to control the behavior.
