### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by esron** [James-Yu/LaTeX-Workshop#1260]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.2.2`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

[James-Yu.latex-workshop-unresponsive.cpuprofile.txt](https://github.com/James-Yu/LaTeX-Workshop/files/3020270/James-Yu.latex-workshop-unresponsive.cpuprofile.txt)

**Comment by stefano-lupo** [comment]
Has this caused you any actual issues using the extension, aside from the inconvenience of heavy CPU usage? My extension seems to lock up and become unresponsive and when I check `htop` I see a vs code process hogging 100% of one of my CPU cores

![image](https://user-images.githubusercontent.com/23197247/55281297-32f29000-532a-11e9-9f91-c9be4f94e42b.png)

FWIW my system / setup is the exact same as the one @esron's

**Comment by stefano-lupo** [comment]
This might be related to something going on between SpellRight and LaTeX Workshop as https://github.com/bartosz-antosik/vscode-spellright/issues/257 also exists


[Dev tools logs](https://gist.github.com/stefano-lupo/f0ba5a22f56b15bcea6e9b41d9c08136)
[CPU Profile](https://gist.github.com/stefano-lupo/b93fdbf3f1a7098f803c80f8602971f2)

Here is a screenshot of the same dev tools logs which might me more visible


![image](https://user-images.githubusercontent.com/23197247/55281496-26236b80-532d-11e9-97a5-d4910fde8b23.png)

**Comment by jlelong** [comment]
SpellRight and LW are known to be incompatible, see [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#Known-incompatible-extensions).
