### ISSUE TITLE
Should "clean up auxiliary files" clean .synctex.gz file?

### ISSUE THREAD

**Issue by wj-c** [James-Yu/LaTeX-Workshop#1261]
The auxiliary files include a file with the extension .synctex.gz, should it be removed when executing the "clean up auxiliary files" command?

**Comment by James-Yu** [comment]
A no for default, as this file is used by synctex. You can always change the config in config.json.

**Comment by memeplex** [comment]
I was about to report this. @James-Yu is it possible to add them to the list without having to copy paste the default value?

**Comment by James-Yu** [comment]
No. You can define your list of file types to be cleaned. The defaults are just a recommendation.

**Comment by sylvainlapeyrade** [comment]
When I use the "clean up auxiliary files" option, every aux files is cleaned except the .log and .synctex(busy) files.
However, they are both in my latex-workshop.latex.clean.fileTypes list (I think they are there as default). Is there something else I must do to clean them as well?

**Comment by tamuratak** [comment]
Please open a new issue.
