### ISSUE TITLE
How to add shortcuts keyboard?

### ISSUE THREAD

**Issue by santiagoftw** [James-Yu/LaTeX-Workshop#1262]
Hi, I'm new here, but I've used used texmaker for a good time. Although you know, in texmaker you can create shortcuts with the keyboard, for example Ctrl + Shift + M produces $ ... $. I would like to know how I can add combinations of keyboards to work to my liking.

Thank you.

**Comment by tecosaur** [comment]
You want to edit `keybindings.json` from the command pallet entry "`Open Keyboard shortcuts`" or "`Open Keyboard Shortcuts (JSON)`". For an example of what this may look like you may be interested in my version of that file.

https://github.com/tecosaur/vscode-settings/blob/master/keybindings.json

**Comment by santiagoftw** [comment]
Thank you very much, I have configured my shortcuts to my liking, what you told me worked, thanks
