### ISSUE TITLE
The visualization of a pdf is different between VS-Code, Preview and adobe in windows

### ISSUE THREAD

**Issue by The33Coder** [James-Yu/LaTeX-Workshop#1264]
**Describe the bug**
I just realized something very bizarre! The display of my pdf is not the same with the different OSs and readers!

On VS-Code. I see exactly the desired result.
![Screenshot_2019-04-01_at_13_41_32](https://user-images.githubusercontent.com/12548652/55349779-d377ba00-54ba-11e9-8903-3ffe8a62ab03.png)

With preview on mac. It's not that yet. 
<img width="901" alt="Screenshot_2019-04-01_at_13_43_00" src="https://user-images.githubusercontent.com/12548652/55349830-f2764c00-54ba-11e9-967c-b1904df753f9.png">

On Windows I have an error and nothing is displayed.
<img width="1384" alt="Screenshot_2019-04-01_at_13_46_29" src="https://user-images.githubusercontent.com/12548652/55335099-c6e36980-549a-11e9-9d18-e6d85eb34dd2.png">

On other files I have a correct display on VS-code but nothing is displayed on Preview and windows. The pdf has something written but is in white font. I disabled xcolor, but nothing changes and I admit I don't know where to look.

However, if I can get a correct display on Preview and export the PDF. I have no display problems on Windows.

**Desktop (please complete the following information):**
 - OS: Mac 14.4
 - VS Code version: 1.32.3
 - Extension version: 6.2.2

**Comment by jlelong** [comment]
I think there is something wrong with your usage of `\color`. You wrote `\color{red}{1}` whereas it should be `{\color{red} 1}` or `\textcolor{red}{1}`.

**Comment by jlelong** [comment]
From your screenshot, I get an error with `\begin{tabular}{*{9}{T}}`. Using, `\begin{tabular}{*{9}{c}}` instead, I get the same pdf in the internal viewer, Acroread, Skim and Preview (Mac). There must be something wrong in your pdf and I do not think this is related to the extension.

**Comment by The33Coder** [comment]
It's normal because T is defined as `\newcolumntype{T}{>{$\tt}c<{$}}`.
I repeat, the problem, is no't the compilation. Is the view difference between platform and viewer.

**Comment by jlelong** [comment]
A minimal working example to reproduce what you suspect to be an issue would have saved some time. Anyway, the extension is not responsible for the content of the `pdf`.

**Comment by The33Coder** [comment]
my main.tex
```
\documentclass[12pt, french, a4paper]{report}

\input{/Users/WorkSpace/Documents/CNAM/Template/header.tex}


\begin{document}

Ceci est un test Page 1
\newpage
Ceci est un test Page 2

\end{document}
```
header.tex
```
\usepackage{babel}

\usepackage{xcolor}
\definecolor{mywhite}{rgb}{1, 1, 0.99}
\definecolor{myblack}{rgb}{0.04, 0.07, 0,17}
\pagecolor{myblack}
\color{mywhite}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}


% Géométrie de la page
\usepackage{geometry}
\geometry{
	paper=a4paper, % Paper size, change to letterpaper for US letter size
	top=2.5cm, % Top margin
	bottom=3cm, % Bottom margin
	left=2.5cm, % Left margin
	right=2.5cm, % Right margin
	headheight=14pt, % Header height
	footskip=1.5cm, % Space from the bottom margin to the baseline of the footer
	headsep=1.2cm, % Space from the top margin to the baseline of the header
	%showframe, % Uncomment to show how the type block is set on the page
}
```

In this exemple pagecolor and color is ignored.

![Screenshot 2019-04-03 at 16 22 30](https://user-images.githubusercontent.com/12548652/55486527-bfec6080-562c-11e9-8a5a-990e7a7e379d.png)

**Comment by jlelong** [comment]
I cannot reproduce the issue. I do get a `myblack` background with `mywhite` foreground.

**Comment by The33Coder** [comment]
main.tex
```
\documentclass[12pt, french, a4paper]{report}

\input{header.tex}

\begin{document}

Ceci est un test Page 1
\newpage
Ceci est un test Page 2

\end{document}
```

header.tex
```
\usepackage{babel}

% Texte en Couleur
\usepackage{xcolor}
\definecolor{mywhite}{rgb}{1, 1, 0.99}
\definecolor{myblack}{rgb}{0.04, 0.07, 0,17}
\pagecolor{myblack}
\color{mywhite}

%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%% Font
%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}


% Géométrie de la page
\usepackage{geometry}
\geometry{
	paper=a4paper, % Paper size, change to letterpaper for US letter size
	top=2.5cm, % Top margin
	bottom=3cm, % Bottom margin
	left=2.5cm, % Left margin
	right=2.5cm, % Right margin
	headheight=14pt, % Header height
	footskip=1.5cm, % Space from the bottom margin to the baseline of the footer
	headsep=1.2cm, % Space from the top margin to the baseline of the header
	%showframe, % Uncomment to show how the type block is set on the page
}
```

VS-Code preview
![Screenshot 2019-04-03 at 16 29 30](https://user-images.githubusercontent.com/12548652/55487255-10b08900-562e-11e9-948c-e8e969eaa60c.png)

Mac Preview (only first page is good)
<img width="901" alt="Screenshot_2019-04-03_at_16_29_43" src="https://user-images.githubusercontent.com/12548652/55487308-2625b300-562e-11e9-8043-ca121cd931da.png">

Windows view
<img width="1384" alt="Screenshot 2019-04-03 at 16 30 28" src="https://user-images.githubusercontent.com/12548652/55487372-46557200-562e-11e9-94cf-e624173fb37d.png">

**Comment by The33Coder** [comment]
I would have preferred to have the vizualization as on mac. Rather than have a "good" viziualization on vscode and in the end realize that my result doesn't match or other people don't see my document. 
With other compilation application I have the visualization as the mac displays it....
