### ISSUE TITLE
Preview support for code-server (an online version of vscode)

### ISSUE THREAD

**Issue by imxieyi** [James-Yu/LaTeX-Workshop#1265]
**Is your feature request related to a problem? Please describe.**
This plugin can already be installed on [code-server](https://github.com/codercom/code-server). Most functions including compiling works just fine out of the box. However, the preview function is broken. It is because the preview extension is listening on localhost as shown in [viewer.ts#L126](https://github.com/James-Yu/LaTeX-Workshop/blob/0ef15bc11f6fe487a20334bf4acae17d2be465c7/src/components/viewer.ts#L126), which is impossible to be connected from a remote host. What makes things worse is that the port number is random.

**Describe the solution you'd like**
If the viewer can be implemented without extra http server, it would be the best solution possible.

**Describe alternatives you've considered**
I wonder if it is possible to reverse proxy the viewer server so that the port for pdf viewer and vscode can be the same. Alternatively the preview url prefix should be able to be configured so that I can reverse proxy the viewer on a subpath using nginx. At the same time the port number should be fixed.

**Comment by jlelong** [comment]
Can you test PR #1271.

**Comment by tamuratak** [comment]
Since VS Code Remote Development is available now, I think we do not need to support code-server. 

To my opinion, code-server itself should support port forwarding for WebView as VS Code Remote Development does. This is an upstream issue.
