### ISSUE TITLE
Synctex with external viewer

### ISSUE THREAD

**Issue by cojua8** [James-Yu/LaTeX-Workshop#1268]
I've seen there is a lot of people trying to make synctex with external viewer work. After hours and hours of searching the internet, I have a working solution for both Windows and Ubuntu

**Windows**
The solution is simple, and works with sumatraPDF. Just add the following option to your configuration (modify it so it get to the right paths. Also, you can replace "code" with the Code.exe path).
```
"latex-workshop.view.pdf.external.synctex": {
    "command": "C:/Program Files/SumatraPDF/SumatraPDF.exe",
    "args": [
        "-forward-search",
        "%TEX%",
	"%LINE%",
	"-reuse-instance",
	"-inverse-search",
        "code \"C:\\Users\\joaqu\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
	"%PDF%",
    ]
}
```

**Ubuntu**
This is trickier, but works. (I found it [here](https://ubuntuforums.org/showthread.php?t=1716268))

1. First, download this file (modified to work with VScode): [evince_synctex.zip](https://github.com/James-Yu/LaTeX-Workshop/files/3032338/evince_synctex.zip)
1. Unzip it in any folder in your PATH ( I put it in ~/.local/bin).
1. Add the following options to your configuration:
```
"latex-workshop.view.pdf.external.command":
{
	"command": "evince2",
	"args": [
		"%PDF%"
	]
},
"latex-workshop.view.pdf.external.synctex": {
	"command": "evince_forward_search",
	"args": [
		"%PDF%",
		"%LINE%",
		"%TEX%"
	]
},
```
To make this work both ways, first open the pdf file with external viewer.

That's it! I hope it helps someone

**Comment by jlelong** [comment]
I have just created a new [wiki entry](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#using-synctex-with-an-external-viewer) with this information. Thanks @cojua8.

**Comment by drdebmath** [comment]
It may be obvious for Sumatra users, but I think it is necessary to mention double click is required for inverse search in SumatraPDF rather than ctrl + click. Nice answer. Thanks.

**Comment by AndyLuckert** [comment]
@cojua8 :
At the end of your post you stated "To make this work both ways, first open the pdf file with external ### ### viewer."

### My follow-up question: How can I make the backward-search work with external PDFs?

_What I did so far:_
I inserted the following into my settings.json and indeed the forward-search from LaTeX-code to the external PDF works (e.g. via the keybinding "Ctrl + Alt + J"):
    "latex-workshop.view.pdf.external.command": {
        "command": "/home/andylu/evince_synctex3/evince_synctex3/evince2",
        "args": [
            "%PDF%"
        ]
    },
    "latex-workshop.view.pdf.external.synctex": {
        "command": "/home/andylu/evince_synctex3/evince_synctex3/evince_forward_search",
        "args": [
            "%PDF%",
            "%LINE%",
            "%TEX%"
        ]
    },

Then again, the reverse search doesn't work as it did before regarding the internal PDF-tab, which just works via "Ctrl + Left-click" from PDF to code.

**Again, what do I need to do that the backward search from external PDF to LaTeX-code works?**
Thanks in advance
Andreas

**Comment by cojua8** [comment]
Hi!,

The proccess to make it work, first open the pdf file by using the "View in external viewer" option, not with the "SyncTeX from cursor" one.
Then you can use ctrl + click to use backward search, and also the forward search from the .tex file

Hope I helped you.
