### ISSUE TITLE
Per folder settings in multi-root workspaces

### ISSUE THREAD

**Issue by fmorgner** [James-Yu/LaTeX-Workshop#1269]
Currently, when working in multi-root workspaces, `LaTeX-Workshop`'s settings don't apply if they are configured as folder settings. For example, consider the following structure:

```
my_workspace (Workspace)
--+---------------------
  \--+> documentation
  |  \--+> .vscode
  |  |  \---> settings.json
  |  \---> main.tex
  |
  \--+> application
  |  \---> sources
```

The `LaTeX-Workshop` settings stored in the `settings.json` file inside `.vscode` folder in the `documentation` folder all (or at least all that I have tried so far) get marked with the following message:

```
This setting cannot be applied now. It will be applied when you open this folder directly.
```

The only workaround I am aware of requires me to put the settings in the workspace settings. However, this is rather unfortunate, since I would much prefer to have the settings applied to the folder they relate to, since either:

* I would need to commit the workspace settings to a separate repository in order to share them with my coworkers
* Or I would need to keep those settings in sync manually, which is cumbersome and error prone.

I have little to no experience in working on VSCode extensions, but considering that other settings can be applied in that fashion, I was hoping that it would be possible to use a similar approach as for example `Code Spell Checker`, which seems to be able to load its custom dictionary entries on a `per-folder` basis in multi-root workspaces.

**Comment by jlelong** [comment]
It seems related to [vscode/45399](https://github.com/Microsoft/vscode/issues/45399). There are many people asking about this on google.

In your example, you do not seem to use multi-root workspace. You could create a workspace (this is different from opening `my_workspace` directory) containing both `documentation/` and `apps/` each of them with their own `.vscode` directory.
