### ISSUE TITLE
Idea: Figure Reference Browser

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#127]
For a large document, identifying a \ref{} by it's key is hard. The solution AUCTeX uses is to show a mini outline of the document, with the keys located in the flow of the document e.g.:

Section 1.1: Title
 key1: Caption 
Section 1.2: Title
 key2: Caption 

Something like this would be great, similar to the functioning of the citation browser.

**Comment by James-Yu** [comment]
Can you please provide a screenshot for AUCTeX on this feature? It is a bit hard to image how it would work.

**Comment by oerpli** [comment]
I don't really know what @jsinglet refers to but I could imagine something like this:

You type in the \ref{} and intellisense suggests some labels from it's dictionary.
In addition to this the first entry could be something like "search label" and it allows traversing the suggestions in a tree-like format (I think this does not work with intellisense).

The tree could be generated from the .aux file as far as I know

For example this aux file

> \@writefile{toc}{\contentsline {section}{\numberline {3}Results}{2}{section.0.3}}
> \@writefile{toc}{\contentsline {section}{\numberline {4}Methods \& data}{2}{section.0.4}}
> \@writefile{toc}{\contentsline {subsection}{\numberline {4.1}Data}{2}{subsection.0.4.1}}
> \newlabel{sec:data}{{4.1}{2}{Data}{subsection.0.4.1}{}}
> \@writefile{toc}{\contentsline {subsection}{\numberline {4.2}Construction of network}{2}{subsection.0.4.2}}
> \newlabel{eq:liabmat}{{1}{2}{Construction of liability network}{equation.0.4.1}{}}


Would result in the tree

- Results
- Methods & Data
    - Data
        - sec:data
    - Construction of network
        - eq:liabmat 

Maybe drop subtrees that don't contain a label in the leaf.

**Comment by jsinglet** [comment]
Here's an example of what I am talking about (from emacs)

<img width="1189" alt="screen shot 2017-04-28 at 11 02 17 am" src="https://cloud.githubusercontent.com/assets/1062841/25534611/466e5d2c-2c02-11e7-894e-a17775f24293.png">

**Comment by James-Yu** [comment]
This commit should provide a similar function. The context is presented in the intellisense document for selection. See the following screenshots:

![image](https://cloud.githubusercontent.com/assets/4210342/25735243/7747170a-319c-11e7-8b22-196978be1626.png)
![image](https://cloud.githubusercontent.com/assets/4210342/25735277/c39678b2-319c-11e7-9cd2-fc91784fcbaf.png)

**Comment by jsinglet** [comment]
Thanks!! Looks good!
