### ISSUE TITLE
Open pdf/preview in the active editor group

### ISSUE THREAD

**Issue by ChristianKurz** [James-Yu/LaTeX-Workshop#1273]
**Is your feature request related to a problem? Please describe.**
A pdf-preview is always opened in a new editor group. This is inefficient on small laptop screens.

**Describe the solution you'd like**
I would like to be able to configure if a new editor group or the active editor group is used.

**Additional context**
The [`OpenTab`](https://github.com/James-Yu/LaTeX-Workshop/blob/0ef15bc11f6fe487a20334bf4acae17d2be465c7/src/components/viewer.ts#L101) function already takes the variable `sideColumn` which defaults to `true`. I merely need an option in the settings to alter this variable.

**Comment by jlelong** [comment]
See the new [wiki entry](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdftabuseNewGroup).
