### ISSUE TITLE
Python3 support for evince-synctex

### ISSUE THREAD

**Issue by cphyc** [James-Yu/LaTeX-Workshop#1275]
**Describe the bug**
The file https://github.com/James-Yu/LaTeX-Workshop/files/3032338/evince_synctex.zip provides python 2 code and hence does not work on systems that use python3 as a default

**To Reproduce**
1. Follow the indications of https://github.com/James-Yu/LaTeX-Workshop/wiki/View#linux
2. Extract the zip file and run `./evince_forward_search`
3. Get back an error
```
 File "./evince_forward_search", line 26
    print 'Usage: evince_forward_search pdf_file line_number tex_file'
                                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Usage: evince_forward_search pdf_file line_number tex_file')?
```

**Expected behavior**
This should work under python3.

**Desktop (please complete the following information):**
 - OS: Arch Linux
- Python version: 3.7.3

**Additional context**
If have attached a working version as a zip bellow. It is the same file passed through 2to3 to make it python3 compatible.

[evince_synctex.zip](https://github.com/James-Yu/LaTeX-Workshop/files/3042526/evince_synctex.zip)

**Comment by jlelong** [comment]
Thanks! I have just updated the wiki.
