### ISSUE TITLE
$$ Equation preview show an extra "$" at left

### ISSUE THREAD

**Issue by Enn83** [James-Yu/LaTeX-Workshop#1278]
The equation preview in latex file (when the mouse is over an equation) show an extra "$" when use two "$$" like, for example : $$ \Sigma^* = \bigcup_{n\in\doubleN} \Sigma^n $$, even if they are space between the "$$" and the equation.

To reproduce, simply type an equation bewteen $$ ......... $$.

 - OS: Windows 10 1809
 - VS Code version: 1.32.3
 - Extension version: 6.3.0

Here an ilustration :
![Double $](https://user-images.githubusercontent.com/46783975/55628041-f3a3c380-57af-11e9-8879-98996a9d50fe.jpg)

Good luck with LaTeX-workshop !

**Comment by tamuratak** [comment]
`$$` is not supported. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#previewing-equations.

**Comment by trevorgunn** [comment]
You [shouldn't be using $$ in LaTeX](https://texfaq.org/FAQ-dolldoll) to begin with.

However, this isn't the only issue with the current regex: https://regex101.com/r/bijiXw/1

I've created a more robust regex that does what we want: https://regex101.com/r/ksPutY/1

`(?<!\$|\\)\$(?!\$)(?:\\.|[^\\])+?\$|\\\(.+?\\\)|\$\$(?:\\.|[^\\])+?\$\$`

Someone just has to figure out how to pass the `$$...$$` matches to MathJax so it doesn't render an extra pair of dollar signs.

**Comment by Enn83** [comment]
Thanks for all your answer, in fact I've not seen $$ ... $$ wasn't supported. 

From what trevorgunn sent me, I'll start using \[ and \] in my new documents.
