### ISSUE TITLE
Use the last used latex recipe on file save

### ISSUE THREAD

**Issue by georgejean** [James-Yu/LaTeX-Workshop#1281]
I regularly use several latex recipes, not only the first one in latex-workshop.latex.recipes.
It would be great and natural that auto-build process use by default the last used recipe in command palette (which is not necessarily the first one in latex-workshop.latex.recipes).
Is there a way to achieve this?

(There is no  magic comments in the root file)

![latex-workshop](https://user-images.githubusercontent.com/11246966/55674252-49f92b00-58b2-11e9-94d9-70b1be6247c4.gif)

**Comment by jlelong** [comment]
See the new [wiki entry](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexautobuildrecipe).

**Comment by georgejean** [comment]
Thanks!
