### ISSUE TITLE
vscode.previewHTML error

### ISSUE THREAD

**Issue by iainmstott** [James-Yu/LaTeX-Workshop#1283]
When trying to view a preview of the LaTeX document, I get an error "command 'vscode.previewHtml' not found". This wasn't happening only 2 days ago, but VSCode has updated since then. Release notes for the new version 1.33.0 suggests that the 'vscode.previewHtml' command has now been removed.

To reproduce: in the environments below, Ctrl+Shift+P > "Latex: Open Preview to the Side"
(or other preview commands). Error message shows in bottom right.

Expected behaviour: compile document. No error logs, as the command doesn't run in the first place.

ENVIRONMENT
Windows 10 enterprise
Version 1803
OS Build 17134.648

VSCode 1.33.0 (user setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

LaTeX workshop
Latest version 6.3.0

**Comment by trevorgunn** [comment]
LaTeX workshop hasn't been using vscode.previewHTML since 9ccc45d.

Also, I don't see any "Latex: Open Preview to the Side" command. The ones I do see are "LaTeX Workshop: View LaTeX PDF file" and "LaTeX Workshop: View LaTeX PDF file in VSCode tab" both of which work as intended for me.

I have the same environment as you: L-W 6.30 on VSC 1.33 on Win 10

**Comment by jlelong** [comment]
The command "Latex: Open Preview to the Side" is provided by [latex-preview](https://github.com/ajshort/vscode-latex-preview), which is an other extension.

**Comment by r351574nc3** [comment]
I am seeing this issue with Latex Workshop 7.3.0. I have no other Latex extensions installed. When I disable, Latex Workshop, I lose the ability to preview `tex` files. When I enable, I get `command 'vscode.previewHtml' not found`.

**Comment by wmeyer48** [comment]
I see this issue with Latex Workshop 8.1.1.
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by natakushi** [comment]
> The command "Latex: Open Preview to the Side" is provided by [latex-preview](https://github.com/ajshort/vscode-latex-preview), which is an other extension.

thx a lot !
