### ISSUE TITLE
Magic Comment Toolchain (Xelatex + Biber)

### ISSUE THREAD

**Issue by pogmat** [James-Yu/LaTeX-Workshop#1285]
When I write a document to be compiled with pdflatex using bibtex for bibliography, the compilation (using the standard `ctrl` + `alt` + `B`) is automatic and fast: it seems that bibtex is executed only when bib file changes.

When I write a document to be compiled with xelatex using biber for bibliography, if I use the magic comment `% !TEX program = xelatex`, biber is not called even if I modify the bib file (and so there are some unresolved reference in the pdf), while if I also use the magic comment `% !BIB program = biber`, all the process (xelatex + biber + xelatex + xelatex) is executed even if I did not modify the bib file.

I think that the behavior with xelatex + biber should be the same of that of pdflatex + bibtex

**Comment by trevorgunn** [comment]
The default program is `latexmk` which is smart about when to call `bibtex`. It might be worth looking into how to configure `latexmk` to use `xelatex` and `biber`.

**Comment by trevorgunn** [comment]
@pogmat Sorry, I forgot that settings in package.json are placed in settings.json once the extension is published. You can best access these settings through vscode's settings page. You'll know it's working if you see `latexmk ... -pdfxe ...` show up in the output tab (default ctrl + shift + U) (make sure you're looking at the output of `LaTeX Workshop` in the dropdown on the top right of the bottom pane.)
