### ISSUE TITLE
Built-in PDF viewer does not maintain scroll position upon refreshing

### ISSUE THREAD

**Issue by iliyang** [James-Yu/LaTeX-Workshop#1287]
**Describe the bug**
The built-in PDF viewer scrolls to an arbitrary location upon reloading the file after a LaTeX rebuild when the `latex-workshop.synctex.afterBuild.enabled` option is disabled.

**To Reproduce**
1. Open your PDF file with the built-in PDF viewer in a tab.
2. Scroll PDF somewhere.
3. Make sure the option `latex-workshop.synctex.afterBuild.enabled` is disabled.
4. Recompile the PDF.
5. Viewer scrolls the document to a different location.

**Expected behavior**
The viewer should maintain the scroll position upon refresh, like the Sumatra and Skim external viewers.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - VS Code version: 1.33.0
 - Extension version: 6.3.0

**Comment by jlelong** [comment]
I cannot reproduce with exactly the same configuration as yours. Do the logs say anything special? Can you post a MWE?

**Comment by qingdujun** [comment]
How to use built-in PDF? What Plugin?
