### ISSUE TITLE
Option to refresh pdf even after build error

### ISSUE THREAD

**Issue by PotatoDrug** [James-Yu/LaTeX-Workshop#1289]
It will be nice to have this option, it seems that currently only builds without error will refresh the pdf viewer, even if there is a valid pdf compiled by the build.

**Comment by jlelong** [comment]
When a build exists with an error, there is no way to know if the available `.pdf` is valid or not. Considering that loading an invalid `.pdf` will surely break the viewer and force the user to restart vscode, I do not think it is worth it.
