### ISSUE TITLE
Question: How do I make use keyboard shortcut to move the cursor in between environments?

### ISSUE THREAD

**Issue by kun-zhou** [James-Yu/LaTeX-Workshop#129]
How do I make use keyboard shortcut to move the cursor in between *custom* environments? The below image illustrates it.

<img width="580" alt="screen shot 2017-04-27 at 12 59 19 pm" src="https://cloud.githubusercontent.com/assets/19158151/25494974/86cea214-2b49-11e7-80a0-d42a32ae42eb.png">

After selecting the first option, I get two cursors so my environment names are synchronizes in the `\begin{env}` and `\end{env}`. However, after finishing typing, what is the most elegant way to move the cursor inside environment with an indent?

**Comment by James-Yu** [comment]
`TAB`
