### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jakobhviid** [James-Yu/LaTeX-Workshop#1298]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.4.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

[James-Yu.latex-workshop-unresponsive.cpuprofile.txt](https://github.com/James-Yu/LaTeX-Workshop/files/3073740/James-Yu.latex-workshop-unresponsive.cpuprofile.txt)

When i load the thesis template from here: https://gitlab.com/claudiomattera/modernthesis (updated)

The entire setup freezes and is extremely slow. Many function, such as loading a pdf preview, results in "activating extensions",  and only work after quite a bit of waiting.

**Comment by trevorgunn** [comment]
There are a few [known incompatible extensions](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions). Namely,
- [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright)
- [Brackets Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2)
- [Prettify Symbols Mode](https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode)

If it's not any of these, you can try disabling all other extensions and then re-enabling them one-by-one until the issue appears.

**Comment by jakobhviid** [comment]
Hi. Thank you for your response. I have already read the page you are linked to, and they are already disabled.

I have gone through and disabled every single extension (including themes etc), but i am still experiencing weird behavior, just as before. The extension finally load after a long waiting time, but in the tex tab, commands and structure loads for ages.
Compile commands that are just waiting for it to get its command through, and nothing happens.

Please let me know if you need any other information. I will gladly provide it.

**Comment by trevorgunn** [comment]
It looks like something in this template is causing `findDependentFiles()` to go into an infinite loop. Can you post a link to the template? You posted the wrong link originally.

**Comment by jakobhviid** [comment]
The corrected link is [here](https://gitlab.com/claudiomattera/modernthesis), and i corrected the original link.

**Comment by jlelong** [comment]
This is because the file `chapters/introduction.tex` includes itself line `148`.

**Comment by James-Yu** [comment]
@jlelong I've been away from file tree parsing for a while. May you please remind me about the rough location of the functions? I'd try to fix the issue with loops if that's the problem.

**Comment by James-Yu** [comment]
Is it https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/manager.ts#L310 and https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/manager.ts#L315 ?

**Comment by claudio-mattera** [comment]
Author of the template here.
I just want to clarify that, while it looks like `chapter/introductions.tex` includes itself on line 148, that line is inside a `minted` environment. It is just rendered verbatim in the output document (with syntax highlighting), and it is not executed. This probably confused the parser.

**Comment by jlelong** [comment]
This is precisely the issue. 
@James-Yu yes, these are the lines to refactor. I can take care of it if you want

**Comment by James-Yu** [comment]
100x thanks to @jlelong !

**Comment by jlelong** [comment]
It still freezes the TeX badge because the structure analyser also gets stuck in a circular inclusion.

**Comment by jakobhviid** [comment]
@jlelong Thanks for the fix!

@James-Yu, when is the next release cycle into the vscode marketplace?
