### ISSUE TITLE
Quote autocomplete in math

### ISSUE THREAD

**Issue by fatanassow** [James-Yu/LaTeX-Workshop#13]
Although the autocomplete which turns one quote into two quotes is correctly disabled inside `$...$` and `\[...\]` when the delimiters appear on the same line -- as it should be since in math the quote char is used for "prime" -- it is not disabled when the delimiters appear on different lines, or inside standard amsmath environments such as `align*`, or inside `\ensuremath`, or in `\newcommand` content which gets spliced into a math context. More than 50% of my math appears in such places, and so the autocomplete gets in the way more often than it helps. Since detecting such contexts is impractical in general, and autocompleting one quote into two quotes is not much of a help anyway, I would like an option to disable it altogether.

**Comment by James-Yu** [comment]
Thanks for the suggestion. New version `0.2.14` remove both quotes' autocompletion. Unfortunately as this is a grammar feature it cannot be controlled by configs.
