### ISSUE TITLE
Idea: Possible synctex improvements

### ISSUE THREAD

**Issue by oerpli** [James-Yu/LaTeX-Workshop#130]
With TexWorks the integrated synctex highlights the part in the PDF that corresponds to the location clicked in the .tex document 

![highlighting also works in the caption of a floating figure environment](http://i.imgur.com/Q0ryIWA.png)

As the built-in PDF viewer has a highlighting option I think this may be possible to implement. 

Furthermore the TexWorks synctex not only jumps to the line/paragraph but also sets the cursor to the location corresponding to the click. I don't know enough about synctex/PDF in general to assess whether it is possible to implement this.

**Comment by James-Yu** [comment]
Sorry this is a unique feature by TexWorks. `synctex` does not natively support these features, and there is no current plan to implement them in the extension.
