### ISSUE TITLE
Plugin not honoring "latex-workshop.latex.recipe.default": "lastUsed" 

### ISSUE THREAD

**Issue by yrammos** [James-Yu/LaTeX-Workshop#1315]
**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug**
LaTeX-Workshop not honoring `"latex-workshop.latex.recipe.default": "lastUsed"` when building.

**To Reproduce**
1. Build a project using a recipe.
2. Make modifications to the project.
3. Save the file.
4. Run `Build LaTeX project` (or save the file if `latex-workshop.latex.autoBuild.run` equals `onFileChange`).

**Expected behavior**
The last-run recipe should be run but is not.

**Logs**
None relevant.

**Comment by jlelong** [comment]
I cannot reproduce the issue. Can you confirm that you are using LaTeX-Workshop 6.4.0?

**Comment by yrammos** [comment]
The issue seems resolved, possibly as a result of restarting the editor. Sorry for the (probably) false alarm. Closing for now and will update if/as necessary. Thanks.
