### ISSUE TITLE
Shortcut changed since v6.4

### ISSUE THREAD

**Issue by sth4nth** [James-Yu/LaTeX-Workshop#1318]
Before v6.4, I type
\equ
to generate the environment 
\begin{equation*}
\end{equation*}
Since v6.4 the default behavior of \equ changed to 
\begin{equation}
   \label{}
\end{equation}

How can I change it back?

**Comment by jlelong** [comment]
The string `\equ` is not the name of a snippet itself, but it triggers intellisense

<img width="709" alt="Capture d’écran 2019-04-17 à 08 30 41" src="https://user-images.githubusercontent.com/2910140/56265888-1d7fb300-60eb-11e9-9574-705bb25c0bba.png">

It is up to the user to choose the right completion. If you set `"editor.suggestSelection": "recentlyUsedByPrefix"`, vscode will remember your choice and will default any further completion to the previous choice

<img width="694" alt="Capture d’écran 2019-04-17 à 08 38 10" src="https://user-images.githubusercontent.com/2910140/56266363-4bb1c280-60ec-11e9-94da-8a66d84a608b.png">

This time, `\begin{equation*}....\end{equation*}` is preselected.

See also the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets) for dedicated snippets.
