### ISSUE TITLE
Popup Citation browser doesn't search

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#132]
After enabling the popup citation browser with `latex-workshop.intellisense.citation.type` (looks great), I noticed that typing doesn't search. The list remains static.

**Comment by James-Yu** [comment]
I cannot reproduce the problem. A screenshot may be required.

**Comment by jsinglet** [comment]
![screen shot 2017-05-05 at 1 10 43 pm](https://cloud.githubusercontent.com/assets/1062841/25756313/4d483766-3194-11e7-9c32-ce7bd753ebbd.png)
![screen shot 2017-05-05 at 1 10 33 pm](https://cloud.githubusercontent.com/assets/1062841/25756315/4d54cb84-3194-11e7-8501-8bf2379b68a3.png)
![screen shot 2017-05-05 at 1 10 21 pm](https://cloud.githubusercontent.com/assets/1062841/25756314/4d50796c-3194-11e7-9f9d-46a6d40ea08c.png)

**Comment by James-Yu** [comment]
![image](https://cloud.githubusercontent.com/assets/4210342/25756370/230c8f32-31f9-11e7-8c8d-7572ff4f0d92.png)

I cannot reproduce the problem. I'm also on the latest 1.12.1.

Totally have no idea what's the problem.

**Comment by jsinglet** [comment]
![screen shot 2017-05-05 at 1 15 14 pm](https://cloud.githubusercontent.com/assets/1062841/25756477/e95e719c-3194-11e7-80be-c57ae244afcd.png)

**Comment by jsinglet** [comment]
That's what I see in the console when I type

**Comment by James-Yu** [comment]
It seems to be an upstream problem of vscode. The only related `toLowerCase()` call by the extension is on parsing `bib` items: [link](https://github.com/James-Yu/LaTeX-Workshop/search?utf8=%E2%9C%93&q=toLowerCase&type=). However, as the dropdown menu can be created, these calls are successful.

**Comment by jsinglet** [comment]
is there a way to set a breakpoint inside your extension (without downloading the source and all that)? I can look and see what's happening more closely...

**Comment by James-Yu** [comment]
No it's not possible. Meanwhile, it looks like [this issue](https://github.com/Microsoft/vscode-cpptools/issues/650). I will check back tmr.

**Comment by James-Yu** [comment]
Can you please provide a minimal working example of your bib file that results in this issue? That would help a lot.
