### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by irving-flores-mejia** [James-Yu/LaTeX-Workshop#1325]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.4.0`
- OS Version: `Linux x64 5.0.7-200.fc29.x86_64`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/alan/James-Yu.latex-workshop-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by trevorgunn** [comment]
First, make sure you're  not using [one of these incompatible extensions](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions). Second, you didn't attach your cpuprofile file; you will need to do that. Third, can you try to say something about what you are doing to cause the issue? If it happens in every `.tex` file, it's most likely an incompatible extension. Is there a specific function you are using that causes this?
