### ISSUE TITLE
Extension host terminated unexpectedly error

### ISSUE THREAD

**Issue by Spacebody** [James-Yu/LaTeX-Workshop#1328]
**Describe the bug**
As the title, extension host terminated unexpectedly error.

**To Reproduce**
1. Block this extension, restart the extension host and it runs normally.
2. Activate this extension, extension host will terminate unexpectedly.

**Expected behavior**
Keep the extension host running normally without block this extension.

**Logs**
I don't know where to find the log.

**Screenshots**
No.

**Desktop (please complete the following information):**
 - OS: macOS Mojava 10.14.4
 - VS Code version: 1.33.1
 - Extension version: 6.4.0

**Additional context**
No.

**Comment by trevorgunn** [comment]
Open the command palette with cmd+shift+p and search for "log". You should find options like "show log" and "open logs folder".

**Comment by Spacebody** [comment]
After open logs folder, which file should I look?

**Comment by Spacebody** [comment]
I found this in a `exhost.log`:

```
[2019-04-24 02:00:14.375] [exthost] [info] ExtensionService#_doActivateExtension James-Yu.latex-workshop {"startup":false,"activationEvent":"onLanguage:latex"}
```

Will this be helpful?

**Comment by trevorgunn** [comment]
That line is normal. Can you post the full exhost log and also the latex-workshop log? (It should be under exthost/output_logging in the logs folder.)

Although, if there is nothing unusual in your logs, there might not be much we can do.

**Comment by Spacebody** [comment]
I cannot find log file of this extension since enabling this extension the extension host will terminate immediately, so I am afraid that there might not have log file generated before host crash.

**Comment by jlelong** [comment]
The problem is bund to come from your installation and it is usually very difficult to diagnose it.
Can it be related to [this](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#the-directory-node_modules-may-cause-errors)? Have you read the different issues dealing Extension host unexpected termination?

**Comment by Spacebody** [comment]
After I move `node_modules` into `npm`, the extension host works. Thanks!
