### ISSUE TITLE
Add option for re-enabling the dropdown

### ISSUE THREAD

**Issue by MagicLegend** [James-Yu/LaTeX-Workshop#1329]
**Is your feature request related to a problem? Please describe.**
Since my horizontal screen space is limited (still rocking 1080p :-)), I like to keep the side bar closed when I'm working on LaTeX documents. However, with the deprecation of the dropdown, the sidebar keeps opening when I manually invoke the building of my documents. I have the enter key bound to my mouse, meaning that I could easily rebuild the document by clicking on the recipe button, and pressing the button on my mouse twice. Now, I can't easily rebuild without having to move my mouse from the initial click (which is a hassle). This is higly frustrating to me.

**Describe the solution you'd like**
I noticed that the code of the dropdown was removed in https://github.com/James-Yu/LaTeX-Workshop/commit/d6ac5d100912970bb47d4a7c7810b36462baa0dc , and I was wondering if this could come back as an unsupported config option to re-enable.

Perhaps adding a new (optinal) button to the bottom bar that would automatically invoke latexmk (or whatever recipe is selected / last used) would also solve the issue, since it also eliminates the additional clicks :-)

Thanks for the amazing extension.

**Comment by jlelong** [comment]
If you do not want to have the TeX side bar constantly pop up, set `latex-workshop.view.autoFocus.enabled` to `false`. Why not using a shortcut `ctrl+alt+b` to build? I do not exactly get why you need the dropdown menu?

**Comment by MagicLegend** [comment]
Because of course I didn't RTFM :-) `ctrl+alt+b` seems like a even eleganter solution than clicking on a button haha. Good to know that there is a config option to disable the popping up of the sidebar! Thank you for your time!
