### ISSUE TITLE
Structure of the tex-document

### ISSUE THREAD

**Issue by aa-b** [James-Yu/LaTeX-Workshop#133]
It would be really nice and more productive if latex-workshop could parse the tex files and list in a panel (like the Explorer Panel for the directory) at the left side all files (.tex, .jpg, ...) included with input or include. The files from this list should be opened when they are clicked.

**Comment by James-Yu** [comment]
VSCode does not allow extension to manipulate GUI. No API for the existing file browser is provided either.

**Comment by aa-b** [comment]
It's a pity. OK.
