### ISSUE TITLE
After build synctex stopped working

### ISSUE THREAD

**Issue by rkkautsar** [James-Yu/LaTeX-Workshop#1330]
Issue Type: <b>Bug</b>

This is a recurring issue. I use the included pdf preview and enabled `synctex.afterBuild`. It works for some time, but after a few (undetermined) builds it just stopped working. I have to restart the VSCode to get it to work again--reopening the preview doesn't work.

Edit: but the manual synctex (⌘+⌥ + J) still works.

Extension version: 6.4.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by tamuratak** [comment]
Please show us log messages at the time this issue occurs.

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

Please show us messages in the console too.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by lyyc199586** [comment]
similiar issue!
the reverse syntex does'n work (crtl+left click)

**Comment by tamuratak** [comment]
@lyyc199586, to clarify that your issue is really the same one, please show us log messages. Thank you for your cooperation.

**Comment by rkkautsar** [comment]
@tamuratak 

Console:
```
webviewElement.ts:392 [Embedded Page] Uncaught TypeError: Cannot read property 'viewport' of undefined
webviewElement.ts:392 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:392 [Embedded Page] PDF 08db9dae8aa5781298b8ffbcdd020d58 [1.5 pdfTeX-1.40.19 / LaTeX with hyperref package] (PDF.js: 2.0.943)
```

Also there's a bunch of `[[object Object]]Cannot read property 'selectionChanged' of undefined` don't know if that's related.

LaTeX Workshop log:
```
[10:33:16] Try to synctex file.pdf
[10:33:16] Build root file file.tex
[10:33:16] Recipe step 1: latexmk, -synctex=1,-bibtex,-interaction=nonstopmode,-file-line-error,-shell-escape,-pdf,-outdir=out,file
[10:33:16] LaTeX build process spawned. PID: 7431.
[10:33:16] Recipe of length 1 finished. PID: 7431.
[10:33:16] Successfully built file.tex.
[10:33:16] Preview PDF file: file.pdf
[10:35:26] LOG command invoked.
```

Compiler log:
```
... bunch of underfull warnings
Output written on out/file.pdf (44 pages, 263382 bytes).
SyncTeX written on out/file.synctex.gz.
Transcript written on out/file.log.
Latexmk: Found input bbl file 'out/bib.bbl'
Latexmk: Log file says output to 'out/file.pdf'
Latexmk: ===For rule 'pdflatex', actual output 'out/file.pdf'
       ======appears not to match expected output 'out/file.pdf'
=== TeX engine is 'pdfTeX'
Latexmk: Found bibliography file(s) [bib.bib]
Latexmk: All targets (file.pdf) are up-to-date
```

**Comment by tamuratak** [comment]
@rkkautsar, please show us the whole log messages, not a part of it.

**Comment by rkkautsar** [comment]
@tamuratak https://gist.github.com/rkkautsar/4c49e33ff500e9b4051a861d0471abc9

**Comment by rkkautsar** [comment]
OK it's a bit difficult to log the actual error since I think it only occur on one specific build and the build after that will just not sync, but I think I manage to capture it. I've updated the gist from earlier. 
To reproduce it somewhat quickly I have to build the document a numerous time (sometimes even triggering a build when the current one is not finished yet) with some intentional builds with syntax errors.

**Comment by tamuratak** [comment]
@rkkautsar  workshop.log has disappeared in your new gist. Please show us workshop.log.

Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.  We can see lots of errors of other extensions.

**Comment by tamuratak** [comment]
@rkkautsar, when a build fails because of a syntax error, SyncTeX does not work since a synctex file is not generated. It is not a bug. 

After fixing the syntax error of a TeX file, SyncTeX after build should work well again. If not, that is a bug.

**Comment by rkkautsar** [comment]
@tamurata

Yeah that's is why I only provide a relevant snippet earlier.

No it's not _disappeared_, it's in the bottom and is just too big to be shown directly so you have to see it in the raw link: https://gist.github.com/rkkautsar/4c49e33ff500e9b4051a861d0471abc9/raw/d5cc8a19d1956661ed7df15a9915637401ce6fea/workshop.log

While I try to reproduce this again with no other extensions (and this can take a while since I still don't know the exact way to reproduce it quickly), why do the error I provide clearly above can't help point out the issue? I think it's clearly points out to this line: https://github.com/James-Yu/LaTeX-Workshop/blob/8dd06def151053ceecfec4bd90547863885a090b/src/components/synctex.ts#L60

`linePageBlocks` is undefined.

**Comment by rkkautsar** [comment]
> After fixing the syntax error of a TeX file, SyncTeX after build should work well again. If not, that is a bug.

Yes it doesn't work well after the first time it doesn't work, even if the build success. As I said earlier, manual forward sync still works so this is a bug.

**Comment by rkkautsar** [comment]
@tamuratak updated the gist: https://gist.github.com/rkkautsar/4c49e33ff500e9b4051a861d0471abc9

**Comment by tamuratak** [comment]
Are you saying that you have disabled all the other extensions except for LaTeX Workshop and you still see this issue?

**Comment by rkkautsar** [comment]
Yes. updated the gist again.

The `TypeError` I mentioned is in line 16 of console.log and line 131 of workshop.log

**Comment by tamuratak** [comment]
> it just scrolls the top of the pdf.

I have heard this for the first time.

**Comment by rkkautsar** [comment]
Yes sorry for not making it clear, the synctex just doesn't fire (no red circle pings), instead the pdfjs just refreshes with the new pdf content so the scrolling position resets to the top.

**Comment by tamuratak** [comment]
If you disable SyncTeX After Build, the scrolling position is restored after a build. It does not reset to the top. You can try.

SyncTeX can fail for various reasons. So, its failure is not necessarily a bug. But, it is a bug that the scrolling position resets to the top when SyncTeX fails after a build. We will look into it.

Thank you for your cooperation.

**Comment by rkkautsar** [comment]
> If you disable SyncTeX After Build, the scrolling position is restored after a build. It does not reset to the top. You can try.

Yeah that seems to be the case. Thanks.

**Comment by rkkautsar** [comment]
Umm I can confirm that the scrolling reset still occurs when I disabled SyncTeX After Build.
Do the fix in #1334 already covers this?

**Comment by tamuratak** [comment]
No. Please show us log messages.

**Comment by rkkautsar** [comment]
Still have no luck reproducing it, I'll just open up a new issue when I can collect the log
