### ISSUE TITLE
Error While Switching Section Level

### ISSUE THREAD

**Issue by uninyhart** [James-Yu/LaTeX-Workshop#1331]
**Describe the bug**

It can't work in some particular positions.

![issue-latexworkshop-switch](https://user-images.githubusercontent.com/41117888/56734449-6d1e4880-6795-11e9-9f41-398be1d4cd27.gif)

**Logs**

Sorry for it. I can't find anything useful.

可能是我的打开方式不对。

**Desktop**
 - OS: Windows 10 & Arch Linux
 - VS Code version: 1.33.1
 - Extension version: 6.5.0

**Comment by trevorgunn** [comment]
This happens whenever the new text would put the cursor before the beginning of the line. I'm thinking about the best way to fix this.
