### ISSUE TITLE
Provide snippets for bibtex files

### ISSUE THREAD

**Issue by brunotvs** [James-Yu/LaTeX-Workshop#1339]
**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug**
Cant use snippets on *.bib files while outside a bibliography entry

**To Reproduce**
1. Go to a blank *.bib file
2. Try to use a snippet
3. Nothing happens

While...
1. Go to a *.bib file
2. Start a new entry like
    @ARTICLE{
        **snippets work fine here**
    }

**Expected behavior**
Snippets to work anywhere in a bibtex file

**Desktop:**
 - OS: Windows 10
 - VS Code version: 1.33.1
 - Extension version: 6.5.0

**Comment by jlelong** [comment]
The extension does not provide any snippet for `bibtex` files. When you edit a non empty `.bib` file, vscode's intellisense pops up suggestions that look like snippets but are not. 

Btw, it would nice to add some snippets for `bibtex` files.

**Comment by brunotvs** [comment]
I meant my user snippets. But it would be nice to have some provided by the extension

**Comment by jlelong** [comment]
The use of your own snippets have nothing to do with the extension.

**Comment by brunotvs** [comment]
### Extension enabled:
**snippets working inside a bib entry**
![image](https://user-images.githubusercontent.com/45828157/56851655-d57d3f00-68e7-11e9-9a76-29ebf50ea604.png)

**snippets not working outside a bib entry**
![image](https://user-images.githubusercontent.com/45828157/56851676-08bfce00-68e8-11e9-9f99-b50d5c735184.png)

Is this a intended behavior? I was expecting that snippets could also work outside a bib entry.

**Comment by jlelong** [comment]
This is because everything outside bib entries is considered as a comment and intellisense is not automatically triggered inside comments but you can trigger it manually using `Ctrl+space` and then the completion shows up.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#bibtex-files for the documentation on snippets for bibtex files.
