### ISSUE TITLE
Feature: word suggestion

### ISSUE THREAD

**Issue by neilsustc** [James-Yu/LaTeX-Workshop#134]
I think it's very useful when writing a document. And this is what I have implemented in a Markdown extension

![word completion](https://raw.githubusercontent.com/neilsustc/vscode-markdown/master/images/gifs/word-completion.gif)

I can make a PR if you think it's a good addition. 😉

**Comment by James-Yu** [comment]
Hmm that might be a nice addition, though I myself feels typing much faster than finding the word in a dropdown list. Others' opinion?

**Comment by neilsustc** [comment]
Oh, in the most cases, I just type some text and if the first candidate 'happens to' be what I expect, I hit Enter. And in the other hand, it can prevent some typos.

I can wait to see if there are other people would like to have this.

**Comment by Haroenv** [comment]
I do think this could be useful, but maybe rather as a standalone extension?

**Comment by neilsustc** [comment]
I agree but maybe several days later.

**Comment by neilsustc** [comment]
@Haroenv 👉 [Dictionary Completion](https://marketplace.visualstudio.com/items?itemName=yzhang.dictionary-completion)
