### ISSUE TITLE
clearTexFileTree goes into infinite loop if filetree has a cycle of length ≥ 2

### ISSUE THREAD

**Issue by trevorgunn** [James-Yu/LaTeX-Workshop#1341]
**Describe the bug**
clearTexFileTree will successfully manage a file including itself but goes into an infinite loop on longer cycles (file A includes file B and file B includes file A)

**To Reproduce**
1. Take the minimal working example I created here: https://github.com/trevorgunn/TeX-FileTree-Test/tree/master/Complicated%20Include
2. Put a breakpoint just inside clearTexFileTree (line 508)
3. Launch the debugger
4. You'll see that lines 512–514 do not successfully handle the cyclical inclusion and will keep generating stack frames without end.

For reference:
```typescript
507 clearTexFileTree(file: string) {
508     if (!this.texFileTree.hasOwnProperty(file)) {
509         return
510     }
511     for (const f of this.texFileTree[file]) {
512         if (f !== file) {
513             this.clearTexFileTree(f)
514         }
515     }
516     delete this.texFileTree[file]
517 }
```

**Desktop:**
 - OS:  Windows 10
 - VS Code version: 1.33.1
 - Extension version: [e9055b6](https://github.com/James-Yu/LaTeX-Workshop/tree/e9055b6cf7ca2ee1248efd7e213126278c476cc0)

**Additional context**
Related to #1333. Also note that removing the reference to `includeA.tex` from `includeB.tex` makes everything work again.

**Comment by jlelong** [comment]
Yes @trevorgunn, I had already identified the problem but did not have time to fix until now. Anyway, thanks for the serious investigation and reproducing examples.

**Comment by trevorgunn** [comment]
@jlelong Practically speaking, I don't expect this issue to show up 99.9999% of the time (maybe even 100%). On the other hand, I commend your ability to fix how these cycles are handles in file"trees". Well done on all the fixes.
