### ISSUE TITLE
buildOnFileChange only triggers build when the modified file has the same root file as the activeTextEditor

### ISSUE THREAD

**Issue by jay-pee** [James-Yu/LaTeX-Workshop#1343]
With pandoc I build from a markdown file a latex file. 

`$ pandoc.exe test.md -o test.latex`

Unfortunately the file watcher doesn't trigger and the PDF previewer is not updated.

I used a windows and this building task:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Tex",
            "type": "shell",
            "command": "pandoc.exe ${file} -o ${fileBasenameNoExtension}.tex",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

A workaround for me is to go from the .md file to the .tex file and save it again. But it drives me crazy two do this two clicks every time. Thank you for your help :)

**Comment by trevorgunn** [comment]
Try adding `&& latexmk.exe ${fileBasenameNoExtension}.tex` to the end of your command. This doesn't address the file watcher but maybe it's an acceptable solution.

**Comment by jay-pee** [comment]
Unfortunately adding this code doesn't help. 

I found another solution though, thanks to your suggestion. I now take SumatraPDF to display the PDF document and changed the output of pandoc to .pdf. This PDF viewer can handle the update of the Document. However it would be nice if I could view the PDF in vscode internally... 

Still this is maybe a (minor) bug you would like address someday.

**Comment by jlelong** [comment]
This has nothing to do with `pandoc` actually but is related two things

1. A build is only triggered when the active text editor has type `LaTeX`, see [`commander.ts#L33`](https://github.com/James-Yu/LaTeX-Workshop/blob/388421c2d0e714bc5b81e084c31fada5be42b2cc/src/commander.ts#L33)
1. The root file to build is determined from the active text editor, see [`commander.ts#L44`](https://github.com/James-Yu/LaTeX-Workshop/blob/388421c2d0e714bc5b81e084c31fada5be42b2cc/src/commander.ts#L44)

The consequence of this is that `buildOnSave` only triggers build when the modified file has the same root file as the active text editor. I will try to fix.

**Comment by jlelong** [comment]
I hope this fix has no hidden side effect. Testing in elaborate workflows is welcome.
