### ISSUE TITLE
Problem of menus of editor context

### ISSUE THREAD

**Issue by lxd** [James-Yu/LaTeX-Workshop#1346]
**Describe the bug**
When I right click in a .tex file, the menus of editor context doesn't display "Build LaTex project" and "SyncTex from cursor". Then I change the "default" of the "latex-workshop.showContextMenu" into "true", and the two menu options display.

**Screenshots**
![20190429112140](https://user-images.githubusercontent.com/11884752/56877216-fcba4480-6a7e-11e9-89e3-1d273c8bb579.png)

![20190429123609](https://user-images.githubusercontent.com/11884752/56877222-02b02580-6a7f-11e9-896a-3e4d11346244.png)

![20190429123709](https://user-images.githubusercontent.com/11884752/56877225-0774d980-6a7f-11e9-8cbd-90d9edba3d9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.33.1

**Comment by jlelong** [comment]
This is the intended behaviour and has been working this way for approximately 8 months. Maybe we should document in the wiki.
