### ISSUE TITLE
bib sometimes work, but sometimes not.

### ISSUE THREAD

**Issue by liganega** [James-Yu/LaTeX-Workshop#1348]
I am relatively new with latex-workshop.
(using mac osx 10.14.4)

When I started to use it, there was no problem in getting bib in the pdf.
But from sometime, it doesn't work. 
I think, the only change was that the tex file became longer. 
On the other hand, with another latex file, it works fine.

I tested the two cases after having removed all the auxiliary files,
that is, using only tex and bib files.

Compiling latex files of both cases is done by clicking on "Build Latex project" or "Recipe: latexmk" of the side panel. (Click on "Recipe: pdflatex -> bibtex -> pdflatex*2" works fine.)

I didn't do any change in setting. 
What could be the reason?

**Comment by jlelong** [comment]
This is most likely unrelated to the extension but has to do with your files. The compilation is carried out by `latexmk`, which takes care of everything and in particular runs `bibtex` when needed.
