### ISSUE TITLE
Doesn't refresh PDF

### ISSUE THREAD

**Issue by christianmalek** [James-Yu/LaTeX-Workshop#135]
Hi,

LaTeX-Workshops doesn't refresh the PDF because of an so-called error in the build toolchain. If I look at the log there are no errors, just warnings and infos:

![image](https://cloud.githubusercontent.com/assets/2873986/25848688/be790fe4-34bb-11e7-9148-55add507f54f.png)

 I just tried to compile it with TeXstudio. This works without problems. Do you have any ideas? The funny part is: The compilations works. But because it thinks that it errored I have to close the PDF view and open it again to refresh it and see the changes.

**Comment by James-Yu** [comment]
Can you please provide your log?

**Comment by christianmalek** [comment]
Of course. (I had to rename it to upload it.)
[master.txt](https://github.com/James-Yu/LaTeX-Workshop/files/986470/master.txt)

**Comment by James-Yu** [comment]
In fact, I mean LaTeX Workshop log. You can access it in the bottom panel.

**Comment by christianmalek** [comment]
Where exactly?

**Comment by James-Yu** [comment]
Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/4210342/25881318/c905eff0-356e-11e7-9bbc-b32edac3293e.png)
You can click the `problem` status bar item to access this panel.

**Comment by christianmalek** [comment]
Thanks! Here you go: 
[log.txt](https://github.com/James-Yu/LaTeX-Workshop/files/988840/log.txt)

**Comment by James-Yu** [comment]
hmm it's strange. The extension reports error when your `latexmk` returns with non-zero exit code, but the latex log shows that everything works fine.
Can you please provide the same log after the following change? That might help a bit.

- Navigate to `C:\Users\your-username\.vscode\extensions\James-Yu.latex-workshop-2.3.1\out\src`
- Open `builder.js`
- Change line 52 from
```javascript
this.extension.logger.addLogMessage(`Toolchain returns with error. ${stdout}`);
```
to
```javascript
this.extension.logger.addLogMessage(`Toolchain returns with error: ${exitCode}.\n${stdout}`);
```

This will also log the exit code of `latexmk`.

**Comment by christianmalek** [comment]
`Toolchain returns with error: 12.`

**Comment by James-Yu** [comment]
Following are the exit code comments of `latexmk`:
```
## Explicit exit codes: 
##             10 = bad command line arguments
##             11 = file specified on command line not found
##                  or other file not found
##             12 = failure in some part of making files
##             13 = error in initialization file
##             20 = probable bug
##             or retcode from called program.
```
So it seems that there are problems in the `latexmk` toolchain, although I cannot find it. I would suppose this is a `latexmk` problem. However, I cannot modify the codebase to allow `retcode=12`, since I have no idea if it is an individual false alarm, or a common problem. Sorry cannot help.

**Comment by christianmalek** [comment]
Thanks anyways. Your extension is awesome!
