### ISSUE TITLE
How do I turn off indenting?

### ISSUE THREAD

**Issue by aapeliv** [James-Yu/LaTeX-Workshop#1353]
#204 introduces some auto-indenting feature.

How do I turn it off?

I don't indent my code in LaTeX, for me it's text with extra markup. Indenting is for code. It also messes up a bunch of cases, like when trying to use the `verbatim` environment.

I attempted to add the following in my settings, but it does't help:

```
    "[latex]": {
        "editor.autoIndent": false
    }
```

**Comment by jlelong** [comment]
Setting `"editor.autoIndent": false` only suppresses indentation when pasting text or hitting `Enter` (after `\begin{...}` for instance) but does nothing as far as snippets are concerned. Indentation inside snippets is represented by `\t` and there is no way to set `tabSize` to `0`, the minimum value is `1`.

**Comment by trevorgunn** [comment]
I think it's a reasonable feature request to add an option to remove the tabs from the snippets. I'm willing to work on this but I need to finish grading final exams first.

**Comment by jlelong** [comment]
This can be only be done for snippets with a prefix starting with `\`. The others are not handled by the extension but directly by VScode and we cannot du much for them. 
I am not convinced this is worth it to have a setting to remove indentation from snippets as unindented `LaTeX` files very quickly become unreadable.

**Comment by aapeliv** [comment]
> Setting `"editor.autoIndent": false` only suppresses indentation when pasting text or hitting `Enter` (after `\begin{...}` for instance) but does nothing as far as snippets are concerned. Indentation inside snippets is represented by `\t` and there is no way to set `tabSize` to `0`, the minimum value is `1`.

Sorry, I don't follow this. What's a "snippet"?

I can't really see any difference from having added the `autoIndent` setting. To clarify, I'd like VSCode not to add the spaces here when I type stuff in:

![Entering some text with unwanted indentation](https://user-images.githubusercontent.com/2975660/57172010-cd7c4c80-6e5d-11e9-8b09-e4c439aa60f5.gif)

> I am not convinced this is worth it to have a setting to remove indentation from snippets as unindented `LaTeX` files very quickly become unreadable.

I've actually never met anyone who indents their latex documents, but then again, I haven't talked about it much with people. Maybe I should start indenting my latex documents too, I'll definitely have a look into it. But I feel people ought to not be forced into it...

**Comment by trevorgunn** [comment]
A snippet is any kind of auto-completion. Here's the difference:

No snippet and `autoIndent = false`:
![gif1](https://user-images.githubusercontent.com/7917549/57172866-01228c80-6df4-11e9-9c3b-fd770ff749af.gif)

Snippet and `autoIndent` setting doesn't matter:
![gif2](https://user-images.githubusercontent.com/7917549/57172867-02ec5000-6df4-11e9-8bac-40185874dddc.gif)

**Comment by aterenin** [comment]
Would also like to turn the tab indents off. Is there an option to do this?

**Comment by tamuratak** [comment]
Please open a new issue.
