### ISSUE TITLE
Default margin trim in PDF

### ISSUE THREAD

**Issue by FMuro** [James-Yu/LaTeX-Workshop#1355]
There's a great zoom option that I personally use to default to page-width. Since LaTeX margins are so thick in many document classes, I always trim 15% at margin (other editors have a text-width zoom), but I have to do it manually as there doesn't seem to be an option to make this by default. Do you think it would be possible? Thanks in advance.

**Comment by jlelong** [comment]
Use the new setting [`latex-workshop.view.pdf.trim`](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdftrim).
