### ISSUE TITLE
Performance drop for long stdout

### ISSUE THREAD

**Issue by kanje** [James-Yu/LaTeX-Workshop#1358]
**Describe the bug**
A project I am building prints huge amounts (8.5M) of text to stdout. Building it via LaTeX Workshop (I have configured it to to use `xelatex`) takes hours while executing the same `xelatex` command in the shell takes less than 10 minutes.

**How to reproduce**
Steps to reproduce the behaviour:
1. Have a project which generates large amounts of stdout.
2. Build the project with the xelatex recipe.

**Expected behaviour**
It takes the same time as running the same `xelatex` command in the shell.

**Root cause**
Building via LaTeX Workshop is slower because it starts to consume all CPU so `xelatex` gets much less resources than it gets when it is run in the shell.

[The performance analysis](https://github.com/James-Yu/LaTeX-Workshop/files/3145672/James-Yu.latex-workshop-unresponsive.cpuprofile.txt) has shown that 99% of CPU is spent in `match()` in `checkStdoutForInfo()`. Is it necessary to match the whole stdout? Wouldn't matching only the last line be enough? Is it necessary to match the same regular expression on the same string twice?

Removing `this.checkStdoutForInfo()` on line 79 in `buildinfo.ts` resolves this issue.

**Standard output**
The project has a lot of plots. The build produces 70k lines like this (beside others):
`NOTE: coordinate (-2.99E-02,-2.69E-05) has been dropped because it is unbounded`

**Desktop:**
 - OS: Linux x64 5.0.10-200.fc29.x86_64
 - VS Code version: 1.33.1
 - Extension version: 6.5.1

**Comment by tecosaur** [comment]
Ahh. This would be my fault.
When I implemented that I must admit that I didn't consider the performance for long logs — rather foolishly.

The issue with just keeping the last line is that some of the matches need to spread over multiple lines.
I can't conclusively state an upper bound, but from what I've seen 5 would probably be too low, perhaps something like 20 or 50 would work.

The solution as far as I can tell would be something like keeping the last 50 lines.

I have two nieve solutions.
1. Keep the lines in a length 50 array, and cycle through and replace entries circularly.
I imagine this would be better than adding and deleting entries. Then each time the regex is run this would have to be reconstructed into a single string.
 2. Every time a line is added to the string, run a regex match for the oldest line in the string and overwrite the string with a new string that is the same, just with that oldest line removed

Not sure which approach is better.

_p.s. To jlelong, James-Yu feel free to assign this issue to me._

**Comment by jlelong** [comment]
From `checkStdoutForInfo()`

````ts
const pageNumberRegex = /\[(\d+)[^\[\]]*\]$/
const latexmkRuleStartedRegex = /Latexmk: applying rule '([A-z \/]+)'\.\.\.\n$/
const rulePdfLatexStart = /This is pdfTeX, Version [\d\.\-]+[^\n]*$/
const ruleSageStart = /Processing Sage code for [\w\.\- \"]+\.\.\.$/
const ruleBibtexStart = /This is BibTeX[\w\.\- \"\,\(\)]+$/
````

I cannot see which rule may spread over several lines. Maybe there is way to split the regex into a starting regex and a continuation one. Ideally, we should only parse every line once.

I think that constructions like 
````ts
if (this.currentBuild.ruleProducesPages && this.currentBuild.stdout.match(pageNumberRegex)) {
      const pageNo = parseInt(this.currentBuild.stdout.match(pageNumberRegex)[1])
````
could be refactored to call `.match` only once. I doubt this is optimised by the typescript compiler.

**Comment by tecosaur** [comment]
The page number regex is multiline as `[^\[\]]` matches newlines. Here's a demo
![image](https://user-images.githubusercontent.com/20903656/57229112-ec3e3700-7047-11e9-8aa3-977f14556fa9.png)
And this can go on for a fair few lines in specific scenarios.

If it weren't for that we could just check the last line, however unfortunately as seen above, that wont work :disappointed: 

I don't think the second match is a big deal. If say a new page is seen, **two** instances of `.match` are run, whereas if there's nothing of note in a new line then **five** instances of `.match` are run.

If we can bring down the number of lines stored, and have that done in an efficient manner I imagine that would relieve the performance issues.

**Comment by tecosaur** [comment]
I've done a simple implementation llimiting stored `stdout` to 50 lines — see: https://github.com/tecosaur/LaTeX-Workshop/commit/e4833beb96224c6ad65924957b7949dea86e5713

**Comment by tecosaur** [comment]
(Unrelated but have also fixed colours breaking, and fontstyle in buildinfo webview, specificly https://github.com/tecosaur/LaTeX-Workshop/commit/453699a94cdb1159fae642dd288ba311e1714c73)
