### ISSUE TITLE
How to add directories into build path?

### ISSUE THREAD

**Issue by Albocoder** [James-Yu/LaTeX-Workshop#1359]
So I have my bibliography in `./bibliography` folder, my figures in `./figures` folder and styles in `./styles` folder and all my tex files in the root directory. I need pdflatex to check those other folders too when compiling but none of the builtin recipes does that. Any suggestions?

**Comment by trevorgunn** [comment]
How exactly are the files linked together? E.g. through `\includegraphic{figures/figurename.pdf}`. How would you get the project to build from the command line? Any special arguments?
