### ISSUE TITLE
Automatically dismiss compilation error notifications when launching a new build

### ISSUE THREAD

**Issue by iliyang** [James-Yu/LaTeX-Workshop#1368]
**Is your feature request related to a problem? Please describe.**
I have build-on-save turned on – great feature! However, often make silly errors in my LaTeX code, and I get a lot of VS Code error notifications in the bottom right. The pain is that I have to close these notifications manually every time.

**Describe the solution you'd like**
How about automatically clearing error notifications when launching LaTeX compilation? If the error has been fixed in the code, the notifications will be gone and I will be able to continue working undisturbed. If the error hasn't been fixed, the compilation will fail again, in which case a new VS Code notification should appear.

**Comment by trevorgunn** [comment]
See the [`latex-workshop.message.error.show`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessageerrorshow) and related options.

**Comment by iliyang** [comment]
Thanks for the quick response! Ticket #898 is about the same issue and the discussion makes it clear that VS Code doesn't currently allow notifications to be closed programmatically. Let's hope it becomes possible at some point, until then I'll use the provided extension options. Thanks again!!
