### ISSUE TITLE
Prepend external newcommands to mathjax preview too

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1370]
**Is your feature request related to a problem? Please describe.**

If you use an external file for your common commands and macros, as it is usual practice, mathjax previews are frequently "broken" in the sense that some parts are unable to be rendered.

**Describe the solution you'd like**

Pass all command definitions to mathjax, no only the ones in the current file as was implemented in https://github.com/James-Yu/LaTeX-Workshop/commit/3429940bfa5853576b7a131d0daa8bec1d2d28d8

I think you are already gathering commands from other files in order to feed intellisense, it shouldn't be difficult to add them to mathjax, I guess.

**Describe alternatives you've considered**

Temporarily copy&pasting all my commands to the current file, which is error prone and cumbersome.

**Comment by jlelong** [comment]
This has been implemented very recently and will be available in the next release.
See [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#configuration-variables) in particular
- [`latex-workshop.hover.preview.newcommand.parseTeXFile.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandparsetexfileenabled)
- [`latex-workshop.hover.preview.newcommand.newcommandFile`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandnewcommandfile)

**Comment by memeplex** [comment]
That's great, thanks! Just while we are at this: is there any way to see the preview without having to resort to the mouse? Some quick shortcut, maybe?

**Comment by jlelong** [comment]
To provide math preview, we use the hover API from vscode and unfortunately it cannot be triggered without using the mouse.

**Comment by memeplex** [comment]
I discovered you can show the hover popup with `C-k C-i`. But the there is this new issue https://github.com/James-Yu/LaTeX-Workshop/issues/1373

**Comment by jlelong** [comment]
Thanks for the tip. I will add to the wiki.

**Comment by PierreMarchand20** [comment]
In the option `latex-workshop.hover.preview.newcommand.parseTeXFile.enabled`, is this only the current `.tex` file or the whole project `tex` ? 

For example, if I have a root file `main.tex` which includes a file `macros.tex` and another file `chapter1.tex`, they both have `% !TEX root=main.tex`, would it be possible to parse `macros.tex` to use them in `chapter1.tex` when previewing math expressions ?

**Comment by jlelong** [comment]
The option `latex-workshop.hover.preview.newcommand.parseTeXFile.enabled` only concerns the current `.tex` file not the rootFile. I guess we could think of it.

If you use a `macros.tex` file, you should set `latex-workshop.hover.preview.newcommand.newcommandFile: macros.tex` to add the content of `macros.tex` to mathjax. 

I guess we should make this clearer in the wiki.

**Comment by PierreMarchand20** [comment]
It would be easier when having several projects in one workspace

An issue I have seen with several projects is that when one goes from one project to the other, what happens with mathjax and the newcommands ? At the beginning I set a `latex-workshop.hover.preview.newcommand.newcommandFile` with a relative path, I looked in one project where I defined new commands and it worked, and then it also worked in another project where I had not defined yet the new commands. So it made me wonder what would happen if I define differently the same command in two projects.

To avoid this issue, I defined a `commun_shorthand.tex` at the root of my workspace, even if it is not ideal. But it is not working. My path is something like `~/Partage/texfiles/commun_shorthands.tex.

**Comment by jlelong** [comment]
I guess `~/Partage/texfiles/commun_shorthands.tex` is not understood as an absolute path, you really need to expand `~`.

**Comment by memeplex** [comment]
> I guess we should make this clearer in the wiki.

I should say that I spend some time figuring that out.

**Comment by jlelong** [comment]
PR are more than welcome to keep the wiki up to date with the developments.

**Comment by memeplex** [comment]
In fact, I first assumed every command parsed by intellisense or whatever would be available to the mathjax rendered, like Pierre is asking for. Maybe that's too difficult to implement, in that case I find the current solution an acceptable alternative, but it imposes some constraints on the project organization: one file with commands for mathjax without any other stuff there that would be ignored by the mathjax parser and thus passed as is to the renderer.

**Comment by PierreMarchand20** [comment]
FYI, this is a detail, but I actually define `\newcommand{\nc}{\newcommand}`to avoid writing `newcommand` every time. It actually breaks the preview.

**Comment by jlelong** [comment]
This is no surprise. Keep in mind that all this parsing mechanism is done using regex and does not use the `TeX` engine, so there is way to understand elaborate constructions.

**Comment by PierreMarchand20** [comment]
> The option `latex-workshop.hover.preview.newcommand.parseTeXFile.enabled` only concerns the current `.tex` file not the rootFile. I guess we could think of it.

It would really help when having several projects in one workspace, for now the best solution is to have one commun file with all the macros at the root of the workspace, but then the macros specific to a project cannot be used in the preview.

But then it depends on how the macros are loaded, because it means that the macros need to be reloaded each time the root file of the current file is changed, to avoid any problem. Which is not easy to do I guess...

**Comment by memeplex** [comment]
I've used org mode to produce a lot of LaTeX in the past. It supports previews but they are rendered by LaTeX itself (it's a bit slower but you can even preview tikz or whatever you fancy). Now, I'm not suggesting that LaTeX Workshop go this way (although it would be nice to have that), I just want to say that the mechanism they provide for feeding the previewer with extra commands and stuff is just a list of packages to include and code snippets to add to the header.  Maybe renaming `latex-workshop.hover.preview.newcommand.newcommandFile` to `latex-workshop.hover.preview.newcommand.newcommandFile`**s** and making it support multiple files would ameliorate the "several projects in one workspace" issue. You still have to split the mathjax-friendly part of each project into its own file, but at least different projects (or even different concerns in the same project, say "optimization.tex", "functional-analysis.tex", etc) would not have to share the same file.
