### ISSUE TITLE
Mathjax preview shows artifact where the cursor is

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1373]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

If the cursor is inside the math environment `$...|...$` when showing the mathjax preview, a glyph is shown for it. I'm not sure whether this is intended or not, but I'm unable to see the point of doing that and sometimes it just breaks the rendering, for example in `$x^|2$` the cursor will be taken to be the exponent instead of 2.  This is specially annoying when using `C-k C-i` to show the hover popup, since in that case the cursor is usually inside the math environment.

**To Reproduce**
1. Enter $x^2$
2. Put the cursor inside the expression
3. Hover the expression with the mouse or press `C-k C-i` inside it.

**Expected behavior**

Show a preview with no trace of a cursor being there. The cursor is not part of the expression.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

[22:56:52] Initializing LaTeX Workshop.
[22:56:52] Creating LaTeX Workshop http and websocket server.
[22:56:52] LaTeX Workshop initialized.
[22:56:53] Server created on 127.0.0.1:40091
[22:56:54] Snippet data loaded.
[22:56:54] LaTeX Workshop version: 6.5.1
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
Nothing suspicious here.
</details>

**Desktop [Required]:**
 - OS: Arch Linux
 - VS Code version: 1.33.1
 - Extension version: 6.5.1

**Comment by memeplex** [comment]
Ok, I realized the indicator is configurable and not an unintended artifact.

That said, even when I set it to the empty string it's disruptive, for example try $x^|2$ with the cursor indicator set to "" (here | is intended to represent the cursor). The 2 won't be rendered as a superscript.

**Comment by jlelong** [comment]
RTFM [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#previewing-equations). The variable `latex-workshop.hover.preview.cursor.enabled` is what you are looking for.
