### ISSUE TITLE
Compilation with errors keep going forever

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1376]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

Ongoing compilation counter and advance bar are shown after failed compilation, even if no compilation is really going on.

**To Reproduce**
1. Create a document as the one in the screenshot below
2. Press C-A-b in order to build it
3. You should see an advance indicator at the status bar, click on it
4. A compilation live info opens, with an ongoing counter
5. Even if you call the Terminate current compilation recipe, the counter keeps going on

**Expected behavior**

No ongoing compilation is running, so both the advance bar and the counter are wrong.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

````
[17:33:31] Linter for root file started.
[17:33:31] Linter for root file running command chktex with arguments -wall,-n22,-n30,-n46,-e16,-q,-f%f:%l:%c:%d:%k:%n:%m
,/home/carlos/Desktop/test.tex
[17:33:31] Linter for root file successfully finished in 0s 49ms
[17:33:31] Linter log parsed with 1 messages.
[17:33:31] Parsing /home/carlos/Desktop/test.tex
[17:33:31] Parsing /home/carlos/Desktop/test.fls to compute dependencies
[17:33:31] File watcher: responding to change in /home/carlos/Desktop/test.tex
[17:33:31] /home/carlos/Desktop/test.tex changed. Auto build project.
[17:33:31] BUILD command invoked.
[17:33:31] Found root file from active editor: /home/carlos/Desktop/test.tex
[17:33:31] Root file remains unchanged from: /home/carlos/Desktop/test.tex.
[17:33:31] Building root file: /home/carlos/Desktop/test.tex
[17:33:31] Build root file /home/carlos/Desktop/test.tex
[17:33:31] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/carlos/Desktop,/home/carlos/Desktop/test
[17:33:31] LaTeX build process spawned. PID: 20509.
[17:33:31] Recipe returns with error: 12/null. PID: 20509.
[17:33:31] Cleaning auxillary files and retrying build after toolchain error.
[17:33:31] CLEAN command invoked.
[17:33:31] Found root file from active editor: /home/carlos/Desktop/test.tex
[17:33:31] Root file remains unchanged from: /home/carlos/Desktop/test.tex.
[17:33:31] Found root file from active editor: /home/carlos/Desktop/test.tex
[17:33:31] Root file remains unchanged from: /home/carlos/Desktop/test.tex.
[17:33:31] File cleaned: /home/carlos/Desktop/test.aux
[17:33:31] File cleaned: /home/carlos/Desktop/test.fls
[17:33:31] File cleaned: /home/carlos/Desktop/test.log
[17:33:31] File cleaned: /home/carlos/Desktop/test.fdb_latexmk
[17:33:31] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/carlos/Desktop,/home/carlos/Desktop/test
[17:33:31] LaTeX build process spawned. PID: 20528.
[17:33:32] Recipe returns with error: 12/null. PID: 20528.
````
</details>

<details>
<summary>LaTeX Compiler Output</summary>

````
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/home/carlos/Desktop"  "/home/carlos/Desktop/test.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(/home/carlos/Desktop/test.tex
LaTeX2e <2018-12-01>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo)) (/home/carlos/Desktop/test.aux)
/home/carlos/Desktop/test.tex:4: Undefined control sequence.
l.4 \jj
       
(/home/carlos/Desktop/test.aux) )
(see the transcript file for additional information)
No pages of output.
Transcript written on /home/carlos/Desktop/test.log.
'test.fls' and '/home/carlos/Desktop/test.fls' are identical (not copied) at /usr/bin/latexmk line 7507.
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to '/home/carlos/Desktop/test.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
````
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/2845433/57574645-2c6c3380-7413-11e9-8548-c22d7b608989.png)

**Desktop [Required]:**
 - OS: Arch Linux
 - VS Code version: 1.33.1
 - Extension version: 6.5.1

**Comment by memeplex** [comment]
Also, notice that the build rule is latexmk, but the live window shows two rules for pdflatex, I really don't understand that.

**Comment by memeplex** [comment]
I've manually run latexmk with the parameters reported in LaTeX Workshop log window and effectively it aborts immediately with an error, so there is no really ongoing activity there.

**Comment by tecosaur** [comment]
I'll take a look at that (feature by me), what I can tell you right now is that you're seeing two instances of pdfLaTeX because what `latexmk` does is call pdfLaTeX until the document stops changing (more or less).

**Comment by Xalip** [comment]
I'm facing the exact same issue as well on Arch Linux. Any advise on fixing this?

**Comment by rahulguptakota** [comment]
I am also facing the same issue on Ubuntu 18.04. For my thesis project, whenever there is an error and compilation is not finished, if you try to compile again in between, it gets stuck and keeps going forever. Even Terminate Compilation doesn't work in that case. I had to restart VS code again to resume work and eventually shifted back to TeXStudio for that project. Although the extension works fine for smaller files.

**Comment by tecosaur** [comment]
We seem to be talking about the compilation loop this extension triggers, so I've spun up a separate issue to deal with the progress bar issue.

**Comment by memeplex** [comment]
I don't think there is a compilation loop anywhere @tecosaur, nothing is really compiling. it's just the counter and the bar going on and on. I barely understand what @rahulguptakota is saying, but "Compilation progress doesn't clear after failure to build" doesn't seem to be a good description to me. More like a mix of this report "spurious advance indicator going on forever when nothing really happens" with "I can't recompile and must restart vscode". But I'm failing to see how that means that there is a compilation loop or that some state is not clearing. If anything this report has loops and maybe non-clearing states; but a second one, to be clarified by @rahulguptakota, should be more severe, because it seems to imply the need to restart the environment just to get something compiled.

**Comment by jlelong** [comment]
The issue originally described in this thread does not hurt actually and certainly does not prevent from using the extension. So I think @rahulguptakota is facing an other problem.
The issue here is that the time counter is not stopped when compilation fails but this is not related to having a LaTeX process running or not and the LaTeX is actually really killed.

Let us keep track of this issue in #1383.

**Comment by rahulguptakota** [comment]
I think maybe the problem is fixed in the newer version. I am not able to reproduce the exact nature of things again. Earlier, the compilation counter would keep on increasing while compiling buggy tex, and newer builds would not execute. I remember to have seen the counter go as high as 1000 seconds (project takes around 60 seconds to build usually) while clicking on build in the meanwhile wouldn't help or reset the counter as it does now.

**Comment by jotagah** [comment]
After any error, when invoking the compiler I got from LaTeX Workshop output:
[13:50:35] BUILD command invoked.
[13:50:35] Cannot find LaTeX root file.
Same as before. Restartin VS Code to continue. This is an annoying issue.

**Comment by jlelong** [comment]
@jotagah I think your is different from this issue.
Please open a new issue, provide an example to reproduce the problem and post the complete logs of the extension from the time you open the `.tex` file.
