### ISSUE TITLE
Conflicts with another extension `vscode-pdf`

### ISSUE THREAD

**Issue by neilsustc** [James-Yu/LaTeX-Workshop#138]
I installed another extension [vscode-pdf](https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf) to preview PDF files which are not from my own LaTeX project.

But after I installed the extension, the command `LaTeX Workshop: view PDF file in new tab` won't work any more.

```
PDF.js v1.5.188 (build: 0e2d50f)
Message: file origin does not match viewer's
```

And it would be ideal that you two can get contacted. Since vscode supports extension dependency, you can merge part of your codes for PDF viewing into that extension.

**Comment by James-Yu** [comment]
It's not likely for us to adapt to specific extensions explicitly.

**Comment by neilsustc** [comment]
OK, I just personally think that it would be better to let pdf previewing become a more general feature. 😞 

And I respect you decision. Thank you.
