### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MaiSao** [James-Yu/LaTeX-Workshop#1384]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.5.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Sao\James-Yu.latex-workshop-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by trevorgunn** [comment]
Please attach the `cpuprofile` file as it says. Also please read the [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) as it describes some known issues. Lastly, please try to describe what it is your are trying to do that is causing the performance issues.

**Comment by jlelong** [comment]
The issue does not contain any description of the problem. I am closing it until more information is provided.
