### ISSUE TITLE
File path can't include non English char: inconsistent behavior between manual and auto build

### ISSUE THREAD

**Issue by kduxin** [James-Yu/LaTeX-Workshop#1385]
I encountered the problem that path can not include non English characters like Chinese today. And I found that the "manual build" behaves the way different from "build on file changed / on save". 
Here "manual build" means build the file by clicking on the "Recipe: xelatex" button as in the figure below:
![image](https://user-images.githubusercontent.com/24538421/57966518-e3c1f680-798d-11e9-8a5e-14f0658671ce.png)

I do check the former issues about the problem . And I succeeded to avoid the compilation error if
(1) I change all the %DOC% to %DOCFILE% in "latex-workshop.latex.tools" setting
(2) Build by "manual build"

But I still can not build by "build on file changed" even if I do the modification as in (1) above, because it leads to the error:
![image](https://user-images.githubusercontent.com/24538421/57966533-2b488280-798e-11e9-9690-6c0fbe053f7e.png)
which is as if I haven't done modification (1).

So I wonder if the behavior of these two build ways "manual build" and "build on file changed" are different. Could someone help?

**Comment by jlelong** [comment]
Build on file change actually calls a recipe. What are the values of the three variables
- `latex-workshop.latex.recipes`
- `latex-workshop.latex.tools`
- `latex-workshop.latex.recipe.default`

**Comment by kduxin** [comment]
> Build on file change actually calls a recipe. What are the values of the three variables
> 
> * `latex-workshop.latex.recipes`
> * `latex-workshop.latex.tools`
> * `latex-workshop.latex.recipe.default`

-----------
`latex-workshop.latex.recipes` : 
    "latex-workshop.latex.recipes": [
        {
            "name": "xelatex",
            "tools": [
                "xelatex"
            ]
        },
        {
            "name": "la->bib->la->la",
            "tools": [
                "latexmk",
                "bibtex",
                "latexmk",
                "latexmk",
            ]
        },
        {
            "name": "xe->bib->xe->xe",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex",
                "xelatex",
            ]
        }
    ],

-------
`latex-workshop.latex.tools` :
    "latex-workshop.latex.tools": [
        {
          "name": "latexmk",
          "command": "latexmk",
          "args": [
          "-synctex=1",
          "-interaction=nonstopmode",
          "-file-line-error",
          "-pdf",
          "%DOC%"
          ]
        },
        {
          "name": "xelatex",
          "command": "xelatex",
          "args": [
          "-synctex=1",
          "-interaction=nonstopmode",
          "-file-line-error",
          "%DOC%"
            ]
        },          
        {
          "name": "pdflatex",
          "command": "pdflatex",
          "args": [
          "-synctex=1",
          "-interaction=nonstopmode",
          "-file-line-error",
          "%DOC%"
          ]
        },
        {
          "name": "bibtex",
          "command": "bibtex",
          "args": [
          "%DOCFILE%"
          ]
        }
      ],
--------
for `latex-workshop.latex.recipe.default`, I used both 'first' and 'lastUsed',
but they didn't work.

**Comment by jlelong** [comment]
I cannot reproduce the issue. 
Post the complete logs of the extension when both auto and manual builds are triggered.

**Comment by kduxin** [comment]
> I cannot reproduce the issue.
> Post the complete logs of the extension when both auto and manual builds are triggered.

I'm using window 10. And the folder path is 
`D:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案`

Below is the tex doc:
`
\documentclass[11pt]{book} 
\begin{document}
It's a strange bug!
\end{document}
`

If I build manually, it succeeds. Log:
`
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex 2019.5.10)  22 MAY 2019 19:19
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**test
(./test.tex
LaTeX2e <2018-12-01>
(d:/texlive/2019/texmf-dist/tex/latex/base/book.cls
Document Class: book 2018/09/03 v1.4i Standard LaTeX document class
(d:/texlive/2019/texmf-dist/tex/latex/base/bk11.clo
File: bk11.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count80
\c@chapter=\count81
\c@section=\count82
\c@subsection=\count83
\c@subsubsection=\count84
\c@paragraph=\count85
\c@subparagraph=\count86
\c@figure=\count87
\c@table=\count88
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
No file test.aux.
\openout1 = `test.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
[1

] (./test.aux) ) 
Here is how much of TeX's memory you used:
 224 strings out of 492922
 2400 string characters out of 6136751
 64272 words of memory out of 5000000
 4358 multiletter control sequences out of 15000+600000
 3656 words of font info for 16 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 22i,4n,19p,120b,145s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on test.pdf (1 page).
`

while it fails when I build in auto mode (on save):
`
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex 2019.5.10)  22 MAY 2019 19:20
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**d:/Dropbox/meko/ȩ±¨/¥ǥ¸¥¿¥뼘·wϰ²ᵰ°¸/¥ǥ¸¥¿¥뼘·wϰ²ᵰ°¸/test

! Emergency stop.
<*> ...meko/ȩ±¨/¥ǥ¸¥¿¥뼘·wϰ²ᵰ°¸/¥ǥ¸¥¿¥뼘·wϰ²ᵰ°¸/test
                                                  
*** (job aborted, file error in nonstop mode)

 
Here is how much of TeX's memory you used:
 3 strings out of 492922
 64 string characters out of 6136751
 64272 words of memory out of 5000000
 4153 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 0i,0n,0p,1b,6s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.
`

**Comment by kduxin** [comment]
> I cannot reproduce the issue.
> Post the complete logs of the extension when both auto and manual builds are triggered.

It seems the paths of these two builds do differ:
1) the path on manually build:
``` ./test.tex```
2) the path on auto build:
``` d:/Dropbox/meko/ȩ±¨/¥ǥ¸¥¿¥뼘·wϰ²ᵰ°¸/¥ǥ¸¥¿¥뼘·wϰ²ᵰ°¸/test```

**Comment by jlelong** [comment]
I need the logs of the extension not of the compiler.

![48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76](https://user-images.githubusercontent.com/2910140/58172914-28a1a200-7c9a-11e9-996c-424e3838d2c1.png)

**Comment by kduxin** [comment]
> I need the logs of the extension not of the compiler.
> 
> ![48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76](https://user-images.githubusercontent.com/2910140/58172914-28a1a200-7c9a-11e9-996c-424e3838d2c1.png)

[20:17:32] Initializing LaTeX Workshop.
[20:17:32] Creating LaTeX Workshop http and websocket server.
[20:17:32] LaTeX Workshop initialized.
[20:17:32] Found root file from active editor: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:34] Root file changed from: undefined. Find all dependencies.
[20:17:34] Instantiating a new file watcher for d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:34] Parsing d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:34] Cannot find file d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.fls
[20:17:34] Server created on 127.0.0.1:50319
[20:17:34] Found root file from active editor: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:34] Found root file from active editor: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:34] Root file remains unchanged from: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex.
[20:17:34] Root file remains unchanged from: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex.
[20:17:34] Snippet data loaded.
[20:17:34] LaTeX Workshop version: 7.0.0
[20:17:55] Parsing d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:55] Cannot find file d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.fls
[20:17:55] File watcher: responding to change in d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:55] d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex changed. Auto build project.
[20:17:55] BUILD command invoked.
[20:17:55] Building root file: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:55] Build root file d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:55] Found TeX program by magic comment: xelatex
[20:17:55] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,d:/Dropbox/meko/情报/デジタル回路练习册答案/デジタル回路练习册答案/test
[20:17:55] LaTeX build process spawned. PID: 2968.
[20:17:56] Recipe returns with error: 1/null. PID: 2968.
[20:17:56] Cleaning auxillary files and retrying build after toolchain error.
[20:17:56] CLEAN command invoked.
[20:17:56] Found root file from active editor: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:56] Root file remains unchanged from: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex.
[20:17:56] Found root file from active editor: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex
[20:17:56] Root file remains unchanged from: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\test.tex.
[20:17:56] File cleaned: d:\Dropbox\meko\情报\デジタル回路练习册答案\デジタル回路练习册答案\texput.log
[20:17:56] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,d:/Dropbox/meko/情报/デジタル回路练习册答案/デジタル回路练习册答案/test
[20:17:56] LaTeX build process spawned. PID: 8064.
[20:17:57] Recipe returns with error: 1/null. PID: 8064.
[20:18:01] ACTIONS command invoked.
[20:18:06] LOG command invoked.
[20:19:16] LOG command invoked.
[20:19:19] LOG command invoked.

Do you mean this?

**Comment by jlelong** [comment]
From the logs, you have magic comment `%TEX program = xelatex`, auto build uses this rule.
But when you click on `Recipe: xelatex` in the left panel, you bypass the magic comment and directly call the `xelatex` recipe  as defined in the configuration you posted above.

You should either remove your magic comment or properly define its arguments using `% !TEX options`, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments).

**Comment by jlelong** [comment]
Can you confirm that your issue is fixed?

**Comment by kduxin** [comment]
> Can you confirm that your issue is fixed?

Oh sorry for the late reply. 
Removing the magic comment does work!!
Thanks for you help :)
