### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by newmrdenis** [James-Yu/LaTeX-Workshop#1388]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.5.1`
- OS Version: `Linux x64 4.18.0-18-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/den/James-Yu.latex-workshop-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jlelong** [comment]
Please read the [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ), attach the `cpuprofile` and describe a bit how it occurs.

**Comment by memeplex** [comment]
I'm not seeing anything like this.

**Comment by jlelong** [comment]
The issue does not contain any description of the problem. I am closing it until more information is provided.
