### ISSUE TITLE
Visual Studio Code requires a lot of processing power after creating a LaTeX document

### ISSUE THREAD

**Issue by DFelten** [James-Yu/LaTeX-Workshop#139]
After the LaTeX document has been created, Visual Studio Code still requires a lot of processing power. The processing power remains so high for 5 minutes every time a document is generated.

![image](https://cloud.githubusercontent.com/assets/1169185/26096614/075f32d6-3a22-11e7-9441-9b30366a70c0.png)

This is the latex workshop log:
> [10:19:19] Found root file by magic comment: c:\Users\Daniel\Dokument\main.tex
> [10:19:19] Root file remains unchanged from: c:\Users\Daniel\Dokument\main.tex.
> [10:19:19] Found root file by magic comment: c:\Users\Daniel\Dokument\main.tex
> [10:19:19] Root file remains unchanged from: c:\Users\Daniel\Dokument\main.tex.
> [10:19:32] Found root file by magic comment: c:\Users\Daniel\Dokument\main.tex
> [10:19:32] Root file remains unchanged from: c:\Users\Daniel\Dokument\main.tex.
> [10:19:37] BUILD command invoked.
> [10:19:37] Found root file by magic comment: c:\Users\Daniel\Dokument\main.tex
> [10:19:37] Root file remains unchanged from: c:\Users\Daniel\Dokument\main.tex.
> [10:19:37] Building root file: c:\Users\Daniel\Dokument\main.tex
> [10:19:37] Build root file c:\Users\Daniel\Dokument\main.tex
> [10:19:37] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,c:\Users\Daniel\Dokument\main
> [10:20:36] LaTeX log parsed with 61 messages.
> [10:20:36] Toolchain of length 1 finished.

This is my .latexmkrc for the glossaries
```
add_cus_dep( 'glo', 'gls', 0, 'makeglossaries' );
sub makeglossaries {
  system( "makeglossaries \"$_[0]\"" );
}
```

I thought maybe it's chktex, but I've disabled it. I also noticed that often a reboot of Visual Studio is necessary, since latex workshop is hanging up.

**Comment by James-Yu** [comment]
This is not an extension-related problem. There is no background actions by the extension which do not have log messages. It looks like `latexmk` uses one full minute to generate the pdf, which can be the problem.

**Comment by DFelten** [comment]
So Latexmk is still running minutes after the creation of the document? If latexmk is executed manually with the shell, the workload is only available during the creation. This means only the one minute and not five minutes longer.
