### ISSUE TITLE
Tooltips show wrong shortcuts for the extension commands

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1390]
I don't think this report needs further details because it's such a trivial detail: on the activity bar the hover tooltip for all entries shows the respective name, except for the TeX one, which says: LaTeX (Ctrl+L Alt+X). This seems wrong to me in two ways:

1. The key sequence is probably hardcoded into the name and doesn't follow what seems to be the norm.
2. LaTeX Actions is not bound to that key sequence in any case, it's unbound by default, at least in my setup.

**Comment by James-Yu** [comment]
It is not hardcoded, but instead an upstream problem with respect to vscode. You may inspect the `view` sections in `package.json` for details.

**Comment by jlelong** [comment]
There are several problems here
- The command associated to the `TeX` badge is `workbench.view.extension.latex`, which is not a _toogle_ command as for all the other icons the Activity Panel
- The command `workbench.view.extension.latex` is associated to two entries in `package.json`
    ````
      {
        "key": "ctrl+alt+x",
        "mac": "cmd+alt+x",
        "command": "workbench.view.extension.latex",
        "when": "editorTextFocus && !latex-workshop:altkeymap"
      },
    ````
   and
   ````
      {
        "key": "ctrl+l alt+x",
        "mac": "cmd+l alt+x",
        "command": "workbench.view.extension.latex",
        "when": "editorTextFocus && latex-workshop:altkeymap"
      },
   ````
   The last entry takes precedence, which explains the shortcut despite the default value for `latex-workshop:altkeymap` is `false`. 

    This precise problem occurs with all duplicated entries as _Build LaTeX project_ for instance
![Capture d’écran 2019-05-20 à 09 12 15](https://user-images.githubusercontent.com/2910140/58002735-7b832a00-7adf-11e9-8661-eb60cf2a4942.png)

To fix all this, I suggest
- [ ] To reorder all duplicated entries in order to make the one associated with `!latex-workshop:altkeymap` appear last
- [ ] To turn `workbench.view.extension.latex` into a toggle function and make the shortcut available no matter the value of `editorTextFocus`.

@James-Yu what do you think of this?

**Comment by James-Yu** [comment]
I've reordered all the alt keymaps.

The tooltip issue might be more complex than it looks. I have several observations:
- The tooltip will show the keybind if defined, see the default ones (explorer, debug, etc.) as examples.
- The keybind in the tooltip is refreshed upon reloading the window, not upon keybind changes.
- The keybind in the tooltip always show the last definition according to the order in `Keyboard Shortcuts`, no matter the condition, see `Show SCM` as an example with GitLens installed which override the binding with `Ctrl+Shift+G G`.

Therefore, we have two imperfect solutions in my view:
1. remove the keybindings for the command. It won't show anything in the tooltip, and is in accordance with many other extensions.
2. Use non-alt-keymap in the tooltip, which has been achieved in the last commit. The issue rises when altkeymap is true.

A side-thought inspired by GitLens. They directly use `config.gitlens.keymap=='chorded'` as key binding condition. Is that doable in our case?

**Comment by memeplex** [comment]
I'm not sure this is related, but the Ctrl+L Alt+V shortcut announced by the "View LaTeX PDF File" icon tooltip is not working for me either. In the statusbar the message "The key combination Ctrl+L Alt+V is not a command" appears.

**Comment by memeplex** [comment]
Ok, I realized there is a toggle for the alt keymap, it just that the tooltips are all assuming this is the active keymap when the fact is that it's not.

**Comment by jlelong** [comment]
I vote for solution 2. It would be sufficient to add a note in the wiki concerning the alternate keymap. I agree that solution 1 would not hurt for the badge command but we would still be left with the issue for all other commands in the Command Palette.

> A side-thought inspired by GitLens. They directly use `config.gitlens.keymap=='chorded'` as key binding condition. Is that doable in our case?

I do not really understand what you mean by that.

**Comment by James-Yu** [comment]
We are using `"when": "latex-workshop:altkeymap"` for the commands, and have
```
    if (configuration.get('bind.altKeymap.enabled')) {
        vscode.commands.executeCommand('setContext', 'latex-workshop:altkeymap', true)
    } else {
        vscode.commands.executeCommand('setContext', 'latex-workshop:altkeymap', false)
    }
```
which seems 1) unnecessary, 2) cannot update until reload.

May we also follow the other's pattern and use sth like `bind.altKeymap.enabled==true`? Will there be some other issues that I'm not aware of?

**Comment by memeplex** [comment]
Does this mean that now the tool tip will always show the non alt keymap, no matter what the actual keymap is?

**Comment by James-Yu** [comment]
afaik, yes. I'm not aware of solutions to this problem from the extension side.

**Comment by jlelong** [comment]
I guess we have improved tooltips the best we could.
