### ISSUE TITLE
PDF with FiraMath font can't be rendered properly

### ISSUE THREAD

**Issue by stone-zeng** [James-Yu/LaTeX-Workshop#1392]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**

When using [FiraMath](https://github.com/firamath/firamath) (dev version), the curly brackets get broken in PDF viewer.

Note that only the develop version will trigger the issue: [FiraMath-Regular.otf.zip](https://github.com/firamath/firamath/files/3203154/FiraMath-Regular.otf.zip)

**To Reproduce**

1. Write the following code:

```latex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{FiraMath-Regular.otf}  % Use dev version

\begin{document}
\[ \{ \} \]
\end{document}
```

2. Use Cmd+Opt+B to compile (use xelatex via latexmk). Part of the configurations are

```json
"latex-workshop.latex.tools": [
    {
        "name": "latexmk",
        "command": "latexmk",
        "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-xelatex",
            "-outdir=%OUTDIR%",
            "%DOC%"
        ],
        "env": {}
    }
]
```

3. View the PDF in a vscode tab.

**Expected behavior**

Actually, there is a pair of `{ }` in the PDF file, but just can't be shown in the default PDF viewer of latex-workshop.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

I use `$PATH$` instead of the real path here.

LaTeX Compiler:

```txt
Latexmk: This is Latexmk, John Collins, 17 March 2019, version: 4.63b.
Rule 'xdvipdfmx': The following rules & subrules became out-of-date:
      'xdvipdfmx'
------------
Run number 1 of rule 'xdvipdfmx'
------------
------------
Running 'xdvipdfmx -o "$PATH$/6.pdf"  "$PATH$/6.xdv"'
------------
Latexmk: applying rule 'xdvipdfmx'...
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
$PATH$/6.xdv -> 6.pdf
[1]
3180 bytes written
Latexmk: All targets () are up-to-date
```

LaTeX Workshop:

```txt
[23:01:14] BUILD command invoked.
[23:01:14] Found root file from active editor: $PATH$/6.tex
[23:01:14] Root file remains unchanged from: $PATH$/6.tex.
[23:01:14] Building root file: $PATH$/6.tex
[23:01:14] Build root file $PATH$/6.tex
[23:01:14] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-xelatex,-outdir=$PATH$,$PATH$/6
[23:01:14] LaTeX build process spawned. PID: 16598.
[23:01:14] Recipe of length 1 finished. PID: 16598.
[23:01:14] Successfully built $PATH$/6.tex.
[23:01:14] Refresh PDF viewer for $PATH$/6.pdf
[23:01:14] Parsing $PATH$/6.fls to compute dependencies
[23:01:14] Handle data type: position
[23:01:15] Preview PDF file: $PATH$/6.pdf
[23:01:15] Handle data type: loaded
```

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/18233088/58107720-03228300-7c1d-11e9-8790-d40fc42c9b51.png)

In Skim PDF reader:

![image](https://user-images.githubusercontent.com/18233088/58108031-a378a780-7c1d-11e9-9258-3634223a8777.png)

**Desktop [Required]:**
 - OS: macOS Majave 10.14.4 
 - VS Code version: 1.34.0
 - Extension version: 7.0.0

**Additional context**

I'm not sure whether it's a bug of latex-workshop or this font; if it's the later, I will transfer the issue to fira math.

**Comment by trevorgunn** [comment]
The internal viewer is a bundled [pdf.js](https://github.com/mozilla/pdf.js) package. Can you try opening the pdf in Firefox (not Chrome, not Safari [at least I think not Safari]) and see if there's still an issue. Because if so, then it's an issue of pdf.js.

**Comment by jlelong** [comment]
I am closing this as it is not directly related to the extension but either to the `FiraMath` font or `pdf.js`.
