### ISSUE TITLE
PDF invert no longer working after 7.0.0 update on Wins 10

### ISSUE THREAD

**Issue by StevenLi-DS** [James-Yu/LaTeX-Workshop#1395]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]** You still see this issue?: Yes

**Describe the bug [Required]**
PDF invert no longer working from time to time (like after reloading vscode) after 7.0.0 update

![image](https://user-images.githubusercontent.com/33796896/58127560-a3f44c80-7be3-11e9-846c-b1278fb9931b.png)

[-1558470171715.log](https://github.com/James-Yu/LaTeX-Workshop/files/3204368/-1558470171715.log)

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.34.0
 - Extension version: 7.0.0

**Comment by memeplex** [comment]
It's working perfectly fine for me with `"latex-workshop.view.pdf.invert": 0.86`

**Comment by StevenLi-DS** [comment]
@memeplex it happens to me yesterday and then for some reason it's back to normal and then happened again today.

**Comment by trevorgunn** [comment]
I can verify that the invert setting works for me in Linux but not in Windows.

**Comment by StevenLi-DS** [comment]
@trevorgunn If I reload vscode, sometimes it works again, but most of the times, it's not.

**Comment by James-Yu** [comment]
Before a stable method of reproducing the problem is found, I cannot debug the problem. You may want to  inspect the developer's console for any log messages suspicious.

**Comment by StevenLi-DS** [comment]
@James-Yu issue was also found by @trevorgunn as well. I indeed attached all the logo found in the console. The stable method to reproduce is double click a .tex file and then toggle View LaTex PDF and then pdf color will not invert.

**Comment by trevorgunn** [comment]
Two things:

1. Between 6.5.1 and 7.0.0 I've found that the `wsServer` no longer sends a message of `loaded` when the page is loaded, causing the value of `view.pdf.invert` never to be sent to the web page. I.e. https://github.com/James-Yu/LaTeX-Workshop/blob/14f188ad7c2e362405256c3f0bb8d2f3443b7e4c/src/components/viewer.ts#L215 is never reached and therefore neither is line 232.

2. When you open the pdf url in Firefox, rather than in VS Code, somehow it works:

![Capture](https://user-images.githubusercontent.com/7917549/58148165-a2e70d80-7c2b-11e9-892e-eda116513c82.PNG)

I'm not sure what to make of this.

**Comment by trevorgunn** [comment]
I've figured out that changing line 127 of `viewer.ts` https://github.com/James-Yu/LaTeX-Workshop/blob/14f188ad7c2e362405256c3f0bb8d2f3443b7e4c/src/components/viewer.ts#L127 from
```ts
localhost:${this.extension.server.port}
```
to
```ts
${this.extension.server.address}
```
makes colour inversion work again.

This was discussed before in this review: https://github.com/James-Yu/LaTeX-Workshop/pull/1357#pullrequestreview-233721943

I don't know what other effects changing this has.

@tamuratak maybe you know something about this?

**Comment by jlelong** [comment]
@trevorgunn thanks for locating the culprit.
I confirm that it works on OS X too, so this is a Windows only issue. It seems that `localhost` and `127.0.0.1` are not handled the same way under Windows.

**Comment by tamuratak** [comment]
@trevorgunn I have found there has been a bug although I cannot reproduce this issue on my Windows 10 machine. Please confirm that #1402 solves this issue.

**Comment by trevorgunn** [comment]
Yes, #1402 works for me.

**Comment by tamuratak** [comment]
Great. Thanks for your report. It helped us a lot.

**Comment by StevenLi-DS** [comment]
It was fixed for me. but I just installed an extension and then uninstalled it, which requires reloading vscode and then the pdf invert stopped working again... am i missing something?

**Comment by tamuratak** [comment]
The fixed version of LaTeX Workshop has not been released yet. Please wait for a while.
