### ISSUE TITLE
Ill-formatted compilation results

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1396]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

The alignment of compilation time is wrong for "Page 1 + Preamble". I assume this is due to the length of this entry compared with others' (Page 2, Page 3, etc).

This is a minor, aesthetic, issue. I believe a screenshot and a brief description are enough, let me know if you need logs. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2845433/58128984-2a625b80-7bef-11e9-8615-e8e66da093e9.png)

**Desktop [Required]:**

- OS: Arch Linux
- VS Code version: 1.34.0
- Extension version: 7.0.0

**Comment by trevorgunn** [comment]
I'm not sure how to reproduce this:

![Capture](https://user-images.githubusercontent.com/7917549/58136288-8d59ef80-7bfb-11e9-83e2-a0ed69bf134e.PNG)

**Comment by tecosaur** [comment]
Yep, this is me again. I'd say this is due to your screen being smaller than mine when I tested this, I'll take a look in the near future (probably this weekend or next week).

**Comment by memeplex** [comment]
I'm on my laptop so, yes, it's a small screen. Anyway, if I maximize the compilation info window I get the same result.

**Comment by tamuratak** [comment]
@tecosaur please don't forget this problem.

**Comment by tecosaur** [comment]
Ooops. I had — sorry. I'll try tweaking the sizing at some point over the weekend.

@jlelong feel free to straight up assign issues like this (anything related to any features from me) to me.

**Comment by tecosaur** [comment]
Gah. Once again I forgot. Erm I'll remember at a good time (when I can actually do something) _soon_. Probably. Hopefully. Eventually.

I'll see if I can set a reminder for ~20h or ~36h to (finally) get this done.

**Comment by tecosaur** [comment]
@memeplex sorry about the delay. Let me know if #1510 makes enough space for the text to fit on one line, or if I need to add a bit more.
