### ISSUE TITLE
Wrong figure caption in Structure and Outline views

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1397]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

Some figure captions like:

```
  \caption{$-p^*(\theta^\ast)$ is the intercept of a supporting hyperplane of
    $\epi p$.}
```

or 

```
  \caption{$p^{**}$ results from the convex closure of $\epi p$.}
```

are wrongly parsed by LaTeX Workshop. It's not difficult to infer what might be wrong:

1. In the first case no caption is shown in the outline, probably the parser is expecting a closing `}` in the same line, which it's not always the case.

2. In the second case the caption shown is `$p^{**`, which is probably because the parser takes the closing `}` for the superindex as a closing `}` for the caption. If the parser is a regex it's not possible to support nesting of arbitrary depth, of course, but maybe supporting up to 2 or 3 levels would solve any practical case.

**Expected behavior**

Full caption is shown both in Outline and in Structure views.

**Desktop [Required]:**
 - OS: Arch Linux
 - VS Code version: 1.34.0
 - Extension version: 7.0.0

**Comment by jlelong** [comment]
Now, caption supports multiline and one level of nested `{...}`. Adding one extra level really enlarges the regex and maintenance becomes a pain. So I prefer to restrict it to one level for now and we will see.
