### ISSUE TITLE
Log level doesn't work as expected

### ISSUE THREAD

**Issue by neilsustc** [James-Yu/LaTeX-Workshop#14]
At first, with the default settings, I got this result
```
Step 1: xelatex  "report1"
Step 2: bibtex "report1"
Step 3: xelatex  "report1"
Step 4: xelatex  "report1"

------------
LaTeX Log Parser Result
[T][undefined:39] Overfull \hbox (1.66997pt too wide) in paragraph at lines 39--40
```
So I went to the settings and set log level to error (I think the output above is a warning), and then I got this
```
Step 1: xelatex  "report1"
Step 2: bibtex "report1"
Step 3: xelatex  "report1"
Step 4: xelatex  "report1"

------------
LaTeX Log Parser Result
```
What matters is that the output panel will **still** be brought out to the front

**Comment by James-Yu** [comment]
Log level is defined as [E]rror > [W]arning > [T]ypesetting. So setting log level to `error` will surpress warnings and typesetting infos. That's why the only log message disappear.

The output panel will pop out no matter if there's any parser messages. Do you think this should get an update?

**Comment by neilsustc** [comment]
My fault, I didn't express clearly. There is nothing wrong with the output message, it's about the output panel. I will comment again soon to describe what I expect (after my dinner). Thanks for your reply.

**Comment by neilsustc** [comment]
With the output panel closed by default, the current behaviors are
- If there is no error or warning, everything works well, and the output panel **won't pop out**
- If there is a warning, **although** the log level is `error`, the output panel **will pop out**.
But as I expect, if I decide to suppress warning by setting log level to `error`, it should behave just like that in the first situation (output panel don't pop out).

Below is a GIF that shows the inconsistent behaviors between that 2 situations. (The commented line will cause a warning)
![latex-workshop-test](https://cloud.githubusercontent.com/assets/7588612/23092636/74554d00-f60a-11e6-972e-eb3569398f81.gif)

**Comment by James-Yu** [comment]
Thanks for the detailed description. This should be fixed shortly.

**Comment by James-Yu** [comment]
Please try out the new version `0.2.15` and see if issue persists.

**Comment by neilsustc** [comment]
Awesome 👍 
And there is another issue, it seems that sometimes the preview is not fully reload, so it looks a mess. (If you close the preview page and reopen it by clicking the top-right `Show Preview` button, it solves.)
Note that I haven't found a 100% reproduce steps, but it often happens.
Sometimes it's when you comment out a line, but sometimes it's when you uncomment a line.
My settings are as below
```
"latex-workshop.compile_argument": "",
"latex-workshop.compiler": "xelatex",
"latex-workshop.log_level": "error"
```
![latex-workshop-reload-issue](https://cloud.githubusercontent.com/assets/7588612/23099189/ebe22726-f69b-11e6-8822-837701e73c92.gif)

**Comment by James-Yu** [comment]
It seems like a bug of [PDF.js lib](https://github.com/mozilla/pdf.js/). Yet I cannot fix the problem. Maybe you may try `pdflatex` and see if problem persists. It works fine for me.

**Comment by neilsustc** [comment]
👌
