### ISSUE TITLE
Math preview has unwanted "\ddager" displayed 

### ISSUE THREAD

**Issue by xiaoweiz** [James-Yu/LaTeX-Workshop#1401]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
If the cursor is in the math environment *and* is not inside a math command leading with the backslash `\`, the math preview would show an unwanted symbol $\ddagger$. The location of the double dagger in the math preview depends on the location of the cursor. This is better explained in the following screenshots. 

1. The cursor is before the backslash (i.e., outside a math command), then double dagger appears
<img width="210" alt="Screen Shot 2019-05-22 at 11 49 21 AM" src="https://user-images.githubusercontent.com/4540215/58146380-6695ca80-7c88-11e9-8f24-d34cc26c4410.png">

2. The cursor is after the backslash but inside the command `\alpha`, then the preview is fine
<img width="203" alt="Screen Shot 2019-05-22 at 11 52 16 AM" src="https://user-images.githubusercontent.com/4540215/58146421-a52b8500-7c88-11e9-92d5-a5c9b34dbc2b.png">

3. The cursor is after `\alpha` (i.e., outside a math command)
<img width="205" alt="Screen Shot 2019-05-22 at 11 52 33 AM" src="https://user-images.githubusercontent.com/4540215/58146447-bd9b9f80-7c88-11e9-85b4-a75ba831730e.png">

4. This erratic behavior appears to be linked to math commands leading with the backslash. For example, if the cursor is placed inside a number, the bug shows. 
<img width="269" alt="Screen Shot 2019-05-22 at 12 03 49 PM" src="https://user-images.githubusercontent.com/4540215/58146733-ec664580-7c89-11e9-8c3f-0da789420459.png">

5. However, if the cursor is outside the math environment, things go back to normal. 
<img width="210" alt="Screen Shot 2019-05-22 at 12 00 04 PM" src="https://user-images.githubusercontent.com/4540215/58146542-2aaf3500-7c89-11e9-970a-2563572cd06d.png">

**Expected behavior**
No extra double dagger appears in the math preview.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

No.

**Desktop [Required]:**
 - OS: [e.g. macOS Mojave]
 - VS Code version: [e.g. 1.34.0]
 - Extension version: [e.g. 7.0.0]

**Comment by James-Yu** [comment]
It indicates your cursor position. You can disable that in the config.
