### ISSUE TITLE
[Question] Finding the right syntax category

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1403]
I use Tomorrow Night theme and I'm pretty happy with it except for my heavy-math LaTeX documents which are full of orange:

![image](https://user-images.githubusercontent.com/2845433/58222676-37fe0b00-7ced-11e9-9e42-f313eb38f879.png)

Now, I realized one can override colors for categories in the TextMate grammar like this:

```
    "editor.tokenColorCustomizations": {"textMateRules": [{
        "scope": "keyword.control.ref.latex",
        "settings": {
            "foreground": "#FF0000"
        }
    }]},
```

But I'm still having a hard time locating the right categories in [the grammar](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX.plist). The xml syntax is terrible to scan.

Could you help me a bit identifying the right syntactical classes?

Thank you very much in advance.

**Comment by tamuratak** [comment]
Menu > View > Command Palette > Type `Developer: Inspect TM Scopes`

Then, you can see the following information.

<img width="725" alt="2019-05-23 12 12 02" src="https://user-images.githubusercontent.com/10665499/58223317-1c7a1b00-7d54-11e9-87af-38d75f2f422a.png">

- https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#tokens-and-scopes
- https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

**Comment by memeplex** [comment]
This is great, much more that I expected, thanks!​
