### ISSUE TITLE
Structure of .tex file is not complete

### ISSUE THREAD

**Issue by HUA-USA** [James-Yu/LaTeX-Workshop#1404]
The .tex file structure on the structure panel shows only first several sections.

**Comment by jlelong** [comment]
Post a MWE to reproduce.

**Comment by jlelong** [comment]
The issue does not contain enough information to investigate the problem. I am closing it until more information is provided.

**Comment by HUA-USA** [comment]
I found out the problem appears when I include .tex source file in the listings environment.

Please see this MWE:

\documentclass{article}
% General document formatting
\usepackage[margin=0.7in]{geometry}
\usepackage[parfill]{parskip}
\usepackage[utf8]{inputenc}

\usepackage{listings}

% Related to math
\usepackage{amsmath,amssymb,amsfonts,amsthm}

\begin{document}

Minimal Working Examples

\section{Part a}

\begin{lstlisting}[caption=Minimal Working Exmaple]
\documentclass{article}
% General document formatting
\usepackage[margin=0.7in]{geometry}
\usepackage[parfill]{parskip}
\usepackage[utf8]{inputenc}
    
% Related to math
\usepackage{amsmath,amssymb,amsfonts,amsthm}

\begin{document}

Minimal Working Examples

\section{Part a}


\end{document}
\end{lstlisting}

\section{Part b}

etc

\end{document}
