### ISSUE TITLE
Math preview using external file fails if the file contains comments (%)

### ISSUE THREAD

**Issue by xiaoweiz** [James-Yu/LaTeX-Workshop#1405]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
The parser for the external file containing customized macros can be improved. If the external file contains symbol `%`, the math preview would be blank. 

<img width="1030" alt="Screen Shot 2019-05-24 at 11 31 08 AM" src="https://user-images.githubusercontent.com/4540215/58301042-8d363b80-7e17-11e9-9ffd-2edfb32ecc93.png">

Deleting the comments in the external file fixes the issue. 
<img width="1035" alt="Screen Shot 2019-05-24 at 11 33 12 AM" src="https://user-images.githubusercontent.com/4540215/58301109-beaf0700-7e17-11e9-923b-0ec2aa18e210.png">

**Expected behavior**
Better parser for the external file that discards comments (starting with `%`)

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.
No.

**Desktop [Required]:**
 - OS: [e.g. macOS Mojave]
 - VS Code version: [e.g. 1.34.0]
 - Extension version: [e.g. 7.0.0]

**Comment by jlelong** [comment]
I cannot reproduce the issue. Comments in the file named in `latex-workshop.hover.preview.newcommand.newcommandFile` does not hurt `mathjax` for me.

**Comment by tamuratak** [comment]
I can reproduce it. If the last line of `newcommandFile` is commented out and does not end with a line break, a TeX string to be rendered itself will be commented out.

**Comment by jlelong** [comment]
Even like this I cannot reproduce the issue on OSX but anyway, would it be sufficient to replace 
````ts
return commandsString + commands.join('')
````
by
````
return commandsString + '\n' + commands.join('')
````
in [`hover.ts#L147`](https://github.com/James-Yu/LaTeX-Workshop/blob/d012470682ab1b657e77bea5d13d0364bd8aede0/src/providers/hover.ts#L147)?

**Comment by tamuratak** [comment]
Yes, it is sufficient.
