### ISSUE TITLE
Make Ctrl-Alt-J jump to the previewer

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1407]
**Describe the solution you'd like**

This may not be possible according to some conversation we recently had here, but anyway...

When in the previewer Ctrl-click not only syncs the editor position but also the editor is shown and given focus. But, rather asymmetrically, Ctrl-Alt-j in the editor doesn't bring the previewer to the front when it's currently not visible.

I would like that the feature worked both ways. Not only for the sake of consistency but because it would be quite helpful and complementary to my request https://github.com/James-Yu/LaTeX-Workshop/issues/1406 in the sense that I could keep the previewer hidden most of the time and just make it popup when needed, then go back to the editor by Ctrl-clicking.

**Comment by jlelong** [comment]
It seems to that we are facing a limitation of VSCode's API, which does not allow an extension to access the list of open editors, see microsoft/vscode/issues/15178. So there is no way to bring a specific editor (in our case the tab embedding the PDF viewer) to the front.
