### ISSUE TITLE
Index style file -o .nls not found.

### ISSUE THREAD

**Issue by BjoernDaase** [James-Yu/LaTeX-Workshop#1408]
0. Running `makeindex thesis.nlo -s nomencl.ist -o thesis.nls` via commandline works perfectly fine without any errors. Running `pdflatex` afterwards creates an index as expected.

1. Add the following step to your build toolchain
```

 {
            "name": "makeindex",
            "command": "makeindex",
            "args": [
                  "%DOCFILE%.nlo",
                  "-s nomencl.ist",
                  "-o %DOCFILE%.nls"
            ]
}
```
to have `makeindex` working (I followed #384).
2. Run a recipe containing this step
```
{
            "name": "pdflatex ➞ bibtex ➞ makeindex ➞ pdflatex ➞ pdflatex",
            "tools": [
              "pdflatex",
              "bibtex",
              "makeindex",
              "pdflatex",
              "pdflatex"
            ]
}
```
3. Result
```
Index style file -o thesis.nls not found.
Usage: makeindex [-ilqrcgLT] [-s sty] [-o ind] [-t log] [-p num] [idx0 idx1 ...]
```

**Expected behavior**
I get no error and the building proceeds.

**Desktop [Required]:**
 - OS: Arch Linux
 - VS Code version:
1.34.0
a622c65b2c713c890fcf4fbf07cf34049d5fe758
x64
 - Extension version: 7.0.0

**Comment by jlelong** [comment]
I think you need to split `"-s nomencl.ist"` into two arguments, the same for `-o %DOCFILE%.nls`. If it does not help, please post the complete logs of the extension.

**Comment by BjoernDaase** [comment]
@jlelong Ahhh...
That's kind of unintuitive but works perfectly.

**Comment by jlelong** [comment]
This is because every entry inside `args` is automatically surrounded by an extra pair of quotes when passed to the `spawn` function.

**Comment by Hogeback** [comment]
I have the same problem.

But i dont know how to split the args entry into two arguements
