### ISSUE TITLE
Cool looking changelog

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1409]
Just noticed how slick the Material Theme's 'I've just updated' page is.

![image](https://user-images.githubusercontent.com/20903656/58377516-3b2b1c80-7fb5-11e9-9c03-80599d1cab78.png)

In a few weeks when I have some time I may look at what they're doing and potentially create a PR.
In the meantime, I thought I'd just put the idea here.

**Comment by jlelong** [comment]
@tecosaur I had a quick look at how Materiel Theme produces their changelog. They ship a `js` file and a `html` file to render all the changes, which are not kept in a `CHANGELOG.md` file anymore. I think this is important for developers to have a `CHANGELOG.md` file. If we really want to improve the look of the changelog, we could use a template engine as `Jekyll` for instance to nicely render the `.md` file and include the generated `.html` and `.css` in each release. This means some extra effort to produce the release. We could also render it in some GitHub pages and just show the remote page inside VSCode.
I am still not sure this is worth it.

**Comment by tecosaur** [comment]
@jlelong Hmmm. Doesn't sound like something worth the effort like that.
Perhaps it would be possible to have some simple parsing of the `.md` file with which an html file is created
(on the user's machine). I may end up taking a look at this approach next week.

**Comment by jlelong** [comment]
@tecosaur There are many `js` libraries to convert `.md` to `.html` so it should be fairly easy to generate an `html` view of the changelog on user's demand.

**Comment by jlelong** [comment]
Considering the above discussion on the effort required to improve the changelog look, I am closing this issue. If you ever come up with a solution, I would be happy to handle a PR.
