### ISSUE TITLE
[Enhancement]: Autocomplete should add Automatically an item to enumerate, itemize and description lists

### ISSUE THREAD

**Issue by zyrikby** [James-Yu/LaTeX-Workshop#141]
Currently,  when you create a new list, autocomplete automatically creates the following construction:
```latex
\begin{itemize}
  
\end{itemize}
```

It would be nice if autocomplete adds also \item:
```latex
\begin{itemize}
  \item 
\end{itemize}
```

**Comment by James-Yu** [comment]
This will be released in the next update.
