### ISSUE TITLE
Disable spell checks in the Problems panel

### ISSUE THREAD

**Issue by albertcthomas** [James-Yu/LaTeX-Workshop#1410]
I would like to disable the spell check errors that appear in the Problems panel after a compilation. Usually they are about correct spellings in a particular domain and over populate the panel.

PS: Thanks for this great vscode extension.

**Comment by James-Yu** [comment]
This extension does not provide spell checking feature. You have others installed.

**Comment by albertcthomas** [comment]
Oups, sorry for my confusion about this. Thanks for the quick response.
