### ISSUE TITLE
First symbol removed from inline preview

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1416]
**Describe the bug [Required]**
First symbol left out of preview.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
Just the standard stuff, i.e.

```
[22:09:20] Linter for active file successfully finished in 0s 76ms
[22:09:20] Linter log parsed with 30 messages.
[22:09:23] Linter for active file started.
[22:09:23] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n1,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m
```

</details>

<details>
<summary>Developer Tools Console [Required]</summary>
Nothing suspicious, and also nothing from latex workshop.

</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/20903656/58749489-9e3b1880-84b9-11e9-82da-e59887c2a91d.png)

![image](https://user-images.githubusercontent.com/20903656/58749554-0db10800-84ba-11e9-80d9-265c5da0a626.png)

**Desktop [Required]:**
 - OS: Linux
 - VS Code version: 1.34.0
 - Extension version: 7.0

**Additional context**

<details>
<summary>latex-workshop.hover.preview.newcommand.newcommandFile contents</summary>

```tex
% \usepackage{etoolbox}
% \usepackage{ctable}
% \usepackage{tabularx}
% \usepackage{multicol}

% \usepackage{graphicx}

% \usepackage{subcaption}
% \usepackage[hypcap=true]{caption}

% \usepackage{fontawesome5}
% \usepackage{infoBulle}
% \usepackage{marginInfoBulle}
% \usepackage{hyperref}

% \DeclarePairedDelimiter{\abs}{\lvert}{\rvert}
% \DeclarePairedDelimiter{\norm}{\lVert}{\rVert}
\newcommand{\abs}[1]{\lvert #1 \rvert}
\newcommand{\norm}[1]{\lVert #1 \rVert}

\newcommand{\R}[1][]{{\mathbb{R}^{#1}}}
\newcommand{\N}[1][]{{\mathbb{N}^{#1}}}
\newcommand{\Z}[1][]{{\mathbb{Z}^{#1}}}
\newcommand{\Q}[1][]{{\mathbb{Q}^{#1}}}
\newcommand{\C}[1][]{{\mathbb{C}^{#1}}}

\newcommand{\dd}[1][]{{\mathrm{d}^{#1}}}
% \DeclareMathOperator{\Lap}{\mathcal{L}}
% \DeclareMathOperator{\Var}{Var} % varience
% \DeclareMathOperator{\Cov}{Cov} % covarience
% \DeclareMathOperator{\E}{E} % expected

% \newcommand*{\qed}{\hfill\ensuremath{\blacksquare}}
% \newcommand*{\qedhere}{\hfill\ensuremath{\square}}

% \let\oldleq\leq % save them in case they're every wanted
% \let\oldgeq\geq
\renewcommand{\leq}{\leqslant}
\renewcommand{\geq}{\geqslant}

\newcommand{\color}[1]{}
\newcommand{\textcolor}[2]{#2}
```

</details>

I'm not sure that I could reproduce this, I'll come back if I can. However I though I may as well put this here because
 - It looks like it's something with the extension
 - If someone else has this issue in the future it may be useful
 - An incomplete error report can be better than none whatsoever

Feel free to imidiately close this, I just though I may as well let you know I've seen this happen.

**Comment by trevorgunn** [comment]
This is the same as #1411 right?

**Comment by tamuratak** [comment]
Please show us the preamble of your TeX file if you do not mind.

**Comment by tecosaur** [comment]
@trevorgunn I saw that issue bit missed Point#4 —oops, though that issue was just about the dagger.

@tamuratak sure, this is what I have.
```tex
%&preamble
\documentclass[solid,sans,chem,math-sans]{bmc}

\titlehead{<titlehead> Notes}
\title{<title>}
\subtitle{<subtitle>}
\author{<name>}

\colorlet{primary}{Green}
\colorlet{secondary}{Blue}
\colorlet{tertiary}{Cyan}

\usepackage{pifont}
\newcommand{\cmark}[1][Green]{\textcolor{#1!60!text}{\ding{51}}}
\newcommand{\xmark}[1][Red]{\textcolor{#1!60!text}{\ding{55}}}

\usepackage{textgreek}

\graphicspath{{./Resources/}}

\pdfcompresslevel=0

\endofdump

\usepackage[automake, acronym, numberedsection=nolabel, style=long3col]{glossaries}
\makeglossaries
```

**Comment by tamuratak** [comment]
Thanks a lot.

However, I cannot reproduce this issue.

**Comment by tecosaur** [comment]
That's fine. Perhaps I'll just close this for now and add to it if I continue having this issue.

**Comment by jlelong** [comment]
See #1428 for an explanation of the problem
