### ISSUE TITLE
New recipie icons

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1418]
Hello,

I've done some more playing around with the recipe names to make them look pretty.
If you like the look of this just say the word and I'll create a PR.
Else just close this issue and ignore me :slightly_smiling_face:

![image](https://user-images.githubusercontent.com/20903656/58757737-09c9c800-8544-11e9-9a0e-4d0ad6fe2709.png)

(Will not include the precompile/compress/sage as they use my-system-specific things)

**Comment by James-Yu** [comment]
I think it looks good!

**Comment by tecosaur** [comment]
I'll look at this next week as in the latest update vscode has changed the widths of the octicons, and I used 1/6em 1/4em and hair width spaces a bit to make them all line up.

The update just missed last weeks package update for my rolling release distro, so I should get that update this weekend.

## Aside

I'm really liking the compress / precompile preamble options for my own documents,
do you think the rest of the community might appreciate them?
I find that the precompile preamble (creates .fmt file) saves me up to ~2 seconds on compilation,
and while for some files compression only makes a ~10% difference for others I shave off up to 80-90% of the size with no noticeable quality degradation.

The issue is I'm while I'm only using latex/system tools, it's Linux specific.
 - Using `sed` for inserting 'use the .fmt file' line to the current document
 - Ghostscript for compression

If you can think of a way around those two issues (and like them) I'll see what I can do.

**Comment by jlelong** [comment]
@tecosaur regarding the aside comment

I am not a big fan of precompiled heading/preamble. That being said, I agree that it can help save compilation time. Unfortunately, I never use Windows so I will not be able to help you on what tools are available to replace `sed` and ghostscript. Also note that the stock version of `sed` on OS X comes from BSD and does not exactly the same option nor extended regex as the GNU version.

**Comment by jlelong** [comment]
@tecosaur  I merge your PR maybe too fast because the icons are not rendered correctly: `$(file)` and `$(repo)` are not replaced.

<img width="248" alt="Capture d’écran 2019-06-16 à 21 37 10" src="https://user-images.githubusercontent.com/2910140/59568726-03c50280-907f-11e9-9c6e-1def8952ff8b.png">

I am reverting the two PR until this is fixed.

**Comment by tecosaur** [comment]
That's funny, I copied that straight from my settings.json - can you confirm whether putting `$(file)` in a recipe name in your settings.json shows an octicon as expected?

**Comment by tecosaur** [comment]
Ooops. Further investigation makes me think this is due to how vscode treats octiocon replacements.
It seems like in the command palette it performs them, however in the LaTeX workshop side-panel it doesn't.

Hmm, I'm not sure what can be done about this.

**Comment by jlelong** [comment]
OK so for the moment I close this issue. If you ever come up with a solution, please make a new PR.
