### ISSUE TITLE
Clear only when compilation success

### ISSUE THREAD

**Issue by Canoming** [James-Yu/LaTeX-Workshop#1419]
Seems the new "Auto Clean" setting only provides options to clean when compilation fails or terminated. Is it possible to add the option to clean when successes? Usually I need the log files to see why the compilation is failed, but I don't need them if it successes.

Also, it would be sweet if I can choose what files to be auto cleaned

**Comment by jlelong** [comment]
I do not think anything has changed on this over the past months.
Please, have a look at the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#cleaning-generated-files) and ask for reopening the issue if needed.

**Comment by Canoming** [comment]
My fault. Actually it was not very new. It was changed since release `6.0.0` on late Feb.

There was an option to auto clean when compilation successes before, but we only have three options now: `never`, `onBuilt`, and `onFailed`.

Also, I do noticed you provides an option to choose which files to clean. What I meant was, say, I need partial aux files when compilation fails, and I what to clean them all when success. I'm not sure if this will make the settings too complex and confusing. But at least could you add the option `onSuccessed` to setting `autoClean.run`?

**Comment by stephenlevitt** [comment]
Hi, please can you reopen this issue, to add (or re-add) the option to clean `onSuccess`. As @Canoming mentions: you normally want to see the log  files when there is a problem. If the build is a success then they can usually be ignored or cleaned.

**Comment by stephenlevitt** [comment]
Thanks

**Comment by jlelong** [comment]
Following the discussion in #2094, I am closing the issue.
