### ISSUE TITLE
Suggestion: TeXcount

### ISSUE THREAD

**Issue by neilsustc** [James-Yu/LaTeX-Workshop#142]
> [TeXcount](http://app.uio.no/ifi/texcount/index.html) is a Perl script for counting words in LaTeX documents

A little but sweet feature, just FYI.

**Comment by jose-a-sa** [comment]
This is a simply but important feature. Instead of running `perl texcount.pl -merge main.tex`, you could add a small counter for only words in the document body.

**Comment by James-Yu** [comment]
Running the script is simple. However, what makes me conservative to this is on the frequency of running the script. Shall it be executed on keystroke? Or upon specific events? I'm uncertain on it.

**Comment by Laberbear** [comment]
For anyone wanting a solution right now:
I'm currently using a modified version of Microsofts Markdown Word Count:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.wordcount

![screenshot 2017-07-27 17 28 22 2](https://user-images.githubusercontent.com/10895804/28678609-175159d2-72f1-11e7-8c4e-561f4d15a851.png)

I haven't done any performance measurements but I haven't noticed anything too bad.
And I just threw some more replace-regex' in there.
Words are calculated at pretty much every keystroke.

If anyone is interested, simply replace the package.json and out/extension.js file with the one in this gist: https://gist.github.com/Laberbear/2269ef2bc685d80270d2d409925ca662

**Comment by James-Yu** [comment]
It works like this:
![image](https://user-images.githubusercontent.com/4210342/28706258-0be70dd4-73a6-11e7-8376-5182f9eb47fd.png)

The script is executed upon user command. This is due to the slow execution of TeXCount. Background continuous TeXCount may significantly reduce system performance.

I will continue testing the feature, and release it to the marketplace soon.

**Comment by janosh** [comment]
Was word count removed in the last update? [It's not mentioned in the changelog](https://github.com/James-Yu/LaTeX-Workshop/blob/master/CHANGELOG.md) but the command doesn't show up anymore.

**Comment by James-Yu** [comment]
It is mentioned in the change log, just in the link you provided.

**Comment by janosh** [comment]
Ah, sorry, the word remnants through me off? SO it was moved to LaTeX Utilities? How do I access it now?

**Comment by yzhang-gh** [comment]
@janosh It is another extension. See the README.

> LaTeX Workshop is an extension for [Visual Studio Code](https://code.visualstudio.com/), aiming to provide core features for LaTeX typesetting with Visual Studio Code. It also has a sibling extension, [LaTeX Utilities](https://marketplace.visualstudio.com/items?itemName=tecosaur.latex-utilities), providing extra features.

---

However, I am confused about this transfer of the word-count feature.
It is a small feature (probably unimportant for some users), but it is apparently not like the other "fancy features" in the LaTeX Utilities extension.
IMHO, it is more appropriate for this feature to be in the base extension.

**Comment by janosh** [comment]
@yzhang-gh I agree.

**Comment by James-Yu** [comment]
Let me clarify. We (at least I and @tamuratak) are more interested in maintaining features that are somehow closely integrated with the core of LaTeX Workshop, i.e., content parsing, auto-completion, compiling, etc. Word counter is a feature that does not need any of them: just `texcount somefile.tex` and you are good. These features are quite modular and should be maintained seperately IMO. The current distinguish between LW and LaTeX Utilities are not clear about this point. Will change the description later.

**Comment by yzhang-gh** [comment]
Thank you. I see your point that this feature is loosely related to LaTeX (in the code level).

I'd like to post a different point of view.

|                                     |                                | Features                                                                   |
| ----------------------------------- | ------------------------------ | -------------------------------------------------------------------------- |
| VSCode                              | Code editor                    | Completions, snippets, ...                                                 |
| VSCode + LaTeX Workshop             | Text/document editor for LaTeX | Toggle styles (bold/italic...), compilation and preview, word count, ... |
| VSCode + LaTeX Workshop & Utilities | More powerful LaTeX editor     | Like the [Live Snippets](https://marketplace.visualstudio.com/items?itemName=tecosaur.latex-utilities#live-snippets) in LaTeX Utilities |

While the second option covers all basic features in the whole process of LaTeX writing, the last combination is for those "high-end" users who pursue extreme efficiency.

---

I can live with any decision you made on this. (This is indeed a small feature.)
Thanks for the great extension!

**Comment by tecosaur** [comment]
@yzhang-gh somehow I rather like your interpretation / segmentation :stuck_out_tongue:

@James-Yu from a few of the issues/comments that have croped up recently, I'm thinking we might need to make the LW/LU distiction clearer in the readme.

**Comment by janosh** [comment]
I was just about to comment something very similar to @yzhang-gh (but then got interrupted). Basically, my point was I think percentage of users likely to need a feature could also be a good rule of thumb to decide where a certain feature should go. And since word count is quite commonly used, it might have a place in this project.

**Comment by jlelong** [comment]
When LU was created, I thought it would hold experimental features needing quite a substantial amount of code or not yet completely mature. These features would target very advanced users. However, LW should remain the ultimate LaTeX extension for 99% of LaTeX users. If most users need both extensions, there is no real gain.

I vote for discussing the border between the two extensions in more details.

**Comment by tecosaur** [comment]
For discussing the general distinction between LW and LU, perhaps we would be better of in #1558.
