### ISSUE TITLE
Is it possible to have an inline math preview feature that reveals realtime changes?

### ISSUE THREAD

**Issue by chenr12** [James-Yu/LaTeX-Workshop#1420]
The math preview on-hover feature is great and makes it more efficient to preview math equations. However, the preview disappear once I press any key or move the mouse cursor away. As a result, every time we modify the equations we have to move the mouse cursor again to trigger the preview.

I am wondering if we can somehow make the followings happen:
1. pin the hovering-preview, say, by some hotkeys, so that it won't disappear when we move the cursor away or modify the equations;
2. the preview auto updates to reveal realtime changes in the equations.

**Comment by trevorgunn** [comment]
You can use Stefan Goessner's extension: https://github.com/goessner/mdmath for a quick preview in a Markdown document. Maybe it would be possible to have our extension open up a new markdown tab to use this extension.

**Comment by chenr12** [comment]
Thank you for getting to the request so quickly.
I agree that a "live preview" feature could be too heavy to have for now. But is there a simple way to make it easier to trigger the hovering preview? The hovering preview feature that we currently have is great, but I am just so reluctant to move to the beginning of the math block every time I want to see the preview...

**Comment by tecosaur** [comment]
Personally, I'm looking forward to when this API (https://github.com/microsoft/vscode/pull/66418) enters stable,
— see #1122.

I think that is the best method of approaching this. Simply put, hover preview was designed for taking a quick peek, this is more what we really want.

**Comment by chenr12** [comment]
Thanks a lot! I look forward the future enhancement.
