### ISSUE TITLE
Evince backward search

### ISSUE THREAD

**Issue by befelix** [James-Yu/LaTeX-Workshop#1421]
The `evince_backwards_search` file that you provide in the wiki directly uses `import gobject` in line 120. From what I gathered online this API is deprecated and to make it work I had to replace it with `from gi.repository import GObject as gobject`.

Maybe one could add the following to avoid people other people running into the same issue?

```
try:
    from gi.repository import GObject as gobject
except ImportError:
    import gobject
```

Thanks

**Comment by jlelong** [comment]
Thanks for the tip. Can you test the new files on the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#linux)?

**Comment by befelix** [comment]
It looks like gi.repository doesn't like to mix with old-style imports and the current code still throws an error. Could you either drop the unused `glib` import or replace it with `from gi.repository import GLib as glib` as with `gobject`. Then it works.

Sorry for the confusion. Somehow `gi.repository` messes with import paths and the error didn't show up for me since importing `gi.repository` apparently messes with import paths. Strange.

**Comment by jlelong** [comment]
Humm, it looks like `glib` is not used but only `dbus.mainloop.glib`. Can you confirm that if you simply remove `glib` from the import list everything works?

**Comment by befelix** [comment]
Yes, I'm using this as we speak :). However, unfortunately I can't test it
on a system where `gi.repository` is not installed.

If you're concerned you can add `import glib` to the except block after the
`ImportError`.

**Comment by jlelong** [comment]
Just updated. Can you check?

**Comment by befelix** [comment]
Works great, thanks!
