### ISSUE TITLE
PDF Preview Live Share 

### ISSUE THREAD

**Issue by andrepbento** [James-Yu/LaTeX-Workshop#1422]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i try to use Live Share with LaTeX-Workshop and the participants can't view the PC on their machines. Also, it appears to attempt to 

**Describe the solution you'd like**
Let the participants preview compiled PDF over Live Share session by somehow making LaTeX-Workshop aware of the Live Share session.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by jlelong** [comment]
Making an extension compatible with Live Share raises some issues, see [here](https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/extensions#known-issues). In particular, as files are not stored locally, it is not possible to access other files than the current active document, which would break a lot of fun features in LW. I think supporting Live Share is far beyond what the effort we can put on the extension. 

If anyone is willing to work on this, please ask for reopening the issue. Meanwhile, I am closing it.

**Comment by James-Yu** [comment]
Now we have an experimental #4308 on Live Share integration, contributed by @quoc-ho @krokosik . If you guys are still using LW, welcome to have a try!
