### ISSUE TITLE
Some Predefined snippets are incomplete

### ISSUE THREAD

**Issue by oyasin** [James-Yu/LaTeX-Workshop#1423]
**Describe the bug [Required]**
The snippet **@(** is incomplete. If you open the latex.json file you can see that the snippet is written as follows

	"(": {
		"prefix": "@(",
		"body": "\\left( $1 \\right",
		"description": "Insert left( ... right)"
	}
It's clear that we are missing **)** after right in the body of the snippet.

*To Reproduce**
1. open any .tex file
2. write the prefix **@(**
3. you will get \left(   \right

**Expected behavior**
The expected behavior is to get \left(   \right)

**Suggestion**
The snippet should be something like this

	"(": {
		"prefix": "@(",
		"body": "\\left( $1 \\right)$0",
		"description": "Insert left( ... right)"
	}
I added the missing **)** and **$0** as a final position for the cursor.

**Note**
**@{** and **@[** are broken in the same way.

**Desktop [Required]:**
 - OS: MacOS Mojave
 - VS Code version: 1.35
 - Extension version: 7.0.0

**Comment by jlelong** [comment]
The parens `(`, `{`and `[` are defined as auto closing pairs in [`syntax.json`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/syntax.json). So depending on the value of `editor.autoClosingBrackets` (I use `languageDefined`, which is the default) , entering `(` yields `()`with the cursor between `(` and `)`. This explains the definition of the snippets.
The final `$0` is actually implicit in snippets.

**Comment by oyasin** [comment]
@jlelong I see, I had `editor.autoClosingBrackets` set to never, which explains the missing parens. I switch it back to the default and it seems to work fine. However this yields to this new problem

**new problem**
When you type the prefix **@(** for example and enter some text and hit tab the final cursor position is before the closing bracket. 
<img width="192" alt="Screen Shot 2019-06-06 at 1 52 30 PM" src="https://user-images.githubusercontent.com/50802294/59027719-743f7880-8862-11e9-91b7-a83f178ce048.png">

**Comment by jlelong** [comment]
Unfortunately, we cannot do much about the final position of the cursor as the closing `)` is not part of the snippet.

**Comment by oyasin** [comment]
@jlelong I understand. Thank you very much for answering my questions.
