### ISSUE TITLE
Enter key not working when LaTex-Workshop enabled

### ISSUE THREAD

**Issue by david-waterworth** [James-Yu/LaTeX-Workshop#1429]
Issue with vscode 1.35.0 (and the previous release) and LaTex-Workshop 7.0.2, after the latest update of LaTex-Workshop my `Enter' key no longer works in *.tex files. It's fine for any other file type, and if I disable LaTex-Workshop it also works in *.tex files. As soon as I re-enable the extension I can no longer add a newline. I tried creating a brand new text.tex file and had the same issue.

Edit: I just discovered the option in vs-code to install a specific version of an extension. I installed LaTex-Workshop 7.0.0 and the issue went away.

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by david-waterworth** [comment]
I did provide the versions, 7.0.2 is the `latest' as I said and it causes the issue, reverting to 7.0.0 fixes the issue. 

Since it's working now I'm not able to provide logs of the issue but when I'm not too busy I'll try and recreate by updating to 7.0.2 again.

**Comment by jlelong** [comment]
Nothing was changed regarding the `Enter` key between `7.0.0` and `7.0.2`.
See also the [wiki entry](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions) on issues with the `Enter` key.

**Comment by jlelong** [comment]
The issue does not contain enough information to investigate the problem. I am closing it until more information is provided.

**Comment by vomout** [comment]
This issue appeared for me in the latest VSCode update. It's not always not working, it's quite random, but particularly during builds the enter key does not work. Other keys do.
