### ISSUE TITLE
Microsoft LaTeX and LaTeX Workshop

### ISSUE THREAD

**Issue by seanmcbreen** [James-Yu/LaTeX-Workshop#143]
Hi,

I work in the VS Code team and worked on our initial Extensibility launch.  At that time one of the extensions we published was https://marketplace.visualstudio.com/items?itemName=ms-vscode.latex. 
 you probably already know that it's really nothing more than a TextMate tmLanguage bundle.

It was a good proof point as to how easily it was to provide simple language support in VS Code.  But we have done a bad job of maintaining it - for better or worse we write mostly in Markdown these days.  So we fell bad not doing a great job for the LateX crowd.

So... this looks like a very well received extension and the feature set is much, much richer.  

I wonder if we should consider sending the users of our extension over to your extension and removing our one.  It's much better to have a good story that is well maintained.  I wanted to test the waters with you and see if you are open to this? 

If you are then I need to check on a few other things on our side.  

If you are interested in what this actually could look like for a user I recently did this for another extension we created (for a different reason) and simply installing it will give you a felling for the user flow...

https://marketplace.visualstudio.com/items?itemName=seanmcbreen.Spell

Let me know what you think.
Sean

**Comment by James-Yu** [comment]
Hi Sean @seanmcbreen ,

Glad to hear from you. That would be a great recognition of this work! I have no problem with your proposal, and would like to see how it works out.

btw, I noticed there is a built-in spellchecker item in the iteration plans. Any updates on it? `Code Spellchecker` has been doing a great job, but there are some minor performance issues here and there.

Cheers!

**Comment by seanmcbreen** [comment]
Ok that's great news - I'll come back with a more concrete update in the next week or so.

For the spell checker - the bottom line is that cSpell is doing a great job - feature rich, responsive, ...  So for now we have decided to focus on other priorities (given users have an option).  

That said, I agree that a native [leveraging the OS] spell checker solution (which I think is the performance point) would be better.  Unfortunately we don't have a clean way for extenders to do that.  I'm pretty sure if we did cSpell would adopt it.

OK stay tuned for an update in the next week or two, but I'll take this discussion as a green light from your side ;)  Again thanks for really helping the LaTeX community and you should be proud for 23 ratings giving you a net of 4.8 Stars -  that's awesome!!!

Sean

**Comment by NineteenZN** [comment]
Hi James~
This extension is great~    but I found that I can't use the commands below to change the font of compiled pdf.

\usepackage{fontspec}
\setmainfont{...}

em...it doesn't support the ’fontspec‘ package?

**Comment by James-Yu** [comment]
@NineteenZN Please create new issues on your problem instead of commenting in unrelated issues. I will remove your comment and this one shortly for clarity.

As to your problem, the extension does not control how latex commands are translated into pdfs. You need to check your latex compiler.

**Comment by seanmcbreen** [comment]
OK well that was the longest week ever :)

I finally freed up some time to look into this.  I have an updated version of the `vscode-latex` extension (as a VSIX) in this repo:  https://github.com/Microsoft/vscode-LaTeX

You can install that and see what the experience will be like for any upgraders: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

If you are OK with it I'll go and publish the update.
Sean

**Comment by James-Yu** [comment]
A week with awesome vscode updates!

I have tested the `vsix` and am really happy to embrace the lovely Recommended Extension button 😊 I'm absolutely fine for the notice XD

Thanks again for all your (and the team!) hard work in making vscode THE best editor!

-J
