### ISSUE TITLE
Math Brackets Match

### ISSUE THREAD

**Issue by chenr12** [James-Yu/LaTeX-Workshop#1430]
I am wondering if it is possible to match
["\\{", "\\}"], ["\\left(", '\\right)'],  ["\\left[", '\\right]'],  ["\\left\\{", '\\right\\}']
as bracket pairs? 

It seems that currently only "(", "[" and "{" are recognized as brackets. So when paired brackets get highlighted, "\\left" and "\\right" will be left out.

I suppose we should be able to customize/extend bracket definitions for latex but haven't figured out how to do that. This may be a nice feature to have so that these math brackets would get highlighted as a whole, which would be even more useful for editing in combination with bracket coloring extensions like [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2).

**Comment by jlelong** [comment]
We already match `["{", "}"], ["[", "]"], ["(", ")"]`. It is currently not possible to also match `["\left(", '\right)'], ["\left[", '\right]']` because of Microsoft/vscode/issues/58619.
I suggest to declare `"\left", "\right"` as a pair.

**Comment by chenr12** [comment]
Thank you for the response (and also showing me how to modify the bracket definition)!

Although we can't get those math brackets as "autoClosingPairs", for those who are using bracket colorizer like me it is still useful to have them declared as "brackets". This is how they look like with  [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2), which it to find matching pairs.
<img width="679" alt="Screen Shot 2019-06-12 at 10 48 11 AM" src="https://user-images.githubusercontent.com/35321665/59366232-a0924380-8cff-11e9-8d3a-88caff1c79dc.png">

However, some people might not want to pair up `"\\left", "\\right"` as its scope would not be nested with other brackets. It is good to have it as an option though.

**Comment by stone-zeng** [comment]
The pair `["\\left", "\\right"]` will often  make the rendering incorrect, e.g.

```tex
% See #1430
\left( \right)
```

![image](https://user-images.githubusercontent.com/18233088/76209739-8dd07f00-623d-11ea-8f6e-e004174ed87b.png)

```tex
% See #1641
{\leftmark }
```

![image](https://user-images.githubusercontent.com/18233088/76209667-64175800-623d-11ea-97d5-e5508e355775.png)

I use the extension Bracket Pair Colorizer 2 too.

Personally I think `\left` and `\right` should be removed from the brackets list.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template if you want to solve your problem.
