### ISSUE TITLE
Apply syntax highlighting to .tex file for listing environment

### ISSUE THREAD

**Issue by kapple19** [James-Yu/LaTeX-Workshop#1432]
It's hard to navigate a listing environment without syntax highlighting.

Can syntax highlighting be applied to the lstlisting environment in the .tex file?

**Comment by jlelong** [comment]
The content of a listing environment consists of some embedded language and the whole difficulty is about telling the syntax highlighter which language we are actually embedding. To overcome this difficulty, we use dedicated environment names for every language

| Environment name | Language |
|-------------------|-----------|
| `pycode`| `Python`|
| `cppcode`| `C++`, `C`|
| `luacode`| `Lua`|
| `scalacode` | `Scala` |
| `hscode` | `Haskell`|

To highlight such environments, you need to have support for the corresponding language in vscode. Those environment names are typically defined by the `minted` package but you could just define
````
\newenvironment{pycode}{\begin{listing}[language=python]}{\end{listing}}
````

**Comment by kapple19** [comment]
Thanks @jlelong, I'll give it a shot.
