### ISSUE TITLE
Docker enable build set task working directory to workspace folder instead root file directory

### ISSUE THREAD

**Issue by alexfdezsauco** [James-Yu/LaTeX-Workshop#1434]
Typically my workspace layout looks as follow:

    [workspace]
        [output]
             main.pdf
        [src]
            main.tex
            ....

Now I trying to use a docker image to build. But when I set docker.enabled to `true` I need that the volume mount be the [workspace]  instead the [src].

The script file also require a parameter `-cd`

**Comment by CheariX** [comment]
I have a similar use-case:

I have different "main-files" which include a `../template.tex`. (e.g. my tikz pictures inside a larger project document)
Using the workspace directory instead of the root-file directory would fix this easily.

**Comment by tamuratak** [comment]
VS Code supports Docker with [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) now. Please try it.

**Comment by tamuratak** [comment]
You can also use [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).

**Comment by alexfdezsauco** [comment]
Thanks could you provide a dev containre configuraiton file? I try this but doesn't work.

Dockerfile:

    FROM blang/latex@sha256:a02f07ad04bcb732ad8018547c2ecf2907ca570013bd3f36037247b5f3f3ab07

devcontainer.json

    {
      "name": "Blang Latex",
      "dockerFile": "Dockerfile",
      "runArgs": [],
      "extensions": [
        "james-yu.latex-workshop"
      ]
    }

**Comment by tamuratak** [comment]
Please remove sha256 in the Dockerfile. It works on my mac. Now, pdf preview on tab does not work due to the bug of VS Code. View in web browser works.

```
FROM blang/latex
```
devcontainer.json
```
{
  "name": "Blang Latex",
  "dockerFile": "Dockerfile",
  "runArgs": [],
  "extensions": [
    "james-yu.latex-workshop"
  ]
}
```
