### ISSUE TITLE
Latexmk and bibtex didn't work

### ISSUE THREAD

**Issue by jackey79** [James-Yu/LaTeX-Workshop#1437]
My latexmk and bibtex didn't work with the error that 

> I found no \bibdata command---while reading file test.aux
> Warning--I didn't find a database entry for "Wille1982"

I just want to add `\cite{Wille1982}` in my document. Both of my **test.tex** and **expbib.bib** are in the same folder.

Here is my setting. Are there any wrong with my tools and recipes ?
Only xelatex and pdelatex work.

```
  "latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "-outdir=%OUTDIR%",
        "%DOCFILE%"
      ],
      "env": {}
    },
    {
      "name": "xelatex",
      "command": "xelatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOCFILE%"
      ]
    },
    {
      "name": "pdflatex",
      "command": "pdflatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOCFILE%"
      ]
    },
    {
      "name": "bibtex",
      "command": "bibtex",
      "args": ["%DOCFILE%"]
    }
  ],

  "latex-workshop.latex.recipes": [
    {
      "name": "latexmk",
      "tools": ["latexmk"]
    },
    {
      "name": "XeLaTeX",
      "tools": ["xelatex"]
    },
    {
      "name": "PDFLaTeX",
      "tools": ["pdflatex"]
    },
    {
      "name": "BibTeX",
      "tools": ["bibtex"]
    },
    {
      "name": "pdflatex -> bibtex -> pdflatex -> pdflatex",
      "tools": ["pdflatex", "bibtex", "pdflatex", "pdflatex"]
    },
    {
      "name": "xelatex -> bibtex -> xelatex -> xelatex",
      "tools": ["xelatex", "bibtex", "xelatex", "xelatex"]
    }
  ],

  "latex-workshop.latex.autoBuild.cleanAndRetry.enabled": false,
  "latex-workshop.message.warning.show": true,
  "latex-workshop.message.error.show": true,
  "latex-workshop.view.pdf.viewer": "tab",
  "latex-workshop.showContextMenu": true,
  "latex-workshop.latex.option.maxPrintLine.enabled": false,
  "latex-workshop.view.pdf.external.command": {
    "command": "",
    "args": ["%PDF%"]
  },
  "latex-workshop.view.pdf.external.synctex": {
    "command": "",
    "args": ["-forward-search", "%TEX%", "%LINE%", "%PDF%"]
  },
  "editor.tabCompletion": "on",
  "[latex]": {
    "editor.defaultFormatter": "James-Yu.latex-workshop"
  }
```

**Comment by jlelong** [comment]
Your configuration looks fine. Your issue is mostly not related to the extension.
If you want some help, provide a minimal working example and the full logs of the extension.

**Comment by jackey79** [comment]
In Windows 10 , texlive2019.Here are my documents.

test.tex
```
\documentclass[11pt,a4paper,fleqn,UTF8]{ctexart}
\usepackage{amsthm,amsmath,amssymb,array,calc,fancyhdr}
\usepackage{cite}
\usepackage{indentfirst}
\usepackage{geometry}
\usepackage{extarrows}
\usepackage{lipsum}
\geometry{left=3.17cm,right=3.17cm,top=2.54cm,bottom=2.54cm}
\pagestyle{plain}
\setlength\parskip{5pt}
\bibliographystyle{plain}
\bibliography{ref}
\begin{document}

\lipsum[1]
\cite{Wille1982}
\lipsum[2]
\end{document}
```

expbib.bib
```
@Inbook{Wille1982,
author="Wille, Rudolf",
editor="Rival, Ivan",
title="Restructuring Lattice Theory: An Approach Based on Hierarchies of Concepts",
bookTitle="Ordered Sets: Proceedings of the NATO Advanced Study Institute held at Banff, Canada, August 28 to September 12, 1981",
year="1982",
publisher="Springer Netherlands",
address="Dordrecht",
pages="445--470",
isbn="978-94-009-7798-3",
doi="10.1007/978-94-009-7798-3_15",
url="http://dx.doi.org/10.1007/978-94-009-7798-3_15"
}
```

The following is the output of latexmk.
> [13:46:53] RECIPES command invoked.
> [13:46:53] BUILD command invoked.
> [13:46:53] Found root file from active editor: d:\Test\LaTeX\TEST\test.tex
> [13:46:53] Root file remains unchanged from: d:\Test\LaTeX\TEST\test.tex.
> [13:46:53] Building root file: d:\Test\LaTeX\TEST\test.tex
> [13:46:53] Build root file d:\Test\LaTeX\TEST\test.tex
> [13:46:53] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=d:/Test/LaTeX/TEST,test
> [13:46:54] LaTeX build process spawned. PID: 2612.
> [13:46:55] Recipe returns with error: 12/null. PID: 2612.

If I compile bibtex after xelatex, there was another problem.The process of xelatex was success. But bibtex was not.
xelatex
> [13:53:37] RECIPES command invoked.
> [13:53:37] BUILD command invoked.
> [13:53:37] Found root file from active editor: d:\Test\LaTeX\TEST\test.tex
> [13:53:37] Root file remains unchanged from: d:\Test\LaTeX\TEST\test.tex.
> [13:53:37] Building root file: d:\Test\LaTeX\TEST\test.tex
> [13:53:37] Build root file d:\Test\LaTeX\TEST\test.tex
> [13:53:37] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,test
> [13:53:38] LaTeX build process spawned. PID: 12440.
> [13:53:40] LaTeX log parsed with 2 messages.
> [13:53:40] Recipe of length 1 finished. PID: 12440.
> [13:53:40] Successfully built d:\Test\LaTeX\TEST\test.tex.
> [13:53:40] Refresh PDF viewer for d:\Test\LaTeX\TEST\test.pdf
> [13:53:40] Cannot find file d:\Test\LaTeX\TEST\test.fls
> [13:53:40] Handle data type: position
> [13:53:41] Preview PDF file: d:\Test\LaTeX\TEST\test.pdf
> [13:53:41] Handle data type: loaded

bibtex
> [13:53:55] RECIPES command invoked.
> [13:53:55] BUILD command invoked.
> [13:53:55] Found root file from active editor: d:\Test\LaTeX\TEST\test.tex
> [13:53:55] Root file remains unchanged from: d:\Test\LaTeX\TEST\test.tex.
> [13:53:55] Building root file: d:\Test\LaTeX\TEST\test.tex
> [13:53:55] Build root file d:\Test\LaTeX\TEST\test.tex
> [13:53:55] Recipe step 1: bibtex, test
> [13:53:55] LaTeX build process spawned. PID: 16420.
> [13:53:55] Recipe returns with error: 2/null. PID: 16420.

**Comment by jlelong** [comment]
You do not seem to refer to `expbib.bib` in `test.tex`. This is most likely why `bibtex` complains.
Try to compile your document outside the extension and you will see that your problem is not related to the extension.

**Comment by jackey79** [comment]
Thanks for your advice.
But if I refer `expbib.bib` , it still doesn't work.
`\bibliography{expbib}`

Here is the output of latexmk.

> [14:57:33] RECIPES command invoked.
> [14:57:33] BUILD command invoked.
> [14:57:33] Found root file from active editor: d:\Test\LaTeX\TEST\test.tex
> [14:57:33] Root file remains unchanged from: d:\Test\LaTeX\TEST\test.tex.
> [14:57:33] Building root file: d:\Test\LaTeX\TEST\test.tex
> [14:57:33] Build root file d:\Test\LaTeX\TEST\test.tex
> [14:57:33] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=d:/Test/LaTeX/TEST,test
> [14:57:33] LaTeX build process spawned. PID: 10296.
> [14:57:36] LaTeX log parsed with 2 messages.
> [14:57:36] Recipe returns with error: 12/null. PID: 10296.

Following is the output of xelatex and bibtex.
> [14:58:06] RECIPES command invoked.
> [14:58:06] BUILD command invoked.
> [14:58:06] Found root file from active editor: d:\Test\LaTeX\TEST\test.tex
> [14:58:06] Root file remains unchanged from: d:\Test\LaTeX\TEST\test.tex.
> [14:58:06] Building root file: d:\Test\LaTeX\TEST\test.tex
> [14:58:06] Build root file d:\Test\LaTeX\TEST\test.tex
> [14:58:06] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,test
> [14:58:07] LaTeX build process spawned. PID: 6820.
> [14:58:09] LaTeX log parsed with 2 messages.
> [14:58:09] Recipe of length 1 finished. PID: 6820.
> [14:58:09] Successfully built d:\Test\LaTeX\TEST\test.tex.
> [14:58:09] Refresh PDF viewer for d:\Test\LaTeX\TEST\test.pdf
> [14:58:09] Cannot find file d:\Test\LaTeX\TEST\test.fls
> [14:58:09] Handle data type: position
> [14:58:10] Preview PDF file: d:\Test\LaTeX\TEST\test.pdf
> [14:58:10] Handle data type: loaded
> [14:58:14] RECIPES command invoked.
> [14:58:14] BUILD command invoked.
> [14:58:14] Found root file from active editor: d:\Test\LaTeX\TEST\test.tex
> [14:58:14] Root file remains unchanged from: d:\Test\LaTeX\TEST\test.tex.
> [14:58:14] Building root file: d:\Test\LaTeX\TEST\test.tex
> [14:58:14] Build root file d:\Test\LaTeX\TEST\test.tex
> [14:58:14] Recipe step 1: bibtex, test
> [14:58:15] LaTeX build process spawned. PID: 16856.
> [14:58:15] Recipe returns with error: 2/null. PID: 16856.

**Comment by jlelong** [comment]
Have a look to the LaTeX compiler log

![48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76](https://user-images.githubusercontent.com/2910140/59548248-c6605800-8f4c-11e9-8028-886fc506db23.png)

Try to compile your files outside the extension. This is not an issue with the extension.

**Comment by jackey79** [comment]
Thanks a lot.  I tried to compile in Textworks editor, the same error turned out again.
