### ISSUE TITLE
Inline citation doesn't popup in subfiles

### ISSUE THREAD

**Issue by jrwrigh** [James-Yu/LaTeX-Workshop#1438]
Foreword: I originally wrote the issue up as a bug report because I was trying to track down a bug. I have now found a "solution" to the bug, but said solution is quite inconvenient. 

**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
Intellisense does not pop-up with citation key suggestions in one of my LaTeX projects. Specifically, a project that uses subfiles. See the "Additional Context" section below for more details.
![CitationExampleWrongThesis](https://user-images.githubusercontent.com/20801821/59554326-5ca57580-8f6f-11e9-8145-7ad40c24f0f8.gif)

**To Reproduce**
1. Go to existing project
2. Start typing in "\cite{"
3. Hit 'Enter' to autocomplete and bring up the intellisense "suggestions" (idk what to call it)
4. Start typing in citation key, but it does not come up

**Expected behavior**
Intellisense to show the citation keys and insert them. This is done on a single files LaTeX project using the same `.bib` file.
![CitationExampleCorrectAIAA](https://user-images.githubusercontent.com/20801821/59554337-7b0b7100-8f6f-11e9-9920-ffc85b7052fe.gif)

**Logs [Required]**
This log is after reloading the VS Code window with nothing but LaTeX Workshop extension loaded, and immediately performing the reproduction steps.
<details>
<summary>LaTeX Workshop Output [Required]</summary>
[13:15:32] Initializing LaTeX Workshop.
[13:15:32] pdflatex is provided by MiKTeX
[13:15:32] Creating LaTeX Workshop http and websocket server.
[13:15:32] LaTeX Workshop initialized.
[13:15:32] Linter for root file started.
[13:15:32] Found root file from active editor: c:\Users\jrwrigh\gitRepos\ms_thesis\background.tex
[13:15:36] Root file changed from: undefined. Find all dependencies.
[13:15:36] Instantiating a new file watcher for c:\Users\jrwrigh\gitRepos\ms_thesis\background.tex
[13:15:36] Parsing c:\Users\jrwrigh\gitRepos\ms_thesis\background.tex
[13:15:36] Cannot find file c:\Users\jrwrigh\gitRepos\ms_thesis\background.fls
[13:15:36] Server created on 127.0.0.1:62975
[13:15:36] Snippet data loaded.
[13:15:36] LaTeX Workshop version: 7.0.2
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
Nothing suspicious
</details>

**Screenshots**
See explanatory gifs above

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.35.1
 - Extension version: 7.0.2

**IMPORTANT CONTEXT/Solution**
The thesis is a subfiles-based project. So it each subfile does not have a `\bibliography{[.bib file]}` command on it. Instead, I have a command defined in the "main" `.tex` file that makes the subfiles package compile correctly:

` \def\biblio{\bibliographystyle{new-aiaa}\bibliography{Sources}}`

If I add a `\bibliographystyle{new-aiaa}\bibliography{Sources}` line to the end of  the subfile, then the intellisense works. However, I'd much prefer to keep this single command in `main.tex` as it's much easier to switch between biliography styles this way.

**Possible Feature Suggestion**
Is it possible to force a bib file to be used as intellisense? Like a magic command:

`% !TEX bibfile = relative/or/absolute/path/to/bibfile.bib`

I know there is `latex-workshop.latex.bibDirs` already available, but I thought that it would check the current directory for `.bib` files, My project has the subfile and `.bib` in the same directory.

**Comment by jlelong** [comment]
Please provide a minimal working example to reproduce the issue.

**Comment by jrwrigh** [comment]
Update 1:
subfiles won't compile the full document if I have the `\bibliographystyle{new-aiaa}\bibliography{Sources}` in the subfile documents. 

Update 2:
I believe I've found a "new" root cause. Not knowing how exactly the extension works, it appears that when a reference to a `.bib` file exists, it dynamically pulls new entries in that `.bib` file. For usage of `subfile`s though, the intellisense suggestions work on a separate "static" database that is only updated when the main file is built. 

I'm currently working on building a minimum working example (has to be multiple files and stuff), but I figured I'd give the update.

**Comment by jrwrigh** [comment]
Alright, I have the minimum working example for you:

`mainMWE.tex`:
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
 
\usepackage{subfiles}
 
\def\biblio{\bibliographystyle{plain}\bibliography{Sources}}  
 
\begin{document}
\def\biblio{}
 
\section{Introduction}
\cite{Clausen1993} 
\subfile{section}

\bibliographystyle{plain}
\bibliography{Sources}
\end{document}
```
`section.tex`:
```latex
\documentclass[./mainMWE.tex]{subfiles}
 
\begin{document}
\textbf{Hello world!}
\cite{Cho1989}
Hello, here is some text without a meaning.  This... 

\biblio
\end{document}
```

<details>
<summary>Sources.bib</summary>

```latex
@article{Clausen1993,
author = {Clausen, P D and Koh, S G and Wood, D H},
doi = {10.1016/0894-1777(93)90039-L},
journal = {Experimental Thermal and Fluid Science},
keywords = {Turbulence,boundary layer,conical diffuser,diffuser,experimental},
number = {1},
pages = {39--48},
title = {{Measurements of a Swirling Turbulent Boundary Layer Developing in a Conical Diffuser}},
volume = {6},
year = {1993}
}
@inproceedings{Cho1989,
address = {Melbourne},
author = {Cho, Nam-Hyo and Fletcher, Clive A J},
booktitle = {10th Australasian Fluid Mechanics Conference},
pages = {3.13--3.16},
title = {{Prediction of Turbulent Swirling Flow in a Diffuser with a Tailpipe}},
year = {1989}
}
```

</details>

### Steps:
1) Open `section.tex` first, and try to trigger an intellisense (it doesn't work)
2) Open up `mainMWE.tex` and try to trigger intellisense (it will work)
3) Go back to `section.tex` and try to trigger intellisense (it will work)

It appears that I simply have to open the "main.tex" file for the static database to reload. For my MS thesis that I'm writing, I rarely if ever open it up. I think if the static database just updated everytime the `.bib` file was updated, it wouldn't be a problem.

**Comment by werunom** [comment]
I am too facing the same issue --- the intellisense citation-key autocomplete is not working on sub-files. 

I have similar setup as reported by @jrwrigh --- I have the main tex-config file in which I have put all the tex configurations; and each tex files imports this main tex-config file.

**Comment by jlelong** [comment]
When a root file is detected (see [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file)), it is parsed and all the included files recursively to detect bibliographies via `\addbibresource` or `\bibliography`. Then, every `.bib` file is associated to all files in the current LaTeX project to provide intellisense. Then, the problem arises with `subfiles`, because every `subfile` has its own `\documentclass[...]{subfiles}` command ans is therefore considered as a root file.
So, if you comment the line `\documentclass[./mainMWE.tex]{subfiles}` in `section.tex`, everything works as expected.

I will think of a way to properly handle the subfiles package.
