### ISSUE TITLE
Hover preview can't parse multiline inline equations

### ISSUE THREAD

**Issue by m93a** [James-Yu/LaTeX-Workshop#1439]
**Describe the bug [Required]**
This code is fine in LaTeX but the equation preview displays incorrectly for it:
```tex
Hello, this is $
an \; equation
$ and this is a variable: $x$.
```

**To Reproduce**
1. Open a tex file
2. Paste the example
3. Hover the mouse over “and”
4. See a broken preview

**Expected behavior**
Preview should be consistent with LaTeX

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/1671665/59555144-639fa880-8fae-11e9-9167-5c551c74eaef.png)
![obrazek](https://user-images.githubusercontent.com/1671665/59555145-68fcf300-8fae-11e9-9645-2e52e61aef3e.png)

**Desktop [Required]:**
 - OS: Ubuntu 18.04.1
 - VS Code version: 1.35
 - Extension version: 7.0.2

**Comment by jlelong** [comment]
We restrict `$...$` to be on a single to avoid too many interferences with `$$...$$`. See the discussions in #1284 and #1393.
This is up to the user to hover on the right position. It is far complicated from a parsing point of view to detect that the first `$` in `$ and this is a variable: $x$` is a closing `$`.
