### ISSUE TITLE
Incorrect environment name "multiline" in code completion list

### ISSUE THREAD

**Issue by XupingYao** [James-Yu/LaTeX-Workshop#144]
Currently, when you want to write
`\begin{multline}
\end{multline}`
the code completion list gives an environment name "multiline" just like
`\begin{multiline}
\end{multiline}`

The `multline` provided by `amsmath` package is a frequent environment. 
Is the name in the the code completion list wrong?

Here is the screenshot. It is easy to reproduce.
![image](https://cloud.githubusercontent.com/assets/20335994/26320839/02629b30-3f57-11e7-93b0-f2b31a4b5137.png)

**Comment by James-Yu** [comment]
Yes it is a bug to be fixed. Thanks for the issue.
