### ISSUE TITLE
intellisense is not coherent when using subfiles

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1443]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

I have the following setup:
`config-file` --- has all the tex configurations (like packages, citation style, etc.)
`tex-file` --- I import the `config-file` in each tex file. 

In this configuration, I observed that there is a difference in intellisense suggestions seen in `config-file` and `tex-file`. 

**To Reproduce**
Type latex commands and see what autosuggestions are given

**Logs [Required]**
Logs might not be required

**Screenshots**
Autocomplete suggestions in `Config-file`
![main-file-cropped](https://user-images.githubusercontent.com/24664855/59584910-e3d42400-90fc-11e9-9ff7-c2e0192813a9.png)

Autocomplete suggestions in `Tex-file`
![sub-file-cropped](https://user-images.githubusercontent.com/24664855/59584923-e9316e80-90fc-11e9-8ac2-429ed8d0ffe0.png)

As you can see, calling `textcite` in `tex-file` does not give all the various autofill options available in the `config-file`. And some other commands (like `autocite`) are not even suggested in the `sub-file`.

**Desktop [Required]:**
 - OS: Linux manjaro
 - VS Code version: 1.35.1
 - Extension version: 7.0.2

**Additional context**

This bug might be related to [this issue](https://github.com/James-Yu/LaTeX-Workshop/issues/1438).

**Comment by jlelong** [comment]
This is the same root cause as #1438. Intellissense depends on the packages used and subfiles do not include any package. Hence, the problem.
I suggest to continue the discussion in #1438.
