### ISSUE TITLE
Incomplete Support for Subfiles Package in Combination with Docker Integration

### ISSUE THREAD

**Issue by sbaeurle** [James-Yu/LaTeX-Workshop#1445]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
Using the subfiles package in combination with the docker integration is not working as expected.
When compiling a subfile in any subdirectory the compilation fails due to incorrect volume binding.
Latex Workshop is mounting the subdirectory into the data folder of the docker container, thus preventing access to the needed root tex.

**To Reproduce**
1. Create a Latex Document with subfiles package
```
\usepackage{subfiles}
\documentclass{article} 
\begin{document}
\subfile{content/introduction}
\end{document}
```
2. Create subfile in subdirectory (e.g. content/introdution.tex)
```
\documentclass[../document]{subfiles}
\begin{document}
\chapter{Introduction}
Hello!
\end{document}
```
3. Compilation will fail

**Expected behavior**
Latex Workshop starts Docker with the correct root directory mounted into the /data folder inside the container.

**Logs [Required]**
```
_irrelevant_\content>docker run -i --rm -w /data -v "_irrelevant_\content:/data" tianon/latex latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=./ introduction 
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'introduction.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "introduction.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./introduction.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/subfiles/subfiles.cls
Document Class: subfiles 2012/05/23 Federico Garcia
(/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)
Preamble taken from file `../document'

! LaTeX Error: File `../document.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name: 
/usr/share/texlive/texmf-dist/tex/latex/subfiles/subfiles.cls:40: Emergency sto
p.
<read *> 
         
l.40 \input{\preamble@file}
                           ^^M
/usr/share/texlive/texmf-dist/tex/latex/subfiles/subfiles.cls:40:  ==> Fatal er
ror occurred, no output PDF file produced!
Transcript written on introduction.log.
Latexmk: Missing input file: '../document.tex' from line
  '! LaTeX Error: File `../document.tex' not found.'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: Errors, so I did not complete making targets
```

<details>
<summary>LaTeX Workshop Output [Required]</summary>
```
[15:03:58] Recipe step 1: _irrelevant_\.vscode\extensions\james-yu.latex-workshop-7.0.2\scripts\latexmk.bat, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=./,introduction
[15:03:58] LaTeX build process spawned. PID: 4528.
[15:04:04] Recipe returns with error: 12/null. PID: 4528.
```
</details>

**Screenshots**

**Desktop [Required]:**
 - OS: Win 10 1803
 - VS Code version: 1.35.1
 - Extension version: 7.0.2

**Additional context**
Issue could be related to  #1434

**Comment by jlelong** [comment]
This is also related to #1438. In short, `introduction.tex` is considered as a root file as it contains `\documentclass` but it requires a file located at a higher level directory.

**Comment by sbaeurle** [comment]
thanks for developing a concept for subfile integration @jlelong 

I tried to compile the subfile again today and aparently the issue stil persists.

The docker volume mapping does only include the subdirectory and therefore latexmk is not able to include the preamble from the main document.

I verified that the compilation works perfectly when the docker volume mapping is change to `-v rootDir:/data` and latexmk is executed with `./subDir/subfile`

**Comment by sbaeurle** [comment]
yet with remote vscode coming it ist questionable if a custom docker integration is really needed
