### ISSUE TITLE
Tikzpicture preview

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1450]
Hi All,

I had an idea earlier for previewing tikzpicturs — https://github.com/James-Yu/LaTeX-Workshop/issues/1427#issuecomment-500757082 and I'm pleased to say I've actually made some progress towards it — [tecosaur/LaTeX-Workshop/tikzpicture-codelense](https://github.com/tecosaur/LaTeX-Workshop/tree/tikzpicture-codelense).

![image](https://user-images.githubusercontent.com/20903656/59705925-fa2fcc00-9231-11e9-9853-b55b91b958a3.png)

I'm not actually too far off, this is the current state of affairs
 - [X] Locate tikzpictures
 - [X] Create codelense
 - [X] create standalone file
 - [X] compile
 - [x] preview
 - [X] identify important tikz lines in file and include
 - [x] keep track of same tikzpicture and same standalone file
 - [x] recompile after typing in tikzpicture
 - [X] precompile preamble for faster compilation

Looking for general feedback / ideas on this.

**Comment by tecosaur** [comment]
Update: No change yet, will do a bit more work on this soon. I've had _some_ ideas about how to keep track of the same tikzpicture environment.

**Comment by tecosaur** [comment]
Currently looking for tikz 'bits' that should be pulled out of the main document for generating the preview. Stuff like `tikzset`. Any suggestions _very_ welcome.

**Comment by tecosaur** [comment]
Update: Process is being made! More details to come later. Shouldn't be too long before I start a PR.

**Comment by david-waterworth** [comment]
Nice work, it would be awesome if this worked for standalone tikz files referenced via `\input' , perhaps with a `magic' to point to a template file similar to how ktikz works (i.e. ktikz_tamplate.pgs sets up the preamble/preview environment for a standalone tikz file).

I normally put my tikz files in a comon figures folder and input them into the document - the tikz files themselves aren't standalone since the document preamble sets up colours etc).

**Comment by david-waterworth** [comment]
> Currently looking for tikz 'bits' that should be pulled out of the main document for generating the preview. Stuff like `tikzset`. Any suggestions _very_ welcome.

I have the following preamble. Not sure how you'd detect the colour references though? As I mentioned above, as an option perhaps a magic to a template could be used with a default?

\usepackage{tikz}
\usetikzlibrary{arrows,shapes,positioning,shadows,trees}
\definecolor{blue}{HTML}{0081FF}
\definecolor{grey}{HTML}{B0B0B0}

\usepackage{pgfplots}
\pgfplotsset{compat=1.12} 
\usepgfplotslibrary{fillbetween}

**Comment by tecosaur** [comment]
Thanks for the example preamble. I can try expanding the regex to get all those important bits. Here's a demo
![image](https://user-images.githubusercontent.com/20903656/61178606-f457bb80-a622-11e9-9188-1c58304a3630.png)
https://regex101.com/r/QcMKoe/1

If you have any other samples, I'd appriciate them :smiley:

Re: `\include`s — that sounds like a good idea, but I think we'd need some way of identifying that they are just tikzpictures, and not something else.

**Comment by david-waterworth** [comment]
I'm only just starting to use tikz, as I come across other stuff I'll upload.

Although it'll be quite difficult to get everything from the preamble that might be used in a fragment since you can put equations for example which might depend on a define from the preamble.

You may need to take the entire preamble?

**Comment by tecosaur** [comment]
That's why my implementation has the setting `latex-workshop.tikzpreview.preambleContents` which is a path to a file, the contents of which are inserted into the preamble used.

**Comment by david-waterworth** [comment]
Excellent, so it should work the same as gtikz / ktitz whihc is nice!

**Comment by tecosaur** [comment]
ktikz looks like a decent comparison to what I want this to end up being as capable as. In my opinion the "tikz commands" part of my _Snippets Pannel_ PR should also help make creating tikz figures easier.

**Comment by FMuro** [comment]
Now that LaTeX Utilities is unmaintained, would it be possible to recover TiZK previews in LaTeX Workshop? I think that this particular functionality should have never left, since TiKZ is more popular everyday.

**Comment by tamuratak** [comment]
No.
