### ISSUE TITLE
Retain focus after launching external pdf viewer

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#1454]
Launching an external pdf viewer moves the focus to the viewer. Please add support for retaining focus back to vs code. The sublime latex plugin has had this feature so it shouldn't be too difficult.

**Comment by jlelong** [comment]
You basically only launch the external viewer once, so this is not such a pain to switch focus back manually. I leave this for the community.

**Comment by musm** [comment]
Well no because everytime you rebuild the editor looses focus.

**Comment by musm** [comment]
This is only when
`  "latex-workshop.synctex.afterBuild.enabled": true `

**Comment by jlelong** [comment]
This is precisely the purpose of this option to call synctex, focus the viewer and highlight the `pdf` location corresponding to the `tex` position.

**Comment by musm** [comment]
Well I'd like to keep the feature of moving the pdf file to the current pdf location, so the pdf viewer is continually updating the location. But at the same time I don't want the editor to lose focus since I want to continue to type.

**Comment by musm** [comment]
In addition, if you close the external pdf viewer and rebuild it no longer relaunched the external viewer. (unrelated bug)

**Comment by tamuratak** [comment]
Notice that external pdf viewer is not officially supported. See [link](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfexternalcommand).

**Comment by musm** [comment]
Understood, but still would be nice seeing too improve the plugin. Trying to switch over from the sublime and latex tools form there.
