### ISSUE TITLE
citation viewer does not recognize biblatex journal names

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#1457]
Citation viewer does not recognize biblatex journal names for articles. The field is in the `journaltitle`  field of the bib file.

**Comment by jlelong** [comment]
Can you explain precisely what does not work and what you would expect? A screenshot may be helpful.

**Comment by musm** [comment]
![image](https://user-images.githubusercontent.com/4319522/59972303-c1a63000-955a-11e9-8ef1-45cde1682062.png)

Publication unknown for journal articles. For books works fine.
