### ISSUE TITLE
Bug Report: "autoBuild.enabled" option

### ISSUE THREAD

**Issue by hokiedsp** [James-Yu/LaTeX-Workshop#146]
Hi, first of all, great VS Code extension!

I run into a behavior that is not consistent with the description: re: autoBuild.enabled option. The option description in the setting JSON reads:

"Build LaTeX after saving LaTeX source file. This property defines whether LaTeX Workshop will execute the LaTeX toolchain command(s) to build the project after **new LaTeX contents are saved.**" (emphasis by me)

Meanwhile, in Windows VS Code with this feature turned on, the auto build is triggered immediately after any edit (as simple as typing a character) well before save.

Thanks!
Kesh

**Comment by James-Yu** [comment]
I can almost confirm this is a local problem. This feature has been implemented since the first several versions of the extension, and none have reported a similar problem. You may want to check if there are some other extensions interfering the default saving operation of vs code.

**Comment by James-Yu** [comment]
If you think the problem can be generalized, please provide some additional information such as LaTeX Workshop log, versions of vscode and extensions, and log messages in development console.
