### ISSUE TITLE
newcommandFile not robust

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#1460]
`latex-workshop.hover.preview.newcommand.newcommandFile`

setting this to `sty` file containing 
```
\usepackage{mathtools}
\newcommand*{\tran}{\mathsf{T}}
```

fails in terms of the hover preview

**Comment by jlelong** [comment]
The `latex-workshop.hover.preview.newcommand.newcommandFile` must not contain `\usepackage` instructions but only newcommands, because mathjax does not accept it. See [stackoverflow](https://stackoverflow.com/questions/21192606/can-i-add-latex-packages-to-mathjax).

**Comment by musm** [comment]
Could we keep the issue open? I know sublime latex tools uses a different approach, somewhat akin to the approach taken https://github.com/James-Yu/LaTeX-Workshop/issues/1450   by generating a texfile and cropping the corresponding output.
