### ISSUE TITLE
User-defined surrounding text

### ISSUE THREAD

**Issue by kenNash** [James-Yu/LaTeX-Workshop#1461]
Not sure this is a feature request.

I really would like to be able to define my own surrounding text. I tried editing a file "commands.json" in my User folder, with the following content:

`{
  "focus":{
    "command":"focus",
    "snippet":"focus{$1}",
    "detail":"Surround selection with \\focus"
  }
}
`

And it worked! But now that I've restarted VS Code, it doesn't work, anymore.

Ideas? Suggestions?

Many thanks.

**Comment by jlelong** [comment]
The `commands.json` file will be overwritten every time the extension gets updates. You should consider defining user snippets instead (call _Configure User Snippets_ from the command palette).
To surround a selection, you should define
```
"focus":{ "command":"focus", "snippet":"\\focus{${TM_SELECTED_TEXT}}", "detail":"Surround selection with \\focus" }
```

**Comment by kenNash** [comment]
Than you Jerome for your support!


> On 25 Jun 2019, at 15:37, Jerome Lelong <notifications@github.com> wrote:
> The commands.json file will be overwritten every time the extension gets updates.
> 
That’s why I didn’t edit the original commands.json, but a new one, located at ~/Library/Application Support/Code/User/, where my personal settings.json file resides (I’m on a Mac).

> You should consider defining user snippets instead (call Configure User Snippets from the command palette).
> To surround a selection, you should define
> 
> "focus":{ "command":"focus", "snippet":"\\focus{${TM_SELECTED_TEXT}}", "detail":"Surround selection with \\focus” }

If I do that instead, several warnings appear:
• Missing property “prefix”.
• Missing property “body”.
• Property command is not allowed.
• Property snippet is not allowed.
• Property detail is not allowed.

**Comment by jlelong** [comment]
My bad, here is the correct stuff
````
"focus": {
		"prefix": "\\focus",
		"body": "\\focus{${TM_SELECTED_TEXT}}",
		"description": "Surround selection with \\focus."
	}
````
Maybe you do not want to put the `\\` in the prefix.

**Comment by kenNash** [comment]
> On 25 Jun 2019, at 15:54, Jerome Lelong <notifications@github.com> wrote:
> 
> My bad, here is the correct stuff
> 
> "focus": {
> 		"prefix": "\\focus",
> 		"body": "\\focus{${TM_SELECTED_TEXT}}",
> 		"description": "Surround selection with \\focus."
> 	}
> Maybe you do not want to put the \\ in the prefix.
> 


Mmm, I’m missing something.

I put your code in my own latex.json file.
Now when I have some text selected, I hit cmd-\, which I bound to latex-workshop.surround. This opens a box on the top, where I can enter the predefined surrounding text prefixes, not my own.

What am I doing wrong?

Thanks again Jerome, very appreciated.

**Comment by jlelong** [comment]
You cannot use `CMd-\` with personal snippets. You need to call _Insert Snippet_ 

![2019-06-25 16 10 19](https://user-images.githubusercontent.com/2910140/60105616-ea4d4600-9763-11e9-9514-3c6a41e5b2c0.gif)

You can even assign a shortcut to _Insert Snippet_.

**Comment by kenNash** [comment]
> On 25 Jun 2019, at 16:12, Jerome Lelong <notifications@github.com> wrote:
> 
> You cannot use CMd-\ with personal snippets. You need to call Insert Snippet
> 
But this is waaay to long!

> You can even assign a shortcut to Insert Snippet.
> 

OK, I’m interested in this one. But I’m able to do it!
If I assign, say cmd-\ (or anything else) to insertSnippet, this doesn’t make the snippets box appear.

I’m veery confused and frustrated…

**Comment by jlelong** [comment]
The function to bind to a shortcut is `editor.action.showSnippets`.

**Comment by kenNash** [comment]
> On 25 Jun 2019, at 17:05, Jerome Lelong <notifications@github.com> wrote:
> 
> The function to bind to a shortcut is editor.action.showSnippets.
> 

Ooh, thank you! Now everything works!

(Still wondering why editing my own commands.json the way I did worked earlier, but not now...)


Many thanks, Jerome.
