### ISSUE TITLE
Synctex opens docs in incorrect window. 

### ISSUE THREAD

**Issue by vomout** [James-Yu/LaTeX-Workshop#1465]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

Reverse synctex (from Skim), to make VSCode open the source file in the position clicked on in the PDF, causes the file to be reopened in **the previously active** VSCode window, not the window where the document is already open, or the window whose workspace is associated with the directory of the document.

This has other annoying side effects, such as the the version control (Mercurial) repository being also reopened in the incorrect window/workspace, showing up as an additional provider in the source control tab. 

**To Reproduce**
1. Set up an external PDF viewer (Skim instructions: https://github.com/James-Yu/LaTeX-Workshop/issues/318#issuecomment-383610589)
2. Open two VSCode windows (possibly on two different MacOS workspaces) with different projects, different VSCode workspaces.
3. Edit a LaTeX project in one workspace/window, build it and have it opened in the external viewer.
4. Switch to the other VSCode window.
5. Return to the PDF viewer (without activating/focusing the other VSCode window, showing the source file for the document in the PDF viewer), and reverse synctex to make VSCode show a particular position of the source file.
6. Observe how the source file is reopened in the previously active wrong window (even if that window is on a different MacOS workspace).

**Expected behavior**

Should go to the already open document instead of reopening. If not already open, should open in a window with whose workspace the directory containing the source file is associated with. 

**Logs [Required]**

Unrelated

**Desktop [Required]:**
 - OS: MacOS 10.14.5
 - VS Code version: 1.35.1
 - Extension version: 7.0.2.

**Comment by jlelong** [comment]
This is not related to the extension but rather to the way vscode handles file opening.
I do not think we can anything about it.

**Comment by vomout** [comment]
Would be helpful to forward it instead of closing...

**Comment by jlelong** [comment]
This is completely independent of the extension. You can of course fill a bug report against vscode.
