### ISSUE TITLE
PDF location not refreshed if rebuild not needed.

### ISSUE THREAD

**Issue by vomout** [James-Yu/LaTeX-Workshop#1466]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

Triggering a rebuild (alt-cmd-b) or view (alt-cmd-v) does not cause the PDF viewer to jump to the cursor location if no PDF rebuild is needed. 

**To Reproduce**
1. Set up VScode to use an external viewer (e.g., Skim)
2. Create and edit a LaTeX document.
3. Build the document and observe the PDF viewer being launched to display the document at the cursor location
4. Move to another location in the document
5. Trigger a rebuild (alt-cmd-b) or view (alt-cmd-v)
6. Observe that the PDF viewer does not jump to the VScode cursor location. 
7. Make a small edit, save, and rebuild, and observe that it does now jump to the new location.

**Expected behavior**

In step 6. the PDF viewer should have jumped to the VScode cursor location.

**Logs [Required]**

Unrelated

**Desktop [Required]:**
 - OS: MacOS 10.14.5
 - VS Code version: 1.35.1
 - Extension version: 7.0.2.

**Comment by jlelong** [comment]
> In step 6. the PDF viewer should have jumped to the VScode cursor location.

I am not convinced about that. You can always use `ctr+alt+j`  to jump the cursor location.

**Comment by vomout** [comment]
> > In step 6. the PDF viewer should have jumped to the VScode cursor location.
> 
> I am not convinced about that. You can always use `ctr+alt+j` to jump the cursor location.

Principles of usability: few commands that just do the right thing. Git (nuts and bolts, cmd-alt-b vs cmd-alt-j) vs. Mercurial (just does the right thing).

**Comment by vomout** [comment]
Time to work on my fork. Horribly hostile project.

**Comment by vomout** [comment]
For anyone else seeking to fix this usability issue: https://github.com/vomout/LaTeX-Workshop_noautocrap/commit/55ffe28624077d3f40f930b031c97a401577f8da
