### ISSUE TITLE
View documentation not work under remote wsl

### ISSUE THREAD

**Issue by zhhhhxhq** [James-Yu/LaTeX-Workshop#1467]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5227132/60313851-2fa38a80-9993-11e9-8214-3960557e8576.png)
Under remote-wsl extension, the view documentation link not work (it did nothing).

Is there any way make it work?

**Comment by jlelong** [comment]
Finding the documentation relies on the `texdoc` command and I bet it is not found. You can configure `texdoc` path using `latex-workshop.texdoc.path`.

Have a look at (or paste) the extension logs to confirm my guess.

**Comment by zhhhhxhq** [comment]
Plese see the screenshot:
![image](https://user-images.githubusercontent.com/5227132/60332239-f8e86700-99c8-11e9-8147-c85c7192427a.png)
I have a windows 10 computer, but I compile latex file under the remote-wsl extension. So when I use texdoc, this command runs in wsl, so there is nothing happened. I hope to find a way make texdoc work in remote-wsl extension.

**Comment by tamuratak** [comment]
@zhhhhxhq please fulfill forms required in the issue template to facilitate communication.

Thank you for your cooperation.

**Comment by tamuratak** [comment]
@zhhhhxhq show us your `settings.json` of VS Code, especially `latex-workshop.texdoc.path`.

**Comment by jlelong** [comment]
I have added a new configuration variable `latex-workshop.texdoc.args`. You should be able to make everything work using the following configuration
````
"latex-workshop.texdoc.path": "wsl",
"latex-workshop.texdoc.args": ["texdoc", "--view"]
````

**Comment by tamuratak** [comment]
@jlelong, he says he is using `remote-wsl`. So, he has to make `texdoc` call a pdf viewer on Windows 10 from the inside of Linux in WSL. That is the problem. To my understanding, the way of calling a windows program in WSL is just calling the program. Weird, but true. See [link](https://docs.microsoft.com/en-us/windows/wsl/interop#run-windows-tools-from-wsl).

Making the pdf viewer  of `texdoc` configurable would help him. By calling `texdoc` with appropriate environment variables, `PDFVIEWER` and others, we can do that.

**Comment by tamuratak** [comment]
In his log message, `texdoc.exe` is called in WSL. That must be `texdoc` without the suffix in WSL.

With the full log messages, I wanted to make sure he really had used `remote-wsl`, or just `WSL`.

**Comment by KiruyaMomochi** [comment]
Edit `texdoc/texdoc.cnf` to add
```bash
viewer_pdf = (explorer.exe $(wslpath -w %s)) &
```

To get the location of `texdoc/texdoc.cnf`, use
```bash
texdoc -f
```
