### ISSUE TITLE
Autocompletion for \cite broken when changing filename

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1469]
Not a big issue, it is more to inform you. That being said, I update my bibliography like this and I have to reload vscode each time or change `latex` project to relaunch the search for the `.bib` file.

**Describe the bug [Required]**
If I change the name of my `.bib in a tex project, autocompletion for \cite breaks.

**To Reproduce**
1. Delete the `.bib` file
2. Put another one with the same name

**Expected behavior**
I would still have autocompletion for my bib items

**Logs [Required]**

<details>
<summary>LaTeX Workshop Output [Required]</summary>

```
[19:54:34] Parsed 388 .bib entries from ********/bibliographie.bib.
[19:57:23] Bib file watcher: ********/bibliographie.bib deleted.
[19:57:23] Forgetting parsed bib entries for ********/bibliographie.bib
```
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
Nothing
</details>

**Desktop [Required]:**
 - OS: macOS 10.14.5
 - VS Code version: 1.35.1
 - Extension version: 1.35.1

**Comment by PierreMarchand20** [comment]
I do know how to make code blocks working in detail environments....

**Comment by jlelong** [comment]
Hum, when a file is deleted we removed any intellisense it provided. So the behaviour is coherent and I cannot see an easy way of handling your workflow. Saving the root file should trigger a new detection of the bibliography. I think that if instead of first deleting and then putting a new file, you just overwrite the file directly, everything will work fine. Let me know if it helps.

**Comment by PierreMarchand20** [comment]
Yes, it handles better the case where overwriting the file:
```
[12:46:51] Bib file watcher - responding to change in **********/bibliographie.bib
[12:46:51] Parsing .bib entries from **********/bibliographie.bib
[12:46:51] Parsed 388 .bib entries from **********/bibliographie.bib.
```
I thought that we could add a command to trigger the parsing the `.bib` file, but I think it is not worth it if overwriting works fine. Thank you
