### ISSUE TITLE
[Enhancement] clean files recursively

### ISSUE THREAD

**Issue by Reeeeeemi** [James-Yu/LaTeX-Workshop#147]
If "latex-workshop.latex.clean.enabled" is set true, cleaner doesn't clean files under subfolder that contains my chapter tex files and aux files, I think it helps to prettify large latex project by making cleaner recursively clean tmp files. Thanks.

**Comment by James-Yu** [comment]
I cannot get what you mean. Why `.aux` file would be generated in sub-folders if the output folder is set to root?

**Comment by Reeeeeemi** [comment]
Sorry for this confusion. My main.tex at the root includes other tex files under a sub-folder, then aux files are generated both in the root and  sub-folder by default. The -aux-directory option offered by latexmk only redirect the main.aux. Is it be possible to redirect all aux files to the root directory. 
I'm a newbie at latex. Thank you so much.

**Comment by James-Yu** [comment]
I'd suggest you customize the clean file glob config. You can add a new item `subfolder/*.aux` to auto delete the `.aux` files in `subfolder/`. Please have a try and see if it works.

**Comment by Reeeeeemi** [comment]
It works like a charm! Thanks again.

Closed.
