### ISSUE TITLE
Placeholders in itellisense autosuggestions are incorrect

### ISSUE THREAD

**Issue by nakamin** [James-Yu/LaTeX-Workshop#1470]
This is the the problem that I see after accepting an autosuggestion for some command:
![image](https://user-images.githubusercontent.com/17557668/60564828-2c135900-9d2f-11e9-92a3-8bf210a9835d.png)
Not only is the highlight distracting, it prevense IntelliSense from triggering.
I think that the reason for this bug is in [this line.](https://github.com/James-Yu/LaTeX-Workshop/blob/aeaa583f2c118cbe0c6cd112ef0ee7c85e675616/data/commands.json#L226) The issue is that the placeholder is `$1`, but it should be `$0` since it is the last thing in the snippet. This can be fixed by changing the python script. I have taken a look at it but it isn't immediately obvious to me what has to be done.

**Comment by jlelong** [comment]
Using `$1` in  `"snippet":"documentclass{$1}"` is intended to be able to jump out of the `{}` by hitting `TAB`.  Note that `"snippet":"documentclass{$1}"` is equivalent to `"snippet":"documentclass{$1}$0"`.
