### ISSUE TITLE
Make invert more consistent with light/dark mode

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1474]
**Is your feature request related to a problem? Please describe.**

I switch between dark and light modes according to ambient lighting conditions.

Accordingly, I change the pdf invert setting to adjust it to the current theme.

This is not for aesthetic reasons: with bright lights around dark mode in my glossy screen is unusable, but under better lighting conditions it's easier on my eyes.

**Describe the solution you'd like**

Add a new invert setting that operates only when a light theme is set. Alternatively, add a flag to disable inverting when a light theme is set.

**Describe alternatives you've considered**

Commenting/uncommenting the invert option in settings file. This is a cumbersome hack.

Installing an extension that sets many options at the same time. Requires an extra extension and some tweaking. It's ok but I think it's somehow wrong that, while everything else is white, the pdf previewer remains black.

**Comment by tamuratak** [comment]
In an extensions process, we are not able to know whether the current theme is dark or not, although there is a workaround. See microsoft/vscode/issues/32813.

**Comment by jlelong** [comment]
I am closing the issue for the now. Please notify us when  microsoft/vscode/issues/32813 is solved and I will reopen the issue

**Comment by tamuratak** [comment]
#2158
