### ISSUE TITLE
VSCode 1.36 breaks syntax highlighting with minted environments

### ISSUE THREAD

**Issue by autinerd** [James-Yu/LaTeX-Workshop#1476]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
When using a minted environment, the syntax highlighting after the code inside the minted environment doesn't work properly. It still uses the first one for all next minted environments, and LaTeX syntax highlighting doesn't work properly at all (numbers and the word before and after a period are highlighted)

**To Reproduce**
Insert a minted environment into the document.
Examples:
```tex
\begin{listing}[htbp]
    \begin{minted}{python}
def main():
    return [test for test in range(3)]
    \end{minted}
\end{listing}

\begin{listing}[htbp]
    \begin{minted}{c}
struct test {
int test2;
int test3;
int test4;
}
    \end{minted}
\end{listing}
This is a test sentence. Here is a number: 39
```

**Expected behavior**
Everything works like it did in VSCode 1.35

**Logs [Required]**
No messages in both logs, which can say anything about it.

**Screenshots**
![Test 1](https://user-images.githubusercontent.com/27780930/60664231-a643fa80-9e61-11e9-92c0-02b51179d650.png)
![Test 2](https://user-images.githubusercontent.com/27780930/60664247-b3f98000-9e61-11e9-9546-dcce70d01553.png)

**Desktop [Required]:**
 - OS: Linux Mint
 - VS Code version: 1.36
 - Extension version: 7.0.2

**Additional context**
With 1.35 everything was fine.

**Comment by jlelong** [comment]
This issue appears only with `c` and `cpp`, so I think it is a bug in the C/C++ grammar. Using `java` code works fine
```
\begin{listing}[htbp]
    \begin{minted}{python}
def main():
    return [test for test in range(3)]
    \end{minted}
\end{listing}

\begin{listing}[htbp]
    \begin{minted}{java}
class test {
int test2;
int test3;
int test4;
}
    \end{minted}
\end{listing}
This is a test sentence. Here is a number: 39
````
I think a bug report should be filled against vscode repo.

**Comment by autinerd** [comment]
Thank you very much! I have now as a workaround like you did in your initial post in the vscode issue changed the LaTeX.plist from `source.cpp` to `source.c`, because I'm only using C code and the LaTeX syntax highlighting is more important to me.

But glad to know that it's not the fault from LaTeX-Workshop!

**Comment by jlelong** [comment]
We cannot do much on the extension side. As I understand from microsoft/vscode/issues/76603, it will be fixed in the next release of VSCode.
