### ISSUE TITLE
Specify PDF file location (use build-folder)?

### ISSUE THREAD

**Issue by fredrikbaberg** [James-Yu/LaTeX-Workshop#148]
Hi,
I've setup LaTeX-Workshop to use pdflatex, with build folder, with build folder, and also have it working with bibtex. What I'm unable to do is to open the PDF file after executing build command. Would it be possible to add a setting to find the PDF file in another folder?
My other option, which I will probably use for now (but I would like to use the build folder), is to hide the files from Visual Studio Code.

The following is what I added to my settings.json file:
```
"latex-workshop.latex.toolchain": [
        {
            "command": "pdflatex",
            "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-output-directory=build",
            "%DOC%"
            ]
        }, {
            "command": "bibtex",
            "args": [
            "build/%DOCFILE%"
            ]
        }, {
            "command": "pdflatex",
            "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-output-directory=build",
            "%DOC%"
            ]
        }, {
            "command": "pdflatex",
            "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-output-directory=build",
            "%DOC%"
            ]
        }
]
```

**Comment by fredrikbaberg** [comment]
After some more testing I managed to get the following to work (does not solve the issue of PDF in build folder, but I get a cleaner directory):
```
"latex-workshop.latex.toolchain": [
        {
            "command": "latexmk",
            "args": [
                "-pdf",
                "%DOC%"
            ]
        },
        {
            "command": "latexmk",
            "args": [
                "-c"
            ]
        }
    ]
```

**Comment by James-Yu** [comment]
Did you also set the `outputDir` config item for the extension in vscode?

**Comment by fredrikbaberg** [comment]
I wasn't aware of that item, so no. I was missing a comma (,) early in settings.json, so I didn't get suggestions, but now that is solved.
Except for using the suggestions from settings.json, is there documentation for what is available? If not, perhaps that would be useful.

**Comment by James-Yu** [comment]
All configurations are listed in the default one with explanation. So it seems to be redundant to provide an exact copy elsewhere.
