### ISSUE TITLE
Publish with npm

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#1483]
Clearly the template won't work here.

I tried to use `vsce publish` to publish `7.1.0` of the extension, after a successful `npm i`. However, `vsce` complained that
```
ERROR  Command failed: npm list --production --parseable --depth=99999
npm ERR! missing: mathjax@2.7.5, required by latex-workshop@7.1.0
npm ERR! missing: mathjax@2.7.5, required by mathjax-node@2.1.1
```
It seems that `npm` was preventing me from switching from `yarn`. Any idea? @jlelong @tamuratak

**Comment by tamuratak** [comment]
Stopping using `minify.sh` and adding entries to `.vscodeignore` seems to be an appropriate way although it is bothersome.

**Comment by James-Yu** [comment]
Emm interesting. Can you please remind me why we need to keep a local copy of mathjax? Do we have a solution to use the npm one?

**Comment by trevorgunn** [comment]
These lines in `minify.sh` seem to cause `npm list` to throw the error (which causes the script to fail):

https://github.com/James-Yu/LaTeX-Workshop/blob/64ee5410def8ef25fa233ede911563d36987b2d8/minify.sh#L1-L2

Specifically, `npm list` does not like `node_modules/mathjax/package.json` being overwritten by `viewer/mathjax/package.json`.

I am not sure what purpose exists in replacing the node version of mathjax with the one in `viewer/mathjax/`.

Also, as far as I can tell, there's no reference to `viewer/mathjax` anywhere in the code base. I don't know what purpose the local copy is serving.

**Comment by James-Yu** [comment]
We actually made a portable and minified version of mathjax in the local folder. The trimmed version is 3mb vs the original 60mb.

**Comment by trevorgunn** [comment]
Then it should be enough to replace everything except preserve npm's `package.json` to trick it into thinking the npm version of mathjax is still there.

**Comment by tamuratak** [comment]
I do not think the difference is enough big, 3mb vs the original 60mb, to justify this unusual trick.

**Comment by jlelong** [comment]
Besides the difference in size between the stock version of `mathjax` and the one shipped with LW, I feel more concerned by maintainability issues, bug corrections in the stock version, etc.

**Comment by James-Yu** [comment]
Will try to diff the local vs stock and add to .vscodeignore
