### ISSUE TITLE
Running in endless loop

### ISSUE THREAD

**Issue by MaxHausmann** [James-Yu/LaTeX-Workshop#1485]
Hey,

first: very nice addon for vs-code. I work with it on my bachelor-thesis and it is very appreciated!

Today when I tried to set some other parameters `htbp` instead of `H` for the `\figure`-environment, the addon ran into a endless loop, meaning that it tries to build the pages, but the pages are increasing until I force close vs-code.

**Normally I use this code to display one large svg on a landscape page:**
`\begin{landscape}
    \topskip 0pt
    \vspace*{\fill}   
    \begin{figure}[H]
        \centering
        \svgpath{{./img/ergebnisse/101_MK_RADIAL_KNEE}}
        \includesvg[width=\textheight]{orig_vs_sense_slice-002_echo-004}
        \caption{[...]}
        \label{fig:knee_2d_slice2_echo4}
    \end{figure}
    \vspace*{\fill}
\end{landscape}`

**Today I tested it with this code which produces the error:**
`\begin{landscape}
    \topskip 0pt
    \vspace*{\fill}   
    \begin{figure}[htbp]
        \centering
        \svgpath{{./img/ergebnisse/101_MK_RADIAL_KNEE}}
        \includesvg[width=\textheight]{orig_vs_sense_slice-002_echo-004}
        \caption{[...]}
        \label{fig:knee_2d_slice2_echo4}
    \end{figure}
    \vspace*{\fill}
\end{landscape}`

I am not sure if it is some error of latex itself or this plugin.

Best regards,
Max

**Comment by jlelong** [comment]
Can you try compiling your document outside vscode?
Show the extension logs and the LaTeX compiler logs?

**Comment by MaxHausmann** [comment]
Additional information: I realized, that `htbp` makes no sense, because it applies all different options at the same time.

**Comment by MaxHausmann** [comment]
Tried to compile it on command line, same issue. It counts up until force close.

**Comment by jlelong** [comment]
This is mainly a LaTeX issue and has nothing to do with the extension.

**Comment by jangxx** [comment]
For anyone else stumbling upon this issue, what fixed it for me was adding `"-halt-on-error"` to the command line parameters for pdflatex, which can be defined in the settings.json. In my case, my `latex-workshop.latex.tools` contains (among others) the following entry

```json
{
    "name": "pdflatex",
    "command": "pdflatex",
    "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-halt-on-error",
        "%DOC%"
    ],
    "env": {}
}
```
