### ISSUE TITLE
Paths with colon (:): LaTeX messages don't work properly, ChkTeX Messages work

### ISSUE THREAD

**Issue by autinerd** [James-Yu/LaTeX-Workshop#1487]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
When the .tex file is in a path which contains a colon, like `/home/user/test:testfolder/test.tex`, LaTeX messages in the 'Problems' tab are linked to the path with the colon and everything behind truncated, like `/home/user/test`, while ChkTeX messages are linked to the actual file.

**To Reproduce**
1. Create .tex file in a folder which contains a colon, like `/home/user/test:testfolder/test.tex`
2. Enable ChkTeX in Extension Settings
3. Paste this code for testing LaTeX and ChkTeX messages:
```latex
\documentclass{scrreprt}
\begin{document}
    This is a Test with a LaTeX message: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

    This is a test with a ChkTeX message. Test - Test.
\end{document}
```
4. Build the file
**Expected behavior**
The LaTeX message is linked to the actual file, like the ChkTeX message is.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
[10:23:24] BUILD command invoked.

[10:23:24] Found root file from active editor: /home/user/test:testfolder/test.tex

[10:23:24] Root file remains unchanged from: /home/user/test:testfolder/test.tex.

[10:23:24] Building root file: /home/user/test:testfolder/test.tex

[10:23:24] Build root file /home/user/test:testfolder/test.tex

[10:23:24] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/user/test:testfolder,/home/user/test:testfolder/test

[10:23:24] LaTeX build process spawned. PID: 7863.

[10:23:25] LaTeX log parsed with 1 messages.

[10:23:25] Recipe of length 1 finished. PID: 7863.

[10:23:25] Successfully built /home/user/test:testfolder/test.tex.

[10:23:25] No PDF viewer connected for /home/user/test:testfolder/test.pdf

[10:23:25] Parsing /home/user/test:testfolder/test.fls to compute dependencies
</details>

Developer Tools Console [Required]: No messages

**Screenshots**

**Desktop [Required]:**
 - OS: Linux Mint
 - VS Code version: 1.36.0
 - Extension version: 7.1.0

**Comment by trevorgunn** [comment]
The issue is in this line https://github.com/James-Yu/LaTeX-Workshop/blob/64ee5410def8ef25fa233ede911563d36987b2d8/src/components/parser.ts#L260

The set `[\w\u00a1-\uffff\-. \/\\#]` doesn't capture colons.

This presents an interesting question: which characters do we allow in file paths? There's no comprehensive list, it depends on the filesystem. Linux's Ext4 will allow a colon but Windows's NTFS will not.

**Comment by trevorgunn** [comment]
@jlelong I think I know the appropriate way to resolve this and am working on a fix.

**Comment by autinerd** [comment]
> which characters do we allow in file paths
All which are allowed (I know, even the newline is allowed in Linux). It should not be possible to get a path from LaTeX when the OS doesn't support it. From which line of LaTeX output the filename needs to be parsed? Maybe it's possible to get the path from another way.
> Linux's Ext4 will allow a colon but Windows's NTFS will not.
That's not true, when using alternate data streams in NTFS, I need the colon as well.

**Comment by trevorgunn** [comment]
> That's not true, when using alternate data streams in NTFS, I need the colon as well.

Apparently it depends on the "namespace" of the filesystem. See page 93: http://dubeyko.com/development/FileSystems/NTFS/ntfsdoc.pdf

The POSIX namespace allows almost everything, the Win32 namespace does not.

My patch covers everything in the POSIX namespace.
