### ISSUE TITLE
Automatically open external pdf viewer after building?

### ISSUE THREAD

**Issue by mejliu** [James-Yu/LaTeX-Workshop#1488]
Is it able to open a external pdf viewer (sumatrapdf) automatically after a successful build? thanks.

**Comment by jlelong** [comment]
Short answer No. You can set `latex-workshop.view.pdf.viewer: external` and define how to call `sumatrapdf` in `latex-workshop.view.pdf.external.command`. See [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfviewer). Then, `ctrl+alt+v` opens the `pdf` file in the external viewer.
