### ISSUE TITLE
LuaLaTeX/XeTeX

### ISSUE THREAD

**Issue by Karl273** [James-Yu/LaTeX-Workshop#149]
Hello,
I would like to know if it is possible to switch on the fly from pdflatex to lualatex/xetex?
In LaTeX-tools for atom/sublime one has both magic comments to specify the engine and a shortcut to choose one.
Thank you!

**Comment by James-Yu** [comment]
This is related to #102.

I did not try the engine magic comments. So if one set `% !TEX TS-program = xelatex`, how do LaTeX-tools determine the command line arguments of `xelatex`?

**Comment by James-Yu** [comment]
A preliminary implementation is given in #154
