### ISSUE TITLE
Are Tex directives for output directory supported?

### ISSUE THREAD

**Issue by hadim** [James-Yu/LaTeX-Workshop#1497]
Here are me Tex directives

```latex
%!TEX encoding = UTF-8 Unicode
%!TEX aux_directory = <<temp>>
%!TEX output_directory = <<temp>>
```

But `aux_directory` and `output_directory` does not seem to be supported.

**Comment by trevorgunn** [comment]
LaTeX Workshop supports the following `%!TEX` comments:

- [`program` and `options`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments) for setting the TeX compiler and its arguments.
- [`root`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file) to declare the root file in a multi-file set-up. (In case it can't be found through other means.)

`%!TEX encoding = UTF-8 Unicode` can be used in TeXMaker to tell TeXMaker how to encode the file it saves. In VSCode, you set this on the right side of the status bar at the bottom of the window. UTF-8 should be the default anyways.

If you want to set the output directory, you need to specify this as a command argument. For example, [the default `latexmk` recipe](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes) calls `latexmk` with `-outdir=%OUTDIR%` and the `%OUTDIR%` placeholder is configured in the [`latex-workshop.latex.outDir`](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshoplatexoutDir) setting.

**Comment by hadim** [comment]
Thank you for your answer. It's a shame, not all Tex software use the same Tex directives...

In the meantime `% !TEX options = -outdir=%TMPDIR%` works great!
