### ISSUE TITLE
\chapter etc. folds \thebibliography into it

### ISSUE THREAD

**Issue by autinerd** [James-Yu/LaTeX-Workshop#1498]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
\thebibliography is folded into \chapter, \section etc.

**To Reproduce**
```latex
\begin{document}
\chapter{Test}
\thebibliography
\end{document}
```
\chapter folds the \thebibliography into it

**Expected behavior**
Because \thebibliography acts as an chapter, don't fold it

**Desktop [Required]:**
 - OS: Linux Mint
 - VS Code version: 1.36.1
 - Extension version: 7.1.0

**Comment by jlelong** [comment]
This is not as easy as it sounds as `thebibliography` is an environment and the folding mechanism is not able to with `\begin...\end` blocks in the hierarchy level. It would require a major refactoring and I am not convinced the amount of work is worth it.

**Comment by jlelong** [comment]
If you really want to define `\thebibliography` as a chapter, set
```
        "latex-workshop.view.outline.sections": [
            "part",
            "chapter|thebibliography",
            "section",
            "subsection",
            "subsubsection"
          ]
```
