### ISSUE TITLE
Github has some nice looking bots

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1503]
## GitHub Bots

#1452 had me thinking, this seems like the sort of thing that a style checker could be good for with PRs. I had a look at https://github.com/marketplace and it seems there are one or two bots that may be of interest.

### https://github.com/marketplace/restyled-io
 - On a PR when autoformatter produces different output, create style fixing PR (on contributor's repo)
![image](https://user-images.githubusercontent.com/20903656/61102087-fabd2a80-a49e-11e9-84f9-4e1bddbe0a8c.png)

### https://github.com/marketplace/codefactor
 - similar to restyled-io. Might be better? Looks rather good in the images at least.
![image](https://user-images.githubusercontent.com/20903656/61102107-0b6da080-a49f-11e9-88cb-8aaa479e280f.png)

### https://github.com/marketplace/deepscan
 - Seems to do rather decent analysis of code, supports typescript and javascript

![image](https://user-images.githubusercontent.com/20903656/61102142-3fe15c80-a49f-11e9-8ecc-4d6786ebdf87.png)

### https://github.com/marketplace/issue-label-bot
 - Does what it says
![image](https://user-images.githubusercontent.com/20903656/61102191-76b77280-a49f-11e9-9c11-61661bf630db.png)

I don't expect these all to suddenly be integrated, but hopefuly one or two of these may be useful.

**Comment by James-Yu** [comment]
I've included the first one for a test. It seems that `prettier` is used, but I did not have prior experience with it. Let's see what happens.

**Comment by tecosaur** [comment]
I tried out the third one on my fork, and I'm pretty happy with what it did. I'll probably create a PR based on the output in a day or two.

See https://deepscan.io/dashboard/#view=project&tid=4729&pid=6480&bid=54298&subview=issues

#### Sample

![image](https://user-images.githubusercontent.com/20903656/62262240-898fe800-b44a-11e9-8fc6-08e16f5196e3.png)
