### ISSUE TITLE
Default build recipe `latexmk 🔃` is inappropriate

### ISSUE THREAD

**Issue by ken-nakanishi** [James-Yu/LaTeX-Workshop#1504]
**Is your feature request related to a problem? Please describe.**
Yes. This default build recipe force users to use pdflatex and then it confuses the latexmk users who have their own `.latexmkrc`, such as #1099 #1075 #1019 #830 . Latexmk is not only for pdflatex.

**Describe the solution you'd like**
I think the `-pdf` option in the arguments of the default recipe should be removed. 
https://github.com/James-Yu/LaTeX-Workshop/blob/46d0db6895124f5b28986f98ced31fd80a7e5120/package.json#L596

**Describe alternatives you've considered**
I think the default `latexmk 🔃` recipe should be renamed to `latexmk (pdflatex)`, and create another default recipe which is `-pdf` removed named like `latexmk (your latexmkrc)`.

**Additional context**
Nothing.

**Comment by jlelong** [comment]
Most people just want to get a `PDF` file out of the box, so I am afraid changing the default recipe is a bad idea. I really feel like leaving the name and behaviour of the default recipe unchanged as I think any change will create so many false bug reports when a new version is released. Anyway, you can just change the definition of the recipe to match your needs.

**Comment by TheNetAdmin** [comment]
A `latexmk (latexmkrc)` is really necessary. My LaTeX template provides `.latexmkrc` and it uses `xelatex`, but this plugin doesn't do what I expected, the `-pdf` overrides my `xelatex` setting.

Or another way: if there is a `latexmkrc/.latexmkrc` file in root dir, use `latexmk` instead of `latexmk -pdf`

**Comment by jlelong** [comment]
This is not so easy as if you want the extension to work well, the following options of `latexmk` are required
````
    "-synctex=1",
    "-interaction=nonstopmode",
    "-file-line-error",
    "-outdir=%OUTDIR%",
````
I do not want people to complain about broken features simply because they are missing some `latexmk` options. So, if you really insist I can define a new recipe `latexmk (latexmkrc)` with only these 4 options. Note that you can actually add it yourself, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes).

**Comment by TheNetAdmin** [comment]
No I don't mean you should define these rules, you just use the `latexmkrc/.latexmkrc` we provided without any option, if there is such a file. If no such file, do whatever you want.

**Comment by TheNetAdmin** [comment]
I just went through some code. As far as I can tell (I'm not a TypeScript developer so correct me if I'm wrong), we may take such method:

1. Check if there's a `latexmkrc` or `.latexmkrc` file
2. If there is, then use `src/components/builder.ts:buildWithExternalCommand`, with `latexmkrc` without any option
3. Considering the viewer need to find the output path, we need to parse `latexmkrc` file for variable `$out_dir` and add it into viewer's pdf search path.

If we can take one step further:

1. Add support for `latexmkrc` file, the file syntax can be found on CTAN or using TexLive's `texdoc latexmk`. It's not a complicated file format, and most of the options are compatible with `LaTeX Workshop`'s settings, we just need to read them out and override the vscode's settings.
2. If possible, we can parse `latexmkrc`'s build rules and set it as default for current workspace.
3. `latexmkrc` can also define clean rules, so we may also override that option.

**Comment by tamuratak** [comment]
I cannot see any strong reason to change the default behavior.

**Comment by TheNetAdmin** [comment]
@tamuratak Fine you don't use xelatex with latexmkrc so you don't know how important it is.

I'd rather do something useful instead of explaining why it's useful.

**Comment by jlelong** [comment]
As already said by @tamuratak and I, I do think changing the default is a bad idea. However, I understand that in some situations as when providing templates, it may be helpful to have a stock `latexmk` rule. The best I can offer for now is to add a new recipe, which simply calls `latexmk`. For the moment, I do not want to add extra code to read configuration variables directly from `latexmkrc`, so I am afraid the user will still have to set `latex-workshop.latex.outDir`.
