### ISSUE TITLE
Project Maintainers

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1507]
Hi @James-Yu and @jlelong,

I'll keep this brief. Just looking at the contributions page I see that @jabooth doesn't seem like he's been active on this repo since early 2017, and since then @tamuratak seems to have shown a interest in helping this extension run smoothly.

Given this, I think the project maintainers could do with an update.

**Comment by tecosaur** [comment]
Because images are nice and this one is appropriate

**Comment by James-Yu** [comment]
Done!
