### ISSUE TITLE
[Proposal] Trigger build when external program changes a tex file

### ISSUE THREAD

**Issue by harmishhk** [James-Yu/LaTeX-Workshop#151]
I would like to propose for a feature about triggering builds when a `.tex` file changes on the file system within the vscode-workspace. That means, a build triggers when some external program or the user from another editor changes the file.

My use-case: I sometimes use the [diagrams](http://projects.haskell.org/diagrams/) library which can directly generate a `.tex` file from Haskell files using the [PGF backend](http://projects.haskell.org/diagrams/doc/manual.html#the-pgf-backend). When it does so, I would like LaTeX-Workshop to rebuild the project. This way I can immediately see the changes in the preview tab. Currently the build does not trigger as my `activeTextEditor` in this case is not a `.tex` file.

I created a simple `FileSystemWatcher` to watch all `.tex` file in current workspace and trigger the build if it detects change in a `.tex` file (and if it not the same file as `activeTextEditor`, and if `autoBuild` is enabled). Pull request is #150.

This solution, however, requires that we [disable checking of `activeTextEditor` is a `.tex` file](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/commander.ts#L17-L19) when the build command is triggered. I don't know original reasoning behind this check, so I cannot say if this is harmful in some situations. In fact, disabling this check allows me to trigger build using the command palette even if the current file is not a `.tex` file or even if no file is open.

Note: there could be another way of triggering builds with additional file types. But this solution does not work in my use case as after saving the Haskell file it takes a couple of seconds to generate the TeX file after which I would like to build my LaTeX project.

**Comment by James-Yu** [comment]
Thank you for your contribution. I will do a code review soon.

Further discussion will be migrated to #150. This issue closed.
