### ISSUE TITLE
BibTeX folder volume mappings for docker

### ISSUE THREAD

**Issue by rmrnc** [James-Yu/LaTeX-Workshop#1512]
I appreciate your support for running latex in a docker container, but am missing support for BibTeX folders located on the docker host. This would require additional volume mappings in --AFAICT at least -- your `scripts/latexmk` script. E.g., 

```bash
docker run --rm --interactive \
    --env="BIBINPUTS=/usr/share/texmf/bibtex/bib" \
    --volume="${HOME}/bib:/usr/share/texmf/bibtex/bib" \
    --volume="${PWD}:${PWD}" \
    --workdir="${PWD}" \
    $LATEXWORKSHOP_DOCKER_LATEX latexmk $@
```

Let me add some observations:

1. Although the `BIBINPUTS` environment variable(s) could be assigned in the corresponding `Dockerfile` instead, I'd prefer it to be passed into the container at runtime thereby leveraging a VSCode specific configuration (see below). 
Why am I assigning a `BIBINPUTS` variable for the standard path `texmf/bibtex/bib` in the first place, you might ask? Pointing to the default TeXLive installation folder used by the Debian distro, i.e., `/usr/share/texmf`, by way of the `TEXMFROOT` environment variable (in `Dockerfile`), breaks LaTeX-Workshop's `latexmk` build, e.g., `! LaTeX Error: File 'book.cls' not found.` (at least on my box). I have no idea why that is.

2. The existing `"latex-workshop.latex.bibDirs"` configuration appears to provide a useful starting point for a volume mapping configuration. Though it would have to be declared as a mapping of host folders to docker folders instead of an array of host folders only, i.e,

```json
"latex-workshop.latex.bibDirs": [ 
    { "/path/to/host/folder1": "/path/to/mapped/docker/folder1" }, 
    ...
],
```

Thank you for your consideration.

**Comment by tamuratak** [comment]
VS Code supports Docker with [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) now. Please try it. You can also use [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl).
