### ISSUE TITLE
Add documentation to autofill popup

### ISSUE THREAD

**Issue by CovertKoala** [James-Yu/LaTeX-Workshop#1514]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
It would be helpful if the LaTex provided documentation for markup as it autocompleted.  For instance, when coding in python, as function names are autocompleted you'll see the function docstring pop up to provide additional information on usage.

**Comment by James-Yu** [comment]
That is almost purely a manpower task. PR w.r.t. these texts always welcomed.
