### ISSUE TITLE
MathReplacement: new feature

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1515]
Hello,

I've recently been inspired by https://castel.dev/post/lecture-notes-1/ to try to implement some of these features in vscode. However unfortunately
 - vscode does not support regex as snippet prefixes
 - vscode does not support no-prompt auto-activating snippets
 - vscode does not support getting textmate scope

So, I have tried to get this to work. I'd like to know whether you would like this to be incorporated into this extension as a PR, and if you have any thoughts on this in general.

### Feature Preview

![feature demo](https://user-images.githubusercontent.com/20903656/61422446-4dcf2b80-a93e-11e9-8455-495647fee5b8.gif)

#### Upside
It 'just happens'
(Can make typing out expressions significantly faster)
#### Downside
It 'just happens'
(has the potential to be annoying)
#### Other important components
_Will_ have:
 - Editable snippets
 - Enable/disable toggle

I've done some work, and created the following two classes:

### TypeFinder
 - Parses backwards from a given position
 - Does this until it can determine whether that position is in math/text mode
 - Seems to take 0-5ms on my machine.

### CompletionWatcher
 - Adds handler to `vscode.workspace.onDidChangeTextDocument`
 - Matches regex snippets against current line up to change
 - When there's a match, the placeholder is removed, and the body is used as a snippet
 - Only active when `typeFinder` says the current env is `maths`

To give a slightly better idea of what I have going on here are some screenshots:

![image](https://user-images.githubusercontent.com/20903656/61422650-22990c00-a93f-11e9-8138-43819f384750.png)
![image](https://user-images.githubusercontent.com/20903656/61422665-30e72800-a93f-11e9-9715-0d9a137520f3.png)

Also @Astrantia I have a suspicion you may be interested in this given the issue you created in vscode's repo.

**Comment by Astrantia** [comment]
@tecosaur I'd love to see this feature. In fact, I was inspired by Castel's lecture notes too, that you have linked in here. I switched from writing latex in vscode to writing latex in vim just because of this difference.

**Comment by tecosaur** [comment]
@Astrantia thanks for the offer! I really appreciate it.

I think performance-wise it probably isn't too bad. I've got TypeFinder down to ~1ms (average) using caching, and CompletionWatcher taking ~2ms to execute when there's nothing to replace, then up to ~50ms when there is. My computer is rather decent, but I think this should be useable for most people.
That said, if there is any more performance that can be squezed out I'd be happy to hear any suggestions!
This isn't in a branch yet (I'll update when it is) but it's basicly just two files which are: [completionWatcher.ts](https://pastebin.com/QpVAx713) and [typeFinder.ts](https://pastebin.com/RyBCJz0K).

However! Re: snippets, I'd love to expand the current collection to try to make as many (reasonable) reductions to keystrokes required for common stuff. The current interface for snippet items is this:
```ts
interface ISnippet {
    prefix: RegExp
    body: string
    description?: string
    priority?: number
    triggerWhenComplete?: boolean
    mode?: 'maths' | 'text' | 'any'
}
```
<details>
  <summary>And my current snippets are in here</summary>

  ```ts
[
    {
        prefix: /([A-Za-z])(\d)$/,
        body: '$1_$2',
        mode: 'maths',
        triggerWhenComplete: true,
        description: 'auto subscript',
    },
    {
        prefix: /([A-Za-z])\s?_(\d\d)$/,
        body: '$1_{$2}',
        mode: 'maths',
        triggerWhenComplete: true,
        description: 'auto subscript 2',
    },
    {
        prefix: /([A-Za-z])\s?\^([\d\+-]\d)$/,
        body: '$1^{$2}',
        mode: 'maths',
        triggerWhenComplete: true,
        description: 'auto superscript',
        priority: 2,
    },
    {
        prefix: /([^\s\+])\+\s?([^\s\+])$/,
        body: '$1 + $2',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /([^\s-])-\s?([^\s-])$/,
        body: '$1 - $2',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /([^\s&=])=\s?([^\s=])$/,
        body: '$1 = $2',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?\.\.\.$/,
        body: ' \\dots ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?=>$/,
        body: ' \\implies ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?=<$/,
        body: ' \\impliedby ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?\/\/$/,
        body: ' \\fraction{$1}{$2} ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /((\d+)|(\d*)(\\)?([A-Za-z]+)((\^|_)(\{\d+\}|\d))*)\//,
        body: '\\frac{$1}{$.1}$.0',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\siff$/,
        body: ' \\iff ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?!=$/,
        body: ' \\neq ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?~=$/,
        body: ' \\approx ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?~~$/,
        body: ' \\sim ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?>=$/,
        body: ' \\geq ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?<=$/,
        body: ' \\leq ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?>>$/,
        body: ' \\gg ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?<<$/,
        body: ' \\ll ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?xx$/,
        body: ' \\times ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?\*$/,
        body: ' \\cdot ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?(to|->)$/,
        body: ' \\to ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?\|->$/,
        body: ' \\mapsto ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /(^|[^\\])\s?(exp|sin|cos|tan|cot|arcsin|arccos|arctan|arccot|csc|sec|pi)$/,
        body: '$1\\$2',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s?(\\?\w+)(,\.|\.,)$/,
        body: ' \\vec{$1} ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\sbar$/,
        body: ' \\overline{$1} ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s([A-Za-z]{1,3})bar$/,
        body: ' \\overline{$1} ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\shat$/,
        body: ' \\overline{$1} ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\s([A-Za-z])hat$/,
        body: ' \\hat{$1} ',
        mode: 'maths',
        triggerWhenComplete: true,
    },
    {
        prefix: /\\\)(\w)$/,
        body: '\\) $1',
        mode: 'text',
        triggerWhenComplete: true,
    },
]
  ```
</details>

**Comment by tecosaur** [comment]
### Minor Update

Branch now exists at https://github.com/tecosaur/LaTeX-Workshop/tree/live-reformatter

**Comment by Astrantia** [comment]
@tecosaur Thanks for the updates. The issues I had with Castel's vim snippets is that they were unaware of the environment. I tried to add environments myself, but they resulted in slowing down the executions. I see you have addressed this in `'mode'` which is very cool. Also, do you think there would be a way to mass convert Castel's snippets to our `live-reformatter`?

**Comment by tecosaur** [comment]
## Another Update

@Astrantia I think I've curreently got most of them with 7fca72222a6069477a20e43890fbb7f764d53c92. 

Found a few issues with the typeFinder but hopefully after 830d21a7800730f2d31b11e48fdbece2650fb378 it's better.
Also managed to implement matching parenthesis to fractions with b19dcae59b7991705713bc8c7f45e5cfc028c322.

#### Matching parenthesis to fractions
`(xnp1+ykk)/2`

![parethesis fractions demo](https://user-images.githubusercontent.com/20903656/61453444-a6c7af80-a990-11e9-8ba3-f13fc89ac06e.gif)

### Todo
 - Sympy snippet would be nice
 - Remove some of the spaghetti from typeFinder
 - Make snippets configurable, issue: having objects in js instead of json is nice for regex.

**Comment by tecosaur** [comment]
@Astrantia

> Let me know if I can help.

If you still want to help out with this (I'll be fine if you don't, but appreciate it if you do) see the todo items in my last comment :smiley: feel free to make a quick PR to that branch.

**Comment by tecosaur** [comment]
You can now use this feature with https://marketplace.visualstudio.com/items?itemName=tecosaur.latex-utilities to find out why this is in another extension read about the functionality split that we decided on in #1544.

###### @Astrantia since you'll probably want to hear about this here's a ping.
