### ISSUE TITLE
Funky citation search

### ISSUE THREAD

**Issue by clsmt** [James-Yu/LaTeX-Workshop#1518]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**

When typing `\cite{`, a list of citations pop up. Then one start typing, for example, a word in the citation title, and that citation should be displayed (other non-matching items should disappear). However, this doesn't always work.

**To Reproduce**
A minimal example here
the tex file:
```
\documentclass[reprint]{revtex4-1}

\begin{document}

\title{random}

\author{clsmt}

\date{\today}

\maketitle

Trying some citation \cite{}

\bibliography{library.bib}

\end{document}
```

library.bib:
```
@article{Moerman1997,
abstract = {The past few years a lot of effort has been put in the development and fabrication of III-V semiconductor waveguiding devices with monolithic integrated mode size converters (tapers). By integrating a taper with a waveguide device, the coupling losses and the packaging cost of OEICs in future fiber-optical networks can be much reduced. This paper gives an overview of different taper designs, the possible fabrication technologies and performances of tapered devices},
author = {Moerman, Ingrid and {Van Daele}, P.P. and Demeester, P.M.},
doi = {10.1109/2944.658785},
isbn = {1077-260X},
issn = {1077260X},
journal = {IEEE Journal of Selected Topics in Quantum Electronics},
keywords = {III-V semiconductors,Mode-size converters,Monolithic integration,Optoelectronic integrated circuits},
number = {6},
pages = {1308--1320},
title = {{A review on fabrication technologies for the monolithic integration of tapers with III-V semiconductor devices}},
url = {http://ieeexplore.ieee.org/document/658785/},
volume = {3},
year = {1997}
}
@article{Yazaki1991,
author = {Yazaki, P.A. and Komori, Kazuhiro and Bendelli, Giampaolo and Arai, Shigehisa and Suematsu, Yasuharu},
doi = {10.1109/68.118000},
issn = {1041-1135},
journal = {IEEE Photonics Technology Letters},
month = {dec},
number = {12},
pages = {1060--1063},
title = {{A GaInAsP/InP tapered-waveguide semiconductor laser amplifier integrated with a 1.5 mu m distributed feedback laser}},
url = {http://ieeexplore.ieee.org/document/118000/},
volume = {3},
year = {1991}
}
```
Now in the .tex file, type `\cite{`, one would see this:
![image](https://user-images.githubusercontent.com/25810085/61514995-4481a580-a9b6-11e9-80fc-28a95969af9e.png)

Then, proceed to type `review` or `fabricate`, both citations disappear.

If typing `\cite{A`, it looks like this:
![image](https://user-images.githubusercontent.com/25810085/61515297-21a3c100-a9b7-11e9-87b6-95f93f7d5e43.png)
which is what I want. Then keep going to type `\cite{A r`, expecting to see the second item starting with `A review...`, but instead I see this:
![image](https://user-images.githubusercontent.com/25810085/61515379-51eb5f80-a9b7-11e9-8322-38df05af92d0.png)

I don't understand why this functions in this way?

**Desktop [Required]:**
 - OS: [Windows 7]
 - VS Code version: [1.36.1]
 - Extension version: [7.1.0]

**Additional context**
I think that search doesn't search the title or something?

**Comment by jlelong** [comment]
Related to #1379. The text used to do the filtering is built as `label author title journal`. Due a limitation in vscode (see microsoft/vscode/issues/74133), only the first `54` characters are considered for filtering.
