### ISSUE TITLE
Part of the highlighting does not work

### ISSUE THREAD

**Issue by allen-j-w** [James-Yu/LaTeX-Workshop#152]
Hi,
It's really a great extention but I have a hightlighting issue.

I've installed the Texlive and LaTex Workshop, I also configured the tool chain that I can build successfully. However, the highlightling of some key words like \section and \large could not work and they were not highlighted at all while some key words like \usepackage highlighted fine. Could you help me to make this straight?

**Comment by James-Yu** [comment]
Can you please give examples/screenshots describing your question? `highlight` is somehow misleading. Do you mean by syntax highlight?

**Comment by allen-j-w** [comment]
Hi,
My apology about the unspecific description. Yes, it's syntax highlight. After a careful compare I found the syntax highlight worked good. Actually the terms like \section and \large were highlighted in light yellow color which is not very distinguished with unhighlighted texts. Maybe I think it is possible to adjust the color more distinguishing a little bit. Any way, thanks very much.

**Comment by James-Yu** [comment]
The color for different tokens are controlled by themes instead of extensions. You can try out some others or customize one.
