### ISSUE TITLE
"autocites" not working as expected

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1523]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
I found two issues related to `autocites` citation snippet. To describe the bug, consider the simplest instance of `autocites[page-no]{citation-1}[page-no]{citation-2}`. The intellisense provides this suggestion as expected ---

![s-1](https://user-images.githubusercontent.com/24664855/61587627-32b52380-abab-11e9-8edb-ca12c57367cd.png)

1. However, when moving through the snippet, the bibliography references are shown only for the first reference block. In the second reference block, bibliography references are not shown.

![s-2](https://user-images.githubusercontent.com/24664855/61587640-858edb00-abab-11e9-8505-ecbf7b7aa917.gif)

2. The `autocites` does not get categorised properly. When checked with TM-scope command, this command gets categorised as `support.function.general.tex`. In contrast, other citation commands like `autocite` gets listed as `keyword.control.cite.latex` as expected. 

Because of this difference, the theme-colour does not apply properly. The difference in colouring can be seen in the below picture

![s-3](https://user-images.githubusercontent.com/24664855/61587677-3301ee80-abac-11e9-93a9-11fff67571b9.png)

**Desktop [Required]:**
 - OS: Linux Manjaro KDE
 - VS Code version: 1.36.1
 - Extension version: 7.2

**Comment by jlelong** [comment]
Note that only the first position is automatically autocompleted. For the next ones, the user has to call intellisense manually.

Fixing highlighting is much more difficult as we do not how many arguments of the form `[]{}` or `[][]{}` to expect. I still have to think of it.

**Comment by flimofly** [comment]
This issue still occurs with the most complex `\autocites` command, namely `\autocites(pre)(post)[][]{}[][]{}`.  Intellisense is not triggered automatically and cannot be triggered manually either. As described in the original issue, highlighting does not work for this command.

![Screen Recording 2020-05-04 at 01 25 07](https://user-images.githubusercontent.com/20085376/80928692-77aaef00-8da6-11ea-93ee-c2958407a455.gif)
