### ISSUE TITLE
There were undefined references

### ISSUE THREAD

**Issue by CharlesAnalyst** [James-Yu/LaTeX-Workshop#1525]
Issue Type: <b>Bug</b>

Description
I want to insert the reference (My Collection.bib) exported from Mendeley into the paper through the test.tex file. However, it gave me some warnings, such as 
"Citation 'Zhong2010' on page 1 undefined", 
"There were undefined references" and 
"Empty 'thebibliography' environment".  
Besides, in the PDF file, it always shows me the "?" where i cited (i want to see the correct digit number).

This is the code of "text.tex":
\documentclass{article}
\begin{document}
Random citation \cite{Zhong2010} embeddeed in text.
\newpage
\bibliographystyle{plain}
\bibliography{My Collection}
\end{document}

This is the code of "My Collection.bib":
@article{Zhong2010,
author = {Zhong, Hua and Beaulaurier, John and Lum, Pek Yee and Molony, Cliona and Yang, Xia and MacNeil, Douglas J. and Weingarth, Drew T. and Zhang, Bin and Greenawalt, Danielle and Dobrin, Radu and Hao, Ke and Woo, Sangsoon and Fabre-Suver, Christine and Qian, Su and Tota, Michael R. and Keller, Mark P. and Kendziorski, Christina M. and Yandell, Brian S. and Castro, Victor and Attie, Alan D. and Kaplan, Lee M. and Schadt, Eric E.},
doi = {10.1371/journal.pgen.1000932},
editor = {Mackay, Trudy F. C.},
issn = {1553-7404},
journal = {PLoS Genetics},
month = {may},
number = {5},
pages = {e1000932},
title = {{Liver and Adipose Expression Associated SNPs Are Enriched for Association to Type 2 Diabetes}},
url = {https://dx.plos.org/10.1371/journal.pgen.1000932},
volume = {6},
year = {2010}
}

Actual results:
Random citation [?] embeddeed in text.
Expected results:
Random citation [1] embeddeed in text.

Extension version: 7.2.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jlelong** [comment]
This is not related to the extension but this is rather a LaTeX issue. Have a look at the compiler logs.
