### ISSUE TITLE
Math Brackets Highlight

### ISSUE THREAD

**Issue by toooonyy** [James-Yu/LaTeX-Workshop#1529]
**Describe the bug [Required]**
probably related to James-Yu/LaTeX-Workshop#1430 and `Bracket Pair Colorizer 2`
The `\left` delimiter is not highlighted as in 1430's screenshot, 

**Expected behavior**
The `\left` delimiter pair is highlighted.

**Screenshots**
![Screen Shot 2019-07-23 at 13 54 48](https://user-images.githubusercontent.com/3480434/61714044-72197680-ad49-11e9-8bde-be89e2845e0d.png)
![Screen Shot 2019-07-23 at 13 52 06](https://user-images.githubusercontent.com/3480434/61714045-72197680-ad49-11e9-9093-0e92dac7ac34.png)

**Desktop [Required]:**
 - OS: macOS 10.14.5
 - VS Code version: 1.36.1
 - Extension version: 7.2.0

**Comment by jlelong** [comment]
I am afraid we cannot do much about that. Anyway, note that `Bracket Pair Colorizer 2` is listed as an incompatible extension, see [https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions)

**Comment by toooonyy** [comment]
> I am afraid we cannot do much about that. Anyway, note that `Bracket Pair Colorizer 2` is listed as an incompatible extension, see https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions

Yeah, I do read the FAQ, just wonder how @ chenr12 get it works properly
<img width="679" alt="1" src="https://user-images.githubusercontent.com/3480434/61714728-223baf00-ad4b-11e9-86ca-70afd2d8c3bb.png">

**Comment by chenr12** [comment]
In `~/.vscode/extensions/james-yu.latex-workshop-7.2.0/syntax/syntax.json`, I modify the `"brackets"` field to be: 
```
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["\\{", "\\}"],
		["\\left(", "\\right)"],
		["\\left[", "\\right]"],
		["\\left\\{", "\\right\\}"]
	],
```
I am not sure if this would bring in any incompatibility issue, but in this way `Bracket Pair Colorizer 2` works just fine for me.

**Comment by toooonyy** [comment]
> In ``

Thx, that works.
