### ISSUE TITLE
Surround selected text with a command input by the user

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1530]
This is a follow up on #246 from @jlanza

The current surrounding command only enables the user to select a command from a fixed list. Allowing the user input would help. I am summarising the discussion in #246.

What could be done is to wrap the selections with `{...}` and put a multi-cursor before the opening `{`. Quoting @jlanza, other options could be

1. Something similar to the one you have already implemented. The only difference would be that in case the typed text is not in the list, it should be accepted. For instance, right now \ac for glossaries is not included in the list, so I cannot use the keyboard shortcut.
2. Another option would be to enable adding new commands to a configuration file, so you will be adding new commands to the list. I guess your current list is hard coded somewhere else. This way you won't be typing something undesired. It is less friendly.
3. You can also think on a mix between option 1 and 2. That is, when you type and click enter on a non-included one, it is added to `settings.json` in your local folder.

**Comment by tecosaur** [comment]
To me, this isn't a big deal. If it's some unusual command, I'd imagine you'd have to type it anyway. You'll always have to select the text you want to surround. Hence I don't see much of a benefit.

| as current | dedicated method |
|---|---|
| select text | select text |
| type `{` | trigger 'surround'  command |
| type `\` | |
| type `command` | type `command` |

If it's a really common wraping e.g. `\( ... \)` it's easy to add your own keyboard shortcut for it.

Am I missing something?

**Comment by jlelong** [comment]
I was not aware of the `select + {` to surround some selected text with `{`. If I got it right, it actually works with any delimiter listed in `surroundingPairs` in [syntax.json](https://github.com/James-Yu/LaTeX-Workshop/blob/c48365a3de08a4faa9b2ea99eba2e4cd8125cfd5/syntax/syntax.json).
Then, I agree that there is not much we can do to improve surrounding. It would be good if the cursor were put before the opening `{` instead of being after the closing `{`, no matter the direction of the selection.

Maybe we could list in the `QuickPick` window all the commands available for completion included the ones defined in the current LaTeX project.

**Comment by tecosaur** [comment]
@jlelong can confirm `(` `[` and `{` all automatically surround the selection.

**Comment by jlanza** [comment]
I was just requesting the solution in order to be coherent, so any time you want to include a command you can use the same shortcut. There is no point in only include the shortcut for commands that you (the developers) have hardcoded somewhere else. I just think it is more sensible to accept any command (and somehow include them in a local file, as for instance, the words in a dictionary).
I knew about select + { or [ or (, but the cursor is set at the end of the word. That implies then 2x ctrl+ left, plus \ , plus write the command (without any tip), plus 2xctrl+ right.

Anyway, you have the final decision, and I only can thank you for such a good extension.

**Comment by jlelong** [comment]
> Maybe we could list in the QuickPick window all the commands available for completion included the ones defined by the user in the current LaTeX project.

I think this could a sensitive improvement. @jlanza Would it be worth it for you?

**Comment by tecosaur** [comment]
@jlelong a PR that I've been considering doing for a while ago (after my current set) is adding "go to definition" actions for in-document macros (it would be nice to do all macros, but that can come later).
I want to add this for those occasions when you are using a macro and then realise you want to tweak it. Simply doing `ctrl`+`click` to go to the definition is much nicer than `ctrl`+`f`+`\newcommand{\thing` or scrolling.

If you plan on adding user macros to the quick pick I think these two things would work well together.

**Comment by jlanza** [comment]
> 
> 
> > Maybe we could list in the QuickPick window all the commands available for completion included the ones defined by the user in the current LaTeX project.
> 
> I think this could a sensitive improvement. @jlanza Would it be worth it for you?

How are you planning to get the ones defined? Do I have to enter them manually? In any case for me it would be more than enough.

**Comment by jlelong** [comment]
We already the user files for `\newcommand`, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#commands).

**Comment by jlanza** [comment]
> 
> 
> We already the user files for `\newcommand`, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#commands).

Then, I guess just including this ones in the QuickPick window would be more than enough.

**Comment by tecosaur** [comment]
@jlelong my impression was (haven't yet looked at the relevant files) is that the IntelliSense works by seeing when the commands are used. Is that correct?

**Comment by jlelong** [comment]
After a bit of testing, I confirm that any command already used in the text as `\mycommand{...}{...}` appears in the QuickPick window. The only requirement is that you have already used the command once in your LaTeX project.

I am closing this issue as I do not think we can do really better.

**Comment by jlanza** [comment]
Sorry commenting again on a closed issue. Have you changed anything in the new LW updates? Suddenly after the last update this new feature has stopped working? Is there any option that now is set to false and previously wasn't?

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template.
