### ISSUE TITLE
Build only works for files changed from within vscode

### ISSUE THREAD

**Issue by david-waterworth** [James-Yu/LaTeX-Workshop#1535]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**

Have to manually touch a .tex file to build it. I'm generating a bunch of reports programatically, the process involves copying a template .tex file to a sub folder and generating a series of images / table.tex files in the same folder. The template file \includegraphics{} or  \input{} the files.

The issue is the files aren't altered in vscode. When I open them in the editor and select "Recipe: latexmk" nothing is built. If I touch the file, then it's ok. The log below inludes a missing report.fls file

[17:31:07] Handle data type: close
[17:31:11] Found root file from active editor: /home/david/dev/model/reports/report.tex
[17:31:11] Found root file from active editor: /home/david/dev/model/reports/report.tex
[17:31:11] Root file changed from: /home/david/dev/model/reports/report.tex. Find all dependencies.
[17:31:11] Root file changed -> cleaning up old file watcher.
[17:31:11] Instantiating a new file watcher for /home/david/dev/model/reports/report.tex
[17:31:11] Parsing /home/david/dev/model/reports/report.tex
[17:31:11] Adding /home/david/dev/model/reports/metrics.tex to file watcher.
[17:31:11] Parsing /home/david/dev/model/reports/metrics.tex
[17:31:11] Adding /home/david/dev/model/reports/hyper-parameters.tex to file watcher.
[17:31:11] Parsing /home/david/dev/model/reports/hyper-parameters.tex
[17:31:11] Cannot find file /home/david/dev/model/reports/report.fls
[17:31:11] Root file remains unchanged from: /home/david/dev/model/reports/report.tex.

**Desktop [Required]:**
 - OS: Ubuntu 18.04
 - VS Code version: 1.36.1
 - Extension version: 7.2.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by jlelong** [comment]
See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file) for an explanation about how `.fls` files are used. It is not a problem if they are not available.

Please the full logs from the extension, not just an excerpt. You will most likely see that `latexmk` itself is responsible for that your project is already up-to-date and does not a new compilation. The extension simply calls the recipe every you build the project.

**Comment by david-waterworth** [comment]
That is the full output. I cleared both logs first, then opened a tex file.

The last message in "Latex Workshop" log is always Root file remains unchanged
The "Latex Compiler Log" is empty

It seems that it's decided there's no need to run latexmk, despite there not being any output.

As soon as I touch the file, then it's ok

**Comment by jlelong** [comment]
There must be some part of the logs missing as there is no reference to any recipe being called. When select `Recipe: latexmk`, that should be written in the logs. Do you rely on the _build on change_ feature to automatically build your project?

**Comment by david-waterworth** [comment]
Normally but when it doesn't work I run it via Recipe: latexmk

Might be related to https://github.com/James-Yu/LaTeX-Workshop/issues/1481

It was working fine today on my office PC, that has an older version of vscode

On my home PC, Recipe: latexmk does nothing, but F1 > Latex Workshop: Build Latex Project works fine

It's almost like none of the command links in the LATEX window are working, i.e. I just noticed View LaTex Compiler log doesn't work either.

**Comment by jlelong** [comment]
Strange because `Recipe: latexmk` works with a single click.
I think we need to wait until the issue is solved in vscode.

**Comment by david-waterworth** [comment]
@jlelong I found the problem, there's an editor setting `workbench.list.openMode` which can be single or double click. I had it set to double click, this then changes how the links on the LATEX panel behave. I'm not sure if this is a new thing or not.
