### ISSUE TITLE
TikZ Preview has trouble compiling on Windows/MiKTeX

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1540]
This is a continuation of the last few bits of conversation in #1528, around this comment: https://github.com/James-Yu/LaTeX-Workshop/issues/1528#issuecomment-515290817.

To quote @joulev, this is the issue.

> @tecosaur I just checked, and both `latexmk` and `pdftex` inside VSCode don't work :disappointed:.
> 
> If I run the commands from the command line, both produce no error messages, but there are nothing in the PDF file. But `\tikzset` is recognized!
> What I have done
> 
>  1. Run `latexmk` in the editor.
>  2. Run `pdftex` from the command line.
>  3. Run `latexmk` from the command line.
> 
> 
> These are the relevant files I think. Ask me if you want more information.

(go to https://github.com/James-Yu/LaTeX-Workshop/issues/1528#issuecomment-515290817 for files)

I was unable to reproduce the issue with MiKTeX on Win7.

**Comment by trevorgunn** [comment]
This is what my pull request: Tecosaur#5 fixes. I've tested it on Windows and Linux and everything compiles fine.

**Comment by tecosaur** [comment]
My interpretation of joulev's comment is that he manually ran the commands and it didn't work. So while your PR (just merged btw, thanks) does fix an issue, I think joulev is encountering a different one.

**Comment by trevorgunn** [comment]
Well, if running the commands manually doesn't work for one person, that's not really an issue with this extension unless the commands don't work for anyone. But they do work for both of us so I'm thinking it could be a missing dependency issue.

`latexmk` requires Perl, which is not included with Windows or with MiKTeX. This was an issue for me when I switched from Texlive to MiKTeX on Windows.

@joulev If this is the issue, you can install Perl from http://strawberryperl.com/. Also make sure you have the `mylatexformat` package and `standalone` class installed for MiKTeX. (Although, MiKTeX should prompt you to install them if they are not already installed.)

**Comment by joulev** [comment]
@trevorgunn Interestingly I already have Perl, `mylatexformat` and `standalone` installed. The following commands run well:

```
perl -v
texdoc mylatexformat
texdoc standalone
```

**Comment by tamuratak** [comment]
@tecosaur  Please reopen this issue in the repository of LaTeX Utilities.

**Comment by tecosaur** [comment]
I think I'll just close this and if this seems to still be an issue make a new one in LU. From what joulev and trevorgunn said it seems like this may have something to do with joulev's particular system at this point.

@joulev if after the upcomming batch of updates you still have issues, feel free to make an issue in https://github.com/tecosaur/LaTeX-Utilities/

**Comment by joulev** [comment]
Thanks. I will try some workaround in advance (maybe I messed up something in my system).

**Comment by joulev** [comment]
@tecosaur Today I got to work and had a check, and... it works. I think at first it was working, but I was breaking something; and now everything is fixed. Thanks for the feature!

**Comment by tecosaur** [comment]
@joulev good to hear!

**Comment by joulev** [comment]
Apparently in the 8.0.4 update, everything related to Ti*k*Z preview is lost.

**Comment by trevorgunn** [comment]
@joulev Certain features were moved to a separate extension: https://marketplace.visualstudio.com/items?itemName=tecosaur.latex-utilities
