### ISSUE TITLE
Build procces freezes

### ISSUE THREAD

**Issue by M4l1K** [James-Yu/LaTeX-Workshop#1546]
Hi, I already read through all of the other issues, but no solution did work for me! My build kind of freezes and the LaTeX Compiler Log doenst show anyting:

Workshop-Log:
```
[13:43:29] Initializing LaTeX Workshop.
[13:43:29] Cannot run pdflatex to determine if we are using MiKTeX
[13:43:29] Creating LaTeX Workshop http and websocket server.
[13:43:29] LaTeX Workshop initialized.
[13:43:29] Found root file from active editor: /Users/user/Documents/Uni/Mathematik/Karten.tex
[13:43:30] Root file changed from: undefined. Find all dependencies.
[13:43:30] Instantiating a new file watcher for /Users/user/Documents/Uni/Mathematik/Karten.tex
[13:43:30] Parsing /Users/user/Documents/Uni/Mathematik/Karten.tex
[13:43:30] Cannot find file /Users/user/Documents/Uni/Mathematik/Karten.fls
[13:43:30] Server created on 127.0.0.1:62949
[13:43:30] Snippet data loaded.
[13:43:30] LaTeX Workshop version: 7.2.0
[13:43:56] BUILD command invoked.
[13:43:56] Found root file from active editor: /Users/user/Documents/Uni/Mathematik/Karten.tex
[13:43:56] Root file remains unchanged from: /Users/user/Documents/Uni/Mathematik/Karten.tex.
[13:43:56] Building root file: /Users/user/Documents/Uni/Mathematik/Karten.tex
[13:43:56] Build root file /Users/user/Documents/Uni/Mathematik/Karten.tex
[13:43:56] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=,/Users/user/Documents/Uni/Mathematik/Karten
```
Here is my Settings:

```
{
    "editor.fontSize": 16,
    "workbench.colorTheme": "Atom One Dark",
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "latex-workshop.view.pdf.viewer": "tab",
    "terminal.integrated.fontSize": 16,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 5000,
    "latex-workshop.view.pdf.external.command": {
        "command": "open",
        "args": [
            "-a",
            "preview",
            "%PDF%"
        ]
    },
    "latex-workshop.chktex.path": "/Library/TeX/texbin/chktex",
    "latex-workshop.latexindent.path": "/Library/TeX/texbin/LatexIndent",
    "latex-workshop.view.pdf.ref.viewer": "tabOrBrowser",
    "latex-workshop.synctex.path": "/Library/TeX/texbin/synctex",
    "latex-preview.command": "/Library/TeX/texbin/pdflatex",
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-outdir=",
                "%DOC%"
            ],
            "env": {}
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ],
            "env": {}
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ],
            "env": {}
        }
    ],
    "python.pythonPath": "/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin"
}
```

OS: 10.14.3
VS-Code: 1.36.1
Workshop: 7.2.0

**Comment by tamuratak** [comment]
Please fill out information required in the issue template.

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by tamuratak** [comment]
@M4l1K Please update both VSCode and LaTeX Workshop to the latest versions.

**Comment by M4l1K** [comment]
@tamuratak Updated both. Still the same.

**Comment by tamuratak** [comment]
Show us new log messages. Make sure that you can compile your LaTeX document with latexmk in the terminal.

**Comment by tamuratak** [comment]
Set "-outdir=" appropriately.

**Comment by M4l1K** [comment]
**I can not run latexmk in Terminal:**

```
userss-MBP-3:Mathematik user$ latexmk
bash: latexmk: command not found
```

**I also can not install latexmk in terminal:**

```
user$ sudo tlmgr install latexmk
sudo: tlmgr: command not found
```

Reseted all settings

**Comment by tamuratak** [comment]
This issue is not related to LaTeX Workshop.
