### ISSUE TITLE
Improve color of border of \boxed in MathJax preview

### ISSUE THREAD

**Issue by joulev** [James-Yu/LaTeX-Workshop#1548]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**
Done.

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**
Done

**Describe the bug [Required]**
Consider this MWE

```latex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[\boxed{\frac{1}{2}+\frac{1}{3}+\frac{1}{6}=1}\]
\end{document}
```

The MathJax preview on hover is working fine with light themes. (Screenshot 1). However, with dark themes, the box created by `\boxed` is still black (even when everything else becomes white) (Screenshot 2).

Moreover, in high-contrast themes, it is almost invisible (Screenshot 3).

**Expected behavior**
The box has the same white color with everything else in dark themes.

**Logs [Required]**
<details>
<summary>LaTeX Workshop Output [Required]</summary>

Not sure if this is related. I did not even compile the document.

```
[12:17:23] Initializing LaTeX Workshop.
[12:17:24] pdflatex is provided by MiKTeX
[12:17:24] Creating LaTeX Workshop http and websocket server.
[12:17:24] LaTeX Workshop initialized.
[12:18:29] Server created on 127.0.0.1:54427
[12:18:31] Snippet data loaded.
[12:18:58] LaTeX Workshop version: 7.2.0
```
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

IMHO there is nothing suspicious here.
![a](https://i.stack.imgur.com/TdgRz.png)
</details>

**Screenshots**
<details>
<summary>Screenshot 1 &ndash; light theme</summary>

![a](https://i.stack.imgur.com/6DfNv.png)
</details>

<details>
<summary>Screenshot 2 &ndash; dark theme</summary>

![a](https://i.stack.imgur.com/ZCBib.png)
</details>

<details>
<summary>Screenshot 3 &ndash; high-contrast theme</summary>

![a](https://i.stack.imgur.com/EPdrh.png)
</details>

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.36.1
 - Extension version: 7.2.0

**Comment by tecosaur** [comment]
@tamuratak could this just be a matter of regex-replacing `color="#000000"` (or something similar) with the svg output?
