### ISSUE TITLE
LaTeX code/multi-file parser rework

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#1549]
First apology to all contributors that I did not put much time on the extension 😭 

Recently @tamuratak had a new latex parser idea that I really like. It made me think of the way this extension did the context-based language feature parsing, especially `\input` siblings in multi-file projects. See the dizzying `findAllDependentFiles` and `findDependentFiles` functions in https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/manager.ts for examples.

To make at least that block of code to be more intelligible, I would like to work on a new multi-file parser that provides 1) complete text, 2) file input points, 3) file hierarchy. The parser should be so efficient that updates can be made between edits, i.e., updates are partial and the parser should be stateful.

This is just a preliminary idea, and it seems that this parser can reside in either this extension or https://github.com/tamuratak/latex-utensils (but need to think about the stateful update). Also, discussions and ideas greatly welcomed! @jlelong @tecosaur

**Comment by tecosaur** [comment]
Having parsing as opposed to regex definitely sounds like a good idea to me.

Something I'd like to do in the future anyway is to do some nice auto-completion for stuff like glossary entries and some bits of tikz (e.g. named coordinates/nodes). I think that having a robust and well thought out parser would make this easier.

For efficient re-parsing, a basic but possibly effective method is to register an `onDidChangeTextDocument` handler, and the for the changed lines to be re-parsed. This should provide good savings on work, however, it would need to mesh well with earlier parsed sections (**issue 1**). The main difficult here would I expect be keeping track of which lines correspond to which parsed objects and in an efficient way too (**issue 2**). Perhaps an offset based approach (relative to the last parsed object) may work relatively efficiently/easily.
