### ISSUE TITLE
Running the contributed command: 'latex-workshop.showCompilationPanel' failed.

### ISSUE THREAD

**Issue by carstenhag** [James-Yu/LaTeX-Workshop#1552]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Did not test, sorry. I guess this is a Latex-Workshop or VSCode thing.

**Describe the bug [Required]**
Clicking on the progress indicator (0/42 pages, progress bar) at the bottom of VS Code, nothing except this error warning shows up:

`Running the contributed command: 'latex-workshop.showCompilationPanel' failed.`

The logs don't mention this or the click at all.

pdflatex biber makeglossaries pdflatex recipe. Compiles fine. Used to show stats.

**To Reproduce**
1. Start a build
2. Click on the progress indicator
3. Error shows up, no progress window

**Expected behavior**
The compilation window opens and shows stats (worked previously)

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
Not relevant (clicking on the progress indicator does not show anything -- compilation runs fine.
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
[Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] PDF 85a14690de5c39e6d1c3b49512b4d111 [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 2.0.943)
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393 Running the contributed command: 'latex-workshop.showCompilationPanel' failed.
onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] PDF fc532f2af29dd8371f38f6b196525ec0 [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 2.0.943)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393 Running the contributed command: 'latex-workshop.showCompilationPanel' failed.
onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] PDF 1c2638d9b937a5cf5bcb2d206b675d12 [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 2.0.943)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] PDF dd33c3bf11e3a6fa7d152590ec08620b [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 2.0.943)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393 Running the contributed command: 'latex-workshop.showCompilationPanel' failed.
onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3582 [Embedded Page] PDF 5711c7652961fcd5080dfd71714f2af8 [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 2.0.943)

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393 Running the contributed command: 'latex-workshop.showCompilationPanel' failed.
onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2393

</details>

**Desktop [Required]:**
 - OS: macOS Mojave -- 10.14.5
 - VS Code version: 1.36.1
 - Extension version: 7.2.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by carstenhag** [comment]
Oh yeah, a "LaTeX Compilation Live Info" tab opens, but it doesn't contain anything, it is blank.

**Comment by tecosaur** [comment]
This is very interesting. I happen to be having the same issue, however I'm unable to reproduce it in "debug" mode :disappointed:.

**Comment by carstenhag** [comment]
What do you mean with debug mode?

**Comment by tecosaur** [comment]
Sorry that was unclear. When I start the extension using the from my development copy (clone of this repo), checkout the `7.2.0` tag, and run it; I can't reproduce the issue. However, I do have it in non-development/debug mode.

The pertinent line from your console log looks like:
```
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. 
```

I'll do a little investigation soon-ish and report back.

**Comment by tecosaur** [comment]
I think this works after `7.3.0`. Well, I was having the same issue and now I'm not. Let me know if it's different for you @carstenhag an I'll reopen the issue.

**Comment by lukasdiegelmann** [comment]
Actually, it does not.  Using v8.16.1 and I keep getting that error with a correct TeXLive install.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).
