### ISSUE TITLE
Dark on dark background in equation preview

### ISSUE THREAD

**Issue by JarnoRFB** [James-Yu/LaTeX-Workshop#1557]
**Is your feature request related to a problem? Please describe.**
Hi, first of all thanks for the great extension! When using hover to preview equations it is hard to see the actual equations, because of the dark background.
![Screenshot from 2019-07-31 16-46-50](https://user-images.githubusercontent.com/8550270/62222006-e344d380-b3b2-11e9-8a53-551938401c53.png)

**Describe the solution you'd like**
Automatically use a light background color.

**Additional context**
I am using version 7.3.0

**Comment by trevorgunn** [comment]
The extension already does this: https://github.com/James-Yu/LaTeX-Workshop/blob/v7.3.0/src/providers/hover.ts#L354-L403

There are a few things that can go wrong:
- Error parsing the theme JSON
- VSCode's API isn't working correctly
- the theme doesn't correctly identify itself as a dark theme

Can you please post:

1) your developer's tools console log
2) what version of VSCode and which operating system you are running
3) what theme you are using and any relevant settings for it.

**Comment by JarnoRFB** [comment]
I am on Ubuntu 18.10. Interestingly, I found out that that it works (the font turns white) when I am in normal VSCode and the problem only occurs when I am in a devcontainer. 
The theme I am using is simply `Dark (Visual Studio)`.
Here is a repo that hopefully reproduces the issue https://github.com/JarnoRFB/paper-template.

**Comment by jlelong** [comment]
Closed by #1571.
