### ISSUE TITLE
Features that should be moved to LaTeX Utiliities

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1558]
A continuation of the discussion in #1478

So far
 - Word Count moved out
 - Formatted Paste moving out

**Comment by tecosaur** [comment]
I'm thinking `View TikZPicture` is probably better off there as well. Thoughts?

**Comment by James-Yu** [comment]
I agree. I had taken a look into that but found it a bit complex. May you do the migration?

**Comment by tecosaur** [comment]
I'll take a look :smiley:

**Comment by tecosaur** [comment]
Just had a think about the Snippet Panel. Even though it may go beyond the minimum of what someone needs to get started, I think it's worth having in the base extension. New users who are also new-ish to LaTeX I imagine would very much appreciate it, but may have no desire for the other 'extra' features in LU.

**Comment by tecosaur** [comment]
Another thought. I imagine this was going to happen anyway, but following semantic versioning, I think the next release should be `v8.0.0` since the 'big feature split' constitutes as "breaking changes" in my mind.

**Comment by James-Yu** [comment]
At the very beginning semantic versioning is used. But soon after that it falls back to the old school `major_feature.minor_feature.bug_fix` style. This is because that all in all LW is not a library/package of some programming language, and every commit includes some breaking changes.

Yet I agree that this is a major feature/change and we should have the major version increased.

**Comment by tecosaur** [comment]
I've had another feature idea, and would appreciate some input on whether this is best suited to LW or LU.

Using `texdef -s` it is possible to get where commands are defined.
```bash
$ texdef -s -t latex -c article section
```
```
% article.cls, line 302:
\newcommand\section{\@startsection {section}{1}{\z@}%
                                   {-3.5ex \@plus -1ex \@minus -.2ex}%
                                   {2.3ex \@plus.2ex}%
                                   {\normalfont\Large\bfseries}}
```
```bash
$ texdef -s -t latex -c article itemize
```
```
% latex.ltx, line 4856:
\def\itemize{%
  \ifnum \@itemdepth >\thr@@\@toodeep\else
    \advance\@itemdepth\@ne
    \edef\@itemitem{labelitem\romannumeral\the\@itemdepth}%
    \expandafter
    \list
      \csname\@itemitem\endcsname
      {\def\makelabel##1{\hss\llap{##1}}}%
  \fi}
```

I'm thinking this can be used to make a `DefinitionProvider` or `DocumentLinkProvider`.

**Comment by tamuratak** [comment]
@tecosaur  off topic. Please open a new issue.

**Comment by tamuratak** [comment]
How about Compilation Info Panel? It confuses users by appearing in the status bar even when it does not work properly. It is not matured.

**Comment by tecosaur** [comment]
Perhaps. One issue would be that that panel is fairly integrated with `builder.ts`, specifically the logging parts. One approach might be to leave the log-processing stuff but send the result of that off to LU, or rather have an event handler that LU can attach to.

Regarding the issue with functionality, for me this works as of `7.3.0`.

**Comment by tecosaur** [comment]
I feel like this conversation has stilted. Until someone has more to discuss, this may as well be closed.
