### ISSUE TITLE
Suggestion: Allow user to set default PDF viewer options

### ISSUE THREAD

**Issue by luismsgomes** [James-Yu/LaTeX-Workshop#156]
It would be really nice if we could set a preference for the default PDF Zoom and "Enable hand tool".

BTW, thank you for this great extension.

**Comment by James-Yu** [comment]
Thanks for the suggestion. Let me think of a proper way to implement it.

**Comment by James-Yu** [comment]
Implemented and will be released shortly in version `2.5.0`.

**Comment by luismsgomes** [comment]
Nice! Thanks.
