### ISSUE TITLE
Table assistant

### ISSUE THREAD

**Issue by Griger** [James-Yu/LaTeX-Workshop#1567]
It could be interesting if this extension provides a table generator or an assistant. For example, in AUCTex the editor writes the necessary & according to the number of columns. There is an [extension](https://marketplace.visualstudio.com/items?itemName=Lw-lonely.latex-table-helper) that does that for VCCode, but it could be better to have this integrated into this awesome extension. Thanks a lot for your contribution to VSCode.

**Comment by tecosaur** [comment]
For making tables, at the moment you can paste tables from a spreadsheet program or import csv files to tabular environments. This is currently a feature of this extension, but as of the next release, you will be able to find in in the companion extension, LaTeX Utilities. See: https://github.com/tecosaur/LaTeX-Utilities/blob/master/CHANGELOG.md.

Does this provide the functionality that you are looking for?

**Comment by James-Yu** [comment]
I would agree with @tecosaur. If @Griger think a plain text -> table transform is cool, please create an issue in https://github.com/tecosaur/LaTeX-Utilities which will hold all non-core LaTeX features.

**Comment by tecosaur** [comment]
For feature requests like this in the future, perhaps it may be worth creating a `latex-utilities` label or similar?

**Comment by tecosaur** [comment]
That was quick!
