### ISSUE TITLE
Using texdef command for DefinitionProvider

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1568]
This was in #1558 but as tamuratak requested it's now it's own issue.

I've had another feature idea, and would appreciate some input on whether this is best suited to LW or LU.

Using `texdef -s` it is possible to get where commands are defined.
```bash
$ texdef -s -t latex -c article section
```
```
% article.cls, line 302:
\newcommand\section{\@startsection {section}{1}{\z@}%
                                   {-3.5ex \@plus -1ex \@minus -.2ex}%
                                   {2.3ex \@plus.2ex}%
                                   {\normalfont\Large\bfseries}}
```
```bash
$ texdef -s -t latex -c article itemize
```
```
% latex.ltx, line 4856:
\def\itemize{%
  \ifnum \@itemdepth >\thr@@\@toodeep\else
    \advance\@itemdepth\@ne
    \edef\@itemitem{labelitem\romannumeral\the\@itemdepth}%
    \expandafter
    \list
      \csname\@itemitem\endcsname
      {\def\makelabel##1{\hss\llap{##1}}}%
  \fi}
```

I'm thinking this can be used to make a `DefinitionProvider`.

**Comment by James-Yu** [comment]
I would say this one as well as `texdoc` should be both in LU. Will do `texdoc` soon.

**Comment by tecosaur** [comment]
Thanks for the input. Would you like me to continue creating individual issues for things like this, or tak them onto the end of #1558?

**Comment by tecosaur** [comment]
For this to work we probably also want to expose `this.extension.completer.command.usedPackages` (for use in `texdef` args)

**Comment by tecosaur** [comment]
Done. Just need to create a PR.
