### ISSUE TITLE
Split bar does not follow cursor when dragging

### ISSUE THREAD

**Issue by Crexyer** [James-Yu/LaTeX-Workshop#1573]
I split my window into two parts to view pdf. When dragging split bar from left to right, the window does not follow my cursor. It seems that I can drag split bar again if cursor is in the outside of pdf viewer. Is it a bug of LaTeX Workshop or VS Code?

Desktop:
 - OS: Windows 10 x64
 - VS Code version: 1.36.1
 - Extension version: 7.3.0

![screenshot](https://user-images.githubusercontent.com/5073771/62416776-76139580-b673-11e9-9342-03607e5fd960.gif)

**Comment by tamuratak** [comment]
Already reported microsoft/vscode/issues/76866
