### ISSUE TITLE
Repeated files in Mac OS X Catalina

### ISSUE THREAD

**Issue by guanghaoch** [James-Yu/LaTeX-Workshop#1575]
Every time I compile the tex files, it replaced the existed auxiliary files in local drive, but created many copies in iCloud Drive. I submitted a bug report to Apple but they said the files were created and then deleted within a short period of time (due to the delete aux files after compile function), and the file ID were not the same. iCloud treated them as different files with the same name. Is there anything you could do to fix it? Thank you.

**Comment by tamuratak** [comment]
You can disable deleting auxiliary files after build. See [link](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#cleaning-generated-files).
