### ISSUE TITLE
PDF tab preview shows white space for .pdf figures

### ISSUE THREAD

**Issue by rubendsa** [James-Yu/LaTeX-Workshop#1577]
**Describe the bug [Required]**
PDF preview shows white space for .pdf figures. When viewing the successfully built output pdf in an external view, the figure shows up correctly. 

**Screenshots**
This is what I see in the tab preview: http://prntscr.com/ooavd2
This is what I see in the external preview (this one is correct) http://prntscr.com/ooavmv

**To Reproduce**
Paste this code in to a blank document and save this .pdf in the same directory [slice2.pdf](https://github.com/James-Yu/LaTeX-Workshop/files/3465399/slice2.pdf)

\documentclass[12pt]{article}
\usepackage{lingmacros}
\usepackage{tree-dvips}
\usepackage{graphicx}

\begin{document}

\begin{figure}[h]
    \begin{center}
    \includegraphics[height=1in]{slice2.pdf}
    \caption{\textit{Locations of the neutral point ($X_{NP}$) and center of gravity ($X_{CG})$ of an individual wing segment. }} 
    \label{fig:test2}
    \end{center}
\end{figure}

\end{document}

**Expected behavior**
Should see the slice2.pdf figure in the preview but all that is seen is white space (see screenshots.)
**Logs [Required]**

16:40:37] Parsing /Dropbox/Apps/Overleaf/test.tex
[16:40:37] Parsing /Dropbox/Apps/Overleaf/test.fls to compute dependencies
[16:40:37] File watcher: responding to change in /Dropbox/Apps/Overleaf/test.tex
[16:40:37] /Dropbox/Apps/Overleaf/test.tex changed. Auto build project.
[16:40:37] BUILD command invoked.
[16:40:37] Building root file: /Dropbox/Apps/Overleaf/test.tex
[16:40:37] Build root file /Dropbox/Apps/Overleaf/test.tex
[16:40:37] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Dropbox/Apps/Overleaf/,/Dropbox/Apps/Overleaf/test
[16:40:37] LaTeX build process spawned. PID: 2917.
[16:40:37] Recipe of length 1 finished. PID: 2917.
[16:40:37] Successfully built /Dropbox/Apps/Overleaf/test.tex.
[16:40:38] ACTIONS command invoked.
[16:40:39] ACTIONS command invoked.
[16:40:39] ACTIONS command invoked.
[16:40:39] ACTIONS command invoked.
[16:40:44] LOG command invoked.
[16:40:44] LOG command invoked.
[16:40:59] LOG command invoked.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Latexmk: All targets (/Dropbox/Apps/Overleaf/test.pdf) are up-to-date
</details>

**Desktop [Required]:**
 - OS: OSX 10.13.6
 - VS Code version: 1.36.1
 - Extension version: 7.3.0

**Are you using LaTeX Workshop with VS Code Remote?**
No

**Comment by tamuratak** [comment]
The file, https://file.io/mDqAlX, is 404 Not Found. Please upload it again. Uploading to github is reliable. Would you like to upload the generated pdf file, `test.pdf`, too?

Please tell us how you created `slice2.pdf`? What software did you use? Inkspace or Adobe Illustrator?

**Comment by rubendsa** [comment]
Just updated the original post with a working link to slice2.pdf. The image was made using affinity design which is very similar in caliber to adobe illustrator.

**Comment by tamuratak** [comment]
I can reproduce this problem. I guess it is related to pdf.js. A workaround I can find is using xelatex. Using latex+dvipdfm also works.

**Comment by rubendsa** [comment]
Gotcha, thanks for looking into this! How would I setup either of those two workarounds?

**Comment by tamuratak** [comment]
Replace `-pdf` with `-pdfxe` in `latexmk`.  This is my using recipe.

```
    "latex-workshop.latex.recipes": [
        {
            "name": "platex",
            "tools": [
                "platex",
                "dvipdfmx"
            ]
        },
        {
            "name": "bibtex",
            "tools": [
                "bibtex"
            ]
        },
        {
            "name": "latex",
            "tools": [
                "latex",
                "dvipdfmx"
            ]
        },
        {
            "name": "lualatex",
            "tools": [
                "lualatex"
            ]
        },
        {
            "name": "pdflatex",
            "tools": [
                "pdflatex"
            ]
        },
        {
            "name": "uplatex",
            "tools": [
                "uplatex",
                "dvipdfmx"
            ]
        },
        {
            "name": "xelatex",
            "tools": [
                "xelatex"
            ]
        },
        {
            "name": "latexmk",
            "tools": [
                "latexmk"
            ]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latex",
            "command": "latex",
            "args": [
                "-synctex=1",
                "-halt-on-error",
                "%DOC%"
            ]
        },
        {
            "name": "lualatex",
            "command": "lualatex",
            "args": [
                "-synctex=1",
                "-halt-on-error",
                "%DOC%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-halt-on-error",
                "%DOC%"
            ]
        },
        {
            "name": "platex",
            "command": "platex",
            "args": [
                "-synctex=1",
                "-halt-on-error",
                "%DOC%"
            ]
        },
        {
            "name": "uplatex",
            "command": "uplatex",
            "args": [
                "-synctex=1",
                "-halt-on-error",
                "%DOC%"
            ]
        },
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-halt-on-error",
                "%DOC%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        },
        {
            "name": "dvipdfmx",
            "command": "dvipdfmx",
            "args": [
                "%DOCFILE%.dvi"
            ]
        },
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
              "-synctex=1",
              "-interaction=nonstopmode",
              "-file-line-error",
              "-pdfxe",
              "-outdir=%OUTDIR%",
              "%DOC%"
            ],
            "env": {

            }
        }
    ],
```

**Comment by rubendsa** [comment]
Got it, thanks! I can confirm on my end that using xelatex works, although it does breaking my formatting when used in my other documents. Although that has to do with xelatex and not this particular bug.

**Comment by tamuratak** [comment]
Reported mozilla/pdf.js/issues/11045.

**Comment by jlelong** [comment]
This issue has been fixed in `pdf.js`
