### ISSUE TITLE
Unable to copy the text in the 'PDF on-the-fly' window

### ISSUE THREAD

**Issue by tczhangzhi** [James-Yu/LaTeX-Workshop#1579]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
Unable to copy the text in the 'PDF on-the-fly' window.

**To Reproduce**
1. Select the text I want to copy
2. Press command + c
3. Press command + v in editor

**Expected behavior**
Able to copy the selected text in the 'PDF on-the-fly' window, which is open in vs code.

**Logs [Required]**
The logs are unrelated.

**Desktop [Required]:**
 - OS: macOS 10.14.5
 - VS Code version: 1.36.1
 - Extension version: 7.3.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by tamuratak** [comment]
This is the bug of VS Code. See microsoft/vscode/issues/65452. We can do nothing on our side.

**Comment by Wongboo** [comment]
https://github.com/microsoft/vscode/issues/65452#issuecomment-614237050
Looks like `vscode` side are pointing out that this is problem for extension? and the problem still exists.

**Comment by tamuratak** [comment]
We don't add tweaks on our side due to the maintenance burden.
