### ISSUE TITLE
Success message barely visible when using Solarized Light theme

### ISSUE THREAD

**Issue by kc1212** [James-Yu/LaTeX-Workshop#158]
![screenshot from 2017-06-02 15-08-49](https://cloud.githubusercontent.com/assets/1093806/26727224/3f72a7ac-47a6-11e7-9f93-33bc9dc2f03e.png)

Hi, I think white on yellow is barely visible. I don't know about vscode internals, is it not possible to use font colours that come with the theme?

**Comment by James-Yu** [comment]
It seems not possible to read the active color theme from extensions in this version of vscode. However, it seems the team is working on that: https://github.com/Microsoft/vscode/issues/26974

**Comment by James-Yu** [comment]
With today's 1.13 update it is possible to reference  theme colors. I will work on this issue soon.

**Comment by James-Yu** [comment]
![image](https://user-images.githubusercontent.com/4210342/27017733-34a3d134-4f5d-11e7-9d15-e4aef4663537.png)

It is working lovely! Will release when other things are ready.
