### ISSUE TITLE
Feature Request: TOC Viewer

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#159]
It would be great to be able to have some form of table of contents viewer (or even just navigation via the TOC).

**Comment by brunnerh** [comment]
VSCode might not have the infrastructure for this, but it could be done via the symbols feature which is currently not used by the extension. Certainly second this request in any case.

(Using the symbols this might be semantically abusive though, as it could also be used for extracting `\newcommand` instances and the like, which would be a nice feature in itself as it would enable functions like "go to definition".)

**Comment by James-Yu** [comment]
I would propose a rough idea of alternative solution. What about we have a dropdown list showing all references in `\label{}`. When selecting any of them, vscode jump to its position. Another command can jump back to where the cursor was originally. Will that be useful?

**Comment by jsinglet** [comment]
that's a good idea; I think the traditional way to do it is to parse the aux files though, no?

**Comment by jsinglet** [comment]
what about providing a new view?

https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews

**Comment by jsinglet** [comment]
Here, I started hacking on this, it might look like the attached screenshot. If you would accept this as a PR I can finish it fairly quickly. 

<img width="475" alt="screen shot 2017-06-12 at 12 48 34 am" src="https://user-images.githubusercontent.com/1062841/27019737-004396a8-4f09-11e7-87cd-6cc6bd2747e7.png">

**Comment by James-Yu** [comment]
Awww that's awesome! I never noticed there is an `outline` section or related APIs. A great lesson to me 😆

**Comment by jsinglet** [comment]
Any thoughts on this? Would looooooove to get my hands on this ;)

**Comment by James-Yu** [comment]
Yes it's a really neat feature, any helping hand is greatly appreciated!

**Comment by jsinglet** [comment]
@James-Yu Here you go! https://github.com/James-Yu/LaTeX-Workshop/pull/175

**Comment by James-Yu** [comment]
Thanks! Will check soon!
