### ISSUE TITLE
Allow "PDF Preview" tab in new windows

### ISSUE THREAD

**Issue by SaswatPadhi** [James-Yu/LaTeX-Workshop#1590]
**Is your feature request related to a problem? Please describe.**
Currently, when I try to move (by dragging) the PDF preview tab to a new VS Code window, it simply fails silently. I am not sure if this is a bug, but I can move other tabs (e.g. other files) to other VS Code windows and that works as expected.

**Describe the solution you'd like**
Having the PDF preview tab open in a new window is very useful for multi-monitor setups and it would be nice if this extension could support it.

**Comment by tamuratak** [comment]
Please use `view in web browser`. We can not implement `PDF preview tab` in a new VS Code window because of the restriction of VS Code API.
