### ISSUE TITLE
MathJax error

### ISSUE THREAD

**Issue by InkLaTeX** [James-Yu/LaTeX-Workshop#1592]
This is when I'm popping a mathjax preview.
<img width="213" alt="无标题 (2)" src="https://user-images.githubusercontent.com/51014035/62765633-17ab4480-bac3-11e9-9a1f-70b48fa7ba75.png">
I think this bug is important to be fixed.

这是我正在弹出mathjax预览的时候的样子。

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Please show us the preamble of your TeX file if you do not mind.

Thank you for your cooperation.

**Comment by InkLaTeX** [comment]
Actually when I updated the VSCODE, this has never happened again.Thank you for your advice anyways.
