### ISSUE TITLE
Store generated build files in separate directory and rename output pdf

### ISSUE THREAD

**Issue by DFelten** [James-Yu/LaTeX-Workshop#16]
An option would be great to store the generated build files like main.aux, main.out, main.toc and so on in a separate directory. All files generated during a build should be redirected to this folder.

This could be possible with this compile_argument: 
`"-synctex=1 -interaction=nonstopmode -file-line-error -jobname \"Output/Output filename\""`

But the problem is now that bibtex is looking for a file with the name main:

> Step 1: pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -jobname "Output/Output filename" "main"
> Step 2: bibtex "main"
> Error: Command failed: bibtex "main"
>  `bibtex "main"` (exited with error code 1)

This atom plugin is able to do it: https://atom.io/packages/latex

**Comment by James-Yu** [comment]
Can you please try `latexmk` with `-auxdir` or `-outdir` parameter? Both should fit your need. [ref](http://tex.stackexchange.com/questions/7716/putting-aux-log-out-toc-bbl-bib-blg-files-in-another-directory-with-latexmk).

**Comment by DFelten** [comment]
Thanks for the answer,  but it seems there are various problems with my template and latexmk. For example all the png images doesn't work (Also not with defining the natwidth). With pdflatex everything works fine (instead of the directory for the output files). 

What would be the correct settings? Maybe you can help me with it. My settings didn't work properly, all the files are generated in the main folder:

```
"latex-workshop.compiler": "latexmk",
"latex-workshop.compile_argument": "-auxdir=Output -outdir=Output -interaction=nonstopmode -pdf main"
```

**Comment by James-Yu** [comment]
My test project with both png and pdf figures works flawless with `-synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=out/` as argument.

**Comment by James-Yu** [comment]
Beside your settings, you also need to set a proper `latex-workshop.compile_workflow`. For `latexmk`, `[%compiler% %arguments% %document%]` is enough.

**Comment by DFelten** [comment]
Thanks again for the fast answer, with these settings it seems to work now:

```
{
    "latex-workshop.compiler": "latexmk",
    "latex-workshop.main_document": "/main.tex",
    "latex-workshop.compile_argument": "-synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=Output -jobname=\"My Document\"",
    "latex-workshop.compile_workflow": [
        "%compiler% %arguments% %document%"
    ]
}
```

But now there is a problem with the pdf preview. As you can see I changed the output file name with the jobname command and the preview tool is searching in the wrong directory for the wrong file:

> PDF.js Version 1.6.414 (build: 3b3a179)
> Nachricht: Missing PDF "file:/// (...) /MainDirectory/main.pdf".

The output file is now located in Output/My Document.pdf.

**Comment by James-Yu** [comment]
Now it can only preview PDF file of the same name with Tex. I'm yet to come up with a better way to intelligently find the proper file to preview.

**Comment by James-Yu** [comment]
A workaround is to add a `cp` command to the tool chain, making it something like `[latexmk, could]`.

**Comment by DFelten** [comment]
Then I will use this workaround. It's working with 

```
compile_workflow": [
    "%compiler% %arguments% %document%",
    "copy \"Output\\My Document.pdf\" main.pdf"
],
```

I now it's an other suggestion, but I think creating an own issue is too much for it. With the new minimap of Visual Studio Code Insiders (`"editor.minimap.enabled": true`) there is unnecessary free space on the right of the preview.

![image](https://cloud.githubusercontent.com/assets/1169185/23359196/669657c2-fce5-11e6-8e29-0846b7c9eeb6.png)

Or should I create a separate issue for it?

**Comment by James-Yu** [comment]
Insider version is not officially supported. Though I will look into this issue.

**Comment by DFelten** [comment]
Yes that is what I thought.

Only for info: The workaround unfortunately does not work with "Find Here in Preview".
