### ISSUE TITLE
Feature Request: Autocomplete third-party packages and classes

### ISSUE THREAD

**Issue by xuebinsu** [James-Yu/LaTeX-Workshop#160]
Awesome extension! This is the only tool that supports fuzzy autocomplete of commands, environments and labels (Please correct me if I am wrong). I think it would be even better if it could support TexStudio-style third-party autocomplete (perhaps by .cwl files).

**Comment by James-Yu** [comment]
This feature requires a huge amount of manpower to finish as latex has a million way to define commands. It seems not quite possible at the current stage of development. IIRC there were similar issues previously submitted in this repo. You may refer to them for detailed discussions.

**Comment by xuebinsu** [comment]
Is it possible to reuse the code base of TeXStudio or other LaTeX development tools?

**Comment by James-Yu** [comment]
No it isn't. TexStudio seems not to be open sourced. CMIIW

**Comment by xuebinsu** [comment]
TeXStudio is open-souced on SourceForge
<https://sourceforge.net/p/texstudio/hg/ci/default/tree/>

2017-06-07 8:12 GMT+08:00 James Yu <notifications@github.com>:

**Comment by James-Yu** [comment]
Will check out later
