### ISSUE TITLE
A little bug in the TikZ snippet panel

### ISSUE THREAD

**Issue by joulev** [James-Yu/LaTeX-Workshop#1600]
When using the snippet panel in the Ti*k*Z part, I notice that `\node` is not understood correctly by VSCode.

For example, with the snippet
```latex
\node (X) at (3,5) {}
```
I expect
```latex
\node[options] (id) at position {label};
```
but it gives
```latex
 
ode[options] (id) at position {label};
```

I don't know much about Javascript, but as far as I know, maybe you should write `\\node` instead of `\node` somewhere in the code, because `\n` is the new line character. I think that is also the reason why there is a new blank line.

In the "Symbol" part of the snippet panel, `\n` is working fine, for example, `\nu` doesn't have any problem.

* **OS:** Windows 10
* **LaTeX Workshop version:** 7.3.0
* **VS Code version:** 1.37.0

**Comment by tecosaur** [comment]
Ooops. Looks like I missed a few things. I'm rather swamped at the moment, but this weekend I'll get that all working as it should have been.

One the topic of the snippet panel though (sicne you seem to be using it), I'd be interested to know if you have any general feedback.

**Comment by joulev** [comment]
Some of my suggestions for the symbol panel:

1. The font size of the symbols are not consistent. Look at the size of the `I` and the `H` in the following screenshot, for example.
    ![a](https://i.stack.imgur.com/SvhbS.png)
2. I think it should be organized like in the Ti*k*Z panel. It is already organized, but I have to change the "All" box to e.g. "Delimiters". So, I think something like this
    ```
    - Greek letters
       \alpha \beta \gamma etc.
    - Delimiters
       | \vert \| \Vert etc.
    - etc.
    ```
    is better than this
    ```
    \alpha \beta \gamma etc. \daleth \gimel | \vert \| \Vert etc.
    ```
    We don't have to change the box to see in what category are these symbols in.
3. If the symbols are organized, I think we can get rid of the search box. At least, it is not really useful to me. When I find `\ell`, all what I have in mind is something like the letter `l`. But when I type `l` to the search box, I get many results, and the one I need is only a little character in some last rows.
4. Some commands require `amsmath`, some require `amsfonts`, etc. If possible, we should have a checker, so that whenever the user uses `\mathbb` without `amsfonts` for example, that user will receive a warning.

Some suggestions for the Ti*k*Z panel (other than the main part of this bug report):

1. Probably minor, but it is TikZ, not Tikz (I know you can fix this in one single commit :))
2. Most LaTeX users use a `typewriter` (`monospace`) font, so I think all the commands should be displayed in a typewriter font.
3. Other than normal paths, many users (at least as I know on TeX StackExchange) use the `to` path, in three main ways:
    ```latex
    \path (coordinate) to[out=angle, in=angle] (coordinate);
    \path (coordinate) to[bend left=angle] (coordinate);
    \path (coordinate) to[bend right=angle] (coordinate);
    ```
    IMHO these usages should be included as well.
4. `grid` path and `parabola` path are necessary.
    ```latex
    \path (coordinate) grid[options] (coordinate);
    \path (coordinate) parabola[options] (coordinate);
    ```
5. `plot` path is very necessary. I do not put this to the fourth point because `plot` is in a different level.
    ```latex
    \path[options] plot[options] (expression for x, expression for y);
    \path[thick] plot[smooth, samples=100, domain=0:4] (\x, \x*\x/4); % example
    ```
6. In path options, color options and `help lines` should be included.
7. If it can be more advanced, I suggest some `pgfmath` commands
    ```latex
    \pgfmathsetmacro{\command}{expression}
    \pgfmathsetmacro{\sum}{\x+\y} % assign value of \x+\y to \sum
    %
    \pgfmathtruncatemacro{\command}{expression}
    \pgfmathtruncatemacro{\sum}{\x+\y} % assign rounded value of \x+\y to \sum
    ```
8. (if this is in your scope) A `BEN`, `BIT`-like snippet for `tikzpicture` environment (and `pspicture` environment too).

**Comment by tecosaur** [comment]
Haven't forgotten about this, just got busy :disappointed:

**Comment by tecosaur** [comment]
Now on it. :smiley: 

### Part 1

1. Font size
  They _should_ all be the same font size. I don't know why those letters are funny like that
2. Another way of showing groups.
  That's a decent idea. I'll have a think
3. Bad search
  I've gone with a very broad search method. For example `asymp` returns `\omega \Theta \Omega \sim \asymp \mathcal{O} ` because they are used in notation for asymptotic complexity.
4. Required packages.
  Good idea. TODO

### Part 2

1. Done
2. Tried that, issue was how much horizontal space it took up
3. Done
4. Done
5. TODO
6. Any specific suggestions?
7. TODO
8. TODO

**Comment by joulev** [comment]
About point 2.6: This is the current Ti*k*Z panel:

![image](https://user-images.githubusercontent.com/44609036/65824701-4fe72c00-e297-11e9-9630-ba989679f976.png)

Maybe an additional column for color options would be nice. Only some minimal colors will suffice. Like

```
🟥 red
🟨 yellow
🟩 green
🟦 blue
...
```
