### ISSUE TITLE
Task: migrate fs to vscode.workspace.fs

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1601]
It may be worth migrating our use of the `fs` Node.js library to the new `vscode.workspace.fs` api (see vscode v1.37 release notes).
This would be good for compatibility with remote workspaces etc. but isn't particularly pressing.

**Comment by tamuratak** [comment]
Even without `vscode.workspace.fs`, LaTeX Workshop can work with VS Code Remote. There is no reason to use the api at present.

I think the explanation by VS Code team is not accurate and misleading. See microsoft/vscode-docs/issues/3059.

I want to think about this again when specific requests come out of users.

**Comment by tecosaur** [comment]
Huh. That's a surprise. Fair enough then.
