### ISSUE TITLE
Configure shell escape output directory

### ISSUE THREAD

**Issue by janosh** [James-Yu/LaTeX-Workshop#1602]
I have a bunch of [standalone files](https://ctan.org/pkg/standalone?lang=en) which require shell escape to build. Following [the guidance here](https://github.com/James-Yu/LaTeX-Workshop/issues/913), I added the option `-shell-escape` to `pdflatex`. However, my custom output directory

```json
  "latex-workshop.latex.outDir": "%DIR%/.tmp",
```
does not appear to extend to shell escape mode. I tried to manually set the output directory as shown below but without success.

```json
  "latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "-outdir=%OUTDIR%",
        "-pdflatex=pdflatex -shell-escape -aux-directory=%OUTDIR% -output-directory=%OUTDIR% %S",
        "%DOC%"
      ]
    },
  ]
```
How can I get the output of standalone files to end up in `latex-workshop.latex.outDir`?

**Comment by jlelong** [comment]
I think you are missing some quotes. Try this.

```
"latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "-outdir=%OUTDIR%",
        "-pdflatex=\"pdflatex --shell-escape %O %S\"",
        "%DOC%"
      ]
    },
  ]
```

If it does not work, you can also have a look at #1043.

**Comment by janosh** [comment]
With those extra quotes, my builds crash immediately:

> Running '"pdflatex -shell-escape  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory=...
> No such file or directory
> Latexmk: fls file doesn't appear to have been made.

**Comment by janosh** [comment]
Also, the docs don't use any quotes [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk) (item 2: Directly specify `-shell-escape` in the compiler flag).

**Comment by jlelong** [comment]
Using item 2 works straightaway for me. Have you tried it? What are your logs with this recipe?

**Comment by janosh** [comment]
Item 2 compiles for me as well, it's just that the output of standalone files, specifically the generated PDF and auxiliary files, don't end up in the specified output directory but in the same folder as the standalone file itself.

Are assume you referring to the logs from the LaTeX compiler? This is (some) of what I get:

```
Latexmk: This is Latexmk, John Collins, 17 March 2019, version: 4.63b.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -shell-escape  -synctex=1 -interaction=nonstopmode -file-line-error
-recorder -output-directory="~/Thesis/.tmp"  "~/Thesis/Thesis.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
```

**Comment by jlelong** [comment]
This is because of `~`, which is not interpreted as `$HOME`. Use a full path instead.

**Comment by janosh** [comment]
An, sorry for the confusion, I abbreviated the full path with `~` myself after pasting the log here to reduce clutter. But it's actually an absolute path.

**Comment by jlelong** [comment]
With a full path, it works for me.

**Comment by janosh** [comment]
With "work", do you mean the output of standalone files ends up in 
```json
  "latex-workshop.latex.outDir": "%DIR%/.tmp",
```

**Comment by jlelong** [comment]
Yes!

**Comment by janosh** [comment]
Odd. Is your standalone file in a subdirectory? As in `mainfile.tex` and `assets/standalone.tex`?

**Comment by jlelong** [comment]
Please post a MWE along with your configuration to see if we can reproduce the issue otherwise we may both waste our time not speaking the same language.

**Comment by janosh** [comment]
Will do (a little later).

**Comment by tamuratak** [comment]
Feel free to reopen if any progress.
