### ISSUE TITLE
latex-workshop.latex.outDir does not work xelatex

### ISSUE THREAD

**Issue by niklasolai** [James-Yu/LaTeX-Workshop#1603]
This setting `"latex-workshop.latex.outDir": "%DIR%/.tmp"` does not work with `% !TEX TS-program = xelatex` but does work with pdflatex. Any ideas?

**Comment by jlelong** [comment]
Have a look at the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#tex-programm-and-options) to know how to pass options to a magic command. You need to specify `--output-directory=% OUTDIR%`. Alternatively, you can define a `xelatex` recipe.

**Comment by niklasolai** [comment]
@jlelong Thanks! This worked!
```
    "latex-workshop.latex.outDir": "%DIR%/.tmp",
    "latex-workshop.latex.magic.args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "--output-directory=%OUTDIR%",
        "%DOC%"
      ],
```
