### ISSUE TITLE
Multi file parser refactoring and too frequent parsing?

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1606]
This is a follow-up to [https://github.com/James-Yu/LaTeX-Workshop/pull/1554#discussion_r310401557](https://github.com/James-Yu/LaTeX-Workshop/pull/1554)

> A long time ago, we had two handlers as you describe: one for changes inside vscode and one for external change. Then, we only kept the external one, which actually watches when a file changes on disk and therefore responds when a file is saved inside vscode. I am wondering if you really need to keep both. If I remember well, `onDidChangeTextDocument` is called after every keystroke or so.

With the new multi file parser, the function [`parseFileAndSubs`](https://github.com/James-Yu/LaTeX-Workshop/blob/899081b3c36873a1ae48029ff826657e66d96cc5/src/components/manager.ts#L301) is called after every keystroke to reparse the `.bib` and input files. I am not convinced we should do it every time the document changes. What about delegating this to the file watcher? 

Of course, this very frequent parsing may not impact performances but it is not very green computing and it creates tons of log entries (which are needed for debugging).

**Comment by James-Yu** [comment]
I should have it removed from `onFileChanged`, but apparently I did not 😢 Will do very soon.
