### ISSUE TITLE
Feature Request: Auto-closing math environment delimiters and quote marks

### ISSUE THREAD

**Issue by xuebinsu** [James-Yu/LaTeX-Workshop#161]
It seems that LW does not support auto-closing math delimiters, e.g., $ $ and \\[ \\], and quote marks `` ''. Would it be better if it does like parens, brackets and braces?

**Comment by James-Yu** [comment]
Sorry but full description is required. What's missing and what's expected?

**Comment by xuebinsu** [comment]
Updated.

**Comment by James-Yu** [comment]
I get it. This issue is somehow in conflict with #13 . Let me see if there are things I can do without violating the previous fix.

**Comment by James-Yu** [comment]
I added auto pairing for $$ and `' . Unfortunately multi-char pairing like \[ and \] does not work with vscode. I also intentionally left out '' pairing, reason issued in #13.
