### ISSUE TITLE
Autocompletion brackets not working anymore (8.x.x)

### ISSUE THREAD

**Issue by jakobsudau** [James-Yu/LaTeX-Workshop#1610]
**Describe the bug**
Starting with version 8.0.0, when autocompleting a command such as `\footnote`, the corresponding brackets are not added anymore

**To Reproduce**
1. Make sure to use version 8.0.0 to 8.0.3 of this plugin
2. in any .tex document, use autocompletion to complete a command that should be followed by brackets (such as `\footnote`, `\url` or `\cite`

**Expected behavior**
The command should be autocompleted with corresponding brackets (e.g. from `\footn` -> autocomplete -> `\footnote{}`).

**Desktop:**
 - OS: macOS Mojave 10.14.6
 - VS Code version: 1.37.1
 - Extension version: 8.0.3

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by oarodriguez** [comment]
I am having the same problems as @jakobsudau after updating to v8.0.3. In my case there is no command suggestions nor autocompletion at all. I am using  LaTeX Workshop with VS Code Remote WSL. 

![imagen](https://user-images.githubusercontent.com/1988576/63308869-1eec0280-c2ba-11e9-8f2b-c43572ee1c5f.png)

I had to reinstall v7.3.0 to continue with my work.

![imagen](https://user-images.githubusercontent.com/1988576/63309112-295acc00-c2bb-11e9-9de3-25aed9e228ea.png)

**Comment by James-Yu** [comment]
Please provide a minimal working example for testing. I cannot reproduce the problem (tested `\footnote` and `\begin`).

**Comment by temnyles** [comment]
I have the same issue. No more autocompletion from 8.0.0 version. I am using Windows VS Code and my LaTeX distribution is installed in WSL.

Here are my settings for LaTeX Workshop:

  `"latex-workshop.view.pdf.viewer": "tab",
  "latex-workshop.chktex.enabled": true,
	"latex-workshop.chktex.path": "wsl",
	"latex-workshop.chktex.args.active": [
    "chktex",
		"-wall",
		"-n22",
		"-n30",
		"-e16",
		"-q"
	],
	"latex-workshop.chktex.args.root": [
		"chktex",
		"-wall",
		"-n22",
		"-n30",
		"-e16",
		"-q"
	],
    "latex-workshop.latex.autoBuild.run": "onFileChange",
    "latex-workshop.latex.autoClean.run": "never",
    "latex-workshop.latex.recipe.default": "first",
    "latex-workshop.latexindent.path": "wsl",
	  "latex-workshop.latexindent.args": [
		"latexindent",
		"-c",
		"%DIR%/",
		"%TMPFILE%",
		"-y=\"defaultIndent: '%INDENT%'\""
    ],
    "latex-workshop.synctex.path": "synctex",
	  "latex-workshop.texcount.path": "wsl",
	  "latex-workshop.texcount.args": ["texcount"],

    "latex-workshop.latex.recipes": [{
        "name": "wsl",
        "tools": [
          "wsl"
        ]
      }
    ],
      "latex-workshop.latex.tools": [{
          "name": "wsl",
          "command": "wsl",
          "args": [
              "latexmk",
              "--shell-escape",
              "-synctex=1",
              "-interaction=nonstopmode",
              "-pdf",
              "main.tex"
          ]
      },
      {
        "name": "pdflatex",
        "command": "wsl",
        "args": [
          "pdflatex",
          "-interaction=nonstopmode",
          "--shell-escape",
          "%DOCFILE%"
    ]}],
    "latex-workshop.intellisense.package.enabled": true,
    "latex-workshop.intellisense.unimathsymbols.enabled": true,
    "latex-workshop.intellisense.package.extra": [
      "true"
    ],
    "latex-utilities.liveReformat.enabled": true,`

**Comment by James-Yu** [comment]
Minimal working example please.

**Comment by James-Yu** [comment]
Also, apparently you are using `wsl`. See the last line of OP's post.

**Comment by jakobsudau** [comment]
Issue resolved for me in 8.0.4 - don't know exactly why (didn't change anything on my machine), but now autocompletion with brackets works as expected.

Sorry for the fuss!
