### ISSUE TITLE
Synctex stops working 

### ISSUE THREAD

**Issue by Saphrosit** [James-Yu/LaTeX-Workshop#1615]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
I am experiencing some problems with synctex. Namely, if I open the PDF with VScode viewer, after few seconds of inactivity I am not able to jump from PDF to source file by cmd+click. If I close the preview and reopen it then it works, but again only for few seconds, then it stops again. 
The issue was not present in version 7.3.0.

**To Reproduce**
Open a new file (write something, say a lipsum or whatever) and generate a PDF, then try to use synctex to jump to line in the source file. 
I was not able to identify exactly what causes the problem. Sometimes synctex stops after few seconds of inactivity, sometimes after a second typeset.

**Logs [Required]**
Not sure what logs may be needed.

**Desktop [Required]:**
 - OS: MacOS 10.14.5

 - VS Code version: 
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

 - Extension version: [e.g. 5.0.0]
8.0.3
**Are you using LaTeX Workshop with VS Code Remote?**
No

**Comment by coxackie** [comment]
The issue also happens with me, on Linux (Arch), extension version 8.0.3.

**Comment by bayesthm** [comment]
Same issue here, on Windows 10, extension version 8.0.3.

**Comment by tamuratak** [comment]
Please show us log messages. Paste the whole of them.

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by carstenhag** [comment]
Well, I was *just* about to report this :D

For me, it broke when saving/building. It's fixed now, thanks.
