### ISSUE TITLE
Syntax highlighting issues

### ISSUE THREAD

**Issue by iliyang** [James-Yu/LaTeX-Workshop#162]
I'm just trying out LaTeX Workshop, coming from Sublime Text + LaTeXTools. I noticed that the out-of-the-box syntax highlighting is not as good as what I have in Sublime Text.

Any idea why come macros (the macros in macro definitions) are not highlighted? Also package names?

(Sublime on the left, VS Code on the right)
![image](https://user-images.githubusercontent.com/802594/26956721-d37071ee-4cb7-11e7-94b8-4859e3393485.png)

**Comment by James-Yu** [comment]
It seems your vscode theme is not working well. This is mine:
![image](https://user-images.githubusercontent.com/4210342/26956798-1deb948e-4cf3-11e7-9057-efdf79535f12.png)

**Comment by iliyang** [comment]
Thanks! Indeed, the theme was the problem.
