### ISSUE TITLE
Place \begin in front of \begingroup when typing "begin" and latexlmx issue

### ISSUE THREAD

**Issue by WildSkywalker** [James-Yu/LaTeX-Workshop#1620]
Here are two issues I found recently. I have searched the existing issues and did not find anything alike. If these have been answered, my apologies. (Also, I basically.. do pure math, which means I can be quite bumbling around this site. )

**Update: Just check the wiki and found I can just type "BAL" and all problems are solved. My bad. I am really sorry.**
~~After a recent update, I found out that when typing the starting words of begin, the syntax \begingroup will appear before \begin. Not only I believe the order should be the other way around, but it actually creates a non-negligible problem. As a person writing mostly mathematics, I (and I believe a lot of other people) use countless \begin{align}\end{align} in our documents. Needing to pressing the down arrow every time we are trying to type a formula adds a lot more hassle than I think. I was wondering if we can have \begin in front of \begingroup on the candidate list while typing "begin".~~

The second issue is little hard to trace. I use my web browser (chrome) to view the pdf file. If I press the latexlmk recipe, sometimes the new document will not stay at the original position but from the beginning after building, making the editing a long paper more difficult. I cannot 100% reproduce this case but it is more likely to happen after a lot of inputs. (For ex, if I add a lot of paragraphs, this issue is much more likely to happen than the case if I only change some letters in a formula).

Thanks in advance for your help.

**Comment by jlelong** [comment]
The ordering of intellisense proposals is internally computed by vscode and we cannot really tweak it. Note that if you set `"editor.suggestSelection": "recentlyUsedByPrefix"` and you complete `\beg` to `\begin` once, it will be the first suggestion for any further completion.

**Comment by jlelong** [comment]
I am closing this issue and I invite you to create a new one for the web browser synctex problem.
