### ISSUE TITLE
auto-completion of equation environment \[  \] not working properly 

### ISSUE THREAD

**Issue by coxackie** [James-Yu/LaTeX-Workshop#1624]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
In previous versions, (7.x), upon typing `\[` and the space (or tab) a closing equation `\]` would appear. As of version 8.04 only `]` instead of `\]` appears.

**To Reproduce**
Type `\[`, and then space or tab. Just `]` will appear. 

**Expected behavior**
after typing `\[`, and then space or tab, `\]` should appear. 

**Desktop [Required]:**
 - OS: Linux (Arch)
 - VS Code version: 1.37.1
 - Extension version: 8.0.4

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by ShuCaiMonkaS** [comment]
This is probably duplicated with #1621.

**Comment by ShuCaiMonkaS** [comment]
> only "]" instead of "]" appears.

Your description seems weird. Do you mean bracket pair auto-completion or environment `\[ \]` auto-completion?

**Comment by coxackie** [comment]
@ShuCaiMonkaS apologies for not having been precise. I mean the equation environment statement. I have now edited the issue.
