### ISSUE TITLE
Eslint complains about `no-async-promise-executor` in `providers\hover.ts`

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#1628]
This issue won't follow the template as it is a dev-related one. The issue is as follows on `master`:
```bash
$ eslint --fix --cache --ext .ts,.js .

Some\Path\LaTeX-Workshop\src\providers\hover.ts
  47:29  error  Promise executor functions should not be async  no-async-promise-executor

✖ 1 problem (1 error, 0 warnings)
```
while the source looks like
```javascript
this.getColor()
        return new Promise( async (resolve, _reject) => {
            const configuration = vscode.workspace.getConfiguration('latex-workshop')
```
and there is an
```javascript
await this.findNewCommand(document.getText())
```
in the block, which calls
```javascript
await this.extension.manager.findRoot()
```

@tamuratak have any idea how to resolve this error?

**Comment by tamuratak** [comment]
Please do not use different versions of eslint from the one in `package.json`.

**Comment by James-Yu** [comment]
Is there a reason why eslint 6 is not preferred? `no-async-promise-executor` is also enabled in `eslint:recommended`.

**Comment by tamuratak** [comment]
It is essential that all the devs use the same version of a linter. Otherwise, the linter cannot do its job. If you want to use eslint 6, you should update `package.json`. Are you saying that you want to update it?

**Comment by James-Yu** [comment]
I would prefer working on the recommended eslint version and config, except when we have special reasons against that. That is why I was asking.

**Comment by tamuratak** [comment]
Until very recently, `typescript-eslint` did not support `eslint 6`. See typescript-eslint/typescript-eslint/pull/645. That's the reason. I am not sure the current maturity.

**Comment by James-Yu** [comment]
I see. Will keep an eye on eslint 6. My environment has global eslint 6 but local eslint 5, that's why I can commit but got errors in command line.
