### ISSUE TITLE
Add nav and snm files produced by beamer to cleanup list

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#1635]
**Is your feature request related to a problem? Please describe.**

Beamer produces some additional auxiliary files that are not correctly cleaned up by LaTeX Workshop. It's cumbersome having to delete them by hand, specially in projects with many files.

**Describe the solution you'd like**

Simply add `*.nav` and `*.snm` by default to `"latex-workshop.latex.clean.fileTypes"` so the user doesn't have to copy the entire list in order to add these two entries.

**Describe alternatives you've considered**

Extending `"latex-workshop.latex.clean.fileTypes"` by hand, which involves copy pasting of many entries and won't be updated if new default entries are added upstream in the future.

**Additional context**

I do a lot of beamer work and I noticed that LaTeX Workshop is a bit less polished for beamer projects than for standard LaTeX documents, so I'm reporting the rough edges I every now and then find.

**Comment by James-Yu** [comment]
We typically don't change the default config values.

**Comment by memeplex** [comment]
Sorry, I'm not sure I understand your rationale here, these two files are routinely produced by beamer, they're clearly ancillary files, beamer is *very* popular as to demand core support and, from this perspective, it looks like an oversight not having them in the cleanup list, the same than it looked like an oversight not having beamer frames in the outline. In these conditions, why wouldn't you change a configuration value? It honestly surprises me.

**Comment by James-Yu** [comment]
Because you can always add these entries to your config. That is the use of a config, otherwise jist hard code it. 

Everyone thinks his way and work flow of using LaTeX is the standard. In many cases it is not.

**Comment by memeplex** [comment]
In general I agree with that but in this case I'm putting forward reasons why in beamer world these two extensions are to be treated at the same level than everything else already in the cleanup list: they are ancilliary files always  produced  while compiling beamer. And I believe you would agree that asking for beamer to get first-class support is not to egotistically wanting to support my fancy workflow that sometimes produce a couple of weird files nobody else cares about. I will look for documentation about these two files supporting my point later, though.

**Comment by jlelong** [comment]
I think @memeplex is right to suggest adding `.snm` and `.nav` extensions to `"latex-workshop.latex.clean.fileTypes"`. These are auxiliary files related to beamer navigation and are treated as such by LaTeX editors as AUCTeX, TeXnicCenter. I will take care of this. 

@James-Yu I do understand your point and we can definitely not satisfy all feature requests but this time I think this is reasonable.
