### ISSUE TITLE
Add option to close document in Adobe Reader before compilation (or prevent compilation when output file is not writable)

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#1639]
**Is your feature request related to a problem? Please describe.**
I use auto-compile on save, and often I proof-read the compiled document in Adobe Reader. Saving any change to the tex file then triggers compilation, which fails with "I can't write on file \jobname.pdf". That wouldn't be too bad of a problem, but that error usually triggers a complete rebuild (involving some 4-5 iterations of pdflatex) of the whole document.

**Describe the solution you'd like**
I'd like a solution where the file is closed in Adobe Reader, compiled, and then reopened after compilation - ideally at the same scroll position. TeXstudio allows doing that through DDE commands.

**Describe alternatives you've considered**
Alternatively, LaTeX workshop could make sure that the output file is writable before starting compilation; if it is not, there is no point in starting a compilation process. (The longer I think about this, the more this is my preferred option. Also, I believe this is much more easy to implement.)

**Additional context**
n/a

**Comment by James-Yu** [comment]
Thanks for the suggestion. It is not practical to implement pdf-reader-closing actions as there are too many kinds of such readers. Yet checking whether the file is writable is a good improvement.

**Comment by James-Yu** [comment]
Note that this check does not work due to limits on `fs` of node. We cannot fix that.
