### ISSUE TITLE
"View PDF in new tab" and "View PDF in web page" no longer works

### ISSUE THREAD

**Issue by netheril96** [James-Yu/LaTeX-Workshop#164]
After the latest update to VSCode, these two commands no longer work. Building and other commands like viewing logs still work. No error messages are displayed anywhere.

**Comment by James-Yu** [comment]
![image](https://user-images.githubusercontent.com/4210342/27018053-f42a7b5a-4f5f-11e7-8b5d-746dcf185322.png)
Mine is working correctly. I would suggest re-installing the extension and see if it works, if there is no error message in latex-workshop log.

As always, attaching the log (no matter if there is anything suspicious) would potentially help. Though in this case I have no idea on what might go wrong.
