### ISSUE TITLE
Can we put inline math on top of the suggestion list?

### ISSUE THREAD

**Issue by tylerliu1998** [James-Yu/LaTeX-Workshop#1642]
After updating to above 7.1.0, the most frequently used 'inline math' does not appear on top of the suggestion list any more, which is extremely annoying for those who types math formula all day.

![bad](https://user-images.githubusercontent.com/48684632/63703089-454bf980-c7f6-11e9-9934-13b38e394467.jpg)

**Comment by jlelong** [comment]
The ordering of intellisense proposals is internally computed by vscode and we cannot really tweak it. Note that if you set `"editor.suggestSelection": "recentlyUsedByPrefix"` and you complete `\(` to `\()` once, it will be the first suggestion for any further completion.
