### ISSUE TITLE
Longer progress bar than intended when compiling

### ISSUE THREAD

**Issue by Hanziness** [James-Yu/LaTeX-Workshop#1644]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: **Yes**

**Describe the bug [Required]**
When I have a specific project structure (MWE below), the compilation progress bar can be made longer than it was (probably) intended to be. When using `\include` to create a document from multiple "subdocuments" and `\includeonly` to only include one of the files (the rest have `.aux` files), the extension might display something like "Page 48/6" in the VS Code status bar when building the document (the only included file is 6 pages long, but due to `\includeonly` the page numbering will start at 43, resulting in the extension thinking that it is already processing pages 43-48!).

Please note that the exact issue is that the progress bar in the status bar "overflows", as it can easily display >100% build progress, potentially even filling the whole bottom bar of VS Code (see screenshots for a small demonstration).

I use this setup to write a longer document and I make use of `\includeonly` to reduce compilation times (omitting parts I'm not working on at the moment).

**To Reproduce**
Here's an MWE to help reproduce the issue.

<details>
<summary>main.tex (root document)</summary>

```latex
\documentclass{report}

\usepackage{lipsum}

% \includeonly{2}

\begin{document}

\include{1}
\include{2}

\end{document}
```

</details>

<details>
<summary>1.tex (and 2.tex, looks the same)</summary>

```latex
% !TeX root = main.tex

\lipsum[1-4]
\pagebreak
\lipsum[1-4]
```

Feel free to make these (especially `1.tex` (a lot) longer). Make sure to have at least two files (hence `1.tex` and `2.tex`).
</details>

Steps:
1. Compile without `\includeonly` - the progress bar will go from 0/4 to 4/4 (as expected)
2. Uncomment the `\includeonly` line, enabling inclusion of only `2.tex`
3. Save & compile - the progress bar will go from `0/2` to `4/2` (**200%**, twice the size of the original progress bar). Please note that you may have to compile twice in step 3 to achieve this, but every subsequent compilation with the `\includeonly` command enabled will produce the same effect!

**Expected behavior**
The bottom progress indicator shouldn't go beyond 100% (not in the label, nor in the displayed progress bar). I'd expect to see `2/2` when finishing the compilation in the case of the MWE, or alternatively (`3/4` and `4/4`), but the graphical progress bar should only go from 0% to 100%.

**Logs [Required]**
I don't believe that logs might help with this, but here we go. This is a simple `pdflatex` compilation.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

```
[20:29:42] Parsing g:\Dokumentumok\tmp\main.tex
[20:29:42] File watcher: responding to change in g:\Dokumentumok\tmp\main.tex
[20:29:42] g:\Dokumentumok\tmp\main.tex changed. Auto build project.
[20:29:42] BUILD command invoked.
[20:29:42] Building root file: g:\Dokumentumok\tmp\main.tex
[20:29:42] Build root file g:\Dokumentumok\tmp\main.tex
[20:29:42] Recipe step 1: pdflatex, --max-print-line=10000,-synctex=1,-interaction=nonstopmode,-file-line-error,-shell-escape,g:/Dokumentumok/tmp/main
[20:29:42] LaTeX build process spawned. PID: 5372.
[20:29:43] LaTeX log parsed with 0 messages.
[20:29:43] Recipe of length 1 finished. PID: 5372.
[20:29:43] Successfully built g:\Dokumentumok\tmp\main.tex.
[20:29:43] Refresh PDF viewer for g:\Dokumentumok\tmp\main.pdf
[20:29:43] Handle data type: position
[20:29:43] Preview PDF file: g:\Dokumentumok\tmp\main.pdf
[20:29:43] Handle data type: loaded
[20:29:43] SyncTex after build invoked.
[20:29:43] Try to synctex g:\Dokumentumok\tmp\main.pdf
[20:32:45] LOG command invoked.
```

</details>

<details>
<summary>Developer Tools Console [Required]</summary>
Found no errors or anything suspicious related to LaTeX Workshop.
</details>

**Screenshots**
At the start of the compilation:
![Compilation 0/2](https://user-images.githubusercontent.com/18259108/63714277-c4b2ea80-c841-11e9-9fc7-60ce47c85336.png)
At the end of the compilation (notice how the progress bar is longer than it is on the first screenshot):
![Compilation 4/2](https://user-images.githubusercontent.com/18259108/63714312-d3010680-c841-11e9-9765-d03972126655.png)

**Desktop [Required]:**
 - OS: Windows 10 1903 (x64)
 - VS Code version: 1.37.1
 - Extension version: 8.0.7
 - MiKTeX

**Are you using LaTeX Workshop with VS Code Remote?**

**No**

**Additional context**
Nothing else there to add.

**Comment by tecosaur** [comment]
Thanks for the bug report. I've managed to reproduce this, I just need to get around to fixing it. ETA this weekend / next week unless anyone else feels inclined to do something sooner.

**Comment by tecosaur** [comment]
Sorry, lots (loootts) of stuff has been cropping up for me :disappointed: I haven't got a spare moment this weekend, but next weekend is looking good (_I swear_).

**Comment by Hanziness** [comment]
No problem, since this is mostly just a visual glitch, I wouldn't consider it to be top priority issue to fix right away :) Thanks for informing me/us!
