### ISSUE TITLE
In TeX, \end is highlighted, \begin not

### ISSUE THREAD

**Issue by autinerd** [James-Yu/LaTeX-Workshop#1648]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
When using the language TeX, \begin is not syntactically highlighted, but \end

**To Reproduce**

Put this into a document and select the language 'TeX'
```latex
\begin{}
\end{}
```

**Expected behavior**
Both are highlighted

**Desktop [Required]:**
 - OS: all
 - VS Code version: 1.37
 - Extension version: 8.0.*

**Comment by autinerd** [comment]
@trevorgunn It's also when something is between the braces.
```latex
\begin{test}
\end{test}
```
has the same behaviour.
And it belongs to TeX, not LaTeX

**Comment by autinerd** [comment]
Oh, I forgot to look in the plist files, then I have had seen it myself! Maybe it's possible to address this issue without breaking the other...

**Comment by jlelong** [comment]
If I understand correctly, you would like to have `\begin{test}` and `\end{test}` pairs highlighted in TeX mode as in LaTeX mode. I am a bit surprised by your demand as I think environments only exist in LaTeX not in TeX. Can you explain us why you want to use the TeX mode.

**Comment by autinerd** [comment]
The other option would be to unhighlight both. I recognized it because I created a beamer theme and there you have LaTeX code in the files. You are right, that this is not TeX code. I was just confused that the \begin is not highlighted, but the \end.

**Comment by jlelong** [comment]
Ok I get it. The solution is to have `\begin` and `\end` highlighted as any other commands in TeX mode. I will have a look at it.

**Comment by autinerd** [comment]
It doesn't matter for me, if they are highlighted or not, I was just confused, that `\begin` and `\end` are treated differently.

**Comment by jlelong** [comment]
It seems that part of the fix introduced in 9198094 is not needed anymore.
