### ISSUE TITLE
Red-colored text \right

### ISSUE THREAD

**Issue by jerryc05** [James-Yu/LaTeX-Workshop#1649]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
`\right` command is marked in RED, like an error. However, it does not affect functionality.

**To Reproduce**
1. Type `\left(\right)`
2. See red-colored text `\right`

**Expected behavior**
Shall be yellow-colored like `\left`

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.
`N/A`

<details>
<summary>LaTeX Workshop Output [Required]</summary>

N/A
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

N/A
</details>

**Screenshots**
![](https://i.ibb.co/1bfD21j/Screenshot-20190827151420.png)

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.38.0
 - Extension version: 8.0.7

**Are you using LaTeX Workshop with VS Code Remote?**

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Additional context**

**Comment by jlelong** [comment]
I bet you are using Bracket Pair Colorizer 2. See #1641 and the referenced issues therein.

**Comment by jlelong** [comment]
Unfortunately no, because of my comment in #1534.
