### ISSUE TITLE
Syntax highlighting: Support more \.*?inline variants

### ISSUE THREAD

**Issue by fehnomenal** [James-Yu/LaTeX-Workshop#165]
At the moment only the `\lstinline` macro is specially treated ([here](https://github.com/James-Yu/LaTeX-Workshop/blob/2f048eb877db235fd5b9f9203df51da7d5860319/syntax/LaTeX.plist#L1120) and [here](https://github.com/James-Yu/LaTeX-Workshop/blob/2f048eb877db235fd5b9f9203df51da7d5860319/syntax/LaTeX.plist#L1201)) with the regex `((\\)(?:verb|lstinline)[\*]?)\s*((?&lt;=\s)\S|[^a-zA-Z])(.*?)(\3|$)`.
Now there is the [`minted`](https://github.com/gpoore/minted) package that supports `\mintinline` as well as custom versions (like `\textinline`, `\htmlinline`, ...).
Of course these macros are not recognized by the regex but that would be super nice.

Right now I fixed this locally very dirty by replacing `lstinline` in the regex above with `(?:\w+?)inline`. It works for all variants that I have registered, but of course it might clash with other macros.

**Comment by James-Yu** [comment]
I have no personal experience so I can't say if it is a good idea to incorporate a package-specific command into the general syntax highlighting plan. Though I'm neither against it. Any ideas from OP and other LaTeXers?
