### ISSUE TITLE
Not able to open latex warnings, filename has square bracket suffix like [5]

### ISSUE THREAD

**Issue by carstenhag** [James-Yu/LaTeX-Workshop#1654]
**I think this was fixed in 8.1.0, but I'm not sure.**

----

**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

Did not try.

**Describe the bug [Required]**
The problem tab shows latex errors (and as I have the code spell extension on, unknown words). 

When clicking on some latex errors, it opens up the file. On some other amount of latex errors, like overfull hbox, the tex file is not opened. See the screenshot.

**To Reproduce**
1. Build a latex project with overfull hbox or other errors (not sure)
2. Open the problems tab
3. On a file that vs code renders as "filename [digit]", click on a warning
4. Error message pops up.

**Expected behavior**
The filename shouldn't have a weird suffix that breaks the warning from showing up.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
[12:52:48] Found root file by magic comment: /Users/chag0709/git/mobile-consumer-apps/Bachelorarbeit/ba-carsten/Bachelorarbeit-Carsten-Hagemann.tex
[12:52:48] Root file remains unchanged from: /Users/chag0709/git/mobile-consumer-apps/Bachelorarbeit/ba-carsten/Bachelorarbeit-Carsten-Hagemann.tex.

That's the only thing that shows up when clicking on entries that don't open.
</details>

**Screenshots**
![Bildschirmfoto 2019-08-29 um 12 45 04](https://user-images.githubusercontent.com/3776997/63934241-2d28e400-ca5b-11e9-829b-6c7cf85071ba.png)

**Desktop [Required]:**
 - OS: macOS 10.14.5
 - VS Code version:  1.37.1
 - Extension version: 8.0.7

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by carstenhag** [comment]
I'll close this, as I tried 8.1.0 for a minute and it works fine now. I'll reopen if it happens again.

**Comment by trevorgunn** [comment]
Yes, this was fixed in #1652 which was included into 8.1.0.

**Comment by carstenhag** [comment]
Ah lovely, thanks!
