### ISSUE TITLE
Option to Configure Auto Build

### ISSUE THREAD

**Issue by benjaminBrownlee** [James-Yu/LaTeX-Workshop#1658]
I'm not sure if this feature exists, but after twiddling with vscode and reading through the documentation I have not been able to achieve what I'm seeking.

Anyways, I want to be able to configure the auto build to describe how it runs rather than simply whether it runs or not. Right now the auto build always fails since I don't make use of `bibtext` (at least, that's what I am presuming). I would like the option to pass my own latex build recipe to the auto build option. In my case, I want to simply want run `pdflatex` on the saved file and then issue the `Refresh all viewers` command.

I'm not sure how this would be implemented into this extension (or even if it already is somehow), but I guess the most intuitive solution would be to have an auto build option that takes a number of items that can be either bash commands or vscode commands, which will all run in order when a tex file is saved if auto build is enabled.

**Comment by trevorgunn** [comment]
The recipe called by the build-on-save feature is either the first recipe in the recipe list (default) or the last recipe you build with. This is configurable through the [latex-workshop.latex.recipe.default](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexrecipedefault) option.

The default recipe is `latexmk` which by default should act just like `pdflatex` (in fact all it does if you don't have `bibtex` is call `pdflatex`). You can try changing the first recipe to `pdflatex`.

Probably what you want to do is try running `latexmk` from the command line and seeing what errors show up. It could be you don't have `latexmk` properly installed (I think this is more likely than something to do with `bibtex`).

> I guess the most intuitive solution would be to have an auto build option that takes a number of items that can be either bash commands or vscode commands, which will all run in order when a tex file is saved if auto build is enabled.

This is exactly what the recipe system does. Each recipe is a list of tools in which order to run them and each tool is a program name and what arguments to supply.

**Comment by jlelong** [comment]
See the [wiki on LaTeX recipes](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes).
