### ISSUE TITLE
Not all autocomplete citation suggestions listed

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#1661]
**Describe the bug [Required]**
After the extension became version 8, I am not getting all autcomplete suggestions for citation commands. For instance, prior to version 8, for `\autocite` I used to get among several options the specific one `\autocite[postnote]{key}`. (This option was available --- see [this](https://github.com/James-Yu/LaTeX-Workshop/issues/1033) and [this](https://github.com/James-Yu/LaTeX-Workshop/issues/1523) issues.)

But as you can see in the below screenshot, this option is not listed anymore.

![citation-1](https://user-images.githubusercontent.com/24664855/64015348-fb3e7d00-cb41-11e9-8ffb-286a89a42726.png)

The same format one is missing for `\textcite` too. 

![citation-2](https://user-images.githubusercontent.com/24664855/64015457-39d43780-cb42-11e9-8fcc-993192102506.png)

**Desktop [Required]:**
 - OS: Linux KDE Manjaro
 - VS Code version: 1.37.1
 - Extension version: 8.1

**Comment by werunom** [comment]
Tried the latest release `8.1.1`. I am still not getting the complete list of suggestions :(

**Comment by tamuratak** [comment]
@James-Yu `out/src/providers/completer/command.js` in v8.1.1 has not been updated. It is out-of date.
