### ISSUE TITLE
Equation reference completion via current equation number

### ISSUE THREAD

**Issue by a-torgovitsky** [James-Yu/LaTeX-Workshop#1666]
**Is your feature request related to a problem? Please describe.**
I am trying to convert to VS code from Vim.
In Vim, I used the [vimtex plugin](https://github.com/lervag/vimtex).
One nice feature of that plugin was that when trying to complete an `\eqref{`, the fuzzy search is done not only by label, but also by the number of the equation in the current compilation.
For example, typing `3<tab>` would fill in the label for the equation currently numbered as (3).

**Describe the solution you'd like**
Tab completion for `\eqref{` to include equation numbers in its search.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tecosaur** [comment]
I'm afraid nobody seems particularly keen to pick this up — do you care about this enough to make a PR?

**Comment by a-torgovitsky** [comment]
No, I don't, so I'll close it.
