### ISSUE TITLE
Constant math preview

### ISSUE THREAD

**Issue by newmrdenis** [James-Yu/LaTeX-Workshop#1667]
It would be great if you add some kind of setting key for that function. I don't know what options could be there I need only one that would turn on constant math preview when I am in math environment.

Thanks for your great work!

**Comment by tamuratak** [comment]
It is not possible because of the restriction of VS Code API. While an API enabling this feature is being proposed, I am not sure when the API is available in the release version of VS Code. Related to #1427.
