### ISSUE TITLE
Consider making a new (ActivityBar) icon with sans serif font

### ISSUE THREAD

**Issue by yzhang-gh** [James-Yu/LaTeX-Workshop#1669]
### Is your feature request related to a problem? Please describe.

As VSCode redesigned its icon set with outline style, the TeX icon looks a little inconsistent.

![image](https://user-images.githubusercontent.com/7588612/64221054-1ae8f300-cefe-11e9-8c84-b81a61c40117.png)

### Describe the solution you'd like

A potential solution is to use a sans serif font

![image](https://user-images.githubusercontent.com/7588612/64221987-491c0200-cf01-11e9-91d9-b690715dc484.png)

```latex
\TeX%

{\sffamily \TeX}
```

### Describe alternatives you've considered

Of course, someone can make a new icon with a different sans serif font, as the `\TeX` command is not aimed to produce a real icon.

### Additional context

Modern icons/logos usually use sans serif fonts as they are "clean" and easy-to-read.

![image](https://user-images.githubusercontent.com/7588612/64222602-46221100-cf03-11e9-9e9a-fc88d5bc6ba1.png)
<sub>source: wikipedia<sub>

**Comment by trevorgunn** [comment]
Or maybe like this:

![drawing svg](https://user-images.githubusercontent.com/7917549/64354493-8cdc3d80-cfcd-11e9-9990-2bba39f7c1fd.png)

**Comment by tecosaur** [comment]
Personally, I think a sans-serif logo works best. It's completely unambiguous. However, if we do use a wireframe of the extension icon personally I'd go for something more like this
![image](https://user-images.githubusercontent.com/20903656/64405222-ff721980-d0b0-11e9-8e02-533d77dffc45.png)
(svg can be found at https://github.com/tecosaur/LaTeX-Utilities/blob/master/demo-media/icon-wirefrane-minimal.svg)

**Comment by James-Yu** [comment]
I personally like the one by @tecosaur more. How do others think?

**Comment by yzhang-gh** [comment]
Looks good to me. (I am still interested in how the sans serif TeX icon will look like. Have no idea how to convert it to an SVG icon 😅)

**Comment by trevorgunn** [comment]
Just keep in mind that the icon will be quite small when displayed. So fine details like the gap between the two tips should be simplified. Also the line needs to be thicker to match the other icons. I believe those icons are about 24 px wide and the lines are about 1.5 px thick.

That looks something like this:

![sample](https://user-images.githubusercontent.com/7917549/64456543-6f3ad100-d0be-11e9-80c9-e33b93bbdfa5.png)

Larger:

![sample-big](https://user-images.githubusercontent.com/7917549/64456744-f5571780-d0be-11e9-8806-cbf644a19bf4.png)

**Comment by trevorgunn** [comment]
@James-Yu I have been thinking for a while that the `\TeX` icon should be replaced by the nib (pen tip) icon. I also think that this icon should have a minimal number of lines (mostly because it will be displayed very small). I think joining the two tips together is better at that size.

**Comment by coxackie** [comment]
Can I just play the devil's advocate here by asking: _does the pen tip icon associate more than the TeX icon itself with a specialised LaTeX extension such as this one_? It mostly screams "editor", but this is what vs code is for the most part...

**Comment by James-Yu** [comment]
I sorta agree with @coxackie about editor vs TeX. Any idea on how to resolve this?

btw, it seems that all other icons have round corners. So the above pen tip icon may also need to have it changed. Tho it should be a small work.

**Comment by tecosaur** [comment]
Personally I'd still just use a sans serif TeX logo, but if you _really_ want to use the pen I'd be happy to make it curvey.

**Comment by James-Yu** [comment]
I forgot about the tex symbol. Will include in next release

**Comment by tecosaur** [comment]
@James-Yu I don't think you did…

**Comment by jlelong** [comment]
I am not sure it has been included in `8.3.0`. Has it?

**Comment by tecosaur** [comment]
It hasn't.

**Comment by James-Yu** [comment]
Any one can make an icon for me? I tried my inkscape but it won't work.

**Comment by trevorgunn** [comment]
@James-Yu 

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="38.465pt" height="22.549pt" version="1.1" viewBox="-72 -72 38.465 22.549" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<metadata>
<rdf:RDF>
<cc:Work rdf:about="">
<dc:format>image/svg+xml</dc:format>
<dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>
<dc:title/>
</cc:Work>
</rdf:RDF>
</metadata>
<style type="text/css"><![CDATA[
text.f0 {font-family:cmss17;font-size:24.787053px}
]]></style>
<g fill="#fff">
<g fill="#fff" aria-label="TEX">
<path d="m-63.994-54.787h-2.2308v-15.74h-5.5275v-1.9582h13.261v1.9582h-5.5027z"/>
<path d="m-47.713-49.451h-9.89v-17.698h9.89v1.9582h-7.6592v5.5275h7.213v1.9334h-7.213v6.3207h7.6592z"/>
<path d="m-34.589-54.787h-2.5283l-4.6848-7.684-4.7591 7.684h-2.3548l5.8745-9.2208-5.5027-8.4772h2.4787l4.3377 6.9404 4.3625-6.9404h2.3548l-5.4779 8.4276z"/>
</g>
</g>
</svg>
```

I made this in latex using `dvisvgm` to convert to svg. Then I used inkscape to convert the text to paths (to avoid issues with fonts). Then I used https://www.svgminify.com/ to clean up all the extra stuff.

**Comment by James-Yu** [comment]
In `v8.3.1`!
