### ISSUE TITLE
Keyboard shortcuts for VScode tab PDF preview

### ISSUE THREAD

**Issue by badralbanna** [James-Yu/LaTeX-Workshop#1670]
**Is your feature request related to a problem? Please describe.**
I often use beamer to create slides. I'd like to be able to easily skip to the next page to see that animations are working, ~~but currently, I can't find any shortcuts that work (even if I select the tab). I seem to remember this working before, but it doesn't seem to now.~~ _Sorry! I just figured out that p, n work. That said it would be nice if I could use shortcuts even when the window is not selected._

**Describe the solution you'd like**
It would be great to have keyboard shortcuts to skip forward/backward a page in the inline Vscode tab PDF viewer. Even better, it would be great if those shortcuts worked even when the TEX file is selected so it wouldn't be necessary to switch tabs. 

Thank you for all your hard work! This is an amazing extension and one of the plugins I use most so I really appreciate it!

**Comment by jlelong** [comment]
From the wiki

> The PDF viewer provided with the extension internally uses pdf.js. The keybindings support by pdf.js are documented [here](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts).

I am afraid we cannot really do much because of vscode API limitations.

**Comment by badralbanna** [comment]
Ah OK. Thank you!
