### ISSUE TITLE
The \setminus snippet is suggested when entering a line break (\\)

### ISSUE THREAD

**Issue by scimas** [James-Yu/LaTeX-Workshop#1671]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
The snippet for inserting `\setminus` pops up as soon as you enter `\\` (for line break). And it gets inserted as soon as your press enter. So you have to hit escape to avoid it every time you want to enter a line break.

**To Reproduce**
1. Create a bare minimum latex file.
2. Type `\\` and observe the described behaviour.

**Expected behavior**
I haven't been using this extension for long, so what I'm describing as bug could be intended.

I would expect the extension to not suggest any snippet at all when typing a line break. In fact it was working that way until yesterday. Today vscode updated to 1.38.0, so something might have broken because of that.

**Logs [Required]**
I'm copying the log here from a fresh run, which shows the same behaviour. But I don't think they are relevant to this issue. The `tmp.tex` file is the minimal file I created for my own testing.
<details>
<summary>LaTeX Workshop Output [Required]</summary>

<pre>
[11:08:47] Initializing LaTeX Workshop.
[11:08:47] Creating LaTeX Workshop http and websocket server.
[11:08:47] LaTeX Workshop initialized.
[11:08:47] Found root file from active editor: /path/to/tmp.tex
[11:08:47] Root file changed from: undefined to /path/to/tmp.tex. Find all dependencies.
[11:08:47] Instantiating a new file watcher for /path/to/tmp.tex
[11:08:47] Creating file watcher for .bib files.
[11:08:47] Parsing /path/to/tmp.tex
[11:08:47] Server created on 127.0.0.1:43587
[11:08:47] Adding /path/to/tmp.tex to file watcher.
[11:08:47] Snippet data loaded.
[11:08:47] LaTeX Workshop version: 8.1.0
</pre>
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

There is nothing in the console other than a line saying that the debugger is listening on port 61939.
</details>

**Screenshots**
![Screenshot from 2019-09-05 11-21-17](https://user-images.githubusercontent.com/16473290/64355529-64554300-cfcf-11e9-8249-a679ad729059.png)

**Desktop [Required]:**
 - OS: Ubuntu 19.04
 - VS Code version: 1.38.0
 - Extension version: 8.1.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**

**Comment by jlelong** [comment]
It works with vscode 1.37. I believe this is an issue in vscode itself or a change in the API. I need to figure out how to report it. @tamuratak Any idea of how to reproduce this outside LW?

**Comment by tamuratak** [comment]
I will look into it.
