### ISSUE TITLE
Build command invoked

### ISSUE THREAD

**Issue by maxcordivani** [James-Yu/LaTeX-Workshop#1673]
**Describe the bug [Required]**

does not generate any files. after the build request remains in: 
"BUILD command invoked."

**Screenshots**

![Schermata 2019-09-06 alle 16 18 37](https://user-images.githubusercontent.com/26182750/64435877-8c25d300-d0c3-11e9-934f-2b39930b0f47.png)

**Desktop [Required]:**
 - OS: Ubuntu 18.04.3
 - VS Code version: 1.34

***Developer Tools Console [Required]**
yarn run v1.17.3
$ theia start --plugins=local-dir:../../plugins
root INFO Theia app listening on http://localhost:3000.
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler { unpackedFolder: '/tmp/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'James-Yu.latex-workshop-8.1.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      '/home/massimo/theia/plugins/James-Yu.latex-workshop-8.1.0.vsix',
     initPath:
      '/home/massimo/theia/plugins/James-Yu.latex-workshop-8.1.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/James-Yu.latex-workshop-8.1.0.vsix
root INFO Resolved "James-Yu.latex-workshop-8.1.0.vsix" to a VS Code extension "latex-workshop@8.1.0" with engines: { vscode: '^1.34.0' }
root INFO Deploying backend plugin "latex-workshop@8.1.0" from "/tmp/vscode-unpacked/James-Yu.latex-workshop-8.1.0.vsix/extension/out/src/main.js"
root INFO Detected keyboard layout from pressed keys: Portuguese (PC)
root WARN Collided keybinding is ignored;  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}  collided with  {"command":"terminal:new","keybinding":"ctrl+shift+`"}
root WARN Could not register keybinding:
  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}
Error: "ctrl+`" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 135 ms
root WARN EditorNavigationContribution.onStart is slow, took: 458 ms
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 39585] Started watching: /root/.theia
root INFO [hosted-plugin: 39600] PLUGIN_HOST(39600) starting instance
root ERROR Unrecognized key 'oem_minus' in 'ctrl+oem_minus'
root WARN Shadowing keybinding is ignored; {"command":"core.toggleMaximized","keybinding":"ctrl+m"}, shadows {"command":"latex-workshop.shortcut.mathbf","keybinding":"ctrl+m ctrl+b"}
root WARN Collided keybinding is ignored;  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}  collided with  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}
root WARN Could not register keybinding:
  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}
Error: "enter" is in collision with something else [scope:1]
root INFO [hosted-plugin: 39600] PLUGIN_HOST(39600): PluginManagerExtImpl/init()
PLUGIN_HOST(39600): initializing(latex-workshop@8.1.0 with /home/massimo/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO Detected keyboard layout from pressed keys: Portuguese (PC)
root WARN Collided keybinding is ignored;  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}  collided with  {"command":"terminal:new","keybinding":"ctrl+shift+`"}
root WARN Could not register keybinding:
  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}
Error: "ctrl+`" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 129 ms
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 39621] Started watching: /root/.theia
root INFO [nsfw-watcher: 39621] Started watching: /home/massimo/theia
root WARN EditorNavigationContribution.onStart is slow, took: 1505 ms
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
terminal ERROR Couldn't attach - can't find terminal with id: 0 
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
terminal ERROR Error attaching to terminal id 0, the terminal is most likely gone. Starting up a new terminal instead.
root INFO [hosted-plugin: 39647] PLUGIN_HOST(39647) starting instance
root INFO [nsfw-watcher: 39621] Started watching: /home/massimo/theia
root ERROR [nsfw-watcher: 39621] Failed to watch "/home/massimo/theia": Inotify limit reached
root INFO [nsfw-watcher: 39621] Stopped watching: /home/massimo/theia
root ERROR Unrecognized key 'oem_minus' in 'ctrl+oem_minus'
root WARN Shadowing keybinding is ignored; {"command":"core.toggleMaximized","keybinding":"ctrl+m"}, shadows {"command":"latex-workshop.shortcut.mathbf","keybinding":"ctrl+m ctrl+b"}
root WARN Collided keybinding is ignored;  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}  collided with  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}
root WARN Could not register keybinding:
  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}
Error: "enter" is in collision with something else [scope:1]
root INFO Started watching the git repository: file:///home/massimo/theia
root INFO Config file tasks.json does not exist under file:///home/massimo/theia
root INFO [nsfw-watcher: 39621] Started watching: /home/massimo/theia/.theia/settings.json
root INFO [nsfw-watcher: 39621] Started watching: /home/massimo/theia/.vscode/launch.json
root INFO [nsfw-watcher: 39621] Started watching: /home/massimo/theia/.vscode/settings.json
root INFO [hosted-plugin: 39647] PLUGIN_HOST(39647): PluginManagerExtImpl/init()
PLUGIN_HOST(39647): initializing(latex-workshop@8.1.0 with /home/massimo/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [nsfw-watcher: 39621] Started watching: /home/massimo/theia/appveyor.yml
root INFO [nsfw-watcher: 39621] Stopped watching: /home/massimo/theia/appveyor.yml
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 39977] Started watching: /root/.theia
root INFO [nsfw-watcher: 39977] Started watching: /home/massimo/Desktop/latex
root INFO Detected keyboard layout from pressed keys: Portuguese (PC)
root WARN Collided keybinding is ignored;  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}  collided with  {"command":"terminal:new","keybinding":"ctrl+shift+`"}
root WARN Could not register keybinding:
  {"command":"terminal:new:active:workspace","keybinding":"ctrl+`"}
Error: "ctrl+`" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 146 ms
root INFO [nsfw-watcher: 39977] Started watching: /home/massimo/Desktop/latex
root WARN EditorNavigationContribution.onStart is slow, took: 1467 ms
root INFO Config file tasks.json does not exist under file:///home/massimo/Desktop/latex
root INFO [nsfw-watcher: 39977] Started watching: /home/massimo/Desktop/latex/sample.tex
root INFO [hosted-plugin: 40007] PLUGIN_HOST(40007) starting instance
root ERROR Unrecognized key 'oem_minus' in 'ctrl+oem_minus'
root WARN Shadowing keybinding is ignored; {"command":"core.toggleMaximized","keybinding":"ctrl+m"}, shadows {"command":"latex-workshop.shortcut.mathbf","keybinding":"ctrl+m ctrl+b"}
root WARN Collided keybinding is ignored;  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}  collided with  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}
root WARN Could not register keybinding:
  {"command":"latex-workshop.onEnterKey","keybinding":"enter"}
Error: "enter" is in collision with something else [scope:1]
root WARN Invalid embedded language found at scope source.asymptote: <<null>>
root WARN Invalid embedded language found at scope source.dot: <<null>>
root WARN Invalid embedded language found at scope source.gnuplot: <<null>>
root WARN Invalid embedded language found at scope source.js: <<null>>
root WARN Invalid embedded language found at scope source.scala: <<null>>
root WARN Invalid embedded language found at scope text.xtml: <<null>>
root WARN Invalid embedded language found at scope source.yaml: <<null>>
root INFO [hosted-plugin: 40007] PLUGIN_HOST(40007): PluginManagerExtImpl/init()
PLUGIN_HOST(40007): initializing(latex-workshop@8.1.0 with /home/massimo/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [hosted-plugin: 40007] PLUGIN_HOST(40007): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/James-Yu.latex-workshop-8.1.0.vsix/extension/out/src/main.js)
root ERROR onWillSave listeners should provide edits, not directly alter the document.

it has never stopped until today.

thanks

**Comment by tamuratak** [comment]
You have to install TeX distributions. Please refer to [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Install).

Please fill out all the information required in the issue template.

Thanks.

**Comment by maxcordivani** [comment]
Thank you for your reply and support.
