### ISSUE TITLE
Include additional bib files in citation browser

### ISSUE THREAD

**Issue by le-cds** [James-Yu/LaTeX-Workshop#169]
I have lots of LaTeX projects that all use the same set of bib files stored in a central repository. LaTeX Workshop only seems to search those in the current workspace when opening the citation browser. I would love there to be a setting that would let me specify additional bib files to include in the browser. Something like this:

```json
"latex-workshop.citations.additionalBibFiles": [
    "path/to/first/bib/file",
    "path/to/second/bib/file"
]
```

Thank you so much for an excellent plug-in. :)

**Comment by James-Yu** [comment]
You need to include the files in you latex document. Then the extension will parse them. It does not make sense if extra bib keys are inserted without latex including/compiling the bib file.

**Comment by le-cds** [comment]
I am including them using `\addbibresource`, but they are in a completely separate folder. Like this:
```
/home/le-cds/Documents/latex/thesis/thesis.tex   <-- file that uses \addbibresource
/home/le-cds/Resources/BibDatabase/main.bib   <-- Main bibliography database
```
The bibliography database is made known to the TeX system by including it in [the local TEXMF tree](http://www.tex.ac.uk/FAQ-what-TDS.html). Another way would be to set the `BIBINPUTS` environment variable, but I had problems doing that.

Anyway, long story short... there are multiple ways to reuse the same bib database across different LaTeX projects. Finding those bib files automatically if they are not already part of the project folder might be difficult to get right. Hence my suggestion to be able to specify additional bib files. :)

**Comment by James-Yu** [comment]
A pretty reasonable use-case. Will implement soon.

**Comment by le-cds** [comment]
Good work, thanks a lot! :smiley:
