### ISSUE TITLE
Tabular (tabularx and others array): Add new line with corresponding ampersand

### ISSUE THREAD

**Issue by basilgass** [James-Yu/LaTeX-Workshop#1691]
When you hit `enter ` and if a line starts with `\item`, the plugin adds a new line starting with `\item`.

It would be nice if this feature would be "extended" for tabulars/arrays... For example, if I have something like this:

    begin{tabular}{ccc}
        a & b & c \\ <-hit enter with cursor here
    \end{tabular}

I would like the script to add a new line with the needed ampersand and tabstops.
`    $1 & $2 & $3 \\`
It should also detect if the 'end of line' is ended with:

1. an optional height, like `a&b&c\\[2em]`
2. an optional horizontal line `\hline`

Basil

**Comment by jlelong** [comment]
I am afraid this feature request goes beyond the scope of the extension. Detecting the format of a tabular is quite a pain and it would not help that much. I am closing it. unless there is a massive vote for it.
