### ISSUE TITLE
Package documentation suggestions

### ISSUE THREAD

**Issue by cojua8** [James-Yu/LaTeX-Workshop#1692]
Hi!,

I use package documentation a lot, so I'd like the "Show package documentation" to suggest the packages called in the document, instead of writing the names every time.

Also, I noticed that when you write a wrong package name, the command opens all previous documentation opened. For example, I was looking at subcaption and hyperref documentation, and tried to open an inexistent hyperreff, both subcaption and hyperref docs were opened again

**Comment by cojua8** [comment]
I understand the problem, and as user I'd prefer a selection list, since I usually want to see documentation of already loaded packages, and look for new packages on google.
Of course, this is just my opinion,

**Comment by jlelong** [comment]
@cojua8 a new command has been introduced for that `latex-workshop.texdocUsepackages`. You can call through the command palette with _Show package documentation actually used_.
