### ISSUE TITLE
Latexdiff support 

### ISSUE THREAD

**Issue by arn-all** [James-Yu/LaTeX-Workshop#1699]
For a neat visualization of the changes to a file, there is a perl tool called latexdiff, recommended by the folks at Overleaf :
https://www.overleaf.com/learn/latex/Articles/Using_Latexdiff_For_Marking_Changes_To_Tex_Documents 

I think it'd be nice to be able to call this tool directly from within VS Code, comparing the current version to the last commit / any commit / any branch.

**Comment by tamuratak** [comment]
duplicate of #411
