### ISSUE TITLE
bibtex error  (exited with error code 1)

### ISSUE THREAD

**Issue by mengyyy** [James-Yu/LaTeX-Workshop#17]
Even i install LaTeX distribution in system PATH 
D:\Program Files\MiKTeX 2.9\miktex\bin\x64

but i get this  

Step 1: xelatex -synctex=1 -interaction=nonstopmode -file-line-error "untitled-1"
Step 2: bibtex "untitled-1"
Error: Command failed: bibtex "untitled-1"
 `bibtex "untitled-1"` (exited with error code 1)

**Comment by James-Yu** [comment]
Do you include any \cite{something} in your tex?

**Comment by mengyyy** [comment]
this is my tex file 
=======
\documentclass{article}
\begin{document}
hello, world
\end{document}
=======
i donot see anything about bibtex in requirement .
so i just test a simple tex file

**Comment by James-Yu** [comment]
Add some citation or remove bibtex from compiler chain in setting.

**Comment by mengyyy** [comment]
I think you should write this in requirement...So confused for new people.
