### ISSUE TITLE
Specify shell (on Windows?) for latex-workshop.latex.external.build.command?

### ISSUE THREAD

**Issue by fuhrmanator** [James-Yu/LaTeX-Workshop#1702]
First: I love LaTeX Workshop in VS Code!!!
**Is your feature request related to a problem? Please describe.**
I lost much time when trying to run a bash script from latex-workshop.latex.external.build.command using VS Code on Windows 10. When I opened a Terminal in VS Code, it's a bash shell, so I made a script to build my LaTeX and would run it from this bash terminal. It worked fine when I executed it by hand.

However, configuring latex-workshop.latex.external.build.command to point to that bash script would result in strange behavior. It doesn't work, and there is no feedback that it's an error. After saving a changed `.tex` file, here's what I see in the log:

```
[12:24:44] BUILD command invoked.
[12:24:44] Build using the external command: ./bibtopic_build.sh 
```
But then there's no other feedback.

Finally, I tried using a `.bat` file with the same commands, as if it was running in a CMD.exe of windows. That works great.

**Describe the solution you'd like**
Perhaps clear up the details in the documentation of what environment the build.command will run in. An even better fix would be to add an option to specify the shell environment in which the build.command will run (or maybe use the VS Code main preference for terminal?). 

**Describe alternatives you've considered**
I created this make script because I am using `bibtopic` and LaTeX Workshop doesn't seem to be smart enough to figure out the [right build commands](http://ctan.mirror.rafal.ca/macros/latex/contrib/bibtopic/bibtopic.pdf), e.g.,

```
$ latex sample
```
_. . . (message from bibtopic.sty to run BibTEX on ‘sample1’ and ‘sample2’ ) . . ._
```
$ bibtex sample1 (Note: Filename without extension! )
$ bibtex sample2
$ latex sample
```
_. . . (message from LATEX: ‘Rerun to get references right’ ) . . ._
```
$ latex sample
```
Ultimately, that would be a great addition to support dynamic `bibtopic` builds.

**Comment by trevorgunn** [comment]
As far as I know, the Javascript engine simply asks the kernel to run various files. In Unix-like operating systems, the kernel has code for dealing with `#!`'s but the Windows NT kernel does not. So if you want to run a bash script in Windows, you cannot rely on the kernel to pass the file to bash, you have to call up bash yourself and tell it to run the script yourself.

That looks like:

```
  {
    "name": "Bash Script",
    "command": "bash",
    "args": [
      "path\to\script.sh"
    ],
    "env": {}
  }
```

**Comment by fuhrmanator** [comment]
@trevorgunn Thanks for that pointer. I'm able to run the right bash script.

However, the trouble I'm encountering now is that with that `bash`, somehow it's running my TeXLive install rather than the Windows MikTeX. I fear there is some mixing of my WSL (windows subsystem for Linux) environment. Is there a way I can specify the Windows install (non WSL) of git bash?

**Comment by fuhrmanator** [comment]
I'm good now, just putting the hard path to the bash as follows:

```javascript
  "latex-workshop.latex.external.build.command": "C:/MinGW/msys/1.0/bin/bash.exe",
  "latex-workshop.latex.external.build.args": [
	  "./bibtopic_build.sh"
]
```
