### ISSUE TITLE
Dependencies with the same name as the root file

### ISSUE THREAD

**Issue by brunotvs** [James-Yu/LaTeX-Workshop#1703]
**Is your feature request related to a problem? Please describe.**
The extension fails to parse and provide intellisense files imported with subimport that has the same name as the base file name.

**Solution**
Parse files imported that has the same name as the base file name

**Alternatives considered**
Keeping the .fls file partialy solves the problem, it can't go more than two 'levels' deep

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template.

**Comment by brunotvs** [comment]
The problem is a bit different than what I was thinking.

I expected the editor to suggest, as the input command argument, folders and files located under the same folder of the file which is "inputing" (ignoring files and folders located above it), when it gets "subimported" using the import package.

It has nothing to do with the files name, my bad.
