### ISSUE TITLE
pdflatex is still working after close the VScode 

### ISSUE THREAD

**Issue by crazydogen** [James-Yu/LaTeX-Workshop#1704]
I use OneDrive for Synchronizing the latex source file, and I noticed that the pdflatex was still running after I closed the VScode (this causes the occupation of some latex source file and the OneDrive can not be synced during the file occupation).
Is there any solution for stopping the pdflatex automatically?

OS: Win10 1809 
VScode: 1.38.1
Latex-Workshop: 8.1.1

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template.

**Comment by tamuratak** [comment]
If any progress, feel free to reopen this issue.
