### ISSUE TITLE
A setting to disable math-mode highlighting?

### ISSUE THREAD

**Issue by mgeorge** [James-Yu/LaTeX-Workshop#1706]
I have my own environment that wraps the lstlistings environment for formatting code listings.  Any time I have a code listing that contains a single $ character the math-mode highlighting gets applied to the entire rest of my document.

I very rarely use math-mode, and often have code listings with a single $ character, so definitely do not want the math-mode highlighting enabled.

Can we have a setting to disable this please?

**Comment by jlelong** [comment]
I am afraid there is no way to disable part of the syntax highlighting. Can you post an example reproducing your issue?

**Comment by mgeorge** [comment]
Here is a complete example that demonstrates the problem.

```
\documentclass[a4paper]{article}

\usepackage{listings}

\lstnewenvironment{codeblock}[1][]{
	% I normally have a large number of settings in here for
        % customizing the code formatting
}{}

\begin{document}

	\begin{lstlisting}
		echo $VAR
	\end{lstlisting}

	This is fine.

	\begin{codeblock}
		echo $VAR
	\end{codeblock}

	This is not fine.

\end{document}
```

There must be an exception for the `lstlisting` environment since the math-mode hightlighting is not applied to the first `$` sign.  The `$`  in the `codeblock` environment triggers the math-mode highlighting which is then applied to the rest of the document.

An alternative solution would be to expose the list of "protected" environments that math-mode is not applied to as a setting.  I could then add my `codeblock` environment to it.

**Comment by mgeorge** [comment]
This is a screenshot of how the above code is displayed in VScode:
![screenie](https://user-images.githubusercontent.com/799737/65298631-4a675300-dbc0-11e9-82d7-c26d68e0faa8.png)

**Comment by trevorgunn** [comment]
I think the best option for you is to edit the syntax file directly: `syntax/LaTeX.tmLanguage.json`. Then find all the places where `lstlisting` shows up and add your `codeblock` environment in there. To facilitate this across updates, maybe make a script to help:

```bash
#!/bin/bash
# Add codeblock environment to LaTeX workshop syntax file

file=~/.vscode/extensions/james-yu.latex-workshop*/syntax/LaTeX.tmLanguage.json

sed -i 's/lstlisting/lstlisting|codeblock/' $file
```

**Comment by jlelong** [comment]
> An alternative solution would be to expose the list of "protected" environments that math-mode is not applied to as a setting. I could then add my `codeblock` environment to it.

Unfortunately, there is no way to enable user configured syntax highlighting. I will create a wiki entry with the list of code environment.

**Comment by mgeorge** [comment]
@trevorgunn's solution of editing the language file works.  Thanks for that.
