### ISSUE TITLE
Feature Request: Clean aux files recursive

### ISSUE THREAD

**Issue by 7zrty** [James-Yu/LaTeX-Workshop#171]
Hey,

I am not sure if i missed a setting but it would be nice if the plugin not only cleans the root folder of the document from unwanted files after compiling, but also the sub-folders of the project. I tend to structure my papers a lot and am left with a lot of auxiliary files everywhere.

I guess this could be achieved with modifying the "latex-workshop.latex.clean.fileTypes" setting to something like "**/*.aux", but that is (in my humble opinion) counter intuitive and should be enabled by default.

greetz,

**Comment by James-Yu** [comment]
Sorry but this will not be implemented by two reasons. On the one hand iterating through all sub-folders can be possible overwhelming. No one knows if anyone may have 1000 sub-folders or so. On the other hand, recursive file removal can be dangerous. The extension should also entertain those who wish to have their customization. This is even more optional as the `glob` file matcher we use can accommodate this demand.

Thank you very much for this suggestion tho. It is always a pleasure to discuss with users on how things should be designed.
