### ISSUE TITLE
Allow using with different file types

### ISSUE THREAD

**Issue by flying-sheep** [James-Yu/LaTeX-Workshop#1714]
The “View PDF” button isn’t shown and manually invoking the action doesn’t do anything for my `.ctx` files. The same might apply to `.ltx` files.

**Comment by tamuratak** [comment]
I can not find what kind of file has the extension `.ctx`. Would you mind explain?

**Comment by flying-sheep** [comment]
[ConTeXt](https://wiki.contextgarden.net/What_is_ConTeXt)!

**Comment by tamuratak** [comment]
Supporting ConTeXt is out of the scope of LaTeX Workshop.

**Comment by flying-sheep** [comment]
I don’t want support, I want to be able to configure the file extensions it recognizes as TeX. As said, `.ltx` is also pretty widespread.

If the subset of functionality that isn’t LaTeX specific doesn’t fit my needs with using ConTeXt, I won’t complain here.

**Comment by jlelong** [comment]
The `.ltx` extension is already considered as a LaTeX file. I will do the same for `.ctx`.

**Comment by flying-sheep** [comment]
Thank you!
