### ISSUE TITLE
Wrong Display of german "Umlaute" "a, "o, "u using vscode and LaTeX Workshop

### ISSUE THREAD

**Issue by kdtieste** [James-Yu/LaTeX-Workshop#1715]
I have written a book using LaTex with 
\inputencoding{latin1}
So, I open the TeX files in the vscode editor using the codepage Windows1252. 

German "Umlaute" are displayed as <?> in the Latex structure of the workshop and also in the pop-up window at the three dots after the filename of the windows. 

Maybe this problem can be solved using a correct translation of the code Windows1252-->UTF8. 

Details see attached screenshot. 

**Desktop [Required]:**
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601
 - OS: [e.g. Windows 7]
 - VS Code version: [e.g. 1.20.0]
 - Extension version: [e.g. 5.0.0]

Name: LaTeX Workshop
Id: james-yu.latex-workshop
Description: Boost LaTeX typesetting efficiency with preview, compile, autocomplete, colorize, and more.
Version: 8.1.1
Publisher: James Yu
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop

**Are you using LaTeX Workshop with VS Code Remote?**

No

The latex workshop seems to be a great software!

Before testing the latex workshop I used the texnixcenter. 

Thanks, 
Karl-Dieter Tieste

![TeXCPWindows1252](https://user-images.githubusercontent.com/55718440/65464749-e6ac8680-de5a-11e9-8cc4-73a17b6a5e57.png)
<!--

**Comment by jlelong** [comment]
> Maybe this problem can be solved using a correct translation of the code Windows1252-->UTF8.

You are right but there is no way the current file encoding from vscode's API. So I am afraid we cannot do much for people not using 'utf-8'.

I will be happy to reopen the issue if anyone thinks of a way to improve this.

**Comment by idhDev01** [comment]
I'm not sure, if there is a chance for Excel-Developers to change to UTF8. No matter, where you finally code your VBA Code, it is provided by the integrated settings of Excel and can hardly be changed, right?
