### ISSUE TITLE
Folding arbitary regions using comments.

### ISSUE THREAD

**Issue by jamesohortle** [James-Yu/LaTeX-Workshop#1716]
Not sure if this is expected behaviour and I couldn't find documentation or another issue for this. Please feel free to point me in the right direction/close as necessary.

In other languages (e.g., Python), if you want to fold arbitrary sections of code you can write
```python
#region
... # any code you want.
#endregion
```
As long as the comments match `"^\\s*#\\s*region\\b"` and `"^\\s*#\\s*endregion\\b"`, respectively, the code will fold and look like 
```python
#region ...
```

I'm not sure if I'm doing this right, but it looks like if I want to get the same behaviour using LaTeX-Workshop, I need to go
```latex
%\begin{region}
Lorem ipsum dolor sit amet...
%\end{region}
```

This will fold to
```latex
%\begin{region} ...
%\end{region}
```

Am I doing this right? Or is there something like the below that I should be using instead?
```latex
%region
Lorem ipsum dolor sit amet...
%endregion
```

I actually find the above behaviour sort of cute but it also means that folding can occur with comments like `%\section{Commented out section}`.

**Comment by trevorgunn** [comment]
There is nothing in the folding code that deals with comments differently. As far as the folding code is concerned, it is like the `%` signs marking comments are not there. That is why 

```latex
%\begin{region}
...
%\end{region}

and

%\section{Some title}
```

create folding sections. It is more an accident than intended behaviour.

**Comment by jlelong** [comment]
I believe commented lines should be ignored when looking for folding markers. Do you agree with that?

**Comment by tecosaur** [comment]
Eh. Is there much of a downside? I think it can be good that with a large chunk of commented code you can fold envs.

At the very least we should definitely support some form of commend-based folding markers in my opinion.

**Comment by jlelong** [comment]
@tecosaur OK I leave it as it is as far as comments are concerned. What would you suggest as a comment based folding marker?

@jamesohortle 
> Or is there something like the below that I should be using instead?
````
%region
Lorem ipsum dolor sit amet...
%endregion
````

You can actually use
```
%\begingroup
Lorem ipsum dolor sit amet...
%\endgroup
```

**Comment by jamesohortle** [comment]
I think we definitely want to keep arbitrary region folding via some comment. I like the fact that `\begin{} ...\end{}` matches normal LaTeX commands (it's sort of cute). I was simply unsure if this was intended behaviour or an unintentional hack.

**Comment by jamesohortle** [comment]
@jlelong Yes, I think `%\begingroup ... %\endgroup` is quite nice. :)

**Comment by jlelong** [comment]
We should create a wiki entry for this.

**Comment by jamesohortle** [comment]
@jlelong I'm happy to write it!

**Comment by tecosaur** [comment]
Excellent. This seems to have resolved nicely.

**Comment by jlelong** [comment]
See the documentation on the wiki https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#code-folding
