### ISSUE TITLE
Automatically duplicates after pasting in bibtex file

### ISSUE THREAD

**Issue by tylerliu1998** [James-Yu/LaTeX-Workshop#1718]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**
You still see this issue?: Yes

**Describe the bug [Required]**
When you paste an entry in a bib file, it automatically duplicates all the contents, which is very annoying and causes compiling failure.

**To Reproduce**
1. Go to Google Scholar and copy some bibtex citation content.
2. Open the latex project and open the bib file. Make sure it is not empty at first.
3. Paste the content at the bottom of the file.
4. It is correct immediately after you paste but in a second it will duplicate itself.

**Expected behavior**
Not duplicate

**Logs [Required]**
Do not need logs.

**Screenshots**

**Desktop [Required]:**
 - OS: macOS
 - VS Code version: any
 - Extension version: any

**Are you using LaTeX Workshop with VS Code Remote?**
No

**Additional context**
If you type the content (not pasting) and click save or format the code, this problem would not appear.

**Comment by jlelong** [comment]
I cannot reproduce the issue. It might be related to `format` settings, in particular `formatOnPaste`.

**Comment by tylerliu1998** [comment]
It is not a formatting issue because the code does not format after you paste. It just duplicates. And I never encounter the problem after formatting. Did you make sure the bib file is not empty when you paste to reproduce?

**Comment by jlelong** [comment]
> Did you make sure the bib file is not empty when you paste to reproduce?
Yes

**Comment by tylerliu1998** [comment]
Sorry, it seems indeed the formatOnPaste of VS Code wrongly after pasting in bib file. It duplicates the contents instead of formatting it. It would not happen if I disable it. It is very strange though because it performs well if I manually format the code.

**Comment by tylerliu1998** [comment]
So you can reproduce it after enabling pasteOnFormat

**Comment by jlelong** [comment]
Unfortunately no but I am convinced that these three settings do not play well together since the formatting utility `latexindent` reads its input from the file on the disk and not from the content of the editor. Every formatting process tries to use the same temporary file, which leads to content altering. This is related to [this](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#my-file-gets-messed-up).

**Comment by tylerliu1998** [comment]
Thanks a lot. I think it is the result of two `latexindent` s running at the same time. Failing to reproduce might be due to different versions of `latexindent` or `perl`. In fact, if you paste too frequently, a formatting failure would appear saying some temporary file which should have been generated by `latexindent` does not exist. So maybe somehow two temporary files merged in my situation. The solution is to disable one of the three settings I mentioned. But one thing remains unclear to me: Why does the focus change and trigger autosave after pasting? What I see is that the cursor remains in the editor area and the focus does not change.

**Comment by jlelong** [comment]
The whole issue comes from how `latexindent` works and we cannot do anything from the extension side to fix all these autoformatting isssues.
