### ISSUE TITLE
Issue with math shortcuts

### ISSUE THREAD

**Issue by jbm91** [James-Yu/LaTeX-Workshop#1719]
Hello
First off, I love this extension and plan on using it for writing my thesis.
I have found one thing that I have a small gripe with however. After using a math snippet whatever is placed in the created brackets will not recognize any of the math snippets until the cursor has been moved out of the brackets, and placed back in.

Example:
@/ produces
\frac{}{} and places the cursor within the two first curly brackets.
If I now try to write x__ I will not be prompted to insert _{}.
If I move my cursor to the next set of brackets using tap, the same behavior persists.
If I move my cursor by using the arrow-keys or my mouse, the behavior seizes.
I do not know if this is a bug with intellisense however. If that is the case, then I'm sorry if this is the wrong palce to post the question.

Best

**Comment by jlelong** [comment]
You need to set `editor.suggest.snippetsPreventQuickSuggestions: false`. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-nest-snippets).

**Comment by jbm91** [comment]
Holy moly, thanks for the fast reply. Sorry for the inconvenience.

**Comment by jlelong** [comment]
You're welcome!
