### ISSUE TITLE
Autocomplete suggestions in math mode?

### ISSUE THREAD

**Issue by tabatabai** [James-Yu/LaTeX-Workshop#172]
When in text mode, i get autocomplete suggestions, but in a math environment like $[...]$ or \begin{equation} [...] \end{equations} i have to trigger the suggestion manually by editor.action.triggerSuggest.
Is this behaviour intended and is there a way to change it?
Thank you!

**Comment by James-Yu** [comment]
I cannot reproduce the problem. See screenshot:
![image](https://user-images.githubusercontent.com/4210342/27548415-7ebd35d4-5acb-11e7-9a49-142b78a6568a.png)

There is no explicit logic on detecting math mode. It should be a local or vscode problem. An gif animation showing the problem may help.

**Comment by tabatabai** [comment]
Sorry, i found the issue. I was using a snippet to write the backslash symbol, which seems not to trigger the suggestion popup. Thanks for your great work i really enjoy the extension!
