### ISSUE TITLE
Word Wrap

### ISSUE THREAD

**Issue by Wenchao-Deng** [James-Yu/LaTeX-Workshop#1721]
I think "word wrap", as in the Sublime, is very useful when writing Latex. Because a text paragraph is often too much long to be show in one line. The "word wrap" will help to avoid typing constantly space key.

Thanks so much for your work on this powerful tool.

**Comment by jlelong** [comment]
I do not understand what you want. VSCode already implements word wrapping, see `editor.wordWrapColumn` and `editor.wordWrap`.

**Comment by Wenchao-Deng** [comment]
> I do not understand what you want. VSCode already implements word wrapping, see `editor.wordWrapColumn` and `editor.wordWrap`.

Okay, I found it. Thank you.
