### ISSUE TITLE
linterOptions in tsconfig.json is not a valid option

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#1722]
@jlelong `linterOptions` in `tsconfig.json` is not a valid option. What is the purpose?

https://github.com/James-Yu/LaTeX-Workshop/blob/167e1de96a5cb8adb5b9836254f94843b8fd8a09/tsconfig.json#L33-L38

**Comment by jlelong** [comment]
I have been facing an annoying issue with `.json` files. Even after fixing an error in a `.json` file, the error message remains in the problem pane and the only way to get rid of it is to restart vscode.

<img width="448" alt="Capture d’écran 2019-09-27 à 06 35 23" src="https://user-images.githubusercontent.com/2910140/65742835-23de7600-e0f2-11e9-9d54-fab488d5ea78.png">

This problem only happens in LW repo (not in vscode repo for instance) and it seems to be related to `tslint` trying to lint `.json` files hence my bad tweak.

**Comment by tamuratak** [comment]
I cannot reproduce the problem even if the TSLint extension is installed. How about disabling the extension for the repository of LaTeX Workshop with `Disable (Workspace)`.

<img width="550" alt="2019-09-27 14 57 47" src="https://user-images.githubusercontent.com/10665499/65745640-5068b100-e137-11e9-9d62-8487f780903f.png">

**Comment by jlelong** [comment]
Strange enough, I do not have `tslint` extension. I have simply cloned the LW repo again and everything is fixed. There was probably something wrong in my local config from the time we switched from `tslint` to `eslint`.

@tamuratak Thanks for pointing this out.
