### ISSUE TITLE
Knitr support?

### ISSUE THREAD

**Issue by RaghuNaik** [James-Yu/LaTeX-Workshop#1724]
Can I compile Rnw files in Latex-Workshop  using Knitr?

It would be great to have this feature in this excellent package. 

Cheers.

R

**Comment by tamuratak** [comment]
You can associate file extensions, `.Rnw` and others, to `latex`. See [link](https://code.visualstudio.com/docs/languages/identifiers).

You can also refer to an [official document](https://yihui.name/knitr/demo/editors/).

**Comment by RaghuNaik** [comment]
Ok great. Thanks.
