### ISSUE TITLE
Citation browser broken

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#173]
I am only able to get the citation browser to respond (i.e., display anything beyond it's default display contents) to the letter "a." Any other letter, or any further letters, has no effect. Let me know if I should provide a screenshot.

**Comment by James-Yu** [comment]
A screenshot is preferred. Also, this seems to be the same issue with #132 . However, I cannot reproduce the problem.

**Comment by zachjweiner** [comment]
It is in fact identical to #132.  I'll also note that the pop-up search works fine, except the display info is a little wonky, especially with respect to authors:

![image](https://user-images.githubusercontent.com/19390728/27670248-691aee10-5c51-11e7-80e6-4ef3e4337198.png)

**Comment by James-Yu** [comment]
Can you please post this piece of bibtex? It might be related with the format of the file.

**Comment by zachjweiner** [comment]
`@article{Wilson:1974sk,
      author         = "Wilson, Kenneth G.",
      title          = "{Confinement of Quarks}",
      journal        = "Phys. Rev.",
      volume         = "D10",
      year           = "1974",
      pages          = "2445-2459",
      doi            = "10.1103/PhysRevD.10.2445",
      reportNumber   = "CLNS-262",
      SLACcitation   = "%%CITATION = PHRVA,D10,2445;%%"
}`

I have also tried replacing the quotes with braces, to no avail.

**Comment by James-Yu** [comment]
Thanks, will test it out soon.

**Comment by James-Yu** [comment]
It seems that the problem is somehow related to how the bibtex parser works. I am implementing a new parser and hopefully the problem can be solved.

**Comment by James-Yu** [comment]
I'll push a new release soon, which handles double quoted strings better. Here are some screenshots of the provided bibitem:
![image](https://user-images.githubusercontent.com/4210342/27678196-e9eb8f8c-5ce6-11e7-8451-e62cba058704.png)
![image](https://user-images.githubusercontent.com/4210342/27678230-16351edc-5ce7-11e7-8c07-49d4ca0abf49.png)
Please comment on whether the problem is solved. Thanks.

**Comment by zachjweiner** [comment]
Much better; while we're here I'll also point out a very minor display issue for long titles (which I might recall has been mentioned before here?):

![image](https://user-images.githubusercontent.com/19390728/27690575-51c22818-5ca7-11e7-8fc8-978b127b7d38.png)

Unfortunately this didn't help the citation browser searching. Maybe I'll try a fresh VSCode install on my second computer and see if there's any interference from other extensions or settings.

**Comment by James-Yu** [comment]
I suppose the display glitch is somewhat related to how vscode handle inline breaks in strings. Meanwhile, one thing that comes to me is how `Proceedings` is processed in the new screenshot. It seems the parser cannot recognize it as an individual "attribute". Is that intended?

As to the citation browser thingy, I still have no idea on why it happened. I think the error messages in the developer console may help tho.

**Comment by zachjweiner** [comment]
I am unsure about `proceedings` - `inspireHEP` generates `.bib` files so I never look too closely at them, and usually only reference journal articles anyway. I'm happy to provide the citation itself if you'd like to look, but this issue I can live with :)

For the citation browser: that lower case stuff from the issue you referred to:

![image](https://user-images.githubusercontent.com/19390728/27737734-e04d052c-5d6e-11e7-853b-c6465d8a4ab9.png)

**Comment by James-Yu** [comment]
The screenshots are awesome. I will check the issue a bit later.

**Comment by James-Yu** [comment]
Hmm I just checked and confirmed that it is not an extension bug. It might be related with how vscode reads the content of each quick menu item. Can you please send me your bugged bibtex file? It can let me confirm if it is a local problem or not. Got some initial guesses but cannot reproduce the problem.

**Comment by zachjweiner** [comment]
Actually, in trying to build more of a MWE I discovered that the issue is a `misc` entry of the form

~~~~
 @misc{github,
      howpublished = "\url{https://github.com}"
 }
~~~~

Removing it, the citation browser is flawless. Maybe it's the lack of author/etc information?

**Comment by James-Yu** [comment]
That should be the problem. For such entries, the extension creates an empty menu item in the quick menu, which vscode cannot auto-remove. Will fix the problem in the next update.

**Comment by zachjweiner** [comment]
Excellent. FYI, modifying the entry to have empty author and title fields, a la

~~~~
 @misc{github,
      howpublished = "\url{https://github.com}",
      author = "",
      title = ""
 }
~~~~
resolves the issue.
