### ISSUE TITLE
SyncTeX from input files

### ISSUE THREAD

**Issue by emanspeaks** [James-Yu/LaTeX-Workshop#1730]
**Is your feature request related to a problem? Please describe.**
I have a multiple-file document with one master *.tex file that `\input`s a bunch of other files.  If I click `SyncTeX from cursor` while inside one of the input files, the extension log has a very long traceback and cryptic errors.  Upon switching back to the master file and putting the cursor in the document, SyncTeX works again

**Describe the solution you'd like**
Have `SyncTeX from cursor` command work when inside a file that is not the TeX root.

**Describe alternatives you've considered**
Not using multiple files but that is a cop-out solution.

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Show us log messages.

**Comment by tamuratak** [comment]
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by emanspeaks** [comment]
I specifically submitted this as a feature request because it seems to me that the current implementation was not designed for this use case.  If, however, it is supposed to do this behavior and it is not, then I will happily submit a new issue as a bug using that template.   I'd like some clarification from someone first what the expected behavior is before I go to the trouble of treating this like a bug.

**Comment by emanspeaks** [comment]
In the short term, I can provide the following:

CPUs | Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 7.88GB (2.48GB free)
Process Argv | C:\Users\raeckman\git\consolehandbook\targo-template.code-workspace
Screen Reader | no
VM | 0%


Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.0.5
vscode-django | bat | 0.19.0
vscode-devtools-for-chrome | cod | 0.0.5
vscode-markdownlint | Dav | 0.30.2
gitlens | eam | 10.0.1
fortranbreaker | eki | 0.0.4
gitlab-workflow | fat | 2.1.1
matlab | Gim | 1.3.0
fortran-ls | han | 0.6.0
text-transformer | jac | 0.0.2
latex-workshop | Jam | 8.2.0
plantuml | jeb | 2.12.1
language-julia | jul | 0.12.3
linter-gfortran | krv | 2.1.1
restructuredtext | lex | 114.0.0
MagicPython | mag | 1.1.0
rainbow-csv | mec | 1.3.1
dotenv | mik | 1.0.1
anaconda-extension-pack | ms- | 1.0.1
python | ms- | 2019.9.34911
remote-ssh | ms- | 0.46.1
remote-ssh-edit | ms- | 0.46.1
remote-ssh-explorer | ms- | 0.46.1
remote-wsl | ms- | 0.39.5
cpptools | ms- | 0.25.1
csharp | ms- | 1.21.3
powershell | ms- | 2019.9.0
vscode-typescript-tslint-plugin | ms- | 1.2.2
vsliveshare | ms- | 1.0.869
debugger-for-chrome | msj | 4.12.0
vscode-yaml | red | 0.5.3
vscode-qt-for-python | sea | 0.4.1
code-settings-sync | Sha | 3.4.3
gitconfig | sid | 2.0.1
vscode-djaneiro | the | 1.4.2
cmake | twx | 0.0.17
cmake-tools | vec | 2.1.3
vscodeintellicode | Vis | 1.1.9
vscode-icons | vsc | 9.4.0
jinja | who | 0.0.8
clang-format | xav | 1.9.0

**Comment by emanspeaks** [comment]
Nevermind, it's working now.  I was able to repeat it after multiple reboots, but then I made further changes to my document and it works now...I'll start a new issue as a bug if I see it again.
