### ISSUE TITLE
Pstrickz problems

### ISSUE THREAD

**Issue by santiagoftw** [James-Yu/LaTeX-Workshop#1731]
Hello

I would like to know how I should configure or what I should install to be able to compile graphics with PSTRICKZ, for example in an editor such as Texmaker, simply compile in the form _LateX + dvips + ps2pdf + View PDF_ (for example), I would like to know if this type of settings is possible in VSC

**Comment by jlelong** [comment]
Have a look at the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes).

In short, you just have to add
- new recipe to `latex-workshop.latex.recipes`
- the three tools `latex`, `dvips`,  ps2pdf` to `latex-workshop.latex.tools`.
