### ISSUE TITLE
No "onSave"option for latex-workshop.latex.autoBuild.run

### ISSUE THREAD

**Issue by baptistecottier** [James-Yu/LaTeX-Workshop#1733]
Hello, 
as said in the title, I don't have the "onSave"option for latex-workshop.latex.autoBuild.run. 
The only one available are "never" and "onChange". 

is there a way to fix it ?

**Comment by trevorgunn** [comment]
`onSave` and `onChange` were combined in https://github.com/James-Yu/LaTeX-Workshop/commit/4d3ea8bf188f685c6fd362dceb25085f51b9e779.
