### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LiaoJingyi** [James-Yu/LaTeX-Workshop#1736]
- Issue Type: `Performance`
- Extension Name: `latex-workshop`
- Extension Version: `6.5.1`
- OS Version: `Linux x64 4.15.0-65-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/liaojingyi/James-Yu.latex-workshop-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by tecosaur** [comment]
@LiaoJingyi I don't believe you've attatched `/home/liaojingyi/James-Yu.latex-workshop-unresponsive.cpuprofile.txt` please do so as we can't do much without it.

**Comment by LiaoJingyi** [comment]
Sorry, this information is uploaded automatically by vscode.
By the way, I think the extension works well. There isn't anything goes wrong. 

[James-Yu.latex-workshop-unresponsive.cpuprofile.txt](https://github.com/James-Yu/LaTeX-Workshop/files/3697178/James-Yu.latex-workshop-unresponsive.cpuprofile.txt)
