### ISSUE TITLE
Intellisense cant find label inside custom commands

### ISSUE THREAD

**Issue by darthblade** [James-Yu/LaTeX-Workshop#1739]
When \label command is used within \newcommand or \NewDocumentCommand that label is not displayed when using \ref or \autoref commands

**To Reproduce**
````
%add to preamble
\newcommand{\insertfigure}[3]
{
  \begin{figure}[!htb]
    \center{\includegraphics[width=\textwidth]{./images/#1}}
		\caption{\label{fig:#2} #3}
  \end{figure}
}

\begin{document}

\insertfigure{test.jpg}{testLabel}{caption}% <-- should generate fig:testLabel in reference keys

\ref{fig:testLabel}% <-- this wont appear in ref keys but should appear as fig:testLabel

\end{document}
````

**Comment by jlelong** [comment]
This is because labels are obtained by directly parsing `.tex` to look for `\label{...}` entries.
We could image to also parse the `.aux` files to complete the labels list.
