### ISSUE TITLE
Compilation frequently fails with error 12/null

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#174]
It always takes >=2 tries running the default `latexmk` toolchain for my document to compile. The first time, it reports a 12/null error, seeming to be related to citations as every citation I make appears as undefined in the log. After two or three more attempts, the document successfully compiles. If I attempt to compile again after successful compilation, it again fails with the same behavior.

**Comment by James-Yu** [comment]
This is not a problem/bug related with the extension. Does the compilation works correctly with commands using CMD/Terminal?

**Comment by zachjweiner** [comment]
Apologies; I didn't realize I had multiply define citations (and the errors weren't helpful... typical LaTeX).
