### ISSUE TITLE
Sweave and LaTeX-Workshop

### ISSUE THREAD

**Issue by ChristopheRoyer21** [James-Yu/LaTeX-Workshop#1741]
This extension is perfect for working in LaTeX. However, I'm used to work with *.Rnw files which are simply TeX files with some chunks of R Code. The chunks look like:

<< [...] >>
_some code_
@

The insertion of R Code in TeX files causes some problems with the syntax. For example, whenever a "$" character is used in a chunk, the extension consider this as a LaTeX equation and brings a syntax problem. Since this is the only thing that is different to LaTeX, I suggest to add to add an option to consider the chunks as comments. This way, the extension could fully work with a *.Rnw except the compiling, which could be done with a Makefile instead.

I don't know a thing about writing extensions but I think something like this could help:

```
  "contributes": {
       "languages": [
            {"id": "latex",
            "extensions": [".tex", ".Rnw"],
            "comments": {
                 "blockComment": ["<<", "@"]
             },
             "configuration": "./language-configuration.json"
             }
         ]
     }


```

**Comment by jlelong** [comment]
I would rather define a new file type associated to the extension `.Rnw` and not alter the definitions for standard latex files. In practice this requires

- to declare a new entry in the languages array
- to create a new syntax file which sources `syntax/LaTeX.tmLanguage.json` with the extra changes you propose in #1740.

You can for instance take inspiration from what I did for the doctex filetype.

**Comment by ChristopheRoyer21** [comment]
Yes that is probably a better idea by far. As I said I'm not used in extension designing or things like that, but I will definitively look at this. I saw #1740 which is actually exactly what I need, I hope it will be available soon.

**Comment by ChristopheRoyer21** [comment]
Yes, what a coincidence! Your syntax highlighting would definitively fixes some problems. I have no experience in doing vscode extensions but I would be glad to work with you or at least to help you finding new ways to enhance this feature.
