### ISSUE TITLE
Recipe terminated with fatal error: spawn latexmk ENOENT

### ISSUE THREAD

**Issue by yrammos** [James-Yu/LaTeX-Workshop#1742]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

Done.

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

Checked. 

**Describe the bug [Required]**

A project that compiles normally on the command line fails in VSC.

Command-line command: `latexmk --xelatex --outdir=out`

LaTeX Workshop recipe:

```
		{
			"name": "latexmk_xelatex",
			"command": "latexmk",
			"args": [
				"-xelatex",
				"-synctex=1",
				"-interaction=nonstopmode",
				"-file-line-error",
				"-outdir=%OUTDIR%",
				"%DOC%"
			],
			"env": {}
		},
```

**To Reproduce**

1. Produce any valid `.tex` file.
2. Run the "Build with recipe" command for the recipe above.
3. The plugin stops immediately with the message: `Recipe terminated with fatal error: spawn latexmk ENOENT`.

**Expected behavior**

PDF document should be built, as on the command line.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

[16:41:34] Parsing /Users/username/j/core/diversity/diversity.tex
[16:41:34] File watcher: responding to change in /Users/username/j/core/diversity/diversity.tex
[16:41:34] /Users/username/j/core/diversity/diversity.tex changed. Auto build project.
[16:41:34] BUILD command invoked.
[16:41:34] Building root file: /Users/username/j/core/diversity/diversity.tex
[16:41:34] Build root file /Users/username/j/core/diversity/diversity.tex
[16:41:34] Recipe step 1: latexmk, -xelatex,-synctex=1,-interaction=nonstopmode,-file-line-error,-outdir=out,/Users/username/j/core/diversity/diversity
[16:41:34] LaTeX build process spawned. PID: undefined.
[16:41:34] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
[16:41:34] Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

</details>

**Desktop [Required]:**

macOS 10.14.6 (Mojave)

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**

I realize this has the appearance of a $PATH problem. Here is the output of `echo $PATH` on the ZSH prompt:

`/Users/username/.nvm/versions/node/v10.16.0/bin:/Users/username/.zplug/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin`

A file named `TeX` is also found in `/etc/paths.d'. As expected, it contains the following line:

`/Library/TeX/texbin`

**Comment by yrammos** [comment]
**UPDATE:**

Replicating the value of `PATH` in the `env` field of the plugin recipe resolves the issue. For some reason, it looks like VSCode does not retrieve the $PATH from the shell.

**Comment by jlelong** [comment]
There have been several issues on this but we cannot do much about it.
See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable) for some extra pointers.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template if you want to solve your issue.
