### ISSUE TITLE
Add \newcommand* to autocompletion

### ISSUE THREAD

**Issue by chrisjsewell** [James-Yu/LaTeX-Workshop#1746]
Currently, auto-completion does not find user defined commands that use `\newcommand*{\mycommand}` (the star forbids macros to accept paragraph tokens, see [here](https://tex.stackexchange.com/a/1057/107738))

I imagine this should be a relatively simple addition to the code?

Otherwise, loving the extension ta :)

**Comment by jlelong** [comment]
Hum, command auto-completion does not work the way you expect. We do not scan the files for command definitions but rather for command usage. Assume you have,
```
\newcommand{\mycommand}{....}
```
Auto-completion will not list `\mycommand` until you first use it (and save the file if `latex-workshop.intellisense.update.aggressive.enabled` is set to false).
