### ISSUE TITLE
Please add hover support for IEEEeqnarray environments

### ISSUE THREAD

**Issue by apoorvkhurasia** [James-Yu/LaTeX-Workshop#1754]
**Is your feature request related to a problem? Please describe.**
Hover/preview support for IEEEeqnarray environments is not there at the moment. This is a problem because one then has to either write the equation, compile, and check the PDF or compose the equations in the eqnarray environment and then change it to IEEEeqnarray environment once done. This is less than ideal as eqnarray environment aligns equations a bit differently than IEEEeqnarray does.

**Describe the solution you'd like**
Can we add a feature so that when the user hovers over an IEEEeqnarray environment VSCode shows a preview of the equations exactly as they would appear in the compiled PDF. This type of support already exists for inline Math, eqnarray environment, and block mode Math.

**Describe alternatives you've considered**
Currently, I compose my complex equations in the eqnarray environment and then change them to IEEEeqnarray once I am satisfied the content is correct.

**Additional context**

**Comment by trevorgunn** [comment]
I tried this and it doesn't work because MathJax (which is used for the equation hover functionality) doesn't support `IEEEeqnarray`. The list of environments supported by MathJax is documented [here](http://docs.mathjax.org/en/latest/input/tex/macros/index.html#environments).

**Comment by jlelong** [comment]
I am afraid we cannot do anything on our side until `IEEEeqnarray` is supported by mathjax.
