### ISSUE TITLE
A way to modify the snippet for inline mathmode.

### ISSUE THREAD

**Issue by ericrbg** [James-Yu/LaTeX-Workshop#1755]
**Is your feature request related to a problem? Please describe.**
Personally, in order to make it legible, I prefer to leave spaces around inline math, e.g. \\( \\int_0^\\infty e^{x^2} \\) as opposed to \\(\\int_0^\\infty e^{x^2}\\), in order to be legible. However, the default snippet inserts the cursor at the caret \\(^\\), and so I tried looking in the extension snippets file to change this to be \\( ^ \\), as is my desired behaviour. However, it isn't there, and I assume that's because it's not a "snippet" in the traditional VSCode sense.

**Describe the solution you'd like**
Some way to be able to configure this, whether it be a standard snippet file for this one or a setting in the extension itself.

**Describe alternatives you've considered**
I haven't yet - my only alternative so far is \<SPACE\> \<SPACE\> \<🡐\>.

**Comment by trevorgunn** [comment]
There are two places that snippets are defined. The first is `snippets/latex.json` and the second is `data/commands.json`. You will find this snippet in `commands.json`.

**Comment by ericrbg** [comment]
Perfect, thanks. Is there any way to change it so that it doesn’t get overwritten on update?

**Comment by tecosaur** [comment]
Nope (unfortunately, as far as I know).

**Comment by trevorgunn** [comment]
The best you can do, I think, is create a bash or powershell script that will make the change for you (via `sed` for example). Then you just double click on that file once after each update.

It would be nice if VSCode provided some way to keep user edits across updates.

**Comment by jlelong** [comment]
@ericrbg See the new [FAQ entry](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#overriding-snippets).

**Comment by ericrbg** [comment]
For some reason, this isn't working anymore :/

**Comment by jlelong** [comment]
Please open a new issue with a MWE and your configuration to reproduce the issue.
