### ISSUE TITLE
Add bibtex-tidy support to format and sort .bib files

### ISSUE THREAD

**Issue by yzhang-gh** [James-Yu/LaTeX-Workshop#1761]
**Describe the solution you'd like**
[bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy) is a tool that can tidy bibtex files (alignment, fields sorting etc.)

![tidy](https://user-images.githubusercontent.com/7588612/67284630-8a479000-f508-11e9-8172-719499e9470c.gif)

It would be great to have this built-in.

**Comment by jlelong** [comment]
Following the discussions in #1780 and #1772, `bibtex-tidy` will not be added but #1780 provides `sorting` and `aligning` for `.bib` files. More advanced formatting will be implemented later by using `biber`.
