### ISSUE TITLE
Cannot use `convert` option inside documentclass

### ISSUE THREAD

**Issue by WyRe** [James-Yu/LaTeX-Workshop#1762]
**Describe the bug [Required]**
I cannot use `convert` option inside `\documentclass[]{}` declaration

**To Reproduce**
Here the MWE:

```
% !TEX program = pdflatex
% !TEX options = -shell-scape "%DOC%"

\documentclass[preview, border=1pt, convert={outext=.png}]{standalone}
\usepackage[utf8]{inputenc}
\include{amssymb}
\begin{document}
  \begin{equation}
    \alpha = \beta\gamma
  \end{equation}
\end{document}
```

I get the following log

```
runsystem(pdflatex  -shell-escape  -jobname 'formula' '\expandafter\def\csname sa@internal@run\endcsname{1}\input{formula}')...disabled (restricted).

runsystem(convert -density 300 -units PixelsPerInch formula.pdf  -quality 90 formula.png)...disabled (restricted).


Class standalone Warning: Conversion failed! Please ensure that shell escape
(standalone)              is enabled (e.g. use '-shell-escape').
```

**Expected behavior**
From cli does work as expected when I use 

```
pdflatex --shell-escape formula.tex
```
It does produce a `.png` output

**Logs [Required]**
Already attached.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

Conversion failed! Please ensure that shell escape
(standalone)	is enabled (e.g. use '-shell-escape').
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

</details>

**Desktop [Required]:**
 - OS: Arch Linux x86_64
 - VS Code version: 1.39.2-1
 - Extension version: 8.2.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Comment by jlelong** [comment]
Your MWE does actually work on my installation (OSX and LW 8.2.0). Btw, there is a typo in your MWE on the second: `-shell-scape` should read `-shell-escape`.
You might be interested in [how to pass `-shell-escape` to `latexmk`](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk).

**Comment by WyRe** [comment]
Lol, it was that typo. I'm so sorry.
