### ISSUE TITLE
Make it possible to open the pdf viewer tab in a new window

### ISSUE THREAD

**Issue by TheDutchDevil** [James-Yu/LaTeX-Workshop#1766]
I have a dual monitor set-up and would love to be able to have the pdf viewer open on one window, and the actual `.tex` files on another window. That way I do not have to struggle with limited screen space.

However, when I have two VsCode instances open, I cannot drag & drop the pdf viewer over to the second instance. Similarily, pressing the view pdf button on the second instance does nothing. The click is registered, but no pdf viewer opens.

Is there any solution to this problem?

**Comment by trevorgunn** [comment]
You can set [`latex-workshop.view.pdf.viewer`](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfviewer) to `browser`. That ought to work for you.

I don't know the API for opening new tabs so I don't know if there is support for opening a new window. If there is, I think it would be a good option to add.

**Comment by jlelong** [comment]
It should be possible to open a new window using 
```
vscode.commands.executeCommand('vscode.openFolder', uri, true);
```
but I cannot make it work inside LW. Anyway, I think that two windows are two separate instances of VSCode and cannot communicate together so synctex would not work. 

In your case, the simplest workaround is to use an external viewer or the browser.. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View)

**Comment by TheDutchDevil** [comment]
> In your case, the simplest workaround is to use an external viewer or the browser.

I checked out both the browser and an external viewer, but I couldn't get `CTRL + clicking` to work, and I love that feature. ;( 

> but I cannot make it work inside LW. Anyway, I think that two windows are two separate instances of VSCode and cannot communicate together so synctex would not work.

After looking into this a bit more I get the idea that this is indeed the problem. For some reason VsCode does not appear to support pop-out windows without opening a new instance like Visual Studio supports. For instance see [this issue](https://github.com/Microsoft/vscode/issues/10121) in the VsCode repo.

Thanks for the response!

**Comment by pelegm** [comment]
In my humble opinion, this is one of the major drawbacks of working with VSCode+LaTeX-Workshop, at least on a 13" laptop. The side-by-side mode is challenging for my eyes. Other options (different window, browser, external PDF viewer) do not play with Synctex well and/or do not allow easy navigation.

I understand that to have such a feature, one needs to change VSCode, rather than LaTeX-Workshop? If so, are there open tickets on this that you are aware of?

**Comment by jlelong** [comment]
FYI, you can actually open the viewer in a new tab but inside [the same editor group](https://code.visualstudio.com/docs/getstarted/userinterface#_editor-groups), see https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdftabeditorGroup. This way, the window is not split.

**Comment by pelegm** [comment]
Right, I am doing that. But this way, Synctex is only working one way (from PDF to TeX, but not vice versa).

**Comment by jlelong** [comment]
I confirm that synctex works both ways. The viewer tab does not automatically get focus when you go from TeX to PDF but the position inside the PDF viewer is correct. You just have to switch to the viewer tab manually.

**Comment by pelegm** [comment]
True, that is actually what I meant (sorry).
The question is: if we do want the PDF to get focus, is it a feature that can be done within LaTeX-Workshop, or are there current limitations of VSCode?

**Comment by pelegm** [comment]
Alternatively, is there a command to switch to the "correct tab"? Or do I need to know the tab number?
I'm asking because if I can somehow know which tab to switch to, perhaps I can do some keybinding to Synctex+switch tab.

**Comment by jlelong** [comment]
You can use `ctrl` + `tab` to circulate between the tabs. The list gets reordered based on the last visited tabs.
