### ISSUE TITLE
ctrl+s not working as supposed (?)

### ISSUE THREAD

**Issue by 858bruno** [James-Yu/LaTeX-Workshop#1768]
Hi! I'm facing a strange problem. I have a tex file that is made it in parts, there is a main tex then others tex files used as input on the main file. Whenever I make a change in the main file and save he builds for a few seconds and I have the change in the pdf. But if I make a change in the input tex files and save he builds for 1~1.2s and does not change anything, but if I make him clear the auxiliary files and then ask him to build(or just save) the tex works just as supposed to do. There is something I can do to solve this?

PS. There are no errors or warnings whatsoever in the files.

**Comment by trevorgunn** [comment]
Please show your logs and desktop information as asked in the [bug report template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). If you could tell us exactly what your file structure is and provide a MWE, if possible that would also help.

**Comment by 858bruno** [comment]
In the mean time one friend solve the problem for me, actually was 2 problems in my code. 
The first one was using input when should be include(and the things that change because of that) in the main code. Second was the ".tex" in the end of the location in the input/include command(Wrong: \include{Ch1/cap1.tex}, Right: \include{Ch1/cap1})
