### ISSUE TITLE
Latex outline does not show Chapters

### ISSUE THREAD

**Issue by jose-a-sa** [James-Yu/LaTeX-Workshop#177]
The Latex outline only identifies the sections within chapters (just ignores `\chapter{}`). The levels of the outline should be like (source: ShareLaTeX):  

<table class="wikitable">
<tbody><tr>
<td> -1 </td>
<td> <code>\part{part}</code>
</td></tr>
<tr>
<td> 0 </td>
<td> <code>\chapter{chapter}</code>
</td></tr>
<tr>
<td> 1  </td>
<td> <code>\section{section}</code>
</td></tr>
<tr>
<td> 2  </td>
<td> <code>\subsection{subsection}</code>
</td></tr>
<tr>
<td> 3  </td>
<td> <code>\subsubsection{subsubsection}</code>
</td></tr>
<tr>
<td> 4  </td>
<td> <code>\paragraph{paragraph}</code>
</td></tr>
<tr>
<td> 5  </td>
<td> <code>\subparagraph{subparagraph}</code>
</td></tr></tbody></table>

**Comment by brunnerh** [comment]
Additionally it might be useful to have a user setting that can add custom commands with the respective hierarchy level it represents. The document class that i currently use has a special command (`firstsection`) for the first section that uses `section` internally, which is then not picked up the outline parser.

**Comment by James-Yu** [comment]
This feature will be released to the marketplace shortly with some other fixes.
