### ISSUE TITLE
LaTeX-Workshop not working with Code-Server

### ISSUE THREAD

**Issue by CaptainDario** [James-Yu/LaTeX-Workshop#1775]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
When I try to execute any command related to latex-workshop an error message pops up.

**To Reproduce**
1. install code-server from https://github.com/cdr/code-server
2. start code-server and install latex-workshop
3. Error:
 "Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/dario/.local/share/code-server/extensions/james-yu.latex-workshop-8.2.0/out/src/main.js'."
pops up after reloading.

**Expected behavior**
I can use the latex workshop extension

**Logs [Required]**
The Log is not available because every latex-workshop related command produces an error of the following form:
"command 'latex-workshop.\<\<Command\>\>' not found"

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**
I tried to uninstall all other extensions and deleted the "james-yu.latex-workshop-8.2.0" folder multiple times.
I tried installing node.js and npm.

**Comment by tamuratak** [comment]
We do not support code-server. Please use [VS Code Remote](https://code.visualstudio.com/docs/remote/remote-overview) for your purpose.
