### ISSUE TITLE
Changing  a  default pdf viewer in VS code to another viewer

### ISSUE THREAD

**Issue by ofenerci** [James-Yu/LaTeX-Workshop#1778]
I wonder it is possible to choose a pdf viewer in a tab (not in a external window). For example, when I compile a document, a pdf viewer shows up on the right side in the VS code. I wonder it is possible to change the viewer in Vs Code (not as a external viewer), say to Zathura.

**Comment by jlelong** [comment]
No it it not possible to change the viewer used inside VScode to display the PDF. We currently rely on `pdf.js` which is a javascript library used to render a PDF file inside a browser. It is also by Firefox. If I  understand well, you would like to embed an external PDF viewer inside VSCode using some kind of a plugin. As far as I know, this not feasible.

**Comment by joesmolsky** [comment]
The LaTeX Workshop extension does this.
