### ISSUE TITLE
Ability to disable Latex Outline

### ISSUE THREAD

**Issue by Vorror** [James-Yu/LaTeX-Workshop#178]
Is there a way to disable the Latex Outline view? I'm getting it in all my projects(that don't contain latex files)

**Comment by James-Yu** [comment]
This commit adds a condition to control the display. However, the API is currently only available in VSCode Insider channel. When it is in the public channel the view can auto-hide on non-LaTeX documents.

**Comment by Vorror** [comment]
@James-Yu Thanks!
