### ISSUE TITLE
FasTex shortcut snippets in Latex Workshop

### ISSUE THREAD

**Issue by RaghuNaik** [James-Yu/LaTeX-Workshop#1784]
I have been using FasTex shortcut snippets (see [here](http://www.cds.caltech.edu/~marsden/about/fastex/home/)). As was wondering if there is a way I can add that to Latex-Workshop.  Would appreciate any guidance here. 

Thanks.

**Comment by trevorgunn** [comment]
The live snippets feature of the [LaTeX-Utilities](https://github.com/tecosaur/LaTeX-Utilities) extension should provide what you need.

**Comment by jlelong** [comment]
I would add to @trevorgunn's answer that if you do not need snippets to depend on whether you are in maths mode or not, you can simply use the [native vscode snippet mechanism](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).

**Comment by RaghuNaik** [comment]
ok great thanks for the feedback.

**Comment by tecosaur** [comment]
@RaghuNaik looking at FasTeX I'm interested in implementing that functionality in LaTeX utils. If you'd be interested in working on this let me know :smiley: 

(I think best way to implement it would be a special action snippet like `SPEACIAL_ACTION_FRACTION`)
