### ISSUE TITLE
"View package documentation" opens all previously opened packages

### ISSUE THREAD

**Issue by LunarLanding** [James-Yu/LaTeX-Workshop#1785]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
Clicking "view documentation" link hovering over a package name opens all previously opened documentation.

**To Reproduce**
1. Create empty directory with single .tex file with the contents:
```latex
\usepackage{a0poster}
\usepackage{color}
```
2. Hover cursor over a0poster, click view documentation. Repeat with color.
3. There will be three new PDFviewer windows. (My PDFviewer is SumatraPDF)

**Expected behavior**
Each view documentation click opens the documentation for the respective package.

**Logs [Required]**
Logs don't show documentation being opened twice.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
[19:25:29] Initializing LaTeX Workshop.
[19:25:30] Creating LaTeX Workshop http and websocket server.
[19:25:30] LaTeX Workshop initialized.
[19:25:31] Server created on 127.0.0.1:57495
[19:25:31] Snippet data loaded.
[19:25:31] LaTeX Workshop version: 8.3.1
[19:25:45] Opening documentation for a0poster.
[19:25:51] Opening documentation for color.
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
empty
</details>

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.39.2
 - Extension version: 8.3.1

**Are you using LaTeX Workshop with VS Code Remote?**
No
**Additional context**
Resetting VSCode resets the documentation being opened.
Using "texdoc --view package-name" on the command line does not cause this issue.
Switched the pdf viewer to adobe acrobat dc, same issue happens.

**Comment by jlelong** [comment]
I cannot reproduce the issue.
Your log `Opening documentation for verbatim` is suspicious as you do not use this package. The behaviour you describe generally occurs when the documentation you want to access is missing on your system.

**Comment by LunarLanding** [comment]
>  Your log `Opening documentation for verbatim` is suspicious as you do not use this package. The behaviour you describe generally occurs when the documentation you want to access is missing on your system.

My bad, I copied the log from another experiment. I updated the issue with the correct logs. I have another machine, I will try to reproduce the issue there.

**Comment by jlelong** [comment]
What does happen when you execute from the command line 
````
texdoc --view a0poster
texdoc --view color
````

**Comment by jlelong** [comment]
OK I have found the bug.
