### ISSUE TITLE
To allow user to change arguments when calling synctex.

### ISSUE THREAD

**Issue by karuboniru** [James-Yu/LaTeX-Workshop#1786]
I am trying to let code in Windows to call texlive stuff in WSL directly without using WSL-remote plugin. Most things works very well such as `latexmk` `latexindent`. But `synctex` seems to hardcode absolute path to `filename.synctex.gz`. Builtin  Synctexjs seems to be unable to handle `filename.synctex.gz` created in wsl. 

**Describe the solution you'd like**
To add a new setting `latex-workshop.synctex.args` to allow me to do things like
```
       "latex-workshop.latexindent.path": "wsl.exe",
       "latex-workshop.latexindent.args": [
              "latexindent",
              "-c",
              "`wslpath \"%DIR%/\"`",
              "`wslpath \"%TMPFILE%\"`",
              "-y=\"defaultIndent: '%INDENT%'\""
       ]
``` 
just like it how I made latexindent to work.

**Describe alternatives you've considered**
To ignore potential wrong paths in `filename.synctex.gz` in the builtin Synctexjs.

**Comment by jlelong** [comment]
We already have
````
latex-workshop.view.pdf.external.synctex.command
latex-workshop.view.pdf.external.synctex.args
````
See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfexternalsynctexcommand).
