### ISSUE TITLE
Single page pdf view

### ISSUE THREAD

**Issue by tachukao** [James-Yu/LaTeX-Workshop#1789]
Would it be possible to have  single page pdf view (instead of the default continuous scroll)? This would be really useful for making slides with beamer. Thanks!

**Comment by jlelong** [comment]
We rely on `pdf.js` to display PDF files. See mozilla/pdf.js/issues/1385 for a discussion on single page mode. The conclusion seems to be that this is not implemented. Hence, I am afraid we cannot do much for this request.

**Comment by trevorgunn** [comment]
A work-around would be to set it to "page-fit" and use the up and down arrows to switch between pages rather than the scroll bar.
