### ISSUE TITLE
TOC Browser Enhancements

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#179]
- TOC Browser should highlight the line containing the section clicked
- TOC Browser jumping to line is off in some cases; generally gets near the section heading, but does not place the cursor on the right line in some situations.

**Comment by James-Yu** [comment]
I'd say the outline currently works quite well. Until I can identify cases on the second bullet point, I will focus more on other enhancements.

I've no idea on how to temporarily highlight a line in vs code. Maybe there's an API?

**Comment by jsinglet** [comment]
I don't think there is an API -- I think you'd have to do it with a timer.
