### ISSUE TITLE
References Not Recognised

### ISSUE THREAD

**Issue by DanGoldwater** [James-Yu/LaTeX-Workshop#1790]
I'm using latex workshop on Windows 10, with a recently updated version of miktex. 

My problem is that when I compile I always get an error, and none of my references are picked up. The recipe I'm using is:
```    "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
```
With my tools configured as
```      "name": "pdflatex",
       "command": "pdflatex",
       "args": [
            "--shell-escape", // if you want to have the shell-escape flag
           "-synctex=0",
      "-interaction=nonstopmode",
           "-file-line-error",
           "%DOC%.tex"
         ]
        },
     {
        "name": "bibtex",
        "command": "bibtex",
        "args": [
          "%DOCFILE%.tex"
        ],
        "env": {}
```
in my settings.JSON file. 

My MWE would be a very standard example, using 
a file called `test.tex` consisting of
```
\documentclass{article}
\title{Test}
\begin{document}
\section{Test}
\cite{Mermin}
\bibliographystyle{ieeetr}
\bibliography{TestLib.bib}
\end{document}`
```
and a `TestLib.bib` file consisting of 
```
`@article{Mermin,
  title={What's wrong with this quantum world?},
  author={Mermin, N David},
  journal={Physics Today},
  volume={57},
  number={2},
  pages={10--12},
  year={2004}
}
```
This MWE produces a PDF with [?] in place of a reference, and a log file stating "I couldn't open file name 'test.tex.aux'. My larger, more realistic documents produce very long error filled logs, with complaints about missing references. However, typing `cite{...` brings up a correct autofill list, so the library is definitely recognised on some level. 

Any help much appreciated.

**Comment by jlelong** [comment]
This is because your configuration of the `bibtex` tool is wrong. Use the default one,

            {
              "name": "bibtex",
              "command": "bibtex",
              "args": [
                "%DOCFILE%"
              ],
              "env": {}
            }

Do not add `.tex` to `%DOCFILE%`. This is why you get complaints about a missing `test.tex.aux` file.

**Comment by DanGoldwater** [comment]
Fixed, thanks!
