### ISSUE TITLE
PDF viewer not behaving correctly when color is inverted

### ISSUE THREAD

**Issue by abccsss** [James-Yu/LaTeX-Workshop#1793]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
When `latex-workshop.view.pdf.invert` is set to a value other than `0`, the PDF viewer doesn't function correctly.

- Internal links in the PDF are not working (clicking on them doesn't make the viewer jump to the position that is linked to).
- Clicking on bookmarks (in the sidebar) doesn't make the viewer jump to the bookmark.
- Zooming doesn't behave correctly. E.g. if you have a 10 page document, go to the last page and zoom in (using Ctrl + scroll), and you'll be on some other page.

These bugs are not present when `latex-workshop.view.pdf.invert` is set to `0`.

**To Reproduce**
1. Set `latex-workshop.view.pdf.invert` to `1`, or any value other than `0`.
2. Open a LaTeX document that contains internal links, PDF bookmarks, and is at least a few pages long.
3. Compile.
4. Open the PDF viewer (or re-open after changing `latex-workshop.view.pdf.invert`).
5. See the bug.

**Expected behavior**
Viewer should behave like when `latex-workshop.view.pdf.invert` is `0`.

**Logs [Required]**
Not applicable

**Screenshots**
None

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.40.0
 - Extension version: 8.3.1

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**

None

**Comment by happyangry** [comment]
Same problems and I didn't realize that the reason causing these problems is `latex-workshop.view.pdf.invert`.
My setting is `latex-workshop.view.pdf.invert=0.2`. The bookmarks fail and the zooming functions don't work properly.

OS: Windows x64 10.0.18362
VS Code version: 1.40.0
Extension version: 8.3.1

**Comment by jlelong** [comment]
@tamuratak @tecosaur Any idea of what is going wrong in there?

**Comment by tamuratak** [comment]
If I view a pdf file on browsers with `latex-workshop.view.pdf.invert`, it works well on Firefox, and not well on Google Chrome. This problem may be related to Chrome.

**Comment by jlelong** [comment]
It also works with Safari. 
While googling around, I came across [https://stackoverflow.com/questions/51589185/css-filter-invert-rule-breaking-fixed-position-on-chrome-68](https://stackoverflow.com/questions/51589185/css-filter-invert-rule-breaking-fixed-position-on-chrome-68). Applying the invert filter to the `<html>` instead of `<div id="viewer">` seems to fix everything.
