### ISSUE TITLE
disable linting

### ISSUE THREAD

**Issue by makslevental** [James-Yu/LaTeX-Workshop#1794]
how do i completely disable linting?

![image](https://user-images.githubusercontent.com/5657668/68547835-6b744500-03b4-11ea-91ed-edf9546f814a.png)

i already have chktex disabled

![image](https://user-images.githubusercontent.com/5657668/68547887-1127b400-03b5-11ea-9a9e-228b363ada7d.png)

**Comment by tecosaur** [comment]
That's not from `chktex`, that's from the parsing of the compiler log. I'm not actually aware of any settings to prevent that.

I must also admit that I fail to see why you'd want that Compiler warnings are usually worth taking note of.

**Comment by makslevental** [comment]
@tecosaur because those warnings in particular are spurious - i'm compiling my document incrementally i.e. adding citations but not running bibtex

**Comment by tecosaur** [comment]
I see. If you change the add the compiler arg `--interaction=batchmode` (see the `latex-workshop.latex.tools` setting) then it shouldn't produce any stdout. It will just succeed or fail.
This comes with its own set of drawbacks, but sounds like it may suit your purposes.

**Comment by makslevental** [comment]
@tecosaur thanks!

**Comment by tecosaur** [comment]
I'm going to assume this works and close the issue. Let us know if this isn't the case.

**Comment by trevorgunn** [comment]
There is a setting [`latex-workshop.message.latexlog.exclude`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessagelatexlogexclude) that will let you exclude certain compiler errors/warnings according to a supplied regex.

**Comment by JustSaX** [comment]
Following @trevorgunn's advice I added the following line in my settings.json and it fixed the problem for me:
```
"latex-workshop.message.latexlog.exclude":["Reference.*undefined"],
```
