### ISSUE TITLE
Compile on save compiles document opened first rather than the current one

### ISSUE THREAD

**Issue by UserRandom** [James-Yu/LaTeX-Workshop#18]
When I have two different tex files open at the same time, saving always compiles the one that I opened first.

Fantastic extension by the way. Once I find a suitable spellcheck solution for it, I will won't have any need for other latex editors.

**Comment by James-Yu** [comment]
You can use the new `compile_here` command to re-assign your root tex file. The command is available in version `0.2.16`.

**Comment by zachjweiner** [comment]
How would one enable this by default (i.e. after save)?

**Comment by James-Yu** [comment]
The extension receives an overhaul since version `1.0.0`+. You may try it out first and submit new issues if any.

**Comment by jabooth** [comment]
Yeah @zachjweiner I'm not clear what you are asking for here, I believe this should now be the current behaviour. To be clear, each time you change file we reassess what the root tex file should be, and if we have nothing else to go on we would select the current tex document, so what you ask for should work? Is it not doing that? If so a concrete example would be very helpful, but please do so in a new issue.

**Comment by zachjweiner** [comment]
I'm sorry, I was doing something stupid and couldn't tell that it was my fault rather than the extension. Working great, thank you so much.
