### ISSUE TITLE
Error in PDF viewer after "LaTeX Workshop: view PDF file in new tab"

### ISSUE THREAD

**Issue by lmdehaas** [James-Yu/LaTeX-Workshop#180]
When trying to view PDF in new tab (ctrl+alt+T on Mac) after building, I get the following error in the PDF viewer:
 
>PDF.js v1.5.188 (build: 0e2d50f)
>Message: file origin does not match viewer's

**Comment by James-Yu** [comment]
Full LaTeX Workshop extension log is required. It can be accessed from `Output` -> `LaTeX Workshop`.

**Comment by lmdehaas** [comment]
I am sorry, it seems to
