### ISSUE TITLE
PDF Viewer broken when returning from suspend

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1804]
When coming back from suspend, the internal PDF viewer does not update anymore and `synctex` (both forward and backward) does not work either. The same happens when using a browser (Chrome) to view the PDF, except that refreshing the page makes everything work fine again.

@chaselweng also reported a similar issue in [1304](https://github.com/James-Yu/LaTeX-Workshop/issues/1304#issuecomment-553230764)

 - OS: MAC OS X Mojave
 - VS Code version: 1.40.0
 - Extension version: 8.3.1

Does anyone experiment this issue also under Windows or Linux?

**Comment by trevorgunn** [comment]
I'm not seeing this behaviour on Linux.

**Comment by jlelong** [comment]
It seems to be fixed by vscode 1.40.1 under Mac OS X.

**Comment by chaselweng** [comment]
Not really, I still encounter the same problem after updating to 1.40.1. :(

**Comment by vitosamson** [comment]
I'm also still seeing this issue after updating to 1.40.1 on Mojave.
