### ISSUE TITLE
\providecommand breaks mathjax preview

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#1805]
It seems that `\providecommand` pollutes the preview rendered by Mathjax. This is related to @carmo-lucas' comment in [856](https://github.com/James-Yu/LaTeX-Workshop/issues/856#issuecomment-553638154)

Consider
```latex
\documentclass[11pt]{article}
\usepackage{amsmath,amsfontsamssymb}
\usepackage[utf8]{inputenc}
\usepackage{t1enc}

\providecommand{\E}{{\mathbb E}}
\newcommand{\cf}{{\mathcal F}}

\begin{document}
$X$
\end{document}
```
Then preview yields

<img width="242" alt="Capture d’écran 2019-11-14 à 08 51 25" src="https://user-images.githubusercontent.com/2910140/68837015-f8bcdf80-06bb-11ea-93e4-5584200543d4.png">

Replacing `\providecommand` by `\newcommand` yields the correct preview

<img width="224" alt="Capture d’écran 2019-11-14 à 08 52 16" src="https://user-images.githubusercontent.com/2910140/68837094-243fca00-06bc-11ea-8e69-a1ccb8170f60.png">

There are two ways to handle this
1. Ignore `\providecommand`  definitions
1. Turn `\providecommand` definitions into `\newcommand` definitions when sending the preamble to mathjax

Any comments?

**Comment by tecosaur** [comment]
Hmm. This is a tricky one. Personally I think the benefits from turning `\providecommand` into `\newcommand` outweigh the drawbacks.

**Comment by carmo-lucas** [comment]
I'm using someone else's .sty file so turning `\providecommand` to `\newcommand` could be problematic.

I fixed it by setting `"latex-workshop.hover.preview.newcommand.parseTeXFile.enabled"` to false.
Not a perfect solution but it works for what I need.

**Comment by jlelong** [comment]
I was perhaps not clear. The translation from `\providecommand` to `\newcommand` would be achieved on the fly by the extension. In no way, would the `.tex` or any other included files be modified.

**Comment by trevorgunn** [comment]
For reference: `\providecommand` acts as `\newcommand` but only creates a new alias if the alias doesn't already exist. So we should be able to achieve the same behaviour by simply passing all the `providecommand`'s to MathJax first (as `newcommand`'s). That way if there was a `newcommand` before the `providecommand` it will be the `newcommand`'s definition that is used.
