### ISSUE TITLE
Manipulating elements in the Outline

### ISSUE THREAD

**Issue by kurisu-gh** [James-Yu/LaTeX-Workshop#1806]
**Is your feature request related to a problem? Please describe.**
Some times refactoring/reorganizing the sections of a document is necessary and it can be quite troublesome for large documents with many sections/chapters/sub-sections. 

**Describe the solution you'd like**
An intuitive way to manipulate the documents elements in the Outline panel.
For example:
* Drag-and-drop one element (e.g. sub-section) outside of its parent section into another section
* Drag-and-drop to re-order your document elements or change their hierarchy level
* Cut/copy/paste/delete elements directly in the Outline panel
* Select multiple document elements for cut/copy/paste/delete, hierarchy promotion/demotion
* A mechanism to filter out elements in the Outline panel by hierarchy level (e.g. show only sub-sections) or by keyword

**Describe alternatives you've considered**
I have tried both [TexStudio](https://www.texstudio.org/) and [TeXlipse](https://projects.eclipse.org/proposals/eclipse-texlipse). They both have outline/structure editing feature to some extent as can be seen in these screenshots for [TexStudio (structure panel)](https://i.imgur.com/onU7YdK.png) and [TeXlipse (outline panel)](https://i.imgur.com/ZOyEBnj.png). TeXlipse actual outline panel capabilities are described [here](http://texlipse.sourceforge.net/manual/outline.html). TeXlipse comes close in the functionality I like but I don't like using the Eclipse IDE. 

Currently, I'm using TexStudio but the text editor itself is very basic and lacks a proper dark theme. All the shortcuts, snippets, table generating functions are very useful though.

I'm currently checking out LaTeX-Workshop+VSCode to see if it is a good alternative for me.

**Additional context**
See screenshots above.

**Comment by jlelong** [comment]
Unfortunately, vscode's outline panel is read-only and does not allow any kind of drag-and-drop manipulation. We cannot control this inside the extension
