### ISSUE TITLE
Auto-closing \(, \[ and \{

### ISSUE THREAD

**Issue by abccsss** [James-Yu/LaTeX-Workshop#1807]
**Is your feature request related to a problem? Please describe.**
When I type in `\{`, the editor auto-closes the bracket like `\{}`. I have to continue to enter `\` so that it becomes `\{\}`, and go back to type in the stuff between the brackets. If I entered `\{\}` altogether, auto-closing would make it `\{\}}` which I don't want.

**Describe the solution you'd like**
When the user types in `\(`, `\[` or `\{`, auto-close like `\(\)`, `\[\]`, or `\{\}`.

**Describe alternatives you've considered**
Disable auto-close for `\(`, `\[` and `\{`.

**Additional context**
None

**Comment by jlelong** [comment]
This is actually the way it works. When you type `\(`, the editor renders `\()` and it triggers a snippet, you just need to accept it using `TAB` or `ENTER` depending on your vscode configuration

<img width="659" alt="Capture d’écran 2019-11-14 à 18 09 42" src="https://user-images.githubusercontent.com/2910140/68879647-0c8f3280-070a-11ea-9c48-82f542f5c711.png">

**Comment by tobiasdiez** [comment]
This is a workaround, however, it requires that the user presses `tab` after typing `\(`. It would be nice if typing `\(` automatically expands to `\( | \)` (`|` marks the cursor). A bit like typing `(` automatically expands to `(|)` without the need of an additional `tab`.
