### ISSUE TITLE
Won't enable shell escape through magic argument

### ISSUE THREAD

**Issue by tmacha** [James-Yu/LaTeX-Workshop#1810]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
Despite adding '--shell-escape' to the Magic Arguments, an error will show when compiling the .tex file at the \includesvg command, stating that shell escape is not enabled   

**To Reproduce**
1. Go to 'Settings'
2. Navigate to Latex-Workshop > Latex > Magic: Args
3. Add '--shell-escape' in front of '%DOC%'
4. Add '\setsvg{inkscape=inkscape -z -D} in the preamble
5. Add '\includesvg{<insert svg filename without extension here>} in document section

**Expected behavior**
LaTeX will automatically call Inkscape to export svg figure to *.pdf_tex 

**Logs [Required]**
Latexmk: This is Latexmk, John Collins, 18 June 2019, version: 4.65.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  --max-print-line=10000 -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="d:/GitHub/diplom"  "d:\GitHub\diplom\diplom.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7250 64-bit)
entering extended mode
(d:/GitHub/diplom/diplom.tex
LaTeX2e <2019-10-01> patch level 3
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/10/25 v1.4k Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo")) ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amstext.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsgen.sty")) ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsbsy.sty") ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsopn.sty")) ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\graphicx.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\keyval.sty") ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\graphics.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\trig.sty") ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-cfg\graphics.cfg") ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-def\pdftex.def"))) ("C:\Program Files\MiKTeX 2.9\tex/latex/svg\svg.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/koma-script\scrbase.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/koma-script\scrlfile.sty")) ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifpdf.sty" ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\iftex.sty")) ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifluatex.sty") ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifxetex.sty") ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\pdftexcmds.sty" ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\infwarerr.sty") ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\ltxcmds.sty")) ("C:\Program Files\MiKTeX 2.9\tex/latex/tools\shellesc.sty") ("C:\Program Files\MiKTeX 2.9\tex/latex/trimspaces\trimspaces.sty")) ("C:\Program Files\MiKTeX 2.9\tex/latex/xcolor\xcolor.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-cfg\color.cfg")) ("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\transparent.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\auxhook.sty"))

Package svg Warning: Setting the executable and associated options
(svg)                for Inkscape should be done with options
(svg)                `inkscapeexe=inkscape'
(svg)                and `inkscapeopt=-z -D'.
(svg)                Nevertheless, this was done by now anyway on input line 10.

Package svg Warning: The key `svgpath' is deprecated. It's recommended
(svg)                to use `\svgpath' instead on input line 10.

(d:/GitHub\diplom\diplom.aux) ("C:\Program Files\MiKTeX 2.9\tex/context/base/mkii\supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\epstopdf-base.sty" ("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\grfext.sty" ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\kvdefinekeys.sty")) ("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\kvoptions.sty" ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\kvsetkeys.sty" ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\etexcmds.sty")))) [1{C:/Users/TobiasMacha/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]

LaTeX Warning: No positions in optional float specifier.
               Default added (so using `tbp') on input line 21.

Package svg Warning: You didn't enable `shell escape' (or `write18')
(svg)                so it wasn't possible to launch the Inkscape export
(svg)                for `images/drawing.svg' on input line 23.

d:/GitHub/diplom/diplom.tex:23: Package svg Error: File `drawing_svg-tex.pdf' is missing.

See the svg package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.23     \includesvg{drawing}
                             

d:/GitHub/diplom/diplom.tex:23: Package svg Error: File `drawing_svg-tex.pdf_tex' is missing.

See the svg package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.23     \includesvg{drawing}
                             
[1] (d:/GitHub\diplom\diplom.aux)

LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

 )
(see the transcript file for additional information)<C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmbx12.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmex10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmmi10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmmi7.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr12.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr17.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr7.pfb>
Output written on d:/GitHub\diplom\diplom.pdf (2 pages, 79227 bytes).
SyncTeX written on d:/GitHub\diplom\diplom.synctex.gz.
Transcript written on d:/GitHub\diplom\diplom.log.
Latexmk: References changed.
Latexmk: Log file says output to 'diplom.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'd:/GitHub/diplom/diplom.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets

<details>
<summary>LaTeX Workshop Output [Required]</summary>

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

</details>

**Screenshots**
[added '--shell-escape' argument](https://abload.de/img/shell-escape3n2jue.jpg)
[error stating shell escape is not enabled](https://abload.de/img/shell-escape4c6k38.jpg)

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.40.1
 - Extension version: 8.3.1

**Are you using LaTeX Workshop with VS Code Remote?**

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Additional context**

**Comment by James-Yu** [comment]
https://github.com/James-Yu/LaTeX-Workshop/issues/1147

https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk
