### ISSUE TITLE
Add a time-to-settle before building based on filesystem changes.

### ISSUE THREAD

**Issue by WeaverThree** [James-Yu/LaTeX-Workshop#1811]
**Is your feature request related to a problem? Please describe.**
On windows, running git commands in Cygwin can cause Latex Workshop to start rebuilding before the git process finishes, and then the git process fails to replace a file because it's locked by the compilation process. (Windows locks files for reading a lot harder than Linux...)

Also sometimes I'd like to save multiple interdependent tex files before a build starts.

**Describe the solution you'd like**
A file-monitoring time-to-settle or quiescence period option in the configuration. E.g., "if a file change is detected, wait until no file changes are detected for this many ms before starting a build."

**Describe alternatives you've considered**
"Build only when file saved by vscode" would be an acceptable alternative, allowing you to still build on ctrl-s but not when external stuff modifies files.

**Comment by tamuratak** [comment]
Closed by #1949.
