### ISSUE TITLE
@jimp and jimp are buffing the extension package size

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#1813]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

The current package is approx. 16MB, which is a 60% increase compared to several minor versions before. I've checked the increase and found that `@jimp` and `jimp` packages contributes to a major portion of the increase. I also noticed that there are a dozen of different plugins in `@jimp` that we seems not use (except for `scale` in `graphicsscaler_worker.ts`). Is it possible to ignore some of these plugins are reduce the package size?

### To Reproduce

1. `npm run release`
2. See the size and open the package with `7z`/`zip`.

### Expected behavior

Hmm. A smaller package?

## Logs [Required]

Unrelated

### LaTeX Workshop Output [Required]

```
To access the log, click the 'problems' icons on the statusbar, select 'OUTPUT', then select 'LaTeX Workshop' from the dropdown menu on the right.

Unrelated
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

Unrelated
```

## Desktop [Required]
 - Extension version: 8.4.0

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Comment by James-Yu** [comment]
@tamuratak may you please take a look? Thx!

**Comment by tamuratak** [comment]
I have tried in 315775eae550dad32d04ee71584ed6312f26d235. It did not reduce the size of the package that much.
