### ISSUE TITLE
option to open on the left for view.pdf.tab.useNewGroup

### ISSUE THREAD

**Issue by vogler** [James-Yu/LaTeX-Workshop#1819]
If `latex-workshop.view.pdf.tab.useNewGroup` is true, it opens a new editor group on the right.
Usually I want it on the left though since more of the editor text is then closer to the middle of the screen.
I could move the editor group to the left every time, but it would be nicer to have an option `latex-workshop.view.pdf.tab.group` with values `new_left, new_right, current` or just a new option to specify left/right if `useNewGroup` is true.

**Comment by jlelong** [comment]
This is far more delicate as it looks like. We rely on [`vscode.ViewColumn`](https://code.visualstudio.com/api/references/vscode-api#ViewColumn) to place the viewer tab. We use the `Beside` position to open the viewer tab in a group on the right but the API does not enable use to open a group on the left. I believe it cannot only be done by 

1. Creating a new group on the right
1. Moving all the editors of the current group to the next one
1. Opening the viewer in the current group

The problems arise in 2. as there is no way to have access to the list of opened editors. So I am afraid we cannot implement the open on the left feature.

**Comment by vogler** [comment]
2 and 3 are solved by `workbench.action.moveActiveEditorGroupRight`. That's what I used so far to swap sides manually.

**Comment by jlelong** [comment]
Thanks for the tip.

**Comment by vogler** [comment]
An already created group should be reused for adding a new preview instead of creating another group.
Seems like this is the case for `right`, but fails for `left`.
Example: I work on a subfile with code right, preview left. I switch to another subfile and open the preview. It creates another editor column in the middle instead of appending the preview to the left column and focusing it.

If we know we have two columns with the preview on the left, it could `swap, open right, swap`.
