### ISSUE TITLE
LaTeX Problem Matcher Export

### ISSUE THREAD

**Issue by atmafox** [James-Yu/LaTeX-Workshop#1824]
I am writing custom tasks to do various build and other steps (such as compressing the PDF) as well as to vary what I build.  Presently I have to write my own problem matcher.

I would like to have the LaTeX Workshop problem matcher/etc exposed in such a way that I can use it from tasks.

I can write my own problem matcher, but given that LaTeX Workshop's works well, I am disinclined to on the basis of DRY.

EDIT: It would be nice if I could also trigger a PDF reload from a task.

**Comment by jlelong** [comment]
To trigger a PDF reload, you can call the command `latex-workshop.refresh-viewer`.

**Comment by jlelong** [comment]
Looking at VSCode's documentation, defining a [Problem Matcher](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) cannot only be done as part of the `package.json` file by directly specifying the regex. It does not seem possible to export a problem matcher defined as internal typescript functions.

Maybe you can have a look at [how to use an external build command](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#external-build-command). Note also that you can define your own recipes with some extra tools inside and our problem matcher will be used.

I am closing this feature request as VSCode's API does not seem to be rich enough for doing this.
