### ISSUE TITLE
Dark background in the pdf viewer

### ISSUE THREAD

**Issue by id0158** [James-Yu/LaTeX-Workshop#1825]
Would it be possible to provide an option or (even better) follow the editor theme for the background color in the pdf viewer ?

By _pdf viewer background_ I mean the area around the document and not the background of the document itself.
It's not so impactful for a regular document, but very useful for Beamer (see screenshots below).
Actual settings provide a (very) light background independently of the editor theme and I did not find an option to change this. 

![VSCode](https://user-images.githubusercontent.com/14804964/69366968-a66d5700-0c97-11ea-9fd7-ebf66b31674f.png)
![Firefox](https://user-images.githubusercontent.com/14804964/69366977-aa00de00-0c97-11ea-8c3b-c732de21893e.png)

Firefox pdf viewer background is more consistent with a dark mode, even if for them it's always dark :smile: 

Thank you otherwise for the great work with this extension !

**Comment by tylerliu1998** [comment]
You can invert both the area around the document and the background of the document. Why do you want to invert only one of them?
![image](https://user-images.githubusercontent.com/48684632/69600817-0293fa80-104d-11ea-9b8b-38adb2be3d25.png)

**Comment by phdoerfler** [comment]
I think they want the area of the viewer that is **not** covered by actual pages and content to be coloured dark

**Comment by tecosaur** [comment]
@jlelong do you know if it would be possible to pass the css variables from the outer iframe to the inner iframe (with the PDF viewing method we use), or just use the outer iframe?

That way we could have the pdf viewer match the user's theme, which would be very nice.

**Comment by jlelong** [comment]
Honestly, I do not know if we could achieve this and I am even wondering whether it would be wise to try doing so considering how delicate the viewer may be. Remember the broken links issue #1793 that was cause by badly positioned css.  Detecting the background tone is already quite tricky in mathjax so I do not know how we could do really better here. Suggestions are welcome.

**Comment by id0158** [comment]
Thank you @tylerliu1998 for pointing out this option, I didn't know it exist.
But as @phdoerfler already said, I usually prefer to preserve the original appearance of a document while reducing as much as possible the light around it in the dark mode (at least).
However, `latex-workshop.view.pdf.invert` can be very handy for night editing !

Thank you very much @jlelong for implementing this !
As @tecosaur, I would have preferred that the pdf viewer automatically match the editor theme.

Meanwhile, could it be possible to provide some different predefined background color options for `latex-workshop.view.pdf.tab.backgroundColor`?
Because, if I understand #1843 correctly, it lets you specify a custom background color only int the HTML format.
While already a progress, providing at least two more predefined options (eg. "light" and "dark) could be an appreciable improvement.
These two predefined color options could be hard coded to mach the default VSCode dark and light themes.

What are your thoughts about this ?

**Comment by tecosaur** [comment]
Hmmm. One janky solution that comes to mind (could be worth having until we think of a better one) would be to have a JSON object that represents the colour of main components, which users can populate by using their current theme and a colour picker. e.g.
```json
"latex-workshop.view.pdf.colors: {
  "background": "#123456",
  "sidebar": "#123456",
  "sidebarFocus": "#123456",
  "text": "#123456"
}

**Comment by jlelong** [comment]
@id0158 In `latex-workshop.view.pdf.tab.backgroundColor`, you can specify colours in any CSS understandable format: it can be hexadecimal code, `rgb(r,g,b)`, or even a colour name. Note that there are plenty of web site to found those codes.

@tecosaur for the moment, the background colour is set in the form `document.querySelector('#viewerContainer').style.background`. I did not find a way to directly pass a block of css. The viewer frame is really complicated with several html elements created on the fly by javascript code so this is particularly difficult to figure out how to tweak the css.
