### ISSUE TITLE
Tool: forward output to file

### ISSUE THREAD

**Issue by SpineEyE** [James-Yu/LaTeX-Workshop#1828]
**Is your feature request related to a problem? Please describe.**
I want to execute `detex` in a recipe but it always outputs to `stdout` and I don't see a way to forward the output into a file in LaTex-Workshop. 

**Describe the solution you'd like**
Possibility to redirect a program's output to file. [It's supported](https://code.visualstudio.com/docs/editor/debugging#_redirect-inputoutput-tofrom-the-debug-target) by VSCode debug configurations.

**Describe alternatives you've considered**
I tried to configure "> file.txt" as an argument but it didn't work. Supposedly it was added as an argument to the program, not to bash. I guess I could write a wrapper script.

**Comment by jlelong** [comment]
Unfortunately, I do not think we can do much about it. Each tool of a recipe is run via a `spawn` call which expects an executable plus every extra arguments as separate tokens. We do not pass a full command line to some `exec` function. 

I guess you would rather use VSCode tasks mechanism for this.
