### ISSUE TITLE
I want to edit vscode tab IP,alter a specific IP, can you help me?

### ISSUE THREAD

**Issue by Mowar** [James-Yu/LaTeX-Workshop#1829]
I try to use Latex-workshop in code server. my code server is on the AWS Cloud. I finish compile my .tex file. but I show vscode tab, I get a problem: Localhost rejected our connection

**Comment by tamuratak** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#code-server-is-not-supported
