### ISSUE TITLE
cmd+shift+B not "building"

### ISSUE THREAD

**Issue by nicofranzp** [James-Yu/LaTeX-Workshop#1830]
I've always compiled my latex documents using the shortcut cmd+shift+B. A couple of weeks ago  I started to get the message "Tasks are only available on a workspace folder" or (if I'm in a WS) "No build task to run found ..." .
If I use the build buttons provided by the extension, everything works fine. Any ideas on what could this be?

**Comment by jlelong** [comment]
The shortcut provided by the extension for building is `cmd+alt+B`.

**Comment by nicofranzp** [comment]
Thanks!! It seems my --- now I remember --- customized key map was overriden at some point
