### ISSUE TITLE
Support XeLatex in the live compilation view

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [James-Yu/LaTeX-Workshop#1833]
**Is your feature request related to a problem? Please describe.**
Please add xelatex support to the live compilation view, not just pdflatex and lualatex support

**Additional context**
I tried adding the regexp in checkStdoutForInfo myself (i.e. replacing the code there by the following):
```
        const hardcodedRulesPageProducing = ['pdflatex', 'pdftex', 'lualatex', 'xelatex']
        const hardcodedRulesOther = ['sage']

        // A rule consists of a regex to catch the program starting and a boolean of whether
        // or not the program produces pages in the PDF
        // TODO: Add more rules
        const rules = {
            pdfTeX: [ /This is pdfTeX, Version [\d.-]+[^\n]*$/, true ],
            BibTeX: [ /This is BibTeX[\w.\- ",()]+$/, false ],
            Sage: [ /Processing Sage code for [\w.\- "]+\.\.\.$/, false ],
            LuaTeX: [ /This is LuaTeX, Version [\d.]+[^\n]*$/, true ],
            XeTex: [ /This is XeTex, Version [\d.-]+[^\n]*$/, true ]
        }
```
However that was not successful, and I don't understand the VSCode extension internals at all (nor do I write Javascript), so I don't know what's wrong with my attempt.

**Comment by trevorgunn** [comment]
I believe the issue is you wrote `XeTex` instead of `XeTeX` in your regex (it's case-sensitive).

**Comment by Cornelius-Riemenschneider** [comment]
Thank you, I thought I copy-pasted the string, but apparently not. That was it!
I opened a PR with my changes.
