### ISSUE TITLE
Cannot use right click in editors

### ISSUE THREAD

**Issue by tylerliu1998** [James-Yu/LaTeX-Workshop#1834]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

In the latest version of VSCode - Insider, it seems right-clicking the mouse would not work in any editors or terminals after enabling LaTeX Workshop. Yet it still works in the activity bar and panels. I have both the Insider and Stable release of VSCode installed with the same version of LaTeX Workshop. The Stable version works fine.

Platform: Mac OS X
VSCode Version: 1.41.0-insider (Have problem), 1.40.1 (No problem)
LaTeX Workshop Version: 8.4.1 (both)

**Comment by jlelong** [comment]
This is mostly related to a change in VSCode Insider. Can you post the full logs of the extension?

**Comment by tylerliu1998** [comment]
Where can I find the full logs? There is nothing strange in the OUTPUT console for LaTeX Workshop.

**Comment by jlelong** [comment]
![Capture d’écran 2019-11-26 à 07 37 37](https://user-images.githubusercontent.com/2910140/69605262-f8a7d280-101f-11ea-95c8-4d57fbda1f1f.png)

**Comment by tylerliu1998** [comment]
![image](https://user-images.githubusercontent.com/48684632/69607725-d6827480-1060-11ea-9288-fdd4fc67f424.png)
I suppose there is no help?

**Comment by jlelong** [comment]
Indeed. I do believe the issue is on VSCode's side. 
Maybe we could just wait for the next Insider release and see if it is fixed.

**Comment by tylerliu1998** [comment]
OK. I also posted this issue in the repo of VSCode but they said that I should post it here. Maybe we could just wait for a while for the next release.

**Comment by tamuratak** [comment]
Related to microsoft/vscode/issues/85576. Reported in microsoft/vscode/issues/85671 again.
