### ISSUE TITLE
Surrounding macro for the itemize environment

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [James-Yu/LaTeX-Workshop#1837]
Say we have a list of several items:
```
- Foo
- Bar
- Baz
```
I'd like to be able to select that text, and then use the "[surround and apply macro](https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#surrounding-text)" feature to convert that into a list, e.g.:
```
\begin{itemize}
\item Foo
\item Bar
\item Baz
\end{itemize}
```
Is that available already? if not, how can I define it myself?

**Comment by jlelong** [comment]
No this is not available. There is no easy way for you to automatically achieve this.
I would go for

1. Replace `-` by `\\item` inside the selection
1. Call `Surround/wrap selection with \begin{}...\end{}`.

The companion extension [LaTeX-Utilities](https://github.com/tecosaur/LaTeX-Utilities) might be interested in developing such a feature.
