### ISSUE TITLE
Parse labels as symbols

### ISSUE THREAD

**Issue by brunnerh** [James-Yu/LaTeX-Workshop#184]
Ideally it should be possible to:

- Go to symbol definition from the various `\ref` instances.
- Invoke _rename symbol_ command in `\label` and all `\ref` occurrences change accordingly.
- Invoke _go to symbol_ anywhere to jump to a given label.

**Comment by James-Yu** [comment]
It involves a overhaul of the auto-complete system, which is of relatively low priority. However, it WILL come in the future, not too far away.

**Comment by brunnerh** [comment]
It would actually also be nice to have the various TOC entries as code block symbols (not sure what they are called under the hood). I noticed that in markdown files the various headings (e.g. `# Title`) appear in the symbols index with a `{}` icon.

**Comment by James-Yu** [comment]
`Rename symbol` may not be implemented, as the extension cannot properly detected text token environment (e.g., text, math mode, or in curly brackets after `\ref`). Meanwhile, the others are implemented.

**Comment by brunnerh** [comment]
Nice, thanks!
