### ISSUE TITLE
Close Environment Command fails

### ISSUE THREAD

**Issue by HannesFunk** [James-Yu/LaTeX-Workshop#1848]
### Description
Closing an open environment fails in the following setting: whenever I try to close an environment in a non-indented line, the command fails with the error "Running the contributed command: 'latex-workshop.close-env' failed."
(Note: The environment is closed just fine whenever there is a leading whitespace in the position where close-env is to be executed)

### To reproduce:
Type \begin{foo} on some line, move to the beginning of some line below and run "Close Current Environment". Error.

The LaTex-Workshop Log only says "CloseEnv command invoked".
Desktop: Windows 10, VS Code 1.40.2, Extension 8.4.2 (also reproduced under Linux Mint)

### Additional Remark
I've already had a look into the source code and the problem seems to be in `envpairs.ts`, line 279 which reads
> const endIndentRange = new vscode.Range(endStartOfLine, curPos.translate(0, -1))

This fails when executed at current character position 0 (which kind of makes sense to me). Moreover, if I just remove the translate-command, everything works just fine, so I'm not sure why it is even there tbh.

**Comment by jlelong** [comment]
The `translate(0, -1)` purpose was to insert the `close` statement before the cursor instead of at the cursor position. I do admit that it was a strange idea (of mines). This is fixed.
