### ISSUE TITLE
Equation preview gives TeX parse error: MathJax maximum macro substitution count exceeded; is there a recursive macro call?

### ISSUE THREAD

**Issue by LeCyberDucky** [James-Yu/LaTeX-Workshop#1849]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Math preview is broken in version 8.4.2. I have tried switching between versions 8.4.1 and 8.4.2 several times. It works fine in 8.4.1. In version 8.4.2, however, instead of math preview, I get the following error in the console: 

![image](https://user-images.githubusercontent.com/19520383/69937003-b415ae80-14d9-11ea-8bbd-aa2b2779e922.png)

### To Reproduce

1. Toggle developer tools
2. Hover over equation
3. See error

### Expected behavior

Math preview should work just like in version 8.4.1. 

## Logs [Required]

I am not entirely sure which logs you mean/where to find them. Could you expand on this, if you think they would be helpful? 

### LaTeX Workshop Output [Required]

```
[07:59:25] Error when MathJax is rendering 
\newcommand\newcommand\newcommand\newcommand\begin{equation}
    \begin{gathered}
        \min\limits_\theta \phi(\theta) \\
        \phi(\theta) = \frac{1}{2} \sum\limits_{i = 1}^n ||y_i - \hat{y}_i||_2^2 = \frac{1}{2} \sum\limits_{i = 1}^n ||y_i - f(\theta; x_i)||_2^2
    \end{gathered}
\end{equation}
[08:01:37] LOG command invoked.
```

### Developer Tools Console [Required]

```
TeX parse error: MathJax maximum macro substitution count exceeded; is there a recursive macro call?
```

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.40.2
 - Extension version: 8.4.2

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Maybe it would be helpful to see which packages I'm including? 

```
\usepackage[a4paper, total={6in, 9in}]{geometry} % Paper and margins size

\usepackage{amssymb} % Nicer mathematical symbols
\usepackage{amsmath} % Referencing equations with parenthesis \eqref

\usepackage{graphicx} % Adding illustrations

\usepackage{float} % Something related to placing figures and stuff where you want it, I think

\usepackage{booktabs} % Table styling

% Typesetting matlab code
\usepackage{listings}
\usepackage{xcolor}
\usepackage[numbered, framed]{matlab-prettifier}
\lstset{style=Matlab-editor}

% Make references clickable. Hide ugly borders around clickable references
\usepackage[hidelinks]{hyperref}

% Advanced table stuff
\usepackage{hhline}
\usepackage{multirow}

% Typesetting algorithms and pseudocode
% https://tex.stackexchange.com/questions/1375/what-is-a-good-package-for-displaying-algorithms
\usepackage{algpseudocode,algorithm,algorithmicx}
\newcommand*\Choose[1]{\textbf{Choose} #1;}
\newcommand*\Set[1]{\textbf{Set} #1;}
\newcommand*\RepeatUntil[1]{\textbf{repeat} until #1}
\newcommand*\EndRepeat{\textbf{end(repeat)}}
```

**Comment by jlelong** [comment]
The syntax of `newcommand` is

    \newcommand{<name>}[<args>]{ <code> }

with an optional `*`. Note the pair of curly braces around `<name>`. These are missing is your `.tex` and are the culprits for the `\newcommand\newcommand\newcommand\newcommand` in the logs.
