### ISSUE TITLE
Hide LaTeX Outline

### ISSUE THREAD

**Issue by christianmalek** [James-Yu/LaTeX-Workshop#185]
It really annoys me that that every VS Code Project shows this:

![image](https://user-images.githubusercontent.com/2873986/27901440-6b86deac-6232-11e7-848b-acb58ceeb55f.png)

Could you please add a option to hide/show it?

**Comment by James-Yu** [comment]
Duplicate of #178 . Wait for Microsoft to release the API.

**Comment by christianmalek** [comment]
@James-Yu Thanks for your fast response.
