### ISSUE TITLE
Compilation issue (vscode version related?)

### ISSUE THREAD

**Issue by MagicLegend** [James-Yu/LaTeX-Workshop#1850]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Biber (?) issues using a newer vscode (I think :-)). The compiler just loops 5 times (or more) with a bunch of errors without errors in the log, I suspect related to biblatex or something. The PDF sometimes comes out as corrupted, even though workshop reports as being done. It should be noted that after a few runs, sometimes I can see that there is a complete PDF file, and no rerun would be necessary. It still tries to re-run.

*However*, on another VM (Kali 2019.2), with VSCode Version: 1.39.2 (further info below), the exact same source works just fine. The only difference is the VSCode version (and the OS, tho both a Linux flavour, and since my compilation is within Docker anyway I don't think this matters). Did something within LaTeX Workshop / VSCode break between v1.39.2 and v1.40.2? LaTeX Workshop version is identical (8.4.2), and other extensions are almost identical (there is actually more installed on the Kali VM).

Further info of the KALI VSCode:
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Noe.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux 64 5.2.0-kali2-amd64

### To Reproduce
If necessary I will spend some time tonight creating a MWE. I just wanna know if it could be a bug. However, it should be noted that I can't reproduce this issue on an older VSCode.

### Expected behavior

A properly compiled LaTeX document :-)

## Logs [Required]
[Logs gist](https://gist.github.com/MagicLegend/0c366dbdbfd93f2e723ac687fd22f4bf)

### LaTeX Workshop Output [Required]

To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.
[Workshop output gist](https://gist.github.com/MagicLegend/aa8501f4c9eaf4c45181e96d75498b12)

### Developer Tools Console [Required]

To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

Nothing really.

## Desktop [Required]
 - OS: Ubuntu 19.10
 - VS Code version: 1.40.2
 - Extension version: 8.4.2

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-25-generic snap

### Are you using LaTeX Workshop with VS Code Remote?

Partly

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

Not using remote, but the (legacy?) docker support (has always worked like a charm)

### Additional context

settings.json:

```
{
    "workbench.iconTheme": "vscode-icons",
    "latex-workshop.docker.image.latex": "koppor/texlive",
    "latex-workshop.docker.enabled": true,

    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
              "-synctex=1",
              "-interaction=nonstopmode",
              "-file-line-error",
              "-shell-escape",
              "-pdf",
              "%DOC%"
            ]
          },
          {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
              "-synctex=1",
              "-interaction=nonstopmode",
              "-file-line-error",
              "-shell-escape",
              "%DOC%"
            ]
          },
          {
            "name": "biber",
            "command": "biber",
            "args": [
              "%DOCFILE%.bcf"
            ]
          },
    ],

    "latex-workshop.latex.recipes": [
        {
          "name": "latexmk",
          "tools": [
            "latexmk"
          ]
        },
        {
          "name": "pdflatex -> biber -> pdflatex*2",
          "tools": [
            "pdflatex",
            "biber",
            "pdflatex",
            "pdflatex"
          ]
        }
      ],
      "latex-workshop.view.pdf.viewer": "tab"
}
```
Latexmk is used here, as shown in the logs.

Document preamble:
[Preamble gist](https://gist.github.com/MagicLegend/bb01563904e45e9cc805581ba1211807)

**Comment by jlelong** [comment]
From the extension logs: `pdflatex: Command for 'pdflatex' gave return code 256`.  Note also that some errors are reported in your TeX compiler logs
````
<to be read again> 
                   \relax 
l.133 \newpage
````

This is a compilation issue and not related to the extension. Please compile your file by hand with the same compiler and look carefully at the logs.

**Comment by MagicLegend** [comment]
So if this is a compilation issue; why does it work in the other VM, since compilation is done within the same docker image? Comparing the log files between [the working compilation](https://gist.githubusercontent.com/MagicLegend/daaec497c589cf4a5fdcbf8129abe5ef/raw/fdb325f360ee08b0d6e92d756e4003bd07421339/latexworkshopcompile_kali.log) vs the [non working compilation](https://gist.githubusercontent.com/MagicLegend/0c366dbdbfd93f2e723ac687fd22f4bf/raw/34c898a0c8525ae01e05d439f013e9a70231faf5/latexworkshopcompiler.log) results in an identical log file; even though one of the two is clearly misbehaving. The error you list is in both logs; so that's clearly not the cause of my issues. Again, the only relevant difference is the vscode version; which makes me think that it is in fact an issue with the extension.

Perhaps switching to the new VS Code remote could fix this?

**Comment by jlelong** [comment]
To make it clear, the extension does not interfere with the compilation itself. It only spawns one process by recipe tools. In your case a single `latexmk` process is spawn and it does not end with the `0` return code, which means an error has occurred. `latexmk` says
````
SyncTeX: Can't rename data_analysis_report.synctex(busy) to data_analysis_report.synctex.gz
Latexmk: Found input bbl file 'data_analysis_report.bbl'
Latexmk: References changed.
Latexmk: References changed.
Latexmk: Log file says output to 'data_analysis_report.pdf'
Latexmk: Found biber source file(s) [bibliography.bib data_analysis_report.bcf]
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
````
The `synctex` message looks weird.  
I would be really surprised if any of this has anything to do with VSCode's version.
