### ISSUE TITLE
Implement a detex command

### ISSUE THREAD

**Issue by Fischer96** [James-Yu/LaTeX-Workshop#1854]
**Is your feature request related to a problem? Please describe.**
Latex Utilities has the possibility to show the word count on a .tex file. I also want to see paragraph, characters and maybe some other metrics which are calculated by other tools.

**Describe the solution you'd like**
Add a Detex-Command to the command palette so you get your .tex file in a new file tab without any latex commands in it. Just pure text.

**Describe alternatives you've considered**
Currently using opendetex or textidote but a direct implemenation would be more useful.

**Additional context**
/

**Comment by jlelong** [comment]
Considering word count has been moved to Latex Utilities, you should file your feature request there.

**Comment by jdoubleu** [comment]
I'd still like to see (official) support for `detex`, just for the raw text output of it.

I tried using detex through `latex-workshop.latex.tools` . Unfortunately, `detex` has no output parameter, like `latex -outdir=...` for example, but just prints everything to `stdout`.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
