### ISSUE TITLE
LaTeXmk recompiles whole project with only small delta

### ISSUE THREAD

**Issue by MarcDirven** [James-Yu/LaTeX-Workshop#1859]
**Is your feature request related to a problem? Please describe.**
Yes, well, sort of. I'm not sure whether this is a problem or my configuration .json is just faulty. Anyhow, if I compile my project whilst having changed only a few characters, the whole file recompiles and takes (because it's 80 pages long) 15 - 30 seconds. Is this normal?

**Describe the solution you'd like**
Maybe it's possible already, but as previously described I do not know how, so this is more of a question really but, how do I enable this sort of makefile looking like structure?

**Describe alternatives you've considered**
I have tried googling to for "`latexmk` recompiles whole file" and equivalents of this, but search results were scarce.

**Additional context**
None really, it's a more of a question rather than a feature.

**Comment by jlelong** [comment]
The extension simply calls `latexmk` and let the tool handle the compilation. It is on `latexmk` to decide what has to recompiled. Try to run `latexmk` from the command line and you will certainly observe the same behaviour. There is nothing we can do from the extension's side.

**Comment by trevorgunn** [comment]
The [tex.stackexchange](https://tex.stackexchange.com/q/8791/136270) has some advice. If you have a question on implementing a specific command line option or something like that in the extension then that would be relevant here.
