### ISSUE TITLE
Build latex project errors

### ISSUE THREAD

**Issue by aviadb** [James-Yu/LaTeX-Workshop#186]
### Description
After installing MikTex + strawberry perl + latexmk.
Running latex workshop ->build latex projects failed with non descriptive errors
such 12/null or 1/null

### How to reproduce

1. 
2. 
3. 

### LaTeX Workshop log messages

<details>
<summary>Log messages</summary>

</details>

**Comment by James-Yu** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/issues/135#issuecomment-300391694 . tldr, `latexmk` problem.

**Comment by aviadb** [comment]
After reading the manual of latexmk, 
I have changed latex-workshop toolchain settings to the following:
`
"latex-workshop.latex.toolchain": [
 {
    "command": "latexmk",
    "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdfxe",
                "-xelatex",
                "%DOC%"
            ]
        }
    ]
`

To use the xelatex engine and render the pdf with pdfxelatex.
Using that combination works perfectly without any errors or warnings.
Maybe filling the default latex workshop toolchain settings with the default latexmk values will help other to play along with those arguments, like -pdf and -latex + providing comments for the available engines.
