### ISSUE TITLE
Viewing PDF Subfile is broken when the subfile is in a subfolder

### ISSUE THREAD

**Issue by hydradon** [James-Yu/LaTeX-Workshop#1860]
**Is your feature request related to a problem? Please describe.**
I have a multi-file project with a main.tex and many subfiles: introduction.tex, methodology.tex, etc.. Whenever I'm on a subfile, after making some edit, I would like to see the change reflected in the PDF. Then, I click View Latex PDF on the sidebar, VSCode then asks me to choose a root file (main or this subfile), after which I choose the subfile. However, VS Code does not display the subfile.pdf.

**Describe the solution you'd like**
When I click View Latex PDF when my focus is on a subfile.tex, I would like it to display subfile.pdf by default.

**Describe alternatives you've considered**
Currently, I have to compile the main.tex to see the main.pdf, which has the change I made in the subfile. This is time-consuming since my project is huge.

**Additional context**

**Comment by jlelong** [comment]
You need to compile the subfile before being able to display it.
See the wiki for more explanations on how we handle the `subfiles` package
- [https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file) item 4
- the associated setting: [`latex-workshop.latex.rootFile.useSubFile`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#latex-workshoplatexrootfileusesubfile)

**Comment by hydradon** [comment]
@jlelong Hi, I have set `latex-workshop.latex.rootFile.useSubFile` this to True.
Also, my current focus is on `methodology.tex`, after clicking Save, auto-build will generate a `methodology.pdf` in the root folder. Then, I click View Latex File, it asks to choose the root file, which I choose the `methodology.tex`. It does not show the pdf, even though the pdf is there in the directory

**Comment by jlelong** [comment]
Unfortunately I cannot reproduce your issue. 
Please post the full logs of the extension. Also what is the file structure of your project, could you make a minimal working example?

**Comment by hydradon** [comment]
@jlelong: Here is my example:

`main.tex` at root folder:

```
\documentclass[conference]{IEEEtran}
\IEEEoverridecommandlockouts

\usepackage{subfiles}
    
\begin{document}

\title{Sample title}
\maketitle
Here is the main file...
\section{Extra Part} \label{sec:extra}
\subfile{section/extra}

\end{document}
```

Here is my `section\extra.tex`:

\documentclass[../main.tex]{subfiles}
\begin{document}
In this section, we describe the extra....
\end{document}

While at this `extra.tex`,  click Build Latex Project > Choose Subfiles packaged root file > Then click View Latex PDF > Choose Subfiles packaged root file

Here, nothing is displayed

**Comment by jlelong** [comment]
This issue comes from the subdirectory `section`. By looking at the logs, it is clear that the `extra.pdf` file is produced in the workspace root directory whereas the viewer looks for it in `section/`. I will look into it. Note that this is why we ask for the logs in the issue template because it helps identifying the issue much faster. Thanks for cooperation

**Comment by hydradon** [comment]
@jlelong thank you for the fix. May I know when this will be released?
