### ISSUE TITLE
Suppress latex warnings

### ISSUE THREAD

**Issue by hookxs** [James-Yu/LaTeX-Workshop#1861]
Please add feature to ignore specific (or all) latex/tex warnings. Some warnings are not important (overfull hbox etc) but are nevertheless displayed using squiggles, popups and highlighted in the minimap, which is distracting and annoying. I could not find any VS Code global setting to ignore existing warnings or pdflatex option not to output warnings.

**Comment by jlelong** [comment]
You can use [`latex-workshop.message.latexlog.exclude`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessagelatexlogexclude).

**Comment by trevorgunn** [comment]
Also `latex-workshop.message.badbox.show` for the overfull hbox warnings specifically.

**Comment by hookxs** [comment]
I didn't know that, thank you.
