### ISSUE TITLE
--shell-escape in the user settings assistant

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [James-Yu/LaTeX-Workshop#1864]
I know there are many issues already on the use of the `--shell-escape` flag, e.g.:

* https://github.com/James-Yu/LaTeX-Workshop/issues/913
* https://github.com/James-Yu/LaTeX-Workshop/issues/1043
* https://github.com/James-Yu/LaTeX-Workshop/issues/1147

They all show how to configure LaTeX Workshop to use this flag in the user settings JSON **file**. 

My question is: is that the only way to configure its use? E.g. does the VSCode user **settings** **assistant** for this extension not have an option where I can include i? 

I mention this mostly because I'm getting started with the extension in general and don't want to mess up its configuration. Thanks!

**Comment by jlelong** [comment]
Unfortunately no. Adding the `--shell-escape` flag can be a bit tricky as you have noticed so this is far too delicate to try to add it automatically on demand.

**Comment by amelio-vazquez-reina** [comment]
QQ @jlelong What's a good reference for configuring `latex-workshop.latex.tools` in VSCode? Any article perhaps in the wiki or issue where these settings are explained / updated over time? Alternatively where would you route people for this type of documentation?

**Comment by jlelong** [comment]
You can have a look at

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes
- https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk
