### ISSUE TITLE
How to change tool "bibtex" to compile the current opened file instead of the  LaTeX root file？

### ISSUE THREAD

**Issue by xinleiyu** [James-Yu/LaTeX-Workshop#1869]
I need to use bibtex to compile the current opened file instead of the LaTeX root file.
Is it possible to get the current opened file name in setting.json?

this is the current bibtex tool. I have no idea to change it.
"latex-workshop.latex.tools": [
     {
        "name": "bibtex",
        "command": "bibtex",
        "args": [
          "%DOCFILE%"
        ],
        "env":{}
    }
]

**Comment by xinleiyu** [comment]
The root file main.tex has two subfiles---chapter1.tex and chapter2.tex.
I need to generate bib for each chapter in my thesis. 
So I wrote a personal script, and using it in terminal or as External build command. It worked.
But I still hope to have a better bibtex tool that the args depends on the current opened file.
Such as, "bibtex chapter1.aux" if use it in chapter1.tex.

**Comment by jlelong** [comment]
Do you mean that you use the `subfiles` package?

**Comment by zepinglee** [comment]
I recommend using `latexmk` which automatically runs `bibtex` on each of your subfiles.

**Comment by jlelong** [comment]
In particular, see Item 4 [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file).

**Comment by xinleiyu** [comment]
> Do you mean that you are using the `subfiles` package?

I am not using the 'subfiles' package. I just use ‘\include’ in the root file to include the other '.tex'.

**Comment by xinleiyu** [comment]
Now, I am using Task.json to run `bibtex` on the current opened file.
It supports variable substitution in Debugging and Task configuration files.
${fileBasenameNoExtension} - the current opened file's basename with no file extension

Does setting.json have similar placeholder？

This is my file Task.json.
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "bibtex current opened file",
      "type": "shell",
      "command": "bibtex ${fileBasenameNoExtension}",
      "problemMatcher": []
    },
    {
      "label": "make my thesis",
      "type": "shell",
      "command": ".\\makethesis.bat thesis",
      "problemMatcher": [],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}

**Comment by jlelong** [comment]
There is no such placeholder in `settings.json`. 
If you want help, please post a minimal example of what you are trying to do because I really do not understand why you want to run `bibtex` on included files.

**Comment by zepinglee** [comment]
> There is no such placeholder in `settings.json`.
> If you want help, please post a minimal example of what you are trying to do because I really do not understand why you want to run `bibtex` on included files.

I guess this is a case of `chapterbib` which facilitates multiple bibliographies.

**Comment by jlelong** [comment]
For sure but I am pretty sure that `latexmk` handles `chapterbib` transparently.

**Comment by xinleiyu** [comment]
> For sure but I am pretty sure that `latexmk` handles `chapterbib` transparently.

Thanks. I will try it.
