### ISSUE TITLE
\begin{env} \end{env} autocomplete snippet broken

### ISSUE THREAD

**Issue by harlecin** [James-Yu/LaTeX-Workshop#188]
Hi, first thanks a lot for your awesome package! (currently writing my Master thesis with it:)

### Description
There is an issue with the \begin{env} \end{env} code snippet.
When I type \begin and accept the autocomplete, the cursor does not mark the default text "env" but rather jumps to the end of "env" so when I want to create e.g. a proof environment it looks like this:
\begin{envproof}
\end{envproof}

### How to reproduce

Start typing \begin and accept autocomplete

### Expected behavior

Behavior should be as with \frac{x}{y}: the default text should be selected an replaced by user input

### Actual behavior

Cursor jumps after default text and therefore default text is not replaced

I use LaTex Workshop 2.10.0

Thx again for your awesome work!

**Comment by James-Yu** [comment]
I cannot reproduce this problem. Here is the screenshot when I press ENTER with the autocomplete:

![image](https://user-images.githubusercontent.com/4210342/28054054-029b6526-6646-11e7-9662-9d272be689a9.png)

**Comment by harlecin** [comment]
Yes, the autocomplete works, but when you start typing it does not replace the "env" part.
Say, I want to have \begin{proof} \end{proof} it will be \begin{envproof} \end{envproof}.
When I try to delete the "env" characters, it only deletes them in the \begin expression and keeps them in the \end expression plus it deletes the right bracket of \begin{} as well.

I am using the VIM plugin, if that makes any difference? But all other latex snippets work fine, say \frac{x}{y} for example

**Comment by James-Yu** [comment]
Look at the screenshot. Both `env` are selected 'by default'. When you are typing, the input replaces `env`. That is the reason why I said I could not reproduce the problem.

**Comment by harlecin** [comment]
Hey, thank you for your quick reply. I found out, why you cannot reproduce the problem, it is related to the VIM plugin from Visual Studio Code. When I disable it for .tex files, everything works as expected.

I suspect it has to do with how the VIM plugin handles multiple cursors. Would you mind taking a look maybe? I don't understand the plugin system well enough unfortunately...

Thank you for your help nevertheless and sorry for the inconvenience!

**Comment by James-Yu** [comment]
Thanks for the notice. It seems to be a bug with VIM plugin on how it handles multiple selections in general auto-complete scenarios.
