### ISSUE TITLE
Latex syntax highlighting in markdown documents

### ISSUE THREAD

**Issue by songololo** [James-Yu/LaTeX-Workshop#1880]
**Is your feature request related to a problem? Please describe.**
For certain large documents it can be convenient to work in markdown and to use something like [`pandoc`](https://pandoc.org) or [`multimarkdown`](https://fletcherpenney.net/multimarkdown/) to then convert the documents into `tex` documents. This is because some of the more mundane `latex` tasks such as setting up parts / sections / chapters or basic tables / lists etc. or basic formatting such as bold / italic etc. are handled automatically by the above mentioned workflow.

The catch is that things like referencing, equations, complex tables, etc. are still written in raw latex and these are then passed-through unaltered when generating the `tex` files. However, no syntax highlighting or equation previews are available, which means that it is sometimes necessary to copy and paste back-and-forth with a raw `tex` document to find syntax or other problems.

**Describe the solution you'd like**
It would be extremely useful to have `tex` syntax highlighting (and equation previews!) available in markdown documents.

**Comment by tamuratak** [comment]
Out of the scope of this extension.
