### ISSUE TITLE
Can't pass wildcards as arguments for recipes

### ISSUE THREAD

**Issue by Phosphorus31** [James-Yu/LaTeX-Workshop#1882]
**Is your feature request related to a problem? Please describe.**
I've been trying to use LaTeX-Workshop within inline Asymptote code in my LaTeX files but if I have multiple asymptote figures in my LaTeX document I would have to specify the name of each in my recipes. Using Asymptote often yields multiple files such as `main-1.asy`, `main-2.asy`, etc. and when I try to compile with a custom recipe I can't seem to pass a wildcard as an argument.

Currently, in my settings, I'm running

```JSON
"latex-workshop.latex.recipes": [
    {
        "name": "latexmk 🔃",
        "tools": [
            "latexmk"
        ]
    },
    {
        "name": "latexmk ➞ asy ➞ latexmk",
        "tools": [
            "latexmk",
            "asy",
            "latexmk"
        ]
    }
]
```

```JSON
"latex-workshop.latex.tools":[
    {
        "name": "latexmk",
        "command": "latexmk",
        "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdf",
            "-outdir=%OUTDIR%",
            "%DOC%"
        ],
        "env": {}
    },
    {
        "name": "asy",
        "command": "asy",
        "args": [
            "%DOC%-1.asy",
            "%DOC%-2.asy"
        ],
        "env": {}
    }
]
```
and I have to change the arguments every time depending on how many files I get. If I try to pass `"%DOC%-*.asy"` as an argument I get an error 

```
error: could not load module '/Users/username/Desktop/Unitlted/things-*.asy'
```

**Describe the solution you'd like**
Would it be possible to allow wildcards to glob when passed as an argument to a recipe? It's pretty frustrating to have to change something in `settings.json` every time I compile based on the number of asymptote figures I have.

**Describe alternatives you've considered**
Currently, I have been changing the recipe in `settings.json` every time I compile for each file that I have. Sometimes I run `asy main-*.asy` in the terminal.

**Additional context**
MacOS 10.15.2
Visual Studio Code 1.41.1
LaTeX Workshop 8.5.0
TeX 3.14159265 (TeX Live 2019)
Latexmk 4.63b
Asymptote 2.61

**Comment by jlelong** [comment]
Unfortunately, this is not so easy to accept wildcards as we do not run these commands in a shell . There are a couple of alternatives
- use [vscode's tasks mechanism](https://code.visualstudio.com/Docs/editor/tasks) with the option `"type": "shell"` to use the underlying shell wildcards.
- Tell `latexmk` to handle the `.asy` files directly (see [https://asymptote.sourceforge.io/doc/LaTeX-usage.html](https://asymptote.sourceforge.io/doc/LaTeX-usage.html). Basically, you only need to add the following content to your `latexmkrc` file
    ```
    sub asy {return system("asy \"$_[0]\"");}
    add_cus_dep("asy","eps",0,"asy");
   add_cus_dep("asy","pdf",0,"asy");
   add_cus_dep("asy","tex",0,"asy");
    ```

**Comment by Phosphorus31** [comment]
I see. Thank you for answering my questions. I will try to use one of the methods you listed here. Thanks for responding.
