### ISSUE TITLE
Viewing Latex PDF in tab opens viewer with spreads

### ISSUE THREAD

**Issue by Agihi** [James-Yu/LaTeX-Workshop#1885]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

When using the "View Latex PDF" command with the "tab" viewer, the viewer is opened with "Even Spreads", even though my setting for "latex-workshop.view.pdf.spreadMode" is "0", which corresponds to "none"

### To Reproduce

1. Go to settings and set spreadMode to 0
2. Then open tex file
3. Then go to plugin pane
2. Click on 'View Latex PDF'
3. PDF viewer shows even spreads instead of none

## Logs [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[16:09:21] VIEW command invoked.
[16:09:21] Found root file from parent: /redacted/path/to/main.tex
[16:09:21] Root file remains unchanged from: /redacted/path/to/main.tex
[16:09:21] Serving PDF file at http://localhost:34841/viewer.html?file=pdf..JTJGaG9tZSUyRnNpbHZpbyUyRlByb2plY3RzJTJGYmFjaGVsb3ItdGhlc2lzJTJGbWFpbi5wZGY
[16:09:21] The encoded path is /redacted/path/to/main.pdf
[16:09:21] Open PDF tab for /redacted/path/to/main.pdf
[16:09:21] Handle data type: open
[16:09:22] Preview PDF file: /redacted/path/to/main.pdf
[16:09:22] Handle data type: loaded
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

webviewElement.ts:241 [Embedded Page] PDF ce4bb6f57a7d2e86ffc30889ed2014ca [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.2.228)
```

## Desktop [Required]
 - OS: Arch Linux (Kernel 5.4.6-arch3-1)
 - VS Code version: 1.41.1
 - Extension version: 8.5.0
 - TeX distribution version: TeX Live 2019/Arch Linux

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
When the option `pdfpagelayout = TwoColumnRight` of the hyperref package is set, the PDF viewer opens the PDF file with the spread mode. 

If the option is not set in your TeX file, please show us a minimal working example of a TeX file causing this problem.

**Comment by tamuratak** [comment]
If any progress, feel free to reopen this issue.

**Comment by jamesadevine** [comment]
Thanks @tamuratak, did this change recently? It only started happening at the beginning of this month.

I did find the `twoside` configuration hidden in the thesis template that I'm using ([CUED PhD thesis template](https://github.com/kks32/phd-thesis-template)). The template configures everything as twosided by default, the offending line is here: https://github.com/kks32/phd-thesis-template/blob/master/PhDThesisPSnPDF.cls#L629. 

Passing the "oneside" option in the document class command fixed it for me:

```
\documentclass[a4paper,12pt,times,numbered,print,withindex,oneside]{config/PhDThesisPSnPDF}
```

**Comment by jlelong** [comment]
The change is related to #1871 (d6bff55)

**Comment by jamesadevine** [comment]
@jlelong Thanks for the info! :smile: It only really got to me today, so I figured I'd track down a minor inconvenience instead of writing my thesis! :wink:
