### ISSUE TITLE
Questions about build behaviour

### ISSUE THREAD

**Issue by alexreg** [James-Yu/LaTeX-Workshop#1887]
Two quick questions (apologies if they're already covered in the wiki, but I couldn't find the answers):

1. How do I set the build recipe for a particular file, so that when when I run *Build LaTeX project*, it uses that.
2. How do I explicitly *disable* building on save for a particular file? (In my case, it's a "preamble" TeX file that's included in actual document TeX files.)

Thank you in advance.

**Comment by tamuratak** [comment]
1. https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes  See Placeholders.
2. https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#latex-workshoplatexwatchfilesignore

**Comment by alexreg** [comment]
Thanks.

**Comment by alexreg** [comment]
It seems none of the values of `latex-workshop.latex.watch.files.ignore` are heeded however. Even if I use "*" or "**" or "**/*" as the glob, TeX files still get compile upon save.

**Comment by jlelong** [comment]
@alexreg thanks for pointing out the inconsistency on `latex-workshop.latex.watch.files.ignore`.
Discussion continues on #1890

**Comment by alexreg** [comment]
No problem. Glad it's being addressed.
