### ISSUE TITLE
Disable pdflatex.fls file gerneration

### ISSUE THREAD

**Issue by sth4nth** [James-Yu/LaTeX-Workshop#189]
When working with large tex file, the building time is often longer than the interval of hitting ctrl-s. It seems that every time I hit ctrl-s while last build hasn't finish yet, latexmk will generate a pdflatex**.fls file. After a while, my dir accumulates a large amount of such files. 

How do I disable the pdflatex.fls file generation. I highly suggest disable this feature in default setting.

**Comment by James-Yu** [comment]
This is a `latexmk` issue. We do not develop that.

Though there is a simple workaround. You can add a new step in your toolchain, which executes `rm pdflatex*.fls` (in linux) after all latex-related command. So the extension will execute this command after latexmk, which deletes all matching files.

**Comment by nicholashanoian** [comment]
Where exactly would I add this command to implement this workaround?

**Comment by jwu277** [comment]
You could write a bash script to compile your `.tex` files. In this case, simply add `rm pdflatex*.fls` e.g.
```bash
latexmk -pdf
rm pdflatex*.fls
```
