### ISSUE TITLE
Prevent the side bar from popping up after backward synctex

### ISSUE THREAD

**Issue by zwwi** [James-Yu/LaTeX-Workshop#1893]
**Is your feature request related to a problem? Please describe.**

The side bar pops up each time after backward synctex from the pdf to the tex file, even in the zen mode. Setting "Show Side Bar" in View->Appearance to false does not solve the problem. This is really annoying. 

**Describe the solution you'd like**

Please prevent the side bar from popping up after backward synctex, or allow that possibility.

**Additional context**

But I do not know whether this issue belongs to here or to the vs code...

**Comment by jlelong** [comment]
Unfortunately I can't reproduce the issue. Can you post a screenshot of what is happening exactly along with the logs of the extension.
This might be related to `explorer.autoReveal`.

**Comment by zwwi** [comment]
Thank you for your quick response!
Here are some screenshots:
1) Before I clicked the pdf file to backward synctex to the tex
![image](https://user-images.githubusercontent.com/3739411/71983304-71c25880-3261-11ea-8bac-a1577ed9ca14.png)
2) After I click somewhere of the pdf file for a backward syntex to the corresponding position in the tex file, the side bar popped out:
![image](https://user-images.githubusercontent.com/3739411/71983380-96b6cb80-3261-11ea-882f-841a8b98aab0.png)

I followed your suggestion to off `explorer.autoReveal` in the setting, the behavior remains.

Could you tell me where I can find the logs of the extension?

**Comment by jlelong** [comment]
It might be related to https://github.com/James-Yu/LaTeX-Workshop/issues/1006#issuecomment-440570698

Can you try to `"latex-workshop.view.autoActivateLatex.enabled": false`.

**Comment by zwwi** [comment]
@jlelong Thank you. I did not find `latex-workshop.view.autoActivateLatex.enabled`, but setting `View Auto Focus` to false solves the problem.

**Comment by jlelong** [comment]
You are right. The variable `latex-workshop.view.autoActivateLatex.enabled`  has been renamed into `latex-workshop.view.autoFocus.enabled` a14aa15
