### ISSUE TITLE
The shortcut Ctrl-L Ctrl-W  doesn't work for Rnw files

### ISSUE THREAD

**Issue by maikol-solis** [James-Yu/LaTeX-Workshop#1899]
Hi!

I'm using LW 8.5 and I'm working with Rnw files. The big issue for me now is LW doesn't recognize  the shortcut Ctrl-L Ctrl-W when surround some text. For regular Latex files, everything is working fine. 

![Screenshot_20200109_121644](https://user-images.githubusercontent.com/4078489/72093512-25672f00-32da-11ea-906a-3ff8e0cd272b.png)

Thanks for the help.

**Comment by jlelong** [comment]
This is no surprise https://github.com/James-Yu/LaTeX-Workshop/pull/1740#issuecomment-542381449

**Comment by maikol-solis** [comment]
Awesome! Thank you very much.
