### ISSUE TITLE
Unable to see preview

### ISSUE THREAD

**Issue by dehuacheng** [James-Yu/LaTeX-Workshop#19]
After the February update, I was no long able to see the preview: It is now only an empty column. By switching back the previous version of vs code, I was able to see preview correctly.

**Comment by James-Yu** [comment]
I did not encounter this problem. Will need further confirmation from others. Can you please provide screenshots if possible?

**Comment by dehuacheng** [comment]
Hi James,
Reinstallation has fixed the problem for me. Thank you!
