### ISSUE TITLE
Question: "latex-workshop.version" in user settings

### ISSUE THREAD

**Issue by lihuanglx** [James-Yu/LaTeX-Workshop#190]
After updated to the latest version, I got a line added in my user settings:

```
"latex-workshop.version": "2.10.0"
```

I wonder if it's intended or not? Thanks!

**Comment by James-Yu** [comment]
Yes it is intended. This is used to display new version notice upon update.

Actually I can hide the setting at somewhere else like some other extensions do. However that seems a bit non-transparent to users. Discussions welcomed.

**Comment by lihuanglx** [comment]
It seems that users' private settings is to reflect how they customize the editor for some personal preferences. Normally each line in the setting is controlled by user, and has certain affect to the editor's behaviour. Perhaps there's a better place to put the version info?

**Comment by James-Yu** [comment]
I agree with your statement. The setting will be moved to other places.

**Comment by chengs** [comment]
Agree with @lihuanglx 
Some users may feel unhappy seeing their user settings are modified without notification.
