### ISSUE TITLE
Smarter "Expand Selection"

### ISSUE THREAD

**Issue by Rojetto** [James-Yu/LaTeX-Workshop#1901]
I heavily use the "Expand Selection" feature of Visual Studio Code. Unfortunately, this often does not behave as expected for LaTeX documents.

__Current behavior__
It seems like only the default text file delimiter symbols (parentheses, brackets, braces, words, line breaks...), are used to determine the limits of the next larger possible selection.

__Expected behavior__
LaTeX specific regions should also factor into this. Specifically, I'm currently thinking of
- Any kind of group, meaning `\begin` and `\end`
- Math delimiters `$...$`, `$$...$$`, `\(...\)`, `\[...\]`
- Sections, chapters, ...
- Macros and all their arguments (when the cursor is in the macro name, this currently expands first to the macro name and then to the whole line, instead of the macro and its arguments)
- `\item` entries in `itemize` and `enumerate` groups
- Cells and rows in tables and matrices, separated by `&` and `\\`
- Entries in key-value arguments

I would also expect for each of these, that the selection first expands to the inside of the delimiters, and when expanding again, to also include the delimiters.

Apparently VSCode provides an API for this kind of semantic selection expansion, documented [here](https://code.visualstudio.com/api/references/vscode-api#SelectionRangeProvider).

**Comment by jlelong** [comment]
A new function has been added to select the full content of an environment including the opening and closing statements.
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#navigating-and-selecting
Environments considered by this function are blocks delimited by `\begin...\end`, `\[...\]`, `\(...\)`. Repeated calls result in selecting the outer environments
