### ISSUE TITLE
Errors about "Latexmk"

### ISSUE THREAD

**Issue by realdwang** [James-Yu/LaTeX-Workshop#1906]
Collected error summary (may duplicate other messages):
  bibtex c:/Users/ddd/Documents/Temporary Papers/article: Could not open bibtex log file for 'c:/Users/ddd/Documents/Temporary Papers/article'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: Errors, so I did not complete making targets
C:\texlive\2018\bin\win32\runscript.tlu:790: command failed with exit code 12:
perl.exe c:\texlive\2018\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -pdf "-outdir=c:\Users\ddd\Documents\Temporary Papers" "c:/Users/ddd/Documents/Temporary Papers/article"

**Comment by jlelong** [comment]
Please fill the template with the full logs of the extension **and** the LaTeX compiler, otherwise we will have no choice but closing the issue. A MWE is also really helpful for that kind of issues.
