### ISSUE TITLE
Support for `DeclarePairedDelimiter` in equation preview

### ISSUE THREAD

**Issue by wirhabenzeit** [James-Yu/LaTeX-Workshop#1907]
Is there a way to enable support for `DeclarePairedDelimiter` environments from the `mathtools` package in equation previews? 

`DeclarePairedDelimiter` allows to create automatically resized paired delimiters, e.g. 
```
\DeclarePairedDelimiter\abs{\lvert}{\rvert}%
\DeclarePairedDelimiter\norm{\lVert}{\rVert}%
```
allows to create absolute value and norm environments with automatically resized delimiters, for example `\abs*{\frac{1}{2}}`. In the current version the above commands seem to be ignored when the tex-file is parsed for user-defined commands.

**Comment by jlelong** [comment]
Because parsing LaTeX is so tricky, the following two commands are unfortunately treated differently
```
      \DeclarePairedDelimiter{<cmd>}{<left_delim>}{<right_delim>}
      \DeclarePairedDelimiter<cmd>{<left_delim>}{<right_delim>}
```
and we cannot really do much about it without writing dirty hacks. 

- `\DeclarePairedDelimiter\abs{\lvert}{\rvert}`
  Intellisense lists `\abs` but completes it into `\abs{}{}` (Removing the `{}{}` is really a pain for the moment)
- `\DeclarePairedDelimiter{\abs}{\lvert}{\rvert}`
  Intellisense lists `\abs` and completes it into `\abs`.

Note that, we also support `DeclarePairedDelimiterX` and `DeclarePairedDelimiterXPP`

@tamuratak do you think, it would be possible for your parser to properly handle `\DeclarePairedDelimiter` in the same way as `\def`?

**Comment by tamuratak** [comment]
Possible. But not immediately. I don't know when. It would take years.

**Comment by jlelong** [comment]
So I am closing this issue.

**Comment by wirhabenzeit** [comment]
@jlelong Thanks for your efforts! Just wondering: should the current version 8.7.1 of the plugin already support `DeclarePairedDelimiter` for equation previews? 

For me it does not work also for declarations including the the braces `{}`.

![screenshot](https://user-images.githubusercontent.com/17571643/73541445-bd1bf100-4432-11ea-9e77-62e051a75445.png)

**Comment by jlelong** [comment]
Actually, I completely misread your first post. I implemented intellisense for commands declared by `DeclarePairedDelimiter` not preview. Equations are rendered using mathjax, which  does not support `DeclarePairedDelimiter`.  I do not think we can really solve this without nasty tricks.

A quick hack would be to create a file `preview-macros.tex` containing

```tex
\newcommand{\abs}[1]{\left\lvert #1 \right\rvert}
```

and set `latex-workshop.hover.preview.newcommand.newcommandFile: preview-macros.tex`. I am afraid this the best I can suggest you for now.

**Comment by jlelong** [comment]
When I have some time, I will investigate how to parse the `DeclarePairedDelimiter` command to automatically inject into mathjax a `\newcommand` declaration of the command. In your example,

```tex
\newcommand{\abs}[1]{\left\lvert #1 \right\rvert}
```

**Comment by wirhabenzeit** [comment]
I can also look into a possible implementation. Do I understand correctly that the parsing of `\newcommand` declarations for math preview is done in `mathpreview.ts`? 

By the way, what is the current class of supported `\newcommand` declarations? Are commands with multiple parameters supported? I assume that declarations including, for example `\if`etc, are not supported?

**Comment by jlelong** [comment]
Yes, everything is done in `mathpreview.ts`

I do not know precisely what mathjax understands http://docs.mathjax.org/en/latest/misc/faq.html#faq-user-macros. `\newcommand` declarations with arguments are fine but probably not`\if`.
