### ISSUE TITLE
Syntax Highlighting Error for "{}"

### ISSUE THREAD

**Issue by xinleiyu** [James-Yu/LaTeX-Workshop#1910]
### To Reproduce
The syntax highlighting seems to be incorrect for the `{` and `}` of the inner environment of an `align` environment in `.tex` file, as follows.

```
\begin{align}
  M&=\left\{ {
 \begin{aligned}
  &1, && 3\\
  &2, && 4
  \end{aligned}}\right.\\
  &=\begin{cases}
    1\\
    2
  \end{cases}
\end{align}
```
### Screenshots
![image](https://user-images.githubusercontent.com/35287049/72525943-3e567e00-38a0-11ea-811c-300f95f66da7.png)

### Expected behavior

The  `{` and `}` of `\begin{aligned}`, `\end{aligned}`, `\begin{cases}`, and `\end{cases}` might be white.

### Desktop [Required]
 - OS:  Windows 10
 - VS Code version: 1.41.1
 - Extension version: 8.6.0
 - TeX distribution version: TeX Live 2019

**Comment by jlelong** [comment]
I do not think this is really a bug. Opening and closing braces in `\begin{...}` and `\end{...}` are matched with the scopes `punctuation.definition.arguments.begin.latex` and `punctuation.definition.arguments.end.latex` respectively. Most themes do not define the `punctuation` scope so the braces get the outer scope, hence the colour difference.

- In `\begin{align}`, the outer scope is `text.tex.latex`
- In `\begin{cases}`, the outer scope is `support.class.math.block.environment.latex`

We cannot do much about it. You can always the `punctuation` scope yourself.
