### ISSUE TITLE
Sweave Support of \Sexpr Function

### ISSUE THREAD

**Issue by ChristopheRoyer21** [James-Yu/LaTeX-Workshop#1918]
## \Sexpr{} function

This LaTeX/Sweave function allows to add inline R code. However it seems this function is not supported in the current version of the extension. This is a problem especially when extracting an element of a list. Here is an example :

![bug_Sexpr](https://user-images.githubusercontent.com/34045208/73150185-0a930980-4093-11ea-9350-511b9f669a10.png)

**Comment by jlelong** [comment]
The current syntax does not accept any `{...}` inside `\Sexpr` arguments. Dealing with nested braces is a bit of a headache and slows down the regex. If this is really need, we could accept one level of nested braces. Let me know.

**Comment by ChristopheRoyer21** [comment]
Except in fonction definition and in code blocks, braces are pretty rare in R (at least by personnal experience). \Sexpr{} is mostly used to add some R variables (short R expression) in a chunk of text. Therefore, nested braces are not needed. As I said earlier, the more frequent conflict I encountered with the Latex syntax is the usage of $ to extract elements from a list (which turn on Equation mode of LateX)

 I don't know if it's possible to add R syntax support inside the function, but if it's not, I suggest to simply turn off the LateX syntax inside the braces of \Sexpr.

**Comment by jlelong** [comment]
The content of `\Sexpr` is now highlighted using the R syntax.

**Comment by ChristopheRoyer21** [comment]
Thank you so much for your quick answer and solution!
