### ISSUE TITLE
Updating the pdf outside from VS Code does not reload the pdf file in the viewer.

### ISSUE THREAD

**Issue by stakaz** [James-Yu/LaTeX-Workshop#1919]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

The PDF-Viewer inside the VS Code does not update the pdf file if it was updated outside of VS Code. 

### To Reproduce

1. Open a pdf file in the pdf viewer
2. Update the pdf file through a command outside VS Code
3. The previewed pdf does not change.

### Expected behavior

The pdf file is reloaded.

The pdf is **not** generated from a tex file but from a markdown file through pandoc. But the problem here is a general one since the Latex-Workshop is **the** way of opening pdf files in VS Code.

## Desktop [Required]
 - OS: arch linux
 - VS Code version: 1.41.1
 - Extension version: 8.6.0

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
You can call the _Refresh all viewers_ command manually `latex-workshop.refresh-viewer`.
