### ISSUE TITLE
When \cite-ing multiple items, hovering over second items until last does not open up the snippet preview of the item.

### ISSUE THREAD

**Issue by ramyadhadidi** [James-Yu/LaTeX-Workshop#1921]
## Preliminary questions [Required]

When citing multiple items (e.g., \cite{li:mad18, li:mad17, li:mad15}), when the cursor is at the end of the first item, I get a preview of the bib entry. Seen in below:

![Screen Shot 2020-01-28 at 11 41 26](https://user-images.githubusercontent.com/5882631/73284831-24cc0500-41c3-11ea-89a5-bccc67ab08db.png)

But, the same behavior does not happen for second to last items.

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### Desktop [Required]
 - OS: MacOS Catalina 10.15.2 
 - VS Code version: Version: 1.41.1, Commit: 26076a4de974ead31f97692a0d32f90d735645c0
 - Extension version: 8.6.0

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
If you remove the spaces after the commas in ` \cite{li:mad18, li:mad17, li:mad15})`, everything works as expected.

**Comment by ramyadhadidi** [comment]
Seems to be fixed in the new update anyways.
