### ISSUE TITLE
TeX files formatter

### ISSUE THREAD

**Issue by Marco87Developer** [James-Yu/LaTeX-Workshop#1923]
I really appreciate your work for _LaTeX-Workshop_ Visual Studio Code extension! Thank you very much! Is an amazing extension. It makes Visual Studio Code the _best_ LaTeX IDE!

I would love to have a **formatter** for my TeX files. Can you do it? Thank you!

**Comment by jlelong** [comment]
You can use `latexindent` https://github.com/James-Yu/LaTeX-Workshop/wiki/Format
