### ISSUE TITLE
Build subfile command / setting / manual autobuild

### ISSUE THREAD

**Issue by Evpok** [James-Yu/LaTeX-Workshop#1925]
It is nice that LaTeX-Workshop has support for subfiles, but it is tiresome that when in a subfile the build command asks you which file to build every time when you are building often (for instance when designing graphics). It would be nice if there was either on of the following equivalent solutions

1. A “don't ask” setting for `build` that would make it just build the current tex file, regardless of its root/subfile status
2. A dedicated `build_subfile` or `build_current_file`
3. An option to manually trigger `autobuild` since it already has a similar option

Until the last update using the `subfile` document class with no `.tex` extension for the root file made LaTeX-Workshop behave as it were not a subfile (which was not perfect, but at least worked) but this has been fixed  :-)

**Comment by jlelong** [comment]
Why cannot you directly use autobuild?

**Comment by Evpok** [comment]
Because for most files it triggers too often, for instance I don't want it to build my root file every time I modify it.

**Comment by Evpok** [comment]
Oh, and I just noticed that the pdf viewer also asks which file I want to see :-(

**Comment by jlelong** [comment]
> Oh, and I just noticed that the pdf viewer also asks which file I want to see :-(
Yes, but you typically only call the viewer once as it gets updated automatically after each build.

**Comment by Evpok** [comment]
Ah, not in my current workflow for long documents I usually summon it right after I build, do a few back-and-forth with SyncTeX to see if the specific part I have changed render correctly, then close it because it takes too much space, but I guess I could drop it in a tab instead.

**Comment by Evpok** [comment]
(Note to potential readers: for now I simply disable the subfile management using a `% !TEX root = mysubfile.tex` magic comment)

**Comment by xinleiyu** [comment]
I am also looking forward to having a command `build_current_file` in the sidebar.

**Comment by jlelong** [comment]
Going back to the original post, three options were considered

> 1. A “don't ask” setting for `build` that would make it just build the current tex file, regardless of its root/subfile status
> 2. A dedicated `build_subfile` or `build_current_file`
> 3. An option to manually trigger `autobuild` since it already has a similar option

After a bit of thought and to avoid adding extra commands in the sidebar that only make sense in specific frameworks, here is what I  plan to implement
- Add a new setting to decide whether the `build` and `view` commands prompt the user for selecting the proper file
- When nothing is prompted, use the existing setting `latex-workshop.latex.rootFile.useSubFile` to decide which file to consider.

I guess everybody should be happy with this.

**Comment by Evpok** [comment]
That would fit perfectly :-)

**Comment by jlelong** [comment]
Just set `latex-workshop.latex.rootFile.doNotPrompt` to `true`.
The default value for this new setting is `false`. Il will update the wiki.

**Comment by jlelong** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file

**Comment by Evpok** [comment]
Thank you very much, that was quick!

**Comment by ugirc** [comment]
How can I only build the current subfile `section1.tex` with `Build with recipe`. I don't want to build the `main.tex` everytime.

![image](https://user-images.githubusercontent.com/46078304/99892292-78f22980-2cae-11eb-8724-e7600596dac3.png)

`set latex-workshop.latex.rootFile.doNotPrompt to true` seems not work for me.

**Comment by jlelong** [comment]
You also need to set `latex-workshop.latex.rootFile.useSubFile` to `true`.

From your screenshot, you need to replace `\documentclass[main.tex]{subfiles}` by `\documentclass[../main.tex]{subfiles}`. If you need more help, open a new issue and fill all the required information.
