### ISSUE TITLE
Associate .tikz files

### ISSUE THREAD

**Issue by Trooper-X** [James-Yu/LaTeX-Workshop#1929]
**Is your feature request related to a problem? Please describe.**
Files with the `.tikz` extension are not recognized by the extension.
As `.tikz` files are used for `tikz` files, with the LaTeX syntax it was expected to be highlighted.

**Describe the solution you'd like**
I'd like to see the `.tikz` file extension to be recognized by the plugin as LaTeX code.

**Describe alternatives you've considered**
A workaround is to add the following code to `settings.json`:
`"files.associations": {
        "*.tikz": "latex"
}`

**Additional context**
None

***Credits***
Thank you for the work on this plugin, it works really smoothly!
Great work!

**Comment by jlelong** [comment]
I am not sure this is a good idea to associate `.tikz` to the `latex` id in case someone ever wants to provide a real `.tikz` grammar through an other extension. I think the workaround to make the association in your personal settings should be fine.
