### ISSUE TITLE
Open external links in a new browser tab instead of window

### ISSUE THREAD

**Issue by oowekyala** [James-Yu/LaTeX-Workshop#1934]
**Is your feature request related to a problem? Please describe.**
In the PDF preview tab, clicking on an external link (eg added with `\href`) open the URL in a new browser window. I'd like the link to open in a new tab if there's already a browser window running. Eg with the firefox CLI, the `-new-tab` switch does exactly this.

**Describe the solution you'd like**
I guess ideally the "open in browser" command is configurable and anyone can supply their own command. I don't know how the PDF preview is implemented, maybe this is already possible?

Thanks

**Comment by trevorgunn** [comment]
This is an external issue. The extension doesn't launch handle opening links. All links are passed to `vscode.open` which in turn tells Electron to make a system call (e.g. [xdg-open](https://freedesktop.org/wiki/Software/xdg-utils/) on Linux).

You need to figure out how you set up your default browser. All I can say is that links open in a new tab for me. All I did was tell Firefox to make itself the default browser.
