### ISSUE TITLE
Formatting failed without any error message

### ISSUE THREAD

**Issue by TaylorWizard** [James-Yu/LaTeX-Workshop#1938]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

## Describe the bug [Required]
Formatting failed without any error message when use format document feature

### To Reproduce

3. See error

### Expected behavior

formatting successfully

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```


18:30:37] Initializing LaTeX Workshop.
[18:30:37] Creating LaTeX Workshop http and websocket server.
[18:30:37] LaTeX Workshop initialized.
[18:30:37] Found root file from active editor: /Users/weichenggu/Documents/latex/test.tex
[18:30:37] Root file changed from: undefined to /Users/weichenggu/Documents/latex/test.tex. Find all dependencies.
[18:30:37] Instantiating a new file watcher for /Users/weichenggu/Documents/latex/test.tex
[18:30:37] Creating file watcher for .bib files.
[18:30:37] Parsing /Users/weichenggu/Documents/latex/test.tex
[18:30:37] Server created on 127.0.0.1:51357
[18:30:37] Adding /Users/weichenggu/Documents/latex/test.tex to file watcher.
[18:30:37] LaTeX Workshop version: 8.7.1
[18:30:37] Snippet data loaded.
[18:40:24] Found root file from active editor: /Users/weichenggu/Documents/latex/test.tex
[18:40:24] Root file remains unchanged from: /Users/weichenggu/Documents/latex/test.tex.
[18:40:27] Formatting with command /usr/local/texlive/2019/texmf-dist/scripts/latexindent/latexindent.pl -c,/Users/weichenggu/Documents/latex/,/Users/weichenggu/Documents/latex/__latexindent_temp.tex,-y=defaultIndent: '  '
[18:40:27] Formatting failed with exit code null
[18:40:27] stderr: 
[18:42:45] LOG command invoked.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]
 - OS: Mac Mojave 10.14.6 
 - VS Code version: [e.g. 1.41.0]
 - Extension version: 8.7.1
 - TeX distribution version: [e.g. ]

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by jlelong** [comment]
Please update the extension.
Try to run the formatting command from the terminal

```
/usr/local/texlive/2019/texmf-dist/scripts/latexindent/latexindent.pl -c /Users/weichenggu/Documents/latex/ -o /Users/weichenggu/Documents/latex/latexindent_test.tex -y="defaultIndent: '  '" /Users/weichenggu/Documents/latex/test.tex
```

**Comment by TaylorWizard** [comment]
@jlelong `Try to run the formatting command from the terminal` what is mean?

**Comment by jlelong** [comment]
> Extension version: [e.g. 8.5.0]

The latest version is 8.7.1. So please update the extension.

> Try to run the formatting command from the terminal

Open the `Terminal.app` application and change to directory `/Users/weichenggu/Documents/latex/`. Then execute

```
/usr/local/texlive/2019/texmf-dist/scripts/latexindent/latexindent.pl -c /Users/weichenggu/Documents/latex/ -o /Users/weichenggu/Documents/latex/latexindent_test.tex -y="defaultIndent: '  '" /Users/weichenggu/Documents/latex/test.tex
```

and paste the output.

**Comment by TaylorWizard** [comment]
@jlelong 
Extension version: [e.g. 8.5.0]

The latest version is 8.7.1. So please update the extension.

Try to run the formatting command from the terminal

Open the Terminal.app application and change to directory /Users/weichenggu/Documents/latex/. Then execute

/usr/local/texlive/2019/texmf-dist/scripts/latexindent/latexindent.pl -c /Users/weichenggu/Documents/latex/ -o /Users/weichenggu/Documents/latex/latexindent_test.tex -y="defaultIndent: '  '" /Users/weichenggu/Documents/latex/test.tex
and paste the output.

% !Tex root=./text.tex
\documentclass[11pt,UTF8]{ctexart}
\usepackage{xeCJK}
\usepackage{pgfplots}
\usepackage{mathpazo}
\usepackage[T1]{fontenc}
% \usepackage[utf8]{inputenc}
% \usepackage{tikz}
\newcommand{\num}{pi}
\pgfplotsset{width=10cm,compat=1.9}
\begin{document}
\include{taylor-expansion/index}
\include{ttt}
\end{document}

**Comment by jlelong** [comment]
Might be related to #1939. What is your version of VSCode?

**Comment by jlelong** [comment]
I am closing this issue as the _Format on Save_ has been updated.
If you still experience troubles in the next release, please open a new issue and carefully fill the template.
