### ISSUE TITLE
Remote docker containers

### ISSUE THREAD

**Issue by MagicLegend** [James-Yu/LaTeX-Workshop#1940]
**Is your feature request related to a problem? Please describe.**
I use the Docker support for this plugin with a lot of love; it is one of the best niche-features of this extension. Not having to clutter my desktop with all the LaTeX things is amazing. However, recently I've ran into a minor issue.

**I want to run my texlive container remotely (over SSH).**

**Describe the solution you'd like**

I would prefer it if I could somehow use the `-H` option of `docker`. Using a command like `docker -H ssh://remoteUser@remote ps` for example; one can connect to the remote docker deamon and list the running containers. Looking at the scripts in this repo I think this shouldn't be too difficult to provide as an setting. However; I am really time-constraint right now (graduation), so I don't really have the time to look into it myself.

**Describe alternatives you've considered**

I have thought about other tricks with the remote-container plugin; only to realize that this of course doesn't modify the behaviour or this plugin (which is actually running the docker command). I also have tried modifiying my own docker installation to always point to the remote; but this is less than ideal as this makes me either switch between daemons (local and remote).

This idea would make it possible to compile within docker remotely, whilst keeping the files and editing remotely.

**Aditional context**
I need this because I work with git repo's; and the remote server I can use to compile with doesn't have access to said git repos (they're internal).

**Comment by tamuratak** [comment]
Since VSCode Remote Development is available, we would not like to add additional features to the Docker support of LaTeX Workshop.

**Comment by MagicLegend** [comment]
Sure, but Remote Development requires the LaTeX to be on the remote as well. I don't want that in this scenario. I want to keep the LaTeX on my local machine; and copy it to the remote for the container. This is a scenario that is not possible in the current LaTeX-Workshop.
