### ISSUE TITLE
regression: Activating extension 'James-Yu.latex-workshop' failed: Cannot find module 'picomatch'

### ISSUE THREAD

**Issue by thetric** [James-Yu/LaTeX-Workshop#1945]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
Probably since v8.7.2 the extension fails to load. LaTeX WS commands don't work.

### To Reproduce

1. Make sure you have v8.7.2 installed
2. Restart VS Code
3. Open the VS Code Developer Tools (Strg+Ctrl+I)

### Expected behavior
The extension should load without errors.

### LaTeX Workshop Output [Required]
Not available, the extension doesn't load

### Developer Tools Console [Required]
```
abstractExtensionService.ts:396 Activating extension 'James-Yu.latex-workshop' failed: Cannot find module 'picomatch'
Require stack:
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/node_modules/readdirp/index.js
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/node_modules/chokidar/index.js
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/out/src/components/manager.js
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/out/src/main.js
- /opt/visual-studio-code/resources/app/out/vs/loader.js
- /opt/visual-studio-code/resources/app/out/bootstrap-amd.js
- /opt/visual-studio-code/resources/app/out/bootstrap-fork.js.
_logMessageInConsole @ abstractExtensionService.ts:396
```

## Desktop [Required]
 - OS: Arch Linux
 - VS Code version: 1.42.0
 - Extension version: 8.7.2
 - TeX distribution version: TexLive 2019.52579-1

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by thetric** [comment]
According to the `package-lock.json` the `picomatch` module should be installed under `.vscode/extensions/james-yu.latex-workshop-8.7.2/node_modules/readdirp/node_modules`.

https://github.com/James-Yu/LaTeX-Workshop/blob/a693907aff0736f95eb7c7e792f9d54e50d84e9d/package-lock.json#L5342-L5349

I ran `npm i` in `.vscode/extensions/james-yu.latex-workshop-8.7.2/node_modules/readdirp` and restarted but another error prevented the extension startup:

```
/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3486 Activating extension 'James-Yu.latex-workshop' failed: Cannot find module 'picomatch'
Require stack:
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/node_modules/anymatch/index.js
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/node_modules/chokidar/index.js
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/out/src/components/manager.js
- /home/me/.vscode/extensions/james-yu.latex-workshop-8.7.2/out/src/main.js
- /opt/visual-studio-code/resources/app/out/vs/loader.js
- /opt/visual-studio-code/resources/app/out/bootstrap-amd.js
- /opt/visual-studio-code/resources/app/out/bootstrap-fork.js.
_logMessageInConsole @ /opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:3486
```

**Comment by thetric** [comment]
The extension works after building it from source. Build env: Node 12.14.1, npm 6.13.7

**Comment by thetric** [comment]
However I wasn't able to reproduce this error on my Windows 10 machine. On Arch Linux the error was reproducible even after reinstalling it

**Comment by trevorgunn** [comment]
I can say that I'm using it now on RHEL7 without issue. I can try it on Arch once I get back home. Although, the version of `picomatch` was updated between `8.7.0` and `8.7.1` not between `8.7.1` and `8.7.2` and I've certainly used `8.7.1` on Arch Linux without issue.

**Comment by thetric** [comment]
Resolved by manually removing `~/.vscode/extensions/james-yu.latex-workshop-8.7.2` and reinstalling. VS Code doesn't actually delete the extension folder when the extension is removed
