### ISSUE TITLE
Syntax highlighting issue when dealing with listings

### ISSUE THREAD

**Issue by Laberbear** [James-Yu/LaTeX-Workshop#195]
### Description

When using the listings package for show source code in a document, the syntax highlighting is getting confused.
It seems like it is interpreting the source code as LaTeX.

### How to reproduce
Minimal LaTeX example:

    
    \documentclass{article}

    \usepackage{listings}
    \begin{document}
        \lstdefinelanguage{JavaScript}{
            morestring=[b]`
        }
    
      \lstset{language=JavaScript}
      \begin{lstlisting}
          let x = `this is a ${string}`
      \end{lstlisting}
      Everything is orange now, that is bad >:
	\end{document}

### Actual behavior
![screenshot 2017-07-14 13 59 59 2](https://user-images.githubusercontent.com/10895804/28211421-df56e1ae-689c-11e7-890f-a31139b1fc68.png)

### Expected behavior
I definitely don't expect you to parse the listings within the document as defined in LaTeX or as a sub-language in VS Code. However it would be cool if the stylings would reset at the end of listing, so that the rest of the LaTeX code is unaffected.

Example:
![screenshot 2017-07-14 14 02 29](https://user-images.githubusercontent.com/10895804/28211478-22442436-689d-11e7-8a12-f82018f3e3ad.png)

**Comment by James-Yu** [comment]
As you may noticed, the syntax highlight is a transpil-ation of the textmate counterpart. I will look into this issue and see if anything can be achieved.

It seems not quite possible to use language-specific highlight, which is far beyond the capability of vscode build-in highlighting paradigm. Let me check if its possible to simply ignore the quoted codes. Will return back shortly.

**Comment by James-Yu** [comment]
Problem Solved (TM). Will release shortly.

**Comment by Laberbear** [comment]
Great, thanks for the fast replies.
