### ISSUE TITLE
Can't add new recipes

### ISSUE THREAD

**Issue by wanyancan** [James-Yu/LaTeX-Workshop#1952]
## Preliminary questions [Required]
I'd like to use xelatex to build. After following the guide, I added recipes and tools. But no way to invoke this new build command

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes 

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes
In powershell terminal, I can build with

    xelatex.exe -synctex=1 -interaction=nonstopmode .\readme.tex

## Describe the bug [Required]

I'm not sure whether the new recipe should be put in file '.vscode/launch.json' 

### To Reproduce

1. mkdir testlatex
2. the folder testlatex has the following contents:

> testlatex
> |-.vscode
> ||-launch.json
> |-readme.tex

file of launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${file}"
        }
    ],
    "latex-workshop.latex.recipes": [
        {
            "name": "xelatex",
            "tools": [
                "xelatex"
            ]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "%DOC%.tex"
            ],
            "env": {}
        }
    ]
}
```
file of readme.tex
```
% !TeX root = ./readme.tex
\documentclass[]{article}
\usepackage[UTF8]{ctex}
\begin{document}
\title{中文}
\author{latex}
\maketitle
    hi
\end{document}

```
### Expected behavior

In command palette, there should be new command in 
Build with recipe, -> xelatex

## Logs [Required]
No new command is found

### LaTeX Workshop Output [Required]

```
[16:07:22] Initializing LaTeX Workshop.
[16:07:22] Creating file watcher for .pdf files.
[16:07:22] pdflatex is provided by MiKTeX
[16:07:22] Creating LaTeX Workshop http and websocket server.
[16:07:22] LaTeX Workshop initialized.
[16:07:22] Server created on 127.0.0.1:10428
[16:07:22] Snippet data loaded.
[16:07:22] LaTeX Workshop version: 8.7.2
[16:11:32] Found root file by magic comment: g:\WX_projs\demo\testlatex\readme.tex
[16:11:32] Looped root file by magic comment found: g:\WX_projs\demo\testlatex\readme.tex, stop here.
[16:11:32] Root file changed from: undefined to g:\WX_projs\demo\testlatex\readme.tex. Find all dependencies.
[16:11:32] Instantiating a new file watcher for g:\WX_projs\demo\testlatex\readme.tex
[16:11:32] Creating file watcher for .bib files.
[16:11:32] Parsing g:\WX_projs\demo\testlatex\readme.tex
[16:11:32] Adding g:\WX_projs\demo\testlatex\readme.tex to file watcher.
[16:12:56] RECIPES command invoked.
[16:14:28] ACTIONS command invoked.
[16:14:36] LOG command invoked.
```

### Developer Tools Console [Required]

```

  | onDidNotificationChange | @ | workbench.desktop.main.js:sourcemap:2720
-- | -- | -- | --
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:2720
  | fire | @ | workbench.desktop.main.js:sourcemap:116
  | addNotification | @ | workbench.desktop.main.js:sourcemap:2741
  | notify | @ | workbench.desktop.main.js:sourcemap:3837
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:3558
  | _showMessage | @ | workbench.desktop.main.js:sourcemap:3557
  | $showMessage | @ | workbench.desktop.main.js:sourcemap:3557
  | _doInvokeHandler | @ | workbench.desktop.main.js:sourcemap:3592
  | _invokeHandler | @ | workbench.desktop.main.js:sourcemap:3592
  | _receiveRequest | @ | workbench.desktop.main.js:sourcemap:3591
  | _receiveOneMessage | @ | workbench.desktop.main.js:sourcemap:3589
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:3588
  | fire | @ | workbench.desktop.main.js:sourcemap:116
  | fire | @ | workbench.desktop.main.js:sourcemap:384
  | _receiveMessage | @ | workbench.desktop.main.js:sourcemap:388
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:385
  | fire | @ | workbench.desktop.main.js:sourcemap:116
  | acceptChunk | @ | workbench.desktop.main.js:sourcemap:381
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:381
  | t | @ | workbench.desktop.main.js:sourcemap:391
  | emit | @ | events.js:200
  | addChunk | @ | _stream_readable.js:294
  | readableAddChunk | @ | _stream_readable.js:275
  | Readable.push | @ | _stream_readable.js:210
  | onStreamRead | @ | internal/stream_base_commons.js:166

```

## Screenshots

![image](https://user-images.githubusercontent.com/3443766/74635850-cc749b80-51a1-11ea-99a6-b7b79409235d.png)

## Desktop [Required]
 - OS: Win10 1909 (18363.657)
 - VS Code version: 1.42.0 (system setup)
 - Extension version:  Latex Workshop 8.7.2
 - TeX distribution version: MiKTeX 2.9.7250

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Any more detailed documents about how to set the new recipt(s) are appreciated.

**Comment by tamuratak** [comment]
You should edit `settings.json` instead of `launch.json`.

See https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

**Comment by wanyancan** [comment]
Thank you for your prompt reply.

After it's been moved to .vscode/settings.json, it still has no effect. Then I noticed this message.

![image](https://user-images.githubusercontent.com/3443766/74646253-6c3b2500-51b4-11ea-8720-1f0cfc3106dd.png)

It turns out that I need to open this folder as File -> Open Folder
However, I usually use File -> Open Workspace to open the folder and for it to work in this way, 
I need to bring File->Preferences->settings (Ctrl+,) and save the settings to **workspace.json** file which should be saved as **sometitle.code-workspace** in the same folder.

One more thing, inside the **sometitle.code-workspace** file the settings should be as below for it to take effect.

```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"latex-workshop.latex.recipes": [
			{
				"name": "xelatex",
				"tools": [
					"xelatex"
				]
			}
		],
		"latex-workshop.latex.tools": [
			{
				"name": "xelatex",
				"command": "xelatex",
				"args": [
					"-synctex=1",
					"-interaction=nonstopmode",
					"%DOC%.tex"
				],
				"env": {}
			}
		]
	}
}
```

I know this may seems to be trivial, I'd like to read more in your provided link about VS Code Settings. Thank you.

**Comment by trevorgunn** [comment]
You want the global settings not the workspace settings. The way I normally access this is through the command pallet (ctrl+shift+p) type in "settings" and look for the option "Open Settings (JSON)". You can also access these through the settings interface if you go to any setting that can only be edited as json (e.g. LW's recipes and tools) and there will be an "edit in settings.json" button.
