### ISSUE TITLE
A better frame environment for beamer documents

### ISSUE THREAD

**Issue by zhuyuming96** [James-Yu/LaTeX-Workshop#1956]
**Is your feature request related to a problem? Please describe.**
Sort of. I'm always frustrated when calling the `frame` environment in beamer document, where it builds up a structure like the following.
```latex
\begin{frame}
	\frametitle{}

	

\end{frame}
```

**Describe the solution you'd like**
It is more common to add the frame title directly after `\begin{frame}` with braces, like the following.
```latex
\begin{frame}{Frame Title}

	

\end{frame}
```
This makes the codes much clearer.

**Comment by trevorgunn** [comment]
I don't know about "more common" but you can make use of the [`latex-workshop.intellisense.commandsJSON.replace`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisensecommandsJSONreplace) setting.

Modify as needed, then reload for it to take effect.

```
"latex-workshop.intellisense.commandsJSON.replace" {
    "frame": "begin{frame}{${1:<title>}}\n\t$0\n\\end{frame}"
}
```

**Comment by zhuyuming96** [comment]
Thanks! I appreciate your information.

Best,
Frederick
