### ISSUE TITLE
Allow to configure additional parameters passed to Docker

### ISSUE THREAD

**Issue by thewilli** [James-Yu/LaTeX-Workshop#1958]
**Is your feature request related to a problem? Please describe.**

I'm using the Docker-based workflow with the extension. While it works fine with *standalone* files, I do have a larger collection of custom classes and packages. In order to use them with Docker I do need to add volume mounts and corresponding env variable entries. As of now, it is [not possible](https://github.com/James-Yu/LaTeX-Workshop/blob/b9914b8/scripts/latexmk#L2) to inject additional stuff into the invocation.

**Describe the solution you'd like**

Additional configuration setting representing additional arguments passed to Docker.

**Describe alternatives you've considered**

My current workaround is to *abuse* the `docker.image.latex` configuration value (`$LATEXWORKSHOP_DOCKER_LATEX` in the scripts), e.g.

```plain
-v /some/path/:/template/ -e TEXINPUTS=/template//: tianon/latex
```

instead of the default `tianon/latex`. This works because the variable isn't quoted in the scripts. It’s really hacky, though.

**Comment by tamuratak** [comment]
Since VSCode Remote Development is available, we would not like to add additional features to the Docker support of LaTeX Workshop.
