### ISSUE TITLE
Citation intellisense browser does not work with multiple citations 

### ISSUE THREAD

**Issue by elderfd** [James-Yu/LaTeX-Workshop#196]
### Description

When using the citation browser for autocompletion (via the option "latex-workshop.intellisense.citation.type": "browser") it is not possible to add multiple citations to a single \cite command. On choosing a second citation from the browser, the first is overwritten.

### How to reproduce

1. Have document with bibliography with multiple records
2. Set the option "latex-workshop.intellisense.citation.type" to "browser"
3. Begin typing "\cite{" and browser will gain focus
4. Choose a citation
5. After first citation type "," and browser will again take focus
6. Choose a second citation

### Expected behavior

This should append the second chosen citation to the first. If the chosen citation keys are "A" and "B" then the above steps are expected to autocomplete to give the text "\cite{A,B}",

### Actual behavior

The second citation overwrites the first. If the chosen citation keys are "A" and "B" then the above steps autocomplete to give the text "\cite{B}".

### Additional Information

Issue was experienced with Latex Workshop 2.10.1, VS Code 1.14.1, Windows 10 64 bit.

**Comment by James-Yu** [comment]
Thanks for the issue. This bug will be fixed in the next release.
