### ISSUE TITLE
How can I turn on auto-pst-pdf in VScode?

### ISSUE THREAD

**Issue by Turbjet** [James-Yu/LaTeX-Workshop#1960]
Hi,

I'd like to use auto-pst-pdf package in my latex file. However, I got this following warning:

> Pacakge auto-pst-pdf Error

When I track it down to the auto-pst-pdf.sty, it says:

> You need to run LaTeX with the equivalent of "pdflatex -shell-escape"\app@nl Or turn off auto-pst-pdf.

I'm not quite sure how should I do this shell escape, can anyone please give me some guide?

Thanks a lot!

**Comment by trevorgunn** [comment]
See the [wiki's FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#how-to-pass--shell-escape-to-latexmk).

**Comment by Turbjet** [comment]
I tried this, but it didn't work

**Comment by jlelong** [comment]
Which approach did you try? Post your configuration and the extension logs if you need help.

**Comment by Turbjet** [comment]
@jlelong Seems like I entered those codes in a wrong place. So a stupid question: could you please tell me where can I find the `latex-workshop.latex.tools` file? I am new to VScode, and I have no idea how to find this file.

**Comment by trevorgunn** [comment]
@Turbjet Next to the setting (File > Preferences > Settings), click the cog wheel and choose "Copy as JSON". 

![Untitled](https://user-images.githubusercontent.com/7917549/77119174-4fd91500-6a0c-11ea-8cee-9435fc9d0c65.png)

Then under the setting, click "Edit in settings.json". Then paste the clipboard contents into the settings file, making sure to add an extra comma before you do.

![Untitled](https://user-images.githubusercontent.com/7917549/77119530-04733680-6a0d-11ea-9d11-9975192ca62a.png)

**Comment by Turbjet** [comment]
But now I run into another issue. The log is attached below

`Latexmk: Log file says output to 'main.pdf'
Latexmk: List of undefined refs and citations:
  Reference `eq::chiToKappa' on page 13 undefined on input line 678
  Reference `eq::chiToKappaDelta' on page 13 undefined on input line 678
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'main-pics.pdf'
Latexmk: Maximum runs of pdflatex reached without getting stable files
Latexmk: Summary of warnings from last run of (pdf)latex:
  Latex failed to resolve 2 reference(s)
----------------------
This message may duplicate earlier message.
Latexmk: Failure in processing file '/Users/shuang91/OneDrive/Mac/PhD/log/notes/8_Information theory quantifier/entropy and LES/main':
   'pdflatex' needed too many passes
----------------------
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: applying rule 'pdflatex'...
Latexmk: All targets () are up-to-date
`

The file can be compiled, but it keeps sending an error message.

**Comment by Turbjet** [comment]
I tried the 1st and 2nd approach in the FAQ mentioned above. But now I run into the following issues

> Latexmk: Log file says output to 'main.pdf'
> Rule 'pdflatex': File changes, etc:
>    Changed files, or newly in use since previous run(s):
>       'main-pics.pdf'
> Latexmk: Maximum runs of pdflatex reached without getting stable files
> This message may duplicate earlier message.
> Latexmk: Failure in processing file '/Users/shuang91/OneDrive/Mac/PhD/log/notes/8_Information theory quantifier/entropy and LES/main':
>    'pdflatex' needed too many passes
> Latexmk: Use the -f option to force complete processing,
>  unless error was exceeding maximum runs, or warnings treated as errors.
> === TeX engine is 'pdfTeX'
> Latexmk: applying rule 'pdflatex'...
> Latexmk: All targets () are up-to-date

**Comment by trevorgunn** [comment]
This looks like something you should figure out on the command line before you try to implement it in Latex Workshop. See how many times you need to run `pdflatex` before you get a stable output. See if the `-f` option works.

**Comment by Turbjet** [comment]
Probably `pdflatex` will not work for me. I'd like to switch to `Latex->dvips->ps2pdf` approach. I am wondering where/how can I specify this? I am guess modify the following part in `latex-workshop.latex.recipes`?

```
{
        "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
        "tools": [
          "pdflatex",
          "bibtex",
          "pdflatex",
          "pdflatex"
        ]
      }
```

**Comment by trevorgunn** [comment]
Yes, but you also have to add the `latex` and `dvips` and `ps2pdf` to the tools. For `latex`, probably you just need to copy `pdflatex`:

	{
		"name": "latex",
		"command": "latex",
		"args": [
			"-synctex=1",
			"-interaction=nonstopmode",
			"-file-line-error",
			"%DOC%"
		],
		"env": {}
	},

For the other two, the same but with just the `%DOC%` argument:

	{
		"name": "dvips",
		"command": "dvips",
		"args": [
			"%DOC%"
		],
		"env": {}
	},
	{
		"name": "ps2pdf",
		"command": "ps2pdf",
		"args": [
			"%DOC%"
		],
		"env": {}
	},

Alternatively, you can try using `latexmk` without the `-pdf` flag by modifying its tool entry.

**Comment by chrisklpp** [comment]
Hey, did you get it to work?
I have the same problem, and it didn't work for me with the proposed settings for drips and ps2pdf.  It exits the compilation with: `Error: /undefinedfilename` so I guess the consistent use of %DOC$ breaks the file chain somewhere?

**Comment by tamuratak** [comment]
Open a new issue.

Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)
