### ISSUE TITLE
Jump-to-pdf with several pdfs open

### ISSUE THREAD

**Issue by coxackie** [James-Yu/LaTeX-Workshop#1961]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When multiple pdfs are open in a project, the focus in at a different pdf then the working tex file is associated to, and I use Crtl+Alt+J to jump to the pdf, the focused pdf file does not change to the one of the working tex file. 

### To Reproduce

Just do as described above - no further particular.

### Expected behavior

I would expect that focus changes to the pdf of the current working pdf file.

## Desktop [Required]
 - OS: Linux
 - VS Code version: 1.41.1
 - Extension version: 8.7.2
 - TeX distribution version: TeX Live 2019

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by machsix** [comment]
same here, when I rebuild the project, the pdf in the tab is refreshed. If I save the tex file, the pdf preview becomes blank and "open pdf in the tab" opens a new tab
