### ISSUE TITLE
Gnuplot support for pgfplots

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1963]
**Is your feature request related to a problem? Please describe.**

Would it be possible to fix syntax colouring when using gnuplot with pgfplots ? Since we can use the dollar sign to call columns, it breaks the syntax colouring of the whole document (see screenshot below).

**Describe the solution you'd like**
It seems that gnuplot syntax colouring is already supported for `gnuplot` environnement (see #916) 

**Describe alternatives you've considered**

At least disable syntax colouring in the example case so that it does not break the whole document.

**Additional context**
![image](https://user-images.githubusercontent.com/15056323/75347657-21e33380-5899-11ea-9c5a-0d11c9f78c74.png)

**Comment by jlelong** [comment]
Could you provide a MWE? I do not understand how to reproduce the issue. Is the `\addplot` command put inside a particular environment?

**Comment by PierreMarchand20** [comment]
My bad, I should have given a MWE from the start:
```
\documentclass[tikz]{standalone}

\usepackage{pgfplots,filecontents}
\pgfplotsset{compat=newest}

\begin{filecontents}{test.dat}   
    0.0000 
    1.0000 
    2.0000 
    3.0000 
    4.0000 
    5.0000 
    6.0000 
    7.0000 
    8.0000 
    9.0000 
    10.0000
    11.0000
    12.0000
    13.0000
    14.0000
    15.0000
    16.0000
    17.0000
\end{filecontents}

\begin{document}
    \pgfplotstableread{test.dat}{\test}
    \begin{tikzpicture}

        \begin{axis}
            \addplot+[no marks,thick]  gnuplot [raw gnuplot] {
                f(x) = exp(x);
                plot 'test.dat' u 1:(f($1));
            };
        \end{axis}
    \end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/15056323/75446341-207c3e80-595f-11ea-87a5-1b29e6afddfb.png)


Notice that you need `gnuplot` of course to run this MWE.

**Comment by PierreMarchand20** [comment]
To answer your question, `addplot` is not in a special environment, but the parameter `gnuplot [raw gnuplot]` makes the input as a gnuplot script. I understand it can be trickier to deal with than with just a `\begin...\end` environment.
