### ISSUE TITLE
Is there a way to list sections and jump to selected one?

### ISSUE THREAD

**Issue by xiaottang2** [James-Yu/LaTeX-Workshop#197]
If you press 'Cmd+r' in Sublime Text when opening a .tex file, all sections and subsections will be listed and it's a very convenient way to have an overview of the document. When you click on a section/subsection, the editor automatically jumps to the beginning of that section.

It would be of tremendous help if LaTex-Workshop could add this feature in a future version.

Thanks.

The interface could be something like this:
![screenshot 2017-07-15 12 53 45](https://user-images.githubusercontent.com/5819834/28236619-ad190652-695c-11e7-95d1-376785c98704.png)

**Comment by James-Yu** [comment]
It's in the LaTeX outline. Screenshot:
![image](https://user-images.githubusercontent.com/4210342/28237378-566b47ca-6970-11e7-988d-b744a8de5312.png)

I noticed that sometimes, vscode does not show the outline part. This should be an upstream problem, and I'll go on looking into the issue.
