### ISSUE TITLE
AutoBuild on git commit/change

### ISSUE THREAD

**Issue by smartens** [James-Yu/LaTeX-Workshop#1973]
**Is your feature request related to a problem? Please describe.**
Right now I'm building the document manually, because I don't see it necessary to build the document all the time. But I always use git when I type something in Latex.

**Describe the solution you'd like**
I would like to have a "latex-workshop.latex.autoBuild.run" setting "OnGitCommit" or "OnGitChange". So that every time I commit a change the document gets automatically build.

**Describe alternatives you've considered**
You can configue to push or sync after a commit in vscode but there's no option to configure a custom command.

**Comment by jlelong** [comment]
You should consider using Git Hooks https://git-scm.com/docs/githooks
