### ISSUE TITLE
Allow disabling mathematical snippets

### ISSUE THREAD

**Issue by LPTK** [James-Yu/LaTeX-Workshop#1974]
**Is your feature request related to a problem? Please describe.**

I heavily use the `@` sign in order to write things in inline code listings, as in `@some code@`, and it often happens that I will insert a comma and then a newline after the closing `@`. But this triggers the `nonumber` snippet, replacing `@some code@,` by `@some code\nonumber`, which drives me insane.

**Describe the solution you'd like**
There should be a way of simply disabling some or all snippet. I tried using `"latex-workshop.intellisense.commandsJSON.replace"` as prescribed [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#overriding-snippets), but that has no effect and the snippet is still active.

    "latex-workshop.intellisense.commandsJSON.replace": {
      "nonumber": "",
    },

**Describe alternatives you've considered**
I tried disabling editor suggestions altogether with `"editor.quickSuggestions": { "other": false }` as mentioned [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#some--snippets-are-not-tab-completed), but that did not seem to work either.

**Comment by jlelong** [comment]
Unfortunately, snippets provided by an extension cannot be disabled, see Microsoft/vscode/issues/10565. The best you can do is to define your own snippet for `@,` .

Your issue seems to be related to the fact that hitting `Enter` accepts the proposed snippets. You can disable this by setting `editor.acceptSuggestionOnEnter: false`. With this setting, you have to use `Tab` to accept a snippet.

**Comment by LPTK** [comment]
Awesome, thanks for the quick answer!

Setting `acceptSuggestionOnEnter` seems like the most appropriate workaround. (To be honest, this is not the only case where I've experienced suggestions annoyingly getting in the way of my inserting newlines.)

Since there is nothing that can be here, I'll just close the issue.

**Comment by oiiiiiiii** [comment]
Actually, there is a way to hide the snippet you don't like. I for example disliked, that whenever I type "." a suggestion for "\dots" pops up and when I hit enter (on the end of a phrase) this snippet is inserted. To avoid this, use `CTRL+ALT+P`, search for `"Insert Snippet"`, hit enter, seach for the snippet you don't want to be shown and hit the eye-icon at the right to hide it for intellisense. 
![grafik](https://user-images.githubusercontent.com/63345269/202718465-d729217c-78c3-40f4-86fd-8d3afa5b8d36.png)
See also [https://code.visualstudio.com/docs/editor/userdefinedsnippets#_can-i-remove-snippets-from-intellisense](here)
