### ISSUE TITLE
The built files cannot save into %OUTDIR%？

### ISSUE THREAD

**Issue by mmrwizard** [James-Yu/LaTeX-Workshop#1977]
While  I add a recipe , the built files cannot save into the %OUTDIR% that I set. But if remove the recipe, it can work well.  It's been bothering me for a whole afternoon.
The json file is as shown bleow:
{
  "editor.largeFileOptimizations": false,
  "explorer.confirmDelete": false,
  "latex-workshop.latex.outDir": "%DIR%/build",
  "latex-workshop.latex.recipes": [
    {
      "name": "xelatex",
      "tools": ["xelatex"]
    }, 
    {
      "name": "xelatex->bibtex-> xelatex*2",
      "tools": [
        "xelatex",
        "bibtex",
        "xelatex",
        "xelatex"
      ]
      }
    ],
    "latex-workshop.latex.tools": [ 
      {
      "name": "xelatex",
      "command": "xelatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "-outdir=%OUTDIR%",
        "%DOC%"
      ]
    },
    
    {
      "name": "bibtex",
      "command": "bibtex",
      "args": [
        "-outdir=%OUTDIR%",
        "%DOC%"
      ]
      }],
    
      "files.autoSave": "afterDelay",
       
      "latex-workshop.view.pdf.viewer": "external", 
  
      "latex-workshop.view.pdf.external.viewer.command":"C:\\Program Files\\SumatraPDF\\SumatraPDF.exe",
      "latex-workshop.view.pdf.external.synctex.command": "C:\\Program Files\\SumatraPDF\\SumatraPDF.exe",
      "latex-workshop.view.pdf.external.synctex.args": [
        "%LINE%",
        "%PDF%",
        "%TEX%",
        "-forward-search",
        "-inverse-search",
         "code \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
      ],
  
        "latex-workshop.latex.clean.fileTypes": [
        "*.aux",
        "*.bbl",
        "*.blg",
        "*.idx",
        "*.ind",
        "*.lof",
        "*.lot",
        "*.out",
        "*.toc",
        "*.acn",
        "*.acr",
        "*.alg",
        "*.glg",
        "*.glo",
        "*.gls",
        "*.ist",
        "*.fls",
        "*.log",
        "*.fdb_latexmk"
        ],
        "editor.wordWrap": "on",
        "workbench.colorTheme": "Visual Studio Light",
        "latex-workshop.latex.autoBuild.cleanAndRetry.enabled": false,
    
  }

**Comment by jlelong** [comment]
Please post the complete logs of the extension. Do not truncate or alter them in particular if the paths contain non ascii characters.

**Comment by mmrwizard** [comment]
> Please post the complete logs of the extension. Do not truncate or alter them in particular if the paths contain non ascii characters.

The brief log is shown as:
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(g:/SWJTUFiles/others/yqqqq/texText/test.tex
LaTeX2e <2018-12-01>
(g:/program files/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(g:/program files/texlive/2019/texmf-dist/tex/latex/base/size10.clo)) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/ctex.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3-code.tex) (g:/program files/texlive/2019/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def)) (g:/program files/texlive/2019/texmf-dist/tex/latex/l3packages/xparse/xparse.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/ctexhook.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/ctexpatch.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/base/fix-cm.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/base/ts1enc.def)) (g:/program files/texlive/2019/texmf-dist/tex/latex/ms/everysel.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/config/ctexopts.cfg) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def (g:/program files/texlive/2019/texmf-dist/tex/xelatex/xecjk/xeCJK.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/base/fontenc.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/base/tuenc.def)) (g:/program files/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.cfg))) (g:/program files/texlive/2019/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg)) (g:/program files/texlive/2019/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty (g:/program files/texlive/2019/texmf-dist/tex/generic/ulem/ulem.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/cjk/texinput/CJKfntef.sty))) (g:/program files/texlive/2019/texmf-dist/tex/latex/zhnumber/zhnumber.sty (g:/program files/texlive/2019/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg)) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-chinese.def (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/config/ctex-name-utf8.cfg)) (g:/program files/texlive/2019/texmf-dist/tex/latex/tools/indentfirst.sty) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/ctex-c5size.clo) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windows.def (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windowsnew.def))) (g:/program files/texlive/2019/texmf-dist/tex/latex/ctex/config/ctex.cfg) (./test.aux) ABD: EverySelectfont initializing macros [1] (./test.aux) )
Output written on test.pdf (1 page).
SyncTeX written on test.synctex.gz.

Transcript written on test.log.
xelatex: unrecognized option `-pdf'
xelatex: unrecognized option `-outdir=g:/SWJTUFiles/others/yqqqq/texText/build'

**Comment by jlelong** [comment]
Remove the `"-pdf"` line from the xelatex command.

**Comment by mmrwizard** [comment]
> elatex command.

I removed the "-pdf" line, unfortunately it still doesn't work.  But if I remove the "latex-workshop.latex.recipes" and "latex-workshop.latex.tools",  it can set the generated file into the build folder. Is there some clash between "recipes" and %outdir%  ?

**Comment by jlelong** [comment]
>  Is there some clash between "recipes" and %outdir% ?

Of course not. Post both the logs of the extension and the logs of the compiler, once `-pdf` is removed.

**Comment by jlelong** [comment]
The logs clearly state that the option `-outdir` is not valid. I think you should use `-output-directory`.

**Comment by jlelong** [comment]
`latexmk` accepts both `-outdir` and `-output-directory` but the LaTeX compilers only accept the latter.

**Comment by mmrwizard** [comment]
> `latexmk` accepts both `-outdir` and `-output-directory` but the LaTeX compilers only accept the latter.

Thanks for your patient reply! Best wishes!
