### ISSUE TITLE
Enabling shell-escape on a project by project basis

### ISSUE THREAD

**Issue by TheoWinterhalter** [James-Yu/LaTeX-Workshop#1978]
**Is your feature request related to a problem? Please describe.**
As far as I can tell there is currently no way of setting the `--shell-escape` flag for just one LaTeX file or project the way you can select `XeLaTeX` through magic comments for instance.

Worse is that the solutions given in the wiki and many issues (#455, #913, #1043, #1147, #1810) that were posted here do not work for me (I have several errors complaining that the flag isn't set, and of course compiling from the terminal just works).

**Describe the solution you'd like**
I would like a magic comment or something similar to enable it.

**Describe alternatives you've considered**
I tried setting it globally (which I think is bad, `--shell-escape` is deactivated by default for safety reasons):

```json
"latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-shell-escape",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-outdir=%OUTDIR%",
                "%DOC%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-shell-escape",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ]
```
But it doesn't even work for me (with xelatex or pdflatex both).

Thanks for considering this.

**Comment by tamuratak** [comment]
Have you tried `% !TEX options`? See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments.

If it does not work, fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by tamuratak** [comment]
You can also use `.vscode/settings.json` to configure per workspace. See https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations.

**Comment by TheoWinterhalter** [comment]
I see, thanks! I couldn't manage to find this, I'm surprised to learn this is not the recommended way but I guess it comes down to the fact that the LaTeX environment isn't unified across IDEs.

Thanks again!
