### ISSUE TITLE
Autocompletion of image files

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [James-Yu/LaTeX-Workshop#1981]
Issue Type: <b>Bug</b>

When I try to include an image with `\includegraphics`, I see autocompletion at the root level of the file, but if images are in a directory, I don't get any autocompletion. 

FYI - I'm not sure if this is e.g. a bug with this extension, a matter of configuration, or just a feature request, so happy to move it to wherever you think it's most appropriate. 

Autocompletion **working** at the root level of the file:
<img width="660" alt="temp" src="https://user-images.githubusercontent.com/1993919/76102186-9acf4300-5f9d-11ea-9cef-5f3110b8b446.png">

Autocompletion **not** displaying files in the images folder (even though I have 7 png files in it):
<img width="274" alt="no_autocompletion" src="https://user-images.githubusercontent.com/1993919/76102193-9dca3380-5f9d-11ea-93f1-8eab0d4892a8.png">

Extension version: 8.7.2
VS Code version: Code - Insiders 1.43.0-insider (b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0, 2020-03-04T23:55:34.718Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (19.21GB free)|
|Process Argv|-psn_0_7862143|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Thank you for your cooperation.

**Comment by tamuratak** [comment]
If any progress, feel free to reopen this issue.
