### ISSUE TITLE
Autocompletion of package name is incorrect

### ISSUE THREAD

**Issue by stone-zeng** [James-Yu/LaTeX-Workshop#1984]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Not applicable

## Describe the bug [Required]

The autocompletion of package name is not correct. Currently, it's the packages' ctan name, rather than the actual file name (e.g. `foo` for `foo.sty`).

Example 1:

There is no `l3kernel` and `l3packages`.

![image](https://user-images.githubusercontent.com/18233088/76216424-8adc8b00-624b-11ea-9b58-0a6bafb0588e.png)

Example 2:

This package is actually `xeCJK`.

![image](https://user-images.githubusercontent.com/18233088/76216528-b52e4880-624b-11ea-9ea3-63dde9ef5e80.png)

Some additional feature request: please consider to add autocompletion for `\documentclass`, `\RequirePackage` and `\LoadClass` etc.

### To Reproduce

1. Create a new LaTeX document.
2. Type `\usepackage{...}`.

### Expected behavior

The autocompletion package should be parsed from file name, rather than its registered name (from ctan or texlive data).

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[21:29:50] Initializing LaTeX Workshop.
[21:29:50] Creating file watcher for .pdf files.
[21:29:50] Creating LaTeX Workshop http and websocket server.
[21:29:50] LaTeX Workshop initialized.
[21:29:51] Server created on 127.0.0.1:62544
[21:29:51] Snippet data loaded.
[21:29:51] LaTeX Workshop version: 8.7.2
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]
 - OS: macOS 10.15.3 (19D76)
 - VS Code version: 1.42.1
 - Extension version: 8.7.2
 - TeX distribution version: TeX Live 2020

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
We get the list of packages from https://ctan.org/json/2.0/packages. If you give me a list of entries to be removed, I can do it.

For the `xeCJK`, it is trickier. The issue is that the package name does not correspond to the `package.sty` name. I am not aware of any way to get the correct information. If there is, please let us know.

> autocompletion for `\documentclass`

I do not know where to find the list of all classes.

**Comment by jlelong** [comment]
The list of [packages](https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/packagenames.json) we use has 5459 entries, 2765 of which **do not** correspond to any `.sty` files on my fairly complete TeXLive installation. I suggest to only keep the entries matching a `.sty` file.

Concerning classes, the simpler approach I can think of is to create a `classnames.json` based on the `.cls` files available on my TeXLive installation.

Once these lists are sanitised, we can start to enrich them.
