### ISSUE TITLE
Improved intellisense for reference

### ISSUE THREAD

**Issue by hanzckernel** [James-Yu/LaTeX-Workshop#1985]
**Could we add more customization to the intellisense preview panel for reference?**

The reason I am raising this issue is because most of the time I use third-party software to maintain library (such as mendeley) and the auto-generated file often have unnecessary content. An example is like:

![Screen Shot 2020-03-09 at 8 29 16 PM](https://user-images.githubusercontent.com/60237900/76250103-e8b9a480-6244-11ea-84bd-9e416118b9f5.png)

which does not help to navigate through the references.

**Suggested solution** 
I am not familiar with typescript, though I would (boldly) guess by parsing the bib content as json and renders only the necessary content by passing some array to ` latex-workshop.hover.ref.style' will allow the screen renders the desired content.

The parsing of bib file has been done in many cases, for example in [bibtex-js](https://github.com/pcooksey/bibtex-js/blob/master/src/bibtex_js.js), to name up one.

**Comment by jlelong** [comment]
I do agree that the current preview shows far too much information. What about only displaying the author, title, journal (or publisher) details as in the intellisense completion? I am not sure making it configurable is worth it.

**Comment by hanzckernel** [comment]
@jlelong Thanks for response, the default value seems to be a nice pick. Maybe making configurable is going a bit too far, so setting the default value would be satisfactory enough.

**Comment by jlelong** [comment]
See the new variable [`latex-workshop.intellisense.citation.format`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisensecitationformat)

**Comment by werunom** [comment]
Thanks for this. I was about to raise the same concern. Glad to see that this has been addressed.
