### ISSUE TITLE
Latex workshop: all actions doesn't work consistently

### ISSUE THREAD

**Issue by aviadb** [James-Yu/LaTeX-Workshop#199]
### Description

Sometimes using Ctrl+Alt+L or Right click and selecting Latex workshop: all actions
doesn't open the menu of actions.
The error or warning is : Running the contributed command:'latex-workshop.actions' failed.

Restarting VScode sometimes fix this problem

### How to reproduce

1. 
2. 
3. 

### LaTeX Workshop log messages

<details>
<summary>Log messages</summary>

</details>

**Comment by James-Yu** [comment]
This is because that the extension is not fully initialized. You can wait for a few seconds before using these commands. If it cannot be initialized after minutes, please post vscode debug logs from help -> development console.

**Comment by aviadb** [comment]
Attached log

[-1500194896422.txt](https://github.com/James-Yu/LaTeX-Workshop/files/1150911/-1500194896422.txt)

**Comment by James-Yu** [comment]
We do not support insider build of vscode. Can you reproduce the problem in the public channel?
