### ISSUE TITLE
Bug for shortcut of \mathbb and \mathbf

### ISSUE THREAD

**Issue by weimiao1993** [James-Yu/LaTeX-Workshop#1990]
I tried to type \mathbb using ctrl+m, ctrl+b. But it popped up \mathbf. Also if I type ctrl+m, ctrl+s, which is supposed to pop up \mathbf, I see \mathsf instead. How can I fix it?

**Comment by tecosaur** [comment]
Try <kbd>ctrl+m</kbd> <kbd>ctrl+shift+b</kbd> for `\mathbb` :)

**Comment by jlelong** [comment]
There were typos in the wiki. Everything should be fixed now.

**Comment by jlelong** [comment]
You can always change the shortcut, see https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization
