### ISSUE TITLE
Shortcuts for snippets

### ISSUE THREAD

**Issue by weimiao1993** [James-Yu/LaTeX-Workshop#1991]
**Is your feature request related to a problem? Please describe.**
I'm using the snippets to type in math symbols. For example, `@/' for `\frac{}{}'. However, I find each time I have to press tab or enter button to select the specific snippet from a hovered window.

**Describe the solution you'd like**
Is there any way to have the snippet work as a macro of the editor? That is to say, after typing `@/', `\frac{}{}'immediately without any hovered window or selections.

**Describe alternatives you've considered**
No alternative has been found.

**Comment by tamuratak** [comment]
We can do nothing on our side. Up vote a related issue of VS Code, microsoft/vscode/issues/64135.

**Comment by tamuratak** [comment]
You can use https://github.com/tecosaur/LaTeX-Utilities
