### ISSUE TITLE
crash after compiling tex file

### ISSUE THREAD

**Issue by zxhcho** [James-Yu/LaTeX-Workshop#1992]
Issue Type: <b>Bug</b>

After I installed the LaTeX Workshop extension on vscode , crash after compiling tex file by recipe:latexmk is much more frequent, which never happens before.

Extension version: 8.7.2
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|8.00GB (1.15GB free)|
|Process Argv|-psn_0_2155022|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tamuratak** [comment]
If you are saying that VS Code itself crashes, it is a bug of VS Code. You should report this problem to the [repository of VS Code](https://github.com/Microsoft/vscode/issues).


If not, fill out all the information required in the issue template. Please paste the whole log messages, not parts of ones. 

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by tamuratak** [comment]
If any progress, feel free to reopen this issue.
