### ISSUE TITLE
My involvement in this project

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1993]
Hello All!

As I imagine you may have noticed, my involvement has somewhat tailed off over the past few months. While this started off as a simple case of me struggling to find the time to continue working on this, I have since been seduced by the insidious `org-mode` file type in a literate programming project, and have found myself dragged over to Emacs. I did not anticipate this, but it's now feeling increasingly unlikely that I will move back.

Hence, as much as I love this extension, I do not anticipate much more activity from me contributing to this project for the time being. Be assured, that should I return to VS Code you'll find me commenting on issues, and making PRs again :) In the meantime, should you have any questions/issues with code I wrote, feel free to ping me.

It's been a pleasure working with you all. Thank you all making my LaTeX experience so much better in VS Code, and being so friendly here.

All the best,

tecosaur.

_p.s. This may not be an issue, but I felt that I should probably announce this instead of just going silent._

**Comment by jlelong** [comment]
Thanks for your post and your involvement in this project!
Funny enough, I started developing for Emacs, then moved to Vim and now VSCode..... 
The most important is to have fun! Enjoy!

**Comment by tamuratak** [comment]
As an ex-Emacs user, I am glad to hear that GNU Emacs, one of the greatest software by the GNU project, is still attractive.
