### ISSUE TITLE
Can't get my recipe working

### ISSUE THREAD

**Issue by AlbanT** [James-Yu/LaTeX-Workshop#1994]
I have a script that I have used for many years in NP++ to compile my LaTeX document.
I tried to recreate it in VS Code and can't get it to work correctly.
My Original script is:
```batch
"pdflatex.exe" -interaction=nonstopmode -synctex=-1 "%~pdn1"
"bibtex.exe" "%~pdn1"
"pdflatex.exe" -interaction=nonstopmode -synctex=-1 "%~pdn1"	
"pdflatex.exe" -interaction=nonstopmode -synctex=-1 "%~pdn1"
"makeindex" -s "indexstylesheet.ist" -o "%~n1.ind" "%~n1.idx"
"pdflatex.exe" -interaction=nonstopmode -synctex=-1 "%~pdn1"
```
In the above code `%~pdn1` represents the folder + filename without .tex so I think it is `%DOC%`.
The `%~n1` is the filename without .tex so that should be `%DOCFILE%`.

I tried to recreate this in the settings.json:

```JSON
  ,"latex-workshop.latex.tools": [
  {
    "name": "pdflatex",
    "command": "pdflatex.exe",
    "args": [
      "-interaction=nonstopmode",
      "-synctex=-1",
      "\"%DOC%.tex\""
    ]
  },
  {
    "name": "bibtex",
    "command": "bibtex.exe",
    "args": [
      "\"%DOC%.tex\""
    ]
  },
    {
      "name": "makeindex",
    "command": "makeindex.exe",
    "args": [
      "-s",
      "\"indexstylesheet.ist\"",
      "-o",
       "\"%DOCFILE%.ind\"",
       "\"%DOCFILE%.idx\""
    ]
  },
    ],


    "latex-workshop.latex.recipes": [{
      "name": "MyRecipe",
      "tools": [
        "pdflatex",
        "bibtex",
        "pdflatex",
        "pdflatex",
        "makeindex",
        "pdflatex"
      ]
    }],
```

When I run this recipe it gives an error that something went wrong (I have a hard time finding a way to see what wentwrong) but the tex file compiled to a pdf but the index is missing as well as the TOC and all references to tables/images etc show up as **??**.
This probably tells me that **bibtex** and **makeindex** fails? 

Does anyone have an idea on what I'm doing wrong?

**Comment by jlelong** [comment]
Have a look at the extensions logs and the LaTeX compiler logs
![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77081172-83ab3f00-69fa-11ea-8db0-5e076d0ea3f1.png)

If you want help. Post your logs.

**Comment by AlbanT** [comment]
Thanks I missed log file :) 

I see this message on the bibtex step when I try my test.tex file:

```
[18:07:13] Recipe step 1: pdflatex, --max-print-line=10000,-interaction=nonstopmode,-synctex=-1,f:/TIJDELIJK/LaTeX/test
[18:07:13] LaTeX build process spawned. PID: 27140.
[18:07:15] LaTeX log parsed with 0 messages.
[18:07:15] A step in recipe finished. PID: 27140.
[18:07:15] Recipe step 2: bibtex, f:/TIJDELIJK/LaTeX/test
[18:07:15] LaTeX build process spawned. PID: 14304.
[18:07:16] Recipe returns with error: 1/null. PID: 14304. message: .
```

but my main tex file issues an error on the first step:

```
[18:24:20] Recipe step 1: pdflatex, --max-print-line=10000,-interaction=nonstopmode,-synctex=-1,"f:/HgRepository/EC14 - JavaScript PCI-clone/JavaScript"
[18:24:20] LaTeX build process spawned. PID: 47820.
[18:25:10] LaTeX log parsed with 423 messages.
[18:25:10] Recipe returns with error: 1/null. PID: 47820. message: .
```
The resulting PDF seems to be correct, except for the missing index and TOC and references.
The 423 messages in the compilation log only show a lot of **Overfull \hbox** and some warnings but I'm used to these as I get them when I compile in NP++ as well :)

Could it be that my script that I use in NP++ just silently continue ignoring the warnings while LaTeX-Workshop stops?

**Comment by tamuratak** [comment]
We can do nothing on our side.
