### ISSUE TITLE
latex-workshop uses old latexmk version 

### ISSUE THREAD

**Issue by lewis206** [James-Yu/LaTeX-Workshop#1995]
Hi, probably it's just me, but when I open latexmk in the terminal it says version: latexmk 4.64a 
but the latexmk that opens in vs Code is somehow version 4.41 and everything I set in my .latexmkrc is not run. 
And it's using a really old lualatex version too, my normal texlive installations runs everything without any problem. 
Do you have an idea, what I do wrong?
Thank you anyhow.

**Comment by jlelong** [comment]
This is mostly a PATH issue. The PATH inside VSCode is not the same as in your terminal. Maybe https://github.com/James-Yu/LaTeX-Workshop/issues/1414 could be helpful.

**Comment by lewis206** [comment]
You're right! Thanks a llot! Did not found that issue.
