### ISSUE TITLE
Ensure any running recipe stops before starting a new compilation

### ISSUE THREAD

**Issue by BambOoxX** [James-Yu/LaTeX-Workshop#1996]
**Is your feature request related to a problem? Please describe.**
Using `arara` for my recipe, when the recipe returns an error, I often get a large amount of non terminated compilation process if I do not pay attention to kill every one of them manually

**Describe the solution you'd like**
I would be nice that starting a new recipe automatically kills all previous hanging recipes and related tasks to avoid crowding the system with hidden useless tasks.

**Describe alternatives you've considered**
Extend the capability of the kill-process switcth to former recipes

**Additional context**
![image](https://user-images.githubusercontent.com/42067365/77246583-3e208900-6c29-11ea-9915-42f904fca1cf.png)

**Comment by tamuratak** [comment]
It is not related to the extension. `arara` should be responsible for killing the processes. That is the job of build tools.

**Comment by BambOoxX** [comment]
@tamuratak  Sorry but your answer seems a bit easy to me. It feels like `arara.exe` is killed indeed by the switch, But as it is killed, it cannot stop underlying tasks. 
I really believe that this is in the scope of the extension since when doing the same by the terminal : start `arara` and kill it with a `ctrl+c` no program remains.

**Comment by tamuratak** [comment]
No. It means that `arara` behaves differently when executed from the command line. Report to https://github.com/cereda/arara.

**Comment by BambOoxX** [comment]
@tamuratak The people developping `arara` had a look into the situation, in the linked issue. Could you have a quick look at their reaction. 

More specifically is there a way to customize the `latex-workshop.kill` action ?

**Comment by tamuratak** [comment]
They say that `arara` v5 is not supposed to be used with LaTeX Workshop and other IDEs. We can do nothing on our side.

**Comment by BambOoxX** [comment]
Sorry again, but where do you see that 
> arara v5 is not supposed to be used with LaTeX Workshop and other IDEs

Also, do you mean there is no way to modify the `latex-workshop.kill` action ?

**Comment by TheTeXnician** [comment]
Speaking from the `arara` perspective: We develop `arara` as a transparent layer that only pipes input/output. Hence, we do not see it as our task to do what you ask for.

> They say that arara v5 is not supposed to be used with LaTeX Workshop and other IDEs. We can do nothing on our side.

We did not say that and we do not want to suggest anybody not to use an IDE to work with arara. But maybe VS Code (which I do not know) is unable to achieve what other editors/IDEs (TeXworks, vim and emacs are the ones I know) get right. The formerly named editors provide a transparent input/output window for user interaction and their kill does work like it does on the command-line.

> No. It means that arara behaves differently when executed from the command line. It depends on how to handle signals. Report to https://github.com/cereda/arara.

You think it's our job to kill subprocesses but you do the following on Linux:

https://github.com/James-Yu/LaTeX-Workshop/blob/933f095c1f1cb9ceeaeae6d98f077dad2b902f4e/src/components/builder.ts#L51-L53

That is, you kill all subprocesses manually. But only on Linux. Are you sure it's consistent if a user asks why it doesn't work on Windows and you answer that it's the fault of another tool?

**Comment by BambOoxX** [comment]
@TheTeXnician, you went much further than expected :). 

@tamuratak Considering the snippet shown by TheTeXnician, something like (not sure of the exact syntax) should work, shouldn't it ?
```
if (process.platform === 'linux') { 
     cp.exec(`pkill -P ${pid}`) 
 } else {
     cp.exec(`taskkill /F /T /PID ${pid}`) 
}
```

**Comment by TheTeXnician** [comment]
@BambOoxX Sensitive birds like `arara`s do not like blaming :wink: 

The code snippet you have shown will do unexpected things on Mac OS. It will need another branch (or at least make the Windows expectation explicit).

**Comment by BambOoxX** [comment]
@TheTeXnician looking at the `process.platform` doc there is no `macos` variation. MacOS should be handled as a linux, no ? I am editing my previous answer to make the windos reference explicit.

**Comment by TheTeXnician** [comment]
No, `darwin` is Mac OS. It is based on Unix but not Linux. But maybe Mac OS has a `pkill` command (I don't know), so it might make sense to use only one branch.

**Comment by BambOoxX** [comment]
It seems there is a `pkill` on MacOS. Modified the snippet. Thanks again for the help.

**Comment by cereda** [comment]
Hello, Paulo here!

First of all, thank you very much for this amazing extension to VS Code! It's been a while since I used the editor in my Linux box (I usually stick with my `vim` setup), but I am sure I used the LaTeX Workshop extension at a certain point before. So kudos to everybody involved in the project!

I am part of the team behind `arara`, so it's interesting to see our project paths crossing, although it is a bit uncomfortable as we have an issue to tackle. However, I always take a positive approach at these situations as a great opportunity to improve code and also to gather with fellow developers who devote their time in these open source endeavours. :wink: 

Since there's an ongoing discussion, I will refrain from now, as I tend to talk too much. :wink:  This is just a friendly poke at the developers to keep up their good work and also offer our (the `arara` team) help and attention in order to provide the best user experience regarding TeX and friends.

Cheerio!

**Comment by jlelong** [comment]
I have added the snippet proposed by @BambOoxX into PR #2002. Could you try it out and let me know if it helps?

**Comment by BambOoxX** [comment]
@jlelong I personally have no idea how to test your code. I found the source in my extension directory. But once I modified the source code, the extension stopped working.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/blob/master/CONTRIBUTING.md

**Comment by BambOoxX** [comment]
Well I gues it's a bit above my paygrade :). Did the proposed step but npm complains that I have no `package.json`. Do I have to pull the sources directly in my code extension folder ?

**Comment by jlelong** [comment]
First, you have to download branch `1996-kill`: https://github.com/James-Yu/LaTeX-Workshop/archive/1996-kill.zip

Then inside `LaTeX-Workshop-1996-kill`, run `npm install --no-optional` and then follow https://github.com/James-Yu/LaTeX-Workshop/blob/master/CONTRIBUTING.md#testing-and-debugging-the-extension. Inside the new windows that pops up, open the LaTeX project you wan to test.

I hope this will help

**Comment by BambOoxX** [comment]
I am sorry, I tried to run the test, but the kill switch did not work after re-compiling the extension. I am totally unfamiliar which the debugging of such programs. I am afraid I can't be of real help here.

**Comment by BambOoxX** [comment]
@cereda @TheTeXnician A quick tip. If you try some tests with this extension and `arara`, note that your compilation rules should alway contain `options: ['-file-line-error','-max-print-line=<something big enough>']` so that the warning and error watching process works correctly. This is done by default with standard compilers but seems to be required when using `arara`.

**Comment by BambOoxX** [comment]
@jlelong I am afraid the implemented solution does not work as of LaTeX-Workshop 8.9.0.
The underlying processes below `arara` are still not killed.

**Comment by BambOoxX** [comment]
@jlelong I confirm this issue should be reopened. The modificatons made in LaTeX-Workshop v8.9.0 do not solve the problem.

**Comment by BambOoxX** [comment]
@jlelong Thanks for re-opening. Unfortunately, I still did not manage to perform tests on my side. I could just see that there are still remaining child processes when compilation fails. I will try again tomorrow.

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by BambOoxX** [comment]
@jlelong Ok, I think I managed to start debugging things. 

So I tried to see what happens in the kill switch here (where the last modifications where made in order to solve the issue). 

![image](https://user-images.githubusercontent.com/42067365/82117890-b744e400-9773-11ea-8ff9-a6ed095383cd.png)

The log output is 
>[12:45:59] LaTeX build process spawned. PID: 7444.
[12:46:06] KILL command invoked.
[12:50:54] Kill the current process. PID: 7444.
[12:50:54] Recipe returns with error: 1/null. PID: 7444. message: .

And in my task list the `arara.exe` process with PID: 7444 is killed, but not his children. Though I believe the key word here is more likely **grandchildren**. 

In fact, if extract the list of children of `arara.exe` I get 
>D:\Dz_Codes\LaTeX-Workshop>wmic process where (ParentProcessId=7444) get ProcessId,Caption
Caption      ProcessId
conhost.exe  19136
java.exe     4660

So as you can see, there is no `pdflatex.exe` here, so this compiler process is seemingly not a children but a grandchildren of the `arara.exe`.

Similar problems seems to have been reported in https://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows or https://stackoverflow.com/questions/45803129/how-to-kill-process-with-node-js.

These posts advise for the use of [tree-kill](https://www.npmjs.com/package/tree-kill) or [fkill](https://www.npmjs.com/package/fkill) to kill processes and their `((grand)^n)`-children.
However, you are probably not willing to add more packages just for this, and could not test these solutions anyway.

Nevertheless, I tried killing the `java.exe` child of `arara.exe` with the `taskkill /F /T /PID` command and everything seems to be killed as expected. 

So I guess a working sequence would be  

1. if the process is `arara.exe`
     a. get the children objects of process `pid`
     b. kill children `java.exe` and his children
2. else kill the process with the current solution

I know far too little of `node` and all this processes to translate this into extension modifications. I will however ask the `arara` developpers to have a look at it too to see if the can be of any help on this matter.

**Comment by BambOoxX** [comment]
@jlelong Another question based on a remark made by @TheTeXnician in https://github.com/cereda/arara/issues/138#issuecomment-603242488. 
Why are the compilation processes killed with the current method and not by providing a `x` when the compiler waits for input ?

**Comment by jlelong** [comment]
I am afraid we are getting far beyond the scope of the extension. 

> Why are the compilation processes killed with the current method and not by providing a x when the compiler waits for input ?

The compiling commands are  not supposed to be launch in interactive mode so that when something goes wrong, the compiler exits with an error code instead of waiting for input. See the flag `-interaction=nonstopmode` in [`latex-workshop.latex.tools`](https://github.com/James-Yu/LaTeX-Workshop/blob/3b9c6050ba5e3252001be4da24aabbd1e8b6343a/package.json#L713)

It may be appropriate to set

```
% arara: pdflatex: { interaction: nonstopmode }
```

It could be set in `.araraconfig.yaml`.

**Comment by BambOoxX** [comment]
@jlelong yes, it seems to go a bit far from the extension scope. I do not know if other LaTeX related programs could be concerned by this issue. The main problem is that `arara` starts children processes, that cannot be handled with just `taskkill` directly. 

The `-interacton=nonstopomode` key is the solution I am currently using, but when the compilation fails you cannot see where the problematic error was directly.

Do you have suggestions for me to test the `tree-kill` or `fkill` solution ? 
I tried importing these packages but then the linter complains thy cannot be loaded. 
Do I have to add some scripts to the extension folder ?

**Comment by jlelong** [comment]
> The `-interacton=nonstopomode` key is the solution I am currently using, but when the compilation fails you cannot see where the problematic error was directly.

If you also pass `-file-line-error` to the compiler, you should be able to directly see the errors in the _Problems_ pane of vscode.

**Comment by BambOoxX** [comment]
Thanks for the info on the `-interaction=nonstopmode` in `latex-workshop.latex.tools` I think I overlooked that part. 

So I guess all this is more due to the fact that by default `arara` does not apply the same compilation parameters as the ones already defined by the extension.  I agree that setting these options directly in the configuration of `arara` is the best way to go.

Just for the sake of testing, what should be the way to make `tree-kill` of `fkill` importable ?

**Comment by jlelong** [comment]
From what I understand, `arara` is assumed to work interactively. From https://gitlab.com/islandoftex/arara/-/releases/v2.0

> There's no need of noninteractive commands anymore. arara can now handle user input through the --verbose tag. If the flag is not set and the command requires user interaction, the task execution is interrupted.

See [CONTRIBUTING.md](https://github.com/James-Yu/LaTeX-Workshop/blob/e177be953f37a101dbfeb9e96f1561c08be74bfe/CONTRIBUTING.md) for how to build the extension from the git repo. This is the way to go if you want to modify the code and test it.

**Comment by BambOoxX** [comment]
@jlelong indeed, I use the `--verbose` flag to print the ouput in the ouput terminal of VSCode, in my `arara` recipe, I will remove it then.

I followed the guidelines for compilation and it seems to work, but not if I tried to load more packages e.g. `fkill` fo instance I tried

- Adding `const fkill = require('fkill');` in `builder.ts` as shown in https://www.npmjs.com/package/fkill
- Calling `fkill(pid)` instead of `cp.exec('taskkill ...')`

But upond running the extension, a new VSCode windows popsup along with this message

![image](https://user-images.githubusercontent.com/42067365/82448454-05c2ed00-9aaa-11ea-885f-c493e3d89fe6.png)
`

**Comment by jlelong** [comment]
You need to list `fkill` as a dependency in `package.json` and run `npm install` again.

**Comment by BambOoxX** [comment]
@jlelong, I just tested that but actually, both `fkill` and `tree-kill` call `taskkill` in the background. I guess there isn't much more I can think of. Thanks anyway for the informations and the extensive help.
