### ISSUE TITLE
file suggestion in subfigure

### ISSUE THREAD

**Issue by funnym0nk3y** [James-Yu/LaTeX-Workshop#1997]
When including a figure in my document with `\includegraphics` in a figure environment I get my available files suggested, which is great. But when nesting a figure environment with a subfigure and include a graphic here, nothing gets suggested. I don't know if that behaviour is on purpose, but I'd like to get suggestions everywhere I want to include graphics. 

That is a basic example of what I mean:
```
\begin{figure}
    \begin{subfigure}
       \includegraphics{file}
    \end{subfigure}
\end{figure}
```

funnym0nk3y

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by funnym0nk3y** [comment]
The log-files don't show anything out of the ordinary, otherwise I would have posted them. 

I investigated a little further and had a strange behaviour:
When typing `\includegraphics` I get two snippets suggested, `\includegraphics` and `\includgraphics[options]{name}`. When choosing the first one, everything works as intended. But the second completion does not make any suggestions, neither in a `subfigure` nor outside. 
Should I rename this issue?

**Comment by tamuratak** [comment]
Paste logs.

**Comment by tamuratak** [comment]
I cannot reproduce this issue. If any progress, feel free to reopen this issue.

**Comment by jlelong** [comment]
I do not know if it is a typo or not, but the second snippet `\includgraphics[options]{name}` contains the typo: the `e` is missing at the end of `includgraphics`. With the correct spelling, I cannot reproduce the issue.

**Comment by funnym0nk3y** [comment]
It is a typo, here a gif for clarification:
![af446702-cdd7-46de-a395-96a848998f52](https://user-images.githubusercontent.com/41870754/77428064-c80e5480-6dd7-11ea-874d-8420241f6dc1.gif)

If I type everything, it works just fine. The issue appears when selecting from the suggestions.

**Comment by jlelong** [comment]
OK, I get. Once, you have erased `name`, you need to trigger intellisense manually bit hitting `ctrl`+`space` (or `cmd` if you are on OSX). Alternatively, if you want to insert snippets with empty placeheloder, you can set [`latex-workshop.intellisense.useTabStops.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisenseuseTabStopsenabled) to `true` and intellisense is automatically triggered.

**Comment by funnym0nk3y** [comment]
Ok, thanks! I remember setting it to true, but apparently it was set to false.
