### ISSUE TITLE
View latex pdf in seperate visual studio code window

### ISSUE THREAD

**Issue by Positev** [James-Yu/LaTeX-Workshop#1998]
It would be very useful to be able to view the pdf in a new visual studio code window and have it update on save. Is this something you can implement at some point?

**Comment by tamuratak** [comment]
Choose `"browser"` at `latex-workshop.view.pdf.viewer`. https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfviewer
