### ISSUE TITLE
Pdf viewer - refresh stays in same page and zoom level

### ISSUE THREAD

**Issue by borablanca** [James-Yu/LaTeX-Workshop#2]
After I edit the tex and save, the pdf viewer refreshes but shows the first page and default zoom level. It would be nice if it stays on the same page where I was looking at (or maybe shows the page where I edited on tex file) and same zoom level after refresh.

**Comment by James-Yu** [comment]
Currently after compilation, the extension call syncTeX to identify the PDF position and scroll to that. I would recommend install syncTeX if not bundled with your TeX distribution.

The PDF viewer is the one shipped with [pdf.js](https://mozilla.github.io/pdf.js/). The said feature need investigation into the source code. It is a future improvement and I will look into it. No ETA though.

**Comment by James-Yu** [comment]
Simpler than thought to be. New version uploaded.

**Comment by borablanca** [comment]
Excelent :) Thank you
