### ISSUE TITLE
workspace settings are not applied until reopening the workspace

### ISSUE THREAD

**Issue by liyi-david** [James-Yu/LaTeX-Workshop#20]
When I try to reconfigure the plugin in the workspace settings, I find that they are not applied until I close the workspace and open it again. For example, I wanna use xelatex instead of pdflatex, so I put

    "latex-workshop.compiler": "xelatex"

in `.vscode/settings.json`, but then when I saved the file again, it was still invoking `pdflatex`.
It's not something that is quite important, but in the beginning that's a little bit annoying.

And thanks for the impressive plugin 👍 .

**Comment by James-Yu** [comment]
Yes this is as described in the README. Change config on the fly may cause some confusion to the extension so it is set as is. Sorry for the trouble caused tho.
