### ISSUE TITLE
LaTeX - Workshop colorizing code

### ISSUE THREAD

**Issue by volcompt** [James-Yu/LaTeX-Workshop#2000]
I have two windows 10 machines. In both I have installed the last version of visual studio code and the last version of LaTeX-Workshop. 

In one machine the Latex code shows up with the correct colors, whereas in the other machine it does not. See screenshots below of the first (working) example and of the second (non-working) example of the same code.

I have tried reinstalling LaTeX-Workshop but it didn't result. 

**Working example:** 
![image](https://user-images.githubusercontent.com/26249361/77435086-bf1e8280-6dd9-11ea-9e3a-058b163b5cc1.png)

**Non-working example:**
![NoColor](https://user-images.githubusercontent.com/26249361/77435155-d9586080-6dd9-11ea-9c4f-33b64aac4fcc.png)

**Comment by BambOoxX** [comment]
Did you check this ? https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#syntax-highlighting-does-not-work-for-most-elements

**Comment by volcompt** [comment]
Thanks BambOoxX. It was indeed a VScode theme problem.

**Comment by volcompt** [comment]
Thanks BambOoxX. It was indeed a VScode theme problem.

**Comment by BambOoxX** [comment]
@volcompt you're welcome, I was just passing by
