### ISSUE TITLE
Writing \\ prompts the user added snippets

### ISSUE THREAD

**Issue by BambOoxX** [James-Yu/LaTeX-Workshop#2001]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?:  Not related to document compilation

## Describe the bug [Required]

When writig `\` in a `.tex` document, the autocompletion box pops up and shows propositions as

![image](https://user-images.githubusercontent.com/42067365/77455842-ab374880-6dfa-11ea-98ee-0b3b08527b51.png)
 
 including both default and user-defined snippets , which is totally fine.

However, when writing `\\` like a linebreak the autocompletion shows what seems to me erroneous snippets including only the user-defined snippets as

![image](https://user-images.githubusercontent.com/42067365/77456105-108b3980-6dfb-11ea-801c-b2e906f0e186.png)

### To Reproduce

1. Create a custom `latex` snippet file 
3. Type `\\`

### Expected behavior

Typing `\\` should only show nothing or `\\[<height>]` as in the snippet below

```
	"\\ linebreak": {
		"prefix": [
			"\\\\",
		],
		"body": [
			"\\\\\\[${1:height}]",
			"$0"
		],
		"description": "A \\\\ linebreak."
	},
```

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.43.1
 - Extension version: 8.8.0
 - TeX distribution version: not related

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
It is not clear to me what the issue is exactly. The only thing we do inside the extension id to trigger extra snippets when `\` is entered, but `\\` deactivates this but we cannot turn off user defined sippets.
Where are all the suggestions coming from In your second screenshot?

**Comment by BambOoxX** [comment]
@jlelong What additional information should I provide ?

**Comment by BambOoxX** [comment]
In the second screenshot, all suggestions come from the `Code > User > snippets > latex.json` file. As you propose in [your post here](https://github.com/James-Yu/LaTeX-Workshop/issues/912#issuecomment-432165283)

**Comment by BambOoxX** [comment]
@jlelong I just found out that I also get weird suggestions such as below
![image](https://user-images.githubusercontent.com/42067365/77555229-4e4d9800-6eb7-11ea-94de-a42fde34f141.png)

Do you think this is due to the extension or to the general way VSCode creates suggestions ?

**Comment by jlelong** [comment]
By design, vscode intellisense list is not restricted to exact matches. Hopefully I might say. Hence your last screenshot. I will investigate the case of `\\` to see if I can deactivate intellisense for this one using 

https://github.com/James-Yu/LaTeX-Workshop/blob/93ec788a58970385cebeb3a6c2e9840e966f86af/syntax/syntax.json#L37

**Comment by BambOoxX** [comment]
@jlelong It's true it can be helpful to not only consider exact matches, but it seems weird that these results come on top of seemingly more appropriate ones, isn't it ?

**Comment by jlelong** [comment]
See https://code.visualstudio.com/docs/editor/intellisense#_suggestion-selection for more details on how intellisense entries are ordered.

**Comment by jlelong** [comment]
I investigated a bit how intellisense works and I came to the conclusion that we cannot do much about your issue. When an extension registers an intellisense provider as we do, two situations can happen: 

1. if the extension returns a non empty suggestion list, it is used to populate the intellisense popup
2. if the extension returns an empty list (this is what we do for `\\`), vscode uses the user defined snippets to populate the intellisense popup and there is no way to prevent this from the extension.

Yet, all snippets (expect `centerarc`)  in your second screenshot should already be provided by the extension. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#Commands and https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#environments. So in principle, you should not need to define these snippets yourself and it would solve your issue. Currently, it does not work with everything provided by `beamer` as we do not take into account the `documentclass` but I will fix it in the coming days.

As `\` is used an intellisense trigger by the extension, I believe you should not use it in your own snippets prefix. You could for instance use `BBL` to trigger a beamer block in the spirit of https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#Environments

I hope this helps.

**Comment by BambOoxX** [comment]
Thanks for the effort. I added some personal snippets, especially about `beamer` environments, since I am currently working on some slides. For some environments, several syntaxes are possible and I guess at that point it's a matter of taste. For instance with `frame`s

- Your snippet provides
```LaTeX
\begin{frame}
	\frametitle{}

	

\end{frame}
```
- While I'd prefer 
```LaTeX
\begin{frame}{}

\end{frame}
```
but once again, it's a personnal choice.
For others, I believe there are some syntax issues as for the `column` environment
- You provide
```LaTeX
\begin{column}
	
\end{column}
```
- But the environment should have a mandatory width argument
```LaTeX
\begin{column}{<width>}
	
\end{column}
```
If you need help checking such discrepancies for `beamer` documents (or other classes, I'm mostly working on scientific documents, or presentations and `tikz`/`pgfplots` graphics) I can provide some help.

For the time being, as I managed to circumvent the issue by adding a personnal snippet for `\\` which simply takes the form of 
```TypeScript
"\\ linebreak": {
		"prefix": [
			"\\\\",
		],
		"body": [
			"\\\\\\",
			"$0"
		],
		"description": "A \\\\ linebreak."
	},
```
so I guess the issue can be closed as it is not in you perimeter. Thanks again !

**Comment by jlelong** [comment]
For the taste questions, you can modify any snippet provided by the extension by using [`latex-workshop.intellisense.commandsJSON.replace`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisensecommandsJSONreplace)

After digging a bit, I have understood where the syntax issues on environments (such as for `column`) come from. Fixing this requires to refactor and improve the snippet mechanism for environments. I am on it.
