### ISSUE TITLE
Delay when zooming using Ctrl+Mousewheel after scrolling with the mousewheel

### ISSUE THREAD

**Issue by kjshen** [James-Yu/LaTeX-Workshop#2004]
## Describe the bug [Required]

After I use my mousewheel to scroll my document in the internal pdf viewer of LaTeX-Workshop, I cannot immediatly start zooming in and out using ctrl+mousewheel, but it has a deadtime of about 1-1,5 seconds before it starts zooming. It doesn't do anything during this time while I hold ctrl and scroll. I can zoom in immediatly after using the scrollbar to scroll. 

However, pressing Ctrl and the +/- keys is instantaneous immediately after scrolling with the mousewheel. 

### To Reproduce

1. Open the a compiled pdf with LateX-Workshops internal pdf-viewer (Ctrl+Alt+V)
2. Start scrolling with a mousewheel
3. Start holding Ctrl and continue scrolling the mousewheel

### Expected behavior
Immedate zooming as soon as I hold Ctrl.

## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.8.0], but it has behaved this way since I started using the extension a few years ago.

### Additional context
I've gotten used to the delay, but recently it started to feel sluggish to me again. I like to zoom out, scroll down the document, and zoom in again.

**Comment by jlelong** [comment]
The same happens if you use Chrome to view your pdf (by setting `latex-workshop.view.pdf.viewer: browser`). I do not think we can anything from the extension side, this is more likely an issue with [pdf.js](https://github.com/mozilla/pdf.js/issues?q=is%3Aissue+scroll+zoom) itself.

**Comment by kjshen** [comment]
Thank you for your quick feedback!
