### ISSUE TITLE
Some environment snippets lack mandatory arguments

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#2006]
This is related to the discussion in #2001 

For instance for the `column` environment in Beamer, we simply provide
```
\begin{column}
	
\end{column}
```

whereas the environment must have a mandatory width argument

```
\begin{column}{<width>}
	
\end{column}
```

We need to refactor the snippet mechanism for environment.

**Comment by tamuratak** [comment]
Notice that #1951 is related. The original template, https://github.com/LaTeXing/LaTeX-cwl/blob/master/class-beamer.cwl, includes these arguments too.

**Comment by jlelong** [comment]
Yes, I know that all the information is in the `.cwl` files, it is just that we drop it when creating the environment snippets. I will have a look at #1951 and merge it.
