### ISSUE TITLE
Additional sub-directory of intellisense for file

### ISSUE THREAD

**Issue by machsix** [James-Yu/LaTeX-Workshop#2019]
**Is your feature request related to a problem? Please describe.**
Both `graphics` and `graphicsx` support command `graphicspath`

>This optional declaration may be used to specify a list of directories in which tosearch for graphics files.  The format is as for the LATEX 2εprimitive\input@path,2
a list of directories, each in a{}group (even if there is only one in the list).  Forexample:\graphicspath{{eps/}{tiff/}}would cause the system to look in thesubdirectoriesepsandtiffof the current directory.  The default setting of thispath is\input@paththat is:  graphics files will be found wherever TEX files are found

This is a handy command making it easier to organize files. However, `latex-workshop.intellisense.file.base` seems not search these paths

**Describe the solution you'd like**
Maybe make `latex-workshop.intellisense.file.base` an array and allow user to add sub-directories to the searching path, I guess most people will only put figures in a sub-directory like `Figs`

**Comment by jlelong** [comment]
The paths listed in `\graphicspath` are taken into account for `\includegraphics` completion.

Note that any file matching one of the patterns listed in the following variables is removed from the list: `files.exclude`, `latex-wokrshop.intellisense.file.exclude`. Moreover, if `search.useIgnoreFiles` is true, any file listed in a `.gitignore` is also removed from the completion list.

To check if a file is indeed listed by a `.gitignore` file, you can run
```
git check-ignore -v full_path_to_the_file
```

**Comment by jlelong** [comment]
This is now documented in the wiki https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#files

**Comment by machsix** [comment]
![violentmonkey](https://user-images.githubusercontent.com/28209092/78274949-ef9fa400-74de-11ea-8796-f3e80f3d4cf2.gif)

I found it doesn't work if I insert a `includegraphics` first, move cursor to somewhere else, add the image path then. I attached a gif to explain it

**Comment by jlelong** [comment]
You have to manually trigger intellisense by hitting `ctrl+Space`
See https://code.visualstudio.com/docs/editor/intellisense
