### ISSUE TITLE
glossaries-swedish

### ISSUE THREAD

**Issue by AndreasNasman** [James-Yu/LaTeX-Workshop#2021]
**Is your feature request related to a problem? Please describe.**
I can't find instructions on how to include additional `glossaries` package languages.

**Describe the solution you'd like**
Be able to add [glossaries-swedish](https://ctan.org/pkg/glossaries-swedish) to my project.

**Describe alternatives you've considered**
I've tried downloading the package and manually adding the files to directory reporting the problem and a couple of other places:
`/usr/local/texlive/2019/texmf-dist/tex/latex/base/glossaries-swedish/`
`/usr/local/texlive/2019/texmf-dist/tex/latex/glossaries-swedish/`

I run on Mac OS, so I've also tried:
`~/Library/texmf/tex/latex/glossaries-swedish/`
as mentioned [here](https://tug.org/mactex/faq/faq.html#qm05).

**Additional context**
![image](https://user-images.githubusercontent.com/17124245/78198293-d112bc00-7490-11ea-8b8d-360e3dd12a74.png)

**Comment by tamuratak** [comment]
Ask at https://tex.stackexchange.com/

**Comment by AndreasNasman** [comment]
Got it working!
The correct place was
`~/Library/texmf/tex/latex/glossaries-swedish/`
just forgot running `pdflatex` on the `.ins`-file.
