### ISSUE TITLE
Follow URL from citation browser/preview

### ISSUE THREAD

**Issue by lotard** [James-Yu/LaTeX-Workshop#2022]
When in citation preview, make URL "clickable".
![image](https://user-images.githubusercontent.com/7230877/78199520-c9c3c200-7440-11ea-98bc-24d26fd9c8d4.png)

Would make it easier to use LaTeX document to check the actual content of citations without having to copy-paste links or dig through the compiled PDF. I think it used to work this way.

**Comment by jlelong** [comment]
@lotard Note that the fields showed in citation intellisense is defined by `latex-workshop.intellisense.citation.format` and has default value 

```
[
            "author",
            "title",
            "journal",
            "publisher",
            "booktitle",
            "year"
          ]
```

You may consider adding `url` to the list.

**Comment by lotard** [comment]
I already have, otherwise it won't be there in the screenshot! Thanks for the update!
