### ISSUE TITLE
Add option to not change the working directory to compile

### ISSUE THREAD

**Issue by paco-sevilla** [James-Yu/LaTeX-Workshop#2024]
**Is your feature request related to a problem? Please describe.**
Before executing the build command, the working directory is changed to the directory of the rootFile. This is done regardless of the recipe or external build command. 

However, I am using bazel to compile latex. This means that the command must be executed from the workspace directory.

**Describe the solution you'd like**
It would be nice to have a simple option to disable changing the working directory. For example a checkbox with the description "Run build command in workspace directory", which is false by default to ensure compatibility to the current settings.

**Describe alternatives you've considered**
For now, I have an created a command that changes the directory back to the workspace directory and then runs the build command from there. However, since we work in a team, this means that every person in the team must define this command depending on where the workspace directory is for them.

**Additional context**
Thank you for creating this awesome extension! 
This feature would make it even better for me and my team :)

**Comment by jlelong** [comment]
I think the external build mechanism should be what you are looking for https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#external-build-command
The command is launched from the workspace directory.
