### ISSUE TITLE
Equation hover does not work with \algnewcommand definition

### ISSUE THREAD

**Issue by pjvalla** [James-Yu/LaTeX-Workshop#2028]
###  Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required] Yes

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

If \algnewcommand is used then equation hover does not render. -- Complete file for reference:
```
\documentclass[a4paper,12pt]{article}
\usepackage[papersize={8.5in,11in}]{geometry}

\usepackage{algorithm}
\usepackage{algpseudocode}
\usepackage{amsmath}

\algnewcommand{\LineComment}[1]{\State \(\triangleright\) \emph{#1}}

\begin{document}


\begin{algorithm}[H]
    \caption{SPA Algorithm}
    % \label{alg:tap_generation}
    \begin{algorithmic}
        \State $L_j \gets \textrm{LLRs}$
        \LineComment{CN Update - Compute CN messages $L_{i \rightarrow j}$}
        \ForAll{$i \in \{0, n_c -1\}$}  \Comment{\emph{$n_c$ number of check nodes}}
            \State $L_{i \rightarrow j} = 2 \tanh^{-1} \left(\displaystyle \prod_{j'\in N(i)- \{j\}} \tanh \left(\frac{1}{2} L_{j' \rightarrow i} \right) \right)$
        \EndFor
    
        \LineComment{VN Update - Compute VN messages $L_{j \rightarrow i}$}
        \ForAll{$j \in \{0, n_v -1\}$} \Comment{\emph{$n_v$ number of variable nodes}}
            \State $L_{j \rightarrow i} = L_j + \sum_{i' \in N(j) - \{i \}} L_{i' \rightarrow j}$
        \EndFor
        \LineComment{LLR Total}
            \ForAll{$j \in \{0, n_v-1\}$}
                \State $L_j^{\textrm{total}} = L_j + \sum_{i \in N(j)}L_{i \rightarrow j}$
            \EndFor
        \LineComment{Run for $I$ iterations or until convergence}
    \end{algorithmic}
    \end{algorithm}

\end{document}
```
If you replace the line ```\algnewcommand{\LineComment}[1]{\State \(\triangleright\) \emph{#1}}``` with 
```\newcommand{\LineComment}[1]{\State \(\triangleright\) \emph{#1}}```.  Then equation rendering works as expected.

**Comment by jlelong** [comment]
The preview is rendered by mathjax, which does not understand the `\ algnewcommand` command. We cannot do much about it.
You can use `latex-workshop.hover.preview.newcommand.parseTeXFile.enabled` and  `latex-workshop.hover.preview.newcommand.newcommandFile` to add extra definitions for preview only. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#previewing-equations
