### ISSUE TITLE
`\let` breaks MathJax preview

### ISSUE THREAD

**Issue by dimitriye98** [James-Yu/LaTeX-Workshop#2035]
Minimal example:
```latex
\documentclass{article}

\let\test\approx

\begin{document}
    $\test$
\end{document}
```

![image](https://user-images.githubusercontent.com/1576330/79095770-2613c500-7d10-11ea-8ccc-4652ba37cfa3.png)

I'm not sure why this is, as MathJax does "support" `\let` as an alias for `\newcommand`. However, even if this can be resolved, there's a more fundamental issue which will break most actual uses of `\let` in LaTeX code. As mentioned, MathJax treats `\let` as a `\newcommand` alias. However, `\let` is supposed to expand its replacement expression at declaration time. This means that redeclarations of the form
```latex
\let\test\approx
\renewcommand{\approx}{\test\test}
```
will crash MathJax's rendering engine anyway.

The solution I'd propose is twofold. Fix whatever is throwing off the MathJax handling of `\let` (or simply perform the alias on the plugin's end, either or), but moreover, replace any `\renewcommand` declaration with a newcommand with a unique generated symbol, e.g. the above would become
```latex
\let\test\approx
\newcommand{\approxLATEXWORKSHOP[random alphabetical identifier here]}{\test\test}
```
or some such (with uses thereof appropriately replaced) allowing MathJax to render it correctly.

**Comment by dimitriye98** [comment]
So while looking at old issues and pull requests to start working on a solution, I quickly stumbled upon this: https://github.com/James-Yu/LaTeX-Workshop/issues/1877

I'm pretty sure it's the exact same problem as is stopping `\let` from working, but of course, solving that problem doesn't solve the bigger problem of `\let`'s expansion time.

**Comment by dimitriye98** [comment]
So, as the latex-utensils issue has been de-prioritized, I'm going to try and see how this can be fixed on LaTeX-Workshop's end for now. Luckily, `\let` commands follow a pretty strict format, which basically means they'll have one of two AST representations when spit out by latex-utensils:

```json
{
  "kind": "command",
  "name": "let",
  "args": []
},
{
  "kind": "command",
  "name": "test",
  "args": []
},
{
  "kind": "text.string",
  "content": "="
},
{
  "kind": "command",
  "name": "approx",
  "args": []
}
```
or the same, but with the `=` sign missing.

Since MathJax considers `\let` to be an alias for `\newcommand` anyway, it should be a simple matter to convert the above to
```json
{
  "kind": "command",
  "name": "newcommand",
  "args": [
    { "kind": "arg.group", "content": [ { "kind": "command", "name": "test", "args": [] } ] },
    { "kind": "arg.group", "content": [ { "kind": "command", "name": "approx", "args": [] } ] }
  ]
}
```
Now, as for translating `\renewcommand` definitions to new tokens to avoid throwing MathJax into an infinite recursion, it *should* be fairly simple, since one can just detect any such commands in the AST representation, alter them to a `\newcommand` definition with a unique identifier, and then add them to a translation table, and then walk through the AST redirecting any succeeding command calls to the redefined command to the new unique identifier.

I'll try and look into this later today if I have time.

**Comment by jlelong** [comment]
The parsing of new commands is done in

https://github.com/James-Yu/LaTeX-Workshop/blob/62f341588af363fa43d61f1d48a3c1f906df57a5/src/providers/preview/mathpreview.ts#L93-L102

Note that the AST representation is parsed node by node. Handling new definitions split over several consecutive nodes would require a major refactoring of this part and I do not think it is worth it. Hence the solution to #1877.

Have you considered using the variable [`latex-workshop.hover.preview.newcommand.newcommandFile`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandnewcommandFile). You could copy paste all your `\let` statements in there.

**Comment by dimitriye98** [comment]
> Have you considered using the variable [`latex-workshop.hover.preview.newcommand.newcommandFile`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandnewcommandFile)? You could copy paste all your `\let` statements in there.

Which would solve the `\let` problem itself, but I wouldn't be using `\let` if I wasn't using `\renewcommand`, adding proper support for which will likely require substantial code due to MathJax's limitations. As a bandaid measure: perhaps a setting to disable the passing of only `\renewcommand` declarations to MathJax? In my experience `\renewcommand` redefinitions *usually* have identical semantics to the old definition, they merely fiddle with the styling. That's how I use them, and that's how most code I've seen uses them. So simply stripping them should yield cleaner output than leaving them in in most cases, until proper support for them is added.

And uh, the `for` loop there to me looks actually quite conducive to the change I wanted to add.
`ast.content` is a simple array, so a change could look along the lines of
```ts
for (let i = 0; i < ast.content.length; i++) {
  const node = ast.content[i];
  if (latexParser.isCommand(node) && node.name === 'let' && node.args.length === 0) {
    let token = ast.content[i + 1]
    let aliasTarget = ast.content[i + 2]
    if (aliasTarget.kind === 'text.string') {
      aliasTarget = ast.content[i + 3]
      i += 3
    } else {
      i += 2
    }
    // Code to inject let command into MathJax here
  } // else ...
}

**Comment by jlelong** [comment]
I do not really understand what your issue with `\renewcommand` is.

**Comment by dimitriye98** [comment]
@jlelong I thought there was an issue with MathJax's order of expansion for `\let` which would break newcommand, since I'd tested the same test code from earlier on the MathJax live demo and it was breaking it. Turns out MathJax does process `\let` properly, there was just a bug in the MathJax live demo as well, not in MathJax itself.

So that part's actually a non-issue. It's just a question of putting in a fix to make LaTeX-Workshop parse `\let` and it'll work properly. I'll work on getting a PR in sometime this week.

**Comment by tamuratak** [comment]
Please notify us if any progress.
