### ISSUE TITLE
Automatically convert the first letter of sentence to uppercase like Microsoft Word

### ISSUE THREAD

**Issue by Jieli12** [James-Yu/LaTeX-Workshop#2036]
### New feature request

This seems to be a new feature. I have not found any solution for latex-workshop in vscode environment. Would you please help me to add this new feature, I just tried to transform sublime-user to vscode-user gradually.

### Description

The expected solution satisfies the following conditions:
1. Only automatically convert lower letter to upper letter in **text mode** within **latex file**
2. Capitalisation of the first letter of a new sentence after punctuation '.' or starting a newline
3. Escape the combinations like i.e., i.i.d., etc
4. If the cursor is at the first place of a new line, when one input non-letter symbols, it should not affect the other functions, for instance, when I input "\\" at the beginning of a new line, it should pop-up intelligence hint as usual.
5. no snippets or key-bindings

### Alternative method
In sublime text, I have fond a solution, please refer to this: https://github.com/SublimeText/LaTeXTools/issues/1444

I appreciate anyone who offers comments and suggestions.

**Comment by jlelong** [comment]
I am sorry to say that I think this is beyond the scope of this extension.
