### ISSUE TITLE
Sumatra PDF  cannot start  inverse search command Please check the command line in setting

### ISSUE THREAD

**Issue by honghanchenchh** [James-Yu/LaTeX-Workshop#2038]
Any one can help me?
I'v tried all kinds of settings, the forward-search works! 
but he inverse-search doesn't work at all, It waste my too much time.
Is there any other pdf viewer for latex workshop?
VSCODE version 1.44.0,  CTex latest version, Sumatra PDF latest version

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

### To Reproduce

3. See error

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by BambOoxX** [comment]
Here are my settings for `SumatraPDF`

```
"latex-workshop.view.pdf.external.viewer.command": "SumatraPDF",
  "latex-workshop.view.pdf.external.viewer.args": [
    "%PDF%",
  ],
  "latex-workshop.view.pdf.external.synctex.command": "SumatraPDF",
  "latex-workshop.view.pdf.external.synctex.args": [
    "-forward-search",
    "%TEX%",
    "%LINE%",
    "-reuse-instance",
    "-inverse-search",
    "\"Code.exe\" \"C:\\Users\\<username>\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -g \"%f\":\"%l\"",
    "%PDF%"
  ],
```

**Comment by jlelong** [comment]
Have you tried https://github.com/James-Yu/LaTeX-Workshop/wiki/View#windows

You can also use the internal PDF viewer https://github.com/James-Yu/LaTeX-Workshop/wiki/View#internal-pdf-viewer

**Comment by jlelong** [comment]
You can also look at #1268
If you need more help, please fill the issue template with the logs and reopen the issue.

**Comment by BambOoxX** [comment]
I ran into the same recurrent problem after updating SumatraPDF to v3.2 (though it may be unrelated). Here are my new settings.  Note the the **absolute path to Code.exe** seems to be required instead of just `code`.

```
  "latex-workshop.view.pdf.external.synctex.args": [
    "-forward-search",
    "%TEX%",
    "%LINE%",
    "-reuse-instance",
    "-inverse-search",
    "C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code\\Code \"C:\\Users\\<user>\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -g \"%f\":\"%l\"",
    "%PDF%"
  ],
```
