### ISSUE TITLE
The `PATH` reported from `latex-workshop` is not the same with the `PATH` from fish shell

### ISSUE THREAD

**Issue by fengyuentau** [James-Yu/LaTeX-Workshop#2041]
## Preliminary questions [Required]
I use fish shell. `mactex-no-gui` is installed via `brew`. When trying to compile my latex project in VS Code, I got an error: `Recipe terminated with fatal error: spawn latexmk ENOENT.`. And in the `Output` tab of `latex-workshop`, it reports a `Does the executable exist?` error with an `PATH` printed which does not include the directory to the mactex (/Library/TeX/texbin/). However, I can see the path to mactex is included in the `PATH` from fish shell (`echo $PATH` in fish shell).

Which `PATH` this extension is using? I solved this issue by `PATH=$PATH:/Library/TeX/texbin/ code mylatexproject`. Is it a VS Code problem instead of this extension's? Any workarounds to solve this issue so that I do not need to set the `PATH` every time I run VS Code or set an alias?

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

I don't know whether this is a bug. Please see the Preliminary questions section.

### To Reproduce

1. Install fish shell.
2. Install `mactex-no-gui` via `brew`.
3. Run VS Code in fish shell.
3. Compile an latex project and see error.

## Logs [Required]

```
[21:28:12] Initializing LaTeX Workshop.
[21:28:12] Creating file watcher for .pdf files.
[21:28:12] Cannot run pdflatex to determine if we are using MiKTeX
[21:28:12] Creating LaTeX Workshop http and websocket server.
[21:28:12] LaTeX Workshop initialized.
....
[21:28:13] Building root file: /path/to/my/project/main.tex
[21:28:13] Build root file /path/to/my/project/main.tex
[21:28:13] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/path/to/my/project/,/path/to/my/project/main
[21:28:13] cwd: /path/to/my/project
[21:28:13] LaTeX build process spawned. PID: undefined.
[21:28:13] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
[21:28:13] Does the executable exist? PATH: /usr/local/Caskroom/miniconda/base/bin:/usr/local/Caskroom/miniconda/base/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

### LaTeX Workshop Output [Required]

```
See Above.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]
 - OS: MacOS Catalina Version 10.15.4
 - VS Code version: 1.44.1
 - Extension version: 8.8.0
 - mactex-no-gui: 2020.0407

### Are you using LaTeX Workshop with VS Code Remote?

No.

### Additional context
No.

**Comment by tamuratak** [comment]
LaTeX Workshop never touches PATH.  See https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable.

**Comment by fengyuentau** [comment]
@tamuratak I guess this issue is something related to the fish shell. I used to use `zsh`. Everything is good until I change to fish shell. BTW, I have checked the wiki. Nothing helps me with this issue.

**Comment by tamuratak** [comment]
The initialization of environment variables on macOS is not well-documented on official documents from Apple. And, `fish` seems not to work well with it. 

We can do nothing on our side. You  can use a workaround of overriding `PATH` with the `env` property of LaTeX recipes.  https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable

**Comment by tamuratak** [comment]
Related to https://github.com/microsoft/vscode/issues/30847#issuecomment-420399383

**Comment by tamuratak** [comment]
- microsoft/vscode/issues/21655
- fish-shell/fish-shell/issues/4336
- https://github.com/fish-shell/fish-shell/blob/e4b64448facdc619f2063cfa9888cbb25f13a8bf/share/config.fish#L194
