### ISSUE TITLE
The shortcut cmd+P gets overtaken by the pdf preview and triggers printing

### ISSUE THREAD

**Issue by jcvtieck** [James-Yu/LaTeX-Workshop#2043]
**Is your feature request related to a problem? Please describe.**
The shortcut cmd+P gets overtaken by the pdf preview and triggers printing.

**Describe the solution you'd like**
Be able to disable cmd+P for printing on the pdf preview.

**Describe alternatives you've considered**
Config file?

**Additional context**
The same mechanism that is used to allow other keyboard shortcuts on the pdf preview.
For example cmd+shift+P works as expected.
Only cmd+P is hijacked by the pdf preview.

Thanks!

**Comment by jlelong** [comment]
Duplicate of #2016
It will be included in the next release.

**Comment by jcvtieck** [comment]
cool!
thanks.
