### ISSUE TITLE
"Indenting" sections so they become subsections and vice versa

### ISSUE THREAD

**Issue by phdoerfler** [James-Yu/LaTeX-Workshop#2044]
**Is your feature request related to a problem? Please describe.**
I find myself changing frequently whether parts of a larger document should be their own chapter or just a section or maybe even just a subsection of an existing section.

**Describe the solution you'd like**
I want a command which will move the section the cursor is currently residing in "up" or "down" one step at a time, including its subsections and subsubsections etc.
This would change a `\section` into a `\chapter` or a `\subsection`.
Think indenting bullet point lists with **Tab** and **Shift+Tab**. I want to do this for sections, chapters, subsections, etc.

**Describe alternatives you've considered**
I have tried the package [coseoul](https://www.ctan.org/pkg/coseoul), but I'd rather still have `\section{Something}` and be able to "indent" it (and the content it contains) further, so it becomes a `\subsection`.
As a reference, this is what using `coseoul` can look like:

```latex
\documentclass{ scrartcl }
\usepackage { coseoul }
\begin { document }
\levelstay{Corynopuntia} % main
\leveldown { Grusonia aggeria } % sub
\levlestay{Grusonia agglomerata} % sub
\levlestay { Grusonia bulbispina } % sub
\end { document }
```

**Comment by jlelong** [comment]
I have the impression that you are looking for https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#promotingdemoting-sectioning-levels

**Comment by phdoerfler** [comment]
Oh my, yes indeed! Thank you for pointing this out, I was completely unaware of this!
