### ISSUE TITLE
Keymappings on OSX

### ISSUE THREAD

**Issue by flindeberg** [James-Yu/LaTeX-Workshop#2045]
**The issue**

I find the keymaps on OSX quite confusing, they seem to view `ctrl` and `cmd` as equal across the board. This is very counterintuitive since ctrl should be ctrl, while cmd usually plays the role of meta. 

Note the keyboard layouts (note also the weirdness of alt on Windows keyboards):

`ctrl - winkey - alt`

`ctrl - option - cmd`

Or more general:

`ctrl - super - meta`

I.e. translation table (in my world):

Domain | Left | Middle | Right
--- | --- | --- | ---
General | `ctrl` | `super` | `meta`
Mac |  `ctrl` | `option` | `cmd`
Win |  `ctrl` | `winkey` | `alt`
Sun | `ctrl` | `alt` | `meta`

**My solution**

When going from general keys to OS X remap `alt` to `cmd`, `winkey` to `option` and leave `ctrl` as it is. 

**Rationale**

It seems like many view `ctrl` and `cmd` as equal due to the Windows copy and paste shortcuts, when `ctrl` is still `ctrl` on both systems and paradigms, it just happens that `ctrl + c` etc is already bound on OSX (`ctrl + c` specifically is `ETX` and `ctrl + v` is `SYN`, and is on Windows as well in classical applications such as the command prompt. AFAIK Windows took `ctrl + c` etc from Xerox).

**Comment by jlelong** [comment]
The convention adopted by vscode is to use `Cmd` on OSX whenever `ctrl` is used on Windows or Unix. See https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf
