### ISSUE TITLE
Behaviour of click on PDF viewer's scroll bar.

### ISSUE THREAD

**Issue by FMuro** [James-Yu/LaTeX-Workshop#2048]
**Is your feature request related to a problem? Please describe.**
In the PDF viewer, when I click on the scroll bar it doesn't go to the precise place where I'm clicking, unlike in the code editor. It rather scrolls a bit up or down, depending on whether you click above or below the current position.

**Describe the solution you'd like**
I understand that the PDF viewer is the same one as FIrefox's (is it called pdf.js?). Therein, the behavior is like in VSCode's text editor, or like in the Firefox PDF viewer.

**Describe alternatives you've considered**
None.

**Additional context**
If my explanations are not clear enough I could maybe upload a video? Let me know.

**Comment by tamuratak** [comment]
We can do nothing on our side

**Comment by FMuro** [comment]
Thanks for your prompt answer! Where should I report this? Is this directly a VSC issue?
