### ISSUE TITLE
Intellisense for expl3

### ISSUE THREAD

**Issue by joulev** [James-Yu/LaTeX-Workshop#2051]
**Is your feature request related to a problem? Please describe.**
`expl3` commands are much longer than that of normal LaTeX. They also contains the underscore, which is a "word-separator" in VSCode, so the automatic "word-auto-suggestion" doesn't help. So, when coding in `expl3`, one often has to type the whole command manually. It is really time-consuming.

**Describe the solution you'd like**
The auto-suggestion feature added to `expl3`.

**Comment by jlelong** [comment]
Could you post a minimal example for me to understand what you would like? I am not familiar with `LaTeX3`. The underscore should not be a problem.

**Comment by joulev** [comment]
A short example: (if you compile this, looking at the log file you will see `> \l_foo_int=5.`.)

```tex
\documentclass{article}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\cs_new:Npn \foo_bar_baz:nnn #1 #2 #3
  {
    \int_set:Nn #3 { #1 + #2 }
  }
\int_new:N \l_foo_int
\foo_bar_baz:nnn { 1 } { 4 } \l_foo_int
\int_log:N \l_foo_int
\ExplSyntaxOff
\end{document}
```

[`\ExplSyntaxOn` and `\ExplSyntaxOff` can be anywhere, it is not necessary to put them inside `document`.]

If you want to intellisense only what is already defined (like in normal LaTeX2e), you have to put all of `expl3` functions to the intellisense engine. That is [a BIG list](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/l3kernel/interface3.pdf). Also you have to detect all new functions and variables declared by the user. This is not hard, but the list of all "defining" commands like `\cs_new:Npn` is another giant list. So I suggest not to do so. Perhaps you should only intellisense all variables and functions used by the user between `\ExplSyntaxOn` and `\ExplSyntaxOff`.

In addition, I think adding the argument pattern to the auto-suggestion in `expl3` is not really necessary, although it is pretty straightforward (`n` is a braced argument, `N` is an one-token argument, etc. &ndash; full list can be seen in Section 1 of `interface3.pdf` linked above).

A demonstration of my suggestion:

```tex
% Nothing is put to the auto-suggestion array (is it an array?)
\cs_new:Npn \foo_bar_baz:nnn #1 #2 #3 
% Push \cs_new:Npn and \foo_bar_baz:nnn to the array
  {
    \int_set:Nn #3 { #1 + #2 }
% Push \int_set:Nn to the array
  }
\int_new:N \l_foo_int
% \int_new:N and \l_foo_int are pushed
\foo_bar_baz:nnn { 1 } { 4 } \l_foo_int
% Both commands are already pushed and ready for use.
\int_log:N \l_foo_int
% \int_log:N are pushed
```

Currently I have to use "word-autosuggestion" in each "group" of the function, which is of course not what we want.

![image](https://user-images.githubusercontent.com/44609036/80323690-273c0a80-8857-11ea-8fa5-6c9c6d4dcf9d.png)

**Comment by jlelong** [comment]
I will look at it in more details. 

In standard LaTeX, we rely on https://github.com/LaTeXing/LaTeX-cwl to build intellisense for commands based on the used packages. However, No such list seems to be available for the `expl3` package. As you suggest, we should probably only rely on variables and functions used by the user. This should not be too hard to implement. What is the regex to match a LaTeX3 function or variable

```
\\[a-zA-Z_]*:[a-zA-Z]
```
Is the `:` mandatory? Should we restrict what comes after `:`to the list defined in [interface3.pdf](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/l3kernel/interface3.pdf) I - 1?

If I understand well, LaTeX3 stuff must be surrounded by `\ExplSyntaxOn ... \ExplSyntaxOff` and the rest of the file is only LaTeX2.

**Comment by joulev** [comment]
> I will look at it in more details.

Great!

> 
> In standard LaTeX, we rely on https://github.com/LaTeXing/LaTeX-cwl to build intellisense for commands based on the used packages. However, No such list seems to be available for the `expl3` package.

Actually there is at least one available. You can look at the index of interface3.pdf. It is extremely long though, and the conversion from the index to a format that VSCode can understand requires great efforts.

> As you suggest, we should probably only rely on variables and functions used by the user. This should not be too hard to implement. What is the regex to match a LaTeX3 function or variable
> 
> ```
> \\[a-zA-Z_]*:[a-zA-Z]
> ```
> 
> Is the `:` mandatory?

No, it is not. `:` is mandatory in function names, while variable names must *not* contain `:`. I am not very good at regex, but one can use this to match things: LaTeX3 functions and variables are just like LaTeX2e commands, but it also allows `:` and `_` (`:` can be used only once and `_` can not be used after `:`).

Perhaps this regex will do?

```
\\[a-zA-Z\_]*(:[a-zA-Z]*)?
```

> Should we restrict what comes after `:`to the list defined in [interface3.pdf](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/l3kernel/interface3.pdf) I - 1?

I am not really sure. That part (called the *signature* of the function) is pretty short, the user can do manually. If you want to implement this, you need to distinguish variables and functions so that only functions will be worked on. Moreover as you can see in the index of interface3.pdf, each function only allows some certain signatures. And then we have `\cs_generate_variant:(Nn|cn)`, which produces more signatures for functions. These stuff can lead to unnecessary complication.

> 
> If I understand well, LaTeX3 stuff must be surrounded by `\ExplSyntaxOn ... \ExplSyntaxOff` and the rest of the file is only LaTeX2.

Exactly!

**Comment by jlelong** [comment]
Thanks for the explanations on how `:` and `_` can be used in LaTeX3 functions and variables. Your regexp looks good to me.

From the index file generated when compiling `interface3.tex`, I have managed to extract a [list of commands](https://gist.github.com/jlelong/9a49e2bc806f076905f6030faa052cdc). It is quite long but I am confident it could be used as a default starting list for intellisense. Let me know i f you think the file should be pruned a bit.

**Comment by joulev** [comment]
@jlelong Impressive! That list is perfection!

**Comment by joulev** [comment]
@jlelong I have just had a close look. Although the list looks really nice, some index entry are included while they should not be. For example,

https://gist.github.com/jlelong/9a49e2bc806f076905f6030faa052cdc#file-expl3-commands-txt-L1119-L1132

```
\par}|hdclindex{14}{usage}}{10}
\par}|hdclindex{16}{usage}}{11}
\par}|hdclindex{18}{usage}}{11}
\par}|hdclindex{20}{usage}}{11}
\par}|hdclindex{22}{usage}}{12}
\par}|hdclindex{24}{usage}}{12}
\par}|hdclindex{26}{usage}}{12}
\par}|hdclindex{28}{usage}}{13}
\par}|hdclindex{30}{usage}}{13}
\par}|hdclindex{32}{usage}}{13}
\par}|hdclindex{34}{usage}}{14}
\par}|hdclindex{36}{usage}}{14}
\par}|hdclindex{38}{usage}}{14}
\par}|hdclindex{618}{usage}}{158}
```

They should not be there obviously.

A quick search gives me 17 such results in total.

**Comment by joulev** [comment]
And I think normal LaTeX2e commands that are included, like `\pdfescapestring`, should be removed as well, except `\ExplSyntaxOn` and `\ExplSyntaxOff`.

**Comment by jlelong** [comment]
You are right. Looking closely, I think any entry not containing `:` or `_` should be removed (73 matches + your 17). I think it is best to enrich the list later if needed.
I have pruned the list.

**Comment by jlelong** [comment]
I have not completely made up my mind on the best way to include intellisense for LaTeX3. Making use of the existing mechanisms in LW, the simplest approach would be to associate the [expl3-commands](https://gist.github.com/jlelong/9a49e2bc806f076905f6030faa052cdc#file-expl3-commands-txt) to the `expl3` package.

@joulev is it reasonable to assume that a LaTeX3 file always uses the `expl3` package or is included in a file that does so?

**Comment by joulev** [comment]
> the simplest approach would be to associate the expl3-commands to the expl3 package.

That is sensible to me.

> is it reasonable to assume that a LaTeX3 file always uses the expl3 package or is included in a file that does so?

Most of the time, yes. However, the user may load `expl3` *indirectly*. For example, I rarely use `\usepackage{expl3}`; I use `\usepackage{xparse}`, which automatically loads `expl3`, so that I can use both `expl3` and the features of `xparse`.

**Comment by jlelong** [comment]
@joulev I have started a PR to enhance LaTeX3 support #2071 
It would help me a lot if you could try this on going development version and let me know if you find any issue.

**Comment by joulev** [comment]
@jlelong It works wonderfully!

However, I guess the list should still be truncated even more. Five variables with `foo` in it, namely `\c_foo_regex`, `\l_foo_clist`, `\l_foo_int`, `\l_foo_seq` and `\l_foo_str`, are not built-in variables so they should not be in the list (they are only used in the example, that is why they appears in the index).

**Comment by joulev** [comment]
There is a weak point though, but I don't think this can be resolved in an easy fix: there are *function variants* in LaTeX3. Simply put, they are functions having the same name but different signatures. An [extreme] example:

![image](https://user-images.githubusercontent.com/44609036/81282727-c518ac00-9085-11ea-977e-e36a07642b5e.png)

(page 39 of interface3.pdf). `\tl_set:Nn` has 11 variants, so the user can use any of the 12. However only the "original" variant, `:Nn`, is indexed, so a large number of variants is missing in the list.

However, tracing these variants is not trivial. As they are not indexed, there are no lists available to parse.

Here I suggest two solutions:

* Leave it as it is. If the user uses a variant, that variant will be automatically included, so the user only has to type manually in the first instance of that variant.
* Parse the sources of interface3.pdf, i.e. all the `*.dtx` files that you finds in `source/latex/l3kernel` of your texmf tree: You look at the part inside `documentation` environment (parsing outside it will result in internal functions being included). Find the `function` environments. They should be something like this:

    ```
    % \begin{function}{\clist_new:N, \clist_new:c}
    %   \begin{syntax}
    %     \cs{clist_new:N} \meta{comma list}
    %   \end{syntax}
    %   Creates a new \meta{comma list} or raises an error if the name is
    %   already taken. The declaration is global. The \meta{comma list}
    %   initially contains no items.
    % \end{function}
    ```
    
    Now take all functions listed in the argument of `function` to the list. In this case, `\clist_new:N` and `\clist_new:c`.

The second is rather a complicated process, so if you uses the first one, it is okay. What do you think?

**Comment by jlelong** [comment]
@joulev thanks for your feedback. 
I will move your last two posts to #2071. It will be easier to follow if comments and commits are linked on the same post.

**Comment by joulev** [comment]
>  I suggest to continue the discussion there.

Okay 😃.
