### ISSUE TITLE
"Open Next/Previous Editor" from PDF viewer skips a tab

### ISSUE THREAD

**Issue by samestep** [James-Yu/LaTeX-Workshop#2055]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

If I switch to a PDF file using a keyboard shortcut and then also use a keyboard shortcut to run either `workbench.action.nextEditor` or `workbench.action.previousEditor` to switch away from the PDF viewer, the adjacent tab is skipped.

### To Reproduce

1. Open the following tabs, in order:
   1. A text file.
   2. A text file.
   3. A PDF.
   4. A text file.
   5. A text file.
2. Use the keyboard shortcut <kbd>Alt</kbd>+<kbd>3</kbd> to switch to the third tab.
3. Use whatever keyboard shortcut is bound to either "View: Open Next Editor" or "View: Open Previous Editor" (<kbd>Ctrl</kbd>+<kbd>PageDown</kbd> or <kbd>Ctrl</kbd>+<kbd>PageUp</kbd> by default, respectively).
4. Note that you are now on either tab 1 or tab 5.

### Expected behavior

I expected that the above steps would switch to tab 2 or 4 (adjacent to the PDF tab). This expected behavior occurs if either of the following are done instead of following the above reproduction steps exactly:
- In step 2, click on the third tab instead of switching to it using a keyboard shortcut.
- In step 3, run the next/previous editor command directly from the "Show All Commands" palette instead of using a keyboard shortcut.

### LaTeX Workshop Output [Required]

```
[12:13:05] Initializing LaTeX Workshop.
[12:13:05] Creating file watcher for .pdf files.
[12:13:05] Creating LaTeX Workshop http and websocket server.
[12:13:06] LaTeX Workshop initialized.
[12:13:06] Server created on 127.0.0.1:35317
[12:13:06] LaTeX Workshop version: 8.9.0
[12:13:06] Snippet data loaded.
[12:13:06] PDF command invoked.
[12:13:06] Serving PDF file at http://localhost:35317/viewer.html?file=pdf..JTJGaG9tZSUyRnNhbSUyRnNhbmRib3glMkZjdHJsdGFiJTJGZmlsZTMucGRm
[12:13:06] The encoded path is /home/sam/sandbox/ctrltab/file3.pdf
[12:13:06] Open PDF tab for /home/sam/sandbox/ctrltab/file3.pdf
[12:13:06] Handle data type: open
[12:13:06] Preview PDF file: /home/sam/sandbox/ctrltab/file3.pdf
[12:13:06] Handle data type: request_params
[12:13:06] Handle data type: loaded
[12:13:15] LOG command invoked.
```

### Developer Tools Console [Required]

```
[Embedded Page] PDF 647a490e89d573ae024cb6193a3786e4 [1.7 3-Heights(TM) PDF Optimization Shell 4.8.25.2 (http://www.pdf-tools.com) / Microsoft Word] (PDF.js: 2.3.200)
```

## Screenshots

![file1](https://user-images.githubusercontent.com/8246041/80511588-4cf60c00-894a-11ea-831c-d34d58034874.png)
![file2](https://user-images.githubusercontent.com/8246041/80511598-4f586600-894a-11ea-85fa-59ddbd366108.png)
![file3](https://user-images.githubusercontent.com/8246041/80511604-51222980-894a-11ea-8bb5-201fbe80b261.png)
![file4](https://user-images.githubusercontent.com/8246041/80511612-53848380-894a-11ea-9ae4-2c369ea257b1.png)
![file5](https://user-images.githubusercontent.com/8246041/80511617-554e4700-894a-11ea-914c-7b89a2505c9c.png)

## Desktop [Required]
 - OS: Ubuntu 18.04.4
 - VS Code version: 1.44.2
 - Extension version: 8.9.0
 - TeX distribution version: TeX Live 2017

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
This looks like #2023 and is mostly not related to the extension

**Comment by samestep** [comment]
@jlelong I saw that issue as I was attempting to debug this, but as far as I can tell it doesn't seem to really be the same (although I could very well be wrong) since that one was apparently fixed by upgrading to VS Code 1.43.2, which is the version I am currently using. Or am I misunderstanding?

**Comment by jlelong** [comment]
I cannot reproduce your issue with vscode 1.44.2

**Comment by samestep** [comment]
@jlelong I just updated to 1.44.2 and am still seeing the same issue. I edited the original post.

**Comment by tamuratak** [comment]
Please down grade to LaTeX Workshop v8.7.2. Check whether you still see this issue. 

You can see how to install the old version at https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#install-older-version

**Comment by samestep** [comment]
@tamuratak That fixes the issue!

**Comment by tamuratak** [comment]
Enabling the keyboard shortcuts on PDF viewers is tricky since the PDF viewers are implemented with `iframe` in `WebView`. See https://github.com/microsoft/vscode/issues/65452#issuecomment-586036474. It seems that we do not need this trick on Linux.

I will disable the following rebroadcasting keyboard events on Linux:

https://github.com/James-Yu/LaTeX-Workshop/blob/9cdc1e7e96b6e983558477b2d8b5f3c460b06314/src/components/viewer.ts#L192-L199

I am not sure this change works fine on all the Linux distributions.

**Comment by timfayz** [comment]
> Please down grade to LaTeX Workshop v8.7.2. Check whether you still see this issue.
> 
> You can see how to install the old version at https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#install-older-version

Thank you for the suggestion, it saved a day! Using Workshop 8.10.0 with VSCode 1.46.0 made the previewer impossible to use again (no tab switching at all + zoom is reset every time you open a terminal or menu bar by pressing Alt).

**Comment by tamuratak** [comment]
Please open a new issue.

**Comment by tamuratak** [comment]
Change this option: https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewerpdfinternalkeyboardevent
