### ISSUE TITLE
Codicon on the menu and dropping the support for old VS Codes < v1.42

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2058]
[Codicon](https://code.visualstudio.com/updates/v1_42#_codicons-for-reuse) on the menu looks good. However, it requires VS Code 1.42.0 or later. Can we drop the supports for VS Code 1.41.0 or prior?

![スクリーンショット 2020-04-30 9 44 49](https://user-images.githubusercontent.com/10665499/80660727-7ee0ad00-8ac7-11ea-903b-a3cf8439a319.png)

You can try it on https://github.com/tamuratak/LaTeX-Workshop/tree/codicon_menu

**Comment by jlelong** [comment]
I think it is good practice to always run the latest stable version of a soft so I would not mind dropping the support of `vscode < 1.42`. However, I am afraid that some large computer parks may run an older version of vscode. I am aware of some still running vscode `1.41.1`.

**Comment by tamuratak** [comment]
Hmm, let's leave it pending for a while.

**Comment by tamuratak** [comment]
It will not be implemented in the near future, so I close.

**Comment by jlelong** [comment]
It seems we are now ready to drop `vscode < 1.42`, so  https://github.com/tamuratak/LaTeX-Workshop/tree/codicon_menu could be merged.

**Comment by tamuratak** [comment]
I think we should also use `debug-start` rather than `rocket` on the toolbar  since we should use the same icon on both the menu and the toolbar, and `debug-start` is consistent with `debug-stop`. 

If VS Code provides `task-start` and `task-stop` icons, we should use them. However, it doesn't.

**Comment by jlelong** [comment]
@tamuratak Feel free to change the build icon in the editor title bar to match the toolbar.

**Comment by tamuratak** [comment]
Closed in 1acdd400f8f83939b130b2d67c11f5dbbc422dc3.
