### ISSUE TITLE
Syntax Highlight Problem

### ISSUE THREAD

**Issue by yu961549745** [James-Yu/LaTeX-Workshop#206]
Hi, I have found these statements would cause a syntax highlight problem, and all codes follow them would have a wrong highlight.

```
\newcommand {\be} {\begin{equation}}
\newcommand {\ee} {\end{equation}}
```

**Comment by James-Yu** [comment]
Sorry but this problem cannot be fixed with the current syntax highlight grammar adopted by vscode, afaik. This problem should also exists in other editors, such as Atom and ST3.
