### ISSUE TITLE
same line \begin, \end behavior is counterlogical

### ISSUE THREAD

**Issue by ArborealAnole** [James-Yu/LaTeX-Workshop#2061]
When embedding an environment within a single line such as `\begin{bmatrix}0\\0\\1\end{bmatrix}` LaTeX Workshop unnecessarily de-indents the line upon typing the second `{`. If the line is then re-indented manually, Workshop will indent the subsequent line once more than the current line's indentation. Can Workshop be made to instead detect that the `\begin` matching the `\end` is on the current line and therefore not de-indent?

**Comment by jlelong** [comment]
It is not clear if we really fix this in the extension. Indentation is handled by vscode itself, see https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules

It is easy to come up with regex that skip `\begin...\end` pairs on a single line. I will think of it

**Comment by jlelong** [comment]
Ensuring that the line after `\begin{bmatrix}0\\0\\1\end{bmatrix}` is not indented is now properly fixed. This should also work fine with nested `\begin`s. For instance, a single indentation is issued after

```
\begin{equation}\begin{cases} x \\ y \end{cases}
```

However, ensuring that the `\end{` in `\begin{bmatrix}0\\0\\1\end{bmatrix}` does not decrease indentation is more delicate. There is no way to detect that a `\end` is preceded by the matching `\begin`. I hope only matching `^\s*\\end{` will make everyone happy. Btw, this is approach used by the `html` mode, 

https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/client/src/htmlMain.ts#L200

**Comment by ArborealAnole** [comment]
Thank you for the quick attention. This solution should work well for my purposes.
