### ISSUE TITLE
Snippet alternatives with built in labels

### ISSUE THREAD

**Issue by rlh1994** [James-Yu/LaTeX-Workshop#2065]
**Is your feature request related to a problem? Please describe.**
Having moved over from using Sublime Text as my default LaTeX editor, I've found the default snippets lack an automatic `\label` feature which made it very easy to just add new sections/subsections automatically and not require manual labelling each time. It also provided a comment line showing the end of that section which was useful but not as much.

**Describe the solution you'd like**
An alternative set of some of the key snippets that provide a default label command to make e.g.
SSEL would generate the following, with the main cursor in the section brackets, but also put the same text in the label (with spaces replaced by underscore). Comment line is optional. Once entered the user would press `TAB` and the cursor be on line 3 in this example.
```latex 
\section{}  
\label{sec:}

% section section_name end 
```
The same approach could be taken with others as well such as subsections and chapters.

**Describe alternatives you've considered**
Adding my own manual snippets, but though if I would find it useful maybe others would as well.

**Additional context**
N/A

**Comment by jlelong** [comment]
There a re two kinds of intellisense for inserting new sections

- the snippets defined in [snippets/latex.json](https://github.com/James-Yu/LaTeX-Workshop/blob/71f2251f8e027ec622f2bb6f122d31e886bba61c/snippets/latex.json). It could be possible to define some additional snippets using other prefixes such as `SSEL`, `SSSL`, `SS2L`, ... that would insert the new sectioning command along with the `\label` command. The transformation of ` ` into `-` is feasible but not so obvious https://github.com/microsoft/vscode/pull/51621#issuecomment-403939223 Note in particular that you have to deactivate autosuggestion inside snippets.

- the LW intellissense provider when hitting `\`. There we could add a configuration variable to control whether to add the label or not. All this would require a real development effort. I would suggest an upvote approach. Vote on the first post if you would like to see the feature implemented.

**Comment by rlh1994** [comment]
I agree the first one makes the most sense and has the benefit of the less development. I don't think there's really a way around the autosuggestion problem, although in this case as it's new sections/subsections I guess there isn't much of a use case anyway.

I was playing around and the following seems to work, with the replacement happening once the user completes snippet (if they click out rather than use tab the replacement will not take place).

```json
"section_label": {
		"prefix": "SSEL",
		"body": "\\section{$1} \n\\label{${1/[ ]/_/g}} \n$0 \n% section ${1/[ ]/_/g} end ",
		"description": "Start a new section with a label attached"
	},
```

**Comment by jlelong** [comment]
For this to work, you need to set `editor.suggest.snippetsPreventQuickSuggestions` to `true`, but then https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-nest-snippets

As a consequence for the time being, I will let you add the snippets to your own configuration.
