### ISSUE TITLE
Intellisense not triggered automatically in autocompleted \autocite[]{} snippet

### ISSUE THREAD

**Issue by flimofly** [James-Yu/LaTeX-Workshop#2066]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
When the snippets `\autocite[]{}` and `\autocites[]{}` are autocompleted, Intellisense is not triggered automatically when the user TABs to the `{}` (although it can be triggered manually there using Ctrl+Space). 

For a GIF showing this, see this old thread: https://github.com/James-Yu/LaTeX-Workshop/issues/744#issuecomment-415865769
Intellisense _is_ triggered automatically when `{` is (re-)typed manually. Intellisense also _is_ triggered automatically in other commands that are part of the biblatex package, such as `\cite[]{}` and `\textcite[]{}`. 

### To Reproduce

1. Type `\au...`
2. Select `\autocite[]{}`
3. Use TAB to move to `{}`

### Expected behavior
On completing Step 3, the inline dropdown list showing bibkeys (or VS Code browser, depending on the settings) should be shown automatically. 

## Logs [Required]

Logs do not show anything.

### Developer Tools Console [Required]

```
No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

## Screenshots

See GIFs in the Issue #744

## Desktop [Required]
 - OS: OS X 10.15.4
 - VS Code version: 1.44.2
 - Extension version: 8.9.0
 - TeX distribution version: Miktex 2020
### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
I cannot reproduce the issue. I am a bit puzzled by your steps to reproduce. In 2, you write select `\autocite[]{}` and in 3, use `TAB` to move to `{}`, but when selecting `\autocite[]{}` the cursor automatically jumps into `{}`. 

Automatic completion cannot happen after hitting `TAB` to select the next placeholder.

**Comment by flimofly** [comment]
That's not the case for me. Here is a GIF I just made: 
![Screen-Recording-2020-05-02-at-20 57 45](https://user-images.githubusercontent.com/20085376/80873348-33d9bc00-8cb8-11ea-9d25-bd8117712252.gif)

**Comment by jlelong** [comment]
There is something wrong in there. I think I get it. The `\autocite` entry in your completion list comes from the previous uses of `\autocite[]{}` whereas it should come from the list of commands provided by the `biblatex` package. Make sure you have `\usepackage{biblatex}` in your document.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#Commands for how command intellisense works.

If none of this helps, try to make a minimal working example.

**Comment by flimofly** [comment]
Thanks! `\usepackage{biblatex}` was in the preamble, but for some reason `latex-workshop.intellisense.package.enabled` was not set to `true` in the Settings. 

This issue may thus be closed.
