### ISSUE TITLE
Beamer SyncTex offset needs special treatment

### ISSUE THREAD

**Issue by tonypottera24** [James-Yu/LaTeX-Workshop#2068]
Currently, the SyncTex offset is fixed in the middle.

This caused a serious problem when previewing beamer since the anchor is always at the bottom of the slides.

Therefore, it would be great if the offset of SyncTex in the preview is adjustable or smartly adjust for beamer document type.

**Comment by jlelong** [comment]
> This caused a serious problem when previewing beamer since the anchor is always at the bottom of the slides.

This reason of this is explained in josephwright/beamer/issues/121
