### ISSUE TITLE
How to format LaTeX files

### ISSUE THREAD

**Issue by bl4ck5un** [James-Yu/LaTeX-Workshop#2069]
Thanks for the great tool. This is a general question rather than an issue so please point me to the right place for questions if it's not here.

How does one format LaTeX files? There is no key binding etc according to https://github.com/James-Yu/LaTeX-Workshop/wiki/Format.

**Comment by tamuratak** [comment]
See https://code.visualstudio.com/docs/getstarted/keybindings#_rich-languages-editing

**Comment by bl4ck5un** [comment]
i see. that's most helpful.
