### ISSUE TITLE
Offer vsix download for releases

### ISSUE THREAD

**Issue by vonAlenberg** [James-Yu/LaTeX-Workshop#2070]
**Is your feature request related to a problem? Please describe.**
I want to run this awesome extion with other platforms (like Theia / code-server). To integrate this extension automatically a vsix file is needed.

**Describe the solution you'd like**
Offer a vsix file with each release.

**Describe alternatives you've considered**
Other options are (1) downloading vsix from another site (insecure) or (2) installing it manually (bad is it shall be deployed in a docker container).

**Comment by jlelong** [comment]
The vsix file is available from https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop _Download Extension_  in the *Resources* menu on the right hand side
