### ISSUE TITLE
Latex workshop causes 100% CPU use

### ISSUE THREAD

**Issue by eirianop** [James-Yu/LaTeX-Workshop#2073]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

I believe this issue is caused by hung pdflatex processes, and happens when there is a document error (pdflatex awaits user input). So in this case no, I cannot compile manually. But I am cross-checking LaTeX workshop compilation with a manual makefile.

## Describe the bug [Required]

pdflatex processes cause 100% CPU load. This seems to happen when an error occurs, and  pdflatex is wanting user interaction

It is not clear to me why a hung process would blow up the cpu load, perhaps LaTeX-workshop is trying to recover somehow and causes high load.

### To Reproduce

write invalid LaTeX and save the document

### Expected behavior
pdflatex processes should be terminated after some set  timeout. You can see this in htop  or OS X's activity monitor

## Screenshots

will provide next time I run into this

## Desktop [Required]
 - OS: OS X 10.15.3
 - VS Code version: 1.45.0
 - Extension version: 8.9.0
 - TeX distribution version: TeX 3.14159265 (TeX Live 2019)

### Are you using LaTeX Workshop with VS Code Remote?

I tried using with VS Code  Remote  to see if I would still get this issue, so I tried both ways.

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote SSH/
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

I have no problems with cpu I kill pdflatex

possible dups: 
https://github.com/James-Yu/LaTeX-Workshop/issues/763
https://github.com/James-Yu/LaTeX-Workshop/issues/1260

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by eirianop** [comment]
do log files persist if VS Code is closed? I have had to force quit over this. 

If so, I will share logs the next time I run into the issue, which is easy to reproduce as per my steps
