### ISSUE TITLE
Add a magnifying glass to the pdf reader

### ISSUE THREAD

**Issue by EmilVogt** [James-Yu/LaTeX-Workshop#2076]
**Is your feature request related to a problem? Please describe.**
While working on a document, usually I have the .tex file next to the .pdf file. While the .tex file usually takes most of the space, sometimes it's important to check a detail in the PDF. Resizing the window for the PDF or zooming into the PDF is however annoying.

**Describe the solution you'd like**
I know from TeXstudio, that a magnifying glass is quite useful. Pressing and holding the mouse in the PDF creates a circle in which the content shows up magnified.

**Describe alternatives you've considered**
As said, resizing the window or zooming in also does the job.

**Additional context**
If needed, I can attach a picture of the feature in TeXstudio.
I don't know if this functionality is a limitation of the PDF reader you're using.

Thank you for your time.

**Comment by tamuratak** [comment]
It will not be implemented in the near future, so close it.
