### ISSUE TITLE
Formatting failed with exit code null

### ISSUE THREAD

**Issue by xiangchen2011** [James-Yu/LaTeX-Workshop#2077]
## Preliminary questions [Required]
Formatting failed with exit code null
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

The log of the plugin is `Formatting failed with exit code null`.
When I run the command in the terminal, the response is `[1]    74484 segmentation fault  latexindent  '    '`

### To Reproduce

3. See error

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[18:21:40] Found root file from active editor: /Users/xiangchen2011/Desktop/code/learn_latex/main.tex
[18:21:40] Root file remains unchanged from: /Users/xiangchen2011/Desktop/code/learn_latex/main.tex.
[18:21:50] Formatting with command latexindent -c,/Users/xiangchen2011/Desktop/code/learn_latex/,/Users/xiangchen2011/Desktop/code/learn_latex/__latexindent_temp.tex,-y=defaultIndent: '    '
[18:21:50] Formatting failed with exit code null
[18:21:50] stderr: 
```

### Developer Tools Console [Required]

```
[Extension Host] [vscode-icons] v10.1.1 activated!
workbench.desktop.main.js:sourcemap:2876 Formatting failed. Please refer to LaTeX Workshop Output for details.
workbench.desktop.main.js:sourcemap:1642   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

## Screenshots

[Screenshot](https://imgur.com/CquIUEU)

## Desktop [Required]
 - OS: [e.g. MacOS 10.12]
 - VS Code version: [e.g. 1.45.0]
 - Extension version: [e.g. 8.9.0]
 - TeX distribution version: [e.g. TeX Live 2018]

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment]
This issue is not related to LaTeX Workshop. You have not installed latexindent properly.

> When I run the command in the terminal, the response is [1] 74484 segmentation fault latexindent ' '

See

- https://latexindentpl.readthedocs.io/en/latest/index.html
- https://latexindentpl.readthedocs.io/en/latest/appendices.html#manually-installed-modules
