### ISSUE TITLE
Use $HOME in latexindent args

### ISSUE THREAD

**Issue by alanlivio** [James-Yu/LaTeX-Workshop#2078]
**Is your feature request related to a problem? Please describe.**
I would like to use a yaml file to configure the latexidennt.
Using a full path works in the latex-workshop.latexindent.args.
But it doesn't work when using a $HOME variable.
See example bellow.

```
  "latex-workshop.latexindent.args": [
    "-c",
    "%DIR%/",
    "%TMPFILE%",
    "-l=$HOME/.conf/latexindent.yaml",
  ],
```

**Comment by tamuratak** [comment]
Why do you want use `$HOME`?  You know what is your $HOME directory.

**Comment by xsanda** [comment]
@tamuratak as an example, so the same configuration file can be used between users or computers?

**Comment by tamuratak** [comment]
I am not convinced. 

You can also use `indentconfig.yaml` and ` localSettings.yaml`.

See
- https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#indentconfig-yaml-and-indentconfig-yaml
- https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html#localsettings-yaml

**Comment by alanlivio** [comment]
Thanks @xsanda My intention was that, use between computers.

"You can also use indentconfig.yaml and localSettings.yaml."
I tried `~/.indentconfig.yaml`  and `~/indentconfig.yaml`  both not worked.
