### ISSUE TITLE
amsthm is missing in data/packagenames.json 

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2082]
`amsthm` is missing in `data/packagenames.json`. `amsthm` itself exists in https://ctan.org/json/2.0/packages. Something is wrong. 

It should be documented how files in `data/` have been generated.

**Comment by jlelong** [comment]
Getting a proper list of package names is not so obvious, see #1987 

The main issue is that the name of a package does not always match the name of the main `.sty` file, which is the one we are actually interested in for `\usepackage` completion. This is currently achieved by parsing the `texmf/ls-R` file of my TeXLive installation based in the fact that a `package` listed in https://ctan.org/json/2.0/packages is installed in `some/path/package/` and there I check if `package.sty` is listed.

The issue with `amsthm` is that it is provided by the AMS class and is installed as `amscls/amsthm.sty`. I had not thought of this when I designed the script. I will look at it and write a short documentation on how all this works.

**Comment by tamuratak** [comment]
#1987 is #1984?

**Comment by jlelong** [comment]
Yes, that was #1984 
I have updated my comment.
