### ISSUE TITLE
List of labels in the side pane

### ISSUE THREAD

**Issue by FMuro** [James-Yu/LaTeX-Workshop#2089]
**Is your feature request related to a problem? Please describe.**

Not a problem, rather a possible improvement.

**Describe the solution you'd like**

The structure view on the left lists sections and such. It's really nice to quickly navigate between them. Sometimes I wish to navigate through theorems and the like. For that, it would be nice to fit labels in the structure pane. I'd list them under the section where they're included.

**Describe alternatives you've considered**

This feature is part of Emac's RefTeX, but I don't think I'm not going back any time soon.

**Additional context**

**Comment by jlelong** [comment]
I am not sure to understand how helpful it would be considering that labels are already automatically completed inside `\ref` alike functions. Moreover, it would make the outline much longer, which might not be good when one wants to get an overview of the document.

Could you expand a bit on what you have in mind if you think it would indeed help?

**Comment by FMuro** [comment]
Let me share a couple of pics (from internet) illustrating how this looks like in WinEdt:

![REgBa](https://user-images.githubusercontent.com/17141976/82457772-1da06e00-9ab6-11ea-94c9-b118e5a3acb6.png)

and, very similar, in TeXstudio:

![8zeFr](https://user-images.githubusercontent.com/17141976/82457813-2d1fb700-9ab6-11ea-8151-d95b1d209ca7.png)

TeXmaker and Kile do this exactly as TeXstudio. Emacs organizes labels within the section hierarchy, you can view it in [this video](https://www.youtube.com/watch?v=-Tyn0sgXt9s&t=285s). 

The main purpose, in my opinion, is quickly browsing the document, as the outline. Not necessarily related to completion. You may want to review the important parts of your document, remember how you organized the results, remember the contents of a few theorems or equations, etc. For instance, I do such things when I restart working on a project which I haven't opened in a while. It need not overload the outline if it is folded by default (e.g. Emacs) or if it is in a separate explorer group (WinEdt, TeXstudio, etc.).

**Comment by jlelong** [comment]
That is clearer. I will think of the best way to implement this.

**Comment by FMuro** [comment]
Thanks! Sorry that I wasn't clear enough at the beginning. Please, let me know if I can help with anything (not too technical, for lack of ability).

**Comment by FMuro** [comment]
You guys are really receptive and very fast answering. Thanks a lot!
