### ISSUE TITLE
xelatex

### ISSUE THREAD

**Issue by kookma** [James-Yu/LaTeX-Workshop#209]
### Magic comments still have problem

Building the following minimal example in Latex-Workshop

```
% !TEX program = xelatex

\documentclass[12pt]{article}
\usepackage{fontspec}
\setmainfont{Times New Roman}
\begin{document}
 This an \textit{example} of document compiled 
 with \textbf{xelatex} compiler. LuaLaTeX should 
 work fine also.
\end{document}
`
results in error. Part of log file is given below:

### Log file
```

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX) (preloaded format=pdflatex 2017.6.14)  28 JUL 2017 01:21
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
`
### Expected behavior
It seems LaTex-Workshop ignore the magic comment and does not use xelatex. It uses pdflatex

**Comment by James-Yu** [comment]
Can you please share your toolchain setting in your configuration?

**Comment by kookma** [comment]
@James-Yu 
James, I just used the default configuration. Latex-Workshop dos the good job for pdflatex. I tried different tests, but when when you force it to use xelatex or lualatex, by magic comments, it fails. Log files shows it ignores the magic comments and still uses the pdflatex

**Comment by James-Yu** [comment]
The usage of magic comment is recorded in README. It just does not work out of the box, which really lacks customization ability.

For short, you should leave `command` as blank (`''`). The toolchain auto replace the blank with the compiler. Arguments will be inherited.

**Comment by kookma** [comment]
Thank you! It works now!

**Comment by arisliang** [comment]
How to open the configuration?

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#settings
