### ISSUE TITLE
MathJax extensions support

### ISSUE THREAD

**Issue by Einlar** [James-Yu/LaTeX-Workshop#2092]
**Is your feature request related to a problem? Please describe.**
Math preview does not support many commands I use on a regular basis, such as `\pdv`, `\dv`, `\bra`, `\ket`, `\colorbox`, etc. However, all of these are already supported by MathJax, by loading [existing extensions](http://docs.mathjax.org/en/latest/input/tex/extensions/index.html).

**Describe the solution you'd like**
A way to load [MathJax extensions](http://docs.mathjax.org/en/latest/input/tex/extensions/index.html), so that their commands will be rendered in math preview. This could be controlled by an extension's setting, providing a list of all extensions to be loaded.

**Describe alternatives you've considered**
I've considered to simply add `\newcommand`s, basically redefining the commands I need. However this is tedious, and in certain cases entirely impossible (only one-line new commands are supported, and things like `\colorbox` are unavailable).

**Additional context**
![image](https://user-images.githubusercontent.com/24481570/82129154-0c5b1700-97c1-11ea-839c-08c08d42cb50.png)

**Comment by tamuratak** [comment]
It will not be implemented in the near future, so close it.
