### ISSUE TITLE
Set default recipe by name

### ISSUE THREAD

**Issue by rick3rt** [James-Yu/LaTeX-Workshop#2095]
It would be nice to be able to set a specific recipe for a workspace, other than just the options `"first"` and `"lastUsed"`.

So if I have the following recipes (in global user settings):
```
"latex-workshop.latex.recipes": [
        {
            "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        },
        {
            "name": "pdflatex ➞ biber ➞ pdflatex × 2",
            "tools": [
                "pdflatex",
                "biber",
                "pdflatex",
                "pdflatex"
            ]
        }
],
```
then it would be convenient if I could set the default recipe to the name of one of the defined recipes in the workspace `settings.json`:
```
"latex-workshop.latex.recipe.default": "pdflatex ➞ biber ➞ pdflatex × 2"
```
(or maybe not the name but the number, but I guess name is more convenient.)

**Comment by jlelong** [comment]
I guess this is sufficient to properly set `latex-workshop.latex.recipes` in your workspace preferences so that the first recipe is the desired one. Have you already considered using a tool like `latexmk`, which already handles all kinds of dependencies and bibliographies transparently, so need to change the recipe?

**Comment by rick3rt** [comment]
Indeed setting `latex-workshop.latex.recipes` in the workspace works, but it just seemed more logical to me to set `latex-workshop.latex.recipe.default` in a workspace, then to copy an 'entire' recipe. I.e. the `recipe.default` setting did not fully do what I expected. 

`latexmk` does not always work with biber/biblatex in my experience, and fails compiling most of the time (plus I use Miktex right now, and don't have perl installed).

**Comment by jlelong** [comment]
I tend to agree with you that being able to set the name of the default recipe would be easier but adding an extra setting does not make sense and would undoubtedly conflict with the current `latex-workshop.latex.recipe.default` setting. Changing the definition of `latex-workshop.latex.recipe.default` would break backward compatibility.

I am afraid there is no perfect solution here.

**Comment by rick3rt** [comment]
Alright thanks for your response. I understand that backwards compatibility is important, and a new setting indeed does not make sense. 

However, looking at [`src/components/builder.ts:416`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/builder.ts#L416), I guess that the case where you would check for matching recipe names could be easily added, whilst maintaining the option to use 'lastUsed' or 'first'. I am not that familiar with TS/JS and vscode extensions to give it a try myself unfortunately.

**Comment by jlelong** [comment]
You are right. It should be possible to alter the current `latex-workshop.latex.recipe.default` setting while preserving compatibility. I will give a try
