### ISSUE TITLE
Completion for options of minted package

### ISSUE THREAD

**Issue by phdoerfler** [James-Yu/LaTeX-Workshop#2098]
I have used this extension quite a lot in the past months and I'd like to give back a little!
I'm still pretty new to VS Code extension development, so maybe I'm misjudging the scope of my idea. Please let me know your thoughts!

What I have in mind is completion support for the options of the minted package. I figured this might be an easy thing to contribute. I.e.,

```latex
\inputminted[firstli<ctrl+space>
```

would then offer to complete `firstli` to `firstline=` and do the same thing for the other macro options in the minted package.

Thanks for this wonderful extension and again, hit me with your feedback, please!

**Comment by jlelong** [comment]
Hmm, easier said than done unfortunately. There is currently no way to define a list of possible completion values for a command (optional) argument. That would be awsome!

**Comment by tamuratak** [comment]
A list of options is available `cwl` files in the `TexStudio` repository.

- https://github.com/texstudio-org/texstudio/blob/master/completion/minted.cwl

**Comment by jlelong** [comment]
Unfortunately, GPL 3.0 stuff cannot be included in a project with MIT licence.
Yet, there is no licence on https://github.com/LaTeXing/LaTeX-cwl where the `.cwl` files we use come from and the commit message states they have been generated by the TexStudio project...

Anyway to go back to the original, my point was not to get the list of available values but rather to integrate this new mechanism inside LW. I have to think about it.

**Comment by James-Yu** [comment]
Here we go with #3579. Finally returned to here.

<img width="656" alt="Screenshot 2022-12-16 at 15 52 03" src="https://user-images.githubusercontent.com/4210342/208049934-66cbdc58-8ba6-4e07-80eb-0388305111cc.png">
