### ISSUE TITLE
Icon instead of text for "Show Preview"

### ISSUE THREAD

**Issue by DFelten** [James-Yu/LaTeX-Workshop#21]
It would be great if we could replace the text "Show Preview" with an icon. This would cost less space. The other buttons at this point also have only icons and no text.

![image](https://cloud.githubusercontent.com/assets/1169185/23654076/65355fc2-032f-11e7-861c-30c9a64b256e.png)

**Comment by James-Yu** [comment]
Can you please provide an example of extension that has an icon at this position? I have tried but vscode won't recognize the octicon syntax.

**Comment by bartosz-antosik** [comment]
Hi,

Arduino VSCode extension seems to be adding two icons to a .cpp file type:

![vscode-arduino-extension](https://cloud.githubusercontent.com/assets/20492548/23904268/8522f860-08c7-11e7-8241-f47b2bafad29.jpg)

**Comment by James-Yu** [comment]
I've tried using the same schema as did in the said extension, yet the icon won't show up in the title bar. 
Can you please provide the version info of your vscode?

**Comment by bartosz-antosik** [comment]
![vscode-about](https://cloud.githubusercontent.com/assets/20492548/23939981/8afe7970-0963-11e7-9251-a160c7bd8353.JPG)

**Comment by James-Yu** [comment]
Got the right way to set it. Will publish soon.

**Comment by bartosz-antosik** [comment]
Damn it! Just came to tell you that I have recreated it in my extension and it seems to work! My intention was to describe what I did... Never mind. :-)
