### ISSUE TITLE
Proposal - BIDI language support

### ISSUE THREAD

**Issue by kookma** [James-Yu/LaTeX-Workshop#210]
### RTL and bi directional (BIDI) language support

The LaTeX-Workshop helps many people to enjoy their TeX document preparation in a modern editor like VSCode. This is a big step forward.

The LaTeX-Workshop is a great tool. I think it needs to be improved. One feature requested is its support for right to left language or RTL and bidirectional texts.
There are a crowd of TeX users need right to left language (RTL) in their daily document preparation. These languages are Persian/Farsi, Hebrew, Arabic,..

I wish to know if possible LaTeX Workshop can support this feature.

**Comment by James-Yu** [comment]
Can you please elaborate more on the topic? What should be achieved but is not working now? AFAIK, text processing under the hood is handled by either VSCode or LaTeX compiler.

**Comment by kookma** [comment]
James,
 Please see this page for a complete description

https://github.com/Microsoft/monaco-editor/issues/280

**Comment by James-Yu** [comment]
I have briefly checked the issue. IMO we need to wait for vscode/monaco support before adding additional supports to the extension. 
I will leave this issue open for now and see how microsoft/community is handling the other issue.

**Comment by amiraliakbari** [comment]
I think there is no blocking problem in using VSCode and this extension for writing RTL documents. Although the VSCode editor is not optimal for writing RTL documents, and has shortcomings such as the mentioned bug, but it can be used without much problem.

Persian LaTeX documents mostly use `xepersian` CTAN package, which require `xelatex` that is not the default in LaTeX-Workshop. Simply by adding the following settings, I am able to typeset RTL document like the attached image. So I think this issue can be closed unless a specific problem regarding RTL support is reported. Thanks for your great extension.

```
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-xelatex",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%.tex"
            ]
        }
    ],
```

![screenshot_20180417_213641](https://user-images.githubusercontent.com/336772/38885227-87b7db36-4287-11e8-8b0d-01f4d1cc39a4.png)

**Comment by kookma** [comment]
The problem is with editor to support RTL writing not with the latex output. VSCode supports unicode, so you can type Persian or other RTL language but it is not an easy task.

**Comment by amiraliakbari** [comment]
The editor supports RTL writing, although it has a few bugs in rendering the text. Anyway I just wanted to clarify the issue and point out that there is no problem with this specific extension. You should wait for the mentioned issue in the monaco-editor to resolve, and meanwhile you can use VSCode even for RTL text like many users do - tolerating the inconveniences.

**Comment by James-Yu** [comment]
I'm closing this issue for cleanness. Also this relies on the editor to provide RTL support.
