### ISSUE TITLE
Entering a space does not hide suggestions.

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2101]
For example, after entering `E \in F`, completion items are still displayed at the current master. The space seems to match completion items.

![May-19-2020 19-24-52](https://user-images.githubusercontent.com/10665499/82315719-ae1f7580-9a06-11ea-8290-80030f2786a9.gif)

**Comment by tamuratak** [comment]
We should set
```typescript
commitCharacters: [' ']
```
for each completion items.

- https://code.visualstudio.com/api/references/vscode-api#CompletionItem

**Comment by jlelong** [comment]
You are right. This is because some commands in the `data/` files contain spaces in their arguments

**Comment by jlelong** [comment]
An other approach would be to exclude the arguments from the `CompletItem.filterText` field and to only keep the command name. It is not clear to me which one is the best.

**Comment by tamuratak** [comment]
I have found that using `commitCharacters` is problematic. When we have `\infty` a lot in the text, the `\infty` command is focused in the suggestions after entering `\in`. Then if we enter a space, `\infty` will be inserted. This behavior is counterintuitive. 


![May-20-2020 09-14-26](https://user-images.githubusercontent.com/10665499/82390905-ecef1300-9a7a-11ea-9c86-7291f442d6d3.gif)

**Comment by jlelong** [comment]
Well, I can think of two solutions

1. Modify all the `.json` files to replace spaces by `_` in place holder names. This can be implemented directly in [pkgcommand.py](https://github.com/James-Yu/LaTeX-Workshop/blob/master/dev/pkgcommand.py).
1. Set `CompletionItem.filterText` to the command with place holders removed, e.g. for `ifnumcomp{integer expression}{relation}{integer expression}{true}{false}, we would set

    ```
    filterText: ifnumcomp{}{}{}{}{}
    ```

The first one seems more natural to me.

**Comment by tamuratak** [comment]
The underscore, `_`, matches the subscripts of `LaTeX`. After entering `\sum_`, suggestions might be being displayed.
