### ISSUE TITLE
RefTeX-like functionality for citations

### ISSUE THREAD

**Issue by ddbrierton** [James-Yu/LaTeX-Workshop#2102]
**Is your feature request related to a problem? Please describe.**
It’s often hard to remember the different citation commands. Everyone knows `\cite` but others like `\footnotecite` and `\citeyear` may be hard to remember, plus there is the the issue of their possible arguments.

**Describe the solution you'd like**
The Emacs mode RefTeX handles this rather nicely:

1. It seems to understand which citation/bibliography package you are using, e.g. `natbib` or `biblatex`.
2. There is one generic command for inserting a citation, and then the user is presented with a list of options given their package options. The command palette would seem an ideal vehicle for this.
3. If the user chooses an option with arguments, the user is prompted for argument values, e.g. “Pre-text: “ and “Post-text: “. Not sure where in the VS Code UI these prompts should be presented.

**Describe alternatives you've considered**
I can’t think of any at the moment.

**Additional context**
A screenshot of RefTeX after invoking the command to insert a reference:
https://i.stack.imgur.com/b8f5j.png

**Comment by jlelong** [comment]
We already have quite a similar feature in the extension. You need to set

```
"latex-workshop.intellisense.package.enabled": true,
"latex-workshop.intellisense.optionalArgsEntries.enabled": true
```

<img width="503" alt="Capture d’écran 2020-05-20 à 08 12 36" src="https://user-images.githubusercontent.com/2910140/82411234-b1038000-9a71-11ea-9911-9e281b3cb5d8.png">

Going beyond that would require a significant effort.
