### ISSUE TITLE
Disable automatically align* after \\enter

### ISSUE THREAD

**Issue by paulrennecke** [James-Yu/LaTeX-Workshop#2105]
Hallo,

everytime I type two backslashes to end the line and press Enter the snippet

"begin{align*}

\end{align*}"

generates automatically, I think this could be a feature, but I can't deactivate it anywhere.

**Comment by jlelong** [comment]
This is related to #2001. 

Your issue is related to the fact that hitting `Enter` accepts the proposed snippets. You can disable this by setting `editor.acceptSuggestionOnEnter: false`. With this setting, you have to use `Tab` to accept a snippet.
