### ISSUE TITLE
Preview in Tab not working when operating in UNC pointed folder

### ISSUE THREAD

**Issue by bartosz-antosik** [James-Yu/LaTeX-Workshop#211]
### Description

When extension operates on VSCode's folder pointed by UNC it Preview in Tab cannot open file:

![preview-in-tab](https://user-images.githubusercontent.com/20492548/28717171-ff1c2792-73a0-11e7-9944-698c1dea58ee.png)

### How to reproduce

1.  Open folder pointed out by UNC path (e.g. \\\\SERVER\documents).
2.  Try to compile (It does not work either because of MiKTeX's latexmk unability to accept files pointed out by UNC paths, it does work however when %DOC% is replaced with %DOCFILE%) document to PDF.
3. Invoke `View PDF file in new tab`.

### suggestion

Maybe which file is passed out to PDF.js could be configurable?

### Additional notices

It works fine with `View PDF file in web page`.

**Comment by James-Yu** [comment]
That is absolutely weird. Do you notice any difference between the shown URL and the one in the browser?

Internally the tab visits the same URL with the browser, see Line 55 and 174 of https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/viewer.ts

**Comment by bartosz-antosik** [comment]
This is what I can see in the address bar of the browser:

http://127.0.0.1:63281/viewer.html?file=\pdf:%5C%5C[MACHINE-NAME]%5CDocuments%5(...)%5Cpicasso.pdf

**Comment by James-Yu** [comment]
It seems the difference is on `\\SERVER`. Please correct me if wrong.

I will look into this issue. However, as I'm not familiar with the UNC things, it 'might' take some time.

**Comment by James-Yu** [comment]
Easier than thought. Please confirm if it works after the fix is updated in the marketplace shortly.

**Comment by bartosz-antosik** [comment]
Yes, it does work. Many thanks!
