### ISSUE TITLE
Make ChkTex warning level seteable

### ISSUE THREAD

**Issue by ruilvo** [James-Yu/LaTeX-Workshop#2110]
I find the fact that ChkTex linting checks as errors annoying and distracting.

I would like for the option to set the warning level, eg, `"latex-workshop.chktex.level": "info"`. Ideally with two different settings for ChkTex errors and warning, but if that's not possible, at least that.

I think that linting should be recommendations, so they would use warning or information level (yellow and blue), not error (red) level.

Thanks for the support!

**Comment by jlelong** [comment]
The `chktex` linter outputs 3 types of messages: errors, warnings and messages (mapped as information). See https://ctan.crest.fr/tex-archive/systems/doc/chktex/ChkTeX.pdf.

Therefore, anything reported as an error in the _Problems Pane_ is marked as so by `chktex` and there is no reason why we should not trust it. 

> I find the fact that ChkTex linting checks as errors annoying and distracting.

Could you elaborate on that?
