### ISSUE TITLE
make compilation available outside the activity bar

### ISSUE THREAD

**Issue by zhyiyu** [James-Yu/LaTeX-Workshop#2117]
The feature I am requesting is not related to a problem.

Currently the only way to access compilation is through activity bar inside LaTeX Workshop, I feel like it would more easier to have a compilation button available even when user is not in the extension.

<img width="1904" alt="compilation" src="https://user-images.githubusercontent.com/26550166/82975531-bb120b00-9faa-11ea-9082-4ebee6d4d5c4.png">

Also, it would be even better if user can choose which `latex-workshop.latex.recipes` to appear as the button.

**Comment by jlelong** [comment]
We will add a button for calling `Build LaTeX project`. The recipe used by this function is defined by [`latex-workshop.latex.recipe.default`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexrecipedefault).

**Comment by jlelong** [comment]
Any suggestion of an icon to be used?

**Comment by zhyiyu** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/26550166/84552919-65469e00-ace0-11ea-8dff-2f9ef4f128de.png)
That is my best try, haha!

**Comment by tamuratak** [comment]
Please use codicon for consistency. See https://code.visualstudio.com/api/references/icons-in-labels.

Example:

https://github.com/microsoft/vscode/blob/95fa0209e8e7198af200b62f3ea58143e619b7e2/extensions/markdown-language-features/package.json#L47

**Comment by musm** [comment]
codicon suggestions:
```
debug-start

wrench

rocket

```

**Comment by tobiasdiez** [comment]
Another idea would be to treat the compilation as a normal build command and integrate it with the "Run" panel (Ctrl +Shift + D).

**Comment by jlelong** [comment]
The "Run" panel relies on [vscode's task mechanism](https://code.visualstudio.com/docs/editor/tasks). The build system in LW uses the [recipe approach](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes), which is completely different. I do not think both can be used together. Moreover, I do not see how it would really help since LaTeX building is already available from the TeX panel and the `ctrl-alt-b` shortcut.

Adding an extra icon on the top right corner is really straightforward once we agree on which icon to use: I vote for `rocket`.

**Comment by tobiasdiez** [comment]
With https://code.visualstudio.com/api/extension-guides/task-provider it should be possible to make each recipe available as a task.

**Comment by jlelong** [comment]
@tamuratak Shouldn't we also consider using a codicon for the view icon. For instance `open-preview`, which is already used by the markdown extension. An other possible choice `preview`.

**Comment by tamuratak** [comment]
Codicon is available from VS Code 1.42. Do you intend to drop the support for prior to VS Code 1.42 from the next release? I am OK for that as in #2058.

https://code.visualstudio.com/updates/v1_42#_codicons-for-reuse

**Comment by jlelong** [comment]
To be honest, I did not pay attention to this. Yet, the current stable being `1.46.1`, I think it is fine to only support `vscode >= 1.42`.

**Comment by tamuratak** [comment]
Discussions continue on #2058.
