### ISSUE TITLE
Syntax file needs cleanup

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2126]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

The "LaTeX" syntax currently has a few problems. These lead to strange colorization and problems in many themes.

- `keyword.control` vs `support.function`
   Some standard commands (such as `\cite`) are tagged as `keyword.control`. This category is usually reserved for keywords related to flow control like continue, while, return, etc. I think `support.function` would be a better scope, e.g. change `keyword.control.cite.latex` to `support.function.cite.latex`. Similar remarks apply to `keyword.control.label.latex`, `keyword.other.item.latex`, `keyword.control.ref.latex`

- Commands in math
   Commands in math mode are tagged as `constant.character.math.tex` or `constant.other.general.math.tex`. For some one could argue that this is indeed the case (`\pi` etc) but for others (`\bigr`) this is definitely the wrong category. Moreover, I feel that `support.function` might be the better category anyway (since for Latex there is no distinction between `\pi` and `\cite`). To provide special colorization of math environments one could add a `meta.math` tag.

- Usage of `support.class`
Latex does not know the concept of a class, and thus this should be converted to `support.function`.

- Incontinence between `tex` and `latex` ending
For example there are `punctuation.definition.function.tex` and `punctuation.definition.function.latex`

- Command arguments
   Sometimes they are tagged as `variable.parameter.function.latex` (e.g `\begin{...}`) and sometimes as `constant.other.reference.citation.latex` (e.g. `\parencite{...}`). It would be good to add (different) meta tags for optional and manditory arguments as well.

- Special scopes missing
  - equals sign, minus, underscore and comma in math (punctation?)
  - braces as command argument delimiters
  - quotes in text

- Wrong classification
   `\,` yields a space in latex but is tagged as `constant.character.escape.tex`. Moreover, everything (even commands environments etc) are tagged as `text.tex.latex`.

### To Reproduce

1. Open an tex file
2. Use "Inspect editor tokens" to view the scope.

### Expected behavior

Consistent scopes.

### Additional context

https://macromates.com/manual/en/language_grammars is a good reference for what scopes exist and what the encompass. Sublime syntax for Latex: https://github.com/sublimehq/Packages/blob/master/LaTeX/LaTeX.sublime-syntax
https://www.sublimetext.com/docs/3/scope_naming.html

**Comment by jlelong** [comment]
See #2192 for a first attempt to improve scope name usage.

> Assigning a special scope to braces as command argument delimiters

Generally speaking, we do not match braces. So it is not possible.
