### ISSUE TITLE
Live preview

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2127]
**Is your feature request related to a problem? Please describe.**
The built-in preview of the PDF is nice, but Latex compilation takes quite some time. It would be nice to get quicker feedback how the text looks. While writing one is usually more interested in the general experience than a pixel perfect representation of the actual compiled pdf, so a quick rendering is ok for this.

**Describe the solution you'd like**
Almost-live preview of the document, similar to what `mdmath` provides for markdown.
![mdmath](https://raw.githubusercontent.com/goessner/mdmath/master/img/mdmath.gif)

**Describe alternatives you've considered**
Using the pdf preview, but as compilation is slow is not really an alternative.

**Additional context**
One solution might be to convert the tex file to html and let mathjax / katex render the math. Another idea could be to use https://github.com/brucemiller/LaTeXML but I'm not sure about the performance.

**Comment by tamuratak** [comment]
Out of the scope of LaTeX Workshop.
