### ISSUE TITLE
Add support for .jnw files (LaTeX + Julia)

### ISSUE THREAD

**Issue by likanzhan** [James-Yu/LaTeX-Workshop#2128]
Latex-workshop now supports `Rnw`, i.e., regular tex file with r code.
I'm wondering whether it is possible to add more supported file types, such as `jnw`, i.e., regular tex file with Julia code.

Furthermore, when my file is a `Rnw` one, the icon `View LaTex PDF File` doesn't show after successful complication. Any suggestions?

Thanks.

**Comment by jlelong** [comment]
Each new filetype requires a tough work, in particular for properly defining syntax highlighting. If you are ready to contribute and properly explain how `.jnw` syntax works I could help.

**Comment by likanzhan** [comment]
It would be my pleasure if I could help.

Generally speaking, an `.jnw` will first be converted to a normal tex file with the `weave` function in the `Weave` package in `julia` language, something like that
```
julia --project=.. -e 'using Weave' -e 'weave("$<", doctype="texminted")'

```

Then the tex file will be converted into pdf as normal.

**Comment by jlelong** [comment]
I would also need a clear description of the syntax used by `.jnw` files (for Julia blocks).

**Comment by likanzhan** [comment]
Could you explain it in more detail, such as using .Rnw as an example to explain 
what specifically do I need to provide?

Thanks 

Likan

**Comment by jlelong** [comment]
The first thing to do is to define a grammar for syntax highlighting in `.jnw` files. See [RSweave.tmLanguage.json](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/RSweave.tmLanguage.json) for how it is done for `.rnw` files.
It basically amounts to specifying how a julia block delimited in `.jnw` files.

Could you post a typical example of `.jnw` file?

**Comment by likanzhan** [comment]
@jlelong 

it is quite similar to a `rnw` file. 
The following is an example that is given in the `Weave` package:
 
[https://github.com/JunoLab/Weave.jl/blob/master/examples/FIR_design.jmd](https://github.com/JunoLab/Weave.jl/blob/master/examples/FIR_design.jmd)

**Comment by kapple19** [comment]
The documentation for LaTeX-Workshop has no examples of .jnw files. Can I get an example of:
* a MWE document that uses:
  * The `Verbatim` environment
  * The `minted` environment
* The above crossed with:
  * Code blocks
  * Reading a `.jl` file

Thanks!

**Comment by tamuratak** [comment]
The question is not related to LaTeX Workshop. Ask at https://stackexchange.com/
