### ISSUE TITLE
\includegraphics{...} with a non-empty argument does not match paths of input files.

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2132]
`\includegraphics{...}` with a non-empty argument does not match paths of input files at the current master. Only `\includegraphics{}` with an empty argument matches them.

Due to a7333ecc9b49b5756d68d13c8701c9d9bbd6fe65 and #2088. Should not change the order of the following line:

https://github.com/James-Yu/LaTeX-Workshop/blob/818603628b55dae371f620adcfe55d3d2796a5e0/src/providers/completion.ts#L84

![スクリーンショット 2020-06-01 10 48 23](https://user-images.githubusercontent.com/10665499/83368909-77c5fb00-a3f5-11ea-87c1-cad68ddda553.png)

**Comment by jlelong** [comment]
My bad! I did not pay attention to the order of completion types.

**Comment by jlelong** [comment]
Humm, it is a little trickier than I thought and I think the bug existed before a7333ec.

The following completions do not work

```
\includegraphics{image}
\includegraphics{image/c}
```

but `\includegraphics{image/}` does work.

- For `\includegraphics{image}`, the extension returns the correct list of completions for vscode considers that `image` should be the start of completion. Hence there is no match.
- For `\includegraphics{image/c}`, `image/c` is considered as the folder where to look for files.

    https://github.com/James-Yu/LaTeX-Workshop/blob/d7f650de009d51de4bfae1b7e374b3bf858169dd/src/providers/completer/input.ts#L139-L141

**Comment by tamuratak** [comment]
Sorry. I have misunderstood the behavior.
