### ISSUE TITLE
Can I specify a recipe in project scope?

### ISSUE THREAD

**Issue by Jeff-Tian** [James-Yu/LaTeX-Workshop#2133]
**Is your feature request related to a problem? Please describe.**
I have multiple projects, and different project uses different recipe to build. 

**Describe the solution you'd like**
Is there a way to put a `workshoprc` file under the project that specifies the recipe name?

**Comment by tamuratak** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#settings
