### ISSUE TITLE
Using the same PDF viewer as TeXstudio to have smooth trackpad zooming

### ISSUE THREAD

**Issue by netw0rkf10w** [James-Yu/LaTeX-Workshop#2134]
Hi,

Thanks for the great extension! I have just switched from TeXstudio, and am quite happy so far!

The only major issue for me is PDF zooming using my Mac's trackpad: it is not smooth at all. (This issue was previously reported [here](https://github.com/James-Yu/LaTeX-Workshop/issues/993).)

I would suggest using the [same PDF viewer](https://github.com/texstudio-org/texstudio/tree/master/src/pdfviewer) as TeXstudio. I don't know if it's technically feasible though.

**Is your feature request related to a problem? Please describe.**
Trackpad zooming is not smooth in macOS.

**Describe the solution you'd like**
Using the same PDF viewer as TeXstudio.

**Comment by tamuratak** [comment]
Not possible.

**Comment by netw0rkf10w** [comment]
Haha that was quick :D Thanks!
