### ISSUE TITLE
Can't locate File/HomeDir.pm in @INC

### ISSUE THREAD

**Issue by LukeIreland1** [James-Yu/LaTeX-Workshop#2135]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Can't format with LatexWorkshop

### To Reproduce

1. I try to format with LatexWorkshop

### Expected behavior

latexindent works on my system, but not with LatexWorkshop. I'm using a perlbrew installation, and I think LatexWorkshop is using my system perl instead. How can I tell LatexWorkshop to use perlbrew perl? It's in my path as I've added it to my zshrc.

## Logs [Required]

```perl
Formatting with command latexindent -c,/Users/lukire01/Documents/Uni/CE601/Code/trump-tweet-semantics/docs/,/Users/lukire01/Documents/Uni/CE601/Code/trump-tweet-semantics/docs/__latexindent_temp.tex,-y=defaultIndent: '  '

Formatting failed with exit code 2

stderr: Can't locate File/HomeDir.pm in @INC (you may need to install the File::HomeDir module) (@INC contains: /usr/local/texlive/2020/texmf-dist/scripts/latexindent /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4/darwin-thread-multi-2level /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/texlive/2020/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 22.
```

In a terminal:
```perl
╰─ latexindent                                                                   ─╯
Please enter text to be indented: (press CTRL+D when finished)
```

### LaTeX Workshop Output [Required]

N/A - See above

### Developer Tools Console [Required]

N/A - Nothing suspicious found

## Desktop [Required]
 - OS: Mac OS Catalina
 - VS Code version: 1.45.1
 - Extension version:8.9.0
 - TeX distribution version: MacTeX 2020.

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by jlelong** [comment]
This is mostly related to the way you have set your `PATH` variable. See the links in https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable

**Comment by LukeIreland1** [comment]
Sorry, that doesn't help at all, I'm not sure why you've closed this issue...

```
╰─ echo $PATH                                                                ─╯
/Users/lukire01/perl5/perlbrew/bin:/Users/lukire01/perl5/perlbrew/perls/perl-5.30.3/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/python@3.8/bin:/usr/local/opt/ncurses/bin:/Users/lukire01/Library/Python/3.8/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
```

My $PATH looks like this, and the appropriate Perl addition is from my .zshrc file
```
source /Users/lukire01/perl5/perlbrew/etc/bashrc
```

There is nothing [here](https://github.com/rbenv/rbenv/wiki/unix-shell-initialization) that's new to me, and nothing [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes) that is useful to me.

**Comment by LukeIreland1** [comment]
I tried this for a recipe, but gives me the same error.

```
{
            "name": "latentindent",
            "tools": "latentindent",
            "env":{
                "PATH": "/Users/lukire01/perl5/perlbrew/bin:/Users/lukire01/perl5/perlbrew/perls/perl-5.30.3/bin:$PATH"
            }
        }
```

**Comment by jlelong** [comment]
Because, this is not an issue related to the extension but rather to how to properly set environment variables. Because you tweak your PATH in `.zshrc`, its value is not the same inside a shell and inside a graphical app.  See https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x.

**Comment by LukeIreland1** [comment]
That helped! The second answer led me to this:
`launchctl setenv PATH $PATH`
I added this to my zshrc, and it worked. Thank you 😄

**Comment by jlelong** [comment]
I am glad you solved your issue but note that as I first answered you it was not related to the extension nor to vscode but rather to your own system configuration. 
You could have found the stackoverflow information yourself without down voting my answer. Remember that we develop and maintain the extension on our spare time.

**Comment by LukeIreland1** [comment]
Sorry, I didn't mean anything by that, other than I disagreed with closing the issue before it was solved. The link you added took me [here](https://github.com/rbenv/rbenv/wiki/unix-shell-initialization) which has no mention of setenv. It may be worth adding it to your FAQ as a result of our findings.
