### ISSUE TITLE
Display the statusbar icon only tex files detected

### ISSUE THREAD

**Issue by Mister-Hope** [James-Yu/LaTeX-Workshop#2137]
**Is your feature request related to a problem? Please describe.**

Yes, the newest plugin is displaying a icon in the status bar.

This can be annoying because rare people are using VSCode only for building latex.

Why should people see this icon if they are working on a node project or an Android project? This icon can be misleading!

**Describe the solution you'd like**

detect if the project is containing(can be whether the user is opening any tex files if there is not an api looking for file names) any tex files, then decide to show the icon or not

**Comment by tamuratak** [comment]
Screenshots, please.

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/83628130-99c4a680-a5ca-11ea-87b5-6409110ac2b8.png)

**Comment by jlelong** [comment]
The Tex icon appears in the status bar only once the extension is loaded. The extension is activated by the events described in

https://github.com/James-Yu/LaTeX-Workshop/blob/9c97441230854720996a119878dbcc00889796b3/package.json#L28-L51

As you can see, LaTeX-Workshop provides vscode with the ability to view PDF file, which it cannot do natively.

**Comment by Mister-Hope** [comment]
Unforunately, we usually do not need to view the pdf files if we are not building a tex project.

I still insist activating this plugin by pdf is a bad idea. So I suggest removing line 34

**Comment by jlelong** [comment]
I really cannot follow you. The extension does not activate if there are PDF files inside the workspace but only if you try to open one of them using VSCode. 

Can you post the complete logs of the extension once you see the TeX icon appearing in the status bar using _Show LaTeX Workshop messages_ from the _Command Palette_?

**Comment by Mister-Hope** [comment]
My fault, one of my installed plugin seems to be the reason that this plugin is activated.
