### ISSUE TITLE
Mount Other Files in Docker File

### ISSUE THREAD

**Issue by Syndlex** [James-Yu/LaTeX-Workshop#2138]
**Is your feature request related to a problem? Please describe.**
My root directory has sister directories with code that I wand to append in the PDF document.
I compile with Docker and the Latex can not find sister directories since they are not mounted in the Docker Container. 

**Describe the solution you'd like**
Something like the Magic comment would be nice where I can say what additional folders should be mounted.

I don't know how hard this would be. just a idea.

**Comment by jlelong** [comment]
For advanced Docker usage, we recommend to use [Remote-Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers).
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#using-docker

We do not plan to enhance Docker support directly inside the extension.
