### ISSUE TITLE
Automaticaly create Tex files in \input{..} with CTRL + left click

### ISSUE THREAD

**Issue by moschmdt** [James-Yu/LaTeX-Workshop#2141]
This is a feature from TexStudio but I think it would be amazing to have. 

Situation:

1. The file _TestFile.tex_ does not exist yet.
2. Write the line \input{TestFile.tex} 
3. The file is not linked because it does not exist, so it must be created manually

Suggestion:
It would be nice to have the possibility to create that file with the same CTRL + left click.

**Comment by jlelong** [comment]
I think this is beyond the scope of this extension all the more so as it is sufficient to create the file in VSCode's Explorer and you will get autocompletion for `\input`.
