### ISSUE TITLE
Descriptive change log

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#2144]
**Is your feature request related to a problem? Please describe.**

Given that the extension is quite actively developed, it would be helpful if the changelog is more descrptive about the newly added features. 

Consider the changelog of the recent release:
```
### Added
- Enhance LaTeX3 support.
- Activate extension for `latex-expl3` language id.
- (#2018) Support restoring PDF viewers.
- (#2088) Add completion support for `includeonly`/`excludeonly`.
- (#2099) Set default recipe by name.
- (#2115) Add intellisense for optional `bibtex` fields.
- (#2118) Texcount comes back.
- (#2136) Filename completion with already typed path.
```
Some of the features added are self-descriptive. However, there are others where it is not clear what the feature. In these cases, only the contributors and the person asked for it knows the nature of the feature. For others, the only way to figure out is go to the PR or issue-number and read through the whole discussion. And most of these cases, it is not clear how to use the feature. For instance, consider the `(#2115) Add intellisense for optional bibtex fields`. Here, even though I went through [the issue](https://github.com/James-Yu/LaTeX-Workshop/issues/2103), it is not clear how to use the feature. 
 
So, I kindly request the moderators to be more descriptive on the nature of the new feature, how to use, etc.

**Comment by jlelong** [comment]
Usually a new feature is documented in the wiki. For `(#2115) Add intellisense for optional bibtex fields`, see (#2115) Add intellisense for optional bibtex fields.
If things are missing in the wiki, please open an issue in https://github.com/jlelong/LaTeX-Workshop-wiki or even better make a PR there.
