### ISSUE TITLE
Automatically prefix labels

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2145]
**Is your feature request related to a problem? Please describe.**
For bigger projects, it's quite common that labels for equations and theorems are labeled with prefixes of the current section and of the kind of label (e.g: `eq` for equation). For example:
```latex
\section{First section}
\label{sec:first}

\begin{equation}
    \label{eq:first: <>} // We are in the first section, so prepend "first"  
\end{equation}
```

**Describe the solution you'd like**
As soon as the user writes `\label{`, the prefix should be automatically inserted. So `\label{` expands to `\label{eq:first:|}` if the equation is in a section with label `sec:first`. 

**Describe alternatives you've considered**
I'm not aware of a convenient workaround (instead of writing the labels by hand of course).

**Additional context**
I guess not everyone wants such a prefix, thus there should be a configuration option toggling it on and off.

**Comment by jlelong** [comment]
I am sorry but this is too much a question of personal taste to be implemented in the extension.

**Comment by tobiasdiez** [comment]
I agree that the precise format of the label might be subjective. However, the general structure of using a prefix such as `eq:` for equations etc seems to be quite common: https://github.com/search?l=latex&p=2&q=%5Clabel%7Beq%3A&type=Code

I guess one can add a few configurations so that users can change it to fit their style. For example, the similar [auto label](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.7/auto_label.py) functionality for the LaTeXTools plugin for sublime supports that user can overwrite the mapping of the prefix e.g `equation -> equ`.

Would you consider accepting a PR that implements the feature?
