### ISSUE TITLE
Synctex does not work after recent update

### ISSUE THREAD

**Issue by yse00** [James-Yu/LaTeX-Workshop#215]
### Description
The synctex is not working and the view is not refreshing after building.

 I have used this extension on for a small amount of time. Thanks for the great work. However, after a recent update, the synctex are not working properly and the view is not refreshing. These two function works well before this recent update.

### Error Log

Here is the log when synctex from the  PDF view:

[18:01:21] Executing synctex with args edit,-o,7:153:627.6:/pdf:d:\LaTeX\ICDCS2017\main.pdf
[18:01:21] Cannot reverse synctex, code: 4294967295, SyncTeX ERROR: could not open /pdf:d:\LaTeX\ICDCS2017\main.synctex, error 22

SyncTeX ERROR: No SyncTeX available for /pdf:d:\LaTeX\ICDCS2017\main.pdf
usage: synctex <subcommand> [options] [args]
Synchronize TeXnology command-line client, version 1.18

The Synchronization TeXnology by Jerome Laurens is a rather new feature of recent TeX engines.
It allows to synchronize between input and output, which means to
navigate from the source document to the typeset material and vice versa.

synctex edit: backwards or reverse synchronization,
command sent by the viewer to edit the source corresponding to the position under the mouse

usage: synctex edit -o page: x:y:file [-d directory] [-x editor-command] [-h offset:context]

-o page: x:y:file
       specify the page and coordinates of the point under the mouse.
       page is 1 based.
       Coordinates x and y are counted from the top left corner of the page.
       Their unit is the big point (72 dpi).
       file is in general the path of a pdf or dvi file.
       It can be either absolute or relative to the current directory.
       This named file must always exist.
       
-d directory
       is the directory containing the synctex file, in case it is different from the directory of the output.
       This directory must exist.
       An example will explain how things work: for synctex -o ...:bar.tex -d foo,
       the chosen synctex file is the most recent among bar.synctex, bar.synctex.gz, foo/bar.synctex and foo/bar.synctex.gz.
		The other ones are simply removed, if the authorization is granted
       
-x editor-command
       Normally the synctex tool outputs its result to the stdout.
       It is possible to execute an external tool with the result of the query.
       The editor-command is a printf like format string with following specifiers.
       They will be replaced by their value before the command is executed.
       %{output} is the full path specifier of the output document, with no extension.
       %{input} is the name specifier of the input document.
       %{line} is the 0 based line number specifier. %{line+1} is the 1 based line number specifier.
       %{column} is the 0 based column number specifier or -1. %{column+1} is the 1 based column number or -1.
       %{offset} is the 0 based offset specifier and %{context} is the context specifier of the hint.
       If no editor-command is provided, the content of the SYNCTEX_EDITOR environment variable is used instead.
       
-h offset:context
       This hint allows a backwards or reverse synchronization by contents.
       You give a context including the character at the mouse location, and
       the offset of this character relative to the beginning of this bunch of text.

**Comment by James-Yu** [comment]
Thank you for your very precise and informative issue. The bug was caused by previous inconsistent coding. Fix is on the way.

**Comment by James-Yu** [comment]
Fixed. Will be published shortly.
