### ISSUE TITLE
Edit environment name in \begin and \end simultaneously

### ISSUE THREAD

**Issue by EmilVogt** [James-Yu/LaTeX-Workshop#2156]
**Problem**
I often want to change a math environment like align from numbered to non-numbered or vice versa. This means, I have to edit the environments name and delete a star or add one.
From
```
\begin{align}
...
\end{align}
```
to
```
\begin{align*}
...
\end{align*}
```
Since the environments name appears twice, this requires two changes. And in between, while the names don't match, the syntax highlighting is off.

**Possible solution**
When clicking in the name of the environment in either `\begin` or `\end`, would it be possible to add a second cursor at the same position in the _corresponding_ other command? So every change is reflected in both `\begin` and `\end`. This would make changing the environment easy.

**Alternative**
Add second cursor manually.

**Comment by tamuratak** [comment]
Call `LaTeX Workshop: Select the current environment name` https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#navigating

**Comment by EmilVogt** [comment]
Thanks, I didn't see that. `latex-workshop.multicursor-envname` seems to be the right command. It still requires several steps, though. When clicking in the name of the environment, renaming is really the only thing you will/can do. So, why not directly setting a second cursor?

**Comment by jlelong** [comment]
You could consider defining a keybinding for `latex-workshop.multicursor-envname`. Then, wherever the cursor is, you use this keybinding to add a multi-cursor to the current environment. Repeated calls result in selecting the outer environments.
