### ISSUE TITLE
command 'latex-workshop.onEnterKey' not found / General stop of working

### ISSUE THREAD

**Issue by cmburg** [James-Yu/LaTeX-Workshop#2160]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

I am writing my masters thesis and am using vscodium (the cleaned version of vscode) to set and compile the document. It worked like a charm and I paused it in between until yesterday. The first oddity was that no "open definition" appeared when I right-clicked an \include{}. It even showed the plugin as disabled/uninstalled (not exactly sure). Reinstalled/activated it. Then I tried to add new lines with the enter-key and got the aforementioned error. 

I thought it might be by messing around in the predefined snippets so I removed all vscodium stuff in my home folder (vs-codium-free and the according folder under .config).

Then I created a new user on my PC to have absolute no traces I might have overlooked. Even then I get the same error.

It seems like the latex plugin is not working properly. I am missing the TeX button on the left but syntax highlighting works...

### To Reproduce

3. See error

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]
Not possible since the button "TeX" is not shown

### Developer Tools Console [Required]

```
Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/foo/.vscode-oss/extensions/james-yu.latex-workshop-8.10.0/out/src/main.js'
Require stack:
- /usr/share/codium/resources/app/out/vs/loader.js
- /usr/share/codium/resources/app/out/bootstrap-amd.js
- /usr/share/codium/resources/app/out/bootstrap-fork.js.
```

## Desktop [Required]
 - OS: elementaryOS 5.1.5
 - VS Code version: 1.46.0
 - Extension version: 8.10.0
 - TeX distribution version: unsure but not important since compiling with atom is flawless

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

further info of vscodium:
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-11T18:31:22.701Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-106-generic

**Comment by tamuratak** [comment]
Please try removing `'/home/foo/.vscode-oss/extensions/james-yu.latex-workshop-8.10.0/` and reinstalling the extension. VS Code's uninstalling extensions does not remove the directories sometimes.

You should see the directory too by executing
```
ls -l /home/foo/.vscode-oss/extensions/james-yu.latex-workshop-8.10.0/out/src/
```

**Comment by cmburg** [comment]
I removed the whole directory (hence I created a new user too to be sure there are absolutely no traces left) but to no avail.

I even tried to reinstall the previous version but that threw an error with the info I have to manually download (and probably install) the package.

**Comment by tamuratak** [comment]
We can do nothing on our side. Please contact with the development team of vscodium.

**Comment by lgsmith** [comment]
This conclusion is a bit surprising to me. I am running this extension with no issues in VSCodium on a different computer (also, for me, ubuntu 20.04; see #2183). The VSCodium version numbers are the same for both machines. The machines are different in other ways, (in particular one is using GNOME desktop, the other KDE) but codium is a point of commonality between them.

**Comment by tamuratak** [comment]
They have begun to use their own marketplace for plugins. See https://github.com/VSCodium/vscodium#extensions-and-the-marketplace. It seems to be problematic. The latest version of LaTeX Workshop is [v8.10.0](https://open-vsx.org/extension/James-Yu/latex-workshop) at their site although the actual latest version is v8.11.0. 

When you use an unofficial product, you have to debug it by yourself. If you do not want to do that, I recommend you to use VS Code, not VSCodium.

**Comment by lgsmith** [comment]
Their marketplace links to this github page. What is problematic about the marketplace? Do you have any insight into the source of the incompatibility? 

This is the only extension (and then, only on one computer) I've ever run into that has an incompatibility that has been attributed to differences between these two differentially licensed versions of code. How are you certain this is coming from VSCodium and not some other issue?

**Comment by tamuratak** [comment]
As I said, please debug by yourself before asking us.

**Comment by tamuratak** [comment]
I have downloaded `vsix` files from https://open-vsx.org/extension/James-Yu/latex-workshop. I have found that they did not include the directory `out/`. That is the cause. 

Please file an issue at https://github.com/eclipse/openvsx or https://github.com/VSCodium/vscodium.

**Comment by tamuratak** [comment]
Tracked in VSCodium/vscodium/issues/486

**Comment by tamuratak** [comment]
Rejected in VSCodium/vscodium/issues/486. 

Anyone who wants this issue fixed, please report to https://github.com/open-vsx/publish-extensions.

**Comment by tamuratak** [comment]
Tracked in open-vsx/publish-extensions/issues/163
