### ISSUE TITLE
latex-workshop.latex.clean.subfolder.enabled redundant  

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#2161]
## Preliminary questions 
`"latex-workshop.latex.clean.subfolder.enabled"`   is redundant, with `""latex-workshop.latex.autoClean.run"`. 

If a user want's autoclean to run, I don't see why they then need to also set `"latex-workshop.latex.clean.subfolder.enabled"`  if they are using an `outDir`.

In fact, it seems that this option isn't even needed. E.g. I set an outdir, and set `"latex-workshop.latex.clean.subfolder.enabled": true`  and `"latex-workshop.latex.clean.subfolder.enabled": false`. Then autoclean still works. 

## Desktop
 - OS:   Windows 10
 - VS Code version: 1.46.0
 - Extension version:  8.10.0
 - TeX distribution version: TeX Live 2020

**Comment by musm** [comment]
Revised the issue to make it more clear. This isn't  a question FYI.

**Comment by jlelong** [comment]
When `latex-workshop.latex.clean.subfolder.enabled` is set, the auxiliary files are cleaned even when they are in a subfolder of `outDir`. This setting is only relevant when the LaTeX compiler creates additional subdirectories.
