### ISSUE TITLE
No documentation hover when options with spaces are set

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#2162]
Example 

```
\usepackage[style=nature,
            doi=false,
            eprint=false,
            url=false,
            isbn=false,
            maxcitenames=2,
            maxbibnames=20,
            giveninits=true,
            backend=biber]{biblatex}
```
Try to hover, doesn't work.

Next remove the spacing between options

```
\usepackage[style=nature,doi=false]{biblatex}
```
Documentation hover works.

**Comment by jlelong** [comment]
This issue is not related to spacing but to line breaks. Remove the newlines and everything will work fine. We cannot do anything about it.

**Comment by musm** [comment]
Is it not possible to allow the parser to skip through newlines? Curious

**Comment by jlelong** [comment]
This would make things far too complicated. You can make a PR if you think it is worth it.

**Comment by musm** [comment]
Wouldn't it be worthwhile to then leave this issue open? Perhaps an onlooker would find this issue easier if it was left open, and it might inspire them to tackle the issue instead of it being closed, which might make it seem like the problem is solved.
