### ISSUE TITLE
Can we make "latex-workshop.latex.bibDirs" search BIBINPUTS?

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#2163]
Right now I have the environment variable `BIBINPUTS` set to path.
To make things work in VS Code I need to also set the explicit path.  Can we just make "latex-workshop.latex.bibDirs" automatically search the `BIBINPUTS` path? This seems far more robust and logical. After all the whole point of `BIBINPUTS` is to set one location for all your `.bib` and then forget about their path in other programs.

**Comment by jlelong** [comment]
If you use different `BIBINPUTS` values in different projects, it becomes far too complicated to handle inside vscode. This is much simpler to set the value of `latex-workshop.latex.bibDirs` once.

**Comment by musm** [comment]
Why would this be too complicated? For example sublime tools latex, uses the system search to look up the environment key and pulls in that for `BIBINPUT`. Why couldn't the same be implemented here.

**Comment by musm** [comment]
I'm not familiar with the codebase and `ts`, I would love to open a PR if I had more expertise, but it doesn't look very complicated to add.

https://github.com/James-Yu/LaTeX-Workshop/blob/4c322bdb5a15151cd98bce2fff2dd33c41e36fda/src/components/manager.ts#L864

What needs to be done is add an additional check  `if bibPath  is empty`   to resolve system environment variables and see if a  non empty path exists and use that.

This would have zero impact on existing workflows and can be added in a backwards compatible manner.

**Comment by musm** [comment]
Is it not better to leave  these open instead of closing them? It makes it look like the issue is resolved or addressed.

**Comment by musm** [comment]
A better way is to simply search 
```
kpsewhich -show-path=bib

```
Which is the most sensible default, since that is what's used by latex to located `.bib`. files

**Comment by jlelong** [comment]
There is even a simpler approach. Running `kpsewhich -format=.bib biblio` tries to find a file named `biblio.bib` somewhere in the paths returned by `kpsewhich -show-path=bib`

**Comment by musm** [comment]
🎉 nice!
