### ISSUE TITLE
ctrl+alt+b on a existing build should cancel the build

### ISSUE THREAD

**Issue by musm** [James-Yu/LaTeX-Workshop#2166]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated that I have to go to the project menu to cancel a build when I note a  mistake in my source code. I'm trying to duplicate the behavior of the Sublime Latex Tools package, which behaves as follows and is a great time saver. 

**Describe the solution you'd like**
Hit <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>b</kbd> to build the project. *While the project is building* press again <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>b</kbd>, this should cancel the existing build.

Why do I want this?

Suppose you are writing code, build, but then see a mistake in your source. You want to quickly cancel then build. Right now you have to press <kbd>ctrl</kbd><kbd>p</kbd>, search for the terminate latex build option and then rebuild. This is not a user-friendly experience.

**Comment by tamuratak** [comment]
Set a keyboard shortcut to `latex-workshop.kill`.

**Comment by musm** [comment]
@tamuratak  How is it possible to set `latex-workshop.kill`  to the same `key`, when I already have 
```
  {
    "key": "ctrl+b",
    "command": "latex-workshop.build",
    "when": "editorLangId == 'latex'" // editorTextFocus && editorLangId == 'latex'
  },
```

Your proposing  to add

```
  {
    "key": "ctrl+b",
    "command": "latex-workshop.kill",
    "when": "editorLangId == 'latex'" // editorTextFocus && editorLangId == 'latex'
  },
```
which will clash. 


The advantage of the same key binding is you don't' end up wasting additional key bindings.
