### ISSUE TITLE
GitHub is unstable. Please stop commiting.

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2171]
I can not see the commit 5b1e234c52c4f053731dbc5bc9fee2f1b203672f at https://github.com/James-Yu/LaTeX-Workshop/commits/master. Something is wrong with github.com?

@James-Yu @jlelong can you see the commit in the history?

**Comment by tamuratak** [comment]
Now I can see the commit. Hmm...

**Comment by James-Yu** [comment]
Quite strange. I just tried again `git push`, while nothing happens on my end, the commit is available on the site. Hmm....
