### ISSUE TITLE
Add generated file name property for PDF viewer

### ISSUE THREAD

**Issue by fatadel** [James-Yu/LaTeX-Workshop#2175]
**Is your feature request related to a problem? Please describe.**
Yes.
I use a custom Makefile to build my project. It creates an output `.pdf` file with a name different than the `.tex` file.
As a result, I can't live preview my document as the extension searches for a file `TEX_FILENAME.pdf` and fails.

**Describe the solution you'd like**
Add a generated file name property for the PDF viewer.

**Describe alternatives you've considered**
For now, I make the Makefile script create a PDF file with the same name as the TEX file.
But that's a quite inconvenient workaround.

Thank you.

**Comment by tamuratak** [comment]
Using the same name is a convention in LaTeX. Our implementation relies on it. Adding the placeholder is difficult.
