### ISSUE TITLE
Wrong focus on a parenthesis out of the current cursor

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2191]
Minor issue. In the following example, when the cursor at `aaa`, the parenthesis of `f(x)` gets a focus. I am not sure this issue should be fixed.

![スクリーンショット 2020-07-02 9 40 21](https://user-images.githubusercontent.com/10665499/86303931-4afd4180-bc48-11ea-97e7-1c5dceb9d22d.png)

LaTeX Workshop: 8.11.1

Version: 1.47.0-insider
Commit: b16b467d3e03e1a1ae05b5836e4e5a5af504e86d
Date: 2020-07-01T05:30:11.898Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

**Comment by jlelong** [comment]
I do not think we can fix this from the extension side. This occurs because we declare `[..]` and `(...)` as bracket pairs
https://github.com/James-Yu/LaTeX-Workshop/blob/71eb4fb8629fcbdf7226ca1e70574f35dc33615b/syntax/syntax.json#L5-L8

It looks like vscode is not able to handle unbalanced pairs.

**Comment by jlelong** [comment]
It seems that adding `["[", ")"]` to the above list fixes the issue without causing side issues but I am not yet convinced this is the way to go.

**Comment by tamuratak** [comment]
I think making `syntax.json` configurable is an appropriate way. See https://code.visualstudio.com/api/references/vscode-api#LanguageConfiguration. However, some properties are missing in `LanguageConfiguration`. 

Tracked in microsoft/vscode/issues/38352

**Comment by jlelong** [comment]
Indeed, that would be a good idea. We have had several issues on matching pairs, for instance #1430 #1529
