### ISSUE TITLE
File rename from \input

### ISSUE THREAD

**Issue by jmg-duarte** [James-Yu/LaTeX-Workshop#2194]
Hello! I'm currently writing my thesis and using exclusively this plugin.
It has saved me countless hours and apart from one kink I'm yet to figure out if it is a bug I love it.

Currently I have my thesis separated in a lot of .tex files, I bundle them together using `\input` commands and while it may not be the best, my files are named after their section numbers.

Example:
```
1-intro.tex
2-state-of-the-art.tex
2-1-crypto.tex
2-2-ds.tex
...
```
Whenever I decide to switch the order of the files in the LaTeX the numbering "breaks". Of course that is to be expected.
My problem is, I want to be able to rename the file from the `\input`, for example, I try to refactor the content of the command and it figures out the file to be renamed along with.

Taking the example above I'd have:
```latex
\input{1-intro.tex}
\input{2-state-of-the-art.tex}
\input{2-1-crypto.tex}
\input{2-2-ds.tex} % if i want to switch this to the line above it becomes section 2.1
```
So it becomes:
```latex
\input{1-intro.tex}
\input{2-state-of-the-art.tex}
\input{2-2-ds.tex}
\input{2-1-crypto.tex}
```
And now I want to rename `2-2-ds.tex` to `2-1-ds.tex` and have this carry over to the actual filenames.
While I can switch the organization scheme, or rename the files and the input labels by hand, it becomes a huge hassle pretty quickly. 
I'd really appreciate if you could look into this.

**Comment by jlelong** [comment]
This is clearly out of the scope of the extension because related to a very specific and personal workflow.

**Comment by jmg-duarte** [comment]
I disagree with "very specific and personal workflow". While the example is indeed specific, having a file being renamed when I rename it in the .tex file is not specific.
In fact it is a common feature in editors.
If you want to dismiss the issue because it is hard to implement and the benefit is small, sure thing, just don't mislabel it when justifying closing the issue without an actual discussion.
