### ISSUE TITLE
Promote / Demote a whole section/chapter/part

### ISSUE THREAD

**Issue by moy** [James-Yu/LaTeX-Workshop#2195]
**Is your feature request related to a problem? Please describe.**
When refactoring the outline of a document (or cut-and-pasting from a document to another), one operation I commonly have to do is to promote or demote a whole section. Currently, I need to select the section, and run the promote/demote in selection commands. But selecting the section properly is a bit tedious if the section is long.

**Describe the solution you'd like**
A pair of commands promote/demote current section, which would find the boundaries of the current section (it would at least be able to run with the cursor under the `\section` command and would find the end of this section, but could also run anywhere, and find the deepest outline level containing the cursor), and apply "promote/demote all the section levels used in the selection" on this portion of the document. One could also imagine being able to do the same from the "structure" panel in the sidebar (e.g. right-click on a section name would open a context menu containing "promote/demote", and possibly "select section").

**Describe alternatives you've considered**
A command to select the current section would already be nice, and could be used in other context.

**Comment by jlelong** [comment]
A new command is available to select the whole content of the current section including its subsections: latex-workshop.select-section.
See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#selecting-a-whole-section)
