### ISSUE TITLE
Continuous non-stop parsing tex file - bug

### ISSUE THREAD

**Issue by kookma** [James-Yu/LaTeX-Workshop#220]
### Non stop parsing the tex file

When you set the output window to LaTeX Workshop in VSCOde editor you can see the log of LW extension.

### How to reproduce

If you open a .tex file and start editing it, you see the  LW traces in output window.
After some editing you see the LW is parsing the file in a non-stop way. See below picture

![lw-nostop parsing](https://user-images.githubusercontent.com/830394/28764915-43fc610e-75dd-11e7-8edd-bddee3730fe6.png)

**Comment by James-Yu** [comment]
I cannot reproduce this problem. Can you please share a minimal working example?

**Comment by kookma** [comment]
This is the .tex file I build.
I named it exmp01.tex

```
\documentclass{article}
\begin{document}
This is a test!
\section{My First Header}        
This is another test!

\subsection{My First Second}
And another and another test!!
\end{document}

```

**Comment by James-Yu** [comment]
I cannot reproduce the problem. See screenshot:
![image](https://user-images.githubusercontent.com/4210342/28855052-0a97ff4a-776d-11e7-8841-9774e2845860.png)

Do you have any special settings? Is this bug reproducable on the public channel instead of insider?

**Comment by kookma** [comment]
James, I installed the stable version of VSCode and the issue is gone now.

**Comment by James-Yu** [comment]
That's interesting. It seems that the insider build has some internal change which breaks compatibility. Unfortunately it is quite unlikely to support unstable builds, so for now please stick to the public channel, and use insider for experimentation. If the change is published to public, I will look into the issue again.
