### ISSUE TITLE
Internal pdf viewer on separate window

### ISSUE THREAD

**Issue by hanzckernel** [James-Yu/LaTeX-Workshop#2201]
I am looking for a solution with working on multiple-screen, where the ideal situation is I can have one screen focused on tex code and the other focused on the pdf file (and I can do back-and-forth sync etc.) 

The current internal pdf viewer does not support such function (or at least what I have tried), and the external pdf viewer has other many problems.

So my suggestion is to enable opening the internal pdf viewer on a separate vscode window (instead of tab), so that I can move it to a separate screen (This would be the thing I did with TexStudio)

Many thanks to all the efforts that has been and will be done!

**Comment by tamuratak** [comment]
Select `View in web browser` in the side bar.
