### ISSUE TITLE
Can not find latexindent in PATH!

### ISSUE THREAD

**Issue by geoffreycastillo** [James-Yu/LaTeX-Workshop#2202]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

Does not relate to compiling

## Describe the bug [Required]

I cannot get latexindent to work on Windows 10 + MiKTeX.

As described in #427, I have downloaded the zip of `latexindent` [from CTAN](https://ctan.org/tex-archive/support/latexindent), extracted it in `C:\Program Files\MiKTeX\scripts\latexindent` and changed `latex-workshop.latexindent.path` to `"C:\Program Files\MiKTeX\scripts\latexindent\latexindent.exe"`. I get the error message `Can not find latexindent in PATH!`.

I have also tried:
- `"C:\\Program Files\\MiKTeX\\scripts\\latexindent\\latexindent.exe"`
- `"C:/Program Files/MiKTeX/scripts/latexindent/latexindent.exe"`
- `C:\Program Files\MiKTeX\scripts\latexindent\latexindent.exe`
- `C:/Program Files/MiKTeX/scripts/latexindent/latexindent.exe`

If I just leave `latexindent`, MikTex default to `latexindent.pl` and I get error messages similar to those in #427 since I do not have the required packages.

I also tried to rename `latexindent.pl` to something else; in that case MiKTeX wants me to reinstall `latexindent.pl`.

### To Reproduce

1. Command palette > Format document
2. See error

### Expected behavior

I expect the document to be formatted.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[11:24:15] Initializing LaTeX Workshop.
[11:24:15] Creating PDF file watcher.
[11:24:16] pdflatex is provided by MiKTeX
[11:24:16] Creating LaTeX Workshop http and websocket server.
[11:24:16] LaTeX Workshop initialized.
[11:24:16] Linter for root file started.
[11:24:16] No root file found for linting.
[11:24:16] Server created on 127.0.0.1:3450
[11:24:16] Snippet data loaded.
[11:24:16] LaTeX Workshop version: 8.11.1
[11:24:41] Start formatting with latexindent.
[11:24:42] Can not find latexindent in PATH!
[11:25:21] LOG command invoked.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

Can not find latexindent in PATH!
onDidChangeNotification @ notificationsAlerts.ts:40
```

## Desktop [Required]
 - OS: Windows 10 Enterprise 1909
 - VS Code version: 1.47.0
 - Extension version: 8.11.1
 - TeX distribution version: MiKTeX 20.6.29

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
You have to install Perl.

**Comment by geoffreycastillo** [comment]
I _do_ have perl:

```
$ perl -v

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

Otherwise I wouldn't get the package errors mentioned in #427 when leaving `latexindent` as `latex-workshop.latexindent.path`.
