### ISSUE TITLE
Customize the highlight color of the internal pdf viewer search results

### ISSUE THREAD

**Issue by DeadRabbits307** [James-Yu/LaTeX-Workshop#2204]
As far as I can see, there is no possibility to customize the color used for highlighting the search results in the internal PDF viewer? For me a blue color is used, which not as clearly visible as f.e. yellow.

**Comment by fazelk** [comment]
Could you please unsubscribe me?
I did 100 times so far but I still get email .

**Comment by tamuratak** [comment]
@fazelk visit https://github.com/James-Yu/LaTeX-Workshop and turn `Watch` off at the top.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
