### ISSUE TITLE
Cannot use proper path in remote ssh.

### ISSUE THREAD

**Issue by hktkzyx** [James-Yu/LaTeX-Workshop#2208]
## Preliminary questions [Required]
An error appears `Recipe terminated with fatal error: spawn xelatex ENOENT.` when I save the tex file to auto-build tex file.

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

My shell is `zsh` and I have added latex path in `~/.zshrc`. However, when I build tex file in the plugin, the error `Recipe terminated with fatal error: spawn xelatex ENOENT.` is prompted. Manually build tex file in terminal is okey.

## Logs [Required]
```
[18:35:46] File watcher - file changed: /home/y***z/Documents/paper.tex
[18:35:46] Parsing a file and its subfiles: /home/y***z/Documents/paper.tex
[18:35:46] Parse fls file.
[18:35:46] Cannot find fls file: /home/y***z/Documents/paper.fls
[18:35:46] Auto build started detecting the change of a file: /home/y***z/Documents/paper.tex
[18:35:46] BUILD command invoked.
[18:35:46] Building root file: /home/y***z/Documents/paper.tex
[18:35:46] Build root file /home/y***z/Documents/paper.tex
[18:35:46] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,paper
[18:35:46] cwd: /home/y***z/Documents
[18:35:46] LaTeX build process spawned. PID: undefined.
[18:35:46] LaTeX fatal error: spawn xelatex ENOENT, . PID: undefined.
[18:35:46] Does the executable exist? PATH: /home/y***z/.vscode-server/bin/4***3/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/snap/bin:/home/yzhubz/bin:/usr/local/bin:/home/y***z/.vscode-server/bin/4***3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
### Developer Tools Console [Required]

```
Recipe terminated with fatal error: spawn xelatex ENOENT.
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:2947
```

## Desktop [Required]

- VScode
    - Version: 1.47.1 (user setup)
    - Commit: 485c41f9460bdb830c4da12c102daff275415b53
    - Date: 2020-07-13T22:42:53.386Z
    - Electron: 7.3.2
    - Chrome: 78.0.3904.130
    - Node.js: 12.8.1
    - V8: 7.8.279.23-electron.0

- OS
    - OS: Windows_NT x64 10.0.18363
    - Remote OS: Ubuntu 20.04 LTS

- Extension
    - Name: LaTeX Workshop
    - Id: james-yu.latex-workshop
    - Description: Boost LaTeX typesetting efficiency with preview, compile, autocomplete, colorize, and more.
    - Version: 8.11.1
    - Publisher: James Yu
    - VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop
    - TeX distribution version: TeX Live 2020

### Are you using LaTeX Workshop with VS Code Remote?

Yes

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Name: Remote - SSH
- Id: ms-vscode-remote.remote-ssh 
- Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
- Version: 0.51.0
- Publisher: Microsoft
- VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

**Comment by tamuratak** [comment]
Where is your `xelatex`? Does it exist in `PATH: /home/y***z/.vscode-server/bin/4***3/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/snap/bin:/home/yzhubz/bin:/usr/local/bin:/home/y***z/.vscode-server/bin/4***3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`?

You can use `which xelatex` if you do not know. 

See https://github.com/rbenv/rbenv/wiki/unix-shell-initialization

**Comment by hktkzyx** [comment]
My `xelatex` is in `/usr/local/texlive/2020/bin/x86_64-linux/xelatex` but not in the `PATH: /home/y***z/.vscode-server/bin/4***3/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/snap/bin:/home/yzhubz/bin:/usr/local/bin:/home/y***z/.vscode-server/bin/4***3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`. However, in terminal, the xelatex path is in `$PATH` and I can execute `xelatex` in the terminal. I think the problem is that `$PATH` showed in the extension log is different from that in terminal.

**Comment by hktkzyx** [comment]
> Where is your `xelatex`? Does it exist in `PATH: /home/y***z/.vscode-server/bin/4***3/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/snap/bin:/home/yzhubz/bin:/usr/local/bin:/home/y***z/.vscode-server/bin/4***3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`?
> 
> You can use `which xelatex` if you do not know.
> 
> See https://github.com/rbenv/rbenv/wiki/unix-shell-initialization for setting PATH appropriately.

My `xelatex` is in `/usr/local/texlive/2020/bin/x86_64-linux/xelatex` but not in the `PATH: /home/y***z/.vscode-server/bin/4***3/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/snap/bin:/home/yzhubz/bin:/usr/local/bin:/home/y***z/.vscode-server/bin/4***3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`. However, in terminal, the xelatex path is in `$PATH` and I can execute `xelatex` in the terminal. I think the problem is that `$PATH` showed in the extension log is different from that in terminal.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable

**Comment by tamuratak** [comment]
You have to set `zsh` as login shell:

- https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell
- https://superuser.com/questions/546761/how-do-i-start-in-bash-when-sshing-into-my-server

**Comment by hktkzyx** [comment]
> You have to set `zsh` as login shell:
> 
> * https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell
> * https://superuser.com/questions/546761/how-do-i-start-in-bash-when-sshing-into-my-server

`zsh` is login shell. I don't know why `PATH` variable showed in the log file is still different.

**Comment by tamuratak** [comment]
You can also override PATH environment variable in the recipe with `"env"`.

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes

**Comment by jlelong** [comment]
I think your need to set your `PATH` in `~/.zprofile` and not in `~/.zhsrc` (used by interactive shell only).
