### ISSUE TITLE
Use a boolean setting for latex-workshop.latex.autoBuild.run

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#2209]
It would make more sense to change `latex-workshop.latex.autoBuild.run` into a boolean `latex-workshop.latex.autoBuild.enabled` as it can only take two values: `never` and `onFileChange`. That would make #2193 cleaner.

@tamuratak Any opinion on this?

**Comment by tamuratak** [comment]
I think it makes things more complicated. We should not make two changes at the same time. How about using the union type `'never' | 'onFileChange'`?

**Comment by jlelong** [comment]
> How about using the union type `'never' | 'onFileChange'`?

I guess you mean enumeration rather than union. This is a good idea.
