### ISSUE TITLE
Scroll bars of PDF file preview don't scale (High DPI)

### ISSUE THREAD

**Issue by wollmich** [James-Yu/LaTeX-Workshop#2212]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

1. Set Windows custom scaling to 150% or 160%
2. Compile a tex file and view LaTeX PDF file

### Expected behavior

The scroll bars of the PDF file viewer are very tiny on a 4k screen. The scroll bars of the TEX editor are scaled correct.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

None
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

None
```

## Desktop [Required]
 - OS: Windows 10 64-bit 1909
 - VS Code version: 1.47.1
 - Extension version: 8.11.1
 - TeX distribution version: MiKTeX 2.9.7250

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment]
Out of the scope of the extension.
