### ISSUE TITLE
Math previews supporting for \if ... \else ... \fi 

### ISSUE THREAD

**Issue by HoyanMok** [James-Yu/LaTeX-Workshop#2213]
**Is your feature request related to a problem? Please describe.**
I defined some useful commands including `\if ... \else ... \fi` such as
```
\newcommand*{\diff}[3][1]
{\if#11%
	\frac{\mathrm{d} #2}{\mathrm{d} #3} % \diff{y}{x}
\else%
	\frac{\mathrm{d}^{#1} #2}{\mathrm{d} #3^{#1}} % \diff[n]{y}{x}
\fi}
```
`\diff y x` and `\diff[2] y x` look like:

<img width="311" alt="2020-07-16 (2)" src="https://user-images.githubusercontent.com/58337895/87663748-e3daa380-c796-11ea-97b1-0f45500d32ce.png">

But the math previews seem like confusing about them:

<img width="758" alt="2020-07-16 (1)" src="https://user-images.githubusercontent.com/58337895/87663911-08cf1680-c797-11ea-9a30-9d0573088204.png">

**Describe the solution you'd like**
I wish that the math preview interpret `\if ... \else ... \fi` correctly.

**Additional context**
Hope my poor English doesn't cause confusions, and if it does ask or correct me please.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
