### ISSUE TITLE
Refresh VSCode tab preview regardless of build failure.

### ISSUE THREAD

**Issue by SainoNamkho** [James-Yu/LaTeX-Workshop#2214]
**Is your feature request related to a problem? Please describe.**
Chances are that I enabled *auto save after delay*  and *build on save* to get live preview.
`.tex` files are builded in nonstopmode.
And when there are errors, `.pdf` file is generated and external preivew in sumatrapdf is refreshed, but in-tab preview remains unchanged.

**Describe the solution you'd like**
I need an option for "refresh VSCode tab preview regardless of build failure".
- The preivew tab may refresh on every build,
- or a temp preview tab be opened for failed builds and 
    - refreshed on successive failed builds,
    - auto-closed then navigated to the original preview tab when build succeeded.

**Comment by tamuratak** [comment]
It might be a bug. Please open a new issue filling out all the information required in the issue template.

https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
