### ISSUE TITLE
amssymb is missing in data/packagenames.json

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2222]
A minor issue. `amssymb` is missing in `./data/packagenames.json`. I am not sure we should directly write it to `data/packagenames.json`, or should fix scripts in `./dev`.

**Comment by jlelong** [comment]
This is the same kind of problem as #2082 

The file `amssymb.sty` is provided by the `amsfonts` package, which already contains an `amsfonts.sty` file. Many packages contain several `.sty` files but only one can be loaded directly into `\usepackage`, hence the current approach 

https://github.com/James-Yu/LaTeX-Workshop/blob/dd464bd740e311b6fd7eb792ebc60976c6e08a76/data/README.md#L87

I think some packages to be added _by hand_.
