### ISSUE TITLE
"press a-z and space for greek letter" in syntax/TeX.tmLanguage.json

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2223]
Just a question. Is this an intended one?

```
"match": "«press a-z and space for greek letter»[a-zA-Z]*",
```

- https://github.com/James-Yu/LaTeX-Workshop/blob/3b0ae7f1860c3d1695d3e9d7ad48a3d8c3f13ff3/syntax/TeX.tmLanguage.json#L133
- https://github.com/James-Yu/LaTeX-Workshop/blob/3b0ae7f1860c3d1695d3e9d7ad48a3d8c3f13ff3/syntax/TeX.tmLanguage.json#L237

**Comment by jlelong** [comment]
Honestly, I have no idea why it is there. It is coming from https://github.com/textmate/latex.tmbundle/blob/master/Syntaxes/TeX.plist#L273, which was used as the v0 version of our syntax file. I assume we can remove this. Let us give it a try.
