### ISSUE TITLE
synctex

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#2226]
Synctex

In windows, I am using the following two variables to invoke SumatraPDF:
     "latex-workshop.view.pdf.external.viewer.command"	: "C:/Program Files/SumatraPDF/SumatraPDF.exe",
     "latex-workshop.view.pdf.external.viewer.args":	[
          "-forward-search", "%TEX%", "%LINE%",
          "-reuse-instance",
          "-inverse-search", "\\"C:\\\\Program Files\\\\Microsoft VS Code\\\\Code.exe\\" \\"C:\\\\Program Files\\\\Microsoft VS Code\\\\resources\\\\app\\\\out\\\\cli.js\\" -r -g \\"%f:%l\\"",
          "%PDF%"],

The command "View in external viewer" starts SumatraPDF nicely and loads the pdf, the inverse search command is set correctly as well.
However, the forward search does _not_ jump to the correct line (which is invoked by "%LINE%" above).
This seems to be broken.

Thank you!

## Desktop
 - Windows 10
 - VS Code version 1.47.2
 - Extension version: 8.11.1

Thank you

**Comment by tamuratak** [comment]
External PDF viewer is not officially supported.
