### ISSUE TITLE
Snippet request for Table

### ISSUE THREAD

**Issue by bagustris** [James-Yu/LaTeX-Workshop#2229]
**Is your feature request related to a problem? Please describe.**
There is already snippet for figure (BFI), but not for table.
In most Latex writing, there is must be a table, especially in scientific writing (to present results). It will be very beneficial to have table snippets like figure, etc.

**Describe the solution you'd like**
Typing BTA (Begin TAble) and tab will open table template, probably like this:
```
begin{table}[${1:htpb}]
	\centering
	\caption{${2:caption}}
	\label{tab:${3:label}}
	\begin{tabular}{${4:c}}
	$0${5/((?<=.)c|l|r)|./(?1: & )/g}
	\end{tabular}
\end{table}
```
**Describe alternatives you've considered**
No alternative

**Additional context**
If implemented, this (wiki) feature should be located within environment group.

**Comment by jlelong** [comment]
Some parts of the snippet you proposed are far too specific such as `\label{tab:${3:label}}` and `${5/((?<=.)c|l|r)|./(?1: & )/g}`. If you really want a bespoke snippet, you should consider defining it yourself, see [VSCode's documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).

**Comment by TakingItCasual** [comment]
The figure snippet is currently the following:
```
\begin{figure}[htbp]
    \centering
    
    \caption{<caption>}
    \label{<label>}
\end{figure}
```
The table snippet could be something similar:
```
\begin{table}[htpb]
    \centering
    \caption{<caption>}
    \label{<label>}
    \begin{tabular}{<columns>}

    \end{tabular}
\end{table}
```
Something to decide is whether to put the caption/label above or below the table. Idk what the standard is, but where I'm at it's standard to put table captions above the table.

**Comment by jlelong** [comment]
I have put the caption after the tabular environment to display it below the actual table as in the `BFI` snippet.
