### ISSUE TITLE
How to enable spell check? (chktex)

### ISSUE THREAD

**Issue by Tapyu** [James-Yu/LaTeX-Workshop#2230]
Hello! I'm very beginner on VScode and I'm a little lost in how to enable a spell check with LaTeX-Workshop. Delving on the internet, I found that LaTeX-Workshop has a tool to check for common errors in LaTeX files called [chktex](https://www.nongnu.org/chktex/).

To enable this, I changed my Json file in the following way:

`{
    "latex-workshop.view.pdf.viewer": "tab",
    "window.zoomLevel": 0,
    "latex-workshop.chktex.enabled": true,
    "latex-workshop.chktex.path": "D:\\Program Files\\Miktex\\miktex\\bin\\x64\\chktex.exe"
}`

Since I specified the path of chktex and enabled the chktex, I was expected to see a underline appearing on my misspelled text. Are the any problem in my solution?

PS: How to set the language? I need to write in English, Portuguese and French.

Thank you in advance and sorry for the (possible) silly question.

**Comment by tamuratak** [comment]
`chktex` is a checker for LaTeX language, not for natural languages. For spell checking, see:

https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#spell-check

**Comment by Tapyu** [comment]
It works! Just for other beginners like me that need spell check for natural language support: If you need more language than those supported by [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker), you can find for extra spell check language, like [Portugese support](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-portuguese), for example. To configure it, you can either in the setting (typing `Cntrl + ,`) or in the pallets (typing `Cntrl + Shift + P`) and type `Show Spell Checker Configuration info` to set what the language that you are using.

I'm not sure that is necessary to install Code Spell Checker first to be able to install the Portuguese extension. I installed both.

Sorry for my confusion and thank you very much for your precise and quick information!
Desculpe pela confusão e muito obrigado pela informação rápida e precisa
Désolé pour la confusion et merci pour les informations rapides et précises
