### ISSUE TITLE
New action: Reveal output PDF in OS

### ISSUE THREAD

**Issue by janosh** [James-Yu/LaTeX-Workshop#2233]
**Is your feature request related to a problem? Please describe.**

For sharing with others you need access to the actual output file.

**Describe the solution you'd like**

A new action "Reveal output PDF in OS".

**Describe alternatives you've considered**
There's already "Reveal output folder in OS". But with `"latex-workshop.latex.outDir": "%TMPDIR%",` this opens a directory that's so full of other stuff that the PDF file is very hard to find.

![tmpdir](https://user-images.githubusercontent.com/30958850/89545598-dba8dd80-d803-11ea-9fcd-2d5074cfd51f.png)

**Comment by jlelong** [comment]
It is sufficient to use _View in external viewer_ from the TeX badge.

**Comment by janosh** [comment]
Ah yes, good point. Wouldn't it make sense to add those actions to the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)?

**Comment by jlelong** [comment]
It would! VSCode's philosophy seems to be to make everything accessible through the command palette

**Comment by janosh** [comment]
> VSCode's philosophy seems to be to make everything accessible through the command palette

Indeed. I quite like it. It's become my go to place for everything. 😄
