### ISSUE TITLE
The process of finding root

### ISSUE THREAD

**Issue by sesajad** [James-Yu/LaTeX-Workshop#2234]
I was using this plugin with a latex code which doesn't directly contain `\document{begin}` 
(I was specifically using a localized version of latex, for avoiding changing keyboard layout from time to time, but this situation is not that rare)

https://github.com/James-Yu/LaTeX-Workshop/blob/98a0b86c9df619abfb2dde054b899c6ebd960de7/src/components/manager.ts#L327

According to this line, the plugin won't detect my root correctly. I suggest that we can use `\documentclass[X]{Y}` for finding root or add a magic `%! root` beside `\document{begin}` to make it work in the mentioned situation.

If you agree with this argument, I can do it and send a PR.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-root-file

You can use `% !TEX root = relative/or/absolute/path/to/root/file.tex`
