### ISSUE TITLE
Forward search for external pdf viewer with mouse click

### ISSUE THREAD

**Issue by chkwon** [James-Yu/LaTeX-Workshop#2238]
I'm currently using Skim on macOS as the external pdf viewer.

The forward search <kbd>cmd</kbd>+<kbd>option</kbd>+<kbd>j</kbd> to jump to Skim at the current line works good. 

Can we also have a mouse click option? For example, <kbd>cmd</kbd>+<kbd>option</kbd>+left click?

**Comment by tamuratak** [comment]
Duplicate of  #716.

Upvote microsoft/vscode/issues/3130.
