### ISSUE TITLE
Update pdf on the fly

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#2239]
Suppose the file filename.PDF, displayed by the internal viewer, changes on the disk. Then the viewer reloads its content and displays the updated content. This is actually a pretty nice and essential feature for LaTeX workshop; latexmk does the changes on the disk.

In doing so, the internal tab-viewer
* fist displays the old content,
* then shows a blank screen,
* and finally displays the updated, new content.

The blank screen in between during reloading is always distracting. SumatraPDF, for example, does everything on the fly and the user would not even realize the update operation, it is done in the background.

Can we remove the distracting blank screen in between?
Note: setting latex-workshop.latex.pdfWatch.delay:0 does not remove the distracting blank screen.

Thank you.

**Comment by tamuratak** [comment]
We cannot.

You can change the backgound color if you want:

See https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfbackgroundcolor
