### ISSUE TITLE
command 'latex-workshop.view' not found

### ISSUE THREAD

**Issue by mjdcurtis** [James-Yu/LaTeX-Workshop#2240]
The previously referenced fix does not work:

temp solution:
```shell
cd "~\.vscode\extensions\James-Yu.latex-workshop-3.14.0"
npm install
```

_Originally posted by @chantisnake in https://github.com/James-Yu/LaTeX-Workshop/issues/474#issuecomment-374047566_

The developer console has the errorL Cannot find module '/home/[user]/.vscode-oss/extensions/james-yu.latex-workshop-8.11.1/out/src/main.js

Am I just out of luck?

**Comment by mjdcurtis** [comment]
I think this is a duplicate of #2160 so I will close.

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template next time.
