### ISSUE TITLE
Show only the errors on output pane

### ISSUE THREAD

**Issue by whlinaa** [James-Yu/LaTeX-Workshop#2241]
**Is your feature request related to a problem? Please describe.**
If there are errors when compiling a .tex files, the log files show lots of info that is irrelevant to the errors that the .tex file has. 
I wonder if it is possible to show only the errors in VSCode's output pane? The following screenshot shows what I'm looking for (this is the output from LatexTools for Sublime Text)

![image](https://user-images.githubusercontent.com/59403078/90309699-50bf9580-df1d-11ea-8245-49dcb09fd611.png)

Can Latex Workshop also be configured to be like the above? Now it is very difficult to know what errors the file has.

Thank you very much! I really appreciate your effort to create such a useful extension!

**Comment by tamuratak** [comment]
See:

- https://stackoverflow.com/questions/43454967/disable-wavy-underline-in-vs-code

**Comment by whlinaa** [comment]
> See:
> 
> * https://stackoverflow.com/questions/43454967/disable-wavy-underline-in-vs-code

Thank you, but this is irrelevant to what I'm asking for. What I want is that Latex workshop shows the errors in VSCode's output pane when there are errors. Currently Latex workshop's log file output does not give concise error messages, making it very difficult to find bugs in the file.

**Comment by tamuratak** [comment]
I cannot understand what you want. Explain with screenshots.

**Comment by tamuratak** [comment]
You see only problems in the problem pane:

![スクリーンショット 2020-08-15 21 27 30](https://user-images.githubusercontent.com/10665499/90312308-609ba180-df3e-11ea-90ba-d06007704210.png)

**Comment by whlinaa** [comment]
Thank you very much. Originally I thought we can see the errors in the Output pane. This is what I saw.
![image](https://user-images.githubusercontent.com/59403078/90312798-fbde4800-df39-11ea-8425-0f6029b249ac.png)

Now I can only see the errors in the Problems pane. Thank you.
