### ISSUE TITLE
Implement NewDocumentCommand parsing for Hover feature

### ISSUE THREAD

**Issue by DruvPai** [James-Yu/LaTeX-Workshop#2247]
Hi,
The [xparse](http://ctan.mirrors.hoobly.com/macros/latex/contrib/l3packages/xparse.pdf) package implements a `NewDocumentCommand` macro which is intended to be used in place of `newcommand`. Is it possible to get support for this with regards to the Hover feature (i.e. if we have a file of `\NewDocumentCommand`-defined macros, then we can parse them and then they are rendered by Hover)?

**Comment by tamuratak** [comment]
MathJax does not support it. We can do nothing on our side.
