### ISSUE TITLE
Formatting bibtex files

### ISSUE THREAD

**Issue by kam193** [James-Yu/LaTeX-Workshop#2250]
**Is your feature request related to a problem? Please describe.**
LaTeX-Workshop has a set of commands format Bibtex files (https://github.com/James-Yu/LaTeX-Workshop/wiki/Format#Bibtex-files). However, they are only functions you can manually call, not a formatting feature you can use as a formatter (by VSCode formatting interface, e.g. on saving file). LaTeX-Workshop sets themselves as a default formatter for `.bib` files, but formats them with regular LaTeX formatter which can be unexpected (e.g. breaks aligning).

**Describe the solution you'd like**
I propose to set e.g. `latex-workshop.bibalignsort` as a command used to formatting `.bib` file. 

**Describe alternatives you've considered**
Since there are three commands that can be used to formatting, it would be nice to have a configuration which will be used to formatt `.bib` files. If it's possible, it could be a separated formatter entry for Bibtex files, so user could decide which (regular LaTeX as now or Bibtex-specyfic) formatter want to use by selecting it in VSCode formatter configuration window.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Format#Bibtex-files for the different ways of formatting a `.bib` file.
