### ISSUE TITLE
PDF Tab Is Opened Twice

### ISSUE THREAD

**Issue by MDHD-Yee** [James-Yu/LaTeX-Workshop#2251]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

After setting `"workbench.list.openMode": "doubleClick"`, double click `View in VSCode tab`, the PDF tab will be opened twice.

### To Reproduce

As described.

### Expected behavior

Only open one PDF tab.

### LaTeX Workshop Output [Required]

Nothing.

### Developer Tools Console [Required]

Nothing.

## Screenshots

![image](https://user-images.githubusercontent.com/25438575/91041566-dee4fb80-e642-11ea-8574-7537a6e604ac.png)

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.48.1
 - Extension version: 8.11.1
 - TeX distribution version: TeX Live 2019

**Comment by tamuratak** [comment]
Due to a bug of VS Code.  microsoft/vscode/issues/105256

**Comment by tamuratak** [comment]
I have confirmed the issue was fixed.

Version: 1.49.0-insider
Commit: 8c9b4015feb0297d99c8051c35e85d208ffe83e3
Date: 2020-09-03T05:43:53.229Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0
