### ISSUE TITLE
Porting Zotero integration from LaTeX Utilities

### ISSUE THREAD

**Issue by janosh** [James-Yu/LaTeX-Workshop#2253]
What do you think of porting the Zotero integration from LaTeX utilities over to this project? It's super useful at least to me and I think could be for others as well if made part of this project.

Related issue: https://github.com/tecosaur/LaTeX-Utilities/issues/209.

**Comment by tamuratak** [comment]
I am against the proposal. Please maintain by yourself.

**Comment by janosh** [comment]
Because you think it's too niche or because it would be too much work?

**Comment by tamuratak** [comment]
Before you ask me, please explain why you do not become the maintainer of LaTeX Utilities.

**Comment by janosh** [comment]
I don't see the need for two separate LaTeX extensions. Having it all in one place would be better in my opinion.

**Comment by tamuratak** [comment]
You can see the reason: James-Yu/LaTeX-Workshop/pull/1478

If you want something, do it yourself at first. 

Thank you

**Comment by janosh** [comment]
> If you want something, do it yourself at first. That's OSS.

Sure, I'm happy to help with the port.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
