### ISSUE TITLE
Hide certain files in a latex workspace

### ISSUE THREAD

**Issue by CirQ** [James-Yu/LaTeX-Workshop#2256]
**Is your feature request related to a problem? Please describe.**

Many intermediate files are generated when building a latex project (.aux, .bbl, etc).
Personally, I ignore these files via the `files.exclude` setting, though I expect the extension itself can automate it.

**Describe the solution you'd like**

I have no knowledge about developing an extension, thus I don't know whether it is feasible.
If this is a valid feature request, I will learn how to do it and try to submit a PR :)

**Additional context**

To decide which files should be hidden, I think some readily available list can be considered, such as that from [gitignore.io](https://www.toptal.com/developers/gitignore/api/latex).

**Comment by tamuratak** [comment]
Out of the scope of the extension. Please use the `files.exclude` setting.
