### ISSUE TITLE
Fails when LaTeX project has spaces in directory path

### ISSUE THREAD

**Issue by SamuelMarks** [James-Yu/LaTeX-Workshop#2259]
8.11.1 with VS Code 1.48.2 on macOS 10.15.6

**Comment by jlelong** [comment]
Please post the complete logs of the extension. Do not truncate or alter them in particular if the paths contain non ascii characters.

![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77959270-98c77e00-72d6-11ea-8c58-4934a9fde39a.png)

**Comment by tamuratak** [comment]
Please notify if any progress.
