### ISSUE TITLE
LaTeX toolchain problem using MikTeX on Windows 10

### ISSUE THREAD

**Issue by Resonanz** [James-Yu/LaTeX-Workshop#226]
### Description

Getting LaTeX-Workshop to work with MikTeX is nightmare-ish LOL. Compilation fails, PDFs do not update automatically, synctex is not installed by default, the miktex binary path need to be added to the environment variables.

Below is only the compilation failure problem.

### How to reproduce

1. Set up the toolchain as below
2. Compile using Ctrl + Alt + B
3. Error

### Expected behavior

Some indication of what the error is :-)

### Actual behavior

In red: "LaTeX toolchain terminated with error"   Clicking this shows no error; no text showing in the "OUTPUT" tab.

During compilation using the following toolchain, step 1 completes, step 2 I think fails as the error arrives quickly after "...step 2..." displays in the purple bar. 

### Log messages

TOOLCHAIN
{
  "latex-workshop.latex.toolchain": [
  {
    "command": "pdflatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "%DOC%"
    ]
  }, {
    "command": "bibtex",
    "args": [
      "%DOCFILE%"
    ]
  }, {
    "command": "pdflatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "%DOC%"
    ]
  }, {
    "command": "pdflatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "%DOC%"
    ]
  }
]
}

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6350)
entering extended mode

("c:/Users/me/Documents/GitHub/Paper/mf Interfacing.tex"
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 1 language(s) loaded.
(C:\texmfs\install\tex\latex\elsarticle\elsarticle.cls
Document Class: elsarticle 2009/09/17, 1.2.0: Elsevier Ltd
(C:\texmfs\install\tex\latex\base\article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(C:\texmfs\install\tex\latex\base\size11.clo))
(C:\texmfs\install\tex\latex\graphics\graphicx.sty
(C:\texmfs\install\tex\latex\graphics\keyval.sty)
(C:\texmfs\install\tex\latex\graphics\graphics.sty
(C:\texmfs\install\tex\latex\graphics\trig.sty)
(C:\texmfs\install\tex\latex\graphics-cfg\graphics.cfg)
(C:\texmfs\install\tex\latex\graphics-def\pdftex.def
(C:\texmfs\install\tex\generic\oberdiek\infwarerr.sty)
(C:\texmfs\install\tex\generic\oberdiek\ltxcmds.sty))))
(C:\texmfs\install\tex\latex\psnfss\pifont.sty
(C:\texmfs\install\tex\latex\psnfss\upzd.fd)
(C:\texmfs\install\tex\latex\psnfss\upsy.fd)) ("mf Interfacing.spl")
(C:\texmfs\install\tex\latex\natbib\natbib.sty))
(C:\texmfs\install\tex\latex\amsfonts\amssymb.sty
(C:\texmfs\install\tex\latex\amsfonts\amsfonts.sty))
(C:\texmfs\install\tex\latex\was\gensymb.sty)
(C:\texmfs\install\tex\latex\geometry\geometry.sty
(C:\texmfs\install\tex\generic\oberdiek\ifpdf.sty)
(C:\texmfs\install\tex\generic\oberdiek\ifvtex.sty)
(C:\texmfs\install\tex\generic\ifxetex\ifxetex.sty)
(C:\texmfs\install\tex\latex\geometry\geometry.cfg))
(C:\texmfs\install\tex\latex\hyperref\hyperref.sty
(C:\texmfs\install\tex\generic\oberdiek\hobsub-hyperref.sty
(C:\texmfs\install\tex\generic\oberdiek\hobsub-generic.sty))
(C:\texmfs\install\tex\latex\oberdiek\auxhook.sty)
(C:\texmfs\install\tex\latex\oberdiek\kvoptions.sty)
(C:\texmfs\install\tex\latex\hyperref\pd1enc.def)
(C:\texmfs\install\tex\latex\00miktex\hyperref.cfg)
(C:\texmfs\install\tex\latex\url\url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(C:\texmfs\install\tex\latex\hyperref\hpdftex.def
(C:\texmfs\install\tex\latex\oberdiek\rerunfilecheck.sty))
("mf Interfacing.aux")
(C:\texmfs\install\tex\context\base\supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (C:\texmfs\install\tex\latex\oberdiek\epstopdf-base.sty
(C:\texmfs\install\tex\latex\oberdiek\grfext.sty))

Package gensymb Warning: Not defining \perthousand.

Package gensymb Warning: Not defining \micro.

*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(C:\texmfs\install\tex\latex\graphics\color.sty
(C:\texmfs\install\tex\latex\graphics-cfg\color.cfg))
(C:\texmfs\install\tex\latex\hyperref\nameref.sty
(C:\texmfs\install\tex\generic\oberdiek\gettitlestring.sty))
("mf Interfacing.out") ("mf Interfacing.out")
(C:\texmfs\install\tex\latex\amsfonts\umsa.fd)
(C:\texmfs\install\tex\latex\amsfonts\umsb.fd)

LaTeX Font Warning: Command \tiny invalid in math mode on input line 160.

LaTeX Warning: Command \textregistered invalid in math mode on input line 160.

LaTeX Warning: Command \textcircled invalid in math mode on input line 160.

(C:\texmfs\install\tex\latex\base\omscmr.fd)

LaTeX Warning: Command \textcircled invalid in math mode on input line 160.

[1{C:/texmfs/data/pdftex/config/pdftex.map}]

Package natbib Warning: Citation `parallel mfs' on page 2 undefined on input line 165.

<pics/Fig1.png, id=101, 540.8205pt x 412.4208pt> <use pics/Fig1.png>

LaTeX Warning: `h' float specifier changed to `ht'.

<pics/Fig2.jpg, id=102, 1424.32124pt x 944.52875pt> <use pics/Fig2.jpg>

LaTeX Warning: `h' float specifier changed to `ht'.

<pics/Fig3.jpg, id=105, 812.3148pt x 860.2539pt> <use pics/Fig3.jpg>

LaTeX Warning: `h' float specifier changed to `ht'.

[2] [3 <./pics/Fig1.png>] [4 <./pics/Fig2.jpg> <./pics/Fig3.jpg>]
<pics/Fig4.jpg, id=167, 1204.5pt x 884.30376pt> <use pics/Fig4.jpg>
<pics/Fig5.jpg, id=168, 1763.58875pt x 1372.12625pt> <use pics/Fig5.jpg>
[5 <./pics/Fig4.jpg> <./pics/Fig5.jpg>]
<pics/Fig6.jpg, id=181, 714.9912pt x 1337.4768pt> <use pics/Fig6.jpg> [6 <./pics/Fig6.jpg>] [7] [8] ("mf Interfacing.bbl" [9] [10])

Package natbib Warning: There were undefined citations.

[11] ("mf Interfacing.aux") )
(see the transcript file for additional information)<C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmbx10.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmbxti10.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmmi10.pfb>
<C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmmi12.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmmi8.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmmi9.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmr10.
pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmr12.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmr5.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmr8.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmr9.
pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy10.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy6.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy8.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmsy9.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmti10.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmti7.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmti9.pfb><C:/texmfs/install/fonts/type1/public/amsfonts/cm/cmtt10.pfb>
Output written on "mf Interfacing.pdf" (11 pages, 4385757 bytes).
SyncTeX written on "mf Interfacing.synctex.gz"
Transcript written on "mf Interfacing.log".

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Comment by James-Yu** [comment]
So what's the problem?

**Comment by James-Yu** [comment]
Fail compilation is LaTeX problem. No PDF update so no PDF refresh. No synctex is a miktex problem, PATH is a common knowledge for command line programs. So what's the problem please?

**Comment by Resonanz** [comment]
Latex is compiling; I think it is failing on the Bibtex stage.

**Comment by James-Yu** [comment]
Sure then it is a bibtex problem. There's nothing the extension can do. I still cannot get what the extension is supposed to react, which is not available now.

**Comment by Resonanz** [comment]
Okay, but the step 2 which is meant to compile the bibtex file fails with
no error message or indication of what the problem is.

**Comment by James-Yu** [comment]
I got your idea. Will look into that.

In the meantime, I would gently recommend you using some bibtex management software, which can rule out almost all possible bibtex errors.
