### ISSUE TITLE
Highlights don't work

### ISSUE THREAD

**Issue by raphateixeira** [James-Yu/LaTeX-Workshop#2262]
## Highlights are not working

Highlights are not working for latex commands. I don't know if it's some configuration of my vscode or something from LATEX-workshop. Anyone else with this problem? Some help?

**Comment by jlelong** [comment]
There is mostly something wrong on your side. Post the logs if you want some help

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#syntax-highlighting-does-not-work-for-most-elements

**Comment by raphateixeira** [comment]
Very good! Great information, I changed the VS-Studio theme here and the highlights returned. How could I doubt the LaTeX-Workshop? Thank you @tamuratak @jlelong !!
