### ISSUE TITLE
Unmatched Perl Lib versions

### ISSUE THREAD

**Issue by lguo-uk** [James-Yu/LaTeX-Workshop#2266]
Hi there,

To use latexdiff on Windows 10, I recently installed the Strawberry Perl. It works fine with that perticular .tex file.

However, when I start compling an other .tex file. I've encountered the conflict between different perl lib versions:
`Perl lib version (5.12.3) doesn't match executable version (v5.32.0) at C:/Strawberry/perl/lib/Config.pm line 50.
Compilation failed in require at C:\Program Files\MiKTeX 2.9\scripts/latexmk\latexmk.pl line 286.
BEGIN failed--compilation aborted at C:\Program Files\MiKTeX 2.9\scripts/latexmk\latexmk.pl line 286.`

Any suggestions?

Many thanks,
Liang

**Comment by tamuratak** [comment]
It has nothing to do with LaTeX Workshop. Ask at https://tex.stackexchange.com/.
