### ISSUE TITLE
Adding detection for weasel words

### ISSUE THREAD

**Issue by salazardetroya** [James-Yu/LaTeX-Workshop#2267]
**Is your feature request related to a problem? Please describe.**
Good writing is not easy for engineers and/or non-native speakers. One example of common but subtle mistake is the use of [weasel words](https://en.wikipedia.org/wiki/Weasel_word).  Having automated help that automatically detect this type of expressions can help many people.

**Describe the solution you'd like**
There are already several implementations that detect this type of phrases:
* https://github.com/devd/Academic-Writing-Check
* https://github.com/btford/write-good
* https://github.com/davidbeckingsale/writegood.vim

Hopefully it is not difficult to use any of these alternatives in the background.

**Describe alternatives you've considered**
No alternative considered.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
