### ISSUE TITLE
Make all commands available from the Command Palette

### ISSUE THREAD

**Issue by alanlivio** [James-Yu/LaTeX-Workshop#2268]
**Is your feature request related to a problem? Please describe.**
Today, the  "View LaTex PDF file" command appear in: (a) LaTex Workshp command panel; and (b) VScode all commands (ctrl+shift+p). However, the "View LaTex PDF file in external viewer" appear only in (a). Is there possible also appear in (b)?

**Comment by jlelong** [comment]
This has already been suggested in #2233 but I did not have time to work on this.

I think all commands provided by the extension should be accessible in the _Command Palette_. @tamuratak are you ok with this?

**Comment by tamuratak** [comment]
Yes, I am OK with this.

**Comment by alanlivio** [comment]
Nice work. Thanks.
