### ISSUE TITLE
LaTeX-Workshop the \ref and equation input

### ISSUE THREAD

**Issue by cxf208** [James-Yu/LaTeX-Workshop#2269]
**Is your feature request related to a problem? Please describe.**
Hi, after I input a figure in the tex file, I create a label for it. But when I want to reference it using \ref{}, the label won't appear automatically only if I have compiled it once. Is there some setting about this to make the \ref{} show the label immediately after I have input it ? And it seems if I just copy the label to \ref{}, the citation won't work, which means I have to compile it first, and then choose the specific label I want.

**Describe the solution you'd like**
After I have a label, I want to reference it immediately without compiling it first.

**Describe alternatives you've considered**

**Additional context**

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisenseupdateaggressiveenabled
