### ISSUE TITLE
\ref completion has problems with punctuation characters

### ISSUE THREAD

**Issue by teored90** [James-Yu/LaTeX-Workshop#227]
### Description

There is a problem with the autocompletion of references that in certain conditions results in a wrong completion, where the prefix is repeated twice. I guess there is some problem with a regex somewhere, that excludes punctuation marks.

This is a minor problem, but it is annoying because in LaTeX it is customary to use labels of the form `eq:emc2` `fig:plot`, with colon or a point to separate the prefix with its description.

### How to reproduce

1. In a .tex file, create a label with a prefix followed by a colon, for instance `\label{eq:example}`.
2. Start typing `\ref{` to trigger the autocompletion menu. Keep typing up to past the colon, e.g. `\ref{eq:exa`. 
3. Now press e.g. the left arrow to close the autocompletion menu. 
4. Write another letter of the label, e.g `\ref{eq:exam`, the autocompletion menu is back again, highlighting the ref `eq:example`. Now press TAB, to autocomplete.

### Expected behavior
The reference should be completed:

    \ref{eq:example}

### Actual behavior
What I get instead is

    \ref{eq:eq:example}

with a repeated prefix. The same happens with a point instead of a colon, and maybe other punctuation marks. It does not happen if there are just letters numbers and underscores.

### Log messages

Nothing relevant in the logs or output.

**Comment by James-Yu** [comment]
Thanks for the report. This is a known issue of how vscode handles autocompletion. There is nothing we can do from the extension side. I even changed my labeling pattern from colon to underline.

Similar problem can also be observed when you hover over some labels with colons. You can see the label is separated into two parts.

**Comment by teored90** [comment]
Has this been reported to the developers, or is there a way to do so?

**Comment by James-Yu** [comment]
Typically they receive bug reports at ms/vscode repo. I did not check if similar issues had been submitted though.
