### ISSUE TITLE
[Linux] Install Extension via bash throws "DeprecationWarning"

### ISSUE THREAD

**Issue by JayJayJazz** [James-Yu/LaTeX-Workshop#2271]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When installing the extension via the Linux bash / console, you receive a deprectation warning:

Installing extensions...
(node:5328) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'James-Yu.latex-workshop-8.12.0.vsix' was successfully installed.

### To Reproduce

1. Open any terminal application on a Linux machine (VSCode is already installed)
2. Execute "code --install-extension James-Yu.latex-workshop-8.12.0.vsix"
3. See error

### Expected behavior

The deprecation warning should not occur.

## Desktop [Required]
 - OS: Linux (Fedora 32)
 - VS Code version: 1.42
 - Extension version: 8.12
 - TeX distribution version: TeX Live 2019

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by JayJayJazz** [comment]
Hmm, this seems to be the root cause: https://github.com/microsoft/vscode/issues/82524

**Comment by tamuratak** [comment]
It is not related to LaTeX Workshop.
