### ISSUE TITLE
Revert #2270

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2272]
Moved from #2270.

Revert #2270. I have fixed the issue in a5ae5dfc36a8c9a64aff24816bb3e1801fd0a223 already. We don't have`require("pdfjs-dist")` in `src/components/builder.js` of the master.

https://github.com/James-Yu/LaTeX-Workshop/blob/8855301a04bd0f7cdc0266543024c64033ed67b5/src/components/builder.ts#L1-L9

However, in `james-yu.latex-workshop-8.12.0/out/src/components/builder.js` of the package `v8.12.0`, we still see `require("pdfjs-dist")`.

```js
const tmp = __importStar(require("tmp"));
const pdfjsLib = __importStar(require("pdfjs-dist"));
const await_semaphore_1 = require("../lib/await-semaphore");
```

Something was wrong with building the release package.

**Comment by James-Yu** [comment]
Sorry for caused misunderstanding. Let me to be exact, WSL is not working even with the above fix. Therefore the previous PR cannot be reverted. In addition, this issue has nothing to do with the previous port forwarding issue.

I will upload log and screenshots when back to dev machine.

**Comment by tamuratak** [comment]
We should discuss in this thread, not at a closed PR #2270.

**Comment by tamuratak** [comment]
The following instructions are quite vague:

> Tested again and confirmed the issue. The test is quite simple:
> 1. remove the `build` folder from `node_modules/pdfjs-dist`.
> 2. Open vscode, try to open the viewer and build project.

https://github.com/James-Yu/LaTeX-Workshop/pull/2270#issuecomment-691043098

I cannot follow them by myself.

**Comment by tamuratak** [comment]
Please create a `vsix` file with the following steps,
```
git checkout v8.12.0
rm -rf node_modules/
npm i --no-optional 
npm run release
```
and then, test with the `vsix`file. You can install the file on the remote host too.

Please provide the log messages with the above test if it fails.

**Comment by tamuratak** [comment]
Related to #2273

**Comment by James-Yu** [comment]
The issue is resolved in the above commit, and let me conclude:
1. #2270 is reverted as the root of issue is found as follows.
2. Somehow in WSL, the viewer visits `build` folder via the internal server, which points all `build` request to the non-polyfilled version.
3. I have no idea why it only happens in WSL, but at least this fix shall be a more elegant one than the previous.

**Comment by tamuratak** [comment]
@James-Yu  Will you upload log and screenshots?
