### ISSUE TITLE
v8.13.0 compiled using v8.12.0 source

### ISSUE THREAD

**Issue by trevorgunn** [James-Yu/LaTeX-Workshop#2273]
When trying to test the new bibtexFormatter, the extension kept trying to use `latexindent`.

The culprit is that the latest extension on the marketplace doesn't compile the latest `main.ts`. So for example we see

```js
// james-yu.latex-workshop-8.13.0/out/src/main.js#56
const bibtexformater_1 = require("./components/bibtexformater");
```

That should say `"./providers/bibtexformater"` if it were the latest version.

Tangentially, that should be "formatter" with two 't's. ~~I'll put in a PR shortly to resolve the spelling error.~~ done

**Comment by James-Yu** [comment]
The typo-fixing PR was merged after `8.13.0`. Will include in the next one.

**Comment by tamuratak** [comment]
This issue is not only about the typo. It is about that the package `v8.13.0` is built in a wrong way.

**Comment by James-Yu** [comment]
No. That is a bug in code, not the build.
