### ISSUE TITLE
Build/PDF button choice in editor group

### ISSUE THREAD

**Issue by lrslei** [James-Yu/LaTeX-Workshop#2275]
(#2117) Added a build icon in place of the PDF viewer's one. Unfortunately, the shortcut for the internal PDF viewer defaults to my Paste history manager (macOS), and in general, I found more consistent the possibility to open a new editor tab with the pdf from the editor group buttons.

I found no extensions to change the buttons in that UI area. Is it possible to make different icons optional from settings?

Thank you.

**Comment by trevorgunn** [comment]
Is the button an issue or is it the associated (configurable) keyboard shortcut?

**Comment by lrslei** [comment]
I'd like an option to have the PDF button back in place. Thanks for the heads-up on the shortcut though.

**Comment by tamuratak** [comment]
It is not possible.

**Comment by tamuratak** [comment]
You have the PDF button.

<img width="274" alt="スクリーンショット 2020-09-13 12 19 22" src="https://user-images.githubusercontent.com/10665499/93009394-88bd0580-f5bb-11ea-9c31-0c71a7a38bb8.png">

**Comment by lrslei** [comment]
So sorry for wasting your time! The PDF icon change misled me, I must have assumed it was native to VS code. Sorry again!
