### ISSUE TITLE
Hovering over \item in enumerate should show number

### ISSUE THREAD

**Issue by MithicSpirit** [James-Yu/LaTeX-Workshop#2280]
**Is your feature request related to a problem? Please describe.**
In long `enumerate` lists it can be difficult to keep track of the current item number without marking them with comments or repeatedly checking the pdf file.

**Describe the solution you'd like**
Similar to how hovering over some math shows it rendered, hovering over `\item` while in an enumerate environment should show the current item number.

**Comment by tamuratak** [comment]
Out of the scope of the extension. Use
```tex
\begin{itemize}
  \item[(1)] a
  \item[(2)] b
  \item[(3)] c
\end{itemize}
```
