### ISSUE TITLE
Reverse synctex keybinding setting needs reload

### ISSUE THREAD

**Issue by JesseRiemens** [James-Yu/LaTeX-Workshop#2284]
## Preliminary questions [Required]
Choosing double click in latex-workshop.view.pdf.internal.synctex.keybinding needs a reload. This is not mentioned and it seems broken if this is not made clear. 
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

When I change the setting latex-workshop.view.pdf.internal.synctex.keybinding to double-click latex workshop needs a reload for this to function. 

### To Reproduce

1. Go to settings, change this setting to double click
2. Try to double click in a pdf 
3. See that it does not work
4. Reload VS Code
5. See that it works now

### Expected behavior
I expected it to work the moment I changed the setting

Logs: Easier to reproduce than to retrieve logs, since it involves a reload and there is no setting change observed in output. 

## Desktop [Required]
 - OS: Ubuntu 20.04.1 LTS
 - VS Code version: 1.49.0
 - Extension version: 8.13.2
 - TeX distribution version: 

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Using internal PDF viewer.

**Comment by tamuratak** [comment]
Closed by https://github.com/jlelong/LaTeX-Workshop-wiki/commit/e81f101ff975ab9faa25f3729db87fc7852a880e
