### ISSUE TITLE
Enable suppressing warnings in-line

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#2285]
**Is your feature request related to a problem? Please describe.**
The document class I use is done poorly: `\documentclass{class}` throws warnings which I would generally like to keep if they are emitted elsewhere (that is, I want to suppress box warnings from this line, but not from other lines).

**Describe the solution you'd like**
I'd like to be able to do
```
\documentclass{class}  % no-warn
```

`% no-warn` can be anythin, compare `# noqa` in `black`, `#pylint:disable=...` in `pylint`, etc.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
