### ISSUE TITLE
User Snippets don't work

### ISSUE THREAD

**Issue by Rt39** [James-Yu/LaTeX-Workshop#2286]
Issue Type: <b>Bug</b>

I tried to write User Snippets in tex files, and unlike c++, I found it useless in LaTeX Workshop.

Extension version: 8.13.2
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.17763

**Comment by tamuratak** [comment]
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

Please show us `User Snippets in tex files` you defined and a tex file you are editing.

**Comment by tamuratak** [comment]
When all of the above is done, this issue will be reopened.

**Comment by tamuratak** [comment]
#2287
