### ISSUE TITLE
run vscode task to compile the latex

### ISSUE THREAD

**Issue by phoeller** [James-Yu/LaTeX-Workshop#2289]
## Preliminary questions [Required]
I create a vscode task to run the latex build and then call out the pdf viewer to show the pdf after compilation in one command. I issue the command ${command:latex-workshop.build} and ${command:latex-workshop.view} in sequence.

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
Setting up the task will partially achieve the purpose except that

1) If there is no syntax error in the latex, the latex will be compiled twice (two xelatex in the recipe), and then the external pdf viewer will be called but after that, there will be two additional compilation by xelatex after the PDF is shown. I don't know why there will be two more additional compilation.

2) Why all compilation information in the OUTPUT tab is gone

3) If there is syntax error in the latex, the compilation will be terminated but the PDF viewer will still be called, how could I force it not to call or show PDF if there is any compilation error?

### To Reproduce
Here I create the tasks.json
-----------------------
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build-latex",
            "command": "${command:latex-workshop.build}"
        },
        {
            "label": "view-latex-pdf",
            "command": "${command:latex-workshop.view}",
            "dependsOn": "build-latex"
        },
        {
            "label": "build-latex-view-pdf",
            "dependsOrder": "sequence",
            "dependsOn": [
                "build-latex",
                "view-latex-pdf"
            ],
            "problemMatcher": [],
        }
    ]
}
-----------------------
Here is my settings.json

"latex-workshop.latex.recipes": [
          {
            "name": "xelatex",
            "tools": [
              "xelatex",
              "xelatex"
                    ]
            },
          "latex-workshop.view.pdf.viewer": "external",  
          "latex-workshop.view.pdf.ref.viewer":"external",
          "latex-workshop.view.pdf.zoom": "page-fit",
          "latex-workshop.message.warning.show": false,
          "latex-workshop.view.pdf.external.viewer.command": "C:/SumatraPDF.exe",
          "latex-workshop.view.pdf.external.viewer.args": [
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "\"C:/Users/adm/AppData/Local/Programs/Microsoft VS Code/Code.exe\" \"C:/Users/adm/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js\" -gr \"%f\":\"%l\"",
        "%PDF%"
    ],
    "latex-workshop.view.pdf.external.synctex.command": "C:/SumatraPDF.exe",
    "latex-workshop.view.pdf.external.synctex.args": [
      "-forward-search",
      "%TEX%",
      "%LINE%",
      "-reuse-instance",
      "-inverse-search",
      "\"C:/Users/adm/AppData/Local/Programs/Microsoft VS Code/Code.exe\" \"C:/Users/adm/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js\" -gr \"%f\":\"%l\"",
      "%PDF%"
    ],
    "latex-workshop.latex.clean.enabled": true,
    "latex-workshop.showContextMenu": true, 
    "latex-workshop.intellisense.package.enabled": true,     "latex-workshop.latex.autoBuild.run": "never",   
    "latex-workshop.latex.autoBuild.cleanAndRetry.enabled": false,
 }

AND last, I associate the key as in keybindings.json 
-------------------------
    {
        "key": "ctrl+f3",
        "command": "workbench.action.tasks.runTask",
        "args": "build-latex-view-pdf",
        "when": "!config.latex-workshop.bind.altKeymap.enabled && editorLangId =~ /latex|rsweave|jlweave/"
    },
------------------------

1. Open a latex file (no syntax error), press ctrl-F3, the latex will be compiled with xelatex twice, and then the PDF will be shown, but after the PDF is shown, two additional xelatex will be run again. Why is it? How do I stop it?

I try to remove the "dependsOn": "build-latex" in the tasks.json, the PDF and/or PDF viewer will always be shown before the compilation is done AND NO additional compilation is executed. However, this is not what I am looking for, I would like the PDF is shown after the file is compiled.

2. Issue 2) is obvious by looking at the OUTPUT tab, we will see no compilation information, but if I run the compilation with Ctrl-L Ctrl-B (default shortcut associate to the latex build recipe),  it is normal.
 

### Expected behavior

I expected 
1) The latex source is compiled ONCE and if it succeeds, call the PDF viewer to show the PDF otherwise, don't bring up the PDF even there was one.

2) Show all compilation in the OUTPUT tab

## Logs [Required]
NO LOGS!!!

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

NO OUTPUT !!!

To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]
NO EXTRA INFO!!!
```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```



## Screenshots

If applicable, add screenshots to help explain your problem.




## Desktop [Required]
 - OS:  Windows 10
 - VS Code version: 1.49.1
 - Extension version: 8.13.2
 - TeX distribution version: TeX Live 2020




## Additional questions

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Add any other context about the problem here.

**Comment by tamuratak** [comment]
It is not supposed to use `tasks.json`.  Use the command menu on the side bar.

![スクリーンショット 2020-09-19 7 43 09](https://user-images.githubusercontent.com/10665499/93651328-167d7280-fa4c-11ea-9137-37bf55fb34ce.png)

**Comment by phoeller** [comment]
Use the command on the side will not achieve this I think. You need to compile the latex first and then call the PDF viewer, which takes two steps, isn't it? I expect it to be done in one click. Thanks.

**Comment by phoeller** [comment]
Thanks Takashi. I tried the way you mentioned but it doesn't achieve 
what I am looking for. In your way, it takes two steps: compile first, 
and execute View Latex PDF to open the PDF, I am looking for a way to 
compile and open the PDF in a SINGLE click.

**Comment by tamuratak** [comment]
> I am looking for a way to compile and open the PDF in a SINGLE click.

Not  supported. And, it will not be supported.

**Comment by phoeller** [comment]
ok, bye
