### ISSUE TITLE
Proposal: Change the quotes format

### ISSUE THREAD

**Issue by zyrikby** [James-Yu/LaTeX-Workshop#230]
While I was writing a tex document, I found out that the default double quotes are used. It would be nice to substitute them according to the LaTeX standard (double accent mark, double apostrophes), i.e.:

"quotes" -> ``quotes''

**Comment by James-Yu** [comment]
Thanks for the suggestion. I'd like to briefly discuss the design principle of this extension. In your described case, a better description should be the user decided to use double quotes. If you may try pressing ` key you will find that the extension auto-pair it with a '. This is an implementation of the principle, i.e., we do not forbid users from doing anything. There can be some special cases in which double quotes are necessary, and a compulsory replace is troublesome in these cases.

All in all, ChkTeX does a great job in alerting these "mistakes".

**Comment by zyrikby** [comment]
Thank you for the clarification. I did not know about this hack! I will use it from now on.
