### ISSUE TITLE
Add support for Tectonic

### ISSUE THREAD

**Issue by GalacticLion7** [James-Yu/LaTeX-Workshop#2301]
Could you add support for [Tectonic](https://tectonic-typesetting.github.io/en-US/)?

**Comment by tamuratak** [comment]
Your request is too vague. Please provide a complete description.

**Comment by jlelong** [comment]
Is it about merging #2276?

**Comment by GalacticLion7** [comment]
> Is it about merging #2276?

Exactly. Thanks!
