### ISSUE TITLE
Feature Request: latex-workshop.latex.auxDir

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#2306]
**Is your feature request related to a problem? Please describe.**
I'd like a setting `latex-workshop.latex.auxDir`, similar to `latex-workshop.latex.outDir`.

It should default to the value of `latex-workshop.latex.outDir`.

It should only be effective when `--aux-dir` is supported (e.g., MiKTeX ). In other cases, this settings should be ignored.

**Comment by tamuratak** [comment]
Out of the scope of the extension. The feature makes implementation too complicated.
