### ISSUE TITLE
data/packages/latex-document_cmd.json includes lots of lesser-used commands

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2309]
`data/packages/latex-document_cmd.json` includes lots of lesser-used  commands. They make finding `\left\{ ...\right\}` difficult. I don't like the idea loading all the commands in `latex-document_cmd.json` by default.

![スクリーンショット 2020-10-01 14 37 37](https://user-images.githubusercontent.com/10665499/94772041-b4315400-03f3-11eb-9d5e-7e0a4dc215d3.png)

**Comment by tamuratak** [comment]
What makes things difficult here is that pressing `{` closes the completion items.

**Comment by jlelong** [comment]
I agree that the completion list is probably too long but it is not really clear to me how to cut it down.

Concerning the difficulty of finding `\left\{`, one should keep in mind that

- `@{` is a snippet prefix for `\left\{ ... \right\}`. The same works for `(` and `[`.
- With `editor.suggestSelection = "recentlyUsedByPrefix"`, vscode remembers how a give prefix has recently been completed and orders the next completion accordingly.

**Comment by tamuratak** [comment]
> @{ is a snippet prefix for \left\{ ... \right\}. The same works for ( and [.

Thanks. I didn't know it. It fits my need.
