### ISSUE TITLE
\ac does not match \acute in completion items

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2310]
With the following steps, `\ac` does not match `\acute`

1. Type `\a`
1. Press `Escape` to close completion items.
1. Press `Ctrl-Space` to open completion items again.
1. Press `c`

![Oct-01-2020 14-55-09](https://user-images.githubusercontent.com/10665499/94773189-3fabe480-03f6-11eb-9f42-b9c48cb41dbc.gif)

Version: 1.50.0-insider
Commit: 0c50e1db17168a738235bd7e5c02b9f05ea5df59
Date: 2020-09-30T06:45:45.996Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

**Comment by jlelong** [comment]
I have managed to narrow down this issue a little.

If after the steps 1-4, you enter `c`, a completion popup shows `\acute`.

When changing `2` by `3` in 

https://github.com/jlelong/LaTeX-Workshop/blob/71eb4fb8629fcbdf7226ca1e70574f35dc33615b/syntax/syntax.json#L40

Typing `c` (second letter) does not make the completion popup disappear but the `u` does (third letter). There is still some mystery in there.

**Comment by tamuratak** [comment]
Reported at microsoft/vscode/issues/108012

**Comment by tamuratak** [comment]
We close the issue because they have closed microsoft/vscode/issues/108012 as expected.
