### ISSUE TITLE
[HOW-TO] Resolving formatting errors on macOS

### ISSUE THREAD

**Issue by SamuelMarks** [James-Yu/LaTeX-Workshop#2311]
Formatting kept failing without any error message.

Here's how I resolved this (macOS):
```
$ brew install perl
$ PERL_MM_OPT='INSTALL_BASE='"$HOME"'/perl5' cpan local::lib
$ echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> "$HOME"'/.bash_profile'
$ cpan install CPAN
$ cpan install Log::Log4perl Log::Dispatch::File YAML::Tiny Unicode::GCString
```

Hopefully this'll help others. This command—derived from https://github.com/James-Yu/LaTeX-Workshop/issues/1938 —may also assist you in debugging:
```
/usr/local/texlive/2020/texmf-dist/scripts/latexindent/latexindent.pl -c '/tmp' -o 'example.tex' -y="defaultIndent: ' '" 'example.tex'
```

EDIT: Do you want this in [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Install)?

**Comment by tamuratak** [comment]
You can contribute at https://github.com/jlelong/LaTeX-Workshop-wiki
