### ISSUE TITLE
Remove ``eqnarray'' from the auto-completion list

### ISSUE THREAD

**Issue by Romeoly** [James-Yu/LaTeX-Workshop#2312]
**Is your feature request related to a problem? Please describe.**
``eqnarray'' is obsolete and should be avoided. Ref [http://tug.org/pracjourn/2012-1/madsen/madsen.pdf](tug-suggestion)

**Describe the solution you'd like**
Just remove it.

**Comment by tamuratak** [comment]
We want to make the extension more configurable rather than opinionated.
