### ISSUE TITLE
How to install packages?

### ISSUE THREAD

**Issue by anjalibhavan** [James-Yu/LaTeX-Workshop#2313]
Hi,
My apologies if this is a trivial question, I could not find the answer anywhere.
I wish to use some Latex packages (like minted) in my document, but on importing them I get error. I suppose they have to be installed separately. How do I do that? I'm using WSL Ubuntu 18.04.

**Comment by tamuratak** [comment]
Ask at https://tex.stackexchange.com

https://tex.stackexchange.com/a/40101
