### ISSUE TITLE
Documentation does not list reverse search command for sumatrapdf

### ISSUE THREAD

**Issue by fpqc** [James-Yu/LaTeX-Workshop#232]
I switched from an older LaTeX IDE to vscode and your excellent package.  However, the documentation does not document precisely how we should signal back from software like sumatrapdf for inverse search in LaTeX.

Could you add this to the documentation? I'm totally stumped.

**Comment by James-Yu** [comment]
The extension does not officially support 3rd party  viewers. Reasons were explained in many previous issues.

**Comment by kav2k** [comment]
While it may not officially support it, inverse search doesn't need support from the extension.

For SumatraPDF, you need to invoke VSC with "goto" switch. For default installation:

```
"C:\Program Files\Microsoft VS Code\Code.exe" -g "%f:%l"
```
