### ISSUE TITLE
Close auto-enclosure of dollar sign $

### ISSUE THREAD

**Issue by Baio0** [James-Yu/LaTeX-Workshop#2321]
Hello, is there a way to close the auto-enclosure of dollar sign "$"?  I'm a math student and use VS-code to write paper. It is not convenience that each time when I type $, two $ appears and when I delete one, two $ is delated. Each time I have to type 3 keys (one $, one right arrow, and one backspace) to type one $. 

I'm a new user. Could anyone tell me how to close this auto-enclosure function? 

Thanks.

**Comment by tamuratak** [comment]
> when I type $, two $ appears and when I delete one, two $ is delated. Each time I have to type 3 keys (one $, one right arrow, and one backspace) to type one $.

LaTeX Workshop does not provide this feature. Please disable all the extensions of VS Code except for LaTeX Workshop.
