### ISSUE TITLE
case sensitive for build on windows

### ISSUE THREAD

**Issue by rphlypo** [James-Yu/LaTeX-Workshop#2323]
**Is your feature request related to a problem? Please describe.**
Windows seems to enforce .TEX as an extension, but when the extension is capitalised LaTeX workshop does not build the file.

**Describe the solution you'd like**
Adding "**/*.TEX" to the default root detection latex-workshop.latex.search.rootFiles.include

**Describe alternatives you've considered**
Manually rename the files with lowercase .tex extension.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue.

**Comment by tamuratak** [comment]
Closed by #2332
