### ISSUE TITLE
Highlight column separator & in longtable

### ISSUE THREAD

**Issue by nvmnghia** [James-Yu/LaTeX-Workshop#2327]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Highlight column separator `&` in  `longtable` environment.

This is the current `longtable`:

![image](https://user-images.githubusercontent.com/22721156/96013538-94784200-0e6f-11eb-9174-99dbb757ce44.png)

This is the current `tabular`:

![image](https://user-images.githubusercontent.com/22721156/96013596-a659e500-0e6f-11eb-87d3-2c6b3ed2c0a3.png)

**Describe alternatives you've considered**
No, I can't find any alternatives.

**Additional context**
No further context. Doesn't everyone love syntax highlighting?

**Comment by nvmnghia** [comment]
@jlelong Hi, sorry for asking for another syntax highlighting.

I want to add syntax highlighting for [`nicematrix`](https://ctan.org/pkg/nicematrix).

I understand that keep asking for syntax highlighting is a waste of time, so I just comment here. This one indeed seems to be less popular than `longtable`. Please ignore my request if you are not interested.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Highlight column separator `&` and other values in `nicematrix`'s environments.

This is the current `matrix`:

![image](https://user-images.githubusercontent.com/22721156/98406646-eee87500-20a0-11eb-8bb8-899b47f32d09.png)

This is the current `bNiceArray`:

![image](https://user-images.githubusercontent.com/22721156/98407565-75ea1d00-20a2-11eb-92ba-5746bfa8f1d1.png)

(`b` for square brackets, `Array` instead of `Matrix` for the `{cccc:c}` argument, and `:` in the argument for dotted vertical line)

**Describe alternatives you've considered**
No, I can't find any alternatives.

**Additional context**
No further context.

**Comment by tamuratak** [comment]
Please open a new issue
