### ISSUE TITLE
Add a command to show all bibliography

### ISSUE THREAD

**Issue by lwg342** [James-Yu/LaTeX-Workshop#2330]
**Is your feature request related to a problem? Please describe.**
Sometimes I'd like to use cite-keys as labels or indices and sometimes I'd like to define new commands that use cite-keys. Right now I have to manually copy the cite-key or type \cite{Intellisense} and delete \cite afterwards. 

**Describe the solution you'd like**
It would be nice to have a command to show all the bibliography in Intellisense style so we don't  have to type "\cite{}", etc.  

**Describe alternatives you've considered**
I remember Sublime Text used to have this command.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by lwg342** [comment]
There is a command "latex-workshop.citation" but I forgot.
