### ISSUE TITLE
Could we fix the ID of the localhost?

### ISSUE THREAD

**Issue by zheyuanWang** [James-Yu/LaTeX-Workshop#2333]
Hi,

every time I need to re-launch the pdf-viewer in the browser. I'd like to keep the page opening so that I don't need to adjust the trimming and config the dark reader (a chrome plugin) repeatedly.

I notice that the local host has an address like 
`http://localhost:55490/viewer.html?file=pdf..YyU`
of which the ID `55490` changes every single time I start the PDF viewer from Latex-Workshop.
Is if possible to fix the ID of the localhost?

Best Regards
wuxiaji

**Comment by tamuratak** [comment]
Set any number larger than `1024` to https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewerpdfinternalport
