### ISSUE TITLE
snippets into snippets

### ISSUE THREAD

**Issue by alexisflesch** [James-Yu/LaTeX-Workshop#2335]
Hi,

First of all, thanks a lot for you work, I love LaTeX-Workshop !

I have one feature request though but I'm not sure whether LaTeX-Workshop is responsible for this odd behavior or if vscode is.

**Description of the problem**

When I start, say, a fraction with a snippet (with `@/`) and hit TAB, I get `\frac{}{}` as expected. Now, if I want to use another snippet while I am in the fraction, say : 
`\frac{u__}{}` in order to write `\frac{u_{n+1}}{}`, when I hit `TAB` again I get sent to the denominator of my fraction and the double underscore isn't replaced with `_{}`. This happens to me in a lot of situations.

Another example, if I want to write : 
`\[ \frac{a}{b}\]`
I would expect to be able to do it by writing:
`\[ TAB @/ TAB a TAB b TAB`
But it doesn't work because I'm trying to insert a snippet inside another snippet and `TAB` gets captured by the first snippet.

Maybe I'm not using `TAB` the right way ? I've googled this a bit and couldn't find anything useful.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-nest-snippets

**Comment by alexisflesch** [comment]
Thanks a lot, I obviously didn't google this with the right keywords. Sorry !
