### ISSUE TITLE
Hover on citation with multiple references should show each citation

### ISSUE THREAD

**Issue by shaferandrew** [James-Yu/LaTeX-Workshop#2336]
**Is your feature request related to a problem? Please describe.**
Hovering on `\cite{Knuth}` will show the correct tool tip.
Hovering on `\cite{Knuth, Steele}` will only show the first tool tip and not the other references.

**Describe the solution you'd like**
Hovering over `\cite{a, b, c}` (or `\cite{a,b,c}`) should either:
1) show all three references in one tool tip, or
2) show just the reference being hovered over

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jlelong** [comment]
Humm, it already works the way you expect. With `\cite{a, b}` (the space does not matter), hovering over `a` shows a tooltip related to `a`. The same works for `b`.

**Comment by shaferandrew** [comment]
@jlelong is correct.  Thanks for the information.

My mistake is that I was trying to move my cursor directly between the items in `\cite{a, b}`.  One must move the mouse off the citation (to clear the tooltip) and then bring the hover back over the desired citation item.

This issue can be closed.
