### ISSUE TITLE
Add Support for concealing Text

### ISSUE THREAD

**Issue by siddhantgoyal44** [James-Yu/LaTeX-Workshop#2337]
**Is your feature request related to a problem? Please describe.**
I usually write maths documents. and the source becomes pretty ugly, and hard to read.
**Describe the solution you'd like**
I think concealing text such as replacing \alpha for α and fractions appearing as real fractions etc, might be nice

**Additional context**
Please checkout the readme of [this vim plugin](https://github.com/KeitaNakamura/tex-conceal.vim), it demonstrates quite accurately what I am asking for.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
