### ISSUE TITLE
Be able to terminate LaTEX builds if they take too long.

### ISSUE THREAD

**Issue by arjo129** [James-Yu/LaTeX-Workshop#2338]
**Is your feature request related to a problem? Please describe.**
Sometimes when creating TiKz diagrams, if someone forgets to place a semicolon one finds that the `pdflatex` seems to go into an infinite loop. This is kind of annoying for users as there is no way currently to kill the current `pdflatex` process.

**Describe the solution you'd like**
Ideally if I end up introducing an infinite loop in my TeX code I should be able to stop the loop from executing via the GUI. Perhaps a terminate build button somewhere would be useful.

**Describe alternatives you've considered**
My current workflow involves closing vscode then calling `killall` on the runaway `pdflatex` process.

**Additional context**

**Comment by tamuratak** [comment]
Select `Build LaTeX project` > `Terminate current compilation` in the side bar.
