### ISSUE TITLE
Syntax highlighting in `optidef` package

### ISSUE THREAD

**Issue by martincornejo** [James-Yu/LaTeX-Workshop#2347]
I'm not 100% sure if this issue should be reported here or is related to the [optidef](https://github.com/jeslago/optidef/issues) package directly.

The optidef package provides an environment for formulating optimization problems, for example:

```latex
\documentclass{article}

\usepackage{optidef}

\begin{document}

\begin{mini}  % formulate minimization problem
  {w}{f(w)+ R(w+6x)}
  {\label{eq:Example1}}{}
  \addConstraint{g(w)}{=0}
  \addConstraint{n(w)}{= 6}
  \addConstraint{L(w)+r(x)}{=Kw+p}
  \addConstraint{h(x)}{=0.}
\end{mini}

\end{document}
```

Problem is the body inside the `optidef` environment is highlighted as a *text* environment instead of a ***math*** environment, leading to some unnecessary warnings and making it more difficult to visualize.

**Comment by jlelong** [comment]
This is the right for reported the wrong highlighting of environments defined by the `optidef` package.
What can easily be done is to highlight environments matching `(arg)?(mini|maxi)[!\*]?` as math environments.
