### ISSUE TITLE
Using \( for starting a mathematical expression completes with ) rather than \), also quotation marks.

### ISSUE THREAD

**Issue by fpqc** [James-Yu/LaTeX-Workshop#235]
The suggested formatting for mathematical expressions is `\( ... \)` for inline expressions and `\[ ... \]` for displays. However, LaTeX Workshop matches parentheses and brackets without respect to these rules, so typing in `\(` will have it complete with `\( ... )`, same with square brackets.  It should probably match a `\(` with a `\)` at the end.

Also, left ticks, which in TeX are used for lefthand quotation marks, are automatically matched with apostrophes on the second half, as it should be, but if you insert a quote containing apostrophes inside 

```     `` ...aasdf's... ''```,

 they are removed from the end of the quote.  I think this is a bug.

**Comment by James-Yu** [comment]
I will look into the first issue soon.

As to the quotation problem, I'm afraid this is constrained by how vscode auto-pairs these tokens. The basic rule is, if the token-to-be-inserted is on the right of the cursor, no new tokens will be inserted.

Or I may mis-interpret the issue.

**Comment by fpqc** [comment]
@James-Yu Yeah, I guess that's a vscode limitation.

**Comment by James-Yu** [comment]
Unfortunately, the math mode pairing for `\(` is not supported by vscode. Specifically,
```
	"autoClosingPairs": [
		["{", "}"],
		["[", "]"],
		["(", ")"],
		["$", "$"],
		["`", "'"],
		["\\(", "\\)"]
	],
```
won't work. There can be some dirty hack like listening to user input and programatically add an addtional `\`. However, I am hesitated to do so since it can be against vscode's design principle, and quality control can be a big issue. Though I will push a small fix on the pairing of ` and '. Further discussion is welcomed.

**Comment by fpqc** [comment]
Can you add an option to disable paren and bracket pairing  then? Having it half working is worse for my workflow than not working at all.

Also, I might submit an upstream issue, and I'll link that issue here, if you could explain the limitation to them if I get it wrong!

**Comment by fpqc** [comment]
thanks! Where do I put that? Settings?

**Comment by lagru** [comment]
Open *File > Preferences > User Snippets*, select "LaTeX" in the dialog and a file named "latex.json" should open.

Paste the above snippet to the appropriate place inside the file and save. After that try typing the following inside a TeX file ``--im`` (which is my chosen prefix) and press tab. VSCode should now replace the prefix with ``\(...\)``.
