### ISSUE TITLE
Add support for Rmarkdown compilation (.Rmd files)

### ISSUE THREAD

**Issue by BerriJ** [James-Yu/LaTeX-Workshop#2354]
Compiling .Rnw documents is already implemented and uses the "rnw2tex" tool which invokes two R commands. Compiling .Rmd files is even more simple as it only uses one R command.  Implementing this should be straightforward and would be a huge time saver and would be very convenient. I tried setting this up on my own. However, when I add "**/*.Rmd" like so:

```
"latex-workshop.latex.search.rootFiles.include": [
  "**/*.tex",
  "**/*.rnw",
  "**/*.Rnw",
  **"**/*.Rmd"**
]
```

Latex-Workshops does not get activated when I open an .Rmd file. Furthermore I setup a recipe and a tool:

```
"latex-workshop.latex.recipes": [
 
        {
            "name": "Compile Rmd files",
            "tools": [
                "rmarkdown"
            ]
        }
    ],

"latex-workshop.latex.tools": [
        
        {
            "name": "rmarkdown",
            "command": "Rscript",
            "args": [
                "-e",
                "rmarkdown::render('%DOCFILE_EXT%')"
            ],
            "env": {}
        }
    ],
```

However, when I invoke this recipe I get "Cannot find LaTeX root file." In the Latex-Workshop Output. 

**Describe the solution you'd like**
Add detection of .Rnw files and (optionally) add the default tool + recipe I provided above.

**Describe alternatives you've considered**
There are no other extensions letting you (automatically) compile .Rnw documents. 

Thanks in advance. Love this extension.

**Comment by jlelong** [comment]
`Rmarkdown` has nothing to do with LaTeX and hence with this extension, it is about embedding dynamic `R` code inside `markdown`. It seems that `Rmarkdown` is already supported by https://github.com/Ikuyadeu/vscode-R
