### ISSUE TITLE
Tests using subfiles will break with v2.0 because of leading spaces

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#2356]
This is related to gsalzer/subfiles/issues/13

Version `v2.0` of `subfiles` does not accept leading spaces in front of `\begin{document}` in the sub files. Hence, many tests will break because 

https://github.com/James-Yu/LaTeX-Workshop/blob/a32dfdfe754e969fb9a4740d23b97e05f40650c0/test/build.test.ts#L297-L299

It basically inserts a space in front of `\begin{document}` and saves the file. Then, it relies on buildOnSave.

**Comment by gsalzer** [comment]
With `subfiles v2.1`, currently only available on [Github](https://github.com/gsalzer/subfiles), this issue is resolved.
