### ISSUE TITLE
Automatically \usepackage when the extension detects that a style from that package is being used

### ISSUE THREAD

**Issue by akhilesh-balaji** [James-Yu/LaTeX-Workshop#2357]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I need to keep importing packages with `\usepackage` whenever I need to use some macro out of the default macros. For instance, using `amsmath`.

**Describe the solution you'd like**
I'd like the extension to detect when a macro outside the default macros is being used, and appropriately import the correct package. For instance, if I use `\frac{}{}` without importing `amsmath`, the extension would detect that I am using a macro from `amsmath`, and insert `\usepackage{amsmath}` in the beginning. Android Studio has similar functionality with its Java files: If it detects that I'm using a function without importing the appropriate module/library, it adds the `import...` statement to the beginning of the document.

**Describe alternatives you've considered**
I wasn't able to find any alternatives to this.

**Additional context**
Rough mockup of what it might do: https://we.tl/t-pjoKPLYHVV

**Comment by tamuratak** [comment]
Out of the scope of the extension.
