### ISSUE TITLE
Run recipies based on priority

### ISSUE THREAD

**Issue by akhilesh-balaji** [James-Yu/LaTeX-Workshop#2358]
**Is your feature request related to a problem? Please describe.**
When I use LaTeX, I may or may not have a `bibiliography.bib` file for references. However, when I _do_ have one, I have to run pdflatex, bibtex, pdflatex, pdflatex to get it to work. So, I set my recipies to this:
```
  "latex-workshop.latex.recipes": [
        {
            "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        },
        {
            "name": "pdflatex",
            "tools": [
                "pdflatex"
            ]
        },
```
However, when I _don't_ have a bib file, the extension keeps popping up with error messages that bibtex gives because it's not able to find a bib file.

**Describe the solution you'd like**
I'd like the recipes to be "priority based". So, if I run the first recipe, and there's an error, LaTeX workshop can revert those changes, I try building with the next recipe in line. Otherwise, do nothing. If there's already a way to do this, please let me know. If this keeps happening, I've considered moving to TeXWorks. The only reason I'm still sticking with VS Code is because the UI is better.

**Describe alternatives you've considered**
If there is an error message, there should be a way to suppress it in that specific scenario.

**Comment by tamuratak** [comment]
Define a different recipe and use it.

You can also disable error messages in popup notifications. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessageerrorshow

**Comment by jlelong** [comment]
I think the real solution to your problem is to rely on a third party tool such as `texify` (MikTeX only) or `latexmk` (part of TeXLive) to properly handle compilation. These tools are responsible for calling the proper bibliography tool if needed and for running the LaTeX compiler the appropriate number of times. 

Note that the default recipe in LaTeX-Workshop uses `latexmk`.
