### ISSUE TITLE
Dosen't compile tex with citations without `-f` for `latexmk`

### ISSUE THREAD

**Issue by sainho93** [James-Yu/LaTeX-Workshop#236]
### Description
With default setting for LaTex `latex-workshop.latex.toolchain` Workshop will stop, but if I add `-f` (Force latexmk to continue document processing despite errors) for `latexmk`, it can run correctly.
Using Latex Tools in SublimeText, which is also uses `latexmk` with `-f`, it can also run correctly.

### How to reproduce

1. With default setting, try to build latex project. (but I used `-xelatex` rather than `-pdf`)

### Expected behavior

tex files will be compiled with citations

### Actual behavior

Stopped after first compiling ( compile for a tex using bibles should be 4 compiling
s)

Here is the errors, it shows that tex has not been compiled with bibtex for citations

![2017-08-15 13 26 26](https://user-images.githubusercontent.com/13290588/29314581-d932278a-81be-11e7-896c-805b1453864b.png)

Here is what it is in PDF

![2017-08-15 13 31 55](https://user-images.githubusercontent.com/13290588/29314636-1ff2779c-81bf-11e7-94bc-46af14b3f10d.png)

### Log messages for error
```
[21:03:15] Build root file /Users/sainho93/CloudStation/BachelorArbeit/Bachelor Thesis/HauptDoc.tex
[21:03:15] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-xelatex,/Users/sainho93/CloudStation/BachelorArbeit/Bachelor Thesis/HauptDoc
[21:03:17] LaTeX log parsed with 130 messages.
[21:03:17] Toolchain returns with error: 12/null.
```

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

#### Log messages for `-f` mode
```
[21:05:23] Toolchain step 1: latexmk, -f,-synctex=1,-interaction=nonstopmode,-file-line-error,-xelatex,/Users/sainho93/CloudStation/BachelorArbeit/Bachelor Thesis/HauptDoc
[21:05:48] LaTeX log parsed with 3 messages.
[21:05:48] Toolchain returns with error: 12/null.
```
Although it also shows error `12/null` and 3 error messages,  but actually it've compiled tex files with citations in one time. 

![2017-08-15 13 30 05](https://user-images.githubusercontent.com/13290588/29314673-492928d6-81bf-11e7-97bb-bc9720ee8473.png)

#### Compiling in Sublime Text
It's correct compiled.
 
![2017-08-15 13 33 47](https://user-images.githubusercontent.com/13290588/29314658-37f1368a-81bf-11e7-8f0a-9de863c8ddda.png)

**Comment by James-Yu** [comment]
Can you try the same command in terminal? It seems that the extension correctly terminates upon latexmk returns nonzero return code.

**Comment by James-Yu** [comment]
I reread your issue description and am more confused. In your described case, it seems that there are errors in the LaTeX. Hence latexmk returns error, and the extension stops correctly. So can you elaborate more on the problem? It seems that the workflow and extension implementation are all correct.

**Comment by sainho93** [comment]
@James-Yu There are errors in the Tex, but when I uses sublimeText and `-f` mode in Workshop, tex file can be compiled correctly. The problem is, with default setting workshop can't compile tex in one click for citation, I must click it 4 times for a tex with citation, just like without latexmk.

**Comment by James-Yu** [comment]
Sorry but I have to say supporting LaTeX compilation with errors is really a niche use case, and will not be specially entertained.

Meanwhile, it is `latexmk` terminates 'pre-maturely', and notifies the extension that something wrong happens. I would suppose the said 'bug' is actually related with `latexmk`. You are recommended to submit issues to its developer, and let `latexmk` returns a special code indicating this use case.

**Comment by James-Yu** [comment]
All in all, it is really disturbing to run the compile command four time once the first time returns an error. This will cause significant troubles to normal users who expect an error should be immediately notified to the user.

**Comment by sainho93** [comment]
Thanks for your responds, again! LaTeX Workshop is absolutely a powerful extension and the reason, why I've switch from sublimetext to vscode.

**Comment by James-Yu** [comment]
Thanks for your favor. Really sorry that the issue cannot be solved with an elegant solution.
