### ISSUE TITLE
Ability to set a keyboard shortcut for “View in external viewer”

### ISSUE THREAD

**Issue by Josef-Friedrich** [James-Yu/LaTeX-Workshop#2365]
**Is your feature request related to a problem? Please describe.**
I use the internal PDF viewer to work on my documents. I use the external viewer to print the finished document.

**Describe the solution you'd like**
I would like to use a custom keyboard shortcut to open the current document in a external viewer.

**Comment by jlelong** [comment]
It is sufficient to define a shortcut for the command `latex-workshop.viewExternal`, see https://code.visualstudio.com/docs/getstarted/keybindings.

**Comment by Josef-Friedrich** [comment]
Are you sure? 

I got this error: command 'latex-workshop.viewExternal' not found

```json
  {
    "key": "ctrl+l ctrl+p",
    "command": "latex-workshop.viewExternal",
    "when": "editorLangId == latex"
  }
```

**Comment by jlelong** [comment]
This is because, the command `latex-workshop.viewExternal` only exists once the LaTeX-Workshop extension is loaded. Make sure to open a `.tex` file (to load the extension) before defining the shortcut. You can use the shortcut preference pane (`Ctrl-K` `Ctrl-S`) and search `external`.

**Comment by tamuratak** [comment]
The command, `latex-workshop.viewExternal`, is not included in `v8.13.2`. It will be available in the next release.

**Comment by jlelong** [comment]
Good point! I completely forgotten we had not made a new release for so long. 
I think we should try to make new releases more frequently.

**Comment by Josef-Friedrich** [comment]
Thank you for pointing this out! Thank you for this great extension!
