### ISSUE TITLE
Follow-up:  #2041 

### ISSUE THREAD

**Issue by sirtoobii** [James-Yu/LaTeX-Workshop#2367]
Since the issue is closed for non-collaborators, the following can be added as comment:

Possible cause:
On debian (and probably all debian based distros with bash), the `.profile` is loaded at login. Together with `.profile`, `.bashrc` is **loaded as long you haven't created a `.bash_profile` file**. 
And since most "tutorials" suggest to edit `.bashrc`, newly spawned shells (which is the case in vs code) see a different `$PATH` as you may observe in a "normal" terminal window.

 #2041

**Comment by jlelong** [comment]
I do not think this is specific to Debian. It works pretty much the same on all Linux distros.

A very explanation on what is what https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

To keep it short, only stuff from `.profile`, or `.bash_profile` is available to GUI applications.

**Comment by tamuratak** [comment]
#2041 is an issue happening on macOS, not Debian.

If you want to contribute to documentation, please open a PR at https://github.com/jlelong/LaTeX-Workshop-wiki.
