### ISSUE TITLE
Snippet @{ does not work in some cases. } is missing.

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2368]
The snippet `@{` does not work in some cases. `}` at the end is missing.  

I encounter this issue when the cursor is at a non-space character.

Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

![Nov-10-2020 13-05-07](https://user-images.githubusercontent.com/10665499/98626779-cccb4d00-2355-11eb-9eeb-6586a2994462.gif)

**Comment by tamuratak** [comment]
Duplicate of #1423

**Comment by jlelong** [comment]
The closing `}` is automatically added by vscode when `editor.autoClosingBrackets=languageDefined` and there is a white space after the cursor. 

See https://code.visualstudio.com/api/language-extensions/language-configuration-guide#autoclosing-before more details on auto closing. I will investigate to see if it can be improved
