### ISSUE TITLE
Conflict with vscode-pdf plugin?

### ISSUE THREAD

**Issue by qiujiangkun** [James-Yu/LaTeX-Workshop#2369]
## Preliminary questions [Required]
I have this config `LaTeX Workshop: View LaTeX PDF file in VSCode tab` and `vscode-pdf` plugin. However, I always get a prompt saying that LaTeX Workshop conflicts with vscode-pdf, please disable either of these. I don't want to disable either because it would cause many inconveniences. Without vscode-pdf I can hardly view pdfs in vscode tab other than latex rendered pdf. 
Moreover, I can use these two normally. I don't understand why and how they are in conflict. (Maybe because of pdf.js?)

**Comment by tamuratak** [comment]
You can preview PDF files only with LaTeX Workshop.

Please click a link in the message `The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?`, when you open a PDF file in VS Code.
