### ISSUE TITLE
Define additional verbatim-like environments

### ISSUE THREAD

**Issue by karljs** [James-Yu/LaTeX-Workshop#237]
I often have to define extra environments which behave in a manner similar to `verbatim` but with small changes.  I also often typeset Haskell code, which frequently makes use of the `$` function.  When a single `$` occurs in a non-`verbatim` environment, it causes the whole rest of the file to be highlighted like it is in math mode even when it's not.  It would be greatly helpful if you could provide a setting that lets me define which environments should be treated like `verbatim`.

Emacs/Auctex do this with `LaTeX-verbatim-environments`

**Comment by James-Yu** [comment]
Unfortunately it is not configurable with vscode. All syntax highlights are hard coded.
