### ISSUE TITLE
Enable Snippet View and drop the support for VS Code < 1.50.0

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2374]
Webview View API is available since [1.50.0](https://code.visualstudio.com/updates/v1_50#_webview-views). With the API, we can implement Snippet View in the side bar.

![スクリーンショット 2020-11-14 16 26 08](https://user-images.githubusercontent.com/10665499/99142261-a92a3e80-2696-11eb-8e7e-9537ece61784.png)

Can we drop the support for VS Code < 1.50.0?

**Comment by jlelong** [comment]
I think we can drop the support for vscode < 1.50.0. People wanting the new LW features are probably up to date with vscode releases.

**Comment by tamuratak** [comment]
Done. 1e251a05c9747df8416f53b6d48168515335db8b.
