### ISSUE TITLE
Addition of a setting to the viewer that prevents duplicate tabs being created when the view command is run?

### ISSUE THREAD

**Issue by samuel-zuk** [James-Yu/LaTeX-Workshop#2377]
Would it be possible to add a setting to the pdf viewer that prevents creating duplicate tabs of the same file when one is already open? Currently, running latex-workshop.view will always open a new internal viewer if it is set to do so, but I was wondering if it would be possible to change that behaviour, if not by default, then optionally with an option in the settings. It would be very useful in my opinion.

**Comment by tamuratak** [comment]
Execute `synctex` to reveal the internal PDF viewer if it is already opened.
