### ISSUE TITLE
Ctrl+Alt+M to close the math preview panel

### ISSUE THREAD

**Issue by Ky-Huang** [James-Yu/LaTeX-Workshop#2379]
As far as I'm concerned, since ctrl+alt+M is opening the math preview panel, then intuitively ctrl+alt+M when the panel has been opened should be closing the panel. Just like switch on and off a light.

Actually, I think that an average latex user is not likely to use the math preview panel all the time, because one usually doesn't need the preview while typing simple equations, and long and tough equations usually show up less than text. But the preview panel take up lots of space so it's not so comfortable while typing text. Therefore, I think the best way to use the preview panel is to call it out while I need it, and close it after use in order to save the screen space. 

Imagine that you suddenly need to type a terribly long equation, you could just press ctrl+alt+M to call out the panel, and then type the equation carefully, and after that you could just press ctrl+alt+M to quickly close the panel. Then you can go on your writing, and the math preview panel won't take up the space of the screen. That's really convenient and easy.

Thus a quick way to close the preview panel is quite significant.  However, in the latest version, in order to close the preview panel one needs to ctrl+shift+p and type a command. This costs too much attention and too many steps. I'd appreciate it a log if the developers could consider my suggestions.

**Comment by Ky-Huang** [comment]
'd appreciate it a lot if the developers could consider my suggestions.

**Comment by Ky-Huang** [comment]
I'd appreciate it a log if the developers could consider my suggestions. (Sorry for typing mistake)

**Comment by tamuratak** [comment]
You can assign a shortcut to the command `latex-workshop.closeMathPreviewPanel` in the Keyboard Shortcuts configuration.

**Comment by Ky-Huang** [comment]
> You can assign a keyboard shortcut to the command `latex-workshop.closeMathPreviewPanel` in the Keyboard Shortcuts configuration.
> 
> ![スクリーンショット 2020-11-19 10 11 53](https://user-images.githubusercontent.com/10665499/99607711-ad1bdf00-2a4f-11eb-9636-8bebb01183aa.png)

Emm... actually I know that works, but that's not so intuitively and elegant. Though it's a small stuff... it actully could be done in a more elegant way, without wasting a key-binding. When the math panel is opened, ctrl+alt+M remains useless untill the panel is closed, but other key-binding might be useful. If the user has to define a new key-biding, it costs extra attention and learning, but ctrl+alt+M doesn't since it is intuitive.

VS Code itself has settings like this. For example you can use ctrl+B to open and close the side-menu, ctrl+~ to open and close the terminal, etc. Even in Latex Workshop, there is such kind of things. For example, ctrl+L ctrl +B to bold face and cancel bold face. For the sake of

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by jlelong** [comment]
Fixed by #2380
