### ISSUE TITLE
The Ctrl+L prefix breaks Ctrl+L in other languages when altKeymap is enabled

### ISSUE THREAD

**Issue by nidrissi** [James-Yu/LaTeX-Workshop#2382]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

The extension uses `Ctrl+L` as a prefix for many shortcuts. VSCode uses `Ctrl+L` for the `expandLineSelection` command. The extension defines `Ctrl+L Ctrl+L` as a replacement in latex mode, fine. But now, VSCode thinks that `Ctrl+L` is the beginning of a chord in every mode, even though there is nothing starting with `Ctrl+L` in other languages. It becomes impossible to use `Ctrl+L` for `expandLineSelection` anywhere except in latex file, where the `Ctrl+L Ctrl+L` chord is defined.

### To Reproduce

1. Install LaTeX-Workshop.
2. Enable `altKeymap`.
3. Pressing `Ctrl+L` in any file displays `(Ctrl+L) was pressed. Waiting for second key of chord...` and does nothing. Of course, no chord starting with `Ctrl+L` is defined, so nothing works.
4. Disabling LaTeX-Workshop restores the `Ctrl+L` command.

### Expected behavior

Installing LaTeX-Workshop should not disable commands in non-LaTeX modes.

## Logs [Required]

There are no logs to speak of, since the extension is not even loaded in non-LaTeX files.

### LaTeX Workshop Output [Required]

See above.

### Developer Tools Console [Required]

The log is empty except for an unrelated message about Jupyter.

## Screenshots

https://i.imgur.com/pFxmFLF.png

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.51.1
 - Extension version: 8.14.0
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

Yes/No

### Are you using LaTeX Workshop with VS Code Remote?

Yes

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote WSL
- Remote Extension Version: 0.51.3

**Comment by jlelong** [comment]
I think this has just been fixed by 233fbcc in #2380. To be merged soon.

**Comment by nidrissi** [comment]
I just realized that disabling the `altKeymap` setting fixes this.
