### ISSUE TITLE
Update PDF.js (and maybe enable native chromium/electron PDF viewer)

### ISSUE THREAD

**Issue by septatrix** [James-Yu/LaTeX-Workshop#2385]
**Is your feature request related to a problem? Please describe.**
The currently used version of PDF.js does not support form which are therefore not visible in the rendered PDF.

**Describe the solution you'd like**
Updating PDF.js to the newest version should fix this.

**Describe alternatives you've considered**
From Electron 9 onwards it once again supports using the native chromium/electron PDF viewer. It would also be nice to let users be able to choose between these two as they both have their pros and cons regarding performance, feature set etc. However I do not know how synctex integration works but I think the option would still be great.

**Additional context**
The release since when PDF.js supports AcroForm and various other improvements is v2.6.347. This is still a pre-release but I think it would be nice to already test it and hear you feedback on it. It is also already shipped in the new firefox version.

**Comment by tamuratak** [comment]
> Update PDF.js 

We will update it. Users do not have to open issues on it.

> using the native chromium/electron PDF viewer

Not possible from the restriction of VS Code.

**Comment by septatrix** [comment]
Okay thanks for the quick feedback. Regarding the native PDF plugin I was able to find the issue for VSCode and will discuss it there.
