### ISSUE TITLE
Autocomplete overwrites selected text while snippets do not

### ISSUE THREAD

**Issue by septatrix** [James-Yu/LaTeX-Workshop#2386]
**Is your feature request related to a problem? Please describe.**
Selecting text and typing a snippet like `FTT` surrounds the selected text with the snippet content `\texttt{selected text}`.
The same with an autocompletion like `\section*{text}` which shows up when typing `\sec...` overwrites the selected text and just shows up as `\section*{}`.

**Describe the solution you'd like**
It would be great if normal autocompletions would also preserve the selected text.

**Describe alternatives you've considered**
Provide every current autocompletion as a snippet but that may be a lot.
Alternatively provide more generic snippets like an environment snippet which puts the selected text inside the environment body and moves the cursor to the environment type (the brackets after the begin/end statement).

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#surrounding-text

**Comment by septatrix** [comment]
Yes however snippets are able to do this natively without needing a shortcut. I do not know how VSCode works but it seems like the same should be possible for autocompletion.

**Comment by septatrix** [comment]
I am not provisioned in vscode extensions so if language autocompletion is limited to a subset of snippets I understand this (and would potentially open an issue in the vscode repo). After a few minutes of search I could not find sources proving or falsifying this claim however. If you happen to know more please let me know.

For now I will try to get used to the shortcuts, thanks for pointing me towards those.

**Comment by trevorgunn** [comment]
We do have one command for this: https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#surrounding-selection-with-an-environment You can assign it a keybinding if you find it useful.

**Comment by trevorgunn** [comment]
Would it hurt to put some `TM_SELECTED_TEXT`s into `data/commands.json`?

**Comment by trevorgunn** [comment]
Alternatively, we could do the replacement `${1} => ${1:${TM_SELECTED_TEXT}}` ourselves in `command.ts`. Maybe a new configuration variable?

**Comment by jlelong** [comment]
I think the replacement in `command.ts` is better as it enables to handle all the commands provided by packages, which are defined in [`data/packages/*_cmd.json`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/data%2Fpackages).

I will investigate if it can be done similarly for environments.

**Comment by jlelong** [comment]
Replacing `${1} => ${1:${TM_SELECTED_TEXT}}` probably only makes sense for snippets/autocompletions with a single placeholder. For snippets with several arguments (e.g. `frac{${1:num}}{${2:den}}`), it is not clear which one should be replaced by the selected text. I think, snippets with several placeholders should be left unchanged.

For environments, it is enough to replace `${0} => ${0:${TM_SELECTED_TEXT}}` to be able to wrap the selected text with the given environment. I will propose a PR soon.
