### ISSUE TITLE
Create extension pack and split this into multiple parts

### ISSUE THREAD

**Issue by septatrix** [James-Yu/LaTeX-Workshop#2387]
I know this would be a rather big change but there are many advantages to this approach.

**Is your feature request related to a problem? Please describe.**
Some users like me like the workflow utilities this extension provides (watching files, preview, build commands etc) however do not need others (snippets) or would like to use different providers for some features (e.g. texlab language server).
Currently this is not possible or can lead to conflicts.

**Describe the solution you'd like**
Splitting this extension into an extension pack with multiple components would eliminate this drawback. People can pick the parts they like, leave other out or replace them with different providers. Furthermore this allows updating components without updating the others and encourages a modular approach.

This could also lead to more users who previously disliked this extension due to bloat and feature creep.

**Describe alternatives you've considered**
Provide settings to let the user choose a IntelliSense/language server provider and disable features they do not like. This would however likely require more changes and seems more fragile and less extensible.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
