### ISSUE TITLE
Add autocompletion for lstlisting labels in ref or vref

### ISSUE THREAD

**Issue by Cellebyte** [James-Yu/LaTeX-Workshop#239]
### How to reproduce

Create a listing by e.g. :
```tex
\begin{lstlisting}[
    language=bash,
    caption={Setup der Daemon.json für Systemd},
    captionpos=b,
    label={lst:script:devicemapper}]
#/usr/bin/env bash
vgremove disk1
vgcreate docker /dev/sdb
lvcreate -n docker-pool -L 70G docker
lvcreate -n docker-meta -L 3G docker
lvconvert --type thin-pool --poolmetadata docker/docker-meta docker/docker-pool
lvcreate -l 100%FREE -n mount1 docker
mkfs.xfs /dev/docker/mount1
\end{lstlisting}
```
### Expected behavior
```tex
\vref{lst:script:devicemapper} 
```
has autocompletion for lstlistings
### Actual behavior
```tex
\vref{lst:script:devicemapper} 
```
has no autocompletion for lstlisting, but 
```tex
\vref{fig:figure1} 
```
has autocompletion
### Additional Information
It is only an enhancement for the \vref or \ref tag in tex.

**Comment by James-Yu** [comment]
I did not use the package so maybe just noob, but why `\label{label-for-lstlisting}` does not work for this special environment?

**Comment by Cellebyte** [comment]
```tex
\begin{lstlisting}[
    language=bash,
    caption={Setup der Daemon.json für Systemd},
    captionpos=b]
\end{lstlisting}\label{lst:script:devicemapper}
```
<--- this produces a reference to the subsection 4.1.1 but it has to be the reference to the listing 3 in chapter 4, so 4.3 is the right reference.
If i use 
```tex
\begin{lstlisting}[
    language=bash,
    caption={Setup der Daemon.json für Systemd},
    captionpos=b]
\label{lst:script:devicemapper}
\end{lstlisting}
```
it is printed into the latex pdf document.
This is the reason why `\label` is not working in this special environment.
It must be given as an option like `caption` and `language`.

**Comment by James-Yu** [comment]
Got it. However, it can be extremely difficult to use regex to parse the `[]` clause. Have to find some workaround, or just dirty solutions.
