### ISSUE TITLE
Support lacheck

### ISSUE THREAD

**Issue by michaelcarno** [James-Yu/LaTeX-Workshop#2393]
**Is your feature request related to a problem? Please describe.**
chktex is very old, and works bad with non english langs;

**Describe the solution you'd like**
lacheck works very well and fast, it suppot unicode;

**Comment by jlelong** [comment]
This is worth having a look. I will try to make a PR

**Comment by James-Yu** [comment]
I am looking into this feature. Is this still valid? I may work on it in the following days.

A trivial design things. Shall we unitfy `chktex` and the potential `lacheck` into a `linter` configuration class? Or treat these two as individual features? @jlelong

**Comment by jlelong** [comment]
I have never used `lacheck`, so I do not have a specific opinion on how it outperforms `chktex`. Anyway, you are welcome to give it a try. Supporting a new linter also requires to implement a parser for its output.

I think it will be easier to maintain if one class is derived from the base `Linter` class for each linter . The same probably applies to the `LinterLogParser` class. As far as configuration variables are concerned, what about making the following changes

- Renaming `latex-workshop.chktex.run` into `latex-workshop.linting.run`, `latex-workshop.chktex.enabled` into `latex-workshop.linting.enabled`
 and `latex-workshop.chktex.delay` into `latex-workshop.linting.delay`.
- Adding `latex-workshop.linting.linter` with possible values `lacheck` or `chktex` (default)
- It would probably be more coherent to rename all the other configuration variables `latex-workshop.chktex` into `latex-workshop.linting.chktex`, but this would make a lot of changes.
- Add variables of the form `latex-workshop.linting.lacheck` 

Btw, there are many deprecated variables `latex-workshop.chktex.*`, which may now be removed?
