### ISSUE TITLE
The extension is interefering with c++ doxygen syntax highlighting

### ISSUE THREAD

**Issue by mehdi-benallegue** [James-Yu/LaTeX-Workshop#2395]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]
Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

Yes

## Describe the bug 
Activating this extension removes all syntax highlighting of doxygen comments in c++ files. 

## Screenshots

Without the extension
![Screenshot from 2020-11-26 17-57-23](https://user-images.githubusercontent.com/435367/100329612-3e232500-3011-11eb-84b6-e929eb1bf3d6.png)

With the extension
![Screenshot from 2020-11-26 17-57-55](https://user-images.githubusercontent.com/435367/100329621-44190600-3011-11eb-9733-38281282bfdc.png)

## Desktop
 - OS: Ubuntu 18.04
 - VS Code version: [. 1.51.1]
 - Extension version: [ v8.14.0]

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context
I haven't even started to compile latex documents...

**Comment by tamuratak** [comment]
I can reproduce. The following is the cause:

https://github.com/James-Yu/LaTeX-Workshop/blob/a5621669636e47912557a6281e8db39288b0b469/package.json#L216-L223
