### ISSUE TITLE
changing global zoom in VScode not scaling the preview as expected in windows

### ISSUE THREAD

**Issue by geoff3jones** [James-Yu/LaTeX-Workshop#24]
This is possibly related to:
> Preview is just a part of the split window #5 

and may actually be more of an upstream issue with the window provided by `previewHTML` from the vscode api

Basically the preview window overflows when you globally scale the client smaller (Zoom out) `Ctrl`+`-` and underflows when globally scaling larger (Zoom in) `Ctrl`+`=`, the later case looking identical to the issue shown in #5. 

If one dynamically resizes the `outerContainer` in viewer.html to have the size of the window outer width then this seems to fix in the case of being zoomed out.
```
<script type="text/javascript">
  var hackZoomOutFix = function(){
  var screenCssPixelRatio = (window.outerWidth) / window.innerWidth;
  /* // for live debugging the window dims as seen from viewer.html
  $('#saywidth').text(' (' + window.outerWidth + ') / ' + window.innerWidth + ' ' + screenCssPixelRatio);
  */
  if (screenCssPixelRatio < 0.99){
    $('#outerContainer').width(window.outerWidth+'px');
  }
  else{
    $('#outerContainer').width('100%');
  }
  };
  $(document).ready(function(e){hackZoomOutFix ;setTimeout(hackZoomOutFix ,1000)});
  $( window ).resize(function(e){hackZoomOutFix ;setTimeout(hackZoomOutFix ,1000)})
</script>
```
However in the case where you are globally zoomed in even trying to resize the window port using `window.resizeTo(h,w)` does not seem to be able to stretch the preview pane out to the correct dimensions hence the suspicion that this is an upstream issue?

I hope this is useful
ps
also added: to viewer.html to make use of jquery,
```
<script  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
```
this was mainly so that I could add a live print-out of the window dims, this also required adding
```
<div id="saywidth" style="position: fixed;
    top: 34px;
    width: 100%;
    color: red;"></div>
```
at the bottom of the body.

Btw LOVE this extension! I had a half baked attempt at integrating pdfjs myself a few months back but never completed the integration due to, ironically, paper deadlines!

**Comment by James-Yu** [comment]
Thanks for the detailed investigation! Do you mind me integrating your code with minor modifications?

**Comment by geoff3jones** [comment]
Hi yes please do use any part or whole of the code suggestions i posted :) I'm just glad this was helpful. Also I totally understand that you may want to change the specifics to keep things in a consistent style and independent of a live internet connection (since I load jquery via CND which it may be better to do from a local copy instead)
