### ISSUE TITLE
Open other PDF files using the LaTex-Workshop viewer?

### ISSUE THREAD

**Issue by kaimdx** [James-Yu/LaTeX-Workshop#240]
Is it possible to use latex-workshop as a generic pdf file viewer in vscode? It works quite well and I don't want to install another plugin.

Currently VScode doesn't support pdf file and the only pdf plugin (https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf) seems not being actively developed. 

There is certainly quite some interests in this: https://github.com/Microsoft/vscode/issues/10821

**Comment by James-Yu** [comment]
Let me check if it is possible. Current scheme won't work with local files.

**Comment by James-Yu** [comment]
I noticed that in the `pdf-preview` pack, users need to explicitly invoke a command to open a viewer instead of click on the item in left sidebar. Am I correct?

**Comment by kaimdx** [comment]
Do you mean the 'vscode-pdf' plugin? For me it doesn't support open pdf file from the sidebar. I didn't find any command in the command palette for opening pdf, either.

**Comment by neilsustc** [comment]
> I noticed that in the pdf-preview pack, users need to explicitly invoke a command to open a viewer instead of click on the item in left sidebar. Am I correct?

Yes, users need to right click on the pdf file from the sidebar and select 'open preview'

Upstream issue [vscode#12176](https://github.com/Microsoft/vscode/issues/12176)

**Comment by James-Yu** [comment]
I'll keep a close eye on related api by vscode. Hope they might do something.

**Comment by aportelli** [comment]
Hi, just to comment that this would be an awesome feature, https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf kindof work but weird things happens (error messages, jumping tabs) if it is used simultaneously with the LaTex-Workshop viewer.

**Comment by James-Yu** [comment]
Will release this feature very soon.

**Comment by timfayz** [comment]
@James-Yu Seems like you've already done it but I can't find any evidence in the context menu :( Did I miss something? I expect it to be something like "Open preview" in the sidebar when right clicking at a file.

**Comment by tamuratak** [comment]
Use left clicking.

**Comment by timfayz** [comment]
When I left clicking it gives me this: 
![image](https://user-images.githubusercontent.com/6209197/62408848-90983100-b5d7-11e9-83bc-fe3cdce90847.png)
After pressing _open it anyway_ it indeed opens that preview but I always have to pointing.

**Comment by tamuratak** [comment]
It is the intended behavior. There is nothing more we can do than this because of the restriction of API of VS Code.

**Comment by timfayz** [comment]
Got it, thank you.
