### ISSUE TITLE
VScode now showing latexmk errors

### ISSUE THREAD

**Issue by Cheaterraptor** [James-Yu/LaTeX-Workshop#2401]
Hello (sorry if this is not the right place to ask this question),
I have some problems with getting error messages when compiling documents.
It is not a specific error, but a more general issue. If I produce some error, I get 'Recipe terminated with error'. Normally the specific problem was displayed in the problems tab of the vscode editor, but not anymore. In the logs I can see the error message clearly and when I compile the document with other latex editors (like texmaker) I see the error messages. 
It's not that I really like error messages, but if the file could not be compiled I would like to know why and not look through the logs every time. Maybe its just a quick fix, but I can not find anything related to this. 
I already reinstalled the extension, tex live and vscode but the problem remains. 
I attached the log, but I produced the error intentionally by inserting '\€'. 
[Building classifcation and recomendation system.log](https://github.com/James-Yu/LaTeX-Workshop/files/5608387/Building.classifcation.and.recomendation.system.log)

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment]
You log says:

> The document does not appear to be in UTF-8 encoding.

This is the cause.

**Comment by Cheaterraptor** [comment]
Hey, I am really sorry to bother you, but this is not what I meant. 
I produced the error on purpose, I know, in this case, that its because of the "\€". My problem is that no error message are displayed in the VScode problems tab.  If you look at the two screenshots in the attachments, one is of vscode and the other one of texmaker. Normally the errors, shown in texmaker, were displayed in vscode. 
![VS_code](https://user-images.githubusercontent.com/38714960/100468640-1bf2db00-30d5-11eb-941e-8c481dd0752f.jpg)
![Tex_maker](https://user-images.githubusercontent.com/38714960/100468641-1c8b7180-30d5-11eb-8d88-595bc9b5b769.jpg)

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by Cheaterraptor** [comment]
Okay, sorry. Fortunately I found the error. Seems if you name your file like my advisor did ("Building classification and recommendation system") vscode is not able to retrieve the errors. (No argue about that its a bad file name).
Thank you for answering and sorry for wasting some of your time.
