### ISSUE TITLE
wordPattern in syntax.json needs {2,}?

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2404]
VS Code Insider has changed the behavior.  Related to #2310.

Version: 1.52.0-insider
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:22:59.162Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Darwin x64 17.7.0

1. Type `\a`
1. Press `Escape` to close completion items.
1. Press `Ctrl-Space` to open completion items again.
1. Press `c`

![Nov-30-2020 09-01-16](https://user-images.githubusercontent.com/10665499/100557224-0f47d000-32eb-11eb-8619-2ff2d6bb2e38.gif)

If we change `{2,}` in `wordPattern` at `syntax/syntax.json` to `{1,}`, we can resolve the issue.

![Nov-30-2020 09-02-22](https://user-images.githubusercontent.com/10665499/100557261-4ae29a00-32eb-11eb-8f94-bedc2c3a520f.gif)

Does `wordPattern` need `{2,}`?

**Comment by tamuratak** [comment]
Ref
- https://github.com/microsoft/vscode/blob/f47aae014cf8567f648e68369d66b4106ae89f08/src/vs/editor/contrib/suggest/completionModel.ts#L167-L176

**Comment by jlelong** [comment]
Removing `{2,}` will not change much as far as command completion is concerned since the completion is triggered by the leading `\`. The only real change concerns quick suggestions, which will popup from the first character on instead of the second one. I have no objection to make this change.

**Comment by tamuratak** [comment]
> The only real change concerns quick suggestions, which will popup from the first character on instead of the second one. 

The side effect seems serious enough to me. I close this issue without changing `wordPattern`.

We will think about this issue again if the behavior of VS Code would change again.

**Comment by jlelong** [comment]
It is pity that there is no extensive documentation on how the autocompletion engine works. I will have a closer look at all this.
