### ISSUE TITLE
Autodetect recipie to run based off of LaTeX file name. 

### ISSUE THREAD

**Issue by mstumpf585** [James-Yu/LaTeX-Workshop#2412]
### Issue
My team currently uses two recipes that each require a different .tex file to be selected. Lets call them FileOne.tex and FileTwo.tex. FileOne.tex requires a python script to be run before calling latexmk. We run them using a virtual environment which is specified in a tool object using relative pathing for the command string ie:
```
 {
                "name": "python_generation",
                "command": "../venv/scripts/python.exe",
                "args":[
                    "%DIR%/../src/main.py",
                    "latex"
                ]
  }
```

This runs fine when the FileOne.tex is selected. However, if FileTwo.tex is selected it errors off because FileTwo.tex is in a different directory than FileOne.tex. 

So if the user doesn't know any better and just hits " Build LaTeX Project" with FileTwo.tex it will default to the first recipe that runs the python script and errors out when the user has FileTwo.tex selected. To build FileTwo.tex the user has to drop the the "Build LaTeX Project" and select the correct command for the given .tex file.  

### Possible Fix? 
Is there a way to detect what file the user has selected and run a specified recipe based on the file name? It seems confusing to have to select the correct .tex file and the correct build command. 

### Alternatives 
Is there a way to maybe just disable the default recipe and force the user to select one recipe over the other? 

### Additional Context 
Tried using an external build command but it seems like that prevents any other recipe from running?

**Comment by mstumpf585** [comment]
I think having latex workshop parse VScode variables in the tool settings would resolve this type of issue https://code.visualstudio.com/docs/editor/variables-reference

**Comment by tamuratak** [comment]
Please use magic comments:

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments

**Comment by mstumpf585** [comment]
I'm not sure I follow, you place the magic comment in one tex file and it uses those args for latexmk? How would this work for two different files? @tamuratak

**Comment by mstumpf585** [comment]
Figured it out using this site: https://www.texdev.net/2011/03/24/texworks-magic-comments/ Thanks for the tip @tamuratak !
