### ISSUE TITLE
Some warnings by ChkTeX should be treated as errors

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2413]
`chktex` reports unmatched `{` and `}` as  a warning. We should treat it as an error. At the same time, we should not treat unmatched `(` and `)` and others as errors.

Since it is a very common mistake, we should also display it at the top of problems.

![スクリーンショット 2020-12-04 21 02 53](https://user-images.githubusercontent.com/10665499/101161514-419f5780-3674-11eb-9e99-86ce3d609384.png)

Notice that error messages by `latex` do not tell us the position of the unmatched `{` and `}`.

**Comment by jlelong** [comment]
I agree that unbalanced `{...}` is very often the reason of compiling errors.

**Comment by tamuratak** [comment]
When calling `chktex` with an option `-e15`, unbalanced `{...}` is treated as an error.  At the same time, unbalanced `(...)` and others are treated as errors. I am not sure it is acceptable.

**Comment by jlelong** [comment]
Unbalanced `(...)` are not that rare, eg half-open intervals. I do not think this is a good idea to enforce `-e15`.

**Comment by tamuratak** [comment]
I've been using `chktex` for a while, adding `-e15` to `latex-workshop.chktex.args`, I am satisfied with it. Let us close this issue.
