### ISSUE TITLE
PDF diff side-by-side

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#2414]
I have just removed `vscode-pdf` due to apparent incompatibilities (at least I received a warning upon each start), so this is my go-to PDF viewer now.

When opening a PDF file from the source-control view, I'd like to see a side-by-side view of two pdfs (old and new) to allow diffs. `vscode-pdf` does this in principle, but shows the new pdf twice (due to a bug, I assume - see https://github.com/tomoki1207/vscode-pdfviewer/issues/70).

**Comment by jlelong** [comment]
This is out of the scope of the extension.

**Comment by bersbersbers** [comment]
I see. Are there any plans then to increase compatibility with other extensions that may offer such a feature? I am thinking about https://github.com/James-Yu/LaTeX-Workshop/blob/139b6130ba90fa15e4b86d0931a2487e15c8f4b6/src/main.ts#L43-L48 for example.

**Comment by jlelong** [comment]
It is not clear to me from  tomoki1207/vscode-pdfviewer#70 that side-by-side view of PDF is part of `vscode-pdf` plans. The incompatibility with `vscode-pdf` is related to both extensions wanting to claim PDF languageId ownership.

**Comment by bersbersbers** [comment]
> It is not clear to me from [tomoki1207/vscode-pdfviewer#70](https://github.com/tomoki1207/vscode-pdfviewer/issues/70) that side-by-side view of PDF is part of `vscode-pdf` plans.

Well, they have "help wanted" tagged for that issue, so I wouldn't say they are opposed to that feature, even if they invest no resources on their own (and there hasn't been a commit or release since June).

> The incompatibility with `vscode-pdf` is related to both extensions wanting to claim PDF languageId ownership.

I see. My thoughts/observations on this: shouldn't it be left to VS Code to handle extensions with conflicting `languageIds` claims? That seems to be the case already - in my use cases, the two extensions work together nicely.

**Comment by tamuratak** [comment]
Encouraging users to use `vscode-pdf` with LaTeX Workshop makes user supports incredibly difficult. Please endure the warning if you want to use it with our extension.
