### ISSUE TITLE
Intellisense should also work for arguments of \newcommand

### ISSUE THREAD

**Issue by MaKaNu** [James-Yu/LaTeX-Workshop#2415]
**My Problem**
I miss some intellisense auto complition for the arguments in the following example (and all other \newcommand):
```latex
\newcommand{\superref}[1]{\namecref{#1} \nameref{#1}}
```
The following gif describes my problem a bit better:
![issueWorkshop](https://user-images.githubusercontent.com/32844273/101197906-fdf02200-3662-11eb-88e4-2a143037ad9c.gif)

As you can see the autocomplition for the argument of the command ```\ref{}``` is working. The autocomplition for the command ```\superref{}``` only works for the command itself. 

Meanwhile I tested to save the newcommand in a seperate file and listed it under ```latex-workshop.latex.texdir```. But this doesn't work either.  

**My Solution**
the following link https://tex.stackexchange.com/questions/86643/newcommand-arguments-auto-prompts describes how to handle this in texmaker. I couldn't find or maybe did not understand correctly how to configure the settings.

**Comment by jlelong** [comment]
Your problem is not clear. Please explain in detail what you would like.

**Comment by jlelong** [comment]
I will fix it once #2417 is merged. Meanwhile, you just have to manually trigger intellisense once inside `\superref{}` using `cltr+space` (or `cltr+i`).

**Comment by MaKaNu** [comment]
You are fast^^
