### ISSUE TITLE
BibTex parsing may be broken

### ISSUE THREAD

**Issue by domoson** [James-Yu/LaTeX-Workshop#242]
### Description

Information about bibtex entries is incorrect (authors are listed where the title should be, etc.), see (I am hovering over `myId`):

![image](https://user-images.githubusercontent.com/21341345/29471632-036cb2f6-8451-11e7-896a-336037a0d171.png)

I am on Windows 10 x64, VS Code 1.15.1 x64, Latex-Workshop 3.3.2 (I believe)

### How to reproduce

Minimum working example:

> test.tex:
```latex
\documentclass{article}
\begin{document}
This is a citation~\cite{myId}
\bibliography{test}
\end{document}
```

> test.bib:
```bibtex
@article{myId,
  title={My Title is a Great Title},
  author={Mueller, Max and Doe, Jonn},
  journal={The Journal of Love},
  volume={5},
  number={15},
  pages={15--25},
  year={2017},
  publisher={Publishing Inc.}
}
```

**Comment by James-Yu** [comment]
I can reproduce the bug. Investigating.

**Comment by James-Yu** [comment]
It's working!

![image](https://user-images.githubusercontent.com/4210342/29500541-29097d96-8654-11e7-80ca-71f19f69bfb7.png)

**Comment by domoson** [comment]
Awesome thanks!

**Comment by James-Yu** [comment]
I'd thank YOU for the awesome issue. Nothing can be more satisfactory when a new issue is packed with all descriptions needed and a working MWE. Anyways, thanks for using VSCode and the extension!
