### ISSUE TITLE
Support auto-completion for bib file located in texmf

### ISSUE THREAD

**Issue by tlannaax** [James-Yu/LaTeX-Workshop#2423]
**Is your feature request related to a problem? Please describe.**
For people who do not know, there is a great trick if you have a master bib file containing all the references.
Just put master.bib in the path texmf/bibtex/bib (and of course do a latex file name database refresh),
you can easily access master.bib via \bibliography{master} in any latex file without having to specify the detailed path every time.
It is even more useful when you sync your master.bib via cloud and create a symlink in texmf/bibtex/bib.

However, latex-workshop does not support to auto-complete the bibkeys in a bib file in texmf. For autocompletion to work you have to specify the absolute or relative path to the bib file.

**Describe the solution you'd like**
Add support for auto-completion for bib file located in texmf.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.
- Please paste the generated `.fls` files.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tlannaax** [comment]
I just figured it out that enabling kpsewhich resolves my problem. Thanks.
