### ISSUE TITLE
how can I create a new command with a parameter as a file path, which could be completed by vscode?

### ISSUE THREAD

**Issue by air391** [James-Yu/LaTeX-Workshop#2425]
**difficulity for adding a picture as a floating body**

```latex
\begin{figure}[H]%
    \centering%
    \includegraphics[width=\textwidth]{figure/fig1.jpg}%
    \caption{a}%
    \label{a}%
\end{figure}%
```

I always use the code to add a picture to my tex.

And when I use the command `` \includegraphics[]{}``, vscode list the file in the folder for me to choose.

But if I want to create a new command like this:

```latex
\newcommand{\figureinsert}[4]{%
    \begin{figure}[H]%
        \centering%
        \includegraphics[width=#2\textwidth]{#1}%
        \caption{#3}%
        \label{#4}%
    \end{figure}%
    }
```

For the parameter #1, the path of the picture,  vscode cannot complete it for me.
**I wonder if I can create a new command with parameters of certain type ,like the path of a file**
If this is a existing feature of vscode or LATEX-workshop, I hope you can tell me how to use it;
if not, I hope this feature will be added to the next version.

**Comment by jlelong** [comment]
Only predefined commands support path completion and there is no way for you to tell LW that a new command should be completed with file paths. Moreover, with your new command the extension will not know that `#4` is label and therefore it will not show up while completing `\ref` commands. 

Using a snippet will fix both problems, see [vscode's documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).

**Comment by air391** [comment]
thanks for your tips.
I‘ve solved this problem.
