### ISSUE TITLE
Highlighting for BibTeX style files has a bug

### ISSUE THREAD

**Issue by gaochenyi** [James-Yu/LaTeX-Workshop#2429]
## Describe the bug

Hi, I find the following function in a BibTeX style file can not be highlighted correctly. I have disabled all the other extensions except for LaTeX Workshop. It seems a bug related to the highlighting for BibTeX style files.

```bst
FUNCTION {output.translation}
{ show.english.translation entry.lang lang.zh = and
    { translation empty$ not
        { translation }
        { "[English translation missing!]" }
      if$
      " (in Chinese)" * output
      write$
      format.doi duplicate$ empty$ not
        { newline$
          write$
        }
        'pop$
      if$
      " \\" write$
      newline$
      "(" write$
      ""
      before.all 'output.state :=
    }
    'skip$
  if$
}
```

## Screenshots

![Screen Shot 2020-12-11 at 18 18 47](https://user-images.githubusercontent.com/32761974/101891684-57b19880-3bdd-11eb-8df0-6029a8c4365c.png)

## Desktop
 - OS: macOS 10.14.16
 - VS Code version: 1.51.1
 - Extension version: 8.15.0
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Could you comment more precisely on what highlighting should look like.
Is this correct?

<img width="391" alt="Capture d’écran 2020-12-11 à 11 52 19" src="https://user-images.githubusercontent.com/2910140/101895131-69784900-3ba7-11eb-9f78-4c1964d1d60f.png">

**Comment by jlelong** [comment]
Feel free to ask for reopening if it is still not good.

**Comment by gaochenyi** [comment]
Thanks for the fix. Sorry for not stating more precisely. By my test, the bug shows up when two backslashes appear in a string, and later functions lose correct highlighting. Check the following snippet.

```bst
FUNCTION {good}
{
  { "1" }
  { "0" }
  if$
}

FUNCTION {bug}
{
  { "1\\" }
  { "0\\" }
  if$
}

FUNCTION {good}
{
  { "1" }
  { "0" }
  if$
}
```

**Comment by gaochenyi** [comment]
With your fix, the bst code is highlighted correctly. Thanks for the fix.
