### ISSUE TITLE
Feature request: Root file detection via .latexmain -suffix

### ISSUE THREAD

**Issue by hhakula** [James-Yu/LaTeX-Workshop#243]
In multi author tex-projects I have found the vi latex-suite approach of labeling the root file, e.g., main.tex with an empty file main.tex.latexmain to lead to smoother workflow than having magic comments.

Perhaps the existance of such a file in the root folder of the workspace could be tested when the files are iterated in step 3 of the root resolution process.

**Comment by James-Yu** [comment]
This won't be implemented shortly since the said method is not a universally-recognized one.
