### ISSUE TITLE
Source control panel opens unexpectedly when focusing tex file in diff view

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#2430]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: N/A

## Describe the bug [Required]

Source control panel opens unexpectedly when focusing tex file, but not txt file:
![idnwua0qoQ](https://user-images.githubusercontent.com/12128514/101901385-43f03d00-3bb1-11eb-8c55-6c7564100cb6.gif)

### To Reproduce

1. Open folder under source control
2. Create x.tex and y.txt
3. Stage both
4. Open x.tex in diff view: "x.tex (Index)"
5. Close Source Control
6. Focus y.txt
7. Focus x.tex

### Expected behavior

Source Control stays closed.

## Logs [Required]

![image](https://user-images.githubusercontent.com/12128514/101901843-f88a5e80-3bb1-11eb-9167-9a847df79638.png)
(I cannot copy the text due to an unrelated bug.)

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

(command does not do anything - note I am not compiling)
```

### Developer Tools Console [Required]

```
  ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'd:\x\.vscode'
contextKeyService.ts:420 Element already has context attribute
w @ contextKeyService.ts:379
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66/node_modules/windows-process-tree/lib/index.js.map: Unknown error
```

## Screenshots

see above

## Desktop [Required]
 - OS: Win 10 20H2
 - VS Code version: 1.51.1, 1.52.0 insiders
 - Extension version: 8.15.0
 - TeX distribution version: MiKTeX

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes, but the problem reproduces standalone

**Comment by tamuratak** [comment]
This is an intended behavior.

**Comment by bersbersbers** [comment]
Thanks. You might add "Source Control" to the FAQ (I did check the FAQ, but "Source Control" did not match anything) and document options (I did look here, but the name of the option did not ring a bell):
![image](https://user-images.githubusercontent.com/12128514/101906154-cfb99780-3bb8-11eb-88d0-e54b3f68b626.png)
)

**Comment by bersbersbers** [comment]
Wait, I misread - this is not working. `view.autoFocus.enabled` does not do anything when `gits.length > 0`.

So are you are saying there is no way to keep the Source Control sidebar closed when working with git?

**Comment by bersbersbers** [comment]
https://github.com/microsoft/vscode/issues/3742 is a different issue in my opinion. I don't want to close the side bar after some time, I would like Latex Workshop to not open it in the first place. My screen is not wide enough for two tex docs (remember, that's a side-by-side diff), a pdf preview, *and* a side bar.

I'd suggest that `view.autoFocus.enabled` should apply to the source control sidebar as well.

**Comment by jlelong** [comment]
My feeling is that we should remove https://github.com/James-Yu/LaTeX-Workshop/blob/4b1a338393e5bde8855f19dc8a6b9c66cdd68f45/src%2Fmain.ts#L210-L212

The other language related extensions do not seem to handle the scm view. Other filetypes do not exhibit this behaviour with the scm view.

**Comment by jlelong** [comment]
This was introduced by 58425b41a09b938240c241a9ff4e8cde4b955d85 but I cannot really see the logic here

**Comment by jlelong** [comment]
I have just reverted it. Wait and see if anyone complains.

**Comment by bersbersbers** [comment]
Thanks - looking forward to the next release!
