### ISSUE TITLE
Snippet View's position gets wrong when commands collapsed and expanded

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2433]
Version: 1.53.0-insider
Commit: 76436a4d43566cd313629799e2ec51b4d00caa64
Date: 2020-12-11T17:46:02.603Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin x64 17.7.0

1. Make the height of Snippet View large.
1. Expand Structure View in the side bar.
1. Collapse Commands View in the side bar.
1. Expand Commands View in the side bar.

![スクリーンショット 2020-12-13 20 39 10](https://user-images.githubusercontent.com/10665499/102010732-5b7f1f80-3d83-11eb-8c7d-d29a094bac98.png)

Related to microsoft/vscode/issues/110450.

**Comment by James-Yu** [comment]
Is this issue resolved? It looks like I cannot reproduce this issue with the following version

Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

**Comment by tamuratak** [comment]
No. I still see the issue.

Version: 1.65.0-insider (Universal)
Commit: 8440b8f47231147823ba9696913d642e5f2d9d58
Date: 2022-02-25T05:18:40.990Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

**Comment by James-Yu** [comment]
It seems still to be an upstream issue. Does vscode repo have a new open issue for this? The previous one and the following PR have been both resolved.

**Comment by tamuratak** [comment]
The linked issue microsoft/vscode/issues/110450 is the one. It has been reopened.

**Comment by tamuratak** [comment]
I have confirmed the issue fixed.

Version: 1.68.0-insider
Commit: 688c80245936b49b7ceca494d9edfe97cae06f8a
Date: 2022-05-18T05:15:18.598Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0
