### ISSUE TITLE
latex-workshop.surround overrides input with multiple selections

### ISSUE THREAD

**Issue by kjshen** [James-Yu/LaTeX-Workshop#2438]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

I used to use LaTeX Workshop's "Surround selection with LaTeX command" hotkey to surround multiple selections simultaneously. Now, it overrides the inputs of all selections with the content of the first selection. Triggering the snippet by typing does work, however.

![SurroundSelection](https://user-images.githubusercontent.com/45091615/102207086-d0f70700-3ecd-11eb-957a-9dd21a849be4.gif)

### To Reproduce

1. Select multiple words
2. Use your "Surround selection with LaTeX command" hotkey
3. Choose \section{}, \emph{} etc.

## Desktop
 - OS: Windows 10
 - VS Code version: 1.52.0
 - Extension version: 8.15.0
 - TeX distribution version: MiKTeX 2.9.7429

**Comment by jlelong** [comment]
The `content` parameter is not used anymore in https://github.com/James-Yu/LaTeX-Workshop/blob/24438bee8cff1088bf7882f625cad469e476f4c5/src%2Fproviders%2Fcompleter%2Fcommandlib%2Fsurround.ts#L5

I think, we can drop the `content` parameter can be dropped in https://github.com/James-Yu/LaTeX-Workshop/blob/24438bee8cff1088bf7882f625cad469e476f4c5/src%2Fproviders%2Fcompleter%2Fcommand.ts#L158
