### ISSUE TITLE
Enhancement to math preview panel

### ISSUE THREAD

**Issue by xiajunwen1007** [James-Yu/LaTeX-Workshop#2444]
The math preview panel is great for me as a mathematics student. I use this feature to check the correction of my writing equation. This feature works perfectly on \begin{}...\end{} math environments and on $...$ inline math, but to $$...$$ math environment, it doesn't seem to work. Here is a screenshot:
![image](https://user-images.githubusercontent.com/49160447/102469492-c97e5c00-408d-11eb-8796-61bb447f830a.png)
  Finally, Love this extension so much.

**Comment by tamuratak** [comment]
Out of the scope of the extension. Due to performance. Please use `\[`.

See https://en.wikibooks.org/wiki/LaTeX/Mathematics#Mathematics_environments
