### ISSUE TITLE
intellisense for files does not work when graphicspath contains command

### ISSUE THREAD

**Issue by Legion2** [James-Yu/LaTeX-Workshop#2445]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

File completion does not work for includegraphics when the `graphicspath` is itself a command which defines the path.
```latex
\graphicspath{{\getgraphicspath}}
\newcommand{\getgraphicspath}{graphics/}
```

https://github.com/latextemplates/scientific-thesis-template/blob/74ac0e693312b94b8faee7f1cd339262aff546bb/config.tex#L375-L376

### To Reproduce

1. Create a latex document with the following content:
```latex
\usepackage{graphicx}
\graphicspath{{\getgraphicspath}}
\newcommand{\getgraphicspath}{graphics/}
```
2. create a file in the `graphics` directory.
2. Type '\includegraphics{'
3. No file completion is provided

### Expected behavior

The files in the `graphics` directory are provided for completion

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.52.1
 - Extension version: 8.15.0
 - TeX distribution version: MiKTeX 2.9.7429

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
The parser we use to detect `\graphicspath` (among everything else) cannot expand macros.  Unfortunately, we cannot do much about this.
