### ISSUE TITLE
Extra closing delimiter with @( and @[ snippets

### ISSUE THREAD

**Issue by btaiii** [James-Yu/LaTeX-Workshop#2449]
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]
I get an extra closing delimiter when using the @[ and @( snippets.  I get the expected behavior up until version 8.13.2, but beginning with 8.14.0 I have the problem.

### To Reproduce

Type @[ [ENTER]

### Expected behavior
I expect to get
  \left[  \right]
but instead I get an extra right square bracket:
  \left[  \right]]

## Screenshots

![image](https://user-images.githubusercontent.com/5440294/102855161-c1098680-43e9-11eb-83f5-89124c006b40.png)

## Desktop [Required]
 - OS:Pop!_OS 20.10
 - VS Code version: 1.52.1
 - Extension version: 8.14.0 or 8.15.0
 - TeX distribution version: TeX Live 2020/Debian

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?
No

**Comment by jlelong** [comment]
I cannot reproduce the issue. Make sure your configuration has `"editor.autoClosingBrackets": "languageDefined"`
Does it happen when all other extensions are disabled?

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by btaiii** [comment]
I found the problem.  It only occurs when I have extension "Latex language support torn4dom4n.latex-support" enabled.  

Before submitting the bug report, I had that extension disabled.  But the error only goes away after disabling and then **restarting** VS Code.

I don't think I need "Latex language support torn4dom4n.latex-support" anyway, so I'm good.  Thank you!
