### ISSUE TITLE
Snippet View does not work with VS Code Remote

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2450]
Snippet View does not work with VS Code Remote.

![102326801-35968c80-3fc8-11eb-8470-6cc2d7fc34d0](https://user-images.githubusercontent.com/10665499/103046535-f79ef700-45cb-11eb-9d76-bc25c9cec010.png)

Reported in microsoft/vscode/issues/112641.

**Comment by ARC-MX** [comment]
I found this problem too

**Comment by tamuratak** [comment]
This issue will be fixed on VS Code 1.56.0.

Version: 1.56.0-insider
Commit: 394a2e4779ff767e2761a59a51b15848dcd24173
Date: 2021-04-13T11:11:34.416Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0
