### ISSUE TITLE
Clean potentially deletes important files.

### ISSUE THREAD

**Issue by jaymody** [James-Yu/LaTeX-Workshop#2451]
The auxiliary file cleaner uses globed file extensions to mark files to be deleted. By default these values are (as set by`latex-workshop.latex.clean.fileTypes`):
```
"*.aux",
"*.bbl",
"*.blg",
"*.idx",
"*.ind",
"*.lof",
"*.lot",
"*.out",
"*.toc",
"*.acn",
"*.acr",
"*.alg",
"*.glg",
"*.glo",
"*.gls",
"*.fls",
"*.log",
"*.fdb_latexmk",
"*.snm",
"*.synctex(busy)",
"*.synctex.gz(busy)",
"*.nav"
```

This is quite dangerous considering `*.log` is one of the options. If an important log is located in the root folder, it gets deleted by the clean operation (see gif below). When used with the `latex-workshop.latex.clean.subfolder.enabled` option, entire directories of valuable logs could get deleted. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26451316/103140594-73756e00-46b6-11eb-81da-15b320166177.gif)

I'm not too familiar with latex, but if I'm not mistaken, shouldn't all the auxiliary files have the same basename, just with different extensions? Is there a reason a glob is being used instead of `root_file_name + extensions_name`, which is much safer?

If not, I really think this is something that should get fixed. Looking at [`cleaner.ts`, the root file path is already being passed to the cleaner function](https://github.com/James-Yu/LaTeX-Workshop/blob/c52a5df00f5fc46d5bdc1ce84ed0a8bc2cf34111/src/components/cleaner.ts), so implementing this change shouldn't be too difficult (although I could be wrong). I've used JavaScript sparingly, but if it's easy enough I'd be more than happy to submit a PR.

An ideal solution would have the list of strings be taken literally, and use some argument to indicate "insert rootfile name here". The new file list would then be something along the lines of:

```
"${root_file}.aux",
"${root_file}.bbl",
"${root_file}.blg",
"${root_file}.idx",
"${root_file}.ind",
"${root_file}.lof",
"${root_file}.lot",
"${root_file}.out",
"${root_file}.toc",
"${root_file}.acn",
"${root_file}.acr",
"${root_file}.alg",
"${root_file}.glg",
"${root_file}.glo",
"${root_file}.gls",
"${root_file}.fls",
"${root_file}.log",
"${root_file}.fdb_latexmk",
"${root_file}.snm",
"${root_file}.synctex(busy)",
"${root_file}.synctex.gz(busy)",
"${root_file}.nav",
"__latexindent_temp.tex"
```

**Comment by jlelong** [comment]
It is actually a bit more complicated than that as auxiliary files are generated for every file include in the root file.

**Comment by jaymody** [comment]
Would there be some way to track all generated files and then compile a list that can later be used in the clean function?
