### ISSUE TITLE
"latex-workshop.view.outline.floats.enabled" can not be found

### ISSUE THREAD

**Issue by cxf208** [James-Yu/LaTeX-Workshop#2455]
**Is your feature request related to a problem? Please describe.**
I want to just show the headlines in STRUCTURE, but there are always Figures shown there. It seems I should change the "latex-workshop.view.outline.floats.enabled" to false, but I can not find the settings anywhere.
It seems there is a solution, but I do not know how to use it:  https://github.com/James-Yu/LaTeX-Workshop/actions/runs/413038015

**Describe the solution you'd like**
I want to show just the headlines in STRUCTURE area.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by tamuratak** [comment]
You can search the setting in the Settings panel.

![スクリーンショット 2020-12-30 18 11 38](https://user-images.githubusercontent.com/10665499/103341559-9d6dcc80-4aca-11eb-8183-ae3cb153e052.png)

**Comment by tamuratak** [comment]
The setting `latex-workshop.view.outline.floats.enabled` will be available in the next release.

**Comment by cxf208** [comment]
Thank you, should I do anything to upgrade it? Or will it upgrade automatically?
