### ISSUE TITLE
A dialog pops up on macOS if git is not installed and search.useIgnoreFiles is true

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2457]
A dialog pops up on macOS if `git` is not installed and `search.useIgnoreFiles` is true.

The dialog says `the "git" command requires the command line developer tools. Would you like to install the tools now?`

We should run `which git` on macOS before executing `git`.

https://github.com/James-Yu/LaTeX-Workshop/blob/d375dfc7e9e75b911ac96b350520dd5234678894/src/providers/completer/input.ts#L25-L29

**Comment by jlelong** [comment]
You are perfectly right. OSX already catches the exception `command not found` when `git` is not installed.
