### ISSUE TITLE
Feature request: surround selected text with a LaTeX command

### ISSUE THREAD

**Issue by narimiran** [James-Yu/LaTeX-Workshop#246]
Currently, when you select some text you can press `(`, `[`, `{` and even `$` to surround that text in matching brackets or inline math with `$`. For example:

`a + b = c` -> press `$` -> `$a + b = c$`

Idea is to have a similar behaviour when you select a text and then press `\` to enter some LaTeX command. (Currently, pressing `\` would replace the selected text)  
Ideally, you should see the same drop-down menu as when you use `\` with no text selected, and you could tab-complete the command. For example:

`danger` -> press `\` -> start typing `em`, tab-complete to select `\emph` -> `\emph{danger}`

**Comment by James-Yu** [comment]
Tbh this is a very hard-to-implement feature. I'm always against the pattern in which each extension creates its own hook to monitor user input. Unfortunately this seems to be a must for the suggested feature. I'll keep investigating.

**Comment by narimiran** [comment]
> I'm always against the pattern in which each extension creates its own hook to monitor user input.

I thought the described behavior with `$` is thanks to this extension, because that doesn't work in files other than `.tex` from what I could tell/try.   

But I can see why `\command{$selected}` might be:
>  a very hard-to-implement feature

**Comment by James-Yu** [comment]
`$` auto-pairing is contributed by this extension, but the implementation is by vscode's API instead of a hook. So the new auto command surrounding is a new task that may need some justification and work.

**Comment by James-Yu** [comment]
I was thinking of this issue for the past several minutes and changed my mind. This feature will be included. Soon (TM).

**Comment by James-Yu** [comment]
Soon (TM) on marketplace.

![image](https://user-images.githubusercontent.com/4210342/29767689-fcca621e-8c15-11e7-90f6-e41e59a17111.png)

**Comment by James-Yu** [comment]
IIRC there's already an update today for bug fixes. So this one will be released tmr or so in order to be not too annoying 😝

**Comment by narimiran** [comment]
Yes, today we've already got one update :)

No rush for this, whenever you feel it would be appropriate. Thank you for rethinking, changing your mind, and a very quick implementation!

**Comment by jpcofr** [comment]
@James-Yu After having highlighted some equation I'd like to have it surrounded by `\(   \)`. However, what I get is the string I chose prepended by `\(\)`. It seems that it doesn't happen with other completions. I guess that this is somehow related to the strings `$0` and `$1` but it is not clear for me how to use this feature.

**Comment by narimiran** [comment]
> I'd like to have it surrounded by `\( \)`

Try using `$...$` syntax, it should work without problem - just select your equation and press `$`.

**Comment by jpcofr** [comment]
I was using that syntax given a ChkTex warning I had.

**Comment by cmellwig** [comment]
Sorry but how does this work exactly?

**Comment by linhtto** [comment]
Sorry for commenting on an old issue again. I see that this works and it's great, but the command has to come from the list. Can we allow a command not from the list as well, and assume that it only has 1 argument (like \footnotesize)?

**Comment by jlanza** [comment]
> 
> 
> Sorry for commenting on an old issue again. I see that this works and it's great, but the command has to come from the list. Can we allow a command not from the list as well, and assume that it only has 1 argument (like \footnotesize)?

I'm lacking the same behaviour. I guess it is nice to have a list, but you can create your own commands, etc. and it would be perfect to have this (with multi-cursor enabled ;))

**Comment by jlelong** [comment]
What do you have in mind exactly?  What could be done is to wrap the selections with `{...}` and put a multi-cursor before the opening `{`. Would that make it?

**Comment by jlanza** [comment]
> 
> 
> What do you have in mind exactly? What could be done is to wrap the selections with `{...}` and put a multi-cursor before the opening `{`. Would that make it?

I think that is ok. I give you some other options:
- Something similar to the one you have already implemented. The only difference would be that in case the typed text is not in the list, it should be accepted. For instance, right now \ac for glossaries is not included in the list, so I cannot use the keyboard shortcut.
- Another option would be to enable adding new commands to a configuration file, so you will be adding new commands to the list. I guess your current list is hard coded somewhere else. This way you won't be typing something undesired. It is less friendly. 
- You can also think on a mix between option 1 and 2. That is, when you type and click enter on a non-included one, it is added to settings.json in your local folder.

**Comment by jlelong** [comment]
I suggest to continue the discussion in #1530.
