### ISSUE TITLE
Use the last successful build recipe instead of the first one in an auto build

### ISSUE THREAD

**Issue by xq114** [James-Yu/LaTeX-Workshop#2460]
**Is your feature request related to a problem? Please describe.**
When the option `auto build` is enabled, it uses the first recipe to build the document by default. However, the first recipe is sometimes not the preferred solution for the current document. 

**Describe the solution you'd like**
It would be nice if latex workshop could detect the recipe used in the last successful build and use it instead of just using the first recipe. If no successful recipe is detected, then it falls back to the first recipe.

**Comment by tamuratak** [comment]
Out of the scope of the extension. It makes things too complicated.

**Comment by jlelong** [comment]
I think the setting [`latex-workshop.latex.recipe.default`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexrecipedefault) does more or less what you want.
