### ISSUE TITLE
Snippet view  display error in linux 

### ISSUE THREAD

**Issue by ARC-MX** [James-Yu/LaTeX-Workshop#2466]
## Preliminary questions [Required]
When I want to use snippet view to enter some formula in Linux. I found that snippet-view  display error like image1, but I use it on windows haven't this problem showing image2.
![image](https://user-images.githubusercontent.com/34829404/103978797-4a290780-51b7-11eb-88e4-2589353e39d9.png)
![Uploading image.png…]()

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment]
Duplicate of #2450
