### ISSUE TITLE
Keyboard shortcuts for text emphasis

### ISSUE THREAD

**Issue by pedromxavier** [James-Yu/LaTeX-Workshop#2470]
Most LaTeX-oriented text editors provide shortcuts (`Ctrl+I`, `Ctrl+B`) for applying/adding `\textit`. `\textbf` to cursor position or selected text, I feel this feature is missing in this extension.

It would be nice to have these and other shortcuts implemented.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#Font-commands

You can also define user snippets:
- https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets
