### ISSUE TITLE
Select external browser for the pdf view

### ISSUE THREAD

**Issue by stakaz** [James-Yu/LaTeX-Workshop#2473]
**Is your feature request related to a problem? Please describe.**
When using the browser for the PDF preview it would be great if one could define the browser or at least use the browser set in vscode. Currently the systems default browser is used.

**Describe the solution you'd like**
An entry in the settings.

This is annoying if one works with the browser and then the preview opens as a new tab instead of a new window. The second thing is that one might prefer a faster browser for the PDF viewer but a feature rich one for the daily work...

**Comment by tamuratak** [comment]
Not possible. Please up vote microsoft/vscode/issues/96132.
