### ISSUE TITLE
Syntax highlighting of `comment` environment between conditionals

### ISSUE THREAD

**Issue by valerioformato** [James-Yu/LaTeX-Workshop#2475]
Code inside a `comment` environment is always rendered as a comment by the syntax highlight even if the environment is disabled by a conditional statement.

Expected behavior: If the `comment` environment is not active the rest of the code should be properly highlighted.

Example reproducer:
```
% \lighttrue
\lightfalse

\iflight
\begin{comment}
\fi 

Some piece of document...

\iflight
\end{comment}
\fi 
```

Result:
![image](https://user-images.githubusercontent.com/10223306/104447562-3eb15400-559c-11eb-9149-1c69529fba7a.png)

**Comment by jlelong** [comment]
Unfortunately, vscode syntax highlighting engine cannot evaluate LaTeX macros.
