### ISSUE TITLE
Add an option to disable auto-closing pairs and parentheses

### ISSUE THREAD

**Issue by fpqc** [James-Yu/LaTeX-Workshop#248]
Following up from my [last issue](https://github.com/James-Yu/LaTeX-Workshop/issues/235), I was wondering if you could add an option in the configuration to just disable all auto-closing pairs in the extension.  I'm filing an issue on the main vscode repository about multicharacter pairings, but in the mean time, could you add an option to just disable them altogether?

**Comment by James-Yu** [comment]
Unfortunately, it's impossible with the current vscode API.

**Comment by fpqc** [comment]
@James-Yu Alright, I submitted an issue on the main repository.  If there is anything else you have to add, the issue is at https://github.com/Microsoft/vscode/issues/33084
