### ISSUE TITLE
BibTeX formatting enhancements

### ISSUE THREAD

**Issue by alexreg** [James-Yu/LaTeX-Workshop#2481]
**Is your feature request related to a problem? Please describe.**
Purely for aesthetic reasons, it's sometimes nice to *not* line up the `=` in BibTeX files.

**Describe the solution you'd like**
A boolean setting like `latex-workshop.bibtex-format.align-equals-signs` (default: true) that indicates whether to line up the equals signs. (An alternative name for the setting could be `latex-workshop.bibtex-format.align-values`.)

If `true`, formats like:
```bibtex
@article{einstein,
	author   = {Albert Einstein},
	title    = {{Zur Elektrodynamik bewegter Körper}. ({German}) [{On} the electrodynamics of moving bodies]},
	journal  = {Annalen der Physik},
	volume   = {322},
	number   = {10},
	pages    = {891--921},
	year     = {1905},
	doi      = {http://dx.doi.org/10.1002/andp.19053221004},
	keywords = {physics},
}
```

If `false`, formats like:
```bibtex
@article{einstein,
	author = {Albert Einstein},
	title = {{Zur Elektrodynamik bewegter Körper}. ({German}) [{On} the electrodynamics of moving bodies]},
	journal = {Annalen der Physik},
	volume = {322},
	number = {10},
	pages = {891--921},
	year = {1905},
	doi = {http://dx.doi.org/10.1002/andp.19053221004},
	keywords = {physics},
}
```

**Describe alternatives you've considered**
I see none, given how the formatter does not allow this at present.

**Comment by alexreg** [comment]
A nice other enhancement would be to get rid of the `latex-workshop.bibtex-format.tab` setting and just have it obey the VS Code setting for that file (which I believe reads from `editor.tabSize` and/or the `.editorconfig` file).

**Comment by jlelong** [comment]
Dropping `latex-workshop.bibtex-format.tab` sounds like a bad idea because when a `.bib` is badly formatted, vscode cannot detect the correct tab size based on the content of the file (see `editor.tabSize` and `editor.detectIndentation`).

Aligning equal signs or not may be an interesting feature to add.

**Comment by alexreg** [comment]
@jlelong Ah right. It may not always be able to detect it, but if `editor.tabSize` or `.editorconfig` is explicitly set, surely that value is readable, and can be used as a default for the `latex-workshop.bibtex-format.tab` setting? So maybe it would be nice to have an `auto` or `default` value for `latex-workshop.bibtex-format.tab`.

**Comment by jlelong** [comment]
In fact, when `editor.detectIndentation` is active, vscode does not take the value of `editor.tabSize` into account but infers it from the content. I am afraid changing the setting `latex-workshop.bibtex-format.tab` will be more harmful than helpful. I will keep it the way it is.

I will try to make a PR for the alignment feature.

**Comment by alexreg** [comment]
Okay, no problem. By the way, I was wondering if it is possible to have `latex-workshop.bibtex-format.tab` accept both string arguments (e.g., "tab") and numerical (just referring to the number of spaces). If not, no worries, it is fine for me like it is now.

**Comment by jlelong** [comment]
> By the way, I was wondering if it is possible to have `latex-workshop.bibtex-format.tab` accept both string arguments (e.g., "tab") and numerical (just referring to the number of spaces).

For the moment, this variable accepts one of the strings `"2 spaces"`, `"4 spaces"`, `"tab"`. I think we could easily accept any number in front of `"spaces"` or even drop the `"spaces"` suffix and only keep the number represented as a string.

@tamuratak any thoughts on that ? Keeping the `"spaces"` suffix would make the change transparent.

**Comment by alexreg** [comment]
@jlelong Yep, that would probably make sense. If you can accept integer values too, then all the better, but that's no big deal if not.

**Comment by alexreg** [comment]
@jlelong While you're at it, would you mind adding an option to sort fields too (e.g., alphabetically, or somme other way)... if this isn't too much trouble;?

**Comment by jlelong** [comment]
What other sorting option than alphabetically do you have in mind? Adding a new sorting option requires some work.

**Comment by alexreg** [comment]
@jlelong We don't even have alphabetic sorting of *fields* right now, do we? That's possibly the one I'd used most, but alternatively what would be nice is a custom sort order, which could be specified as an array of field names, e.g., `["title", "author", "journal", "volume", ...]`.

**Comment by jlelong** [comment]
Now, the variable `latex-workshop.bibtex-format.tab` can be "tab", "X spaces" or "X" where X is a number.

**Comment by alexreg** [comment]
That's great, thanks. (Also, for the new issue for field ordering.)
