### ISSUE TITLE
Setting to prevent auto-closing backtick quotes

### ISSUE THREAD

**Issue by alexreg** [James-Yu/LaTeX-Workshop#2483]
**Is your feature request related to a problem? Please describe.**
I use the `csquotes` package, which means it is not necessary to use the usual quoting style (i.e. `` `...'``). The standard behaviour is to auto-complete backticks (`` ` ``) with single quotes (`'`), but this is undesirable. I can turn off auto-quote-closing altogether for LaTeX files, but this is overkill (`"editor.autoClosingQuotes": "never"`).

**Describe the solution you'd like**
A setting for specifically turning off auto-closing of backticks. It would also be nice to never have backtick quotes auto-closed within comments.

**Describe alternatives you've considered**
None.

**Comment by tamuratak** [comment]
Not possible. Please up vote microsoft/vscode/issues/38352.

**Comment by alexreg** [comment]
Will do, thanks for linking me.
