### ISSUE TITLE
Killing the build process makes vscode crash when pkill is provided by proctools

### ISSUE THREAD

**Issue by alexreg** [James-Yu/LaTeX-Workshop#2484]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue.

You still see this issue?: Yes (sporadically)

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: No, but this is precisely the point

## Describe the bug [Required]

Sometimes a build hangs, but when I do "Kill LaTeX Compiler Process", it crashes VS Code.

### To Reproduce

1. Create a TeX document that hangs.
2. Observe never-ending build-in-progress status in bottom-right of window: <img width="130" alt="Screenshot 2021-01-18 at 03 35 32" src="https://user-images.githubusercontent.com/67036/104869548-395a5d80-593e-11eb-9d9c-0889ed0ba925.png">.
3. Perform command "Kill LaTeX Compiler Process".
4. Observe VS Code crash (immediate, no dialog or information screen).

### Expected behavior

Simply a peaceful termination of the LaTeX compiler process -- not a crash of the entire VS Code app, naturally.

### LaTeX Workshop Output [Required]

https://gist.github.com/0052a9d49640b2082303d4402df4640f

### LaTeX Compiler Output

https://gist.github.com/53d6e54ebc347f2bdcb82297bd547299

### Output from manually running `latexmk` command in terminal

https://gist.github.com/285257e52d062373d4f46327744041d1

### Developer Tools Console [Required]

https://gist.github.com/abf948c0194689c6e8426a916746170f

## Screenshots

See above.

## Desktop [Required]
 - OS: macOS 11.1
 - VS Code version: 1.52.1
 - Extension version: 8.15.0
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

[Sample TeX document that causes hanging](https://gist.github.com/477f11b7e0896dc866ea2ae5640a866d)

**Comment by alexreg** [comment]
Last time there was no crash screen, but this time I got this one:
<img width="1418" alt="Screenshot 2021-01-18 at 04 01 37" src="https://user-images.githubusercontent.com/67036/104871015-dec30080-5941-11eb-9c68-82a033d08956.png">

**Comment by tamuratak** [comment]
Your log says:

> localProcessExtensionHost.ts:258 W0118 00:58:44.405406   67966 loader.go:223] Config not found: /Users/alex/.kube/config{    "kind": "Config",    "apiVersion": "v1",    "preferences": {},    "clusters": null,    "users": null,    "contexts": null,    "current-context": ""}

It seems related Go lang. Please disable all the other extensions except for LaTeX Workshop, and then paste the required logs.

**Comment by tamuratak** [comment]
Please notify if any progress.

**Comment by tamuratak** [comment]
#2491

**Comment by tamuratak** [comment]
Please install Visual Studio Code Insiders https://code.visualstudio.com/insiders/ and check whether the issue occurs with Visual Studio Code Insiders.  The issue might be solved because it uses a newer version of Electron.

**Comment by alexreg** [comment]
Will do.

**Comment by alexreg** [comment]
I confirm: exactly the same issue in VS Code Insiders. Are you sure you aren't accidentally killing the wrong process?

**Comment by tamuratak** [comment]
@jlelong  Can you reproduce the issue with macOS Big Sur?

**Comment by jlelong** [comment]
Unfortunately, I am still running Catalina, I haven't upgraded to Big Sur yet.

**Comment by jlelong** [comment]
Btw, on Catalina killing the build process does not actually kill the `pdflatex` process, which keeps using 100% CPU.

**Comment by tamuratak** [comment]
@jlelong Could you share a sample LaTeX document? Does it happen with a just large document without `-shell-escape`?

**Comment by jlelong** [comment]
My comment about not being able to kill the build was related to the [example by @alexreg](https://gist.github.com/477f11b7e0896dc866ea2ae5640a866d) compiled with the standard `latexmk` recipe. I cannot manage to reproduce this with an other example but I will keep trying.

The logs say

```
[14:29:02] Building root file: /Users/jl/devel/LaTeX-Workshop/mytests/2484/main.tex
[14:29:02] Build root file /Users/jl/devel/LaTeX-Workshop/mytests/2484/main.tex
[14:29:02] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/jl/devel/LaTeX-Workshop/mytests/2484,/Users/jl/devel/LaTeX-Workshop/mytests/2484/main
[14:29:02] Recipe step env: {}
[14:29:02] cwd: /Users/jl/devel/LaTeX-Workshop/mytests/2484
[14:29:02] LaTeX build process spawned. PID: 6102.
[14:29:02] Linter for root file successfully finished in 0s 176ms
[14:29:02] Linter log parsed with 0 messages.
[14:29:02] File watcher - file changed: /Users/jl/devel/LaTeX-Workshop/mytests/2484/main.tex
[14:29:02] Parsing a file and its subfiles: /Users/jl/devel/LaTeX-Workshop/mytests/2484/main.tex
[14:29:02] Parse fls file.
[14:29:02] Fls file found: /Users/jl/devel/LaTeX-Workshop/mytests/2484/main.fls
[14:29:03] Parse aux file: /Users/jl/devel/LaTeX-Workshop/mytests/2484/main.aux
```

and meanwhile the build icon keeps spinning. The `pdflatex` process has PID 6104. The `kill` command inside LW does kill `latexmk` (PID 6102) but not `pdflatex`.

**Comment by alexreg** [comment]
That's curious. You'd think it would kill its child processes too, unless they've detached themselves...

**Comment by jlelong** [comment]
I think I have the kill issue. In the `kill` function, we first kill all processes with parent pid equal the pid of `latexmk` and then kill `latexmk` itself

https://github.com/James-Yu/LaTeX-Workshop/blob/afa3d71e8610db036087a11e03a0555664954f8f/src/components/builder.ts#L54-L62

Yet, the killing of child processes is done asynchronously. I suspect the parent process gets killed before the children (which are not killed because they are detached) and then they become orphans and are not killed by the `pkill -P` command. Using `cp.execSync` fixes the issue.

@alexreg Could you try the code from the `master` branch on Big Sur? See https://github.com/James-Yu/LaTeX-Workshop/blob/master/CONTRIBUTING.md if you do not know how to do this. Thanks for your help.

**Comment by alexreg** [comment]
@jlelong Thanks for your efforts. Same crash, I'm afraid.

**Comment by alexreg** [comment]
@jlelong I've got it working here locally. I will submit a PR shortly.

**Comment by alexreg** [comment]
Alright, I opened the PR. Hopefully that looks good to you.

As a sidenote, what do you guys think about adding support for able to click the "Build" button of the status bar (per below), and a context menu appears with a "Stop" option. I've seen this for one or two other extensions, I believe.

![](https://user-images.githubusercontent.com/67036/104869548-395a5d80-593e-11eb-9d9c-0889ed0ba925.png)

**Comment by tamuratak** [comment]
Please open a new issue.

**Comment by jlelong** [comment]
@alexreg Can you try the following?
Build your example inside VSCode. Note the pid returned on the logs (you can also get it with `ps ux`), then run `pkill -P pid` where `pid` is the pid of `latexmk`. Does it kill `latexmk` and the child process `pdflatex`? Does it make VSCode crash?

**Comment by alexreg** [comment]
@jlelong That won't work because when the OS reaps `latexmk`, its child processes get reassigned the parent PID of 1 (for `launchd`).

**Comment by alexreg** [comment]
@jlelong Yeah, that works interestingly enough.

**Comment by jlelong** [comment]
What do you mean by that works? Does it kill `latexmk` and the child process `pdflatex`? Does it make VSCode crash?

**Comment by alexreg** [comment]
Yes, of course. "Works" means "works correctly".

**Comment by alexreg** [comment]
Please note, killing an active build that has produced an error but not finished triggers an auto-rebuild as soon as the build process is killed. This is obviously undesirable behaviour. It is fixed (by a straightforward and I believe correct means) in my PR that you guys did not want, but so be it. Please do not ask me to submit a new issue; I'm leaving this report here as a matter of courtesy; it's up to you if you want to fix it or not, by whatever means. :-)
