### ISSUE TITLE
Follow-up on issue #2484

### ISSUE THREAD

**Issue by alexreg** [James-Yu/LaTeX-Workshop#2491]
Following up on issue #2484, the crash upon "Kill LaTeX Compiler Process" still occurs as before, having disabled all other extensions.

[Here are the relevant logs.](https://gist.github.com/3774664b1f8a8675b4f74edb1cd449d6)

P.S. @tamuratak That wasn't helpful that you closed the previous issue! It would have made more sense to continue the discussion there.

**Comment by tamuratak** [comment]
#2484
