### ISSUE TITLE
Context menu option to stop/kill build

### ISSUE THREAD

**Issue by alexreg** [James-Yu/LaTeX-Workshop#2494]
**Is your feature request related to a problem? Please describe.**
A convenient way to stop (kill) the current build. It is already possible, but this offers a convenient and idiomatic method that is in line with other extensions, I believe.

**Describe the solution you'd like**
Allow the "Build" button of the status bar (see below) to open a context menu, which would provide a "Stop" button. I've seen this for one or two other extensions, as I recall. It's purely a convenience feature, of course, but a nice one in my view.

![](https://user-images.githubusercontent.com/67036/104869548-395a5d80-593e-11eb-9d9c-0889ed0ba925.png)

**Describe alternatives you've considered**
Use the Command Palette to stop the build. This takes quite a few keystrokes, however, and is more time-consuming given this is a very common operation (for me).

**Comment by tamuratak** [comment]
Use the side bar.

![スクリーンショット 2021-01-25 7 21 34](https://user-images.githubusercontent.com/10665499/105645300-113ea180-5ede-11eb-8833-d47e7980373b.png)

**Comment by alexreg** [comment]
The whole point of this is a convenience feature in line with other extensions that build things.

**Comment by jlelong** [comment]
You can assign a keybinding to the command `latex-workshop.kill`.
