### ISSUE TITLE
"Kill LaTeX Compiler process" does not kill pdftex process on Windows 10 in case of infinite loop

### ISSUE THREAD

**Issue by r0uv3n** [James-Yu/LaTeX-Workshop#2495]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Does not apply.

## Describe the bug [Required]
On Windows 10, when the LaTeX compiler / pdftex gets stuck in an infinite loop, invoking "Kill LaTeX compiler process" does not kill pdftex, which continues using up CPU. Only way to kill the pdftex process is to use Task Manager or equivalent.

### To Reproduce

1. Compile (using the standard latexmk recipe / pressing CTRL+ALT+B) a script that causes an infinite loop, for example this one:
 ```
\documentclass{minimal}
\usepackage{commath, tikz}
\begin{document}
\begin{tikzpicture}
  \node {$:$};
\end{tikzpicture}
\end{document}
```
2. Wait a bit
3. Try to kill the Compiler process by invoking the "Kill LaTeX compiler process".
4. Open Task Manager (or equivalent) and find pdftex process still running and using CPU.

### Expected behavior

pdftex (and all other child processes) are killed when invoking "Kill LaTeX compiler process".

### LaTeX Workshop Output [Required]
```
[15:47:13] Found root file from active editor: c:\Users\henry\Desktop\Test.tex
[15:47:13] Keep using the same root file: c:\Users\henry\Desktop\Test.tex
[15:47:13] Building root file: c:\Users\henry\Desktop\Test.tex
[15:47:13] Build root file c:\Users\henry\Desktop\Test.tex
[15:47:13] Recipe step 1: latexmk, --max-print-line=10000,-synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=c:/Users/henry/Desktop,c:/Users/henry/Desktop/Test
[15:47:13] Recipe step env: {}
[15:47:13] cwd: c:\Users\henry\Desktop
[15:47:13] LaTeX build process spawned. PID: 24908.
```
### Developer Tools Console [Required]

No output.

### LaTeX .log
https://gist.github.com/r0uv3n/3bfbb85d1cab557214ee6aa7eb13dd93

## Screenshots

![image](https://user-images.githubusercontent.com/26653862/105633533-6be1ea00-5e59-11eb-9738-9cd6cea3c82c.png)
This is after "Kill LaTeX compiler process".

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.53.0-insider
 - Extension version: 8.15.0
 - TeX distribution version: MiKTeX 2.9.7429

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

This has been a problem for me for more than a year, but I only now got around to creating an Issue.

**Comment by jlelong** [comment]
I think this is related to https://github.com/James-Yu/LaTeX-Workshop/issues/2484#issuecomment-766145146 and has been fixed by 6b594d5
