### ISSUE TITLE
Documentation of a package on hover for multiline \usepackage

### ISSUE THREAD

**Issue by Pantastisch** [James-Yu/LaTeX-Workshop#2496]
**Current State**
Currently documentation of a package on hover seems to be supported only for single line \usepackage, as documented on [https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#documentation-of-a-package](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#documentation-of-a-package).

`\usepackage[ngerman,shadow,textsize=footnotesize]{todonotes}`

<img width="534" alt="Bildschirmfoto 2021-01-24 um 22 24 38" src="https://user-images.githubusercontent.com/45369229/105644266-14616f80-5e95-11eb-835e-c26ade2b0c63.png">

**Feature Request**
I suggest to add support for documentation of a package on hover on multi line \usepackage, as this increases the usability in comparison to the Command Palette.

The reason is, that sometimes dev information on parameters is required, as you can see in following code and picture:

```
\usepackage[
    % disable, % TODO: Enable when finished
    ngerman,
    shadow,
    textsize=footnotesize
]{todonotes}
```
<img width="376" alt="Bildschirmfoto 2021-01-24 um 22 29 06" src="https://user-images.githubusercontent.com/45369229/105644264-10cde880-5e95-11eb-9e2f-81ed9ff33a7d.png">

**Comment by jlelong** [comment]
Every time the mouse is moved, LW scans the line under the mouse to decide whether it falls in one of the [hovering cases](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#hovering-and-previewing-features). Handling multiline commands would require to scan several lines (possible the whole document up to the line under the mouse). This would make the hovering feature far too complicated and costly. For the time being, I do not think it is worth it.

Furthermore, note that multiline commands are not properly supported by the highlighting engine and we cannot do much about it.
