### ISSUE TITLE
No autocompletion for \cite{}

### ISSUE THREAD

**Issue by JuanCabre** [James-Yu/LaTeX-Workshop#25]
Is there a problem in my setup or am I experiencing an issue with the plugin? After I write `\ref{` I can see the list of labels in all my files that I can reference to. However, if I type `\cite{`, I do not see any suggestions other than words written in my current file. I was expecting to see something similar to the suggestions in `\ref{`.

My bibliography entries are located in a `.bib` file in a subfolder of my project. In my main.tex, I have the following command `\bibliography{bibliography/references}`

**Comment by James-Yu** [comment]
Can you please try to move your bibliography file to the root folder and see if problem is resolved? This can help me identifying the problem.

**Comment by JuanCabre** [comment]
Thanks for the quick answer. So when the `.bib` file is in the root folder, I get the suggestions as expected, including the multi-citation support.

**Comment by James-Yu** [comment]
I think I get where the problem is. Will have an update in hours.

**Comment by JuanCabre** [comment]
You are awesome :D

**Comment by James-Yu** [comment]
Changes will be published soon with some other issues solved.
