### ISSUE TITLE
Is there a way to automatically add the aux files to .gitignore?

### ISSUE THREAD

**Issue by scaomath** [James-Yu/LaTeX-Workshop#2500]
**Is your feature request related to a problem? Please describe.**
Not really a problem. It would be nice that when working in a git repo, the aux files generated by the compiler would be automatically added to `.gitignore`.

**Describe the solution you'd like**
The best would be adding a button in the menu on the left panel of vscode, saying "adding aux files to .gitignore".

**Describe alternatives you've considered**
Alt would be just adding the files in the `files.exclude` of vscode, but by default there is `.git` so there might be a problem...

**Comment by jlelong** [comment]
Making this automatic is too complicated to be integrated in the extension. For now, I consider it as out the scope.

For what it is worth, github uses https://github.com/github/gitignore/blob/master/TeX.gitignore to initialize `.gitignore` for LaTeX projects. You can can use the Source Control view of VSCode and right click _Add to .gitignore_  the files to be ignored.
