### ISSUE TITLE
labels in LaTeX are unique

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#2505]
A named label, as `\label{eq:MyEquation}`, is unique in a LaTeX file; otherwise, the reference is ambiguous and causes a warning.
**Feature request:** 
If `\label{eq:MyEquation}` appears twice in a .tex-file, then every occurrence of `eq:MyEquation` should be highlighted in red color, say, as a warning.
This useful feature facilitates writing LaTeX as tracking reference errors is superfluous. In addition, the new feature removes a slight advantage of TeXstudio over LaTeX Workshop.
Thank you!

**Comment by jlelong** [comment]
I agree that this would be nice as the `multiply-defined labels` message reported by the compiler does not come with a line number. This should be the linter's job but unfortunately `chktex` does not check that. I will study how much work it is to add that to the linter call.

**Comment by aloispichler** [comment]
This is really appreciated.
`chktex` is reported in the problem section. But TeXstudio immediately highlights the issue while typing and this is clearly the most suitable solution.

**Comment by aloispichler** [comment]
This is appreciated.
`chktex` reports in the problem section. But TeXstudio immediately highlights the issue while typing. Apparently, is the preferred solution.

**Comment by jlelong** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/Linters#duplicate-labels
