### ISSUE TITLE
pipenv support?

### ISSUE THREAD

**Issue by lewiswolf** [James-Yu/LaTeX-Workshop#2506]
**Is your feature request related to a problem? Please describe.**
Hi, 

I am trying to create a latex template that uses the [minted](https://www.ctan.org/pkg/minted) package. Minted requires [Pygments](https://pygments.org/) to be installed, which I am trying to do with [pipenv](https://pypi.org/project/pipenv/). I can't get VSCode to recognise my pipenv installation, and therefore my document won't compile anything that is _minted_. I would like to use pipenv so that I can make this template a repository where all the packages/dependencies are included. 

**Describe the solution you'd like**
Can I specify this in the settings.json?

**Describe alternatives you've considered**
I could install Pygments globally, which I have done in the past, however I'm trying to use pipenv religiously (in the manner of package.json for node).

**Comment by lewiswolf** [comment]
This may actually be an issue with minted rather than vscode... feel free to close this if you agree. Thanks for your time.

**Comment by tamuratak** [comment]
You can set environment variables for recipes with the `env` property. See:

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes
