### ISSUE TITLE
Integrate with build tasks

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2513]
**Is your feature request related to a problem? Please describe.**
If you invoke Ctrl + Shift + B (Run build task) in a Latex document, nothing happens.

**Describe the solution you'd like**
It should show a list of the defined recipies, and invoke them when selected.

**Describe alternatives you've considered**
While the current "Build with recipe" works, it doesn't integrate well with the 'normal' workflow to compile/run projects in other languages.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by tobiasdiez** [comment]
Thanks for the response, but may you further clarify why this is out of scope? I thought the purpose of the extension was to integrate Latex into VS Code, and thus a proper integration with the built framework seems desirable.

**Comment by jlelong** [comment]
First, the advantage brought by integrating with the standard task system is not clear but has several downsides. In particular, when a build succeeds, the extension parses the `.aux` and `.fls` files to improve dependency detection and on hover features (especially label numbers). This is much easier done when everything is handled by the extension.
