### ISSUE TITLE
Run on save is not reliable

### ISSUE THREAD

**Issue by tobiasdiez** [James-Yu/LaTeX-Workshop#2514]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

1. Activate the option to build on save.
2. Make changes to document, and save.
3. Sometimes, nothing happens and one has to trigger the build manually.

It's sadly not reproducible, but occurs often enough to be annoying.

### Expected behavior
Compile latex automatically on save.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

Will do so, once the issue appears again.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```
Will do so, once the issue appears again.

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```
Will do so, once the issue appears again.

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.53.0
 - Extension version: latest
 - TeX distribution version: TeX Live latest

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

When all of the above is done, we will reopen this issue if needed.

Please notify If any progress.

**Comment by tobiasdiez** [comment]
The error now occurred again, and I've added the log messages. What usually solves the issue is closing the tex document and reopening it.

I have the problem on two computers (that sync their settings).

**Comment by jlelong** [comment]
I cannot find the logs.

**Comment by tobiasdiez** [comment]
Sorry, apparently my edit was to large for github which why it was rejected and I didn't noticed the error message. Now it should be updated. The whole log was to large, thus I've removed quite a bit from the middle that can be found here: https://pastebin.com/jV29tFBN

**Comment by tamuratak** [comment]
- Please provide a clear and concise description of what the bug is with timestamps. 
- Please provide what you did with timestamps. 
- When did the issue occur in the log?

**Comment by tobiasdiez** [comment]
The issue occurred at the end. And as I said, I don't know yet what triggers this. For the log, I don't know what I did when - it was the log of  few hours of usage and I copied everything as soon as the bug occurred.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template If any progress.
