### ISSUE TITLE
pdf image added in the tex file not rendered correctly by internal pdf viewer.

### ISSUE THREAD

**Issue by sirlis** [James-Yu/LaTeX-Workshop#2518]
## Describe the bug

Adding a pdf format image generated by microsoft visio into tex file. Compile it via latex workshop, but the image is not rendered correctly by internal pdf viewer.

Any external pdf viewer will see the generated pdf file with correctly rendered image.

## Screenshots

![image](https://user-images.githubusercontent.com/12960298/107229013-45769e00-6a58-11eb-98cc-aaa063f13395.png)

the dots between characters are nat at their right positions.

the left image is correct (pdf rendered by Sumatra), but the right image is wrong (which is rendered by internal pdf viewer).

## Desktop
 - OS: Windows 10
 - VS Code version: 1.53.0
 - Extension version:  8.15.0
 - TeX distribution version: MiKTeX portable 21.1-x64

**Comment by jlelong** [comment]
Can you check if the PDF file is displayed correctly in Firefox? If not, then the issue is probably related to https://github.com/mozilla/pdf.js

**Comment by yiqiangjizhang** [comment]
I wanted to ask if your pdf is rendered correctly. I am new using latex workshop and the output is disappointing. It is very pixelated

**Comment by tamuratak** [comment]
Please notify If any progress.

**Comment by sirlis** [comment]
I have no FireFox, but it can be corectly displayed in Edge and Chrome.

**Comment by tamuratak** [comment]
This issue will be fixed after updating PDF.js of LaTeX Workshop. I am not sure when it will be updated.
