### ISSUE TITLE
Extra setting for adding supported languages (to allow for snippets being inserted other file types)

### ISSUE THREAD

**Issue by gijswijs** [James-Yu/LaTeX-Workshop#2520]
I use a setup where I write in Markdown and use Pandoc to either create PDF's directly or create tex-files.

For advanced stuff (like  equations) I insert LaTeX directly in my Markdown files. It would be nice if LaTeX-Workshop would allow for the snippets to be inserted in documents that do not have a .tex extension. And  the on-the-fly previewing of equations (and/or the Math Preview Panel) to work as well on those snippets.

I took a look at the code, and the snippet insert only works if `hasTexId` returns true. Currently it does so if the `languageId` of the current document is one of the following: tex, latex, latex-expl3, doctex, jlweave, rsweave

I am suggesting a new setting that allows for an array of strings where you can add language ids that should *also* make `hasTexId` return true.

I would definitely be willing to do this myself if there is support for such a feature.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by gijswijs** [comment]
Fair enough.

For those interested, this is the workaround:

- Set the Language Mode to Tex. 
![image](https://user-images.githubusercontent.com/7912094/107312200-cec6b880-6aca-11eb-8ac9-cdbb3c98a607.png)
- Put `\documentclass[]{}` somewhere in the document.
- Insert snippets now works. Math Preview Panel works as well
- Don't forget to change the Language Mode back, and remove `\documentclass[]{}`.

**Comment by jlelong** [comment]
Hum, we already have some support for LaTeX fenced inside `.md` files: syntax highlighting and static snippets (those not triggered by `\`). I will investigate if there is a way to make the other features available to come up with a full support of LaTeX fenced block.

**Comment by tamuratak** [comment]
I am against supporting completions for LaTeX fenced block on our side. It should be treated as a language embedded in Markdown language. See:

- https://code.visualstudio.com/api/language-extensions/embedded-languages

Markdown language  extensions should take control of it. If they forward requests to LaTeX Workshop, our codes will be called appropriately.

- https://code.visualstudio.com/api/language-extensions/embedded-languages#request-forwarding

**Comment by jlelong** [comment]
I fully agree. My point is precisely to investigate why it does not already work this way. We already provide support for LaTeX embedding in Markdown, but is seems limited and it should not be.

**Comment by tamuratak** [comment]
> VS Code won't do anything special for embedded languages and that it's the sole responsibility of the embedder, e.g. html must know that it embeds js and it must handle it.

- https://github.com/microsoft/vscode/issues/43538#issuecomment-368550533
- https://github.com/microsoft/vscode/issues/47288

> why it does not already work this way.

Markdown language extensions have to call `commands.executeCommand('vscode.executeCompletionItemProvider', ...)`.
