### ISSUE TITLE
incorrect installation instructions

### ISSUE THREAD

**Issue by VictorEijkhout** [James-Yu/LaTeX-Workshop#2524]
"simply run ext install latex-workshop in VS Code Quick Open (ctrl/cmd + P)."

Typing Cmd-p brings up something, but not related to extensions.
Instead: go to the left sidebar, Extensions, then search.

(And please don't use the word simply. It doesn't add information, nor does it make anything simpler.)

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.
- Please paste screenshots.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment]
#2525
