### ISSUE TITLE
Cmd-p does not work for installation

### ISSUE THREAD

**Issue by VictorEijkhout** [James-Yu/LaTeX-Workshop#2525]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

Yes.

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No

Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

Yes.

## Describe the bug [Required]

Cmp-p does not give the option to install latex-studio

### To Reproduce

1. type Cmd-p
2. type latex-studio
3. See error in attached screenshot

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

there is no log since I was unable to install

### LaTeX Workshop Output [Required]

there is no output since I was unable to install

### Developer Tools Console [Required]

there is no log since I was unable to install

## Screenshots

attached

## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]

### Are you using VSCodium?
NO

### Are you using LaTeX Workshop with VS Code Remote?

NO
<img width="1086" alt="Screen Shot 2021-02-11 at 09 42 15" src="https://user-images.githubusercontent.com/684162/107660504-f7c38680-6c4d-11eb-9d61-fba9c1deeb56.png">

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context
None

**Comment by VictorEijkhout** [comment]
updated screenshot
<img width="998" alt="Screen Shot 2021-02-11 at 09 48 59" src="https://user-images.githubusercontent.com/684162/107661029-78828280-6c4e-11eb-97b9-0bc8589fa831.png">

**Comment by tamuratak** [comment]
Please enter `ext install latex-workshop` instead of `latex-workshop`.
