### ISSUE TITLE
Request for additional options for docker .bat files

### ISSUE THREAD

**Issue by georgealverson** [James-Yu/LaTeX-Workshop#2527]
I would like to be able to modify the docker command files via LaTeX-Workshop options as in the following example [james-yu.ltex-workshop-8.15.0/scripts/latexmk.bat]:

From
@docker run -i --rm -w /data -v "%cd%:/data" %LATEXWORKSHOP_DOCKER_LATEX% latexmk %*
To:
@docker run -i --rm -w /workspace -v "%cd%:/workspace" --entrypoint="/bin/bash" %LATEXWORKSHOP_DOCKER_LATEX%  -c latexmk %*

This would require the addition of Workshop options for an alternative entrypoint ("/bin/bash" here), argument for the entrypoint ("-c"), and a possible different folder mapping than data (/workspace).

Best regards!

**Comment by tamuratak** [comment]
Out of the scope of the extension.
