### ISSUE TITLE
Do a forward syntex without viewing the document first

### ISSUE THREAD

**Issue by septsea** [James-Yu/LaTeX-Workshop#2528]
**Is your feature request related to a problem? Please describe.**
I have to press `Ctrl + Alt + V` to open the internal PDF viewer before I can do the first forward syntex,

**Describe the solution you'd like**
Is it achievable to open the internal PDF viewer directly when I press `Ctrl + Alt + J`?

**Describe alternatives you've considered**
Well, I knew that using an external PDF viewer (such as Sumatra) solves the problem, but I just prefer the internal one.

**Additional context**
_None._

**Comment by tamuratak** [comment]
Out of the scope of the extension.
