### ISSUE TITLE
synctex not working

### ISSUE THREAD

**Issue by fa93hws** [James-Yu/LaTeX-Workshop#253]
### Description
When trying forward search, it says
    Cannot synctex: spawn synctex ENOENT, 
When trying inverse search, it says
    Cannot reverse synctex: spawn synctex ENOENT,

### setting of the tool chain
        {
          "command": "pdflatex",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%"
          ]
        }

### Additional Information
Forward search and inverse search works fine with my sumatraPDF, sublime text3 and miktex

It will be very appreciated if you can help me to fix the synctex issue.
Thanks

**Comment by James-Yu** [comment]
You need to install synctex for miktex. See readme for reference.

**Comment by fa93hws** [comment]
Thanks

**Comment by chantisnake** [comment]
Just to add here, an easier way would be `choco install synctex`
