### ISSUE TITLE
We must take care of cases where user-defined JSON files are invalid

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2530]
We must take care of cases where user-defined JSON files are invalid. We must check whether objects returned by `JSON.parse` have appropriate properties. Because the TypeScript type of returned objects is `any`, the TypeScript compiler can do nothing on it.

https://github.com/James-Yu/LaTeX-Workshop/blob/c5b6cad0f478a5ee27f9c1480bacc5bdc81cdc62/src/providers/completer/environment.ts#L231

https://github.com/James-Yu/LaTeX-Workshop/blob/c5b6cad0f478a5ee27f9c1480bacc5bdc81cdc62/src/providers/completer/command.ts#L341

**Comment by jlelong** [comment]
Actually, we should have done this a while ago because some of the `.cwl` files are buggy and the resulting `.json` is not 100% reliable. I will make a PR on this.
