### ISSUE TITLE
PDF split view

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#2533]
`View LaTeX PDF >> View in VSCode Tab` opens a new tab displaying the PDF. Repeating the command opens a second view of the same PDF in an additional tab. This feature is indeed very convenient and useful when writing LaTeX, as it allows multiple or split views of the same PDF. 

At the moment, the command `SyncTeX from cursor` syncs the PDF in _all_ tabs.
However, the user most certainly does not want to sync _all_, but only _one_ tab.

**Feature request**:
It would be a nice improvement to sync only one (perhaps the youngest, i.e., the most recently opened) tab.

Thank you indeed for LaTeX workshop. I enjoy your extension every day.

**Comment by Enivex** [comment]
This is a a related feature, so I'm gonna put it here. Does anyone else think it would be a good idea to have a command that opens a tab that does not refresh at all on build? Sometimes I'll rewrite a small section, and I'll have to make a copy of the original version to have open in an external PDF viewer for reference. Having the ability to open a frozen snapshot of the PDF in a tab would make this process simpler.

**Comment by Romeoly** [comment]
It is really wonderful if both the `.tex` file and the `.pdf` file have split views like MS Word. Sometimes you really need to refer to the context when you are writing something (e.g., when citing references ).
