### ISSUE TITLE
[Feature] Internal synctex: Reveal .tex tab if open

### ISSUE THREAD

**Issue by Toliak** [James-Yu/LaTeX-Workshop#2537]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm using synctex with internal PDF viewer. When I'm Ctrl+Clicking the content, source code usually opens in wrong group.

**Describe the solution you'd like**
I would like to expect, that source code tab will reveal, if it is already opened.

Simular feature is implemented in `workbench.editor.revealIfOpen`, however, this setting does not work with synctex.

**Describe alternatives you've considered**
Maybe there is a setting, that enables described feature. Unfortunately, I did not find it..

**Additional context**

1.
![image](https://user-images.githubusercontent.com/25643405/108819498-f9853680-75cb-11eb-8364-29acfc0b1f82.png)

2. (Expected revealing existing tab)
![image](https://user-images.githubusercontent.com/25643405/108819578-13267e00-75cc-11eb-8fb2-fb59596ed2c2.png)

UPD:

**System Info**

OS: Manjaro Linux 

`uname -a`:
```
Linux manjaro 5.4.97-1-MANJARO #1 SMP PREEMPT Wed Feb 10 10:24:32 UTC 2021 x86_64 GNU/Linux
```

VSCode version (`code --version`):
```
1.53.1
5d424b828ada08e1eb9f95d6cb41120234ef57c7
x64
```

**Comment by jlelong** [comment]
It seems that removing the `viewColumn` argument from https://github.com/James-Yu/LaTeX-Workshop/blob/c52a5df00f5fc46d5bdc1ce84ed0a8bc2cf34111/src/components/locator.ts#L344

fixes it. When no `viewColumn` argument is provided, the default value `ViewColumn.Active` is used, but its meaning is not clear to me. Yet, in this case it always reveals an already opened editor no matter the value of `workbench.editor.revealIfOpen`.

**Comment by tamuratak** [comment]
I have found that we cannot implement the requested feature due to the restriction of VS Code API. The same request as this issue is microsoft/vscode/issues/13639, which is forwarded to microsoft/vscode/issues/15178, which is locked as too heated.

**Comment by Toliak** [comment]
Oh, ok. I'll wait for mentioned VSCode issue resolution..
Thank you for feedback!

**Comment by tamuratak** [comment]
Reopen the issue since https://github.com/microsoft/vscode/issues/15178#issuecomment-909462369 is going to be implemented.
