### ISSUE TITLE
Command not found when click pdf preview button.

### ISSUE THREAD

**Issue by sbwtw** [James-Yu/LaTeX-Workshop#254]
vscode 1.15.1 on Linux.
LaTeX Workshop 3.4.0

![deepinscreenshot_select-area_20170830142522](https://user-images.githubusercontent.com/3384652/29858244-356f7274-8d8f-11e7-9016-5a7e79df2597.png)

**Comment by zhjsun** [comment]
I update LaTeX Workshop to 3.4.0 this morning. I find that all the actions don't work now.
vscode 1.15.1 on Windows x64
![default](https://user-images.githubusercontent.com/25036446/29860282-e9ee71d4-8d65-11e7-93c5-a6e576b24f4a.png)

**Comment by James-Yu** [comment]
It looks like the extension cannot be activated. Does the status bar item appear? What's the error log in developer console?

**Comment by zhjsun** [comment]
It seems not be activated when start vs code.
![default](https://user-images.githubusercontent.com/25036446/29861242-ec2140aa-8d68-11e7-8fa5-4992e59bac58.png)

**Comment by sbwtw** [comment]
![deepinscreenshot_select-area_20170831112457](https://user-images.githubusercontent.com/3384652/29905085-0d148192-8e3f-11e7-8abb-94f464006ec0.png)
I removed these lines and it's work again.

**Comment by James-Yu** [comment]
It looks like a conflict in registering commands with other extensions. Can you please provide your extension list for me to debug?

**Comment by Songjia** [comment]
It's conflicting with Vim extension. 
Disable Vim and latex will work.

**Comment by alexozer** [comment]
Just talked to a major vscodevim contributor, and he says "latex shouldn't bind `type` while vim should". What is `type` used for in this extension? Can it be avoided?

**Comment by Chillee** [comment]
IMHO, this extension should not be claiming the `type` command, especially for something like this: "Fix intellisense citation browser overriden by word hint". 

I'm not completely sure what that is, but perhaps it would be possible to disable/enable `editor.wordBasedSuggestions` before/after?

**Comment by James-Yu** [comment]
`type` command is not related with word hint thing. It actually provides support to #246 . I need to check if there's other ways to register a key-press listener in vscode api.

**Comment by Zardinality** [comment]
So is there any workaround currently? I have disabled almost all extensions and disabled `editor.wordBasedSuggestions` but doesn't work for me.

**Comment by James-Yu** [comment]
No it's not a user-side configuration. I need to figure out a workaround to register keypress hooks. I am very surprised that vscode has for-only-one-extension api.

**Comment by Chillee** [comment]
@zardinality does disabling all extensions but latex not work? 

@james-yu it kind of makes sense. If the type command functioned more like a pipeline, then we would run into issues about how to order that pipeline.

**Comment by Zardinality** [comment]
Right, I've disabled all extensions but latex in my current workspace, but still `command 'XXX-XXX' not found` error. Should I disabled them in all workspace? Besides, I comment out lines in `main.js` as @sbwtw told above but with no luck.

**Comment by James-Yu** [comment]
@Zardinality please open another issue describing your observations, as it is irrelevant to this issue.
