### ISSUE TITLE
Python code highlighting for all environments of the package `pythontex`

### ISSUE THREAD

**Issue by edward-martyr** [James-Yu/LaTeX-Workshop#2542]
**Is your feature request related to a problem? Please describe.**
When I use the `sympycode` environment (and some others) defined by the package `pythontex`, the Python code isn't highlighted.

**Describe the solution you'd like**
Highlight Python code in all environments provided by `pythontex`, as it already is in the `pycode` environment.

**Comment by jlelong** [comment]
It would help if you could list all the environments that we should support?

**Comment by edward-martyr** [comment]
@jlelong Below are the commands and environments which `pythontex` provides. (It would be better if syntax highlighting in commands can be supported as well)

Python
– Base name py: `\py, \pyc, \pyv, \pyb, pycode, pyverbatim, pyblock`.
– Base name pycon: `\pycon, \pyconc, \pyconv, pyconsole, pyconcode, pyconverbatim`.

Python + pylab (matplotlib module)
– Base name pylab: `\pylab, \pylabc, \pylabv, \pylabb, pylabcode, pylabverbatim, pylabblock`.
– Base name pylabcon: `\pylabcon, \pylabconc, \pylabconv, pylabconsole, pylabconcode, pylabconverbatim`.

Python + SymPy
– Base name sympy: `\sympy, \sympyc, \sympyv, \sympyb, sympycode, sympyverbatim, sympyblock, sympyconsole`.
– Base name sympycon:` \sympycon, \sympyconc, \sympyconv, sympyconsole, sympyconcode, sympyconverbatim`.

and `pysub, \pythontexcustomc, pythontexcustomcode`.

(See [pythontex doc](https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/pythontex/pythontex.pdf) p. 22-28)

**Comment by edward-martyr** [comment]
While the python code is highlighted, the LaTeX environment is not. @jlelong 

<img width="164" alt="スクリーンショット 2021-03-03 14 02 13" src="https://user-images.githubusercontent.com/42882301/109760158-32a35380-7c29-11eb-838f-ba89d7a71092.png">
