### ISSUE TITLE
Using execSync is vulnerable

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2544]
Using `execSync` is vulnerable.

See https://twitter.com/CaptnBanana/status/1365424583898185729

I recommend deleting the feature.

https://github.com/James-Yu/LaTeX-Workshop/blob/50df7f8f4460629c0910e3e7b9e1efca27c5a5a0/src/providers/completer/input.ts#L22-L46

**Comment by jlelong** [comment]
I am not sure to fully understand the problem. Is it really about calling  `execSync` on its own? Or is it related to `git check-ignore`. There is an other place at which we use `execSync`

https://github.com/James-Yu/LaTeX-Workshop/blob/8efa9bb20b6781abac8895f757396ba8bc50c6b6/src/components/builder.ts#L40-L43

It may be worth looking inside vscode how they handle `search.useIgnoreFiles`

**Comment by ps1337** [comment]
that's right! ive planned to open an issue myself but i was tired yesterday :D

the issue is exactly the line @jlelong  mentioned above. file names should be properly escaped

**Comment by tamuratak** [comment]
We should not allow a person to join the discussion who uploaded the 0-day vulnerability before contact with authors.
