### ISSUE TITLE
For the Math Preview

### ISSUE THREAD

**Issue by franto666** [James-Yu/LaTeX-Workshop#2545]
good morning.
I am an Italian student who, like many others, would like to be able to view everything inside the math mode directly below or next to the code. There is already an option that allows me to view the formulas through the cursor, but it is not very convenient to do so: I would like to ask if it is possible to add an option that allows you to view all the mathematical formulas directly next to the code, in the same way as Sublime Text 3
![WhatsApp Image 2021-02-27 at 15 30 24](https://user-images.githubusercontent.com/77899243/109390285-fd3cf400-7910-11eb-9458-9291d62927a0.jpeg)

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#realtime-math-preview-panel for how to have a live math preview panel.

**Comment by franto666** [comment]
hi, thank you for your answer, but unfortunately it is not effective, it does not solve the problem that I have posed. I don't want to open another panel, I just want to see the math preview directly below or next to the code I need to write. I don't want to use the cursor (mouse) to display the formula:

I repeat, there is that I asked, only it works only when I move the cursor, I don't want to use the cursor, I want to see all the mathematical formulas directly.

PS: but if you know how to solve the problem I have exposed, please indicate step by step (really all the steps).

**Comment by Antonella112** [comment]
The Problem you have found is very interesting, it is the only thing that misses in VSCode.

**Comment by jlelong** [comment]
I am afraid integrating a preview of a math environment next to it is out of the scope of the extension.

**Comment by franto666** [comment]
If possible, I ask you to implement this function, since it is one of those functions that allows you not to have to view the pdf document, and therefore enormously speeds up the work that must be done on latex, since you immediately see the result of the written code .

Please implement it.

**Comment by tamuratak** [comment]
Not possible.
