### ISSUE TITLE
"View LaTeX PDF File" should build LaTex

### ISSUE THREAD

**Issue by JesseHines0** [James-Yu/LaTeX-Workshop#2550]
"View LaTeX PDF File" fails silently if the project hasn't been built yet. This is somewhat confusing, as it isn't immediately clear what went wrong. It would be convenient if "View LaTeX PDF File" would automatically build the project if necessary.

Alternatively, it could just pop up an error message telling you to build the project.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by JesseHines0** [comment]
Where would it be in scope?
