### ISSUE TITLE
Allow autocomplete of tags at more positions

### ISSUE THREAD

**Issue by hussein-esmail7** [James-Yu/LaTeX-Workshop#2551]
I find it tiring when I realize I missed the point where I had to press `tab` to autocomplete the end-tag in LaTeX. For example,

> \begin{itemize}
> \item This is an item.
> \end{itemize}

It would be amazing if you could press tab (or ENTER) after the } of the first line, and the rest would auto-generate (without typing what to end), similar to writing HTML in VS Code (<h_1> automatically makes it <h_1></h_1>, without the _ of course, but I don't want to mess up the format of this post).

Here's what already exists:
![What exists](https://user-images.githubusercontent.com/31802504/109585262-2c01c880-7ad1-11eb-9a9b-d644cdb1c562.gif)

Here's what I'm proposing:
![What I want](https://user-images.githubusercontent.com/31802504/109585263-2c9a5f00-7ad1-11eb-9a80-15b61ae9736a.gif)

**Comment by tamuratak** [comment]
Out of the scope of the extension. For the `itemize` environment, please enter `\itemitze`

**Comment by hussein-esmail7** [comment]
@tamuratak `\begin{itemize} + \end{itemize}` is just one example. I'm not referring to something specific for itemize, I mean the actual `\begin{}` and `\end{}` parts. Other examples can be `equation`, `tabular`, `align`, etc.

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#environments for the three different ways of inserting a new environment.
