### ISSUE TITLE
Vim Like Bindings for internal viewer

### ISSUE THREAD

**Issue by edmccabe5** [James-Yu/LaTeX-Workshop#2553]
**Is your feature request related to a problem? Please describe.**
I don't like using the mouse to do stuff if I don't have to. Vim keybinds make everything faster.

**Describe the solution you'd like**
If the PDF viewer had the option for some simple vim bindings `h`, `j`, `k`, and `l` to get around, that would be great.

**Describe alternatives you've considered**
Could use an external PDF viewer, but then lose SyncTex functionality. I use evince on my desktop, but I have to use Windows 10 at work. So I use this extension.

**Additional context**

**Comment by jlelong** [comment]
Navigation shortcuts recognised by the internal viewer are listed at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#navigation.

- `n`, `j`: next page
- `p`, `k`: previous page
- up and down arrows can be used to scroll
