### ISSUE TITLE
Embedding C++ code is partly broken

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#2555]
Consider the latex code

```latex
  \begin{cppcode}
    void f(double x) {
      return x * x;
    }
  \end{cppcode}
```

Although the `C++` code is properly highlighted, it does not have `cpp` language type and hence calling `editor.action.commentLine` does nothing.

The problem was introduced by #2398.

**Comment by tamuratak** [comment]
I think it is an appropriate way to use [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide). By applying semantic highlighting to codes inside the `cpp` environments, highlighting and the command will work.

According to a [comment](https://github.com/microsoft/vscode/issues/113640#issuecomment-754061490) by the VS Code team, parts of the LaTeX document not covered by semantic highlighting will be highlighted with TM tokens.

**Comment by tamuratak** [comment]
The above approach seems not to work. microsoft/vscode/issues/81558

**Comment by jlelong** [comment]
I cannot find how to solve this issue without reverting  #2398.

A possible solution, would be to automatically generate a new bailed out version of the `cpp` syntax every time we create a new release. It is just about adding 

```
"bailout": "node dev/generate-bailout.js"
```

to the scripts defined in `package.json` and calling `bailout` inside the `release` script. What do you think of this?

**Comment by tamuratak** [comment]
How about creating a JSON file where `comments`, `autoClosingPairs`, and others  are defined for the `cpp_embedded_latex` language?

**Comment by jlelong** [comment]
This is also possible. In any case, it would help to have a mechanism to automatically keep track of changes in https://github.com/microsoft/vscode-cpptools

**Comment by jlelong** [comment]
Yes you are right. We create the bailed out version of the grammar from https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/syntaxes/cpp.tmLanguage.json. 

If we follow the strategy described in https://github.com/James-Yu/LaTeX-Workshop/issues/2555#issuecomment-796282644, we should also monitor https://github.com/microsoft/vscode/blob/main/extensions/cpp/language-configuration.json
