### ISSUE TITLE
Replace the progress bar with a time counte

### ISSUE THREAD

**Issue by hao3han3** [James-Yu/LaTeX-Workshop#2556]
In my view, the progress bar just shows that the compilation is in progress, but can not show how much percentage of the work have down. This makes me a little nervous and anxiety because I do not know when it finished but only look at the pdf views and wait.
But, the time of the complication is shown after it is finished.

Thus, I want to ask a time counter, which is start at zero when complication start.
This is because I know how much time needed in one complication. This is based in many preview complications and the time shown after complication. 

Just make an example for better understand:
I know it will cost roughly 40s for one complication, no matter it is 39s or 45s. This is because I did a lot of complication.
And, then, there is a time counter, which is located at the position of progress bar, that start at 0 when I press "Ctrl + Alt + B". Then I know how much time passed and how much time I estimate to wait. So I do not need to wait  and look at but nothing to do.

OK, this is my suggestion.
I hope this function can be added with an option to turn it on/off or replace with progress bar.
Thank you.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
