### ISSUE TITLE
Enable CodeQL

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2558]
I have enabled CodeQL, which scan vulnerabilities in our code base.

- https://github.blog/2020-09-30-code-scanning-is-now-available/
- https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/using-codeql-code-scanning-with-your-existing-ci-system

We can see errors and warnings [here](https://github.com/James-Yu/LaTeX-Workshop/security/code-scanning), which are visible only to collaborators.

**Comment by jlelong** [comment]
This is really helpful
