### ISSUE TITLE
IntelliSense for Declaremathoperator, Declaremathoperator* and newcommand*

### ISSUE THREAD

**Issue by YonYonYonYonYon** [James-Yu/LaTeX-Workshop#2559]
Currently IntelliSense detects commands added by \newcommand (for example \newcommand{\test}{test}, now \test comes up in IntelliSense)
It does not detect it for \Declaremathoperator, \Declaremathoperator* and \newcommand*.
It would be nice to extend this functionality to these situations.
For \newcommand* it would be nice to make it respect number of arguments as it does for \newcommand (i.e. \newcommand*{\test}[3]{test #1 #2 #3} should come up as \test{}{}{})

**Comment by fpqc** [comment]
I didn't test \providecommand and \providecommand*, but these should also be added to the same logic.
