### ISSUE TITLE
Specific Mechanism for true Latex preview math

### ISSUE THREAD

**Issue by RaphaelArkadyMeyerNYU** [James-Yu/LaTeX-Workshop#2560]
**Is your feature request related to a problem? Please describe.**
I would like LaTeX packages to be included in the math preview.

(I know I'm not the first person to request this, and I know that the current MathJax system is fundamentally not able of doing this.)

**Describe the solution you'd like**
I'm used to using LaTeXTools from the Sublime Text 3 community, which can quickly generate math previews that are genuinely created with LaTeX. Specifically, my understanding is that they use ImageMagick and Ghostscript to pipe the LaTeX pdf output (rendered as a standalone documentclass) into a png that Sublime can render.

I propose porting this approach over into LaTeX-Workshop.

**Describe alternatives you've considered**
I tried finding a VSCode package that already does this, but found nothing.

I also considered just dealing with the extra red text, but this is actually pretty prohibitive for me. When I open any existing LaTeX project of mine, and preview a math equation, at least 4/5 of the width of the preview is just red text.

Another alternative is just to hide the red text entirely (maybe an optional setting?). This would really help, at least in the short term.

**Additional context**
Sources: [LaTeXTools readthedocs](https://latextools.readthedocs.io/en/latest/features/#previewing) and [LaTeXTools source code](https://github.com/SublimeText/LaTeXTools/blob/master/st_preview/preview_math.py)

This approach runs really well in my experience: a 6 year old middle-tier laptop could render and update multiple equations at once without any issue whatsoever.

This would require users to have ImageMagick and Ghostscript installed on their machines, which seems fine to me?

Caveat: I am new to VSCode, so I would not know about any VSCode specific issues that prevent this implementation of this.

I also would not mind working on this myself, but I wouldn't know where to start.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
