### ISSUE TITLE
LaTeX-style quatation mark

### ISSUE THREAD

**Issue by mattia-lecci** [James-Yu/LaTeX-Workshop#2563]
In LaTeX, quotation marks should be `` ` ' `` instead of `' '`, and double quotation marks should be ``` `` '' ``` instead of `" "`.

Coming from Sublime Text 3 with LaTeXTools+LaTeXYZ, quotation and double quotations were automatically coupled and substituted with the correct latex form and the cursor in the middle just typing `'` or `"`.
Would this be possible in VSCode as well?

Alternative (sub-optimal) solution: can a simple snippet be added?

I checked the documentation but couldn't find a solution anywhere.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

Please type `
