### ISSUE TITLE
Further improvement in handling frame titles

### ISSUE THREAD

**Issue by tueda** [James-Yu/LaTeX-Workshop#2569]
**Is your feature request related to a problem? Please describe.**

Related to #1524 and #1527.

It will be nice if more complicated Beamer frame titles containing groupings `{...}` could be shown in the outline (see the example below).

**Describe the solution you'd like**

Extend the regular expressions in [getCaptionOrTitle](https://github.com/James-Yu/LaTeX-Workshop/blob/39743dd1841ea439bab3ad0bacfecb4a2ff02d4f/src/providers/structure.ts#L303) to capture more complicated frame titles, though I'm not sure in general it is possible to capture nested brackets (for example, `\textit{{\Huge}}`) with RegExp.

**Describe alternatives you've considered**

If capturing arbitrarily nested brackets is difficult, maybe a certain nested level (1 or 2) for brackets would be enough. Indeed, what actually I hit was:
```tex
\begin{frame}{\texorpdfstring{$q \bar{q}$}{q qbar}}
```

**Additional context**

Currently (v8.16.1), complicated frame titles don't match with the regular expressions and are ignored for the outline. For the following example, the 2nd and 5th ones are ignored.
```tex
\documentclass{beamer}
\begin{document}

\begin{frame}{FRAME 1}
  This is OK.
\end{frame}

\begin{frame}{\textit{FRAME 2}}
  Not OK.
\end{frame}

\begin{frame}
  \frametitle{FRAME 3}
  OK.
\end{frame}

\begin{frame}
  \frametitle{\textit{FRAME 4}}
  OK.
\end{frame}

\begin{frame}
  \frametitle{\textit{FRAME {\Huge 5}}}
  Not OK.
\end{frame}

\begin{frame}{FRAME 6}
  OK.
\end{frame}

\end{document}
```

![image](https://user-images.githubusercontent.com/1481665/110472967-5b43b580-8121-11eb-9096-a68ce1cb0651.png)

**Comment by jlelong** [comment]
Indeed, it is not possible to capture any number of levels of nested brackets using regex. We can allow 1 or 2 levels.

**Comment by jlelong** [comment]
Now, we accept 2 levels of nesting braces in frame titles.

**Comment by tueda** [comment]
Thank you! I've confirmed that frame titles of my document match with the improved regexp (though I haven't tried the master branch of LaTeX-Workshop with VS Code).
