### ISSUE TITLE
use editorTextFocus for "when" field of keybindings

### ISSUE THREAD

**Issue by jfeist** [James-Yu/LaTeX-Workshop#257]
First of all: thanks a lot for this really great package!

While using LaTeX-Workshop, I would many times press the keybindings for building or SyncTeX etc, and they were mysteriously not working. At some point, I discovered that they are defined with a `"when"` field of `"editorFocus && !findWidgetVisible && !replaceActive && !searchViewletVisible"`, and sure enough, they stopped working as soon as the find widget was visible. I presume that this is to prevent the keybindings from working while the user is entering text in the find widget, but as it's written, it also suppresses them when the cursor is in the editor. I accidentally discovered that you can simply use `"editorTextFocus"` instead, so that they work as long as the cursor is in the editor window, even if the find widget is open. 
IMHO, this behavior makes much more sense, unless there's some additional reason for the current behavior that I missed. Could this be changed?

**Comment by James-Yu** [comment]
It's actually some 'historical' issue. Fixed and will be published soon.
