### ISSUE TITLE
Doubled warnings from chktex in files included via \input

### ISSUE THREAD

**Issue by miromarszal** [James-Yu/LaTeX-Workshop#2570]
Files included via `\input` get double warnings.

Consider the following project that has one root file and one included file.

```main.tex```
```latex
\documentclass{report}

\begin{document}
    \input{included.tex}
    And also here...
\end{document}
```

```included.tex```
```latex
I should use ldots here...
```

I would expect two warnings, one for each incorrect ellipsis. However, what I see in vscode is this:
![chktex_double_warn](https://user-images.githubusercontent.com/29063081/110526788-85dc4100-8116-11eb-8dfd-6c02753a2df7.png)

I don't think it's a problem with chktex itself, as I was not able to reproduce this from command line. Should I somehow modify the default config to handle projects with a root file and multiple `\input`? I have a feeling that the linter goes through the file twice for some reason.

**Comment by jlelong** [comment]
Related to #2535 and PR #2549. It seems that we got it wrong in #2535, `chktex` lints included files if we do not pass `-I0`.
It seems sufficient to remove 0e3858a to fix this.
