### ISSUE TITLE
Previewing graphics error 

### ISSUE THREAD

**Issue by xjtunk** [James-Yu/LaTeX-Workshop#2574]
Recently, I have updated VSCode into Version1.54.1, while the Latex-Workshop has been updated into Version 8.16.1. However, there is something wrong with previewing graphics. Sepecifically,  the .png figures will be previewed as messy code, as shown in following figure.
![Error for png](https://user-images.githubusercontent.com/5841833/110643000-9233cd00-81ee-11eb-84fd-3be9be9bbdbb.png)

And the .pdf figures also can not be displayed correctly, as shown in following figure.
![Error for pdf](https://user-images.githubusercontent.com/5841833/110642999-9233cd00-81ee-11eb-9828-1440591f1ac2.png)

Looking forward to you can fixed this bug.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.
