### ISSUE TITLE
Different recipes with different shortcut.

### ISSUE THREAD

**Issue by wang-xudong** [James-Yu/LaTeX-Workshop#2577]
If I have any way that binding different recipes with different shortcuts. For example, I want use 'ctrl+a' to build latex with a recipe names pdflatex, and 'ctrl+b' to build latex with a recipe names xelatex. I found a command 'latex-workshop.recipes', but when I use it, I have to choice a recipe every time.

**Comment by jlelong** [comment]
In `keybindings.json` (Keyboard Shorcuts menu), add

```
    {
        "key": "alt+cmd+a",
        "command": "latex-workshop.recipes",
        "args": "pdflatex ➞ bibtex ➞ pdflatex × 2",
        "when": "editorLangId =~ /latex|rsweave|jlweave/"
    }
```

You set the recipe name in `args`.
