### ISSUE TITLE
Choosing a LaTeX recipe by dynamical conditions

### ISSUE THREAD

**Issue by tueda** [James-Yu/LaTeX-Workshop#2578]
**Is your feature request related to a problem? Please describe.**

It will be useful if a LaTeX recipe could be chosen by additional dynamical conditions, like the existence of some files or executables. For example, use `make` defined in `latex-workshop.latex.tools` if the following 3 conditions are satisfied:

1. `Makefile` exists,
2. `make` utility is available, and
3. `make -n %DOCFILE%.pdf` succeeds (`-n` is the POSIX option for "dry run"), i.e., a rule for `%DOCFILE%.pdf` exists.

Another use case is to use [`llmk`](https://ctan.org/pkg/light-latex-make) if:

1. `llmk.toml` exists, and
2. `llmk` utility is available.

This is a kind of generalization of https://github.com/James-Yu/LaTeX-Workshop/issues/298.
(But note that this is completely different from https://github.com/James-Yu/LaTeX-Workshop/issues/337; CMake is a generator of Makefile (or recipes for other build tools) and one needs to prepare for how to generate recipes by programming in CMake language, though VS Code has a very good extension to support CMake.)

**Describe the solution you'd like**

How about the following idea?
Add a new `if` key, whose value takes a list of strings, in LaTeX recipes. For example,

```json
"latex-workshop.latex.recipes": [
  {
    "name": "make",
    "tools": [
      "make"
    ],
    "if": [
      "test -f Makefile",
      "command -v make",
      "make -n %DOCFILE%.pdf"
    ]
  },
  {
    "name": "llmk",
    "tools": [
      "llmk"
    ],
    "if": [
      "test -f llmk.toml",
      "command -v llmk"
    ]
  },

  "... other recepes, e.g., latexmk"
]
```
with
```json
"latex-workshop.latex.tools": [
  {
    "name": "make",
    "command": "make",
    "args": [
      "%DOCFILE%.pdf",
    ]
  },
  {
    "name": "llmk",
    "command": "llmk",
    "args": [
      "%DOCFILE_EXT%",
    ]
  },

  "... other tools ..."
]
```
would do the job that I described above. Here I assumed that each string for the `if` key is executed as a command in a POSIX shell and the return code will be checked. More favourable if this could be somehow more portable (i.e., Windows). With `"latex-workshop.latex.recipe.default": "first"`, the set of conditions for `make` is checked first, that for `llmk` is second, and if they are not satisfied then the first one in the other recipes (e.g., `latexmk`) will be executed as a fallback.

**Describe alternatives you've considered**

Maybe the external build command mechanism could be extended with similar dynamical conditions.

**Additional context**

**Comment by jlelong** [comment]
Ouf the scope of the extension.
