### ISSUE TITLE
curly brackets are incorrectly matched with escaped brackets.

### ISSUE THREAD

**Issue by we-taper** [James-Yu/LaTeX-Workshop#2582]
## Preliminary questions

Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue.

You still see this issue?: Yes

Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: No

## Describe the bug

When a curly bracket is escaped with `\`, it mess up the bracket matching in VSCode.

### To Reproduce

Minimal example:

```tex
\documentclass{article}

\begin{document}

There is a bracket inside brackets {\}}.

\end{document}
```

Opening the above example in vscode, the first bracket "{" will pair with the second bracket in "\}" but it should pair with the third bracket.
![image](https://user-images.githubusercontent.com/6148706/111151699-b9d8bb80-8587-11eb-89d7-d3f4906cf35b.png)

I am not sure if this is a bug or a feature request though... :smiley_cat:

**Comment by tamuratak** [comment]
We can do nothing on our side due to the restriction of VS Code API.

**Comment by we-taper** [comment]
@tamuratak Shall I create issue in VSCode instead?

**Comment by tamuratak** [comment]
I recommend you not to create such an issue. Please endure the current behavior.
