### ISSUE TITLE
Project not compiling if bibliography is missing

### ISSUE THREAD

**Issue by ajdapretnar** [James-Yu/LaTeX-Workshop#2586]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Project cannot be compiled when bibliography is missing.

### To Reproduce

Try to compile a project without \bibliography command.

### Expected behavior

The project compiles normally.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
------------
Running 'bibtex  "2021-heristem"'
------------
Latexmk: applying rule 'bibtex 2021-heristem'...
For rule 'bibtex 2021-heristem', running '&run_bibtex(  )' ...
This is BibTeX, Version 0.99d (TeX Live 2019)
The top-level auxiliary file: 2021-heristem.aux
A level-1 auxiliary file: ch-copyright.aux
I found no \citation commands---while reading file 2021-heristem.aux
I found no \bibdata command---while reading file 2021-heristem.aux
I found no \bibstyle command---while reading file 2021-heristem.aux
(There were 3 error messages)
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
Latexmk: Errors, so I did not complete making targets
```

### Developer Tools Console [Required]
None. 🤷 

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: OSX (High Sierra)
 - VS Code version: 1.54.3
 - Extension version: v8.16.1
 - TeX distribution version: TeX Live 2019

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Apologies if some info is missing. I tried my best.
The issue could be with Latexmk, not sure. I am just wondering if there's a way to turn off bibliography parsing?

**Comment by tamuratak** [comment]
This issue is not related to the extension.

Please ask at https://tex.stackexchange.com/
