### ISSUE TITLE
Meta: please don't limit conversation to collaborators for closed issues

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#2588]
I understand that you may want to avoid unnecessary notifications for closed issues by unhappy users. However, I think limiting conversations to collaborators is a bad way of achieving that. There are a bunch of things that would still be helpful for users to be able to do, which are impossible in limited conversations:

- Share workarounds for issues closed without resolution
- Edit past comments (fix typos and errors, update workarounds, add new insight, ...)
- React to other comments (to highlight a comment as particularly helpful, or as not applicable)
- Add arguments why closing the issue is a bad idea (these cases do happen)

**Comment by tamuratak** [comment]
Please endure it.
