### ISSUE TITLE
Auto-completion for control word does not include trailing non-letter char

### ISSUE THREAD

**Issue by wwtan** [James-Yu/LaTeX-Workshop#2589]
**Is your feature request related to a problem? Please describe.**
The auto-completion for control word does not include the trailing non-letter char.
I have taken the Option 4 in this [Guho's answer in stackexchange](https://tex.stackexchange.com/questions/31091/space-after-latex-commands/290504#290504), which is to add a trailing non-letter char such as `/` to that the spacing after the control word will work properly.

### To Reproduce

1. define new control word, `\newcommand{\arnold/}{Arnold Schwarzenegger}`
2. in the document, type `\arno` and press _tab/enter_ to auto-complete.
3. the auto-completion gives `\arnold` without the trailing `/`.

**Describe the solution you'd like**
auto-completion should yield `\arnold/`

**Describe alternatives you've considered**
Seems to be similar to #1915?
Adding additional `/` to the regex similar to [this commit](https://github.com/James-Yu/LaTeX-Workshop/commit/56090490a5a316f8c4a4b861b84b93149b21c0c2) would help?
To be honest, I am not a latex expert so please do let me know if trailing `/` is not a good idea. I just followed the Guho's answer.

**Additional context**
Just tried this extension and it's my default now! Thanks and kudos for the awesome work!

**Comment by jlelong** [comment]
According to https://tex.stackexchange.com/a/66671, a command cannot mix letter and non-letter characters. Indeed, the following does not compile

```latex
\documentclass{article}

\newcommand{\arnold/}{Arnold Schwarzenegger}
\begin{document}
    \arnold/
\end{document}
```

Of course, you can always assign a letter _catcode_ to a non-letter character but this is not standard.

**Comment by wwtan** [comment]
Hi @jlelong,
sorry that I had the wrong code in item 1. it should be using `\def` instead of `\newcommand` (I have updated the issue). It should be able to compile with standard latex now.
```tex
\documentclass{article}

\def\arnold/{Arnold Schwarzenegger}
\begin{document}
    \arnold/
\end{document}
```
