### ISSUE TITLE
Auto rename tag, but for latex environments

### ISSUE THREAD

**Issue by abrahammurciano** [James-Yu/LaTeX-Workshop#2590]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I change from `equation` environment to `gather`, or from `gather` to `align` or whatever, and I have to change the name of both `\begin{whatever}` and `\end{whatever}`.

**Describe the solution you'd like**
Just like [this extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) does for HTML, I'd like to only change it once and the matching begin/end should update to match my change.

**Comment by jlelong** [comment]
When inside an environment, you can use the command `latex-workshop.select-envname` to select the environment inside `\begin{...}` and `\end{...}`. Then, you can replace both at once thanks to VSCode's multicursors.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#Navigating-and-selecting
