### ISSUE TITLE
after changing the outDir in settings.json and outputdir in .tex , minted fails

### ISSUE THREAD

**Issue by hyjz2018** [James-Yu/LaTeX-Workshop#2597]
by using cmd line `xelatex -shell-escape demo.tex` I get the right pdf with 4 snippets as follows 
![cmdxelatex](https://user-images.githubusercontent.com/39937562/112709188-0c07ce00-8ef2-11eb-8a0d-de69c3f79659.png)

but when I change the outDir in settings.json and outputdir in demo.tex at the same time , vscode recipe `xelatex` compiled result shows there are only 2 .pygtex so the same snippet as follows
![dirchanged](https://user-images.githubusercontent.com/39937562/112709189-13c77280-8ef2-11eb-8ea0-617ecac0820e.png)

here are my settings and demo.tex
```
"latex-workshop.latex.outDir": "C:/Users/hy-jz/tmp/tex",
"latex-workshop.latex.tools": [
    {
        "name": "xelatex",
        "command": "xelatex",
        "args": [
            "-shell-escape",
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-output-directory=%OUTDIR%",
            "%DOC%"
        ],
        "env": {}
    },
],
"latex-workshop.latex.recipes":[
    {
        "name": "xe",
        "tools": [
          "xelatex"
        ]
    },   
    {
        "name": "latexmk",
        "tools": [
          "latexmk"
        ]
    },

],
```

tex file
```
\documentclass[12pt,openany]{book}
\usepackage[outputdir="C:/Users/hy-jz/tmp/tex"]{minted}
%\usepackage{minted}
% cachedir="C:/Users/hy-jz/tmp/tex"

\newminted{sh}{frame=single}
\begin{document}
\title{demo}
\author{me}

\chapter{chap1 }
text
\section{sec 1}
\begin{shcode}
#!/bin/bash
echo 1
\end{shcode}

\begin{shcode}
#!/bin/bash
echo 2
\end{shcode}

\begin{minted}{shell}
#!/bin/bash
echo 3
\end{minted}

\begin{minted}{shell}
#!/bin/bash
echo 4
\end{minted}

\end{document}
```

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment]
gpoore/minted/issues/298
