### ISSUE TITLE
Issue with synctex shortcut ??

### ISSUE THREAD

**Issue by angan06** [James-Yu/LaTeX-Workshop#26]
Dear James, I apologize for which is maybe a simple question : 

I tried to assign a shortcut to use the command synctex like this:
{"key": "alt+numpad2", "command": "latex-workshop.synctex"}

However this has no effect. But using right click "Find here in Preview" works. 
Do you know where the problem come from. 

Thank you for you last answer. With the last update of code, it is now possible to see the symbol \sum and \prod.
Once again, thank you for your extension.
PS : I am on linux mint.

**Comment by James-Yu** [comment]
I am not sure what causes this problem. My suspicion is on using ALT as modifier key. Did you try others such as ALT+CTRL+N2?
The menu item and the command is equivalent:
https://github.com/James-Yu/LaTeX-Workshop/blob/master/package.json#L75

**Comment by angan06** [comment]
Yes, I tried several shortcut such as ctrl+ a letter, your suggestion or even just a letter. But it does not have any effect. 
The menu item show me the shortcut I set next to Find Here in Preview. 
Using the menu item always works smoothly.

**Comment by James-Yu** [comment]
Sorry I cannot identify the problem. I would figure it to be an upstream problem with vscode. Temporarily close the issue.
