### ISSUE TITLE
duplicate labels

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#2600]
Above all, I'd like to thank @jlelong for implementing duplicate labels #2505.
It seems to correctly check and to correctly add the warning in the problems panel. This causes VS Code to squiggly underline the duplicate label (\label{eq:1}, say) in the text.
However, it seems that only the _first occurrence_ of \label{eq:1} is underlined in the text, but not the second, duplicate. Of course, it would be useful to underline _every_ occurrence of the duplicate labels. 

I hope I spotted this behavior correctly. 

Nonetheless, I have to congratulate again to your maintenance of this fantastic extension.

**Comment by jlelong** [comment]
It was more related to the duplicate labels being defined in the same file or not. Ask for reopening if you are still able to reproduce the issue and provide an example.

**Comment by aloispichler** [comment]
This works well now.
Congrats, and thank you!
