### ISSUE TITLE
Duplicate of  #2574. Fixed in 47b54cf520da2419c09c208130fbe287a1907704

### ISSUE THREAD

**Issue by camots** [James-Yu/LaTeX-Workshop#2604]
Duplicate of  #2574. Fixed in 47b54cf520da2419c09c208130fbe287a1907704

_Originally posted by @tamuratak in https://github.com/James-Yu/LaTeX-Workshop/issues/2592#issuecomment-803540420_

**Comment by camots** [comment]
What does this mean now?
Do we have to move to vscode-Insiders in order to get it working?
In vscode 1.55.0 the issue still remains.

**Comment by tamuratak** [comment]
The issue will be fixed in the next release of LaTeX Workshop.
