### ISSUE TITLE
Inclusion of Rnw files using <<child=...>> does not work

### ISSUE THREAD

**Issue by pascalsiemsen** [James-Yu/LaTeX-Workshop#2607]
**Is your feature request related to a problem? Please describe.**
I am working with multiple Rnw files. The structure overview shows the root tex file that gets created after knitting. This is not helpful in navigation as I want to navigate inside the Rnw and not the tex file.

**Describe the solution you'd like**
Let the structure overview show the contents of the Rnw. Maybe it could detect the root magic 

`%!Rnw root=index.Rnw`

**Additional context**
I've seen that a content for an Rnw file is only produced when \begin{documtent} is present. But as my Rnw is a child, there is no \begin{document}. 

![Screenshot from 2021-04-07 15-11-28](https://user-images.githubusercontent.com/36855562/113871887-a4843500-97b3-11eb-9b1e-764775c3f3f5.png)

**Comment by jlelong** [comment]
Can you share a minimal working example to debug what is going on?
It looks like the extension thinks the root file is `index.tex` instead of `index.Rnw`.

**Comment by pascalsiemsen** [comment]
Just created the minimal example below and now the structure is empty. This suggest that the extension does not refer to the created root.tex in this example. But an empty overview is also not helpful.

Btw, thanks for this great extension. Makes editing text so much more pleasing.

Example:

https://github.com/pascalsiemsen/rnw_structure


root.Rnw

```
\documentclass{article}
% General document formatting
\usepackage[margin=0.7in]{geometry}
\usepackage[parfill]{parskip}
\usepackage[utf8]{inputenc}


\begin{document}

<<child-demo, child='ch1.Rnw'>>=
@
\end{document}
```


ch1.Rnw
```

% !Rnw root = root.Rnw 

\section{Section 1}
Test file

\section{Section 2}
test
```

**Comment by jlelong** [comment]
For the moment, we only support file incluse using `SweaveInput` but not `<<child='ch1.Rnw'>>`. I will study how we could use the `<<child=...>>` meta information.

**Comment by James-Yu** [comment]
With #3335 merged, the structure support to `<<child='...'>>` is dropped.
