### ISSUE TITLE
Feature Request - Show LaTeX log in the Output window during a Project Build

### ISSUE THREAD

**Issue by kuenzign** [James-Yu/LaTeX-Workshop#261]
Most stand-alone LaTeX editors will show the log file in an output window during compilation.  The ability to see the log appears to be an available feature with this extension, but it would be great to see the live output feed in the Output window.  Additionally, syntax highlighting for this would be useful (warnings vs. errors vs. information).

**Comment by James-Yu** [comment]
Can you please elaborate on the reason of providing live log in place of the current presentation form? What most others do might not be a mandatory for late-comers.

**Comment by kuenzign** [comment]
Most other languages in VS Code display a live log to the output window during compilation.  Additionally, it makes it a lot easier to follow issues on larger projects because the information is presented one line at a time, instead of all at once in a large file.  It also seems a little out of the way to open the log file (around 3 mouse clicks vs. 0 clicks and having it output dynamically).

**Comment by kuenzign** [comment]
Thanks for the quick response!
