### ISSUE TITLE
Loading PDF slowly on ARM64 version

### ISSUE THREAD

**Issue by GengchaoCode** [James-Yu/LaTeX-Workshop#2612]
Issue Type: <b>Performance Issue</b>

It simply takes minites to load a small PDF file on my Surface Pro X.

Extension version: 8.16.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:08.002Z)
OS version: Windows_NT arm64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Microsoft SQ2 @ 3.15 GHz (8 x 1670)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.47GB (11.08GB free)|
|Process Argv|--crash-reporter-id a620ead8-20dc-46b3-b7da-69be7a9b19da|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    71	  6308	code main
    0	   153	  2164	   gpu-process
    1	    79	  2948	   window (Issue Reporter)
    0	    35	  7140	   utility
    0	    22	  8548	   crashpad-handler
    0	   105	 11052	   shared-process
    0	    61	 12700	     ptyHost
    0	   196	 12224	   window (Visual Studio Code)
    0	   126	  1844	     extensionHost
    0	    63	  5288	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=1844
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30286882

```

</details>

**Comment by tamuratak** [comment]
We can do nothing on our side.
