### ISSUE TITLE
Option to disable the "Surrounding text" feature when typing over highlighted text

### ISSUE THREAD

**Issue by devonupton** [James-Yu/LaTeX-Workshop#2613]
**Is your feature request related to a problem? Please describe.**

 While the problem is not a bug, it's a problem with workflow. When I highlight text and begin to type over it, I'd like that text to be gone and not suddenly reappear after I enter a command. The "Surrounding text" feature is great when triggered with a hotkey (Ctrl+LW) by default, but I'd _really_ like to disable this alternative trigger as it's very frustrating to work around.

For example, if I highlight the `\)` part of `\(y=x\)` and type `$`, I want it to replace the highlighted text, (i.e. `\(y=x$`) , not surround it (i.e. `\(y=x$\)$`).

Another example: If I highlight any amount of text and type '\itemize \<Tab\>' with the intention of overwriting that text, it ends up pasting the text that I just overwrote inside the itemize environment! I do not want this to occur. I want that text to be gone unless I manually trigger the Ctrl+LW hotkey.

**Describe the solution you'd like**

I'd like the ability to disable this alternative feature. So far, this extension has been great for customizability, even though I've kept most of the default settings since they're pretty good, but the ONE feature that I dislike happens to be the ONE feature I'm not allowed to disable. Just my luck!

To be clear, I don't want to disable the "Surrounding text" feature entirely, just the part where typing over highlighted text triggers it. The hotkey approach should ideally still be available.

**Describe alternatives you've considered**

In some cases, like my second example above, when it rewrites the previously deleted text, it stays highlighted, which fortunately allows me to immediately type over it, but this isn't ideal. This alternative solution doesn't work everywhere though anyway.

**Comment by tamuratak** [comment]
> For example, if I highlight the \) part of \(y=x\) and type $, I want it to replace the highlighted text, (i.e. \(y=x$) , not surround it (i.e. \(y=x$\)$).

Set `"editor.autoSurround": never`. See https://code.visualstudio.com/api/language-extensions/language-configuration-guide#autosurrounding

> When you select a range in VS Code and enter an opening bracket, VS Code surrounds the selected content with a pair of brackets. This feature is called Autosurrounding

**Comment by devonupton** [comment]
Ah thank you! I didn't realize this was a VS Code feature, so I guess I'm blaming the wrong party here. I'm surprised I haven't encountered this issue in other filetypes.
