### ISSUE TITLE
`\usepackage` in hover preview? 

### ISSUE THREAD

**Issue by Romeoly** [James-Yu/LaTeX-Workshop#2614]
**Is your feature request related to a problem? Please describe.**
When I hover over an equation, some commands (e.g., `\dag' and `\bm') can not be interpreted. 

**Describe the solution you'd like**
Can I, or how do I, use `\usepackage` in `latex-workshop.hover.preview.newcommand.newcommandFile`?

**Comment by jlelong** [comment]
Equations are rendered by mathjax, which cannot load LaTeX packages, see https://stackoverflow.com/a/21194570. Files listed in `latex-workshop.hover.preview.newcommand.newcommandFile` can only contain command definitions.

The commands understood by mathjax are listed on https://docs.mathjax.org/en/latest/input/tex/macros/index.html.
