### ISSUE TITLE
Update Documetation for setting up "arara"

### ISSUE THREAD

**Issue by mafsi** [James-Yu/LaTeX-Workshop#2615]
**Is your feature request related to a problem? Please describe.**
I tried in settings to use `arara` but I don't know how to configure. If I use it from TexStudio or from CLI is working

**Describe the solution you'd like**
The code for command using arara

**I tried this**

in `"latex-workshop.latex.tools"`
```
        {
            "name": "arara",
            "command": "arara",
            "args": [
                "--verbose",
            ],            
            "env": {}
        }   
```

I get the error

```
Usage: arara [OPTIONS] file...

Error: Missing argument "file"
```

**My file has these lines**

```
% !TeX program = arara
% !TeX encoding = UTF-8
% !TeX spellcheck = ro_RO-Romanian
% arara: pdflatex: { synctex: on, shell: off }
% arara: biber
% arara: pdflatex: { synctex: on, shell: off }
% arara: pdflatex: { synctex: on, shell: off }
% arara: clean:  { extensions: [ aux, log, out, toc, blg, bbl, bcf ] }
```

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by mafsi** [comment]
I managed to solve the problem.

**Instead of:**

```
        {
            "name": "arara",
            "command": "arara",
            "args": [
                "--verbose",
            ],            
            "env": {}
        } 
```

**Should be**

```
        {
            "name": "arara",
            "command": "arara",
            "args": [
                "--verbose",   
                "%DOCFILE%"  % <-- this line should be added.
            ],            
            "env": {}
        }    
```

Thanks for your extension! Keep up the good work!
