### ISSUE TITLE
Format Verbatim Environment

### ISSUE THREAD

**Issue by a-mhamdi** [James-Yu/LaTeX-Workshop#2616]
I am struggling with the *format document* option when it contains `verbatim` environment. Sometimes, I need to include `Python` code snippets to my `**LaTeX**` files and I do not want the code inside the verbatim environment to be formatted.

**Is it possible to format the document globally and exclude the verbatim environment?**

Thanks :)

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by a-mhamdi** [comment]
@tamuratak Thanks for the hint! Some tweaking resolved the issue. Very grateful.

**Comment by a-mhamdi** [comment]
@tamuratak Thanks for the hint.
