### ISSUE TITLE
How do I disable "Underfull \hbox (badness 10000)" warning?

### ISSUE THREAD

**Issue by OtakoidTony** [James-Yu/LaTeX-Workshop#2619]
![20210416_232749](https://user-images.githubusercontent.com/36785562/115040197-24c13d80-9f0c-11eb-9bf7-27a4736e512d.png)

How do I disable a blue underline in a picture?

**Comment by jlelong** [comment]
Set `latex-workshop.message.badbox.show` to `false`, see https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessagebadboxshow
