### ISSUE TITLE
The TOC for web browser is dim.

### ISSUE THREAD

**Issue by Teng-Martin-Ma** [James-Yu/LaTeX-Workshop#2622]
When taggle the table of contents on browser, the words are dim and background is too dark to select. Hurt eyes.

**Comment by jlelong** [comment]
Post a screenshot to explain your issue along with an example and the settings used to reproduce the behaviour. When done, we will reopen the issue if needed.

**Comment by Teng-Martin-Ma** [comment]
![image](https://user-images.githubusercontent.com/16615115/115241180-6e7e7380-a118-11eb-95e2-ddf14af11bec.png)
The screenshot is like above (the default setting), can we change the background color to white?

**Comment by jlelong** [comment]
Duplicate of #2624
