### ISSUE TITLE
Equation Preview not including amsmath and other packages

### ISSUE THREAD

**Issue by NicoJG** [James-Yu/LaTeX-Workshop#2623]
I guess this is not really a bug report but rather a question how I can improve the Hover Preview.

How can I include packages for the hover preview of equations? 
I use multiple maths packages that would be awesome to have a hover preview for: amsmath, amssymb, mathtools, unicode-math, siunitx .
How can I tell LaTeX-Workshop where to find and to include these packages?

And a side question: Where should I ask those questions the next time?

**Comment by tamuratak** [comment]
We implement hover preview with MathJax. MathJax does not support LaTeX packages. Please see commands supported by MathJax:

- http://docs.mathjax.org/en/v2.7-latest/tex.html#supported-latex-commands
