### ISSUE TITLE
Synthaxic coloration problem in math modes in VS Code

### ISSUE THREAD

**Issue by louim-lbs** [James-Yu/LaTeX-Workshop#2627]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When typing with math enviromnent (\[ \] or \begin{displaymath}_\end{displaymath}, \begin{equation}_\end{equation} and even $$), the syntaxic colration is all blue/green or something strange: not correct regarding the normal coloration everywhere and particularly in correct math modes.

### To Reproduce

`In the $(O, \overrightarrow{y},\overrightarrow{z})$ plan, let's pose the vectors:

\[
    \overrightarrow{OA}=\binom{y_A}{z_A}\mbox{~;~}
    \overrightarrow{OA'}=\binom{y_A'}{z_A'}\mbox{~;~}
    \overrightarrow{OA''}=\binom{y_A''}{z_A''}
\]`

### Expected behavior

Classic coloration...

## Screenshots

![image](https://user-images.githubusercontent.com/82395416/115258402-40595d80-a131-11eb-8772-e024f611191c.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.55.2
 - Extension version: 8.16.1
 - TeX distribution version: MiKTeX 4.2
 

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
I am afraid everything is fine here. What do you mean by 

> the normal coloration [...] in correct math modes

**Comment by louim-lbs** [comment]
Is it normal that everything is green between the $$ or \[ \] ?

I'd expect coloration like the second line of displaymath in my screenshot. Different colors for every part, like the "\begin{array} \end{array}".

**Comment by louim-lbs** [comment]
![image](https://user-images.githubusercontent.com/82395416/115356856-595b2080-a1bc-11eb-8371-54ccfe799777.png)

WIth the math environment everything is fine, for me.

**Comment by jlelong** [comment]
The environments `math` and `displaymath` are not recognised as math code by the extension. Indeed, I have never used them myself. This explains the syntax highlighting differences.

Yet, there is something wrong in

<img width="408" alt="Capture d’écran 2021-04-20 à 17 24 06" src="https://user-images.githubusercontent.com/2910140/115422533-47e63880-a1fd-11eb-980c-357c50b7ea5e.png">

The highlighting of the code inside the array environment is wrong. The functions `\sin` and `\cos` should look like `\overrightarrow` whereas `\theta` should be in blue in my example. I will have a look at this.
