### ISSUE TITLE
Top of PDF file covered by toolbar

### ISSUE THREAD

**Issue by chrisyeh96** [James-Yu/LaTeX-Workshop#2632]
When I open the sidebar in the PDF viewer, the toolbar covers the top portion of the PDF file. Can the PDF viewer please be changed to shift the PDF file down by the height of the toolbar so that it is no longer covered? Thanks!

![image](https://user-images.githubusercontent.com/7686641/115621797-3ca21400-a2b4-11eb-840c-f7f888958420.png)

Steps to reproduce:
1. Find/create a PDF file that has no top margin.
2. Open the PDF in VSCode using the LaTeX Workshop extension.
3. Click the sidebar button (top left corner of PDF viewer)

## Desktop

 - OS: Windows 10 (20H2)
 - VS Code version: 1.53.2
 - Extension version: 8.17.0

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by chrisyeh96** [comment]
@tamuratak If this is out of the scope of the extension, who's scope is it in?

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
