### ISSUE TITLE
Preview PDF on first pdflatex pass

### ISSUE THREAD

**Issue by Nauhaie** [James-Yu/LaTeX-Workshop#2634]
Hi, it seems to me that PDF preview only updates once the whole compilation process is over, which can be quite long depending on the number of passes pdflatex & friends.

Would it possible to update the PDF Preview after every pass? I understand that, at times, this might result if wrong references showing up for a few seconds, but that is a very minor drawback IMHO.

I would gladly implement this as my own recipe, but I don't know how to trigger the PDF preview refresh from there...

Thanks a lot.

**Comment by tamuratak** [comment]
Please define a recipe for a quick preview and execute it.

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
