### ISSUE TITLE
Auto change environment begin/end when the other is edited

### ISSUE THREAD

**Issue by circumspect** [James-Yu/LaTeX-Workshop#2635]
Would it be possible to change the begin/end tags when the other is edited, similar to the [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) extension? For example, if I want to change an `equation` environment to `align`, I currently have to edit both of them manually.

**Comment by tamuratak** [comment]
Use `latex-workshop.select-envname`. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#navigating-and-selecting

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
