### ISSUE TITLE
How to view and synctex with Xchange Editor?

### ISSUE THREAD

**Issue by gxkkkkkk** [James-Yu/LaTeX-Workshop#2638]
I don't know if that's OK?
Wiki only has a way to configure SumatraPDF

**Comment by tamuratak** [comment]
We don't know nothing about Xchange Editor. Please ask at https://tex.stackexchange.com/.

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
