### ISSUE TITLE
LaTex toolchain terminated with error 

### ISSUE THREAD

**Issue by Dicridon** [James-Yu/LaTeX-Workshop#264]
### Description
Hi, I am a Chinese student learning LaTex using CTex, which is based on MikTex, and I found latex-workshop on VS code, so I installed it. However, when I was trying to build a latex project and check pdf file, I saw message "LaTex toolchain terminated with error" and no pdf file is generated. Actually, nothing was generated.
I searched for solution and noticed that my latexmk was not working, so I installed Perl and generated a pdf file successfully with latexmk  in command line, so latexmk works, but latex-workshop still reported "LaTex toolchain terminated with error.
I also tried your MikTex solution, it didn't work, either. But if I type texify main.tex --pdf, a pdf file would be generated. --synctex option is not available.

### How to reproduce

I am not sure if steps below would reproduce my problem, my operating system is Win10
1.  install CTex using packaged offered on its official site
2.  install activePerl
3. I didn't make any change to latex-workshop
4. start a project, and after saving, message "LaTex toolchain terminated with error"
5. I used a Emacs keymap extension in vscode
### Expected behavior
after saving, latex-workshop could build my project so I can check pdf file

### Actual behavior
report that "Latex toolchain terminated with error"

### Log messages
sorry I can not find log file, and in another issue you mentioned I can check output on output panel of vscode, unfortunately, my output panel is always empty, it seems that latex-workshop even didn't start any command

here is three screenshots for you, including my PATH variable
![first](https://user-images.githubusercontent.com/24477137/30117420-bd6a6f4e-9352-11e7-8e10-5c5c74c16b3d.png)
![second](https://user-images.githubusercontent.com/24477137/30117423-c2d06920-9352-11e7-8ca0-b1edc266bc39.png)
![third](https://user-images.githubusercontent.com/24477137/30117429-c7ebf9a6-9352-11e7-9e09-52111fe7e53f.png)

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Comment by James-Yu** [comment]
You may access the log from the output panel, but also select LaTeX Workshop from the dropdown menu on the right of the output panel. The log messages are critical to know what's the problem.

You may also check LaTeX compiler log. From your description I suppose it is a compiler problem instead of an extension one.

**Comment by Dicridon** [comment]
Sorry to say that I don't where is the output panel, do you mean the panel near terminal panel, or is there any short cut I can use to open output panel? 
Below is a screen shot of my settings and output from terminal in vscode, and if I type the command latexmk main.tex -pdf in terminal of vscode, the pdf file can not be generated
![default](https://user-images.githubusercontent.com/24477137/30120079-6dc4ecf0-935a-11e7-9381-def2069b83c1.png)
And below is my tex log file
This is pdfTeX, Version 3.1415926-2.3-1.40.12 (MiKTeX 2.9) (preloaded format=pdflatex 2017.9.6)  6 SEP 2017 23:17
entering extended mode
**main.tex
("D:\Courses\AI\homework template\main.tex"
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for loaded.
(D:\CTeX\MiKTeX\tex\latex\base\article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(D:\CTeX\MiKTeX\tex\latex\base\size10.clo
File: size10.clo 2007/10/19 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(D:\CTeX\MiKTeX\tex\latex\hyperref\hyperref.sty
Package: hyperref 2012/02/06 v6.82o Hypertext links for LaTeX

(D:\CTeX\MiKTeX\tex\generic\oberdiek\hobsub-hyperref.sty
Package: hobsub-hyperref 2011/04/23 v1.4 Bundle oberdiek, subset hyperref (HO)

(D:\CTeX\MiKTeX\tex\generic\oberdiek\hobsub-generic.sty
Package: hobsub-generic 2011/04/23 v1.4 Bundle oberdiek, subset generic (HO)
Package: hobsub 2011/04/23 v1.4 Subsetting bundle oberdiek (HO)
Package: infwarerr 2010/04/08 v1.3 Providing info/warning/message (HO)
Package: ltxcmds 2011/04/18 v1.20 LaTeX kernel commands for general use (HO)
Package: ifluatex 2010/03/01 v1.3 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
Package: ifvtex 2010/03/01 v1.5 Switches for detecting VTeX and its modes (HO)
Package ifvtex Info: VTeX not detected.
Package: intcalc 2007/09/27 v1.1 Expandable integer calculations (HO)
Package: ifpdf 2011/01/30 v2.3 Provides the ifpdf switch (HO)
Package ifpdf Info: pdfTeX in PDF mode is detected.
Package: etexcmds 2011/02/16 v1.5 Prefix for e-TeX command names (HO)
Package etexcmds Info: Could not find \expanded.
(etexcmds)             That can mean that you are not using pdfTeX 1.50 or
(etexcmds)             that some package has redefined \expanded.
(etexcmds)             In the latter case, load this package earlier.
Package: kvsetkeys 2011/04/07 v1.13 Key value parser (HO)
Package: kvdefinekeys 2011/04/07 v1.3 Defining keys (HO)
Package: pdftexcmds 2011/04/22 v0.16 Utilities of pdfTeX for LuaTeX (HO)
Package pdftexcmds Info: LuaTeX not detected.
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode found.
Package: pdfescape 2011/04/04 v1.12 Provides string conversions (HO)
Package: bigintcalc 2011/01/30 v1.2 Expandable big integer calculations (HO)
Package: bitset 2011/01/30 v1.1 Data type bit set (HO)
Package: uniquecounter 2011/01/30 v1.2 Provides unlimited unique counter (HO)
)
Package hobsub Info: Skipping package `hobsub' (already loaded).
Package: letltxmacro 2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
Package: hopatch 2011/01/30 v1.0 Wrapper for package hooks (HO)
Package: xcolor-patch 2011/01/30 xcolor patch
Package: atveryend 2011/04/23 v1.7 Hooks at very end of document (HO)
Package: atbegshi 2011/01/30 v1.15 At begin shipout hook (HO)
Package: refcount 2010/12/01 v3.2 Data extraction from references (HO)
Package: hycolor 2011/01/30 v1.7 Color options of hyperref/bookmark (HO)
)
(D:\CTeX\MiKTeX\tex\latex\graphics\keyval.sty
Package: keyval 1999/03/16 v1.13 key=value parser (DPC)
\KV@toks@=\toks14
)
(D:\CTeX\MiKTeX\tex\generic\ifxetex\ifxetex.sty
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
)
(D:\CTeX\MiKTeX\tex\latex\oberdiek\kvoptions.sty
Package: kvoptions 2010/12/23 v3.10 Keyval support for LaTeX options (HO)
)
\@linkdim=\dimen103
\Hy@linkcounter=\count87
\Hy@pagecounter=\count88

(D:\CTeX\MiKTeX\tex\latex\hyperref\pd1enc.def
File: pd1enc.def 2012/02/06 v6.82o Hyperref: PDFDocEncoding definition (HO)
)
\Hy@SavedSpaceFactor=\count89

(D:\CTeX\MiKTeX\tex\latex\00miktex\hyperref.cfg
File: hyperref.cfg 2002/06/06 v1.2 hyperref configuration of TeXLive
)
Package hyperref Info: Hyper figures OFF on input line 4046.
Package hyperref Info: Link nesting OFF on input line 4051.
Package hyperref Info: Hyper index ON on input line 4054.
Package hyperref Info: Plain pages OFF on input line 4061.
Package hyperref Info: Backreferencing OFF on input line 4066.
Package hyperref Info: Implicit mode ON; LaTeX internals redefined.
Package hyperref Info: Bookmarks ON on input line 4284.
\c@Hy@tempcnt=\count90

(D:\CTeX\MiKTeX\tex\latex\ltxmisc\url.sty
\Urlmuskip=\muskip10
Package: url 2006/04/12  ver 3.3  Verb mode for urls, etc.
)
LaTeX Info: Redefining \url on input line 4637.
\Fld@menulength=\count91
\Field@Width=\dimen104
\Fld@charsize=\dimen105
Package hyperref Info: Hyper figures OFF on input line 5757.
Package hyperref Info: Link nesting OFF on input line 5762.
Package hyperref Info: Hyper index ON on input line 5765.
Package hyperref Info: backreferencing OFF on input line 5772.
Package hyperref Info: Link coloring OFF on input line 5777.
Package hyperref Info: Link coloring with OCG OFF on input line 5782.
Package hyperref Info: PDF/A mode OFF on input line 5787.
LaTeX Info: Redefining \ref on input line 5827.
LaTeX Info: Redefining \pageref on input line 5831.
\Hy@abspage=\count92
\c@Item=\count93
\c@Hfootnote=\count94
)

Package hyperref Message: Driver (autodetected): hpdftex.

(D:\CTeX\MiKTeX\tex\latex\hyperref\hpdftex.def
File: hpdftex.def 2012/02/06 v6.82o Hyperref driver for pdfTeX
\Fld@listcount=\count95
\c@bookmark@seq@number=\count96

(D:\CTeX\MiKTeX\tex\latex\oberdiek\rerunfilecheck.sty
Package: rerunfilecheck 2011/04/15 v1.7 Rerun checks for auxiliary files (HO)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
82.
)
\Hy@SectionHShift=\skip43
)
(D:\CTeX\MiKTeX\tex\latex\graphics\graphicx.sty
Package: graphicx 1999/02/16 v1.0f Enhanced LaTeX Graphics (DPC,SPQR)

(D:\CTeX\MiKTeX\tex\latex\graphics\graphics.sty
Package: graphics 2009/02/05 v1.0o Standard LaTeX Graphics (DPC,SPQR)

(D:\CTeX\MiKTeX\tex\latex\graphics\trig.sty
Package: trig 1999/03/16 v1.09 sin cos tan (DPC)
)
(D:\CTeX\MiKTeX\tex\latex\00miktex\graphics.cfg
File: graphics.cfg 2007/01/18 v1.5 graphics configuration of teTeX/TeXLive
)
Package graphics Info: Driver file: pdftex.def on input line 91.

(D:\CTeX\MiKTeX\tex\latex\pdftex-def\pdftex.def
File: pdftex.def 2011/05/27 v0.06d Graphics/color for pdfTeX
\Gread@gobject=\count97
))
\Gin@req@height=\dimen106
\Gin@req@width=\dimen107
)
(D:\CTeX\MiKTeX\tex\latex\ams\math\amsmath.sty
Package: amsmath 2000/07/18 v2.13 AMS math features
\@mathmargin=\skip44

For additional information on amsmath, use the `?' option.
(D:\CTeX\MiKTeX\tex\latex\ams\math\amstext.sty
Package: amstext 2000/06/29 v2.01

(D:\CTeX\MiKTeX\tex\latex\ams\math\amsgen.sty
File: amsgen.sty 1999/11/30 v2.0
\@emptytoks=\toks15
\ex@=\dimen108
))
(D:\CTeX\MiKTeX\tex\latex\ams\math\amsbsy.sty
Package: amsbsy 1999/11/29 v1.2d
\pmbraise@=\dimen109
)
(D:\CTeX\MiKTeX\tex\latex\ams\math\amsopn.sty
Package: amsopn 1999/12/14 v2.01 operator names
)
\inf@bad=\count98
LaTeX Info: Redefining \frac on input line 211.
\uproot@=\count99
\leftroot@=\count100
LaTeX Info: Redefining \overline on input line 307.
\classnum@=\count101
\DOTSCASE@=\count102
LaTeX Info: Redefining \ldots on input line 379.
LaTeX Info: Redefining \dots on input line 382.
LaTeX Info: Redefining \cdots on input line 467.
\Mathstrutbox@=\box26
\strutbox@=\box27
\big@size=\dimen110
LaTeX Font Info:    Redeclaring font encoding OML on input line 567.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 568.
\macc@depth=\count103
\c@MaxMatrixCols=\count104
\dotsspace@=\muskip11
\c@parentequation=\count105
\dspbrk@lvl=\count106
\tag@help=\toks16
\row@=\count107
\column@=\count108
\maxfields@=\count109
\andhelp@=\toks17
\eqnshift@=\dimen111
\alignsep@=\dimen112
\tagshift@=\dimen113
\tagwidth@=\dimen114
\totwidth@=\dimen115
\lineht@=\dimen116
\@envbody=\toks18
\multlinegap=\skip45
\multlinetaggap=\skip46
\mathdisplay@stack=\toks19
LaTeX Info: Redefining \[ on input line 2666.
LaTeX Info: Redefining \] on input line 2667.
)
(D:\CTeX\MiKTeX\tex\latex\amsfonts\amssymb.sty
Package: amssymb 2009/06/22 v3.00

(D:\CTeX\MiKTeX\tex\latex\amsfonts\amsfonts.sty
Package: amsfonts 2009/06/22 v3.00 Basic AMSFonts support
\symAMSa=\mathgroup4
\symAMSb=\mathgroup5
LaTeX Font Info:    Overwriting math alphabet `\mathfrak' in version `bold'
(Font)                  U/euf/m/n --> U/euf/b/n on input line 96.
))
(D:\CTeX\MiKTeX\tex\latex\algorithms\algorithm.sty
Package: algorithm 2009/08/24 v0.1 Document Style `algorithm' - floating enviro
nment

(D:\CTeX\MiKTeX\tex\latex\float\float.sty
Package: float 2001/11/08 v1.3d Float enhancements (AL)
\c@float@type=\count110
\float@exts=\toks20
\float@box=\box28
\@float@everytoks=\toks21
\@floatcapt=\box29
)
(D:\CTeX\MiKTeX\tex\latex\base\ifthen.sty
Package: ifthen 2001/05/26 v1.1c Standard LaTeX ifthen package (DPC)
)
\@float@every@algorithm=\toks22
\c@algorithm=\count111
)
(D:\CTeX\MiKTeX\tex\latex\algorithms\algorithmic.sty
Package: algorithmic 2009/08/24 v0.1 Document Style `algorithmic'
\c@ALC@unique=\count112
\c@ALC@line=\count113
\c@ALC@rem=\count114
\c@ALC@depth=\count115
\ALC@tlm=\skip47
\algorithmicindent=\skip48
)
(D:\CTeX\MiKTeX\tex\latex\base\textcomp.sty
Package: textcomp 2005/09/27 v1.99g Standard LaTeX package
Package textcomp Info: Sub-encoding information:
(textcomp)               5 = only ISO-Adobe without \textcurrency
(textcomp)               4 = 5 + \texteuro
(textcomp)               3 = 4 + \textohm
(textcomp)               2 = 3 + \textestimated + \textcurrency
(textcomp)               1 = TS1 - \textcircled - \t
(textcomp)               0 = TS1 (full)
(textcomp)             Font families with sub-encoding setting implement
(textcomp)             only a restricted character set as indicated.
(textcomp)             Family '?' is the default used for unknown fonts.
(textcomp)             See the documentation for details.
Package textcomp Info: Setting ? sub-encoding to TS1/1 on input line 71.

(D:\CTeX\MiKTeX\tex\latex\base\ts1enc.def
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
)
LaTeX Info: Redefining \oldstylenums on input line 266.
Package textcomp Info: Setting cmr sub-encoding to TS1/0 on input line 281.
Package textcomp Info: Setting cmss sub-encoding to TS1/0 on input line 282.
Package textcomp Info: Setting cmtt sub-encoding to TS1/0 on input line 283.
Package textcomp Info: Setting cmvtt sub-encoding to TS1/0 on input line 284.
Package textcomp Info: Setting cmbr sub-encoding to TS1/0 on input line 285.
Package textcomp Info: Setting cmtl sub-encoding to TS1/0 on input line 286.
Package textcomp Info: Setting ccr sub-encoding to TS1/0 on input line 287.
Package textcomp Info: Setting ptm sub-encoding to TS1/4 on input line 288.
Package textcomp Info: Setting pcr sub-encoding to TS1/4 on input line 289.
Package textcomp Info: Setting phv sub-encoding to TS1/4 on input line 290.
Package textcomp Info: Setting ppl sub-encoding to TS1/3 on input line 291.
Package textcomp Info: Setting pag sub-encoding to TS1/4 on input line 292.
Package textcomp Info: Setting pbk sub-encoding to TS1/4 on input line 293.
Package textcomp Info: Setting pnc sub-encoding to TS1/4 on input line 294.
Package textcomp Info: Setting pzc sub-encoding to TS1/4 on input line 295.
Package textcomp Info: Setting bch sub-encoding to TS1/4 on input line 296.
Package textcomp Info: Setting put sub-encoding to TS1/5 on input line 297.
Package textcomp Info: Setting uag sub-encoding to TS1/5 on input line 298.
Package textcomp Info: Setting ugq sub-encoding to TS1/5 on input line 299.
Package textcomp Info: Setting ul8 sub-encoding to TS1/4 on input line 300.
Package textcomp Info: Setting ul9 sub-encoding to TS1/4 on input line 301.
Package textcomp Info: Setting augie sub-encoding to TS1/5 on input line 302.
Package textcomp Info: Setting dayrom sub-encoding to TS1/3 on input line 303.
Package textcomp Info: Setting dayroms sub-encoding to TS1/3 on input line 304.

Package textcomp Info: Setting pxr sub-encoding to TS1/0 on input line 305.
Package textcomp Info: Setting pxss sub-encoding to TS1/0 on input line 306.
Package textcomp Info: Setting pxtt sub-encoding to TS1/0 on input line 307.
Package textcomp Info: Setting txr sub-encoding to TS1/0 on input line 308.
Package textcomp Info: Setting txss sub-encoding to TS1/0 on input line 309.
Package textcomp Info: Setting txtt sub-encoding to TS1/0 on input line 310.
Package textcomp Info: Setting lmr sub-encoding to TS1/0 on input line 311.
Package textcomp Info: Setting lmdh sub-encoding to TS1/0 on input line 312.
Package textcomp Info: Setting lmss sub-encoding to TS1/0 on input line 313.
Package textcomp Info: Setting lmssq sub-encoding to TS1/0 on input line 314.
Package textcomp Info: Setting lmvtt sub-encoding to TS1/0 on input line 315.
Package textcomp Info: Setting qhv sub-encoding to TS1/0 on input line 316.
Package textcomp Info: Setting qag sub-encoding to TS1/0 on input line 317.
Package textcomp Info: Setting qbk sub-encoding to TS1/0 on input line 318.
Package textcomp Info: Setting qcr sub-encoding to TS1/0 on input line 319.
Package textcomp Info: Setting qcs sub-encoding to TS1/0 on input line 320.
Package textcomp Info: Setting qpl sub-encoding to TS1/0 on input line 321.
Package textcomp Info: Setting qtm sub-encoding to TS1/0 on input line 322.
Package textcomp Info: Setting qzc sub-encoding to TS1/0 on input line 323.
Package textcomp Info: Setting qhvc sub-encoding to TS1/0 on input line 324.
Package textcomp Info: Setting futs sub-encoding to TS1/4 on input line 325.
Package textcomp Info: Setting futx sub-encoding to TS1/4 on input line 326.
Package textcomp Info: Setting futj sub-encoding to TS1/4 on input line 327.
Package textcomp Info: Setting hlh sub-encoding to TS1/3 on input line 328.
Package textcomp Info: Setting hls sub-encoding to TS1/3 on input line 329.
Package textcomp Info: Setting hlst sub-encoding to TS1/3 on input line 330.
Package textcomp Info: Setting hlct sub-encoding to TS1/5 on input line 331.
Package textcomp Info: Setting hlx sub-encoding to TS1/5 on input line 332.
Package textcomp Info: Setting hlce sub-encoding to TS1/5 on input line 333.
Package textcomp Info: Setting hlcn sub-encoding to TS1/5 on input line 334.
Package textcomp Info: Setting hlcw sub-encoding to TS1/5 on input line 335.
Package textcomp Info: Setting hlcf sub-encoding to TS1/5 on input line 336.
Package textcomp Info: Setting pplx sub-encoding to TS1/3 on input line 337.
Package textcomp Info: Setting pplj sub-encoding to TS1/3 on input line 338.
Package textcomp Info: Setting ptmx sub-encoding to TS1/4 on input line 339.
Package textcomp Info: Setting ptmj sub-encoding to TS1/4 on input line 340.
)
(D:\CTeX\MiKTeX\tex\latex\geometry\geometry.sty
Package: geometry 2010/09/12 v5.6 Page Geometry
\Gm@cnth=\count116
\Gm@cntv=\count117
\c@Gm@tempcnt=\count118
\Gm@bindingoffset=\dimen117
\Gm@wd@mp=\dimen118
\Gm@odd@mp=\dimen119
\Gm@even@mp=\dimen120
\Gm@layoutwidth=\dimen121
\Gm@layoutheight=\dimen122
\Gm@layouthoffset=\dimen123
\Gm@layoutvoffset=\dimen124
\Gm@dimlist=\toks23

(D:\CTeX\MiKTeX\tex\latex\geometry\geometry.cfg))
\c@theorem=\count119
\c@proof=\count120

("D:\Courses\AI\homework template\main.aux")
LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for PD1/pdf/m/n on input line 26.
LaTeX Font Info:    ... okay on input line 26.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 26.
LaTeX Font Info:    Try loading font information for TS1+cmr on input line 26.

(D:\CTeX\MiKTeX\tex\latex\base\ts1cmr.fd
File: ts1cmr.fd 1999/05/25 v2.5h S

**Comment by James-Yu** [comment]
It’s 输出

Sent from Mail for Windows 10

**Comment by Dicridon** [comment]
well, nothing can be found, I've saved several times, but the output panel is still empty
![default](https://user-images.githubusercontent.com/24477137/30120564-cd150d88-935b-11e7-882a-b1ee3622dfd6.png)

**Comment by James-Yu** [comment]
And select LaTeX Workshop from the dropdown menu showing 任务

Sent from Mail for Windows 10

**Comment by Dicridon** [comment]
Maybe this is the problem, in task menu, there is no LaTex Workshop
![default](https://user-images.githubusercontent.com/24477137/30120920-c7f7b002-935c-11e7-8b95-6377bf72a763.png)

**Comment by James-Yu** [comment]
Please.
![30120564-cd150d88-935b-11e7-882a-b1ee3622dfd6](https://user-images.githubusercontent.com/4210342/30121099-4dfd3f00-935d-11e7-8c91-12aaa1391176.png)

**Comment by Dicridon** [comment]
I am so sorry wasting you so much time teaching me to use this
![default](https://user-images.githubusercontent.com/24477137/30121221-b224fba8-935d-11e7-885e-dc1273070c19.png)

**Comment by James-Yu** [comment]
You are using the wrong `texify` command. Please read README and pay special attention to file extension `.tex`.  For other `texify`-related problems, you may refer to https://docs.miktex.org/manual/texify.html .

**Comment by Dicridon** [comment]
well, my problem is solved, 
I switched to latexmk again, 
at frist it didn't work, so I try the command with arguments given in the setting file, error occured, so I deleted some arguments, now it works~
Thank you so much, you saved me
![default](https://user-images.githubusercontent.com/24477137/30121770-237be25c-935f-11e7-9615-65ae3d89089b.png)
