### ISSUE TITLE
Magic comment to define recipe per file

### ISSUE THREAD

**Issue by mopication** [James-Yu/LaTeX-Workshop#2642]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature related to a problem? Please describe. [Required]

I wouldn't exactly call it a problem, but I'm often finding myself drawing tikz-figures in a second document without any nomenclatures, bibfiles, external build commands, etc. 
Now, the build recipe (pdflatex, makeindex, pdflatex, biber, pdflatex, pdflatex) i usually use fails because of this, so I manually click on a recipe containing only pdflatex. After that i can build on save with the lastUsed recipe.
When I'm happy with my drawing, I copy the code back into my main document, compile and get loads of warnings, because I'm only building with pdflatex once, so I manually have to click on my default recipe, which I'd like not to do.

Can I already use the `% !TEX program = ...` magic comment for this? If not, please read on ;)

## To Reproduce  [Required]

1. Set default recipe to "lastUsed"
2. Build a document with one recipe
3. Build another document with another recipe
4. Build the first document with the first recipe again

## Describe the solution you'd like  [Required]

I was thinking of some magic comment defining the recipe to use for this file.
Something like this:
`% !recipe = pdflatex ➞ makeindex ➞ pdflatex ➞ biber ➞ pdflatex × 2`
or
`% !recipe = first`

Or maybe introduce numbers/some kind of unique identifier other than the name for the recipes, so you can write
`% !recipe = 2`

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.55.2
 - Extension version: 8.17.0
 - TeX distribution version: (TeX Live 2020/W32TeX)

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Defining a recipe per file is out the scope of the extension. There are very powerful tools to automates  the process of compiling a LaTeX document and we believe that they should be used instead.


For instance, use `latexmk`. It will find out which commands (`pdflatex`, `makeindex`, `bibtex`, `biber`, ...) to run to properly compile your files.
