### ISSUE TITLE
Automated snippet extension

### ISSUE THREAD

**Issue by tknuth** [James-Yu/LaTeX-Workshop#2644]
I noticed that, for certain environments like itemize, additional `\item` are added when pressing enter.

```
    \begin{itemize}
        \item some text
        \item % appears automatically
    \end{itemize}
```

I have been unable to find this in the source code and it seems not to be a feature of VSCode's snippet engine.

Would you be so kind to point me to the right source so I can build this automatism into my own snippets and possibly contribute them?

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/blob/7ac1fc39af47c62095c3a6877eecd258025732cb/src/commander.ts#L418

Notice that we will not accept contributions on this feature because it is complicated.
