### ISSUE TITLE
Language Server Protocol support

### ISSUE THREAD

**Issue by fwcd** [James-Yu/LaTeX-Workshop#2647]
First of all, thanks for this extension, it makes editing LaTeX in VSCode a breeze!

Since other editors could potentially benefit from good LaTeX support, would it be possible to extract the completion/linting functionality into a language server?

VSCode offers very good support for language servers, also there are official server/client libraries for LSP, making the transition from using VSCode's APIs directly to LSP quite seamless. Of course, things like tool panels and PDF previews would still have to be implemented on the client-side, however having the 'common' logic in a language server would make it easy to e.g. have code completion and linting in editors like other editors like Vim, Emacs or Atom, with little effort.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
