### ISSUE TITLE
Create an option for traditional keybindings from other editors

### ISSUE THREAD

**Issue by meneguzzi** [James-Yu/LaTeX-Workshop#2648]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

I am switching from TextMate (and other editors) which have keybindings akin to what one would use in a regular text editor (e.g. ctrl+i for italics/emph, ctrl+b for bold/textbf, etc), and I'm frustrated with the complicated multi-step default keybindings from the extension. 

## To Reproduce  [Required]

1. Go to 'editor'
2. Select a desired piece of text
3. Try to make it italic

## Describe the solution you'd like  [Required]

So my suggestion would be to get sets of keybindings from popular alternatives (e.g. Textmate, TeXShop, etc) and create a dropdown option to set them in bulk. Bonus points if such sets of keybindings could be saved (but this might already be a feature in VSCode). 

I understand this might be related to issue #2470, however, that issue just mentioned the existence of keybindings at all, which I well understand are there, but I refer to being able to redefine such keybindings to match existing workflows. 

## Logs [Required]

N/A

### LaTeX Workshop Output [Required]

N/A

### Developer Tools Console [Required]

N/A

## Screenshots

N/A

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: MacOS 10.15.7
 - VS Code version: 1.55.2
 - Extension version: 10.1.0
 - TeX distribution version: TeX Live 2021

### Are you using VSCodium?

Yes/No

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment]
Out of the scope of the extension.

See https://code.visualstudio.com/docs/getstarted/keybindings
