### ISSUE TITLE
Stop supporting the progress bar and the build info panel.

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2652]
The current progress bar is problematic. See https://github.com/James-Yu/LaTeX-Workshop/issues/2646#issuecomment-829220014.

It is also not easy to maintain the code. We had better remove the progress bar and the build info panel.

@jlelong  What do you think?

**Comment by jlelong** [comment]
I have never be in favour of this feature. It is not really useful. Considering the amount of code it requires and the side effects it can induce, i am perfectly fine with removing this feature or at least deactivating per default.
