### ISSUE TITLE
"Previewing equations" does not work if the command `\newcommandtwoopt` from the package `twoopt` is used.

### ISSUE THREAD

**Issue by MrWhiteRichard** [James-Yu/LaTeX-Workshop#2658]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue.

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug

[Previewing equations](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#previewing-equations) does not work if the command `\newcommandtwoopt` from the package `twoopt` is used.

### To Reproduce

Create a `\newcommandtwoopt` and see for yourself.

### Expected behavior

I would have expected the [Previewing equations](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#previewing-equations) to work as it would have without `\newcommandtwoopt`.

## Desktop

 - OS: Windows 10
 - VS Code version: 1.55.2
 - Extension version: 8.17.0
 - TeX distribution version: MiKTeX-pdfTeX 4.6 (MiKTeX 21.3)

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

**Comment by jlelong** [comment]
We implement hover preview with MathJax. MathJax does not support LaTeX packages. Please see commands supported by MathJax: http://docs.mathjax.org/en/v2.7-latest/tex.html#supported-latex-commands

**Comment by MrWhiteRichard** [comment]
Interestingly, commands created with `\NewDocumentCommand` from the package `xparse` do not stop the preview from rendering. Unfortunately however, it does not render the part of the equation, where a command defined via `\NewDocumentCommand` is used, properly. The rest seems to be showing up without an issue.

**Comment by jlelong** [comment]
This is because our regex to find new commands is not selective enough

https://github.com/James-Yu/LaTeX-Workshop/blob/7d6fac11a846417c69f37504d7df6b79625d13fa/src/providers/preview/mathpreviewlib/newcommandfinder.ts#L83

Instead, we should use 

```js
/((re)?new|provide)command(\\*)?$|DeclareMathOperator(\\*)?$/
```

**Comment by tamuratak** [comment]
> /((re)?new|provide)command(\\*)?$|DeclareMathOperator(\\*)?$/

It is not easy to understand the regexp. We had better use a regexp joining all the commands with `|`.
