### ISSUE TITLE
Interactive compiler

### ISSUE THREAD

**Issue by tjustel** [James-Yu/LaTeX-Workshop#2660]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature related to a problem? Please describe. [Required]

The default latex compiler behavior (outside vscode) is to stop when an error occurs and prompt the user, which is a desirable behavior for debugging, especially in large projects. It is not possible to use this functionnality with this extension since any compiler prompt appears in the extension output, that is read only. 

## To Reproduce  [Required]

1. Create a recipe in latex-workshop.latex.tools using an interactive compiler, e.g. 
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-file-line-error",
                "%DOC%"
            ],
            "env": {}
        }.
2. Create a .tex file with an error.
3. Compile this file using your recipe.
4. The compiler stops encountering the first error and prompt the user for the behavior to adopt. 
5. It is impossible for the user to answer the prompt ("Cannot edit in the read only editor").

## Describe the solution you'd like  [Required]

Latex compilation occurs in an interactive terminal (which allow the user to answer compiler prompts).
If user answers "E" to the prompt ("edit file" option) the corresponding .tex file should be opened in vscode editor.

## Screenshots

![unable_to_answer_latex_compiler_prompt](https://user-images.githubusercontent.com/34620135/117202379-07d2a880-adee-11eb-9933-26a80ad8c8ba.png)

## Desktop [Required]

 - OS: Linux 4.15.0-142-generic
 - VS Code version: 1.55.2
 - Extension version: 8.17.0
 - TeX distribution version: MiKTeX-pdfTeX 4.6 (MiKTeX 21.3)

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by tjustel** [comment]
Why is it out of the scope ? In my opinion the possibility to answer this kind of compiler prompt is essential for debugging...
Isn't it possible to run the command used by the extension in a terminal inside the IDE instead of launching it in the background ?
