### ISSUE TITLE
PDF Background Transparency

### ISSUE THREAD

**Issue by sambilbow** [James-Yu/LaTeX-Workshop#2663]
Hello! It would it be possible to add PDF background transparency so that it was the colour of the workspace theme's background? I have been using invert + tuning brightness + sepia to match it closely, but if you change colour themes often (light/dark mode) this takes a lot of time.

I can see that you have the option for the background around the document that is an HTML colour hex. As an aside, would it be possible for this to contain an alpha channel too? i.e. #00xxxxxx creates a transparent border showing the workspace background colour.

My main feature request is the PDF background colour though.

Understand if its way too much work or not at all possible. :)

I'm currently using the vibrancy extension that allows workspace transparency.

![Screenshot 2021-05-06 at 20 08 37](https://user-images.githubusercontent.com/31018239/117352391-dcf85b00-aea6-11eb-907d-1d4465a77ae8.png)

**Comment by tamuratak** [comment]
Out of the scope of the extension.
