### ISSUE TITLE
Support invoking XeTeX

### ISSUE THREAD

**Issue by artagnon** [James-Yu/LaTeX-Workshop#2670]
latex-workshop currently runs `pdflatex`, and for certain packages like `fontspec`, the `xetex` engine must be run instead.

**Comment by tamuratak** [comment]
Please define a recipe. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
