### ISSUE TITLE
LaTeX Workshop doesn't ignore verbatim in external files

### ISSUE THREAD

**Issue by hellmrf** [James-Yu/LaTeX-Workshop#2671]
I have a main file that `\include`s some chapters from another folder. When I save these chapter files with just some text, everything works well and `main.tex` is recompiled. However, if I have a verbatim in these chapters with the `\begin{document}` content, LaTeX Workshop thinks that it's a real file and tries to compile, generating many aux files and an annoying warning.

## Minimum, Complete and Verifiable Example: 

Suppose the following directory structure:
```plain
.
├─ chapters
│   └─ introduction.tex
└─ main.tex
```

`main.tex` has:
```latex
\documentclass{article}

\begin{document}
    \include{./chapters/introduction.tex}
\end{document}
```

And `chapters/introduction.tex` has:
```latex
\section{Introduction}

This is a minimum \LaTeX\ document:

\begin{verbatim}
    \documentclass{article}

    \begin{document}
        Hello World!
    \end{document}
\end{verbatim}
```

If you save `chapters/introduction.tex` in VSCode, LaTeX Workshop will trigger the compilation recipe, generate a bunch of files and error out because, obviously, it's not a valid LaTeX file.

**Comment by jlelong** [comment]
This issue comes from  https://github.com/James-Yu/LaTeX-Workshop/blob/9c289b058ee48d51ecfc6210d20b5a1c9ae4b159/src/components/manager.ts#L286-L291

We should be using `utils.stripCommentsAndVerbatim`. The same holds for the function `findRootInWorkspace`.

@tamuratak I have a question concerning `getDirtyContent`. In `this.cachedContent[file] = {content: fileContent, element: {}, children: [], bibs: []}`, do we need to keep the `verbatim` parts in `fileContent`?

**Comment by tamuratak** [comment]
I think we don't need the `content` property. We can read the content from the disk if we need. We can remove the property. We can also remove the `getContent` method.

https://github.com/James-Yu/LaTeX-Workshop/blob/7467c884f116fffa11e2e60d427607dee46217ab/src/components/manager.ts#L470-L477

**Comment by hellmrf** [comment]
I noticed two related things. 

- First, the file should be ignored unconditionally when it starts with `% !TeX root = `, it containing a `\begin{document}` or not. In that case, the user is explicitly saying this *is not* the root file.
- `utils.stripCommentsAndVerbatim` only takes care of `verbatim` environment and `\verb` macro, but it should be customizable, like [latexindent.pl does](https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html?highlight=verbatim#lst-verbatimenvironments). I think at least these should be considered verbatim environments by default:
  - verbatim
  - lstlisting
  - minted

If you give me some advice, maybe I can work on it.

**Comment by tamuratak** [comment]
@jlelong  It would be good to add a test to `./test/fixtures/build` for this issue.

**Comment by jlelong** [comment]
Done in 1cacd62
