### ISSUE TITLE
Smaller Package / Minify?

### ISSUE THREAD

**Issue by chrisyeh96** [James-Yu/LaTeX-Workshop#2683]
A fresh install of this extension uses ~40MB of disk space. To me, this seems like a lot of space, and I hope that this extension can be packaged to use less space.

Most of the space usage comes from the `node_modules` directory (~30MB), and a spot-check through that folder suggests that most of the space is coming from JavaScript text files, many of which are not minified. Is there any way of minifying most of these files when publishing this extension?

Perhaps there are other ways to reduce the size of this extension as well?

**Comment by tamuratak** [comment]
Out of the scope of the extension.
