### ISSUE TITLE
keyboard shortcuts for non-default recipes

### ISSUE THREAD

**Issue by jonas-frey** [James-Yu/LaTeX-Workshop#2684]
To speed up compilation on save, I created a tool & recipe running `pdflatex` only once following [this](https://tex.stackexchange.com/questions/478865/vs-code-latex-workshop-custom-recipes-file-location), and set the recipe as default.

Now I want to add a keyboard shortcut to run the full `latexmk` . However, this doesn't seem to be possible through the `keyboard shortcuts` view in vscode, and asking [here](https://stackoverflow.com/questions/66556901/how-to-create-compilation-shortcut-in-vscode-latex-workshop) didn't yield an answer. 

Is it possible to create keyboard shortcuts for non-default build tools or recipes? If now, I would suggest to add that as a feature.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/issues/2577#issuecomment-797383801

**Comment by jonas-frey** [comment]
Thanks a lot!
