### ISSUE TITLE
`\include{filename}` cannot include the extension `.tex` in the filename

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2687]
`\include{filename}` cannot include the extension `.tex` in the filename.

- https://www.overleaf.com/learn/latex/Management_in_a_large_project#Inputting_and_including_files
- https://en.wikibooks.org/wiki/LaTeX/Modular_Documents#Comparing_the_methods:_input_vs_include

https://github.com/James-Yu/LaTeX-Workshop/blob/5bee29b7651508d7beb440ab7bbb6be77aaed460/test/fixtures/build/fixture011/main.tex#L1-L6

**Comment by jlelong** [comment]
Thanks for taking care of this.
