### ISSUE TITLE
Refactoring `Manager.fsWatcher` and `Manager.filesWatched`

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2688]
@jlelong I have a question. Why do we define `Manager.filesWatched` while `Manager.fsWatcher.getWatched()` available?

https://github.com/James-Yu/LaTeX-Workshop/blob/cee520f54793574557b8667a67fef7e999a0ff95/src/components/manager.ts#L90-L96

- https://github.com/paulmillr/chokidar#methods--events

Since the `getWatched` method is async, I am not sure it could fix our need. 

- paulmillr/chokidar/issues/1075

**Comment by jlelong** [comment]
This is a good question. 

Since  `add` is asynchronous, if we do not maintain our own list, it could happen that we call `add` twice with the same file. Moreover, the object returned by `getWatched` is not so straightforward to use

> The object's keys are all the directories (using absolute paths unless the cwd option was used), and the values are arrays of the names of the items contained in each directory.

I was tempted to use `.on('add', ...)` to avoid calling 

```js
this.fileWatcher.add(file)
this.filesWatched.push(file)
```

every time, but because `.add` is async I do not think it would work.

**Comment by tamuratak** [comment]
Please notice that we should always care about data consistency. `fileWatcher.getWatched()` and `filesWatched` can be inconsistent without careful treatment.

For example, after  #2689 merged, while the following lines is being executed,

```ts
await this.fileWatcher.close()
this.filesWatched = []
```

the following lines can be called.

```ts
this.fileWatcher.add(file)
this.filesWatched.push(file)
```
 
The execution order can be 

```ts
await this.fileWatcher.close()
this.fileWatcher.add(file)
this.filesWatched.push(file)
this.filesWatched = []
```

because we await `this.fileWatcher.close()`. Then, data inconsistency occurs.

**Comment by tamuratak** [comment]
> it could happen that we call add twice with the same file.

When we call add twice with the same file, can any problem occur? With a test script, I see the only one event is emitted.

**Comment by tamuratak** [comment]
>  it could happen that we call add twice with the same file.

Even if we call `add` twice with the same file, it seems that `chokidar` can handle it appropriately. 

```js
  // if the file is already being watched, do nothing
  if (parent.has(basename)) return;
```

https://github.com/paulmillr/chokidar/blob/1d226cbfa50292e122043ceb3c1f4c34a5acd16e/lib/nodefs-handler.js#L356-L359

**Comment by jlelong** [comment]
As double addition is properly handled by `chokidar` and based on https://github.com/James-Yu/LaTeX-Workshop/blob/d19c60b8c04c0bf03683000a2299d7fa5bdba006/src/components/manager.ts#L771, we could add `
this.filesWatched.push(file)` directly to  https://github.com/James-Yu/LaTeX-Workshop/blob/d19c60b8c04c0bf03683000a2299d7fa5bdba006/src/components/manager.ts#L789


With #2689, there would be no data inconsistency while calling 

```js
await this.resetFileWatcher()
this.createFileWatcher()
```

Maybe, we could move 

```js
fileWatcher?: chokidar.FSWatcher
filesWatched: string[]
```

to a subclass to prevent direct access to the `chokidar.FSWatcher`. It would only have the following public methods

```js
initiateFileWatcher
resetFileWatcher
getWatchedFiles
```

**Comment by jlelong** [comment]
Indeed, this is what is already done for [`BibWatcher`](https://github.com/James-Yu/LaTeX-Workshop/blob/45ddb078dca0d3ea71ff204c28447a994a252b18/src/components/managerlib/bibwatcher.ts).

**Comment by tamuratak** [comment]
Close with  #2723
