### ISSUE TITLE
Why is clean up no longer able to remove folders?

### ISSUE THREAD

**Issue by Cube707** [James-Yu/LaTeX-Workshop#2690]
## Preliminary questions [Required]
I have LaTex system set up to produce all auxiliary files in a subfolder called `.aux/`. Untill V8.18.0 I was able to remove the folder with all it's content by simply defining `.aux/**` inside `latex-workshop.latex.clean.fileTypes`. The nice thing about this was, that one could only remove files and leave the folder by using `.aux/*`.  
This is no longer possible and the folder will not be removed with the message: `Not removing non-file: Path/to/.aux`

Is this an intended behavior? 
It's only a minor inconvinience to have the folder arround, but I still liked the old behavior.

EDIT: I should probably add, that MikTex has a parameter for this: `-aux-directory=%OUTDIR%/.aux`
Using this in combination with the `-output-directory=%OUTDIR%` allows for all aux-files to be created in a subfolder while the pdf still stayes in the output folder.

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

With previos versions one could specify `.aux/**` as a garbage pattern and when running _clean up auxiliary files_ the complete folder would be removed.  
With V8.18.0, this results in a log message and the folder is preserved.

### To Reproduce

1. Go into 'settings.json'
2. Set up `"latex-workshop.latex.clean.fileTypes": [".aux/**"]`
3. create a folder `.aux/` in the projectfolder
4. run _clean up auxiliary files_ (`.aux/`will be preserved, log message shown)
5. roll back to V8.17.0
6. run _clean up auxiliary files_ (`.aux/`will be removed)

### Expected behavior

The folder `.aux/` should be removed, when the pattern `.aux/**` is present.

### LaTeX Workshop Output [Required]

```
[14:39:18] Not removing non-file: Path\to\.aux
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.56.2
 - Extension version: 8.18.0
 - TeX distribution version: MiKTeX 21.3

**Comment by Cube707** [comment]
I found https://github.com/James-Yu/LaTeX-Workshop/pull/2656#issuecomment-831756053, which seems to be the reason the beavior changed to the way it is now.
I get that removing directories poses a risk of deleting stuff that is still needed, but maybe there should be a way to removed directories specificly created to hold junk. From my point of view the convenience could be worth some risk of dataloss in case of a misconfiguration.

**Comment by Cube707** [comment]
also found https://github.com/James-Yu/LaTeX-Workshop/issues/530, should I delete this issue and post as a usecase into that one?

**Comment by jlelong** [comment]
Indeed, this is related to https://github.com/James-Yu/LaTeX-Workshop/pull/2656#issuecomment-831756053 because it creates a security risk, which prevails over the benefits I think. No need to post on the closed issue #530

**Comment by Cube707** [comment]
Could you explain what the security risk is here?

I get that the possibility of deleting files not produced by latex is not desirable, but using `folder/*` or `folder/**` will delete all files anyway and just leave a empty folder structure. How is that more secure than deleting the folders as well?
