### ISSUE TITLE
Subfiles is not compatible with %TMPDIR%

### ISSUE THREAD

**Issue by caph1993** [James-Yu/LaTeX-Workshop#2691]
I have a project with the following structure:

```
- main.tex
- body
| - introduction.tex
```
And the following minimal content:
```latex
% main.tex:
\documentclass[english]{article}
\usepackage{subfiles}
\begin{document}
  This is main, and...
  \subfile{body/introduction}
\end{document}

% body/introduction.tex:
\documentclass[../main.tex]{subfiles}
\begin{document}
This is the introduction.
\end{document}
```

Depending on the value of `Latex-workshop › Latex: Out Dir`, the compilation of `introduction.tex` and `main.tex` may or not work:

 - When the outdir is set to `%DIR%`, both work, and I can view the output with Ctrl+Alt+V.

 - However, when it is set to `%TMPDIR%`, only `main.tex` works and `introduction.tex` stops working.
 
The output console is empty and the `Problems` tab indicates `../main.tex not found`:

![image](https://user-images.githubusercontent.com/5473460/118710826-1de55d80-b81f-11eb-90a2-fb1ca084dc50.png)

**Comment by jlelong** [comment]
This is related to https://github.com/James-Yu/LaTeX-Workshop/issues/1967#issuecomment-592392976.
In short, you need to pass the `-cd` option to latexmk.  For instance, you can add `$do_cd=1;` to your `.latexmkrc` file.

**Comment by caph1993** [comment]
Worked. I am closing the issue.

I created a file `.latexmkrc` at the "main" level with content `$do_cd=1;` and compilation is working for both documents (although with some issues related to cross-references and citations).
