### ISSUE TITLE
What if I don't need bibtex in my workflow

### ISSUE THREAD

**Issue by neilsustc** [James-Yu/LaTeX-Workshop#27]
How about making the workflow smarter? I mean, if there is a `\bibliography` in the main document, we'll do `%compiler%`, `bibtex`, `%compiler%`, `%compiler%`. But if there is not, we can simply do `%compiler%` once.
(I know that I can config the workflow in the `settings.json`, but it's not convenient.)

**Comment by James-Yu** [comment]
What you need is `latexmk`. It is a well designed auto toolchain for latex

**Comment by neilsustc** [comment]
Thanks
