### ISSUE TITLE
lua syntax in `\directlua`

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#270]
Is it possible to use lua syntax highlight in `\directlua`? Or just leave it as a verbatim envrionment may be a good choice. Some characters like `$` in lua may disturb all the syntax highlight afterwards.

PS: In `expl3` synatx, several commands has the similar effect. They are `\luatex_directlua:D`, `\lua_now_x:n` and `\lua_now:n`.

**Comment by James-Yu** [comment]
The development of any LaTeX 3 support will not be initiated by me. So I have to say your request will depend on the community contribution. I personally have no expl 3 experience, so I do not know if your suggestion can be implemented or not.

**Comment by Stone-Zeng** [comment]
This issue actually doesn't have too much connection with LaTeX3.

The simplest way I think is to leave `\directlua` as a command to write verbatim. For example,

```tex
% From expl3-code.tex
\directlua{%
  local i
  local t = { }
  for _,i in pairs(tex.extraprimitives("luatex")) do
    if string.match(i,"^U") then
      if not string.match(i,"^Uchar$") then %$
        table.insert(t,i)
      end
    end
  end
  tex.enableprimitives("", t)
}%
```

Here, there are two `$` in the `\directlua`. They will break all the normal syntax highlight afterwards. (You can see that the highlight on this GitHub webpage has broken)

If you can treat the `\directlua` as a verbatim command (like `\verb`, but delimeters should be `{` and `}`), then these special characters will not have any effects on the afterward syntax highlight.

For *future* improvement, maybe adding truly lua syntax in this command is a wonderful thing. But at present it's not urgent. At least I don't care.

The only thing in LaTeX3 is that `\directlua` has another names. So if you like, you could add the same as `\directlua` support for them.
