### ISSUE TITLE
Setting External PDF viewer to zathura

### ISSUE THREAD

**Issue by anupamsobti** [James-Yu/LaTeX-Workshop#2701]
Hi

I'm using VSCode with the WSL Remote plugin. I enjoy using zathura as an external viewer for my latex output. Could you help me figure out how to set the external viewer as `zathura`?

https://github.com/James-Yu/LaTeX-Workshop/issues/441 discusses setting a custom command for an external viewer. In a similar fashion, I used 
```
    "latex-workshop.view.pdf.viewer": "external",
    "latex-workshop.view.pdf.external.command": {
        "command": "zathura",
        "args": [
            "%PDF%"
        ]
    },

    "latex-workshop.view.pdf.external.synctex": {
        "command": "zathura",
        "args": [
          "%PDF%",
          "%LINE%",
          "%TEX%"
        ]
      },
 ```

to set up zathura. But the external pdf viewer still invokes GNU gv.

**Comment by tamuratak** [comment]
The external PDF viewer is not officially supported. We can not help you.

I doubt that the external PDF viewer works under VSCode with WSL.

**Comment by anupamsobti** [comment]
The external pdf viewer does work fine since I have an xserver running on Windows and the WSL environment uses that to open programs. However, I'm not able to change the default pdf viewer for WSL, which is why I was hoping to do it through this configuration. Nevertheless, thanks for the awesome plugin :-)

**Comment by anupamsobti** [comment]
I was able to change the default viewer for wsl2 and latex workshop invokes the external viewer correctly and refreshes automatically on save. Only synctex doesn't work for me as of now.
I'm just leaving this here as hope for others 😄
