### ISSUE TITLE
Bibliography warning/error unused bibliography

### ISSUE THREAD

**Issue by AzuStar** [James-Yu/LaTeX-Workshop#2702]
### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

What the title says.
Would be neat if vscode would display a warning in bib file if reference is not used.
Also, make that option configurable, something like
`"latex-workshop.bibtex-fields.unusedWarning": true,`

P.S. I tried looking up intellisense on wiki and in code to see if there is a setting or something, but came empty handed so there.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
