### ISSUE TITLE
`result[1] in items` is always `false`

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2704]
The condition `result[1] in items` is always `false`. Then `!(result[1] in items)` is always `true`.

https://github.com/James-Yu/LaTeX-Workshop/blob/365e728b68f050e967c78c4425e1dd974fc49759/src/providers/completer/citation.ts#L279-L287

**Comment by jlelong** [comment]
I guess we can simply remove the condition `if (!(result[1] in items))`. The original idea was to check if two `bibitem`'s had the same key, but this is indeed a LaTeX error.
