### ISSUE TITLE
Subtle text context and scopes inside math

### ISSUE THREAD

**Issue by gruvw** [James-Yu/LaTeX-Workshop#2708]
What do you think about this: [hsnips#50](https://github.com/draivin/hsnips/issues/50)

I think I found a similar issue talking about this same problem: [#2215](https://github.com/James-Yu/LaTeX-Workshop/issues/2215)

I would like to bring that back as it could really improve my writing experience of `\text` in math mode.  
As I read that it could be more complicated to implement, I don't really need (or see the point of) multiple nesting of that kind (see hnsips#50).  
However,  one level nesting is pretty common to be honest:
```latex
\[
    x^2 = 4 \quad \text{This means that \(x=2\) or \(x=-2\).}
\]
```

Let me know what do you think about it.

**Comment by jlelong** [comment]
I think there is a misunderstanding on what I meant about _nesting_ in #2215. I was speaking of nested **braces** inside `\text{}`.

More importantly, it is not possible to remove a scope once it has been added. Hence, there is no way to remove the scope `support.class.math.block.environment.latex`, which is added to the content of every math environment. I guess the best I can do is that assign a new specific scope to the content of `\text{...}`. Then, it would be up to the user to customize their color theme for this new scope.  You can try the branch `2708-text-in-maths` on `https://github.com/jlelong/LaTeX-Workshop.git`  and customize the color for `meta.text.normal.tex` using 

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "meta.text.normal.tex",
                ],
                "settings": {
                    "foreground": "#e9e3e3ce"
                }
            }
        ]
    }
```

Let me know if it helps

**Comment by gruvw** [comment]
Hi, thank you for your reply.  
This idea would solve my issue.

I have tested the provided patch, it is working, but there is an issue.  
The new `meta.text.normal.tex` scope is applied correctly while inside a word or a sentence within a `\text{}` inside a math environment.  
However, when the cursor is right before the closing curly bracket, it is not applying the `meta.text.normal.tex` scope:
![Screenshot from 2021-07-03 06-37-53](https://user-images.githubusercontent.com/63407038/124343103-4a83e780-dbc9-11eb-9dfd-5c0e1817dfbd.png)
This is also causing an empty `\text{}` not having the scope inside the curly braces.

**Comment by jlelong** [comment]
I am not sure there is an issue. On your screenshot, the cursor is actually on the closing `}`, note the highlighting on the pair `{}` . The opening and closing braces do not have the `meta.text.normal.tex` scope. Note that in  an empty`\text{}`, there is no interior so the cursor cannot be between `{` and `}`.

**Comment by gruvw** [comment]
Yes, I get your point.

This would not be an issue if I was using that scope for syntax highlighting, but it actually is an issue as I need that scope for snippets triggering context.  
I don't want my math snippet to trigger inside a `\text{}` even if I did not write anything in it yet.
In fact, it would barely make a difference if the scope is not present at the end of the `\text{}` as when I write I am always at the end, so my snippets would trigger.  
Currently, as it is, the snippets won't trigger just when I edit the text inside the curly braces.

**Comment by jlelong** [comment]
Now, I understand what you would like to do. I can assign the `meta.text.normal.tex` scope to the braces too.
I have just give it a try on the branch `2708-text-in-maths` on https://github.com/jlelong/LaTeX-Workshop.git

**Comment by gruvw** [comment]
Is there an easier way to try out an extension from a GitHub branch other than https://stackoverflow.com/questions/50714638/install-extension-from-a-specific-repo-branch-on-github ?

**Comment by jlelong** [comment]
Great! I will merge my branch into master.

Have a look at https://github.com/James-Yu/LaTeX-Workshop/blob/master/CONTRIBUTING.md. Once you have installed the necessary dependencies using `npm`, just start vscode debugging. It will launch a development host window in which you can test the extension being debugged.

**Comment by gruvw** [comment]
Thank you very much
