### ISSUE TITLE
real-time auto preview of math blocks

### ISSUE THREAD

**Issue by yfzhao20** [James-Yu/LaTeX-Workshop#2712]
## Describe the solution you'd like  [Required]

I think hover preview is good, but real-time auto preview is maybe better, just like Typora:

![image](https://user-images.githubusercontent.com/80528249/119228379-577ed700-bb45-11eb-9767-39d7dc627d84.png)

If it is supported, maybe I don't need to move my mouse or build the document. And it is easy to debug😃.

**Comment by tamuratak** [comment]
Execute the command `latex-workshop.toggleMathPreviewPanel`
