### ISSUE TITLE
Custom preamble on hover preview

### ISSUE THREAD

**Issue by Kreijstal** [James-Yu/LaTeX-Workshop#2715]
I have custom commands, that are not previewed when previewed on hover, is it possible to customize the preamble that the preview is using?

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandnewcommandfile

If MathJax does not support the commands, it does not work.

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
