### ISSUE TITLE
Show current rule (run) number during compilation

### ISSUE THREAD

**Issue by keth-tex** [James-Yu/LaTeX-Workshop#2716]
Working with LuaLaTeX using `scrlayer-notecolumn` compilation with `latexmk` can take several minutes because often times four or five runs are necessary. Also: When I see that there is a sixth or seventh run, I know that there is something wrong with the code an that I can terminate the compilation.
Therefore it would be quite helpful if the number of the current run/rule could be displayed in the status bar.

I missed the "heated discussion" on the removal of `BuildInfo`. If this feature would be re-considered as an optional setting which is deactivated by default, that would be highly appreciated.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

Please execute `latex-workshop.compilerlog` and see LaTeX compiler logs if you need.
