### ISSUE TITLE
Wrap fields during bibtex formatting to a set linewidth

### ISSUE THREAD

**Issue by jolars** [James-Yu/LaTeX-Workshop#2721]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

I'm using the bibtex format feature in the extension, which I think is great. The problem is that it removes line breaks in bibtex fields with a lot of text and instead puts, for instance the abstract, on a single line, which makes it hard to read.

## To Reproduce  [Required]

1. Format a `.bib` file using LaTeX-Workshop with a field containing a lot of text.
2. Some of the lines, e.g. the abstract, run very long and existing line breaks are removed.

## Describe the solution you'd like  [Required]

I would like LaTeX-Workshop to wrap the lines in the bibtex fields to a set length, such as 80 columns, or alternatively to respect original line breaks.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.
- Please paste a sample `.bib` file.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by jolars** [comment]
Sorry, I've updated the post with all the information now. I also realized that I was wrong about the extension removing line breaks (it does not) so I've updated the description as well.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by jlelong** [comment]
What you are actually asking for is hard wrapping the bib file while formatting. Unfortunately, the grammar engine used by VSCode cannot work smoothly with hard wrapped files. You should rather use VSCode soft wrapping features: `editor.wordWrap`, `editor.wordWrapColumn` and `editor.wrappingIndent`.
