### ISSUE TITLE
Snippet autocompletion doesn't get triggered for certain tokens

### ISSUE THREAD

**Issue by L1szt** [James-Yu/LaTeX-Workshop#2722]
VS Code Version: 1.56.2
Latex Workbench Version: v8.18.0
OS Version: MacOS BigSur 11.2.3

I have created certain snippets in the latex.json file. Most of them work, but for certain characters those snippets don't get triggered:
```
"implies": {
        "prefix": ["=>"],
        "body": [
            "\\Longrightarrow",
        ],
        "description": "implies"
    },
```
This is one example, the snippet doesn't appear when typing =>. Other characters where it didn't work for me are:
`=<`,`/`, `!=`.
With triggered I mean that it doesn't show up automatically, only when explicitly "forcing" it by pressing Ctrl+Space.

This issue got already posted on vscode's github ([here](https://github.com/microsoft/vscode/issues/124751)) and the conclusion was that the extension's author can specify the "definition" of a "word" which is the reason why the autocompletion  doesn't get triggered. Is there a way one can change this on his own or is this a deeper "issue" which can only be handled by the extension's author[s]?

**Comment by jlelong** [comment]
The definition of a "word" is give in https://github.com/James-Yu/LaTeX-Workshop/blob/2391afdeb25716970ec0d962cc43bfec624040b0/syntax/syntax.json#L62


You cannot change it yourself. There are several issues dealing with automatic suggestions and the `wordPattern` setting is very sensitive, so I am against playing with it.

However, as you can see, anything starting with `@` is considered as a word. So, I guess you could just use `@` as a prefix for your snippets.

**Comment by L1szt** [comment]
@jlelong I don't want to use the `@` symbol because it's uncomfortable for me, especially when using it that extensively.
