### ISSUE TITLE
ISSUE OF PDF VIEWER BOOKMARK LIST RENDER

### ISSUE THREAD

**Issue by heartacker** [James-Yu/LaTeX-Workshop#2724]
![PDF](https://user-images.githubusercontent.com/1876302/119920161-6ed31f80-bf9e-11eb-9b20-5026f79818a1.gif)

**Comment by tamuratak** [comment]
Duplicate of #2640. This issue will be fixed after updating PDF.js to v2.8. We are not sure when we will update it.

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
