### ISSUE TITLE
Register PDF viewer as "customEditor"

### ISSUE THREAD

**Issue by septatrix** [James-Yu/LaTeX-Workshop#2725]
## Preliminary questions [Required]

You still see this issue?: N/A

You visited the wiki?: Yes

You can compile a TeX document manually?: N/A

## Is your requested feature related to a problem? Please describe. [Required]

Opening a PDF file always results in the message "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?". Opening it anyway always prompts for an editor to choose for this file.

## To Reproduce [Required]

1. Open any PDF file in VSCode

## Describe the solution you'd like [Required]

VSCode allows extensions to register a "custom editor" for text files but also binary files.
Such a editor can also be a read-only viewer of the file type.
These editors can then be associated with different file endings (like *.pdf) etc. which will result in VSCode automatically using that editor for the corresponding file type.

## Logs [Required]

N/A

### LaTeX Workshop Output [Required]

N/A

### Developer Tools Console [Required]

N/A

## Screenshots

![image](https://user-images.githubusercontent.com/24257556/119962425-50bded00-bfa7-11eb-8629-76f094da6aec.png)
![image](https://user-images.githubusercontent.com/24257556/119962456-59aebe80-bfa7-11eb-82b3-8a3d0302a38d.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 20.10, Linux 5.8.0-53-generic
 - VS Code version: 1.56.2
 - Extension version: 8.18.0
 - TeX distribution version: Texlive 2020.20200804-2

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

o
### Additional context

https://code.visualstudio.com/api/extension-guides/custom-editors#readonly-custom-editors

**Comment by tamuratak** [comment]
Out of the scope of the extension.
