### ISSUE TITLE
lualatex supported?

### ISSUE THREAD

**Issue by python152** [James-Yu/LaTeX-Workshop#273]
I used to have a Sublime latex project with header set as:

`%!TEX program = lualatex
`

switching to VS code with Latex-workshop, the compile insists on using `pdflatex`, is this not the correct way of specifying it, or do I need to configure something extra? TIA

**Comment by James-Yu** [comment]
Yes, supported.
Please read README.

**Comment by python152** [comment]
Well, README says %! TEX program is supported, the example given there says only `xelatex`, I had assumed `lualatex` should work the same way, but it is not in my case.

Anything I can check to know why `%! TEX program = lualatex` is not in effect?

From Latex workshop output

`[14:31:01] Toolchain returns with error: 12/null.
`
I am not sure if this is relevant.

From latex compiler output:

```
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "/Users/pyz/linear-solver.tex"'
------------
Latexmk: applying rule 'pdflatex'..
```.

**Comment by James-Yu** [comment]
README also says
```
All command in toolchain which are empty will be replaced with the program set by % !TEX program magic comment ...
```

**Comment by python152** [comment]
I noticed that, and I also tried to check for toolchain settings to make sure it is empty as the README says, but ` File>Preferences>Settings>latex-workshop.latex.toolchain` seems for Windows only. I can't locate it on Mac. Any idea?

**Comment by James-Yu** [comment]
No it is not platform specific. You can edit with `CMD+,`

**Comment by python152** [comment]
aha, that is the part I missed: it seems to use `program` magic command, you *MUST* redefine toolchain command as empty.  Another clarification: the readme says, if it is empty, and no `program` defined, then it will fall back to `pdflatex`. However, the default setting in `command` is `latexmk` - just out of curiosity, why it won't just fall back to `latexmk`, or alternatively, make `pdflatex` the default in the command?

**Comment by python152** [comment]
well, after working with the special `program` for a while, I think maybe it should fall back to `latexmk` instead of `pdflatex`, sinece I am seeing at times, the cross-references not done properly, and I have to compile it manually one more time to make it work ... could this be a bug?

**Comment by James-Yu** [comment]
By default it IS `latexmk`, and by default it uses `pdflatex`.
