### ISSUE TITLE
[Tip] Apparmor affects external pdf viewer in linux (snap)

### ISSUE THREAD

**Issue by caph1993** [James-Yu/LaTeX-Workshop#2748]
I tried the three viewers for linux shown in [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#linux), and only okular launched. Evince and Zathura did not start at all.

If you have the same problem, this may resolve it: run `sudo dpkg-reconfigure apparmor`, type your home location during the configuration (`/home/(you)`) and restart.

I share the solution in this repository because it may help many other users.

**Details.** This issue affects the **snap version of vscode**. Some [other snap apps](https://forum.snapcraft.io/t/ubuntu-18-04-fresh-install-apparmor-blocking-slack-spotify-and-vscode/5245) have reported similar problems.  It took me several hours of googling and debugging with `journalctl | tail -f` and `dmesg` to solve it. I am on kde linux (ubuntu based distro).

**Comment by tamuratak** [comment]
We don't recommend using the snap and flatpak versions of VS Code. See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#problems-with-snap-and-flatpak-versions-of-vs-code
