### ISSUE TITLE
Improve pdf preview icon

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#275]
![image](https://user-images.githubusercontent.com/9464825/30510492-df0b0666-9af7-11e7-9568-7e11deb0f01c.png)
![image](https://user-images.githubusercontent.com/9464825/30510500-f339c2b2-9af7-11e7-8d57-130522750216.png)
![image](https://user-images.githubusercontent.com/9464825/30510503-0a6fdc82-9af8-11e7-9f4f-1348aff9ef13.png)
![image](https://user-images.githubusercontent.com/9464825/30510506-281e6c44-9af8-11e7-9c64-80ca4123b02a.png)

The pdf viewer button just feels "not right"

**Comment by James-Yu** [comment]
Unfortunately, aesthetic issues are always hard to fix for everyone. I will leave this issue open and see if others may come up with better designs.

**Comment by bartosz-antosik** [comment]
@James-Yu I already did! Exactly in this aspect. ;-) At the end of thread #229, Thought you were annoyed by me & my icons, so have not brought this back. Please have a look: [icons.zip](https://github.com/James-Yu/LaTeX-Workshop/files/1216340/icons.zip).

**Comment by bartosz-antosik** [comment]
But when I look at them right now I think that I have neglected dark themes. Here is better version:

[icons.zip](https://github.com/James-Yu/LaTeX-Workshop/files/1332532/icons.zip)

![screenshot-20170926-112516](https://user-images.githubusercontent.com/20492548/30852933-9d351ee4-a2ad-11e7-840a-ef26a8e453c5.png)

![screenshot-20170926-112538](https://user-images.githubusercontent.com/20492548/30852938-9fadfe20-a2ad-11e7-868c-f12c0cb33578.png)

I am not sure if I am entirely happy with them however. ;-)

**Comment by innerlee** [comment]
@bartosz-antosik nice designs. IMHO, red is a little bit being too "energetic". It makes people feel sad when they are tired after staring at the screen for a long time.

**Comment by bartosz-antosik** [comment]
Less energetic:

[icons.zip](https://github.com/James-Yu/LaTeX-Workshop/files/1332659/icons.zip)

![screenshot-20170926-114733](https://user-images.githubusercontent.com/20492548/30854442-e76ef85a-a2b1-11e7-9fbf-1fea5ece9cfe.png)

![screenshot-20170926-114757](https://user-images.githubusercontent.com/20492548/30854446-e9db5f20-a2b1-11e7-9468-c37dd7d715c4.png)

It is actually color used for red markings in editor's slider.  So I think it it more "in line" with the whole spirit of VSCode. And it is different in light/dark themes...

How does this this make people feel?

**Comment by James-Yu** [comment]
You are much better artists than me! Will incorporate soon.

**Comment by bartosz-antosik** [comment]
Thank you. Happy to help.  And I am not an artist of course. Not a bit. ;-)
