### ISSUE TITLE
`latex-workshop.docker.image.latex` is empty by default

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2750]
We have changed the default value of `latex-workshop.docker.image.latex` from `"tianon/latex"` to `""`. Since the image seems to be unmaintained. #2579

Please find an appropriate image by yourself and set the name to  `latex-workshop.docker.image.latex`.

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#using-docker

**Comment by raynigon** [comment]
Changing this, broke my setup and now i`m still using `tianon/latex` because i don`t have the time to do research.
I think it would be better if there would be at least a suggestion for another image which was tested and is compatible.

**Comment by tamuratak** [comment]
> I think it would be better if there would be at least a suggestion for another image which was tested, is compatible and maintained.

No, we don't suggest any image. Please find it by yourself. 

If you want to continue to use the `"tianon/latex"` image, please set the value to `"latex-workshop.docker.image.latex"`.

**Comment by YOUSIKI** [comment]
Maybe the image `texlive/texlive` can be used as default value? (Just suggestion
