### ISSUE TITLE
"view pdf" right-click not available

### ISSUE THREAD

**Issue by adamaltmejd** [James-Yu/LaTeX-Workshop#2751]
How do I view a pdf file thats not generated by a .tex document. The right-click option that I read about in other threads is not available for me. But installing vscode-pdf or similar creates conflicts. Is viewing not supported anymore or is this a bug?

Right-clicking a pdf in the file explorer shows only these options to me:

<img width="265" alt="Screen Shot 2021-06-11 at 07 48 55" src="https://user-images.githubusercontent.com/736668/121637312-7b20a780-ca89-11eb-8687-3617e3ceb2f7.png">

And left-clicking only shows the error: "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?"

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

3. See error

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]

### Are you using VSCodium?

Yes/No

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by jlelong** [comment]
> And left-clicking only shows the error: "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?"

Just click on *Do you want to open it anyway?* and the pdf file should be rendered.

**Comment by adamaltmejd** [comment]
Haha thanks! It did not work at first but now it started even opening pdfs just when I click them. No idea whats going on.

**Comment by adamaltmejd** [comment]
Or actually, it is working for one file but not another. There I only see:

<img width="597" alt="Screen Shot 2021-06-11 at 08 33 11" src="https://user-images.githubusercontent.com/736668/121641623-b1f9bc00-ca8f-11eb-9ed7-3781a586dfdd.png">
