### ISSUE TITLE
Support Version

### ISSUE THREAD

**Issue by Zeyecx** [James-Yu/LaTeX-Workshop#2754]
Unfortunately, the extension always crashes with the new VSCode versions. Can this be fixed, please? 

```PowerShell
C:\Users\Zeyecx>code --version
1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64
```

**Comment by Zeyecx** [comment]
![image](https://user-images.githubusercontent.com/15014849/121688375-a88a4700-cac3-11eb-87cc-3424bd060237.png)
Unfortunately, it says here that only the old versions are supported.

**Comment by tamuratak** [comment]
The extension is not ours. It is `TeX Workshop`. Ours is `LaTeX Workshop`.

**Comment by Zeyecx** [comment]
That is interesting. The links point directly to the git here.

**Comment by tamuratak** [comment]
Please install our extension.

**Comment by jlelong** [comment]
TeX Workshop is a fork https://github.com/Jeff-Tian/LaTeX-Workshop/ of our extension, which has not been updated since July 2020.
