### ISSUE TITLE
Provide an option to disable indentation 

### ISSUE THREAD

**Issue by jiaan** [James-Yu/LaTeX-Workshop#2755]
I often write long equations or matrices that spans multiple lines. The snippets such as 'BEQ' 'BSP' and shortcuts 
such as '\array' really come in handy. But I am really annoyed at the new tab automatically inserted whenever I create a new environment through these shortcuts. Eventually I have multiple levels of indentation with little space to write my equations within my 80-character width limit and I have to manually remove these indentations. I understand programmers likes well-indented code. But I find indentation unnecessary and uncomfortable in latex.  I wonder is it possible to have an option to disable auto indentation by striping these new tab characters? Thanks.

**Comment by jlelong** [comment]
You can set

```
json
"editor.tabCompletion": "off",
"editor.tabSize": 0
```

for LaTeX mode.

**Comment by jiaan** [comment]
Hi jlelong, I had tried changing tabSize before, it gives me an error saying  value is below the minimum of 1.

**Comment by jlelong** [comment]
Unfortunately, there is no way to remove indentation inside snippets.
Yet, you can redefine the snippets without the `\t` (ie. without indentation) and hide the snippets provided by the extension. See https://github.com/microsoft/vscode/issues/10565#issuecomment-721832613
