### ISSUE TITLE
How to change shortcut-bindings?

### ISSUE THREAD

**Issue by 1900011604** [James-Yu/LaTeX-Workshop#2763]
I am used to [TexStudio](https://github.com/texstudio-org/texstudio)'s shortcut `Ctrl+Alt+F` for `\frac{}{}`, is there any way of editing the shortcut list?

**Comment by jlelong** [comment]
The `\frac{}{}` snippet is defined in https://github.com/James-Yu/LaTeX-Workshop/blob/c1900b2dde52cf6e7c7eeb3987fa8e1af10084a9/snippets/latex.json#L37-L41

You can associate a keybinding to it as explained at https://code.visualstudio.com/updates/v1_9#_insert-snippets
