### ISSUE TITLE
Failed to get cross-references right

### ISSUE THREAD

**Issue by RicardoCLake** [James-Yu/LaTeX-Workshop#2767]
Compiling results in a perpetual latex warning regarding changing labels:
Label(s) may have changed. Rerun to get cross-references right.

This interferes with automatic recompilation / opening of pdf files. The reason for the warning seems to be a redefinition of \bibcite in abntex2cite.sty (around line 629)

The fix is to simply comment those lines:

\ifthenelse{\boolean{ABNThyperref}}{%
%\renewcommand{\bibcite}[2]{%                                                        comment here
% \@newl@bel{b}{#1}{\hyper@@link[cite]{}{cite.#1}{#2}}}%              comment here
\newcommand{\bibciteEXPL}[2]{%
 \@newl@bel{b}{#1++EXPL}{\hyper@@link[cite]{}{cite.#1}{#2}}}%
\newcommand{\bibciteIMPL}[2]{%
 \@newl@bel{b}{#1++IMPL}{\hyper@@link[cite]{}{cite.#1}{#2}}}%
\newcommand{\bibciteYEAR}[2]{%
 \@newl@bel{b}{#1++YEAR}{\hyper@@link[cite]{}{cite.#1}{#2}}}%
}{}
Could you add this change to the repo?

**Comment by jlelong** [comment]
This has nothing to do with the extension.
