### ISSUE TITLE
Turn off autocomplete in normal text?

### ISSUE THREAD

**Issue by btracey** [James-Yu/LaTeX-Workshop#277]
Autocomplete is great for commands and environments, but it's distracting to have an autocomplete box pop up on every word. It would be nice if there were a way to filter when the autocomplete suggestions happen.

**Comment by James-Yu** [comment]
It's not this extension, but `editor.wordBasedSuggestions` config provided by vscode.

**Comment by btracey** [comment]
Thanks.

**Comment by retrography** [comment]
I think it is useful if this is included as a useful hint on the package's intellisense help page.

**Comment by tamuratak** [comment]
You can contribute. https://github.com/jlelong/LaTeX-Workshop-wiki
