### ISSUE TITLE
remote support

### ISSUE THREAD

**Issue by akosyakov** [James-Yu/LaTeX-Workshop#2772]
An extension fails to work in remote settings like Gitpod: https://github.com/gitpod-io/gitpod/issues/4513

The issue is that CSP policy hardcoded to use localhost: https://github.com/James-Yu/LaTeX-Workshop/blob/ba9a629e34899e0b5d892e5ee84880f78338672f/viewer/viewer.html#L29 But should use webview CSP.

Please see for details: https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api

**Comment by tamuratak** [comment]
This is intentional. We load `viewer/viewer.html` as the `src` of `iframe` through a local server. We should not use the webview CSP.

We will not support gitpod on our side.
