### ISSUE TITLE
Intellisense for glossary in external file 

### ISSUE THREAD

**Issue by scimax** [James-Yu/LaTeX-Workshop#2780]
Hello everyone!
I'm using Latex-Workshop for an extensive writing project and make heavy use of acronym entries in a glossary. I would like to use the completion functionality of IntelliSense for this. While going through the issues I found #516 and pull request #2298 which adds glossary completion. However, it did not work for me. After reducing the files to an MWE I figured out that it is due to putting the glossary entries in a seperate file.

`main.tex`:
```tex
\documentclass{article}
\usepackage{lipsum}  
\usepackage{glossaries}
\makeglossaries
\loadglsentries{glossary}

\begin{document}
\lipsum[2-4]
\gls{rf} \gls{rf} \gls{rf}
\end{document}
```
`glossary.tex`:
```tex
\newacronym{rf}{RF}{radio-frequency}
\newacronym{te}{TM}{Transverse Magnetic}
```
When entering `\gls{` no suggestion is showing up in the main file.

As it is probably similar to the completion for bib entries shouldn't that be possible somehow? I couldn't find any info in the wiki. Compiling is fine and it works as desired.

I'm sorry that I don't stick to the bug report template for issues. But I have the impression most questions are not suitable for the problem. Maybe it's more like a feature request? Sorry if that's the case. As pointed out at the end of #2298 user feedback is welcome, so I thought it would be useful.

 - OS: Windows 10
 - VS Code version: 1.57.1
 - Extension version: 8.19.2
 - TeX distribution version: MikTex 21.6

VSCodium? No
Snap or Flatpack versions of VS Code? No
Are you using LaTeX Workshop with VS Code Remote? No

Thanks a lot for this great extension!

**Comment by jlelong** [comment]
There are actually two issues here

1. We do not support `\loadglsentries` for the moment. I will add it.
2. Once `main.tex` has been compiled with `latexmk`, the file `glossary.tex` should be discovered using the file `main.fls`. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-dependencies. It does not work if the file `glossary.tex` has already been opened because it is present in `cachedContent`

    https://github.com/James-Yu/LaTeX-Workshop/blob/6a6c5c775a48ac652174d8cb42abbb839eff2c3c/src/components/manager.ts#L711

**Comment by scimax** [comment]
Hi @jlelong ,
thanks for the quick response! Yes, that makes sense. Should I open a second issue or do we keep them tegether?
Regarding the second point, does that mean, it should work with the `glossary.tex` being closed, after fixing point 1.? The `.fls` file contains `INPUT .\glossary.tex` as you mentioned. What's the difference to the `.bib` file? Usually it is not necessary to close it before compilation.

**Comment by scimax** [comment]
Oh, sorry, I haven't seen your PR. So then opening another issue is obsolete, I guess^^

**Comment by jlelong** [comment]
I do not want to go too much into the implementation details but closing `glossary.tex` will not make any difference. `.bib` and `.tex` files are handled differently.
