### ISSUE TITLE
"surround with ..." removes line break

### ISSUE THREAD

**Issue by maaaaadn** [James-Yu/LaTeX-Workshop#2782]
I'm facing a strange issue.
When surrounding e.g. a multiline equation with "\\" linebreak inside after surrounding the first "\\" is replaced with "\". 
This seems to happen independent of the environment I'm using to surround and which I was using in the first place to type a multiline equation. 

Is this a known problem, is there any workaround? I've attached a short screen recording of the issue:

https://user-images.githubusercontent.com/4591716/123754955-b9a4c780-d8bb-11eb-9a98-9aa5e2076078.mp4

**Comment by jlelong** [comment]
Note that to wrap some text inside an environment, you should rather use https://github.com/James-Yu/LaTeX-Workshop/wiki/Snippets#with-an-environment as it is almost impossible to handle indentation properly with the _surround with command_ approach.

**Comment by maaaaadn** [comment]
Okay, I see. Thanks for the help!
Interestingly it works without problems if I use the second approach of "surround with command", simply selecting the text and starting \subeq.. 

but I'll begin using the surround with environment for that case. 
thanks again!
