### ISSUE TITLE
openWebviewPanel has a timing issue.

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2788]
`openWebviewPanel` has a timing issue on VS Code Remote SSH. It also has the same issue on my local setting sometimes.

https://github.com/James-Yu/LaTeX-Workshop/blob/0389ad4717cc7f402c40739b30f9a97d17240a2a/src/utils/webview.ts#L21

https://user-images.githubusercontent.com/10665499/124369680-7eced500-dca9-11eb-81be-e841ac032796.mov

I would like to use `await vscode.window.showTextDocument(editor.document, editor.viewColumn, false)` dropping the support for `latex-workshop.view.pdf.tab.editorGroup: left` and `above`. See  #2203 and 800359beba4e0b33e4a2acd1501ec8e6489be8a1.

Another choice is that we won't fix the issue.

**Comment by tamuratak** [comment]
Increasing the number from `500` to `1000` or `2000` might solve the issue:

https://github.com/James-Yu/LaTeX-Workshop/blob/0389ad4717cc7f402c40739b30f9a97d17240a2a/src/utils/webview.ts#L64

With the new numbers, the focus gets back to the current editor a little later.

**Comment by jlelong** [comment]
I agree that the delay is acceptable. I think we could make the delay configurable such that only users experiencing a timing issue would increase it. Some users may find the delay a bit too long, but as there was a real demand for `latex-workshop.view.pdf.tab.editorGroup: left` and `above` I am sure other users will miss it.

My opinion is that if we can (almost) solve this issue by making the delay configurable, then it is fine. We are at the edge of VS Code's API features and for the moment there is no perfect solution.

**Comment by tamuratak** [comment]
I agree.
