### ISSUE TITLE
Missing input file

### ISSUE THREAD

**Issue by senyai** [James-Yu/LaTeX-Workshop#279]
I'm working on Windows with quite recent MiKTeX.

I have 'main.tex' that includes other tex files in such a way:

    \input{chapters/abs}
    \input{chapters/intro}
    \input{chapters/fht3lines}

When I modify `chapters/abs.tex` file, the workshop kicks in, and starts:

    Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "c:\Users\senyai\projects\papers\ip2017_houghs\main.tex"'

Which is what I expect. But then I get:

    'chapters/fht3lines.tex:14: LaTeX Error: File `pics/3d_line_example' not found.'

I guess current directory isn't changed to the directory where main.tex belong.

**Comment by James-Yu** [comment]
Sorry for the late reply. It seems that the extension is working correctly, and the compiler is complain about missing files. Can you please first double check on the file names and then provide a minimal working example for me to reproduce the problem?

**Comment by senyai** [comment]
Thanks for the extension and your time. Hmm, I can't reproduce the issue with the same project now. I will report back with project files if I see the same issue again.

**Comment by James-Yu** [comment]
Glad to know the issue resolved. Thanks for using the extension!
