### ISSUE TITLE
Question about keyboard forwarding

### ISSUE THREAD

**Issue by bunsenstraat** [James-Yu/LaTeX-Workshop#2790]
Hi, this is just a question, is this keyboard forwarding working ( copy/paste especially, the others work fine ) for you guys on 1.57 on MacOs? It seems it stopped working on 1.56.

https://github.com/James-Yu/LaTeX-Workshop/blob/b340b2fa4c853670d64420537d0b9341bea4fa88/src/components/viewer.ts#L316

I'm asking because your fix was suggested by:
https://github.com/microsoft/vscode/issues/65452#issuecomment-586485815

Thanks!

**Comment by tamuratak** [comment]
No, it doesn't work for copy and paste.

**Comment by bunsenstraat** [comment]
Thanks!
