### ISSUE TITLE
How to make synctex work when using Microsoft Edge as the external PDF viewer?

### ISSUE THREAD

**Issue by stephenlevitt** [James-Yu/LaTeX-Workshop#2791]
My use case is as follows: I use Firefox as my default Windows browser but I want to use Edge as the PDF viewer because it renders PDFs better. I have therefore set up LaTeX Workshop to use Edge as the external viewer.

When I make Edge my default browser in Windows 10 and use `browser`  for the PDF viewer setting _then synctex works without a problem_. If it is not my default browser and I set Edge as the external PDF viewer, then a forward search displays the tex source, and a reverse search does not work at all. Viewing the PDF in Edge, using Ctrl-Alt-V works fine.

These are my settings:
```
    "latex-workshop.view.pdf.viewer": "external",
    "latex-workshop.view.pdf.external.viewer.command": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "latex-workshop.view.pdf.external.synctex.command": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "latex-workshop.view.pdf.external.synctex.args": [ 
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "code \"C:\\Users\\xxxxxx\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
        "%PDF%",
    ],
```
I'm using LaTeX Workshop build 8.19.2.

**Comment by tamuratak** [comment]
Not possible. Please up vote microsoft/vscode/issues/96132.
