### ISSUE TITLE
Update class and package names

### ISSUE THREAD

**Issue by zepinglee** [James-Yu/LaTeX-Workshop#2792]
The `data/{classnames,packagenames}.json` files (which are used for auto-completion) were generated from the `texmf-dist/ls-R` file of a TeX Live 2020 distribution. As of 2021, the classes and packages have many changes and these files need to be updated.

Furthermore, there are several issues about auto-completing classes and packages.

1. Several packages in `extra-packagenames.json` added by me are not processed into `packagenames.json` yet.
2. The `xeCJKfntef.sty` which is part of `xeCJK` (<https://ctan.org/pkg/xecjk>) now requires explicit loading in the preamble after a recent change. Thus it should be added to the `extra-packagenames.json`.

I'm happy to make a PR.

**Comment by jlelong** [comment]
Yes, I will update the list of classes and packages based on TeXLive 2021.

I do not understand what the file`extra-packagenames.json` is referring to. Could you be more precise?

**Comment by zepinglee** [comment]
It is [`dev/extra-packagenames.json`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/dev/extra-packagenames.json), which contains `.sty` packages that cannot be detected by their CTAN names.

BTW, I suggest using <https://mirror.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb> rather than the local `ls-R` file for listing the `.sty` packages. The tlpdb is more complete than the local `ls-R` if a partial installation of TeX Live was performed. And the remote tlpdb is always up-to-date.

**Comment by jlelong** [comment]
Thanks for the tip on `tlpdb`. 

> Several packages in `extra-packagenames.json` added by me are not processed into `packagenames.json` yet.

I am sure to understand the issue here. The packages listed in `dev/extra-packagenames.json` are added to `data/packagenames.json` by the Python script `dev/ctanpkglist.py`. The file `dev/extra-packagenames.json` is not directly used by the extension.
