### ISSUE TITLE
(Installation) In ReadMe, List packages required for LaTeX-Workshop

### ISSUE THREAD

**Issue by ravikumargrk** [James-Yu/LaTeX-Workshop#2797]
## Preliminary questions [Required]
This feature request about installation and is not an issue

## Is your requested feature  related to a problem? Please describe. [Required]
While installing TexLive, the default installation scheme (A scheme is set of packages defined by TexLive installer) installs 4 GB of unnecessary packages, which takes a lot of time. Basic scheme does not contain latexmk, which is required for LaTeX-Workshop. Using schemes causes either installing too many packages or not downloading necessary packages. It would be easy if you could list packages that are **absolutely necessary, only** for LaTeX-Workshop to work, so that users can run custom install (refer screenshot) and save space on their desktop. 

## To Reproduce  [Required]
1. Run TexLive installer, from [this link](https://www.tug.org/texlive/acquire-netinstall.html)
2. Click "Advanced" button when GUI loads
3. Check "Selections" panel for schemes, Disk Space required etc
4. Click "Customize" button to choose packages to be installed.

## Describe the solution you'd like  [Required]
If necessary packages to be installed from TeXLive installer is mentioned in ReadMe markdown file, I could select right packages in **Custom Install** _Step 4 in : To Reproduce_ 

## Screenshots
![image](https://user-images.githubusercontent.com/15543980/125680005-db4b7d60-882e-4fa7-8ff9-1e2dc5682cc6.png)

## Desktop [Required]
 - Windows 10
 - VS Code version: 1.57.1
 - Extension version: 8.19.2
 - TeX distribution version: TeX Live 2021

### Are you using VSCodium? 
No

### Are you using the Snap or Flatpack versions of VS Code?
No

### Are you using LaTeX Workshop with VS Code Remote?
No

**Comment by jlelong** [comment]
LaTeX-Workshop does not require any specific LaTeX package to work. `latexmk` is not a LaTeX package per se, it is a script to automate the compilation of a LaTeX document. Note that `latexmk` requires a Perl intallation to work. You should be able to install `latexmk` through the TeXLive package manager.
