### ISSUE TITLE
Blurry icons

### ISSUE THREAD

**Issue by bartosz-antosik** [James-Yu/LaTeX-Workshop#28]
Newly introduced toolbar icons are bit blurry:

![vscode-latex-workshop-1](https://cloud.githubusercontent.com/assets/20492548/23946470/cf19673e-097a-11e7-9a1e-af49e0cda8d4.PNG)

![vscode-latex-workshop-2](https://cloud.githubusercontent.com/assets/20492548/23946474/d4c383b8-097a-11e7-921b-b7b10aab3733.PNG)

Could I propose these two icons I made with LaTeX Workshop in mind?

![vscode-latex-workshop-3](https://cloud.githubusercontent.com/assets/20492548/23946512/f1798dcc-097a-11e7-88b7-bb126bf84985.PNG)

![vscode-latex-workshop-4](https://cloud.githubusercontent.com/assets/20492548/23946507/ee105be8-097a-11e7-8675-d78086f4bf3a.PNG)

[icons.zip](https://github.com/James-Yu/LaTeX-Workshop/files/844292/icons.zip)

**Comment by James-Yu** [comment]
Awesome work! Will integrate them for sure. Any licensing issues btw?

**Comment by bartosz-antosik** [comment]
Loupe is from VSCode icons. The rest is mine. So go figure!

You may have it on whatever license fits.

**Comment by bartosz-antosik** [comment]
If I may I would also suggest changing tooltips to "Show PDF Preview" and "Locate LaTeX Column".
