### ISSUE TITLE
Linking Texlive Installed under Windows 10 bash

### ISSUE THREAD

**Issue by Githelang** [James-Yu/LaTeX-Workshop#280]
Can LaTeX Workshop detect texlive installed through Windows 10 bash?

**Comment by James-Yu** [comment]
If the compiler binaries are available from path then yes. Typically it is not related to which bash is used to install texlive.

**Comment by nikhilweee** [comment]
@Githelang Were you successful in trying this out? If yes, I'd like to know how.
