### ISSUE TITLE
is defaultSettings.yaml for latexindent working?

### ISSUE THREAD

**Issue by NeoFantom** [James-Yu/LaTeX-Workshop#2801]
I tried changing some settings in `defaultSettings.yaml` for latexindent, but it didn't show any effect. I'm not sure if I did things right. But I wanna know, is this file working for latexindent when I format tex file through latex-workshop extension?

**Comment by NeoFantom** [comment]
E.g. when I change `defaultIndent` setting, it has no effect. But changing indent on vscode bottom toolbar works. I'm confused.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.
