### ISSUE TITLE
custom watched file directory with globbing

### ISSUE THREAD

**Issue by ggraham** [James-Yu/LaTeX-Workshop#2802]
I had elected to use a pgfkeys/custom macro to include chapters, implemented as so:

```
\pgfkeys{
  /chapters/.is family, /chapters,
  default/.style = {%
    introduction = true,
    relatedwork = true,
    experimentaldesign = true,
    results = true,
    discussion = true},
  introduction/.store in = \includeintroduction,
  relatedwork/.store in = \includerelatedwork,
  experimentaldesign/.store in = \includeexperimentaldesign,
  results/.store in = \includeresults,
  discussion/.store in = \includediscussion,
}

\newcommand{\includechapter}[3]{%
  \pgfkeys{/chapters, default, #1}%
  \chapter{#3}
  \ifthenelse{\equal{true}{\includeintroduction}}{%
    \section{Introduction}
    \input{chapters/#2/introduction.tex}}{}
  \ifthenelse{\equal{true}{\includerelatedwork}}{%
    \section{Related Work}
    \input{chapters/#2/related_work.tex}}{}
  \ifthenelse{\equal{true}{\includeexperimentaldesign}}{%
    \section{Experimental Design}
    \input{chapters/#2/experimental_design.tex}}{}
  \ifthenelse{\equal{true}{\includeresults}}{%
    \section{Results}
    \input{chapters/#2/results.tex}}{}
  \ifthenelse{\equal{true}{\includediscussion}}{%
    \section{Discussion}
    \input{chapters/#2/discussion.tex}}{}
}
```
and called like so:
```
\includechapter{introduction=false,discussion=false}{model_details}{Model Details}
```
wherein it will look in the "chapters" subdirectory under the root, followed by the specified subdirectory, in this case "model_details", and include introduction.tex, experimental_design.tex, related_work.tex, results.tex, and discussion.tex, unless explicitly negated. An example of this is in the function call above, with introduction=false. Because this work has a number of chapters, not all of which have all of the elements described (and because I was looking for a programmatic solution to avoid typing all of those "\include"s in the root .tex), I decided this might be a way about it.

Unfortunately, this prevents chktex from running through those files (not that big of a problem)
```
chktex: WARNING -- Unable to open the TeX file `chapters/#2/introduction.tex'.
chktex: WARNING -- Unable to open the TeX file `chapters/#2/related_work.tex'.
chktex: WARNING -- Unable to open the TeX file `chapters/#2/experimental_design.tex'.
chktex: WARNING -- Unable to open the TeX file `chapters/#2/results.tex'.
chktex: WARNING -- Unable to open the TeX file `chapters/#2/discussion.tex'.
```
The larger problem is that the watcher does not traverse the "chapters/" directory, nor any subdirectories.

```
[22:33:30] Manager.fileWatcher.getWatched: {"c: [...] root":["glossary.tex","main.tex"]}
[22:33:30] Manager.filesWatched: ["c: [...] root\\main.tex","c:\\ [...] root\\glossary.tex"]
```
(full filepath is abbreviated with [...])

I really *really* like the intellisense autocompletion for \ref and have used it heavily in the past. Unfortunately files that are dynamically included are not recognized as part of the root .tex, and as a result, any \labels in those figures or tables are not available for autocomplete (though, of course, figures and tables included in the root .tex still work fine).

This also has the effect of not triggering re-compile on save of any files in the \chapters subdirectories.

Manual inclusion with \include of chapters\model_details\introduction.tex updates the files being watched as well as makes the \ref autocomplete available for any \labels in root\chapters\model_details\introduction.tex, of course.

```
[23:08:15] Manager.fileWatcher.getWatched: {"c:\\ [...] root":["glossary.tex","main.tex"],"c:\\ [...] root\\chapters\\model_details":["introduction.tex"]}
[23:08:15] Manager.filesWatched: ["c:\\ [...] root\\main.tex","c:\\ [...] root\\glossary.tex","c:\\ [...] root\\chapters\\model_details\\introduction.tex"]
```

## Describe the solution you'd like

I don't think coding manager.ts to look for dynamically included files is reasonable, as there could be any number of strange implementations like mine. I think, however, that exposing the watch directories or allowing the list to be appended in settings would be _very helpful_. I don't necessarily know that this will allow \labels to be found in watched files, but I suspect this to be true.

## Desktop [Required]

 - OS: Windows 10.0.19043
 - VS Code version: 1.58.2
 - Extension version: 8.19.2
 - TeX distribution version: MiKTeX 2.9

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by jlelong** [comment]
The solution to your problem is to rely on the `.fls` file, see the second paragraph at https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-dependencies

Basically, you have to compile your project with `latexmk` or manually pass `-recorder` to your LaTeX compiler to produce a `.fls` file. Then, LW will use it to compute the exact list of included files.

**Comment by ggraham** [comment]
Fantastic, thank you! I'll adjust the ```latexmk``` call accordingly and preserve the .fls file(s) from cleanup.

Thanks for your time on this wonderful project!
