### ISSUE TITLE
Group of Suggestions

### ISSUE THREAD

**Issue by Balrrach** [James-Yu/LaTeX-Workshop#2806]
Hello. First I want to congratulate everyone who is working in the project because it makes for the best and cleanest way to currently write latex documents. I want to make a couple of suggestions that I'd like to see implemented in order for this project to be near to perfect. I'm going to  divide the suggestons in groups.

### Syntex Related Issues
1. **Direct Syntex Has Wrong Behabiour When Called From A Paragraph With a _Footcite_**: When Direct Syntex is called from a paragraph with a _footcite_ this makes the pdf focus on the footcite and not on the paragraph. I dpn't think this is the expected behabiour and is not the one presented in other LaTex editors like TexStudio. I think the correct behabiour shoud be to redirect to the paragraph and only if Direct Syntex is called upon a _footcite_ then redirect to the _footcite_ itself wich is the way it works in other LaTex editors.
2. **Reverse Syntex Is a Bit Slow**: This is a bit picky but Reverse Syntax is not instantaneous like Direct Syntax it takes halve a second for VS Code to reposition in the right line.

### PDF Viewer Related Issues
1. **Option to load the whole pdf**: The full PDF is never loaded into memory, only the current page and a few more before and after the current page. This causes loading icon when you quickly change to a different page that is far away from the current one, for example, when doing forward syntax from a piece of code that is far away from the current page being viewed. I know this is strongly related to the pdfViewer extension and I know this is made in order to reduce memory consumption but I think having the option to load the whole document is good.
2. **Zooming in/out with mouse wheel is too coarse/gross**: Contrary to zooming in/out with the touchpad results in big jumps in the view. I'd appreciate these to be reduced or have the possibility to adjust the sensibility.
3. **Custom PDF Viewer Tab size**: I don't know if this feature can be implemented. Currently when the pdf viwer is opened it occupies half the screen, I'd love to be able to set the size of such tab to a percentage having the pdf viewer to always open with a given tabsize.
4. **Links Are not Opened**: When I hover over a link to a webpage in the pfd it gets yellow but when I click on it doesn't get to open in the browser like in other LaTex editors. I think this is a desired behabiour.

### UI Related Issues
1. **Unclickable Preview Tab**: I think it doesn't make sense to be able to change current working tab to PDFViewer one because there is nothing to be done there. It is anoying when one unintentionally clicks on the preview and then uses the arrow keys hopping to change the pointer position in the text editor to see the pdf move up and down. Other LaTex editors don't allow to change the working tab to the preview.

### Compilation Related Issued
1. **Move Compilation Recepies To Dedicated Files**: I think It would be great to move compilation recipies to independent files with a format like json in order to untie them from VS Code. I think this is reasonable since different projects may have different compilation recipies and if I have to compile a project other person set I would have to create a recipe in VS Code just to compile that project in addiction to con having the option to take such configuration from the owner of the project who may very well be compiling in VS Code. What I'm asking is for compilation recepies to be defined in a given file just like they are in VS Code settings.json.

I know it is quite a few things but they are the only ones preventing this to becoming the best latex editor, at least for me.
Like I said congratullations to everyone who's involved in the project and thanks a lot.

**Comment by tamuratak** [comment]
> Syntex Related Issues 
> PDF Viewer Related Issues
> UI Related Issues

We can do nothing on our side.

> Compilation Related Issued

See https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

> You can also have different settings for each project with .vscode/settings.json at the root of each project workspace. See an official doc.

Please open one issue for one topic next time. Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
