### ISSUE TITLE
Direct Syntex Has Wrong Behabiour When Called From A Paragraph With a Footcite

### ISSUE THREAD

**Issue by Balrrach** [James-Yu/LaTeX-Workshop#2808]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Problem Description
When Direct Syntex is called from a paragraph with a footcite this makes the pdf focus on the footcite and not on the paragraph. I dpn't think this is the expected behabiour and is not the one presented in other LaTex editors like TexStudio. I think the correct behabiour shoud be to redirect to the paragraph and only if Direct Syntex is called upon a footcite then redirect to the footcite itself wich is the way it works in other LaTex editors

## To Reproduce  [Required]

1. Go to a paragraph with a footcite
2. Call Direct Syntex anywhere on that paragraph
3. Watch the pdf viewer move at the footcite instead of the paragraph

## Describe the solution you'd like  [Required]
Pdf viewer should move to the paragraph instead of the footcite when calling Direct Syntax  from anywhere in the paragraph except on the footcite.

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

I know this is related to the way the extension uses Syntex since this is not the way it works in the rest of the LaTex editors.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by Balrrach** [comment]
Entry fully updated

**Comment by tamuratak** [comment]
The search of SyncTeX is line-based. If TeXStudio treats the case well, TeXStudio would have implented some tweaks on their side. We won't implement them on our side.
