### ISSUE TITLE
[Suggestion] need support for multiple build behavior

### ISSUE THREAD

**Issue by fa93hws** [James-Yu/LaTeX-Workshop#281]
Hi
There is only one build behavior in the current version (ctrl + shift + B)
In order to include the cross reference and the bibliography, a chain of four steps are necessary.
While in most of the case, only one step is need since the .aux file and the .bbl file are remain unchanged.
Four steps takes too much time especially when writing a thesis.

It will be very appreciated if you could add another build behavior with another shortcuts and a option to make as the default build behavior ( so that when ctrl+s is triggered, only a build with one step is fired)

Thanks

**Comment by James-Yu** [comment]
That is the main reason why latexmk is recommended. You can refer to the readme for more info.

**Comment by fa93hws** [comment]
You are right, thanks
