### ISSUE TITLE
Zoom PDF with mouse scroll

### ISSUE THREAD

**Issue by liyuxuan3003** [James-Yu/LaTeX-Workshop#2810]
When I used your Internal PDF viewer, I tried to zoom in or zoom out the file with my mouse scroll. However, it is too sensitive, the zoom level will suddenly jump from 10% to 110% with just one move. In comparison, the buttons "+" , "-" in the PDF viewer and the hot keys "Crtl +" , "Crtl -" work well.

I noticed that it may have something to do with the Windows Settings of mouse. The setting of "Set the number of rows to scroll each time" on my computer is 3(It is the default value). When I changed it to 1, zoom with mouse scroll in your PDF viewer became much better, but the value 1 is too low for other use(Something like scrolling the web page).

So could you add a setting in your extension about the sensitivity of mouse scroll zooming in PDF viewer?

The extension version is v8.19.2.
The VSCode version is version 1.58.2(system setup).

**Comment by tamuratak** [comment]
I have found that zooming in or zooming out  with my mouse scroll does not work with PDF.js on Google Chrome 92. You can try https://mozilla.github.io/pdf.js/web/viewer.html

We can do nothing on our side.
