### ISSUE TITLE
Cannot Run the Preview in Linux VSCode

### ISSUE THREAD

**Issue by SmaranDhg** [James-Yu/LaTeX-Workshop#2811]
# VSCode report
```
Running the contributed command: 'latex-preview.showPreview' failed.

```

# Step done so far
- Freshly installed the LatexWorkshop
- Write simple document
```tex
\documentclass{report}
\begin{document}
\title{I want to be a Wombat}
\author{Carl Capybara}
\maketitle
\textbf{This text is typeset in bold}
This is some tex twiht \emph{emphasised words}
\end{document}

```
- While using `open preview` button in vscode give this error.

**Comment by tamuratak** [comment]
The command `latex-preview.showPreview` is not defined in LaTeX Workshop. It would be related to the extension, LaTeX Preview, https://marketplace.visualstudio.com/items?itemName=ajshort.latex-preview. Please uninstall LaTeX Preview.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
