### ISSUE TITLE
Add support for biblatex entries in Intellisense

### ISSUE THREAD

**Issue by caminsha** [James-Yu/LaTeX-Workshop#2813]
### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

While this great extension supports me in writing latex I have the problem that Intellisense does not have support for the biblatex entry types (i.e. online). It would be much easier to write the documents if Intellisense would support the Biblatex-entries.

## Describe the solution you'd like  [Required]

It would be nice to create the following two files for biblatex so that it will get supported by Intellisense:

- https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/bibtex-entries.json
- https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/bibtex-optional-entries.json

As some entries differ in their required and optional arguments (i.e. book) it would be the best way to create additional files. I think there should then also be a config option so that the user can decide if he'd like to use BIBTeX or biblatex.
For example there could be the following config option:
```
    "latex-workshop.intellisense.citation.backend": "",
```
The values could be `bibtex` and `biblatex` with `bibtex` as default to not break the workflow of some users.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Fedora 34
 - VS Code version: 1.58.2
 - Extension version: v8.19.2
 - TeX distribution version: texlive

### Are you using VSCodium?

Yes

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
If you provide that `biblatex-entries.json` and `biblatex-optional-entries.json` files, I can add `biblatex` intellisense support.

**Comment by caminsha** [comment]
Thanks for your answer. I'll start with the files and let you know when I finished with them.
