### ISSUE TITLE
Separate viewing of subfile pdf from viewing of root file pdf

### ISSUE THREAD

**Issue by kaba2** [James-Yu/LaTeX-Workshop#2814]
## Describe the solution you'd like  [Required]

Currently:

I have my Latex files divided into subfiles. When I choose "Latex Workshop: View Latex PDF file" from command palette, Latex Workshop always prompts me to choose whether I want to view the subfile PDF or the root file PDF. This is slightly frustrating, since the root file is almost never the right choice.

What would be nice:

Create two separate commands:
 * "Latex Workshop: View Latex PDF file"
 * "Latex Workshop: View Latex PDF file (root)"

The first command should act as if always choosing the subfile PDF. In the rare case that I want to open the root file PDF from a subfile, I would then go to the command palette and choose the second command.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS:  Windows 10
 - VS Code version:  1.58.2
 - Extension version: 8.19.2
 - TeX distribution version: MikTex 2.9.7338

**Comment by jlelong** [comment]
Set `latex-workshop.latex.rootFile.doNotPrompt` to `true`, see the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexrootfiledonotprompt).

**Comment by kaba2** [comment]
Thanks. That surely helps.

I still think that the "do not prompt" setting should be the default.
