### ISSUE TITLE
How to disable the auto-item feature

### ISSUE THREAD

**Issue by 1900011604** [James-Yu/LaTeX-Workshop#2818]
As my habit is:
```
    \begin{itemize}
        \item
        abcd

        \item
    \end{itemize}
```
I do not want the auto-item feature which produce an `\item` when I press the `Enter` key after an `\item` like this:
```
    \begin{itemize}
        \item abcd
        \item 
    \end{itemize}
```

**Which file should I edit to disable this feature?**

**Comment by jlelong** [comment]
Set `latex-workshop.bind.enter.key` to `false`. See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#itemize-like-environments).
