### ISSUE TITLE
Make `{` configurable as a suggestion trigger

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#2819]
I would like move `{` to the default value of `latex-workshop.intellisense.triggers.latex` because I  want to make `{` configurable as a suggestion trigger.

When we type `\b{` with the current `master`:

https://user-images.githubusercontent.com/10665499/127824766-bd3babdc-0259-4429-9d4d-8388072d68c3.mov

When disabling `{` as a suggestion trigger:

https://user-images.githubusercontent.com/10665499/127824971-6e1f1f5a-85bc-48f4-b9f6-8ebb97760437.mov

**Comment by jlelong** [comment]
Yes, why not.

Note that if you completely disable `{`,  some completion will not work so directly. For instance, typing `\cite{` will not pop up a list of citation keys but instead you will have to first accept `\cite{` as a suggestion and then you will get the list of citation keys. The same will happen with labels.
