### ISSUE TITLE
Option to disable building on save?

### ISSUE THREAD

**Issue by fantasticfears** [James-Yu/LaTeX-Workshop#282]
Can I request a feature that we have an optional which disable building on save? My XeTex is a hog which I would prefer use a shortcut key to build.

**Comment by James-Yu** [comment]
There is such a config. Pleas behave a check.

**Comment by rahulguptakota** [comment]
Just for anyone else searching, "onFileChange"/"latex-workshop.latex.autoBuild.run" is probably the config you are looking to change to "never".
