### ISSUE TITLE
Use latex-workshop.latex.outDir for __latexindent_temp.tex

### ISSUE THREAD

**Issue by gakada** [James-Yu/LaTeX-Workshop#2820]
I pointed `latex-workshop.latex.outDir` to `/tmp`, so that the working directory isn't populated by auxiliary files anymore; however, `__latexindent_temp.tex` is still [being created](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/latexformatter.ts#L164) in the working directory. Should it respect `latex-workshop.latex.outDir` (or some other configuration option) maybe? So that it is possible to have a clean working directory.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by gakada** [comment]
This is a minor feature request (not creating `__latexindent_temp.tex` in the working/file directory when `latex-workshop.latex.outDir` is specified, again, it is created [here](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/latexformatter.ts#L164)), so that information would be irrelevant.

**Comment by tamuratak** [comment]
Rejected.
