### ISSUE TITLE
Compiler support search

### ISSUE THREAD

**Issue by JoseRamos159** [James-Yu/LaTeX-Workshop#2824]
Supports Xelatex, luaLatex and PStricks ?. And if so, what would be the commands or steps to follow to achieve it?
I was trying to compile some Overleaf templates in VScode, but they were throwing errors. Please help.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes

Please ask at https://tex.stackexchange.com/ for further questions.

Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
