### ISSUE TITLE
Automatically open compiler log and go to Problems on compile error

### ISSUE THREAD

**Issue by jonwarneke** [James-Yu/LaTeX-Workshop#2826]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

No

## Describe the solution you'd like  [Required]

If the latex compiler terminates with an error, I'd like to automatically open the compiler log and go to "problems" so I can quickly see the issue, rather than having to click through that sequence.

## Logs [Required]

N/A

### LaTeX Workshop Output [Required]

N/A

### Developer Tools Console [Required]

N/A

## Screenshots

N/A

## Desktop [Required]

 - OS: macOS Big Sur 11.5.1
 - VS Code version: July 2021 (Version 1.59) (not insiders version)
 - Extension version: 8.19.0
 - TeX distribution version: TeX Live 2020 (MacTex)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
Not convinced. Rejected.
