### ISSUE TITLE
Questions about the implementation of the internal pdf viewer.

### ISSUE THREAD

**Issue by Haetsal-Lee** [James-Yu/LaTeX-Workshop#2832]
Is it required to open the another web server for its functionality? I wonder if there could be another implementation for the same  functionallity.(inverse search)

In fact, I want to use the extension with Code server.

I know there has been refused pull requests about making internal viewer to open on non local host urls.

I totally agree that there are security issues for exposing pdf viewer server.

I am just wonder that if the editor can communicate with the pdf viewer  just like language severs do.( I guess for the case of language server, the editor always initiate a commnucation?)

Thank you.

**Comment by tamuratak** [comment]
We need the web server for the `View in web browser` feature.

> If you want to preview the PDF file in a separated window, you can do that with the browser selecting View in web browser in the side bar.

- https://github.com/James-Yu/LaTeX-Workshop/wiki/View#viewing-the-pdf-file-generated-from-a-latex-project
