### ISSUE TITLE
div is "division", not "divergence"

### ISSUE THREAD

**Issue by 1900011604** [James-Yu/LaTeX-Workshop#2843]
In your `commands.json`, you say:
```
"div": {
    "command": "div",
    "detail": "∇ (divergence)"
```
But `\div` means the division mark ÷, which makes me confused.

![Screenshot_20210821_220934](https://user-images.githubusercontent.com/65082432/130324377-b67eff37-1d27-425f-994a-194085d2fc09.png)

**Comment by jlelong** [comment]
FYI, the `physics` package redefines `\div` as the divergence command. This is probably the cause of this wrong description.
