### ISSUE TITLE
command 'latex-workshop.onEnterKey' not found (again)

### ISSUE THREAD

**Issue by jemand771** [James-Yu/LaTeX-Workshop#2845]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Not applicable

## Describe the bug [Required]

Pressing enter inside the editor for a .tex file does not create a new line but rather shows the warning `command 'latex-workshop.onEnterKey' not found` in the bottom right corner.

### To Reproduce

1. Install extension from openvsx.com
2. create a new .tex file
3. inside that file, press enter

### Expected behavior

Enter key works as it should when typing normally

## Logs [Required]
The TeX pane on the left is not visible, even when a .tex file is opened.

### LaTeX Workshop Output [Required]
The TeX pane on the left is not visible, even when a .tex file is opened.

### Developer Tools Console [Required]

The only extension-related log message I see is:
```
Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/gitpod/.gitpod-code/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js'
Require stack:
- /ide/out/vs/loader.js
- /ide/out/bootstrap-amd.js
- /ide/out/bootstrap-fork.js.
$onExtensionActivationError @ mainThreadExtensionService.ts:95
```
However, that might be related to me reinstalling the extension a couple of times.

## Screenshots
Just to add some color to this issue, here's the little warning window :)
![image](https://user-images.githubusercontent.com/19669567/130576486-f32b121e-c3ca-4de6-96cd-8d63d04f6b09.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 20.04.2 LTS inside docker container (remote)
 - VS Code version: 1.58.2
 - Extension version: 8.20.2 (from [openvsx](https://open-vsx.org/extension/James-Yu/latex-workshop))
 - TeX distribution version: None (custom setup w/ texlive inside docker, not really applicable)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Not really - I don't have a local _and_ remote vscode installation, it's kind of remote-only (vscode in browser)

### Additional context

Since I can't see the TeX menu at all, this might be related to some other issues more important than pressing enter. Note that #961 / #903 are unrelated as I've disabled all other extensions. Also, #1193 and #2463 show the same error message but aren't a duplicate since they were windows-related.

This only started happening today, version 8.20.2 was released only a couple of hours ago to [openvsx](https://open-vsx.org/extension/James-Yu/latex-workshop), so I suspect that broke something. Unfortunately, I can't find 8.20.1 anywhere and don't know which version I was using previously. I can say that the issue does not exist in 8.19.2.

I find it slightly strange that this release came much later than the git corresponding git tag, not sure if that's normal (I can't see any auto-release workflows, so it might be expected).

Another weird thing: I've compiled the extension myself (current master aswell as 8.20.2 tag) and the issue doesn't exist with either of those versions. I think something may be wrong with the openvsx release.

Lastly, I think the keyboard debug output would be helpful:

```
[2021-08-24 09:44:01.517] [window] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: NumpadEnter, keyCode: 13, key: Enter
[2021-08-24 09:44:01.522] [window] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: NumpadEnter, keyCode: 3 ('Enter')
[2021-08-24 09:44:01.555] [window] [info] [KeybindingService]: | Resolving Enter
[2021-08-24 09:44:01.564] [window] [info] [KeybindingService]: \ From 25 keybinding entries, matched latex-workshop.onEnterKey, when: acceptSuggestionOnEnter && config.latex-workshop.bind.enter.key && editorTextFocus && !editorReadonly && !suggestWidgetVisible && !vim.active && editorLangId =~ /latex|rsweave|jlweave/, source: user extension James-Yu.latex-workshop.
```

For now, I can just disable `config.latex-workshop.bind.enter.key` or delete the shortcut entirely to get enter working again. However, that's more of a workaround than a fix.
(I don't use the TeX menu at all, so the fact that that's missing isn't a problem for me. I merely use LaTeX workshop for its syntax highlighting and pdf viewer)

**Comment by 8hur** [comment]
I have the same issue (Ubuntu 20.04)

**Comment by hpiedcoq** [comment]
Same here : 
command 'latex-workshop.build' not found

using codium, under ubuntu.

**Comment by jemand771** [comment]
@8hur can you please post some more info about your setup? I was worried that it's related to my remote setup (gitpod.io has previously been frowned upon by the latex-workshop maintainers, #2772 ).

**Comment by tamuratak** [comment]
Please report to https://github.com/open-vsx/publish-extensions/issues

The `James-Yu.latex-workshop-8.20.2.vsix` file at open-vsx does not include `extension/out/src/main.js`. The file is invalid. And, we don't publish the file at open-vsx. They publish the file independently of us.

We don't support GitPod and VSCodium. We recommend you to use VS Code.

**Comment by tamuratak** [comment]
open-vsx/publish-extensions/issues/414
