### ISSUE TITLE
How to combine build and view?

### ISSUE THREAD

**Issue by ShuhuaGao** [James-Yu/LaTeX-Workshop#2854]
I am an old user of TeXStudio, which has a handy button called "Build & View (F5)". In LaTeX Workshop, how can I combine the two operations?  

I want to set up a shortcut (e.g., F6) such that the tex files are first built (normally ctrl+alt+B) and then the PDF is displayed in an external viewer (normally ctrl + alt + V). I can execute the two operations separately now, but I want to run them in a sequence automatically.

**Comment by tamuratak** [comment]
Not, you cannot.

Out of the scope of the extension.
