### ISSUE TITLE
Syntax highlighting for cite keys with dash

### ISSUE THREAD

**Issue by byteSamurai** [James-Yu/LaTeX-Workshop#2855]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Paperpile creates cite keys with dashes, like this one:
```
\cite{Bass2021-ih}
```
The dash ist not highlighted, though it seems to be legit, to have a dash in a cite key according to [this StackExchange](https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys).

At the moment it looks like:
![image](https://user-images.githubusercontent.com/6654064/132025289-e401968b-07e2-4955-89fc-27058d79e14a.png)

### To Reproduce

1. create a `.tex`-file
2. add `\cite{Bass2021-ih}` or some other citation with a dash somewhere in the file

### Expected behavior

Dashes are recognised as part of the citation key, like here:
![image](https://user-images.githubusercontent.com/6654064/132025583-972a8997-0dd9-476f-9fb9-805f35eca9dc.png)

### LaTeX Workshop Output [Required]
...cmon, it is just cosmetic 😄 

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

I will send a PR

**Comment by byteSamurai** [comment]
@jlelong Sorry, did I bother you somehow?

**Comment by byteSamurai** [comment]
Oh, sorry, I see you fixed it yourself. Sorry for the noise. Have a nice day :)

**Comment by jlelong** [comment]
It was actually easier to fix myself than to alter your PR. Thanks for reporting the issue and trying to make a PR.
