### ISSUE TITLE
Feature suggestion: Outline remembers which entires have been collapsed

### ISSUE THREAD

**Issue by tbrodbeck** [James-Yu/LaTeX-Workshop#2858]
Would be cool if the outline would remember the collapsed/uncollapsed display of entries after reopening.

## Desktop
Extension Version: v8.20.2

**Comment by jlelong** [comment]
It is a limitation of vscode, see https://github.com/microsoft/vscode/issues/53262 and it is out of the scope to implement it inside the extension for the TeX panel
