### ISSUE TITLE
Problem with the real-time math preview

### ISSUE THREAD

**Issue by eidimohammadreza** [James-Yu/LaTeX-Workshop#2859]
Hi, 

It seems that the real-time math preview does not work properly when external packages (such as physics) are used for writing an equation. Could you please help me enabling the correct preview? 

For example, $\mel{\psi}{x}{\psi}$ should show the expectation value of x in the preview 
![Screenshot_20210906_145608](https://user-images.githubusercontent.com/26275291/132220852-ab87a94e-cfd4-411b-81cb-45dd10a5f3b7.png)
but it shows
![Screenshot_20210906_145211](https://user-images.githubusercontent.com/26275291/132220462-87781c7d-6621-4e56-b3d0-f0eca67ef5ba.png).

please note that you need to add \usepackage{physics}

Thanks so much in advance.

**Comment by jlelong** [comment]
This is related to #2614. 
Real time preview is rendered by mathjax, which cannot load LaTeX packages. Unfortunately, we can do nothing on our side.
