### ISSUE TITLE
Print from PDF preview supported?

### ISSUE THREAD

**Issue by mcoweber** [James-Yu/LaTeX-Workshop#286]
Hi,

just in informal question: Is printing from the PDF preview (within VS Code) supported?
When I click on the print button "prepareing document for printing" shows up, but nothing happens.

Best regards
Marc

**Comment by James-Yu** [comment]
Hmm that's interesting. I have never tried that function. A brief investigation has the following observations:
- This function depends on the build-in printing feature of the hosting environment.
- It seems that VSCode doesn't have such an interface, therefore printing won't work within vscode tabs.
- `View in web page` works as expected.

I would classify this issue as an improvement. The extension should be adaptive and provide printing only when opened in new browser tabs. That is what comes into my mind on solutions.
