### ISSUE TITLE
How to show the building time consumed in total?

### ISSUE THREAD

**Issue by hellojialee** [James-Yu/LaTeX-Workshop#2860]
After I upgrade the VSCode from an old version, LaTeX-Workshop does not show the compiling time anymore.

**Comment by tamuratak** [comment]
See #2652

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
