### ISSUE TITLE
Some log message can not be excluded

### ISSUE THREAD

**Issue by Youguang** [James-Yu/LaTeX-Workshop#2863]
## Describe the bug

The problems panel shows "empty key" BibTex warning for bib references with key contains Chinese, for other bib references no problem. I want to exclude this log message, but it did not work, while I can use `latex-workshop.message.latexlog.exclude` to prevent `Font` related messages.

### To Reproduce

```
@article{肖水源_1994_995,
   author = {肖水源},
   title = {社会支持评定量表的理论基础与研究应用},
   journal = {临床精神医学杂志},
   volume = {4},
   number = {2},
   pages = {98-100},
   year = {1994},
   type = {Journal Article}
}
```

### Message

```
{
	"resource": "/Users/notshown/Biblio/ref.bib",
	"owner": "BibTeX",
	"severity": 4,
	"message": "empty key",
	"source": "BibTeX",
	"startLineNumber": 580,
	"startColumn": 1,
	"endLineNumber": 580,
	"endColumn": 65536
}
```

### And `latex-workshop.message.latexlog.exclude` could not prevent this message

```
    "latex-workshop.message.latexlog.exclude": [
        "Font",
        "empty"
    ],
```

## Desktop

 - OS: Mac OS Big Sur
 - VS Code version: 1.60.0
 - Extension version: 8.20.2
 - TeX distribution version: TeX Live 2020

**Comment by jlelong** [comment]
The new configuration variable [`latex-workshop.message.bibtexlog.exclude`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessagebibtexlogexclude) has been added.
