### ISSUE TITLE
 File associations are all pdf

### ISSUE THREAD

**Issue by LuckyPick** [James-Yu/LaTeX-Workshop#2864]
After installing the new version, clicking on the .tex file cannot be previewed and displayed as “Latex Workshop PDF Viewer is opening a PDF file",then automatically close the tab.

Extension version: 8.20.2
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by LuckyPick** [comment]
Sorry to interrupt you, I have solved the problem, the problem occurred when using the plugin for the first time, vscode provided wrong file association settings like this 
![image](https://user-images.githubusercontent.com/30816201/132936079-3593fded-5c02-4d85-92fd-180c136c8741.png)
Thanks again for your reply. @tamuratak
