### ISSUE TITLE
OpenVSX

### ISSUE THREAD

**Issue by daiyam** [James-Yu/LaTeX-Workshop#2865]
Hi @James-Yu,

The recent version of your extension is broken on OpenVSX (https://open-vsx.org/extension/James-Yu/latex-workshop) due to missing.
I understand that you are not responsible for the issue. But could you directly deploy your extension?

Related issues: https://github.com/VSCodium/vscodium/issues/486 https://github.com/VSCodium/vscodium/issues/839

PS: You should also look into https://github.com/vercel/ncc to compile your extension into a single file. It would simplify the deployment.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#vscodium-is-not-officially-supported

> VSCodium is not officially supported. We do not help to resolve issues related to VSCodium.

**Comment by tamuratak** [comment]
Duplicate of #2845
