### ISSUE TITLE
Toolchain returns with error: 1/null

### ISSUE THREAD

**Issue by lonaparte** [James-Yu/LaTeX-Workshop#287]
### Description

Hello, after installation, first time I run "Build LaTeX project", it works well. But after a little of modification, the second time I run the same code, it doesn't work. I am sure that the code in the two times are the same. It shows that Toolchain returns with error: 1/null. It seems that after one time of error, I have to reinstall the tool LaTeX Workshop, or I can not build a project, even if there is no error.

### How to reproduce

1. Run "Build LaTeX project"
2. Modify a little in the tex code, run "Build LaTeX project", there is some errors; and than recover to the origin. 
3. Rerun "Build LaTeX project"

### Expected behavior

Show the same results like the first time, produce a pdf file.
### Actual behavior

Toolchain returns with error: 1/null
### Log messages

(d:/Software/Latex/texlive/2017/texmf-dist/tex/latex/csquotes/csquotes.def
File: csquotes.def 2017/03/11 v5.2b csquotes generic definitions (JAW)
)
Package csquotes Info: Trying to load configuration file 'csquotes.cfg'...
Package csquotes Info: ... configuration file loaded successfully.

(d:/Software/Latex/texlive/2017/texmf-dist/tex/latex/csquotes/csquotes.cfg
File: csquotes.cfg 
)
Package csquotes Info: Enabling multilingual quotes.
))
! Emergency stop.
<*> .../Codes/rapportECL_template/Template_ECL.tex
                                                  
*** (job aborted, no legal \end found)

 
Here is how much of TeX's memory you used:
 23263 strings out of 493005
 521205 string characters out of 6131656
 703519 words of memory out of 5000000
 27083 multiletter control sequences out of 15000+600000
 6638 words of font info for 16 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 47i,0n,51p,10446b,3426s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.

<details>
<summary>LaTeX Workshop Output</summary>

Building root file: e:\Onedrive\Documents\Lonaparte-PC\Codes\rapportECL_template\Template_ECL.tex
[11:31:30] Build root file e:\Onedrive\Documents\Lonaparte-PC\Codes\rapportECL_template\Template_ECL.tex
[11:31:30] Toolchain step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,e:\Onedrive\Documents\Lonaparte-PC\Codes\rapportECL_template\Template_ECL
[11:31:32] Toolchain returns with error: 1/null.
[11:31:37] Root file remains unchanged from: e:\Onedrive\Documents\Lonaparte-PC\Codes\rapportECL_template\Template_ECL.tex.
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information

My parametre is:

"latex-workshop.latex.toolchain": [
        {
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOC%"
            ]
        },
        {
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        },
        {
            "command": "xelatex",
            "args": [
                "--synctex",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "command": "xelatex",
            "args": [
                "--synctex",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }
    ],

**Comment by lonaparte** [comment]
Even if I want to build the most simple project like this:

\documentclass[oneside,a4paper,11pt]{article}
    \begin{document}
        %文章标题
        \title{\LaTeX教学笔记}
        %文章作者
        \author{张三}
        %生成标题页的命令
        \maketitle
        %居中
        \begin{center}
                这会是一本神奇的书
        \end{center}
    \end{document}

The output is the same: Toolchain returns with error: 1/null

**Comment by James-Yu** [comment]
```
Package csquotes Info: Enabling multilingual quotes.
))
! Emergency stop.
<*> .../Codes/rapportECL_template/Template_ECL.tex
```

From the LaTeX log you provided, it seems that there's some problem with the compiler instead of the extension. Does tailor-made `latexmk` command work for you? Is this problem reproducible from command line prompt?

**Comment by liz282907** [comment]
i met the same problem, but i can call the xelatex in the terminal. any idea of solving the problem?

**Comment by XiaojiaZhang** [comment]
I can use the pdflatex to compile the .tex file, however when change to xelatex, there is a error message that:"Toolchain terminated with the fatal error", both pdflatex and xelatex work well in the terminal
