### ISSUE TITLE
8.20.2 no longer works on vscodium (command 'latex-workshop.build' not found)

### ISSUE THREAD

**Issue by l1ving** [James-Yu/LaTeX-Workshop#2871]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes/No

Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

Yes

## Describe the bug [Required]

`command latex-workshop.<anything> not found`
 
### To Reproduce

1. Run any latex-workshop command, such as  building

### Expected behavior

It works fine

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

There is no TeX icon
```

### Developer Tools Console [Required]

```
workbench.desktop.main.js:2036 Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/liv/.vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js'
Require stack:
- /usr/share/vscodium-bin/resources/app/out/vs/loader.js
- /usr/share/vscodium-bin/resources/app/out/bootstrap-amd.js
- /usr/share/vscodium-bin/resources/app/out/bootstrap-fork.js.
$onExtensionActivationError @ workbench.desktop.main.js:2036
workbench.desktop.main.js:749 Error: command 'latex-workshop.build' not found
    at g._tryExecuteCommand (workbench.desktop.main.js:1523)
    at workbench.desktop.main.js:1523
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async P.runAction (workbench.desktop.main.js:174)
    at async P.run (workbench.desktop.main.js:174)
    at async u.onClick (workbench.desktop.main.js:664)
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Arch
 - VS Code version: `vscodium-bin 1.59.1-1`
 - Extension version: `8.20.2`
 - TeX distribution version: Unsure how to get this

### Are you using VSCodium?

Yes/No

Yes

### Are you using the Snap or Flatpack versions of VS Code?

Yes/No

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Referenced in open-vsx/publish-extensions#163 and #469. Was previously fixed on a much older version.

**Comment by l1ving** [comment]
Nevermind, I just saw that vscodium is no longer supported for whatever reason.

**Comment by tamuratak** [comment]
Duplicate of #2845
