### ISSUE TITLE
Setting to disable occurence highlighting

### ISSUE THREAD

**Issue by luc-j-bourhis** [James-Yu/LaTeX-Workshop#2873]
## Preliminary questions [Required]

Is there a way to disable occurence highlighting only for the file types handled by the LaTeX-Workshop extension? If not it would be nice!

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

Clicking on a word (single-click) makes it highlighted, and so do all other occurences of it in the file. This is distracting and totally useless most of the time (c.f. the example for the word "in" in the attached screenshot). This feature makes sense for programming languages to highlight all occurences of a variable for example, but for writing text in LaTeX, it is not. 

## To Reproduce  [Required]

1. Open any TeX or LaTeX file
2. Click on any word in the text
3. Notice how it is highlighted and so are all its occurences

## Describe the solution you'd like  [Required]

One can disable occurence highlighting overall in VS Code by using `editor.occurrencesHighlight` or by tweaking `editor.selectionHighlightBackground` and `editor.selectionHighlightBorder` but I would like a more fine-grained solution. At least the equivalent of `occurrencesHighlight` but only applied to file types of the TeX world.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Screenshots

![Screenshot 2021-09-20 at 12 33 13](https://user-images.githubusercontent.com/295281/133990721-995eb434-eab3-4d14-abe3-9785321a5eda.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: MacOS 10.14.6
 - VS Code version: 1.60.1
 - Extension version: 8.20.2
 - TeX distribution version: n/a

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment]
See https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings

```json
    "[latex]": {
        "editor.occurrencesHighlight": false
    },
```
