### ISSUE TITLE
Latexindent command can't work in vscode

### ISSUE THREAD

**Issue by Vincent0706** [James-Yu/LaTeX-Workshop#2875]
I want to set a different command for latexindent on vscode. 
There is my config.
~~~
"latex-workshop.latexindent.args": [
        "-m %DOC_EXT% -o %DOC_EXT% -l D:\\LaTex\\latexindent\\textwrap.yaml",
        "-c",
        "%DIR%/",
        "%TMPFILE%",
        "-y=defaultIndent: '%INDENT%'"       
    ],
    "latex-workshop.latexindent.path": "D:\\LaTex\\latexindent\\latexindent.exe"
~~~
![image](https://user-images.githubusercontent.com/82581024/134193639-747a86af-1326-428d-8cf4-db55de74b4a8.png)

But when I try to format the code, the result is still the defualt.

https://user-images.githubusercontent.com/82581024/134194169-c41af638-c705-422d-a355-feb5b670638b.mp4

You can find that the code can be formated as the defualt config. And when I use the command `f:/CodeTest/latex/Untitled-1.tex -o f:/CodeTest/latex/Untitled-1.tex -l D:\LaTex\latexindent\textwrap.yaml,-c,f:/CodeTest/latex/,f:/CodeTest/latex/__latexindent_temp.tex,-y=defaultIndent: '    '` in the cmd or terminal, latexindent can format the code with my config. (The command is from the vscode output)
![image](https://user-images.githubusercontent.com/82581024/134194932-6cd78bce-9ce5-4648-b601-6985b5b0a48a.png)

**Comment by jlelong** [comment]
Every entry `latex-workshop.latexindent.args` must be a single argument. You need to split `"-m %DOC_EXT% -o %DOC_EXT% -l D:\\LaTex\\latexindent\\textwrap.yaml"` into 

```
"-m",
"%DOC_EXT%",
"-o",
"%DOC_EXT%",
"-l",
"D:\\LaTex\\latexindent\\textwrap.yaml"
```

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
