### ISSUE TITLE
Dispatch issue for pdf viewer

### ISSUE THREAD

**Issue by mly32** [James-Yu/LaTeX-Workshop#2877]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Using `keyCode` as the dispatch makes shortcuts in the pdf viewer not work.

### To Reproduce

1. Use the following settings:
```jsonc
"keyboard.dispatch": "keyCode", // breaks pdf keyboard bindings
"latex-workshop.viewer.pdf.internal.keyboardEvent": "force",
```
2. Click on a pdf within VSCode
3. Try any shortcut (ex. `Ctrl-W` or `Ctrl-Shift-P`

### Expected behavior

Shortcuts should work when the pdf view is focused. It does work when the keyboard dispatch mode is not set to key code.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

There are no logs because this is a problem with the pdf viewer.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

- OS: Linux x64 5.11.0-36-generic
- VS Code version: 1.60.1
- Extension version: 8.20.2
- TeX distribution version: TeX 3.141592653 (TeX Live 2021)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

I am using key code dispatch because I have CAPS and ESC keys swapped.

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.
