### ISSUE TITLE
Activate extension when workspace contains .tex files

### ISSUE THREAD

**Issue by likeadoc** [James-Yu/LaTeX-Workshop#2878]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe.

LaTeX-Workshop currently does not autoload upon opening a LaTeX Workspace in VS Code - the extension only loads when a LaTeX file is opened.  

## To Reproduce 

1. Close all VS Code instances
1. Open a Latex workspace in VS Code
3. LaTeX Workshop only loads when opening a .tex file inside the workspace

## Describe the solution you'd like  [Required]

This could be implemented by adding the `workspaceContains` activation event directive to package.json - i.e `"workspaceContains:**/*.tex"`.

## Desktop

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Manjaro Linux
 - VS Code version: 1.60.2-1
 - Extension version: 8.20.2
 - TeX distribution version: Tex Live 2021.58710-2

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
> LaTeX-Workshop currently does not autoload upon opening a LaTeX Workspace in VS Code - the extension only loads when a LaTeX file is opened.

What is your use case? What is the advantage of activating the extension before opening a LaTeX file?

**Comment by tamuratak** [comment]
No response. Close.
