### ISSUE TITLE
Support for plain TeX files

### ISSUE THREAD

**Issue by ykis-0-0** [James-Yu/LaTeX-Workshop#2879]
Does this extension support plain TeX files? I tried but it seems like I wasn't able to find any information about using this extension with TeX rather than LaTeX. And if it isn't supported now would this be a correct feature request? Thank you very much.

**Comment by tamuratak** [comment]
Out of the scope of the extension.

**Comment by jlelong** [comment]
Actually, we provide syntax highlighting for plain TeX files. Use the `TeX` language type.
What features would you expect for plain TeX files?

**Comment by ykis-0-0** [comment]
I need only some basic features right now, like:
- Syntax highlighting as you mentioned above
- Suggestions for primitives like `\def` (and possibly for the plain TeX macros like	`\rlap`)
- Ways to hide LaTeX definitions from showing up as suggestions
- Default recipes to compile those documents without LaTeX, when I specify the document as "TeX" in VS Code
