### ISSUE TITLE
Add config to disable command surrounding feature. (backslash lead to unexpected dialog)

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#288]
Sometimes, after entering in a backslash, a dialog "Press ENTER to surround previous selection with selected commamd" will show.

### How to reproduce

1. Type in some commands like `\documentclass`, then use TAB to auto-complete it as `\documentclass{<class>}`.
2. Enter a backslash in the `<class>`, then something unexpected will show at the top of editor.

### Expected behavior

The backslash `\` should be normally typed in.

### Actual behavior

![vscode](https://user-images.githubusercontent.com/18233088/31318250-ca441a6a-ac81-11e7-9550-a5d47cf05aef.gif)

### Additional Information

**VS code**: version 1.17.0
**LaTeX-Workshop**: version 3.5.5

**Comment by James-Yu** [comment]
This works as intended. When there is a selection, backslash will try to surround the selected content with LaTeX commands. You may remove the selection with backspace and then `\` to insert command.

I know this is somehow misleading. However, I cannot come up with a better invoke method for the command surrounding feature.

**Comment by Iw1s** [comment]
**_Can you think of another way to invoke this or provide us with a setting to disable this feature?_**  
Personally, I don't use it at all, but find myself replacing text via selection very often. Thus, the quick selection pops up and everytime this happens I'm forced to press `ESC` to hide it.  
Currently I just edited `command.js` in `out\src\providers\completer` to remove this feature entirely.

**Comment by James-Yu** [comment]
I would figure this as a reasonable feature request. Will do soon.

**Comment by zachjweiner** [comment]
Thanks for implementing this. Could you possibly add a similar option for autocompletion of `$'s for mathmode, braces, etc?

**Comment by James-Yu** [comment]
That is not possible with the current vscode API. They are implemented using a different pattern than command completion. The said completion is actually named `pairing`.

**Comment by bernhard-hoerl** [comment]
Thanks for this option!

**Comment by mattecapu** [comment]
Thank you!
