### ISSUE TITLE
External viewer %PDF% without extension

### ISSUE THREAD

**Issue by fulviof79** [James-Yu/LaTeX-Workshop#2882]
## Preliminary questions [Required]
Is it possible to have a variant of %PDF% that expands without ext? as in %DOC%. Or to let %DOC% , %DOCFILE% etc to expand in latex-workshop.view.pdf.external.viewer.args.
I would like to use the external viewer to open a second pdf that i compile with -jobname and that add -sol.pdf 

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes/No

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

## To Reproduce  [Required]

3. See error

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.41.0]
 - Extension version: [e.g. 8.5.0]
 - TeX distribution version: [e.g. TeX Live 2019/MiKTeX 2.9.7250]

### Are you using VSCodium?

Yes/No

### Are you using the Snap or Flatpack versions of VS Code?

Yes/No

### Are you using LaTeX Workshop with VS Code Remote?

Yes/No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment]
The external PDF viewer function is not officially supported. We don't add features to that.

https://github.com/James-Yu/LaTeX-Workshop/wiki/View#external-pdf-viewer

> This function is not officially supported.

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
