### ISSUE TITLE
Call other extensions to format `r` code in `Rnw` files

### ISSUE THREAD

**Issue by sukanka** [James-Yu/LaTeX-Workshop#2883]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

I find that the formatter doesn't work for `r` code blocks in `rnw` files. All `r` codes are aligned abnormally, not as elegant as it is in an R script.

Here are two example files, `main.r` is formatted as follows:
```R
#main.r
price <- function(x) {
    return(x$Close)
}
simpleReturn <- function(x) {
    x$pdiff <- diff(x$Close)
    x$srtn <- x$pdiff / x$Close
    return(x$srtn)
}
logReturn <- function(x) {
    return(diff(log(x$Close)))
}
```
But in `main.rnw`, it is formatted like below. The `return` and `}` are not aligned properly. The output pdf is, thus, a little strange.
![image](https://user-images.githubusercontent.com/31362108/135021514-7adbdb0f-fe7b-4b3f-afba-513deb3d9887.png)
Besides, code like `x=5+6` will be formatted as `x <- 5 + 6` in `r` code, but LaTeX work shop won't do this job currently.
```latex
% main.rnw
\documentclass{article}

\begin{document}
<<>>=
price <- function(x) {
        return(x$Close)
    }
simpleReturn <- function(x) {
        x$pdiff <- diff(x$Close)
        x$srtn <- x$pdiff / x$Close
            return(x$srtn)
    }
logReturn <- function(x) {
        return(diff(log(x$Close)))
    }
@
\end{document}
```
## Describe the solution you'd like  [Required]

I'd like LaTeX Workshop to call other extensions to format code blocks in `rnw` files, for example, [vscode-R](https://github.com/REditorSupport/vscode-R).

Currently, I use vscode-R to format my code, and then paste it into my rnw file.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: archlinux
 - VS Code version: 1.60.2
 - Extension version: v8.20.2
 - TeX distribution version: TeX Live 2021

### Are you using VSCodium?

No
### Are you using the Snap or Flatpack versions of VS Code?

No
### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
Out of the scope of the extension.
