### ISSUE TITLE
Highlighting `pycode` env breaks when using command in argument.

### ISSUE THREAD

**Issue by real-yfprojects** [James-Yu/LaTeX-Workshop#2885]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

- [x] I still see this issue when disabling all the other extensions and restart vs code
- [x] I visited the wiki.

## Describe the bug [Required]

When using a `pycode` environment the python code is highlighted like python code which is
great. The problem is that the highlighting will break when I pass a mandatory argument using a command to the environment.

```latex
Here everything is normal. \LaTeX commands are highlighted normally.

\begin{pycode}{\test}
    def Test:
        pass
\end{pycode}

class Python Highlighting is still enabled. \LaTeX Commands turn red.
Not usable.
```
![grafik](https://user-images.githubusercontent.com/62463991/135132395-48c50df7-ec83-415b-bd84-0287d4be46b0.png)

### To Reproduce

1. Enter the above latex code into a latex file.
2. Compare to using square brackets instead of the curly brackets (works fine)
3. Compare to removing the argument (works fine)

### Expected behavior

I expect that the highlighter returns to latex mode after leaving the environment. 
It should also highlight arguments as latex code.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[:10:21] Linter for root file started.
[:10:21] Linter for root file running command chktex with arguments ["-wall","-n22","-n30","-e16","-q","-f%f:%l:%c:%d:%k:%n:%m\n","latex/template.tex"]
[:10:21] Linter for root file failed with exit code 2 and error:
[:10:21] The .chktexrc file not found.
[:10:21] Linter log parsed with 39 messages.
[:10:21] Linter for active file started.
[:10:21] Linter for active file running command chktex with arguments ["-wall","-n22","-n30","-e16","-q","-I0","-f%f:%l:%c:%d:%k:%n:%m\n"]
[:10:21] Linter for active file failed with exit code 2 and error:
[:10:21] The .chktexrc file not found.
[:10:21] Linter log parsed with 2 messages.
```
The log messages are the same when the issue is not happening.

### Developer Tools Console [Required]

```
Nothing.
```

## Desktop

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Linux x64 5.4.0-88-generic snap (Ubuntu)
 - VS Code version: 1.60.2
 - Extension version:  8.20.2
 - TeX distribution version: TeX Live 2019/Debian

### Are you using the Snap or Flatpack versions of VS Code?
Yes snap

**Comment by real-yfprojects** [comment]
Thank you @jlelong! When will this fix be released?

**Comment by jlelong** [comment]
This will be included in the next release, probably by the end of October.
