### ISSUE TITLE
Activate extension when workspace contains .tex files

### ISSUE THREAD

**Issue by likeadoc** [James-Yu/LaTeX-Workshop#2888]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

This is a duplicate of [!2878](https://github.com/James-Yu/LaTeX-Workshop/issues/2878), which unfortunately got closed before I was able to comment.
Latex -Workshop currently does not autoload upon opening a LaTeX Workspace in VS Code - the extension only loads when a LaTeX file is opened.

## Use Case:
When opening a multi level Latex workspace and working on non .tex files (e.g. bibliography, media data, graphs etc.) I want to be able to build my project without opening a .tex file first.

## To Reproduce  [Required]

1. Close all VS Code instances
2. Open a Latex workspace in VS Code
3. LaTeX Workshop only loads when opening a .tex file inside the workspace

## Describe the solution you'd like  [Required]
Can be implemented by adding a single  workspaceContains activation event directive to package.json - i.e "workspaceContains:**/*.tex".

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

OS: Manjaro Linux
VS Code version: 1.60.2-1
Extension version: 8.20.2
TeX distribution version: Tex Live 2021.58710-2

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
Rejected.

We don't want to activate the extension when not necessary.

If you open a `.bib` file and other related files, the extension is to be activated. See

https://github.com/James-Yu/LaTeX-Workshop/blob/0dd0eaf304a9504be78567cb1f2bf0760b939a16/package.json#L28-L53

If not activated, it is a bug. Please open a new issue.

You can also activate the extension by executing VS Code commands in the above list.
