### ISSUE TITLE
Citation browser can not handle new lines in bib entries properly

### ISSUE THREAD

**Issue by nujabse** [James-Yu/LaTeX-Workshop#2889]
## Preliminary questions
My .bib file has a lot of new lines, because it has a fixed line width, just looks like this: 
![image](https://user-images.githubusercontent.com/9455367/135423192-205db2fb-2e15-4d3e-a1aa-f406cbb207d6.png)
This poses a visual problem when I set the citation completion to "browser", because in the citation browser, only part of the title would be displayed, especially for very long titles:
![image](https://user-images.githubusercontent.com/9455367/135423633-0c4e415a-773a-4757-a053-eb6a168299b5.png)

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. 

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

The citation browser can not strip the unnecessary new line in the bib entry, making the ciation browser messy.

## To Reproduce  [Required]

1. run "Latex Workshop: Open citation browser" in the command pallete.

## Describe the solution you'd like  [Required]

Properly remove the new line symbl "\n" when parsing the titles of a bib entry

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Mac OS 11.6
 - VS Code version: 1.60.2
 - Extension version: v8.20.2
 - TeX distribution version:  TeX Live 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Would not it be sufficient to trim strings? see [stackoverflow](https://stackoverflow.com/a/5568828) for a concise way of doing it. @tamuratak your opinion?

For what it is worth, I do believe that using hard wrapping is somehow against VSCode natural way of (soft) wrapping text. See `editor.wordWrapColumn`.

**Comment by nujabse** [comment]
Thanks for the reply. I think maybe I can trim my bib file to avoid this problem.
