### ISSUE TITLE
Extract recipe for build script

### ISSUE THREAD

**Issue by AlastarFrost** [James-Yu/LaTeX-Workshop#2890]
I have been using LatexWorkshop to build my latex projects so far.

Now I want to automate my build process using a CI script.

Is there a way to extract the build script with all parameters from Latex Workshops recipe?

I want my build script to work exactly the same as the recipe in Latex Workshop, so that builds on local machines behave the same as builds in the CI.

Maybe this seems trivial, but I have never really built the latex document on command line.

If this script could be autogenerated by a button, that would be a great feature. Tweaking it from there should be easy enough to transfer it to a different enviroment.

**Comment by jlelong** [comment]
Out of the scope of the extension.

The default recipe does nothing more than calling `latexmk`.
