### ISSUE TITLE
LaTeX outline does not update on saving of tex file

### ISSUE THREAD

**Issue by ekzhang** [James-Yu/LaTeX-Workshop#291]
### Description
When adding a section or subsection to a LaTeX file and saving it, the outline does not change. It only updates to reflect the new document structure after closing and reopening the file.

### How to reproduce

1. Make a new .tex file, with some code.
2. Add or remove a \section or \subsection in the file.
3. Save.

### Expected behavior

I would expect the outline to update with every save of the file.

### Actual behavior

The outline only updates when the file is closed and reopened.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information

VS Code version 1.17.1, running on macOS Sierra 10.12.6

**Comment by James-Yu** [comment]
I can recall that this problem was resolved in previous commits. Can you please provide the extension log messages, especially when removing sections and saving? It is critical for me to debug what's wrong with the process.

**Comment by James-Yu** [comment]
The content tree can be correctly parsed, but the new tree is not updated. I will check API for possible solutions.

**Comment by ekzhang** [comment]
@James-Yu Here are the log messages in `output` from opening a simple latex file with four sections, deleting the last one, and saving it. The outline does not update to reflect that the fourth section is gone.

> [20:42:52] Initializing LaTeX Workshop.
> [20:42:52] Creating LaTeX Workshop http and websocket server.
> [20:42:52] LaTeX Workshop initialized.
> [20:42:52] Found root file from active editor: /Users/ezhang/Documents/test/test.tex
> [20:42:52] Root file changed from: undefined. Find all dependencies.
> [20:42:52] Instatiating new file watcher for /Users/ezhang/Documents/test/test.tex
> [20:42:52] Parsing /Users/ezhang/Documents/test/test.tex
> [20:42:52] Server created on 127.0.0.1:56588
> [20:42:52] Default environments loaded
> [20:42:52] LaTeX Workshop version: 3.5.5
> [20:42:52] Parsing /Users/ezhang/Documents/test/test.tex for outline
> [20:42:52] Default commands loaded
> [20:42:52] Default unimathsymbols loaded
> [20:43:13] BUILD command invoked.
> [20:43:13] Found root file from active editor: /Users/ezhang/Documents/test/test.tex
> [20:43:13] Root file remains unchanged from: /Users/ezhang/Documents/test/test.tex.
> [20:43:13] Building root file: /Users/ezhang/Documents/test/test.tex
> [20:43:13] Build root file /Users/ezhang/Documents/test/test.tex
> [20:43:13] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,/Users/ezhang/Documents/test/test
> [20:43:13] Parsing /Users/ezhang/Documents/test/test.tex for outline
> [20:43:13] File watcher: responding to change in /Users/ezhang/Documents/test/test.tex
> [20:43:13] Parsing /Users/ezhang/Documents/test/test.tex
> [20:43:14] LaTeX log parsed with 0 messages.
> [20:43:14] Toolchain of length 1 finished.
> [20:43:14] Successfully built /Users/ezhang/Documents/test/test.tex
> [20:43:14] No PDF viewer connected for /Users/ezhang/Documents/test/test.pdf
> [20:43:27] Root file remains unchanged from: /Users/ezhang/Documents/test/test.tex.

**Comment by Dellu** [comment]
The documentation doesn't mention Outline. 

How do I display the outline?
