### ISSUE TITLE
Cannot view PDF with web browser (cross-device, under same WiFi)

### ISSUE THREAD

**Issue by yzhang-gh** [James-Yu/LaTeX-Workshop#2915]
Thanks for the nice extension.

## Preliminary questions [Required]

When I view the PDF using command `latex-workshop.viewInBrowser` it is perfectly okay in the current device (`127.0.0.1`).

However, if I open the URL on another device (in the same local area network, replacing `127.0.0.1` with `192.168.xxx.xxx`), the PDF is not shown.

I have tried another local server (`python -m http.server`) and things work well across devices (so it is not the network issue).

Is it designed to be accessible only on the host device?

### To Reproduce

1. `latex-workshop.viewInBrowser`
2. Copy the URL, replace the `127.0.0.1` with the host IP (use `ipconfig`)
3. Open the URL on another device (under the same WiFi)
4. PDF not shown

### Expected behavior

View the PDF rather than not responding

**Comment by tamuratak** [comment]
> Is it designed to be accessible only on the host device?

Yes. 

We restrict the access for security reasons.
