### ISSUE TITLE
Compilation process hangs

### ISSUE THREAD

**Issue by jonas-frey** [James-Yu/LaTeX-Workshop#2921]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: I cannot, but at least I get an error message and it doesn't hang.

## Describe the bug [Required]

When I compile a file, the little wheel in the bottom bar keeps turning instead of compilation exiting with an error.
When I stop the compilation with `kill latex compiler process` the wheel stops turning, but there's remains a pdflatex process in the background eating CPU.

### To Reproduce

Compile file with the content

```
\documentclass{article}
\usepackage{mathtools}
\mathtoolsset{centercolon}
\usepackage{tikz-cd}

\begin{document}
\begin{tikzcd}\ar[r,","] &\end{tikzcd}$:$
\end{document}
```
with the standard recipe (`latexmk`).

The compilation should exit with an error, but hangs and cannot be properly terminated through vscode as described above.

### Expected behavior

Compilation should fail and give error message.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: kubuntu 21.10
 - VS Code version: 1.61.1
 - Extension version: 8.21.0
 - TeX distribution version: TeX Live 2020/Debian

### Are you using VSCodium?

/No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment]
Another workaround is calling commands with `-halt-on-error`, not `-interaction=nonstopmode`.
