### ISSUE TITLE
Disable buildOnSave when saving .sty or .cls

### ISSUE THREAD

**Issue by fortierq** [James-Yu/LaTeX-Workshop#2946]
Currently, saving a .sty or .cls file triggers buildOnSave which is not desired, in my opinion.  
The extension then builds a random .tex file, note the one I am currently working on.  
Therefore, I suggest only triggering buildOnSave for .tex files.

**Comment by jlelong** [comment]
You can use [`latex-workshop.latex.watch.files.ignore`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexwatchfilesignore) to ignore `.sty` or `.cls` files.

**Comment by fortierq** [comment]
Thanks. The wiki is great.
