### ISSUE TITLE
PDF previewer as separate package

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#2947]
Sorry I'm not following the template but it really doesn't match what I'm proposing here. Namely, to distribute the pdf previewer as a separate package. The reason is twofold:

1. Alternatives are worse: one is seemingly closed source, the other one is also based on PDF.js but doesn't seem as well maintained, documented and featured as LW previewer is.

2. Using pandoc or other markdown based alternatives in order to produce pdf through LaTeX is a popular approach that require pdf visualization but not a LaTeX IDE.

The current situation is not ideal in two ways:

1. LW is not discoverable for anyone looking for a pdf previewer in the marketplace or google. If you already use LW you know it will do it, but if not I believe it's unlikely that you end up here.

2. It requires installation of a lot of LaTeX stuff that you won't need if you have a markdown based workflow.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
