### ISSUE TITLE
Unable to open browser

### ISSUE THREAD

**Issue by xukai92** [James-Yu/LaTeX-Workshop#295]
Each time I want to open the .pdf in browser it says "Unable to open browser" and asks me to copy it on my own. It is expected that users need to copy the link on their own instead of the browser will be opened automatically?

**Comment by James-Yu** [comment]
This issue was discussed in https://github.com/James-Yu/LaTeX-Workshop/issues/244#issuecomment-326907050 . To summarize, the `opn` node package does not support your OS or config.
