### ISSUE TITLE
QuickFix for duplicate entries in BibTeX

### ISSUE THREAD

**Issue by jooyoungseo** [James-Yu/LaTeX-Workshop#2955]
Currently, there is no easy way to tidy up duplicate entries in BibTeX file in VSCode.

Could you please consider adding a QuickFix functionality for that?

**Comment by jlelong** [comment]
Duplicate entries are actually entries with the same key but not necessarily identical entries. Hence, automatically fixing duplicate entries is far too delicate and goes beyond the scope of the extension.
