### ISSUE TITLE
Highlight to-dos from todonotes package

### ISSUE THREAD

**Issue by cestanis** [James-Yu/LaTeX-Workshop#2958]
`todonotes` is a nice package to organize to-dos. Texstudio highlights these within the text and also has a section on the navigation plane.

<img width="127" alt="Screenshot 2021-11-07 at 18 10 44" src="https://user-images.githubusercontent.com/91360984/140654783-42194d1a-479f-4429-8f06-f42609129543.png">

<img width="176" alt="Screenshot 2021-11-07 at 18 11 06" src="https://user-images.githubusercontent.com/91360984/140654784-7c98eb99-24a4-43ea-9dc6-324c5eaabbc7.png">

Would be happy to see this here.

**Comment by jlelong** [comment]
I am not convinced by having a dedicated highlighting for `\todo{...}`. 

Adding todos to the outline/structure view could be considered as part of a larger improvement. We could add a new setting for the user to defined which commands should appear in the outline/structure view.

**Comment by jlelong** [comment]
Add `"todo"` to the new configuration variable `latex-workshop.view.outline.commands`.
