### ISSUE TITLE
Surround previous selection option

### ISSUE THREAD

**Issue by bernhard-hoerl** [James-Yu/LaTeX-Workshop#296]
Hi,
I'm new to GitHub but I use LaTeX-Workshop almost daily, it's awesome.

I encounter a small problem with my workflow, but it's not very big but annoying.
Every time I, for example, use the \frac{x}{y} environment I get an popup when I replace x with a slash \ command, which tells me:
"Press ENTER to surround previous selection with selected command"

I know this is probably a feature, but it would be nice if you could turn this off. If you already can please correct me, I didn't find the option.

Keep up the good work, I love to write LaTeX in VScode more and more  thanks to your extension <3

**Comment by James-Yu** [comment]
Thanks for your description and I am always moved by users' positive suggestions. This feature will be discussed in #288 , You may track/discuss the issue there.
