### ISSUE TITLE
Breadcrumbs for higher level symbols

### ISSUE THREAD

**Issue by PedroLima92** [James-Yu/LaTeX-Workshop#2961]
## Preliminary questions [Required]

<details> <summary>Preliminary questions</summary>

  ### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]
  
  You still see this issue?: Yes
  
  ### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.
  
  You visited the wiki?: Yes
  
  ### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.
  
  You can compile a TeX document manually?: Yes

</details>

## Is your requested feature  related to a problem? Please describe. [Required]

It seems like there's a feature missing: LatexWorkshop provides a full outline of a `.tex` file, and if I launch the command `breadcrumbs.focusAndSelect` it does reach all sections and labels.

However, the breadcrumbs topbar only shows three dots for any symbol not root level:
`file > ...` 
where for root level symbols we get a full path
`file > symbol`

The more limiting aspect of it is that, when I launch the command `breadcrumbs.focusAndSelect` (through the default keybind `Ctrl`+`Shift`+`.`) the breadcrumbs menu shown starts from the first symbol instead of the current symbol.

## To Reproduce  [Required]
In this MWE you can see it by placing your cursor in the scope of Subsection1.1

Minimal working example:
```latex
\documentclass[12pt]{article}

\begin{document}

\section{Section1}
Lorem ipsum

  \subsection{Subsection1.1}
  Lorem ipsum

\section{Section2}
Lorem ipsum

\end{document}
```

## Describe the solution you'd like  [Required]

I'd expect a full path to labels and subsections to be possible. But I'm primarily interested in support of the `breadcrumbs.focusAndSelect` starting at the current symbol. It would make navigation within `.tex` files much more efficient.

<details><summary>Logs aren't necessary</summary>

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/44039025/140742227-5b459d34-3a59-4fd6-9434-7c85e456b16d.png)

![image](https://user-images.githubusercontent.com/44039025/140742611-2f4cabd7-67f6-4fd2-91f7-eee6697e2736.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 20.04
 - VS Code version: 1.62 x86
 - Extension version: 8.21.1
 - TeX distribution version: TeX Live 2019.20200218-1

<details><summary>Additional questions</summary>

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

Yes

### Are you using LaTeX Workshop with VS Code Remote?

No

</details>

Thanks for the great extension, by the way :+1:

**Comment by jlelong** [comment]
This is actually a bug coming from the wrong range of (sub)section symbols.

<img width="590" alt="Capture d’écran 2021-11-09 à 07 48 27" src="https://user-images.githubusercontent.com/2910140/140875729-7d80a403-83da-4488-906f-aeb61f381f57.png">

Observe that the range of the `\section` stops at the beginning of the `\subsection`. An ellipsis `...` shows up in the breadcrumbs when the current line is not within a symbol range.
