### ISSUE TITLE
Allow usermapping for docker images

### ISSUE THREAD

**Issue by ORippler** [James-Yu/LaTeX-Workshop#2962]
### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Is your requested feature related to a problem? Please describe.

It's not strictly a problem, but it would be nice if compilation via docker images would be executed as current user rather than the user given by the Dockerfile (which defaults to root).

## To Reproduce 

1. Compile any `.tex` file with Tex-Workshop and a Docker image where the current user is `root`.
2. Files generated during the process will belong to `root` user if user is not changed in the Dockerfile.

## Describe the solution you'd like

Under the assumption that we want to compile as current active user, perform dynamic user-mapping by providing current user to `docker run` commands via `--user`.

For example, [```docker run -i --rm -w "$(pwd)" -v "$(pwd):$(pwd)" $LATEXWORKSHOP_DOCKER_LATEX latexindent "$@"```](https://github.com/James-Yu/LaTeX-Workshop/blob/0fac0e2bef9075e0e58a23e86fa967381bcba7c3/scripts/latexindent)
would change to ```docker run -i --rm -w "$(pwd)" -v "$(pwd):$(pwd)" `--user `id -u`:`id -g`` $LATEXWORKSHOP_DOCKER_LATEX latexindent "$@"```.

I am not an expert for windows, but believe that providing `--user` to `docker run` is not necessary , as the user-mapping is handled differently between Windows and Linux:
https://github.com/docker/for-win/issues/497

### Additional context

A blog post on user mapping in [`docker`](https://jtreminio.com/blog/running-docker-containers-as-current-host-user/#what-containers-need-this), and docker docs for [`--user`](https://docs.docker.com/engine/reference/run/#user).

**Comment by tamuratak** [comment]
We will not add features to the Docker support. Please use VS Code Remote Development for advanced features.

https://code.visualstudio.com/docs/remote/remote-overview
