### ISSUE TITLE
Recipes that come with the extension do not show in settings.json file

### ISSUE THREAD

**Issue by empeirikos** [James-Yu/LaTeX-Workshop#2964]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When I install the Latex-Workshop extension I can see the list of recipes shown in the following picture:

<img width="422" alt="Screenshot 2021-11-08 at 10 30 37" src="https://user-images.githubusercontent.com/80323854/140940454-3e96e2a8-b332-472c-9a4b-d195d1cbfe48.png">

However when I open the `settings.json` file this is all I can see:
```
{
    "python.pythonPath": "/Users/theodoremavroidis/opt/anaconda3/bin/python",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "python.defaultInterpreterPath": "/Users/theodoremavroidis/opt/anaconda3/bin/python",
    "latex-workshop.view.pdf.viewer": "external",
    "launch": {
        "configurations": [
        ]
    },
}
```
I want to make sure I add new recipes/tools in the file that has the original recipes. Where are they?

### To Reproduce

1. Click on `Code>Preferences>Settings`
2. Go to `Latex-workshop>Latex: Recipes` and then choose `Edit in settings.json`

### Expected behavior

I was expecting the settings.json file to contain the recipes listed on the TeX tab.

## Logs [Required]

n/a

### LaTeX Workshop Output [Required]

n/a

### Developer Tools Console [Required]

n/a

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: macOS Catalina 10.15.7 
 - VS Code version: 1.62.0 
 - Extension version: 8.21.1
 - TeX distribution version: TeX Live 1.49

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Related to https://github.com/microsoft/vscode/issues/134908

Just click on `Copy setting as JSON` to copy the default value of the recipes. Then, you can paste the setting in `settings.json` and edit it according to your needs.

**Comment by empeirikos** [comment]
Sorry for this but how and where do I click `Copy setting as JSON` I am sure it is obvious to you but it is not obvious to me ... All I can see is a list of LaTeX commands in the left panel and an option `Edit in settings.json` in Settings. Guess I have not been using Visual Code for a long while...

**Comment by jlelong** [comment]
Move your mouse over `Latex-workshop › Latex: Recipes` to reveal the setting wheel icon on the left. Right click on it.
