### ISSUE TITLE
How does one get snippet view?

### ISSUE THREAD

**Issue by lightningHoneypot** [James-Yu/LaTeX-Workshop#2966]
I guess the title says it all, I can get _snippet panel_ but how does one get snippet view?

(once you guys give out the answer, please if possible delete this "issue" note 24 hours after reply if possible)

**Comment by tamuratak** [comment]
In the side bar.

<img width="393" alt="スクリーンショット 2021-11-10 14 22 44" src="https://user-images.githubusercontent.com/10665499/141054809-e6484fed-3818-4259-9d35-85d185ac8266.png">
