### ISSUE TITLE
PDF Viewer Tab not working

### ISSUE THREAD

**Issue by Weasy666** [James-Yu/LaTeX-Workshop#297]
### Description

The PDF Viewer doesn't find the compiled PDF.

### How to reproduce

Create a Latex project with a path like ``C:\Coding\Code\C#\`.

### Expected behavior

PDF Viewer shows compiled PDF file.

### Actual behavior

Viewer says it can't find the PDF file.

### Log messages

```
Serving PDF file at http://127.0.0.1:60267/viewer.html?file=/pdf:e%3A%5CCoding%5CCode%5CC%23%5CBT_AR-Navigation_Book_Localization%5Cdocs%5Cthesis%5Ccoverletter.pdf
Open PDF tab for e:\Coding\Code\C#\BT_AR-Navigation_Book_Localization\docs\thesis\coverletter.pdf
Error reading PDF file: e:/Coding/Code/C
```

You can see that the PDF Viewer doesn't get the complete path... it stops right where the `#` should be.

**Comment by James-Yu** [comment]
My preliminary guess is that `PDF.js` cannot recognize `#` properly. I will come back with more investigations.

**Comment by James-Yu** [comment]
Found the problem. `#` and chars after hashtag won't be passed as URL component. Working on a fix.

**Comment by Weasy666** [comment]
Thought so. Maybe you can http encode the path. Then the `#` would be a `%23`. That'll maybe work.
