### ISSUE TITLE
Inverse Search does not work

### ISSUE THREAD

**Issue by security-cheng** [James-Yu/LaTeX-Workshop#2976]
I follow the setting as follows, but after some updating of VS code, the function does not work. Forward Search function works well.

    "latex-workshop.view.pdf.viewer": "external",
    "latex-workshop.latex.recipe.default": "lastUsed",
    "latex-workshop.synctex.afterBuild.enabled": true,
    "latex-workshop.latex.autoClean.run": "onFailed",
    "latex-workshop.view.pdf.ref.viewer":"auto",
    "latex-workshop.view.pdf.external.viewer.command": "C:/Users/Cheng/AppData/Local/SumatraPDF/SumatraPDF.exe", 
    "latex-workshop.view.pdf.external.viewer.args": [
        "%PDF%"
    ],
    "latex-workshop.view.pdf.external.synctex.command": "C:/Users/Cheng/AppData/Local/SumatraPDF/SumatraPDF.exe",
    "latex-workshop.view.pdf.external.synctex.args": [
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "\"C:\\Users\\Cheng\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" \"C:\\Users\\Cheng\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"",
        "%PDF%",
    ],

**Comment by tamuratak** [comment]
Duplicate of #2975

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
