### ISSUE TITLE
[Feature] Auto clean auxiliary files on successful compilation

### ISSUE THREAD

**Issue by spivakj** [James-Yu/LaTeX-Workshop#2977]
## Is your requested feature related to a problem? Please describe. 
I want to auto clean files on successful compilation, but not on failure so that I can read the log file and debug. There's an option for auto cleaning on failure, but not for auto cleaning on success. 

## Describe the solution you'd like 
Add a onSuccess option to latex-workshop.latex.autoClean.run

## Desktop 
OS: Windows 10
VS Code version: 1.62.3 x54
Extension version: 8.22.0
TeX distribution version: MiKTeX-pdfTeX 4.8 (MiKTeX 21.8)

**Comment by tamuratak** [comment]
Duplicate of #2094
