### ISSUE TITLE
Suggest LTex in Wiki

### ISSUE THREAD

**Issue by dikti** [James-Yu/LaTeX-Workshop#2978]
In the [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#spell-check), you already recommend vscode-languagetool for spell and grammar checking, which is abandoned. Using the same underlying engine, there is [valentjn/vscode-ltex](https://valentjn.github.io/ltex/) and I think that should be recommended instead. As I can't edit/propose edits for the wiki, a suggestion for the entry here:

```markdown
## Spell check
[LTeX][1] is a great tool for checking spelling, grammar and style in many languages.
If you only need spell checking, [Code Spellchecker][2] does a great job, too.

[1]: <https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex>
[2]: <https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker>
```

**Comment by tamuratak** [comment]
Please open an issue at https://github.com/jlelong/LaTeX-Workshop-wiki
