### ISSUE TITLE
Proposal: support local Makefile

### ISSUE THREAD

**Issue by happyaron** [James-Yu/LaTeX-Workshop#298]
### Description

Please support building the pdf file with a local Makefile, which is the usual way a lot people used to organized their tree, thus they won't get a fatal error upon saving the .tex file every time.

**Comment by James-Yu** [comment]
While I personally don't use makefile, I would consider it as a good addition.

Can you please provide some brief samples/materials on how a makefile would work for LaTeX/the extension?

**Comment by James-Yu** [comment]
I suppose this feature request is identical to #337, which has a more detailed description.
