### ISSUE TITLE
[Question] Building from active file that is not root file.

### ISSUE THREAD

**Issue by spiffrgr** [James-Yu/LaTeX-Workshop#2980]
Is it possible to build a file that is not the root file?
Can I build from the active file without having \begin{document} or the magic comment?

If I add the magic comment and I build, I get to view my file. If I remove the comment, all temporary files are still there and I can still update my changes and preview them without it being the root file anymore.

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#multi-file-projects

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
