### ISSUE TITLE
Enable LaTex grammar for VS Code on the Web

### ISSUE THREAD

**Issue by isidorn** [James-Yu/LaTeX-Workshop#2983]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure LaTex grammar is available in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

I checked your extension and I see there are quite some dependencies, so this transition to web might not be trivial or possible. However it would be cool if you could at least contribute `grammars` for web, and using `when` clauses disable all other contributions which can not work on the web.

We are also open to helping here. Let us know what you think. Thanks!

@aeschli

**Comment by jlelong** [comment]
@isidorn Thanks for getting in touch on this. If I understand well, it would be sufficient to provide the LaTeX grammar as a separate extension as discussed in #2731. I should already have done it but I ran out of time. Making the LaTeX grammar available on the web gives me extra motivation to make a basic LaTeX language extension to just provide the grammar.

I suggest to keep track of the progress on this in #2731.

**Comment by isidorn** [comment]
Yeah, that issue might just do what we need!
I am not a LaTeX expert and I definitely do not know what other LaTeX functionality could work in the browser. If you think the `grammar` is the only thing that is doable then feel free to close this issue and we can continue in #2731

**Comment by jlelong** [comment]
> If you think the grammar is the only thing that is doable then feel free to close this issue and we can continue in #2731

I would not go that far for the moment. It is fairly easy to handle the grammars. The other features are much more intricate and many need access to the project files on the user disk. So, making these features work in a browser requires a major effort.

**Comment by isidorn** [comment]
Ok. So it might make sense to keep this issue open and potentially tackle in the future when tile allows.
Though whatever you prefer. Thank you!

**Comment by tamuratak** [comment]
I have confirmed LaTeX syntax highlighting available on https://insiders.vscode.dev/

**Comment by jlelong** [comment]
I still have a few things to fix to easily synchronise the grammars and language configurations between https://github.com/jlelong/vscode-latex-basics and the ones in LW. Keeping the definitions of `brackets`, `autoClosePairs` and `surroundingPairs` in sync between the different languages is a pain. So, I am working on a script to define a new language configuration as an extension of an existing one. More to come by the end of the week-end

**Comment by jlelong** [comment]
@tamuratak I have finally come up with a utility to extend languages in VS Code, see https://github.com/jlelong/vscode-extend-language and at [npmjs](https://www.npmjs.com/package/vscode-extend-language).
