### ISSUE TITLE
Placeholder for enviroments and parentheses

### ISSUE THREAD

**Issue by HengrongDu** [James-Yu/LaTeX-Workshop#2984]
By default, there is no placeholder outside the equation environment and parentheses, so the Tab key does not work for jumping out of them after writing. Could anyone help me with that? Thanks.

**Comment by jlelong** [comment]
There is no placeholder to jump out of any environment because being inside a placeholder makes typing more delicate in particular when using intellisense.

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/feature-request.md) next time.
