### ISSUE TITLE
Adding `[`...`)` and `(`...`]` to bracket pairs to support semi-open and semi-closed interval

### ISSUE THREAD

**Issue by ZhangSongyi** [James-Yu/LaTeX-Workshop#2985]
As I suggest [here](https://github.com/microsoft/vscode/issues/137774#issuecomment-979584373), marking `[`...`)` and `(`...`]` as bracket pairs can make semi-open and semi-closed interval renders correctly.

It turns
![image](https://user-images.githubusercontent.com/12276998/143514460-014da7a6-05ae-40aa-9ecf-065ccead6471.png)
into
![image](https://user-images.githubusercontent.com/12276998/143514467-0460936b-da8f-424f-83eb-382866d05c10.png)

I'm not sure if such a change will cause other problems, but I will continue to follow up at that issue and here

**Comment by jlelong** [comment]
It would make sense to mark `[..)` and `(...]` as bracket pairs. I do not think it would cause any other problem.
@hediet do you confirm despite `[...]` being also a bracket pair?

@ZhangSongyi note that the `chktex` linter will still mark `[...)` as a paren mismatch.

**Comment by hediet** [comment]
> @hediet do you confirm despite [...] being also a bracket pair?

That should work - the same closing bracket can be used in different pairs.
