### ISSUE TITLE
Inverse Search in vscode 1.62.3, windows 11, with Sumatra PDF

### ISSUE THREAD

**Issue by loftea** [James-Yu/LaTeX-Workshop#2988]
the SyncTex can be used with the following settings:

**In sumatraPDF: (THIS IS IMPORTANT)**
```
InverseSearchCmdLine = "D:\Code\VS code\Microsoft VS Code\Code.exe"  -g "%f":"%l" // the part of cli.js is deleted
EnableTeXEnhancements = true
```

**In vscode: (other settings are the same as normal)**
```
"latex-workshop.view.pdf.external.synctex.args": [
        "-forward-search",
        "%TEX%",
        "%LINE%",
        "-reuse-instance",
        "-inverse-search",
        "code \"C:\\Users\\Eussi_kun\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"", 
        //In this place, whether the cli.js is deleted seems like make no sense
        "%PDF%",
    ],
```

P.S. it seems like that the cli.js is not necessary, but i do not know the reason why the deletion will make sense since i have no idea about the file or anything about the principle of SyncTex, but it truly works for me. By the way, this way seems like also solve the problem that the SyncTex fails when use inverse search and open the cli.js in vscode instead.

This issue is also post in the wiki project.

**Comment by jlelong** [comment]
Thanks for the advice. I am closing this issue in favour of jlelong/LaTeX-Workshop-wiki/issues/89
