### ISSUE TITLE
Feature request: go to definition

### ISSUE THREAD

**Issue by poscat0x04** [James-Yu/LaTeX-Workshop#2989]
## Preliminary questions
Support go to definition

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

Yes

## Is your requested feature  related to a problem? Please describe. [Required]

No

## To Reproduce  [Required]

?

## Describe the solution you'd like  [Required]

Implement go to definition

## Logs [Required]

?

### LaTeX Workshop Output [Required]

?

### Developer Tools Console

?

## Desktop [Required]

 - OS: NixOS
 - VS Code version: 1.62.3
 - Extension version: 8.22.0
 - TeX distribution version: texlive 2021

## Additional questions

?

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

?

**Comment by tamuratak** [comment]
Rejected.

This issue is not doable.
