### ISSUE TITLE
PDF Viewer not updating

### ISSUE THREAD

**Issue by Weasy666** [James-Yu/LaTeX-Workshop#299]
### Description

After compiling a pdf file and opening it in the PDF viewer everything is ok. But if the viewer is open and you recompile the pdf file the viewer shows an error.
Fix of #297 maybe broke something.

### How to reproduce

Create a Latex project compile it once and open the pdf file with the viewer. Afterwards compile it again, with the viewer still open.

### Expected behavior

PDF Viewer shows updated PDF file.

### Actual behavior

Viewer shows following error.
![bug](https://user-images.githubusercontent.com/11967542/32419507-f0f81814-c27a-11e7-8602-72035228c407.png)

**Comment by James-Yu** [comment]
Absolutely. This bug was created by #297, which changed the way PDF page tells the server which file it is requesting. Fix incoming.

**Comment by Weasy666** [comment]
Nice. Thank you :)
