### ISSUE TITLE
Focus jump in viewer when using landscape pages

### ISSUE THREAD

**Issue by mgrewe** [James-Yu/LaTeX-Workshop#2994]
Hi, I encountered an issue with the internal pdf viewer. It focuses wrongly after a rebuild when the pdf contains differently oriented landscape pages. I.e., depending on whether I use ```pdflscape``` (does rotate) instead of ```lscape``` (does not rotate), the pdf viewer jumps to different locations in the document. This is particularly annoying when having multiple landscape pages which causes the viewer to jump to a completely different location.

I assume this might be an issue with the calculation of page sizes?

Thanks for consideration of this issue.

**Comment by mgrewe** [comment]
BTW: Here is a short snippet for testing:

```
\documentclass[a4paper]{scrbook}

%\usepackage{lscape}
% use this to rotate page also in pdf
\usepackage{pdflscape}


\begin{document}  
Portrait

\newpage

\begin{landscape}
Landscape
\end{landscape}

\newpage

\begin{landscape}
Landscape
\end{landscape}

\newpage

Portrait

\end{document}
```

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment]
We don't support VSCodium.
- https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#vscodium-is-not-officially-supported

I can't reproduce the issue with VS Code. Please install VS Code and use it. Please install the latest version of VS Code and LaTeX Workshop.

If you still see the issue with VS Code, please open a new issue filling out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).

**Comment by tamuratak** [comment]
#2996
