### ISSUE TITLE
How to modify AutoComplete

### ISSUE THREAD

**Issue by yaohong772** [James-Yu/LaTeX-Workshop#2995]

**Comment by yaohong772** [comment]
How to turn off keyboard typing " ` " auto-completion to " `' " ？

**Comment by yaohong772** [comment]
![image](https://user-images.githubusercontent.com/57561655/144079862-d6ad2e7a-9cd1-42af-b449-d8d722907046.png)

**Comment by jlelong** [comment]
If you have the setting `"editor.autoClosingBrackets": "languageDefined"`, the auto closing pairs are defined by https://github.com/James-Yu/LaTeX-Workshop/blob/1c0be8263c9cd0da39e2dd3a1c2f3f7efd9e899d/syntax/latex-language-configuration.json#L22-L49

You cannot change these setting, but you can change the value of `editor.autoClosingBrackets`. See https://stackoverflow.com/a/46474285
