### ISSUE TITLE
Automatically dismiss build error popup after successful build

### ISSUE THREAD

**Issue by eshimoniak** [James-Yu/LaTeX-Workshop#2998]
I'm still getting the hang of LaTeX, so I have still often make simple errors that are easy to fix. However after correcting these errors and building successfully, the two "Recipe terminated with error" messages still hang around. This makes me need to do a double take for subsequent builds; did I make a new error or is the old message just persisting?

**Comment by tamuratak** [comment]
The old message is just persisting. See #898

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
