### ISSUE TITLE
SyncTeX cannot be found

### ISSUE THREAD

**Issue by hexler81** [James-Yu/LaTeX-Workshop#3]
When opening the main tex file of a project, I get a warning saying "SyncTeX not found", even though there is a file ".synctex.gz" available. The warning is also shown when using synctex without compression ("-synctex=-1"). Building the pdf with pdflatex as well as the pdf preview work. Syncing does not.

I am working on Windows 10 with the MiKTeX distribution.

**Comment by James-Yu** [comment]
MiKTeX does not ship with SyncTeX. So I recommend TeXLive in readme, though downloading that is a pain.

.synctex.gz file is generated by pdflatex, not synctex

**Comment by hexler81** [comment]
Ok, I see. Do you think it is possible to support the synctex implementation of pdflatex in your extension? Up to now I am using TeXnicCenter + SumatraPDF in combination with pdflatex for syncing the pdf preview and the latex source.

**Comment by James-Yu** [comment]
Synctex is not an implementation of pdflatex: they are two different things. I don't think VSCode extension can bundle binary files as that can cause security issues. For other standalone latex IDEs like TeXStudio, they do not have this restriction and thus included synctex binaries.

**Comment by hexler81** [comment]
Ok. Thanks for the explanation.

**Comment by hexler81** [comment]
I found another discussion/explanation about this issue here:
http://tex.stackexchange.com/questions/338078/how-to-get-synctex-for-windows-to-allow-atom-pdf-view-to-synch
(just for completeness)

**Comment by James-Yu** [comment]
It's a really nice reference :❳

**Comment by zachjweiner** [comment]
@hexler81 did you ever get Synctex to work with MikTex? I followed the instructions that you linked to, but I continually get "Cannot synctex: Error: Command failed: synctex view" errors.

**Comment by hexler81** [comment]
Honestly, I did not try further ...

**Comment by hexler81** [comment]
I've just installed TeX Live (full installation). This installed synctex, too. Note that you need to add the TeX Live bin directory to PATH (in my case `C:\texlive\bin\win32`) and also remove MiKTeX from PATH in order to ensure that the TeX Live distribution is used. Having done this, building, previewing, and syncing with Code works perfectly.
