### ISSUE TITLE
Parse multiple bib files in one \bibliography-command

### ISSUE THREAD

**Issue by Inachos** [James-Yu/LaTeX-Workshop#30]
I have a bibliography-setup that looks like this call:
~~~~
\bibliography{./latex-base-files/library,./latex-base-files/IEEEabrv,./latex-base-files/settings}
~~~~
That is one actually library, the Abbreviation rules, and customized settings. I need the keys from file 1.
The parser doesn't work with this, because it take the whole body of the bibliography-command. Due to the way the regex is set up, I can work for now like this
~~~~
%\bibliography{./latex-base-files/library}
\bibliography{./latex-base-files/library,./latex-base-files/IEEEabrv,./latex-base-files/settings}
~~~~
This parses the bibliography call in the comment line and finds the citations.

It would be great however if the parser could split the bibliography line by "," symbols and parse them partially. I may try to do this if i find the time, but I don't know Javascript that well.

**Comment by James-Yu** [comment]
This one should fix the problem. If not, please re-open this issue.
