### ISSUE TITLE
begin/end tab completion not working correctly for to fill context

### ISSUE THREAD

**Issue by dpastoor** [James-Yu/LaTeX-Workshop#300]
### How to reproduce

Using the VsCodeVim plugin + latex-workshop to do editing, try to insert a begin/end statement
through tab completion

![image](https://user-images.githubusercontent.com/3196313/32517123-740fdb70-c3d3-11e7-87f7-8dfb86d8a0cd.png)

### Expected behavior

I expect to have a multiple cursor to rewrite the env placeholder for both begin/end.

### Actual behavior

![image](https://user-images.githubusercontent.com/3196313/32517133-7ec17664-c3d3-11e7-9230-a84685fbaea9.png)

Once tab completing the begin and hitting `i` (for insert mode), the leading env is deleted, including the trailing `}`, however the end is not, therefore breaking the multiple cursor.

I honestly am not sure if this is an issue with latex-workshop or the vim plugin. I figured I would check here first.

**Comment by James-Yu** [comment]
My 2c is that this is a bug on vim side. LW only uses official vscode API to provide multi-selected completion.
