### ISSUE TITLE
Auto-complement for `\]' 

### ISSUE THREAD

**Issue by Romeoly** [James-Yu/LaTeX-Workshop#3001]
## Preliminary questions [Required]
Every time when I type `\]`, the auto-complement list is shown, the very first term of which is `\item[label]`. As a result, if I type `\[+<enter>`, I shall get `\item[]` instead of `\]`. 
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by jlelong** [comment]
I can reproduce the behaviour with `editor.acceptSuggestionOnEnter: on`. Set it to `off` to stop accepting suggestions on hitting `Enter` but only on hitting `Tab`.

**Comment by Romeoly** [comment]
Setting `editor.acceptSuggestionOnEnter: off`, all suggestions are turned off. Can we just add `\]` to the suggestion list of itself so that a following hit of `<enter>` or `<tab>`  pushes `\]` into the text?

**Comment by jlelong** [comment]
You can add `\]` to your own LaTeX snippets. See [vscode's documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).

```json
"close-bracket": {
	"prefix": "\\]",
	"body": "\\]"
}
```
