### ISSUE TITLE
Wrong coloring of environments inside $...$

### ISSUE THREAD

**Issue by Romeoly** [James-Yu/LaTeX-Workshop#3002]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?:  Irrelevant.

## Describe the bug [Required]

Wrong coloring of environments inside $...$

### To Reproduce

````
\documentclass{minimal}
\begin{document}
$\begin{pmatrix}
    1 & 2 \\ 3 & 4
\end{pmatrix}$ 
\end{document}
````

### Expected behavior

`\end{pmatrix}` should begin with a  yellow `\end`, not green. 

## Logs [Required]

 Irrelevant.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

  Irrelevant.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

 Irrelevant.
```

## Screenshots

![foo](https://user-images.githubusercontent.com/3127531/144691533-2380aaaf-02c3-4468-8cdd-3b2b36e26e73.jpg)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS:  Windows 11
 - VS Code version: 1.62.3
 - Extension version: 8.22.0
 - TeX distribution version: TeX Live 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

Add any other context about the problem here

.

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to https://github.com/jlelong/vscode-latex-basics, so I've moved the issue to that repository: jlelong/vscode-latex-basics#5.
