### ISSUE TITLE
Custom Editor

### ISSUE THREAD

**Issue by TheBicPen** [James-Yu/LaTeX-Workshop#3003]
## Preliminary questions [Required]
I'm just curious, why is the internal PDF viewer not implemented as a [custom editor](https://code.visualstudio.com/api/extension-guides/custom-editors)? If I understand correctly, implementing it that way would allow the extension to provide more general PDF support than what it provides now. Is there some technical limitation with the custom editor API or is this issue just not on the priority list?

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes
## Describe the solution you'd like  [Required]

PDF viewer implemented as a custom editor.

**Comment by tamuratak** [comment]
> If I understand correctly, implementing it that way would allow the extension to provide more general PDF support than what it provides now.

We are not interested in providing advanced features.

Out of the scope of the extension.
