### ISSUE TITLE
Open hyperlinks in the pdf viewer

### ISSUE THREAD

**Issue by peixinshen** [James-Yu/LaTeX-Workshop#3007]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

I have used LaTeX workshop to write papers for a long time. Usually, I will add some hyperlinks to the references. Yet, after clicking the links in the internal PDF view, I cannot open a new webpage window for that reference. 

## To Reproduce  [Required]

1. Compile arbitrary papers using BibTeX with the entry of url.
2. Click on the hyperlink on the output PDF.
3. Cannot open a new window to browse the expected webpage.

## Describe the solution you'd like  [Required]

After clicking the hyperlinks in the internal PDF view, I want to open that webpage in the default browser.

## Desktop [Required]

 - OS: MacOS Monterey 12.0.1
 - VS Code version: 1.63.0
 - Extension version: 8.22.0
 - TeX distribution version: TeX Live 2020

**Comment by jlelong** [comment]
This feature used to exist but was removed because it created a severe injection vulnerability. See https://snyk.io/blog/visual-studio-code-extension-security-vulnerabilities-deep-dive/
