### ISSUE TITLE
Drop support for LaTeX Utilities

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3009]
LaTeX Utilities has been unmaintained for over a year. We had better drop the support to decrease  security risks and the maintenance burden.

@jlelong  How do you think?

**Comment by jlelong** [comment]
Could you remind me of what features we rely on LaTeX Utilities for?

**Comment by tamuratak** [comment]
I am saying that we had better delete the following lines to decrease security risks and the maintenance burden:

https://github.com/James-Yu/LaTeX-Workshop/blob/acce9aa4062810a983748ed7d24fe459ceb3188c/src/main.ts#L136-L162

We should stop exposing the API.

**Comment by jlelong** [comment]
Yes, I do agree that we are exposing too much of our internal design and that we do not want to ensure any compatibility guaranty on this part. Maybe, we should leave a message in https://github.com/tecosaur/LaTeX-Utilities that we will stop exposing our internal API?

**Comment by tamuratak** [comment]
I think we don't have to do since the repository seems abandoned. It would be enough to announce on our side.

**Comment by jlelong** [comment]
I am fine with this.
