### ISSUE TITLE
Unable to compile under MacOS and MacTeX 2017

### ISSUE THREAD

**Issue by fpiraneo** [James-Yu/LaTeX-Workshop#301]
### Description

Installed Visual Studio Code 1.18.0 and LaTeX Workshop 3.6.1.
LaTeX toolchain is MacTeX 2017 downloadable at https://www.tug.org/mactex/.
Configured LaTeX workshop to use the pdflatex because the latexmk doesn't exists in this toolchain.

ISSUE: When Visual Studio Code try to compile the project, the compilation fails with:
_LaTeX fatal error: spawn pdflatex ENOENT, . Does the executable exist?_

The command risen by the IDE is:
**Toolchain step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/Users/fpiraneo/Documents/sbp-specs/sb**

Started the same command on the shell, the PDF is correctly generated with no errors.

Something to modify on the configuration to work with this toolchain?

Thanks a lot.

**Comment by James-Yu** [comment]
I did not experience a similar issue on the same versions. Did it work before vscode 1.18?

**Comment by fpiraneo** [comment]
Yes! I used vscode and LaTeX Workshop with the June 2017 versions and worked fine.
Just to give you all the info, here is the configuration:
```
"latex-workshop.latex.toolchain": [
        {
          "command": "pdflatex",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%"
          ]
        }, {
          "command": "bibtex",
          "args": [
            "%DOCFILE%"
          ]
        }, {
          "command": "pdflatex",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%"
          ]
        }, {
          "command": "pdflatex",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%"
          ]
        }
      ]
```
As you see it's copy-pasted from your doc.

**Comment by James-Yu** [comment]
That would be quite strange. I would recommend you start vscode by typing `code` and enter in a terminal. It seems not to be a problem on the extension side.

Any other mac users please correct me if I'm wrong.

**Comment by fpiraneo** [comment]
Well, simply typing `code` doesn't work at all; on MacOS I have to type the following (getting the results...)

```
>./Visual\ Studio\ Code.app/Contents/MacOS/Electron 
2017-11-09 13:44:27.953 Electron[10232:359542] *** WARNING: Textured window <AtomNSWindow: 0x7fa84356f3d0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
bash: syntax error near unexpected token `('
```

Trying to compile the `.tex` file I don't get any extra message but the compilation still fail; now there is a `bash: syntax error near unexpected token` that I'd want to investigate further.

**Comment by James-Yu** [comment]
I'm fine for a remote investigation, yet I will be quite busy on IRL matters in the following days. Let me investigate first and return to you a bit later.

**Comment by fpiraneo** [comment]
Good! In the meanwhile I've tested the LaTeX workshop under Windows 10 and with the default LaTeX toolchain and works fine. I think the issue is limited to the MacOS... :-(

Any help is strongly apreciated.

**Comment by fpiraneo** [comment]
Hi James, I finally get the point; it seems that the compilation fails because I put the vs code app on another folder than the standard **/Applications** folder (in the case I put vscode on **/Users/username/My Apps/**.
Once removed vscode from the personal app folder and put on the system wide app folder the compilation succeded correctly.
I can consider the issue closed now; as suggestion I'll put on the doc that the vscode app should reside on the system wide application folder to make the latex workshop plugin works correctly. What do you think about?

**Comment by Leshao-Zhang** [comment]
I have the same issue. I solved this with the command: shell: add code to PATH

**Comment by lzfelix** [comment]
I had the same issue and my problem was similar to @fpiraneo, `vscode` was installed in a folder different from `/Applications`, where my *tex toolchain is. Maybe it should be fruitful to mention this on the README, @James-Yu?

**Comment by Yousanflics** [comment]
I came with the same problems but I think that because after I installed `code` command by using `cmd+shit+p` then entered shell install code, by using this command I opened the vscode not from /Application so I change this command in my zshrc file `export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH" ` after doing this the error disappeared, and thinks for @fpiraneo 's conclusion that first I changed my way to open up vscode and open it from /Application file then it really works.

Platform: MaxOS 10.14.0
VScode verison:1.32.3
Latex workshop version:6.2.2
