### ISSUE TITLE
Release script fails to execute with npm

### ISSUE THREAD

**Issue by filiptronicek** [James-Yu/LaTeX-Workshop#3011]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

N/A

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

N/A

### To Reproduce

1. Install deps with `npm i`
2. Run the release script with `npm run release`

### Expected behavior

The extension gets packaged successfully, instead I get an `npm list error`. This can be fixed by using yarn, but I wonder why. 

## Logs [Required]

```
gitpod /workspace/LaTeX-Workshop $ npm run release

> latex-workshop@8.22.0 release
> npm run clean && npm run lint && npm run compile && vsce package


> latex-workshop@8.22.0 clean
> rimraf out/ .eslintcache


> latex-workshop@8.22.0 lint
> eslint --cache --ext .ts,.js .


> latex-workshop@8.22.0 compile
> tsc -p tsconfig.json && tsc -p viewer/tsconfig.json

 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! code ELSPROBLEMS
npm ERR! missing: worker-loader@^3.0.7, required by pdfjs-dist@2.10.377

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-12-13T15_35_15_774Z-debug.log

```

### LaTeX Workshop Output [Required]

N/A

### Developer Tools Console [Required]

N/A

## Screenshots

N/A

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Linux 20.04
 - VS Code version: n/a
 - Extension version: 8.22.0
 - TeX distribution version: n/a

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by filiptronicek** [comment]
May be related: https://github.com/microsoft/vscode-vsce/issues/477

**Comment by jlelong** [comment]
Related to mozilla/pdf.js#13825. Until we upgrade to PDF.js v2.11, use npm v6.
