### ISSUE TITLE
Please consider re-adding snippet panel and removing snippet view

### ISSUE THREAD

**Issue by aterenin** [James-Yu/LaTeX-Workshop#3012]
The snippet panel was removed in #2959 in order to reduce maintenance burden.

I instead suggest that it would be better user experience to remove the snippet view rather than the snippet panel. The reason for this is that the snippet view is restricted to either the bottom bar, or the left toolbar, and cannot be placed within a larger panel in the user's workspace. 

I therefore believe that, if forced to choose between these, the snippet panel should be kept, because it is easier to for the user to view.

**Comment by tamuratak** [comment]
You can move the panel to the right side:


![スクリーンショット 2021-12-14 7 26 19](https://user-images.githubusercontent.com/10665499/145899011-89409b90-2679-4f82-a39a-1d6ce3bfd7ff.png)

![スクリーンショット 2021-12-14 7 26 32](https://user-images.githubusercontent.com/10665499/145898938-71fe62fb-1c46-44e4-85ac-46e9d70527b7.png)
