### ISSUE TITLE
Delete some entries in `snippets/latex.json`

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3014]
We had better remove some entries in `snippets/latex.json`. It would be better to remove `item`:

https://github.com/James-Yu/LaTeX-Workshop/blob/7a4d03de17b0ead6784f346630c3b8bebaa0c7b0/snippets/latex.json#L2-L6

Related to #3013. The behavior of snippets is fragile. It changes on every upgrade of VS Code. It would reduce complaints from users to keep the number of built-in snippets small.

Personally, I disable all the snippets defined in `snippets/latex.json` for my usage. 

- https://code.visualstudio.com/updates/v1_52#_hide-extension-snippet

@jlelong how do you think?

**Comment by jlelong** [comment]
The `item` snippet should definitely be removed. 

I am a big fan of the other snippets, in particular `__`, `**` and the ones starting with `B`. I actually implemented them based on my long use of `vim-latex`. So, I am afraid I will not have a fair opinion on that. The snippets `__` `**` and `...` need specific tweak of https://github.com/James-Yu/LaTeX-Workshop/blob/1c0be8263c9cd0da39e2dd3a1c2f3f7efd9e899d/syntax/latex-language-configuration.json#L64

See `(__)|(\\*\\*)|(\\.\\.\\.)`.

Al the other snippets could be added by the user himself should we provide their definitions in the wiki for instance.

**Comment by tamuratak** [comment]
I see. Let's remove only the `item` snippet at the moment.

**Comment by tamuratak** [comment]
Closed in 660ca5842348c002af14fa242a8b0e6f6387ccab
