### ISSUE TITLE
"Recipe: Compile Rnw files" calls Anacondas version of R

### ISSUE THREAD

**Issue by pehkawn** [James-Yu/LaTeX-Workshop#3028]
## Preliminary questions [Required]
I tried compiling a .Rnw with LaTeX Workshop, which rendered the error message "Error in readRDS(pfile): cannot read workspace version 3 written by R 3.1.2  (need R 3.5.0 or newer)"

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: I can now.

## Describe the bug [Required]

I googled around a bit. Seemingly this issue had to with having different versions of R. I have an older version of R installed in Anaconda, which I haven't used. My system `$PATH` points to the newest version, I installed via `apt` from the the official CRAN repos. LaTeX Workshop seem not to recognize this, and still tries to use the Anaconda version. Replacing the script `opt/anaconda3/lib/R/bin/R` with `/lib/R/bin/R` solved the issue.

### To Reproduce

1.  Install R in Anaconda, and install newest version of R from official repo.
2. Make sure $PATH points to the newest version
3. Open/create .Rnw file
4. Click on 'Build LaTeX project.
5. See error
6. Solution: Replace `opt/anaconda3/lib/R/bin/R` with `/lib/R/bin/R`

### Expected behavior

Generation of PDF.

## Logs [Required]

Cannot access anymore.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 21.04 LTS
 - VS Code version: 1.63.2
 - Extension version: 8.23.0
 - TeX distribution version: TeX Live revision 56458

**Comment by jlelong** [comment]
It is very important to have access to the logs to identify the issue. So please add them to your initial post.

This is likely an issue with how you set your environment variable `PATH`. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable

**Comment by pehkawn** [comment]
Compiling `.tex` works fine, so I doubt this is issue is with TeX Live path. I can call `tlmgr` from any directory, so it has to be added to $PATH.

I changed back to the original `opt/anaconda3/lib/R/bin/R` and have added the output from LaTeX Compiler.

**Comment by jlelong** [comment]
> Compiling `.tex` works fine, so I doubt this is issue is with TeX Live path. I can call `tlmgr` from any directory, so it has to be added to `$PATH`.

You did not get my point. If LW is not using the correct version of `R`, this is because the value of `PATH` in VS Code is wrong and contains `opt/anaconda3/lib/R/bin/R` before `/lib/R/bin/R`.  This has nothing to do with the TeX Live path. 

Please post the complete logs of the extension starting from `Initializing LaTeX Workshop`. 

![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77959270-98c77e00-72d6-11ea-8c58-4934a9fde39a.png)

You will find the value of `PATH` as seen by VS Code in the logs of the extension.

**Comment by pehkawn** [comment]
Sorry, I got a bit confused there why you wanted me to check TeXLive's path and what you wanted me to do.

I reset folder names, and tried compiling again in a new window. I have attached the full log from both LaTeX Workshop extension and LaTeX compiler.

**Comment by jlelong** [comment]
From the extension logs

```
[17:05:50] The environment variable $PATH: /opt/anaconda3/bin:/opt/anaconda3/condabin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/mplusdemo
```

This is why the `R` version from anaconda3 is used and not the one provided by the system. Now, you have to figure out where the is value for the `PATH` is set (have a look at files `/etc` also).

When, you launch VS Code from a terminal using `code -n .`, it inherits the values of the environment variables from your shell. This is well explained [here](https://help.ubuntu.com/community/EnvironmentVariables#Inheritance). Indeed, I recommend to read the whole article.

**Comment by pehkawn** [comment]
If you are referring to `/opt/anaconda3/bin:/opt/anaconda3/condabin` in path, I was already aware of this issue because it created problems in the past. 

I tried to [explain in my other post](https://github.com/James-Yu/LaTeX-Workshop/issues/3029#issuecomment-1002650151) on issue #3029, I deleted the R file in `/opt/anaconda3/bin` a while back. I then also had issues with two shell wrappers for R in $PATH, `opt/anaconda3/bin/R` and `/usr/local/bin/R`, each pointing to different home directories, `R_HOME_DIR=/opt/anaconda3/lib/R` and `R_HOME_DIR=/lib/R/bin/R`, respectively. There was no shell wrapper for the R executable in `$PATH` when I tried to compile the .Rnw.

Typing "R" in terminal yields:
```
~$ R --version
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
Which means R 4.1.2 must be set in $PATH, right?

**Comment by jlelong** [comment]
> Which means R 4.1.2 must be set in $PATH, right?

Not necessarily, The `PATH` used by VS Code when running a recipe is 

```
/opt/anaconda3/bin:/opt/anaconda3/condabin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/mplusdemo
```

This value of the `PATH` may be different from the one you have in a terminal (even in the terminal pane of VS Code). Check by running `echo $PATH`.

> ```
> [17:05:50] Recipe step 1: Rscript, -e,knitr::opts_knit$set(concordance = TRUE); knitr::knit('lwe.Rnw')```

Note that the recipe for compiling `.rnw` files looks for a `Rscript` executable and not directly for `R`. You may have a `Rscript`  pointing to the wrong `R` version.

**Comment by pehkawn** [comment]
> Note that the recipe for compiling .rnw files looks for a Rscript executable and not directly for R. You may have a Rscript pointing to the wrong R version.

Hmm, that may actually be what's causing it. There is an `Rscript` in `/opt/anaconda3/bin` which would be in VS Code's $PATH
Typing in terminal gives
```
$ Rscript --version
R scripting front-end version 3.2.2 (2015-08-14)
```
As mentioned, replacing the `R` file in the same directory with the one in `/lib/R/bin/R` resolved the issue. I can only assume the reason it worked is that `Rscript`, even if it's an older version, now can retrieve information from the newest R version. Anyway, both `R` and `Rscript` are now removed from `/opt/anaconda3/bin`. Hopefully, this will prevent any further issues.
