### ISSUE TITLE
Adding lines for autocompilations of .Rnw gives "Duplicate object key" warning

### ISSUE THREAD

**Issue by pehkawn** [James-Yu/LaTeX-Workshop#3029]
## Preliminary questions [Required]
Adding autocomile sentences returns "Duplicate object key" warnings.

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Adding the lines described in the [.Rnw wiki section](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#building-a-rnw-file) to `settings.json` returns two warnings in the "Problems", saying there are "Duplicate object keys".

### To Reproduce

1. Go to 'Files>Preferences>Settings'
2. Write `latex-workshop.latex.recipes' in the search filed.
3. Click on 'Edit in settings.json'
3. Insert code blocks from wiki
```
{
"name": "rnw2tex",
    "command": "Rscript",
    "args": [
      "-e",
      "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
    ],
    "env": {},

 "name": "Compile Rnw files",
 "tools": [
    "rnw2tex",
    "latexmk"
    ]
}
```

### Expected behavior

I am uncertain if these warnings matter, but they are caused by duplicate objects "name".

### LaTeX Workshop Output [Required]

```
{} settings.json ~/.config/Code/user
   Duplicate object key jsonc(520) [21,5]
   Duplicate object key jsonc(520) [21,5]
```
```
[{
	"resource": "/home/user/.config/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "520",
	"severity": 4,
	"message": "Duplicate object key",
	"source": "jsonc",
	"startLineNumber": 21,
	"startColumn": 5,
	"endLineNumber": 21,
	"endColumn": 11
},{
	"resource": "/home/user/.config/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "520",
	"severity": 4,
	"message": "Duplicate object key",
	"source": "jsonc",
	"startLineNumber": 29,
	"startColumn": 5,
	"endLineNumber": 29,
	"endColumn": 11
},]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Ubuntu 21.04.1 LTS
 - VS Code version: 1.63.2
 - Extension version: 8.23.0
 - TeX distribution version: revision 56458

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

Yes

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment]
Related to #2964 

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes for how to define recipes. Note that the recipe for building `.rnw` files is already defined in the extension without changing anything.

I guess you are playing around with the extension configuration because of #3028. You should investigate how you set your `PATH` instead. If you want to make sure you have the same `PATH` in your shell and in VS Code, directly launch VS Code from your shell using `code -n .`.

**Comment by pehkawn** [comment]
Yes, I started meddling around because of #3028. Since the recipe is already defined, I suppose I don't need to add the lines in settings.json.

Regarding $PATH variables. I am uncertain how I would proceed. I know that both R versions' directories were added to `$PATH` (`/usr/local/bin`, `/opt/anaconda3/bin`). I had problems with this earlier, so I simply removed the script in `/opt/anaconda3/bin`. After that the newest version of R (4.1.2) started normally. This also means that Anaconda's version could only have been called from Anaconda's R installation folder `opt/anaconda3/lib/R/bin/R`, which is not a `$PATH` variable.

Regarding running VS Code from shell (`code -n`). Sorry, but exactly how does this help me find which `$PATH` VS Code uses?

**Comment by jlelong** [comment]
> Yes, I started meddling around because of #3028. Since the recipe is already defined, I suppose I don't need to add the lines in settings.json.

Correct. Everything should just work fine out of the box. 

Please continue on #3028 and if you want more help post the complete logs of the extension there
