### ISSUE TITLE
keys for citations

### ISSUE THREAD

**Issue by jldodds** [James-Yu/LaTeX-Workshop#303]
### Description

I'm using the key field to sort my bibtex website entries.

```
@Misc{IHG,
  title =    {Industrial Haskell Group},
  howpublished = {\url{http://industry.haskell.org/}},
  key = {Industrial Haskell Group}
}
```

The autocomplete for the entry then uses the key field (which I can't use because it has spaces) instead of IHG

**Comment by James-Yu** [comment]
`key` is the official term that is used to describe the citation key. Therefore in the extension `key` is parsed as the intellisense hint key. You may consider changing your `key` entry to another name.

**Comment by jldodds** [comment]
This is still a bug. My comment about not being able to use the citation due to spaces is misleading. "key" is a distinct field, and cannot be used for citations. For example, 

```
@Misc{IHG,
  title =    {Industrial Haskell Group},
  howpublished = {\url{http://industry.haskell.org/}},
  key = {ihgweb}
}
```

cannot be cited using intellisense

**Comment by James-Yu** [comment]
`key` should not be used as a key, even in plain bibtex

**Comment by jldodds** [comment]
Indeed. Here is the autocomplete for the entry from my previous post however. The bib entry is valid but the suggestion should be `IHG`, not `ihgweb`
![autocomplete](https://user-images.githubusercontent.com/667803/32794349-728fe318-c91d-11e7-92b4-22ef304a7aa0.png)
