### ISSUE TITLE
No "Build" and "View" buttons on .Rnw files

### ISSUE THREAD

**Issue by pehkawn** [James-Yu/LaTeX-Workshop#3030]
## Preliminary questions [Required]
Could "Build" and "View" buttons be implemented for .Rnw files the same way as for .tex files?

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

When creating/opening a .tex file, a "Build" and a "View" button appears in the top right corner. However, when creating/opening a .Rnw file, these buttons do not appear. I am unsure whether there is something with my configuration, a bug, or simply lacking. Keyboard shortcut keys work normally though.

## To Reproduce  [Required]

1. Go to 'File>New file'
2. Click on 'Select language' and select 'R Sweave'
3. No buttons for "Build" and "View" in the top left corner
3. Repeat step 1 & 2, only now select 'LaTeX' as language.
4. The "Build" and "View" buttons now appear in the top right corner.

## Describe the solution you'd like  [Required]

Same functionality for .Rnw as for .tex.

## Logs [Required]

Assumed not to be relevant for this question.

## Screenshots
![.Rnw: Buttons missing in top right corner](https://user-images.githubusercontent.com/44672121/147680373-c2f403a6-4692-4067-bbcd-ab64c3eb452f.png)
![.tex: "Build" and "view" buttons in top right corner](https://user-images.githubusercontent.com/44672121/147680435-df60314d-933f-4607-aa52-6c49ca929c87.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

- OS: Ubuntu 21.04.1 LTS
- VS Code version: 1.63.2
- Extension version: 8.23.0
- TeX distribution version: revision 56458

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by pehkawn** [comment]
Thanks for improving the issue so fast. Is there a way to apply the changes already now?

**Comment by jlelong** [comment]
Unfortunately not. I am afraid you will have to wait for the next release.
