### ISSUE TITLE
Classic ENOENT - Rehashed

### ISSUE THREAD

**Issue by Pedro-Roque** [James-Yu/LaTeX-Workshop#3033]
A double of https://github.com/James-Yu/LaTeX-Workshop/issues/3032#issue-1092103643 - which was closed without a proper fix.

@tamuratak , thank you for your hint, but my configuration is completely default - I limited myself to install texlive-full and Latex Workshop.

I'd appreciate some insight since I tried to fix the issue on my own first without success.

**EDIT:** apparently a setting was creating on my settings file for this. Should this be default behavior? Removing it fixes the issue....

**Comment by tamuratak** [comment]
> apparently a setting was creating on my settings file for this. Should this be default behavior? Removing it fixes the issue....

The behavior is not related to LaTeX Workshop. LaTeX Workshop never changes user settings.
