### ISSUE TITLE
Register bracket pairs \left| ... \right|, \left\| ... \right\|, \langle ... \rangle, \lvert ... \rvert, \lVert ... \rVert

### ISSUE THREAD

**Issue by matrix-ranger** [James-Yu/LaTeX-Workshop#3036]
They are not registered currently as you can see [here](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/latex3-language-configuration.json).

(Also for combinations with \bigl \bigr and \left \right etc.)

**Comment by jlelong** [comment]
Could you please make a comprehensive list of bracket pairs you would like to see added?

**Comment by matrix-ranger** [comment]
\langle ... \rangle
\lvert ... \rvert
\lVert ... \rVert
\left| ... \right| 
\left\| ... \right\|
\left\langle ... \right\rangle
\left\lvert ... \right\rvert
\left\lVert ... \right\rVert
\bigl\langle ... \bigr\rangle
\bigl| ... \bigr|
\bigl\vert ... \bigr\vert
\bigl\lvert ... \bigr\rvert
\bigl\| ... \bigr\|
\bigl\lVert ... \bigr\rVert
\bigl\Vert ... \bigr\Vert
\Bigl\langle ... \Bigr\rangle
\Bigl| ... \Bigr|
\Bigl\lvert ... \Bigr\rvert
\Bigl\vert ... \Bigr\vert
\Bigl\| ... \Bigr\|
\Bigl\lVert ... \Bigr\rVert
\Bigl\Vert ... \Bigr\Vert
\biggl\langle ... \biggr\rangle
\biggl| ... \biggr|
\biggl\lvert ... \biggr\rvert
\biggl\vert ... \biggr\vert
\biggl\| ... \biggr\|
\biggl\lVert ... \biggr\rVert
\biggl\Vert ... \biggr\Vert
\Biggl\langle ... \Biggr\rangle
\Biggl| ... \Biggr|
\Biggl\lvert ... \Biggr\rvert
\Biggl\vert ... \Biggr\vert
\Biggl\| ... \Biggr\|
\Biggl\lVert ... \Biggr\rVert
\Biggl\Vert ... \Biggr\Vert

**Comment by matrix-ranger** [comment]
Looks like a lot but they are quite common when you write math proofs.

**Comment by matrix-ranger** [comment]
Also, it seems [this file](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX.tmLanguage.json) also needs to be updated as suggested by [this issue](https://github.com/microsoft/vscode/issues/137774).

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to https://github.com/jlelong/vscode-latex-basics, so we have moved the issue to that repository: jlelong/vscode-latex-basics#13
