### ISSUE TITLE
word count in the status bar

### ISSUE THREAD

**Issue by drdebmath** [James-Yu/LaTeX-Workshop#3041]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

No

## To Reproduce  [Required]

It exists inside the menu of the LaTeX Workshop.

## Describe the solution you'd like  [Required]

It would be great to include the word count of the compiled Latex Document in the status bar. 
An extension doing the same exists at https://marketplace.visualstudio.com/items?itemName=geoffkaile.latex-count

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Screenshots

<img width="467" alt="Screenshot 2022-01-05 at 5 01 35 PM" src="https://user-images.githubusercontent.com/5823408/148248934-b7f7a3bb-0c62-4766-8efb-f4a27e3c0e8f.png">

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Mac OS
 - VS Code version: 1.61
 - Extension version: 8.23
 - TeX distribution version: MacTex 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

It would be easier to keep track of word limits.

**Comment by jlelong** [comment]
This is out of the scope of the extension.

**Comment by drdebmath** [comment]
Hi Professor @jlelong , my point was the information is already present in the extension in the `Miscellanous: Count words in Latex project` section. Sorry, I am not sure how much work is required to do this, since it is only required to display existing info. The word count in the pdf matters more compared to the word count in the existing tex file, so I suggested this. Thanks again for your reply.

**Comment by jlelong** [comment]
The information is obtained by calling the `texcount` utility. Hence, this is not directly available and certainly not live. Then, I do not think this is a good idea to display it permanently in the status bar.

**Comment by drdebmath** [comment]
Can we not update it only when we compile it? 

1. Does that create more overhead?
2. Or in case of compilation failure, does it not work? 

If any of 1 or 2 is true, then I agree with you. Thanks.

**Comment by jlelong** [comment]
After giving a second thought, I could add a setting to automatically call `texcount` on save. The result would be displayed in a popup window as it is when _Miscellanous: Count words in Latex project_ is called.

**Comment by jlelong** [comment]
Setting `latex-workshop.texcount.autorun` to `onSave` displays the word count in the status bar next to the _line / column_ information. It is only updated on save and only counts the number of words in the current document.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#counting-words

**Comment by drdebmath** [comment]
Thank you for adding this feature. I agree with your approach regarding the current document. One small question: suppose I have `input1.tex` to `main.tex` and I am editing `input1.tex`, does it only count words in`input1.tex`?

**Comment by jlelong** [comment]
Yes, if the active editor is `input1.tex`, it only counts the words there.

**Comment by drdebmath** [comment]
Thank you again. When will this update be released?

**Comment by jlelong** [comment]
This will be part of the next release but I do not know exactly when. Probably in a couple of weeks or so.
