### ISSUE TITLE
latex inbuild PDF viewer by default connect to localhost to serve PDF

### ISSUE THREAD

**Issue by VinothKumar-V** [James-Yu/LaTeX-Workshop#3051]
Hi 
We have deployed VScode and Latex Workshop on remote machine and access it through web browser, 
so when ever we build PDF and try to preview using VSCode/Web-Browser it try to open file from localhost( Browser Host not from remote host ), so end up saying localhost refused to connect

is there way that we can change this behavior?

**Comment by tamuratak** [comment]
> is there way that we can change this behavior?

No.

Please use VS Code Remote: https://code.visualstudio.com/docs/remote/ssh-tutorial

**Comment by tamuratak** [comment]
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
