### ISSUE TITLE
Change the syntax highlighting in verbatim or listings sections.

### ISSUE THREAD

**Issue by JamieMair** [James-Yu/LaTeX-Workshop#3054]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? 

When I am using a package to enable proper typesetting of Julia code, the syntax highlighting does not use the Julia syntax highlighting, but the default latex highlighting. This is shown below:
![image](https://user-images.githubusercontent.com/13971435/149601532-7d1c2f89-1bae-441d-b701-8decba768276.png)
This becomes an issue when using special characters:
![image](https://user-images.githubusercontent.com/13971435/149601551-8529d278-02e4-427f-a592-e73ea9db8477.png)

## To Reproduce  [Required]

Insert code as shown above. This can be useful for the verbatim package as well.

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: jlelong/vscode-latex-basics#14
