### ISSUE TITLE
PDF Viewer broken, produces white artifacts

### ISSUE THREAD

**Issue by LukasDr23** [James-Yu/LaTeX-Workshop#3063]
Since the last Windows 11 update, the internal PDF viewer does not work reliably anymore. It produces blank spots where some letters get cut off. Opening the produced PDF in an external viewer (either Edge or Adobe Reader) results in a correct PDF. 

![image](https://user-images.githubusercontent.com/30218247/150367627-d4130648-106b-45b2-af34-1304f2f4bc53.png)

Tried already to reinstall the Extension and VSCode itself.

**Comment by tamuratak** [comment]
Please try

```
code --disable-gpu
```

- https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#the-pdf-viewer-is-blank-or-has-graphical-glitches
- https://code.visualstudio.com/docs/supporting/FAQ#_vs-code-is-blank

We can do nothing on our side. Please report to https://github.com/microsoft/vscode

**Comment by LukasDr23** [comment]
thanks a lot, disabling the gpu for vscode did solve it for now, I'll report the bug to vscode.
