### ISSUE TITLE
No math style commands provided for snippets

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#3064]
# No math style commands provided for snippets

LaTeX provides commands to determine 4 math styles, but LaTeX Workshop does not provide snippet.

- `\displaystyle`
- `\textstyle`
- `\scriptstyle`
- `\scriptscriptstyle`

> [Math styles (LaTeX2e unofficial reference manual (October 2021))](https://latexref.xyz/Math-styles.html#index-_005cscriptscriptstyle)

## Desktop

- OS: Windows10
- VS Code version: 1.63.2
- Extension version: 8.23.0
- TeX distribution version: TeX Live2021

**Comment by jlelong** [comment]
I agree that `\displaystyle` could be added to the list of completion items. However, the other three commands are used far less often. I suggest to define your own snippets, see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets.
