### ISSUE TITLE
Set details to snippet completion items

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3065]
We had better set `CompletionItem.detail` of snippet completion items. It is difficult for new users to figure out what `@6` and others are.

https://github.com/James-Yu/LaTeX-Workshop/blob/1c0538ab2f2e69454618f3d541b1e3d2ed7fdd59/src/providers/completer/snippet.ts#L32-L38

![スクリーンショット 2022-01-23 15 55 18](https://user-images.githubusercontent.com/10665499/150668097-af5aed8c-e467-4014-8bc9-3ca69b39a2c4.png)

**Comment by jlelong** [comment]
I agree with you. You can already find the information you are looking for in the _detail widget_. Note that if you open the _detail widget_ once, it will automatically open on further completion triggers.

<img width="793" alt="Capture d’écran 2022-01-23 à 16 49 05" src="https://user-images.githubusercontent.com/2910140/150686741-22b1d1e9-18df-4d01-ac23-545f0446aa8d.png">

If we add `completionItem.detail = item.description` to https://github.com/James-Yu/LaTeX-Workshop/blob/3a5a3c2b6958ff09e6a7d45d5744169dc3a0357a/src/providers/completer/snippet.ts#L36 and set `editor.suggest.showInlineDetails=True` (see microsoft/vscode#109690), we have

<img width="470" alt="Capture d’écran 2022-01-23 à 16 49 52" src="https://user-images.githubusercontent.com/2910140/150686868-2415c195-7fe4-45cf-8bc5-0ae0cd106de8.png">
