### ISSUE TITLE
Announce breaking changes in the extension itself

### ISSUE THREAD

**Issue by slhck** [James-Yu/LaTeX-Workshop#3067]
## Is your requested feature  related to a problem? Please describe. [Required]

See https://github.com/James-Yu/LaTeX-Workshop/issues/3066

## Describe the solution you'd like  [Required]

The extension should announce breaking changes to the user by means of a popup window.

The background is that a breaking change was introduced in a recent minor version release, disabling a feature that was previously activated. This causes confusion for end-users, aind in the particular case, it was not easy to remediate the issue.

It cannot be reasonably expected from end users to follow "announcement" labels on GitHub repositories for VS Code extensions. Since there are mechanisms for showing such information in VS Code itself, it would be good to use this kind of channel for any future breaking/feature changes.

Examples for such behavior are shown here: https://stackoverflow.com/questions/63840742/how-can-i-display-a-message-when-someone-updates-to-a-new-version-of-my-extensio

**Comment by slhck** [comment]
PS/Meta: I saw that #3066 was immediately locked after being closed. I find this a bit irritating since there may be valid reasons for other users to comment on this behavior, or provide workarounds, etc. Is there any other channel for discussions? I see no other place for that.

**Comment by tamuratak** [comment]
> The extension should announce breaking changes to the user by means of a popup window.

Out of the scope of the extension.

> PS/Meta: I saw that #3066 was immediately locked after being closed. I find this a bit irritating since there may be valid reasons for other users to comment on this behavior, or provide workarounds, etc. Is there any other channel for discussions? I see no other place for that.

If you want premium customer support, please use other applications.
