### ISSUE TITLE
Question: why do you guys recommend Texlive over Miktex?

### ISSUE THREAD

**Issue by lightningHoneypot** [James-Yu/LaTeX-Workshop#3068]
the question from above, it would be nice if one of you could explain why; maybe you could link this question to the wiki too once you guys answered.

**Comment by tamuratak** [comment]
Read

> Please note MiKTeX does not ship with Perl. You have to install Perl by yourself, which latexmk requires.

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#requirements
