### ISSUE TITLE
Support Multi-root Workspaces

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#307]
This will be great!

**Comment by James-Yu** [comment]
Can you please describe in details how the extension should change to adopt multi-root workspace? AFAIK the extension does not care about single or multi root when finding the root LaTeX file.

**Comment by innerlee** [comment]
this pr https://github.com/JamesYu/LaTeX-Workshop/pull/308 is what i mean :P

**Comment by James-Yu** [comment]
Will discuss there.
