### ISSUE TITLE
\coloneq and \coloneqq in the math-preview-panel

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#3072]
Seems that \coloneq and \coloneqq are not working properly in Math-Preview-Panel.
The error seems to be in the file data/unimathsymbols.json, lines 1677 and 1678, where it should be "coloneqq" instead of "coloneq".
Then, compare also the lines 381-385 in the same file.
Thank you for your incredible work on LaTeX-Workshop!

**Comment by tamuratak** [comment]
Add `mathtools` to `latex-workshop.hover.preview.mathjax.extensions`

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewmathjaxextensions
