### ISSUE TITLE
Add mathtools to defaults for mathjax preview

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#3073]
### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

Mathtools is a widely used extension, and I would think most users of LaTeX Workshop would benefit from having it enabled by default (for the same reason ams is). Especially since many may not even be aware that it has been implemented in mathjax now.

See for instance the recent issue https://github.com/James-Yu/LaTeX-Workshop/issues/3072

## Describe the solution you'd like  [Required]

Add mathtools to defaults for latex-workshop.hover.preview.mathjax.extensions

**Comment by tamuratak** [comment]
Rejected.

It is configurable. That's enough.
