### ISSUE TITLE
Add switches btw display & inline math mode, btw $$...$$ and \[...\]

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [James-Yu/LaTeX-Workshop#3074]
Checking before asking this question: 

- [x] yes, I have read through the wiki. 

Is there a possibility to add a functionality to switch between TeX math mode parentheses \[...\] and LaTeX's $$...$$ in an equation, likewise I can use a shortcut provided by extension to toggle between \begin{equation} ... \end{equation} and \[...\] in the .tex file? 
I am asking this because I frequently typeset math formulae in .tex using the Math Display Panel which AFAIK currently [does not work](https://github.com/James-Yu/LaTeX-Workshop/pull/1284) for LaTeX Display Mode ($$) due to difficulties in the determination of the boundaries of math formulae, so I have to type \[...\]. 
The problem of mine is that the main document is sometimes in R Markdown (sic, not RSweave, since R and Python are being used interchangeably), which expects the formulae embedded in $$...$$. Another walkaround could be writing inline equations initially $...$, but then I would also like to convert these to $$...$$ with some shortcut.

I understand that in many cases I can just regex-replace \[ and \] to $$...$$ .  
Thanks in advance for any response!

**Comment by tamuratak** [comment]
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.
- Please paste a sample LaTeX file.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by jlelong** [comment]
`$$` is actually a TeX primitive. LaTeX advocates the use of `\[...\]` for display math, see for instance https://tex.stackexchange.com/a/69854. So, even if I understand why you ask, a function to turn `\[...\]` into `$$...$$` would sound weird. Moreover, finding the boundaries of math formulae with `$$...$$` would still be an issue as in #1284.
