### ISSUE TITLE
 Feature Request - support diff and revision 

### ISSUE THREAD

**Issue by johnvon** [James-Yu/LaTeX-Workshop#3077]
Although it has been discussed before (see #411), I think it would be very helpful if the diff (with latexdiff) and review functions can be supported by LaTeX-Workshop.  I think of the following workflow, but don't know if it is possible. 

Firstly, generate the diff LaTeX file (diff.tex), by wrapping the following commands：
- latexdiff: need two tex files as inputs
- latexdiff-vc: compare the current version to the last commit (default)
Note: the default behavior of the above two commands have many options.

Secondly, open diff.tex file generated in the last operation (which is in the current folder) without leaving the vscode.

Thirdly, generate the diff.pdf directly using the diff.tex file, Or use review function described below, which are similar with these in MS Word, such as: 

1. **reject all revision**  (provided by latexdiff and latexidff-vc, or completed by vscode replace using regex)
2. **accept all revision** (same with the above)
3. **find next revision** (can be done by searching for the latexdiff marks using regex )
4. **find previous revision** (similar with the above)
4. **accept the current revision** (remove the latexdiff marks from the current selected (located by the find command), which can be done using  the vscode replace operation using regex match enabled)
5. **reject the current revision** (similar with the above)
6. 
After the required revisions, we can generate the final pdf.

**Comment by tamuratak** [comment]
Out of the scope of the extension.
