### ISSUE TITLE
What is the realease tagging policy ? 

### ISSUE THREAD

**Issue by lrnv** [James-Yu/LaTeX-Workshop#3079]
Hey, 

I would love to get the feature from #1898, which was merged a month ago into master. 

- I did not see the release policy of the repo stated anywhere, did I miss it ? 
- When would the next release occur ? 
- Is there a way to use the master branch of the extension while waiting ?

**Comment by tamuratak** [comment]
> I did not see the release policy of the repo stated anywhere, did I miss it ?

We don't have such a policy due to the maintenance burden.

> When would the next release occur ?

Please wait.

> Is there a way to use the master branch of the extension while waiting ?

See how to build the extension. 

- https://github.com/James-Yu/LaTeX-Workshop/blob/master/CONTRIBUTING.md
