### ISSUE TITLE
Do not show equation number in Previewing equations

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#3080]
# Do not show equation number in Previewing equations

Or add a setting that can be configured to be hidden.

Displaying the eqution number makes it difficult to see the equation. This becomes more noticeable when you reload VS Code.

Sometimes you want to see the equation from `\ref{labelName}`, but equation number doesn't matter. It doesn't matter if equation number isn't displayed. If you need equation number, refer to PDF.
However, you may need a mechanism to clarify which equation you are referencing.

You can hide equation numbering with `latex-workshop.hover.ref.number.enabled`, but `labelName` is displayed instead, so `labelName` and equation are still overlaped.

## Demo

Demo is shown below.

```latex
\documentclass{article}
\usepackage{amsmath}
\begin{document}

\begin{align}
  f(x)
    & = ax^2 + bx + c
    % Just ``\label" without ``\ref"
    \label{eqn:Quadratic_equation}
    \\
    & = a\left( x + \frac{b}{2a} \right)^2 - \frac{b^2}{4a} + c
    \label{eqn:Completing_the_square}
\end{align}

% Do not include this ``\ref" ↓
%% \ref{eqn:Completing_the_square}

\ref{eqn:Quadratic_equation}

\end{document}
```

| Hover on environment name                                                         |
| :-------------------------------------------------------------------------------- |
| You can preview the equations without any problem. <br> ![On environment name][1] |

[1]: https://i.gyazo.com/16e3f3a6fdfce7c4e9bba6bf19890c68.png

| Hover on `\ref` (and `\label`) after *compile*                                                                                      |
| :---------------------------------------------------------------------------------------------------------------------------------- |
| The equation is hidden a little. Equation number is displayed only in the referenced equation. <br> ![On ref after compile][2] |

[2]: https://i.gyazo.com/a4c569affedeab49d4137848d0b77676.png

| Hover on `\ref` (and `\label`) after *reload*                    |
| :--------------------------------------------------------------- |
| I can't see the equation at all!! <br> ![On ref after reload][3] |

[3]: https://i.gyazo.com/84d14614d21905b9014a3b50f853af14.png

Previewing equations feature is great, but it spoils because it displays equation number.

On the other hand, in `Realtime math preview panel`, the width is wide, so displaying equation numbering may not cause such a problem. This is just an idea.

## Version

- Windows10
- VSCode: 1.64.1
- LaTeX Workshop: 8.23.0

**Comment by tamuratak** [comment]
I agree that it is not usable displaying labels.  This is duet to the migration to MathJax 3.2.

Now, we don't display numbers when:
```
latex-workshop.hover.ref.number.enabled: false
```
