### ISSUE TITLE
Change settings scope from "window" (default) to "resource" for a number of settings

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#3082]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

I have two docs in a structure like this:
```
D:\BUG
│   bug.code-workspace
│
├───doc1
│   └───.vscode
│           settings.json
│
└───doc2
```

I open both docs in one VS Code window. This is what `bug.code-workspace` is for.

In `doc1`, I would like to set a few settings that I do not want to apply to `doc2`. This is what `doc1/.vscode/settings.json` is for, and it looks like this:

```json
{
    "editor.wordWrapColumn": 88,
    "latex-workshop.latexindent.args": [
        "-c",
        "%DIR%/",
        "%TMPFILE%",
        "-y=defaultIndent: '%INDENT%'",
        "-l",
    ],
}
```

So far, so good. However, this is not working because `latex-workshop.latexindent.args` is window-scoped, while `editor.wordWrapColumn` is resource-scoped. In line with that, the setting is greyed out and not applied:

![image](https://user-images.githubusercontent.com/12128514/153915001-83c233fe-c102-4f57-b00d-16e5d49028fb.png)

The reason is that the setting is not properly scoped - it has `window` scope:
https://github.com/microsoft/vscode/blob/6136c815bc6e7b99ec2dac56dccb3869574d2dd8/src/vs/workbench/contrib/preferences/browser/preferencesRenderers.ts#L596-L603

And the reason for that is that it does not have an explicit scope at all, so it falls back to `window` - see https://code.visualstudio.com/api/references/contribution-points:
https://github.com/James-Yu/LaTeX-Workshop/blob/04f73108e439661faef2c8f85eac7baacbdb736b/package.json#L1810-L1822

This is certainly not intentional - I see no reason for this setting to (necessarily) be the same for all resources in a window. It should be able to differ by resource (folder).

## Describe the solution you'd like  [Required]

The fix is simple: set the scope for `latex-workshop.latexindent.args` (and probably other settings as well) to `resource`. Happy to provide a PR if that helps.

**Comment by jlelong** [comment]
I never paid attention to the possibility to assign a scope to a setting. What you suggest sounds reasonable. I guess other settings should also have a `resource` scope. We should try to make a list.

**Comment by bersbersbers** [comment]
Maybe an inverse list is appropriate, too. I went through the list of settings

https://github.com/James-Yu/LaTeX-Workshop/blob/04f73108e439661faef2c8f85eac7baacbdb736b/package.json#L763-L2128

and to be honest, I had a hard time finding settings which should remain `window`-scoped. (I always wonder why that is the default - probably historic reasons). Everything related to a editing or compiling a specific file (editor settings, syntax, tools, etc.) should be `resource`-scope IMHO.

The ones I found that *may* not be correct to scope by `resource` are the ones that may not be uniquely tied to a single document, such as everything related to (pre-)loading and configuring extensions used by multiple documents:

```
latex-workshop.view.pdf.*
latex-workshop.mathpreviewpanel.*
latex-workshop.hover.preview.mathjax.extensions
```

**Comment by tamuratak** [comment]
Notice that we have to rewrite the way of calling `workspace.getConfiguration`.

See https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#settings-api

> The configuration example above defines a setting scoped to a resource. To fetch its value you use the workspace.getConfiguration() API and pass the URI of the resource as the second parameter. You can see [Example 3](https://github.com/Microsoft/vscode-extension-samples/blob/master/configuration-sample/src/extension.ts) how the setting is used in the basic-multi-root sample.

- https://github.com/microsoft/vscode-extension-samples/blob/e52c48f22a81355b568f3cde8c60538726caad22/configuration-sample/src/extension.ts#L76-L96

**Comment by jlelong** [comment]
My 2c comment on why `window` is the default scope. In VS Code, a window corresponds to an instance. This implies that only a single instance of an extension can run inside a window. Some settings require to reload the window after change typically because they are used in constructors (theirs values are fixed in the instance). All these settings must not have the `resource` scope. This is probably why the default scope is `window`.

Hence, making the list of settings that could have the `resource` scope is not so simple. All this requires a lot of care to avoid introducing very tricky bugs.

**Comment by bersbersbers** [comment]
> Some settings require to reload the window after change typically because they are used in constructors (theirs values are fixed in the instance).

Thanks, understood. This is what I meant when I used the somewhat ill-defined term "pre-loading", so I fully agree that the implementation determines whether or not a setting can be `resource`-scoped, and not the uninitiated issue author browsing by the code ;)

**Comment by jlelong** [comment]
Here is the list of properties that might be assigned a `resource` scope

```
 latex-workshop.latex.recipe.default
 latex-workshop.latex.tools
 latex-workshop.latex.magic.args
 latex-workshop.latex.magic.bib.args
 latex-workshop.latex.external.build.command
 latex-workshop.latex.external.build.args
 latex-workshop.latex.build.forceRecipeUsage
 latex-workshop.latex.outDir
 latex-workshop.latex.texDirs
 latex-workshop.latex.verbatimEnvs
 latex-workshop.kpsewhich.path
 latex-workshop.kpsewhich.enabled
 latex-workshop.latex.bibDirs
 latex-workshop.latex.search.rootFiles.include
 latex-workshop.latex.search.rootFiles.exclude
 latex-workshop.latex.rootFile.useSubFile
 latex-workshop.latex.rootFile.doNotPrompt
 latex-workshop.latex.autoBuild.run
 latex-workshop.latex.autoBuild.interval
 latex-workshop.latex.autoBuild.cleanAndRetry.enabled
 latex-workshop.latex.build.clearLog.everyRecipeStep.enabled
 latex-workshop.latex.autoClean.run
 latex-workshop.latex.clean.subfolder.enabled
 latex-workshop.latex.clean.fileTypes
 latex-workshop.latex.clean.command
 latex-workshop.latex.clean.args
 latex-workshop.latex.clean.method
 latex-workshop.latex.option.maxPrintLine.enabled
 latex-workshop.view.pdf.viewer
 latex-workshop.view.pdf.tab.editorGroup
 latex-workshop.view.pdf.tab.openDelay
 latex-workshop.view.pdf.ref.viewer
 latex-workshop.view.pdf.internal.synctex.keybinding
 latex-workshop.view.pdf.external.viewer.args
 latex-workshop.view.pdf.external.synctex.command
 latex-workshop.view.pdf.external.synctex.args
 latex-workshop.synctex.path
 latex-workshop.synctex.afterBuild.enabled
 latex-workshop.synctex.synctexjs.enabled
 latex-workshop.chktex.enabled
 latex-workshop.chktex.run
 latex-workshop.chktex.path
 latex-workshop.chktex.args.active
 latex-workshop.chktex.args.root
 latex-workshop.chktex.delay
 latex-workshop.chktex.convertOutput.column.enabled
 latex-workshop.chktex.convertOutput.column.chktexrcTabSize
 latex-workshop.texcount.path
 latex-workshop.texcount.args
 latex-workshop.texcount.autorun
 latex-workshop.texcount.interval
 latex-workshop.intellisense.citation.type
 latex-workshop.intellisense.citation.label
 latex-workshop.intellisense.citation.format
 latex-workshop.intellisense.file.exclude
 latex-workshop.intellisense.file.base
 latex-workshop.intellisense.label.keyval
 latex-workshop.intellisense.unimathsymbols.enabled
 latex-workshop.intellisense.package.enabled
 latex-workshop.intellisense.package.extra
 latex-workshop.intellisense.package.dirs
 latex-workshop.intellisense.includegraphics.preview.enabled
 latex-workshop.message.badbox.show
 latex-workshop.message.bibtexlog.exclude
 latex-workshop.message.latexlog.exclude
 latex-workshop.message.information.show
 latex-workshop.message.warning.show
 latex-workshop.message.error.show
 latex-workshop.message.log.show
 latex-workshop.latexindent.path
 latex-workshop.latexindent.args
 latex-workshop.hover.ref.enabled
 latex-workshop.hover.ref.number.enabled
 latex-workshop.hover.citation.enabled
 latex-workshop.hover.command.enabled
 latex-workshop.hover.preview.enabled
 latex-workshop.hover.preview.maxLines
 latex-workshop.hover.preview.scale
 latex-workshop.hover.preview.newcommand.parseTeXFile.enabled
 latex-workshop.hover.preview.newcommand.newcommandFile
 latex-workshop.hover.preview.cursor.enabled
 latex-workshop.hover.preview.cursor.symbol
 latex-workshop.hover.preview.cursor.color
 latex-workshop.intellisense.optionalArgsEntries.enabled
 latex-workshop.intellisense.useTabStops.enabled
 latex-workshop.texdoc.path
 latex-workshop.texdoc.args
```

I do not think it really makes sense for all of them. In particular, I believe everything related to  `intellisense`, `hover`, `kpsewhich`, `message` and `view` should not be changed. That would give a much shorter list

```
latex-workshop.latex.recipe.default
 latex-workshop.latex.tools
 latex-workshop.latex.magic.args
 latex-workshop.latex.magic.bib.args
 latex-workshop.latex.external.build.command
 latex-workshop.latex.external.build.args
 latex-workshop.latex.build.forceRecipeUsage
 latex-workshop.latex.outDir
 latex-workshop.latex.search.rootFiles.include
 latex-workshop.latex.search.rootFiles.exclude
 latex-workshop.latex.rootFile.useSubFile
 latex-workshop.latex.rootFile.doNotPrompt
 latex-workshop.latex.autoBuild.run
 latex-workshop.latex.autoBuild.interval
 latex-workshop.latex.autoBuild.cleanAndRetry.enabled
 latex-workshop.latex.build.clearLog.everyRecipeStep.enabled
 latex-workshop.latex.autoClean.run
 latex-workshop.latex.clean.subfolder.enabled
 latex-workshop.latex.clean.fileTypes
 latex-workshop.latex.clean.command
 latex-workshop.latex.clean.args
 latex-workshop.latex.clean.method
 latex-workshop.latex.option.maxPrintLine.enabled
 latex-workshop.synctex.path
 latex-workshop.synctex.afterBuild.enabled
 latex-workshop.synctex.synctexjs.enabled
 latex-workshop.chktex.enabled
 latex-workshop.chktex.run
 latex-workshop.chktex.path
 latex-workshop.chktex.args.active
 latex-workshop.chktex.args.root
 latex-workshop.chktex.delay
 latex-workshop.chktex.convertOutput.column.enabled
 latex-workshop.chktex.convertOutput.column.chktexrcTabSize
 latex-workshop.texcount.path
 latex-workshop.texcount.args
 latex-workshop.texcount.autorun
 latex-workshop.texcount.interval
 latex-workshop.intellisense.file.exclude
 latex-workshop.intellisense.file.base
 latex-workshop.latexindent.path
 latex-workshop.latexindent.args
 latex-workshop.texdoc.path
 latex-workshop.texdoc.args
```

Any thoughts on this?

**Comment by bersbersbers** [comment]
> I believe everything related to `intellisense`, `hover`, `kpsewhich`, `message` and `view` should not be changed.

I wonder why that is. Is that motivated by the required implementation effort, or by your opinion that these should not be configurable by `resource` from a use-case perspective? As far as I have understood settings scopes, changing a `window`-scoped setting to a `resource`-scoped setting will not break anything at all for existing users - it will only open additional possibilities to move a setting into a resource-specific location. So I wonder what the motivation is to prevent users from, for example, using different `latex-workshop.intellisense.file.exclude` patterns for different documents, or from adapting `latex-workshop.intellisense.update.delay` for each document to account for different document sizes and thus processing times (just two examples, I might be able to think of more).

**Comment by tamuratak** [comment]
I agree the list is reasonable. We can discuss further on a pull request. We might have to remove some of them due to the implementation difficulty.

**Comment by jlelong** [comment]
To make things crystal clear. Any properties not listed in my first list cannot be assigned a `resource` scope without heavy implementation changes, which we will not make.  You mention `latex-workshop.intellisense.update.delay`, which was not in my fisrt and `latex-workshop.intellisense.file.exclude`, which I kept in the second one.

Because of the need to access the document `uri`, some of these properties may still be removed from the second list.

https://github.com/microsoft/vscode-extension-samples/blob/e52c48f22a81355b568f3cde8c60538726caad22/configuration-sample/src/extension.ts#L76-L96

**Comment by jlelong** [comment]
I suggest to wait until we know more about 

- microsoft/vscode#143462
