### ISSUE TITLE
build failed with that ReadableStream is not defined

### ISSUE THREAD

**Issue by stu-GYULA** [James-Yu/LaTeX-Workshop#3084]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
Whenever I start the build command, the symbol in the bottom bar starts spinning. The compiler is not started and it's output is Ready. latexmk in the console works. 

This bug is similar with #1134. But the developer console error is not the same.
The error of developer console in this bug is 'ReferenceError: ReadableStream is not defined'.

### To Reproduce
1. Build LaTeX Project

### Expected behavior
Start and complete the build process 

### LaTeX Workshop Output [Required]

<details>
<summary>Latex Workshop log</summary>
<pre><code>
[03:19:42] Initializing LaTeX Workshop.
[03:19:42] Creating PDF file watcher.
[03:19:42] Creating LaTeX Workshop http and websocket server.
[03:19:42] LaTeX Workshop initialized.
[03:19:42] Started finding workspace...
[03:19:42] Current workspace folders: ["file:///root/test"]
[03:19:42] Current workspaceRootDir: /root/test
[03:19:42] Found root file from active editor: /root/test/test.tex
[03:19:42] Root file changed: from undefined to /root/test/test.tex
[03:19:42] Start to find all dependencies.
[03:19:42] Instantiating a new file watcher for /root/test/test.tex
[03:19:42] Creating Bib file watcher.
[03:19:42] Parsing a file and its subfiles: /root/test/test.tex
[03:19:42] Parse fls file.
[03:19:42] Cannot find fls file: /root/test/test.fls
[03:19:42] Server created on 127.0.0.1:46005
[03:19:42] Added to file watcher: /root/test/test.tex
[03:19:42] Snippet data loaded.
[03:19:42] LaTeX Workshop version: 8.11.1
[03:19:47] BUILD command invoked.
[03:19:47] Started finding workspace...
[03:19:47] Current workspace folders: ["file:///root/test"]
[03:19:47] Current workspaceRootDir: /root/test
[03:19:47] Found root file from active editor: /root/test/test.tex
[03:19:47] Keep using the same root file: /root/test/test.tex.
[03:19:47] Building root file: /root/test/test.tex
[03:19:47] Build root file /root/test/test.tex
[03:19:57] Started finding workspace...
[03:19:57] Current workspace folders: ["file:///root/test"]
[03:19:57] Current workspaceRootDir: /root/test
[03:19:57] Found root file from active editor: /root/test/test.tex
[03:19:57] Keep using the same root file: /root/test/test.tex.
</code></pre>
</details>

### Developer Tools Console [Required]

<details>
<summary>Developer Tools Console Output (before build latex project)</summary>
<pre><code>
workbench.desktop.main.js:578  INFO IExtensionHostStarter.start() took 22 ms.
workbench.desktop.main.js:578   ERR [Extension Host] (node:23316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:75 [Extension Host] (node:23316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
I @ workbench.desktop.main.js:75
workbench.desktop.main.js:578  INFO Invoking resolveAuthority(attached-container)
workbench.desktop.main.js:578  INFO resolveAuthority(attached-container) returned '127.0.0.1:32895' after 5013 ms
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///e%3A/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f746865736973227d/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:1722
A @ workbench.desktop.main.js:1724
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
createTokenizationSupport @ workbench.desktop.main.js:1898
_create @ workbench.desktop.main.js:186
resolve @ workbench.desktop.main.js:186
getOrCreate @ workbench.desktop.main.js:186
(anonymous) @ workbench.desktop.main.js:1898
_handle @ workbench.desktop.main.js:1489
acceptUsers @ workbench.desktop.main.js:1489
_handleExtensionPoint @ workbench.desktop.main.js:3036
_doHandleExtensionPoints @ workbench.desktop.main.js:3036
_startLocalExtensionHost @ workbench.desktop.main.js:3039
async function (async)
_startLocalExtensionHost @ workbench.desktop.main.js:3039
_scanAndHandleExtensions @ workbench.desktop.main.js:3039
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///e%3A/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f746865736973227d/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:1722
A @ workbench.desktop.main.js:1724
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
createTokenizationSupport @ workbench.desktop.main.js:1898
_create @ workbench.desktop.main.js:186
resolve @ workbench.desktop.main.js:186
getOrCreate @ workbench.desktop.main.js:186
(anonymous) @ workbench.desktop.main.js:1898
_handle @ workbench.desktop.main.js:1489
acceptUsers @ workbench.desktop.main.js:1489
_handleExtensionPoint @ workbench.desktop.main.js:3036
_doHandleExtensionPoints @ workbench.desktop.main.js:3036
_startLocalExtensionHost @ workbench.desktop.main.js:3039
async function (async)
_startLocalExtensionHost @ workbench.desktop.main.js:3039
_scanAndHandleExtensions @ workbench.desktop.main.js:3039
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///e%3A/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f746865736973227d/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:1722
A @ workbench.desktop.main.js:1724
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
createTokenizationSupport @ workbench.desktop.main.js:1898
_create @ workbench.desktop.main.js:186
resolve @ workbench.desktop.main.js:186
getOrCreate @ workbench.desktop.main.js:186
(anonymous) @ workbench.desktop.main.js:1898
_handle @ workbench.desktop.main.js:1489
acceptUsers @ workbench.desktop.main.js:1489
_handleExtensionPoint @ workbench.desktop.main.js:3036
_doHandleExtensionPoints @ workbench.desktop.main.js:3036
_startLocalExtensionHost @ workbench.desktop.main.js:3039
async function (async)
_startLocalExtensionHost @ workbench.desktop.main.js:3039
_scanAndHandleExtensions @ workbench.desktop.main.js:3039
workbench.desktop.main.js:1722 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///e%3A/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f746865736973227d/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:1722
A @ workbench.desktop.main.js:1724
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
async function (async)
_getOrCreateGrammarFactory @ workbench.desktop.main.js:1898
createTokenizationSupport @ workbench.desktop.main.js:1898
_create @ workbench.desktop.main.js:186
resolve @ workbench.desktop.main.js:186
getOrCreate @ workbench.desktop.main.js:186
(anonymous) @ workbench.desktop.main.js:1898
_handle @ workbench.desktop.main.js:1489
acceptUsers @ workbench.desktop.main.js:1489
_handleExtensionPoint @ workbench.desktop.main.js:3036
_doHandleExtensionPoints @ workbench.desktop.main.js:3036
_startLocalExtensionHost @ workbench.desktop.main.js:3039
async function (async)
_startLocalExtensionHost @ workbench.desktop.main.js:3039
_scanAndHandleExtensions @ workbench.desktop.main.js:3039
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/f80445acd5a3dadef24aa209168452a3d97cc326/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
</code></pre>
</details>

<details>
<summary>Developer Tools Console Output(before build latex project)</summary>
<pre><code>
workbench.desktop.main.js:75 [Extension Host] rejected promise not handled within 1 second: ReferenceError: ReadableStream is not defined
I @ workbench.desktop.main.js:75
$logExtensionHostMessage @ workbench.desktop.main.js:1513
_doInvokeHandler @ workbench.desktop.main.js:1513
_invokeHandler @ workbench.desktop.main.js:1513
_receiveRequest @ workbench.desktop.main.js:1513
_receiveOneMessage @ workbench.desktop.main.js:1513
(anonymous) @ workbench.desktop.main.js:1513
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:584
fire @ workbench.desktop.main.js:67
E._fileReader.onload @ workbench.desktop.main.js:584
workbench.desktop.main.js:75 [Extension Host] stack trace: ReferenceError: ReadableStream is not defined	at MessageHandler.sendWithStream (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45460:5)	at new PDFWorkerStreamReader (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45833:45)	at PDFWorkerStream.getFullReader (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45797:31)	at getPdfManager (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:306:35)	at setupDoc (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:457:7)	at wphReady (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:646:7)	at LoopbackPort.MessageHandler._onComObjOnMessage (/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45410:7)	at /root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2062:18	at Array.forEach (<anonymous>)	at /root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2061:23	at processTicksAndRejections (internal/process/task_queues.js:93:5)
I @ workbench.desktop.main.js:75
$logExtensionHostMessage @ workbench.desktop.main.js:1513
_doInvokeHandler @ workbench.desktop.main.js:1513
_invokeHandler @ workbench.desktop.main.js:1513
_receiveRequest @ workbench.desktop.main.js:1513
_receiveOneMessage @ workbench.desktop.main.js:1513
(anonymous) @ workbench.desktop.main.js:1513
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:584
fire @ workbench.desktop.main.js:67
E._fileReader.onload @ workbench.desktop.main.js:584
workbench.desktop.main.js:1900 [[object Object]]ReadableStream is not defined
$onExtensionRuntimeError @ workbench.desktop.main.js:1900
_doInvokeHandler @ workbench.desktop.main.js:1513
_invokeHandler @ workbench.desktop.main.js:1513
_receiveRequest @ workbench.desktop.main.js:1513
_receiveOneMessage @ workbench.desktop.main.js:1513
(anonymous) @ workbench.desktop.main.js:1513
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:584
fire @ workbench.desktop.main.js:67
E._fileReader.onload @ workbench.desktop.main.js:584
workbench.desktop.main.js:1900 ReferenceError: ReadableStream is not defined
	at MessageHandler.sendWithStream (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45460)
	at new PDFWorkerStreamReader (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45833)
	at PDFWorkerStream.getFullReader (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45797)
	at getPdfManager (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:306)
	at setupDoc (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:457)
	at wphReady (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:646)
	at LoopbackPort.MessageHandler._onComObjOnMessage (vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.worker.js:45410)
	at vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2062
	at Array.forEach (<anonymous>)
	at vscode-file://vscode-app/root/.vscode-server/extensions/jeff-tian.tex-workshop-8.11.1/node_modules/pdfjs-dist/build/pdf.js:2061
	at processTicksAndRejections (internal/process/task_queues.js:93)
</code></pre>
</details>

### LaTeX Compiler 
<details>
<summary>LaTeX Compiler </summary>
<pre><code>
before starting: "Ready"
after starting: "Ready
</code></pre>
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/34018527/154192142-34229986-51f4-434e-af95-8e3f68d188e6.png)

## Desktop [Required]

 - OS: Windows 10
 - Docker Desktop:  4.5.0
 - VS Code version: 1.64.2
 - Extension version: 8.11.1
 - TeX distribution version: TeX 3.141592653 (TeX Live 2021) in docker image(texlive/texlive:latest, image id:93565fa16a01, the system of image: Debian GNU/Linux)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes

- Remote Containers
- Remote Extension Version: v0.217.4

### Additional context

target tex document:
\documentclass{article} 
\begin{document} 
``Hello world!'' from \LaTeX. 
\end{document}

The settings.json of vscode is empty.

**Comment by tamuratak** [comment]
> extensions/jeff-tian.tex-workshop-8.11.1/

It is different from ours. Our extension is `james-yu.latex-workshop`

**Comment by tamuratak** [comment]
Please report [jeff-tian.tex-workshop](https://marketplace.visualstudio.com/items?itemName=Jeff-Tian.tex-workshop) to Microsoft if you want.
