### ISSUE TITLE
Pipe input to latexindent

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3088]
https://github.com/James-Yu/LaTeX-Workshop/blob/b551666d779a5fe26db6b1ed574080ce31ae46b8/src/providers/latexformatter.ts#L161-L165

`latexindent.pl` has been accepting piping from stdin input since `3.4`. The current stable release is `3.15`.
@tamuratak What about using using this feature to avoid creating an intermediate file?

**Comment by tamuratak** [comment]
I am against it because version 3.4 is relatively new, released in 2020:

- https://github.com/cmhughes/latexindent.pl/releases/tag/V3.4

Especially lots of docker images might include it or older versions.

**Comment by jlelong** [comment]
Actually, the dates on github releases are not correct. All older version were generated on the same day.

Version 3.4 goes back to January 2018.

https://github.com/cmhughes/latexindent.pl/commit/47681e1f3a2d5160763e83436c6ec0b13ad1d08a

But, fine if you think this is still used.

**Comment by tamuratak** [comment]
> Version 3.4 goes back to January 2018.

Thank you.

I close this issue since the version in `tianon/latex` is very old.

> $  docker run tianon/latex latexindent -h       
> latexindent.pl version 2.2
> usage: latexindent.pl [options] [file][.tex]

**Comment by jlelong** [comment]
> I close this issue since the version included in `tianon/latex` is very old.
> 
> > $  docker run tianon/latex latexindent -h
> > latexindent.pl version 2.2
> > usage: latexindent.pl [options] [file][.tex]

How can it be! This goes back to the middle ages! Let us leave it like this for now.
