### ISSUE TITLE
Feature Request: Enable Github "Discussions"

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#3089]
I have expressed my discontent with limiting conversations to collaborators before (https://github.com/James-Yu/LaTeX-Workshop/issues/2588), and I would like to kindly repeat and extend my arguments (with solutions!). 

First, all the points in my original post are still valid. I acknowledge that
> GitHub Issues is not a user forum.

But where is, if not on GitHub? StackExchange? LaTeX.org's forum? When I, as any other user, check the [market place](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop), all external links point to this very GitHub repository:
- [Issues](https://github.com/James-Yu/LaTeX-Workshop/issues), [Repository](https://github.com/James-Yu/LaTeX-Workshop.git) - GitHub
- [Homepage](https://github.com/James-Yu/LaTeX-Workshop) - GitHub.
- "The manual of the extension is maintained as a [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki)" - on GitHub.
- Q & A? "Visit publisher's [GitHub repository](https://github.com/James-Yu/LaTeX-Workshop/issues) *for extension related questions*. - This one even links to GitHub issues specifically.

So there is no wonder users end up at GitHub Issues.

Related to this, there is three recommendations I want to make, in increasing order of how much I'd like them:

1. If you consider users something very different from developers, then you might recommend users a "forum" (other than GitHub Issues) to meet other users without offending any of the developers with their presence. (Although I doubt this truely helpful, as you want user to report new issues here, and I would say that many LaTeX users are by definition quite tech savy and could contribute useful points to other issues.) You don't have to maintain and moderate that place, just pick one and recommend it.
2. You might enable GitHub Discussions for this repository, as a place where developers (and users!) can discuss features, share workarounds, and generally continue discussions you do not prefer to have in Issues.
3. Please, *please* don't limit conversations. Why?
   - It is pretty uncommon (I am not aware of any other big repository doing it this way).
   - I see no reason to do it. 
     - For closed issues, if you are not interested in ongoing discussions, you could simply close and unsubscribe, and you will never hear from it again.
     - For open issues, you are taking the so-called community a chance to contribute. One example: I opened #3082 and my idea was met positively. A proposal was made for which feedback was requested ("Any thoughts on this?"), and upon giving my feedback, the conversation was immediately limited. I am now unable to write or edit commits to apologize for an apparent oversight, to elaborate on specific points, or even to agree with @jlelong. Other people will not be able to chip in, either.
   - I think you are missing out on a great amount of positive feedback from the community. Ever wondered why you are not even getting a "thanks" for closing an issue? There is *no* way of doing that when the conversation is limited.
   - Last but not least, it feels *very* rude for someone to be silenced this way. You have no idea how glad I usually am to be able to contribute to making software better, even if it's just by opening an issue and saying thanks for closing it. But from past experience, I must admit that LaTeX-Workshop is the *only* repository that's giving me bad feelings before even reporting an issue. I feel it should not be this way, and it certainy does not have to be this way.

Thanks for the attention, and looking forward to continuing to contribute to LaTeX-Workshop, through whatever small bits and pieces.

**Comment by tamuratak** [comment]
We have no time to maintain and moderate a user forum.

**Comment by tamuratak** [comment]
@James-Yu could you join here jlelong/LaTeX-Workshop-security/issues/5
