### ISSUE TITLE
Highlight word when using SyncTex

### ISSUE THREAD

**Issue by uxsoft** [James-Yu/LaTeX-Workshop#315]
Hi,
Would it be possible to instead of only scrolling to the general area where the text which the viewer is being navigated to was also highlighted? Other latex viewers already do this and it helps a great deal with finding the exact sentence I'm trying to inspect.

I've already had a look at the code, and while I think this should be possible, I'm having troubles getting the synctex -> pdfjs div coordinates transformation working properly. If you can point me to the right direction I can submit a pull request.

**Comment by James-Yu** [comment]
The mysterious transformation lies in line 370 to 372 of `viewer/viewer.html`. Though I have no idea how the syncTeX output can be parsed to give information on the horizontal location,

**Comment by uxsoft** [comment]
Yes, I’ve got that far :-) problem I was having is that if i feed data.data.x and data.data.y to the pdfjs viewport, it gives me a point that is quite far off. Maybe I’m missing a translation somewhere or the drawing coordinates are different somehow. Another minor thing also was that synctex is outputting small h and capital H but in viewer in the payload only small h is present. Not an issue because neither is in use but its just something i noticed :)

**Comment by quoc-ho** [comment]
Should we put this issue on pdf.js? Maybe they can help.

**Comment by James-Yu** [comment]
I suppose the problem is on synctex side: the returned result of synctex actually does not contain information about which word it is referencing. Though gaining the attention of a larger community is always a good idea.

**Comment by quoc-ho** [comment]
Paragraph level highlighting, which is what most editors do, would already be a big improvement, and this doesn't need any modification on synctex. Also, from the comments above, it seems like we don't understand what pdf.js does.

I rmb reading that for more fine-tuned pinpointing, some editors do heuristic search on the pdf side.

**Comment by James-Yu** [comment]
A preliminary version of synctex location indicator in the new version.
