### ISSUE TITLE
External PDF Viewers (Sumatra PDF, Skim, etc.)

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3160]
This is another announcement besides #3159, so I break the rule of issue template again using my "privilege".

I noticed that many previous issues are created concerning the use of external PDF viewers. Here `external` means third-party applications such as Sumatra PDF on Windows and Skim on MacOS.

Please kindly be noted that support to external PDF viewers was and will be experimental in the foreseeable future (unless new collaborators would like to maintain it, warmly welcome!). By experimental it means that no official support will be provided, and absolutely no guarantee will be made.

You may ask, why don't the core devs provide official support? PDF viewing is such an important aspect of TeX writing!

The reason is that the extension have already provided a quite full-fledged built-in PDF viewer. Forward and reverse synctex? Out-of-the-box. Menu? Out-of-the-box. `hyperref` jumping and going back? Out-of-the-box. Many more to be mentioned.

A highly suggested feature of the built-in PDF viewer, also a major reason of referring to external viewers, is that users want to **put the PDF on a secondary monitor**.

**The built-in viewer can do that. Out-of-the-box.** Take a minute to click on the TeX icon on the left/right quick action bar, select `View LaTeX PDF`, then `View in web browser`. Now we have a full-fledged PDF viewer in a browser tab that can be moved to a secondary monitor, sidecar, or anything displays.

I also acknowledge that inevitably the built-in PDF viewer may lack functionalities (which I am not aware of during my writing) that were provided by other viewers. If so, please do file a feature request suggesting the function to be incorporated in the built-in viewer.

Thank you very much for your time reading this and comprehension.

**Comment by tamuratak** [comment]
I commented out encouraging users to file a feature request.

We had better not encourage users to file a feature request on the internal PDF viewer. Almost all of them are impossible to implement on our side.
