### ISSUE TITLE
Bibexport may be added

### ISSUE THREAD

**Issue by sdomingue** [James-Yu/LaTeX-Workshop#3161]
This is not an issue, is more of a feature request (I did not answer the questions below neither I found this in a past issue).

I have recently found out about bibexport in my search for wanting to have a bibtex files organized by project (or as a single giant bib file) and generate the needed bib file for a particular paper. I really like the Latex workshop you guys have put together for VSCode. I am wondering if it'd be possible to add a feature to create a bib file for a particular manuscript from a larger bib file, just like the bibexport command does. Here is a link with an example of it:

https://tex.stackexchange.com/questions/41821/creating-bib-file-containing-only-the-cited-references-of-a-bigger-bib-file

I hope this can be done and that it does not bring to many difficulties to the developer team.

Cheers,
Sebastian

**Comment by jlelong** [comment]
I am not sure to understand what you are suggesting. Considering the feature you are describing is basically a one time action in a project, it is not clear to me what the benefits are especially if tools like `bibexport` or [`bibtool`](https://www.ctan.org/pkg/bibtool) already do the job. Could you explain what you have mind?

**Comment by James-Yu** [comment]
It looks like a one-time action per submission, instead of a frequent one during LaTeX editing or compiling. I would recommend to use the said command or refer to JabRef for the feature. Please feel free to leave a message on why this feature is a must in the extension, how frequent it will be used, etc.
