### ISSUE TITLE
Latex-Workshop is not listed as a formatter extension

### ISSUE THREAD

**Issue by alanlivio** [James-Yu/LaTeX-Workshop#3163]
## Preliminary questions [Required]

When searching `category:formatters latex` , Latex-Workshop is not listed as a formatter extension.

![image](https://user-images.githubusercontent.com/604808/155506825-d4e95f4d-9ed1-4d05-99f6-b72eefcd9770.png)

**Comment by alanlivio** [comment]
thanks @jlelong

**Comment by jlelong** [comment]
You should thank @James-Yu this time.

**Comment by alanlivio** [comment]
Thank you both @jlelong @James-Yu =)
