### ISSUE TITLE
Auto-complete when entering expression

### ISSUE THREAD

**Issue by xkzero** [James-Yu/LaTeX-Workshop#317]
### Description

always have double $$ when I want to enter a expression even at bottom and make $$ not match
### How to reproduce

1. enter x = a_1 + b_1
2. enter $x=a_1+b_1
3.enter $x=a_1+b_1$ and then it will auto complete as $x=a_1+b_1$$ which makes $ symbol not match any more

### Expected behavior

1. enter x = a_1 + b_1
2. enter $x=a_1+b_1
3.enter $x=a_1+b_1$  and do not auto complete

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Comment by innerlee** [comment]
I believe this is on vscode side, not the fault of extension.
As a workaround, you can select x = a_1 + b_1 and type $, it will enclose the selection as desired.

**Comment by James-Yu** [comment]
As @innerlee explained, this extension only uses the default vscode api to provide symbol pairing. Therefore I suppose the issue recorded is an upstream problem.
