### ISSUE TITLE
No build/view buttons and command keybindings in `LaTeX-expl3`

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3171]
### Discussed in https://github.com/James-Yu/LaTeX-Workshop/discussions/3170

<div type='discussions-op-text'>

<sup>Originally posted by **syvshc** February 28, 2022</sup>
## Preliminary questions [Required]

When I switch language to `tex` or `LaTeX-expl3`, the button of `view pdf` disappears and snippet of `synctex from cursor` doesn't work. 

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

A clear and concise description of what the bug is

When I switch the format into `TeX` or `LaTeX-expl3`, there is no button of `View LaTeX PDF File`. 

### To Reproduce

1. Open a `.tex` file
2. Compile it with `-synctex=1` option
3. switch the format between `LaTeX` and `LaTeX-expl3` and see difference. 

### Expected behavior

My expected behavior is that "view pdf" button is still there and snippet of synctex works

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

[lw.log](https://github.com/James-Yu/LaTeX-Workshop/files/8150575/lw.log)

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```
It is no business about compiling, just SyncTeX. 

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```
![image](https://user-images.githubusercontent.com/38098591/155923589-c9cfc763-308b-4e03-ae9d-8fa832af5ee3.png)

## Screenshots

I recorded a video to describe my problem, hope it is clear

https://user-images.githubusercontent.com/38098591/155933189-bde21561-8b0f-48c2-ae72-815ad2fffbdd.mp4

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Arch linux 5.16.11
 - VS Code version: 1.64.2
 - Extension version: 8.23.0
 - TeX distribution version: TeXLive 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

</div>

**Comment by jlelong** [comment]
This is caused by a too restrictive language selector

https://github.com/James-Yu/LaTeX-Workshop/blob/2bc2c15932d5932494889d561a4709e920ef7c4b/package.json#L2150-L2155

We should be using `editorLangId =~ /latex|latex-expl3|rsweave|jlweave/` almost everywhere instead.

**Comment by tamuratak** [comment]
I am against adding `latex-expl3`. `LaTeX-expl3` is a programming language. We should not encourage users to use it to write documents.

**Comment by James-Yu** [comment]
Please don't lock and close the issue so early without a thorough discussion.

**Comment by jlelong** [comment]
> I am strongly against adding `latex-expl3`. `LaTeX-expl3` is a programming language to implement LaTeX packages. We must not mislead users to use it to write documents. It would be harmful to the LaTeX ecosystem.

I do not feel at ease telling users what they should or should not do regarding the LaTeX ecosystem. I do not see why we should not make it possible for users of `LaTeX-expl3` to build their documents and use `synctex`.

**Comment by tamuratak** [comment]
I might be confused about what `LaTeX-expl3` means. If it means a programming language `expl3`, we should not make it possible for users to build their documents with the language. If it means a markup language `LaTeX` where `expl3` commands are also supported, it would be reasonable to make it possible.

For the latter case, `expl3` commands should be optional. For usual users, they don't have to write `expl3` commands.

**Comment by jlelong** [comment]
The language id `LaTeX-expl3` was designed to be used for LaTeX documents where `expl3` commands are also supported.  The name `latex3` may be more appropriate, we could rename `latex-expl3`. The main reason for defining a new language id was that we needed to extend the standard grammar to support the new `LaTeX3` syntax.

See #2071 for a discussion of what we should list as suggestions. I am tempted to leave it as it is for now and wait for some feedbacks.

**Comment by tamuratak** [comment]
> The language id LaTeX-expl3 was designed to be used for LaTeX documents where expl3 commands are also supported. 

Then, at least, we had better call `extraPackages.push('latex-document')` too even if `languageId === 'latex-expl3'`

https://github.com/James-Yu/LaTeX-Workshop/blob/75bc0d6c93819c441172e4b1a2c03f3ca02d784f/src/providers/completer/command.ts#L220-L225

**Comment by jlelong** [comment]
> Then, at least, we had better call `extraPackages.push('latex-document')` too even if `languageId === 'latex-expl3'`

Yes, I agree.
