### ISSUE TITLE
SyncTex with Skim pdf viewer?

### ISSUE THREAD

**Issue by jasonsun0310** [James-Yu/LaTeX-Workshop#318]
I would like to use Skim viewer to preview the tex document but I don't know how to configure the pdf sync command inside the Skim viewer since vscode is not in its preset config. I uploaded an screenshot to show where I am stuck.

![screen shot 2017-11-19 at 10 01 25 am](https://user-images.githubusercontent.com/22034141/32991823-a39dabba-cd10-11e7-908c-0d8c9c2ceb70.jpg)

**Comment by innerlee** [comment]
The command is path to vscode binary, and argument is to tell vscode to open which file and the line no.
Ref https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/ how to get filename and line no, and find vscode documentation for how to specify file and line via command line.

**Comment by James-Yu** [comment]
While @innerlee provided a workaround, I would like to note that this extension does not officially support 3rd-party pdf viewers. Multiple previous issues have discussed this problem.

**Comment by dsteg** [comment]
Which is a pity given how slow the international compilation/view cycle has become.

**Comment by Liam0205** [comment]
Here is the full workaround, as a tip for aftercommings.

Firstly, make a symbol link in `/usr/local/bin`, since Skim only search `/usr/bin` and `/usr/local/bin`.

```bash
ln -sf /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron /usr/local/bin/vscode
```

Secondly, in the configuration of the LaTeX workshop extension, we have the following settings.

```json
    "latex-workshop.view.pdf.external.synctex": {
        "command": "/Applications/Skim.app/Contents/SharedSupport/displayline",
        "args": [
            "-r",
            "%LINE%",
            "%PDF%",
            "%TEX%"
        ]
    },
    "latex-workshop.view.pdf.viewer": "external",
```

Finally, in Skim, we give the following settings, for reverse sync.

```
Command: vscode
Arguments: -g "%file":%line
```

**Comment by vomout** [comment]
This does not seem to update the file in Skim upon finishing compilation, or to switch to right location. That has to be manually, which means waiting and monitoring for the compilation to finish...

**Comment by Liam0205** [comment]
@vomout Skim can trace the chage of PDF file by it self.

**Comment by Liam0205** [comment]
@vomout You might need to raise a new issue. : )

**Comment by linhtto** [comment]
@Liam0205 , sorry for being slow, but where do you store your script displayfile? I suppose you have to make it executable and searchable? When you recompile, do you refresh the same instance of Skim or another instance will be opened?

Finally can you explain why we need displayline and displayfile and not /Applications/Skim.app/Contents/MacOS/skim?

Thank you!
