### ISSUE TITLE
Compile single beamer slide or allow comment toggle in structure-overview

### ISSUE THREAD

**Issue by florian-wagner** [James-Yu/LaTeX-Workshop#3185]
Thank you for the great plugin! I absolutely love it.

I regularly compile larger beamer documents (lectures), which take long. Since one is usually working on a single slide, it would be great if it would be possible to compile the current slide only via a keyboard shortcut for example. Would something like this be possible?

Alternatively, and more general (i.e., beamer independent), maybe the structure outline could allow little checkboxes to allow toggling/commenting these parts of the document?

Thank you for considering!

**Comment by James-Yu** [comment]
Thanks for the feature request. Sadly that it is unlikely to support a particular use of `beamer` from the extension side due to the extra workload and maintenance effort. However, you can still achieve the same function programmatically, with maybe the same user effort. Please refer to https://tbrink.science/blog/2017/05/13/compiling-only-some-slides-of-a-latex-beamer-presentation/ for one possible solution. Feel free to comment!

**Comment by florian-wagner** [comment]
Thank you @James-Yu! That is indeed a good workaround! (But I still think that a toggling comment button in the structure outline, i.e. for other non-beamer related structures like sections etc. could be a valuable feature to compile only parts of a document.)

---
For other users with the same problem: I ended up making the following user snippet. This allows to quickly create a frame which is the only one rendered and after finishing it, one just needs to delete (or comment) the first and uncomment the second line.

`[...]/snippets/tex.json`:
``` json
    "Beamer simple frame": {
		"prefix": "frame",
		"body": [
                        "\\includeonlyframes{current}\\begin{frame}[label=current]",
                        "%\\begin{frame}",
                        "\\frametitle{$1}",
			"\t$2",
			"\\end{frame}",
		],
		"description": "Add a simple beamer frame with a title"
	},
```

If anyone has a better solution (i.e. simply compiling the current frame by a keybinding without explicit changes to the code), I would be very interested.
