### ISSUE TITLE
Wildcards for additionalBib setting

### ISSUE THREAD

**Issue by rensa** [James-Yu/LaTeX-Workshop#319]
### Description

I'm really enjoying using LaTeX-Workshop for editing RMarkdown projects! I know that isn't the intended use, but the citation browser is fantastic, and since it can be triggered using the command palette as well (since `Rmd` files [use a `[@citation_key]` syntax](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations#citation_syntax) instead of `\cite{citation_key}`), it can really be used on any kind of file.

However, I've noticed that I have to specify each `bib` file in my projects individually. For example, in my workspace settings, using the following works:

```
"latex-workshop.latex.additionalBib": ["bib/sydney.bib", "bib/intercity.bib", "bib/mywork.bib"]
```

But putting a wildcard into this path (either in the workspace settings or user settings) doesn't (as in, I reload VSCode and try to open the citation browser, but there are no entries to cite):

```
"latex-workshop.latex.additionalBib": ["bib/*.bib"]
```

The latter would be really helpful as a "default" user setting.

**Comment by James-Yu** [comment]
I almost forget about this configuration. The requested change is quite reasonable, and will be implemented shortly.
