### ISSUE TITLE
Inline Documentation for commands 

### ISSUE THREAD

**Issue by ldorigo** [James-Yu/LaTeX-Workshop#3197]
(Removed the standard bug report template as none of it is relevant. I have read the FAQ in the Wiki.)

I don't know if LaTeX provides any mechanisms for doing something like this, but would it be doable to see documentation inline when entering latex commands? (in the intellisense tooltip - see the screenshot below for an example of what I mean).
 
![Screenshot_20220315_101757](https://user-images.githubusercontent.com/8631181/158345770-3b42cd14-454c-4959-8f42-b4a8193acce0.png)
 
This would be a major improvement over having to locate the docs for a package and then finding the relevant command within those docs.

**Comment by tamuratak** [comment]
Rejected due to the maintenance burden.

**Comment by jlelong** [comment]
Unfortunately there is no mechanism to retrieve such information in LaTeX.
