### ISSUE TITLE
RFC: Add title and author list to the citation search.

### ISSUE THREAD

**Issue by Inachos** [James-Yu/LaTeX-Workshop#32]
Hi,
I want to know all your thoughts on this:

Currently, when entering a cite-command, a list of all citationKeys in the bib-files comes up, and typing incrementally searches this. LaTeXing for sublime has a similar feature, however, there, the entries in the list are combined key+title+authors, which means you can search for any part.

I understand that that adds a lot of noise, but it facilitates finding the right citation (at least for me). Any thoughts?

**Comment by James-Yu** [comment]
Will check if it is do-able

**Comment by James-Yu** [comment]
This is implemented in the latest `1.0.0` version.
