### ISSUE TITLE
Can only insert citations in other file formats once I've tried to insert one in a .tex file

### ISSUE THREAD

**Issue by rensa** [James-Yu/LaTeX-Workshop#320]
### Description

I'm using LaTeX Workshop to insert citations in an RMarkdown project, which uses `.Rmd` files (as well as `.tex` under the hood).

I've noticed that if I dive right in and start trying to insert citations in my `.Rmd` files using the Citation Browser, I get an error: `command 'latex-workshop.citation' not found`.

But if I do the same in a `.tex` file, it works fine—and I can then go back to the `.Rmd` file and use the Citation Browser without a problem (until I restart).

### How to reproduce

1. Install and configure LaTeX Workshop (particularly by configuring `additionalBib`).
2. Open an `.Rmd` file.
3. Run `LaTeX Workshop: Open citation browser` (error appears).
4. Open a `.tex` file.
5. Run `LaTeX Workshop: Open citation browser` (reference list appears and works as expected).
6. Open an `.Rmd` file.
7. Run `LaTeX Workshop: Open citation browser` (reference list appears and works as expected).

### Expected behavior

I expect the Citation Browser to work on file types other than `.tex` as soon as I open the program.

### Actual behavior

Citation Browser throws an error until I try to open it in a `.tex` file.

### Log messages

`command 'latex-workshop.citation' not found`

(There is no output in the Output pane.)

### Additional Information

```
// user settings
"latex-workshop.latex.autoBuild.onSave.enabled": false,

// workspace settings
"latex-workshop.latex.additionalBib": ["bib/sydney.bib", "bib/intercity.bib", "bib/mywork.bib"]
```

**Comment by innerlee** [comment]
The .rmd file type is not registered as latex-type. So opening .rmd does not activate the latex extension and thus related commands are not available. The extension is activated when you open a .tex file.

**Comment by rensa** [comment]
@innerlee Is it possible to either register `.rmd` as latex-type just for the purposes of the extension, or to have the extension load for other file types? Or else to just break the citation browsing out into its own extension; it's useful for a few flavours of Markdown.

**Comment by innerlee** [comment]
Register `.rmd` as latex is semantically strange. I guess a solution might be provide a command simply to activate the extension. Let's see what the package owner think.

**Comment by rensa** [comment]
This isn't a super big problem for me; my project actually does have a `.tex` file in it (used as a template for RMarkdown), so I can duck into it to activate the extension 🙂

**Comment by James-Yu** [comment]
It was a loooong weekend but I'm back! There are a lot of variants of TeX with their own file extensions. So it's impractical to enumerate and register all of them. In the meantime, the `"activationEvents"` entry of `package.json` requires commands registered one by one, i.e., no wildcard. Let me think if it is worth.

**Comment by rensa** [comment]
[7315ab8](https://github.com/James-Yu/LaTeX-Workshop/commit/7315ab8662b9438a8639da26972d12874155cda9) doesn't appear to actually fix this issue: the extension is opened when I run the citation browser in a non-latex file type, but the browser isn't populated with references until I try to run it in a latex file type.

**Comment by James-Yu** [comment]
Can you please post a detailed extension log with annotations on important times for debug? It might be that the extension cannot find a root file.

**Comment by notZaki** [comment]
Since this issue is still open, I thought I'd mention that the citation browser does show references in an `.Rmd` file for me. 

The setup involves an `.Rmd` file containing a magic comment resembling: 
```
<!-- 
% !TEX root = relative/or/absolute/path/to/root/file.tex
-->
```
where the tex file only contains a single line stating: ` \bibliography{bibFileName}`

Alternatively, the `.Rmd` file can be associated with the tex language by inserting the following in the settings:
```
"files.associations": {
        "*.Rmd": "tex"
    }
```
This can be applied to any other file type too.  
Of course, this means giving up the markdown colorizer, but the nice thing is that intellisense works - so `\cite{}` will pop up the citations.

**Comment by jtkiley** [comment]
Along the same use case lines as this issue, it would be nice for [pandoc markdown citations](https://pandoc.org/MANUAL.html#citations), which also rely on bibtex. The [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package for Atom does this, and it would be nice to have analogous support in vscode.

**Comment by nickynicolson** [comment]
@jtkiley have you seen [pandoc citer](https://marketplace.visualstudio.com/items?itemName=notZaki.pandocciter) which looks like it should do this? (I couldn't get it configured properly, but you might fare better).

**Comment by maikol-solis** [comment]
> Alternatively, the `.Rmd` file can be associated with the tex language by inserting the following in the settings:
> 
> ```
> "files.associations": {
>         "*.Rmd": "tex"
>     }
> ```
> 
> This can be applied to any other file type too.
> Of course, this means giving up the markdown colorizer, but the nice thing is that intellisense works - so `\cite{}` will pop up the citations.

Excellent workaround!
