### ISSUE TITLE
`align` doesn't exist in suggestions

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3203]
The `align` environment doesn't exist in suggestions at the current master.

```latex
\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{bm}

\begin{document}
a
\end{document}
```

![2022-03-17 7 47 55](https://user-images.githubusercontent.com/10665499/158704174-6a1ea6d3-2230-4ae3-a577-3b5615b73386.png)

**Comment by tamuratak** [comment]
I must keep saying the same thing. Please consider adding tests. Notice that we can add unit tests in the same way as CI tests. What I am saying is that:

1. If adding unit tests is difficult, do refactoring to make it easier.
2. Add unit tests to ensure that suggestions include intended items.

**Comment by jlelong** [comment]
Then, I must keep saying that I do believe in tests but unfortunately I cannot devote more time that I already do. If you implement a unit test framework, I will be more than happy to contribute.

Btw, concerning the format of `json` files, I am wondering why we catch errors in https://github.com/James-Yu/LaTeX-Workshop/blob/d08775a743de260c0d73865487ad62b13a5feb43/src/providers/completion.ts#L49-L53

If loading the default elements fails, it means there is a problem in the `json` files.

**Comment by tamuratak** [comment]
> If you implement a unit test framework, I will be more than happy to contribute.

We already have it. We can use `./test` for unit tests. One of the ways is:

1. Open an empty directory as a fixture.
2. Do unit tests.

> If loading the default elements fails, it means there is a problem in the json files.

The lines already existed before I edited. See:

https://github.com/James-Yu/LaTeX-Workshop/blob/2da3d22b35f909a2bd5d0f6f8c74a383d34f732f/src/providers/completion.ts#L29-L30

**Comment by jlelong** [comment]
> The lines already existed before I edited

I know. I am just saying that they may be more harmful than helpful.

Well, it is not yet completely clear to me how to proceed with unit tests.

**Comment by tamuratak** [comment]
See https://github.com/tamuratak/LaTeX-Workshop/tree/84633a932274fc06976f920a6064c4efe77de39a

Run 

```
$ npm run test unittest
```

**Comment by jlelong** [comment]
Thanks for the explanations. This is actually what I did for multi-root workspace tests.

I understood unit tests as tests that could run without a VS Code instance (see https://code.visualstudio.com/api/working-with-extensions/testing-extension). This is why I did not understand what you meant. Now, this is clear.
