### ISSUE TITLE
Support Document symbol for BibTeX file

### ISSUE THREAD

**Issue by jooyoungseo** [James-Yu/LaTeX-Workshop#3215]
I was wondering if you could consider supporting Document Symbol (Ctrl+Shift+.) feature for BibTex files. Having structural information would be greatly appreciated.

**Comment by jlelong** [comment]
What would you expect as symbols in a bibtex file?

**Comment by jooyoungseo** [comment]
What about displaying each unique citation key as an expandable root level and "author," "title," etc. as sub-key symbols?

**Comment by James-Yu** [comment]
Can you please explain more on the use case of this structure? Considering the large volume of entries in a bib file and the high readability of bib files, I myself cannot think of a good use for the extra structure view.

**Comment by jooyoungseo** [comment]
First, the structure view that Document symbol provides is very accessible to screen reader users just like me who is blind because it gives users expandable and collapsible hierarchy treeview as an overview of the current file. Without this feature, screen reader users have to read the whole file structure by using line-by-line navigation, which is cognitively overloading.

Second, within Document Symbol pane, heavy keyboard users like screen reader users can quickly jump to the next symbol by typing the first letter. for example, if there are kim2022 and kim 2019 articles and their bib entry keys are represented as symbols, keyboard users can quickly skip over to kim article by typing "k" or "kim" in the Document Symbol view.

**Comment by James-Yu** [comment]
Thank you @jooyoungseo for the reply, and we should have think more for screen reader users. I will look into this.
