### ISSUE TITLE
Code folding not working in .cls and .sty files

### ISSUE THREAD

**Issue by johanzietsman-em** [James-Yu/LaTeX-Workshop#3218]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Code folding with %\begingroup %\endgroup and % region % endregion works in .tex files, but not in .cls and .sty files.

### To Reproduce

1. Open a .cls or .sty file.
2. Create code folding regions with %\begingroup %\endgroup and % region % endregion.
3. Test whether code folding works.

### Expected behavior

When adding code folding regions with %\begingroup %\endgroup and % region % endregion, the demarkated regions should fold in the VS Code editor.

## Logs [Required]

Not relevant.

### LaTeX Workshop Output [Required]

Not relevant.

### Developer Tools Console [Required]

Not relevant.

## Screenshots

Not relevant.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Kubuntu 20.04
 - VS Code version: 1.65.2
 - Extension version: 8.23.0
 - TeX distribution version: TeX Live 2019 revision 53568

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Not relevant.

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar and language definition to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#21
