### ISSUE TITLE
Add a dark theme to the pdf viewer

### ISSUE THREAD

**Issue by ismasou** [James-Yu/LaTeX-Workshop#322]
### Description

I just decided to start using VS code for my TeX and I'm in love with this plugin, the only reason I'm actually switching is because of the dark theme of VS code, and I was wondering if you could implement a dark theme for the viewer too.

### How to reproduce

The easiest way would be to just switch dark text into white and the white background black. The other colors should stay the same.

**Comment by James-Yu** [comment]
I'm afraid that this won't be implemented. The proposed plan may only work well with b/w documents, but it may cause great problems for color ones.

**Comment by henrikdahlberg** [comment]
What exactly is the issue? Colored documents will have their colors inverted as well, that's the entire point. I usually inverted everything on my screen, webpages for instance, and there are smart inverters that don't invert images. Color inversion is a feature that essentially every PDF viewer has implemented and it's annoying to have to use an external one when working with LaTeX Workshop.

**Comment by James-Yu** [comment]
While I am still finding what you said is a must for PDF viewer in my installation of Adobe Acrobat Reader DC, I'd unfortunately say this feature is currently not on the list to implement.

**Comment by bvibhav** [comment]
I usually use Adobe reader on Linux tiled side by side with VS Code. Ctrl+I and you have inverted colors.

**Comment by tamuratak** [comment]
Related to mozilla/pdf.js/issues/2071.

**Comment by fuzihaofzh** [comment]
I also hope this feature could be considered. I just wonder whether using the gray scale mode could simplify the development? Many pdf viewers (e.g. pdf expert) provide many background colors mode. In these modes, the document is converted into grayscale and then render the user-defined colors. I think this could make things simpler?

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfinvert
