### ISSUE TITLE
Go to symbol leads to the wrong line

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3221]
Go to symbol reveals the wrong line because we consider that line 0 is the one containing `\begin{document}` instead of the first line of the document

https://github.com/James-Yu/LaTeX-Workshop/blob/0d558c7bcdaa7e615674cc733d2c573e5e5b4e2e/src/providers/structure.ts#L88-L92

Introduced in 0d558c7.

**Comment by James-Yu** [comment]
I also noticed this issue. One more question, is it technically possible to refactor the whole logic using `latex-utensils`? If yes, I'm happy to look into it.

**Comment by jlelong** [comment]
This was actually on my TODO list to investigate how to refactor the whole structure logic using `latex-utensils`. This is not easy as there are a lot of tweaks in the current regex based parser but I am pretty confident that they can be transposed. 

That is great if you can look into it! I will try yo help if need be. Maybe we should start by writing tests for all the existing tweaks.

**Comment by jlelong** [comment]
This issue was introduced by https://github.com/James-Yu/LaTeX-Workshop/commit/0d558c7bcdaa7e615674cc733d2c573e5e5b4e2e (blame me), which was not part of release `8.23.0` but is in `8.24.0`.

I am almost fixed it

- The go to line works perfectly in the _Outline_ view of _Explorer_ pane
- There is still a one line offset in the _Structure_ view of the _TeX_ pane because of https://github.com/James-Yu/LaTeX-Workshop/blob/3790d6890e43f8bacdb0dd779985ce586ac888c5/src/providers/structure.ts#L528-L530 I am afraid we cannot do much about it for now because `buildBibTeXModel` relies on `latex-utensils` which counts lines from `1`, whereas `buildLaTeXModel` counts lines from `0`. This will be completely fixed once the structure provider is refactored

@James-Yu Yet, it might be worth making a new release with this (almost) fixed to avoid false issues. I let decide how to proceed.
