### ISSUE TITLE
Refactor latex structure provider to use `latex-utensils`

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3224]
Use `latex-utensils` to compute the structure of latex files. Refactor https://github.com/James-Yu/LaTeX-Workshop/blob/f6825fd8cb0a200177911799fb5fe435e1c60b2d/src/providers/structure.ts#L108

**Comment by James-Yu** [comment]
I have a great grand plan: completely refactor the (dirty/saved) file content caching system and refactor bib and tex structure. Let me look into this after caching 😄

**Comment by tamuratak** [comment]
I think it is not necessary to cache the content: 

https://github.com/James-Yu/LaTeX-Workshop/blob/5e1a4a32d32b21abb8ce194e09a7cc288e8ade52/src/components/manager.ts#L32-L36

You had better investigate the necessity with some benchmarks.

**Comment by jlelong** [comment]
For files opened in vscode (`workspace.textDocuments` list all documents known by vscode), we could rely on the associated `vscode.TextDocument`, which is already a cached content, see  
- https://github.com/Microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostDocumentData.ts 
- https://github.com/Microsoft/vscode/blob/main/src/vs/editor/common/model/mirrorTextModel.ts

**Comment by tamuratak** [comment]
I have changed my opinion.

We had better store the original content corresponding to the abstract syntax trees.

**Comment by James-Yu** [comment]
As per attempts in #3225, it seems that the parsing is slow for a real-time latex structure provider. Switching to AST-based structure may introduce performance degradation. Therefore I suggest to close this issue for now and keep an eye on other possible ways to improve the structure provider.

**Comment by jlelong** [comment]
It turned out that the structure was recomputed far too often. This has been fixed in #3252 by introducing caching.
Now, the LaTeX structure is only recomputed when a `.tex` file included in the LaTeX project is saved or the root file changes.

It may worth investigating if we could use the same AST tree as for updating the completer.
