### ISSUE TITLE
Support  \cite<text>{keylist} commands from apacite

### ISSUE THREAD

**Issue by eqol-fomi** [James-Yu/LaTeX-Workshop#3226]
## Description
I often use command \cite<e.g.>{},
but syntax highlighting of this command is not the same as the one of \cite{}.
![image](https://user-images.githubusercontent.com/102793631/161380010-f5e1b552-acde-4f92-820c-fda9f07b918b.png)
![image](https://user-images.githubusercontent.com/102793631/161380025-ec37ab26-fccf-4f8b-9f94-51c0eec5757e.png)
And no autocompletion for this command. 
I tried editing settings:
```
"latex-workshop.intellisense.commandsJSON.replace":{"cite[text]{keylist}": "cite[${2:text}]{${1:keylist}}","cite<text>{keylist}": "cite<${2:text}>{${1:keylist}}"}
```
But it doesn't seem to work……

**Comment by jlelong** [comment]
I have never come across that form of the `\cite` command. Could you tell us by which package it is provided?

The setting `latex-workshop.intellisense.commandsJSON.replace` is used to replace already defined commands, not to define new ones; `cite<text>{keylist}` is a new command. You could for instance use

```json
"latex-workshop.intellisense.commandsJSON.replace":{"cite[text]{keylist}": "cite<${2:text}>{${1:keylist}}"}
```
to have the suggestion `\cite[text]{keylist}` to actually write `\cite<${2:text}>{${1:keylist}}`.

**Comment by eqol-fomi** [comment]
`apacite` package provides `\cite<pre-note>[post-note]{citekey}`
I found this usage on [https://tex.stackexchange.com/questions/408564/how-to-write-e-g-surname-2018-with-apacite](url).
I tried ``` "latex-workshop.intellisense.commandsJSON.replace":{"cite[text]{keylist}": "cite<${2:text}>{${1:keylist}}"} ```,
but it still doesn't work.

**Comment by jlelong** [comment]
Commands using `<...>` to delimit their arguments are non standard and hence are not recognized by the extension. This is why the highlighting is wrong and why you will not get citation completion after the brace inside `\cite<e.g.>{`. I will investigate if this reasonable to support  such commands. Meanwhile, there are a couple of alternative solutions

1. Use `\citep[postfix][prefix]{keylist}` from the `natbib` package as `\citep[e,g][]{key}` 
2. If you want to keep using `apacite`, define
    ```tex
    \newcommand{\citep}[2][]{\cite<e.g>[#1]{#2}}
    ```
    You can use `\citep{key}` or `\citep[post-note]{key}`. The command name must match the following regexp

    ```
    /(\\)(?:[aA]uto|foot|full|no|short|[tT]ext|[pP]aren|[sS]mart)?[cC]ite(?:al)?(?:p|s|t|author|year(?:par)?|title)?[ANP]*\*?/
   ```


The setting `latex-workshop.intellisense.commandsJSON.replace` is only used by command intellisense. With 

```
"latex-workshop.intellisense.commandsJSON.replace":{"cite[]{}": "cite<${2:text}>{${1:keylist}}"}
```
![Apr-02-2022 17-02-13](https://user-images.githubusercontent.com/2910140/161389282-c11664cc-44db-484a-9b75-8d5ad04fe77f.gif)

**Comment by jlelong** [comment]
The `apacite` package has not been updated since 2013. I doubt it is still maintained and therefore, I do not think supporting it is really needed.

**Comment by eqol-fomi** [comment]
Thank you for the solutions.
I use the `apacite` package because the newest template of AGU (American Geophysical Union) still uses the `apacite` package.

Overleaf still supports this command as well.
![image](https://user-images.githubusercontent.com/102793631/161411662-4739e184-43cd-4c5f-8ff5-2e1c222301a9.png)
![image](https://user-images.githubusercontent.com/102793631/161411669-650a780c-81fe-478f-bada-4f5b0b5f07a2.png)

**Comment by jlelong** [comment]
I plan to support `\cite` commands from `apacite`

- [ ] syntax highlighting for these commands will be added to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics)
- [ ] provide citation intellisense inside these cite commands
- [ ] write a `apacite_cmd.json` file to list the commands provided by `apacite`
