### ISSUE TITLE
If the commands contained in `commands.json` are suppressed, `cleveref`'s commands loaded by `\usepackage` will not be displayed.

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#3227]
# Bug report

This issue is IntelliSense bug.

## To reproduce

1. I didn't like `\cref` and `\cpageref` being suggested even if I didn't use `cleveref`, so I set it as follows.

    ```json
      "latex-workshop.intellisense.commandsJSON.replace": {
        "cref{}": "",
        "cpageref{}": ""
      },
    ```

      

      

2. If the extension does not load `cleveref`, suggestions will not be displayed. This is normal behavior.

    ```latex
    \documentclass{article}
    \begin{document}
    % \cref

    % \cpageref

    \end{document}
    ```

      ![cref-intellisense1](https://user-images.githubusercontent.com/75878492/161393562-d5d2b60b-cf0f-4ff8-8b32-daaefad721a3.gif)

3. Even if the extension loads `cleveref`, `\cref` and `\cpageref` suggestions will not be displayed.

    ```latex
    \documentclass{article}
    \usepackage{cleveref}
    \begin{document}
    % \cref

    % \cpageref

    \end{document}
    ```

      ![cref-intellisense2](https://user-images.githubusercontent.com/75878492/161393566-e17bda3e-3bd6-4bc8-8429-26ba800633a3.gif)

4. Also, if you do the following, it will be displayed in the suggestion, but you cannot decide.

    ```latex
    \documentclass{article}
    \begin{document}
    % \cref
    \cref
    % \cpageref
    \cpageref


    \end{document}
    ```

    ![cref-intellisense3](https://user-images.githubusercontent.com/75878492/161394078-825a37ea-0a8f-4d61-990f-39d7ca16e63a.gif)

## Version

- LaTeX Workshop: 8.24.1
- VS Code

    ```
     Version: 1.66.0 (user setup)
      Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
        Date: 2022-03-30T05:50:14.623Z
    Electron: 17.2.0
    Chromium: 98.0.4758.109
     Node.js: 16.13.0
          V8: 9.8.177.11-electron.0
          OS: Windows_NT x64 10.0.19043
    ```

This problem was also reproduced in VS Code 1.65.2.

**Comment by jlelong** [comment]
3. I find the behaviour quite normal; your use case is a bit surprising. Yet,  I will investigate if we can do something about. Currently, we remove from the commands provided by packages all the default commands (all the commands defined in `data/commands.json`). The question is to know if it would make sense to do this at runtime, which would solve your use case.
4. This is normal. Every command used in the file is registered for later suggestions.

**Comment by Yarakashi-Kikohshi** [comment]
I mainly use LuaLaTeX, but `\cref` is not available by default. You can only use `\cref` by loading `\usepackage{cleveref}`.

Currently, the commands provided by `commands.json` are described as "[a set of standard LaTeX commands](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#commands-starting-with-)". I understand that this means defining commands that can be used without the use of packages.

In other words, it seems be strange that `\cref` and `\cpageref` are suggested when `cleveref` is not used. Also, when `cleveref` is used, `\cref` and `\cpageref` should be suggested. (I don't believe this is my use case...)

More to the point, I think you should remove `\cref` and `\cpageref` from `commands.json`.

#### 3.

> Currently, we remove from the commands provided by packages all the default commands (all the commands defined in `data/commands.json`).

Sorry, I don't understand this part of the story...

#### 4.

> This is normal. Every command used in the file is registered for later suggestions.

Check carefully. I am trying to select a suggestion but cannot decide. This is not normal behavior.

**Comment by jlelong** [comment]
I cannot reproduce the behaviour of 4.
