### ISSUE TITLE
Clicking on problem does not open file in multi-file document

### ISSUE THREAD

**Issue by dsteg** [James-Yu/LaTeX-Workshop#323]
Clicking on a an entry in the problems pane does not open the relevant file. It throws an error message:
Unable to open 'HeterogeneityModels.tex ': File not found (file:///Users/xxx/xxx/HeterogeneityModels.tex )".  However, the file does exist at that location.

While I was unable to reproduce it in a minimal working example, it seems to be caused by an extra whitespace after the filename, i.e., it looks for a file name.tex_ not name.tex.

### Log messages

No relevant entry in LatexWorkshop log

**Comment by James-Yu** [comment]
Seems caused by irregular log format. The commit should fix this issue.
