### ISSUE TITLE
`latex-workshop.bibtex-format.sort.enabled` not effective in `settings.json` in multi-root workspace

### ISSUE THREAD

**Issue by bersbersbers** [James-Yu/LaTeX-Workshop#3239]
## Describe the bug [Required]

`latex-workshop.bibtex-format.sort.enabled` setting is not effective when set in a folder `settings.json` in multi-root workspace.

Related: #3219 (and before that, #3082)

I believe the reason is that the following two calls of `vscode.workspace.getConfiguration` are missing a scope argument, compare https://github.com/James-Yu/LaTeX-Workshop/issues/3082#issuecomment-1040001501:

https://github.com/James-Yu/LaTeX-Workshop/blob/ca3fe284ad5fa9f2c308bd4d469b94302e9e2a33/src/providers/bibtexformatter.ts#L165

https://github.com/James-Yu/LaTeX-Workshop/blob/ca3fe284ad5fa9f2c308bd4d469b94302e9e2a33/src/providers/bibtexformatter.ts#L171

(And it would probably make sense to add it here as well, but not 100% sure:)

https://github.com/James-Yu/LaTeX-Workshop/blob/ca3fe284ad5fa9f2c308bd4d469b94302e9e2a33/src/providers/bibtexformatter.ts#L58

### To Reproduce

```
D:\Bug>tree /f
D:.
│   bug.bib
│   bug.code-workspace
│
└───.vscode
        settings.json


D:\Bug>more bug.code-workspace
{
    "folders": [
        {
            "path": "."
        }
    ],
}

D:\Bug>more bug.bib
@article{B,
  author = B
}
@article{A,
  author = A
}

D:\Bug>more .vscode\settings.json
{
    "latex-workshop.bibtex-format.sort.enabled": true, // not working
    "latex-workshop.bibtex-format.trailingComma": true, // working fine
}

D:\Bug>code bug.code-workspace
```

1. Set up the files above
2. Open the workspace
3. Open the `.bib` file
4. Save it
5. Note that trailing comma is added, but entries are not sorted.

### Expected behavior

File is sorted.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.66.0
 - Extension version: 8.24.1 <s>8.11.1</s>

**Comment by jlelong** [comment]
You are using a very old version of the extension. Please update to `8.16.1`.

**Comment by bersbersbers** [comment]
Excuse the incorrect version number - I usually work remotely and created a local repository for reproduction, and the local installation of  the extension was out of date. The problem reproduces as reported in v8.24.1.

**Comment by bersbersbers** [comment]
@jlelong would you mind reopening this issue? I have fixed the original post.
