### ISSUE TITLE
Provide root file location with a command

### ISSUE THREAD

**Issue by FelixBenning** [James-Yu/LaTeX-Workshop#3240]
## Is your requested feature  related to a problem? Please describe.

I am using [latexml](https://math.nist.gov/~BMiller/LaTeXML/) to also compile my `.tex` files to html. For this I wrote a task. But at the moment it only works if I have the root file selected. It would be really nice if it would also work for child files. Since LaTeX workshop also works when child files are updated, there is a root file detection mechanism. I would like to be able to piggyback on that detection mechanism if possible.

## Describe the solution you'd like

It is possible to use [command variables](https://code.visualstudio.com/docs/editor/variables-reference#_command-variables) in the task. If I could use something like `${command:latex-workshop.latex.get-root}` in my task for example, that would be nice. I also see that you have [Placeholders](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#placeholders) already. But I think those only work in recipes passed to LaTeX workshop. That being said, I will probably rewrite my task as a recipe to work around this issue for now.

**Comment by tamuratak** [comment]
Rejected due to the maintenance burden.

**Comment by James-Yu** [comment]
@tamuratak may I recommend to not lock and limit issues as long as the post is not replied too heated? Close an issue might already be sufficient. It is perfectly ok to not respond to closed issue for maintainers.
---
@FelixBenning I'm not sure if using `task` for your particular need is better than the `recipe` system. Can you please provide additional information on this? I will look into it when I finished the current PR.

**Comment by FelixBenning** [comment]
> @FelixBenning I'm not sure if using `task` for your particular need is better than the `recipe` system. Can you please provide additional information on this? I will look into it when I finished the current PR.

Honestly, I just tried to create a task because that is what you do when you want to automate something in vscode. Later I realized that it was kind of annoying that I could not create the html from a subfile, so I looked into how I might go about replacing the `${file}` with a pointer to the root. I realized that I would probably have to use the latex workshop so I tried to find a command which provided me with the root file. I did not find one so I started with the PR. When I explained what I wanted I referenced the placeholders for illustration and realized in that moment that I could probably just write a recipe.

So I guess the benefit is discoverability for people used to the vscode way of doing things. That being said: Why does latex workshop have a recipe system when vscode already has tasks? There even seems to be a watch system to run them on save:
https://github.com/Microsoft/vscode/issues/2159

**Comment by FelixBenning** [comment]
I guess there was already an issue for that: https://github.com/James-Yu/LaTeX-Workshop/issues/2513. So this the advantage of integration I guess. Discoverability.

@James-Yu (since this issue is closed and I should probably have referenced you in the first place).
