### ISSUE TITLE
vs code outline don't work after update in April

### ISSUE THREAD

**Issue by sentry-cy** [James-Yu/LaTeX-Workshop#3244]
## Preliminary questions [Required]

It's quite strange since only happened in most recent update of vs code(should be one version in April), latex file outline can't show section or chapter or other symbol.
![image](https://user-images.githubusercontent.com/12124312/162610046-1d7879f3-354e-453a-9015-9ba576693ac2.png)
other extension can show outline
![image](https://user-images.githubusercontent.com/12124312/162610408-5aeb746b-d167-4b1f-b8e8-c182be87855c.png)

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

**Comment by tamuratak** [comment]
Deplicate of #3236
