### ISSUE TITLE
snippets not working when the file extension is `.jnw`.

### ISSUE THREAD

**Issue by likanzhan** [James-Yu/LaTeX-Workshop#3249]
Suppose I have a simple document with the following content (The files are attached as a zip file):
```
\documentclass{article}
\begin{document}

\end{document}
```

If the extension of the file is `.tex`, and I insert `SS`, I get the following:

<img width="693" alt="tex" src="https://user-images.githubusercontent.com/10531698/163083021-4de9c3b9-550a-409e-98c6-a5388bfac515.png">

But if I change the extension of the same file into `.jnw`, I get the following:

<img width="276" alt="jnw" src="https://user-images.githubusercontent.com/10531698/163082977-1f2a3e71-8617-4a23-842a-bd8ad362d6c9.png">

Please note the snippets not showing in the latter case.

Thanks.

The original documents:
[Archive.zip](https://github.com/James-Yu/LaTeX-Workshop/files/8477615/Archive.zip)

**Comment by jlelong** [comment]
Please give an example to reproduce the issue. Explain exactly what you are calling snippets, there are many completion mechanisms in LW.

**Comment by jlelong** [comment]
I cannot reproduce the issue. What version of LW are you using? 
Check your setting `editor.snippetSuggestions` for the `LaTeX` and `Weave.jl` languages.

**Comment by likanzhan** [comment]
It seems to be caused by another package installed in my VScode, i.e., `language-weave`. The problems disappears after I uninstalled the package. Thanks.
