### ISSUE TITLE
Double-click jump to a problem doesn't work

### ISSUE THREAD

**Issue by Weasy666** [James-Yu/LaTeX-Workshop#325]
### Description

If there are problems after compiling a PDF and i double-click the problem it doesn't jump to the specific
location, but shows an error. Seem to be the same problem with the char `#` in the path, like in #297, #299.

### How to reproduce

Create a Latex project with a `#` in the path, compile it once so that there are some problems that ChkTeX identifies and try to jump to the location by double-clicking the problem.

### Expected behavior

Should jump to the line of the problem.

### Actual behavior

Doesn't jump and shows an error.
![image](https://user-images.githubusercontent.com/11967542/33174521-b281e8e4-d058-11e7-8463-7bacf910d3ee.png)

**Comment by James-Yu** [comment]
Fix and I strongly suggest against the usage of special characters in file paths/names.
