### ISSUE TITLE
Patterns where `smartSelect` does not work well

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#3257]
Disabling other extensions will still cause this problem.

[`latex-workshop.selection.smart.latex.enabled`][wiki smartSelect] is true.

[wiki smartSelect]: https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#latex-workshopselectionsmartlatexenabled

## Patterns that do not work well

- An environment containing `[]` after `\begin{...}`, such as table environment
- An environment containing `{}` after `\begin{...}`, such as tabular environment
- The lstlisting environment provided by [listings](https://www.ctan.org/pkg/listings)

### Demonstrations

I tested `smartSelect` with the following file.

```latex
\documentclass{article}
\usepackage{listings}
\begin{document}

\begin{table}[tbh]
  \centering
  \caption{Demonstration}\label{tbl:demo}
  \begin{tabular}{lrc}
    column 1   & column 2   & column 3  \\
    content 1  & content 2  & content 3
  \end{tabular}
\end{table}

\begin{lstlisting}[caption={Output ``Hello world!''}, label=cHelloWorld]
  #include<stdio.h>
  int main(){
      printf("Hello world!");
  }
\end{lstlisting}

\begin{lstlisting}
  #include<stdio.h>
  int main(){
      printf("Hello world!");
  }
\end{lstlisting}

\end{document}
```

### An environment containing `[]` or `{}` after `\begin{...}`

There are no steps where `[tbh]` or `{lrc}` is not included in the selection.

1. Press `Shift+Alt+Right` 8 times repeatedly
2. Press `Shift+Alt+Left` 8 times repeatedly

![smartSelect1](https://user-images.githubusercontent.com/75878492/163838259-5d99d247-9f5f-44e7-b928-42f90a1ec764.gif)

***What is required:*** Add step to select without `[]` or `{}` in environments where `\begin{...}` is followed by `[]` or `{}`.

### The lstlisting environment

It seems that `smartSelect` is not working well with lstlistings. It seems that it doesn't matter if there is `[]` or not.

1. Press `Shift+Alt+Right` 1 time
2. Press `Shift+Alt+Left` 1 time

![smartSelect2](https://user-images.githubusercontent.com/75878492/163838264-5d50d8be-cef1-4b4f-b9f8-67a7deda3766.gif)

***What is required:*** Add step to select only the source code in the environment.

I don't know if there are other patterns like this.

## Version

- LaTeX Workshop: 8.25.0
- VS Code:

    ```
     Version: 1.66.1 (user setup)
      Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
        Date: 2022-04-06T14:50:12.141Z
    Electron: 17.2.0
    Chromium: 98.0.4758.109
     Node.js: 16.13.0
          V8: 9.8.177.11-electron.0
          OS: Windows_NT x64 10.0.19043
    ```

**Comment by tamuratak** [comment]
We will not add tweaks due to the maintenance burden.
