### ISSUE TITLE
Sidebar icon should be thicker

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [James-Yu/LaTeX-Workshop#3259]
As seen in the following image, the sidebar icon is much thinner compared to the other icons (with default icons):

![image](https://user-images.githubusercontent.com/49895442/164369997-8f685c25-e27b-4557-96f6-67c846e222c6.png)

It would be more visually pleasing if the icon was updated to have the same weight as the others.

**Comment by tamuratak** [comment]
Rejected due to the maintenance burden.

**Comment by James-Yu** [comment]
> Rejected due to the maintenance burden.

Why maintenance burden if this is a one-time fix?

**Comment by James-Yu** [comment]
I'm afraid this is the only thing we can do from the extension side @SubjunctiveQuaver . It looks good on me tho. In fact I'm not sure why the icons in your screenshot are so thick.

![image](https://user-images.githubusercontent.com/4210342/164396542-53868cda-61aa-4c34-b750-9a7169f2a775.png)
