### ISSUE TITLE
Remove a configuration on `markdown.latex.codeblock`

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3263]
@jlelong  We had better remove the following:

https://github.com/James-Yu/LaTeX-Workshop/blob/df3b06dccbd3aec4265102fc1584e91e01091444/package.json#L219-L229

Related to jlelong/vscode-latex-basics/issues/1 and microsoft/vscode-markdown-tm-grammar/pull/99

**Comment by jlelong** [comment]
You are right. I will do

**Comment by tamuratak** [comment]
It would be better to upgrade the engine to the one where the markdown-tm-grammar change merged:

https://github.com/James-Yu/LaTeX-Workshop/blob/df3b06dccbd3aec4265102fc1584e91e01091444/package.json#L14-L16

https://github.com/James-Yu/LaTeX-Workshop/blob/df3b06dccbd3aec4265102fc1584e91e01091444/package.json#L2439

**Comment by jlelong** [comment]
LaTeX code blocks were added to vscode by https://github.com/microsoft/vscode/commit/d07ee608294 and were first released in `1.64.0`.
