### ISSUE TITLE
PR #3255 breaks indentation for lines without "\item"

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3278]
PR #3255 seems to change the indentation behavior for lines without "\item" in an unintended way:
``` latex
% with these changes:

    Some line. %<-press enter here
%<- cursor ends up here


% without these changes:

    Some line. %<-press enter here
    %<- cursor ends up here
```

_Originally posted by @ManuelHentschel in https://github.com/James-Yu/LaTeX-Workshop/issues/3255#issuecomment-1115119401_

**Comment by jlelong** [comment]
It seems to be a limitation of vscode's api. The only way to insert a newline and indent it is to call `vscode.commands.executeCommand('type', { source: 'keyboard', text: '\n' })`, which unconditionally applies to all cursors. 

I think the best approach is to simply deactivate the `onEnterKey` key feature when there are several cursors. This is actually what they ended up doing in the _Markdown All in One_ extension, see https://github.com/yzhang-gh/vscode-markdown/issues/829.

**Comment by tamuratak** [comment]
You can try using `On Enter Rules` in the language configuration. With the configuration, we could not implement the exactly same behavior. However, it might reduce the maintenance burden.

- https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules

**Comment by jlelong** [comment]
Thanks for the reference but I do not think `On Enter Rules` could honor the configuration variable `latex-workshop.bind.enter.key`. The rules are always activated or never.

Giving a second thought to all this, here is the approach I suggest when `latex-workshop.bind.enter.key` is true
- If for all the cursors the active lines match `^\s*\\item`, apply the current onEnterKey command
- If not, simply call `vscode.commands.executeCommand('type', { source: 'keyboard', text: '\n' })` which adds an indented newline at every cursor.

I think this the best I can do to support multi-cursors
