### ISSUE TITLE
More building steps control

### ISSUE THREAD

**Issue by lincolnBe** [James-Yu/LaTeX-Workshop#328]
I am using it to writing thesis.  As bib needed, the file needs to be compiled at least twice to make everything perfect. 

But since I am just drafting and only want to check big placehold are right, it is possible to provide a command to only run the first step without going through everything? 

Now in order to run only first step, I have to change latex workshop setting, which is not convenient.

Best,
Linkun

**Comment by James-Yu** [comment]
`latexmk` was developed to solve this problem.
