### ISSUE TITLE
Rewrite dev/manager-logic.odg with Mermaid.js

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3287]
@jlelong, we can rewrite the diagram in `dev/manager-logic.odg` with Mermaid.js. See 

- https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

You can render diagrams on VS Code with the extension https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid

- https://github.com/James-Yu/LaTeX-Workshop/tree/master/src#architecture
- https://github.com/James-Yu/LaTeX-Workshop/tree/master/viewer#sequence-diagrams

**Comment by jlelong** [comment]
This is super cool. I will look at it as soon as I finish the tests related #3283.
