### ISSUE TITLE
SyncTeX not opening

### ISSUE THREAD

**Issue by j-marcon** [James-Yu/LaTeX-Workshop#329]
### Description

I get the error message `PDF is not viewed` when trying to open my PDF document with SyncTeX. My workflow used to work a couple of months ago. I'm back to using LaTeX Workshop and I'm unable to open my PDF document with SyncTex by clicking `SyncTeX from cursor`.

SyncTeX is still installed and `-synctex=1` is called with `latexmk`.

### How to reproduce

I'm honestly not sure. I must have something wrong with my configuration but can't figure out what exactly.

### Expected behavior

I would expect SyncTeX to open in the side panel with the produced PDF.

### Actual behavior

Nothing happens.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
Executing synctex with args view,-i,20:367:c:\path\to\proposal.tex,-o,c:\path\to\proposal.pdf
PDF is not viewed: c:\path\to\proposal.pdf
</details>

**Comment by James-Yu** [comment]
You can try rebuild the project and check if it works.

**Comment by j-marcon** [comment]
> You can try rebuild the project and check if it works.

I have tried that. I have also tried to uninstall and re-install LaTeX-Workshop, just in case. That didn't work either.

**Comment by James-Yu** [comment]
Please post full extension log for debug.
