### ISSUE TITLE
`\boldsymbol` cannot be preview after VS Code updated into v1.67

### ISSUE THREAD

**Issue by xiaodl813** [James-Yu/LaTeX-Workshop#3293]
## Describe the bug [Required]

I updated my VS Code version into 1.67 and I found that the `\boldsymbol` cannot be previewed.

I have read Wiki and closed issue and unfortunately, I didn't find any solution of it. It seems like a new bug.

The figure of this bug is shown below: 👇

![image](https://user-images.githubusercontent.com/50045896/168842353-e735f5e6-83d2-4736-9d17-b0ba9efc3d7f.png)

![image](https://user-images.githubusercontent.com/50045896/168842416-1a56847b-89be-42ba-8bad-d9a9a05a964f.png)

### Expected behavior

In the old version of VS Code (I'm afraid that I cannot sure the exact version), `\boldsymbol` could be previewed properly just like [Supported TeX/LaTeX commands](http://docs.mathjax.org/en/latest/input/tex/macros/index.html) said.

## Logs [Required]

I'm sorry but this is just a preview issue and I didn't have any log files. :(

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10 21H1
 - VS Code version: 1.67.1
 - Extension version: 8.26.0
 - TeX distribution version: TeX Live 2020

Thanks!

**Comment by VictoriousRaptor** [comment]
#3180
