### ISSUE TITLE
Disable VS Code error texts

### ISSUE THREAD

**Issue by christianmalek** [James-Yu/LaTeX-Workshop#33]
Hi,

Is it possible to disable the alerts when the compiling is failing? It's sufficient to see the error log for me. Otherwise it would be neat if they go away automatically if the next compilation is successful.

I mean these alerts:
![image](https://cloud.githubusercontent.com/assets/2873986/24148069/65b1c2a6-0e3d-11e7-8fcd-3b944900d514.png)

**Comment by James-Yu** [comment]
Solved in #35
