### ISSUE TITLE
Need way to override pdfTeX when compiling.

### ISSUE THREAD

**Issue by brownem** [James-Yu/LaTeX-Workshop#330]
### Selecting Default Compiler

We need a way to set a default compiler other than pdflatex, like you can with most LaTeX editing programs (such as TeXworks)

### Running any LaTeX file that doesn't play nice with UTF-8 or more complex formatting.

Using the fontspec package, to allow for more control over custom fonts, requires using XeLaTeX. Calling for this package in either the main TEX file or something like an accompanying CLS will cause LaTeX Workshop to fail building the PDF.

### Expected behavior

PDF file generated. I've already produced this, admittedly complex, file with Overleaf and TeXworks.

### Actual behavior
Fails when the user doesn't force XeLaTeX with `% !TEX program = XeLaTeX+MakeIndex+BibTex` added to the very beginning of the file, before even `\documentclass[letterpaper]`. Adding the forced compiler selection doesn't solve the problem either, since you still only get a blank PDF output. I suspect that LaTeX Workshop isn't properly selecting the necessary compilers. I confirmed it works perfectly with TeXworks running the `XeLaTeX+MakeIndex+BibTex` compiler option.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
C:\Users\...\AppData\Local\Programs\MiKTeX 2.9\tex\latex\fontspec\fontspec.

sty:37: Fatal fontspec error: "cannot-use-pdftex"

! 
! The fontspec package requires either XeTeX or LuaTeX.
! 
! You must change your typesetting engine to, e.g., "xelatex" or
! "lualatex"instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>

 ) ) )
(see the transcript file for additional information)
No pages of output.
Transcript written on Resume.log.
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Resume.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
</details>

**Comment by James-Yu** [comment]
You need to read readme. Especially FAQ.

**Comment by brownem** [comment]
I did read the Readme, first line to last, and I thought I had already configured things correctly. Hence my Issue. "RTFM" is pretty much my go-to. But re-reading my initial issue, I recognize that it wasn't as clear as it could have been - I was pretty tired and it was pretty late here when I opened it.

Opening your main `.tex` files as follows _should_ automatically force the compiler to use the XeLaTeX engine. XeLaTeX can also be replaced with any other LaTeX engine that is installed.
```
% !TEX program = XeLaTeX
\documentclass[letterpaper]
```
This is the case in other IDEs; confirmed in TeXworks last night, and Sublime Text this evening. This is not the case when using Latex Workshop in VSC. Editing the Toolchain did not solve this problem, possibly because the Readme as it stands is not clear on how to invoke a different engine. You can set parameters for the different commands, but you cannot - as far as the documentation explains - set new default commands. That is to say, I could tell Latex Workshop what settings I want to use for XeLaTeX, and in what order, but I cannot seem to tell it to use XeLaTeX before using pdflatex when performing the default `CTRL+ALT+B` build command. On top of this, the way it seems to be handling latexmk when your press `CTRL+ALT+B` ignores the forced XeLaTeX call at the beginning of the `.tex` file. This is the first time I've ever seen any LaTeX IDE do this. You _can_ solve this in a hacky-way by modifying `latexmk`, and I will explain this below.

**This is the first issue, that a command to use a specific engine called out in the header of a tex file is ignored because of the way Latex Workshop handles `latexmk`. There is also a second, related, issue if you modify latexmk.**

If you need a engine other than XeLaTeX when using Latex Workshop with a modified `latexmk`, then you're up the creek again. You need to go back into the configuration file and re-modify it to use yet another engine.

## Brute force solution to the second issue
Instead, in order to get it work (in case someone else with the same problem sees this), I had to modify latexmk. Latexmk has been able to natively call XeLaTeX for years now, but you still modify the configuration in order to get it to use it over latexpdf. On Windows, you accomplish this by creating a folder
```
C:/latexmk
```
then creating a blank, extension-less file titled `LatexMk`. This will be the configuration file for latexmk, and all custom settings go here. Put `$pdflatex=q/xelatex -synctex=1 %O %S/` in the first line, and save it. latexmk will now use XeLaTeX every time it is run, instead of pdflatex.

## What would make it simpler
A way to simply select which engine is used would be great improvement to Latex Workshop, and give it feature parity with the other LaTeX IDEs out there. Whether it is a drop down menu somewhere (like TeXworks) or editing the settings file to provide a sequential order of engines to use in case one fails makes no difference to me. This will solve the second issue, but could create future headaches if you run into a file or package that doesn't play nice with XeLaTeX (or whichever engine you tell latexmk to use instead of pdflatex)

If this is already possible, directly mentioning how to use a different engine in the Readme file of Latex Workshop would also solve the second issue, without potentially creating new issues in the future.

As for the first issue - ignoring a command in the main .tex file header that invokes a specific engine - that doesn't have a clear solution, but I would rank it as even higher importance, as it could cause other, completely unrelated, issues when a user tries to invoke certain arguments in their file.

**Comment by James-Yu** [comment]
According to the README
> LaTeX toolchain refers to a sequence/array of commands which LaTeX Workshop will execute sequentially when building LaTeX projects. It is set in File>Preferences>Settings>latex-workshop.latex.toolchain. This configuration item is an array of objects, which should have a command field and an optional args array field. The former defines the command that will be invoked in each step of the toolchain, while the latter defines the arguments that will be passed alongside with the command.
This means that you can define the sequence of commands which the extension will use to compile the project.

> LaTeX Workshop supports both % !TEX root and % !TEX program magic comments. The former is used to define the root file, while the latter helps select compiler program.
> All command in toolchain which are empty will be replaced with the program set by % !TEX program magic comment in the root file. Suppose there is a line % !TEX program = xelatex in the root file, and the toolchain is set as follows:
Alternatively, set command to empty to enable `% !TEX program` magic comments.

I do not see any problem here, since your issue, i.e., `This is the first issue, that a command to use a specific engine called out in the header of a tex file is ignored because of the way Latex Workshop handles latexmk.`, is not valid. The extension does not force `latexmk` or `pdflatex`. It just need some config in the config.

Dropdown menu for specific extension is not valid in vscode. The editor does not enable DOM manipulation.

For ease of your work, I propose a valid `xelatex` toolchain for you, which is edited from the example given in README:
```
"latex-workshop.latex.toolchain": [
  {
    "command": "xelatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "%DOC%"
    ]
  }, {
    "command": "bibtex",
    "args": [
      "%DOCFILE%"
    ]
  }, {
    "command": "xelatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "%DOC%"
    ]
  }, {
    "command": "xelatex",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "%DOC%"
    ]
  }
]
```

**Comment by brownem** [comment]
Unfortunately, the toolchain you've suggested is identical to the one I had produced myself, and still produces errors with selecting xelatex. I did copy and paste in the one you provided here, just to be sure.

Setting my latex toolchain to be empty just causes the compile option to "complete" without doing anything.

Only the modified latexmk has worked so far.

**Comment by James-Yu** [comment]
I can't see where the problem should be. Can you post your config and extension log messages?
