### ISSUE TITLE
Changed `chktex.args.active`  to `chktex.args`

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3307]
@jlelong  I am not sure we have to change `chktex.args.active`  to `chktex.args`. It would be enough to remove `chktex.args.root` only. I am neutral about the decision.

At least you had better add the change to `CHNAGELOG.md`.

**Comment by jlelong** [comment]
I agree that this was not required. I could just have removed `chktex.args.root`, but I wanted to make the variable naming coherent with what we do for running various commands: `blabla.path` and `blabla.args`.
