### ISSUE TITLE
TypeError: configuration.get is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3308]
Version: 1.68.0-insider (Universal)
Commit: 528ee1ae3daabe30c1307cf9dcd6e77eb96094bc
Date: 2022-05-26T05:16:32.715Z
Electron: 17.4.4
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 20.6.0

1. Set the following in `settings.json`:

```json
    "latex-workshop.chktex.args.active": [
        "-wall",
        "-q",
        "-e15",
        "-e16",
        "-n1"
    ],
    "latex-workshop.chktex.args.root": [
        "-wall",
        "-q",
        "-e15",
        "-e16",
        "-n1"
    ]
```

2. Run the current master 195fa17279c3a0aca540e0463b091768253585da. We see the following error:

```
TypeError: configuration.get is not a function or its return value is not iterable
	at Linter.lintRootFile (/Users/tamura/src/github/LaTeX-Workshop/out/src/components/linter.js:149:40)
	at Linter.lintRootFileIfEnabled (/Users/tamura/src/github/LaTeX-Workshop/out/src/components/linter.js:95:23)
	at /Users/tamura/src/github/LaTeX-Workshop/out/src/main.js:182:67
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The returned value by `configuration.get('chktex.args')` is weird. It would be a bug of VS Code.

https://github.com/James-Yu/LaTeX-Workshop/blob/195fa17279c3a0aca540e0463b091768253585da/src/components/linter.ts#L135

**Comment by jlelong** [comment]
I think it is a limitation of VS Code. One configuration variable name cannot match the section of an other variable.

`latex-workshop.chktex.args.active` shadows `latex-workshop.chktex.args`.

```
configuration.get('chktex.args')
Proxy {active: Array(17)}
configuration.get('chktex.args').active
(17) ['-wall', '-e16', '-n1', '-n3', '-n6', '-n12', '-n19', '-n21', '-n22', '-n24', '-n25', '-n30', '-n36', '-n37', '-n44', '-n46', '-q']
```

So there is no way to replace `latex-workshop.chktex.args.active` and `latex-workshop.chktex.args.root` by `latex-workshop.chktex.args` because linting will be broken for all users who modified these settings.

**Comment by tamuratak** [comment]
I am neutral about this kind of breaking changes because all I have to do is just changing the setting.

However, you have to deal with questions and complains from users on this change. If you are fine with it, I am fine with the change.

**Comment by jlelong** [comment]
I will think about the best way to handle this.

**Comment by jlelong** [comment]
Let us leave it like this. I may add a tweak before accessing `chktex.args` to ensure that `chktex.args.{active,root}` is not defined.
