### ISSUE TITLE
Conflict in default settings: Ignoring latex-workshop.chktex.args.active as latex-workshop.chktex.args is ["-wall","-n22","-n30","-e16","-q"]

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3315]
On Developer Tools, we see the following errors:

```
Conflict in default settings: Ignoring latex-workshop.chktex.args.active as latex-workshop.chktex.args is ["-wall","-n22","-n30","-e16","-q"]
Conflict in default settings: Ignoring latex-workshop.chktex.args.root as latex-workshop.chktex.args is ["-wall","-n22","-n30","-e16","-q"]
```

It would be better to use a name different from `latex-workshop.chktex.args`.

**Comment by jlelong** [comment]
The section `latex-workshop.chktex` is already used by many configuration variables, so we had better keep it. The best solution seems to put `args` and `path` in a subsection of `latex-workshop.chktex`. 

What about `latex-workshop.chktex.exec.args` and `latex-workshop.chktex.exec.path`?

**Comment by tamuratak** [comment]
> What about latex-workshop.chktex.exec.args and latex-workshop.chktex.exec.path?

They would be better.
