### ISSUE TITLE
Open file on click

### ISSUE THREAD

**Issue by MSkovmand1** [James-Yu/LaTeX-Workshop#332]
Very green guy here, not even sure if you can call it an issue, but here goes.
I've been using TexStudio almost all my latex writing days, which are not that many years. Recently I've had reason to start doing some basic coding, and ended up with visual studio, and thought that I could do my text editing in that as well. I've dl'ed your extension and have a few questions if it is doable.

Firstly, in Texstudio, when having a lot of \include{somerandomtext.tex} I can just cmd+mouse click. and it will open the file. When having many subfiles, this is extremely efficient, is this possible with Vscode and your extension, if so - how?

Secondly, when I first got the extension rolling I got an "latex outline" in my explorer. I "accidently" removed it, and have no idea how to get it back. Can you assist me?

I'm very sorry if this is out of terms, but i find it extremely difficult finding help for this online. And as I'm new to Vscode and this world, in general, it doesn't make it easier. 

Hope you can assist me!

Edit: Is there a way to get a color for "&" in math and tabular mode?

**Comment by James-Yu** [comment]
Thanks for your issue. AFAIK there's no support for file-redirection, but it can be implemented in the future.

As to the outline, you can right click on `EXPLORER` at the top to bring up this context menu:
![image](https://user-images.githubusercontent.com/4210342/33469798-f13e6308-d69f-11e7-8927-0a4854f25df8.png)

`&` needs a special syntax highlight rule, which is a bit out of my capability. Leave for community contribution?

**Comment by MSkovmand1** [comment]
Thanks for your answer, I feel like a moron, with the outline. But when opening it, there is no info in it.
<img width="602" alt="skaermbillede 2017-12-01 kl 08 23 44" src="https://user-images.githubusercontent.com/34109720/33472117-0bd687e2-d671-11e7-9e33-60b33087b57b.png">

I've read in an earlier topic saying that I should open another, not .tex file, this doesn't seem to work. I've run a random python file, debugged it, and recompiled my master.tex, and the LaTex outline is still empty.

Any ideas?

**Comment by innerlee** [comment]
I guess there are many independent tex files in the workspace. The current program logic cache for the first root file, and that file happens to be empty.

**Comment by innerlee** [comment]
A fix might be call [findRoot](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/manager.ts#L66) before [refresh](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/outline.ts#L28). But I'm not sure how often the `refresh` would be called and how much the cost of `findRoot` is.

**Comment by MSkovmand1** [comment]
There are many independent, which are all called in the master file.

If I understand you correctly, the first file in the workspace, should be my master file?

Again, thanks a lot for your time and effort.

**Comment by zoehneto** [comment]
Opening included files (both latex and bibtex) could probably be accomplished using [languages.registerDefinitionProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#languages.registerDefinitionProvider). You could then open the files using "Go to Definition" or the respective shortcut. See [this](https://github.com/Microsoft/vscode-go/blob/a74c6ca5e9622de72ab77767bd143598852e484e/src/goDeclaration.ts) for how its implemented in the vscode go extension.
