### ISSUE TITLE
"View Latex PDF file" button at right upper corner are disabled

### ISSUE THREAD

**Issue by Sakurajyan** [James-Yu/LaTeX-Workshop#3325]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yeso

## Describe the bug [Required]

"View Latex PDF file" button at right upper corner are disabled. But the keyboard shortcut Ctrl+alt+v and view latex pdf in left activity bar are working correctly. This bug appeared after I update Latex-Workshop to version 8.27.0.

### To Reproduce

3. See error

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 11
 - VS Code version: 1.67.2
 - Extension version: 8.27.0
 - TeX distribution version: /MiKTeX 22.3

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by weaponrex** [comment]
duplicate issue #3324 

it's an issue with the recent 8.27 release. The workaround is to use the keyboard shortcut.

You can also install earlier version 8.26 and restart vscode to bring back the button functionality.
