### ISSUE TITLE
Enable "Toggle Line Comments" (CTRL-#, CTRL-\) shortcut for .bib files.

### ISSUE THREAD

**Issue by bwegge** [James-Yu/LaTeX-Workshop#3327]
This was already requested a while ago (https://github.com/James-Yu/LaTeX-Workshop/issues/2593) and closed with the remark that only the biber backend would understand comments. Meanwhile, it appears that BiBTeX (and potentially other backends) does understand line comments outside of entries (see comment below https://tex.stackexchange.com/a/335678/248556). Even the official BiBTeX example file uses line comments: https://ftp.rrze.uni-erlangen.de/ctan/biblio/bibtex/base/xampl.bib

Therefore, I think it would still be helpful for those people who do use bib backends that understand comments to be able to use the feature (instead of having to manually enter '%' on each comment line), or who want to responsibly use comments only outside entries.

Hope this was convincing ;). Anyway, thanks for the great extension!

**Comment by James-Yu** [comment]
> The `%` character does not indicate the start of a comment in BibTeX files. In a BibTeX, everything outside an entry is a comment. See https://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#comment for a very detailed description of how comments work in BibTeX.

Awesome example! Also in the example file provided by @bwegge there is line comments without `%`. We'd better follow the practice.

#3342 solves the comment in `biber`.
