### ISSUE TITLE
Add folding of \item blocks

### ISSUE THREAD

**Issue by mfederczuk** [James-Yu/LaTeX-Workshop#3333]
I'm often creating `enumerate` or `itemize` environments with rather large `\item` blocks, so it would help to focus on the current item I'm working on when the individual `\item` blocks would be able to be folded. 

Here is a mock-up I created, that shows how it could look like:

![Mock-Up Image][mock_up]

Of course, it is possible to put `%\begingroup` in the first line and `%\endgroup` in the one before the next `\item`, though this is a bit of a hassle and seems more like a hack - it'd be a nice-to-have feature if it would work properly out of the box.

[mock_up]: <https://user-images.githubusercontent.com/14075939/173197638-17f60784-4b5e-4774-bf38-bf5c5a74eaf0.png> "Made with glorious GIMP"

**Comment by James-Yu** [comment]
@mfederczuk Thanks for the feature request. However, the current folding implementation can be difficult to adapt to the usecase of `\item`:

Currently, the extension uses https://github.com/James-Yu/LaTeX-Workshop/blob/4ac6292731da9792959d507592a373d96ceb682d/src/providers/folding.ts to calculate the folding ranges, which depends on two functions `getSectionFoldingRanges` and `getEnvironmentFoldingRanges`. The former relies on a highly-complex logic to determine the starting and ending lines of a document, and the latter requires a clear `begin` and `end` definition for each type of folds. Unfortunately, neither works natively for `\item` as it does not have a consistent ending 'signature'.

I would recommend close this issue for now and come back if we eventually can switch to `latex-utensil`-based parsing, where #3224 is a starting point.
