### ISSUE TITLE
Consider using the customEditor api (Re-submit)

### ISSUE THREAD

**Issue by ManuelHentschel** [James-Yu/LaTeX-Workshop#3338]
Re-submitting, since locking the issues/PRs makes it impossible to answer.
Could you please reconsider using the customEditor api for the pdf viewer provided by this extensions?
I already implemented this in https://github.com/James-Yu/LaTeX-Workshop/pull/3069, which was promptly rejected and locked.

In https://github.com/James-Yu/LaTeX-Workshop/issues/3337, you answered "Rejected with the same reason.", which seems to refer to https://github.com/James-Yu/LaTeX-Workshop/pull/3069#issuecomment-1025154388:
> Rejected. Not convinced.
> >   Avoids opening the same pdf multiple times
>
> The feature of opening the same pdf multiple times is what we want.

As stated in the original PR, opening the same pdf multiple times is still possible with the changes, the same way you can open any other editor multiple times. Furthermore, you can use the native vscode behaviour to e.g.
- open the pdf in a new view column, by dragging the filename from the explorer view to the side of the currently open editor
- refocus an already opened pdf viewer by clicking on the filename in the explorer view
- use file icon themes
- avoid stealing focus if you switch editors while "LaTeX Workshop PDF Viewer is opening a PDF file..." is shown

Let me know if you disagree with any of the points above and please consider not locking this issue immediately, in order to give everyone a chance to answer. Thank you very much in advance!

Edit: https://github.com/James-Yu/LaTeX-Workshop/discussions/3273 should also be resolved by this PR.

**Comment by ManuelHentschel** [comment]
Follow up: The setting mentioned in https://github.com/James-Yu/LaTeX-Workshop/pull/3069#issuecomment-1025261878 does not solve the problems mentioned above, since it makes it impossible to refocus an already instance of the pdf viewer.

**Comment by James-Yu** [comment]
@ManuelHentschel please join the discussion in #3337 if it is not locked. p.s., this should not be labeled as feature request, which the default action is reject. Your proposal seems to be an adoption of newer api.
