### ISSUE TITLE
Toolchain terminated with error - synctex, intreraction bad option

### ISSUE THREAD

**Issue by Ericcur** [James-Yu/LaTeX-Workshop#334]
### Description

I can't compile my tex files. I installed texlive and latexmk(placed latexmk.bat and latexmk.pl in PATH) so i should have everything to build a .tex file. However, when i try to build i get "LaTeX toolchain terminated with error 

### How to reproduce

1. Open a .tex file
2. press ctrl + alt + B (Build Latex project)

### Expected behavior

Create a PDF with no errors

### Actual behavior

Fails to compile .tex file and return an error

### Log messages

c:\Users\cirec\Dropbox\LaTeX>Rem Execute latexmk.pl, searching for it in the PATH 

c:\Users\cirec\Dropbox\LaTeX>Rem Assume perl is in the PATH.  If not, you should replace 'perl' by  

c:\Users\cirec\Dropbox\LaTeX>Rem the full pathname of the perl executable, e.g., 'C:\perl\bin\perl.exe' 

c:\Users\cirec\Dropbox\LaTeX>perl -S latexmk.pl -synctex 1 -interaction nonstopmode -file-line-error -pdf c:\Users\cirec\Dropbox\LaTeX\text   
Latexmk: -synctex bad option
Latexmk: -interaction bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
C:\texlive\2017\bin\win32\runscript.tlu:708: command failed with exit code 10:
cmd /c call C:\texlive\2017\bin\win32\latexmk.bat -synctex=1 -interaction=nonstopmode -file-line-error -pdf c:\Users\cirec\Dropbox\LaTeX\text

**Comment by James-Yu** [comment]
It is not related with the extension. After all, texlive bundles latexmk and you should be able to use it with a valid perl installation.
