### ISSUE TITLE
color problem in the pdf viewer

### ISSUE THREAD

**Issue by angan06** [James-Yu/LaTeX-Workshop#336]
Dear James, 

swith the new theme of the PDF-viewer, the title of the thumbnails seems to not be visible.
Maybe a darker color for the side panel, or for the text should correct that.
![color problem](https://user-images.githubusercontent.com/26283490/33541890-2c2c79cc-d8d1-11e7-985e-dae1f9b45439.png)

Best regards.

**Comment by James-Yu** [comment]
I cannot recall that there were titles for pages. Can you please find a previous screenshot to remind me on that?

**Comment by James-Yu** [comment]
I got what you mean. Fix on the way.

**Comment by angan06** [comment]
Ok, thank you I was currently writing more explanations. It is true that I was not very precise, sorry.
