### ISSUE TITLE
CMake Server Mode support

### ISSUE THREAD

**Issue by MathiasMagnus** [James-Yu/LaTeX-Workshop#337]
### Description

Because the task execution engine built into VS Code lacks in many regards, it would be nice if a ubiquitous build system (generator) would be supported. I would argue, that CMake is perhaps the best choice. I do teach junior physicist (who have to deal with quite a lot of LaTeX in their professional life) how to automate building a library, an exe consuming it, invoking the exe for a data file, plotting the data using GnuPlot and compiling a LaTeX document using the plot in an [end-to-end](https://github.com/Wigner-GPU-Lab/Teaching/tree/master/KutInf) manner with proper dependencies being tracked by the generated build system (Ninja per say).

It would be nice if following in the footsteps of [cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), LaTeX-workshop picked up prime-time CMake support. [CMake Tools](https://marketplace.visualstudio.com/items?itemName=vector-of-bool.cmake-tools) is a nice extension that should provide the hooks through its API to detect custom_command invocations relevant to LaTeX-Workshop. The feature driving IDE hooks into CMake is [CMake Server Mode](https://cmake.org/cmake/help/latest/manual/cmake-server.7.html), a long-running (build server-like) mode of CMake that constantly monitors the scripts of CMake used to generate the build system files, as well as presenting a JSON API for the resulting CMake Configuration. Every IDE extension can query this JSON for the parts relevant to them to trigger language service features, GUI hooks, SyncTex and what not.

Currently, even though I get my resulting PDF, I [cannot open it](https://github.com/James-Yu/LaTeX-Workshop/issues/240), because the extension is not aware of it/was not created by it. The authors of [UseLATEX](https://github.com/kmorel/UseLATEX) and CMake Tools are both very eager to help on their part (vector-of-bool can be unresponsive at times) and I'm sure ends can be made to meet.

This enhancement is orthogonal/supplementary to the awesome in-flight proposal of using the [built-in LaTeX compilation](https://github.com/James-Yu/LaTeX-Workshop/issues/119). UseLATEX can easily be configured to use any LaTeX compiler.

**Comment by tamuratak** [comment]
Feel free to reopen if any progress.
