### ISSUE TITLE
Python code highlighting for all environments of the package `pyluatex`

### ISSUE THREAD

**Issue by nplatis** [James-Yu/LaTeX-Workshop#3376]
Issue #2542 implemented Python code highlighting when the `pythontex` package is used. I would like to ask to extend this support for the `pyluatex` package.

The commands provided by the package, that have Python code as parameters, are: `\py{}`, `\pyq{}`, `\pyc{}`,  `\pycq{}`, `\pyif{<test>}{<then>}{<else>}` (where only `<test>` is Python code, `<then>` and `<else>` are LaTeX code).

Also, the environments provided by the package are: `python`, `pythonq`, `pythonrepl`.

**Comment by James-Yu** [comment]
@jlelong May you have a look in this? Many thanks!

**Comment by jlelong** [comment]
I will look at this.
@nplatis It would really help if you could provide some examples for all these commands and environments.

**Comment by nplatis** [comment]
Thanks for the quick response.

All the commands that I list take some Python code as their _only_ parameter. For example, `\py{3+2}` outputs `5`, or `\pyc{print(’hello’)}` outputs `hello`; but I suppose that the exact function of each command does not really matter, what' s important is their parameters. As I mentioned, the only more complex command is the `\pyif{}{}{}` one, where the first parameter is Python code and the other two are LaTeX code. Let me note that the package provides some other commands, which take "simple" parameters (not Python code), so I do not mention them here.

Similarly, the environments do not have any optional parameters and only include Python code.

The commands and environments are very similar to the ones of `pythontex` package (and some even have the same names).

More details can be found in Sections 3.2 and 3.3 of the `pyluatex` [manual](https://ftp.cc.uoc.gr/mirrors/CTAN/macros/luatex/latex/pyluatex/pyluatex.pdf).

**Comment by jlelong** [comment]
We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so I have transferred the issue to that repository: 
- jlelong/vscode-latex-basics#28

Let us keep discussing there if needed.
