### ISSUE TITLE
Multiples toolchain

### ISSUE THREAD

**Issue by caiofcm** [James-Yu/LaTeX-Workshop#338]
It is possible to have more than one "latex-workshop.latex.toolchain" set, such that I can chose the suitable toolchain?

Some times the toolchain: [pdflatex; bibtex; pdflatex; pdflatex] is necessary, but other times just pdflatex action would be enough.

**Comment by James-Yu** [comment]
This is the design purpose of `latexmk`. I would recommend you to have a check on this great automation tool.

**Comment by caiofcm** [comment]
Great, thank you
