### ISSUE TITLE
[dev] Await-semaphore

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3388]
https://github.com/James-Yu/LaTeX-Workshop/blob/a064e154c2cfec3bb241b0eb91c1cb47abcb45d3/src/lib/await-semaphore/index.ts#L1

When looking back in the code, I noticed this dependency here. @tamuratak may I know if there is any particular reason on maintaining our own copy of the lib, instead of using https://www.npmjs.com/package/await-semaphore? Did we made modifications to the codebase? If it does not make a difference, I'm happy to make a PR to remove the lib and test. Maybe modern variants of the mutex can also be integrated e.g., https://www.npmjs.com/package/async-mutex. I'm also good to look into their difference.

**Comment by tamuratak** [comment]
See

- https://github.com/James-Yu/LaTeX-Workshop/pull/1180#issuecomment-464943930

I don't there is any advantage of using `async-mutex`. The current `await-semaphore` works well and flawlessly without any maintenance. We should not touch it because it works.

**Comment by James-Yu** [comment]
Thanks for the heads up. I agree that no bug no change. Will think for another sec on if we can outsource the code without changing project compile options.
