### ISSUE TITLE
Reverse SyncTex Problem

### ISSUE THREAD

**Issue by ganxy1028** [James-Yu/LaTeX-Workshop#34]
Hi,
Windows 10 with TeXLive 2016 , it fails to Reverse SyncTex (from PDF to Tex). Any idea?

**Comment by James-Yu** [comment]
No idea with given information.

**Comment by ganxy1028** [comment]
I used Ctrl + left click on PDF preview, but nothing happened , so as my two friends. And I found some Reviews in the visualstudio.com Marketplace about this problem. So maybe there are bugs when using Windows ?
Sorry, it may seem stupid, but I don't know what information else I can provide.

**Comment by ganxy1028** [comment]
I used Ctrl + left click on PDF preview, but nothing happened , so as my two friends. And I found some Reviews in the visualstudio.com Marketplace about this problem. So maybe there are bugs when using Windows ?
Sorry, it may seem stupid, but I don't know what information else I can provide.

**Comment by James-Yu** [comment]
Can you please check if synctex is in your path?

Open a command line window, type `sycntex.exe`, enter and see what's the output.

**Comment by ganxy1028** [comment]
![default](https://cloud.githubusercontent.com/assets/26629457/24299601/b4d2228c-10e4-11e7-808b-3368afe63848.PNG)
It's already in the path.
And Everything works well with Texworks editor, if this information helps

**Comment by James-Yu** [comment]
Do you have the .synctex.gz file with your pdf?

**Comment by ganxy1028** [comment]
![default](https://cloud.githubusercontent.com/assets/26629457/24300156/7994a882-10e6-11e7-82f1-96c614f20640.PNG)
Yes. And there is nothing wrong with the .synctex.gz file, if I use TeXworks editor to open the Tex code  , it is not needed to compile agan to get  reverse synctex work with it.

**Comment by ganxy1028** [comment]
![Uploading 123.jpg…]()
Yes. And there is nothing wrong with the .synctex.gz file, if I use TeXworks editor to open the Tex code , it is not needed to compile it agan to get reverse synctex work with it.

**Comment by ganxy1028** [comment]
Yes. And there is nothing wrong with the .synctex.gz file, if I use TeXworks editor to open the Tex code , it is not needed to compile it agan to get reverse synctex work with it.

**Comment by ganxy1028** [comment]
Yes. And there is nothing wrong with the .synctex.gz file, if I use TeXworks editor to open the Tex code , it is not needed to compile it agan to get reverse synctex work with it.
![123](https://cloud.githubusercontent.com/assets/26629457/24301615/ffbfb768-10ea-11e7-97f5-15c06eb5a64d.jpg)

**Comment by James-Yu** [comment]
Please try removing spaces in your file name.

**Comment by ganxy1028** [comment]
I writed a new  TeX code with simple configuration to do some test, which is showed above. It still can't work.

**Comment by James-Yu** [comment]
Sorry but without advanced logging, I cannot identify the problem.

Tho I plan to completely rewrite the extension shortly. Will definitely review this issue.

**Comment by ganxy1028** [comment]
Thank you all the same.
I will still recommend your extensions to my friends.

**Comment by liyi193328** [comment]
same question, is there any solution now ? thanks

**Comment by dccastro** [comment]
@James-Yu, I'm having the same problem, and it does seem to be due to spaces in the path -- which I've confirmed by running `synctex` on the command line with the same arguments. A simple fix would be to surround the path with quotes when assembling the `synctex edit -o` arguments here (e.g. `4:123.4:56.7:"/my path/with spaces/file.pdf"`):
https://github.com/James-Yu/LaTeX-Workshop/blob/c74c1e9873588286270e81cc439cf4c9d8da8c31/src/components/locator.ts#L211
