### ISSUE TITLE
Highlight support for lco files

### ISSUE THREAD

**Issue by MaKaNu** [James-Yu/LaTeX-Workshop#3406]
## Is your requested feature  related to a problem? Please describe. [Required]

If I format my letters for the `scrlttr2` KOMAScript class I use `lco`-files for formatting. At the moment their is no package available which supports highlighting lco files. Since they are related to `tex` files a support from this extension would be fitting.

## Describe the solution you'd like  [Required]

A similar highlighting as with normal tex files. Here a small example of such file:

```tex
\ProvidesFile{brief.lco}[%
  2002/07/09 v0.9a LaTeX2e unsupported letter-class-option]

\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{ngerman}
\usepackage{lmodern}
\setkomavar{fromname}{My Name}
\newcommand\addrsecrow{My Org}
\newcommand\rechtsform{Something}
\setkomavar{fromaddress}{WONDERROAD 132 \\12345 Wondercity}
\setkomavar{fromphone}{Tel: +49 (0)30 12 34 56 78 }
\setkomavar{fromfax}{Fax: +49 (0)30 12 34 56 99}
\setkomavar{fromemail}{info@diefirma.web}
\setkomavar{signature}{Mr Blob}
\newcommand\ustid{UstID: DE 123 456 789}
\setkomavar{frombank}{Bankverbindung\\
	   Eurcorp Bank Berlin\\
	   Kto 123 45 67\\
           BLZ 123 456 78
}

\pagestyle{myheadings}
\addtoplength{firstfootvpos}{5mm}
\setplength{firstheadvpos}{12mm}
\setplength{firstheadvpos}{12mm}
\addtolength{\textheight}{15mm}


\setkomafont{backaddress}{\scriptsize}
\typeout{\scdefault}                                                                                                          
\DeclareFixedFont{\fa}{\encodingdefault}{cmr}{m}{\scdefault}{12} 
\DeclareFixedFont{\cc}{\encodingdefault}{cmr}{m}{\scdefault}{24.88} 
\setkomavar{firsthead}{
    \resizebox{\useplength{firstheadwidth}}{!}{%
	\begin{tabular}{c}
	    \cc  \usekomavar{fromname}\\[4mm]
	    \fa  \addrsecrow 
	\end{tabular}
    }
}


\setkomavar{firstfoot}{%
      \scriptsize{
        \parbox{\useplength{firstfootwidth}}{ 
          \rule{180mm}{0.5pt} 
          \begin{tabular}{ll}
	  \usekomavar{fromname}\\
          \rechtsform\\
	  \usekomavar{fromaddress}\\
	    \end{tabular}\hfill
          \begin{tabular}{cc}
	  \usekomavar{fromemail}\\
	  \usekomavar{fromphone}\\
	  \usekomavar{fromfax}\\
	  \ustid
          \end{tabular}\hfill
          \begin{tabular}{rr}
	  \usekomavar{frombank}\\
	             \end{tabular}
       }}
}

\setkomavar{nextfoot}{%
    \parbox{\useplength{firstfootwidth}}{
          \begin{tabular}{ll}
		  \usekomavar{fromname}
	      \end{tabular}\hfill
	      \begin{tabular}{cc}
		  \today 
	      \end{tabular}\hfill
	      \begin{tabular}{rr}
		  \thepage
	      \end{tabular}
    }
}



\endinput
% vim: set filetype=tex  :EOF

```

As you can see the markdown supports with `tex` as language, so I think it would be not to complicated.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: WIN10
 - VS Code version: 1.69.2
 - TeX distribution version: TexLive 2022
 

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
You can select your highlight language at the bottom right corner of vscode. This does not have any limitation on the file type.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/4210342/182029987-0a5e653c-da01-43da-8873-419037d05cd1.png">

**Comment by MaKaNu** [comment]
As always fast and helpfull. I really appretiate the work.
