### ISSUE TITLE
The PDF output is not generated into the outdir defined by  "latex-workshop.latex.outputDir" 

### ISSUE THREAD

**Issue by sidmishraw** [James-Yu/LaTeX-Workshop#341]
### Description
The PDF output is not generated into the `outdir` defined by  `"latex-workshop.latex.outputDir"` . Rather, it is generated at `./`.

I have tried reloading VSCode and the extension but, there has been no impact.

### How to reproduce

1. Add workspace setting for `"latex-workshop.latex.outputDir"` 

### Expected behavior
The PDF files should be generated into the directory assigned to the `"latex-workshop.latex.outputDir"` contribution point.

### Actual behavior

Output is generated at `./` instead.

**Comment by James-Yu** [comment]
`The directory where output files (e.g., PDF and SyncTeX files) are located.\nBoth relative and absolute pathes are supported. Relative path start from the root file location, so be ware if it is located in sub-directory.`

This does not control your toolchain. Rather, this config guides the extension to find the output file in the given folder.

**Comment by sidmishraw** [comment]
Thanks for clearing it. I associated it with the toolchain – my bad.

**Comment by James-Yu** [comment]
I'd thank you for raising the issue. Actually this config should have a better description. Change on the way.
