### ISSUE TITLE
Add support for VS Code 'Drop into editor' API

### ISSUE THREAD

**Issue by c-schuhmann** [James-Yu/LaTeX-Workshop#3420]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

If you want to include images or other files into your document, you have to manually write all LaTeX code to import it or copy/edit some snippets.

## Describe the solution you'd like  [Required]

This extension could add support for the new [Drop into editor API](https://code.visualstudio.com/updates/v1_70#_drop-into-editor-api) for VS Code, added in version. 1.70. Some examples would be automatically adding a `figure` section, when dropping an image file into the editor, or adding an `\input` statement when dropping a `.tex` file.

To be honest: It's not really a problem, but having this feature would be a small nice to have.

## Desktop [Required]

 - OS: Windows 10
 - VS Code version: 1.70.0
 - Extension version: 8.28.0
 - TeX distribution version: texlive-full 2017.20180305-1 (debian package)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

Yes

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote WSL
- Remote Extension Version: 0.66.3

**Comment by James-Yu** [comment]
#3417
