### ISSUE TITLE
Syntax Highlight Issue

### ISSUE THREAD

**Issue by fathi0amir** [James-Yu/LaTeX-Workshop#3446]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

The syntax highlighting changes when there is line break. e.g. you use "\usepackage" command without line break the color 
is purple same as the "\documentclass" command (in my theme). But if you go to new line to continue the options 
for a package, the "\usepackage" command changes color to yellow (same color as "\begin" command). Of course this 
is not a big issue but it will nice if its consistent with all the command calls without the line break. I will include a screenshot 
as well. 

### To Reproduce

\usepackage[perpage, para, symbol]{footmisc}

\usepackage[
	backend=biber,
	style=nature]{biblatex}

compare the syntax highlighting of the above inputs. 

### Expected behavior

Have consistent color highlighting for the same command. 

## Screenshots
![image](https://user-images.githubusercontent.com/78668053/187872880-4a5ead94-4c17-4539-ac47-e3997086a644.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: [e.g. Windows 11]
 - VS Code version: [e.g. 1.7.1]
 - Extension version: [e.g. 8.29.0]
 - TeX distribution version: MiKTeX 22.7

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#36
