### ISSUE TITLE
Placeholder %WORKSPACE_FOLDER% not accessible from cleanCommand args

### ISSUE THREAD

**Issue by alvarezdqal** [James-Yu/LaTeX-Workshop#3451]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

As you can see below, I use a custom `outDir`. I would like to delete an **ancestor** of this `outDir` completely during cleanup, but, since the path makes reference to `%WORKSPACE_FOLDER%`  and there is [very little placeholder replacement in `cleanCommand`](https://github.com/James-Yu/LaTeX-Workshop/blob/802fb4c8dcbb46d4ba72a3ea9f7a4e9f66825c19/src/components/cleaner.ts#L161), this is not possible.

***Would you be able to add support for placeholders in a `cleanCommand` ?***
**This might be as simple as running `replaceArgumentPlaceholders` on `latex-workshop.latex.clean.args`.**

```json
{
    "latex-workshop.latex.outDir": "%WORKSPACE_FOLDER%/out/%RELATIVE_DIR%",
    "latex-workshop.latex.clean.method": "cleanCommand",
    "latex-workshop.latex.clean.command": "rm",
    "latex-workshop.latex.clean.args": [
        "-rf",
        "%WORKSPACE_FOLDER%/out"
    ]
}
```

### To Reproduce

1. Define a `cleanCommand` that refers to any placeholder (other than `%TEX%`).
2. Run the `cleanCommand` and observe that the placeholder is treated as a literal file/directory name.

### Expected behavior

I would like placeholders to be replaced with their values.

## Logs [Required]

Here are the logs showing that the placeholder was not replaced.

```log
[13:45:15] CLEAN command invoked.
[13:45:15] Current workspace folders: ["file:///home/dqal/documents/mol/problem_sets"]
[13:45:15] Found root file from active editor: /home/dqal/documents/mol/problem_sets/example_course_2/problem_set_1/example_document.tex
[13:45:15] Keep using the same root file: /home/dqal/documents/mol/problem_sets/example_course_2/problem_set_1/example_document.tex
[13:45:15] Clean temporary files command: rm
[13:45:15] Clean temporary files command args: ["-rf","%WORKSPACE_FOLDER%/out"]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 11
 - VS Code version: 1.71.0
 - Extension version: 8.29.0
 - TeX distribution version: TeX Live 2022/dev/Debian

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
I've check the use case and figure that allowing all placeholders in the clean command argument does no harm.
