### ISSUE TITLE
Latex Outline with multiple \input files.

### ISSUE THREAD

**Issue by TiemenSch** [James-Yu/LaTeX-Workshop#346]
Currently, the LaTeX outline is empty when you use a masterfile and several inputs. References work like a charm across the different input files (that BibTex intellisense <3), but the outline remains empty. It would be great if it would populate based on all the inputs. 

Perhaps only updated after a build if it would otherwise ruin performance?

It was already mentioned in #332, but that was raised for a different reason (CMD+click on file capabilities). 

Thanks for the great plugin! I ditched TeXstudio and TeXlipse right away 🥇

**Comment by innerlee** [comment]
outline works for one master file and several inputs. It might not work well for multiple master files. Could you provide some reproduce files?

**Comment by James-Yu** [comment]
Please provide a minimal working (or rather breaking) example for debug. Thanks.

**Comment by TiemenSch** [comment]
document.tex:
```latex
\documentclass{article}
\begin{document}
\section{Test}
    \input{test}
\end{document}
```

test.tex:
```latex
\section{Stuff}
```

Previously, for me the outline wouldn't even populate. Just now, it sometimes populates, but it takes ages to do so.

On what files is the outline based?

**Comment by James-Yu** [comment]
Interesting. If you remove the spaces before `\input`, everything is fine. Looking for the bugged line now.

**Comment by TiemenSch** [comment]
Many thanks for the fix! Clever to notice it could be the spacing.

**Comment by TiemenSch** [comment]
This seems to be broken again!
