### ISSUE TITLE
Fair well

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#3469]
@jlelong since @James-Yu has revoked my collaborator, I stop contributing to the extension. Thank you for your collaboration. @James-Yu, thank you giving me a great chance to contribute to the great extension.

I will hack my fork at my repository for my own interest. If you want to cherry pick commits, never mind doing it.

**Comment by jlelong** [comment]
@tamuratak thanks for everything I have learned by your side.
