### ISSUE TITLE
feature request/question regarding chktex linter

### ISSUE THREAD

**Issue by daviehh** [James-Yu/LaTeX-Workshop#347]
Coming from sublime text, one feature I really like is the ability to ignore some warnings given by the linter, e.g. see the "Settings" section for the sublime text linter [here](https://github.com/SublimeLinter/SublimeLinter-chktex). Is there some user setting to ignore given warning number given by chktex such as "Warning 22 (Comment displayed)" or "Warning 46 (Use \( ... \) instead of $ ... $)"? If not implemented, one nice way is to follow the sublime text's linter setting where there is an array in the setting e.g. `"ignore":[22,46]` so that the warning numbers are ignored.
Thanks a lot!

**Comment by innerlee** [comment]
put [this file](https://github.com/innerlee/chktexrc/blob/master/.chktexrc#L178) in your project root folder. you can ignore warn 22 by add `-n 22` to the `CmdLine` section

**Comment by James-Yu** [comment]
You can edit this config
```
"latex-workshop.chktex.args.active": [
    "-wall",
    "-n22",
    "-n30",
    "-e16",
    "-q"
  ]
```
to exclude your warnings.
