### ISSUE TITLE
Add custom shell config option to use for builds

### ISSUE THREAD

**Issue by xubuntutux** [James-Yu/LaTeX-Workshop#3470]
Invoking a build command launches a child process with `cp.spawn()` [builder.ts#L273](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/builder.ts#L273) or [builder.ts#L282](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/builder.ts#L282).  On *NIX, this is always `/bin/sh` per [node.js docs](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options).  It is desirable to allow the user to specify an alternative shell via a setting available in `settings.json` to use instead of the default.

**Comment by James-Yu** [comment]
Can you please provide a comprehensive use case on the necessity of defining shell? Thanks.

**Comment by xubuntutux** [comment]
The TeX Live installation, including a corporate provided texmf tree, exists inside a Singularity container.  Both the TeX Live build commands and Singularity tools are loaded via [Lmod](https://github.com/TACC/Lmod).  Thus, the build process normally goes this like:

```sh
module load singularity
module load texlive
# At this point, latexmk and company are available from the command prompt;
# however, latexmk first calls `singularity exec <sif image>`
# where singularity is also defined by the Lmod module

# Build commands executed via LaTeX-Workshop
latexmk <%DOC%>
```

A normal shell invoked with `/bin/sh -c` as is done by Node.js will not allow proper loading of the Lmod modules.  Thus, there is a need to specify an alternate shell by which preloading the modules can be achieved.

**Comment by jlelong** [comment]
What about using [external build command](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#external-build-command). You could launch the correct shell inside your script.

Btw, I think the right solution is to load the modules prior to launching vscode such that any sub-shell spawned from inside vscode would inherit the correct paths.

**Comment by xubuntutux** [comment]
Yes, an external build command could work for one of the builds, but we have several types for a single project depending on whether we need extra/alternate flags passed to `latexmk`, as well as whether we clean (`latexmk -C`) prior to building or not.  Thus, we have a need for several recipes.

I should have mentioned that we are building on a remote machine with the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension.  With this configuration, it is possible to get a custom shell with the modules preloaded via [profile configurations](https://code.visualstudio.com/docs/terminal/profiles#_configuring-profiles), or even a custom debug environment with the [task/debug configurations](https://code.visualstudio.com/docs/terminal/profiles#_configuring-the-taskdebug-profile).   However, Node.js seems to only spawn a plain vanilla shell without inheriting the parent environment.

**Comment by James-Yu** [comment]
@xubuntutux can you please try out the branch `custom-shell` and see if the new config item fits your need?

[latex-workshop-8.29.0.vsix.zip](https://github.com/James-Yu/LaTeX-Workshop/files/9559638/latex-workshop-8.29.0.vsix.zip)

**Comment by xubuntutux** [comment]
It works beautifully!  Thank you!

**Comment by James-Yu** [comment]
@xubuntutux Unfortunately the above change may create notable security holes in shell command execution. We may need to figure out a better solution.

**Comment by xubuntutux** [comment]
Thank you for considering the possibility.  I understand the security risks make it not practical.

Is there a way to pass along the environment from one `spawn()` to the next?  For example, I can `module load` in one `latex-workshop.latex.tools` and have the subsequent tools inherit the resulting environment.  I note that when I say 'environment' I mean aliases as well as environment variables since the modules will set specific aliases.
