### ISSUE TITLE
Highlight tabulararray redefined amsmath environments

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3485]
> With `\UseTblrLibrary{amsmath}` in the preamble of the document, `tabularray` will load `amsmath` package, and define `+array`, `+matrix`, `+bmatrix`, `+Bmatrix`, `+pmatrix`, `+vmatrix`, `+Vmatrix` and `+cases` environments. Each of the environments is similar to the environment without + prefix in its name, but has default rowsep=2pt just as tblr environment. Every environment except +array accepts an optional argument, where you can write inner specifications.

This is another issue besides #2851, relating to `tabularray` package

You can see that, after adding the `+` the highlight is wrong:

![Screenshot_20220918_235436](https://user-images.githubusercontent.com/65082432/190916191-d348f80a-a8d6-406c-9349-12e7de1baf27.png)

I used to think all `\begin` and `\end` pairs will be highlighted?

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#37

**Comment by Firestar-Reimu** [comment]
https://github.com/jlelong/vscode-latex-basics/issues/37 is solved, but the auto-completion of `+cases`, `+matrix`, etc. is still without +

![Screenshot_20221108_110923](https://user-images.githubusercontent.com/65082432/200465857-35776a91-75e5-48ee-ac9e-8d758aec4057.png)

**Comment by jlelong** [comment]
Please, could you open a new issue?

**Comment by jlelong** [comment]
You can use the command `\beginend` to insert environments starting with a `+` instead of relying on the autocompletion of the `\end` instruction based on what you enter in `\begin`.
