### ISSUE TITLE
PDF viewer page frames do not follow the pageColorsForeground setting

### ISSUE THREAD

**Issue by stepelu** [James-Yu/LaTeX-Workshop#3487]
## Describe the bug

When setting custom colors for PDF rendering the PDF viewer page (and trimming) frames are not changed accordingly.

For example, setting the following options in `settings.json`:
```
  "latex-workshop.view.pdf.color.dark.backgroundColor": "#282c34",
  "latex-workshop.view.pdf.color.dark.pageColorsBackground": "#282c34",
  "latex-workshop.view.pdf.color.dark.pageColorsForeground": "#abb2bf",
```
produces the following result (this with 10% trimming, without trimming the white vertical frames disappear):

<img width="838" alt="image" src="https://user-images.githubusercontent.com/6617696/192128315-fd19d618-e40c-4ff5-b1dc-4eb97e58b884.png">

This is not an issue when using inversion, the following image is produced with `"latex-workshop.view.pdf.invert": 0.85`

<img width="851" alt="image" src="https://user-images.githubusercontent.com/6617696/192128368-02c0c4bc-0819-4070-866e-ae28eabf7772.png">

### To Reproduce

Use the settings above in `settings.json` and view a PDF.

### Expected behavior

It would be great if `"latex-workshop.view.pdf.color.dark.pageColorsForeground"` (or a dimmed version of it) were used for the page frames, which otherwise really stand out visually.

## Desktop

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: OSX 12.6
 - VS Code version: Version: 1.71.2 (Universal)
 - Extension version: v8.29.0
 - TeX distribution version: brew installed texlive 2022

**Comment by James-Yu** [comment]
Can you please have a try on #3488? Thanks. You may change the extension of the following file from `zip` to `vsix` to install it.

[latex-workshop-8.29.0.zip](https://github.com/James-Yu/LaTeX-Workshop/files/9640322/latex-workshop-8.29.0.zip)

**Comment by stepelu** [comment]
I renamed the `zip` to `vsix` and installed via `code --install-extension latex-workshop-8.29.0.vsix`:
```
Installing extensions...
(node:93601) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'latex-workshop-8.29.0.vsix' was successfully installed.
```
However the `"latex-workshop.view.pdf.color.dark.pageBorderColor"` setting is grayed out and seems not to have an effect.
I tried the obvious candidates (install while vscode is closed, reload, ecc ecc), any idea on what could be going wrong?
