### ISSUE TITLE
Checking duplicate bib entries

### ISSUE THREAD

**Issue by xiaoxstz** [James-Yu/LaTeX-Workshop#3491]
Does this plugin have the function of checking duplicate bib entries?

When there are many duplicate bib entries, only the used ones can be checked out.

**Comment by xiaoxstz** [comment]
OK, I found a solution.

We can use [bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy) to tidy our bib entries and remove the duplicates, by the way.

It's open-source at [GitHub repository](https://github.com/FlamingTempura/bibtex-tidy.

**Comment by xiaoxstz** [comment]
I hope the function `bibtex-tidy` could be embedded into this plugin.

It's simple with `bibtex-tidy`.

````bash
npm install -g bibtex-tidy   % install
bibtex-tidy references.bib  % usage
````

**Comment by James-Yu** [comment]
There are three commands.
- `latex-workshop.bibsort` 
- `latex-workshop.bibalign`
- `latex-workshop.bibalignsort`

**Comment by xiaoxstz** [comment]
But I just want to tidy it up and remove the duplicates. Besides,`bibsort`,`bibalign`,`bibalignsort` cannot remove the duplicates by the way.

**Comment by xiaoxstz** [comment]
> There are three commands.
> 
> * `latex-workshop.bibsort`
> * `latex-workshop.bibalign`
> * `latex-workshop.bibalignsort`

But I just want to tidy it up and remove the duplicates. Besides,bibsort,bibalign,bibalignsort cannot remove the duplicates by the way.

**Comment by xiaoxstz** [comment]
> I hope the function `bibtex-tidy` could be embedded into this plugin.
> 
> It's simple with `bibtex-tidy`.
> 
> ```shell
> npm install -g bibtex-tidy   % install
> bibtex-tidy references.bib  % usage
> ```

I found two perfect solution to use `bibtex-tidy` in VS Code. 

## Solution 1
Just install the plugin `Command Runner` and add the configuration below to `keybinding.json`. Then, you can just press F6 to tidy your bib files(Open the .bib file, and then press F6).

```json
{
    "key": "F6",
    "command": "command-runner.run",
    "args": { "command": "bibtex-tidy ${file} --quiet" },
    "when": "resourceExtname == .bib",
},
```

## Solution 2
If you prefer clicking with  the mouse, you can use the plugin `Run Terminal Command` instead.

Just install the plugin `Run Terminal Command` and add the configuration below to `setting.json`. 

```json
"runTerminalCommand.commands": [
    {
        "command": "bibtex-tidy {resource} --quiet",
        "name": "bibtex-tidy",
        "auto": true,
    },
],
```

Then, you can use it. Just select the .bib file, click the mouse right button, click `Run Terminal Command`. Then select the `bibtex-tidy` command.
