### ISSUE TITLE
Open Pdf on build

### ISSUE THREAD

**Issue by AshtonSBradley** [James-Yu/LaTeX-Workshop#3492]
A simple request: is there a way to make the pdf open on build by default? 

When I latex the project the first time, I always have to fish around in the menu to open the pdf.

I can't see how to get past this. I just want the default to be: open the pdf on build, even on the first time.

**Comment by James-Yu** [comment]
No need to fish around. There is an icon top right of the tex editor.

**Comment by AshtonSBradley** [comment]
oh! thank you, how did I not know that
