### ISSUE TITLE
Preview internal links in PDFs on mouse hover.

### ISSUE THREAD

**Issue by FMuro** [James-Yu/LaTeX-Workshop#3495]
I think this could be a nice feature to have in the internal PDF viewer of this extension.

It is implemented in here:

https://github.com/belinghy/PDFRefPreview

![demo](https://user-images.githubusercontent.com/17141976/193476332-b493ffd0-7a3b-4f2f-8339-8e71405844c1.gif)

**Comment by James-Yu** [comment]
I’m not sure it is an easy integration. Will look into it later.

**Comment by James-Yu** [comment]
Thanks for the feature request. I have implemented a prototype, yet to find out that the hack used cannot respond to size changes made to the pdf viewer. This is not an easy task to be resolved on my effort, so I'd close this feature request for now and see if the community may contribute.
