### ISSUE TITLE
Auto-completion of the inline formula

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3496]
Auto-completion of the inline formula `\[\]` (the formula is on a line by itself), in `~/.vscode/extensions/james-yu.latex-workshop-(version_number)/data/commands.json` find `"command": "["` paragraph (i.e. `"display math"`), change the value of "snippet" to:

`"[\n\t${1}\n\\]"`

so as to match the auto-formatting of latex-workshop

PS: PDFjs by mozilla has updated to 2.16

**Comment by James-Yu** [comment]
I don’t understand.
