### ISSUE TITLE
knitr support 

### ISSUE THREAD

**Issue by davidaarmstrong** [James-Yu/LaTeX-Workshop#350]
I was wondering if it is possible to specify a knitr toolchain for .Rnw documents.  In Atom, I would have a special .latexcfg file that looks as follows: 

  {
  "toolchain": "Rscript -e \"library(knitr); knit('%DOC.Rnw')\" && latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf %DOC"
  }

Can I do that in VS Code, too?  If so, is it possible to specify a global toolchain for .Rnw documents that is different from the global toolchain for .tex documents? 

Thanks, 
Dave.

**Comment by James-Yu** [comment]
Yes, it's possible to run `rscript` using the extension. However it is not possible to specify a global toolchain for such documents. Considering that there are numerous variants of latex with different file extensions, enumerating them seems to be cumbersome.
