### ISSUE TITLE
Latex structure view in vscode not showing for rnw files

### ISSUE THREAD

**Issue by EdoardoCostantini** [James-Yu/LaTeX-Workshop#3503]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

Not related to compiling.

## Is your requested feature related to a problem? Please describe. [Required]

The VScode latex-workshop extension has a helpful latex structure outline. However, this only works for .tex files and not for .rnw.

## To Reproduce  [Required]

1. Open any Rnw with the structure defined by the usual section names of the LaTeX outline hierarchy.
2. Go to 'structure view'
3. See error

## Describe the solution you'd like  [Required]

I would like to see the same structure view when I open a .rwn file as when I open a .tex file.

## Logs [Required]

No log.

### LaTeX Workshop Output [Required]

No output.

## Screenshots

This is what I see with a tex file in the structure view

![Screenshot 2022-10-11 at 11 07 15](https://user-images.githubusercontent.com/38205413/195048083-036f3964-2a69-41de-9c92-acc8f749da8f.png)

When I focus on a .rnw file the structure view is empty or shows the structure of the previous .tex file I opened.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: [macOS Monterey 12.6]
 - VS Code version: [1.71.2 (Universal)]
 - Extension version: [v8.29.0]
 - TeX distribution version: [TeX 3.141592653 (TeX Live 2021)]

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
Can you please provide an `rnw` file for test?

**Comment by EdoardoCostantini** [comment]
I apologise. While creating a trial document for the test, I realized that the problem is different from what I originally described. I am able to see the structure of an .Rnw document. My problem is due to the structure I'm using. I'm working with a `main.tex` file that includes `.tex` files that are created by knitting `.Rnw` files. The structure of the `main.tex` file is correctly picked up by LaTeX-Workshop, but then when I work on the `.Rnw` files the structure is not visible anymore. And because of the specific set up I'm using, the structure that is picked up is that of the `.tex` files, not that of the `.Rnws`. I think this is a peculiarity of my workflow and that it is not really something that LaTeX-Workshop can solve.
