### ISSUE TITLE
Highlight math mode text differently

### ISSUE THREAD

**Issue by Darylgolden** [James-Yu/LaTeX-Workshop#3505]
## Preliminary questions [Required]
not relevant
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes/No

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No

## Is your requested feature  related to a problem? Please describe. [Required]

I frequently miss typing dollar signs in the correct places and run into compilation errors. Since LaTeX workshop does not highlight text within math mode differently, it's often quite tedious to find where exactly the dollar signs are missed. 

## To Reproduce  [Required]

Steps to reproduce the behavior: not relevant
3. See error

## Describe the solution you'd like  [Required]

I feel like highlighting text within dollar signs can help with finding these errors much more efficiently.

## Logs [Required]

not relevant

### LaTeX Workshop Output [Required]
not relevant

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]
not relevant

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

not relevant

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by James-Yu** [comment]
The extension highlights math mode. If it does not work on your side, please post screenshots and working examples.
