### ISSUE TITLE
Copy links embedded in PDFs in previewer

### ISSUE THREAD

**Issue by ghillb** [James-Yu/LaTeX-Workshop#3506]
Currently it is not possible to open links in PDFs opened in the previewer (feature was removed, https://github.com/James-Yu/LaTeX-Workshop/issues/3242). 

This can lead to annoying situations, where the user has to open the PDFs in another viewer just to open the link.

A possibility to copy links (e.g. via right-click context menu) would be very useful.

**Comment by James-Yu** [comment]
Resolved in aacd21b.
