### ISSUE TITLE
Adding some more bracket pairs to latex-language-configuration.json

### ISSUE THREAD

**Issue by longisland-icetea** [James-Yu/LaTeX-Workshop#3511]
When Bracket Pair Colorization is enabled, write \(\left. something \right|\) in a tex file (although it's not frequently used), \left. will be the right color but \right| will be red. And all the bracket pair's color in the below will change (to the color of the next level).

![image](https://user-images.githubusercontent.com/20827609/196964579-12f7cbf0-0bae-4002-810a-ec0903e12fbe.png)

I have seen several similar issues such as https://github.com/microsoft/vscode/issues/137774#issue-1061945380 and it seems more convinient to simply add these barcket pair config to the latex-language-configuration.json file in the extension project.

`["\\left|", "\\right."],
["\\left.", "\\right|"],
`

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), can you fill your issue against that repo?

**Comment by longisland-icetea** [comment]
It seems that the 9.0.1 version in vscode market is not the same as the github version.

![image](https://user-images.githubusercontent.com/20827609/201314882-ecc5cfb1-7514-4f5c-9c17-29072cf2fbd3.png)

(It's not that important and I just write here to inform you.)

**Comment by jlelong** [comment]
This is normal because I updated these definitions yesterday in f8a8257f. These changes will be included in the next release.
