### ISSUE TITLE
“Terminate current compliation" button on the upper right corner, beside the green triangle "Build LaTeX project"

### ISSUE THREAD

**Issue by LiRMNG** [James-Yu/LaTeX-Workshop#3516]
Sometimes, especially when the TeX file contains thousands of lines, the auto-built LaTeX file (on Ctrl+S) might be ill-formed.  This makes the building extremely long.  So, is it better to place  the "Terminate current cpmpliation" next to the GREEN TRIANGE on the upper right corner? I think **_a mechanism for forced rebuilding must be very helpful._**

**Comment by James-Yu** [comment]
You can always use the kill command to do so. Padding too many buttons top might not be an elegant solution.

**Comment by LiRMNG** [comment]
Or can we just let green triangle terminate an existing compliation (if there is any) first and then start a new one? Anyway, most people don't have to run two or more latex's simultaneously. Most important of all, a lot of users cannot figure it out if the compliation got stuck.  They just cannot see their PDFs, and they will notice the "Build" on the lower left corner.  In this case, if pressessing the green triangle makes the PDF shown, it would be very great.

**Comment by James-Yu** [comment]
It’s not possible and counterintuitive. The button is bound to the build command, which also invokes upon save. Imagine someone saved the project, wait for few second, save again, wait for few second, did so and repeat.
