### ISSUE TITLE
Free double cursor after tab-typing \begin{xx} \end{xx}

### ISSUE THREAD

**Issue by daguiam** [James-Yu/LaTeX-Workshop#352]
### Description

When we type `\begin{ }` using the tab to complete with `\end{ }` we get a double cursor that allows us to type simultaneously inside both `{ }` at the same time.
However, after typing `equation` for example, the double cursor remains there and is not freed. 
I do not know of the correct shortcut to stop the double cursor typing except clicking somewhere in the document.

### How to reproduce

1. Type `\begi`+`tab`
2. Type `equation` in between the `{ }`
3. Move cursor with arrow keys
4. The double cursors remain there

Notice how the double cursor typing is still there despite you moving anywhere in the document.

### Expected behaviour

It would be better that after you type the `equation` inside the `{ }`, the double cursor would be freed and back to single cursor typing.

### Actual behavior

It types in two lines simultaneously

**Comment by James-Yu** [comment]
This is a fixed behavior of vscode. You may press ESC to free it.
