### ISSUE TITLE
Set environment variable BIBINPUTS and TEXINPUTS

### ISSUE THREAD

**Issue by stefanpricopie** [James-Yu/LaTeX-Workshop#3521]
Hello.

The compilation of the main.tex file works, but it outputs this at the end. I believe it has to do with my `.bib` files being stored in a `bib` folder, while the input `.tex` files are in `chapters` folders. My output directory is `'%DIR%/.tmp'`

```
Rc files read:
  ./.latexmkrc
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Set environment variable BIBINPUTS='path/to/folder/.tmp:'
Set environment variable TEXINPUTS='path/to/folder/.tmp:'
Latexmk: All targets (path/to/folder/.tmp/main.pdf) are up-to-date
```

Any help with this would be greatly appreciated.

System Version: macOS 12.6 (21G115)
VSCode: Version: 1.73.0 (Universal)
LaTeX Workshop: v8.29.0

**Comment by James-Yu** [comment]
Not related to the extension. Most likely your latexmk setting.

**Comment by stefanpricopie** [comment]
Upgrading to MacTex 2022 solved it
