### ISSUE TITLE
`@(` overwrites the selected text

### ISSUE THREAD

**Issue by peiranxiao** [James-Yu/LaTeX-Workshop#3533]
I realize that `@(` now overwrites the selected text. For example, if I want to add a pair of brackets `$\left(  \right)` to `$a+\frac{a}{b} c$`, selecting `a+\frac{a}{b}` and then typing `@(` gives me `$\left(  \right) c$` instead of `$\left( a+\frac{a}{b} \right) c$`.  If I remember correctly, the previous version handled this properly (otherwise, this will be a feature request). 
 
 - VS Code version: 1.73.0
 - Extension version: 9.0.1

**Comment by James-Yu** [comment]
#3531
