### ISSUE TITLE
Color decorations of document structure

### ISSUE THREAD

**Issue by xuestrange** [James-Yu/LaTeX-Workshop#3534]
Thw structure view of long latex document is very helpful. However, if we can draw different colors to different levels of sections, it would be more clear. Th picture below which contains a lot of table and relative labels seems messy to view. Two options are diabling `show labels in structure` and drawing colors to different levels of sections, both can make it clear.
![](https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/202211091453533.png)

**Comment by James-Yu** [comment]
It’s not possible to color tree items. A vscode limitation afaik.

**Comment by jlelong** [comment]
See also 
- [`latex-workshop.view.outline.commands`](https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#latex-workshopviewoutlinecommands)
- [`latex-workshop.view.outline.floats.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#latex-workshopviewoutlinefloatsenabled)

to tune what you want to be shown in the structure pane.

**Comment by xuestrange** [comment]
> See also
> 
> * [`latex-workshop.view.outline.commands`](https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#latex-workshopviewoutlinecommands)
> * [`latex-workshop.view.outline.floats.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#latex-workshopviewoutlinefloatsenabled)
> 
> to tune what you want to be shown in the structure pane.

Thanks
