### ISSUE TITLE
auto-completion of tabulararray redifined environments

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3537]
auto-completion of `+cases`, `+matrix`, etc. is still without +

![Screenshot_20221108_110923](https://user-images.githubusercontent.com/65082432/200465857-35776a91-75e5-48ee-ac9e-8d758aec4057.png)

`+array, +matrix, +bmatrix, +Bmatrix, +pmatrix, +vmatrix, +Vmatrix, +cases`

this is easy to fix editing the `/data/environments.json`

**Comment by jlelong** [comment]
I am not convinced this is a good idea to add these environments to the list of default environments. A better approach is to create a `tabularray.cwl` in https://github.com/jlelong/LaTeX-cwl/ containing the list of commands and environments provided by the `tabularray` package.

We also need the check LW's completion provider to make sure `+` is allowed as part of an environment name. I am pretty sure, we have restricted environment names to `[a-zA-Z]\*?` so far.
