### ISSUE TITLE
Asymptote Diagrams Not Loading

### ISSUE THREAD

**Issue by circosine** [James-Yu/LaTeX-Workshop#354]
After installing texlive-full along with the asymptote package, any asymptote code still will not render in the preview mode. The /end{asy} will also show the following error: [LaTeX]: file "file-#.tex" not found. However, I think the program is mistaken because it automatically creates .asy files but the program is looking for a .tex file.

This issue can be reproduced fairly simply.
1. Use default settings on VSCode and the plugin itself.
2. Import latex code containing asymptote language and important the asymptote package in the header.
3. Render and one can notice that the code is not rendering.

The code is suppose to render an asymptote diagram, but in reality there is just a bit of extra space.

The only error message shown is the following: "[LaTeX]: file "file-#.tex" not found."

I believe this is caused because the problem is looking for .asy files but its set to find .tex files.

Please fix these issues ASAP. This has been a great inconvenience but I'm still loving the rest of this extension. Keep up the great work!

**Comment by James-Yu** [comment]
TBH I'm totally confused by your descriptions. Can you please pose full extension log? It can be accessed from the all action menu.

**Comment by sivapvarma** [comment]
You need to put the following into your `.latexmkrc` in your homefolder to make sure latexmk know what to do with `asy` blocks in your latex code.

```
sub asy {return system("asy '$_[0]'");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
```

After this you should be able to build your latex project as it is.
