### ISSUE TITLE
Quick copy equation by it's number.

### ISSUE THREAD

**Issue by tomasrei** [James-Yu/LaTeX-Workshop#3543]
I have used Latex Workshop only for a few weeks, I think it is a really great experience. There is one thing, however, that I think would be a major improvement to my and probably many others' workflow.  

When working on a document with many equations (my current project has 80+ equations on 11 pages), finding the one equation you want by looking at the code can be difficult/frustrating. Searching for a specific equation on the pdf preview is of course much faster, and more pleasant as well. Let's say I want to re-use, say, equation 28 in my 11-page pdf. 

Wouldn't it be great if I can use some simple shortcut, say ctrl+alt+28, and Latex Workshop would fetch that equation and paste it wherever the cursor is? This would also save time so that you don't need to open that particular .tex file that contains equation 28.

/Tom

**Comment by James-Yu** [comment]
That's theoretically possible, but very hard to implement and highly error-prone. I'd recommend you to use reverse synctex to locate the code from anything on a PDF by ctrl/cmd+click.
