### ISSUE TITLE
Option for external links to open in browser

### ISSUE THREAD

**Issue by edemaine** [James-Yu/LaTeX-Workshop#3550]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: n/a

## Is your requested feature  related to a problem? Please describe. [Required]

When I click (or perhaps ctrl-click) on a link in the PDF viewer, I expect it to open in my default browser.  This is what happens when I ctrl-click on a link in the LaTeX source.

Instead the link gets copied to the clipboard, and I get this message:

https://github.com/James-Yu/LaTeX-Workshop/blob/72ea328ab760cd5fa986102b8953830b4c132f90/src/components/viewer.ts#L264

This change was made because of a security vulnerability; see #2931 and [snyk.io](https://snyk.io/blog/visual-studio-code-extension-security-vulnerabilities-deep-dive/). But it's still a little inconvenient.

## To Reproduce  [Required]

1. Open a PDF file with a 
2. Click on the link
3. See message

## Describe the solution you'd like  [Required]

Perhaps it's possible to avoid the security vulnerability for the websocket to be verified via a shared secret between the plugin and the viewer? Or a shared pipe with no external visibility? I'd be willing to look into implementing this if I could get some direction on whether you think one of these approaches (or another) is feasible.

## Screenshots

![image](https://user-images.githubusercontent.com/2218736/203180184-7aee036f-cb01-4ece-b046-453efd8f6462.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 11
 - VS Code version: 1.73.1
 - Extension version: 9.0.1
 - TeX distribution version: Cygwin TeXLive 

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
I personally am not convinced with a sophisticated solution for the bit of ease. The proposed implementation may notable increase the burden of maintain in the future.

Another solution is to only open http/https directly, and copy to clipboard for any other uri scheme.

**Comment by edemaine** [comment]
Only opening http/https protocols sounds like a reasonable option to me!
