### ISSUE TITLE
Inline math brackets auto-surround  stopped

### ISSUE THREAD

**Issue by bogdanbacila** [James-Yu/LaTeX-Workshop#3554]
### Discussed in https://github.com/James-Yu/LaTeX-Workshop/discussions/3553

<div type='discussions-op-text'>

<sup>Originally posted by **bogdanbacila** November 23, 2022</sup>
I was constantly using the auto-surrounding feature of a selected piece of text to add the "\(" and "\)" brackets around it. This stopped working a few weeks ago and I am not sure if it was after a latex-workshop update or after a vscode update. I don't have the time now to file a proper bug request and play around with the settings as I'm rather busy writing a thesis. This feature was saving me a lot of time but it is now not working anymore, unfortunately. Could you please advise on what might have happened or a clear way to get it back working again? It would be much appreciated! 

Best,
Bogdan </div>

**Comment by James-Yu** [comment]
It's not likely an extension issue. You may consider downgrade vscode or the extension to see if issue resolved.
