### ISSUE TITLE
Formatter: Word wrap

### ISSUE THREAD

**Issue by LasseRosenow** [James-Yu/LaTeX-Workshop#3557]
Add option to add a max line length for the latex formatter.
This would allow to automatically wrap the words to fit this max line length on save.

This would be very helpful to make latex files more readable in general and not only in IDEs that use the vscode word wrap setting.

Many programming language integrations would have this functionality and I am really missing this in latex :o

**Comment by James-Yu** [comment]
We don’t have a plan to implement this function.

**Comment by LasseRosenow** [comment]
@James-Yu Thank you for this quick reply, but could I ask what is the reasoning for your decision not to consider implementing this?

**Comment by jlelong** [comment]
LaTex-Workshop delegates formatting to `latexindent`, which already offers the ability to hard wrap line. See https://latexindentpl.readthedocs.io/en/latest/sec-the-m-switch.html
