### ISSUE TITLE
Feature request: add description section to `latex-workshop.intellisense.atSuggestionJSON.replace`

### ISSUE THREAD

**Issue by tapyu** [James-Yu/LaTeX-Workshop#3558]
I think it is not possible to add a description section in `latex-workshop.intellisense.atSuggestionJSON.replace`, as it is done in [`LaTeX-Workshop/data/at-suggestions.json`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/at-suggestions.json). It would be great being able to add it to the new `@` suggestions that is customized by the user.

**Comment by James-Yu** [comment]
It is possible, yet the change will invalidate current settings of `intellisense.atSuggestionJSON.replace` and everyone who used this feature need to change their configurations. I am a bit hesitated on this.

**Comment by tapyu** [comment]
@James-Yu And how can I do it?

**Comment by tapyu** [comment]
Trying to do as it is done in [LaTeX-Workshop/data/at-suggestions.json](https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/at-suggestions.json) leads to error

![image](https://user-images.githubusercontent.com/22801918/204097779-5ca1be6a-ff36-4c85-95b4-b757dc0f1f3a.png)

**Comment by James-Yu** [comment]
It’s currently not possible. Implementing the feature is possible but worrisome.

**Comment by tapyu** [comment]
I got it now... Well, I would increase the customizability, at least.

**Comment by jlelong** [comment]
> It is possible, yet the change will invalidate current settings of `intellisense.atSuggestionJSON.replace` and everyone who used this feature need to change their configurations. I am a bit hesitated on this.

I have the exact same concern and I am really not convinced the changes are worth it. Every entry of `intellisense.atSuggestionJSON.replace` would become a dictionary itself, which would make the editing inside the _Settings panel_  more delicate.

**Comment by James-Yu** [comment]
Just as @jlelong commented, the change may really cause unpredicted troubles. I will close this issue for now, but other possible implementing suggestions are welcomed!
