### ISSUE TITLE
Using shared files in `~/texmf` to build a project

### ISSUE THREAD

**Issue by sylv3r** [James-Yu/LaTeX-Workshop#356]
Maybe I missed something, but it seems you are not using the environment variables and tex system configuration. 
I have shared files in my `$TEXMFHOME` (the default one `~/texmf`) and I got a "File not found" error when using your extension to build my pdf, while everything is fine with my usual Makefile (I'm using `latexmk` under the hood).

Here's the related export env variables : 
```
export TEXINPUTS=~/textmf//:
export TTFONTS=~/textmf//:
export OPENTYPEFONTS=~/textmf//:
```

Maybe that's somewhere in your config, but I didn't find it.

**Comment by sylv3r** [comment]
Nevermind, I needed to add the "-i" flag in the `terminal.integrated.shellArgs.linux` option.

**Comment by sylv3r** [comment]
I'm sorry to reopen it, but I'm stuck. I can get everything to work within an integrated terminal, but when the build is triggered by your extension, it fails to find the files in my `~/texmf` folder. Even with the env variables set in the `.bashrc`, the workspace settings and the user settings of vscode. Plus the partial build messed up the intermediary files (the `.fls` and the `fdb_latexmk`) so I need to clean up everything before having a functional build again from my command line.

Any help would be appreciated, your extension is very useful and that sucks to have to go back to trigger the build manually again.

Thanks

**Comment by James-Yu** [comment]
I'm sorry but IMO this is not an extension related problem. It is related to how nodejs spawns bash. I would recommend you refer to the [document](https://nodejs.org/api/child_process.html) for details.
