### ISSUE TITLE
How to disable "go to definition"?

### ISSUE THREAD

**Issue by gaoqiangks** [James-Yu/LaTeX-Workshop#3560]
I know vscode  has a "go to definition" feature, which is very useful in other programming language. However, I never use it with latex language.   It will pop up a menu like "Could not find definition for \lambda" when I accidentally pressed the wrong key, which may occur more frequently in VIM mode.  Is there any way to disable this feature?

**Comment by James-Yu** [comment]
Correct me if I am wrong, but I don't think this is an extension-side issue. You may look for vscode configurations to see if you may disable the alert particular for languageID `latex`. I am not aware of such a config though.
