### ISSUE TITLE
bracket highlight is broken

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3564]
![Screenshot_20221130_153341](https://user-images.githubusercontent.com/65082432/204734867-ad0af55c-94c8-4eac-a2f6-aff1f6902a4d.png)

why is the last `}` being black?

vscode version:

```
1.73.1
6261075646f055b99068d3688932416f2346dd3b
2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.10-arch2-1
```

Latex workshop version: v9.0.1

**Comment by jlelong** [comment]
I cannot reproduce the issue.
