### ISSUE TITLE
Can't view pdf in new tab but in web page is all right

### ISSUE THREAD

**Issue by Claire-Jiaqi** [James-Yu/LaTeX-Workshop#357]
### I can't view pdf in new tab but I can view it in web page.Why?

I am on the latest version with mac os 10.13.2
Viewing in new tap don't work for me. It shows nothing in VSCode and opens about:blank in browser.

The log is:
[11:43:15] Found root file from active editor: /Users/jiaqi970602/Downloads/Paper.tex
[11:43:15] Root file remains unchanged from: /Users/jiaqi970602/Downloads/Paper.tex.
[11:43:15] No PDF viewer connected for /Users/jiaqi970602/Downloads/Paper.pdf
[11:43:15] Serving PDF file at http://127.0.0.1:58688/viewer.html?file=/pdf:%2FUsers%2Fjiaqi970602%2FDownloads%2FPaper.pdf
[11:43:15] Open PDF tab for /Users/jiaqi970602/Downloads/Paper.pdf

**Comment by James-Yu** [comment]
Can you please post screenshots of it? It would be weird if no new tab is created.

**Comment by Claire-Jiaqi** [comment]
Oh sorry I said something wrong. I can see the pdf in web browser but in new tab it is black.
<img width="1280" alt="2017-12-31 11 48 56" src="https://user-images.githubusercontent.com/23518139/34459120-fb0d4bae-ee20-11e7-8c71-51de84ad056e.png">

**Comment by James-Yu** [comment]
Are there anything abnormal in the developer's console? It's in the Help menu.

**Comment by Claire-Jiaqi** [comment]
<img width="972" alt="2018-01-02 16 15 56" src="https://user-images.githubusercontent.com/23518139/34477871-3fcc4d36-efd8-11e7-894a-d0429d2591ea.png">

**Comment by Claire-Jiaqi** [comment]
Is this one? Where should I check?

**Comment by James-Yu** [comment]
It's actually in the console tab but nvm. Can you please create a minimal working example for me to debug? It seems that I can't reproduce the problem.
