### ISSUE TITLE
Citations don't work using Workshop but they work using Overleaf

### ISSUE THREAD

**Issue by ymenzilcioglu** [James-Yu/LaTeX-Workshop#3575]
Hello,

I have been enjoying Latex-Workshop extension for VS Code; however I have encountered a bug that prohibited my work.

The same project recompiles when I upload it to Overleaf. My document was fine on Dec 5 around 10pm but stopped working the following day even though I didn't change anything. I attached my project zip with the .tex and .bib files.
[project_error.zip](https://github.com/James-Yu/LaTeX-Workshop/files/10180548/project_error.zip)

I also attached the screenshot of the error messages I'm seeing. I would greatly help your assistance.

Thanks,
Yagmur
<img width="1023" alt="Screen Shot 2022-12-07 at 17 35 18" src="https://user-images.githubusercontent.com/51761703/206311578-863674a0-147f-4f8c-8bcb-cb06b8c03e3b.png">

**Comment by James-Yu** [comment]
This is not related to the extension. You may want to read the logs to see what happened.
