### ISSUE TITLE
LaTex PDF view in code-server

### ISSUE THREAD

**Issue by qianchd** [James-Yu/LaTeX-Workshop#3577]
## Preliminary questions [Required]

Though as claim in the Wiki, code-server is not supported, I manage to run the [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) extension in a https webpage of code-server. It works just fine for editing, highlighting, generating PDF and so on. The only problem now is that the LaTex PDF view in code-server does not work since it calls the loaclhost address.

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

When one uses this extension in the code-server installed in a remote linux machine, with the https webpage open, the internal PDF viewer will call the local address of the local machine which makes it does not work properly. 

My personal solution now is to open an ssh forwarding session in the local machine to map the remote port to the local one, which is fine in PC but unstable in IPad or Android Pad. I wonder if there is any official support can deal with this issue.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS:  Windows 10, ubuntu latest, Android webpage.
 - VS Code version: latest
 - Extension version: latest
 - TeX distribution version: Tex Live latest

**Comment by James-Yu** [comment]
latest

**Comment by modaresimr** [comment]
in version 9.2.1 this problem still exists. would you please help?

**Comment by modaresimr** [comment]
Even with version 9.2.2 it has similar problem
