### ISSUE TITLE
Remove the indentation when auto-completing \begin{document}

### ISSUE THREAD

**Issue by 500InternalError** [James-Yu/LaTeX-Workshop#3578]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

LaTeX Workshop inserts indentation when auto-completing \begin{document}.

## To Reproduce  [Required]

1. Type `\document`
2. Press tab to autocomplete `\begin{document}`
3. There's indentation after `\begin{document}`

## Describe the solution you'd like  [Required]

There should be no indentation after `\begin{document}`.
Appending `"snippet": "\n$0"` after 
```
"document": {
    "name": "document"
```
in data/environments.json fixes this issue.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Screenshots

before modifying data/environments.json

![Kooha-2022-12-16-10-36-46](https://user-images.githubusercontent.com/39024699/208009384-673d5268-0faa-4794-8954-65af7c725033.gif)

after modifying data/environments.json

![Kooha-2022-12-16-10-37-48](https://user-images.githubusercontent.com/39024699/208009442-4c49bbe0-f484-41e6-bcd0-bad4020ce8b1.gif)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS:Arch Linux
 - VS Code version: 1.74.1
 - Extension version: 9.1.1
 - TeX distribution version: TeX Live 2022

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
@jlelong I tend to accept this suggestion as begin document is quite different from other envs imo. What do you think?

**Comment by jlelong** [comment]
The indentation rule defined for the LaTeX language is indeed not to increase indentation after `\begin{document}`

https://github.com/James-Yu/LaTeX-Workshop/blob/f8a8257f3fcbc02b4e26c255a68bb98b46f6a9f6/syntax/latex-language-configuration.json#L111-L114

I think the suggested change is good.

**Comment by jlelong** [comment]
Looking closely at the issue, the suggested change only solves the issue when the `document` environment is insert via the command `\begin{`. Using the command `\document` still increases indentation. This is because `latex-document.json` also defines a `document` environment.  

I think default commands and environments should not be overwritten by packages.
