### ISSUE TITLE
Syntax Highlighting for Asymptote files (.asy)

### ISSUE THREAD

**Issue by sivapvarma** [James-Yu/LaTeX-Workshop#358]
Currently  [Asymptote (`.asy`)](https://github.com/vectorgraphics/asymptote) files are treated as plain text.

![vscode-asy-plain](https://user-images.githubusercontent.com/1314675/34464435-655a4b4e-ee33-11e7-858a-ef41c02e15a2.png)

Here is the same file in TeXStudio

<img width="614" alt="texstudio-asy" src="https://user-images.githubusercontent.com/1314675/34464438-7bdf6d54-ee33-11e7-9d61-3a5f4cc26d86.png">

Since asymptote has C++ like syntax, changing language to C++ helps a bit (but this has to be done manually ?)

![vscode-asy](https://user-images.githubusercontent.com/1314675/34464443-ae2625e6-ee33-11e7-8def-0ceba7190afb.png)

It would be cool to have dedicated support for asymptote.

If you are on a mac, you install asymptote using tlmgr
```bash
sudo tlmgr install asymptote
```

**Comment by jlelong** [comment]
I find it a bit strange to implement asymptote syntax into this package. For instance, there is a [separate package](https://github.com/supakorn-ras/language-asymptote) for Atom.
If the asymptote language were implemented in an extension for vscode, what could be done is to highlight the `asy` environment using this style thanks to the embedding mechanism.

**Comment by jlelong** [comment]
Everything inside `\begin{asy}...\end{asy}` is recognized as Asymptote code. Note that to make it work, you first need to install the [Asymptote extension](https://marketplace.visualstudio.com/items?itemName=supakornras.asymptote).
