### ISSUE TITLE
Default environments are not available for completion as \envname

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3584]
The following code fails

https://github.com/James-Yu/LaTeX-Workshop/blob/770738afb477919ddc7d77d2bbd59e8919e0d7e8/src/providers/completer/command.ts#L67-L69

because `this.extension.completer` is not yet defined. See the message `Error reading data: TypeError: Cannot read properties of undefined (reading 'environment')` in the logs when starting the extension.

This error results in default environments to be unavailable for completion as `\envname`.

This is related to changes in https://github.com/James-Yu/LaTeX-Workshop/commit/136c797d19792f7571b90d4b896fc9f4286c22ae. The extension has become very powerful but at the expense of a quite sophisticated code. Unfortunately, its little test coverage forces us to very cautious when making changes and encourages small PRs that can be easily reviewed.

**Comment by James-Yu** [comment]
I absolutely agree. Need to force myself to write tests.
