### ISSUE TITLE
How to install from github repo

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3586]
I want to install from github git branch, but I do not find way to build in wiki. Can you give a guide? Thanks!

**Comment by James-Yu** [comment]
We have an npm script called release to build a vsix file. Use npm run release

**Comment by Firestar-Reimu** [comment]
Thanks! I found it in [CONTRIBUTING.md](https://github.com/James-Yu/LaTeX-Workshop/blob/aa2ff41c1aeca2fc1d5a2456d4ea3baf5ef5b2ff/CONTRIBUTING.md)

PS:
```
npm WARN deprecated vsce@2.14.0: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
```

**Comment by James-Yu** [comment]
Now you may download recent compiled artifacts from GitHub Actions.
