### ISSUE TITLE
Key input delay and suggestion loading failure

### ISSUE THREAD

**Issue by DrBro23** [James-Yu/LaTeX-Workshop#3601]
## Preliminary questions [Required]
Keyboard input delay and suggestion loading failure

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]
You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.
You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.
You can compile a TeX document manually?: Does not affect the problem

## Describe the bug [Required]
The key "enter" delays after input, for example if you hit "enter" 4 times, it will think about it 3s and then display it in tex file.
To use the suggestions for tex, they are loading very long and mostly only after triggering it by pressing ctrl+space.

Also vscode says that latex workshop is incompatible with vscode-pdf. 
This message was not displayed before either.

Tested on 3 Win11 machines, same issues.

### To Reproduce

Steps to reproduce the behavior key input:
(it is also doing it while normally writing text)
1. Go in a .tex file and write a text
2. Hit a couple of times "enter" 
3. highlight those entered lines 
4. clear them and hit one or two times "enter" again
5. then it is delaying the input of step 4

Steps to reproduce the behavior loading failure:
1. Go in a .tex file and write a text
2. Begin to use any predefined tex commands, like \begin{fig
4. normally you can choose a autocompletion but it is not loading anything or it takes a very long time

### Expected behavior
That it is running smoothly again, like last week (before christmas eve 2022).

### LaTeX Workshop Output [Required]
nothing to do with that, no compile errors

## Desktop [Required]

 - OS: Windows 11
 - VS Code version: 1.74.2
 - Extension version:  9.2.0
 - TeX distribution version: MiKTeX-pdfTeX 4.13 (MiKTeX 22.12)

**Comment by James-Yu** [comment]
Not reproducible on my side. Did you experience the same level of lag after successfully loading auto-completion for at least once? If so, something wrong with your disk (likely an HDD). If not, please paste the extension log.

As to the enter issue, very likely due to extremely slow disk reading speed. Unfortunately I still cannot reproduce on my side.
