### ISSUE TITLE
IntelliSense package data contains duplicate values

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#3612]
I found it out while checking the repository for the current data structure so that I could reuse my privately created IntelliSense data.

`"xpatch"` is duplicated.

https://github.com/James-Yu/LaTeX-Workshop/blob/2a91143ad48096e3e797cb83cf1e0b04dfcc3ee8/data/packages/biblatex.json#L10-L12

I was able to clone the repository and find similar problem of IntelliSense data with the following regex:

```regexp
(".+"),\n\s+\1
```

- `apacite.json`
- `babel.json`
- `biblatex.json`
- `bidi.json`
- `caption.json`
- `currfile.json`
- `hyperref.json`
- `listings.json`
- `mdframed.json`
- `minted.json`
- `pgfplots.json`
- `pst-eps.json`
- `siunitx.json`
- `subcaption.json`
- `subfig.json`
- `xepersian.json`

The regex matches consecutive identical values, but it seems that there are also non-consecutive identical values.

https://github.com/James-Yu/LaTeX-Workshop/blob/2a91143ad48096e3e797cb83cf1e0b04dfcc3ee8/data/packages/biblatex.json#L52-L57

I don't know if this problem affects performance or anything, but I think it should not be a duplicate.

**Comment by James-Yu** [comment]
It does not influence the performance for any bit. It’s related to optional cmd, which has not been implemented and has a relatively low priority.

**Comment by James-Yu** [comment]
Recorded in #3609
