### ISSUE TITLE
Citation Autocomplete (And Others) should be context aware

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#362]
Currently, when editing, replacing auto completed text doesn't properly understand (and replace in context).

For example, if one positions the cursor after the `:` in the example below:

`\ref{sec:}`

Deletes the `:` and types, you will get auto complete listings. If you select one, the result is:

`\ref{sec:sec:myselection}`

The desired result is:

`\ref{sec:myselection}`

**Comment by James-Yu** [comment]
This is a wierd behavior of vscode autocomplete. It seems not possible to have an extension-level workaround.
