### ISSUE TITLE
Support for .pnw files (LaTeX + Python)

### ISSUE THREAD

**Issue by B1ochem1st** [James-Yu/LaTeX-Workshop#3620]
With LaTeX-Workshop supporting both R and Julia code integration one more Weave option could be added bringing Python into the package. I would hope that with popularity of Python this functionality could prove to be a great and a welcomed addition. 

Users would need the [Pweave](https://mpastell.com/pweave/) package installed to their Python build  via `pip` or `conda`. Weaving a Pweave source file could be accomplished with `pweave -f tex dummy.pnw` for verbatim or `pweave -f texminted dummy.pnw` for minted code.

Pweave integration already works with only minimal additions to the current build of the package on my computer.  For this, preexisting code enabling .jnw/.rnw document support should be slightly altered and appended to the package.json, main.ts, manager.ts and builder.ts files. Definition of syntax highlighting could also be easily derived from other Weave syntax files. Similar to Sweave/Weave.jl code blocks starting with `<<[chunk options]>>=` and ending with `@` should be implemented. In addition, Pweave allows inline code with `<% %>` or `<%= %>`. I attach the language file used in my local alteration of the package [Pweave.tmLanguage.txt](https://github.com/James-Yu/LaTeX-Workshop/files/10343243/Pweave.tmLanguage.txt).

For the testing purposes [examples files](https://mpastell.com/pweave/examples/index.html) provided by the Pweave package could be used.

**Comment by jlelong** [comment]
Close by #3621
