### ISSUE TITLE
Theme aware background for PDF viewer

### ISSUE THREAD

**Issue by carlos-souto** [James-Yu/LaTeX-Workshop#3622]
This is a feature request.

Is it possible to change the background color of the built-in PDF viewer:

For example, from:

![image](https://user-images.githubusercontent.com/83190503/210679373-83cf63e2-e25c-4e74-96aa-ff2958dcc469.png)

To:

![Untitled](https://user-images.githubusercontent.com/83190503/210679489-39d8c7c3-3131-4b0b-bc72-347a6541acaa.png)

**Comment by James-Yu** [comment]
You have a variety of configurations to refer to:
- `latex-workshop.view.pdf.color.light.pageColorsForeground`
- `latex-workshop.view.pdf.color.light.pageColorsBackground`
- `latex-workshop.view.pdf.color.light.backgroundColor`
- latex-workshop.view.pdf.color.light.pageBorderColor`

You may also want to play with `latex-workshop.view.pdf.invert`.

**Comment by carlos-souto** [comment]
It would, however, be nice if the `backgroundColor` would automatically update based on the current theme.

**Comment by James-Yu** [comment]
Unfortunately, no. It seems that extension cannot get theme color code, therefore don’t know what the current background color is.
