### ISSUE TITLE
Ability to pop-out the PDF preview to another window

### ISSUE THREAD

**Issue by suhailrehman** [James-Yu/LaTeX-Workshop#3624]
It would be great if the PDF preview can be popped-out into another window so that it can be moved to another screen. I know that I can always open the PDF in an external viewer, but then synctex wont work. 

Related issue from VSCode: Ability to move tabs across screens:
https://github.com/Microsoft/vscode/issues/10121 

Thanks for this awesome plugin!

**Comment by James-Yu** [comment]
#3160

**Comment by suhailrehman** [comment]
Incredible! Thank you so much.
