### ISSUE TITLE
Itemize and enumerate completion injects `\n\t` from v9.4.0 on

### ISSUE THREAD

**Issue by BambOoxX** [James-Yu/LaTeX-Workshop#3638]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Starting with v9.4.0, `itemize` and `enumerate` environment completion (maybe others suffer from the same problem) inserts `\n\t`. 

| Version | 9.3.0 | 9.4.0|
|-----------------|-----------|----------|
| **Before completion** | ![image](https://user-images.githubusercontent.com/42067365/211557995-e02a5665-4401-4760-889c-1b86543c46bf.png)         | ![image](https://user-images.githubusercontent.com/42067365/211557719-c012652a-994d-4a09-a61e-e22257163a21.png)        |
| After completion  | ![image](https://user-images.githubusercontent.com/42067365/211558033-86bf6e51-698a-47ff-925a-3017c3987b26.png)         | ![image](https://user-images.githubusercontent.com/42067365/211557773-69dd7645-1b90-4345-81dd-850e09b4a01b.png)        |

It seems the `data/environments.json` file was modified when moving to 9.4.0 https://github.com/James-Yu/LaTeX-Workshop/compare/v9.3.0...v9.4.0#diff-310999b8de71138566d480f39a2c4dd7cbb2d02c1206f92f157b2e6985babdd5. Now some `\n\t` are double escaped. I am not sure this is the root cause, but it looks related. 

### To Reproduce

Open a document and type `\itemi` -> tab 

### Expected behavior

Revert back to pre v9.4.0 behavior.

**Comment by James-Yu** [comment]
Thanks for the report. This issue is worth an emergency release.
