### ISSUE TITLE
Keep document outline showing in pdf viewer sidebar after rebuilding?

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3649]
### Discussed in https://github.com/James-Yu/LaTeX-Workshop/discussions/3647

<div type='discussions-op-text'>

<sup>Originally posted by **bagrow** January 14, 2023</sup>
When I rebuild my document, the sidebar in the pdf viewer (if it is open) returns to the "Show Thumbnails" view. I find the "Show Document Outline" view more helpful. 

Can the sidebar remember which view it was on after rebuilding? Is there a setting I can change? I couldn't find anything obvious...

I have a vague memory that the sidebar used to stay on the existing view. Even if it lost its place in the outline after rebuilding, it was still more useful to me than seeing the thumbnails. Did an update change this?</div>

**Comment by James-Yu** [comment]
Hi @bagrow can you try out 37e79dc6f4aac607c1ebd81ecabc4933c74f83cb and see if things work as you expected? This feature was previously not implemented by the extension, maybe provided by pdf.js but later removed from their side.

I currently do not have a PDF with outline available with me, so the changes are by speculation and may need your help to verify. Many thanks!

You may download a packaged `vsix` from https://github.com/James-Yu/LaTeX-Workshop/actions/runs/3916957184 , bottom of the page has an artifact section.

**Comment by bagrow** [comment]
Fantastic! Tried the .vsix and it works great, exactly what I was hoping for!
