### ISSUE TITLE
Typing $ causes bad typing behavior 

### ISSUE THREAD

**Issue by jsinglet** [James-Yu/LaTeX-Workshop#365]
Often I will have to type a $ and the beginning and end of a formula. If I move the cursor to the end of the formula and type $ LW will insert $$. If I insert at the start of the formula it only inserts a single $. I think a better behavior is to not insert pairs of $; it rarely works out that this doesn't cause the wrong behavior.

**Comment by James-Yu** [comment]
I agree with you. Should remove the pairing in the next release.
