### ISSUE TITLE
\dfrac auto insert `num` and `den`

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3651]
![Screenshot_20230117_105914](https://user-images.githubusercontent.com/65082432/212800557-c7fa45c6-93c9-4393-8b8f-71ac17daa99f.png)
 
like this, when I insert `\dfrac` and press `Enter`, the auto-completion insert `num` and `den`.

I do not need `num` and `den`, and `\frac` do not have this issue.

**Comment by James-Yu** [comment]
latex-workshop.intellisense.argumentHint.enabled
