### ISSUE TITLE
Separate command and argument-signature suggestions

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3656]
### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

### If your requested feature is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

With the recent implementation of package commands, now command suggestions are sometimes clogged with many entries with the same command name and different argument signatures, e.g., `\cmd[]{}` and `\cmd{}` and `\cmd` and `\cmd[]{}{}`. This makes auto-completing the command name quite indirect.

What about we split the command suggestion into two parts, namely, if the command name has completed, all signatures are provided, otherwise only complete command names are provided. For example, suggesting `\cmd` yields `[]{}`, `{}`, `[]{}{}`, `\cmdother`, `\cmdanother`.

May I have your opinion on this? @jlelong I am happy to implement this if your consider it not bad.

**Comment by jlelong** [comment]
> This makes auto-completing the command name quite indirect.

Yet, VS Code learns from your previous suggestion selection to sort the list of suggestions. The ones you tend to often select are at the top of the list. This makes completion easier after some time.

> For example, suggesting `\cmd` yields `[]{}`, `{}`, `[]{}{}`, `\cmdother`, `\cmdanother`.

In relation with my above point, this will break VS Code learning as the choice between `[]{}`, `{}`, `[]{}{}` actually depends on `\cmd`and VS Code is not aware of the command to be completed. This would actually require the second suggestion to show `\cmd[]{}` and `\cmd{}` and `\cmd` and `\cmd[]{}{}`, which is the current list filtered with `\cmd`.

My second point is that entering `\cmd[]{}{}` would require triggering and accepting two suggestion steps. This would actually slow down typing a little.

I may give a second thought on this but my first opinion is not really positive.

**Comment by James-Yu** [comment]
I agree that separating these are detrimental to vscode learning. Let me close this issue for now and think of if there’s a better solution.
