### ISSUE TITLE
"Outline" not working when text is wrapped in custom command

### ISSUE THREAD

**Issue by JHenneberg** [James-Yu/LaTeX-Workshop#3663]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

I am using a command to manage more then one language in one file:

```tex
\RequirePackage{ifthen}

\newif\ifen%
\newif\ifde%
\newcommand{\en}[1]{\ifen#1\fi} % \en{english Issue}
\newcommand{\de}[1]{\ifde#1\fi} % \de{deutsche Ausgabe}
```

Before `\begin{document}` I "activate" one of those defined languages and turn all others "off"
```tex
% Set the languages
\entrue%
\defalse%
```

So i can write the following:

```tex
\en{
  \section{Section}
  This is not german.
}
\de{
  \section{Abschnitt}
  Dies ist nicht deutsch.
}
```

Unfortunately "Outline" in Visual Code is not recognizing the `\section`, `chapter{}` etc anymore because of the surrounding command.

### To Reproduce

1. Insert my command and create a *.tex file using those commands
2. Check the "Outline" winwos in VS Code
3. See it is empty instead of showing the hierarchie of the document

### Expected behavior

Showing the hierarchie of the document despite the fact it is wrapped in custom commands

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Win 11
 - VS Code version:1.74.3
 - Extension version: 9.5.0
 - TeX distribution version: MiKTeX 22.12

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by James-Yu** [comment]
Unfortunately, LW won't support this kind of command expansion in outline. Implementing such feature is more or less equivalent to implementing a LaTeX engine.
