### ISSUE TITLE
all errors on line 1, column 1

### ISSUE THREAD

**Issue by RobertHarper** [James-Yu/LaTeX-Workshop#3666]
Hello,  I am using LaTeX Workshop on VS Code, and am finding that all errors are reported in the output window as occurring on Line 1, Col 1, even though the underlying TeX compiler reports the proper line number of the mistake.  This means that I cannot jump to errors, which is not the best behavior.  Oddly, warnings report the correct line numbers!  It is only the Red errors, as distinct from the Yellow warnings, that have stopped working.

Can someone please advise me as to what might be wrong, and how to fix it?

**Comment by James-Yu** [comment]
Please fill in the issue template, provide proper information, and develop a minimal working example if possible.
