### ISSUE TITLE
support for asymptote

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3672]
> The sample LaTeX file below, named latexusage.tex, can be run as follows:
```
latex latexusage
asy latexusage-*.asy
latex latexusage
```

but in latex-workshop, how to set the filename `"%DOCFILE%"` for `latexusage-*.asy`?

**Comment by James-Yu** [comment]
No, it’s not possible. You need to create your own tools and recipe.
