### ISSUE TITLE
Modern style scrollbar in the built-in pdf viewer

### ISSUE THREAD

**Issue by qianchd** [James-Yu/LaTeX-Workshop#3678]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Is your requested feature related to a problem? Please describe. [Required]
No.

## Describe the solution you'd like  [Required]

The default scrollbar in the pdf.js viewer is alien to the scrollbar of the vscode windows. I add several lines in the [latexworkshop.css](https://github.com/James-Yu/LaTeX-Workshop/blob/master/viewer/latexworkshop.css) to get a thin scrollbar. It can also hide itself when the viewer is not focused and change into bold mode when the thumb is selected. 

```
/*
	scrollbar
*/
#viewerContainer::-webkit-scrollbar {
    width: 10px;
    background-color: transparent;
    border-style: none;
}

#viewerContainer::-webkit-scrollbar:hover {
    background-color: rgb(225, 225, 225);
}

#viewerContainer:focus::-webkit-scrollbar {
    background-color: rgb(225, 225, 225);
}

#viewerContainer:hover::-webkit-scrollbar-thumb {
    border-style: solid;
    border-color: transparent;
    border-radius: 6px;
    background-clip: content-box;
    background-color:
        rgba(190, 190, 190);
}

#viewerContainer:focus::-webkit-scrollbar-thumb {
    border-style: solid;
    border-color: transparent;
    border-radius: 6px;
    background-clip: content-box;
    background-color:
        rgba(190, 190, 190);
}

#viewerContainer::-webkit-scrollbar-thumb:hover {
    border-radius: 6px;
    background-clip: border-box;
    background-color: rgba(190, 190, 190);
}

#viewerContainer::-webkit-scrollbar-thumb:active {
    background-color: rgba(120, 120, 120);
}
```

I am not sure if someone will be interested in such a beautification

## Screenshots
![image](https://user-images.githubusercontent.com/48825214/215841777-8281dccd-cb7f-46da-a7c8-39d2b950086d.png)

![image](https://user-images.githubusercontent.com/48825214/215840791-adf24d81-dd9b-4031-9dc9-30b8d3ad0905.png)

![image](https://user-images.githubusercontent.com/48825214/215840898-fc08c5b0-b11a-4e64-b6ab-d743920ba83d.png)

![image](https://user-images.githubusercontent.com/48825214/215841007-36512930-e7b0-4704-8a89-704ec6f24d7c.png)

## Desktop [Required]

 - OS: Windows 10
 - VS Code version: 1.74.3
 - Extension version: 9.4.5
 - TeX distribution version: TeX Live 2022

**Comment by James-Yu** [comment]
Look quite good! Please file a PR and I will review it.
