### ISSUE TITLE
Question: using flag --jobname when building with pdflatex

### ISSUE THREAD

**Issue by rs7q5** [James-Yu/LaTeX-Workshop#3680]
I am trying to add a flag to my recipes to add a suffix to my jobname using pdflatex. So in textstudio I can make a custom command that is equivalent to `pdflatex -> bibtex -> pdflatex *2`, but my beamer pdf is renamed as `file_withnotes.pdf` instead of just `file.pdf`. 

The following custom command in TexStudio works, note each "|" separates each main command. 

`
% pdflatex.exe -synctex=1 -interaction=nonstopmode --shell-escape --jobname=%_withnotes %.tex | bibtex.exe %_withnotes | pdflatex.exe -synctex=1 -interaction=nonstopmode --shell-escape --jobname=%_withnotes %.tex | pdflatex.exe -synctex=1 -interaction=nonstopmode --shell-escape --jobname=%_withnotes %.tex
`

I have tried adding the following to my recipe settings file. (the additions are `pdflatex_beamernotes` and `bibtex_beamernotes`
![image](https://user-images.githubusercontent.com/46969733/215844078-d71b886a-8740-4ab0-9246-57a678ddc861.png)

and then added this recipe
![image](https://user-images.githubusercontent.com/46969733/215844210-3986e8d1-47f2-4d0a-a636-ca6f345d6c4a.png)

But it doesn't seem to work. When I look at the compiler output I just get the following below, but I don't think I'm adding that flag correctly... also I think it may still be attempting to compiile, but getting stuck somewhere, which is where I'm not sure the correct syntax that should be done with `jobname`.

![image](https://user-images.githubusercontent.com/46969733/215844635-a4dcd984-fb4d-4ef8-94a5-ee947a3e738b.png)

**Comment by James-Yu** [comment]
Obviously, you are not compiling anything in your `pdflatex_beamernotes` tool, i.e., missing a `%DOC%` at the end of args.

**Comment by rs7q5** [comment]
Is that not what the %DOC% is the % in the command that works in texstudio is basically the file name character?

Where would I define this in the workshop or can you direct me to the setting I should change instead. Basically if I run this command in texstudio it creates tmp files and a PDF named `file_withnotes` instead of just `file` should with notes be inside of docs? 

Figured since stuff like syntax=1 or what not was in one line jobname should have the equal sign and value too.

**Comment by James-Yu** [comment]
You see in your config, all arguments are `-something`. They are flags, not your doc to compile.

**Comment by jlelong** [comment]
I think it is sufficient to one more entry to the `args` array : "%DOC%". The jobname flag only specifies the root of the generated file but does not say what file to compile. Note that when the jobname is different from the tex file name, some features of LW will not work
- LW will not be able to find the `.aux` file, hence some features related to intellisense and math preview may not work
- LW will not be able to link the `.tex` and `.pdf`: synctex from tex will be broken, view pdf will not work.
And maybe more...

**Comment by rs7q5** [comment]
So what should that entry be? In TexStudio it points to the same .tex file and I have some logic in there to print my beamer slides with or without notes. I get the file name discrepancy. 

But I guess I forgot changing the `%DOC%` would change the file its actually looking for not just the output file? 

But either way where would you suggest I redirect the output file even though it's compiling the same file. The flag when doing this though does create new `.aux` files with that file extension name. 

Thanks in advance!

**Comment by rs7q5** [comment]
GOT IT!!!! Thanks for the help @James-Yu and @jlelong your comments helped me decipher that. I had the purpose of `%DOCS%` backwards. 

Solution for the `pdlatex` and `bibtex` commands used in the recipe is as follows:

![image](https://user-images.githubusercontent.com/46969733/216076224-8c99995a-b986-4492-b3f1-f40d6e0dca38.png)

**Comment by rs7q5** [comment]
Ah the swapping of temporary files was due to a setting of cleaning and building.  Sometimes I have to run twice for it to successfully build, but pretty sure that's a thing on my end as I've had that in texstudio if I recall correctly.
