### ISSUE TITLE
(θ:r) display bug

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3681]
(θ:r) display bug

![Screenshot_20230201_105638](https://user-images.githubusercontent.com/65082432/215934271-b24e19cf-8630-44e9-af69-f93f0da53da2.png)

```
Latex-Workshop 9.6.0
vscode: 1.74.3
commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.2.0-rc6-1-mainline
sandbox: No
```

**Comment by James-Yu** [comment]
<img width="230" alt="Screenshot 2023-02-01 at 11 18 16" src="https://user-images.githubusercontent.com/4210342/215936923-e57fe0e4-a262-41f5-88e1-587e69ad1fcd.png">

Looks good for me. No idea why unless there were dev clues from your local machine.

**Comment by Firestar-Reimu** [comment]
![Screenshot_20230201_154755](https://user-images.githubusercontent.com/65082432/215982415-13e4d4b4-75b2-43a8-a4b0-69cfae9c6d6b.png)

I found that if I drag the left bar to maximum size it will be normal but at smaller width it will have bugs.

**Comment by James-Yu** [comment]
I'm not surprised on the occurrence of such bugs, yet I cannot do anything on my side for this visual issue (most likely css-related) unless I can reproduce. You may find clues in developer's console and inspect the css/boxes there, yet this may require some knowledge into css/html.
