### ISSUE TITLE
Cursor not work as expected when viewing pdf file

### ISSUE THREAD

**Issue by likanzhan** [James-Yu/LaTeX-Workshop#3682]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

Not related to compile

## Describe the bug [Required]

When viewing a pdf file with the pdf file shipped with LaTeX-Workshop, as ''Text Selection Tool'' is selected by default, the behavior of the cursor is supposed to be 'text selection'. It turns out, however, the behavior of the cursor is 'Hand tool'.

If I click "Hand Tool" and then click back to "Text Selection Tool", the behavior of the cursor then works as expected.
### To Reproduce

I'v attached a video to reproduce the problem.

### Expected behavior

The default behavior of the cursor is expected to be "Text Selection Tool"

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Screenshots

https://user-images.githubusercontent.com/10531698/215971292-d25b0b65-40a7-456d-9301-4d4e7281ad96.mov

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: MAC
 - VS Code version:  1.74.3
 - Extension version: v9.6.0
 - TeX distribution version: TeX Live 2022

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by James-Yu** [comment]
I cannot reproduce. What's your config on `latex-workshop.view.pdf.hand`?
