### ISSUE TITLE
Randomly the extension won't compile LaTeX files

### ISSUE THREAD

**Issue by 1103-Guyer-Josiah** [James-Yu/LaTeX-Workshop#3685]
### Pre-check

- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

9.6.0

### Operating System and Version

Windows 11

### Visual Studio Code Version

1.74

### LaTeX Distribution Version

TexLive 2022

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

![Screenshot_20230201_122814](https://user-images.githubusercontent.com/121468662/216156214-cea327d9-241c-4266-8b6a-463f242dd8a9.png)
It just started this morning out of nowhere. It usually compiles but since this morning every time I restart the VScode I get one compile then this error appears and it doesn't compile anymore.

### Reproduction Steps

I was literally using it last night and this morning this what was stated in "The Issue" occured

### Expected Behavior

For it to compile when I click compile

### Actual Behavior

No compile

### LaTeX Workshop Output

See image in "The Issue"

![Screenshot_20230201_010021](https://user-images.githubusercontent.com/121468662/216162365-eb50620c-289a-4d37-9ac4-8351de83bb0b.png)

I only use VScode for LaTeX at the moment, nothing else.

**Comment by James-Yu** [comment]
Please precheck and extension log.

**Comment by 1103-Guyer-Josiah** [comment]
Thank you!
