### ISSUE TITLE
Gnuplot cannot find *.gnuplot files when using the "Latex-workshop > Latex: Out Dir" option

### ISSUE THREAD

**Issue by Architect0rr** [James-Yu/LaTeX-Workshop#3686]
### Pre-check

- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

9.6.0

### Operating System and Version

Linux Mint 21.1 (Vera) x86_64 6.0.0-1010-oem

### Visual Studio Code Version

1.74.3

### LaTeX Distribution Version

TeX 3.141592653 (TeX Live 2022/dev/Debian) kpathsea version 6.3.4/dev

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

File `mm.tex` contains

    \documentclass[14pt,a4paper]{extarticle}
    \usepackage[utf8]{inputenc}
    \usepackage[T1]{fontenc}
    \usepackage[english]{babel}
    \usepackage{makeidx}
    \usepackage{amsmath}
    \usepackage{amsfonts}
    \usepackage{amssymb}
    \usepackage[left=10mm, top=15mm, right=10mm, bottom=15mm]{geometry}
    \usepackage{gnuplottex}
    
    \begin{document}
    
    \begin{gnuplot}[terminal=epslatex]
      set terminal epslatex color size 19cm,12cm
    
      set xrange [-4:4]
    
      plot x**2
    \end{gnuplot}
    
    \end{document}

When I compile a document without using this option, everything compiles.

When I use the "Latex-workshop > Latex: Out dir" option, the file doesn't compile and an error occurs
`line 0: Cannot load input from './mm-gnuplottex-fig1.gnuplot'`

File `mm.gnuploterrors` is in the root directory, compilation via standard `latexmk` recipe

Gnuplot verison: gnuplot 5.4 patchlevel 2

Latexmk version: 4.76

### Reproduction Steps

Set `Latex-workshop > Latex: Out Dir` option, copy example and paste it into a `.tex` file.

### Expected Behavior

Everything compiles

### Actual Behavior

Gnuplot can not find `*.gnuplot` file and creates a `*gnuploterrors` file in the root directory

### LaTeX Workshop Output

Rc files read:
  /etc/LatexMk
  /home/kein/.latexmkrc
Latexmk: This is Latexmk, John Collins, 20 November 2021, version: 4.76.
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      '/home/kein/Documents/нуклеация/analytics/xdc/mm.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="build"  "/home/kein/Documents/нуклеация/analytics/xdc/mm.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(/home/kein/Documents/нуклеация/analytics/xdc/mm.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21> (/usr/share/texlive/texmf-dist/tex/latex/base/extarticle.cls
Document Class: extarticle 1996/10/08 v1.0 Non Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/extsizes/size14.clo) (/usr/share/texlive/texmf-dist/tex/latex/base/exscale.sty)) (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty) (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty (/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2aenc.def (/usr/share/texlive/texmf-dist/tex/latex/base/t2aenc.dfu)) (/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2acmr.fd)) (/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty (/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def) (/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf) (/usr/share/texlive/texmf-dist/tex/generic/babel-russian/russianb.ldf)) (/usr/share/texlive/texmf-dist/tex/latex/base/makeidx.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty) (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/share/texlive/texmf-dist/tex/generic/iftex/ifvtex.sty (/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty))) (/usr/share/texlive/texmf-dist/tex/latex/gnuplottex/gnuplottex.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty) (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))) (/usr/share/texlive/texmf-dist/tex/latex/moreverb/moreverb.sty (/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)) (/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty) (/usr/share/texlive/texmf-dist/tex/generic/catchfile/catchfile.sty (/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty) (/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty) (/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty))) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def) (build/mm.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg)) Opening gnuplot stream ./mm-gnuplottex-fig1.gnuplotsystem returned with code 256

Package gnuplottex Warning: Conversion of ./mm-gnuplottex-fig1.gnuplot failed.

Package gnuplottex Warning: Please convert ./mm-gnuplottex-fig1.gnuplot manually.

(./mm.gnuploterrors)

Package gnuplottex Warning: Gnuplot execution produced errors:
ine 0: Cannot load input from './mm-gnuplottex-fig1.gnuplot'

.

(build/mm.aux) )
No pages of output.
Transcript written on build/mm.log.
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'build/./mm-gnuplottex-fig1.gnuplot'
      'build/mm.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="build"  "/home/kein/Documents/нуклеация/analytics/xdc/mm.tex"'
------------
Latexmk: Examining 'build/mm.log'
=== TeX engine is 'pdfTeX'
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(/home/kein/Documents/нуклеация/analytics/xdc/mm.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21> (/usr/share/texlive/texmf-dist/tex/latex/base/extarticle.cls
Document Class: extarticle 1996/10/08 v1.0 Non Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/extsizes/size14.clo) (/usr/share/texlive/texmf-dist/tex/latex/base/exscale.sty)) (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty) (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty (/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2aenc.def (/usr/share/texlive/texmf-dist/tex/latex/base/t2aenc.dfu)) (/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2acmr.fd)) (/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty (/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def) (/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf) (/usr/share/texlive/texmf-dist/tex/generic/babel-russian/russianb.ldf)) (/usr/share/texlive/texmf-dist/tex/latex/base/makeidx.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty) (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/share/texlive/texmf-dist/tex/generic/iftex/ifvtex.sty (/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty))) (/usr/share/texlive/texmf-dist/tex/latex/gnuplottex/gnuplottex.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty) (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))) (/usr/share/texlive/texmf-dist/tex/latex/moreverb/moreverb.sty (/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)) (/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty) (/usr/share/texlive/texmf-dist/tex/generic/catchfile/catchfile.sty (/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty) (/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty) (/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty))) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def) (build/mm.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg)) Opening gnuplot stream ./mm-gnuplottex-fig1.gnuplotsystem returned with code 256

Package gnuplottex Warning: Conversion of ./mm-gnuplottex-fig1.gnuplot failed.

Package gnuplottex Warning: Please convert ./mm-gnuplottex-fig1.gnuplot manually.

(./mm.gnuploterrors)

Package gnuplottex Warning: Gnuplot execution produced errors:
ine 0: Cannot load input from './mm-gnuplottex-fig1.gnuplot'

.

(build/mm.aux) )
No pages of output.
Transcript written on build/mm.log.
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made
Failure to make 'build/mm.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: failed to create output file
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
Latexmk: Examining 'build/mm.log'
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets

**Comment by James-Yu** [comment]
This is a `latexmk` issue: `latexmk` is moving your `.gnuplot` file to `-outdir` (also `-aux-directory` if you set it), and `gnuplot` cannot figure this action. You need to play with either `latexmk` config or `gnuplot` config to coordinate these two. I am not familar with them so I cannot give you more detailed advise.

This issue is not with the capacity of the extension.
