### ISSUE TITLE
[Request] Color options for pdf preview

### ISSUE THREAD

**Issue by Splike** [James-Yu/LaTeX-Workshop#369]
Using the pdf preview with a dark theme really looks wrong.
Would it be possible to add the option to set the hex color for text as well as the background?

**Comment by Splike** [comment]
While the new option the invert the colors are nice, it's not an optimal solution. the white text is distorted with pink-ish coloring and makes it hard to read.

I'd like to re-open this issue and ask for the option to pick a custom text color and background color. This way I can also make it match the current theme I am using.

**Comment by StevenLi-DS** [comment]
I didn't see anything but a gray background when setting the value to `0.5`

**Comment by Splike** [comment]
A hex value for background color and text color would be a great addition.
