### ISSUE TITLE
syncTex from cursor

### ISSUE THREAD

**Issue by YanhuiS** [James-Yu/LaTeX-Workshop#3693]
None of the shortcut keys of the latex workshop responded
![desk](https://user-images.githubusercontent.com/62749239/216804179-c48a9c63-4fa0-41db-a011-c50e0b25e2ca.png)
settings.json
"latex-workshop.view.pdf.internal.synctex.keybinding": "double-click",
"latex-workshop.showContextMenu":true

I can not use syncTex from cursor

**Comment by James-Yu** [comment]
It's for reverse synctex: PDF to TeX.

**Comment by YanhuiS** [comment]
None of the shortcut keys of the latex workshop responded，Do you know where the question is?

**Comment by James-Yu** [comment]
I don’t know.
