### ISSUE TITLE
cannot auto-select snippet when typing

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3697]
### Pre-check

- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

9.6.1

### Operating System and Version

Archlinux

### Visual Studio Code Version

1.75.0

### LaTeX Distribution Version

TeXLive 2022

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

cannot auto-select snippet when typing

### Reproduction Steps

open a tex file and type `\fra` or `\frac`

### Expected Behavior

The first option `\frac{}{}` should be blue and press `Enter` to auto-insert all `\frac{}{}`, cursor between the first `{}`

![Screenshot_20230206_111315](https://user-images.githubusercontent.com/65082432/216875824-b1664455-5d4c-4937-b7e7-af1c834ce43d.png)

### Actual Behavior

**Not Always**

![Screenshot_20230206_110156](https://user-images.githubusercontent.com/65082432/216874296-beedc14d-d717-4861-ad91-abfa819ff185.png)

The first option `\frac{}{}` is white and press `Enter` will switch to the next line

### LaTeX Workshop Output

I think log is of no use

https://paste.c-net.org/DustinSullivan

**Comment by James-Yu** [comment]
This is not an extension-related issue. You may search and see if there is a vscode config controlling this behavior. I recalled that there should be one.

**Comment by Firestar-Reimu** [comment]
This is my config:

```json
    "latex-workshop.bind.enter.key": false,
    "latex-workshop.message.error.show": false,
    "latex-workshop.message.warning.show": false,
    "latex-workshop.latex.autoClean.run": "onBuilt",
    "latex-workshop.latex.watch.delay": 0,
    "latex-workshop.latex.watch.interval": 0,
    "latex-workshop.view.pdf.tab.openDelay": 0,
    "latex-workshop.view.pdf.viewer": "tab",
```

**Comment by James-Yu** [comment]
editor.acceptSuggestionOnEnter

If this does not work, please approach vscode github.

**Comment by Firestar-Reimu** [comment]
`editor.acceptSuggestionOnEnter` is on by default, I consider this as a bug of suggestion algorithms

**Comment by xywei00** [comment]
Got the same problem. Ths issue is not about the Enter key, but about that quick suggestion is prevented in snippets. Found a solution here: https://github.com/microsoft/vscode/issues/173412. Just set `editor.suggest.snippetsPreventQuickSuggestions` to `False`.
