### ISSUE TITLE
something wrong with the highlight when using equations with \{ and \. 

### ISSUE THREAD

**Issue by hebinhao1993** [James-Yu/LaTeX-Workshop#370]
### environment:

- ubuntu 16.04
- vscode 1.19.1
- latex-workshop 3.12.0 

### Description

when I want to write equations like below:

OS: ubuntu 1
```tex
\begin{equation}
    f(x) = \left{\begin{aligned}
        &1, when H_1 is accepted
        &0, when H_0 is accepted
    \end{aligned}
    \right.
\end{equation}
```
there is some wrong with highlight just like below:
![2018-01-07 21-24-22](https://user-images.githubusercontent.com/31690238/34649816-3d79b0ce-f3f1-11e7-8db1-57c3e4ee656a.png)

the color of the second `\end{equation}` should be blue like the first,  but it is jacinth. 
the color of the text after the second equation should be white, however it is also jacinth.

### How to reproduce

if I do not close the `\left{`with`\right}`, there will be this problem.

### update
there is something wrong with me!!! shame on me
the tex code should be 
```tex
\begin{equation}
    f(x) = \left\{\begin{aligned}
        &1, when H_1 is accepted
        &0, when H_0 is accepted
    \end{aligned}
    \right.
\end{equation}
```

**Comment by James-Yu** [comment]
The highlight plan for `\{` is correct.
