### ISSUE TITLE
Preview of starred paired delimiter broken

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#3701]
### Pre-check

- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

9.6.1

### Operating System and Version

Windows 11

### Visual Studio Code Version

1.75.0

### LaTeX Distribution Version

MiKTeX 22.10

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

Starred variants of \DeclarePairedDelimiter from mathtools are not displayed correctly.

### Reproduction Steps

Define

`\DeclarePairedDelimiter{\parn}{\lparen}{\rparen}`

in preamble, and add (for instance) the environment

```
    \begin{gather*}
        \parn{\int}\\
        \parn[\bigg]{\int}\\
        \parn*{\int}
    \end{gather*}
```

### Expected Behavior

I'm expecting to see

(integration sign)
(integration sign), with `\bigg` parentheses
(integration sign), with size matching that of `\left(\int\right)` (or at the very least the same as the first line )

### Actual Behavior

![image](https://user-images.githubusercontent.com/2191754/216976579-48615945-0c37-49f7-a6b6-87fc3a22e450.png)

The starred variant seems to match that of `\parn{*}\int` instead

### LaTeX Workshop Output

Not particularly relevant

**Comment by jlelong** [comment]
This is a mathjax issue, see https://github.com/mathjax/MathJax/issues/2313

**Comment by Enivex** [comment]
> This is a mathjax issue, see [mathjax/MathJax#2313](https://github.com/mathjax/MathJax/issues/2313)

But that issue was closed after they added mathtools to Mathjax. Are you saying it was closed prematurely?

**Comment by James-Yu** [comment]
I was just debugging the issue, and it looks a bit more complicated than I thought. Will try to push a fix soon.

**Comment by James-Yu** [comment]
You may try the artifact in https://github.com/James-Yu/LaTeX-Workshop/actions/runs/4105116031 to see if issue resolved.

**Comment by Enivex** [comment]
> You may try the artifact in https://github.com/James-Yu/LaTeX-Workshop/actions/runs/4105116031 to see if issue resolved @Enivex .

That does indeed fix the issue, thanks.

The ideal solution would be if the star could be sent along to Mathjax, so that the size would be correct, but this is a lot better than the previous behavior!

Looking at https://github.com/mathjax/MathJax-src/blob/f939f2ff2c4678785e9bf3d3b17e8c6151f0ce9c/ts/input/tex/mathtools/MathtoolsMethods.ts it does seem like mathjax should be able to handle it

`  PairedDelimiters(parser: TexParser, name: string,
                   open: string, close: string,
                   body: string = '#1', n: number = 1,
                   pre: string = '',  post: string = '') {
    const star = parser.GetStar();
    const size = (star ? '' : parser.GetBrackets(name));
    const [left, right] = (star ? ['\\left', '\\right'] : size ? [size + 'l' , size + 'r'] : ['', '']);
    const delim = (star ? '\\middle' : size || '');
    if (n) {
      const args: string[] = [];
      for (let i = args.length; i < n; i++) {
        args.push(parser.GetArgument(name));
      }
      pre  = ParseUtil.substituteArgs(parser, args, pre);
      body = ParseUtil.substituteArgs(parser, args, body);
      post = ParseUtil.substituteArgs(parser, args, post);
    }
    body = body.replace(/\\delimsize/g, delim);
    parser.string = [pre, left, open, body, right, close, post, parser.string.substr(parser.i)]
      .reduce((s, part) => ParseUtil.addArgs(parser, s, part), '');
    parser.i = 0;
    ParseUtil.checkMaxMacros(parser);
  },`

**Comment by James-Yu** [comment]
Indeed. However, the current mathjax preview codes in this extension is a bit too entangled. Directly passing that to MathJaX may *potentially* require a refactor on the component, which has a relatively low priority.
