### ISSUE TITLE
PDF viewer changes zoom when resizing window when page trimming is on

### ISSUE THREAD

**Issue by jonwarneke** [James-Yu/LaTeX-Workshop#3703]
### Pre-check

- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

9.6.1

### Operating System and Version

macOS Ventura 13.2

### Visual Studio Code Version

1.75.0

### LaTeX Distribution Version

pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

PDF viewer changes zoom when resizing window when page trimming is on

### Reproduction Steps

Open side-by-side panes (one left/right of the other), one of which is a tex PDF viewing pane.
Turn on page trimming in the tex PDF viewing pane.
Resize the PDF viewing pane to be smaller.
The zoom will increase in the PDF viewing pane. 

### Expected Behavior

The zoom on the PDF should stay the same

### Actual Behavior

The zoom on the PDF viewing pane increases

### LaTeX Workshop Output

asdf

**Comment by James-Yu** [comment]
I cannot reproduce the issue. On my mac, the pdf resizes with the width of pane. Can you provide a screen capture on the issue? That may not be enough to identify the problem, yet we first confirm what happened.
