### ISSUE TITLE
Personal "problem" after latest update

### ISSUE THREAD

**Issue by kahijes** [James-Yu/LaTeX-Workshop#3706]
I am using 2 tabs: 1 with .tex, 1 with the generated pdf. The pdf scrolls back to the first page after each save (ctrl+s). The issue was fixed after I switched to using the previous version, so the newest update has done something that causes it.

**Comment by bandgeekdante** [comment]
Same as James-Yu/LaTeX-Workshop#2017, but the proposed fix there involves changing a deprecated setting

**Comment by James-Yu** [comment]
#3670
