### ISSUE TITLE
Avoid Syntax Highlighting in a specific env or command

### ISSUE THREAD

**Issue by Bigaluca** [James-Yu/LaTeX-Workshop#3709]
### The Issue

The issue is the one described here: https://github.com/James-Yu/LaTeX-Workshop/issues/3696

### The Solution

It is not possible to add an option in the plugin settings that automatically adds to the `LaTeX.tmLanguage` file custom environment names (by adding them to `lstlisting|minted|pyglist`) and custom command names (by adding them to `mint|mintinline`) so as to disable syntax highlighting in the editor with an interface similar to the `Verbatim Envs` setting?

This way maybe could avoid having to change the file every time update the extension.

**Comment by jlelong** [comment]
No that is far too complicated and creates a severe security breach to change file on the user computer.
