### ISSUE TITLE
Using magic circumvents latexmk, interfering with auxiliary progs.

### ISSUE THREAD

**Issue by timtro** [James-Yu/LaTeX-Workshop#371]
Thanks in advance. Also, thank you for developing and contributing this useful extension. I appreciate it, and of course, many others do as well.

### Description

Because of the way the `program` magic command is handled, I don't see a way to have bibtex/biber run when `program` is specified.

When latexmk is used (by default), it automatically detects and handles execution of bibtex or biber. In order to use the magic command, we set the toolchain to:
```
    "latex-workshop.latex.toolchain": [
        {
            "command": "",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }
    ]
```
where the blank command is replaced by the value specified by the command in the document, for example:
```
%!TEX program = lualatex
```
The problem is that lualatex is called directly, not using latexmk, so we lose all of the good stuff that latexmk handles.

### Recommended fix

Rather than running the command specified in the magic comment as a shell command, pass it to latexmk. For example, if `pdflatex`, `xelatex` or `lualatex` is specified, then pass it this way:
```
latexmk -pdflatex=<magic program> -pdf %DOC%
```
Alternatively, one might be able to add `%CMD%` to the list of variables that can be used in the toolchain specification so that I can do this:
```
    "latex-workshop.latex.toolchain": [
        {
            "command": "latexmk",
            "args": [
                "-pdflatex=%CMD%"
                "-pdf",
                "%DOC%"
            ]
        }
    ]
```
(NB: I don't know if %DOC% is a VS code thing, or a LaTeX-workshop thing, and whether or not new ones can be added.)
  
### Workaround

For now, what I've done is specified my toolchain this way:
```
    //
    // LaTeX
    //
    "latex-workshop.latex.toolchain": [
        {
            "command": "",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "command": "biber",
            "args": [
                "%DOCFILE%"
            ]
        },
        {
            "command": "",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }
    ],
```
but this obviously doesn't autodetect if biber/bibtex is needed, nor can it select between them. It's hardcoded to run biber, which only suits my needs at the moment. I'll have to modify my settings each time I switch to documents with different requirements.

**Comment by James-Yu** [comment]
The problem is, the extension never know if `latexmk` should be used or not. Given that many LaTeX users do not have the tool, such changes may make them sad.

IIRC there should be another issue on this problem. Let me find it first.

**Comment by James-Yu** [comment]
I'll try find a solution for this and #339 .

**Comment by James-Yu** [comment]
Fix will be published soon. README changes coming.

**Comment by timtro** [comment]
Thanks. I'm a GNU/Linux user, so I didn't realise that LaTeXmk wasn't a widely distributed tool. I thought it defaulted with MikTeX, but I Googled it and learned otherwise.

I appreciate you taking the time in the matter. I'm also sorry I didn't offer a pull request along with the bug, but I'm (obviously) no expert in cross-platform concerns, nor am I a JS programmer.
