### ISSUE TITLE
Different coloring of keywords if followed by numbers without space, e.g. \times and \times10

### ISSUE THREAD

**Issue by pazner** [James-Yu/LaTeX-Workshop#3711]
### Pre-check

- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

v9.6.2

### Operating System and Version

macOS 12.6.1

### Visual Studio Code Version

1.75.1

### LaTeX Distribution Version

TeXLive 2022

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

Syntax coloring of special commands does not work when the command is followed by a number without a space.

![image](https://user-images.githubusercontent.com/11493037/217963428-070709ff-6995-45bf-830a-19b025ad149e.png)

### Reproduction Steps

Enter the following in a tex file:

```tex
$\times$
$\times10$
```

### Expected Behavior

The word "times" in both `\times` and `\times10` should be colored the same.

### Actual Behavior

The word "times" in `\times` and `\times10` is colored differently.

### LaTeX Workshop Output

N/A

**Comment by jlelong** [comment]
This is not so simple as usually numbers are not allowed in command names, at least those defined with `\newcommand`. Yet, this limitation can be circumvented, which makes `\times10` ambiguous. Should it be interpreted as `\times 10` or is this a command name? It is impossible to figure it out without the whole context. Considering the highlighting of `\times10`, there are two approaches

1. `\times` and `10` have the same colour.
2. `\times`  and `10` are coloured as in `\times 10`. (This is what you suggest)

I will think of it.

**Comment by Enivex** [comment]
Is this related to the incorrect syntax highlighting when using enumitem?

![image](https://user-images.githubusercontent.com/2191754/218269932-063c4bb3-a678-4930-89d8-6e12b42d13f4.png)
The brackets should have the same color

**Comment by jlelong** [comment]
This has nothing to do with the current issue. This is related to bracket pair colorizing by vscode. Yet, you should observe that `[` has the same color as `)` because `[...)` is declared as a pair

https://github.com/James-Yu/LaTeX-Workshop/blob/1f25ffb56925be7562a1fa24097bbebca78bdb6b/syntax/latex-language-configuration.json#L7-L10

<img width="240" alt="Capture d’écran 2023-02-11 à 17 49 37" src="https://user-images.githubusercontent.com/2910140/218270349-604ffb4e-d100-458a-9b0f-12bdd25646f2.png">

There is nothing we can do about it as there is indeed a non matched paren or bracket.
