### ISSUE TITLE
Allow unsafe pdf preview in web browser on WLAN

### ISSUE THREAD

**Issue by YijunYuan** [James-Yu/LaTeX-Workshop#3713]
### The Issue

It is known that due to security considerations, viewing the pdf in a web browser on other devices is not allowed (cf. [this issue](https://github.com/James-Yu/LaTeX-Workshop/issues/2915)). However, since this feature is highly convenient for using a pad as a second screen, is it possible to provide a solution to remove this restriction after acknowledging the risk?

### The Solution

I'm not sure how to modify the source code, so no solution can be provided.

**Comment by James-Yu** [comment]
#3699
