### ISSUE TITLE
support \bm and \boldsymbol in math preview

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3714]
### The Issue

support `\bm` and `\boldsymbol` in math preview

https://www.ctan.org/pkg/bm

https://www.ctan.org/pkg/amsbsy

### The Solution

![Screenshot_20230212_171815](https://user-images.githubusercontent.com/65082432/218302641-20b0dc49-5179-4287-95ae-02562b007a74.png)

### Alternative Solutions

a `\mathbf` command that can be applied when no appropriate bold italic font is available.

### Anything Else?

![Screenshot_20230212_172251](https://user-images.githubusercontent.com/65082432/218302843-c03fc774-8d6c-4a01-b3b1-727461646412.png)

this is the current support

**Comment by James-Yu** [comment]
This is a MathJaX issue.

**Comment by Firestar-Reimu** [comment]
https://docs.mathjax.org/en/latest/input/tex/extensions/boldsymbol.html
