### ISSUE TITLE
support snippet for `\left\{ \right\}`

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3717]
### The Issue

support snippet for `\left\{ \right\}`

### The Solution

when I type `\left\{`, press `Enter`, it can auto insert `\right\}`

**Comment by jlelong** [comment]
Because `\` is a trigger character, it is not possible to consider `\left\{` as a single work to have it automatically completed. Instead, you have to use `\left{` which gets expanded into `\left\{ ... \right\}`.
