### ISSUE TITLE
Strange autocompletion `\left[]` --> `\left[\right\right\right]`

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#3718]
### Pre-check

- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] If the issue is related to compiling a document, it can be successfully compiled in OS terminal.

### Extension Version

git version

### Operating System and Version

osx

### Visual Studio Code Version

1.75.1

### LaTeX Distribution Version

aa

### Extension Environment

- [ ] I am using VSCodium.
- [ ] I am using the Snap or Flatpack version of Visual Studio Code.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote Containers.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote SSH.
- [ ] I am using LaTeX Workshop with Visual Studio Code Remote WSL.

### The Issue

The following command definitions for autocompletion seem wrong to me https://github.com/James-Yu/LaTeX-Workshop/blob/d4a667a3ee8b101063a34c287ee4ecfcc8a8d17b/data/packages/tex.json#L1294-L1314

For instance, `\left[]` is expanded into `\left[\right\right\right]`. Btw, most of these commands are already defined in `commands.json`. The following definitions https://github.com/James-Yu/LaTeX-Workshop/blob/d4a667a3ee8b101063a34c287ee4ecfcc8a8d17b/data/packages/latex-document.json#L486-L496 also produce useless entries in the completion menu. I am not sure how to fix all this and how `tex.json` and `latex-document.json` are used.

### Reproduction Steps

aa

### Expected Behavior

aa

### Actual Behavior

aa

### LaTeX Workshop Output

aa

### Anything Else?

Btw, I am not a big fan of the new issue interface with required fields. Sometimes the template is just irrelevant and I am afraid users might be bothered by it... I would prefer a pure text version by far

**Comment by James-Yu** [comment]
For `tex.cwl` and `latex-document.cwl`, the syntax is a bit different. So in the above two commits, we have additional special logic in the parsing script. Now it should work much better.

As to the issue template, will revert shortly!
