### ISSUE TITLE
Root file determination fails for subfile package

### ISSUE THREAD

**Issue by michaelaye** [James-Yu/LaTeX-Workshop#372]
### Description

Because the current scheme to determine the root file is using the presence of `\begin{document}`, it fails with the standard `subfile` use case, where each imported file has a `\begin{document}`.

I actually don't dislike that, because sometimes it's just faster to only compile the current file, as it saves from compiling the whole manuscript, but in an ideal case:

1. The root file determination should be able to deal with this subfile use case
2. Users should be able to choose if they want the root file to be compiled or the subfile.

Thanks for your great package, it's really powerful already and works rather flawless! I'm just very prone to find corner cases. ;)

**Comment by James-Yu** [comment]
Thank you for the suggestion. Meanwhile, I need to think of it carefully as the root finding logic is quite critical to the extension.
