### ISSUE TITLE
Highlight syntax errors in bibliography with biber

### ISSUE THREAD

**Issue by LinqLover** [James-Yu/LaTeX-Workshop#3720]
> Please fill the following fields with a star (*) and provide as much related information as possible.

## Pre-checks*
> Please change the following `[ ]` to `[x]` for confirmation.
- [x] The feature request has not been suggested in this repository.

## The Missed*
> Is your feature request related to a problem? Please provide a clear and concise description of what the problem is.
- I often insert syntax errors in bib files (missing commas between properties of an entry, unescaped accents, missing/additional curly braces, ...). These are hard to debug because I always need to look into the logs or do manual bisect-debugging for finding the buggy entry (i.e., removing half of the entries until the file compiles again).
   Example:
   ```bib
      @article{zingheim2002downturn
   	title	= {In a Downturn Do You Cut Pay, Slash the Workforce or Protect Precious Talent?},
   	author	= {Zingheim, Patricia K and Schuster, Jay R},
   	journal	= {Strategy & Leadership},
   	volume	= {30},
   	number	= {1},
   	pages	= {23--26},
   	year	= {2002},
   	publisher	= {MCB UP Ltd}
   	doi	= {10.1108/10878570210414417}
   }
   ```

## The Solution*
> Please provide a solution you would like to have.
- Highlight syntax errors in the bib file. This could either be done through the grammar by being less forgiving in the parser or by generating annotations from the outputs of the parsers (probably the former is easier as different bibliography backends might create different kinds of logs, but I'm neither an expert in that nor in parser design :D).

## Anything Else?
> Add any other context about the feature request below.
- Thank you for developing and maintaining this awesome extension!

**Comment by jlelong** [comment]
With your exemple I get
<img width="371" alt="Capture d’écran 2023-02-16 à 11 34 08" src="https://user-images.githubusercontent.com/2910140/219341804-beb47041-b8b7-49e2-bc6c-acbac26c9c1d.png">

<img width="468" alt="Capture d’écran 2023-02-16 à 11 36 01" src="https://user-images.githubusercontent.com/2910140/219341824-fa34af06-b5b4-4238-842e-446fdbf2f205.png">

As you can see, the bitex error is reported in the _Problems_ pane et the `doi` line is not highlighted as other lines. The line reported by `bibtex` is wrong but we cannot do anything about it. 

@LinqLover Could you elaborate on what you would like on top of that?

**Comment by LinqLover** [comment]
Hmm, this looks different to me:

![image](https://user-images.githubusercontent.com/38782922/219432421-d35a7f09-40bf-4861-91fe-09c79802dfed.png)

This might depend on the theme, I am using [Windows XP Theme for VS Code](https://github.com/sinedied/vscode-windows-xp-theme).

Still, I would argue that the difference is very subtle. The syntax highlighting also does not give any clue that a comma is missing after the key.

What I would love to see here would be two red wiggle lines in the first line and in the second to last line (ideally even before saving the file).

The problem pane does also not mention the bib file, even though the LaTeX Compiler output contains as expected:

```
Biber error: [1007] Utils.pm:410> ERROR - BibTeX subsystem: C:\Users\CHRIST~1\AppData\Local\Temp\biber_tmp_ueGn\f4d088b3f9f145b5c3058da33afd57d4_27432.utf8, line 2, syntax error: found "title", expected ","
```

**Comment by jlelong** [comment]
You are right. Themes assign colours to scopes which are set by the grammar. 

Red wiggle lines are usually produced by some linter. Unfortunately, I do not think there are linters for `.bib` files. It is completely of the scope of grammars to produce those Red wiggle lines.

Our log parser only supports `bibtex` messages for the moment. I will add support for `biber` message soon

**Comment by LinqLover** [comment]
Biber support sounds great!

Couldn't you also use the results from parsing the logs for producing wiggle lines? I find them more obvious than entries in the problem pane.

Do you maybe have a quick pointer to me what scopes the syntax highlighter uses in the example? Maybe I could fix the assigned color in my theme.

**Comment by jlelong** [comment]
> Do you maybe have a quick pointer to me what scopes the syntax highlighter uses in the example? 

You can use _Developer: inspect editor tokens and scope_ from the command palette.
