### ISSUE TITLE
Changed hostname fails at CORS check

### ISSUE THREAD

**Issue by asztrikx** [James-Yu/LaTeX-Workshop#3723]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## The Issue
Commit 0818c0d introduced changing the hostname for which the server binds itself. However addressing CORS doesn't work as it uses ([place1](https://github.com/James-Yu/LaTeX-Workshop/blob/0818c0de9730f0e44494d6c80dc6007b9eba70c8/src/components/server.ts#L29), [place2](https://github.com/James-Yu/LaTeX-Workshop/blob/0818c0de9730f0e44494d6c80dc6007b9eba70c8/src/components/server.ts#L29)) `validOrigin` from [obtainValidOrigin](https://github.com/James-Yu/LaTeX-Workshop/blob/0818c0de9730f0e44494d6c80dc6007b9eba70c8/src/components/server.ts#L122) which when given `0.0.0.0` returns an url containing `127.0.0.1` therefore always skips the if statement.

### Expected Behavior
On changed hostname (based on the current code) CORS check should be ignored with an early return if hostname is not `127.0.0.1`.

**Comment by James-Yu** [comment]
Wrong. `0.0.0.0` does not assign a `127.0.0.1` origin to `validOrigin`. Please read the log.
