### ISSUE TITLE
Tab or browser PDF is not automatically updated after building LaTex project

### ISSUE THREAD

**Issue by pwangcs** [James-Yu/LaTeX-Workshop#3727]
##  Issue
Tab or browser PDF is not automatically updated after building LaTex project. So I must do 'View LaTex PDF - Refresh all reviers' by the mouse. This is weird, I remember that PDF can be automatically updated before.

## Reproduction
- Compile a .tex file.
- Open PDF preview by 'View LaTex PDF - View in VSCode tab'.
- Output the PDF.
-  Write and compile again, the PDF is not automatically updated.
-  Do 'View LaTex PDF - Refresh all reviers', the PDF is updated.

## Expectation
 PDF is automatically updated after building LaTex project without additional operations.

**Comment by pwangcs** [comment]
Why do you close all issues related with latex-workshop in github?

开 2023/2/16 23:39:09, James Yu ***@***.***> 写到:

Closed #3727<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJames-Yu%2FLaTeX-Workshop%2Fissues%2F3727&data=05%7C01%7Cwangping%40westlake.edu.cn%7C669918584c5944dccae408db1033f01c%7C7e82de2f7ef644169b9644c1457be81b%7C1%7C0%7C638121587496894858%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H%2B4a4SSX%2FBfOPtMzYFWsfHjId8x6%2Bbsf4l53oWQMKkM%3D&reserved=0> as completed.

**Comment by James-Yu** [comment]
I don't close all issues. I closed your #3726 .

FILL IN THE FXXKING ISSUE TEMPLATE.

Issues not complying with the template are subjected to immediate close without comment after the first attempt.
