### ISSUE TITLE
Differentiate AutoClean run options based on build succes/fail

### ISSUE THREAD

**Issue by lodewijkvankeizerswaard** [James-Yu/LaTeX-Workshop#3728]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Currently I am using AutoClean to remove all auxilary files. However, when compilation fails, the compiler refers to the log files, which by now have been removed by AutoClean. When I really need to, I can of course turn off AutoClean and recompile.

## The Solution*
> _Please provide a solution you would like to have._
- This can be addressed in two ways:
- 1. Add the OnSucces option to the `latex-workshop.latex.autoClean.run` setting, which means that the log files are available for reference when compilation fails. Recompiling after debugging, will then AutoClean the files; the desired behaviour when successful. I think this would be the preferred option based on effort/added functionality.
- 2. Differentiate `latex-workshop.latex.clean.fileTypes` on OnBuilt and OnSucces, allowing more fine grained control over the cleaning process based on the build status.

## Anything Else?
> _Add any other context about the feature request below._
- I searched for this feature request in the issues of this repo and could not find anything. I hope I didn't miss a duplicate.

**Comment by James-Yu** [comment]
Edge case but sounds reasonable.
