### ISSUE TITLE
superfluous argument is pushed to latexmk command

### ISSUE THREAD

**Issue by yistLin** [James-Yu/LaTeX-Workshop#373]
### Description

I've configured `latex-workshop.latex.toolchain` to use `latexmk` and used `xelatex` as typesetting engine. However, in version 3.12.2, I got an error while compiling with `latexmk` because of the superfluous argument `-pdflatex=pdflatex` added at the end of the command.

I supposed this could be caused by line 131 in `src/components/builder.ts`

### How to reproduce

1. no magic comment to specify typesetting engine in root file.
2. use package like **fontspec** or **xeCJK** and configure latexmk to use typesetting engine *XeLaTeX* with argument `-xelatex`.
3. compile and get error.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
 Toolchain step 1: latexmk, -interaction=nonstopmode,-file-line-error,-xelatex,/Users/yistlin/Documents/ltcl-final-report/main,-pdflatex=pdflatex
</details>

**Comment by James-Yu** [comment]
I agree with your observation. This was introduced in the last version to deal with `latexmk` and magic comment. Fix incoming.
