### ISSUE TITLE
Customizing keyboard shortcuts for PDF navigation

### ISSUE THREAD

**Issue by ChesterXXX** [James-Yu/LaTeX-Workshop#3731]
The internal PDF viewer supports going back/forward after clicking any internal hyperlink. There are buttons for these two actions in the top navigation bar inside the PDF viewer.

I am aware of `Alt + LeftArrow` and `Alt + RightArrow` does this as well. But these shortcuts are also bound to editor navigation back/forward. If I unbind them from editor navigation, then they work fine in the PDF viewer.

But how do I customize these keyboard shortcuts for the PDF viewer? I would like to bind `Backspace` and `Shift + Backspace` respectively, which is the default behavior in Sumatra PDF. I couldn't find the respective key in the keyboard shortcuts JSON.

**Comment by James-Yu** [comment]
On my Mac, the keys are cmd+left/right when viewer is focused. It does not interfere with vscode shortcuts. I think on windows, the keybind should also be ctrl+left/right.
