### ISSUE TITLE
Choose recipe based on magic comment

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#3734]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

It has _sort of_  been requested before

https://github.com/James-Yu/LaTeX-Workshop/issues/2642

(but not really, since my problem is different)

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

I have several documents. Some of which must be compiled using lualatex or xelatex because of fontspec and unicode-math. Right now, I have to manually choose the appropriate latexmk recipe, which partially defeats its purpose.

Thankfully `"latex-workshop.latex.recipe.default": "lastUsed",` means that I only have to do so once every restart, provided I don't have to juggle multiple documents at a time, but it's not ideal.

## The Solution*
> _Please provide a solution you would like to have._
- 

The solution I'd like to have is an extension of https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments where I can do something like

% !TeX recipe = latexmk

or

% !TeX recipe = lualatexmk

in order to an overriding default recipe for the current document. That is, it should be used in place of the recipe from latex-workshop.latex.recipe.default.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
May I have your opinion on this request @jlelong ? I am sort of positive to this feature, which might be useful if there are mix usages of pdflatex and xelatex for example in the same project, e.g., figures from TiKZ use custom fonts and main document requires pdflatex (blame you IEEETran).

**Comment by jlelong** [comment]
I was actually also wondering about this feature request. I am rather positive too. 
Magic comments are already bypassing the recipe definition, so allowing magic comment to set the name of the recipe sounds reasonable. Yet, it might not be very portable as recipe names can be local to a user configuration. We have to make clear how we handle this.
