### ISSUE TITLE
Workspace setting to set root file

### ISSUE THREAD

**Issue by cascremers** [James-Yu/LaTeX-Workshop#3735]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When working with multi-file projects that have multiple alternate root files that include the same sub-files, the current root file detection can be hard to switch. For example:

 1. A1 and A2 are root files that both input B, and only define some toggles: these build two different versions of a document (e.g. for short/full versions of some document).
 2. B contains \begin{document} and possibly includes multiple subfiles C1...CN
 
Using the current root file setup, it is cumbersome to switch between A1 and A2, especially when editing Cx, as the root file to compile needs to be either hardcoded in all these files B,C1..CN, or one needs to switch back to A1/A2 to trigger the build.

## The Solution*
> _Please provide a solution you would like to have._
- A generic solution that would probably work for many other use cases, is to introduce a workspace setting that, if present, overrides the root file detection (https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-root-file). This could be called something like, e.g., `latex-workshop.latex.rootfile` or `latex-workshop.latex.forceRootfile`.

(Note that I tried to simulate this behavior with include/exclude lists for the root file search, but this didn't yield the override I wanted in all cases.)

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
Instead of creating a new config item that is highly likely non-portable, f94300a adds a logic to keep the current root file if multiple candidates are found and the current one is in. I think this should resolve your use case.

You may try out https://github.com/James-Yu/LaTeX-Workshop/actions/runs/4239892165 , or wait for the next release of the extension.

**Comment by cascremers** [comment]
Thank you @James-Yu for the super quick response!

I tried the specific version, and it solves the problem indeed when editing C1...CN. This was the main issue, thank you.

Note that it doesn't solve the problem completely in this setup, but that is mostly connected to the coarse root file detection based on scanning for `\begin{document}`, and I can (mostly) work around it:
 - [minor] A1 and A2 don't have `\begin{document}`, so still need a hack to get them detected as root files. One is to insert the magic comment referring to themselves; another is to have a fake `\iffalse \begin{document} \fi` in both.
 - [still tricky] Since B is not the intended root file, but has `\begin{document}`, it still triggers a broken compile in the logic of this fix. A workaround is to ensure B never has real content that needs editing, and always essentially inputting some C that has the real content.

I am very grateful for this fix that allows me to work in this type of use case with some further hacks. However, I guess the issue of the coarseness of scanning for `\begin{document}` as the core mechanism will pop up in many contexts still in the future.
At the moment I don't quite grasp why a new config item would not be portable.

**Comment by James-Yu** [comment]
The whole root file detection mechanism can be in fact circumvented, which fits well with you use case. In particular, you can create two recipes/tools, in which instead of using the `%DOC%` placeholder, just insert the file names of A1 and A2. By setting the default recipe config to `lastUsed`, you can switch between these two files with just one click on the respective recipe name.

Please comment if this solution won't work well for you.

**Comment by cascremers** [comment]
Minor note: even when hardcoding names in the recipes (with the intent of circumventing root file detection issues), it seems the root file detection is still used in the logic of the `view latex PDF` preview button, needing a minor workaround there.

**Comment by James-Yu** [comment]
Just click the pdf files in vscode explorer. They will get updated automatically.
