### ISSUE TITLE
latex-workshop.latex.verbatimEnvs doesn't work

### ISSUE THREAD

**Issue by Aljumaily** [James-Yu/LaTeX-Workshop#3736]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: MacOS Ventura 13.2.1
- Visual Studio Code Version: Version: 1.75.1
- LaTeX Workshop Version: 9.7.0
- TeX Distribution Version: TeX Live 2022

## The Issue*
I want to create a custom environments, similar to `verbatim` or `lstlistings`, where the text inside is _not_ indented. For example, consider the two custom environments `mycenteredText` and `code`:

```latex
\documentclass{article}

\newenvironment{mycenteredText}[1]
{\begin{center}#1}
{\end{center}}

\NewDocumentEnvironment{code}{O{\ttfamily} +!b}
{#1#2}
{}

\begin{document}
\begin{verbatim}
verbatim
\end{verbatim}
\begin{mycenteredText}
  My centred Text
\end{mycenteredText}
\begin{code}
  My Code environment
\end{code}
\end{document}
```
### Reproduction Steps
Let us assume the text inside the environment is not indented. When saving the file, the environments will automatically have the text indented. What is interesting is that modifying `latex-workshop.latex.verbatimEnvs` in `settings.json` doesn't work. Whether I leave the default values (_e.g._, `"verbatim", "lstlisting", "minted"`) or remove them, they will still be treated as verbatim environments. Adding `code` and/or `mycenteredText` to the array doesn't change anything. Here are the settings I am using for the extension:
```json
"[latex]": {
    "editor.defaultFormatter": "James-Yu.latex-workshop"
  },
  "latex-workshop.latex.recipes": [
    {
      "name": "pdflatex",
      "tools": [
        "pdflatex"
      ]
    },
    {
      "name": "xelatex",
      "tools": [
        "xelatex"
      ]
    },
    {
      "name": "xelatex -> biber -> xelatex*2",
      "tools": [
        "xelatex",
        "biber",
        "xelatex",
        "xelatex"
      ]
    },
    {
      "name": "pdflatex -> bibtex -> pdflatex*2",
      "tools": [
        "pdflatex",
        "bibtex",
        "pdflatex",
        "pdflatex"
      ]
    }
  ],
  "latex-workshop.latex.tools": [
    {
      "name": "pdflatex",
      "command": "pdflatex",
      "args": [
        "-shell-escape",
        "-enable-write18",
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOC%"
      ]
    },
    {
      "name": "bibtex",
      "command": "bibtex",
      "args": [
        "%DOCFILE%"
      ]
    },
    {
      "name": "biber",
      "command": "biber",
      "args": [
        "%DOCFILE%"
      ]
    },
    {
      "name": "xelatex",
      "command": "xelatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOC%"
      ]
    }
  ],
  "latex-workshop.latex.verbatimEnvs": [
    "verbatim",
    "lstlisting",
    "minted",
    "mycenteredText",
    "code"
  ],
```

### Expected Behavior
Have `latex-workshop.latex.verbatimEnvs` register the environments that should not be indented.

## Anything Else?
In case there is a cheeky workaround to this, I am more than happy to hear it out ☺️.

**Comment by James-Yu** [comment]
I don't understand what you mean or request. `latex-workshop.latex.verbatimEnvs` has nothing to do with indentation.

**Comment by Aljumaily** [comment]
I might be mistaken. I thought `latex-workshop.latex.verbatimEnvs` will ensure that the environments will be treated as verbatim and hence, no auto indentation will occur. My request is that if I wanted to create a custom environment and suppress auto indentation in it, how can I achieve that?

**Comment by James-Yu** [comment]
I don't think scoped auto-indent is available in vscode. This is not controlled by the extension, if I recall correctly. You can switch it off completely, or turn on for all. Correct me if I am wrong as I'm not 100% sure on this.

**Comment by Aljumaily** [comment]
I wonder why `verbatim` and `lstlisting` environments don't indent the code but code inside of other environments is indented automatically.

**Comment by jlelong** [comment]
It seems that you are using VSCode's format on save feature. For LaTeX files, formatting is done by `latexindent`. See https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#verbatim-code-blocks for a solution to your request

**Comment by Aljumaily** [comment]
Thank you for the quick and informative responses! As [jlelong](https://github.com/jlelong) mentioned, it deals with [latexindent](https://github.com/cmhughes/latexindent.pl). Here are the steps required to create custom verbatim environments that will not be indented in VSCode.

 - There are three parts (I am not sure if *all* requirements must be installed for it to work, but install all of them to be on the safe side): 
   - Installing latexindent, Perl and YAML extension
   - Configuring `mySettings.yaml`
   - Adding `mySettings.yaml` along with the YAML schema to VSCode
 
- To install latexindent, please have a look at Section 3 of the manual (Version [3.20.3](https://ctan.math.ca/tex-archive/support/latexindent/documentation/latexindent.pdf))
- To install the YAML extension (by Red Hat), please go to [YAML Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
- Now, we need to configure the default rules of latexindent
  - Go to the default rules that are found in the [`defaultSettings.yaml`](https://github.com/cmhughes/latexindent.pl/blob/main/defaultSettings.yaml) file and copy/paste the text
  - Place the text into a new file named `mySettings.yaml` that you create yourself
    - This file will be used later, place it in some appropriate location
  - We need to add our custom verbatim environments
    - In `mySettings.yaml`, <kbd>CTRL</kbd> + <kbd>F</kbd> and search for `verbatimEnvironments:`, it should have the following (around line 110):
```
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1
```

- We can add our environment below the three default environments (remember the indentations):
```
verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1
    code: 1
    mycenteredText: 1
```
- Save it and our file is complete
- To add it to VSCode, we need to use the latexindent schema (explained in [Section D](https://ctan.math.ca/tex-archive/support/latexindent/documentation/latexindent.pdf))
- In case your LaTeX distribution is up to date, it should be there by default, otherwise, download [`latexindent-yaml-schema.json`](https://github.com/cmhughes/latexindent.pl/blob/main/documentation/latexindent-yaml-schema.json) and place it somewhere appropriate
  - My MacOS path is given under `/usr/local/texlive/2022/texmf-dist/doc/support/latexindent/latexindent-yaml-schema.json`
  - Note that you might have `2021` or `2023` instead of `2022`
- In VSCode, go to `settings.json` and place the following:
```
{
  yaml.schemas": {
    "<path to latexindent-yaml-schema.json>": "<path to mySettings.yaml>"
  },
}
```
In my case, it is:
```
{
  "yaml.schemas": {
    "/usr/local/texlive/2022/texmf-dist/doc/support/latexindent/latexindent-yaml-schema.json":
    "/Users/maysara/Documents/yamlfiles/mysettings.yaml"
  },
}
```

The last thing to do is to add the arguments for VSCode, which are given as:
```
"latex-workshop.latexindent.args": [
    "-c",
    "%DIR%/",
    "%TMPFILE%",
    "-l=<path to mysettings.yaml>",
  ],
```
For me, all of the added code in `setting.json` is:
```
{
  "yaml.schemas": {
    "/usr/local/texlive/2022/texmf-dist/doc/support/latexindent/latexindent-yaml-schema.json":
    "/Users/maysara/Documents/yamlfiles/mysettings.yaml"
  },
  "latex-workshop.latexindent.args": [
    "-c",
    "%DIR%/",
    "%TMPFILE%",
    "-l=/Users/maysara/Documents/yamlfiles/mysettings.yaml",
  ],
}
```
**Bonus:** you could also define an inline verbatim command, such as `verb`, under `verbatimCommands:` in `mysettings.yaml`. Restart VSCode and it *should* work. Good luck!

**Comment by James-Yu** [comment]
That's the true spirit of internet and community! Thank you!
