### ISSUE TITLE
Use `\documentclass[]{}` instead of `\begin{document}` to detect root

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3739]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- This FR is indeed inspired from the discussion in #3735 . Currently we are using `\begin{document}` to detect root. Overleaf, for example, [uses `\documentclass` instead](https://www.overleaf.com/learn/how-to/Set_Main_Document).
- I want to initiate a short discussion on which one might be better. Currently I am a bit inclined on the documentclass solution.

## The Solution*
> _Please provide a solution you would like to have._
- Use `\documentclass[]{}` instead of `\begin{document}` to detect root, as that will more commonly appear in the real root.

## Anything Else?
> _Add any other context about the feature request below._
- May I have your thoughts on this @jlelong ? Many thanks!

**Comment by jlelong** [comment]
I cannot  see any drawback to switch to detecting `\documentclass` rather than `\begin{document}`. I think it is worth testing as it should help in projects with complex structures. I am positive on this change.
