### ISSUE TITLE
Linter squiggles in wrong place if text uses tabs instead of spaces

### ISSUE THREAD

**Issue by tehKaiN** [James-Yu/LaTeX-Workshop#374]
### Description

When using tabs instead of spaces as indents, linter squiggles appear in wrong place.

### How to reproduce

1.  Create empty tex document
2. Set tab size to 2
3. Write tab-indented paragraph with single dash inside it

### Expected behavior

`[ChkTeX] 8` squiggles should appear directly beneath dash.

### Actual behavior

`[ChkTeX] 8` squiggles will appear 7 chars after dash.

### Additional Information

Tested with texlive on vscode x64 + win10 x64

**Comment by James-Yu** [comment]
It seems to be a `chktex` problem, which considers `tab` as one char instead of multiples. Sorry but there's no obvious workaround or fix on the extension side.
