### ISSUE TITLE
Syntax Highlighting does not work after \lstinline in same line.

### ISSUE THREAD

**Issue by SabicAlija** [James-Yu/LaTeX-Workshop#375]
### Description
When using `\lstinline{}` commands, syntax highlighting is apparently turned off.

### How to reproduce

Write the following text in the same line:

Use class `\lstinline{Integer}` to wrap `\lstinline{int}` values in object instances.

### Expected behavior
When `\lstinline{}` is used, LaTeX syntax hightlighting should be turned on, after the closing curly bracket.

**Comment by James-Yu** [comment]
`lstinline` is generally unsupported in syntax highlight, since it is unrealistic to include all possible language highlights in a LaTeX extension. This is a common practice for textmate syntax highlighter. Sorry to let you down.

**Comment by SabicAlija** [comment]
Never mind. Thank you for your great vscode extension. I like it a lot.

Just to avoid misunderstandings, here's what I've ment:

![image](https://user-images.githubusercontent.com/13609768/36603352-bfd68ea0-18ba-11e8-80eb-acc230abb159.png)


You see, the first appearance of \lstinline{} is actually highlighted correctly. But when it appears a second time in a line, it isn't recognized or highlighted correctly.
