### ISSUE TITLE
Change Style of Hints

### ISSUE THREAD

**Issue by mfeuerle** [James-Yu/LaTeX-Workshop#3750]
I typically get many notes from Ltex (more than 100 is common), as it does struggle with math dominated files a bit. This makes it really annoying to identify actual useful notes, e.g. Overfull \hbox.

![Bildschirmfoto von 2023-02-28 18-36-19](https://user-images.githubusercontent.com/55590262/221932937-e47b9c57-5ba9-41ae-b5b3-a90234ab9d6b.png)

Thus, i would like to change the appearance of Ltex to "hint" instead of "information", since i would like to see them in the editor, but not be flooded in the list of relevant Errors, Warnings or Informations. 

Unfortunately, the appearance of Hints in the editor is just barely recognizable with the three light gray dots. 

![Bildschirmfoto von 2023-02-28 18-30-31](https://user-images.githubusercontent.com/55590262/221931662-8af42141-66d9-45c6-8d36-b0a1b4be1646.png)

I would like to change the style of Hints (e.g. to a small green underline, comparable to the wavy blue underline for Information).

**I would thus request a feature, to change the style of hints.**

**Comment by James-Yu** [comment]
Obviously, your issue is related to LTeX, not this extension (LaTeX Workshop).

If you want to hide underfull/overfull box messages, you may consider use `latex-workshop.message.badbox.show`.

**Comment by mfeuerle** [comment]
I don't think this issue is Ltex related. I can change the setting of Ltex, such that all suggestions from Ltex appear as Error, Warning, Information or Hint.

https://valentjn.github.io/ltex/settings.html#ltexdiagnosticseverity

But i assume the style, how these messeges are highlited in the editor is controled by the latex workshop extension.
