### ISSUE TITLE
'latexmk' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by FlyingFaller** [James-Yu/LaTeX-Workshop#3752]
Running VSCode on Windows 11. I installed Latex Workshop through the VSCode Marketplace and get the following error when I try to compile a .tex document. `'latexmk' is not recognized as an internal or external command,
operable program or batch file.`

It appears to me that my system path is unchanged so latexmk is not being picked up. What I can't figure out is what I need to add to the path. Documentation says this step should be handled automatically for Windows and provides no further information about the Windows path should that not occur. 

Apologies if this is not the right place to receive support. Thanks.

**Comment by James-Yu** [comment]
Please search for the issue before creating a new one.

**Comment by Stanley-Michael** [comment]
searching "latexmk not recognized" only comes up with this thread. It may be more beneficial to post a solution here.
