### ISSUE TITLE
Keyboard shortcuts for back/forward when PDF viewer is in focus

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#3756]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

As far as I'm aware, there is no way to go back/forward in the PDF viewer without manually clicking the buttons. The shortcuts here work for other things https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts but there is no button listed for back/forward. Presumably because pdf.js is typically embedded in a web browser, and uses whatever hotkey the browser does.

This is a nice thing to have when following links created by hyperref, or combined with synctex.

I apologize if there already is a way to do this. I tried to look through the documentation, but couldn't find anything

## The Solution*
> _Please provide a solution you would like to have._

Add keyboard shortcuts for this.

I suggest Backspace for back and Shift+Backspace for forward as a default. That's what Sumatra PDF uses.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
#3731

**Comment by Enivex** [comment]
> #3731 

Wow, I searched for various things trying to find a relevant issue. Can't believe I missed that one.

Might wanna document these shortcuts to prevent others from asking the same questions.

**Comment by Enivex** [comment]
@James-Yu I've tried Ctrl+Left/Right on Windows, but they don't seem to do anything for me. Alt +Left/Right does, but then I run into the same problem the other person had.
