### ISSUE TITLE
Formatting failed error

### ISSUE THREAD

**Issue by michaelaye** [James-Yu/LaTeX-Workshop#376]
### Description
When I activate globally "editor.formatOnSave" (as is done for a while it seems in VSCode), I get this error, everytime I save a Latex file:

<img width="1355" alt="screenshot 2018-01-12 13 53 36" src="https://user-images.githubusercontent.com/69774/34894831-2b75a13c-f7a0-11e7-9ba5-f24f23153029.png">

I suspect this has something to do wit the fact that I need to enable "formatOnSave" on a global level now, to have it working for my Python programming.

I guess your package does not support formatting, which is why I get this error?

I deactivated the error message by adding this language-specific setting to my settings, like so:

```json
    "[latex]": {
        "editor.formatOnSave": false,
    }
```

So, I'm fine, I was just wondering if there is actually automatic formatting available for this extension somehow? I will close this issue immediately, but wanted to create the issue for somebody else to find.

**Comment by zoehneto** [comment]
This extension actually supports formating using latexindent if you have it installed. The log should explain why it didn't work.

**Comment by michaelaye** [comment]
and how do i find that mysterious log? ;)

**Comment by zoehneto** [comment]
You can find it by clicking on `View` -> `Output` in the menu and then selecting `LaTeX Workshop` from the dropdown on the right. It should have an entry starting with `Formatting failed: ` and the error message.

**Comment by thedadams** [comment]
I am having this same issue now after using the extension for some time. I have latexindent installed and the Output has no information in it.

**Comment by quicky84** [comment]
I have the same problem as the previous speaker: `latexindent` is set up, formatting fails, there is no mentioning `Formatting failed:` in the output. I use MiKTeX 2.9 and the following config as advised in the plugin docs:
```
"latex-workshop.latex.toolchain": [
        {
            "command": "texify",
            "args": [
                "--synctex",
                "--pdf",
                "--tex-option=\"-interaction=nonstopmode\"",
                "--tex-option=\"-file-line-error\"",
                "%DOC%.tex"
            ]
        }
    ]
```

**Comment by quicky84** [comment]
All right I found the problem. `latexindent` is distributed as a perl script while on Win you need an `exe` file. Thus:
1. Download a zip distro of the package from [CTAN](https://www.ctan.org/pkg/latexindent)
2. Rename the `latexindent` folder to whatever you like, then create another `latexindent` folder and place the contents of the zip file there.
3. Disable `formatOnSave` for `tex` files as pointed out in the first post, i.e.,
```
"[latex]": {
    "editor.formatOnSave": false,
}
```

4. Configure the toolchain, mine looks as follows:
```
        "latex-workshop.latex.toolchain": [
        {
            "command": "c:/...path.../latexindent/latexindent.exe",
            "args": [
                "-w",
                "-s",
                "%DOC%"
            ]
        },
        {
            "command": "texify",
            "args": [
                "--synctex",
                "--pdf",
                "--tex-option=\"-interaction=nonstopmode\"",
                "--tex-option=\"-file-line-error\"",
                "%DOC%.tex"
            ]
        }
    ]
```
5. Optionally specify in `defaultSettings.yaml` or your own conf file that you want one backup and whatever else you like to change.

**Comment by zoehneto** [comment]
Do you see `Can not find latexindent in PATH!` in the extension log? As you said, the formatter implementation currently expects latexindent to be available as an exe file in your path on [windows](https://github.com/James-Yu/LaTeX-Workshop/blob/f95c86f05f406dca3b512059445cc4c01299f293/src/providers/latexformatter.ts#L23). If MiKTeX always distributes latexindent as a perl script then I could change the implementation to consider that. Then you won't have to make any changes to your toolchain and could use format on save.

**Comment by quicky84** [comment]
I've been looking for `Formatting failed:` as you suggested earlier. That's not in the log.

`latexindent` is in my `PATH`, but it's a different `latexindent` than the one I used in the config! The former weighs 11kb while the latter 11MB. If I replace `latexindent` in the config (as I posted above) with the one I have in `PATH`, the toolchain fails with the message
```
latexindent.exe: The script engine could not be found.
latexindent.exe: Data: scriptEngine="perl.exe"
```

There is something fishy with MiKTeX. Apparently the small `latexindent` in `PATH` is just wrapper calling per interpreter.

**Comment by thedadams** [comment]
I am working with TeXLive on macOS, so I don't think the above fix works for me.

I currently have `editor.formatOnSave` set to `false` so that the error won't pop up.

**Comment by quicky84** [comment]
you can still try to fall back on installing the perl interpreter and either it will work as is or employ approach similar to mine.

**Comment by zoehneto** [comment]
There are two possible log messages: if the extension can't find latexindent at all (possible issue with MiKTeX) you should see `Can not find latexindent in PATH!` in the extension log. If latexindent is found in the PATH but doesn't work (for example if some perl modules are missing on linux) you should see `Formatting failed:` in the log with latexindents  error message. Please check which one applies to you.

**Comment by thedadams** [comment]
Neither of those applies to me because the output log is empty (see my comment above).

**Comment by zoehneto** [comment]
If you don't use `editor.formatOnSave` you can open your latex file you want to format, right click on the content and select `Format Document`. You should then see the result in the log.

**Comment by quicky84** [comment]
Neither of those applies to me either. As I said `latexindent` _is_ in my `PATH` but it is apparently just a wrapper around the perl script and it does not work if executed in command line.  `Format Document` fails with no output except the aforementioned error pop-up.

PS: Win 7, MiKTex 2.9.

**Comment by zoehneto** [comment]
Do you use Latex Workshop 3.12.1 or later (logging for formatting was added with 3.12.1) ? Latexindent in your PATH means `latexindent.exe` in your path and found by the `where` command on windows, otherwise the extension won't recognize it.

**Comment by zoehneto** [comment]
So I just installed MiKTeX on Windows to reproduce this issue. Here is how I got it to work:
- According to [this](https://tex.stackexchange.com/a/158797) StackExchange post, MiKTeX stopped distributing Perl a couple of years ago so you will need to download and install Perl from [here](https://www.activestate.com/activeperl/downloads)
- Then you need to install the `latexindent` package using the MiKTeX Package Manager
- Afterwards you have to install the missing perl modules from cpan using `cpan` on the command line. In my case those were `Log::Log4perl `, `Log::Dispatch::FileShared`, `YAML::Tiny` and `Unicode::GCString` (the exact missing packages can be found by executing the formatter a mentioned above and checking the log)
- At last there was one bug I found which I will submit a PR for shortly

**Comment by quicky84** [comment]
Thanks for looking into that. As I said `latexindent.exe` _is_ in my `%PATH%` and the corresponding file _is_ an exe file, but it weighs only 55 kb and fails with 
```
latexindent.exe: The script engine could not be found.
latexindent.exe: Data: scriptEngine="perl.exe"
```
So, I assume, it requires the modules that you listed above.

The exe file that one extracts from the `latexindent` package downloaded from CTAN is 11 MB and it works as is. So there are 2 options: stick to my fix, or replace the original `latexindent.exe` (found with `where`) with the one from CTAN.

**Comment by zoehneto** [comment]
I would guess that the latexindent in your PATH is the one provided by MiKTeX or the placeholder provided by MiKTeX (this would require you to install perl as described above). It would be interesting whether format on save works if you delete the latexindent provided by MiKTeX and add the one you downloaded to the PATH. If this works one possible solution would be to provide a config option for Latex Studio to specify the directory where latexindent is installed.

**Comment by quicky84** [comment]
I wrote exactly this a couple of messages ago.
I would rather have it configurable in Latex Studio.

**Comment by zoehneto** [comment]
I will look into adding a config option. Your message described a workaround using the toolchain though and I was interested whether the detection would work if you have the downloaded version in your PATH. With a config option this won't be an issue though so it might be the best solution for Windows.

**Comment by zoehneto** [comment]
I've created a PR for the config option, so once PRs #381 and #383 are merged you can set the config option `latex-workshop.latexindent.path` to point your downloaded latexindent package and the formatting should work on save and with standard vs code methods instead of requiring you to add it to the toolchain.

**Comment by zoehneto** [comment]
@quicky84 James just released a new version which contains the fixes described above. Could you please test whether the issue is now resolved?

**Comment by quicky84** [comment]
I am afraid I can't as I moved from win to mac.

**Comment by yenWu** [comment]
@thedadams , can u format ur code? (Not saving after formatting) Or u already solved it? It seems it's just one case of failure.

I'm a Mac User too. My issue is unable to format codes. As @quicky84 said, the problem might be in `latexindent` not `LaTeX-Workshop`. Here is my error message:
```
[18:36:40] Formatting failed: Command failed: latexindent -c "/Users/yenWu/git/report-poly" "/Users/yenWu/git/report-poly/__latexindent_temp.tex" -y="defaultIndent: '    '"
Can't locate File/HomeDir.pm in @INC (you may need to install the File::HomeDir module) (@INC contains: /usr/local/texlive/2017/texmf-dist/scripts/latexindent /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 23.
BEGIN failed--compilation aborted at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/GetYamlSettings.pm line 23.
Compilation failed in require at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 19.
BEGIN failed--compilation aborted at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 19.
Compilation failed in require at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
BEGIN failed--compilation aborted at /usr/local/texlive/2017/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
Compilation failed in require at /Library/TeX/texbin/latexindent line 27.
BEGIN failed--compilation aborted at /Library/TeX/texbin/latexindent line 27.
``` 

If so, here is a shortcut.
```
sudo cpan Unicode::GCString
sudo cpan App::cpanminus
sudo cpan YAML::Tiny
sudo perl -MCPAN -e 'install "File::HomeDir"'
```

More details u can found in this [issue](https://github.com/Glavin001/atom-beautify/issues/1792) in [Atom-beaultifier](https://github.com/Glavin001/atom-beautify).

**Comment by thedadams** [comment]
@yenWu Yes, I fixed it. I was missing some perl modules. Thanks for checking.

**Comment by him229** [comment]
Encountered the same problem on Mac. Here are the packages I installed to make it work. 

```
sudo cpan Log::Log4perl
sudo cpan Log::Dispatch
sudo cpan YAML::Tiny
sudo cpan File::HomeDir
sudo cpan Unicode::GCString
```

**Comment by drmattprior** [comment]
Installed all these packages and get the error 

> Cannot write to 'indent.log': Permission denied at /Library/Perl/5.18/Log/Dispatch/File.pm line 100.

**Comment by yzy1996** [comment]
Solution is that : "latex-workshop.latexindent.path" in vs code settings you can change to your path ,just like this 
`"latex-workshop.latexindent.path": "C:\\Users\\Jerry\\Downloads\\latexindent\\latexindent.exe"`

Before of this, you should download latexindent.exe from [latexindent](https://ctan.org/tex-archive/support/latexindent?lang=en) . I find that installing from MikTeX console packages isn't working, so you'd best installed by yourself.

**Comment by gavinxgu** [comment]
> File::HomeDir



> Encountered the same problem on Mac. Here are the packages I installed to make it work.
> 
> ```
> sudo cpan Log::Log4perl
> sudo cpan Log::Dispatch
> sudo cpan YAML::Tiny
> sudo cpan File::HomeDir
> sudo cpan Unicode::GCString
> ```



> Encountered the same problem on Mac. Here are the packages I installed to make it work.
> 
> ```
> sudo cpan Log::Log4perl
> sudo cpan Log::Dispatch
> sudo cpan YAML::Tiny
> sudo cpan File::HomeDir
> sudo cpan Unicode::GCString
> ```
In my case, File::HomeDir needs force install
```
sudo cpan -fi File::HomeDir
```

**Comment by adam-erickson** [comment]
Thank you, @him229! Your solution worked for me for MacOS.

**Comment by MohamedAlFahim** [comment]
@adam-erickson Provided you already have latexindent installed on your system, In Visual Studio Code's settings, go to `Latex-workshop > Latexindent: Path`, then set the path to something like "/usr/local/texlive/2018/texmf-dist/scripts/latexindent/latexindent.pl". hope this helps. 😄
