### ISSUE TITLE
Real time synchronization

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#3762]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

Synctex currently has to be manually triggered

## The Solution*
> _Please provide a solution you would like to have._

Recently, I discovered this vscode extension. It seems to use synctex to continuously synchronize the .tex file and preview. Scrolling either will scroll the other as well.

https://github.com/matjp/latex-preview

This would be a nice feature to have as an option in Latex Workshop 

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
This sounds to be a good thing, but the performance (not time performance) can be quite tricky. Consider a multi-file project with auto scrolling on, jumping between different files can be confusing.

Despite that, thanks for the feature suggestion. I will keep it in mind in case a more elegant solution can be discovered.
