### ISSUE TITLE
Trying to expand a suggestion inside an other one fails

### ISSUE THREAD

**Issue by hjr1990** [James-Yu/LaTeX-Workshop#3764]
I am using VSCode with LaTeX Workshop extension for writing LaTeX. I am a big fan of its helpful shortcuts for math symbols. But recently, the shortcuts began exhibiting a nagging bug that isn't critical to workflow, but is very inconvenient.

So, for example, when I type "@ a" (the space between @ and a is to avoid tagging random people here) and press enter, I get "\alpha". But, if I first type (say) "@(" (which gives me "\left( \right)" and then type "@ a" and press enter, the program does not convert it to "\alpha"; instead the enter key puts me to the next line. So after typing "@(", I need to press esc first and then type "@ a" to get my "\alpha".

Example:
typing "@(, Enter, @ a, Enter" gives
"\left( @ a
\right)"

typing "@(, Enter, esc, @ a, Enter" correctly gives
\left( \alpha \right)

This did not use to be the case. But it recently started occurring with any shortcut that places me inside a bracket (such as \\( -> \\( \\), @/ -> \frac{}{}, @ 2 -> \sqrt{}, @ I -> \int_{}^{}, etc.); any subsequent shortcut without pressing esc is ignored as above. Since there are so many such shortcuts that I use on a daily basis, the esc requirement is becoming a small but quite incessant distraction.

Is this a bug? Or is there some setting configuration that I accidentally changed that is causing this?

Thanks,
HJR

**Comment by jlelong** [comment]
This is mostly not related to the extension but rather to a change in VS Code. It seems to be the same as https://github.com/microsoft/vscode/issues/176439

It seems that deactivating `editor.suggest.snippetsPreventQuickSuggestions` temporary solves the issue until it gets fixed properly.

**Comment by hjr1990** [comment]
Thank you for the quick reply. It works!

**Comment by jlelong** [comment]
Well, actually it is not really solved. This setting has been around for long and it used to work. So, it is likely that something is broken in VS Code 1.76.0.
