### ISSUE TITLE
Option to use snippets in math enviroment as default

### ISSUE THREAD

**Issue by cang-ming** [James-Yu/LaTeX-Workshop#3766]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

For example, when I want to input this line:
$ q2-\frac{\pi}{2} $

I have set a snippet to replace `freak` into `\frac{$1}{$2} `, but in `$ $ ` environment, I need to press `ESC` firstly, then the hint can jump out and let me press enter to trigger this snippet.

Then when I need to use snippets in the first bracket of \frac{}{}, I need to press ESC again...That makes things really disturbing. 

## The Solution*

provide an option in the settings, let us be able to use snippets by default in the math environment

## Anything Else?

Hope not to bother!

**Comment by jlelong** [comment]
I am not sure to understand but it looks similar to #3764
