### ISSUE TITLE
can not view pdf in VSCode tab

### ISSUE THREAD

**Issue by liliw27** [James-Yu/LaTeX-Workshop#3780]
<img width="1512" alt="WechatIMG773" src="https://user-images.githubusercontent.com/43234270/226377135-21e392d1-3841-4a32-917c-680bb3a768f5.png">
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [macOS Monterey 12.3.1]
- Visual Studio Code Version: [1.52.1]
- LaTeX Workshop Version: [8.19.2]
- TeX Distribution Version: [MacTeX 2023]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- When I use latex in vs code, the XeLaTeX successfully complies but the generated pdf file can not be viewed in the VSCode tab, while it can be viewed in the browser or other external viewer.
- 
<img width="1511" alt="issue" src="https://user-images.githubusercontent.com/43234270/226382667-9c4f3267-a668-41c8-81b2-01812d93304d.png">

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. 
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- the pdf can be viewed on time when the tex file is complied
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/Users/PSUN/Library/CloudStorage/OneDrive-TheHongKongPolytechnicUniversity/WangLi/Work/PaperWriting/crowdsourcing/submission/manuscript/hello.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-24> (/usr/local/texlive/2022/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/size10.clo)) (/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-xetex.def (|extractbb --version))
No file hello.aux.
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/ts1cmr.fd) [1] (./hello.aux) )
Output written on hello.pdf (1 page).
SyncTeX written on hello.synctex.gz.
Transcript written on hello.log.
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:829
contextKeyService.ts:420 Element already has context attribute
w @ contextKeyService.ts:379
notificationsAlerts.ts:40 Cannot disable 'Jupyter' extension alone. 'Python' extension depends on this. Do you want to disable all these extensions?
onDidChangeNotification @ notificationsAlerts.ts:36
(anonymous) @ breadcrumbsModel.ts:294
fire @ event.ts:525
addNotification @ notifications.ts:171
notify @ notificationService.ts:68
prompt @ notificationService.ts:148
(anonymous) @ extensionsWorkbenchService.ts:1043
checkAndSetEnablement @ extensionsWorkbenchService.ts:1043
promptAndSetEnablement @ extensionsWorkbenchService.ts:1043
setEnablement @ extensionsWorkbenchService.ts:874
run @ extensionsActions.ts:1184
runAction @ actions.ts:184
run @ actions.ts:184
runAction @ contextmenuService.ts:169
click @ contextmenuService.ts:89
c @ globals.ts:88
onceWrapper @ events.js:313
emit @ events.js:223
onMessage @ electron/js2c/renderer_init.js:139
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: connect ECONNREFUSED 127.0.0.1:7890
t.log @ console.ts:112
console.ts:137 [Extension Host] stack trace: Error: connect ECONNREFUSED 127.0.0.1:7890	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
t.log @ console.ts:112
log.ts:197   ERR connect ECONNREFUSED 127.0.0.1:7890: Error: connect ECONNREFUSED 127.0.0.1:7890
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
3notificationsAlerts.ts:40 Recipe terminated with error.
onDidChangeNotification @ notificationsAlerts.ts:36
<img width="556" alt="consolelog" src="https://user-images.githubusercontent.com/43234270/226382068-f8975eed-8934-43e1-8223-7af024ac7f64.png">

```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by BLACKSWORD0** [comment]
Same issue. When I open the tab pdf viewer, my vscode will stuck . I have to force quit.
 My system version is macos Monterey 12.6.3. ,   vscode  version is 1.76.2.  ,    latex workshop version is v9.7.0.

**Comment by jlelong** [comment]
Have you checked https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#the-pdf-viewer-is-blank-or-has-graphical-glitches

@liliw27 Can you check if you can view the PDF file in Firefox? We rely on the same rendering engine as Firefox.

**Comment by liliw27** [comment]
Thanks, Jerome @jlelong. Restart VScode with 'code --disable-gpu' works well for me!
