### ISSUE TITLE
%OUTDIR% should be used in the default `pdftlatex -> bibtex -> pdflatex -> pdflatex` recipe

### ISSUE THREAD

**Issue by floringogianu** [James-Yu/LaTeX-Workshop#3781]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
- I noticed that by default the `pdftlatex -> bibtex -> pdflatex -> pdflatex` recipe was not using `%OUTDIR%`, the custom build directory. I suppose `%OUTDIR%` should be supported by all the default recipes.

## The Solution*

After a bit of research it turned out that only some small changes are required to the default tools. Not sure though if this is the best way to go about it. If it is though, I can turn it into a pull request.

```json
    "latex-workshop.latex.recipes": [
        {
            "name": "pdflatex + bibtex (OUT)",
            "tools": [
                "pdflatexOut",
                "bibtexOut",
                "pdflatexOut",
                "pdflatexOut"
            ]
        },
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "pdflatexOut",
            "command": "pdflatex",
            "args": [
                "-output-directory=%OUTDIR%",  // tell pdflatex where the source tex is
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ],
            "env": {}
        },
        {
            "name": "bibtexOut",
            "command": "bibtex",
            "args": [
                "%OUTDIR%/%DOCFILE%"  // tell bibtex where the source is
            ],
            "env": {}
        },
    ],
```

In my project I then have:

```
.
├── bibliography.bib
├── build
│   ├── main.aux
│   ├── main.bbl
│   ├── main.blg
│   ├── main.log
│   ├── main.pdf
│   ├── main.spl
│   └── main.synctex.gz
├── some_template.dtx
├── some_bibliography_style.bst
├── main.tex
```
And in `main.tex` things stay the same:

```
\bibliographystyle{some_bibliography_style} 
\bibliography{bibliography}
```

Hope this helps. Let me know if this should be a pull request for the defaults of `pdftlatex -> bibtex -> pdflatex -> pdflatex`, since probably all recipes should respect `OUTDIR`.

## Anything Else?
- Nope

**Comment by jlelong** [comment]
The bibtex tool does not always work well when it is not called directly from the directory containing the `.aux` and `.bib` files. So I am not in favour of tweaking the recipe. I am converting this issue into a conversation in case anyone is interested by your solution.

Note that all this is properly handled by `latexmk`, which is probably the best way to go.
