### ISSUE TITLE
Auto-linking DOIs

### ISSUE THREAD

**Issue by janheinrichmerker** [James-Yu/LaTeX-Workshop#3782]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
- URLs in `.bib` files can be opened with Ctrl+click. It would be usefful to have the same function for DOIs, to check for broken links.

## The Solution*
- Ctrl+click on a DOI in a `.bib` file should open `https://doi.org/...` in the default browser.

**Comment by heinrichreimer** [comment]
Totally understood. Thanks anyway for this great extension!
