### ISSUE TITLE
Keeping focus on the editor after "SyncTeX from cursor"

### ISSUE THREAD

**Issue by Dilemian** [James-Yu/LaTeX-Workshop#3784]
I'm using SumatraPDF as an external viewer, and whenever I use "SyncTeX from cursor" from the editor, the focus on the editor gets lost (it moves to SumatraPDF) and I can't keep editing the tex file.

Is this intended? Is there a way to not lose focus on the editor after "SyncTeX from cursor"?

**Comment by jlelong** [comment]
I am afraid we have no control on this from the extension side. This is mostly handled by the OS or maybe even the viewer app itself. The function _SyncTeX from cursor_ only calls the command `latex-workshop.view.pdf.external.synctex.command` with the arguments `latex-workshop.view.pdf.external.synctex.args`.

When viewing the PDF file in a browser, the browser does not grab focus when _synctex from cursor_ is called.
