### ISSUE TITLE
Feature request: Synchronised scrolling for preview and source file

### ISSUE THREAD

**Issue by tillahoffmann** [James-Yu/LaTeX-Workshop#379]
Would it be feasible to implement synchronised scrolling for the source file and the PDF preview similar to https://github.com/Microsoft/vscode/issues/5047?

**Comment by James-Yu** [comment]
It can be problematic. For instance, the PDF file may have two columns. Also it requires a very frequent `synctex` execution, which can be overwhelming to some low-end computers.

I'd like to see what the community think of this feature.

**Comment by DRempfer** [comment]
Not feasible, I think. In addition to the multicolumn issue, consider the placement of LaTeX floats: You may end up randomly jumping around in your source while going over these. The mapping between linear source and pdf file location is, in general, not linear.

**Comment by AllanWang** [comment]
One thing that may be preferred is to automatically call syntex after a rebuild. However, I do agree that synchronized scrolling may be problematic. Even the markdown one isn't incredibly accurate when the contents is beyond plain text

**Comment by tillahoffmann** [comment]
Very good points! I hadn't thought about the subtleties.

**Comment by marnunez** [comment]
+1 to automatically call syntex after rebuild. Shall I create this as a new enhancement proposal?

**Comment by jlelong** [comment]
Set `latex-workshop.synctex.afterBuild.enabled` to `true`.
