### ISSUE TITLE
add *.xdv to latex-workshop.latex.clean.fileTypes by default

### ISSUE THREAD

**Issue by ZhuangQu** [James-Yu/LaTeX-Workshop#3793]
The feature request has not been suggested in this repository.

## The Missed
XeLaTeX creates `.xdv` files. When I set `latex-workshop.latex.autoClean.run`, it helps me clean up all junk files except `*.xdv`. To clean fully, I have to add `*.xdv` to `latex-workshop.latex.clean.fileTypes`. This will copy all `latex-workshop.latex.clean.fileTypes` list to my `settings.json`, which make it too long.

## The Solution
Add `*.xdv` to `latex-workshop.latex.clean.fileTypes` by default.

**Comment by James-Yu** [comment]
We don’t support request on modifying default config.
