### ISSUE TITLE
Rootfile-detection-mechanism error

### ISSUE THREAD

**Issue by JannisZeller** [James-Yu/LaTeX-Workshop#3797]
Hello everybody. I have the following problem occurring (only) in the newest version 9.8.1. 

### Minimal example: 
I have a main file `main.tex` in my root folder and an outsourced praeambel in the `parts` subdir. The structure is
```
root/
├──main.tex
├── parts/
│   ├──test.tex
```
The file contents are
```
# main.tex
\input{./parts/test.tex}
\begin{document}
Test
\end{document}  

# test.tex
\documentclass[]{article}
```
When trying to build the project, `test.tex` seems to be recognized as the root file and errors are thrown because there is no `\begin{document}` in there (at least as far as I understand the latex-typical cryptic error messages).

Adding `"latex-workshop.latex.search.rootFiles.exclude": ["./parts/test.tex", "test.tex"]` to the workspace settings did not fix the problem. 

It seems to work if I put the `\documentclass[]{article}` line to `main.tex`. If the project is then the built once, it works fine - even when putting the `\documentclass[]{article}` back to  `test.tex` - until the auxiliary files are removed, then the error is back.
*Edit:* For this to work, the project has to be closed and re-opened after switching the documentclass-line, which is why I suspect this behavior is not intended.

Is this behavior with the rootfile-detection-mechanism being dependent on the documentclass-declaration intended and I missed some update or is that an actual error?

Working on Windows 11, VSCode v. 1.76.

**Comment by jlelong** [comment]
We used to detect the root file based on the presence of `\begin{document}`.  Since version 9.8.0, we have been relying on the `\documentclass` statement to detect the root file just as overleaf is doing. We think this approach is more robust.

**Comment by jlelong** [comment]
Btw, the wiki has not been updated to reflect this change. I will do shortly

**Comment by JannisZeller** [comment]
Alright, thank you for the fast reply! I did not notice the switch and was looking at the outdated wiki. I will remanage my projects accordingly.

Thanks again and keep up the great work!

**Comment by BerriJ** [comment]
Sorry to bother you. However, with the latest 9.8.1 Release, I still have problems with the root file detection.

I created a minimal reprex.

```
exam/
├── K2_WS20182019/
│   ├── Klausur_Vorlage.tex
│   ├── Vorspann_Skript.tex <<< The file Latex_workshop tries to compile
├── K2_WS20222023/
│   ├── Klausur.tex <<< The file I want to compile
│   ├── Vorspann_Skript.tex
```

The file contents are as follows:

```
# K2_WS20182019/Klausur_Vorlage.tex

\input{Vorspann_Skript.tex}
\begin{document}
\end{document}

# K2_WS20182019/Vorspann_Skript.tex

\documentclass[11pt]{scrartcl}

# K2_WS20222023/Klausur.tex

% !TEX root = exam/K2_WS20222023/Klausur.tex

\input{Vorspann_Skript.tex}

\begin{document}

Foo

\end{document}

# exam/K2_WS20222023/Vorspann_Skript.tex

\documentclass[11pt]{scrartcl}
```

You can see in the screenshot below that Latex Workshop tries to compile a file from the `K2_WS20182019` folder, although I've set the magic root file command. 

![Bildschirmfoto vom 2023-03-27 11-42-48](https://user-images.githubusercontent.com/37799358/227907371-cbf2c748-61fb-4a8f-a0ea-544992e9fb03.png)

I've attached the exam folder.
[exam.zip](https://github.com/James-Yu/LaTeX-Workshop/files/11077197/exam.zip)

This issue should be reopened and pinned to the top so that people know about this change.

**Comment by jlelong** [comment]
@BerriJ The root file path specified as a magic comment must be either a full path or relative to the current file.
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-root-file
