### ISSUE TITLE
disabling snippets

### ISSUE THREAD

**Issue by pkozlows** [James-Yu/LaTeX-Workshop#3799]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- I am using latex workshop with the dictation software Talon voice using text navigation with Cursorless. I believe that the build in snippets in latex workshop are giving me weird behavior  when I try to use voice commands to write latex. I will be using the snippet framework that Cursorless offers instead.

## The Solution*
> _Please provide a solution you would like to have._
-  a way to disable snippets and also potentially Intellisense, so that I can use latex workshop as my .tex editor in vscode. this aspect of pagan able to use then cake is beneficial for me thru the automatic compiling I can get w/ this extension and also the ability to do latex using cursor less in vscode.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by pkozlows** [comment]
To give an example of what I mean, `insert("\\ket{{}}")` sans latex workshop is giving \ket{}, but in the latex workshop it is giving \ket, which I presume is an issue relating to the snippets.

**Comment by pkozlows** [comment]
what is odd is that `insert("\\ket{{0}}")` is giving \ket{0} as it should in the workshop.

**Comment by pkozlows** [comment]
Apologies, the above lines of code are in talonscript, which you are probably not that familiar with.

**Comment by James-Yu** [comment]
I believe you can disable the auto suggestion thing for [latex] languageid by setting a vscode config? You may try that first.

**Comment by James-Yu** [comment]
Should be `"editor.acceptSuggestionOnCommitCharacter": false` I think.
