### ISSUE TITLE
'LaTeX' vs 'latex' language ID issues

### ISSUE THREAD

**Issue by jabooth** [James-Yu/LaTeX-Workshop#38]
Following #37 I think there is a bit of a broader issue here. I then found autocompletion didn't work, and to get it to work, sure enough I had to change:
```diff
-    context.subscriptions.push(vscode.languages.registerCompletionItemProvider('LaTeX', extension.completer, '\\', '{', ','));
+    context.subscriptions.push(vscode.languages.registerCompletionItemProvider('latex', extension.completer, '\\', '{', ','));
```
I took a look at the language selection screen and see this:

<img width="604" alt="screenshot 2017-03-26 13 20 30" src="https://cloud.githubusercontent.com/assets/1312873/24331222/a833d996-1227-11e7-9138-acc1e3299dec.png">

I then realised I have the basic LaTeX language support installed:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.latex

And figured that will be making the association from `.tex` -> `latex`.

Sure enough, if I uninstall it:

![image](https://cloud.githubusercontent.com/assets/1312873/24331244/03dcea12-1228-11e7-8b93-61b3845a9051.png)

LaTeX Workshop gets it's way and chooses `LaTeX` as the language ID.

The problem is, I'm sure many other users will have the basic syntax highlighting extension installed as I did, and will run into these kinds of issues. Furthermore, the dev guide for language extensions has this to say on [Language IDs](https://code.visualstudio.com/docs/languages/overview#_language-id):

> A language identifier is often (but not always) the lowercased programming language name. Note that casing matters for exact identifier matching ('Markdown' != 'markdown').

It seems to me that it makes a lot more sense for LaTeX Workshop to continue to standardise on lower case `latex` for the language ID to match the wider vscode/latex community to avoid all these confusions and issues.

PS hope this doesn't come across really negative, as I think you've done a great job of tidying everything up in this new version! Very happy to continue contributing over the next few months whilst I'm writing my thesis 👍 :)

**Comment by James-Yu** [comment]
You really cast light on the issue! Will fix it immediately. Thanks bro!

**Comment by jabooth** [comment]
@James-Yu awesome, thanks! Loving this responsive feedback mate, makes collaborating really fun!

**Comment by James-Yu** [comment]
Hope no one get annoyed by the absurdly highly frequent updates 🤐
