### ISSUE TITLE
PDF Preview Sometimes Doesn't Work

### ISSUE THREAD

**Issue by AllanWang** [James-Yu/LaTeX-Workshop#380]
In continuation of https://github.com/James-Yu/LaTeX-Workshop/issues/181

When viewing the PDF preview in a new tab, I sometimes get the following error:

```
[09:40:10] TAB command invoked.
[09:40:10] Found root file from active editor: /home/.../notes.tex
[09:40:10] Root file remains unchanged from: /home/.../notes.tex.
[09:40:10] No PDF viewer connected for /home/.../notes.pdf
[09:40:10] Cannot establish server connection.
```

This issue seems to be on and off, in that it sometimes works and sometimes doesn't.

I'm on linux and can provide other logs upon request.

**Comment by AllanWang** [comment]
I only just noticed it now, and have yet to confirm, but this may be an issue with the network. It looks like the pdf viewer works fine when I'm at home, but not when I'm at my university.

**Comment by James-Yu** [comment]
`Cannot establish server connection` means that the websocket server cannot be created. This can be caused by multiple local configuration issues. You may want to check the linux network settings and privilege ones.

**Comment by AllanWang** [comment]
As of now I'm quite certain that it's due to my universities network? As it seems to work fine whenever I'm at home. Is there any specific setting I should be looking out for, or is there no way to use the preview in a public setting?

**Comment by AllanWang** [comment]
I was about to comment my fix and noticed that it was already done in https://github.com/James-Yu/LaTeX-Workshop/issues/401

I didn't have localhost pointing to 127.0.0.1 for whatever reason, and updating it fixed it for me.
