### ISSUE TITLE
Clean up remove _markdown_* folder

### ISSUE THREAD

**Issue by alanlivio** [James-Yu/LaTeX-Workshop#3801]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The [markdown ](https://ctan.org/pkg/markdown?lang=en) package generate auxiliary folders in the format _markdown_<file_name_with_markdown>, which is not cleaned in the LaTeX-Workshop cleaning task.

## The Solution*
> _Please provide a solution you would like to have._
- Clean _markdown_<file_name_with_markdown> like folder during LaTeX-Workshop cleaning task.

## Anything Else?
> _Add any other context about the feature request below._

**Comment by James-Yu** [comment]
latex-workshop.latex.clean.fileTypes

**Comment by alanlivio** [comment]
Thank you @James-Yu.
The `fileTypes` does not work because the `_markdown_*` is a folder. Is there a alternative?

**Comment by jlelong** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexcleanfiletypes for how to remove a folder. You basically need to remove all the files in it first.
