### ISSUE TITLE
add "--shell-escape" in default tools arguments

### ISSUE THREAD

**Issue by alanlivio** [James-Yu/LaTeX-Workshop#3802]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The "--shell-escape" is required in many cases (e.g., markdown package) but it is not in the default LaTeX-Workshop
default tools (e.g., latexmk, pdflatex) arguments.

## The Solution*
> _Please provide a solution you would like to have._
- Add  "--shell-escape" to tools arguments

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
Change your local settings.
