### ISSUE TITLE
Plugin now compiles wrong file. How to fix the assocations?

### ISSUE THREAD

**Issue by cottrell** [James-Yu/LaTeX-Workshop#3803]
I have various sections etc. But generally this use to work. Saving a file would compile the correct entry point. And then openpdf would open the correct pdf.

Looking for hints on what log to look at or what settings to try to manually fix associations.

v9.8.1

I think it's just doing some random ordering. Something with the latest update

**Comment by cottrell** [comment]
Yes, this looks like it.

**Comment by jlelong** [comment]
So, I am closing this issue. If you think there is indeed a bug, please fill in a new issue with the complete logs.

**Comment by cottrell** [comment]
Yes, I think it's the same bug as #3804

**Comment by mcmara** [comment]
All my project no longer build (and they are a lot...). I can't find a way to specify the root file. Auto-detecting it is not the best solution, especially with sym-linked shared template libraries. My document class is inside included templates.

**Comment by James-Yu** [comment]
@mcmara You can use `%!TeX root` derivative. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#multi-file-projects

**Comment by mcmara** [comment]
> @mcmara You can use `%!TeX root` derivative. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#multi-file-projects

Thank you: works perfectly in my case.
