### ISSUE TITLE
Sample templates

### ISSUE THREAD

**Issue by bishshoy** [James-Yu/LaTeX-Workshop#3814]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- N/A

## The Solution*
> _Please provide a solution you would like to have._
- N/A

## Anything Else?
> _Add any other context about the feature request below._
- https://www.overleaf.com/latex/templates

**Comment by James-Yu** [comment]
Out of scope.
