### ISSUE TITLE
macro names with non latin character are first character colored only

### ISSUE THREAD

**Issue by hubaishan** [James-Yu/LaTeX-Workshop#3818]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System:  Windows 10
- Visual Studio Code Version: 1.47.0
- LaTeX Workshop Version:  9.8.2
- TeX Distribution Version: MiKTeX 2.9.7250

## The Issue*
> _Please briefly describe the issue you come across._
-  macro names with non latin character are first character colored only 
- 
![image](https://user-images.githubusercontent.com/2285457/229487806-eb22cb15-b3a4-4712-901a-d8ac9876a805.png)

the example is
```
\def\صل{صلى الله عليه وسلم}
قال \صل 
```
-

**Comment by James-Yu** [comment]
@jlelong This looks like a syntax issue?

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#48
