### ISSUE TITLE
Wrong syntax highlighting when using option `escapeinside` of package `minted`

### ISSUE THREAD

**Issue by sjiang95** [James-Yu/LaTeX-Workshop#3822]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository. #1046
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*

- Operating System: Ubuntu 22.04.2 LTS
- Visual Studio Code Version: 1.77.0
- LaTeX Workshop Version: 9.8.2
- TeX Distribution Version: TeX Live 2023

## The Issue*
Highlighting is wrong when using `escapeinside` option of package `minted`.

### Reproduction Steps

```tex
\documentclass{article}
\usepackage{algorithm}
\usepackage{minted}
\usepackage{lipsum}
\begin{document}

\begin{algorithm}
\begin{minted}[escapeinside=||]{python}
	def func(a=|$\alpha$|): % escape $alpha$ to print the Greek alphabet
        pass
\end{minted}
\end{algorithm}

\lipsum

\end{document}
```

#### Editor

Highlighting is wrong since the user-defined delimiter.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/51251025/229703256-4b4dc68c-9f49-42ac-9e8b-d74b34e8e957.png">

#### PDF

Compiled by `pdflatex`.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/51251025/229703738-b89d3407-e580-4fe7-a968-dd0d81201662.png">

### Expected Behavior

Right syntax highlighting.

## Logs

Not applicable.

**Comment by jlelong** [comment]
Unfortunately, the grammars used by VS Code are purely static. There is no way to make it aware of escape characters.
