### ISSUE TITLE
Citation browser stop work

### ISSUE THREAD

**Issue by t-abreu** [James-Yu/LaTeX-Workshop#3824]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [* ] The issue has not been reported in this repository.
- [* ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ *] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [ Windows 11]
- Visual Studio Code Version: [e.g. 1.77.0]
- LaTeX Workshop Version: [e.g. 9.8.2]
- TeX Distribution Version: [TeX Live 2023 ]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- Before, when typing \ cite {, citation browser automatically opened and showed the reference options, now it no longer opens.
- 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. 
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- 
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by jlelong** [comment]
I cannot reproduce the issue. This is most likely an issue with the parsing of your bib file.
Please provide a minimal example and the logs of the extension.

**Comment by t-abreu** [comment]
When I select version 9.7.0 of Latex-Workshop, and use \cite{} the list of citation pop up, like image 970.
From the version 9.8.0 this list don't pop up.  I performed these tests by mutting the versions of the extension and realized this problem.
![970](https://user-images.githubusercontent.com/9003181/230158358-67801f18-2e77-46cd-b236-4276926bf09c.png)

**Comment by James-Yu** [comment]
A minimal working example is required.

**Comment by MoritzSchley** [comment]
Can confirm, having the same problem. Citation preview working on 9.7.0 but not 9.8 and upwards. If I can provide any information to help fixing this feel free to contact me.

**Comment by James-Yu** [comment]
Closed for lacking info. Will reopen if a minimal working example is provided and bug can be reproduced.
