### ISSUE TITLE
build root texx when after change the file defined in \markdownInput

### ISSUE THREAD

**Issue by alanlivio** [James-Yu/LaTeX-Workshop#3827]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
- LaTeX-Workshop builds the tex root after changing a file defined in \input. A similar behavior should happen after changing a file defined in \markdownInput (see more [here](https://www.overleaf.com/learn/how-to/Writing_Markdown_in_LaTeX_Documents)). For instance, consider the example below. I would like that the LateX-Workshop builds when changing the .md file.

```latex
% sample.tex
\documentclass{article}
\usepackage{markdown}
\begin{document}
\markdownInput{sample.md}
\end{document}
```

```markdown
<!-- sample.md-->
## Sample
sample

### Sample
sample
```

## The Solution*
- Capture root tex from \markdownInput

**Comment by James-Yu** [comment]
Please give a more informative description and sample files for your request.

**Comment by alanlivio** [comment]
Thanks, you @James-Yu. I update the issue text with some sample files as you requested.
Bests

**Comment by alanlivio** [comment]
Hi @James-Yu. I tried the recent version but this issue still persists for me using the above sample files.
I am running from it WSL. See some env info below.

```
> (Get-CimInstance Win32_OperatingSystem).version
10.0.22624
> wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22624.1470
> code --version
1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
>  code --show-versions --list-extensions|grep latex
James-Yu.latex-workshop@9.10.0
```
