### ISSUE TITLE
Auto rename paired tags of environments

### ISSUE THREAD

**Issue by gaoqiangks** [James-Yu/LaTeX-Workshop#3830]
I have an environment 
`\begin{proposition} `
    `Something.  ` 
`\end{proposition}   `

Now I want to change this proposition to a lemma.
`\begin{lemma}   `
   ` Something.   `
`\end{lemma}  ` 

I have to modify "proposition" to "lemma" twice, which is unpleasant.  Is there any way to automatically rename `\end{proposition}` to `\end{lemma}` when I change the `\begin` tag?

**Comment by James-Yu** [comment]
You can use `@command:latex-workshop.select-envname`.

**Comment by gaoqiangks** [comment]
> You can use `@command:latex-workshop.select-envname`.

Is there any way to do this automatically?  For example,  when I edit a html file, if I change an open tag, the editor will automatically change the closed tag without having to do anything else.

**Comment by James-Yu** [comment]
No, it won’t auto-change.
