### ISSUE TITLE
Make Ctrl skip over whole equation when adjacent to $

### ISSUE THREAD

**Issue by kaba2** [James-Yu/LaTeX-Workshop#3839]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Sometimes I need to copy and paste equations, and then make small changes, as when doing an equation array. To select the equation I need to either use the mouse, or slowly move to start/end by arrow keys. Using keys, pressing Ctrl+arrow will skip over words, which is faster. However, it is still not fast enough, and it is somewhat difficult to know when to stop. When I am about the skip the $ symbol at the start/end of an equation, it will just skip that. However, I would like it to skip the whole equation.

## The Solution*
> _Please provide a solution you would like to have._
- Change the behaviour of Ctrl+arrow to skip over the whole equation if it is adjacent to $.

## Anything Else?
> _Add any other context about the feature request below._

**Comment by jlelong** [comment]
You can use the commands `latex-workshop.select-envcontent` or `latex-workshop.select-env` and define your own keybinding.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#navigating-and-selecting

**Comment by kaba2** [comment]
The problem with, say, "Navigate to matching begin/end", is that I cannot combine it with Shift to select it. 

Aside, that command seems to have a bug in that it does not reach the end of an $...$ equation:

https://user-images.githubusercontent.com/2399754/231663336-b94fd6c1-4230-440e-b1b2-4db088685d84.mp4

I could also use Alt+Shift+(Left/Right) for "Expand/Shrink Selection". But that does not seem to treat an $...$ equation as an expansion level?

https://user-images.githubusercontent.com/2399754/231663125-d82e5be3-f4d1-4ff2-822a-d61754431fff.mp4

**Comment by jlelong** [comment]
As I suggested above, use "Select the current environment content" or "Select the current environment" which already perform the selection for your.

I agree that there is a negative offset when calling "Navigate to matching begin/end" with `$...$`

**Comment by kaba2** [comment]
"Select current environment" works. Thanks! I wish though I could use the "Expand selection".

"Select current environment content" does not work:

https://user-images.githubusercontent.com/2399754/231664624-22b09f3a-233c-4d44-8d17-5c007bcc53ff.mp4
