### ISSUE TITLE
`nomencl` Unable to include `makeindex` in latex workshop toolchain

### ISSUE THREAD

**Issue by bjverhoe** [James-Yu/LaTeX-Workshop#384]
### Description
Hi, I'm using the LaTeX-Workshop package for writing my Thesis, and having a genuinely great time, thanks for this!

I am trying to inlclude the [`nomencl` package](http://texdoc.net/texmf-dist/doc/latex/nomencl/nomencl.pdf) into my workflow, as it is required for me to have a list of abbreviations. I succeeded in making a list of abbreviations via the command-line. I am trying to get it into my `latex-toolchain` as part of my workflow. However for some reason the `makeindex` step is giving me problems.

### How to reproduce
For the preamble for example:
```
\documentclass{book}
\usepackage{nomencl}
\makenomenclature
\renewcommand{\nomname}{List of Abbreviations}
\begin{document}
...
\printnomenclature
...
\end{document}
```
The `nomencl` package dictates the following steps to create the nomenclature:
1. Compile with a LaTeX compiler. This will generate a `.nlo` file with the list.
2. Run `makeindex filename.nlo -s nomencl.ist -o thesis.nls`
3. Compile with a LaTeX compiler again.

These steps work for me in a command-line.

How I've tried to include it in my Toolchain:
```"latex-workshop.latex.toolchain": [
        {
            "command": "lualatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "command": "makeindex",
            "args": [
                  "%DOC%.nlo",
                  "-s nomencl.ist",
                  "-o %DOC.nls%
            ]
        },
        {
            "command": "lualatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }
    ]
``` 
I've tried other variations but to no success:
```
{
            "command": "makeindex %DOC%.nlo -s nomencl.ist -o %DOC%.nls",
            "args": [
            ]
        },
```
```
{
            "command": "makeindex",
            "args": [
                  "%DOC%.nlo",
                  "-s=nomencl.ist",
                  "-o=%DOC.nls%
            ]
        },
```

### Expected behavior
So normally I would expect the same behaviour as in the command-line
### Actual behavior

What I actually get is:
`Index style file -o=thesis.nls not found` or others like `need to include stylefile -s [..]` errors.

### Log messages
```
This is LuaTeX, Version 1.0.4 (TeX Live 2017)  (format=luatex 2017.11.11)  17 JAN 2018 18:08
 restricted system commands enabled.
**a;dfj

! Emergency stop.
<*> a;dfj
      
End of file on the terminal!

!  ==> Fatal error occurred, no output PDF file produced!
```

<details>
<summary>
```
[20:12:34] Toolchain step 2: makeindex %DOC%.nlo -s nomencl.ist -o %DOC%.nls, 
[20:12:34] LaTeX fatal error: spawn makeindex %DOC%.nlo -s nomencl.ist -o %DOC%.nls ENOENT, . Does the executable exist?
[20:12:49] Found root file from active editor: /Users/BV/Thesis/book/thesis.tex
```
</summary>
</details>

<details>
<summary>Developer Tools Console</summary>
Nothing found.
</details>

### Additional Information

**Comment by James-Yu** [comment]
You may try arguments as follows
"%DOC%.nlo",
"-s"
"nomencl.ist",
"-o"
"%DOC.nls%"

**Comment by bjverhoe** [comment]
Your suggestion gave me the following error: 
Latex Workshop output:
```
[12:42:22] Toolchain step 1: lualatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/Users/BV/Thesis/book/thesis
[12:42:29] LaTeX log parsed with 4 messages.
[12:42:29] Toolchain step 2: makeindex, /Thesis/book/thesis.nlo,-s,nomencl.ist,-o,/Thesis/book/thesis.nls
[12:42:29] Toolchain returns with error: 1/null.
```
Compiler output:
```
makeindex: Not writing to /Thesis/book/thesis.nls (openout_any = p).
Can't create output index file /Users/BV/Thesis/book/thesis.nls.
Usage: makeindex [-ilqrcgLT] [-s sty] [-o ind] [-t log] [-p num] [idx0 idx1 ...]
```
However when I changed `%DOC%` in the toolchain to `thesis` (which is the filename) the step worked fine. So this workaround is working out, but I'm wondering why the `%DOC` option is not working?

**Comment by James-Yu** [comment]
```
[12:42:29] Toolchain step 2: makeindex, /Thesis/book/thesis.nlo,-s,nomencl.ist,-o,/Thesis/book/thesis.nls
```
`%DOC%` was translated to `/Thesis/book/thesis.nlo`, which seems to be unacceptablt to `makeindex`.

You can try `%DOCFILE%` which is only the file name without extension and path.

My 2c only.

**Comment by bjverhoe** [comment]
Yep, the `%DOCFILE%` option worked as you expected. Looks like `makeindex` doesn't accept full filepaths.

**Comment by Turbjet** [comment]
I following the suggestions in this thread by adding
```
{
          "command": "makeindex",
          "args": [
            "%DOCFILE%.nlo",
            "-s",
            "nomencl.ist",
            "-o",
            "%DOC.nls%"
          ]
},
```
in the `tools`, and then in the `recipes`, I use 
```
{
        "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
        "tools": [
          "pdflatex",
          "bibtex",
          "makeindex",    <----- This is what I add
          "pdflatex",
          "pdflatex"
        ]
      },
```
However nothing happens. No nomenclature shows up. Am I doing anything wrong?

**Comment by tamuratak** [comment]
If you want to fix your problem, please open a new issue.

Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)
