### ISSUE TITLE
Server port number is undefined

### ISSUE THREAD

**Issue by aguevara** [James-Yu/LaTeX-Workshop#3844]
Observed when a second VS Code is launched from WSL2 (Ubuntu) on a different \LaTeX\ document than the first one. The second instance reports the error when trying to view PDF in tab or browser. I have 4200 set as the server port in User, Ubuntu, and Workspace for both VS Code instances. Closing the first Code frees up the port for the second and error vanishes. I found the error string in the code file `LaTeX-Workshop/src/components/server.ts` 

It took about an hour to figure out the issue, maybe something can be done to improve the experience. Ideal would be to still allow both PDFs to be viewed, "somehow". If the server cannot be shared across instances or if the port cannot be shared across servers, then perhaps reverting to a randomized port for additional instances would be better than current behavior?

**Comment by James-Yu** [comment]
Unfortunately, the server cannot be shared across instances. Setting the port number should not have more complicated logic other than setting the port number. A hint on this issue may fit in the description.
