### ISSUE TITLE
scroll/cursor sync (between tex and pdf file)

### ISSUE THREAD

**Issue by Zerotask** [James-Yu/LaTeX-Workshop#3847]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

If you edit your tex files it automatically rebuilds the PDF file but you can't see your changes directly. You have to scroll to the position.

## The Solution*
> _Please provide a solution you would like to have._

If possible, I'd like to have an option to sync the source (tex) with the output (PDF).
If I change something, it rebuilds the PDF and sets the cursor exactly at the same line as in my tex file.

Besides editing, there could be an option to sync scrolling for both files:
- you scroll in the PDF (vscode tab or browser) and it scrolls to the same position in the tex file
- you scroll in your tex file and it scrolls to the same position in the PDF file

Additionally, for people who don't like to have a scroll sync, there could be a new option in the context menu "jump to this line".
If you click on it, the output (PDF) will scroll to this line.
(this is available in an extra menu: SyncTeX from cursor, but not as a context menu (if you right-click in your tex file))

With those changes it's even easier to see your 

## Anything Else?
> _Add any other context about the feature request below._

In TeXstudio is a button you can activate to enable scroll sync

![image](https://user-images.githubusercontent.com/20150243/232604740-74bcc8b7-5dd3-4321-a6ac-9e84185bc9f0.png)

**Comment by James-Yu** [comment]
#3762 and many.
