### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by y-spreen** [James-Yu/LaTeX-Workshop#385]
Commands like `mathcal` and `overset` seem to be missing. After the first use, they are recognized, but commands like `overset` and `underset` should have suggested params `{a}{b}` like `frac` already does.

**Comment by y-spreen** [comment]
Okay, no seconds after posting it, it miraculously works? Does it take some time to initialize or something?

**Comment by James-Yu** [comment]
Yes, should be save or something. Realtime parsing requires unnecessary computing power, which is never preferred for an editor like vscode.
