### ISSUE TITLE
Pressing enter key has multiple second delay

### ISSUE THREAD

**Issue by varkor** [James-Yu/LaTeX-Workshop#3853]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: macOS 12.6.2
- Visual Studio Code Version: 1.77.3
- LaTeX Workshop Version: 9.8.2
- TeX Distribution Version: TeX Live 2021

## The Issue*
When pressing enter to create a new line, there will often be a noticeable delay (sometimes multiple seconds) before a newline is created. If new characters are typed in this time, they will appear on the old line, not the new line. This issue has been reported in the past (https://github.com/James-Yu/LaTeX-Workshop/issues/1809), but was closed as fixed.

### Reproduction Steps
It is quite difficult to figure out how to reproduce this consistently. However, on my computer, it often occurs in a large LaTeX document.

### Expected Behavior
No delay.

### LaTeX Workshop Output*
(I wasn't sure how to access this.)

### Developer Tools Console
After clearing the console, and then pressing enter, the following messages appeared:
```
 ERR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at mainThreadSaveParticipant.ts:37:18
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 Debugger attached.
log.ts:421  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:421  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
log.ts:431  WARN UNRESPONSIVE extension host: 'james-yu.latex-workshop' took 97.6% of 76.25ms, saved PROFILE here: 'file:///var/folders/m9/4r2xqx112cx3z2vj4t6pf39c0000gn/T/exthost-d39df5.cpuprofile'
```

**Comment by James-Yu** [comment]
I cannot reproduce this issue even with ~4000 line doc. I'm afraid you may need to provide a working example for debug purpose. The causes can be multitude.

**Comment by varkor** [comment]
I will try to construct a standalone example soon.

For now, I will just mention that I've noticed it's not just pressing enter that has a long delay: it also affects triggering a build, so it seems to be an issue with the entire plugin lagging rather than newlines specifically.
