### ISSUE TITLE
Additional search paths for PDF viewer

### ISSUE THREAD

**Issue by mw88-personal** [James-Yu/LaTeX-Workshop#3857]
## Pre-checks*
- [ x] The feature request has not been suggested in this repository.

## The Missed*
I am using a ``.latexmkrc`` configuration file for my latex documents, which set
~~~
$out_dir = 'build';
~~~
The internal pdf preview can not find the output pdf in this custom location, so I have to open in manually and can not use the hotkey command.

## The Solution*
Ideally, I would like the pdf preview to have additional search locations. I envision these solutions:
* add a setting for additional lookup paths: This way, every user can configure their strange paths, wherever they might put their files.
* add crawling of ``latexmkrc`` and ```.latexmkrc`` files into the search paths
* add some default output directory names to the search path, e.g. ``out``, ``outdir`` or ``build``

**Comment by James-Yu** [comment]
There is a config with the name outdir.

**Comment by mw88-personal** [comment]
Indeed there is, but my toolchain uses ``.latexmkrc`` configurations, to share the configuration with my coworkers per-project.

If I wanted to use ``latex-workshop.latex.outDir``, I would have to set this manually in the workspace settings. It would be more convenient, if it could be read from the config file.

However, I can live with the workaround. Thank you for pointing that out.
