### ISSUE TITLE
unable to compile a file

### ISSUE THREAD

**Issue by banmeidareu** [James-Yu/LaTeX-Workshop#386]
### Description
Can't build after installing latexmk from the automatic install from miktex install manager

### How to reproduce

1. build a tex file

### Expected behavior
Should build a pdf

### Actual behavior

Latex toolchain has terminated with error

### Log messages

File::Path version 2.08 required--this is only version 1.08 at C:\Program Files\MiKTeX 2.9\scripts\latexmk\latexmk.pl line 157.
BEGIN failed--compilation aborted at C:\Program Files\MiKTeX 2.9\scripts\latexmk\latexmk.pl line 157.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>
<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information
 Nothing pops up under problems, i'm just getting started with this stuff, I'm not quite sure what wrong

**Comment by James-Yu** [comment]
It seems that your installation of `latexmk` is incorrect. You may try the command in CMD and see the problem. It is not related to the extension AFAIK.
