### ISSUE TITLE
Intelligence recognize special comments (e.g. TODO) as warnings.

### ISSUE THREAD

**Issue by Ao-Last** [James-Yu/LaTeX-Workshop#3860]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
-  Not a problem.

## The Solution*
> _Please provide a solution you would like to have._
- Recognize some special comments such as TODO as warnings.

**Comment by James-Yu** [comment]
This is not a LaTeX feature.

**Comment by James-Yu** [comment]
Let me elaborate a bit more: We cannot enumerate all --- or even common --- use of such comments and provide highlighting support. This is also not something that LaTeX would care about.

**Comment by Ao-Last** [comment]
FYI. Not a highlight support but a warning message that will show at the `Problems` tab in the panel. It should work like a lint function. Understand your design and hope this is helpful. Although this function could be done using other extension such as to-do tree, but it will be better if it is self-contained. I remember that the C/C++ extension support this feature. :)

**Comment by James-Yu** [comment]
The same. I don’t think I myself am interested in implementing and maintaining the feature. If there is a PR on this, the necessity will be discussed in depth.

**Comment by jlelong** [comment]
A mechanism already exists to have some specific commands show up in the structure/outline view

Instead of using a comment `% TODO`, use a command `\TODO` and add it to `latex-workshop.view.outline.commands`.
See 
- #2958 
- #3022
