### ISSUE TITLE
Include Prettify symbols?

### ISSUE THREAD

**Issue by Narfinger** [James-Yu/LaTeX-Workshop#387]
### Description
Implement something similar to [this](https://github.com/siegebell/vsc-prettify-symbols-mode) or more important [magic-latex-buffer](https://github.com/zk-phi/magic-latex-buffer) from emacs.

The mode replaces common symbols in math with their unicode character, i.e., \forall changes to ∀. When the cursor is either close or near ∀ it automatically opens back up to \forall.

This would make reading math much easier.

**Comment by chantisnake** [comment]
I don't know how long this pull request will be merged. @siegebell is usually very busy.

If you want to use this feature you can download the vsix file here: https://github.com/chantisnake/vsc-prettify-symbols-mode/releases/download/v0.4.2/prettify-symbols-mode-0.4.2.vsix
This provides prettify symbols mode version 0.4.2 with latex support.

you can install this extension via this command:
```console
code --install-extension .\prettify-symbols-mode-0.4.2.vsix
```

**Comment by chantisnake** [comment]
**NOTICE: `latexindent.pl` may mess up the prettify symbol.**

**Comment by siegebell** [comment]
@chantisnake thanks for the pull request!

By the way, you can override the prettify-symbols substitutions and add new languages by modifying `"prettifySymbolsMode.substitutions"` in your own vscode settings.

**Comment by James-Yu** [comment]
Looking forward to the new release with LaTeX support!

**Comment by James-Yu** [comment]
Quite unlikely. I had a peek into the code of pretty symbols extension, and found out that it would be really hard to add such maintenance burden to this extension.
