### ISSUE TITLE
Sorting for Acronyms and Glossary Entries

### ISSUE THREAD

**Issue by Enough7** [James-Yu/LaTeX-Workshop#3871]
Hi, I am thinking about a feature which enables the user to sort Acronyms or Glossary Entries after their id.

## Pre-checks*
- [X] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- No, it is not related to a problem

## The Solution*
Sort the contents of a `Glossary.tex`-File after their IDs such as 

Input:
```latex
\newglossaryentry{v2x}{
    name={Vehicle-To-X Communication},
    description={}
}

\newglossaryentry{c2x}{
    name={Car-to-X Communication},
    description={}
}

\newglossaryentry{v2v}{
    name={Vehicle-To-Vehicle Communication},
    description={}
}
```
Output:
```latex
\newglossaryentry{c2x}{
    name={Car-to-X Communication},
    description={}
}

\newglossaryentry{v2v}{
    name={Vehicle-To-Vehicle Communication},
    description={}
}

\newglossaryentry{v2x}{
    name={Vehicle-To-X Communication},
    description={}
}
```

## Anything Else?
I have sufficient overall programming skills, but I am new to VSC-Extensions development.
A bit highlevel guidance would be helpful.
What do you think about my proposal?

**Comment by James-Yu** [comment]
I think this may be a bit too specific for this extension.

**Comment by Enough7** [comment]
Yeah also it might breaks the hierarchy:  
_The parent entry must be defined before it’s referenced in the parent key of another
entry._  
See: [User Manual for glossaries.sty v4.52 - glossaries-user.pdf](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.pdf)
