### ISSUE TITLE
Main memory size

### ISSUE THREAD

**Issue by dbonattoj** [James-Yu/LaTeX-Workshop#3873]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
-  My bibliography seems too big to be compiled, it exceed some latex main memory limit.
![image](https://user-images.githubusercontent.com/28501597/236661193-3dd4eab2-b255-44c6-9e8b-dddf526f1f5a.png)

## The Solution*
- I would like to be able to change the max memory as a parameter in the extension

I think https://tex.stackexchange.com/a/124206 contains a solution

**Comment by James-Yu** [comment]
You can customize your tools and recipes to achieve this.
