### ISSUE TITLE
Is removing dependency to `latex-utensils` a good idea?

### ISSUE THREAD

**Issue by James-Yu** [James-Yu/LaTeX-Workshop#3877]
This issue is a dev discussion.

@jlelong In the past few days, I've been thinking on the pros and cons of `latex-utensils` dependency. I am currently with a thought that while LU grants lazy parsing, the limitations are significant enough such that reverting back to an enhanced regex-based parsing might indeed improve the long-term maintanence experience. The incapability when a minor syntax error appeared in editor, the (relatively) long parsing time on a long document, the still-problematic `stripText`, the less maintained and related repo, and the fact that indeed we may not need a full-fledged AST for LaTeX.

I am aware that this can be a quite big change, and a very notable harm to what we have been sticking to in the past year. If you also share a similar thought, I may start on something small, e.g., the structure (as I have been struggling with it for quite some time). The change may rollout very slowly and gradually, so that the flood of bug reports can be attenuated.

What do you think @jlelong ? I am happy to take the tasks if you think it may worth a try.

**Comment by James-Yu** [comment]
Thanks for the input. Indeed, the major drawback for AST-based parsing, afaik:

X. Relatively slow parsing speed, which in fact 1) is not a big deal if we have a perfect `stripText` (somehow hard) or 2) is notable if the document is too literal.
X. Still needs to fallback to regex if the LaTeX document has syntax errors, even if they are not related to a particular feature.

Regex may contribute to both, but the maintainence is indeed very challenging. I totally agree.

Let me take a look at `unified-latex` and see if it is a good in-place substitution. It would be awesome if both problems can be resolved.

Let me also shake off my thought on turning back to regex 🤣

**Comment by James-Yu** [comment]
Tiny test:

- `unified-latex` is 3x slower than `latex-utensils`. However, the excessively long document in #3813 (7400+ lines, 300k+ chars) renders ~400ms and ~166ms for either to parse, which is beyond my expectation. Maybe AST-based parsing is not as bad as I thought in terms of speed.
- `unified-latex` can properly parse LaTeX with syntax errors! It just follows the catcode definition of LaTeX.
- `unified-latex` does not have too many and too detailed types for LaTeX syntax, which to me is indeed quite promising.

It looks like `unified-latex` is a good candidate to switch. However,

- `unified-latex` does not have a `bibtex` parser. At least, yet.

What do you think? Switch to `unified-latex` looks like not a too heavy task, but we may need to 1) stick with LU for bibtex, or 2) fallback to regExp-based bibtex.

**Comment by jlelong** [comment]
Thanks a lot for these tests, which look very promising. I really think `unified-latex` is worth a try.

As far as bibtex is concerned, could we imagine to extract the `bibtex` parser from LU into a separate repo? This would allow us to have full control and fix the current issues. Scrolling through LU, I noticed that you had tried to contribute a `bibtex` grammar, which was not accepted. Maybe, we could be happy with a simpler AST.

**Comment by James-Yu** [comment]
Indeed. BibTeX does have a much simpler syntax and AST. I will take a look on that and maybe maintain LW's minimal BibTeX AST parser.
