### ISSUE TITLE
.nav, .snm, .vrb files not cleaned after Build with Beamer class

### ISSUE THREAD

**Issue by yjcui** [James-Yu/LaTeX-Workshop#3878]
When I use beamer class under VScode, the above mentioned aux files are not cleaned after Build, even they are listed in `latex-workshop.latex.clean.fileTypes`. I noticed there was an early discussion for this issue, but it is still happending to me. 

I tried both the default `latexmk` and self-configured `pdflatex->pdflatex` and this issues still exists.

Also I could not configure it to delete aux folders under beamer. To be specific, I was using the `minted` package for code insertion and an aux folder `_minted_filename` got created every time. I tried adding `_minted*/` to `latex-workshop.latex.clean.fileTypes`, but it never got deleted.

**Comment by James-Yu** [comment]
```
Files to clean when `#latex-workshop.latex.clean.method#` is set to `glob`
```
Please change `latex-workshop.latex.clean.method` to `glob`.

**Comment by yjcui** [comment]
Thanks for the quick answer!! It works!
