### ISSUE TITLE
Can't locate Digest/MD5.pm

### ISSUE THREAD

**Issue by TomaszMyszak** [James-Yu/LaTeX-Workshop#3880]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- when i try compile latex file in Visual Studio Code on Windows 11 i have issue 
- "Can't locate Digest/MD5.pm in @INC (you may need to install the Digest::MD5 module) (@INC contains: C:/Users/tomaszmyszak/AppData/Local/Programs/MiKTeX/scripts/latexmk/ C:/Program Files (x86)/LyX 2.3/Perl/lib .) at C:/Users/tomaszmyszak/AppData/Local/Programs/MiKTeX/scripts/latexmk/latexmk.pl line 82."
- 
BEGIN failed--compilation aborted at C:/Users/tomaszmyszak/AppData/Local/Programs/MiKTeX/scripts/latexmk/latexmk.pl line 82.

## The Solution*
> _Please provide a solution you would like to have._
- i install on cpan shell Digest/MD5

## Anything Else?
> _Add any other context about the feature request below._
-  it still this issue.

**Comment by jlelong** [comment]
This is not related to the extension but to your local LaTeX and Perl installations
