### ISSUE TITLE
Problem Upgrading form 9.10.0 to 9.11.0

### ISSUE THREAD

**Issue by lcnittl** [James-Yu/LaTeX-Workshop#3888]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Microsoft Windows 11 Enterprise (10.0.22621 Build 22621)
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: 9.11.0
- TeX Distribution Version: TeX Live 2023

## The Issue*
- IntelliSense is not working (no suggestions for refs, citations etc.; no preview of refs, citations etc.; no [Ctrl]+[click] navigation for refs, citations etc.)
- Additionally, #3886 is observed

### Reproduction Steps
1. Create the following file
    ```latex
    % !TeX encoding = UTF-8
    % !TeX spellcheck = en_GB
    % !TeX program = latexmk
    % !TeX options = -r "../../.latexmkrc" -rc-report
    \documentclass{article}

    \begin{document}

    \section{Main part}
    \label{sec:main}

    Ref to sec:main \ref{sec:main}

    \end{document}
    ```
1. Upgrade from 9.10.0 to 9.11.0

### Expected Behavior
- IntelliSense working
- Structure showing

### LaTeX Workshop Output*
- [**Version 9.10.0**](https://gist.github.com/lcnittl/f95b4927d3d6293221e72891f3935c0f#file-latex_workshop_log_v9-10-0-log)
- [**Version 9.11.0**](https://gist.github.com/lcnittl/f95b4927d3d6293221e72891f3935c0f#file-latex_workshop_log_v9-11-0-log)

### Developer Tools Console
- [**Version 9.10.0**](https://gist.github.com/lcnittl/f95b4927d3d6293221e72891f3935c0f#file-latex_workshop_debug_console_v9-10-0-log)
- [**Version 9.11.0**](https://gist.github.com/lcnittl/f95b4927d3d6293221e72891f3935c0f#file-latex_workshop_debug_console_v9-11-0-log)

## Anything Else?
- If you require any more info, please let me know.

Thank you for looking into it!

**Comment by James-Yu** [comment]
By the way, I really appreciate the way you organize your issue and related information. Kudos!

**Comment by James-Yu** [comment]
This is even more complicated than I thought: https://stackoverflow.com/a/71665228

The root is, vscode depends on electron, which does not allow use of ES modules, which is indeed how `unified` is now designed.

Still looking for a workaround.

**Comment by James-Yu** [comment]
Changes reverted in #3892 and bug should be fixed.
