### ISSUE TITLE
Lulatex failing with error code 1

### ISSUE THREAD

**Issue by Sujay-shetty** [James-Yu/LaTeX-Workshop#3893]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [e.g. Windows 10]
- Visual Studio Code Version: [e.g. 1.41.0]
- LaTeX Workshop Version: [e.g. 8.5.0]
- TeX Distribution Version: [e.g. TeX Live 2019 / MiKTeX 2.9.7250]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
-  Not able to generate pdf document and lualatex throwing error code 1

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. use node js project
2. Create child process for executing command
     const childProcess = require('child_process');
     const latexmk = childProcess.spawn('latexmk', BASE_OPTIONS_SPAWN_COMMANDS.concat([tempFileNameLatex]), {
            cwd: TEMP_FOLDER,
          });
      latexmk.on('close', (code) => {
         if (code) {  
              logger.info(`inside latex service close method code == ${JSON.stringify(code)}and err == ${JSON.stringify(err)}`);
              reject(err);
         } 
      }    

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- pdf file should be genrated
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
debug: Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
debug: Rule 'lualatex': Rules & subrules not known to be previously run:
debug:    lualatex
Rule 'lualatex': The following rules & subrules became out-of-date:
      'lualatex'
Run number 1 of rule 'lualatex'
debug: ------------
Running 'lualatex  -halt-on-error -synctex=1 -recorder -output-directory="."  "temp-latex-file2.tex"'
debug: Collected error summary (may duplicate other messages):
debug:   lualatex: Command for 'lualatex' gave return code 1
      Refer to 'temp-latex-file2.log' for details
debug: Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
info: inside latex service close method code == 12 and err == null }
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
Not related to this extension.
