### ISSUE TITLE
When the parameter "latex-workshop.latex.outDir" is defined, the feature from #3890 doesn't work

### ISSUE THREAD

**Issue by cfgnunes** [James-Yu/LaTeX-Workshop#3898]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The issue has not been reported in this repository.
- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Ubuntu 22.04.2
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: 9.11.4
- TeX Distribution Version: TeX Live 2019

## The Issue*
> _Please briefly describe the issue you come across._
- When the parameter "latex-workshop.latex.outDir" is defined, the #3890 doesn't work.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Set the "latex-workshop.latex.outDir" to "latex.out";
2. Open a latex file and compile it;
3. Use the command "SyncTex from cursor" to open the "View LaTex PDF file".

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- The "View LaTex PDF file" must have shown. 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
Cannot view file PDF file. File not found: file:///home/cristiano/Documents/paper/Source/latex.out/latex.out/manuscript.pdf
```

## Anything Else?
> _Add any other context about the problem below._
- Note that "latex.out" is repeated twice:  ".../latex.out/latex.out/manuscript.pdf"

**Comment by James-Yu** [comment]
Please provide full log.
