### ISSUE TITLE
[feature request] open .sty file shown in log

### ISSUE THREAD

**Issue by jannick0** [James-Yu/LaTeX-Workshop#390]
It would be great if a .sty file whose path is shown in the log (displayed as file in the VS Code editor) could be opened in VS Code upon user request (e.g. right-click menue).

Many thanks!

**Comment by James-Yu** [comment]
It seems that the feature is not supported by the current vscode API. I will close this issue for now but would be more than happy to accept any PR/discussion on this topic.

**Comment by jannick0** [comment]
I was inspired by the looking-up feature of header files for c code which the VSCode package [cpptools](https://github.com/Microsoft/vscode-cpptools) as of now provides. I am not sure if this is then really possible for LaTeX-Workshop.
