### ISSUE TITLE
New versions of LaTeX-Workshop fails to load my project on windows

### ISSUE THREAD

**Issue by AetherDim** [James-Yu/LaTeX-Workshop#3901]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Windows 10
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: 9.11.3 and 9.11.4
- TeX Distribution Version: Tex Live 2022

## The Issue*
With the newer version my project loads indefinitely. Old version including 9.11.2 load fine. 

### Reproduction Steps
For the moment I was not able to reproduce this in a simple test project.

### Expected Behavior
LaTeX-Workshop finished startup correctly.

**Comment by A-I-18** [comment]
Same here
