### ISSUE TITLE
The structure on the left does not jump when you click on it

### ISSUE THREAD

**Issue by lan-slot** [James-Yu/LaTeX-Workshop#3905]
![WX20230529-214310@2x](https://github.com/James-Yu/LaTeX-Workshop/assets/68606787/d5fcd1de-375e-48ae-8eb2-a4fc34543289)

Previously, clicking with the mouse jumped to the corresponding section, but now clicking does not jump (will only jump to the beginning of the document \documentclass{ } section).

**Comment by Lemonlee8** [comment]
I also met the same problem. If the tex file is long, you'll be a little bit unaccustomed to it. Longing for the fixing.

**Comment by BlankSeed** [comment]
I seem to encounter the same problem in V9.11.4. Wonder if there is any solution for this

**Comment by jlelong** [comment]
Please wait for the next release.
