### ISSUE TITLE
Subsubsection folding subsection inside of it when they differ more than 2 levels

### ISSUE THREAD

**Issue by jobtijhuis** [James-Yu/LaTeX-Workshop#3906]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System: Fedora 37
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: 9.11.4
- TeX Distribution Version: Tex Live 2022

## The Issue
- When folding a `\subsubsection{}` it gobbles up the next `\subsection{}` as well
- This only happens when the `\subsubsection` follows a `\section` without a `\subsection` in-between first.

### Reproduction Steps
The following MWE reproduces the problem:
```latex
\documentclass{book}

\begin{document}

\chapter{Chapter 1}

\section{Section 1}
Some example texts.

\subsubsection{Subsubsection 2}
Some example texts.

\subsection{Subsection 2}
Some example texts.

\chapter{Chapter 2}

\end{document}
```
- When you fold the `\subsubsection{}` it will fold the `\subsection{}` inside of its fold.

### Expected Behavior
- The `\subsubsection{}` folds but does not fold the \subsection inside of it

Of course in a final document you should not have subsections that differ in more than two levels, but during drafting this error can catch you out if you are only looking at the .tex and have folded everything.

**Comment by James-Yu** [comment]
<img width="753" alt="Screenshot 2023-06-05 at 01 51 22" src="https://github.com/James-Yu/LaTeX-Workshop/assets/4210342/c0a435a3-ee9d-4296-b109-3fdfc64bea35">

I don't see a problem with the latest commit?
