### ISSUE TITLE
Is there a way to select entries from remote .bib files?

### ISSUE THREAD

**Issue by jaanli** [James-Yu/LaTeX-Workshop#3909]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
- Thank you so much for this @James-Yu  ! 

We need this for a large class that uses Visual Studio Code and needs to cite from Zotero but is currently unable to use LaTeX Workshop for this :)

## The Solution*
- Is there a way to select entries from Zotero's bibliography online?

## Anything Else?
- Example: This Overleaf project (https://www.overleaf.com/read/nwqyqtbznbhd) lets one select `.bib` entries from Zotero, at this URL: https://api.zotero.org/groups/4809667/items/top?format=bibtex&style=numeric&limit=100.

**Comment by jlelong** [comment]
Unfortunately, this is not possible and we do not have the resources to support it.
