### ISSUE TITLE
Not building from within a bib file

### ISSUE THREAD

**Issue by pesho-ivanov** [James-Yu/LaTeX-Workshop#3914]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Ubuntu 20.04.6 LTS]
- Visual Studio Code Version: [1.78.2]
- LaTeX Workshop Version: [9.11.4]
- TeX Distribution Version: [TeX Live 2019]

## The Issue*
- Neither manual build nor Ctrl+Alt+B compile the project from a .bib file.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Open a .bib file.
2. Ctrl+Shift+P for commands dropdown.
3. Enter "LaTeX Workshop: Build LaTeX project"

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- To build the project the same way as it builds it from a .tex file.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[20:36:36][Structure] Structure updated with 3 entries for %WS1%/sidepubs.bib .
[20:36:36][Event] STRUCTURE_UPDATED
```
No log entry is produced in the LaTeX Workshop Output when trying to build from .tex.

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._

No log entry is produced in the Developer Console when trying to build from .tex.

**Comment by James-Yu** [comment]
I cannot reproduce the problem. You may need to provide the FULL log and a minimal working example.

**Comment by jlelong** [comment]
@pesho-ivanov You are right calling the LaTeX build command from a `.bib` file does not work. It only works from a file with LaTeX language id. Note that keybinding `alt-ctrl-b` is only defined for files with LaTeX language id.

However, if `latex-workshop.latex.autoBuild.run` set to `onFileChange`, saving a `.bib` file triggers a build through the watcher mechanism. 

Maybe, we could implement a build trigger when saving a `.bib` file.

**Comment by James-Yu** [comment]
> Maybe, we could implement a build trigger when saving a `.bib` file.

Together with https://github.com/James-Yu/LaTeX-Workshop/issues/3875#issuecomment-1578209095 , what about we also check whether the `fsPath` of the saved file is included in the project when saving?

**Comment by jlelong** [comment]
> > Maybe, we could implement a build trigger when saving a `.bib` file.
> 
> Together with [#3875 (comment)](https://github.com/James-Yu/LaTeX-Workshop/issues/3875#issuecomment-1578209095) , what about we also check whether the `fsPath` of the saved file is included in the project when saving?

Yes, both issues are partly related. We could extend the `onSave` trigger to any file whose `fsPath` is included as a dependency of the root file.
