### ISSUE TITLE
Extremely slow load times.

### ISSUE THREAD

**Issue by cottrell** [James-Yu/LaTeX-Workshop#3919]
I've disabled everything but this extension.

v9.11.4 on

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-43-generic
Sandboxed: Yes

I tried to load the .cpuprofile in chrome but there was complaint about title missing.

Any suggestions on debug? I see the toString errors in the log. I saw the issues about that were all marked resolved so I'm not sure if that is an issue or not.

chrome log has numerous entries but I think this is the relevant one.

**Comment by James-Yu** [comment]
Also see #3907
