### ISSUE TITLE
Hyperlink to PDF of bibliography items

### ISSUE THREAD

**Issue by bpiwowar** [James-Yu/LaTeX-Workshop#392]
### Description

If the bibtex item contains a "file" field, use it to provide a link to the user. This would allow to quickly look at the citation paper - for example to check for details. 

Another option would be to allow hooks at this level, by having a "More details..." link at the beginning of the citation popup, and to let the user choose how to handle a click on "More details...".

1. Hover the citation
2. In the popup that is showing, display the "file" field as a hyperlink (if the file is detected or not)

**Comment by James-Yu** [comment]
Unfortunately this feature seems to have some problem. People usually use bibtex management software to manage their bib-files, and they tend to leave relative paths in `file` field. It can be overwhelming for the extension to find out where exactly the file locates.

Discussion/PR welcomed as always!

**Comment by bpiwowar** [comment]
Well, at least mine (on export) gives an absolute path; otherwise, maybe adding a workspace setting would be an option. 

I will have a look at the code and submit a PR when I have some time.
