### ISSUE TITLE
Delay when pressing Enter (in combination with Elastic Tabstops Mono extension)

### ISSUE THREAD

**Issue by LinqLover** [James-Yu/LaTeX-Workshop#3921]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository:

   Duplicates #903 and #3853 have been closed but the underlying problem apparently has not been not solved.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.

  The issue only occurs when isral.elastic-tabstops-mono is enabled. However, isral.elastic-tabstops-mono without this extension does not create the problem.

- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: 9.11.4
- TeX Distribution Version: 

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using WSL whose version is v0.78.9

## The Issue*
> _Please briefly describe the issue you come across._

Exactly the same as described in #903

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Press Enter in a large file at the end of any line
2. Have to wait for a couple of seconds before the linebreak appears

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Line break should be inserted immediately

## Anything Else?
> _Add any other context about the problem below._

It would be great if I could use these two extensions together. If they are not compatible, this should be mentioned in the FAQ, but actually, I don't understand why they could not be compatible. Could you maybe shortly reply to https://github.com/James-Yu/LaTeX-Workshop/issues/903#issuecomment-432633791? Can I disable the keybindings for this extension for `onEnterKey` or what consequences would I have to expect?

Thanks in advance for your time!

**Comment by jlelong** [comment]
You can disable this keybinding by setting `latex-workshop.bind.enter.key` to `false`.

I have no idea why https://github.com/isral/elastic_tabstops_mono.vsce/tree/master is incompatible with our overloading of the `Enter` key.

**Comment by LinqLover** [comment]
Thank you! Will disabling this keybinding have any negative consequences?

**Comment by James-Yu** [comment]
Enter key is rebound to insert \item automatically in e.g. itemize env. Apart from that, setting it to false won’t harm.

**Comment by LinqLover** [comment]
Thank you! Maybe this info should be mentioned in the FAQ as well. :-)

**Comment by jlelong** [comment]
Done.
