### ISSUE TITLE
Show the output log of latexmk (e.g. the content of the `.log` file) instead of output of latexmk on the second invokation

### ISSUE THREAD

**Issue by PatrickJosh** [James-Yu/LaTeX-Workshop#3924]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

Currently, if there's an error during compilation, but the compilation is done again, latexmk does not display the errors that occurred during the last iteration again, but only the following generic message:

```
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
Rc files read:
  /etc/latexmkrc
Latexmk: This is Latexmk, John Collins, 4 Apr. 2023. Version 4.80.
Latexmk: Nothing to do for '/home/noeske/testing/test.tex'.
Latexmk: All targets () are up-to-date
Collected error summary (may duplicate other messages):
  lualatex: gave an error in previous invocation of latexmk.
```

So, if I press the button that opens the compiler log to have a look what went wrong, I always only see this message since latexmk is apparently invoked multiple times.

## The Solution*
> _Please provide a solution you would like to have._

I'd like to see the actual log of the last compilation, so that I can see the error messages. Currently, I have to open the logfile myself to see them, which is annoying.

## Anything Else?
> _Add any other context about the feature request below._

It seems like this was not a problem for me until some weeks ago. Before, I could always see the actual log when I pressed the button.

**Comment by James-Yu** [comment]
I'm not sure on your request. The log display has not been changed for many years, namely, display the last tool's output.
