### ISSUE TITLE
Repeated tabs when opening the same PDF files

### ISSUE THREAD

**Issue by twni2016** [James-Yu/LaTeX-Workshop#3925]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System:  Darwin x64 21.4.0
- Visual Studio Code Version: 1.78.2
- LaTeX Workshop Version: v9.11.4
- TeX Distribution Version: [e.g. TeX Live 2019 / MiKTeX 2.9.7250]

## The Issue*

Suppose we have a PDF file in the working directory, and we keep opening the same PDF file for several times. Each time we open the same PDF file, this extension in VS Code will generate a new tab in the open editors.

I used Start Extension Bisect command to figure out that it is this extension that caused such an issue.

**Comment by James-Yu** [comment]
#3882
