### ISSUE TITLE
Feature "Structure of the document" not running properly with starred version of structures

### ISSUE THREAD

**Issue by tionway** [James-Yu/LaTeX-Workshop#3926]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: macOS 13.4
- Visual Studio Code Version: 1.79.0
- LaTeX Workshop Version: 9.11.4
- TeX Distribution Version: mactex-20230314

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- When the starred version of structure is the first one of the same level, for example, "\section*{}", Visual Studio Code would show "Cannot read properties of undefined (reading 'toString')" when restarting Visual Studio Code and the STRUCTURE in the TeX panel is empty.
- But surprisingly, when they are not the first one, for example, "\section{} ... \section*{}", the STRUCTURE in the TeX panel works fine.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Write
```
\documentclass{article}
\begin{document}
\section*{A}
\end{document}
```
And compile it.
2. Write
```
\documentclass{article}
\begin{document}
\section{A}
\section*{B}
\end{document}
```
And compile it
### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- In the first case, there should be something like "* A" in the STRUCTURE in the TeX panel, but it's empty.
- In the second case, STRUCTURE works fine, it shows "1 A ... * B".

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
It's empty
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
workbench.desktop.main.js:sourcemap:1851 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1851
workbench.desktop.main.js:sourcemap:1851 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1851
workbench.desktop.main.js:sourcemap:1851 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1851
workbench.desktop.main.js:sourcemap:1851 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1851
workbench.desktop.main.js:sourcemap:1851 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1851
workbench.desktop.main.js:sourcemap:97 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'toString')
y @ workbench.desktop.main.js:sourcemap:97
workbench.desktop.main.js:sourcemap:97 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
y @ workbench.desktop.main.js:sourcemap:97
workbench.desktop.main.js:sourcemap:1972 [James-Yu.latex-workshop]Cannot read properties of undefined (reading 'toString')
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1972
workbench.desktop.main.js:sourcemap:1972 TypeError: Cannot read properties of undefined (reading 'toString')
	at addSectionNumber (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:374:52)
	at construct (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structurelib/latex.js:52:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async StructureView.build (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:104:34)
	at async StructureView.reconstruct (/Users/shen/.vscode/extensions/james-yu.latex-workshop-9.11.4/out/src/providers/structure.js:116:26)
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1972
workbench.desktop.main.js:sourcemap:624  INFO [perf] Render performance baseline is 24ms
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
#3897
