### ISSUE TITLE
Stuck on “activating extension”

### ISSUE THREAD

**Issue by Dcarr89** [James-Yu/LaTeX-Workshop#3927]
- 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. 
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- > _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Mac osx
- Visual Studio Code Version: 1.41.0
- LaTeX Workshop Version: v9.11.4
- TeX Distribution Version: MacTeX

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- > _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Mac osx
- Visual Studio Code Version: 1.41.0
- LaTeX Workshop Version: v9.11.4
- TeX Distribution Version: MacTeX

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- LaTeX VScode on mac - stuck on activating extensions

I've reinstalled VScode and all the libraries several times but I still can't get my latex project to compile. VScode is stuck on activating extensions:

I'm using version:

LaTeX Workshop v9.11.4 James Yu

I've tried a full reinstall and checked that my LaTeX distribution is working. any ideas?

I reinstalled VScode and disabled all extensions, re-enabling one by one and it still didn't fix the issue.

I also tried editing in another TeX editor and it compiled no issue.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[none.]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
I can’t help you with the given info.
