### ISSUE TITLE
LaTeX workshop extension stuck on generating commands/structure/snippet view

### ISSUE THREAD

**Issue by empeirikos** [James-Yu/LaTeX-Workshop#3928]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [x ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [macOS Catalina, version 10.15.7]
- Visual Studio Code Version: [1.79.0 (Universal)]
- LaTeX Workshop Version: [9.11.4]
- TeX Distribution Version: [TeX Live 2022]

## The Issue*
- I have reinstalled LaTeX Workshop ; when I load a LaTeX file, the extension is activated. I then try to load the side panel which contains the Commands window so that I can build the file. I clock appears on the TEX icon and the side panel is loading for ever (see screenshot).
<img width="373" alt="Screenshot 2023-06-13 at 01 46 02" src="https://github.com/James-Yu/LaTeX-Workshop/assets/80323854/cc969c31-815e-4ef6-a47b-c820b17a9d49">
 
 

### Reproduction Steps
1. Reinstall LaTeX Workshop to latest version.
2.  Load a LaTeX project.
3.  Select the *.tex file.4. 
4. As TEX extension is generated on the left bar click it to access commands. 

### Expected Behavior
- It was loading Command Window a few hours ago; now it is stuck.

**Comment by empeirikos** [comment]
How can this be completed so quickly? :-)

**Comment by Dcarr89** [comment]
@James-Yu I'm also having this issue
