### ISSUE TITLE
Lost graph color when using the black mode

### ISSUE THREAD

**Issue by julien-blanchon** [James-Yu/LaTeX-Workshop#3930]
When viewing a pdf in black mode I lost all the graph color.
Both the black text and the non-black element such as graph are switch to black as you can see in this image:
<img width="295" alt="Screenshot 2023-06-13 at 11 49 57" src="https://github.com/James-Yu/LaTeX-Workshop/assets/11278197/14e667b9-bb8a-44a7-9195-67d66e31d987">

<img width="295" alt="Screenshot 2023-06-13 at 11 50 20" src="https://github.com/James-Yu/LaTeX-Workshop/assets/11278197/4fc4331e-27a0-4040-82e8-a9b5c5c29807">

Here is my latex-workshop config:

```json
"latex-workshop.view.pdf.color.dark.pageColorsBackground": "#1F1F1F",
 "latex-workshop.view.pdf.color.dark.pageColorsForeground": "lightgrey",
 "latex-workshop.view.pdf.color.dark.backgroundColor": "black",
  ```

**Comment by James-Yu** [comment]
This is a [PDF.js](https://github.com/mozilla/pdf.js/) issue/feature. We just pass these values to PDF.js viewer.

**Comment by julien-blanchon** [comment]
Hum I'm not sure how to explain this issues on the PDF.js side
