### ISSUE TITLE
LaTeX Workshop on Mac stuck on activating extensions

### ISSUE THREAD

**Issue by HugooB** [James-Yu/LaTeX-Workshop#3931]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: MacOS 12.6.6
- Visual Studio Code Version: 1.79.1
- LaTeX Workshop Version: v9.11.4
- TeX Distribution Version: TeX Live 2020

## The Issue
VScode is stuck on activating extensions as shown in this picture 

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/14057134/74530366-406e-4f4e-8244-cb5278da0930)

It has also been posted on StackOverflow, [here](https://tex.stackexchange.com/questions/688376/latex-vscode-on-mac-stuck-on-activating-extensions) and [here](https://stackoverflow.com/questions/76459905/vscode-latex-on-mac-stuck-on-activating-extension)

### Reproduction Steps
1.  Open VSCode
2. Click on the TeX icon in the left bar
3. It remains stuck

### Expected Behavior
Quickly loading the extension, not being stuck

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```
No log created

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
INFO UNRESPONSIVE extension host: starting to profile NOW log.ts:431  
WARN UNRESPONSIVE extension host: 'james-yu.latex-workshop' took 91.23630644773773% of 4564.463ms, saved PROFILE here: 'file:///var/folders/10/wt59fjy973b9psf7wwgq7f4r0000gn/T/exthost-155fb0.cpuprofile'
```

## Anything Else?
Nope.

**Comment by HugooB** [comment]
Oh, just discovered #3927, #3928, #3929... Maybe keep this issue here until the new release is out?

**Comment by HugooB** [comment]
I'm sorry @James-Yu , but the fix didn't help. Is there a way I can produce more logs? 
The only logs I could find are the ones already mentioned in the issue, but that only states that the extension has become unresponsive.. I really appreciate the effort you put into developing this extension, so more than willing to help you fixing this problem.

**Comment by James-Yu** [comment]
You may have a try on the latest 434d8915ce3ea1f3ef0ee15cf3fff5111f2b1523

**Comment by HugooB** [comment]
It's working again, thank you! 👍
