### ISSUE TITLE
Feature Request: Auto formatting of tabulary tables

### ISSUE THREAD

**Issue by mrnolte** [James-Yu/LaTeX-Workshop#3932]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Auto-formatting of tables written using the `tabulary` package does not work.

## The Solution*
> _Please provide a solution you would like to have._
- Tables written using the `tabulary` package should be formatted just like `tabular` or `tabularx`-tables

**Comment by James-Yu** [comment]
We rely on https://github.com/cmhughes/latexindent.pl for formatting. Please file an issue there.
