### ISSUE TITLE
Quote on multiple lines (with inner apostrophe in math mode) causes issues

### ISSUE THREAD

**Issue by gertab** [James-Yu/LaTeX-Workshop#3939]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System: MacOS 13.4
- Visual Studio Code Version: Visual Studio Code Version: 1.79.1
- LaTeX Workshop Version: LaTeX workshop v9.12.0.
- TeX Distribution Version: TeX Live 2023

## The Issue
- When quote (``...'') is split over multiple lines and there is an apostrophe in math mode, the text following it loses its coloring scheme.
- No problem for versions up to 9.11.4. However in versions **9.11.5** and upwards, there is this issue.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. The following snippet reproduces the issue, where the bottom text loses its color scheme:
```latex
\documentclass{article}

\begin{document}

Original text

``This $x'$ is 
on the same line''

Bottom text and math symbols $x$

\end{document}

```

### Expected Behavior
- From the given example both `Original text` and `Bottom text and math symbols $x$` should be the same color.

**Comment by James-Yu** [comment]
@jlelong Looks like a highlighting issue?

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#61
