### ISSUE TITLE
Improving cSpell (Code Spellchecker) support for LaTex

### ISSUE THREAD

**Issue by Jason3S** [James-Yu/LaTeX-Workshop#394]
Hello James,

I'm the author of Code Spellchecker.

A few people have been asking for improved support of LaTex. Many of them have pointed to your extension as an example on how to make some fixes.

Since I don't use LaTex, I don't have a good feel for what is needed. Any input would be helpful. At the very least, I'll add your exclusions.

Example Requests:
https://github.com/Jason-Rev/vscode-spell-checker/issues/167
https://github.com/Jason-Rev/vscode-spell-checker/issues/172

Kindly,
Jason

ps. It might take me a bit of time to respond, the spell checker is a hobby, not my work.

**Comment by James-Yu** [comment]
Hi Jason,

Glad to hear from you.

I would say the provided regex works well for me. As to technical terms, I'd suggest showing them only once with or without the total number of appearance. I've no idea if this can be implemented or not though 🤔

**Comment by Jason3S** [comment]
Thank you. At the very least, I'll add in your suggested exclusions.
