### ISSUE TITLE
Autobuild ignoring onsave value and saving after in regular intervals if the file is changed

### ISSUE THREAD

**Issue by devaneando** [James-Yu/LaTeX-Workshop#3940]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Debian GNU/Linux 11 Q4OS 4.12
- Visual Studio Code Version: 1.79.2
- LaTeX Workshop Version: 9.12.0
- TeX Distribution Version: 3.14159265 (TeX Live 2020/Debian)

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
- I set autoBuild to only run on save.
- Every time I change the file, like adding a \textbf format, it will build.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Leave all latex-workshop default options, change the ones in the json below
2. Starting editing a file, add a  \textbf format, do not save
3. You will see the OUTPUT window showing the build running.

```json
{
  "latex-workshop.bibtex-format.tab": "4 spaces",
  "latex-workshop.latex.autoBuild.run": "onSave",
  "latex-workshop.latex.autoClean.run": "onBuilt",
  "latex-workshop.latex.clean.command": "/usr/bin/latexmk",
}
```

### Expected Behavior
> I expect that the build would only run if I save the file

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
Log pls.
