### ISSUE TITLE
Language highlight between ` and '

### ISSUE THREAD

**Issue by SwitWu** [James-Yu/LaTeX-Workshop#3945]
It seems that the language highlight has some problems which can be seen from the following screenshot:
![1](https://github.com/James-Yu/LaTeX-Workshop/assets/39337667/549b82d3-e567-465a-9a06-b13c668ccaa1)
The code between `` ` `` and the `'` is in brown color (like markdown's inline codeblock) which is not what I want. How to fix this?

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#62
