### ISSUE TITLE
Display latex inline 

### ISSUE THREAD

**Issue by henusys** [James-Yu/LaTeX-Workshop#3949]
I remember seeing someone's latex editing setup where the latex was rendered inline, so when you'd type \alpha in your .tex file it'd be replaced with the letter alpha for example. (but only visually, the actual .tex file would still contain \alpha) It made latex a lot easier to read and edit, but I haven't been able to find this setup again. Does anyone know where I can find something like this? (preferrably for vs code, if possible)

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/9565297/c2b74611-68dc-4408-9693-c1b3472d5248)

参考自：https://tex.stackexchange.com/questions/621016/display-latex-inline-in-vs-code

**Comment by James-Yu** [comment]
It is not possible within vscode. You may consider file a feature request there.
