### ISSUE TITLE
backtick symbol \` in \catcode\` and \char\` should not be used for syntax highlighting

### ISSUE THREAD

**Issue by DailyShana** [James-Yu/LaTeX-Workshop#3952]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- LaTeX Workshop Version: [9.2.12]

## The Issue*
> _Please briefly describe the issue you come across._
- the backtick symbol \` in \catcode\` cause syntax highlighting mess
- the backtick symbol \` in \char\` cause syntax highlighting mess

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Type the following 
```
\documentclass{ctexart}
\catcode`\。=\active
\newcommand{。}{．}
\begin{document}
\end{document}
```
```
\documentclass{ctexart}
\begin{document}
\char`~
\end{document}
```
2. the syntax highlighting is abnormal:
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/8469304/fbb81a5d-a62a-4c16-b5e6-c73a40cf49cb)
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/8469304/f4f84485-d06e-4100-8fb4-caa20dd9c6f7)

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- 
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/8469304/2a2924c6-b111-4414-9f27-5dcdead6afb1)

-

**Comment by James-Yu** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics). So please move this issue to that repository for a fix.

**Comment by jlelong** [comment]
Duplicate of https://github.com/jlelong/vscode-latex-basics/issues/62
