### ISSUE TITLE
Use of Title Formatting of Sections (\titleformat) Create Fake Structure Headings

### ISSUE THREAD

**Issue by sdhosseini88** [James-Yu/LaTeX-Workshop#3953]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository: **I searched in issues, and couldn't find anything.**
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: **Windows 10**
- Visual Studio Code Version: **1.79.2**
- LaTeX Workshop Version: **9.12.2**
- TeX Distribution Version: **TeX Live 2012**

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am not using VSCodium.

## The Issue*
> I have used \titleformat command (for example \titleformat{\section}) to restyle the headings of the document.
But, in the structure, the "\Section" argument inside the \titleformat is detected as a heading, and a number is assigned to it in the structure.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Add \titleformat{\section} to the main document, before the \begin{document}
2. An empty heading is created in the structure.

### Expected Behavior
> The use \titleformat{\section} should not create any heading in the structure.

### LaTeX Workshop Output*
> This issue is not related to the building of the document.

### Developer Tools Console
> This issue is not related to the building of the document.

## Anything Else?
> No, and many thanks for the great extension.

**Comment by James-Yu** [comment]
#3947

**Comment by sdhosseini88** [comment]
Thank you @James-Yu
