### ISSUE TITLE
booktabs environment from tabularray is not considered as a table

### ISSUE THREAD

**Issue by ainar** [James-Yu/LaTeX-Workshop#3954]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Ubuntu 22.04.2 LTS
- Visual Studio Code Version: 1.79.2
- LaTeX Workshop Version: 9.12.2
- TeX Distribution Version: TeX Live 2023
- VSCode Snap version 695af097

## The Issue*
The `booktabs` environment of _tabularray_ with library _booktabs_ is not considered as a table.
The "&" are not colored and the auto-indent does not affect the content of this environment.

### Reproduction Steps
Write in a empty document the following MWE in VSCode with Latex-Workshop enabled:
```latex
\documentclass{article}
\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}
\begin{booktabs}{ll}
    foo & bar\\
    qux quux & corge grault
\end{booktabs}
\end{document}
```
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/12114853/8db7db20-8e6a-4f63-a5d6-d07200a0f6f3)

Right-click then "Format..." or [CTRL+Maj+I] on Ubuntu.
Nothing happen.

The compilation result is OK:
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/12114853/815e77de-45a3-440c-8f95-8d8b4966a893)

### Expected Behavior
The columns should align vertically at the "&" character like in a  `tabular` or `tblr` environment.
The "&" should be colored.

### LaTeX Workshop Output*
```
[15:51:48.822][Format][TeX] Start formatting with latexindent.
[15:51:48.824][Format][TeX] Formatting LaTeX. The command is latexindent:["-c","%WS1%/","%WS1%/Chapters/__latexindent_temp_ch24-experiences.tex","-y=defaultIndent: '    '","-l=/home/aina/.vscode/latexindent.yaml"].
[15:51:49.026][Format][TeX] Formatted %WS1%/path/to/file
```

### Developer Tools Console
None.

**Comment by James-Yu** [comment]
The indentation is done by `latexindent`. I recommend you to file the indentation issue at https://github.com/cmhughes/latexindent.pl

As to the syntax highlighting issue, we have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics). I recommend you to create another issue solely on the highlighting overthere.

**Comment by jlelong** [comment]
> As to the syntax highlighting issue, we have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics). I recommend you to create another issue solely on the highlighting overthere.

Fixed in https://github.com/jlelong/vscode-latex-basics/commit/3fdf10f2f31628a335ed7f26b709c037a3263457
