### ISSUE TITLE
Auto-completion for macros created by \DeclareMathOperator and \DeclarePairedDelimiter

### ISSUE THREAD

**Issue by KervynH** [James-Yu/LaTeX-Workshop#3955]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*

If a new macro is defined by `\DeclareMathOperator` or `\DeclarePairedDelimiter` in the preamble of a tex file, such as
```latex
\DeclareMathOperator{\argmin}{argmin}
\DeclarePairedDelimiter{\abs}{\lvert}{\rvert}
```
The newly defined macros `\argmin` or `\abs` will not be suggested by the auto-completion feature; see the picture below.

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/123544684/8514d49d-0a2a-4e2d-b3a4-a72d828662bf)

## The Solution*

But if the new macro is defined by `\newcommand`, it could be recognized by the auto-completion. For example, if `\abs` is defined in the preamble by
```latex
\newcommand{\abs}[1]{\left\lvert #1\right\rvert}
```
then it will show up in the auto-completion; see the picture below.
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/123544684/178c6cc8-bc50-4d20-bb48-7dba8e858576)

I believe that `\DeclareMathOperator` and `\DeclarePairedDelimiter` should work in an analogous way, since the logic is almost the same. I will greatly appreciate if you could consider adding this feature in some future version!

**Comment by James-Yu** [comment]
#3948
