### ISSUE TITLE
`\DeclarePairedDelimiterX` and `\DeclareRobustCommand` still broken after 'fix'

### ISSUE THREAD

**Issue by MartinRJDagleish** [James-Yu/LaTeX-Workshop#3960]
## Pre-checks
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The issue has not been reported in this repository.
- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10 AND Manjaro Linux (Gnome)
- Visual Studio Code Version: 1.80.0
- LaTeX Workshop Version: 9.12.3 (fresh update!)
- TeX Distribution Version: MikTeX latest 

## The Issue*
> _Please briefly describe the issue you come across._
- As stated in #3948 before, the same issue seems to continue. I am not getting any IntelliSense for 
`\DeclarePairedDelimiterX` as before, but also `\DeclareRobustCommand` seems to be broken now as well. 
- I thought that previously  `\DeclareRobustCommand` was working.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Same as in #3948 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- IntelliSense for the custom commands

**Comment by James-Yu** [comment]
`\DeclareRobustCommand` was never parsed.

**Comment by MartinRJDagleish** [comment]
@James-Yu Thank you very much for this quick fix! 

I do not want to sound ungreatful, as your extension has massively improved my workflow for the creation of LaTeX documents. So thank you for taking the time to fix this issue!
