### ISSUE TITLE
the function "latex workshop: open math preview pannel" dose not work well.

### ISSUE THREAD

**Issue by unknownnumbers** [James-Yu/LaTeX-Workshop#3971]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10
- Visual Studio Code Version: 1.80.1
- LaTeX Workshop Version: 9.13.1
- TeX Distribution Version: TeX Live 2022

## The Issue*
> _Please briefly describe the issue you come across._
- the function "latex workshop: open math preview pannel" crashed after typing ``` \def ```and can no work successfully unless rebooting the VSCode.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. execute the latex workshop: open math preview pannel 
2. select into a math environment such as ``` \begin{equation}  \end{equation} ```
3. type ``` \def ``` in the left-to-right order
4. when typing the last character "f", the preview crashed and can no work successfully unless rebooting the VSCode.

### Expected Behavior
> _Make it works correctly.

**Comment by James-Yu** [comment]
On my side, the panel does not crash; it just stop updating until `\def` is removed. This also happens only when you `\def` inside a math environment, which should be avoided in any cases.

If you consider this a must, I suggest you file an issue to MathJax as we just use it to render equations.
