### ISSUE TITLE
No highlight inside \iffalse......\fi block

### ISSUE THREAD

**Issue by YijunYuan** [James-Yu/LaTeX-Workshop#3972]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
-  No

## The Solution*
> _Please provide a solution you would like to have._
- No idea

## Anything Else?
> _Add any other context about the feature request below._
- Using `\iffalse`...`\fi` as a block comment environment is a common trick in LaTeX. Currently, any content in it will still get original highlights. On the other hand, content in the `comment` environment (from the `comment` package) will not have any highlight, which stands for comment, just as the usual inline comment starting with `%`. Is it possible to disable the highlight inside the `\iffalse`...`\fi` block?

**Comment by James-Yu** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics). So please move this issue to that repository for a fix.
