### ISSUE TITLE
A compilation bug

### ISSUE THREAD

**Issue by xjz1123** [James-Yu/LaTeX-Workshop#3976]
Type: <b>Bug</b>

If you start with a bracket in "\begin{equation}\begin{aligned}\end{aligned}\end{equation}'', the content inside the bracket is compiled as blank. i.e.
''\begin{equation}
    \begin{aligned}
        [abc]
    \end{aligned}
\end{equation}''
is compiled as blank.

Extension version: 9.13.3
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by James-Yu** [comment]
This is not an extension bug.
