### ISSUE TITLE
Specify the pdf location

### ISSUE THREAD

**Issue by im-Kitsch** [James-Yu/LaTeX-Workshop#3979]
Hi, 

I would like to recommend re-open this issue https://github.com/James-Yu/LaTeX-Workshop/issues/148. Now that latexmk has upgraded.It supports `-aux-dir` also on texlive.  So when we specify auxillary folder, the pdf may not be in aux dir. 

So I think it would be better to split  `latex-workshop.outdir` to two items, one is pdf location, one is out dir(or also could bereffered as `auxdir`). Or we would additionally add a configuration about pdf location.

Best.

**Comment by James-Yu** [comment]
I don’t get you. Please fill the template.

**Comment by im-Kitsch** [comment]
> I don’t get you. Please fill the template.

Hi, sorry for the careless issue, I have update the feature request with template. Could you check the feature request again?

Thanks a lot for your good work of this extension

**Comment by James-Yu** [comment]
This is mine that achieves your objective:
```

        {
            "args": [
                "%DOC%",
                "-file-line-error",
                "-interaction=nonstopmode",
                "-synctex=1",
                "-aux-directory=./aux_files",
                "-outdir=%OUTDIR%",
                "-emulate-aux-dir",
                "-shell-escape",
                "-pdf"
            ],
            "command": "latexmk",
            "env": {},
            "name": "latexmk"
        }
```

**Comment by im-Kitsch** [comment]
ah, thanks, I have not noticed that it's possible to use both auxdir and outdir.
