### ISSUE TITLE
Option request : logging of latexindent as an option

### ISSUE THREAD

**Issue by MrYann** [James-Yu/LaTeX-Workshop#398]
It seems that latex workshop triggers latexindent upon save, which is nice. Latexindent is available as a latex package. However, it requires the Log4Perl package, which in turn requires even more Perl dependencies. 
Could there be an option to disable that logging ? (at the "load log4perl" level of course, otherwise there is not real point)

As a side note, I went through the steps to install all the dependencies and I am now stuck with
> Cannot write to 'indent.log': Permission denied

The logging is done in a restricted folder. Since launching latexindent with sudo is not an option, could there be a way to have the logging in the `latex-workshop.latex.outputDir` directory ?

**Comment by zoehneto** [comment]
The logging issue has been resolved with PR #381, it will be fixed as soon as James releases the next version.

**Comment by zoehneto** [comment]
Since we don't want to start modifying perl packages the next release will also add an option to configure the latexindent package to use. You can then download the packaged version of latexindent from ctan which includes all dependencies, configure it as the one to use (`latex-workshop.latexindent.path` in vs code settings) and won't have to deal with perl packages (see #376 for details).

**Comment by MrYann** [comment]
Excellent !

**Comment by James-Yu** [comment]
Sorry for the miss. New version incoming.

**Comment by michaelaye** [comment]
i have Latex Workshop 5.6.1 and have exactly this error? Which version should I get to have this fixed?

**Comment by yzy1996** [comment]
I think you can see this : https://github.com/James-Yu/LaTeX-Workshop/issues/376#issuecomment-432479571

**Comment by MrYann** [comment]
The issue is back !
I do not know what I updated that caused the dependency to be required again (I never installed log4perl, and it was fine until now). And Issue 376 is not the solution :  latexindent is found. The problem is log4perl.

**Comment by tamuratak** [comment]
We can do nothing on our side.
