### ISSUE TITLE
Select environment slow in long document

### ISSUE THREAD

**Issue by userrand** [James-Yu/LaTeX-Workshop#3980]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

First, this extension is amazingly good.

Now for the problem:

"Select environment" takes about 8 second on 44 page document but if i remove the content above the equation, it is practically immediate.  "Select environment is also slow with long documents. 

Is the command scanning all the lines from the top until the current equation? If so, why? Why not search directly for the closest math enclosing delimiters around the equation ignoring the rest?

## The Solution*
> _Please provide a solution you would like to have._

search for the nearest delimiters ignoring the rest of the file.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
This is caused by the slow parsing of the current LaTeX document. I'm afraid that you may need to share a working example publicly/privately with me for debugging.

**Comment by userrand** [comment]
> This is caused by the slow parsing of the current LaTeX document. I'm afraid that you may need to share a working example publicly/privately with me for debugging.

The command parses the whole document each time? Is there a way to cache that? I do not know how to make vs code plugins but if there is a way to obtain the cursor position, I would search for the first enclosing $,\( ,\[,$$ or begin going left and up and the opposite way in the other direction. but there could be a lot of edge cases.

I saw that the processing is slow on chapter 11 of the latex found here https://arxiv.org/format/2106.10165.

**Comment by James-Yu** [comment]
Sorry for my late reply. Just find some time to process this backlog.

I've tested on my laptop on the said chapter 11. Selecting the current environment, though is not instantaneous, is quite acceptable under half a second for the `align` at line 414. Can you please help profile on which line is the selection time-consuming in this file for example?

**Comment by userrand** [comment]
@James-Yu 

I checked again and it takes about 7 seconds for practically any equation, for example, on line 425 of 11_global.tex, `$\z{i}{\delta}{\ell}$`. I disabled all extensions (via the command pallete) then activitated only latex workshop.

I provide below further information

vscode version 1.81 (July 2023 version)

latex workshop version v9.13.4 (up to date)

The laptop is about maybe 2 or 3 years old laptop and is fairly fast in general (it's a gaming laptop that i got for the gpu (but low vram/memory, I believe 8 gb, not sure i would recommend)). 

Further specifications :

part of the output of lscpu

```
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 7 5800H with Radeon Gra
                         phics
    CPU family:          25
    Model:               80
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            0
    Frequency boost:     enabled
    CPU(s) scaling MHz:  47%
    CPU max MHz:         4462.5000
    CPU min MHz:         1200.0000
```
RAM : 13.5 gb

**Comment by James-Yu** [comment]
Your laptop should be far exceeding the requirement of parsing. Can you please look for log lines like the following? This indicates the parsing time of the document. Please try close all editors, wait for a dozen of seconds, open only this file:
```
[12:12:17.175][Cacher] Parse LaTeX AST: %WS1%\11_global.tex .
[12:12:17.930][Cacher] Parsed LaTeX AST: %WS1%\11_global.tex .
```
You may see on my side, the parsing took ~800ms. Not good, but not too bad.

**Comment by userrand** [comment]
@James-Yu 

I am not sure i understand that command as I do not see it in the menu item `view LaTeX Workshop extension log`  when I use `select environment content` from the command palette  ( I see [14:25:38.147][Commander] SelectEnv command invoked.) but i do see it in previous logs of that menu item, in any case here is an example

```
[14:22:31.048][Cacher] Parse LaTeX AST: ~/path/to/Chp11-features/11_global.tex .
[14:22:31.048][Event] ROOT_FILE_SEARCHED
[14:22:31.054][Server] valdOrigin is http://[hidden as i am not sure if it's private]
[14:22:37.198][Cacher] Parsed LaTeX AST: ~/path/to/Chp11-features/11_global.tex .
```

**Comment by James-Yu** [comment]
Yes, that's what I meant. It took 7.1s to parse the AST of this file on your laptop, which obviously wasn't expected. I would recommend you create a slow parsing speed issue at https://github.com/siefkenj/unified-latex, which is the package we use to generate LaTeX AST. At the same time, you may also find it potentially useful to test on https://siefkenj.github.io/latex-parser-playground and see what was going on.

I also understand that you may think the feature should not involve too much computation. That is, however, how it was implemented for now. I will think of better solutions for that but don't reference on these words 😢

**Comment by userrand** [comment]
@James-Yu 

Maybe it is related to the root file search part in the log as the file references a root or something but you do not seem to have that issue when you select equations.

**Comment by James-Yu** [comment]
No, it does not search root file. When you invoke the command, this extension refers to unified-latex to parse the dirty content of the document to generate an AST, based on which the extension further constructs a pair tree. You may want to check the code here
https://github.com/James-Yu/LaTeX-Workshop/blob/643aed6a537a165c98fa34b34c0cbaba24af3185/src/components/envpair.ts#L71

For a better context on why we parse AST instead of doing a RegExp search, you may refer to #3770

**Comment by userrand** [comment]
@James-Yu 

I tried the playground page and using ast, i got a message that the page was not responding but clicked on wait and after a while or something it gave the output but it was quite slow.

I suppose the reason for not using regex is due to not being able to detect matching brackets for inline math with `\(`. It does feel like a bit much to reconstruct an entire expression tree every time we select an equation but I can see some of the issues.

One option could be to allow a maximal equation size setting and then make a temporary file that copied the text from the current cursor position to +/- max equation size and use the parser on that part of the text. If possible, the extension could time the parsing time and if large it could recommend in the status bar to use that setting.

It could also be nice to save the tree and use git or something to see whether that part of the tree needs to be reconstructed but this sounds like it could be harder to figure out (if it could work at all).

**Comment by James-Yu** [comment]
Thanks for the suggestions. You may also see the added complexity to the parsing, and that is among the reasons why I am hesitated in implementing that: highly error-prone and low maintainability. I would suggest you approach `unified-latex` and see what went wrong on their side, as the same document get parsed fairly quickly on my not-very-beefy laptop. My guess is that there are issues with your particular hardware/software setting, which is beyond the scope of this extension or this issue repo.
