### ISSUE TITLE
PDF viewer broken on lates VS code

### ISSUE THREAD

**Issue by fcdimitr** [James-Yu/LaTeX-Workshop#3986]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: [iPad OS 16.6]
- Visual Studio Code Version: [1.82.0-insider]
- LaTeX Workshop Version: [v9.13.4]

- I am using Visual Studio Code Remote Tunnel to a Windows machine.

## The Issue*
I can open and compile LaTeX files, but I cannot preview the PDF files (neither via the built-in viewer, nor via web browser over the tunnel). I am trying to view the PDF on an iPad.

### Reproduction Steps
Simply connect using tunnels to a remote machine (I tried Windows and Linux). Compile a document and try to see the generated PDF.

**Comment by James-Yu** [comment]
Unfortunately, we don’t provide support to iOS.

**Comment by fcdimitr** [comment]
Sorry for the confusion. The error appears regardless of the OS. I opened another issue:  #3991
