### ISSUE TITLE
Code Folding working incorrectly

### ISSUE THREAD

**Issue by jetlime** [James-Yu/LaTeX-Workshop#3987]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System: macOS Ventura 13.5
- Visual Studio Code Version:  1.81.1 (Universal)
              Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
              Date: 2023-08-09T22:20:33.924Z (1 wk ago)
              Electron: 22.3.18
              ElectronBuildId: 22689846
              Chromium: 108.0.5359.215
              Node.js: 16.17.1
              V8: 10.8.168.25-electron.0
              OS: Darwin arm64 22.6.0
- LaTeX Workshop Version: 9.13.4
- TeX Distribution Version: TeX Live 2023, v. 6.3.5

## The Issue
In latex files who do not contain preamble code at the end of the document such as ```\end{document}```, the collapsing
function does not work correctly. If the document ends with a section's content, the collapsing function will not hide the last line of the document even if it belongs to the section I wish to collapse. 

A document ending with the content of a section is quite common and can be found in ```.tex``` files imported into other latex files. 

### Reproduction Steps
1. Create any ```.tex``` file
2. Place the following content inside it,
```tex
\section{a}
  paragraph
\section{b}
this is a paragraph.
this is the last line of the .tex document.
```
4. Using the collapse arrows on the left hand-side, collapse section ```a``` and section ```b```.
5. I observe section ```a``` collapsing correctly, while section ```b``` collapses every content of its section besides the last paragraph.

__Before collapsing:__

<img width="585" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/29337128/788fed3e-bd98-4b3e-9460-9da77b601a96">

__After collapsing:__

<img width="542" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/29337128/8062e511-d221-40c2-8fb5-11af8ab0b026">

### Expected Behavior
The collapsing of the last section b shall hide every content of the section itself. The last line of the section shall not be visible.

## Anything Else?
- As this issue is related to GUI, I do not have any logs.
- The incorrect behavior works for each dividing latex command (section, subsection, paragraph..) who do not have an ending tag. To solve the issue the regex in charge of searching for the content to fold shall look for an EOF instead of simply searching for any ```\end``` tag.

**Comment by jlelong** [comment]
I think this is related to #3983 because the range of sectioning commands is currently wrong.

**Comment by jlelong** [comment]
Now that #3983 is fixed, I am closing this issue.
