### ISSUE TITLE
ConTeXt Support

### ISSUE THREAD

**Issue by ljrk0** [James-Yu/LaTeX-Workshop#3988]
## Pre-checks
- [x] The feature request has not been suggested in this repository.

## The Missed
- Some internal logic is hardcoded to certain file types and expectations, e.g.:
   - Looking for `\documentclass`
   - Only including files named in `inferLanguageId`: https://github.com/James-Yu/LaTeX-Workshop/blob/3a32f1b2b03f08d8a535427f210a86f966965cd8/src/components/manager.ts#L191-L206
- All this unnecessarily constraints LaTeX Workshop to only LaTeX, [ConTeXt](contextgarden.net/) -- a different macro package -- is unsupported, despite being very closely related.

## The Solution
- Allow for different "tags" to detect the root file or a direct override/configuration in the workplace's settings
- Make the list of extensions used in the above function configurable, similar to `latex-workshop.latex.search.rootFiles.include`

## Anything Else?
- Additionally, later, support for the `context` recipe could be added.

**Comment by James-Yu** [comment]
I do not use or know how to use Context, nor do other maintainers if I’m right. Therefore, we need the community help on this.

**Comment by ljrk0** [comment]
I can totally assist with this, but I've no experience in Js nor with VS Code scripting.  As far as I can tell, the only really critical thing would be to add `.mkiv`, `.mkvi`, `.mkix` etc. to the list of recognized/accepted extensions.  That should be rather straight-forward – alternatively, making this configurable.

Anything else, an alternative to the `documentclass` logic and special recipes are leas required.  FWIW, I can already build ConTeXt files in this extension if I use the `.tex` extension.  But it is customary to also use different file extensions, that's all.
