### ISSUE TITLE
Extending Docker Executions

### ISSUE THREAD

**Issue by arget888** [James-Yu/LaTeX-Workshop#3989]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- I'm using your great plugin with docker to build my PDF's on Mac. After many hours to check why i can not use biber within a docker installation. I recognized following output: 'Do not use Docker to invoke the command: biber' so i searched a bit in the source code and found out, that you only support latexmk to run inside a docker container. That means i have to install biber or other tools i need in my build process directly on my local machine and not inside the docker container!

## The Solution*
> _Please provide a solution you would like to have._
- It would be great if all commands are executed inside docker if docker is enabled or at least have a option field `runInDocker` in the settings of the tool definitions.

**Comment by James-Yu** [comment]
Please note that docker support is not official, and adding features solely rely on community effort with a very strict code check to avoid adding maintenance burden. I'm closing this issue for now, but discussions are always welcomed.
