### ISSUE TITLE
Support output to image? (feature req)

### ISSUE THREAD

**Issue by jaymickey** [James-Yu/LaTeX-Workshop#399]
### Description

It would be awesome if you could support output to image (.png preferred) via command palette.

It appears the [`standalone`](https://ctan.org/pkg/standalone?lang=en) package could help with this? Although, it requires [ImageMagick](https://www.imagemagick.org/script/index.php).

Alternatively there is [`pdftoppm`](https://linux.die.net/man/1/pdftoppm)

**Comment by James-Yu** [comment]
This can be achieved by [vscode tasks](https://code.visualstudio.com/docs/editor/tasks).

**Comment by jaymickey** [comment]
Oh right, of course! Sorry for the time waste @James-Yu!
