### ISSUE TITLE
PDF viewer broken on latest VS code via Remote Tunnels

### ISSUE THREAD

**Issue by fcdimitr** [James-Yu/LaTeX-Workshop#3991]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: [macOS 13.3] (actually the error appears under both Windows and Linux as well)
- Visual Studio Code Version: [1.81.1]
- LaTeX Workshop Version: [v9.13.4]

- I am using Visual Studio Code Remote Tunnel to a Windows machine.

## The Issue*
I can open and compile LaTeX files, but I cannot preview the PDF files (neither via the built-in viewer, nor via web browser over the tunnel). I am trying to view the PDF either via the application or via the vscode-dev web browser.

### Reproduction Steps
Simply connect using tunnels to a remote machine (I tried Windows and Linux). Compile a document and try to see the generated PDF.

**Comment by Msadat97** [comment]
I also have the same issue that compiling a multi-file project on my remote server breaks over ssh but the same project can be compiled locally.

**Comment by James-Yu** [comment]
We have not touched the communication between LW server and web viewer for a very long time. My guess is that some of your local LAN configurations (e.g., firewall) is interfering the operation. Can you please do a check to see since which version of LW this feature stopped working?

**Comment by ZikangXiong** [comment]
Same issue after upgrading VS Code to 1.82.0. 

Before 1.82.0:
The internal PDF viewer works fine when connecting with ssh, but does not work when connecting with vscode tunnel extension. 

After 1.82.0:
The internal PDF viewer does not work for both. 

Disabling firewall on server/in local does not work.

The pdf can be opened by `PDF Viewer` extension, but it does not support jumping back from PDF to tex.  

Code version:
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621


My guess is that the port forwarding somehow gets down.

**Comment by xukai92** [comment]
I'm seeing this same viewer as https://github.com/James-Yu/LaTeX-Workshop/issues/3991#issuecomment-1710892711 since today.

**Comment by James-Yu** [comment]
I’d suggest you file issues on vscode repository (or maybe vscode-remote?), as this issue is beyond our reach.
