### ISSUE TITLE
Autocompletion of custom commands

### ISSUE THREAD

**Issue by AVAtarMod** [James-Yu/LaTeX-Workshop#3995]
## Pre-checks*
- [ ] The feature request has not been suggested in this repository.

## The Missed*
Latex-Workshop not provide auto-completion for custom commands that
created using `\NewDocumentCommand{name}{xargs}{def}`.

Screenshot:
![Screenshot from 2023-08-24 20-51-55](https://github.com/James-Yu/LaTeX-Workshop/assets/37958026/7dce7899-8678-44ad-8fad-924f022c8b95)

MVE:
```latex
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\NewDocumentCommand{\test}{}{a_{oops}}
\NewDocumentCommand{\longFuncNameSoAutoCompleteWillNotShowAnyGuesses}{}{a_{oops2}}

\begin{document}
\(\test, \longFuncNameSoAutoCompleteWillNotShowAnyGuesses\)
\end{document}
```

Some time ago users requested similar thing, but their needs was not same as in
my request.
## The Solution*
Parse command definition similar way as `\newcommand`

**Comment by James-Yu** [comment]
`\NewDocumentCommand` operates quite differently from `\newcommand`. It requires a whole new set of logics for parsing. Yet I do think the support is necessary. Will do later (but not very soon as I was too busy recently).
