### ISSUE TITLE
Display `missing character` message in the problem panel

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#3999]
## Pre-checks*

- [x] The feature request has not been suggested in this repository.

## The Missed*

Currently, `Missing characters` is logged when a symbol not in the font is attempted to be output, but LaTeX Workshop does not detect this as a warning message.

This message is an important information as a warning message and should be displayed on the problem panel. If it is not displayed, there will be a delay in noticing that the symbol is not being output.

test file:

```latex
%#!lualatex
\documentclass[a4paper]{article}
\usepackage{unicode-math}
\begin{document}

$A \Vbar B$

\end{document}
```

The terminal log has the following message:

```log
Missing character: There is no ⫫ (U+2AEB) in font [latinmodern-math.otf]:mode=base;script=math;language=dflt;mathfontdimen=xetex;!
```

## The Solution*

Detect `Missing characters` message in the log and display them as a warning message in the problem panel.

**Comment by James-Yu** [comment]
Thanks for the feature request. Before I finally have some time to look into this, may I recommend you (or anyone interested) to look into https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/parserlib/latexlog.ts and make a contribution? Totally voluntary and thanks.

**Comment by Yarakashi-Kikohshi** [comment]
I could not do anything to help, but your update now causes the warning to appear. thank you! :tada:
