### ISSUE TITLE
Does not compile without Preview pane

### ISSUE THREAD

**Issue by bartosz-antosik** [James-Yu/LaTeX-Workshop#4]
After upgrade to 0.2.1 extension ceased to to compile. 

It was unclear to me it it's not caused by me tweaking the configuration as I have migrated synctex.exe from TeX Live to MiKTeX but it turns out to be an exception in compile.js. It happens in this line:

preview_1.getPreviewPosition();

where exception's message says:

"Cannot read property 'send' of undefined"

If the preview is NOT displayed prior to compilation.

**Comment by James-Yu** [comment]
Yes I can reproduce this bug. Working on a new version to fix it.

**Comment by James-Yu** [comment]
@bartosz-antosik 0.2.2 uploaded to marketplace. Please check if the problem exists.

**Comment by bartosz-antosik** [comment]
The issue is is solved. Thank you.
