### ISSUE TITLE
Command-Popup opens sometimes when backslash is typed

### ISSUE THREAD

**Issue by y-spreen** [James-Yu/LaTeX-Workshop#400]
### Description

This is one of those inconsistent issues, that only shows up when you don't want to see it, and seems impossible to reproduce. Sometimes when I type a backslash, a command-popup opens, this is what it looks like:  
![image](https://user-images.githubusercontent.com/12631527/35673103-d0b5de6e-0740-11e8-9ab3-0157f2d3c8fc.png)

It's some sort of IntelliSense, because I can search it for LaTeX commands, but it's not as complete as the usual IntelliSense. It seems to only contain functions, and not constants like Greek letters.

### How to reproduce

No idea. Like every 10th backslash-press opens this menu.

1. I do have a german keyboard
2. this means I type `\` with `alt gr` + `ß/?` or `ctrl` + `alt` + `ß/?`
3. Maybe this has something to do with it?

### Expected behavior

Inline-IntelliSense

### Actual behavior

IntelliSense-PopUp

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

No Output. (see additional Info)
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information

As you can see in the image, alpha finds nothing, and there is no output.
![image](https://user-images.githubusercontent.com/12631527/35674880-5be1edde-0746-11e8-890c-538a7726ec0f.png)

**Comment by James-Yu** [comment]
When you select something and then type `\`, this thing comes up. If you select any command, the selected one will surround the selection. This feature can be disabled in the config.

**Comment by y-spreen** [comment]
I did not select anything! This is not the solution
