### ISSUE TITLE
Compile at start-up

### ISSUE THREAD

**Issue by oliviercailloux** [James-Yu/LaTeX-Workshop#4001]
## Pre-checks
- [x] The feature request has not been suggested in this repository.

## Context
Having enabled auto-compiled when document is modified.

## The Missed
When opening a latex document that has been modified out of LaTeX-Workshop, the corresponding PDF is not up-to-date. I have to trigger a manual compilation to update it, which is sub-optimal (have to use the mouse or remember a shortcut just for this case) as afterwards I never have to trigger compilation manually.

## The Solution
Provide a configuration option that compiles (meaning, triggers the default task) the document when opening. 

## Anything else?
Thanks for this great tool.

**Comment by James-Yu** [comment]
Thanks for the feature request. However I do consider the request to be niche and may lead to unprecedented side effects. Sorry to turn it down.
