### ISSUE TITLE
Can the definition provider also accept \thlabel{...} as well as \label{...}?

### ISSUE THREAD

**Issue by teorth** [James-Yu/LaTeX-Workshop#4002]
Currently it seems that the definition provider for the "Go to definition" feature accepts theorems that are labeled using the usual \label{} tag, but not the \thlabel{} used in the theoremref package.  Would it be possible to update the definition provider to also accept \thlabel{} as well?

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Solution*
> _Please provide a solution you would like to have._
- This may just be a matter of adjusting the definition-label entry in LaTeX.tmLanguage.json

**Comment by James-Yu** [comment]
This is because that the upstream https://github.com/siefkenj/unified-latex does not support `theoremref` package. I will contribute to that when I have some time later.

**Comment by Enivex** [comment]
You could consider using cleveref instead

**Comment by teorth** [comment]
> You could consider using cleveref instead. It should cover what theoremref does, but also does much more.

OK, I was unaware of this package, and on playing with it, it does address my specific use case.  Thanks!

**Comment by James-Yu** [comment]
It seems that we have a better solution and this issue natural resolves. Closing for now.
