### ISSUE TITLE
Custom trim values and different trim values for vertical and horizontal dimensions in PDF viewer

### ISSUE THREAD

**Issue by mocenigo** [James-Yu/LaTeX-Workshop#4004]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The trim feature in the PDF previewer is absolutely great, especially for those of us that write scientific papers and can thus eliminate the white border to get a better usage of the screen real estate. However, for many publication, esp. in mathematics and cryptography, the borders one the top and bottom are, percentage-wise, larger than the left and side borders, so a lot of space above and below still remains even if the sides have been trimmed satisfactorily.

## The Solution*
> _Please provide a solution you would like to have._
- A solution would be to have 2 (or even 4) trim values, for the four sides. H(horizontal) and V(vertical), and if R(right), L(eft), T(op), B(bottom) values are also given they would override H and V.  Some formats shift the printed part a bit, so having four values could have a value (sic), but having two values for H and V 
- It would be nice to have it confifgurable from the menu
- Another feature could be to take it from the main tex file. for instance, at the top one could add
   - % !TRIM value
   - % !TRIM H=value, V=value
and then apply automatically to the preview. This would absolutely ROCK.

## Anything Else?
> _Add any other context about the feature request below._
- This project is simply fantastic.

**Comment by James-Yu** [comment]
Thanks for the request. Unfortunately the described behaviour, while looks simple, is too hard to be implemented with the same level of rendering due to the limit to the underlying viewer code. Sorry to turn it down.

**Comment by mocenigo** [comment]
Ok so I will add something like

\addtolength{\paperwidth}{-2in}
\addtolength{\paperheight}{-1.5in}
\addtolength{\evensidemargin}{-1in}
\addtolength{\oddsidemargin}{-1in}
\addtolength{\topmargin}{-0.5in}

at the begin of a document and then remove it before shipping.
