### ISSUE TITLE
When using Docker images TexLive commands are not accessible (`latexdiff`, ...)

### ISSUE THREAD

**Issue by iagobaapellaniz** [James-Yu/LaTeX-Workshop#4005]
## Pre-checks*
- [ ] The feature request has not been suggested in this repository.

## The Missed*
- I'm using a docker image, and accessing latexdiff command of that image is not trivial at all. Providing a basic tool just to produce diff.tex would make live much easier for whom we use latex images.

## The Solution*
- simple command "Latexdiff" which asks for first and second files, and then it produces diff.tex
- the feature could be more general. Would it be possible to have a command "Run command in environment ..." which ask for a prompt which would run inside the container? This way we gain access to the whole set of texlive commands and more. 

## Anything Else?
- Sorry for reopening/reposting about #3077 , ... and thanks

**Comment by James-Yu** [comment]
We don't officially support docker.
