### ISSUE TITLE
\input causes strange behavior

### ISSUE THREAD

**Issue by vilasopher** [James-Yu/LaTeX-Workshop#4006]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [MacOS Ventura 13.4.1]
- Visual Studio Code Version: [1.82.0]
- LaTeX Workshop Version: [9.13.4]
- TeX Distribution Version: [TeX Live 2023]

## The Issue*
> _Please briefly describe the issue you come across._
- LaTeX studio cannot properly compile files that start with \input{some other file}. It works fine for files that don't input anything else, but when I try to compile a file which starts with \input, it seems to just choose a random file to compile (and view the pdf render of).

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Start with a file that uses \input at the top.
2. Compile it with the green "play" button. Some other file compiles (I think).
3. View the pdf with the "pdf sideview" button. Some other file comes up.

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- I would expect that the correct file is compiled and viewed.

**Comment by James-Yu** [comment]
Compile behavior not related to this extension.

**Comment by vilasopher** [comment]
Wait, this is specific to how the extension works. Compiling works fine on my computer outside of the extension. The only issues I have are behavior within the extension. I guess the issue isn't the compilation itself but the extension knowing which file to compile

**Comment by James-Yu** [comment]
The extension does not instruct your latex binaries which input files to consider. Please provide a minimal working example if you believe this was a bug.

**Comment by vilasopher** [comment]
Okay, after reading the documentation I realized what I could do to make things work. I restructured my projects to avoid using \input and instead wrote some package files. The issue was that the \documentclass command was not in the file I was trying to compile.

So I guess this is not a bug, but the behavior changed between versions as far as I can tell. The way I was doing things before was working before a few updates ago, but I guess it was the wrong way. Anyway, thanks for all your work on the extension!

**Comment by riZZZhik** [comment]
Hi @James-Yu,

I'm having a similar issue. I have two files: base.tex and example.tex. In base.tex, I define the document class, packages, theorems, etc. Then, I include it using `﻿\input{base.tex}` in example.tex and write the document there.

The problem is that the extension ignores the opened example.tex file and tries to build base.tex instead, even though the file itself is correct. It works fine when I build it using latexmk in the terminal: `latexml -pdf example.tex`.

I believe this happens because example.tex is missing the required \documentclass syntax and extension ignores it. Is there a way to disable this check and build the opened file?

### Example files:

base.tex:

```tex
\documentclass[a4paper]{article}

% Language packages
\usepackage[utf8]{inputenc}
\usepackage{cmap}
\usepackage[T2A]{fontenc}
\usepackage[russian]{babel}

% Geometry
\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm,bindingoffset=0cm]{geometry}

\author{Secret Secret Secret}
```

example.tex:

```tex
\input{../base.tex}

\title{Calculus Seminars}
\date{September 2023}

\begin{document}

\maketitle

\section{Семинар \#1}
Hello world!

\end{document}
```

**Comment by James-Yu** [comment]
Please see latex-workshop.latex.rootFile.indicator

**Comment by riZZZhik** [comment]
Yes, it works for this case. 
But what if `\begin{document}` is also present in _base.tex_? 
Currently, `latex-workshop.latex.rootFile.indicator` only supports two specific options. Would it be possible to modify it to accept any string?

## Example files:

base.tex:
```tex
\documentclass[a4paper]{article}

% Language packages
\usepackage[utf8]{inputenc}
\usepackage{cmap}
\usepackage[T2A]{fontenc}
\usepackage[russian]{babel}

% Geometry
\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm,bindingoffset=0cm]{geometry}

\title{abc}
\author{Secret Secret Secret}

\begin{document}
\maketitle
```

example.tex:

```tex
\input{base.tex}

\section{Семинар \#1}
Hello world!

\end{document}
```

**Comment by James-Yu** [comment]
You can always set your file name in the tools.

**Comment by riZZZhik** [comment]
Sorry, I didn't understand.
Tools for building work fine. The extension fails to recognize the example.tex file and outlines/builds/etc the base file.

**Comment by James-Yu** [comment]
We are unlikely to support custom string. My suggestion is to avoid this use case, which to me does not make notable sense.

**Comment by riZZZhik** [comment]
To me either, but my professors are sending their text files like this. I will have to manually fix them :(
Anyway, a huge thanks for the support!
