### ISSUE TITLE
Wrong comment character inside macrocode in dtx files

### ISSUE THREAD

**Issue by JLanzuisi** [James-Yu/LaTeX-Workshop#4008]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Ubuntu 23.04
- Visual Studio Code Version: 1.18.1
- LaTeX Workshop Version: 9.13.4
- TeX Distribution Version: TeXLive 2022

## The Issue*
> _Please briefly describe the issue you come across._

When editing `dtx` files inside a `macrocode` environment, using the `Toggle Line Comment` command adds 
the `^^A` character at the beginning of the line, when I think the correct behavior is to add a `%`.
This is because text inside `macrocode` is treated verbatim so a  `^^A` gets added to the produced source file,
in my case a `.sty` file, and in that context  `^^A` is not a comment.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Open `skeleton.dtx` from [dtxtut](https://ctan.org/tex-archive/info/dtxtut) with the extension enabled.
2. Inside a `macrocode` run `Toggle Line Comment`.
3. Then run `latex` on `skeleton.ins` producing `skeleton.sty`.
4. The `^^A` is in `skeleton.sty`, producing an error eventually when the package is loaded.

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Use `%` instead of `^^A` in `macrocode`.

**Comment by James-Yu** [comment]
Unfortunately, vscode cannot use different comment signs according to the context for a same type of file. This is a limit by the upstream, and we cannot circumvent it.
