### ISSUE TITLE
Cannot use PDF viewer: Change server.host from 'localhost' to '127.0.0.1'

### ISSUE THREAD

**Issue by rachitnigam** [James-Yu/LaTeX-Workshop#401]
After an update today, I was having issues with the 'View PDF in new tab'. After some debugging, it turned out that the server that latex-workshop tries to create uses the string value of `localhost` which was getting resolved to my universities network and getting blocked with an EADDRNOTAVAIL. 

Changing the string value 'localhost' to '127.0.0.1' in components/server resolved this issue for me. I am not sure if the correct solution would be to change this value in the repo, but I wanted to bring this issue up.

### Expected behavior

PDF viewer should work.

### Actual behavior

Cannot establish server connection.

### Log messages

Modified the code to log server.on('error') events. Line 1 is the output I get before changing 'localhost'
to '127.0.0.1'.

<details>
<summary>LaTeX Workshop Output</summary>
[11:51:43] Server error: Error: listen EADDRNOTAVAIL 128.119.113.200
[11:51:43] Default environments loaded
[11:51:43] LaTeX Workshop version: 3.13.0
[11:51:43] Default commands loaded
[11:51:43] Default unimathsymbols loaded
</details>

### Additional Information
Running antergos arch linux.

**Comment by James-Yu** [comment]
127.0.0.1 is reserved for ipv4. I need to find a solution for ipv6 only users. Quite not familiar with such things 😢

**Comment by James-Yu** [comment]
Try this fix and see if ipv6 users would complain about it. Have no such network environment to simulate.

**Comment by rachitnigam** [comment]
Thanks for the quick fix and the awesome plugin!
