### ISSUE TITLE
Hiding app on macosx does not work from pdf preview pane

### ISSUE THREAD

**Issue by mocenigo** [James-Yu/LaTeX-Workshop#4010]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The issue has not been reported in this repository.
- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: macOS Ventura
- Visual Studio Code Version: 1.81 (but also VSCodium 1.80)
- LaTeX Workshop Version: 9.13.4
- TeX Distribution Version: TeX Live 2023

## The Issue*
> Open PDF preview in a pane
- Select some text in the  PDF pane.
- Press CMD-H to hide the application
- the application DOES NOT hide
- click in the text editing window
- Press CMD-H to hide the application
- the application hides

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
See above

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- The application should hide if CMD-H is pressed. Note that under the "VSCODIUM" menu there is a Hide Application: CMD-H command listed also when in the preview.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
No new log messages appear when I press CMD-H

**Comment by James-Yu** [comment]
This is a limit by vscode, where key bindings in webview is not passed to the system. You may consider file an issue in vscode's repository.
