### ISSUE TITLE
Syntax Highlight Issue

### ISSUE THREAD

**Issue by sleepymalc** [James-Yu/LaTeX-Workshop#4014]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: macOS 13.5.2 (22G91)
- Visual Studio Code Version: 1.82.2
- LaTeX Workshop Version: 9.13.4
- TeX Distribution Version: TeX Live 2023

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- The syntax highlight of `\( \)` behaves weird in, e.g., `\hyperref[]{}`
<img width="180" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/60427058/6b221286-306a-427a-b032-93fe8577714f">
- The previous version (e.g., version 9.7.0) is the expected highlight behavior
<img width="174" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/60427058/cd9a357b-21cd-48db-8b82-3e5a370762a0">

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Type `\hyperref[\(\)]{\(\)}`

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Ref. The Issue: 
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/60427058/c27b7c5e-d25a-44dc-8eac-5966735da171)

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), could you please post your issue there and clarify what behaviour you expect?
