### ISSUE TITLE
Syntax highlighting for German quotation marks

### ISSUE THREAD

**Issue by jfrerking** [James-Yu/LaTeX-Workshop#4015]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Windows 11
- Visual Studio Code Version: 1.82.2
- LaTeX Workshop Version: 9.13.4
- TeX Distribution Version: MiKTeX 4.9

## The Issue*
Closely related to issue #593 . German quotation marks are often written as `text ,,quote`` text` in LaTeX. The syntax highlighting interprets everything after the closing marks (two back ticks) as a string and highlights it accordingly. One can circumvent the problem by using the csquotes package and writing `text \enquote{quote} text`, but it would be great, if the syntax interpreter treats ,,quote`` as a string, indicated by two commas not followed by any space (or ignores the two back ticks if they are not followed by '' anywhere?). 

(I agree with user stone-zeng in issue #593 that string highlighting seems unnecessary in tex-files generally, but understand if disabling it altogether is not possible.)

Thank you!

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), so we have moved the issue to that repository: 
- jlelong/vscode-latex-basics#68
