### ISSUE TITLE
Hover.preview.snippet not working

### ISSUE THREAD

**Issue by asapsmc** [James-Yu/LaTeX-Workshop#4016]
## Pre-checks*
- [X] The issue has not been reported in this repository.
- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: MacOS Ventura 13.5.2
- Visual Studio Code Version: 1.82.2

## The Issue*
- I'm getting "Unknown configuration setting for " "latex-workshop.hover.preview.snippet.enabled": true, and also this is not working, ie, I'm not getting any preview of images.

**Comment by jlelong** [comment]
I cannot remember of any configuration variable named `latex-workshop.hover.preview.snippet.enabled`. The configuration variable you are looking for is [`latex-workshop.hover.preview.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewenabled). Its default value is `true`. If you experience graphics preview failures, please open a new issue and provide the complete logs (extension and developer console) along with an example to reproduce it.

**Comment by asapsmc** [comment]
> I cannot remember of any configuration variable named `latex-workshop.hover.preview.snippet.enabled`. The configuration variable you are looking for is [`latex-workshop.hover.preview.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewenabled). Its default value is `true`. If you experience graphics preview failures, please open a new issue and provide the complete logs (extension and developer console) along with an example to reproduce it.

You're absolutely right, I don't know how I inadvertently included 'snippet' in the setting. Thank you.
