### ISSUE TITLE
Structure panel appendix numbering

### ISSUE THREAD

**Issue by briochemc** [James-Yu/LaTeX-Workshop#4017]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
Maybe this is just the environment I am using, but my appendix section numbers in the structure panel do not restart and thus do not match the PDF:

<table>
<tr><th>PDF (counter is restarted for appendices)</th><th>Panel structure (counter is not restarted)</th></tr>
<tr>
<td>
      
```
1. Introduction
2. Methods
3. Results
4. Conclusions
A1. Appendix 1
A2. Appendix 2
```

</td>
<td>

```
1. Introduction
2. Methods
3. Results
4. Conclusions
5. Appendix 1
6. Appendix 2
```

</td>
</tr>
</table>

## The Solution*
Maybe the presence of `\appendix` can be parsed and used to restart appendix counters?

**Comment by briochemc** [comment]
Wow such quick turnaround! Thank you so much!

However I'm sorry to say that I made a mistake in my haste to post this issue... What I wrote above is not the desired output. Appendices should start a new alphabetical counter, so more like

<table>
<tr><th>PDF (New alphabetic counter is started for appendices)</th><th>After 4f5bc3f</th></tr>
<tr>
<td>

```
1. Introduction
2. Methods
3. Results
4. Conclusions
A. First appendix 
B. Second appendix
```
</td>
<td>

```
1. Introduction
2. Methods
3. Results
4. Conclusions
A.1 Appendix 1
A.2 Appendix 2
```
</td>
</tr>
</table>

**Comment by James-Yu** [comment]
The output in the pdf depends on your particular class file. The implemented behavior is the default latex one, and is unlikely to be changed or customized for simplicity.

**Comment by briochemc** [comment]
Oh I see, I wrongly assumed the default was A, B, C, and so on... Thanks for the quick (and correct) fix! 🚀

**Comment by KCaglarCoskun** [comment]
The numbering is incorrect in my environment for the following mwe.

```
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}
\section{section}
adsf
\appendix
\section{Section}
\subsection{Subsection}
To find t
\subsubsection{subsubsection}
This c
\section{Section}
\subsection{Subsection}
To find t
\subsubsection{subsubsection}
This c
\end{document}
```
 which results in
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/19360095/8e8b08e6-7c2b-4406-b1f5-61671ccab8f4)
and
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/19360095/2e1af6bc-05c8-43fb-a328-b458cabe3b5c)

I am using MiKTeX, although I am not sure if that would change the defaults. The default in Overleaf is also in unison with what I have observed: [https://www.overleaf.com/read/nvnytmrhxdss](https://www.overleaf.com/read/nvnytmrhxdss)
