### ISSUE TITLE
Autocompletion does not take commands from latex-workshop.intellisense.package.dirs

### ISSUE THREAD

**Issue by fachu000** [James-Yu/LaTeX-Workshop#4027]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: macOS Monterey 12.5.1
- Visual Studio Code Version: 1.82.2
- LaTeX Workshop Version: [9.14.0] - 2023-09-19
- TeX Distribution Version: TeX Live 2022

## The Issue*
It is described [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#commands-starting-with-) that if I place a .json file generated by `pkgcommand.py`, then autocomplete will use the completions in the files specified by `[latex-workshop.intellisense.package.dirs](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisensepackagedirs)`. However, no such completions show up in the autocompletion list. Please see the screenshots [here](https://www.dropbox.com/s/dtu472bumoqpxvf/Screenshot%202023-09-26%20at%2023.14.30.png?dl=0) and [here](https://www.dropbox.com/scl/fi/rxm4w6ujmw8x41ig9p0z6/Screenshot-2023-09-26-at-23.15.49.png?rlkey=yvnb52kjmcd4i1nj7yfu37t7p&dl=0).

### Reproduction Steps
1. I just created a new profile, to make sure there is no issue with configuration or other extensions.
2. Install LaTeX-Workshop
3. Create a CWL command, e.g. [this](https://www.dropbox.com/scl/fi/4up9dy4f2vfadvanpyd9r/test.cwl?rlkey=z3wlcllyz3tt13xojk4gs753y&dl=0).
4. Use `pkgcommand.py` to generate a .json file from the above CWL file. This yields [this](https://www.dropbox.com/scl/fi/0geb77flsnd5db1o9lfgv/test.json?rlkey=7yvpmxzu93ognks9wklhxr97z&dl=0) json file.
5. Add the folder containing the json file to `latex-workshop.intellisense.package.dirs`
6. Close and open VS Code to check whether this fixes the problem --> it does not
7. Go to a LaTeX file but the commands in the aforementioned file do not show up as possible autocompletions.

### Expected Behavior
The commands in the indicated file should show up in the suggested completions.

### LaTeX Workshop Output*
No output produced.

### Developer Tools Console
```
Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///Users/dani/.vscode/extensions/james-yu.latex-workshop-9.14.0/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///Users/dani/.vscode/extensions/james-yu.latex-workshop-9.14.0/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///Users/dani/.vscode/extensions/james-yu.latex-workshop-9.14.0/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///Users/dani/.vscode/extensions/james-yu.latex-workshop-9.14.0/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///Users/dani/.vscode/extensions/james-yu.latex-workshop-9.14.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:46
log.ts:421  INFO [perf] Render performance baseline is 17ms
```

**Comment by James-Yu** [comment]
You also need to `\usepackage{test}` to make the extension search for a `test.json` file. We set this to avoid aggressively reading all `json` files, which may not be related and can be dangerous.

**Comment by James-Yu** [comment]
It's true that the Wiki description is not clear. Will fix.

**Comment by fachu000** [comment]
Perhaps reading the files in `latex-workshop.intellisense.package.dirs` e.g. every time the project is built would be easy to do and would not be heavy, right?

**Comment by fachu000** [comment]
The command `Developer: Reload Window` does the job, so I came up with a solution. 

I wonder: Is there a way to prioritize the suggestions from `latex-workshop.intellisense.package.dirs` over the ones in standard packages? That would be very useful.

Thanks!!

**Comment by James-Yu** [comment]
Unfortunately, no. The priority (or order of suggestion) is automatically determined by vscode. This extension cannot instruct how items are sorted.

**Comment by fachu000** [comment]
Ok, thanks anyway.
