### ISSUE TITLE
Duplicate textcite and citeauthor autofill suggestions

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#4029]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [*] The issue has not been reported in this repository.
- [*] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [*] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [*] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Mac Sonoma
- Visual Studio Code Version: 1.82.2
- LaTeX Workshop Version: 9.14
- TeX Distribution Version: TeX Live 2019

## The Issue*
For `textcite` and `autocite` commands, I see that there are duplicate suggestions, one small-case and another upper-case. This is confusing and sometimes I have to consciously pick the small-case one as the autosuggestion is first suggesting the upper-case one. (Not sure why is this.)

<img width="540" alt="SCR-20230928-rnnh" src="https://github.com/James-Yu/LaTeX-Workshop/assets/24664855/462a85c1-e128-4a6a-8d01-615edc75d7af">

<img width="512" alt="SCR-20230928-rrle" src="https://github.com/James-Yu/LaTeX-Workshop/assets/24664855/93cba5da-cb11-4309-b605-346e981c7a93">

And for `citeauthor`, there is no smallcase command; only uppercase. Not sure why this is the case. 

<img width="568" alt="SCR-20230928-rnja" src="https://github.com/James-Yu/LaTeX-Workshop/assets/24664855/f76860f9-6ab1-41f8-a0cf-b16611b1cdfd">

I am not sure whether these are features or just discrepancies.  Anyways, thought of pointing it out.

Also, I was surprised to see that [a bug I reported in 2019](https://github.com/James-Yu/LaTeX-Workshop/issues/1661) indicates that this was the behaviour from a long time.

**Comment by James-Yu** [comment]
`\textcite` defined here:
https://github.com/texstudio-org/texstudio/blob/da236299dabc38315b3c2e5d286608931b40b180/completion/biblatex.cwl#L491-L505

`\citeauthor` defined here:
https://github.com/texstudio-org/texstudio/blob/da236299dabc38315b3c2e5d286608931b40b180/completion/abntcite.cwl#L9

If you think that is an error, please create an issue at https://github.com/texstudio-org/texstudio .
