### ISSUE TITLE
when i type ,, not , , in latest version (v9.14.1) it has changed my code color

### ISSUE THREAD

**Issue by Prajakchai** [James-Yu/LaTeX-Workshop#4032]
> _Please fill the following fields with a star (*) and provide as much related information as possible._
* When I type ,, it will change my code color but previous version it did not change my code color
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- your old version when I type ,, it does not change my code color
- 
![Screenshot 2023-10-06 023629](https://github.com/James-Yu/LaTeX-Workshop/assets/126894090/4396553d-d84f-4198-9b36-d80e05ce114b)

-but when I update it to v9.14.1 the lastest version it change my code color when  i type ,,
![3](https://github.com/James-Yu/LaTeX-Workshop/assets/126894090/b4ebcfc3-f41e-4294-8abe-ed28849e36ee)

So i try to spacing ,, to , , and yeah the color back to  normal but my code get error because it want ,, not , , 

## The Solution*
> _Please provide a solution you would like to have._
- I want something that not change my code color

## Anything Else?
> _Add any other context about the feature request below._
- Please READ This problem and Please reply me back ,Thanks for your extension that help me can write latex on vs code

**Comment by bulkazszynka** [comment]
+1 especially annoying when typing in polish since ",," is "open quote" in PL

**Comment by jlelong** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics). Please open an issue at https://github.com/jlelong/vscode-latex-basics and let us discuss there.

This is related to https://github.com/jlelong/vscode-latex-basics/issues/68.
