### ISSUE TITLE
Wrong token on proper quotation

### ISSUE THREAD

**Issue by js-open-projects** [James-Yu/LaTeX-Workshop#4034]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: N/A but I use Windows 10
- Visual Studio Code Version: 1.83.0
- LaTeX Workshop Version: 9.14.1
- TeX Distribution Version: N/A but I use TeX Live 2023

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using none from above

## The Issue*
> _Please briefly describe the issue you come across._
- If you start quotation from double comma (,,) it does not end on double apostrophe (''). It ends on double backprime, but it leads to improper characters in final document used by LaTeX. See the picture
- 
![wrong-quotation](https://github.com/James-Yu/LaTeX-Workshop/assets/25607836/3730f838-3e27-4b09-beb4-dd558d0f615b)

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Type double comma and some text then close it with double apostrophe character.

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Token with quotation should finish after double apostrophe.
- Other solution is to disable such feature. I prefer to disable quotation if they should be marked wrongly.

**Comment by James-Yu** [comment]
#4032
