### ISSUE TITLE
A new command which will replace fragile characters in selected text with \symbol{num}

### ISSUE THREAD

**Issue by js-open-projects** [James-Yu/LaTeX-Workshop#4035]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
- If I enter text like 

```
new_namespace\ClassName{}
```

and make a selection of this line, then I would like to use this new command I receive contents like:

```
new\symbol{95}namespace\symbol{92}ClassName\symbol{123}\symbol{125}
```

The command should replace only following characters to its \symbol representation:
```
@, #, $, %, ^, &, _, {, }, [, ], |, ', \, ", <, >, `, ~
```
As seen it is necessary to use ASCII code for the character.
```
\symbol{64}, \symbol{35}, \symbol{36}, \symbol{37}, \symbol{94}, \symbol{38}, \symbol{95}, \symbol{123}, \symbol{125}, \symbol{91}, \symbol{93}, \symbol{124}, \symbol{39}, \symbol{92}, \symbol{34}, \symbol{60}, \symbol{62}, \symbol{96}, \symbol{126}
```

**Comment by James-Yu** [comment]
Your issue is indeed a feature request and I'm afraid that I personally am not interested in implementing it. Sorry for letting you down.
