### ISSUE TITLE
Option to focus editor on reverse SyncTeX in web browser

### ISSUE THREAD

**Issue by taha-yassine** [James-Yu/LaTeX-Workshop#4036]
## Pre-checks*
- [X] The feature request has not been suggested in this repository.

## The Missed*
- When ctrl+clicking on a target in the web browser, the cursor in the editor is moved to the corresponding item in the .tex, but the browser still holds focus.

## The Solution*
- It would be nice if there was an option to enable automatic focus switch to the editor. This works OOTB in the internal viewer. 

## Anything Else?
- N/A

**Comment by jlelong** [comment]
Switching focus between applications is handled by the OS. I am afraid that there is very little the extension can do.
