### ISSUE TITLE
Add a setting to open the compiler log on startup

### ISSUE THREAD

**Issue by Vasco-Da-Gama-png** [James-Yu/LaTeX-Workshop#4038]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When the LaTeX Project folder is opened, it might be useful that the LaTeX compiler is automatically opened.
- So that users are able to see the output.

## The Solution*
> _Please provide a solution you would like to have._
- I didn't find a very easy solution for myself, but I think implementing this in the extension would be quite easy with another bool variable and the command
`
"activationEvents": [ "onStartupFinished" ]
`
For my project I personally realised it with the great extension [Auto Run Command](https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command) and the following code in my settings.json:
```
    "auto-run-command.rules": [
        {
          "condition": "isRunningInContainer",
          "command": "latex-workshop.compilerlog",
          "message": "Open LaTeX Compiler Log"
        }
      ],
```
I thought this might be a useful feature for other users as well and should be quite easy to implement. And if LaTeX-Workshop would have this oppertunity I need one extension less.

**Comment by Vasco-Da-Gama-png** [comment]
Because it is useful to get compiling errors to see.
And specifically because I have a template used by many people and for many of them the compiler output is too hidden.
Like this everyone is confronted with it when the project folder is opened.
So this would be a feature located in the project locales setting.json, because for other projects you do not want this to happen.

**Comment by James-Yu** [comment]
If this got implemented, the default will absolutely be `false`. If a user knows how to change this config to `true`, they will already know how to open the compiler log.
