### ISSUE TITLE
Zoom misbehaving when trimming is enabled

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#4040]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Windows 11
- Visual Studio Code Version: 1.83.1
- LaTeX Workshop Version: 9.14.1
- TeX Distribution Version: MiKTeX 23.10

## The Issue*
If trim is enabled in PDF tab view, zooming will first only affect one axis, until it updates a few moments later. This is obviously not a breaking issue, but it can be quite distracting.

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/2191754/f1cff193-f0ad-4cfc-a7dc-48000d8dec1f)

### Reproduction Steps
See above

### Expected Behavior
Zoom should affect both axes equally, even before the update

**Comment by Enivex** [comment]
I only now realized that the zoom dropdown menu also stops working when trimming is enabled. I've been using my scroll wheel and/or touchpad.

Is it intentional that zooming should be disabled? In that case it's a bug that the scroll wheel still works.

**Comment by James-Yu** [comment]
It is intentional. You cannot zoom with trim on.

**Comment by Enivex** [comment]
> It is intentional. You cannot zoom with trim on.

I'm not sure most people realize this when ctrl + scroll wheel or touch gestures still work. Shouldn't the user be prevented from zooming in the first place?
