### ISSUE TITLE
Enabling trim should disable zoom also through other means (like ctrl + scroll wheel and touch gestures)

### ISSUE THREAD

**Issue by Enivex** [James-Yu/LaTeX-Workshop#4041]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

See https://github.com/James-Yu/LaTeX-Workshop/issues/4040 for more information

**Comment by James-Yu** [comment]
Unfortunately, this level of control seems not possible if we go on using pdf.js viewer.
