### ISSUE TITLE
Allow snippet view to work in other files, such as Markdown

### ISSUE THREAD

**Issue by Saltsmart** [James-Yu/LaTeX-Workshop#4044]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The snippet view panel is only working in tex files, but it would be a great enhancement to allow inserting the symbols in other files, like markdown or ipython notebook (if latex-workshop extension is enabled).

## The Solution*
> _Please provide a solution you would like to have._
- Allow inserting the symbols in this panel at the station of cursor, whatever the current file is.

## Anything Else?
> _Add any other context about the feature request below._
- Nothing else. The above feature is enough to make the extension more all-purpose ❤️!

**Comment by James-Yu** [comment]
Thanks for the suggestion. Unfortunately, this extension may be too heavy for these other languages if activated. I would suggest seeking for implementation on other Markdown extensions.
