### ISSUE TITLE
Switching back to regex breaks `findNewCommand` for math preview, sometimes

### ISSUE THREAD

**Issue by TamotsuTokazu** [James-Yu/LaTeX-Workshop#4045]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10
- Visual Studio Code Version: 1.83.1
- LaTeX Workshop Version: 9.14.1
- TeX Distribution Version: TeX Live 2022/dev/Debian

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using WSL2.

## The Issue*
> _Please briefly describe the issue you come across._
- When there's a `\newcommand` across multiple lines, the regex in [`findNewCommand`](https://github.com/James-Yu/LaTeX-Workshop/blob/dac0ee527ce0241f295ae74ebf38b89c7d1b5a41/src/providers/preview/mathpreviewlib/newcommandfinder.ts#L71) only matches the first line. Then an open brace will be sent to MathJax, causing an error, thus breaking the math preview.
- I investigated a little bit for this. In 2019, `latex-utensils` was used in this project so that we don't rely on regex to find the `\newcommand`s. However, in version 9.12.0, `latex-utensils` is removed from the dependencies, and we are using regex again.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._

The following two LaTeX document is a simple example to show the unwanted behaviors in two different ways.
- In the first example, only `\newcommand{\exampleA}{a` is matched, which contains an open brace.

  ```latex
  \documentclass[preview]{standalone}
  
  \newcommand{\exampleA}{a
  }
  
  \begin{document}
  $\exampleA$
  \end{document}
  ```
- In the second example, `\newcommand{\exampleB}{b}\begin{document}` is matched. MathJax doesn't know what `\begin{document}` is, causing an error.
    ```latex
    \documentclass[preview]{standalone}

    \newcommand{\exampleB}{b}\begin{document}
    $\exampleB$
    \end{document}
    ```

    Personally, I don't know any reason to write something like this, so maybe this case is much less pressing.
### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Both files are valid tex source files, so I'm expecting the math preview to show up.

## Logs
I believe things are clear enough here, so I won't bother.

## Anything Else?
> _Add any other context about the problem below._
- Indeed, most user-defined math commands are simple and usually can fit into one single line. But in some cases, including the preamble I've been using, there are some other commands (for titles, blocks, etc.) that use multiple lines. So maybe a promising way to handle this is to just filter out the (incomplete) commands that will cause errors in MathJax.
- Or, I can just stick with 9.11.5, which is what I'm currently doing. However, nobody wants to miss the new features in the future, so I would really appreciate it if someone could handle this issue. Thanks!

**Comment by jlelong** [comment]
@James-Yu I am wondering why we cannot rely on the same approach as [parseAst](https://github.com/James-Yu/LaTeX-Workshop/blob/63aeacb5afe5da3e24b42bd857347c35f07a56ce/src/providers/completer/command.ts#L202) for passing newcommands to Mathjax. There must be a way to factorise the code between the two components. I think it would make maintenance easier.

**Comment by James-Yu** [comment]
This is because I didn't dare to touch the remains by tamu, really a mess to me. I need to find some time to revisit the hover previews, MathJax preview and snippet panel. Understanding the functions is painful.
