### ISSUE TITLE
brace matching is not working in equation environment

### ISSUE THREAD

**Issue by starship863** [James-Yu/LaTeX-Workshop#405]
### Description
The brace matching is working for the braces "{" and "}" in text, but it is not working for braces "{" and "}" in equation environment.

### How to reproduce

1. put cursor at a right brace "}" in the equation environment
2. the corresponding left brace "{" is not highlighted

### Expected behavior
Brace matching should also work in the equation environment.

### Additional Information

Vscode - Insiders V. 1.20.0-insider

**Comment by James-Yu** [comment]
Duplicate of #292
