### ISSUE TITLE
tikz pattern lines show as dashed lines

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#4051]
![Screenshot_20231101_100745](https://github.com/James-Yu/LaTeX-Workshop/assets/65082432/309955a2-f797-42b0-bcd2-6fbb072cd138)

This is what it is like on vscode

![Screenshot_20231101_144030](https://github.com/James-Yu/LaTeX-Workshop/assets/65082432/331eb882-6040-43d5-a0e4-6cf2e50ab02b)

This is what it is like on okular

```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{patterns.meta}
\begin{document}
\begin{tikzpicture}
    \draw [pattern={Lines[angle=45,distance=4pt]},pattern color=red]
    (0,0) rectangle (1,1);
\end{tikzpicture}


\begin{tikzpicture}
    \draw [pattern={Lines[angle=0,distance=4pt]},pattern color=red]
    (0,0) rectangle (1,1);
\end{tikzpicture}
\end{document}
```

Maybe it is a tikz issue?

**Comment by James-Yu** [comment]
This is a PDF.js issue. Please report the bug to their repository.

**Comment by Firestar-Reimu** [comment]
Thanks! What is the pdfjs version?

**Comment by James-Yu** [comment]
Latest is on `3.11.174`.
