### ISSUE TITLE
pdfLateX+makeindex+bibtex

### ISSUE THREAD

**Issue by lbold27** [James-Yu/LaTeX-Workshop#4056]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The issue has not been reported in this repository.
- [ x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11
- Visual Studio Code Version: 
- LaTeX Workshop Version: 1.84.0 
- TeX Distribution Version: 2.9.6600

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- NA

## The Issue*
> _Please briefly describe the issue you come across._
- I am trying to compile a main.tex document with pdflatex+makeindex+bibtex and I get the error "input file .../main.nlo not found. Usage: makeindex...". A pdf document still appears but with no "Table of Contents". With TeXmaker I can compile the document with the combination pdflatex+makeindex+bibtex and it produces the pdf with table of content. I tried a solution discussed in a similar issue by replacing %DOCFILE% with %DOC% but it did not work. Your help would be greatly appreciated!

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
my settings.json file is the following:
{
    "latex-workshop.latex.recipes": [
        {
            "name": "latex_ultimate",
            "tools": [
                "pdflatex",
                "makeindex",
                "bibtex"
            ]
        }
    ],

    "latex-workshop.latex.tools": [
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
              "-synctex=1",
              "-interaction=nonstopmode",
              "-file-line-error",
              "%DOCFILE%"
            ],
            "env": {}
          },
        { 
            "name": "makeindex",
            "command": "makeindex",
            "args": [
                "%DOCFILE%.nlo",
                "-s",
                "nomencl.ist",
                "-o",
                "%DOC.nls%" 
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
              "%DOC%"
            ],
            "env": {}
          }
    ]
}

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
I was expecting to see the table of contents in the document, in the same way as when I compile using TeXmaker

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
I cannot paste the log.

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
- I followed a similar post and changed %DOCFILE% with %DOC% in the latex-workshop.latex.tools where I define the "makeindex" tool but it did not work.

**Comment by James-Yu** [comment]
Please paste your full log. Also, %DOC.nls% won’t work, %DOC%.nls maybe.

**Comment by lbold27** [comment]
do you mean main.log?
