### ISSUE TITLE
Math preview panel overlaps with other components.

### ISSUE THREAD

**Issue by black-pwq** [James-Yu/LaTeX-Workshop#4057]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Windows 10]
- Visual Studio Code Version: [1.83.0]
- LaTeX Workshop Version: [9.14.1]
- TeX Distribution Version: [TeX Live 2021]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._

I'm not sure whether it is caused by this extension (since I rarely use splitting preview in other situations). The problem is that the math preview panel overlaps other components like Mini Map or the Sliding Bar in the editor if I split this way:
<img width="826" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/105478488/0d0c7f8a-2112-44b5-a39f-170cf6fc1ceb">

It becomes even stranger once I open the pdf
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/105478488/faa5b1a1-8245-4cbe-84b6-8c707f7515b2)
 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1.  Write some math equations
2.  Open math preview panel

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._

It should look like this:
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/105478488/874a7ca4-1e24-4a4b-ab15-2d2ef86923b7)

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
This is not controlled by the extension. It should be a vscode appearance glitch.
