### ISSUE TITLE
Formatting failed with exit code 3, nothing written inside "stderr"

### ISSUE THREAD

**Issue by jacopoaltieri** [James-Yu/LaTeX-Workshop#4058]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not beenreported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11 Home 22H2
- Visual Studio Code Version: 1.84.2
- LaTeX Workshop Version: 9.14.1
- TeX Distribution Version: MiKTeX-pdfTeX 4.16 (MiKTeX 23.10.12)

## The Issue*
> I have a multi-file LaTeX project. I can compile it just fine, but the code formatting itself returns an error.
By default, I have code formatting on save (Ctrl+s), but i get the following error:
"formatting failed. please refer to latex workshop output for details"

Differently from other posts, I get no stderr inside the terminal output, as I will point out in the next fields

### Reproduction Steps
> Save a .tex file

### Expected Behavior
> Correctly formatted .tex code

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[17:07:22.994][Event] STRUCTURE_UPDATED
[17:07:23.956][Format][TeX] Start formatting with latexindent.
[17:07:23.993][Format][TeX] Formatting LaTeX. The command is latexindent:["-c","h:/Il mio Drive/Magistrale/Master_Thesis/Tesi/","h:/Il mio Drive/Magistrale/Master_Thesis/Tesi/Chapters/__latexindent_temp_chapter_1","-y=defaultIndent: '    '"].
[17:07:24.597][Format][TeX] Formatting failed with exit code 3
[17:07:24.597][Format][TeX] stderr: 
[17:07:24.628][Extension] onDidSaveTextDocument triggered: file:///h:/Il mio Drive/Magistrale/Master_Thesis/Tesi/Chapters/chapter_1

```

**Comment by James-Yu** [comment]
The extension calls latexindent for formatting. Apparently, it does not tell us anything except for an error code 3. You may need to look in to latexindent for reason.
