### ISSUE TITLE
Synctex between two Vscode instancies on different screens

### ISSUE THREAD

**Issue by tapyu** [James-Yu/LaTeX-Workshop#4059]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
I have a two-screens setup to work with LaTeX on VScode.

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/22801918/3271e331-1acb-435d-b4af-b7d93be98b6a)

On the main screen, I have a `.tex` file opened. On the second screen, I have the PDF LaTeX file. **The problem is: they aren't synchronized**. I tried to config but it seems there isn't a straightforward manner to sync them. When I `cntrl+click` on the `.pdf` file, it opens a new `.tex` file in a new group instead of going to the already-opened `.tex` file on the other screen.

## The Solution*
> _Please provide a solution you would like to have._

Being able to easily to `synctex` a latex `.pdf` file with its source `.tex` file (regardless it is opened in a different process or on a different screen) would be a nice feature.

## Anything Else?
> _Add any other context about the feature request below._

System configuration:
```
OS: Ubuntu 22.04.3 LTS x86_64 
Host: Inspiron 5570 
Kernel: 6.2.0-36-generic 
Uptime: 42 mins 
Packages: 2776 (dpkg), 6 (flatpak), 14 (snap) 
Shell: zsh 5.8.1 
Resolution: 1920x1080 
DE: GNOME 42.9 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: kitty 
CPU: Intel i5-8250U (8) @ 3.400GHz 
GPU: Intel UHD Graphics 620 
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 530/535 / 620/6 
Memory: 1580MiB / 2272MiB
```

**Comment by James-Yu** [comment]
It's not possible to sync between two vscode instances. This is a limit by vscode and won't implement from the extension side.
