### ISSUE TITLE
need help - win10 vscode - large file - 'extension host' throws error in vscode dev tools console "FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory"

### ISSUE THREAD

**Issue by ahkscriptlerim** [James-Yu/LaTeX-Workshop#4064]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: `Microsoft Windows [Version 10.0.19045.3693]`
- Visual Studio Code Version: `1.84.2`
- LaTeX Workshop Version: `v9.15.0`
- TeX Distribution Version: `One MiKTeX Utility 1.8 (MiKTeX 23.10.12)`

## The Issue*
- i have a long latex file with ~`765,000` lines of content. does not compile. thats all.
- when it was shorter it was compiling
- now it does not compile, no standard console output, extension just closes
- vscode popup in the corner: 'notification Extension host terminated unexpectedly 3 times within last 5 minutes' (basically vscode tried over and over again)
- vscode dev tools console throws error `FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory` under `<--- JS stacktrace --->` title
- i cannot make it extend memory, problem persists, extension is not usable

### Reproduction Steps
0. whatever I do (with or without these steps) error persists so most likely `99%` of the time you will encounter
here lists what i've tried:
1. vscode ide focused environment on clean windows 10 (less conflict intended, new versions installed from zero - no upgrade)
2. .tex has 765,000 lines (with `\verbatim{}` max `50` character lines, `empty` line after every line)
3. `extension bisect` makes it sure that no conflict occurs, only `LaTeX-Workshop` extension
4. after this i've tried installing clean nodejs (stable [20.9.0 LTS] version) but i dont know of node.js servers
5. i added system environment variables `NODE_OPTIONS` `--max_old_space_size=8192 --max_semi_space_size=64` manually
6. in cmd `node --help --v8-options | find "--max-old-space"` and `node --help --v8-options | find "--max-semi-space"` commands verify that environment vars have overwritten the `default:0` values
7. also listening to internet suggestion user environment variable `path` changed to `C:\Program Files\nodejs` (from some `%appdata%`) at least i can verify currently `npm` command directly works in cmd
8. vscode preferences about node are `TypeScript` so preferences are chaged `npm` `"C:\Program Files\nodejs\npm"` `Max TS Server Memory` `8192` and the third one `node path` `"C:\Program Files\nodejs\node.exe"`
9. also `Bibtex: Max File Size` changed as `64`
10. `JavaScript: Default Runtime Executable` edited in json as `"debug.javascript.defaultRuntimeExecutable": { "pwa-node": "\"C:\\Program Files\\nodejs\\node.exe\"" }`

### Expected Behavior
- `pdflatex` command on cmd works fine (on this file) 
- vscode works fine
- extension host (node.js server(?)) is the problem
- this gave me the courage to post here (hopefully i didnt overlook something)

### LaTeX Workshop Output*
```
```

### Developer Tools Console
```
INFO [perf] Render performance baseline is 37ms
latexworkshop.js:420 Closed: WebScocket to LaTeX Workshop.
abstractExtensionService.ts:784 Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: unknown
yb @ abstractExtensionService.ts:784
log.ts:441   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
vscode-file://vscode-app/c:/Users/ahk/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=7be3f3b0-8884-434a-b346-2a38f0fac9d6:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
localProcessExtensionHost.ts:281 Extension Host
localProcessExtensionHost.ts:282 <--- Last few GCs --->[14864:000043F400628000]     8210 ms: Scavenge 1061.3 (1092.2) -> 1057.2 (1088.7) MB, 1.22 / 0.00 ms  (average mu = 0.984, current mu = 0.982) allocation failure; [14864:000043F400628000]     8383 ms: Scavenge 1079.0 (1110.2) -> 1073.8 (1105.6) MB, 1.00 / 0.00 ms  (average mu = 0.984, current mu = 0.982) allocation failure; [14864:000043F400628000]     8427 ms: Scavenge 1082.5 (1114.0) -> 1079.9 (1112.0) MB, 1.34 / 0.00 ms  (average mu = 0.984, current mu = 0.982) allocation failure; <--- JS stacktrace --->FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory 1: 00007FF7256217B6 node::SetTracingController+80086 2: 00007FF725621A43 node::OnFatalError+595 3: 00007FF728310683 v8::Function::NewInstance+835 4: 00007FF728310613 v8::Function::NewInstance+723 5: 00007FF7283D9037 v8::CppHeap::CollectGarbageInYoungGenerationForTesting+74791 6: 00007FF727044329 v8::MicrotasksScope::PerformCheckpoint+1744009 7: 00007FF726FFB91B v8::MicrotasksScope::PerformCheckpoint+1446523 8: 00007FF72701D4A5 v8::MicrotasksScope::PerformCheckpoint+1584645 9: 00007FF72704BE16 v8::MicrotasksScope::PerformCheckpoint+177547810: 00007FF72711BAEB v8::MicrotasksScope::PerformCheckpoint+262663511: 00007FF7274331BA v8_inspector::String16::String16+253500212: 00007FF787767CC6 
console.ts:137 [Extension Host] Git installation not found.
w @ console.ts:137
latexworkshop.js:443 Try to reconnect to LaTeX Workshop: (1/10).
connection.js:12 WebSocket connection to 'ws://127.0.0.1:3466/' failed: 
(anonymous) @ connection.js:12
connection.js:16 Uncaught (in promise) Error: Failed to connect to ws://127.0.0.1:3466/
    at WebSocket.<anonymous> (connection.js:16:57)
abstractExtensionService.ts:784 Extension host (LocalProcess) terminated unexpectedly. Code: 0, Signal: unknown
yb @ abstractExtensionService.ts:784
log.ts:441   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
vscode-file://vscode-app/c:/Users/ahk/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/services/extensions/worker/webWorkerExtensionHostIframe.html?&vscodeWebWorkerExtHostId=682c2b9e-cf3a-424e-86e5-2cb05d2bf0d7:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
```

## Anything Else?
- internet suggested me to divide into smaller files
- or work on popular tex editors supporting big files
- in this particular project i cannot divide content into perfect pdf pages (with `\include`) so no performance will be gained. also dividing will have no meaning other than clutter. its like an oldscool win10-notepad-like one-page solid file. (latex didnt let me do it in cashier paper roll like one page that's how geek it is)
- i wanted you to hear me out since internet suggested me to change my ide for this

**Comment by James-Yu** [comment]
Neither do I think the underlying parser `unified-latex` will handle this file. My only suggestion is to look for advice from https://github.com/siefkenj/unified-latex on such extremely large file parsing. However, I am afraid that the guys there won't have a good solution either.
