### ISSUE TITLE
[Question] Double Cursor to Single Cursor

### ISSUE THREAD

**Issue by AllanWang** [James-Yu/LaTeX-Workshop#407]
When writing `\begin{...}`, two cursors will be opened so that the command can be written simultaneously for begin and end. However, it remains like that until I click.

Is there a keyboard shortcut that exists or can be configured to allow for single selection without using a mouse, or is there an option to go from double to single after say pressing the down arrow? The latter will only apply when the cursor is spilt for writing an environment

**Comment by James-Yu** [comment]
Yes, that is `ESC`.
