### ISSUE TITLE
Support env variable resolution in `latex-workshop.latex.tools` `env`.

### ISSUE THREAD

**Issue by skwde** [James-Yu/LaTeX-Workshop#4071]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Allow environment path resolution in `latex-workshop.latex.tools`  `env`.

## The Solution*
> _Please provide a solution you would like to have._
- Support something like

```jsonc
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-shell-escape",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-outdir=%OUTDIR%",
                "%DOC%"
            ],
            "env": {
                "PATH": "/usr/local/bin:${env:PATH}"
            }
        },
    ]
```

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
There's no obvious evidence supporting this. Also, the `${}` macro can't be expanded in `spawn` iirc.
