### ISSUE TITLE
PDF preview jumps to the beginning of the document after building

### ISSUE THREAD

**Issue by janwil123** [James-Yu/LaTeX-Workshop#4073]
The PDF preview used to remember the place where the editing activity is going on, so after ctrl-s and rebuilding the preview was refreshed into the same place. Now the PDF preview is often reloaded into the beginning of the document, and it is very annoying to have to scroll back to the place of editing, especially for larger documents. It does not happen every single time, but once it starts happening, it keeps happening consistently. Has anything changed recently in regards to the PDF preview handling?

I am experiencing this issue on the Linux version of VSCode and consistently across several machines, so I don't think it is a problem of one corrupt configuration. My VSCode version is currently 1.84.2 and LaTeX-Workshop version is 9.15.0.

_Originally posted by @janwil123 in https://github.com/James-Yu/LaTeX-Workshop/discussions/4066_

**Comment by James-Yu** [comment]
Please fill the issue template, especially the console logs. Also, please provide a minimal working example.
