### ISSUE TITLE
Disable autoBuild in individual files using !TEX magic

### ISSUE THREAD

**Issue by lzkelley** [James-Yu/LaTeX-Workshop#4074]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.  (Not that I can find at least)

## The Missed*
- I have a latex file that is used as input/preamble for many separate documents (built separately) in my current project.  When I save the preamble file, it tries to automatically build it, which fails.  There also isn't a single "root" file that I can point to (although picking one is certainly a workaround).

## The Solution*
- It would be helpful to be able to add a magic command at the top of the file to say, "don't autobuild this one", like `% !TEX autoBuild = False`

**Comment by James-Yu** [comment]
We tend to not introduce custom magic comments to `.tex`. You can use workspace configs to disable the auto-build.
