### ISSUE TITLE
Improving error messages

### ISSUE THREAD

**Issue by yordiak** [James-Yu/LaTeX-Workshop#4075]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
Could you improve error messages handling? There are multiple cases where the information provided does not easily indicate the error. Thus, I have to use other software, e.g. TexShop.

**Comment by James-Yu** [comment]
Please provide details.
