### ISSUE TITLE
Treat highlighting for terminal and minted equally

### ISSUE THREAD

**Issue by VanNostrand** [James-Yu/LaTeX-Workshop#4077]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Linux
- Visual Studio Code Version: 1.84.2
- LaTeX Workshop Version: 9.15.0
- TeX Distribution Version:  texlive 2023

## The Issue*
> _Please briefly describe the issue you come across._
- I had some minted environments in my document that I am now replacing with terminal environments from the CTAN termsim package, which uses minted environments internally.
- If the code within the environment contains an uneven amount of $ characters, the rest of the document is green, like math formulas between two dollars.

This minimal example with minted works as expected:

````
I am normal

\begin{minted}{text}
~> FP=4711
~> gpg --expert --edit-key $FP
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
blah
\end{minted}

I am normal too
````

This minimal with terminal example doesn't:

````
I am normal

\begin{terminal}{shelltitle}
~> FP=4711
~> gpg --expert --edit-key $FP
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
blah
\end{terminal}

I should be normal but I am green

\begin{itemize}
\item I am still screwed up
\end{itemize}

and I am no better

\begin{terminal}{shelltitle}
~> FP=4711
~> gpg --expert --edit-key $FP
gpg (GnuPG) 2.2.27; Copyright (C) 2021 Free Software Foundation, Inc.
blah
\end{terminal}

and I am broken too
````

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- I was expecting that the code parsing within the terminal environment gets treated like in minted environments

**Comment by James-Yu** [comment]
Thank you for filing this issue! We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), could you please post your issue there and clarify what behaviour you expect?
