### ISSUE TITLE
Add a way to switch between inline equation and environment

### ISSUE THREAD

**Issue by kaba2** [James-Yu/LaTeX-Workshop#4078]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*

I find myself doing a lot of conversions from inline equations of the form `$x^2 + 4x + 1$` to environment-form of the form 

```
\begin{eqs}
x^2 + 4x + 1
\end{eqs}
```

Here `eqs` is my own environment which expands to 

```
\begin{equation}
\begin{aligned}
...
\end{aligned}
\end{equation}
```

This occurs all the time when writing mathematical papers. A proof of a theorem may start with inline equations, but later I tend to change them to the environment-form so that the proof becomes easier to read. Having its own line for the equation provides the proof some air, and also highlights the important parts. 

## The Solution*

I wish there was a shortcut to convert an inline equation to the environment form, where I could maybe also specify the environment to use (here `eqs`). Optionally, there could also be a way to do the reverse: to convert an `eqs` environment to an inline equation.

**Comment by James-Yu** [comment]
`latex-workshop.toggle-equation-envname`

Custom env won't be supported.

**Comment by kaba2** [comment]
I don't know what `latex-workshop.toggle-equation-envname` means. I searched for settings in 9.15.0, and could not find it. I found a way to toggle between `\[x^2\]` and `\begin{equation*}x^2\end{equation*}`, but not one for `$x^2$`.

**Comment by James-Yu** [comment]
That is a command instead of a config, just did what you say on `\[\]`. The extension does not support the conversion of $...$ as it is generally recommended against. Also parsing $...$ can be far more difficult.

**Comment by kaba2** [comment]
I'm not sure who is recommending against and what. The meaning of `$x^2$` is an inline equation (i.e. sprinkled between text), which is distinct from a block-equation `\[ x^2\]` which has its own line. A typical proof for us mathematicians looks like this:

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/2399754/9d690ef0-e13e-4856-887c-bd5da7a083a2)

It's rendering looks like this:

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/2399754/bc3201aa-2dd3-412b-8626-55d12dfc5a52)

Sometimes though, you want to make some of the equations stand out, like this:

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/2399754/54111b5c-47c3-457c-89c0-bdffaaed41a8)

It's rendering looks like this:

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/2399754/47daddba-caf2-41e5-8767-f8def6037720)

Which ones to display inline and which as blocks is a matter of taste, and you may end up switching back and forth. This is the process I'd like to automate. I currently have 1241 proofs like shown above. A fast way to convert between inline and block equations would significantly accelerate my work.

**Comment by jlelong** [comment]
I will try to clarify what James said. The recommended construction for inline maths is `\(...\)` instead of `$...$`. See https://tex.stackexchange.com/a/513 for instance.

Parsing `$...$` constructions can only be done by starting from the beginning of the file. It is far too costly to be integrated into the extension.

**Comment by kaba2** [comment]
Parsing `$...$` is trivial when you restrict to the most common use-case. Starting from the cursor, find the first $ on the left, and the first $ on the right; done. The key-point is that the extension does not need to handle _all_ cases if that cannot be done efficiently because of ambiguities; just state the restriction in the documentation.

I cannot use `\(...\)` because typing `\(...\)` is too difficult/time-consuming. On my Finnish keyboard typing `\(` (or `\[`) means `Alt+Key` + `Shift+Key`, followed by the equation, and then `Alt+Key` + `Shift+Key` again for `\)`, which is very clumsy.

I count 20588 uses of $ symbol in my paper, which translates to roughly 10000 equations. As you can see from the proofs above, I type a math delimiter roughly every 10 characters. Hence whether typing the math-delimiters takes `x` time or `2x` time is important.
