### ISSUE TITLE
Build Latex-Workshop reports "Latex Toolchain Terminated With Error,"  <- Wrong.

### ISSUE THREAD

**Issue by 7Moses** [James-Yu/LaTeX-Workshop#408]
Thank You! For Latex Workshop, 

Upon Build Latex-Workshop reports "Latex Toolchain Terminated With Error,"  and there is no refresh in PDF Tab (Latex Workshop)  <- Wrong. There is a Build reported/viewable in Skim, looks good. Textmate and Command Line (pdflatex) build and report just fine.

Not a big issue in workflow, onwards, but any suggestions would be great, Thanks,

Configuration: High Sierra 10.13.2, VSCODE Version 1.19.3, Latex Workshop 3.13.0

**Comment by James-Yu** [comment]
You can refer to the log messages for what's going wrong. It can be accessed through command palette.
