### ISSUE TITLE
documentation: installation and MikTex

### ISSUE THREAD

**Issue by F-I-D-O** [James-Yu/LaTeX-Workshop#4082]
Hi,
First, thank you for this amazing tool that boosts my writing productivity!

Now to the request, it relates to the documentation. At first, I followed the advice to install TinyTex instead of Miktex. This resulted in a large amount of wasted time, as it is much harder to maintain compared to the MikTex. Later, I used Miktex on another computer together with Latex Workshop, and I realized that it works completely fine. The Perl installation is a five-minute job. So, my suggestion is to update the documentation accordingly to help future users of Latex Workshop not to repeat my mistake.

Is this possible? What can I do to help?

Cheers,
David

**Comment by James-Yu** [comment]
PR welcomed.
