### ISSUE TITLE
Add settings for ClearType level on Windows

### ISSUE THREAD

**Issue by vaisest** [James-Yu/LaTeX-Workshop#4084]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
Text displayed by the internal PDF viewer is ugly on an OLED screen which does not have a standard RGB subpixel layout.
Here is a screenshot comparing the internal PDF viewer (left) with  Firefox with `gfx.font_rendering.cleartype_params.cleartype_level = 0` (right).
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/4550061/26af6e6c-46ff-4c9b-94fd-72af34529343)
![SKY20231204_152213256](https://github.com/James-Yu/LaTeX-Workshop/assets/4550061/fb4a7d24-f651-46c4-ad48-99bbda31a21a)

The picture is clearly not the best example ever, but the left picture shows colour fringing due to the ClearType subpixel rendering. The resulting text is much more thick, but I believe this may be controllable with the other cleartype_params settings in Firefox. Chrome also has a relevant setting called `--disable-lcd-text` and so does VSCode as it uses Electron. The setting in VSCode however does not fix the internal PDF viewer.

## The Solution*
Firefox has a setting called `gfx.font_rendering.cleartype_params.cleartype_level` which desaturates the rendered text. This doesn't disable anti-aliasing, but allows for the browser to display PDFs with grayscale rendering. This looks much better on an LG OLED panel. 

## Anything Else?
Relevant issue highlighting why ClearType performs badly on OLED screens: https://github.com/microsoft/PowerToys/issues/25595

**Comment by mdrejhon** [comment]
There is an FreeType third party pull request modification that can add subpixel support:

https://github.com/rennr/freetype/pull/1

I'd like to see it upstream into the main FreeType repo, so it can go to all distributions.  So the word "cleartype" should be changed to something else generic (subpixel rendering) long term, especially as more open source projects gain support.  Custom subpixel geometry support is already in https://github.com/snowie2000/mactype and now that someone made a modification for FreeType, I'd like to see it become more widespread.

**Comment by James-Yu** [comment]
The extension cannot change electron settings. You may consider submitting an issue to vscode’s repo.
