### ISSUE TITLE
Error : Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by BertrandRdp** [James-Yu/LaTeX-Workshop#409]
### Description

Since last VSCode update, I get the error : Cannot read property 'path' of undefined when I open some of my tex files. Beside the error showing up, it seems like everything is still working fine.

### How to reproduce

I don't know and unfortunately I can't find a way to reproduce this out of my current working space. I also disabled all extensions and in this case no error message shows up, and it shows up again when I enable only Latex Workshop.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
Nothing displayed here
</details>

<details>
<summary>Developer Tools Console</summary>
In VSCode developer tool 
console.ts:123 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
messageService.ts:126 Cannot read property 'path' of undefined : TypeError: Cannot read property 'path' of undefined
	at t.createHandle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:822)
	at t.createTreeItem (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:351)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:458:259
	at Array.map (native)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:458:202
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
	at n.Class.derive._creator._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
	at n.Class.derive._creator._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
	at n.Class.derive._oncancel.then (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:75:398)
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ mainThreadTreeViews.ts:82
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ lazyPromise.ts:78
e._receiveReplyErr @ rpcProtocol.ts:154
e._receiveOneMessage @ rpcProtocol.ts:99
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
undefined:1 GET file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/electron-browser/bootstrap/undefined net::ERR_FILE_NOT_FOUND
console.ts:123 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
</details>

**Comment by zoehneto** [comment]
Seems to be fixed with the first patch release for 1.20:
https://github.com/Microsoft/vscode/milestone/63?closed=1
https://github.com/Microsoft/vscode/issues/43466

**Comment by BertrandRdp** [comment]
Fixed with last vscode patch indeed !
