### ISSUE TITLE
Trouble with automatic zoom of the PDF viewer

### ISSUE THREAD

**Issue by lijunkang12** [James-Yu/LaTeX-Workshop#4093]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: MacOS 14.2
- Visual Studio Code Version: 1.85.0
- LaTeX Workshop Version: 9.15.6
- TeX Distribution Version: MacTeX 2023

## The Issue*
> _Please briefly describe the issue you come across._

Hello, since the update yesterday or today, the automatic zoom of the PDF viewer no longer works as expected. For example, even if I manually select zooming to be "page width", it changes back to "automatic zoom" after each reload (which means after each compilation for me). Changing `latex-workshop.view.pdf.zoom` to `page-width` has no effect on this.

**Comment by Yassan0486** [comment]
# Enviroment
- Operating System: Windows 10
- Visual Studio Code Version: 1.85.0
- LaTeX Workshop Version: 9.15.6
- TeX Distribution Version: TexLive 2023

# The Issue*
The environment is different from the first poster, but the first time up to [20:48:13.892] it is displayed with "page-fit", but the second time it is compiled, it auto-zooms.
[log.txt](https://github.com/James-Yu/LaTeX-Workshop/files/13660361/log.txt)

**Comment by James-Yu** [comment]
Thanks for the log. Will push the fix soon.

**Comment by voruti** [comment]
Many thanks. This fixed it!

**Comment by lijunkang12** [comment]
Many thanks to @Yassan0486 for the log and to @James-Yu for the fix!
