### ISSUE TITLE
Disable smooth scrolling in integrated pdf viewer?

### ISSUE THREAD

**Issue by Cimiteriophiliac** [James-Yu/LaTeX-Workshop#4094]
Not 100% sure if this maybe can be changed with some vscode setting, but I couldn't find one.

**Comment by James-Yu** [comment]
No.

**Comment by Cimiteriophiliac** [comment]
I found a workaround at https://github.com/microsoft/vscode/issues/90750 , adding `--disable-smooth-scrolling` to the `target` field of the Windows shortcut I use to run vscode solves the issue. I'd assume this means it can't be solved from within LaTeX workshop.
