### ISSUE TITLE
LilyPond-Integration not working

### ISSUE THREAD

**Issue by andy-lilypond** [James-Yu/LaTeX-Workshop#410]
Hey

Thanks for your great work on this useful piece of software!

I use LaTeX in combination with LilyPond for typesetting of music scores and use Visual Studio Code and LaTeX-Workshop for editing the files.
But embedding LilyPond files in LaTeX throws errors in the editor, so I just wanted to ask if you could provide the possibility to use LilyPond-Embedding in LaTeX-Workshop?

Mainly there are just a few keywords which should be provided:

\lilypond{...}
\begin{lilypond}...\end{lilypond}
\lilypondfile{...}
\musicxmlfile{...}

The official documentation of the LilyPond project could be found here:

http://lilypond.org/doc/v2.18/Documentation/usage/latex

Thanks for your response.

Greetings,
Andy

**Comment by James-Yu** [comment]
Can you please provide the errors for debugging?
