### ISSUE TITLE
Unable to insert symbol, Error: TextEditor#insertSnippet not possible on closed editors

### ISSUE THREAD

**Issue by Hainuo-Wang** [James-Yu/LaTeX-Workshop#4102]
When I want to use snippet, it shows "Unable to insert symbol, Error: TextEditor#insertSnippet not possible on closed editors".

**Comment by deskpil0t** [comment]
## Troubleshooting Snippets - Managed to get snippet view working, even though i am not sure how, steps included

I was getting the same error message in the beginning.  after some setting research/troubleshooting i was getting a slightly different error.  **"unable to get document to insert symbol into"**


**System Info:**<br>
Version: 1.85.1<br>
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2<br>
Date: 2023-12-13T09:47:11.635Z<br>
Electron: 25.9.7<br>
ElectronBuildId: 25551756<br>
Chromium: 114.0.5735.289<br>
Node.js: 18.15.0<br>
V8: 11.4.183.29-electron.0<br>
OS: Linux x64 5.15.0-91-generic<br>
<br>
workshop version 9.16.1<br>

## Steps/Troubleshooting
- i have texlive installed<br>
   which tex:   /usr/bin/tex <br>
   This is TeX, Version 3.141592653 (TeX Live 2022/dev/Debian)<br>
- /usr/bin is in the path
- snippetsPreventQuickSuggestions is set to false
- latex-workshop.intellisense.atSuggestion.trigger.latex   set to the @ symbol
- deleted anything i had added/tried to enter into /home/username/.config/code/user/snippets/latex.json
- installed extension 'insert unicode'
- installed extension 'unicode latex'
**- restarted vscode snippet view now inserts into latex document**
- disabled 'insert unicode', reload vsc, still works
- disabled 'unicode latex', reload vsc, still works

I am not sure why it's working, but figured someone else might be able to stumble through it.  

## Other error message/symptom ##
At one point after cleaning up some settings i was getting a different error message for a while.  "unable to get document to insert symbol into"

**Comment by Hainuo-Wang** [comment]
Thank you for sharing your problems with me. When I reload vsc, it works! But I don't know how to solve your problems.

Share my settings bellow:
  "latex-workshop.latex.autoBuild.run": "never",
  "latex-workshop.showContextMenu": true,
  "latex-workshop.intellisense.package.enabled": true,
  "latex-workshop.message.error.show": false,
  "latex-workshop.message.warning.show": false,
  "latex-workshop.latex.tools": [
    {
      "name": "xelatex",
      "command": "xelatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOCFILE%"
      ]
    },
    {
      "name": "pdflatex",
      "command": "pdflatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOCFILE%"
      ]
    },
    {
      "name": "latexmk",
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "-outdir=%OUTDIR%",
        "%DOCFILE%"
      ]
    },
    {
      "name": "bibtex",
      "command": "bibtex",
      "args": ["%DOCFILE%"]
    }
  ],
  "latex-workshop.latex.recipes": [
    {
      "name": "XeLaTeX",
      "tools": ["xelatex"]
    },
    {
      "name": "PDFLaTeX",
      "tools": ["pdflatex"]
    },
    {
      "name": "BibTeX",
      "tools": ["bibtex"]
    },
    {
      "name": "LaTeXmk",
      "tools": ["latexmk"]
    },
    {
      "name": "xelatex -> bibtex -> xelatex*2",
      "tools": ["xelatex", "bibtex", "xelatex", "xelatex"]
    },
    {
      "name": "pdflatex -> bibtex -> pdflatex*2",
      "tools": ["pdflatex", "bibtex", "pdflatex", "pdflatex"]
    }
  ],
  "latex-workshop.latex.clean.fileTypes": [
    "*.aux",
    "*.bbl",
    "*.blg",
    "*.idx",
    "*.ind",
    "*.lof",
    "*.lot",
    "*.out",
    "*.toc",
    "*.acn",
    "*.acr",
    "*.alg",
    "*.glg",
    "*.glo",
    "*.gls",
    "*.ist",
    "*.fls",
    "*.log",
    "*.fdb_latexmk"
  ],
  "latex-workshop.latex.autoClean.run": "onFailed",
  "latex-workshop.latex.recipe.default": "lastUsed",
  "latex-workshop.view.pdf.internal.synctex.keybinding": "double-click",
