### ISSUE TITLE
Keep auto-defined available during each update

### ISSUE THREAD

**Issue by lcs27** [James-Yu/LaTeX-Workshop#4109]
## Pre-checks
- [x] The feature request has not been suggested in this repository.

## The Missed
- In my personal $\LaTeX$ writings, I usually use a home-made package where many commands are defined. And I want to add auto-completion for my own package so I wrote the json file of my own package and copy it to the ``data/commands.json`` file of the LaTeX Workshop package. The issue is that each time our extension is updated (thanks a lot for continous improvement), the ``data/commands.json`` would be replaced by a new file and I have to recopy again my commands to the ``data/commands.json``.  It's not so difficult but it would be better if I don't need this action for each update.

## The Solution
In fact I don't know if you have already left this interface, sorry for my unknown if you have already done. As I don't know how the extension is written, here I just propose two solutions that may be useful. 
- A (maybe) simpler one:  Add a setting in the extension for user to decide whether the ``commands.json``, ``environments.json`` and other files would be replaced during each update. However, once we decide not to replace them, this may be a pity if you add some new features in these files as we as users won't be able to keep up with it.
- A (maybe) difficult one: Leave an item in settings to allow us add the location of our own ``autodefined-package-commands.json`` files, which can be stored in another place. And this item won't be changed during each update. 

Thanks a lot!

**Comment by James-Yu** [comment]
Thanks for the suggestion. Before proceeding to implementation, may I ask for your example on your use case, where the auto `\newcommand` finder won't work for your project?

**Comment by lcs27** [comment]
Hello, sorry for this late reponse. I would  better describe the situation with an example. In fact I have a set of autodefined symbols  for which I would want to add auto-completion. Thus I added in ``data/commands.json`` the codes like in the following: 

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/73965032/8ba87d2f-4f1b-4633-9636-151f093e791c)

This works well! But the problem is that once LaTeX Workshop extension is updated (like the last update in 2023-12-22), this file will be replaced by your original one during the update and I will lose my self-defined command like in the picture. As a result I will have to reput my commands in ``data/commands.json``. (This is not difficult but I would be better if I need to do nothing for each update)

I don't now if I've described it clearly. Thanks for your implementation  and glad for more question.

**Comment by James-Yu** [comment]
I mean, how are your “deri” macros defined in your latex project? Are the file included in your latex document?

**Comment by lcs27** [comment]
yeah exactly. At the beginning of my file, I've done ``\usepackage{pacakage_defined_by_me}``

**Comment by James-Yu** [comment]
You can add the definitions to `latex-workshop.intellisense.command.user`.

**Comment by lcs27** [comment]
OK thanks, I will try
