### ISSUE TITLE
Feature Request - Latex Diff

### ISSUE THREAD

**Issue by fps7806** [James-Yu/LaTeX-Workshop#411]
First of all, thank you so much for this awesome tool!

Since Visual Studio Code also supports git, would be very helpful if I could visualize the pending changes with latexdiff.
Would it be possible to integrate with the commit history to quickly create latexdiffs between different commits?

**Comment by zoehneto** [comment]
There are already vs code extensions for showing a diff to the latest state from git (I use gitlens exactly for this use case).

**Comment by fps7806** [comment]
I don't want to visualize the source code changes...vs does that natively without any extensions.
I want to visualize the differences on the output of the latex pipeline. Something like this: https://www.sharelatex.com/blog/2013/02/16/using-latexdiff-for-marking-changes-to-tex-documents.html

**Comment by James-Yu** [comment]
Unfortunately, many writers won't use SCM, and implementing git-related features is really out of my knowledge. I would like to promote this issue as a community-driven contribution.

**Comment by jlelong** [comment]
I am not convinced such a feature should be implemented as a built-in tool within the extension. Getting a diff pdf file can easily be obtained by

1. Checking out an older version, not necessarily the last one.
1. Running `latexdiff old.tex current.tex > diff.tex`
1. Compiling `diff.tex`

Note that it can happen that the `diff` file actually contains syntax errors, so compiling it is not always that straightforward.

You may also consider directly using [git-latexdiff](https://gitlab.com/git-latexdiff/git-latexdiff).

**Comment by carstenhag** [comment]
I'd like to see this on LaTeX-Workshop.

I am often getting errors compiling the diff, so then I have to open that folder in VS Code manually again, for example

**Comment by jlelong** [comment]
This cannot really be more automated than what [git-latexdiff](https://gitlab.com/git-latexdiff/git-latexdiff) offers as the `diff` file is often corrupted and needs hand fixing. I cannot see how to avoid opening the `diff` folder in vscode.

**Comment by carstenhag** [comment]
Sure, this is true (and I hate it, sadly).

The GUI part can be improved or enabled by this extension. I know, sorta out of scope.
