### ISSUE TITLE
When clicking on show latex pdf file icon, nothing happens.

### ISSUE THREAD

**Issue by weima** [James-Yu/LaTeX-Workshop#412]
- Extension Name: latex-workshop
- Extension Version: 3.13.0
- OS Version: Linux x64 4.13.0-32-generic
- VSCode version: 1.20.0

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 131,
		"activateCallTime": 10,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:latex"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "spawn EACCES"
		},
		{
			"name": "Error",
			"message": "ENOENT: no such file or directory, open 'Untitled-2'"
		}
	]
}
```

**Comment by James-Yu** [comment]
This is because there is no PDF generated. You need to first build the project.
