### ISSUE TITLE
How to assign a shortcut key that only work when the active editor is the PDF viewer to refresh all PDF files

### ISSUE THREAD

**Issue by taquangtrung** [James-Yu/LaTeX-Workshop#4120]
Hi,

I want to assign a shortcut key to the command `latex-workshop.refresh-viewer` such that this shortcut key can only work when the active editor/viewer is a PDF viewer.

Can you advise how to do so?

Currently, I can only assign a global shortcut key for that command. But I want to use the same shortcut key to refresh different types of editors/viewers, not only the PDF viewer.

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- No

## The Solution*
> _Please provide a solution you would like to have._
- How to assign a context key, such as `latex-workshop.pdf-viewer.enabled` so that I can detect when the active editor is the PDF Viewer?

## Anything Else?
> _Add any other context about the feature request below._
- No

**Comment by James-Yu** [comment]
I don't think so. It means that you want to bind a shortcut to multiple commands, under different conditions. You may approach vscode's API for help, which I am not familiar with.
