### ISSUE TITLE
Add ```$``` to autoClosingPairs

### ISSUE THREAD

**Issue by 500InternalError** [James-Yu/LaTeX-Workshop#4121]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- 

## The Solution*
> _Please provide a solution you would like to have._
- Add ```$``` to autoClosingPairs so it will be auto closed when editing formulas. I personally think it will be much more convenient when editing a bunch of formulas.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
#810
