### ISSUE TITLE
Add support for bbm package in hover preview.

### ISSUE THREAD

**Issue by gaoqiangks** [James-Yu/LaTeX-Workshop#4128]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
-  The package bbm provides blackboard bold type for lower case letters, which is very usefully for typing the imaginary unit  `i`.

![aaaaaaaaaaa](https://github.com/James-Yu/LaTeX-Workshop/assets/52161883/d3e0c75b-b4e7-4ba3-bd47-796bf340954b)

The following is what `\mathbbm{i}` looks like.
![bbbbbbbbbbb](https://github.com/James-Yu/LaTeX-Workshop/assets/52161883/16ffb4b2-9b5f-4561-925d-6ddb3ba2cce6)

## The Solution*
> _Please provide a solution you would like to have._
- Could you please add support for this package?

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
https://docs.mathjax.org/en/latest/input/tex/extensions/index.html

`mathbbm` is not supported.
