### ISSUE TITLE
Syntax highliting issue on mismatching quotation marks in multi-paragraph quotation

### ISSUE THREAD

**Issue by CyanoHao** [James-Yu/LaTeX-Workshop#413]
Multi-paragraph quotation, like this
```latex
``This is the first paragraph.

``This is the second paragraph.

``This is the last paragraph.''
```
makes following texts highlighted as if they were quoted, due to the mismatching quotation marks.

![image](https://user-images.githubusercontent.com/14287996/36085156-9276bae4-0ffe-11e8-8965-4e614c5e16e1.png)

Note: Mismatching quotation marks are recommended in Simplified Chinese, as is said in _GB/T 15834-2011:
标点符号用法_:

> 4.8.3.5 独立成段的引文如果只有一段，段首和段尾都用引号；不止一段时，每段开头仅
用前引号，只在最后一段末尾用后引号。

> 4.8.3.5 Add `“` `”` around the texts in single-paragraph quotation. Add `“`s before texts in each paragraph, and a `”` after the texts in last paragraph in multi-paragraph quotation.

**Comment by James-Yu** [comment]
This is a good catch, however a solution is not clearly available. Adding support to such matching will obviously break normal cases where quotes are paired. Can you please check the highlight plan in other editors, e.g., TeXStudio?

**Comment by wojciechbielecki** [comment]
Perhaps try using `\enquote{}` from `csquote` package. I think if you put several paragraphs in `\enquote{}` it should correctly apply mismatched quotation marks if that should be the case in your language of choosing.
