### ISSUE TITLE
Movement of other files rather than output to a separate .output_log file

### ISSUE THREAD

**Issue by skfrost19** [James-Yu/LaTeX-Workshop#4133]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The working directory becomes too cluttery after compilation.

## The Solution*
> _Please provide a solution you would like to have._
- Move all other files rather than output pdf to a separate hidden folder (.folder_name) 

## Anything Else?
> _Add any other context about the feature request below._
- That is all, thank you for the extension.

**Comment by James-Yu** [comment]
Please check the auxfile option of the compiling tool you use, or you can create an mv tool to be included in your recipe.
