### ISSUE TITLE
Enable Intellisense/autocomplete on Markdown

### ISSUE THREAD

**Issue by felipecrp** [James-Yu/LaTeX-Workshop#4139]
## Pre-checks*

- [x] The feature request has not been suggested in this repository.

## The Missed*

When using Latex Workshop with the latex markdown package, the IntelliSense/ autocomplete does not work with markdown syntax.

The following latex code generates a session, a reference to the session, and a citation. The IntelliSense works completing inside of the commands \ref, \citet, and \citep.

```latex
\section{Introduction}\label{sec:intro}

\ref{sec:intro}

\citet{Curty2018}

\citep{Curty2018}
```

The following markdown code generates the same output as the above. But the IntelliSense does not work when you type the <# and the @ commands to reference and cite.

```markdown
\begin{markdown}

# Introdution {#sec:intro}

<#sec:intro>

@Curty2018

[@Curty2018]

\end{markdown}
```

## The Solution*

The solution comprises including IntelliSense to the markdown syntax.

## Anything Else?

I used the markdown_latex_combined language.

**Comment by James-Yu** [comment]
Markdown intellisense is out of scope of this extension.
