### ISSUE TITLE
Suggestion: Clean auxillary files and retry on toolchain error

### ISSUE THREAD

**Issue by schrej** [James-Yu/LaTeX-Workshop#414]
When the toolchain fails this can be resolved by deleting the auxillary files pretty often. Currently this is a two step process (three steps if the build is triggered manually).

It would be very useful if the workshop automatically deletes the auxillary files and tries to build once again when there is an error within the toolchain.

It should only retry once. There should also be a config option to enable (or disable) the feature.
The feature should also automatically disable when the `latex.clean.enabled` is set to true as the errors can't be caused by the auxillary files then.

**Comment by James-Yu** [comment]
Great idea! Will implement soon after my vacation. PR always welcomed.
