### ISSUE TITLE
[Q]: Extending word count to include refs

### ISSUE THREAD

**Issue by yordiak** [James-Yu/LaTeX-Workshop#4149]
_Disclaimer: This is more like a question than an actual feautre request_

I am wondering if it possible to include references in the word counting. I searched on the wiki and I didnt find a way to do it, thus any guidance is appreciated

**Comment by James-Yu** [comment]
The extension does not count words. You may need other extensions/software to do so.

**Comment by jlelong** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#counting-words

Word count is entirely based on the `texcount` utility and we cannot go beyond what it offers. You can have a look at its document on https://ctan.org/pkg/texcount but I doubt it will solve your issue

**Comment by yordiak** [comment]
> https://github.com/James-Yu/LaTeX-Workshop/wiki/ExtraFeatures#counting-words
> 
> Word count is entirely based on the `texcount` utility and we cannot go beyond what it offers. You can have a look at its document on https://ctan.org/pkg/texcount but I doubt it will solve your issue

Overleaf provides such a feature (see [](https://www.overleaf.com/learn/how-to/Is_there_a_way_to_run_a_word_count_that_doesn%27t_include_LaTeX_commands%3F)

Since I dont like using online editors, I was wondering whether overleaf's approach can be used in vscode, as well
