### ISSUE TITLE
[DocTex] outline shows `[object Object]` for macro and enviroment

### ISSUE THREAD

**Issue by Cube707** [James-Yu/LaTeX-Workshop#4153]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System:Windows_NT x64 10.0.19045
- Visual Studio Code Version: 1.85.2 (system setup)
- LaTeX Workshop Version: v9.18.0

## The Issue
On `dtx` files (DocTex)  the outline failes to display the names of `macro` or `enviroment` enviroments.

### Reproduction Steps
for the following example file:

```latex
% \section{Implementation}
%
% \begin{macro}{\foo}
% this is an example macro.
%    \begin{macrocode}
\newcommand{\foo}{}
%    \end{macrocode}
% \end{macro}
%
% \begin{environment}{bar}
% this is an example enviroment.
%    \begin{macrocode}
\newenvironment{bar}{}{}
%    \end{macrocode}
% \end{environment}
```

the outlien shows only `[object Object]`

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/62838959/f32a35ea-2ab6-4ecb-8cc2-ddfb426c1eca)

### Expected Behavior
The outline should show the definined conents.

## Anything Else?
The issue seems to be this line where `caption` can not convert to a string properly.

https://github.com/James-Yu/LaTeX-Workshop/blob/285e887125769c15202be6c5e532fdf53589366c/src/outline/structure/latex.ts#L151

**Comment by Cube707** [comment]
It should be noted that `caption.content` holds the correct content (`foo` and `bar` for the example) and could be used here? I could submit a PR for that, but I am not sure if for macro-elements it should convert to a string with a leading `\` (so `\foo` in the example).

Should the output show: `Macro: \foo` or is `Macro: foo` good enough?

**Comment by jlelong** [comment]
For coherence with what we do for macros listed `latex-workshop.view.outline.commands`, I think we can show `Macro: foo`.
