### ISSUE TITLE
Weird order of intellisence suggestion for completion

### ISSUE THREAD

**Issue by maurerle** [James-Yu/LaTeX-Workshop#4157]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Debian
- Visual Studio Code Version: VSCodium 1.85.2
- LaTeX Workshop Version: v9.18.0
- TeX Distribution Version: Texlive 2022

## The Issue*
The order of suggestions is not intuitive in most cases

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/25026204/4400f706-232b-4b83-95ff-06058e342f29)

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/25026204/33182406-05fd-4045-87f8-e7c8add45b8f)

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. write \cite or \ref or anything
2. wonder about all the options and preference of the star and so on
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- shortest command should be preferred
- alternatively, the last used completion should be preferred

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
vscode controls the order. Unfortunately the extension cannot do anything from our side.
