### ISSUE TITLE
PDF Preview in Auxiliary Window 

### ISSUE THREAD

**Issue by derjasper** [James-Yu/LaTeX-Workshop#4164]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When moving the PDF preview into the recently introduced auxiliary window, it shows "This type of editor cannot be opened in other windows yet."

## The Solution*
> _Please provide a solution you would like to have._
- Add support for the PDF preview in the auxiliary window.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
This is a vscode limit.
