### ISSUE TITLE
List of TODOs in side panel

### ISSUE THREAD

**Issue by rahulshw** [James-Yu/LaTeX-Workshop#4165]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
- While writing a large document, we skip over some of the details and come back to them whenever possible or needed. It becomes very crucial to keep a list of TODOs. This request is show a list of TODOs on the side panel. 

## The Solution*
- A lot of IDEs(eg: PyCharm), give this feature of todo list somewhere in the panel, if you click on them, it would take you right where it is placed. How do you mark the TODOs? just put a comment starting with "TODO: bla bla bla". A similar solution can be implemented here. In fact texlive has a package named, "todonotes" for handling todos. This solution can either rely on the package "todonotes", or implement something new. 

## Anything Else?
- There was a request earlier to highlight the "\todo" commands https://github.com/James-Yu/LaTeX-Workshop/issues/2958. This request is on the similar lines but further ahead.

**Comment by James-Yu** [comment]
Unrelated to LaTeX.
