### ISSUE TITLE
Shortcuts of Refresh all viewers?

### ISSUE THREAD

**Issue by ronming1303** [James-Yu/LaTeX-Workshop#4172]
Hi there,

I cannot find the keyboard shortcut of Refresh all viewers.

I only find that ctrl+alt+v is for preview. But how to refresh the preview?

Thanks!

**Comment by James-Yu** [comment]
There is no default keyboard binding. The command you are looking for is `latex-workshop.refresh-viewer`. You can bind a shortcut by yourself.
