### ISSUE TITLE
The customization of the LATEX: STRUCTURE pane

### ISSUE THREAD

**Issue by sylph520** [James-Yu/LaTeX-Workshop#4174]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
-  When we have set some label in the latex document, the information is displayed in the LATEX: STRUCTURE pane, which is useful for some situation, But will let the TOC looks messy when the document contains lots of labels (e.g., figures, tables) .
## The Solution*
> _Please provide a solution you would like to have._
-  I was wondering whether we can have some toggle options to display the labels or not. and some other customization options may be also useful. e.g., the depth of displaying levels.
## Anything Else?
> _Add any other context about the feature request below._
-  Setting labels for figures, tables is rather common in academic paper/book writing, I suppose.

**Comment by James-Yu** [comment]
`latex-workshop.view.outline.commands`
