### ISSUE TITLE
An integrated spell checker

### ISSUE THREAD

**Issue by dskinnion** [James-Yu/LaTeX-Workshop#4176]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- We have tried a few different spell-checkers, but none are as good as those in emacs/auctex (which recognizes latex) or google docs (which doesn't recognize latex but is still better).

## The Solution*
> _Please provide a solution you would like to have._
- An integrated spell-checker that recognizes latex functions (and does not highlight those as spelling errors) and has few false positives for text.

## Anything Else?
> _Add any other context about the feature request below._
- We've also tried other extensions, such as Grammarly, LTeX and Code Spell Checker, and none are as useful as those in emacs/auctex or google docs. Thank you!

**Comment by jlelong** [comment]
This is out of the scope of the extension.
