### ISSUE TITLE
Word suggestion UI (single-click)

### ISSUE THREAD

**Issue by dskinnion** [James-Yu/LaTeX-Workshop#4177]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The current UI for word suggestions requires a mouseover, then click, then clicking on your choice, which is a lot of steps.

## The Solution*
> _Please provide a solution you would like to have._
- Ideally, like in google docs, we could simply hover over words for suggestions, and do a one-click replacement on that choice.

## Anything Else?
> _Add any other context about the feature request below._
- Thanks!

**Comment by jlelong** [comment]
I am not sure to understand your point. Autocompletion can be triggered by a shortcut and you can use `Enter` or `tab` to accept a suggestion. Please provide a screenshot.

**Comment by jlelong** [comment]
This is related to the spell checker you use not LW.
