### ISSUE TITLE
Automatic fill-in suggestions appear as actual text and need to delete in order to type attributes

### ISSUE THREAD

**Issue by dskinnion** [James-Yu/LaTeX-Workshop#4179]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When there are automatic fill-in suggestions, the suggestions appear as actual text in the editor. For example, for \uncover<overlay specification>{text}, if we edit, we have to manually delete the text "overlay specification" as it is actual text in the editor, as opposed to just a visual hint.

## The Solution*
> _Please provide a solution you would like to have._
- Once we start typing, it should automatically know we are inputting text that is supposed to take its place. The fill-in suggestions should be visual hints, not actual text in our code. For example, in Gmail there is a "Subject" in the subject line, but it not actually text there. When you start typing in the subject line, the "Subject" disappears automatically.

## Anything Else?
> _Add any other context about the feature request below._
- Thanks!

**Comment by jlelong** [comment]
In `\uncover<overlay specification>{text}`, both `text` and `overlay specification` are placeholders (see https://code.visualstudio.com/docs/editor/userdefinedsnippets). Once, you have the first text, type `TAB` to jump to `overlay specification`, which will be replaced as soon as you start typing.
