### ISSUE TITLE
Word wrapping that recognizes latex code

### ISSUE THREAD

**Issue by dskinnion** [James-Yu/LaTeX-Workshop#4182]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Sometimes word wrapping will break up latex expressions.

## The Solution*
> _Please provide a solution you would like to have._
- Is there a way for word wrapping to recognize latex expressions, and instead only break at spaces, not in the middle of a latex expression?

## Anything Else?
> _Add any other context about the feature request below._
- Thanks!

**Comment by jlelong** [comment]
Wrapping is directly handled by VS Code and we have no control over it.
Well, this is not completely true. Wrapping is based on the value of `wordPattern` defined by the language. However, this setting is used for many different purposes and in particular for autocompletion. Playing with it will break too many other features.
