### ISSUE TITLE
Emacs/Auctex commands

### ISSUE THREAD

**Issue by dskinnion** [James-Yu/LaTeX-Workshop#4183]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- N/A

## The Solution*
> _Please provide a solution you would like to have._
- We're wondering if there are additional commands from emacs/auctex that could be mimicked in the Latex Workshop extension. For example, commands to automatically enter begin/end pairs with a choice of which environment it is.

## Anything Else?
> _Add any other context about the feature request below._
- Thank you!

**Comment by jlelong** [comment]
It is already implemented
https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#inserting-an-environment
https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#environments
