### ISSUE TITLE
Math preview panel in VSCode panel

### ISSUE THREAD

**Issue by memeplex** [James-Yu/LaTeX-Workshop#4187]
## Pre-checks*

- [X] The feature request has not been suggested in this repository.

## The Missed*

Opening another editor for the math preview panel uses a significant amount of screen real estate. Oftentimes the VSCode panel is already open and the math preview panel stacks over it. 

## The Solution*

Allow to specify the VSCode panel as another valid location for the math preview panel.

**Comment by James-Yu** [comment]
Extensions of vscode cannot control the size or locations (other than up, down, left, right).

**Comment by memeplex** [comment]
Sorry, I don't think this is actually the case. Some extensions add new panes to the panel. Moreover, individual panes in the sidebar accordion can be dragged into the panel. The Quarto extension also implements a formula preview pane that is by default in the sidebar but can easily be relocated (https://quarto.org/docs/tools/vscode.html#live-preview).
