### ISSUE TITLE
Intellisense for DocTeX with expl3

### ISSUE THREAD

**Issue by huangyxi** [James-Yu/LaTeX-Workshop#4189]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

Currently, A `dtx` file could syntax highlight well with LaTeX3 commands in `DocTeX` mode from #569.
However, the Intellisense feature for LaTeX3 didn't enabled or deployed in DocTeX,
and the syntax highlighting for `dtx` file didn't render well in `LaTeX-Expl3` mode.

## The Solution*
> _Please provide a solution you would like to have._

Provide a new Language Mode with `DocTeX-Expl3`, enabling both Intellisense for LaTeX3 and syntax highlighting for `dtx` file.

## Anything Else?
> _Add any other context about the feature request below._

Nope.

**Comment by James-Yu** [comment]
Please detail your request with more info and examples.

**Comment by huangyxi** [comment]
Apologies, the problem was due to an issue with my custom fork.
The official release is functioning properly.
