### ISSUE TITLE
Bibliography autocomplete fails when using subfiles

### ISSUE THREAD

**Issue by randolf-scholz** [James-Yu/LaTeX-Workshop#4192]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Ubuntu 22.04
- Visual Studio Code Version: 1.87.0
- LaTeX Workshop Version: v9.19.0
- TeX Distribution Version:TexLive 2023

## The Issue*

I am using a multi-file project via `subfiles`. Following the manual, I include the bibliography via:

```tex
\usepackage[backend=biber]{biblatex}
\addbibresource{\subfix{bibliography.bib}}
```

However, then citation autocomplete fails, both in the main file and in included chapters.

### Reproduction Steps

`main.tex`

```tex
\documentclass{book}
\usepackage{subfiles}
\usepackage[backend=biber]{biblatex}
\addbibresource{\subfix{bibliography.bib}}

\begin{document}
\subfile{chapters/chapter1.tex}
\backmatter
\printbibliography
\end{document}
```

`chapters/chapter1.tex`

```tex
\documentclass[../main.tex]{subfiles}
\begin{document}
\cite{....} % <- no autocomplete available!
\end{document}
```

Notably, autocomplete becomes available again, if `\addbibresource{bibliography.bib}` is used instead of `\addbibresource{\subfix{bibliography.bib}}` (even in the subfiles!), but then only the `main.tex` file can be compiled successfully.

**Comment by randolf-scholz** [comment]
@James-Yu I assume some form of pattern matching is used? Because the following ridiculous workaround seems to function:

```tex
\usepackage[backend=biber]{biblatex}
\addbibresource{\subfix{bibliography.bib}}
\newcommand{\ignore}[1]{\relax}
\ignore{\addbibresource{bibliography.bib}}
```

**Comment by jlelong** [comment]
To detect the name of the `.bib` file, we scan the content of the command `\addbibresource`, which fails if the content is a macro.

I thought the `.fls` could help but maybe not. I will look into it.

**Comment by randolf-scholz** [comment]
I modified the line in my local `~/.vscode/extensions` to

```js
const bibReg = /(?:\\(?:bibliography|addbibresource)(?:\[[^[\]{}]*\])?){(?:\\subfix{)?([\s\S]+?)}(?:\})?|(?:\\putbib)\[(.+?)\]/gm;
```

and that seems to work.

**Comment by James-Yu** [comment]
No. Also need to consider compiling from subfile.
