### ISSUE TITLE
Default option for toolchain doesn't work under MiKTeX

### ISSUE THREAD

**Issue by cgranade** [James-Yu/LaTeX-Workshop#42]
The new default option for ``latex-workshop.toolchain`` uses ``latexmk`` as opposed to ``texify``. Under MiKTeX, however, ``latexmk`` fails unless a separate Perl interpreter is also installed and properly configured by the user. As a possible mitigation, the following seems setting to work under MiKTeX:
```json
    "latex-workshop.toolchain": [
        "texify --synctex --tex-option=\"-interaction=nonstopmode -file-line-error\" --pdf %DOC%"
    ]
```

**Comment by James-Yu** [comment]
Thanks for the issue. Actually this is set to a config setting instead of a hard coded toolchain. MikTeX users can either use this or install synctex according to the instructions in the readme.

I will consider adding this as an enum item for the toolchain.

**Comment by James-Yu** [comment]
Maybe add a new section in the readme stating this is a good idea. Though users tend to ignore readme, no more I can do to notify them on this... {sad face}
