### ISSUE TITLE
Intellisense support for custom commands

### ISSUE THREAD

**Issue by 0xdw** [James-Yu/LaTeX-Workshop#4200]
For example:

Assume I want to preserve consistent figure names across my paper, and it is a lengthy report. When citing my figures, I must always write 'Figure \ref{fig:temperature-distribution}', correct? So, what I do is develop a custom command where I just need to alter it in one place if any modification is required, and I would only use '\fig{temperature-distribution}' as a reference.

```tex
% The custom figure referencing command
\newcommand{\fig}[1]{\figurename{ \ref{fig:#1}}}
```

```tex
% Example figure
\begin{figure}[H]
    \centering
    \includegraphics[width=\textwidth]{Graphics/Temperature-Distribution.pdf}
    \caption{Temperature Distribution}
    \label{fig:temperature-distribution}
\end{figure}
```

But with normal referencing, `Figure \ref{fig:temperature-distribution}` it shows this when I start typing, but not in `\fig{temperature-distribution}`.

<img width="713" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/12568779/1a2b3df1-d469-4d45-8ced-d47daebb91d1">

This is just an example command that I actually use. There are more custom commands, such as wrapping the Example figure into a single command and expecting it to show accessible graphic files. But it's not.

So my request is, is it possible to make that list appear in the custom commands as well?

**Comment by James-Yu** [comment]
It won't be supported, unfortunately. What you request need a full-fledge macro expansion engine, which is far beyond the scope of this extension.

**Comment by jlelong** [comment]
A lot of things can already be done with out a full-fledge parser. 

We use the following regex to run a reference completion

```
/(?:\\hyperref\[([^\]]*)(?!\])$)|(?:(?:\\(?!hyper)[a-zA-Z]*ref[a-zA-Z]*\*?(?:\[[^[\]]*\])?){([^}]*)$)|(?:\\[Cc][a-z]*refrange\*?{[^{}]*}{([^}]*)$)/
```

So, if you rename your to `\figref` or `\reffig` for instance, you will have the completion.

**Comment by 0xdw** [comment]
> A lot of things can already be done without a full-fledge parser.
> 
> We use the following regex to decide if a reference completion should be triggered
> 
> ```
> /(?:\\hyperref\[([^\]]*)(?!\])$)|(?:(?:\\(?!hyper)[a-zA-Z]*ref[a-zA-Z]*\*?(?:\[[^[\]]*\])?){([^}]*)$)|(?:\\[Cc][a-z]*refrange\*?{[^{}]*}{([^}]*)$)/
> ```
> 
> So, if you rename your to `\figref` or `\reffig` for instance, you will have the completion.

Thank you so much for the tip. It works perfectly! ❤️

<img width="406" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/12568779/e90f6ccd-dec9-49ec-b919-57f5e71c5703">
