### ISSUE TITLE
Exceedingly slow compile times for large documents

### ISSUE THREAD

**Issue by HenryCarr98** [James-Yu/LaTeX-Workshop#4201]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Mac OSX 14.1]
- Visual Studio Code Version: [1.87.2]
- LaTeX Workshop Version: [9.19.1]
- TeX Distribution Version: [pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023/Homebrew)]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- Compiling thesis document and the extension loads, compiles fine for about an hour then the extension will either crash or become stuck in an infinite compilation loop. Rebooting VScode is the only valid fix and takes valuable time from my work. 
- 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. N/A: simple large document compilation. 
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Document should compile 
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
Here is how much of TeX's memory you used:
 30128 strings out of 476025
 577491 string characters out of 5779036
 1885388 words of memory out of 5000000
 48854 multiletter control sequences out of 15000+600000
 587485 words of font info for 353 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 124i,21n,118p,2372b,1031s stack positions out of 10000i,1000n,20000p,200000b,200000s
</opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmex10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi12.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi6.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi8.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmib10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr12.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr6.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr8.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy6.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy8.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/lm/lmss17.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/symbols/msam10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/public/amsfonts/symbols/msbm10.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/urw/courier/ucrr8a.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/urw/times/utmb8a.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/urw/times/utmr8a.pfb></opt/homebrew/Cellar/texlive/20230313_2/share/texmf-dist/fonts/type1/urw/times/utmri8a.pfb>
Output written on main.pdf (182 pages, 10538349 bytes).
PDF statistics:
 3248 PDF objects out of 3580 (max. 8388607)
 2775 compressed objects within 28 object streams
 699 named destinations out of 1000 (max. 500000)
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by HenryCarr98** [comment]
Excuse me? How can you be so sure? Worked fine before the update

**Comment by HenryCarr98** [comment]
@James-Yu this is plainly a problem with your extension. I've consulted with colleages who've all complained of similar issues with the extension. Today alone its crashed twice.

**Comment by HenryCarr98** [comment]
@James-Yu  A response would be appreciated.

**Comment by James-Yu** [comment]
This is not an extension problem. Additionally please kindly noted that the extension does not come with guarantee in any kind. Your provided information does not show anything wrong. I’m sorry but I cannot help resolve this issue.

**Comment by jlelong** [comment]
If you expect any kind of help, a clear description of this issue with the complete logs of the extension is required. You only posted the logs of the LaTeX compiler,  which are pointless here. The Developer Tools Console may also show useful information.

**Comment by HenryCarr98** [comment]
@jlelong @James-Yu How can I post logs when the very problem is it won't compile?

**Comment by James-Yu** [comment]
If that’s the problem, it is unrelated to the extension.

**Comment by HenryCarr98** [comment]
It plainly is, my colleague can't compile on his machine. It's not an error, it simply stays compiling forever until I restart VScode then it works for about an hour

**Comment by James-Yu** [comment]
If that’s the problem, it is unrelated to the extension.

**Comment by HenryCarr98** [comment]
@James-Yu Issue is persisting
