### ISSUE TITLE
When I edit a file imported via \input, the outline/structure bar doesn't scroll with my editing position.

### ISSUE THREAD

**Issue by changlichun** [James-Yu/LaTeX-Workshop#4207]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10
- Visual Studio Code Version: 1.87.1
- LaTeX Workshop Version: [e.g. 8.5.0]
- TeX Distribution Version: TeX Live 2023

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- When I edit a file imported via `\input`, the `outline/structure` bar doesn't scroll with my editing position.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. At least two file and one is imported by `\input`
2. The imported file contain only `\subsubsection` level structure

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Behave like in a single file

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
- I would like to provied my example code here
example.tex
```
\documentclass[]{article}
\usepackage{lipsum}

\begin{document}
\section[1]{sec 1}
\lipsum[1-3]

\subsection{sub 1}
\input{example-section}

\end{document}
```
example-section.tex
```
% \subsection{sec 2} 
% behave correctly when contain the subsection level title 
\subsubsection[2]{subsub 2}
\lipsum[4-6]
\subsubsection[3]{subsub 3}
```

**Comment by jlelong** [comment]
I cannot reproduce the issue. Are talking about the _Outline_ view in the _Explorer_ panel or about the _Structure_ view in the _TeX_ panel? In the _Outline_ view in the _Explorer_ panel, make to activate _Follow Cursor_ in the three dots

<img width="484" alt="Capture d’écran 2024-03-16 à 14 42 18" src="https://github.com/James-Yu/LaTeX-Workshop/assets/2910140/4725eade-c8b6-46c3-a216-07e7dae1c73a">

**Comment by changlichun** [comment]
I apologize for not being clear. I am talking about the structure view.
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/46743938/e56ed6f6-725f-48d4-bbb3-6e179877e7c9)

**Comment by jlelong** [comment]
Can you post a screenshot describing what you consider as an issue because I am not sure to understand what the true problem is?

**Comment by changlichun** [comment]
The current editing position should normally be spotlighted in the _structure_ view, but this is not possible when the file contains only `\subsubsection`

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/46743938/cdbe6191-6de2-4b56-9296-4ae247f7136e)

![image](https://github.com/James-Yu/LaTeX-Workshop/assets/46743938/1aabddda-f49f-40f0-88d8-676dd37d82f1)

**Comment by jlelong** [comment]
Thanks for the screenshots and for spotting the role of the first sectioning level in the included file.

**Comment by James-Yu** [comment]
For self-note: this issue was caused by the previous file path tracing logic, which only inspects the immediately children's file path. The fix will inspect the paths for all children and children-of-children.
