### ISSUE TITLE
I do not know why this happens

### ISSUE THREAD

**Issue by CherryRum** [James-Yu/LaTeX-Workshop#421]
![Uploading Snipaste_2018-02-18_19-51-24.jpg…]()
 

Log files are as follows

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX) (preloaded format=pdflatex 2018.2.9)  18 FEB 2018 19:42
entering extended mode
 restricted \write18 enabled.
 # file:line:error style messages enabled.
 %&-line parsing enabled.
**f:/Thesis/tex/1.tex
(f:/Thesis/tex/1.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 84 language(s) loaded.
(e:/texlive/2017/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(e:/texlive/2017/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) (./1.aux)
\openout1 = `1.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <12> on input line 5.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <8> on input line 5.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <6> on input line 5.
 [1

{e:/texlive/2017/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./1.aux) ) 
Here is how much of TeX's memory you used:
 224 strings out of 492995
 2359 string characters out of 6136403
 54074 words of memory out of 5000000
 3853 multiletter control sequences out of 15000+600000
 6675 words of font info for 24 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 23i,6n,17p,143b,187s stack positions out of 5000i,500n,10000p,200000b,80000s
<e:/
texlive/2017/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb><e:/texlive/20
17/texmf-dist/fonts/type1/public/amsfonts/cm/cmr12.pfb><e:/texlive/2017/texmf-d
ist/fonts/type1/public/amsfonts/cm/cmr17.pfb>
Output written on 1.pdf (1 page, 29528 bytes).
PDF statistics:
 20 PDF objects out of 1000 (max. 8388607)
 13 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by James-Yu** [comment]
So what's the problem?
