### ISSUE TITLE
latexmk enforces pdflatex

### ISSUE THREAD

**Issue by BaumiCoder** [James-Yu/LaTeX-Workshop#4211]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System:  Linux Mint 21.3 Virginia 64-bit
- Visual Studio Code Version: Version: 1.87.2
- LaTeX Workshop Version: 9.19.1
- TeX Distribution Version: TeX 3.141592653 (TeX Live 2024)

- I am using VSCodium whose version is:
```
Version: 1.87.2
Release: 24072
Commit: f7ed6417a7cfae92f98129384c13b505bb9cfc53
Date: 2024-03-12T18:30:28.994Z
Electron: 27.3.2
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.15.0-101-generic
```

## The Issue*
The default latexmk `tool` enforce the compiler `pdflatex`. This overwrites settings from the `.latexmkrc` file.

### Reproduction Steps
1.  Create a LaTeX document and in the same folder a file `.latexmkrc` with this content:
```
$pdf_mode=4,
$lualatex='lualatex --shell-escape %O %S'
```
2. Use in the latex document something that needs shell escape. 
3. Now you should be able to compile the document with `latexmk`.
4. Open it with VSCode and compile it there. The default there is also `latexmk` and should be triggered by file modifications.

### Expected Behavior
Settings from the `.latexmkrc` file is used, when I use `latexmk`.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
The settings for the tools latexmk has an `-pdf`:
```json
"latex-workshop.latex.tools": [
  {
    "name": "latexmk",
    "command": "latexmk",
    "args": [
      "-synctex=1",
      "-interaction=nonstopmode",
      "-file-line-error",
      "-pdf",
      "-outdir=%OUTDIR%",
      "%DOC%"
    ],
    "env": {}
  },
  //...
]
```
Manual page for this option:
```
       -pdf   Generate  pdf  version of document using pdflatex.  (If you wish
              to use lualatex or xelatex, you can use whichever of the options
              -pdflua, -pdfxe, -lualatex or -xelatex applies.)   To  configure
              latexmk  to  have  such  behavior by default, see the section on
              "Configuration/initialization (rc) files".
```
But also [other sources](https://mg.readthedocs.io/latexmk.html) suggest `-pdf` to make sure to get a pdf file.

**Comment by jlelong** [comment]
Use the recipe `latexmk (latemxkrc)` instead.
To set the default recipe see https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexrecipedefault

**Comment by BaumiCoder** [comment]
> Use the recipe `latexmk (latemxkrc)` instead. To set the default recipe see https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexrecipedefault

Right, that works, but is that a solution or only a workaround? The most tools are named as the compiler, but calls them over latexmk. For example:
```json
{
        "name": "lualatexmk",
        "command": "latexmk",
        "args": [
          "-synctex=1",
          "-interaction=nonstopmode",
          "-file-line-error",
          "-lualatex",
          "-outdir=%OUTDIR%",
          "%DOC%"
        ],
        "env": {}
      },
```
So why the tool `latexmk` is not called `pdflatex`? The naming and behavior contradict each other. 

And why there is a separate `latexmk (latemxkrc)` even necessary? How could be there a reason to ignore user and project settings?

**Comment by James-Yu** [comment]
1. That is a solution.
2. Because the command is latexmk, not pdflatex.
3. We only pass the arguments to latexmk. Whether considering the rc file or not is determined by latexmk, not this extension.
