### ISSUE TITLE
File::Path version 2.08 required

### ISSUE THREAD

**Issue by ARPIT2128** [James-Yu/LaTeX-Workshop#4212]
### Issue Description
When attempting to run `latexmk.pl`, I encountered the following error message:

```
File::Path version 2.08 required--this is only version 1.08 at D:/latex/scripts/latexmk/latexmk.pl line 81.
BEGIN failed--compilation aborted at D:/latex/scripts/latexmk/latexmk.pl line 81.
```

### Steps to Reproduce
1. Execute `latexmk.pl`.
2. Observe the error message.

### Expected Behavior
`latexmk.pl` should execute without errors.

### Also whenever i build for first time using {pdflatex} it gets successfully compiled
![image](https://github.com/LaTeXing/LaTeXing/assets/93235104/ddb5d598-2492-4426-b463-813d62f73045)

**Comment by James-Yu** [comment]
Not related to the extension.
