### ISSUE TITLE
Stop working with latexmk 4.84 - Upstream bug (Workaround)

### ISSUE THREAD

**Issue by BaumiCoder** [James-Yu/LaTeX-Workshop#4221]
## Situation

[latexmk](https://ctan.org/pkg/latexmk) in version `4.84` does not work with the option `-outdir` / `-output-directory`. The maintainer of latexmk is informed.
If you run latexmk without this option, there are no problems. So some users maybe thing, that it is a bug in LaTeX-Workshop.
So I create this issue to inform the users of the plugin about the root of the problem.

## Workaround

The workaround is to avoid the problematic option. For LaTeX-Workshop you have to go to the [latex-workshop.latex.tools in the settings.json](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-tools). There remove the lines:
```
"-outdir=%OUTDIR%",
```
for all entries with the command latexmk or at least the entries you are using.

## Updates

I will update this issue if I get feedback from the maintainer and when there is a bug fix available for latexmk.

**Comment by James-Yu** [comment]
https://github.com/James-Yu/LaTeX-Workshop/issues/4219#issuecomment-2033021354
