### ISSUE TITLE
Enable table of contents for .cls file

### ISSUE THREAD

**Issue by SwitWu** [James-Yu/LaTeX-Workshop#4228]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

For a big project such as a thesis template, the developers usually need to write a .cls file with several thousands of code lines. So it is desirable to be able to see the table of contents （or, say, structure) in the .cls file.

For example, one can mark the structure as follows:
```tex
% # process class and package options
some source code
% # load class and packages
some source code
% # handle paper size
some source code
% # chapter and section headings
some source code
```

## The Solution*
> _Please provide a solution you would like to have._

Is it possible for the plugin to recognize these structure markers and automatically make a toc for the developers so that they can jump to the code area they want to edit quickly?

## Anything Else?
> _Add any other context about the feature request below._

**Comment by James-Yu** [comment]
Unfortunately no, as such markers are not standard LaTeX macros. You may want to resort to other extensions for the feature. This extension can and will only parse TeX macros to construct the structure.

**Comment by SwitWu** [comment]
Fine. Have a good day
