### ISSUE TITLE
Completion with cwl files

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#4229]
@James-Yu 

While looking for `.cwl` for `tikz-*` packages in relation to #4215, I came across https://github.com/texstudio-org/texstudio/tree/master/completion

texsutdio has far more cwl files than https://github.com/LaTeXing/LaTeX-cwl and they also seem much more up to date. Unfortunately, texstudio seems to be released under the GPL-3, while LW complies with the MIT licence. I am afraid we cannot benefit from their files. What do you think?

**Comment by James-Yu** [comment]
I recall that using the code (data in our case) to generate new data is not restricted by GPL v.s. MIT. Indeed, the current script is using cwl files from texstudio, very poorly documented though.

I will search for the discussion issue on the license thingy shortly and add a dev document on the current workflow of cwl->json.

**Comment by James-Yu** [comment]
Got it. Originally discussed in #3579.
