### ISSUE TITLE
Can't find "perl.exe", PDF won't be displayed

### ISSUE THREAD

**Issue by zeneszenz** [James-Yu/LaTeX-Workshop#423]
### Description

I want to view the tex file as a PDF within VSC. I'm completely new to VSC and LaTex. 

### How to reproduce

1. Installed MiKTex in C:\MiKTeX, updated it afterwards
2. Installed VSC + the LaTeX-Workshop extension
3. Created an example.tex and tried via the LaTeX Workshop commands "View LaTeX PDF file in new tab"

### Expected behavior

Show the .tex File as an PDF within VSC next to the editor window

### Actual behavior
Nothing happens. Sometimes I get the error "LaTex toolchain terminated with an erorr"

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

From LaTex compiler:

latexmk: The script engine could not be found.
latexmk: Data: scriptEngine="perl.exe"

From LaTex workshop:

[16:12:41] No PDF viewer connected for c:\Users\jjohn\Documents\Latex\example.pdf
[16:12:41] Cannot find PDF file c:\Users\jjohn\Documents\Latex\example.pdf

</details>

### Additional Information

As stated before I'm a bloody beginner when it comes to LaTex and VSC. When using TeXWorks I can compile and view the PDF just fine. Once it is compiled by Texworks it is no problem for VSC to view the PDF so I guess the compiler is producing this problem?

**Comment by James-Yu** [comment]
`latexmk` requires `perl`. You can refer to README for other toolchains without `perl` dependency.
