### ISSUE TITLE
PDF viewer not showing the right font

### ISSUE THREAD

**Issue by LeonE2024** [James-Yu/LaTeX-Workshop#4230]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ *] The issue has not been reported in this repository.
- [ *] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ *] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [* ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Windows 11
- Visual Studio Code Version: 1.88.1
- LaTeX Workshop Version: 9.19.2
- TeX Distribution Version: TeX Live 2023

## The Issue*
> I am working with a dokument in the Arial font. Unfortunately, the build-in web browser still shows the document in the default latex font instead of arial. If I open the same document in google chrome, it is correctly displayed in arial.

### Reproduction Steps
1. create a latex document
2. use the magic comment %!TEX program = xelatex to set the compiler to xelatex
3. set the font to Arial with \usepackage[no-math]{fontspec} \setmainfont{Arial}
4. view it with the integrated PDF viewer

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```

**Comment by James-Yu** [comment]
Please provide an example pdf file with the problem.

**Comment by James-Yu** [comment]
Close for now due to inactivity.
