### ISSUE TITLE
Feature Request: Enhance or Disable Breadcrumbs for PDF Files

### ISSUE THREAD

**Issue by singularitti** [James-Yu/LaTeX-Workshop#4235]
I am reaching out to suggest an enhancement related to the breadcrumb functionality in Visual Studio Code when viewing PDF files using the LaTeX Workshop extension. Currently, when opening a PDF, such as `main.pdf`, both the editor tab and breadcrumb display the filename `main.pdf`. This redundancy does not provide additional navigational utility, particularly when the breadcrumb does not interact with the internal structure of the PDF, such as chapters or sections, which could be potentially useful.

<img width="439" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/25192197/15869cf2-7271-4a48-ade3-1e51952622f9">

## Issue Description

- When opening a PDF file in VS Code with LaTeX Workshop, the breadcrumb bar redundantly shows the PDF's filename, mirroring the tab's display without offering additional navigation or context.
- Attempting to disable this through `"breadcrumbs.filePath": "off"` results in the breadcrumb area showing "no elements" rather than being hidden, which does not improve the user interface.

<img width="227" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/25192197/69566556-7826-4cfa-b5dd-3f2b08a6d100">

## Feature Request

1. **Dynamic Breadcrumb Content**: Ideally, it would be fantastic if the breadcrumb could reflect the internal structure of the PDF (like chapters or sections listed in the PDF's bookmarks/catalogue). This would turn the breadcrumb into a useful tool for navigating through the document.
2. **Breadcrumb Disable Option**: If integrating dynamic content proves too complex, an alternative solution would be to provide an option to disable the breadcrumb display entirely when viewing PDFs through LaTeX Workshop. This would clean up the UI by removing the redundant display.

**Comment by James-Yu** [comment]
Unfortunately, I don't think it is possible via extension-side configuration. I would suggest filing an issue on vscode repo, mentioning breadcrumb for custom editor tabs and custom webviews.

**Comment by singularitti** [comment]
Thanks for the reply!
