### ISSUE TITLE
Backward/Reverse synctex  doesn't work

### ISSUE THREAD

**Issue by LKN321** [James-Yu/LaTeX-Workshop#4236]
Regardless of using the built-in PDF viewer or the browser, Backward/Reverse synctex suddenly stopped working, which was functioning fine  hours ago. Forward searching is still working normally.

Can you tell me what can I do  to fix it?

Thanks a lot!

**Comment by James-Yu** [comment]
Please fill the template.

**Comment by txctxc** [comment]
> Regardless of using the built-in PDF viewer or the browser, Backward/Reverse synctex suddenly stopped working, which was functioning fine hours ago. Forward searching is still working normally.无论使用内置的 PDF 查看器还是浏览器，Backward/Reverse synctex 都突然停止工作，而几个小时前它运行良好。正向搜索仍然正常工作。
> 
> Can you tell me what can I do to fix it?你能告诉我我能做些什么来修复它吗？
> 
> Thanks a lot! 多谢！

Same problem as yours. I'd like to suggest that you install another version before this bug is fixed.

**Comment by LKN321** [comment]
> > Regardless of using the built-in PDF viewer or the browser, Backward/Reverse synctex suddenly stopped working, which was functioning fine hours ago. Forward searching is still working normally.无论使用内置的 PDF 查看器还是浏览器，Backward/Reverse synctex 都突然停止工作，而几个小时前它运行良好。正向搜索仍然正常工作。
> > Can you tell me what can I do to fix it?你能告诉我我能做些什么来修复它吗？
> > Thanks a lot! 多谢！
> 
> Same problem as yours. I'd like to suggest that you install another version before this bug is fixed.

Thanks a lot! It does work!

**Comment by James-Yu** [comment]
The bug can't be fixed without a proper report. It's not a universal issue.
