### ISSUE TITLE
LaTeX3 syntax highlight fails in environments

### ISSUE THREAD

**Issue by SwitWu** [James-Yu/LaTeX-Workshop#4240]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [macOS Sonoma 14.4.1]
- Visual Studio Code Version: [1.88.1 (Universal)]
- LaTeX Workshop Version: [latest]
- TeX Distribution Version: [TeX Live 2024]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._

## The Issue*
> _Please briefly describe the issue you come across._

LaTeX3/expl3 syntax highlight fails in environments.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. creates `a.cls`
2. add the code
    ```tex
    \int_case:nn
    \begin{center}
      \int_case:nn
    \end{center}
    ```
3. The result is 
<img width="242" alt="image" src="https://github.com/James-Yu/LaTeX-Workshop/assets/39337667/9ffd8817-887f-4361-8604-29d95b713500">

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._

I expect the `\int_case:nn` in `center` has the right highlight as that out of `center`.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by James-Yu** [comment]
Thank you for filing this issue. We have outsourced our LaTeX syntax highlighting grammar to [vscode-latex-basics](https://github.com/jlelong/vscode-latex-basics), could you please post your issue there?
