### ISSUE TITLE
Conflict with "vscode-pdf"

### ISSUE THREAD

**Issue by mxdoerfler** [James-Yu/LaTeX-Workshop#4241]
## Pre-checks
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System: MacOS Sonoma 14.0
- Visual Studio Code Version: 1.81.1
- LaTeX Workshop Version: 9.20.0
- TeX Distribution Version: TeX Live 2024

## The Issue
When trying to preview a latex document get the following warning.

> LaTeX Workshop is incompatible with  "vscode-pdf". We compete when opening a PDF file from the sidebar. Please consider disabling either extension. 

This has been raised before and marked as fixed. Seems to be back.

**Comment by James-Yu** [comment]
Yes. The extension does conflict with the other one. "We compete when opening a PDF file from the sidebar."

**Comment by mxdoerfler** [comment]
Ah my bad, had read old issue as conflict was resolved and don't have to disable one of the two 👍
