### ISSUE TITLE
Cannot copy text from pdf viewer after updating and restarting any extension

### ISSUE THREAD

**Issue by anf4108** [James-Yu/LaTeX-Workshop#4248]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [macOS Sonoma 14.4.1]
- Visual Studio Code Version: [1.88.1]
- LaTeX Workshop Version: [9.20.0]
- TeX Distribution Version: [TeX Live 2022]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- Cannot copy text from pdf viewer after updating and restarting any extension. 
- This promblem likely came out after the [VSCode March 2024 update](https://code.visualstudio.com/updates/v1_88#_extensions-update-improvements). After pressing "update" and "Restart Extension" of any extension to update it, I cannot use `cmd-C` to copy the text content from the PDF. However, I can click the "Edit-Copy" from the toolbar as an alternative. After restarting vscode, it will be fine again.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Open a pdf file, select text and copy with `cmd-C`. It's ok.
<img width="1352" alt="Screenshot 2024-04-25 at 22 10 13" src="https://github.com/James-Yu/LaTeX-Workshop/assets/110650085/873deadd-1ff0-41cd-ad6a-e99f438d8e45">
2. When a extension is ready to update, click the "update" and then "restart extension" to update the extension without restart the whole vscode.
<img width="1352" alt="Screenshot 2024-04-25 at 22 11 30" src="https://github.com/James-Yu/LaTeX-Workshop/assets/110650085/07dc2415-9622-4723-9bf0-06978e80d004">

3. Copy different text, but then `cmd-C` is disabled actually.
<img width="1352" alt="Screenshot 2024-04-25 at 22 12 01" src="https://github.com/James-Yu/LaTeX-Workshop/assets/110650085/869e4484-ce46-47de-af6d-f14e562070bd">

4. Click "Edit-Copy", it works normally.
<img width="1352" alt="Screenshot 2024-04-25 at 22 22 45" src="https://github.com/James-Yu/LaTeX-Workshop/assets/110650085/cb6a25d7-f44e-4cb8-bc4e-cdd461f5a7f3">

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Be able to copy text from pdf viewer normally at any time.
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
- I don't no which caused this problem: the extension itself, vscode, or pdf.js?
- By the way, the copy shortcuts also have problem while using ssh. When I use ssh to open pdf on Ubuntu with vscode and LaTeX-Workshop, I must use `ctrl-C` to copy text instead of `cmd-C`, while copying in other files is still `cmd-C`.

**Comment by James-Yu** [comment]
Very likely that you need to reopen the pdf tab.

Please include logs.
