### ISSUE TITLE
Ctrl+click command on the pdf viewer not working with the most recent update of Windows 11

### ISSUE THREAD

**Issue by RayleighLord** [James-Yu/LaTeX-Workshop#4249]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The issue has not been reported in this repository.
- [x ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11
- Visual Studio Code Version:1.88
- LaTeX Workshop Version: 9.20
- TeX Distribution Version: TeX Live 2023

## The Issue*
> _Please briefly describe the issue you come across._
- Today, I have noticed that the `Ctrl+click` command to go from the pdf viewer to the LaTeX file does not work in Windows 11. I have not encountered this issue in Linux, where the functionality was correct. I have also reproduced this issue in two different computers, both with Windows 11 updated to the latest version.

**Comment by Zwchen1** [comment]
The same issue I have met！！
