### ISSUE TITLE
Default icon for LaTeX-Expl3

### ISSUE THREAD

**Issue by homchom** [James-Yu/LaTeX-Workshop#4250]
## Pre-checks
- [x] The feature request has not been suggested in this repository.

## The Missed
- I like VSCode's file icons, as they help me distinguish different file extensions easier. I especially like the default theme (Seti). However, since `LaTeX-Expl3` is a configured language, it is not part of the icon theme, and `.tex` files with `LaTeX-Expl3` selected look like this:
<img width="93" alt="Screenshot 2024-04-27 at 15 23 42" src="https://github.com/James-Yu/LaTeX-Workshop/assets/41265646/6fecd853-0693-4407-95d0-d0ab7d1c40f3">

## The Solution
- [As of VSCode 1.64, configured languages can have default icons.](https://code.visualstudio.com/updates/v1_64#_language-default-icons) It would be nice if `LaTeX-Expl3` had a default icon.

**Comment by James-Yu** [comment]
The extension does not provide file icon. You may need to report to your icon provider extension.
