### ISSUE TITLE
Broken intellisense test

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#4255]
Related to 2b95587
The following test is broken https://github.com/James-Yu/LaTeX-Workshop/actions/runs/8875693549/job/24365661941#step:13:179 

https://github.com/James-Yu/LaTeX-Workshop/blob/00a8195dc63d73e018b2c928bca7325ede51611e/test/suites/04_intellisense.test.ts#L250-L255

I am not sure what we exactly want here. With the new implementation, we always consider the content of `\lablel` and `\linelabel` as labels for further reference. 
https://github.com/James-Yu/LaTeX-Workshop/blob/808b8480ef790c0154452f9cda6febe56b8c2144/package.json#L1990-L1999

**Comment by James-Yu** [comment]
Seems that the test were functional, but the design was indeed wrong? Will fix that soon.

**Comment by James-Yu** [comment]
Spent some time and figured that the fix in 2b95587dcff30b8ca769143afd0d06e6157710f7 was incorrect. #4252 now is correctly fixed. The root was that the macro parser in unified-latex consider a signature of `d<> o m` for `label` by default, but was forced to `o m` in the script. f628304b4403bdb260e4d1a0f8e38decdc40bfb9 reverted the fix and implement the correct one.
