### ISSUE TITLE
Proposal: Intellisense additions to \usepackage

### ISSUE THREAD

**Issue by Swoy** [James-Yu/LaTeX-Workshop#426]
Hello,

I've looked at the syntax plist files, but I cannot wrap my head around it. So I was hoping to get some help here;

After I have expanded \usepackage{$1} I would like to add a _second_ layer to the code suggestion with help text for all CTAN available packages. My problem is that I don't know how to do this.

I can provide *name* and *help description*/link to CTAN/usage for all packages in the format you desire, as long as I know how to write the data :)

**Comment by James-Yu** [comment]
Instead of `syntax`, intellisense are coded in the extension. You may refer to `src/providers/completer` for how `\cite{}` works.

In the meantime, it is already good enough to provide the data in the form of `data/unimathsymbols.json`, which contains the symbols suggested by the extension.

**Comment by Swoy** [comment]
Alright, I've made a packages.json now with 27298 lines. It has the following format:
```
    "zwpagelayout": {
	    "command": "zwpagelayout",
	    "detail": "https://ctan.org/pkg//pkg/zwpagelayout",
	    "documentation": "Page layout and crop-marks."
      },
```
Does this work?

**Comment by James-Yu** [comment]
That's good enough. Can you please rename the file and place it in the corresponding folder? I am more than happy to merge your PR.

**Comment by Swoy** [comment]
I'm not sure which folder and name you refer to, I apologize, I am quite new with extensions ^^
I will send you a PR as soon as I know this :)

**Comment by Swoy** [comment]
Pull request added as #429
