### ISSUE TITLE
Allow customisation for the regex to decide if a completion should be triggered.

### ISSUE THREAD

**Issue by Guscccc** [James-Yu/LaTeX-Workshop#4268]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Yes, custom commands won't trigger intellisense if the command name doesn't match predefined regex. For example, `\let\ci\cite` and `\ci` won't trigger the citation hover.

## The Solution*
> _Please provide a solution you would like to have._
- Allow customisation of the regex to trigger intellisense.

## Anything Else?
> _Add any other context about the feature request below._
- Related: James-Yu/LaTeX-Workshop/issues/4200

**Comment by James-Yu** [comment]
Honestly, I am highly hesitated to expose the internal regexs to the end-user, as I can foresee the flood of issues due to improper definition of them. I would recommend you to adhere to the pattern requiring `cite` end.
