### ISSUE TITLE
missing auto completion of commands with () as arguments

### ISSUE THREAD

**Issue by DailyShana** [James-Yu/LaTeX-Workshop#4270]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Many commands in tkz-euclide doesn't have a completion. #4257, they are commands with () as arguments https://github.com/James-Yu/LaTeX-Workshop/issues/4257#issuecomment-2110113706

## The Solution*
> _Please provide a solution you would like to have._
- ignore the arguments, just record the name of the commands. Auto completion of the commands without arguments is still useful.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
It conflicts with the macro deduplication mechanism. Sorry to let this request down.

**Comment by DailyShana** [comment]
so, could you improve "macro deduplication mechanism", which seems to avoid repeated macros in cwl when parsing it?
I think it can be done by update pkgcommand.py and related scripts.

@jlelong could you take a look? sorry for at you directly
