### ISSUE TITLE
Option to pass verbatimEnvironments to latexindent

### ISSUE THREAD

**Issue by Tianmaru** [James-Yu/LaTeX-Workshop#4273]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- it is not intuitive, that changing latex-workshop's `verbatimEnvironments` option is not passed to latexindent
- appears to do nothing
- related to https://github.com/James-Yu/LaTeX-Workshop/issues/3736 

## The Solution*
> _Please provide a solution you would like to have._
- add a checkbox option to pass verbatim environments to latexindent
- maybe this should be the default
- at least add some information in the option's description how to achieve wanted behaviour
- `-y=verbatimEnvironments:comment:1`
- 

## Anything Else?
> _Add any other context about the feature request below._
- consider including `comment` environments to verbatimEnvironments

**Comment by James-Yu** [comment]
You can change `latex-workshop.latexindent.args`.

**Comment by Tianmaru** [comment]
Yes, that is what I did in the end - however, my point was, that it is not obvious from the description of the `verbatimEnvironments` option that the environments will not be passed to latexindent automatically.
