### ISSUE TITLE
Remove Equation Labels when hovering over an equation

### ISSUE THREAD

**Issue by Alex2134556** [James-Yu/LaTeX-Workshop#4274]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- If I were to hover on an equation post-compilation, then it gets the equation label which messes up the Hover image (presumably due to some \hfill commands to right-justify the equation label. However, the same issue isn't present when I hover pre-compilation. For reference I have included the pictures: 

Post-Compilation:
![Screenshot 2024-06-03 at 1 33 32 PM](https://github.com/James-Yu/LaTeX-Workshop/assets/95665546/a1e65a57-fe23-4ffc-850d-b919b6583a63)

Pre-Compilation: 
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/95665546/e8e91014-f866-48cb-a15c-6eeaf7dd9fe5)

## The Solution*
> _Please provide a solution you would like to have._
- Adjusting the hover so that it works as if we have pre-compiled would be best (or having a toggle option between setting hover to read pre-compilation or post-compilation.

**Comment by James-Yu** [comment]
There is such a config.
