### ISSUE TITLE
Structure panel is not considering files included by custom inclusion macros

### ISSUE THREAD

**Issue by marlondecol** [James-Yu/LaTeX-Workshop#4276]
## Pre-checks

- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment

- Operating System: macOS Sonoma 14.5
- Visual Studio Code Version: 1.90.0
- LaTeX Workshop Version: 9.20.1
- TeX Distribution Version: TeX Live 2024

## The Issue

The structure panel doesn't show anything when my document uses a custom file inclusion macro.

Let's suppose I have the following file:

```latex
% methodology.tex

\chapter{Methodology}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed venenatis at.
```

When this file is included as shown below, the structure panel works as expected:

```latex
% main.tex

\begin{document}
\input{methodology}
\end{document}
```

But when it is included using a custom macro, the structure panel is empty:

```latex
% main.tex

\NewDocumentCommand\append{}{\cleardoublepage\input}

\begin{document}
\append{methodology}
\end{document}
```

The thing is that the structure panel only interpret standard file inclusion commands.

### Expected Behavior

What I expect is that the structure panel considers files included by custom inclusion macros that implement the standard ones. The extension could, e.g., offer a setting to define the macros to be considered.

---

I believe this is enough to understand the issue. If not, I can include other information as needed.

**Comment by James-Yu** [comment]
Unfortunately, the extension does not have the capability of expanding macros. We use regex and static grammar parsing to build the structure of a document.

It is highly unlikely to provide such support, as it requires reimplementing the whole TeX macro expansion logic, which is way to complex.
