### ISSUE TITLE
Autocomplete `\end{environment}` after `\begin{environment`

### ISSUE THREAD

**Issue by LinqLover** [James-Yu/LaTeX-Workshop#4277]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When using an environment, currently, I can either type `\environment` and press tab (but this only works for environments that have already existed during the last build) or start with `\begin{environment` and write everything manually.
- First, this is redundant typing and second, the paths for automation and manual typing diverge.

## The Solution*
> _Please provide a solution you would like to have._
- It would be great if after typing `\begin{environment`, I could press tab to autocomplete the end and empty body of the environment.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
https://github.com/James-Yu/LaTeX-Workshop/assets/4210342/d4632879-643d-4959-962e-bdc1b88df035

**Comment by LinqLover** [comment]
Thanks for the screencast, I did notice that it already works in this situation! However, this seems not to work when I type the `\begin` manually without pressing Tab before typing the environment name:

[Screencast from 09.06.2024 23:43:39.webm](https://github.com/James-Yu/LaTeX-Workshop/assets/38782922/c9502705-5baf-4940-84bb-6e6667be1eeb)

Second, this does not work for new environments before I have compiled the document:

[Screencast from 09.06.2024 23:45:54.webm](https://github.com/James-Yu/LaTeX-Workshop/assets/38782922/206a6190-ad6a-4a16-98b5-5a98c1e54678)

I would find this pretty helpful :)

**Comment by James-Yu** [comment]
Done.
