### ISSUE TITLE
Mathpreviewpanel of long equation with \tag{}

### ISSUE THREAD

**Issue by qmphys** [James-Yu/LaTeX-Workshop#4287]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10, WIndows 11
- Visual Studio Code Version: 1.90.1
- LaTeX Workshop Version: 9.20.1
- TeX Distribution Version: [e.g. TeX Live 2019 / MiKTeX 2.9.7250]

## The Issue*
> _Please briefly describe the issue you come across._
- When I use the math preview panel to preview a long equation with \tag{} label, the panel displays a narrow result with overlapped tag. 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Type a long equation in equation or align environment and use \tag{} to label it.
2. Call out the math preview panel or use hover preview, the displayed region is narrow with overlapped tag.
3. Delete \tag{}, there is no problem.

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Preview equation normally with \tag{} command.

**Comment by James-Yu** [comment]
This is a MathJax issue. You may post the issue at https://github.com/mathjax/MathJax .
