### ISSUE TITLE
Passing indentconfig.yml to LaTeX docker image

### ISSUE THREAD

**Issue by dulimarta** [James-Yu/LaTeX-Workshop#4291]
Running the LaTeX binaries through a Docker container is an excellent feature I enjoy a lot, however I did not find an easy way to customize the formatter latexindent to my preferred style.

## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Solution*
- Add an option similar to `"latex-workshop.latexindent.args"` for specifying the indentconfig.yaml to use during docker run

**Comment by James-Yu** [comment]
Docker usage is not supported by us.
