### ISSUE TITLE
Unexpected default trim levels

### ISSUE THREAD

**Issue by kevinbbbb** [James-Yu/LaTeX-Workshop#4293]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: Ubuntu 22.04 LTS
- Visual Studio Code Version: 1.90.2
- LaTeX Workshop Version: 9.21.0
- TeX Distribution Version: TexLive 2024

## The Issue*
- The new `latex-workshop.view.pdf.trim` setting does not behave as expected.
- The levels 0, 1, 2, 3 of the setting seem to trim 0%, 1%, 2% and 3%, respectively.

### Reproduction Steps
1. Change `latex-workshop.view.pdf.trim` setting (see screenshot). 
![Screenshot_20240623_202604](https://github.com/James-Yu/LaTeX-Workshop/assets/91126221/5dbae0bb-de47-473a-a747-b34079bd5079)
2. Reopen PDF to see changes. Besides the obvious low trim level, the faulty numerical trim level can also be seen in the drop-down menu of the PDF viewer (see screenshot). ![Screenshot_20240623_203855](https://github.com/James-Yu/LaTeX-Workshop/assets/91126221/1591a540-070a-4bbb-859e-cb70008d1de2)

### Expected Behavior
- The descriptions of the `latex-workshop.view.pdf.trim` setting suggests that instead, it should set the trim level to 0%, 5%, 10% and 15%, respectively.

**Comment by James-Yu** [comment]
That’s the changed behavior. I forgot to make an announcement. You may read the new description to the config.

**Comment by kevinbbbb** [comment]
Resarting VS Code fixed it and I can now set the default trim level myself instead of choosing between three presets.
