### ISSUE TITLE
align pdf viewer to center

### ISSUE THREAD

**Issue by thangckt** [James-Yu/LaTeX-Workshop#4298]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

When setting
```
"latex-workshop.view.pdf.zoom": "page-actual",
```
the PDF viewer aligns to the left by default.
I wonder if there is any setting that can center the PDF viewer by the default.

Thank you.

**Comment by James-Yu** [comment]
The pages are center-aligned no matter what zoom level is selected. If not, please share your PDF for debug.

**Comment by thangckt** [comment]
hi @James-Yu 

My pdf viewer align on the left
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/46436648/a59d3fbc-6477-45e0-a78a-8fa522c8b9f5)

**Comment by James-Yu** [comment]
That's the "actual" size of your PDF. You have a scrollbar in the bottom.

**Comment by James-Yu** [comment]
Scroll it. There is no auto-way of doing so.

**Comment by thangckt** [comment]
@James-Yu Thank you for your information
In some editors, such as Texstudio, there is an option to display pdf page with "fit to textwidth". Can you implement it in Latex-workshop?

Thank

**Comment by James-Yu** [comment]
`page-width`

**Comment by thangckt** [comment]
I see the `page-width` option, but it displays in different way with `text-width`

**Comment by James-Yu** [comment]
There is no such a feature. You are advised to submit a feature request to PDF.js viewer, as we primarily use this viewer to display PDF.
