### ISSUE TITLE
pdf error - possibly related to align environment 

### ISSUE THREAD

**Issue by Jo-Fleck** [James-Yu/LaTeX-Workshop#430]
I am encountering a problem which seems to be related to empty lines between plain text and the \begin{align}...\end{align} environment. I have not been able to reproduce the error in other tex editors so I am a bit puzzled.

If I run the code below the pdf looks fine after the first compilation. If I then remove or add blank lines in front or after the align environments and compile again, the pdf is either empty, the font is corrupted or I cannot open it at all (or a combination of the first two). See the image below.

There is no error or warning message displayed. Any idea what I am doing wrong?

Thanks a lot for developing this extension and maintaining it!

\documentclass[10pt,a4paper]{article}
\usepackage[left=2.5cm,right=2.5cm,top=1.6cm,bottom=1.6cm,includeheadfoot]{geometry}

\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}
\usepackage{csquotes}
\usepackage[english]{babel}
    
\usepackage{setspace}
\linespread{1.2}
\usepackage{parskip}
\setlength{\parskip}{0.3em}

\usepackage{amsmath, latexsym, mathtools}

\title{Illustration of align bug}
\date{\today}
\author{}

\begin{document}

\maketitle
\tableofcontents
\newpage

\section{Section 1}

\subsection{Subsection 1}

Here is the first equation 
\begin{align}
    u(c,l) &= \log(c - v(l))
\end{align}
followed by the second one
\begin{align}
    y_i &= (\varepsilon_i l_i)^{\alpha}
\end{align}

and the last one
\begin{align}
    c_i &= y_i
\end{align}

\end{document}

<img width="952" alt="screen shot 2018-02-23 at 7 59 30 pm" src="https://user-images.githubusercontent.com/25301265/36611534-1de5eb08-18d4-11e8-8e9f-5a96621f5823.png">

**Comment by James-Yu** [comment]
I am quite confident that this is not related to the extension. By nature it only invokes the corresponding compiler to produce PDF. No LaTeX contents are manipulated. You may want to compare the results with one produced in command line (CMD/Bash/Terminal).

**Comment by Jo-Fleck** [comment]
Thanks a lot for your response! If I invoke the compiler via the command line the pdf looks fine. But I agree with your reasoning so I tried to find another explanation.

I think this is the reason: If I keep the pdf open in Preview (I am on a Mac) while making changes to the tex file and then compile again, the problem described above occurs. If I want to display the pdf in a browser the same thing happens. 

I only started to encounter this issue after installing the macOS High Sierra 10.13.3 Supplemental Update (more info here: https://support.apple.com/en-us/HT208535). 

Do you think this could be what's going on?

**Comment by Jo-Fleck** [comment]
Quick followup - I played around some more and was able to narrow down what's causing the problem: If I save the changes to the tex file (cmd s) in VSCode this automatically runs the build command and the pdf looks correct. If instead I do not save the changes but invoke the build command directly, the pdf has the problems described above. Is this behavior expected?

**Comment by Jo-Fleck** [comment]
The code fed into the compiler is the above. At this point, I think there is some reason to believe the problem is tied to VSCode and/or the Latex Workshop extension (see below). I might be wrong of course. As I don't have info if other users experience the same problem and as I found a workaround I'll just wrap up my findings and then you can proceed how you think is best. Let me know if you need any further info. Thanks for your work on this great extension!

What I tried but did not help: 
using a pdf viewer other than Preview; viewing the pdf in a browser; closing the viewer/browser during compilation

What I tried and did not lead to the same problem:
compiling the tex code using another editor (TeXShop, TeXworks); compiling directly via the command line; using an online compilers (Overleaf)

What I did to exclude other reasons:
check if a recent Mac update causes the problem (very unlikely); double-check my VSCode keybindings
