### ISSUE TITLE
Autocompletion of custom \knowledgenewrobustcmd commands not working 

### ISSUE THREAD

**Issue by dfigueira** [James-Yu/LaTeX-Workshop#4309]
In the context of the [knowledge](https://ctan.org/pkg/knowledge) package, one can define custom commands using `\knowledgenewrobustcmd` (with the same syntax as `\newcommand` or `\newrobustcmd`). 

Autocompletion does not work for `\knowledgenewrobustcmd` custom commands, and it would be great if you could extend its usage to `\knowledgenewrobustcmd` definitions as well!

(similar to #4303 but for `\knowledgenewrobustcmd`)

**Comment by James-Yu** [comment]
You can define the macros in `latex-workshop.intellisense.command.user`. We cannot support all packages of LaTeX unfortunately.
