### ISSUE TITLE
Error when \documentclass is inside an \input file

### ISSUE THREAD

**Issue by dgomezcastro** [James-Yu/LaTeX-Workshop#4310]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
- Operating System: MacOS Sonoma
- Visual Studio Code Version: 1.90.2
- LaTeX Workshop Version: v10.1.0
- TeX Distribution Version: TeXLive 2024

## The Issue*
The MWE is the following: a `main.tex` file
```
\input{header.tex} 

\begin{document}
a
\end{document}
```
and the `header.tex` file
```
\documentclass{article}
```
When trying to run LaTeX Workshop on `main.tex`, it tries to compile `header.tex`

In more complicated cases, it may randomly choose some other .tex file. 

### Reproduction Steps
1. Create the two files for the MWE and try to compile `main.tex` 

### Expected Behavior
I would expect it to compile `main.tex`

**Comment by James-Yu** [comment]
`latex-workshop.latex.rootFile.indicator`

**Comment by dgomezcastro** [comment]
Yes, this solved it. Thanks!
