### ISSUE TITLE
“SyncTex from cursor” not working.

### ISSUE THREAD

**Issue by WuXinglong-HIT** [James-Yu/LaTeX-Workshop#4312]
## Environment*
VSCode Version: 1.91
LaTex-Workshop Version: v10.1.0

## The Issue*
After compiling the latex file, I am able to view the Latex PDF file.
To enhance readability, I right-click on the tab header and select the "Move into new window" option.
However, after making edits in the .tex file, when attempting to preview the .pdf file and clicking on "SyncTex from cursor", the function fails to work as expected.
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/73932819/1c8bb738-9858-4bbb-8348-0b2b1df62338)
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/73932819/ba85763b-d0d8-46f9-9ff9-39e7a5d7cc05)

## Anything Else?
> By the way, the funciton fails from .tex to .pdf, but not vice versa. Locating the corresponding position in .tex file from .pdf file is executed without any issues.

**Comment by James-Yu** [comment]
You cannot move it to a new window, or the extension will lose track of the tab. This is (almost surely) a vscode limitation.
