### ISSUE TITLE
Support BibLaTex multiprenote and multipostnote

### ISSUE THREAD

**Issue by postylem** [James-Yu/LaTeX-Workshop#4313]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- BibLaTex 'multicite' commands (see [biblatex docs](https://mirrors.mit.edu/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf#page=109.49), §3.9.3 Qualified Citation Lists) seem to be not (fully) supported. Specifically, there are no autocomplete snippets for a so-called multi-prenote and multi-postnote (notes which come before / after the whole list of citations).

    ✔️ While a multi-citation command `\parencites`, with the following syntax, is supported
    ```tex
    \parencites[pre][post]{bibid}[pre][post]{bibid} 
    ```
    ❌ the version with multiprenote and/or multipostnote (which are in parentheses) seem not to be supported:
    ```tex
    \parencites(multipre)(multipost)[pre][post]{bibid}[pre][post]{bibid} 
    ```
    This is the case with other multicite commands which all have the same syntax, such as `\footcites`, `\textcites`, `\smartcites`, and uppercase versions, etc.  Since these are standard commands in biblatex, it seems reasonable they should be supported, but maybe this is intentional. Sorry if so.

## The Solution*
> _Please provide a solution you would like to have._
- Autocomplete snippets (and other support? see below) for these commands.

## Anything Else?
> _Add any other context about the feature request below._
- I am not sure whether this is part of LaTeX-Workshop's features or not, but the more egregious problem that I notice when using these commands is that they do not seem to be supported by the latex syntax highlighter, and that this issue arises even without the parenthetical arguments (and also the spellchecking I am using, but that is an issue for another extension).

    <img width="693" alt="Screenshot 2024-07-06 at 14 06 31" src="https://github.com/James-Yu/LaTeX-Workshop/assets/5202957/5e09e523-a268-4f23-a01a-0f91681292b7">

    It's worth noting that the citation info on hover does work in all these cases.

**Comment by James-Yu** [comment]
Thanks for the issue. Have you tried `latex-workshop.intellisense.package.dirs` and its documentation?

**Comment by jlelong** [comment]
I will look into the syntax highlighting issue jlelong/vscode-latex-basics#93

**Comment by jlelong** [comment]
As far as intellisense is concerned, the multi-prenote (or postnote) versions are included in `biblabtex.cwl` but these entries are ignored by our Python script, which generates the [`biblatex.json`](https://github.com/James-Yu/LaTeX-Workshop/blob/729fe8ae88d4e82bf9fe24ef845b45dd28946be9/data/packages/biblatex.json) data file. I will look into the conversion toolchain

**Comment by postylem** [comment]
> latex-workshop.intellisense.package.dirs

Thanks, I hadn't looked at that, but now that I did, and I'm not sure I understand.  Are you referring to what jlelong mentioned re these versions with parens being generated into the biblatex.json data file?

**Comment by jlelong** [comment]
@James-Yu We use to have intellisense for macros containing `(...)`, but it was apparently removed by d545d62. I cannot remember why, do you have a better memory than I do?

**Comment by James-Yu** [comment]
Will check, may not be very soon sadly 😭
