### ISSUE TITLE
Reverse sync is very inaccurate

### ISSUE THREAD

**Issue by bhancock8** [James-Yu/LaTeX-Workshop#432]
### Description

When I have my latex document up in two tab view (.tex on the left, pdf preview on the right), forward sync works perfectly, but the reverse sync from the pdf back to the source text is very inaccurate, usually off by half a page to a full page. 

I know the synctex.gz file is okay, since when I open the same file up in Sublime, syncing works correctly in both directions. I also tried deleting all auxiliary files and rebuilding; same problem. It happens for all latex documents I try. I see there was an update on 2/22 to improve synctex accuracy, but it didn't change anything for me. 

Other than this one glitch, the extension works wonderfully and I'm a big fan!

Any ideas for what else to try?

**Comment by James-Yu** [comment]
Can you please provide an example for debugging? I never encountered similar problems.
