### ISSUE TITLE
Can `.fls` file be auto-cleaned?

### ISSUE THREAD

**Issue by lirm-math** [James-Yu/LaTeX-Workshop#4322]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Every time I compile a `.tex` file, I have a new `pdflatex-<numerals>.fls` file.  

## The Solution*
> _Please provide a solution you would like to have._
- Stop these files from generating or just delete them? 

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
You can tweak auto-cleaning configs to remove them.

**Comment by jlelong** [comment]
Note that cleaning a `.fls` might alter your experience with the extension. See  the second paragraph of https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#the-dependencies
