### ISSUE TITLE
Structure view shows unwanted entries

### ISSUE THREAD

**Issue by T-Tonic** [James-Yu/LaTeX-Workshop#4323]
## Pre-checks*

- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*

- Operating System: macOS Sonoma 14.5
- Visual Studio Code Version: 1.91.1 (Universal)
- LaTeX Workshop Version: 10.1.0
- TeX Distribution Version: TeX Live 2024

## The Issue*

- When adjusting spacing for section titles using the titlesec package the structure view picks up unwanted commands

![image](https://github.com/user-attachments/assets/f0b55622-40dc-4fd0-9899-ae8eb5213779)

### Reproduction Steps

1. Run the following MWE:

```
\documentclass{book}

\usepackage{titlesec}

\titlespacing\section{20pt}{12pt plus 4pt minus 2pt}{20pt plus 2pt minus 2pt}

\begin{document}

\chapter{Chapter}

\section{Section}

Some text.

\end{document}

```

### Expected Behavior

- I would expect the `\section `after the `\titlespacing` to be ignored in the structure view

**Comment by James-Yu** [comment]
`\titlespacing{\section}{20pt}{12pt plus 4pt minus 2pt}{20pt plus 2pt minus 2pt}`
