### ISSUE TITLE
Command suggestions do not include some commands, like \gls{}

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [James-Yu/LaTeX-Workshop#4327]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- when starting to write a command, such as \gls{} or \citep{}, I get suggestions for other commands but not those, even if I write the command completely. See the short video attached exemplifying this.

## The Solution*
> _Please provide a solution you would like to have._
- I would like to have suggesions and autocomplete of these commands as for others.

## Anything Else?
> _Add any other context about the feature request below._
[Screencast from 31-07-2024 16:02:12.webm](https://github.com/user-attachments/assets/f32b4684-ee43-4dbb-982f-c4a94f2e1d90)

**Comment by James-Yu** [comment]
<img width="910" alt="image" src="https://github.com/user-attachments/assets/14ae5b02-b533-438c-bc57-21513135b6fb">

You need to compile first.

**Comment by Miguel-LlamasLanza** [comment]
I have compiled it first and it does not work. Actually the issue seems to be related to the fact that I use a preamble.sty file which loads all the modules. See e.g. [This website](https://www.overleaf.com/learn/latex/Management_in_a_large_project#Preamble_in_a_separate_file).

Because of this, the suggestions are not provided in the main.tex or other tex files

**Comment by Miguel-LlamasLanza** [comment]
So basically the request should be to include suggestions when the packages are loaded in a preamble file

**Comment by James-Yu** [comment]
It's not a preamble tex file: the tutorial you provide is creating a new package. You can use almost the same content in the .sty file but change the file extension to .tex, then `\input` it.

**Comment by James-Yu** [comment]
Another option is, you can force load package suggestions in `intellisense.package.extra` config.

**Comment by Miguel-LlamasLanza** [comment]
Thanks. That works :)
