### ISSUE TITLE
Image path auto-completion for overpic environment 

### ISSUE THREAD

**Issue by roma28** [James-Yu/LaTeX-Workshop#4329]
## Pre-checks*
- [x ] The feature request has not been suggested in this repository.

## The Missed*
- When using `overpic` environment from `overpic` package there is no auto-completion of image path, which adds difficulties when working on a project with complex structure.

## The Solution*
- Implement path autocompletion for `overpic` environment in the same way it's implemented for `\includegraphics`

**Comment by James-Yu** [comment]
Thanks for the request. Unfortunately, we will not support macros/envs from packages if its usage differs from more widely used ones. The referenced `overpic` is an environment, and we do not have similar logic implemented already.

**Comment by James-Yu** [comment]
I will keep an eye on this request and try to find simple ways to support it.
