### ISSUE TITLE
Feeature Request - Secondary Toolchain

### ISSUE THREAD

**Issue by u5589306** [James-Yu/LaTeX-Workshop#433]
### Description
Working on big(ish) papers / project, the toolchain, bound to a keyboard shortcut is super convenient (after it has been updated to build and refresh the bibliography with pdflatex and bibtex respectively). Furthermore, enabling clean upon build clears the clutter ones the toolchain executes successfully.

However, when working on a smaller document, like a letter without a bibliography, the toolchain does not executes successfully as the bibliography is missing (the file still builds though).

Log upon build:
[14:24:38] Toolchain step 3: bibtex, let7
[14:24:38] Toolchain returns with error: 2/null.

### Request

Current workaround I have is using magic comment:
% !TEX program = true
to skip bibtex for files I want and replacing "true" with "bibtex" for when I do want bibtex.  This produces the results I want but builds the file several time when only one (or twice) would have sufficed.

In my opinion, the ideal solution would be to have a secondary build command / toolchain that could be modified and bound to a different keyboard shortcut.

PS. Thanks for the plugin. Really makes vscode so much more usable than some of the clunky IDEs.
PPS (or PSS?). It does sound like a small issue but as much as I like pretending it, I am not a software guy (or at least, yet). I could not work out what was going on after about two hours of searching.

**Comment by lbittarello** [comment]
While this feature isn't added, one can use tasks to run a secondary toolchain. I set up a test task to run biber:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Biber",
            "type": "shell",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "command": "biber '${workspaceFolder}\\${fileBasenameNoExtension}'",
        }
    ]
}
```

You can even assign a shortcut to test tasks for convenience.

(Inspiration from [here](https://pmateusz.github.io/latex/2018/01/30/vs-code-latex-editor.html).)

**Comment by u5589306** [comment]
Hi @lbittarello 
Thanks for the reply. So I have created the task.json in ~/.vscode with the following content

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "CompileTexWithoutBibFile",
            "type": "shell",
            "group": {
                "kind": "test",
                "isDefault": true
                     },
            "command": "pdflatex '${workspaceFolder}\\${fileBasenameNoExtension}' && pdflatex '${workspaceFolder}\\${fileBasenameNoExtension}'",
         }
             ]
}
```

However, I have a couple of questions.
a. How do I access this command? Because tasks are only available on a workspace folder.
b. How would I assign a shortcut to it?

Thanks again.

**Comment by lbittarello** [comment]
You could have separate task files for each project. You could then switch between workspaces as you work on different projects. As an alternative, you could have one workspace with this task file and add all your projects to it. (A workspace can span multiple folders.)

To assign a shortcut, you need to add the following code to your `keybindings.json` file (which you can access from the command palette by searching "Preferences: Open Keyboard Shortcuts File"):
```
{
    "key": "***",
    "command": "workbench.action.tasks.test",
    "args": "Run Test Task"
}
```
