### ISSUE TITLE
Independently trim margins in horizontal and vertical directions

### ISSUE THREAD

**Issue by dmitry-kabanov** [James-Yu/LaTeX-Workshop#4330]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

N/A 

## The Solution*

When trimming margins for a PDF, it would be useful to trim horizontal margins separately from vertical ones.

Now, when I trim, they are trimmed uniformly which leads to the situation, when I should stop trimming due to the vertical margins being much smaller than the horizontal margins.
This leads to the situation, when the text is still too small and there are visible left and right margins.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
Thanks for the feature request. However, the feature will add an additional layer of complexity to the alread-too-convoluted viewing and trimming logic. I'd recommend you approach PDF.js viewer repo at https://github.com/mozilla/pdf.js for the request.
