### ISSUE TITLE
Tex to Docx

### ISSUE THREAD

**Issue by dbourrion** [James-Yu/LaTeX-Workshop#4333]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Hi. Im' a writer, using visual studio code and LaTeX and LaTeX-Wokshop for my works. The little problem I have is that a lot of publisher here in France want the manuscript in docx.
So each time a text is done, I have to pass it from tex to docx using tools out of VSC
It would be amazing to have that export **inside** VSC

## The Solution*
> _Please provide a solution you would like to have._
- A simple pandoc command like `pandoc foo.tex --from latex --to docx > foo.docx ` makes the magic happen

## Anything Else?
> _Add any other context about the feature request below._
- THANKS :)

**Comment by James-Yu** [comment]
You can create a tool and add it to a recipe. See wiki.
