### ISSUE TITLE
Feature Request: emphasize/italicise selected text with Keyboard Shortcut.

### ISSUE THREAD

**Issue by SabicAlija** [James-Yu/LaTeX-Workshop#434]
### Description

In Texmaker one can select a text, that should be emphasized and press <kbd>CTRL</kbd>+<kbd>B</kbd> to wrap the text portion with \textbf{%TEXT%}.

### Additional Information
<kbd>CTRL</kbd>+<kbd>B</kbd>  is probably already in use, but one could certainly use other combinations.

### Proposal

Would be great if one could select a text (%TEXT%) and press

* <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd> to wrap it inside \textbf{%TEXT%} - alt. {\bfseries %TEXT%}, and
* <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> to wrap it inside \textit{%TEXT%} - alt. {\itshape %TEXT%}

**Comment by Swoy** [comment]
keybindings.json:

**Comment by SabicAlija** [comment]
Great! Worked instantly. Thanks a lot. :blush:

Is there a way to activate those keybindings only for certain file extensions (e.g. tex)? :thinking:

**Comment by Swoy** [comment]
Yes, by using multi-clause in ´when´ clause.

Like this:  ´"when": "editorLangId == latex && editorTextFocus",´

Keep in mind that you probably need to do some tweaking here.

**Comment by SabicAlija** [comment]
Almost. :wink:

```{r, engine='bash', code_block_name} ...
"when": "editorlangId == latex && editorTextFocus",
```

Anyway, thank you.

**Comment by Swoy** [comment]
oh, for me the `L` has to be capitalized or it wont work.

**Comment by ManuGira** [comment]
For latex file only, the `editorlangId == latex` dosen't work for me. But I managed to make it work for file with extention ".tex" using `resourceExtname == .tex`
I also replaced `editorTextFocus` by `editorHasSelection` which is better suited to my needs. 
I finally end up with the following:
``` 
"when": "editorTextFocus && resourceExtname == .tex",
```
