### ISSUE TITLE
Show warnings and errors from custom latexmkrc in problems panel

### ISSUE THREAD

**Issue by ShaiAvr** [James-Yu/LaTeX-Workshop#4340]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- I wanted to create a `.latexmkrc` file to copy the ouput pdf into another location. I only want to do that for a single project, so I think it should be done in a  local `.latexmkrc` file and not in the tools and recepies settings of Latex Workshop. I came up with something like this:
```perl
use File::Copy;

$success_cmd = 'internal OnSuccess %D';

sub OnSuccess
{
	my $file = $_[0];
	copy($file, "/.../Destination") or die "Failure! $!";
}
```
and it works well. I changed the destination to a non-existing path to see how it reports errors. The compilation failed, but no error is displayed in the problems panel. Instead I have to look for my error message in the compiler log:

![Screenshot 2024-08-17 155921](https://github.com/user-attachments/assets/2f581a86-dd0c-4d8d-a973-5f300067e634)

If I change the `die` command to `warn`, then it compiles succesfully, which makes sense, but the warning is still not dispalyed in the problems panel. I need to look for it in the compiler log:

![Screenshot 2024-08-17 160154](https://github.com/user-attachments/assets/bcbd80f7-6aa4-475e-afcc-a4b36f7477e4)
This is bad since the compilation succeeded so I don't even realize I need to look for warnings in the logs.

## The Solution*
> _Please provide a solution you would like to have._
- I think the problem panel should collect and display the errors and warnings from a custom `.latexmkrc` file. Especially the errors, since it just tells me the compilation fails and shows nothing on the problem panel, so I now need to hunt down the error message in the log. I originally wanted to use `warn` instead of `die` since the compilation succeeded and just the post proccessing step of copying the output failed, but by using `warn` I don't get any indication that this step failed until I find that the output wasn't copied.

**Comment by James-Yu** [comment]
It's not possible. Just think: how to define a pattern of text denoting a failure and can be agreed by other users?

> I only want to do that for a single project, so I think it should be done in a local .latexmkrc file and not in the tools and recepies settings of Latex Workshop.

You can define project-specific settings in vscode.

**Comment by ShaiAvr** [comment]
@James-Yu I meant a specific Latex project. My vscode workspace contains multiple Latex projects.
