### ISSUE TITLE
Export a LanguageServer or LanguageService

### ISSUE THREAD

**Issue by StefanoDeVuono** [James-Yu/LaTeX-Workshop#4342]
## Pre-checks*
- [x] The feature request has not been suggested in this repository.

## The Missed*
- I'm implementing Markdown extension to do request forwarding for LaTeX embedded in markdown files. However, unlike VS Code's examples where CSS embedded in HTML can leverage the HTML LanguageService to call:

```js
htmlLanguageService.doComplete(
  document,
  textDocumentPosition.position,
  htmlLanguageService.parseHTMLDocument(document)
);
```

As far as I know, LaTeX-Workshop does not export or expose a LanguageService or LanguageServer.

## The Solution*
- An incrementally implemented LanguageService that would allow other extensions to do something like:
```ts
latexWorkshopLanguageService.provideCompletionItems(
  document: vscode.TextDocument,
  position: vscode.Position
)
```

## Anything Else?
> _Add any other context about the feature request below._
- Something like this was discussed in #2520, with @tamuratak mentioning that it would be useful to make a plugin for LaTeX completions within Markdown. **Note** that the following code:

```js
commands.executeCommand('vscode.executeCompletionItemProvider', document.uri, triggerCharacter)
```

Does not work on virtual documents, it only works on document URIs for real files. (You can get around this with a temp file, but that's slow and does not seem like a good design.)

**Comment by James-Yu** [comment]
Thanks for your request. Unfortunately, this extension is designed around the concept of LaTeX document (or project). It cannot support patches of LaTeX code as in Markdown, at least without very significant changes in its fundamental design.

**Comment by StefanoDeVuono** [comment]
Not wanting to fundamentally change the design of your extension makes a lot of sense.

I've found two fairly easy solutions.

One, that changes five lines in main, adds support for virtual files:
```patch
diff --git a/src/main.ts b/src/main.ts
index 6e34d2f0..c517ace4 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -265,7 +265,7 @@ function registerProviders(extensionContext: vscode.ExtensionContext) {
     )
 
     extensionContext.subscriptions.push(
-        vscode.languages.registerCompletionItemProvider({ scheme: 'file', language: 'tex'}, lw.completion.provider, '\\', '{'),
+        vscode.languages.registerCompletionItemProvider([{ scheme: 'file', language: 'tex'},{ scheme: 'embedded-latex', language: 'latex'}], lw.completion.provider, '\\', '{'),
         vscode.languages.registerCompletionItemProvider(bibtexSelector, lw.completion.bibProvider, '@')
     )
 
@@ -291,8 +291,11 @@ function registerProviders(extensionContext: vscode.ExtensionContext) {
     const registerAtSuggestion = () => {
         const atSuggestionLatexTrigger = vscode.workspace.getConfiguration('latex-workshop').get('intellisense.atSuggestion.trigger.latex') as string
         if (atSuggestionLatexTrigger !== '') {
+            const embeddedLatexSelector: vscode.DocumentSelector = [{scheme: 'embedded-latex', language: 'latex'}]
+            const withEmbedded = embeddedLatexSelector.concat(latexDoctexSelector)
             lw.completion.atProvider.updateTrigger()
-            atSuggestionDisposable = vscode.languages.registerCompletionItemProvider(latexDoctexSelector, lw.completion.atProvider, atSuggestionLatexTrigger)
+            atSuggestionDisposable = vscode.languages.registerCompletionItemProvider(
+                withEmbedded, lw.completion.atProvider, atSuggestionLatexTrigger)
             extensionContext.subscriptions.push(atSuggestionDisposable)
         }
     }
```
This code already works to allow other extensions to use LaTeX-Workshop's existing capabilities. 

While, I have not finished the language server, it might not require *any* design changes to the core code. It would, however, necessitate making LaTeX-Workshop packable as an npm module. If you were to allow adding something *like the following*, then people could iterate on the language service, without changing any underlying code:
```patch
diff --git a/src/languageService.ts b/src/languageService.ts
new file mode 100644
index 00000000..c653238e
--- /dev/null
+++ b/src/languageService.ts
@@ -0,0 +1,14 @@
+import vscode from 'vscode'
+import { lw as latexWorkshop } from './lw'
+
+type Lw = typeof latexWorkshop
+
+export const init = (lw: Lw) => {
+    const languageService = {
+        doComplete: (document: vscode.TextDocument, position: vscode.Position) => {
+            return lw.completion.provider.provideCompletionItems(document, position)
+        }
+    }
+    return languageService
+}
+
```

Hopefully, both of these solutions are minimally invasive as they allow us to leverage LSP's embedded request forwarding to support LaTeX in other extensions.

**Comment by James-Yu** [comment]
Is `scheme: 'embedded-latex'` a universal definition? If so, the first option seems do no harm and I am happy to review a PR.

**Comment by StefanoDeVuono** [comment]
> Is scheme: 'embedded-latex' a universal definition? If so, the first option seems do no harm and I am happy to review a PR.

Not quite, but it seems to follow common design pattern to allow consumption by virtual documents.

For example, in the vscode-python extension, they use: [`{ scheme: 'vscode-notebook', language: PYTHON_LANGUAGE }`](https://github.com/microsoft/vscode-python/blob/61bc2d510ee0b3d69bed259f21b318c6f129254f/src/client/common/constants.ts#L12); in the VS Code Language Server's tests, they create [`scheme: 'file-test'`](https://github.com/microsoft/vscode-languageserver-node/blob/14ddabfc22187b698e83ecde072247aa40727308/client-node-tests/src/servers/testServer.ts#L140) for an in memory test file system.

So, `scheme: 'embedded-latex'` would be something your plugin defines. The existing Markdown math plugin (which doesn't provide intellisense, but still references your plugin) creates a language and grammar called `"markdown-math"`. Maybe something like `scheme: 'markdown-math'` or `scheme: 'embedded-markdown-math'` could work?

**Comment by StefanoDeVuono** [comment]
Also, I was able to get things working by loading your extension via it's path in my extension:
```ts
 const LatexWorkshop = vscode.extensions.getExtension('James-Yu.LaTeX-Workshop')
  const LatexWorkshopPath = LatexWorkshop?.extensionUri.path
  const LatexWorkshopFullPath = path.join(LatexWorkshopPath!, 'out/src/lw.js')
  import(LatexWorkshopFullPath).then(({lw})=> {
    const completion = lw.completion

    vscode.languages.registerCompletionItemProvider('markdown',
      new MarkdownCompletionItem(completion),
      ...completionTrigger
    )
  })
```
This seems a little hacky, as it makes arbitrary assumptions about your extension and consumes it in a way it probably wasn't designed to be used. But, if the above doesn't seem like a good idea, at least we have this! Being able to use your extensions intellisense implementation would be pretty great, so I'm open to different ideas!

Thanks for taking a second look!

**Comment by James-Yu** [comment]
> Also, I was able to get things working by loading your extension via it's path in my extension:

Indeed this is a possible way to do it. Once back we expose our internal API to a global variable to save some hassle. It was removed because we cannot guarantee API compatibility. However, I'd say the current framework won't see too big changes in the near future.

**Comment by StefanoDeVuono** [comment]
> Indeed this is a possible way to do it.

All right. I'll stick with that for now! Thanks for taking the time to discuss and consider these options!
