### ISSUE TITLE
Math preview for empheq environment

### ISSUE THREAD

**Issue by fk128** [James-Yu/LaTeX-Workshop#4349]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- I want to be able to see math previews for equations defined inside `empheq` env. E.g. the following does not generate a math preview:

```tex
\documentclass[]{article}
\usepackage{empheq}

\begin{document}
\begin{empheq}[box=\fbox]{align}
    A & = B \\
    C &= D
\end{empheq}
\end{document}
```

## The Solution*
> _Please provide a solution you would like to have._

The solution seems to be simply adding `empheq` to `ENV_NAMES` https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/parse/find.ts#L6 

One issue, however, is that `\begin{empheq}[box=\fbox]{align}` would result in `Error: Invalid option: box` whereas `\begin{empheq}[]{align}` would work to generate a preview. Perhaps it would be possible to get mathjax to ignore the options when it's an empheq env or strip the options out in the mathjaxify function https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/preview/hover/utils.ts#L8? I can make a PR for this, if this sounds sensible.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
https://docs.mathjax.org/en/v3.2-latest/input/tex/extensions/empheq.html

We generally won't alter tex string passed to MathJax other than new command definitions. Making ENV_NAMES in MathJaX finding would be fine, and I am happy to review PR on that.
