### ISSUE TITLE
Is there a way to disable auto indent for Tex only?

### ISSUE THREAD

**Issue by rxyang** [James-Yu/LaTeX-Workshop#435]
I know where to disable auto indent in general in vscode. Would like to know there is a way to disable auto indent for latex editing only. Thanks!

**Comment by James-Yu** [comment]
You may want to use [Language specific editor settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings) of vscode.

**Comment by rxyang** [comment]
Thank you!
