### ISSUE TITLE
Snippet for `@article` in bibtex

### ISSUE THREAD

**Issue by lirm-math** [James-Yu/LaTeX-Workshop#4353]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [X] The issue has not been reported in this repository.
- [X] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [X] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [X] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Windows 11]
- Visual Studio Code Version: [1.92.2]
- LaTeX Workshop Version: [10.2.0]
- TeX Distribution Version: [TeX Live 2023]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- There are no `pages` entry in the snippet for `.bib` files

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Create an empty `.bib` file, say `refs.bib`
2. Type `@ar` and then `<enter>` for auto-completion
3. You get 
```
@article{key,
  author = {},
  journal = {},
  number = {},
  title = {},
  volume = {},
  year = {}
}
```

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
```
@article{key,
  author = {},
  journal = {},
  number = {},
  title = {},
  volume = {},
  year = {},
  pages = {}
}
```

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
- I am not quite sure if this is due to "LaTeX Workshop", or anythihg else.

**Comment by James-Yu** [comment]
`pages` is not a mandatory field for `@article`.

**Comment by lirm-math** [comment]
> `pages` is not a mandatory field for `@article`.

Yes, `pages` is not required for `@article`, according to  [bibtex.com](https://www.bibtex.com/e/article-entry/). There are only four required fields: `author`, `title`, `journal` and `year`. `volume` and `number` are not `required`, either, as well as `pages`. They are all `optional`, more mandatory than the level `non-standard`. However, to the best of my knowledge, `pages` appears far more frequently than `number`, at least as much as `volume`, in the articles I read.   So, would you please add `pages` to the list, or, would you please show me how I set it up for myself? 

Thank you so much for your help.

**Comment by James-Yu** [comment]
It's in https://github.com/James-Yu/LaTeX-Workshop/blob/da45fa38fadb987c4c181be85264f23376e3f541/data/bibtex-entries.json#L2-L8
