### ISSUE TITLE
Magic comment not working anymore?

### ISSUE THREAD

**Issue by ArneMeier** [James-Yu/LaTeX-Workshop#4354]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Mac OS Sonoma 14.6.1 (23G93)
- Visual Studio Code Version: 1.92.2 (Universal)
- LaTeX Workshop Version: 10.2.0
- TeX Distribution Version: 3.141592653-2.6-1.40.26 (TeX Live 2024)

## The Issue*
- The magic comments seem to be completely ignored. After downgrading to 10.1.0 they work again.

**Comment by James-Yu** [comment]
Fixed in d3c86b06721cceab0ae7fbc296519c74b23c14d6
