### ISSUE TITLE
Image drag-and-drop in markdown_latex_combined

### ISSUE THREAD

**Issue by flyingpurplepeopleeater** [James-Yu/LaTeX-Workshop#4355]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Sonoma 14.6.1]
- Visual Studio Code Version: [1.92.2]
- LaTeX Workshop Version: [10.2.1]
- TeX Distribution Version: [TeX 3.141592653 (TeX Live 2024)]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- N/A

## The Issue*
The Markdown functionality for dragging and dropping an image is that it not only drops in the name of the file, but also the image syntax (that is, ![alt text](image.png)). markdown_latex_combined only drops in the name of the file.

### Reproduction Steps
1. Open up a new file, and set the grammar to markdown_latex_combined
2. Drop in any image.

### Expected Behavior
The full image syntax

### LaTeX Workshop Output*
N/A

### Developer Tools Console
```
N/A
```

## Anything Else?
feature request, inclusion of the "markdown.editor.drop.copyIntoWorkspace" setting but for markdown_latex_combined 🥺

**Comment by James-Yu** [comment]
You posted in wrong repo.

**Comment by James-Yu** [comment]
Found it. You may report to https://github.com/tecosaur/LaTeX-Utilities

**Comment by flyingpurplepeopleeater** [comment]
I don't have Latex Utilities, only Latex Workshop; is this still an issue for tecosaur? (Apologies if so!)

**Comment by James-Yu** [comment]
This extension does not handle drag n drop image. If there is auto-snippet insertion, it’s not done by us.
