### ISSUE TITLE
Remove env suggest triggered by character

### ISSUE THREAD

**Issue by DarvidTorres** [James-Yu/LaTeX-Workshop#4356]
I want to remove the suggestions of environment based on a single character (or remove all the env suggestions at once). Whenever I type "b" it triggers the align environment which is annoying when typing.

![image](https://github.com/user-attachments/assets/c3dd1f4c-1450-45f3-b456-e46e39848573)

Settings:

"[latex]": {
        "editor.tabSize": 2,
        "editor.wordWrapColumn": 80,
        "editor.wordWrap": "wordWrapColumn",
        "editor.defaultFormatter": "nickfode.latex-formatter",
        "editor.wordBasedSuggestions": "off",
        "editor.suggestOnTriggerCharacters": false,
        "editor.suggest.showFunctions": false,
        "editor.suggest.showClasses": false,
        "editor.suggest.showConstants": false,
        "editor.suggest.showKeywords": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.acceptSuggestionOnCommitCharacter": false,
        "editor.acceptSuggestionOnEnter": "off",
        "editor.inlineSuggest.suppressSuggestions": true,
    },

**Comment by James-Yu** [comment]
https://stackoverflow.com/a/70595277

**Comment by DarvidTorres** [comment]
The problem is that I don't want to turn off all snippet suggestions, only the default ones triggered by single characters like the example above. I want, however to keep the suggestions for other snippets and also the user-defined snippets. Here's how I solved it:

I went to the folder where the `latex-snippet.json` file is found on my PC within the `.vscode\extensions\james-yu.latex-workshop-10.2.1\data` folder and changed the name to `_latex-snippet.json`

![image](https://github.com/user-attachments/assets/0b2bff71-821c-4a41-b095-5ec139fc53c9)

Restarted VSCode and it worked as desired

**Comment by AstaSchnee** [comment]
I used to adopt the same method as yours, and it works. However, you have to repeat this after each update. This troubles me.
I just found another answer to the problem shared by James Yu that works well, see https://stackoverflow.com/a/78723774. 
This may help avoid this. (I believe it, but have not verified it.)
