### ISSUE TITLE
Proposal: General purpose PDF viewer

### ISSUE THREAD

**Issue by bartosz-antosik** [James-Yu/LaTeX-Workshop#437]
Would it be possible to make PDF viewer work for other PDF files selected from explorer?

I cannot really decide whether this solution would be elegant or not but I am quite sure would be very handy.

**Comment by James-Yu** [comment]
It should be working if you right click on any pdf file.

**Comment by GoBigorGoHome** [comment]
I have a question that might be a little off-topic: how can I (if it's possible at all) make the PDF viewer opened in a window different from the window enclosing the .tex source file? 

If this is possible it'll be a lot more convenient when working with 2 screens.

**Comment by James-Yu** [comment]
Open PDF in browser tab is what you are looking for @GoBigorGoHome

**Comment by bartosz-antosik** [comment]
Oh, thank you, haven't noticed this!

Out of curiosity: It is not possible to handle straight click on the file in Explorer?

**Comment by James-Yu** [comment]
Right, there is no such API unfortunately 😢

**Comment by bartosz-antosik** [comment]
Thank you for response. I will maybe seek to escalate this to VSCode.
