### ISSUE TITLE
error custom auto-completion

### ISSUE THREAD

**Issue by FouPouDave** [James-Yu/LaTeX-Workshop#4372]
Hello, I have translated my text for you.

I am using custom auto-completion. For example:

```json
"latex-workshop.intellisense.command.user": {
  "image...": "begin{center}\r\n\t\includegraphics[width=${2:0.9}\textwidth]{./images/$1}\r\n\end{center}\r\n"
}
```

Before version 10.3.0, it worked very well. I used to get this result when I typed "\ima":

```latex
\begin{center}
    \includegraphics[width=0.9\textwidth]{./images/}
\end{center}
```

Now it gives me:

```latex
\image...begin{center}
    \includegraphics[width=0.9\textwidth]{./images/}
\end{center}
```

---

Let me know if you need any further adjustments!

**Comment by James-Yu** [comment]
This is a regression. Will look into the issue.
