### ISSUE TITLE
Feature request: Showing word-count of selection in the status bar

### ISSUE THREAD

**Issue by Rasul-Esmaeilbeigi** [James-Yu/LaTeX-Workshop#438]
It would be great to see the number of words in the status bar. I usually use a word-processor such as MS word or Libreoffice for this purpose. This is rather annoying and time consuming. Thanks.

**Comment by James-Yu** [comment]
You can use ctrl+shift+p then type `count latex` to count the words. It is burden-some to auto invoke the script.
