### ISSUE TITLE
Cannot tap PDF to move to LaTeX on remote file system

### ISSUE THREAD

**Issue by akenejie** [James-Yu/LaTeX-Workshop#4386]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Linux Mint 22 / Windows 11
- Visual Studio Code Version: 1.93.1
- LaTeX Workshop Version: 10.3.2
- TeX Distribution Version: TeX Live 2024

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using Open Collaboration Tools whose version is 0.2.4
- I am using Japanese Language Pack for Visual Studio Code whose version is v1.93.202409110

## The Issue*
> _Please briefly describe the issue you come across._
- When you tap a PDF in a remote environment,
“[SyncTeX] %WS1%/テスト.synctex, %WS1%/テスト.synctex.gz not found.”
and cannot navigate to the PDF.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Shared using Open Collaboration Tools
2. Open the LaTeX source and PDF files
3. Click on the PDF file while holding down the Ctrl key

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- PDF file glows red for a moment and moves to LaTeX file.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[SyncTeX] %WS1%/テスト.synctex, %WS1%/テスト.synctex.gz not found.
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```

```

## Anything Else?
> _Add any other context about the problem below._
- This appears to be a bug related to .synctex.gz references in remote file systems in general, independent of the Open Collaboration Tools.

**Comment by James-Yu** [comment]
The extension does not support collaborative tools. See FAQ.
