### ISSUE TITLE
Feature request for internal PDF viewer: Showing the last modified part of the document

### ISSUE THREAD

**Issue by Rasul-Esmaeilbeigi** [James-Yu/LaTeX-Workshop#439]
Currently it seems that the internal PDF viewer works rather independently of the text editor. Each time you save the file it shows the first page of the PDF file instead of showing the recent modifications. You need to do some extra work to see the most recent change. It would be great to add this feature as it makes life much easier! Thanks for your great work.

**Comment by James-Yu** [comment]
The pdf file is scrolled to where it was left.
