### ISSUE TITLE
IntelliSense auto suggest issues with cite and ref

### ISSUE THREAD

**Issue by karimmd** [James-Yu/LaTeX-Workshop#4393]
I think previously I did not have this issue but recently I noticed that while I type `\cite`, the IntelliSense auto suggest brings only `\cite[]{}` but not `\cite{}`. Also I noted that if I type `\ref` then `\cite{}` is appearing alongside `\ref{}`. I want to ask whether this is the default settings and if there are ways that I can modify so that if I type `\cite` the auto suggest should firstly show me `\cite{}` and in the similar ways if I type `\ref`, it should first show `\ref{}`.
![image](https://github.com/user-attachments/assets/03ebd369-885b-4303-a791-d301efb5fb46)
![image](https://github.com/user-attachments/assets/e35c0a3d-67a6-4156-aa58-894b6135e4d9)

**Comment by James-Yu** [comment]
Should be partially resolved in 2e59b4e .
