### ISSUE TITLE
doc: add tex-fmt formatting documentation to the wiki

### ISSUE THREAD

**Issue by WGUNDERWOOD** [James-Yu/LaTeX-Workshop#4398]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- tex-fmt support has been added but is currently undocumented.

## The Solution*
> _Please provide a solution you would like to have._
- Add tex-fmt documentation (similar to existing latexindent documentation) to the Wiki.

## Anything Else?
> _Add any other context about the feature request below._
- I can help with this but would need some time to understand the implementation.

**Comment by James-Yu** [comment]
Done
