### ISSUE TITLE
LaTeX formatter error in v10.4.0

### ISSUE THREAD

**Issue by MarkusPriska** [James-Yu/LaTeX-Workshop#4399]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
- Operating System: Windows 11
- Visual Studio Code Version: 1.93.1
- LaTeX Workshop Version: 10.4.0
- TeX Distribution Version: TeX Live 2024

## The Issue
-  When using format document i get the following error

![image](https://github.com/user-attachments/assets/d12ce46a-06f4-41b8-a4ae-c2def5fa359f)

### Reproduction Steps
1. Format document

### Expected Behavior
- The document begin formatted

**Comment by MarkusPriska** [comment]
Should add that it works normally in v10.3.2 so right now i just dont update.

**Comment by James-Yu** [comment]
Set the config in the error message to a formatter.

**Comment by MarkusPriska** [comment]
But i don't see anywhere in the LaTeX Workshop extension settings a place to pick a formatter?
