### ISSUE TITLE
The shortcut for "view LaTeX PDF file in new tab" (Ctrl + Alt + T) not working in Ubuntu

### ISSUE THREAD

**Issue by Rasul-Esmaeilbeigi** [James-Yu/LaTeX-Workshop#440]
In Ubuntu you cannot use "Ctrl + Alt + T" as a shortcut for "view Latex PDF file in new tab" because it is the default shortcut for opening the terminal. Is there any way to make "view Latex PDF file in new tab" as default (currently you should click on the corresponding button on the top-right corner). Thanks.

**Comment by James-Yu** [comment]
You can customize the keybinding in File->Preference
