### ISSUE TITLE
"view pdf" button/command argument customisation

### ISSUE THREAD

**Issue by maxerikss** [James-Yu/LaTeX-Workshop#4402]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- I like having the pdf alongside my main.tex file in the project folder. So instead of having something like myProject/output/main.pdf, I have myProject/myProject.pdf. I have written a script which copies the output pdf and rename it  and puts it in the main folder. However, when clicking the view pdf button vscode opens myProject/output/main.pdf instead of myProject/myProject.pdf and there doesn't seem to exist a way to change this.

## The Solution*
> _Please provide a solution you would like to have._
- Add a setting for giving latex-workshop.view command a custom argument. I guess it is something like %OUTPUT%/%DOC% right now. And I would like to change it to ${workspaceFolderBasename}.pdf

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
No it’s not possible. You can just click on the file in the vscode file browser to view it.
