### ISSUE TITLE
Default formatter to valid option

### ISSUE THREAD

**Issue by TLCFEM** [James-Yu/LaTeX-Workshop#4410]
https://github.com/James-Yu/LaTeX-Workshop/blame/a253abf0eac83dd540ecc1687d5bc028a9690bef/package.json#L2154

Is defaulting to none intended?
If not, can this default to `latexindent` so it works out of box.

**Comment by James-Yu** [comment]
It’s intended.

1. We don’t want to be opinionated on this selection.
2. latexindent does not work out of box for a number of distributions without its binary bundled. Requires cpan some modules which are highly ambiguous to non-Perl users.
