### ISSUE TITLE
Add PDF viewer support for remote writing using Remote Tunnel and VSCode Web

### ISSUE THREAD

**Issue by albertomercurio** [James-Yu/LaTeX-Workshop#4412]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
I tried to write latex documents on a remote server. I can connect to it both using the Remote SSH and Remote Tunnel extensions. The first one works perfectly, but the second one doesn't show the pdf. I can write of course, and I can compile, but I can't see the PDF with the extension viewer. I can open it with another PDF viewer, but then I don't have many features.

This would be great also for people accessing with VSCode web (for example iPad people), where they can connect to their server only using Remote Tunnel.

## The Solution*
> _Please provide a solution you would like to have._
- A working PDF viewer for Remote Tunnel and VSCode Web

**Comment by James-Yu** [comment]
We don’t support the said extension.

**Comment by Jiefei-Wang** [comment]
I ran into the same issue here. My understanding is that there are ways to view the pdf:
1. PDF preview: the window that will show up when you click a PDF file
2. web browser: You can view a pdf by clicking the latex button on the left panel -> Commands -> View in web browser

I tried both, only the second method is supported for remote development. I think that's what the wiki means @LorenzoFioroni

**Comment by LorenzoFioroni** [comment]
> only the second method is supported for remote development

I guess that's it, yes. That's unfortunate though, as I don't find the preview with web browser to be as usable as the PDF preview. I am not sure why, but it feels less natural. 
Anyway, I can definitely deal with opening vscode and the browser side by side for the moment.
Thanks!
