### ISSUE TITLE
dvipdfmx breaks when included in toolchain

### ISSUE THREAD

**Issue by silenfoot** [James-Yu/LaTeX-Workshop#442]
I'm working on a Japanese document using a template that includes a (very simple) makefile.  More out of curiosity than any sort of utility, I tried translating the makefile into a LW toolchain.

The toolchain is as follows: `platex TEXFILE -> dvipdfmx -p PAPERSIZE DVIFILE`.

For some reason, building the document with this LW toolchain in place doesn't work.  Instead, dvipdfmx tries to tell me that the provided PAPERSIZE is invalid:
`dvipdfmx:fatal: Invalid paper size:  "182mm,257mm" (0.00x728.50)`

Running the commands manually, running make, and using "make" as the LW toolchain all behave as expected.

Obviously I have several workarounds for this problem (no need to define a toolchain when i'm already provided with a makefile), but I thought it was worth mentioning.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

- BUILD command invoked.
- Found root file from active editor: /home/silenfoot/Workspace/rireki-style/rireki.tex
- Root file remains unchanged from: /home/silenfoot/Workspace/rireki-style/rireki.tex.
- Building root file: /home/silenfoot/Workspace/rireki-style/rireki.tex
- Build root file /home/silenfoot/Workspace/rireki-style/rireki.tex
- Toolchain step 1: platex, rireki
- LaTeX log parsed with 0 messages.
- Toolchain step 2: dvipdfmx, -p "182mm,257mm",rireki.dvi
- Toolchain returns with error: 1/null.

</details>

**Comment by James-Yu** [comment]
It seems that you put `-p` and `"182mm,257mm"` in the same line. Try split it into two arguments.

**Comment by silenfoot** [comment]
That does indeed work. I presumed that since the dimensions were an argument for the `-p` flag that they should be included in the same element of `args`.
