### ISSUE TITLE
Autocomplete for commands created with \def

### ISSUE THREAD

**Issue by jharbig** [James-Yu/LaTeX-Workshop#4421]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

When you create commands with `\def` there are no autocompletion suggestions. 

I created the following minimal example to demonstrate this:
```
\documentclass{article}

\newcommand{\autocompletedCommand}{Autocomplete works for this command}
\def\notAutocompleted{This command will not be auto completed}

\begin{document}

\autocompletedCommand
\notAutocompleted
\notAutocompleted{}
\notAutocompleted{}{}

Autocomplete not even works after a few usages
\notAutocompl

\end{document}
```
As you can see in the following image, there are no suggestions.

![image](https://github.com/user-attachments/assets/bb6dc642-7afa-4a1d-a8fe-91ddcdc0cea6)

## The Solution*
> _Please provide a solution you would like to have._

It would be nice to have autocompletion similar to commands created with `newcommand`. 

![image](https://github.com/user-attachments/assets/80fc042c-9846-41e2-becc-ccd4c8171204)

I also suggest including the non-letter character after the command in the suggestion because LaTeX requires this character in the usage (e.g. `\def\myCommand/{something}` can only be used `\myCommand/). So, in effect, this character is part of the command (more details below). 

If it is complicated to include a command from \def, it would be helpful when the autocompletion suggests commands that were used before.

## Anything Else?
> _Add any other context about the feature request below._

I considered refactoring all my commands from \def to \newcommand. Unfortunately, there is a different behavior, especially with a space after a command. I usually define commands with a slash afterward (e.g., `\def\myCommand/{something}` such that you do not forget to add a space after a command. See https://tex.stackexchange.com/questions/31091/space-after-latex-commands or page 204 of "The TEXbook" for more info on that behavior/problem.

**Comment by James-Yu** [comment]
The extension does not parse `\def`. You may consider report the issue to `unified-latex` as this extension relies on that package to parse LaTeX.

Generally, `\def` is anti-pattern.

Further, we won't parse randomly appeared macros in the document, as it can be to convolute to parse its argument signature.
