### ISSUE TITLE
White borders (margin, gap, space) occur on the bottom and the right side of pages in the internal PDF viewer when dark background is enabled

### ISSUE THREAD

**Issue by ghake** [James-Yu/LaTeX-Workshop#4431]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: MacOs
- Visual Studio Code Version: 1.94.2
- LaTeX Workshop Version: v10.5.0

## The Issue*
> _Please briefly describe the issue you come across._
- [This pdf.js bug](https://github.com/mozilla/pdf.js/issues/18694) occurs with the pdf-preview with latex-workshop settings 

```
"latex-workshop.view.pdf.color.dark.pageColorsBackground": "#253237",
"latex-workshop.view.pdf.color.dark.pageColorsForeground": "lightgrey",
"latex-workshop.view.pdf.color.dark.backgroundColor": "#253237",
"latex-workshop.view.pdf.color.dark.pageBorderColor": "#253237",
```

It is supposed to look like [this](https://tex.stackexchange.com/a/723436):

![grafik](https://github.com/user-attachments/assets/16455030-18a8-4a06-bc7d-8c9f941997d3)

But instead white borders (margin,gap,space) occur on the bottom and the right side of the pages and it looks like this :

<img width="1440" alt="Bildschirmfoto 2024-10-12 um 09 08 17" src="https://github.com/user-attachments/assets/9d96bded-155c-43b0-b1da-8d9fe501c83d">

I guess it's [this pdf.js bug](https://github.com/mozilla/pdf.js/issues/18694) .

**Comment by James-Yu** [comment]
Yes, that's an upstream issue. Will update to latest.
