### ISSUE TITLE
Warning: command 'latex-workshop.build' not found

### ISSUE THREAD

**Issue by Windzard** [James-Yu/LaTeX-Workshop#444]
### Description
About two weeks before, LaTeX-Workshop worked perfectly well on my computer, but today when I hit ctrl + alt +b, vs code pops up a warning says: "command 'latex-workshop.build' not found". I am sure that I havn't change anything since my last use. I have TeX Live, and the path is well set. My toolchain is like this:
    "latex-workshop.latex.toolchain": [
        {
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }, {
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }, {
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        }, {
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
    ]
Is there anything else I can post to make this issue clear?

**Comment by James-Yu** [comment]
Obviously the extension is not activated. You may want to double check if the extension is enabled. If so, it is a vscode problem. You *may* find some clue from the developer console which can be found in Help menu.

**Comment by xiaoFine** [comment]
@James-Yu  I have the same problem but with MikTex.
When I open the vs code with Latex-workshop installed, I'm warned that 'Cannot find module 'opn'.
![image](https://user-images.githubusercontent.com/12167470/36946290-a9b03cd8-1ff5-11e8-8b74-f6c2aed4dcb9.png)
There is no response when I click 'Build' option or hit ctr+alt+B.
I re-installed vs code of version 1.19.2 and then updated to the latest version, the problem remains in both.
You'are welcomed to ask for more information.
