### ISSUE TITLE
Adding IntelliSense data for duplicate packages will not receive suggestions for the original package

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [James-Yu/LaTeX-Workshop#4440]
## Pre-checks

- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment

- Windows 11
- Visual Studio Code Version:
    ```
    Version: 1.93.1 (user setup)
    Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
    Date: 2024-09-11T17:20:05.685Z
    Electron: 30.4.0
    ElectronBuildId: 10073054
    Chromium: 124.0.6367.243
    Node.js: 20.15.1
    V8: 12.4.254.20-electron.0
    OS: Windows_NT x64 10.0.22631
    ```
- LaTeX Workshop Version: 10.5.3
- TeX Live 2024

## The Issue

When I add <samp>[dev/packages/][]</samp> to `latex-workshop.intellisense.package.dirs` will not accept intellisense from package expl3.

[dev/packages/]: https://github.com/James-Yu/LaTeX-Workshop/tree/master/dev/packages "LaTeX-Workshop/dev/packages at master · James-Yu/LaTeX-Workshop"

### Reproduction Steps

1. Put <samp>dev/packages/</samp> locally
1. Specify the directory <samp>dev/packages/</samp> in `latex-workshop.intellisense.package.dirs`
1. Create a TeX file and enter `\usepackage{expl3}`
1. Typing `\int_new` etc. does not show suggestions

### Expected Behavior

I would like to be able to get expl3 suggestions as well as when <samp>dev/packages/</samp> is not placed locally

## Anything Else?

[dev/packages/expl3.json][dev-expl3] and [data/packages/expl3.json][data-expl3] have different content.

[dev-expl3]: https://github.com/James-Yu/LaTeX-Workshop/blob/master/dev/packages/expl3.json "LaTeX-Workshop/dev/packages/expl3.json at master · James-Yu/LaTeX-Workshop"
[data-expl3]: https://github.com/James-Yu/LaTeX-Workshop/blob/master/data/packages/expl3.json "LaTeX-Workshop/data/packages/expl3.json at master · James-Yu/LaTeX-Workshop"

I am only focusing on expl3 here, but there may be other packages with similar symptoms.

**Comment by James-Yu** [comment]
It works as expected: a custom package .json supersedes the bundled one.

I'll remove the dev/ version of expl3.json though.
