### ISSUE TITLE
jump to bibtex entry from \cite{key}

### ISSUE THREAD

**Issue by v4hn** [James-Yu/LaTeX-Workshop#4445]
## Pre-checks*
- [x] The feature request has not been suggested in this repository. (to the best of my meager lookup skills)

## The request

As someone migrating to vscode from texstudio for writing latex, I expected that `<Ctrl>+<Left Click>` on the argument of `\cite{bibkey}` would jump to the bibentry of `bibkey` in the `bib` file. The same mechnism *does* work for `\ref`/`\autoref` and I use it a lot.

**Comment by jlelong** [comment]
It actually works as you describe it. 
If you experiment some issues, please post the logs. There is most likely a problem with the detection of the `.bib` file.
