### ISSUE TITLE
\ref link highlighting breaks at some valid characters

### ISSUE THREAD

**Issue by v4hn** [James-Yu/LaTeX-Workshop#4446]
## Pre-checks*
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Debian Trixie
- Visual Studio Code Version: 1.94.2
- LaTeX Workshop Version: 10.5.5
- TeX Distribution Version: texlive 2024

## The Issue*

The link highlighting for references that include `:` or `-` (and possibly other valid characters) ends at these characters, but still links to the correct label. Screenshots to illustrate the issue:
![screenshot241024-155558](https://github.com/user-attachments/assets/1e46cf70-4907-4e15-955d-8ce2f28b0c8c)
[Holding `<Ctrl>` and hovering over a part of the ref argument]
![screenshot241024-155632](https://github.com/user-attachments/assets/2b7a23a5-d1a8-444c-a3ca-d1e7f780434b)

### Reproduction Steps

1. create a latex file with a label like `\label{a:b-c}` and a reference to it `\ref{a:b-c}`
2. build the file
3. hold `<Ctrl>` and hover over any of the letters of the argument to `\ref`
4. only part of the argument turns into a link

### Expected Behavior

- The whole argument should turn into a (usually blue and underlined) link

**Comment by jlelong** [comment]
Related to #3312 
See in particular this specific https://github.com/James-Yu/LaTeX-Workshop/issues/3312#issuecomment-1139740611
