### ISSUE TITLE
Use less aggressive font hinting in pdf viewer

### ISSUE THREAD

**Issue by nlgranger** [James-Yu/LaTeX-Workshop#445]
First: thanks for this awesome project!

### Description

The pdf previewer uses some aggressive font hinting which makes small fonts hard to read on screen with average resolution/dpi.

### How to reproduce

generate any text to preview, zoom out

### Expected behavior

Readable text (from evince on linux at a similar zoom level):

![screen2](https://user-images.githubusercontent.com/3764009/36800689-6c1f8704-1cb0-11e8-970a-d9483155e82c.png)

### Actual behavior

Thinner character part like the horizontal bar of the e are gone:

![screen](https://user-images.githubusercontent.com/3764009/36800725-822db39a-1cb0-11e8-9c0b-683ea15a7a7c.png)

**Comment by James-Yu** [comment]
This is an upstream pdf.js issue.
