### ISSUE TITLE
Jobname setting got deleted in JSON settings

### ISSUE THREAD

**Issue by thirschbuechler** [James-Yu/LaTeX-Workshop#4450]
## Pre-checks
- [x] The issue has not been reported in this repository.
- [n/a] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [n/a] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment
Vscode 1.94.2-1728494015 from Microsoft PPA (Ubuntu)
pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024) from tug.org

## The Issue

The jobname setting (to compile multiple `tex` files in a folder into one `pdf`, regardless of which one is open) seemingly stopped working when working with or updating to `10.5.5` _and got auto-deleted_, re-adding the line in the workspace`JSON` and rolling back to `10.5.4` fixed it.

## Why are two pre-checks missing

- Because recreating the jobname setting alone didn't fix it at first, but the additional rollback did, I assume that other extensions do not cause an issue here. Each time I ran `rm -f *.aux *.bbl *.bcf *.blg *.log *.out *.run.xml *.toc *.lof *.lot *.fls *.fdb_latexmk *.synctex.gz *.nav *.snm *.vrb *.xdv` manually before compiling (in my tex folder) to delete cached files.

- As the jobname-setting is a way to circumvent adding it as command-line parameter, testing it without latex-workshop and Vscode is not applicable. Everything works with the older extension version, so `pdflatex`, `latexmk` etc. seem to work fine.

## Why no compiler-log
When trying to reproduce the issue by upgrading to `10.5.5` again it was not reproducable. Maybe the `unsupported` tagging in the  `JSON` is the issue, and Vscode garbage-collected it?

## Further Info
The jobname setting line is marked as `unsupported property` (and greyed out) by the settings-linter in the workspace `JSON`, but worked the last few weeks (auto-updated latex-workshop). The [wiki](https://github.com/james-yu/latex-workshop/wiki/compile) has it as not depreciated. Other `latex-workshop.latex.tools` settings are not marked this way.
 
[user-config.json](https://github.com/user-attachments/files/17539943/userconfig.json)
[workspace-config.json](https://github.com/user-attachments/files/17540569/workspaceconfig.json)
![unsupported_property](https://github.com/user-attachments/assets/81d4eac7-d83c-41b4-92f0-abe1e874f906)

**Comment by James-Yu** [comment]
Thanks for your report. I appreciate your very detailed explanation.

However, this extension does not change anything in your config JSON file. Nor has it touched the related config in the past a few months. You can still see it here: https://github.com/James-Yu/LaTeX-Workshop/blob/668b3cf48ab9c41ea6bb005f3b0bad70066df92f/package.json#L1103-L1108

As long as the line is here, vscode should not mark the config as unsupported. Unless you may discover reliable reproduction steps, we cannot identify it’s whose responsibility (highly unlikely ours).
