### ISSUE TITLE
Add Hover Preview Support for \includesvg

### ISSUE THREAD

**Issue by Chelocad** [James-Yu/LaTeX-Workshop#4451]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- The LaTeX extension does not provide a hover preview for SVG files when using \includesvg{}. This limits the ability to visualize graphics, unlike \includegraphics{}, which shows previews for PNG files.

## The Solution*
> _Please provide a solution you would like to have._
- Implement a hover preview for SVG files. The generated PDF from the SVG can be used to display a preview when the mouse hovers over the \includesvg{} command.

## Anything Else?
> _Add any other context about the feature request below._
- Adding this feature will improve the user experience and make it easier to work with SVG graphics in LaTeX documents.

**Comment by James-Yu** [comment]
Thank you for your request. Unfortunately, vscodes' hover hint cannot show svg file, and converting svg to png is way too heavy for this extension. The feature cannot be implemented.
