### ISSUE TITLE
Cleanup post error

### ISSUE THREAD

**Issue by hsmyers** [James-Yu/LaTeX-Workshop#4452]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- 

## The Solution*
> _Please provide a solution you would like to have._
- Remove the remaining error popup after an error has been fixed.

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
Compile again.

**Comment by hsmyers** [comment]
It remains until dismissed.

**Comment by James-Yu** [comment]
That’s a limit by vscode.
