### ISSUE TITLE
Autocomplete `fontawesome5` values

### ISSUE THREAD

**Issue by AndreVale69** [James-Yu/LaTeX-Workshop#4454]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Although I insert `\usepackage{fontawesome5}` ([package info](https://ctan.org/pkg/fontawesome5)), I didn't see any of the command of this package, such as `\faIcon{}`. Furthermore, when I'm inside the scope of the `faIcon` command, I can't have any suggestion about what value I can insert. I leave a very short video to understand what I mean: [video.webm](https://github.com/user-attachments/assets/45591f7d-efa5-446b-a067-14d46c4c0b37).

## The Solution*
> _Please provide a solution you would like to have._
- I think it might be helpful to have suggestions within the faIcon scope. I leave an example video: [video-2.webm](https://github.com/user-attachments/assets/02735fc9-d0e4-41df-9ffd-fa6e5d08ca87)

## Anything Else?
> _Add any other context about the feature request below._
- I don't know if it requires a lot of work or if it's possible, but I think it can be helpful. Thanks as always for your great work on this extension.

**Comment by James-Yu** [comment]
We generate suggestions from https://github.com/texstudio-org/texstudio/tree/master/completion .
