### ISSUE TITLE
My Snippents in LaTeX Files doesn't work?

### ISSUE THREAD

**Issue by Explorer-cc** [James-Yu/LaTeX-Workshop#4455]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: windows 11 professional
- Visual Studio Code Version: 1.88.0
- LaTeX Workshop Version: v10.5.6
- TeX Distribution Version: TeXLive2024

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> As I have configured the snippets in `latex.json` file as below:
```json
	"replace ￥￥": {
		"prefix": "￥￥",
		"body": [
		  "$$"
		],
		"description": "replace ￥￥"
	},
	"fraction": {
		"prefix": "fr",
		"body": [
			"\\frac{$1}{$2} ",
		 ],
		 "description": "fraction"
	}, 
	 "partial fraction": {
		"prefix": "pf",
		"body": [
			"\\frac{\\partial $1}{\\partial $2} $3",
		 ],
		 "description": "partial fraction"
	}, 
```
As my video as below, the `latter TWO` worked but the `￥￥` can't...... While in my another computer it worked, I got very confusing about that.

## Anything Else?

https://github.com/user-attachments/assets/1cc3ac00-f357-4216-99a9-807462b9ebe1

**Comment by James-Yu** [comment]
It’s not related to this extension. Please report to vscode repo.
