### ISSUE TITLE
Compiling files with extensions other than `.tex`

### ISSUE THREAD

**Issue by zhengxinhao-comp** [James-Yu/LaTeX-Workshop#4457]
## Environment
- Operating System: Windows 11
- Visual Studio Code Version: 1.95.2
- LaTeX Workshop Version: 10.5.6
- TeX Distribution Version: TeX Live 2024

## The Issue
LaTeX Workshop refuses to compile source file with file extension other than `.tex`.

### Reproduction Steps
I use a music typesetter called [LilyPond](https://lilypond.org/). The way it corporates with LaTeX is that I input the LaTeX source code with LilyPond code in the environment `\begin{lilypond}` `\end{lilypond}`, and save the file with the extension `.lytex`, and use the command `lilypond-book` to compile it. `lilypond-book` would compile the `.lytex` file to a `.tex` file, then the user can use a regular LaTeX command to compile the intermediate file to PDF.

I've set the following tool
```json
        {
            "name": "lilypond-book",
            "command": "lilypond-book",
            "args": [
                "%DOC_EXT%"
            ],
            "env": {}
        }
```
and recipe
```json
        {
            "name": "Compile lytex",
            "tools": [
                "lilypond-book",
                "xelatexmk"
            ]
        }
```
to automate the task but I can't get the compilation running when I click the recipe in LaTeX panel.

### Expected Behavior
LaTeX Workshop should be able to compile source file with extensions other than ".tex". I don't know if it's possible, or it would be better to have an option in the settings defining file extensions LaTeX Workshop recognizes and is able to compile.

**Comment by James-Yu** [comment]
Compiling files other than `tex` is out of scope of this extension. You may resort to vscode tasks for the job.

**Comment by jlelong** [comment]
It reminds me of what I implemented to support literate programming for the R and Julia languages. 
@James-Yu If you are fine with it, I can try to make a PR to support to `.lytex`. From my point of view, it is not so much a matter of compiling the file as there are alternative approaches but rather to make other features such as intellisense work.

The first step is to closely look at the structure of a `.lytex` file to determine if it is feasible with little modification. @zhengxinhao-comp could you provide a representative example of such a file?

**Comment by zhengxinhao-comp** [comment]
> It reminds me of what I implemented to support literate programming for the R and Julia languages. @James-Yu If you are fine with it, I can try to make a PR to support to `.lytex`. From my point of view, it is not so much a matter of compiling the file as there are alternative approaches but rather to make other features such as intellisense work.
> 
> The first step is to closely look at the structure of a `.lytex` file to determine if it is feasible with little modification. @zhengxinhao-comp could you provide a representative example of such a file?

Thanks! `.lytex` works pretty much like a regular LaTeX package but it uses an external program to typeset music notation. Here is an example:
```latex
\documentclass{article}
\begin{document}
Here is an excerpt of using LilyPond with \LaTeX :

\begin{lilypond}
% Here goes the LilyPond code
\relative c' { c c g' g | a a g2 | f4 f e e | d d c2 \bar "||" }
\end{lilypond}
\end{document}
```
Save the file to `example.lytex` and run `lilypond-book example.lytex`, it will generate `example.tex` with the following code:
```latex
\documentclass{article}
\usepackage{graphics}
\begin{document}
Here is an excerpt of using LilyPond with \LaTeX :

{%
\parindent 0pt
\noindent
\ifx\preLilyPondExample \undefined
\else
  \expandafter\preLilyPondExample
\fi
\def\lilypondbook{}%
\input{f2/lily-477c6dad-systems.tex}%
\ifx\postLilyPondExample \undefined
\else
  \expandafter\postLilyPondExample
\fi
}
\end{document}
```
and a bunch of other files, which include an `.eps` file which contains the music excerpt. Then I can just run `xelatex example.tex` to get the result PDF:

**Comment by jlelong** [comment]
@zhengxinhao-comp Just a gentle reminder. What kind of syntax highlighting would you expect for  `lylipond` environments?

**Comment by jlelong** [comment]
I am closing the issue as there has been no response.
