### ISSUE TITLE
Alt-click on Preview to open the preview not to the side

### ISSUE THREAD

**Issue by scoskey** [James-Yu/LaTeX-Workshop#4458]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository. (I hope)

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When writing markdown you can preview in a new tab to the side, or alt-click (option-click) to preview in a new tab in the same tab group as the current one.

## The Solution*
> _Please provide a solution you would like to have._
- Add the same functionality for previewing latex.

## Anything Else?
> _Add any other context about the feature request below._
- I hope this is clear, sensible, and easy to do :)

**Comment by jlelong** [comment]
Have you checked https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdftabeditorgroup ?

**Comment by scoskey** [comment]
No I had not thank you! I think it would be nice to have two options (click and meta-click), like with markdown. I personally like to use both "right" and "current" in different moments. I suppose if there were two options, they could both could be configured in such a fashion.

**Comment by jlelong** [comment]
We will think of it. In the meantime, you can always drag and drop the viewer tab at an other position or configure `latex-workshop.view.pdf.tab.editorGroup` on a a project basis

**Comment by scoskey** [comment]
No worries, that is understandable!
