### ISSUE TITLE
There were undefined citations error

### ISSUE THREAD

**Issue by Rasul-Esmaeilbeigi** [James-Yu/LaTeX-Workshop#446]
When I use Texstudio, the attached latex project compiles very well. With LaTeX Workshop there a problem with citations.

[Test.zip](https://github.com/James-Yu/LaTeX-Workshop/files/1773238/Test.zip)

**Comment by James-Yu** [comment]
Line 455 of your bib file is not closed by `,`.

**Comment by Rasul-Esmaeilbeigi** [comment]
Thanks James,

I'm Just curious. How did you find the issue so quickly?

**Comment by James-Yu** [comment]
The compiler log says so.
