### ISSUE TITLE
Add simple pdflatex recipe as default

### ISSUE THREAD

**Issue by kjshen** [James-Yu/LaTeX-Workshop#4462]
## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

I couldn't find any discussions on why the default compiler is `latexmk`, but I feel like changing it might make it easier for some people to get started with VSCode + LaTeX workshop.
## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

I always recommend people to use VSCode with this extension for their LaTeX work.
However, in my experience, often times people are hesitant to additionally install perl for `latexmk`, especially first time LaTeX users.
Which is totally fine and works, however, this requires the user to do a little more set up work:
The user has to change the default recipe, which is set to `first` and thereby `latexmk`.
Furthermore, there is no simple `pdflatex` recipe but only the `pdflatex -> bibtex -> pdflatex*2` recipe, which will result in errors or warnings depending on the document of the user.
So the user has to manually add a `pdflatex` recipe and put it as the first recipe, which - depending on the user - might require support.

## The Solution*
> _Please provide a solution you would like to have._

Therefore, I'd like to suggest to add a simple `pdflatex` recipe as the default recipe.
I'd also add simple `bibtex` and `biber` recipes by default so that the user can click them.

**Comment by James-Yu** [comment]
It has been discussed before. We won't change that.

**Comment by kjshen** [comment]
Okay I see. What is your stance on adding simple `pdflatex` and `bibtex`/`biber` recipes by default?

**Comment by James-Yu** [comment]
I'm against the change: the default has been there for almost ten years. Changing that may lead to many angry users not knowing why their workflow no longer works. Regarding the gain, I don't think the change is worth.

**Comment by kjshen** [comment]
Oh no, I didn't make clear what I mean. 
These are the default recipes after a fresh installation:
![LaTeXworkshopdefaults](https://github.com/user-attachments/assets/434d578d-6037-4be9-9f9b-03880af5c67f)

How do you feel about adding just a simple recipe that only does `pdflatex`? So that new users without perl have the option to just click the `pdflatex` recipe instead of having to use `pdflatex -> bibtex -> pdflatex*2` or having to adjust the settings themselvs.

**Comment by James-Yu** [comment]
That's minimal. I'm happy to review a PR on that.
