### ISSUE TITLE
After updating to `v10.6.0`, some images shown as black boxes when open with internal pdf viewer

### ISSUE THREAD

**Issue by mooxiu** [James-Yu/LaTeX-Workshop#4468]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: macOS Sequoia 15.1.1 arm64
- Visual Studio Code Version: Version: 1.95.3 (Universal)
- LaTeX Workshop Version: v10.6.0
- TeX Distribution Version: TeX 3.141592653 (TeX Live 2024) 

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- The pdf is compiled normal (confirmed by opening the pdf with other software), just when opening with the internal pdf viewer, some of the images are shown as black boxes (the sizes of the black boxes are correct).
- If I downgrade to previous version (v10.5.6), and open the pdf again, images can be shown correctly.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Double click the compiled pdf file in vscode
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- Images should be shown correctly
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
19:51:13.968][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:54502/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRlVzZXJzJTJGbXV5YW9oc2lhbyUyRkRvY3VtZW50cyUyRndvcmtzcGFjZSUyRmxhdGV4X25vdGVzJTJGTUlUXzE4LjQwNEpfdGhlb3J5X29mX2NvbXB1dGF0aW9uJTJGbWFpbi5wZGY .
[19:51:13.969][Cacher][Watcher] Watched file://%WS1%/main.pdf by the .pdf watcher.
[19:51:13.969][Event] FILE_WATCHED: "file://%WS1%/main.pdf"
[19:51:14.106][Viewer] Handle data type: open
[19:51:14.138][Server] Preview PDF file: file://%WS1%/main.pdf
[19:51:14.182][Viewer] Handle data type: loaded
[19:51:14.182][Event] VIEWER_PAGE_LOADED
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
- This is what it looks like
![Xnip2024-11-25_19-41-40](https://github.com/user-attachments/assets/6502ced7-af63-4fba-84f6-783e5cb22902)

**Comment by James-Yu** [comment]
Please provide an example PDF.

**Comment by mooxiu** [comment]
[main.pdf](https://github.com/user-attachments/files/17901828/main.pdf)

Please refer to the last page of the pdf.

This is what I see when opening with v10.6.0:
<img width="774" alt="image" src="https://github.com/user-attachments/assets/47bf3a7c-3fec-4456-b796-dc4ca58ddf71">

**Comment by James-Yu** [comment]
I've confirmed this is an upstream issue with v4.8.69 of https://github.com/mozilla/pdf.js . Please report there to ask for a fix. We cannot fix the issue on our side.

**Comment by mooxiu** [comment]
thanks for confirming

**Comment by James-Yu** [comment]
This problem should be fixed with the latest version of LaTeX Workshop, with the updated PDF.js.
