### ISSUE TITLE
Feature Request / Guidance on Adding RTL Support and Custom LaTeX Command Conversion

### ISSUE THREAD

**Issue by Imanparast** [James-Yu/LaTeX-Workshop#4471]
Dear LaTeX Workshop Development Team,

I hope this message finds you well.

I am reaching out to inquire if it would be possible to add a feature or provide guidance on how I could implement the following custom functionality in LaTeX Workshop for Visual Studio Code:

Automatic Conversion of Custom Commands (like Persian Math Equations):
I would like to create a feature where Persian or custom commands (e.g., /شروع{معادله} and /پایان{معادله}) in the editor automatically get converted to the corresponding LaTeX commands (\begin{equation} and \end{equation}). This would allow for a more seamless experience when writing LaTeX documents with Persian mathematical expressions. If this functionality is not currently supported, I would appreciate any advice or steps on how I might be able to implement this myself within the extension.

I would like to create a feature where Persian or custom commands (e.g., /شروع{معادله} and /پایان{معادله}) in the editor automatically get converted to the corresponding LaTeX commands (\begin{equation} and \end{equation}). This would allow for a more seamless experience when writing LaTeX documents with Persian mathematical expressions. If this functionality is not currently supported, I would appreciate any advice or steps on how I might be able to implement this myself within the extension.
Right-to-Left (RTL) Text Support:
Another aspect I am interested in is enabling right-to-left (RTL) writing support in LaTeX Workshop, particularly for Persian text. While I understand that LaTeX itself can handle RTL text using specific packages (like bidi or polyglossia), I am curious if there are any settings, plugins, or workarounds within VS Code and LaTeX Workshop that could facilitate smoother editing and rendering of RTL content directly in the editor. Any guidance or pointers on enabling this feature would be greatly appreciated.

I am aware that implementing customizations to such an advanced tool may require careful consideration of the extension’s codebase. If you could point me to relevant parts of the code or provide any suggestions, that would be extremely helpful.

Thank you very much for your time and for the incredible work you are doing with LaTeX Workshop. I look forward to your response.

Best regards,

**Comment by James-Yu** [comment]
Thank you for your FR. As far as I am concerned, your first request can be implemented using custom snippets. The second is a vscode issue.

Please kindly note that the extension aims at providing standard LaTeX functions. As I cannot read Persian or use Persian to write LaTeX, I have no sufficient knowledge on whether `/{شروع{معادله` is a standard way of writing LaTeX equations (seems not though).

**Comment by Imanparast** [comment]
Thank you for your response.

As you know, languages like Arabic and Persian are written from right to
left. In LaTeX scripting, languages that are written from left to right,
like English, do not pose any issues. However, for Persian, this creates
challenges.

I should also mention that LaTeX supports languages like Arabic and
Persian. However, the script must be written from left to right, and
Persian or Arabic text should also be treated from left to right, which
makes it difficult.

I am looking for a way to make LaTeX scripts compatible with the
right-to-left writing direction of Persian and Arabic.

For example, consider the prototype image below:

[image: image.png]

In the right image, the LaTeX keyword equivalents are shown.

I don’t have sufficient knowledge of extension scripting, so I wanted to
ask for your guidance on the following:

1) How can I add code to the LaTeX WorkShop extension that can translate
these Persian or Arabic equivalents into standard LaTeX scripts before
running the LaTeX compiler, without changing the script file? In other
words, I don’t want the Persian script file (i.e., the right image) to be
changed like a find and replace. Instead, I want the extension to handle
this and send the result to the compiler.

2) How can I write text from right to left in the VS Code environment? Or
how can I change the text direction wherever necessary? Like in MS Word,
where the text direction can be changed with Ctrl+Shift to the right or
left.

Than you very much

**Comment by James-Yu** [comment]
1. It’s not possible. Not the way this extension works.
2. It’s a vscode question.
