### ISSUE TITLE
`latex-workshop.intellisense.argumentHint.enabled` defaults to `true` but documented as `false`

### ISSUE THREAD

**Issue by muzimuzhi** [James-Yu/LaTeX-Workshop#4477]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: macOS 14.7.1
- Visual Studio Code Version: 1.95.3
- LaTeX Workshop Version: 10.7.0
- TeX Distribution Version: basicTeX 2024

## The Issue*
> _Please briefly describe the issue you come across._

In the code, `latex-workshop.intellisense.argumentHint.enabled` defaults to `true` (from day one, see https://github.com/James-Yu/LaTeX-Workshop/commit/f44c23e1e3e4ce595b3ecdb973c7518f50621e46) but it's documented as defaulting to `false`.

https://github.com/James-Yu/LaTeX-Workshop/blob/39e25b9a7b4b52d13fbda61e02c6f2056f02a70f/package.json#L2385-L2390

- link to current wiki
  https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense#latex-workshopintellisensecitationtype
- permalink in jlelong/LaTeX-Workshop-wiki
  https://github.com/jlelong/LaTeX-Workshop-wiki/blob/b79d769675c9654e5d71fb55eea2918284218f66/Intellisense.md?plain=1#L275-L283

**Comment by jlelong** [comment]
Thanks a lot.
Closed by https://github.com/jlelong/LaTeX-Workshop-wiki/commit/9cf4a789dafba06dc01f864517c1f502a8250918.

**Comment by muzimuzhi** [comment]
Thanks for the quick response and fix.

BTW I've checked all the boolean configs and this was the only one used to have inconsistent default values.

After merging of all of
- https://github.com/jlelong/LaTeX-Workshop-wiki/pull/122
- https://github.com/jlelong/LaTeX-Workshop-wiki/pull/123
- https://github.com/jlelong/LaTeX-Workshop-wiki/pull/124

all boolean configs should be mentioned at least once in the wiki, either in their dedicated sections, in general descriptions, or in the FAQ page.
