### ISSUE TITLE
Intellisense completions of LaTeX3 interfaces provided by LaTeX2e 

### ISSUE THREAD

**Issue by muzimuzhi** [James-Yu/LaTeX-Workshop#4478]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._

In LaTeX2e, recently added modules are written in LaTeX3/expl3, which then may provide both traditional LaTeX2e-style user interfaces and the LaTeX3-style ones. For example, the hook management module provides both
```tex
\AddToHook[<label>]{<hook>}{<code>}
% and
\hook_gput_code:nnn {<hook>} {<label>} {<code>}
```
(see docs `texdoc lthooks-doc` and `texdoc lthooks-code`).

Currently only the LaTeX2e-style interfaces have Intellisense completions, but not the LaTeX3-style ones.

## The Solution*
> _Please provide a solution you would like to have._

I've tried something in [`muzimuzhi/James-Yu:feat/latex2e-expl3-entries`](https://github.com/muzimuzhi/LaTeX-Workshop/tree/feat/latex2e-expl3-entries), by extending `dev/latex3command.py` and `parse-cwl.ts`:
```
LaTeX2e dtx files -> latex2e-expl3.cwl -> latex2e-expl3.json
```

But I know nothing about how the `data/package/*.json` are bundled in the extension and when the completions entries in them are enabled.

## Anything Else?
> _Add any other context about the feature request below._

In general, not only the LaTeX kernel, but also any packages and classes may provide public and documented LaTeX3 functions and variables. For instance, `fontspec` package provides `\fontspec_font_if_exist:nTF` and several more, see sec. VIII.5 "Programming interface" in its doc.

It needs to be decided whether to record LaTeX3 entries in the same `<package>.json` along with the existing LaTeX2e ones and only show them in completion list when in LaTeX3 coding style, or to record them in separate files, for example `<package>.expl3.json` (less likely to encounter naming clashes) or `<package>-expl3.json`.

Ideally auto-completion for LaTeX3-style functions should provide corresponding argument descriptions too, but currently that's missing from TeXstudio cwl files. Maybe there was a feature request for that in TeXstudio, but I cannot find it for now.

Cc @mbertucci47

**Comment by mbertucci47** [comment]
@muzimuzhi I opened https://github.com/texstudio-org/texstudio/issues/3896. If that is added then I can make the cwl with arguments.

**Comment by James-Yu** [comment]
Resolved in #4476? Correct me if I'm wrong.

**Comment by muzimuzhi** [comment]
@James-Yu Nope. #4476 updates the completions for `l3kernel` functions and variables, documented in `texdoc interface3.pdf` (or just `texdoc l3`), while this issue is about adding completions for functions and variables that i) follow LaTeX3/expl3 naming scheme and ii) are provided out side of the `l3kernel`.

For instance `l3kernel` provides `\tl_new:N`, the LaTeX2e [base](https://github.com/latex3/latex2e/tree/develop/base) provides `\hook_new:n`, and package `fontspec` provides `\fontspec_font_if_exist:nTF`. Currently LaTeX-Workshop only have completions for the first kind of names.

**Comment by James-Yu** [comment]
I see. There is no plan to parse dtx files of latex2e packages for macro definitions. We will stick to the cwl solution.
