### ISSUE TITLE
\cite{} and \bibliography{} doesn't work?

### ISSUE THREAD

**Issue by bluepi0j** [James-Yu/LaTeX-Workshop#448]
I tried to compile my essay,` \cite{}` and` \bibliography{}` doesn't work (it will create the pdf, but cite and bib content doesn't show up). It worked before Feb, So I guess it's the  `2018-02-22 update` break it.

I used this APA style reference template. I tried to compile it, it do nothing, even doesn't create the pdf.
https://cn.sharelatex.com/templates/journals/apa

**Comment by James-Yu** [comment]
In the update, the toolchain is not changed. I figure the problem is not related to the extension.
