### ISSUE TITLE
tex-fmt: option `--keep` changed to `--nowrap`

### ISSUE THREAD

**Issue by WGUNDERWOOD** [James-Yu/LaTeX-Workshop#4483]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ ] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [e.g. Windows 10]
- Visual Studio Code Version: [e.g. 1.41.0]
- LaTeX Workshop Version: [e.g. 8.5.0]
- TeX Distribution Version: [e.g. TeX Live 2019 / MiKTeX 2.9.7250]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
- 
- 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. 
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- 
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by WGUNDERWOOD** [comment]
Just letting you know that this flag has changed for v0.5.0.

**Comment by flaribbit** [comment]
encountered `tex-fmt returned 2 . Be cautious on the edits.` after upgrading tex-fmt to v0.5.0, seems that this is the reason

![image](https://github.com/user-attachments/assets/1b4e15be-9581-49e8-9df9-e4a5479ca569)

![image](https://github.com/user-attachments/assets/f6dc4678-10e6-4180-9158-bd2f8241f15d)
