### ISSUE TITLE
 Disable or add a way to customize the PDF.js keybindings

### ISSUE THREAD

**Issue by Sakarah** [James-Yu/LaTeX-Workshop#4484]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- Currently, PDF.js registers a lot of keybindings as stated on the page https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts. Those keybindings are effective for internal viewer tabs but they do not appear in the list of VSCode keybindings, and thus cannot be customized. This can be very annoying because these keybindings may conflict with others bindings, and some of them are redundant with existing VSCode features.
For my personal use case, the `Ctrl+O` keybinding for `Open a file` is a real issue since I use Vim keybindings and `Ctrl+O` is normally bound to `Jump to previous location`.

## The Solution*
> _Please provide a solution you would like to have._
- An easy intermediate solution for my particular use case would be to completely remove keybindings that are already covered by VSCode features. Such keybindings are the download document (Ctrl+S) and the open file (Ctrl+O) bindings.
- To handle all possible keybinding conflicts, it would be great to allow the customization of all keybindings of PDF.js in the standard VSCode `keybindings.json`.

## Anything Else?
> _Add any other context about the feature request below._
- The two solutions I have listed are not mutually exclusive because it will never make sense to create another way of opening or saving a pdf file than what VSCode already provides.

**Comment by James-Yu** [comment]
This is the best thing we can do. As keybindings of viewer are hard coded, it's almost impossible to customize them by vscode settings.
