### ISSUE TITLE
Latex workshop with CHK-TEX 

### ISSUE THREAD

**Issue by TexLayer** [James-Yu/LaTeX-Workshop#4487]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
Windows 11 24H2 
Visual Studio Code Version: 1.95.3
LaTeX Workshop Version: 10.7.0
TeX Distribution Version:MiKTeX 24.1
ChkTeX 1.7.8 (latest is 1.7.9, however 1.7.8 is distributed with miktex currently)

## The Issue*
While using Chk-Tex as linter with Latex Workshop the VSCode reports "information message" level errors as "warnings".

### Reproduction Steps
In settings.json set:
    "latex-workshop.linting.chktex.enabled": true,
    "latex-workshop.linting.chktex.exec.args": [
        "-mall", // report all errors as messages
    ]

Using MWE such as below, chech the error messages reported at VSCode output.
    \documentclass[11pt]{article}
    \begin{document}
    \begin{enumerate}} %<-- extra bracket to produce an error
        \item single item line
    \end{enumerate}
    \end{document}

### Expected Behavior
It is expected the errors are reported as "information message" in VSCode output tab instead of warnings when chktex command line argument is "-mall"

### ChkTex output with different error reporting levels
> chktex **-mall** -I0 -f%f:%l:%c:%d:%k:%n:%m\n chktex_test.tex
```chktex_test.tex:5:18:1:Message:10:Solo `}' found.\nchktex_test.tex:9:1:0:Message:17:Number of `{' doesn't match the number of `}'!\nNo errors printed; No warnings printed; No user suppressed warnings; No line suppressed warnings.```

> chktex **-wall** -I0 -f%f:%l:%c:%d:%k:%n:%m\n chktex_test.tex
```chktex_test.tex:5:18:1:Warning:10:Solo `}' found.\nchktex_test.tex:9:1:0:Warning:17:Number of `{' doesn't match the number of `}'!\nNo errors printed; 2 warnings printed; No user suppressed warnings; No line suppressed warnings.```

> chktex **-eall** -I0 -f%f:%l:%c:%d:%k:%n:%m\n chktex_test.tex
```chktex_test.tex:5:18:1:Error:10:Solo `}' found.\nchktex_test.tex:9:1:0:Error:17:Number of `{' doesn't match the number of `}'!\n2 errors printed; No warnings printed; No user suppressed warnings; No line suppressed warnings.```

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
---
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
---
```

### Fixing the error
As the messages from chktex seem to obey the input argument ('-wall', '-mall' or '-eall') correctly the bug must be in chktex output interpretation. 
in ```function showLinterDiagnostics(linterLog: ChkTeXLogEntry[])```
There is a const for error level severity:
```
const DIAGNOSTIC_SEVERITY: { [key: string]: vscode.DiagnosticSeverity } = {
    'typesetting': vscode.DiagnosticSeverity.Information,
    'warning': vscode.DiagnosticSeverity.Warning,
    'error': vscode.DiagnosticSeverity.Error,
}
```

By changing **'typesetting'** to **'message'** (which is the output string of chktex) the errors are correctly displayed as info messages in VSCode.

**Comment by James-Yu** [comment]
Sorry but I don’t see the necessity on the change. Indeed, I also don’t understand why the linter would have such an option.

**Comment by TexLayer** [comment]
Well, I agree your reasoning -- I cannot immediately state if there exists any messages that should be brought to user as "informative" from the linter anyway. 👍

Just thought it would be best place to suppress chosen messages using chktex arguments - which can be easily changed by user. Not so that workshop would change them in any way. But in the end this can be changed to everyones taste from the \extensions\james-yu.latex-workshop-10.7.0\out\src\lint\latex-linter\chktex.js
