### ISSUE TITLE
default output into -outdir=%OUTDIR%/.tex

### ISSUE THREAD

**Issue by calidion** [James-Yu/LaTeX-Workshop#4488]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

当前插件自动生成中间文件时，全部放在了.tex文件的当前目录，导致查找困难，版本控制困难。

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- 

## The Solution*
> _Please provide a solution you would like to have._
- 建议默认创建一个子目录 `.tex` 或者`.tmp`用于放罢中间文件。
- 目前我使用`-outdir=%OUTDIR%/.tex`用于将输出结果全部放到子目录，效果很好。
- 当然如果能让pdf保存回上一层目录更好。

## Anything Else?
> _Add any other context about the feature request below._
-

**Comment by James-Yu** [comment]
You can change your local config.
