### ISSUE TITLE
Improper handling of `+` symbol in url in the PDF previewer

### ISSUE THREAD

**Issue by dharmik2319** [James-Yu/LaTeX-Workshop#4489]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x ] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 11
- Visual Studio Code Version: 1.96.0
- LaTeX Workshop Version: 10.7.0
- TeX Distribution Version: MiKTeX-pdfTeX 4.19 (MiKTeX 24.4)

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._

## The Issue*
> _Please briefly describe the issue you come across._
- When I insert [this](https://www.wolframalpha.com/input?i=f%28x%29%3D%28x%2F%28x-1%29%29*f%28x-1%29%2B1%2Cf%281%29%3D1`) link using `\href`, the `%2B` part of the URL turns into a `+`, which causes the `+` symbol to disappear in the actual Wolfram Alpha page, and instead causes a whitespace to appear.
- Manually opening this in Firefox works fine, but clicking/copying the link from the viewer/editor leads to the non-`+` version.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1.  Insert link with + symbol
2.  click on the said link
3.  notice that in the content of the page, the + turns into a whitespace

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- When I click on the link, I should be led to the correct page.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
Not applicable
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
Not applicable
```

**Comment by James-Yu** [comment]
I don’t understand your issue. Please elaborate more. Where does the change happen? Where does the jump fail?

Also please make sure that’s an extension issue, instead of a href package issue. You can verify that by opening the pdf with another viewer and click on the link.

**Comment by dharmik2319** [comment]
@James-Yu so basically, when I have a url in my document with a '+' sign in it, it would be something like
`\href{https://www.wolframalpha.com/input?i=1%2B1}{try}`, where the `%2B` is the url encoded `+` symbol. when I try to click on it from the file previewer, or even when I ctrl+click in the editor, it shows a prompt like this one:
![image](https://github.com/user-attachments/assets/90684198-6738-41b2-bbf0-96da7a9fe5d7)
Notice that the `%2B` has been decoded into a + here. it isnt a problem with other special characters, but instead of taking me to [this page](https://www.wolframalpha.com/input?i=1%2B1) it takes me to [this one](https://www.wolframalpha.com/input?i=1+1), which makes much difference. This does not happen when I use firefox's inbuilt pdf viewer. So the main problem is the automatic url decoding on the extension's side, instead of letting the browser handle it.

**Comment by James-Yu** [comment]
That can be a vscode issue if clicking in the editor decodes `%2B` to `+`.

**Comment by dharmik2319** [comment]
But it also occurs in the in built pdf viewer

**Comment by James-Yu** [comment]
I don't see a problem with the following code. You need to make your issue clear with reproduction steps and latex code. Avoid using `this` and `that`.

```latex
\documentclass{article}
\usepackage{hyperref}

\begin{document}
\href{https://www.wolframalpha.com/input?i=f%28x%29%3D%28x%2F%28x-1%29%29*f%28x-1%29%2B1%2Cf%281%29%3D1%60}{123}
\end{document}
```
