### ISSUE TITLE
Intellisense with external packages

### ISSUE THREAD

**Issue by Addie2595** [James-Yu/LaTeX-Workshop#450]
Is it possible to get latex commands from external packages (mainly siunitx) to show in intellisense? I know Sublime Text's LaTeXTools allow to configure a list of cwl files, is something similar possible? 

Also, there seems to be regular latex commands missing from intellisense too, namely \section*{} and \subsection*{}. Is it possible to add them?

**Comment by James-Yu** [comment]
For the first problem, no. The extension will register existing commands in your project and show them.

For the second one, yes by editing the file in `data` folder. However, enumerating all possible commands is impractical and unnecessary.

**Comment by Addie2595** [comment]
I do not understand the second sentence. Does it mean that the extension should automatically find siunitx provides the \SI{}{} command and show it? It doesn't for me.

**Comment by James-Yu** [comment]
No. It means if you have `\myrandomcommand` in your file, it will show in intellisense.

**Comment by Addie2595** [comment]
Oh, ok, thanks! It would be nice to have the cwl file feature in future, any chance it will appear at some point?

**Comment by James-Yu** [comment]
It's not on my list. Pull requests are always welcomed though.
