### ISSUE TITLE
Shortcut to bold/italize/etc... text

### ISSUE THREAD

**Issue by ataiya** [James-Yu/LaTeX-Workshop#454]
Could we add a command/shortcut that surrounds the existing text in a command?  (I have been a heavy TextMate/Latex user for years, and there you have CMD+B for bold CMD+I for italic and so on)

For example, in the following text (square brackets indicate text currently selected):
```
Lorem ipsum dolor sit amet, [consectetur] adipisicing elit.
```

Would result, upon pressing CMD+B (or CTRL+B in windows?)
```
Lorem ipsum dolor sit amet, \textbf{consectetur} adipisicing elit.
```

A generalization of this would also be nice ("surround selection with command"), where after pressing the shortcut the cursor lands after the "\" for manual command entry

```
Lorem ipsum dolor sit amet, \CANTYPEHERE{consectetur} adipisicing elit.
```

**Comment by ataiya** [comment]
Personal note: achieved similar behavior with this plugin:
https://www.granneman.com/webdev/editors/brackets/extensions/surround/

And by placing this as content of ``.vscode/surrounding.json``:
```
{
  "settings": [
    {
      "prefix": "\\textbf{",
      "postfix": "}",
      "index": 0
    }
  ]
}
```

(however, still feels pretty dirty/hacky, and it's not Latex specific for now?)

**Comment by James-Yu** [comment]
Duplicate #434.

**Comment by ataiya** [comment]
Thanks James, it's great that this can be done within VSCode directly (trying it out now), but don't you think it should come as default as part of your framework?

**Comment by James-Yu** [comment]
No because it will introduce too many keyboard shortcuts, which will inevitably conflict with other extensions.

**Comment by James-Yu** [comment]
It's not possible to create tasks by extension AFAIK. Currently the All actions menu is already clogged with random commands, a second level menu seems even worse than type the command directly.

**Comment by ataiya** [comment]
I see, maybe what is really missing from VSCode is script-based customization of the menu.
Similarly to what TextMate/Latex has under the bundles menu. 
Then it'd be easy to customize shortcuts
