### ISSUE TITLE
Passing arguments to the latex compiler

### ISSUE THREAD

**Issue by Spirits-** [James-Yu/LaTeX-Workshop#455]
A particular latex package (minted: https://github.com/gpoore/minted ) requires that I pass the -shell -escape arguments when compiling a document, how do I do this in VS Code with Tex Workshop? I've tried fumbling with the toolchain but to no avail. I'd simply like to add the parameters to the %!TEX=xelatex command I already have. Is this possible?

**Comment by James-Yu** [comment]
Append the arguments to `args`. Each argument in one line.

**Comment by Spirits-** [comment]
I've tried to append it like this:
``       {
            "command": "minted",
            "args": [
                "-shell",
                "-escape",
                "-pdf",
                "%DOC%"
            ]
        }``
This doesn't work.

**Comment by Spirits-** [comment]
Appending it to the default toolchain also does not work.

**Comment by Spirits-** [comment]
I've fixed it. You need to append "-shell-escape" instead of "-shell", "-escape" as it is one argument and not two.

**Comment by cliubf** [comment]
@Spirits- Hi, I'm wondering that where did you pass the argument to? I opened User Setting and found out these. Did you pass the argument `{ "command": "minted", "args": [ "-shell-escape", "-pdf", "%DOC%" ] }` to each one compiler (latexmk, pdflatex, bibtex)?

```json
"latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOC%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ]
```

**Comment by cliubf** [comment]
I have just figured out what to do, add the args as indicate below:

```json
{
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "--shell-escape",
                "%DOC%"
            ]
        }
```
Refer to issue #420
