### ISSUE TITLE
Feature request: Customized word count where some tags can be excluded

### ISSUE THREAD

**Issue by simonljus** [James-Yu/LaTeX-Workshop#456]
Being able to ignore the text within \begin{comment}\end{comment}
Example: 
\section{Title}
Count these words
\begin{comment}
Ignore these words in word count 
\end{comment}
Count this as well 
\begin{itemize}
\item Count this bullet point
\end{itemize}

**Comment by James-Yu** [comment]
This extension use texcount to count words. I cannot implement features related to it.
