### ISSUE TITLE
User-created snippets do not autocomplete in math mode

### ISSUE THREAD

**Issue by hexagonhexagon** [James-Yu/LaTeX-Workshop#458]
When I define a user-created snippet in latex.json and try to autocomplete it inside a math environment ($..$ or \[..\]), the dropdown menu for it does not pop up, and it refuses to autocomplete it.

Here is an example snippet I was trying to make work:
```javascript

"left(": {
	"prefix": "left(",
	"body": "\\left($0\\right)",
	"description": "Do left/right delimiters."
}
```

And here is a picture of the problem:
![test2](https://user-images.githubusercontent.com/25755516/37171945-74c5cbb0-22dd-11e8-8fad-441fe20ac5e1.png)
![test](https://user-images.githubusercontent.com/25755516/37171782-fa825d00-22dc-11e8-811d-ece126d7a01f.png)

**Comment by James-Yu** [comment]
The extension does not intercept snippet intellisense, yet I can reproduce your problem. My 2c is that vscode does not allow snippets in math mode, which is not unique in LaTeX. I would recommend an issue in vscode repo.

**Comment by tamuratak** [comment]
@jlelong, do you know what actually prevents user snippets to appear in completion items? Is there any issue related to this one on  [Microsoft/vscode/issues](https://github.com/Microsoft/vscode/issues)?

**Comment by jlelong** [comment]
The snippet works for me in math mode.
<img width="481" alt="capture d ecran 2018-12-04 a 18 50 24" src="https://user-images.githubusercontent.com/2910140/49462089-84b06100-f7f5-11e8-8ed8-48d5c7d08547.png">

**Comment by tamuratak** [comment]
Sorry. I have misunderstood the concept of snippets. We need to enter prefixes first before entering ctrl+Space. Now, they also work for me.
