### ISSUE TITLE
Support for WSL: Build toolchain never finishes using WSL

### ISSUE THREAD

**Issue by nikhilweee** [James-Yu/LaTeX-Workshop#460]
### Description
I can use the following toolchain and use WSL binaries to build the project. 
```
    "latex-workshop.latex.toolchain": [
        {
            "command": "wsl",
            "args": [
                "latexmk",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-pdf",
            ]
        }
    ],
```
The project builds fine, but I think VSCode never finds out that the WSL process has finished.
The status bar is forever stuck on "LaTeX build toolchain step 1."

### How to reproduce

1. Use the build toolchain as described above.
2. Try to build any project

### Expected behavior
The build toolchain must finish successfully

### Actual behavior
The build toolchain never finishes.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

```
[11:01:33] BUILD command invoked.
[11:01:33] Found root file from active editor: f:\projects\msr\thesis-report\report.tex
[11:01:33] Root file remains unchanged from: f:\projects\msr\thesis-report\report.tex.
[11:01:33] Building root file: f:\projects\msr\thesis-report\report.tex
[11:01:33] Build root file f:\projects\msr\thesis-report\report.tex
[11:01:33] Kill previous process
[11:01:33] LaTeX log parsed with 0 messages.
[11:01:33] Toolchain returns with error: null/SIGTERM.
[11:01:33] Build root file f:\projects\msr\thesis-report\report.tex
[11:01:33] Toolchain step 1: wsl, latexmk,-synctex=1,-pdf
```
LaTeX Compiler, on the other hand, suggests that the command executes successfully
```
Output written on report.pdf (7 pages, 265484 bytes).
SyncTeX written on report.synctex.gz.
Transcript written on report.log.
Latexmk: Found input bbl file 'report.bbl'
Latexmk: Log file says output to 'report.pdf'
Latexmk: Found bibliography file(s) [references.bib]
Latexmk: All targets (report.pdf) are up-to-date
```
I also verified the generated PDF. It has all the required changes.
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information

I installed texlive and latexmk on WSL with the following commands.
```
$ sudo apt install texlive-base latexmk
```

**Comment by James-Yu** [comment]
This should be a node and wsl problem. The extension knows that a tool chain has finished only if nodejs told it, which obviously did not happen in this case.

See https://github.com/nodejs/node/issues/18431 for more info.

**Comment by James-Yu** [comment]
Another note: it seems to be not possible to add `child.stdin.end()` to the building process, since the extension never know when the process ends unless wsl exits.

**Comment by wopian** [comment]
`stdin.end()` exits at the correct point from this test. LaTeX report was compiled and then the exit and closed events were emitted.

```js
const { spawn } = require('child_process')
const child = spawn('bash', [ '-i', 'bin/report' ])

child.stdout.pipe(process.stdout)
child.stderr.pipe(process.stderr)
child.stdin.end();

// This is emitted
child.on('exit', () => { console.log('Exited') })
// This is emitted
child.on('close', () => { console.log('Closed') })
```

Making the toolchain go through this to spawn the `wsl` or `bash` command produces no errors and refreshes the PDF after completion.

**Comment by Backfighter** [comment]
Just in case someone stumbles over this in the future. I have found a solution that works for me. 

Create a batch file:  
```Batchfile
@echo off
wsl ./build.sh < nul
exit %errorlevel%
```

Put a build.sh file into your project folder that executes the necessary commands of your distribution. 

Then put the following into your latex-workshop.latex.tools: 
```json
"name": "build"
"command": "cmd", 
"args": [
   "/c", 
   "path/to/batch/file", 
]
```
