### ISSUE TITLE
Enhancement: unify some of the formats

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#461]
There are now several formats supported in this extension:

- tex
- latex
- latex-expl3
- latex-beamer
- latex-memoir
- dtx (under development)

and some other things (bib and log).

Personally, I don't think `beamer` and `memoir` should be consider as separate formats, since they still use the normal LaTeX syntax. But dtx should be separated, since the syntax is almost totally different and the extension is different as well (`.dtx` rather than `.tex`).

However, things are a little bit complex for expl3. Basically, LaTeX3/expl3 is a "new" language. But it is compatible with the traditional LaTeX2e. In one words, I can write LaTeX2e materials in a LaTeX3 file, and using LaTeX3 in LaTeX2e is also OK if put in the `\ExplSyntaxOn` ... `\ExplSyntaxOff`.

Therefore, what I want to say is that, we can merely use two format: `latex` and `dtx`, but they should support LaTeX3/expl3 syntax at the same time. `tex`, `latex`, `latex-beamer` and `latex-memoir`, in my opinion, can be merged into a single format.

Thank you very much!

**Comment by jlelong** [comment]
I agree that `latex-memoire` and `latex-beamer` should be part of `latex`.

Because of all the `\begin ... \end` constructions in `latex`, I would rather keep a pure `tex` syntax separated from `latex` to make `tex` reusable.  
For instance in `dtx`, you can have unterminated groups ended by `\end{macrocode}`, whereas overlapping groups are LaTeX errors.  In order to make the `latex` syntax compatible with this,  everything dealing with groups has to be redefined, which means a lot.

**Comment by jlelong** [comment]
@James-Yu, if you think it is a good idea  I can merge `latex-beamer` into `latex` as a first step.

**Comment by James-Yu** [comment]
@jlelong Yes it would be fine to combine some, though I'm hesitated on `tex` and `latex`.

**Comment by jlelong** [comment]
I do think we need to separate `tex` and `latex`. This is the case for most editors.
Vim through its `vim-latex` provides a `plaintex` mode and a `latex` mode. The same holds for Emacs with Auctex. Actually, plain `tex` files can contain unbalanced `latex` stuff inside `\def` for instance , which the main reason why both must keep separated.

**Comment by Stone-Zeng** [comment]
Maybe the format `TeX` should be called `plain TeX`, to be precise.

Actually, plain TeX and LaTeX (as well as ConTeXt and the unfinished LaTeX3) are all independent `formats` based on TeX (not plain TeX!). However, sometimes we call plain TeX just TeX for simplicity, which leads to some ambiguities.

**Comment by jlelong** [comment]
You are perfectly right @Stone-Zeng.
My feeling is that the actual `TeX` syntax actually contains far more than TeX and plain TeX, as it recognizes most math commands and symbols. As it does nothing weird with `\begin ... \end` construction, it can be used to highlight pure TeX files.

To be coherent with others editors, we could rename the `TeX` format as `plain TeX` without changing its content and keep separate `plaintex` and `latex` formats.

**Comment by jlelong** [comment]
I noticed that in the `LaTeX` grammar, in `\begin{XXX} .... \end{XXX}` constructions, the `{` is either matched as `punctuation.definition.arguments.begin.latex` or `punctuation.definition.arguments.latex`.  To be coherent with what is done in the different grammars shipped with `vscode`, I would suggest to use `punctuation.definition.arguments.begin.latex` everywhere.
@James-Yu as you wrote the syntax files, do you have any opinion on that?

**Comment by James-Yu** [comment]
@jlelong Actually the syntax was from [tmbundle.latex](https://github.com/textmate/latex.tmbundle), which is a common pattern for language extensions of vscode. I personally do not have any experience in dealing with it, so please feel free to make modifications.

**Comment by jlelong** [comment]
I plan to merge `latex-memoir` into `latex`. The main difference between the two is that in `latex-memoir`, sectioning commands may take two optional arguments instead of one.

**Comment by jlelong** [comment]
I have just made a PR #585 to merge `latex-memoir` into `latex`. 
I do not use the `memoir` class, so it would be great if one could test my PR a bit more than I did.
