### ISSUE TITLE
Ghost hyperlinks in the pdf preview window after compiling

### ISSUE THREAD

**Issue by jccha** [James-Yu/LaTeX-Workshop#462]
### Description

When ``latex-workshop.view.pdf.zoom`` is set to 1.1, if the first page of the compiled pdf file has hyperlinks (e.g., produced by ``\ref{...}`` or ``\cite{...}`` together with ``hyperref`` package), then the pdf preview tab shows "ghost" hyperlinks when it is first opened by ``CTRL+ALT+T``.  The ghosts are at the location where the hyperlinks would be shown if ``latex-workshop.view.pdf.zoom`` was 1.

The ghost hyperlinks disappear when the zoom value is changed in the preview tab.  Or when the pdf is rotated.

Perhaps this is a bug related to pdf.js?  It is reproduced on both Windows and OS X.  I didn't check it on Linux.  I didn't attach LaTeX workshop output log, since there seems nothing relevant in the log.

### How to reproduce

The following is a sample LaTeX code which reproduces the problem:

```
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\section{First Section}
\label{l}
Here is a hyperlink to Section~\ref{l}.
\end{document}
```

The following screenshot shows the "ghost" hyperlink together with the correct hyperlink.

![screenshot](https://user-images.githubusercontent.com/7088544/37289219-7ec27916-264c-11e8-9041-8aec80c8fd75.png)

**Comment by James-Yu** [comment]
My guess is that it's a pdf.js problem or at least problem of the pdf viewer provided. I'll keep an eye on it in case I found something skeptical.
