### ISSUE TITLE
command 'latex-workshop.build' not found

### ISSUE THREAD

**Issue by kewenl** [James-Yu/LaTeX-Workshop#469]
### Description
I am using Mac VS code with your latex workshop extension.
When I build the latex project, I got an error: command 'latex-workshop.build' not found. I tried other functions like 'Clean up auxiliary files', it pops up a similar error: command 'latex-workshop.clean' not found. I remembered that when I used the old latex workshop version, it worked for me.

Could you please help hint me how to fix this? Cheers.

**Comment by chantisnake** [comment]
I had similar issue, try this: 

```shell
cd ~\.vscode\extensions\James-Yu.latex-workshop-3.14.0
npm install
```

**Comment by James-Yu** [comment]
See #474.

**Comment by huyiqun** [comment]
Have not changed a thing on my remote server where latex is installed, but experienced the same error for command 'latex-workshop.build' not found. Everything used to work just fine. Tried all the commands mentioned here and in #474 but still got the same problem. Any suggestions? Thanks!

**Comment by tamuratak** [comment]
If you want to fix your problem, open a new issue and fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)
