### ISSUE TITLE
Bibtex parsing fails on @string aliases

### ISSUE THREAD

**Issue by jabooth** [James-Yu/LaTeX-Workshop#47]
Seems the bibtex parsing is struggling in the new version, and I don't know if it's simple to gain the robustness back.

I'm looking into it now. It may make more sense to go back to relying on a third party provider to cover weird edge cases in bibtex.

**Comment by James-Yu** [comment]
The new one is a trimmed version of the original 3rd party extension, which seems to be obsolete for some time. Can you please give some examples of bibitems that failed?

**Comment by jabooth** [comment]
Apologies, clearly wasn't related to v1 but actually to changes I made in my bibtex yesterday. Fix incoming for that anyway.

**Comment by James-Yu** [comment]
Seems solved with the latest commit.
