### ISSUE TITLE
Highlight matching parentheses/brackets not working in latex math mode

### ISSUE THREAD

**Issue by s-ilic** [James-Yu/LaTeX-Workshop#470]
Pretty much said it in the title : matching parentheses/brackets are not highlighted when editing a .tex document when inside one of Latex's math modes : $ $, \begin{equation}, etc....

I know the issue has already been mentioned in this github (see e.g. [here](https://github.com/James-Yu/LaTeX-Workshop/issues/292) and [here](https://github.com/James-Yu/LaTeX-Workshop/issues/99)) and to quote James (see second link) it seems to him that :

> this is more a textmate/vscode upstream problem which disables brackets pairing in latex.math environments. Sorry it is not a problem that can be fixed from my side. I would recommend you submit an issue on vscode's repo.

I therefore submitted an issue about this on the vscode github (see [here](https://github.com/Microsoft/vscode/issues/45890)) and this is the answer I got :

> Ok, I see. The problem is that the Latex grammar from 'LaTeX-Workshop' uses the scope string.other.math.block.environment.latex inside the \begin blocks.
Surrounding pairs are disabled inside strings. It's a bit strange to use that scope for a whole block, so I'd suggest to file an issue against 'LaTeX-Workshop' to improve that. The request to allow or configure bracket matching inside strings is [#12388](https://github.com/Microsoft/vscode/issues/12388)

Any comments ?

**Comment by jlelong** [comment]
I am on it. I hope to make a PR to fix this week-end.

**Comment by jlelong** [comment]
I have made a PR #471 to fix this.
The difficulty is to choose an other scope selector, which is configured by most themes. The only scope not used yet is the `support.class` scope and it is rather well customized by the standard themes. Any other suggestion is welcome.
