### ISSUE TITLE
Cannot display any PDFs

### ISSUE THREAD

**Issue by WyldeLaRue** [James-Yu/LaTeX-Workshop#479]
### Description
When I right click view on a pdf file nothing happens. If I just left click the pdf file, I get the standard "The file will not be displayed in the editor..." message.

I don't know if it is just that I am not using the pdf viewer correctly or if it isn't working. I can't really find any documentation about how it is supposed to work. 

I have made sure that I have no other pdf viewer extensions. I am on MacOS Sierra.

### How to reproduce

1. Find any .pdf file
2. Right click it in the sidebar and select "View PDF file."

### Expected behavior
PDF file displays somehow.

### Actual behavior
Nothing happens. As in the right click dialogue box closes and it's not clear that anything happens at all.

### Log messages

No error messages.

<details>
13:09:33.731 /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host]% Object
13:15:39.435 console.ts:136 [Extension Host]% Object {$mid: 1, fsPath: "/Users/Tristan/topology/midterm.pdf", external: "file:///Users/Tristan/topology/midterm.pdf", path: "/Users/Tristan/topology/midterm.pdf", scheme: "file"}$mid: 1external: "file:///Users/Tristan/topology/midterm.pdf"fsPath: "/Users/Tristan/topology/midterm.pdf"path: "/Users/Tristan/topology/midterm.pdf"scheme: "file"__proto__: Objectconstructor: function Object()arguments: nullassign: function assign()caller: nullcreate: function create()defineProperties: function defineProperties()defineProperty: function defineProperty()entries: function entries()freeze: function freeze()getOwnPropertyDescriptor: function getOwnPropertyDescriptor()getOwnPropertyDescriptors: function getOwnPropertyDescriptors()getOwnPropertyNames: function getOwnPropertyNames()getOwnPropertySymbols: function getOwnPropertySymbols()getPrototypeOf: function getPrototypeOf()is: function is()isExtensible: function isExtensible()isFrozen: function isFrozen()isSealed: function isSealed()keys: function keys()length: 1name: "Object"preventExtensions: function preventExtensions()prototype: Objectseal: function seal()setPrototypeOf: function setPrototypeOf()values: function values()__proto__: function ()[[FunctionLocation]]: <unknown>hasOwnProperty: function hasOwnProperty()arguments: nullcaller: nulllength: 1name: "hasOwnProperty"__proto__: function ()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()arguments: nullcaller: nulllength: 1name: "propertyIsEnumerable"__proto__: function ()toLocaleString: function toLocaleString()arguments: nullcaller: nulllength: 0name: "toLocaleString"__proto__: function ()[[FunctionLocation]]: <unknown>toString: function toString()valueOf: function valueOf()arguments: nullcaller: nulllength: 0name: "valueOf"__proto__: function ()[[FunctionLocation]]: <unknown>__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
13:15:39.435 temp1
13:15:39.435 temp2
13:15:39.435 temp3
13:15:39.435 Object {$mid: 1, fsPath: "/Users/Tristan/topology/midterm.pdf", external: "file:///Users/Tristan/topology/midterm.pdf", path: "/Users/Tristan/topology/midterm.pdf", scheme: "file"}
13:15:39.435 Object {$mid: 1, fsPath: "/Users/Tristan/topology/midterm.pdf", external: "file:///Users/Tristan/topology/midterm.pdf", path: "/Users/Tristan/topology/midterm.pdf", scheme: "file"}$mid: 1external: "file:///Users/Tristan/topology/midterm.pdf"fsPath: "/Users/Tristan/topology/midterm.pdf"path: "/Users/Tristan/topology/midterm.pdf"scheme: "file"__proto__: Object
13:15:39.435 Object {$mid: 1, fsPath: "/Users/Tristan/topology/midterm.pdf", external: "file:///Users/Tristan/topology/midterm.pdf", path: "/Users/Tristan/topology/midterm.pdf", scheme: "file"}$mid: 1external: "file:///Users/Tristan/topology/midterm.pdf"fsPath: "/Users/Tristan/topology/midterm.pdf"path: "/Users/Tristan/topology/midterm.pdf"scheme: "file"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
</details>

**Comment by James-Yu** [comment]
It's most likely not related to the extension. Please provide LaTeX Workshop message, which can be accessed from `OUTPUT`.

**Comment by WyldeLaRue** [comment]
Ahh you are 100% correct. I figured out the mistake. Sorry for wasting your time and thanks for the excellent feature!
