### ISSUE TITLE
Change on-the-fly preview setting impossible

### ISSUE THREAD

**Issue by stuzfuz** [James-Yu/LaTeX-Workshop#482]
### Description

Visual Studio Code updated the plugin and forced me to select the on-the-fly preview setting.
I've selected "Browser" but I wan't to change it back to "Visual Studio Code".
Can't find the right setting.

### Additional Information

OS: Windows 10
Visual Studio Code: 1.21.1
LaTeX Workshop 5.0.0

**Comment by James-Yu** [comment]
It's `latex-workshop.view.pdf.viewer`. Do you think it is necessary to provide a  standalone action to change it?

**Comment by my1347** [comment]
no neccessary

**Comment by stuzfuz** [comment]
@James-Yu thanks for your fast feedback.
Standalone action is not necessary, but you should add it to the documentation section.

**Comment by my1347** [comment]
@stuzfuz yes ,you are right or it will be confusing

**Comment by stuzfuz** [comment]
As there are many settings available for the user I think it is neccessary to add them to the documentation section.
Nobody knows how to use the settings properly without the documentation guideline.

**Comment by James-Yu** [comment]
I have to say PR is much better than issues.
