### ISSUE TITLE
Add more magic TeX comments

### ISSUE THREAD

**Issue by amyspark** [James-Yu/LaTeX-Workshop#484]
### Description

I've migrated my thesis workflow to VS Code from Atom (it's waaaay faster now, thanks for your work!). 
However, the VS extension lacks support for some of Atom's "magic TeX comments", which force me to be a bit less automatic with the build step.

### Expected behavior

My documents use the following magic comments:

Name | Value | Use
-- | -- | --
enableSynctex | yes, no, true or false | Override SyncTeX setting
enableShellEscape | yes, no, true or false | Override shell escape setting
engine or program | pdflatex, lualatex, etc. | Override the LaTeX engine to use for build.
root | file path, e.g. ../file.tex | Specify the root file that should be built. Only available via "magic" TeX comments.

`enableShellEscape` and `root` are critical for me; the first because I use Pygments for linting code snippets, the second because I have my thesis' chapters separated into different files (and I tend to break builds by triggering them from within `\include`d files).

### Actual behavior

The remarked TeX comments do not work in VS Code.

### Additional Information

The complete list of the "comments" I'm using was taken from Atom's `atom-latex` package: https://github.com/thomasjo/atom-latex#overriding-build-settings .

**Comment by James-Yu** [comment]
`root` and `program` works well. The others are not widely adopted ones, and there is no current plan to implement them.

**Comment by gw0** [comment]
@James-Yu What about magic comment to override or specify additional `options` when executing a TeX and a BIB `program`? So that it is not necessary to put them in `"latex-workshop.latex.magic.args"`.

Example of the suggestion using `xelatex` and `bibtex` with a custom class and special intermediate and output directories:

```
% !TEX program = xelatex
% !TEX options = -aux-directory=./int -include-directory=./myclass -include-directory=./int -output-directory=./out
% !BIB program = bibtex
% !BIB options = -include-directory=./myclass
```

- https://latextools.readthedocs.io/en/latest/features/#tex-options

**Comment by gw0** [comment]
Hm, it may even make sense to introduce a magic comment to specify a recipe (`!TeX recipe =`)?

**Comment by jlelong** [comment]
See the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#magic-comments).
