### ISSUE TITLE
IntelliSense breaks in some documents but not others

### ISSUE THREAD

**Issue by huw** [James-Yu/LaTeX-Workshop#490]
### Description

This one's really weird, but I noticed it was affecting my current project. When typing `\` on my system (macOS 10.12, standard texlive 2017 installation, latest versions of everything else) in certain documents, IntelliSense completely breaks down and the Code Helper process hangs with 100% CPU usage.

### How to reproduce

1. Copy and paste the following into a Code window with the LaTeX grammar:

```
\documentclass{article}

\begin{document}

Her experiment found that this approach produced small but significant (< ) correlations between and weight loss when trained on Support Vector

\end{document}
```

2. Type `\` at the end of the paragraph

Restart VSCode and quit the 'Code Helper' process.

1. Create the following document:

```
\documentclass{article}

\begin{document}

Her experiment found that this approach produced small but significant correlations between and weight loss when trained on Support Vector

\end{document}

```

2. Type `\` at the end of the paragraph

### Expected behavior

In both examples, a list of autocompletions should appear.

### Actual behavior

For the first example, autocompletion completely breaks anywhere in the current VSCode window, and the Code Helper process uses ~100% of CPU:

![Activity Monitor](https://i.imgur.com/qUrbLcK.png)

No info appears in the Workshop logs, and workshop ceases to function. Hovering over the paragraph produces a 'Loading...' pop-up and nothing else.

Weirdly, for the second example, _VSCode functions perfectly_.

Further, the first example works when you remove the last word and restart everything (including Code Helper). It seems to be length-dependent. The second example (without the `(< )`) works with any length of code.

### Log messages

Nothing is logged in either location.

### Additional Information

I tested this with a number of files and projects. Another very large project (including a bibliography) completely worked, and this project also worked up to a certain point. I was able to isolate the problem to this block of text, but not much further. I'm really really confused about what could be causing this especially since the error is so fleeting and with little info.

**Comment by huw** [comment]
Update: I did some more testing and was able to isolate it beyond `\cite`. It seems to have something to do with the `(< )` bit — which I need in my document to type `(p < 0.005)`. Really really confused about this error.

**Comment by James-Yu** [comment]
![image](https://user-images.githubusercontent.com/4210342/37873249-ec6a963a-304a-11e8-8f8d-6fcc8a3eed54.png)

It is working good on my side. I'm with updated version.

**Comment by huw** [comment]
For reference, this was an issue with Code Spell Checker. I solved it by migrating to SpellRight.
