### ISSUE TITLE
Default PDF viewer

### ISSUE THREAD

**Issue by marcosegborges** [James-Yu/LaTeX-Workshop#494]
### Default PDF viewer

I noticed a little inconvenient in the version 5.0.2: the default PDF viewer is set to "none" in the **User Settings**, and "by default" it opens in the browser. I believe the best behavior could be open in a new "tab" in the VSCode, and if some user wants different configurations, he/she could change it.

### Expected behavior

```LaTeX
// The default PDF viewer.
"latex-workshop.view.pdf.viewer": "tab",
```
### Actual behavior

```LaTeX
// The default PDF viewer.
"latex-workshop.view.pdf.viewer": "none",
```

### Additional Information

Thanks for this excellent extension: I'll try to participate more in code development!

**Comment by awgneo** [comment]
This is still an issue for me with the latest version (5.5.1). Perhaps it has something to do with installing the latex binaries after installing the VS Code plugin?
