### ISSUE TITLE
Ctrl+Click not work when file path contains CJK characters

### ISSUE THREAD

**Issue by LukeLike** [James-Yu/LaTeX-Workshop#495]
### Description

When I press ctrl+click in the pdf file whose path contains CJK characters, it does not jump to .tex file. It seems that the CJK characters in the path is not recognized because in the log for LaTeX Workshop the CJK characters are garbled. However sync from .tex file to pdf works fine.

Is there a way to fix this?

**Comment by James-Yu** [comment]
It's not related to the extension, since LaTeX and its tools generally do not respect CJK chars. I'm not aware of solutions.

**Comment by LukeLike** [comment]
Well, I don't think this is an issue for synctex tool. Because when I run the synctex command directly in the command line, the output seems correct. I guess this is due to some encoding issues when reading the stdout.

![screenshot](https://user-images.githubusercontent.com/8063808/37946836-2616fac0-31ba-11e8-8177-16debe57091a.PNG)
