### ISSUE TITLE
Feature Request: Option to disable "Recipe succeeded." message

### ISSUE THREAD

**Issue by dkumor** [James-Yu/LaTeX-Workshop#496]
I save the file very frequently while working to see my changes, and find the message a bit distracting since it pops up every couple seconds (each time I save the file). I would really appreciate an option to disable the "Recipe succeeded." message.

I tried looking for this in the settings, but was unable to find it, so apologies if I simply missed it!

**Comment by mikchmie-ifm** [comment]
Exactly. The old way of displaying success/error info was far less distracting. It would be nice if there was an option to choose between old and new version.

**Comment by dkumor** [comment]
Thanks! I really appreciate it!
