### ISSUE TITLE
Feature Request: Predefined Macro Key

### ISSUE THREAD

**Issue by chantisnake** [James-Yu/LaTeX-Workshop#498]
I have enabled `chktex`, and learned about the difference between `$` and `\(`, `$$` and `\[`

However, it is too pains-taking to type `\(`, so is it possible to bind a macro for `\(`. For example, when you type `$`, it turns into `\( \)`.

**Comment by James-Yu** [comment]
It should be a feature provided by vscode, though I am not aware of it. You may refer to vscode documentation for reference.
