### ISSUE TITLE
Feature Request: Autofix `$ $` to `\( \)` and `$$ $$` to `\[ \]`

### ISSUE THREAD

**Issue by chantisnake** [James-Yu/LaTeX-Workshop#499]
chktex will mark this as warning, but you cannot auto-fix it.

**Comment by jlelong** [comment]
`chktex` only reports bad `LaTeX` constructions along with a suggestion to fix it, but no auto-fix suggestion. Some linters are able to fix some warnings by themselves, but unfortunately `chktex` cannot. Implementing an auto-fix feature directly in the extension does not really make sense and would really require a lot of work, actually redoing most of the linting process.

Although this is a desirable feature, I think it is not feasible with `chktex`. I am closing the issue. Feel free to reopen it if you have other ideas or suggestions.

**Comment by jlelong** [comment]
It can be done quite easily for when the maths expression `$...$` or `$$...$$` is on a single line as `chktex` detects the whole expression. For multiline constructions like
```
$$
.....
$$
````
only the opening `$$` are highlighted. Auto-fixing would require to parse the document to detect the end pattern `$$`. Do not know if it is worth it.

I suggest to start with single line constructions.
