### ISSUE TITLE
LaTeX3 support

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#50]
I'm doing something using the `expl3` syntax these days. Is it possible to add the LaTeX3 syntax support in the future?

**Comment by James-Yu** [comment]
I would suppose what you need is on syntax highlighting. This really depends on how https://github.com/textmate/latex.tmbundle/issues/79 works, as VS Code heavily rely on textmate syntax highlighting solution.
