### ISSUE TITLE
Open Compiler log when clicking on error window

### ISSUE THREAD

**Issue by u2berggeist** [James-Yu/LaTeX-Workshop#500]
It'd be nice that if a compiler error occurs and the error windows pops up if when you clicked it, it opened the compiler windows.

It's kind of annoying having to see the error message, exit out of it, go to `View>Output`, then go to the drop down for the LaTeX compiler.

**Comment by auguster** [comment]
Thanks, I had a message saying the recipe failed but couldn't find the logs until I saw your message.
I agree that the view>output should show the "Latex compiler" logs on failure. It's seems to be the common practice for the other extensions anyway.
