### ISSUE TITLE
Recipe being ignored in favor of magic comment // wrong behavior for magic comment

### ISSUE THREAD

**Issue by acristoffers** [James-Yu/LaTeX-Workshop#504]
I've setup a toolchain and recipe to build my projects using xelatex->biber->xelatex->xelatex.
However, due to the presence of % !TeX program = xelatex, the toolchain is ignored.
There are two issues here, at the same time:

1) Even if I run the "Build with recipe" task, my recipe is not run due to the magic comment.
2) The behavior of the magic comment toolchain is, I think, wrong. It should do a 4-pass compilation, as most tools need that. First to generate aux files, second to build bibliography, third to get cross-ref right and fourth to generate the PDF with everything in place. Or am I wrong here? It seems to work like that for xelatex, lualatex and pdflatex.

The way it is now I'm not getting references nor bibliography in the output pdf.
All works if I remove the magic comment (but I need it).

Proposal: make the default toolchain for magic comments be
(!TeX program) -> (!BIB program) -> (!TeX program) -> (!TeX program)

**Comment by James-Yu** [comment]
This issue is reasonable imo. Will implement after my vacation. PRs in the mean time is always welcomed.
