### ISSUE TITLE
When use chinese input method, the first key press will be missed.

### ISSUE THREAD

**Issue by yelantingfeng** [James-Yu/LaTeX-Workshop#506]
### How to reproduce

1. Open pdf viewer in vscode new tab.
2. Use Alt+Tab to switch to another app. (or other way to focus on somewhere outside the vscode)
3. Use Alt+Tab to switch back to vscode. (or other way to focus on vscode but not by clicking the editor in vscode)
4. Then I try to input a chinese charater ‘’你好” so that I pressed 'n','i','h','a','o'. However, the first key press is not catched by my input method, it is just regarded as a English letter 'n' and typed into the text, while the following 'ihao' are catched by the input method.

### Expected behavior

All key press actions are catched by the input method.

**Comment by James-Yu** [comment]
It should not be related to the extension. Only my guess and correct me if I'm wrong. You may find some assistance from vscode repo.

**Comment by Stone-Zeng** [comment]
It should be fixed now in vscode, see https://github.com/Microsoft/vscode/issues/26527.
