### ISSUE TITLE
Cannot get rid of toolchain recipe warning message

### ISSUE THREAD

**Issue by steronydh** [James-Yu/LaTeX-Workshop#507]
Whenever I change focus into a Latex window, I get this popup warning:

![image](https://user-images.githubusercontent.com/4245329/38240826-939747d0-3728-11e8-86f2-e5760bca5bfa.png)

If I then click auto change, I get this:

![image](https://user-images.githubusercontent.com/4245329/38240863-ac231162-3728-11e8-9cb0-763c14eefa37.png)

but changing focus brings back the original warning box.

FYI I don't compile within Code, I just want to stop the warning box!

**Comment by auguster** [comment]
It happened to me until I deleted from the vscode setting file the old toolchain that was still there.
You can find it easily, it's underlined by vscode saying "unknown settings" (or something alike).

**Comment by steronydh** [comment]
I got around it by uninstalling the extension and clearing everything related from user settings, then reinstalling.

**Comment by James-Yu** [comment]
I agree this can be an annoying issue. Will have a fix on that.
