### ISSUE TITLE
Clicking 'View LaTex PDF File' opens the PDF in Chrome

### ISSUE THREAD

**Issue by j1c** [James-Yu/LaTeX-Workshop#508]
The usual behavior of opening the PDF is opening the pdf within VSCode in a split viewer mode. This means you have your Latex code on the left half of VSCode and the PDF itself on the right half of VSCode. However, just today, clicking the 'View LaTex PDF File' button opens the pdf in Chrome instead within VSCode itself. 

Im not sure what caused this change of behavior.

**Comment by wopian** [comment]
The default behaviour changed. Add this to your settings to revert the behaviour back to a VSCode pane

```json
"latex-workshop.view.pdf.viewer": "tab"
```

**Comment by James-Yu** [comment]
On the first click of the button, the extension let you choose and should give the above information.

**Comment by j1c** [comment]
@James-Yu Hmm I don't think it gave me a choice earlier today. It literally was opening within VScode before noon then switched to web browser without any warning for me.

**Comment by brownem** [comment]
I also had it switch unexpectedly on me as well. Didn't even close or reload anything. One build loaded in the 'side tab', and then the very next one (fixing a typo in the text) opened it in Chrome.

Changing the variable back from `browser` to `tab` did resolve this though. still a little weird that something changed it on me.
