### ISSUE TITLE
Text highlighting for .bib files

### ISSUE THREAD

**Issue by u2berggeist** [James-Yu/LaTeX-Workshop#509]
I feel like the highlighting for .bib files could be improved significantly. May just the the output of the citation manager I'm using (Mendley), but separating the key from it's value is very difficult. See below:

![image](https://user-images.githubusercontent.com/20801821/38325222-62f9b1f6-3810-11e8-9b49-eafc31ad55cb.png)

I'm suggesting having the key and value be different highlighting schemes. It's been awhile since I've working on syntax highlighting stuff, but I'll try and take a look at it if someone else doesn't get to it.

**Comment by jlelong** [comment]
You are right, keys and values should be highlighted differently. I will have a look at it and hopefully make a PR soon.

**Comment by u2berggeist** [comment]
So I've just gotten the update (5.2.0) and the .bib file still doesn't have different syntax highlighting for keys and values. I can see that the style for the highlighting has changed, but that's it. 

I'm using a Monokai theme.

![image](https://user-images.githubusercontent.com/20801821/38769403-a0ebf196-3fd0-11e8-9241-5f4aa0b446e2.png)

**Comment by u2berggeist** [comment]
Gotcha. Yeah, I remember running into those issues when I was doing syntax highlighting on a different extension.

**Comment by jlelong** [comment]
I have changed scope `support.variable.key` to `support.class.key`. I Hope it helps for most themes.

**Comment by u2berggeist** [comment]
Looking at Monokai's theme json, `support.function` has a registered color, so that should work. `support.variable` didn't have a definition, which would explain why the syntax highlighting didn't work before.

**Comment by u2berggeist** [comment]
To confirm, it now works on my machine. Thanks for fixing this!
