### ISSUE TITLE
Texify log should be parsed differently

### ISSUE THREAD

**Issue by oerpli** [James-Yu/LaTeX-Workshop#511]
When the document is compiled with texify, the various compilation steps are handled by texify.exe and the log contains the output of all three runs. 

The parser then look for errors/warnings in the whole log and finds undefined references of the first pdflatex run which are resolved in the last step.

What could be done: 

1. Ignore the problem and use the recipe build system instead of texify (maybe check if texify is in the toolchain and give the user some warning)
2. If texify is used ignore some parts of the log.

Ad 2.:

As far as I can tell the log contains something like:

```
This is pdfTeX ...
This is BibTeX ...
This is pdfTeX ...
This is BibTeX ...
...
[ Warnings/Errors that could be parsed if .bib errors/warnings are relevant]
[ Example: Warning--empty publisher in branwen_silk_2011 ]
...
This is pdfTeX ...
[ Warnings/Errors that should be parsed ]
```

How it could be implemented:

1. Check if texify is in toolchain
2. Look for lines containing "^This is \w+"
3. Skip lines that are not:
  a.) between the last "This is BibTeX" and the next "This is pdfTeX"
  b.) after the last "This is pdfTeX"

**Comment by James-Yu** [comment]
Please provide a full log of `texify`.

**Comment by oerpli** [comment]
Here's a gist of two logs:
https://gist.github.com/oerpli/6e99e2ae52169a60b7fa0576c59cdbff

* The usual %DOC%.log (provided by pdfTeX I think)
* The console output during compilation

Maybe it would be easier to just use the first one (`cat %DOC%.log`) instead of the latter which is currently used as far as I know.
