### ISSUE TITLE
Math Syntax-Highlighting Issue

### ISSUE THREAD

**Issue by hno2** [James-Yu/LaTeX-Workshop#515]
### Description
I got an oddly specific Syntax-Highlighting Issue where `\end{eqauation}` is not detected, so the rest of the document is Math highlighted.

### How to reproduce
`\underbrace{\{ foo\}}` and `\underbrace{\{\foo\}}` `\underbrace{\{ \foo\}}`yield the wrong results. `\underbrace{\{foo\}}` does not. Please note the Space between { and foo.
Seen enclosed screenshots.
<img width="248" alt="bildschirmfoto 2018-04-06 um 14 40 59" src="https://user-images.githubusercontent.com/436990/38422204-24fc3216-39aa-11e8-9434-ee0f408b46ca.png">
<img width="187" alt="bildschirmfoto 2018-04-06 um 14 41 09" src="https://user-images.githubusercontent.com/436990/38422206-25212dd2-39aa-11e8-9d94-22595e837076.png">
<img width="242" alt="bildschirmfoto 2018-04-06 um 14 41 23" src="https://user-images.githubusercontent.com/436990/38422207-2541d42e-39aa-11e8-858d-a73b57e572e7.png">

**Comment by views63** [comment]
```
\[
{\{
}
\]
```
yield the wrong results.
