### ISSUE TITLE
IntelliSense for Glossaries

### ISSUE THREAD

**Issue by hno2** [James-Yu/LaTeX-Workshop#516]
Having autocompletion for the defined glossaries entires would be great. 

There seems to be an atom package for this: https://atom.io/packages/autocomplete-glossaries

**Comment by Swoy** [comment]
I found this CSS repo that implements this for CSS HTML and so forth. Maybe something we can use there?
https://github.com/zignd/HTML-CSS-Class-Completion

**Comment by yputter** [comment]
> Having autocompletion for the defined glossaries entires would be great.
> 
> There seems to be an atom package for this: https://atom.io/packages/autocomplete-glossaries

Please note that the author mentions: "The glossaries entries definition has to be done in the document environment (i.e. not in the preamble as usual)." and that there are drawbacks of doing it this way.

**Comment by xinleiyu** [comment]
This feature has been implemented in WinEdt too.
Hope to have this new feature in LaTeX-Workshop. 

Good luck for  LaTeX-Workshop.

**Comment by tecosaur** [comment]
@xinleiyu you'd be pleased to hear I'm interested in working on this in the near-ish future. I've just got a queue of a few things I need to get through first (such as **v0.4** for LaTeX-Utilities).
