### ISSUE TITLE
Intellisense Complete Mulitple Selections

### ISSUE THREAD

**Issue by dektoud** [James-Yu/LaTeX-Workshop#517]
Just reporting! not a massive issue but its different from what I thought would happen. Not sure if possible to fix or accommodate. Thanks for the excellent extension! 

### Description

Intellisense autocomplete with `\` with multiple selections

### How to reproduce

1. select multiple text items
2. press `\`, type `textbf` hit enter
3.  observe

### Expected behavior

both items individually would be wrapped with the intellisense completion

### Actual behavior

![2selections](https://user-images.githubusercontent.com/14908618/38424471-65b9e65e-396e-11e8-9fd5-4859a4c29b02.gif)

**Comment by James-Yu** [comment]
Unfortunately it is currently impossible to track multiple selections by the extension. I will leave this issue open for others' idea.

Basically the extension tracks selection behavior and record the content of the first selection. When `\` is pressed, the selected content is first cleared by the editor, then the extension show the dropdown menu. It seems hard to intervene this process, rendering multi-surrounding impossible.

**Comment by jlelong** [comment]
As discussed in #844, a new surrounding feature has been implemented, which deprecates the use of `\`. Instead use <kbd>ctrl</kbd>+<kbd>l</kbd>, <kbd>ctrl</kbd>+<kbd>w</kbd>. This new approach works with multiple selections (see the [README file](https://github.com/James-Yu/LaTeX-Workshop/blob/master/README.md))
