### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by chasset** [James-Yu/LaTeX-Workshop#52]
On MacOS, the PDF Viewer in a tab doesn't fill the whole width of the tab. So, the viewer has a small width discouraging any reading. It was ok before version 1. Except that, your extension is very useful. Thanks for any improvements!

**Comment by James-Yu** [comment]
Please provide screenshots describing the problem. Does it work well in browser tabs?

**Comment by Inachos** [comment]
Here's a screenshot from my macOS sierra. I don't notice something wrong.
Is it the same for you @chasset, or is there some more space somewhere?
![screen shot 2017-03-28 at 12 24 43](https://cloud.githubusercontent.com/assets/5030798/24400741/d3cf1418-13b1-11e7-9cc2-4960370a0b73.png)

**Comment by chasset** [comment]
on MacOS Sierra 10.12.3

**Comment by James-Yu** [comment]
I think I got what you mean. Is it the 20 pixel left of the viewer panel? This is left by intended for all vs code editors, including text editors. Maybe I can come up with a hack for it.

**Comment by James-Yu** [comment]
Tried but unfortunately impossible. It was a CSS by vscode, which can not be accessed by the extension or the embedded iframe.

**Comment by chasset** [comment]
I succeed to suppress it: I completly reinstall VSCode!
