### ISSUE TITLE
Commond Not Found

### ISSUE THREAD

**Issue by Awdrtgg** [James-Yu/LaTeX-Workshop#525]
### Description

I suddenly cannot use any of the commands of Latex-Workshop. All the actions are not found and no things are done. I've tried to reinstall the workshop, however it doesn't work. I don't think it's a problem about my own environment since I can use latex commands in the terminal and tex studio works well.

### Log messages
 
There's no log message.  When I try to implement any actions (either by shortcut keys ,by right click, or by ctrl+shift+P to show all the cmds), an error occurs and it says "command 'latex-workshop.actions' not found".

**Comment by James-Yu** [comment]
Try uninstall and reinstall. It's not related to the extension.

**Comment by Awdrtgg** [comment]
Well, but I tried many times...
