### ISSUE TITLE
Enhancement: CLEAN command could remove directories recursively

### ISSUE THREAD

**Issue by rgcv** [James-Yu/LaTeX-Workshop#530]
### Description

After adding a glob for a folder (let's call it `test/`) to be cleaned and issuing the CLEAN command, it returned an error and couldn't remove it. I found out that putting a glob for the files inside it (say `test/*`) first and then the directory itself worked, which means the removal is not recursive (I'm assuming).

It'd be great if an option for toggling cleaning folders recursively as well (disabled by default, to avoid issues of removing important directories unintentionally). Users could opt for it on or off, logging an info message or even notifying the user it found a folder glob but isn't going to be removed unless they choose to do so.

### How to reproduce

One can reproduce the error I stumbled upon by doing the following:

1. Create a folder in the output directory (by default set to be the one with the root .tex). Call it `test`, for example.
2. Populate `test` with some files (`stub.txt`, `empty.tex`, etc)
3. Place a glob in `latex-workshop.latex.clean.fileTypes` for the folder you created (in this example, `test` or even `test/`)
4. Issue a CLEAN command (Command pallette > LaTeX Workshop: Clean up auxiliary files)

### Expected behavior

The folder along with its children will be removed, appearing a successful log message in the extension's log output.

### Actual behavior

The folder isn't removed, appearing an error log message in the extension's log output.

### Log messages

```sh
[12:34:56] File cleaned: /path/to/output/dir/*.aux
...
[12:34:56] File cleaned: /path/to/output/dir/*.out
[12:34:56] Error removing file: /path/to/output/dir/test
```

### Additional Information

Since one must first remove the files within the folder, as of right now, if one would want to remove folders within the folder, it is necessary to first add the globs for the children files inside the target folders subfolders, then the target folder's children files and, finally, the target folder itself, i.e.,

```json
{
  "latex-workshop.latex.clean.fileTypes": [
    "test/sub/*",
    "test/*",
    "test/"
  ]
}
```

It's clear that the deeper the tree, the more globs one would have to add to the list instead of just a glob for the target folder.

**Comment by James-Yu** [comment]
Thanks for the issue. Can you please provide a use-case where there are nested folders generated by LaTeX compilers that need to be removed for a clean build? I myself have never encountered such a case.

**Comment by rgcv** [comment]
Hmm indeed not by the compiler alone, but by other tools/packages such as `minted` or `pythontex`. Each by default produce a folder in which they store files as part of their workflow. Getting rid of the entire resulting directory at once is rather more pleasing than to have this caveat in mind and having to add the extra apparently unnecessary glob.

Other than that, someone could still change their output directory and have a single glob in the `fileTypes` for the folder alone and completely purge the output of resulting builds.

**Comment by James-Yu** [comment]
My recommendation is to add a new tool called `rm` or `DEL` and use it as the new last step in your recipe. The clean function is only meant to delete the auxiliary files to prevent the compiler itself reuse the corrupted ones. IMO the suggested method is far more flexible than `clean`. What do you think?

**Comment by rgcv** [comment]
Hmm that indeed does make sense, but isn't as portable (hence requiring either `rm` or `DEL` based on the platform). One could argue portability could be solved with a local `settings.json`, of course.

Though, don't some packages generate auxiliary files as well? Such as the ones I mentioned, generating midway files in order to assist in compiling the final document. Wouldn't they be in the same auxiliary category? Or are they seen separately entirely, meaning a different notion auxiliary?

It can go both ways, really. Understandably, I like the idea of adding a new tool to the chain, only picking out portability as a somewhat noticeable issue.

**Comment by James-Yu** [comment]
#933
