### ISSUE TITLE
text in PDF is not rendered properly in preview

### ISSUE THREAD

**Issue by toniatop** [James-Yu/LaTeX-Workshop#531]
### Description
The built-in pdf preview capability does not work. The text seems not to be rendered properly in the preview. See below. 
![selection_151](https://user-images.githubusercontent.com/5911007/38604557-195051d2-3db4-11e8-9cbf-633cfcf1cfc5.png)
The pdf above has been opened with other editors and is just fine.
Behaviour is consistent across pdfs, all of them do not show any text rendered. Only pictures.

Behaviour observed on Ubuntu 16.04.  vscode 1.22
### How to reproduce

1.  Right click on any pdf on the side bar
2. Click on View PDF file

### Expected behavior
Pdf rendered properly. 

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
[18:20:16] PDF command invoked.

[18:20:16] No PDF viewer connected for /media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf

[18:20:16] Serving PDF file at http://127.0.0.1:45365/viewer.html?file=/pdf:%2Fmedia%2FHome%2FArticle%20AIAA%202018%2Fpreparation-papers-aiaa%2Fmain.pdf

[18:20:16] Open PDF tab for /media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf

[18:20:16] Preview PDF file: /media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf
</details>

<details>
<summary>Developer Tools Console</summary>
[Extension Host]% Object {$mid: 1, fsPath: "/media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf", external: "file:///media/Home/Article%20AIAA%202018/preparation-papers-aiaa/main.pdf", path: "/media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf", scheme: "file"}$mid: 1external: "file:///media/Home/Article%20AIAA%202018/preparation-papers-aiaa/main.pdf"fsPath: "/media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf"path: "/media/Home/Article AIAA 2018/preparation-papers-aiaa/main.pdf"scheme: "file"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
2webview.ts:128 
[Embedded Page] #of_pages is undefined.
webview.ts:128 
[Embedded Page] PDF 11ab66f88f445594f3e95f84dc3326c3 [1.5 pdfTeX-1.40.18 / LaTeX with hyperref package] (PDF.js: 1.10.97)

**Comment by James-Yu** [comment]
That is quite interesting since there's no report on such issues in the history. Can anyone else confirm the bug? It seems that I cannot reproduce the problem.
