### ISSUE TITLE
"file will not be displayed" issue

### ISSUE THREAD

**Issue by Zichuanyun** [James-Yu/LaTeX-Workshop#536]
### System & Version

- vscode: 1.22.1
- latex-workshop: 5.1.0
- MacOS 10.12.6

### Description

vscode complains:

```
The file will not be displayed because is it either binary, very large or uses an unsupported text encoding.
```

when trying to view pdf in a tab.

All other parts are working fine. The tex file can compile and the pdf can be normally viewed in browser or in other external viewers.

The default viewer is already set to 'tab'.

### Log messages

Nothing. All other parts are working fine.

**Comment by James-Yu** [comment]
Right click.

Unrelated to the extension.
