### ISSUE TITLE
VS Code often laggs when editing latex document.

### ISSUE THREAD

**Issue by Vargnatt** [James-Yu/LaTeX-Workshop#537]
### Description

I am editing my thesis, using non-English language,  However, when typing in an active document, VS Code often stucks for second or lags. And it occurs every few seconds.  We can observe a high CPU usage when lagging. The document contains multiple .tex files with rather a complex template. 

I am wondering if it is because of linting, non-English characters or template, etc.. And how to deal with the problem.

**Comment by James-Yu** [comment]
Not related to the extension. You can find help on vscode's repo.
