### ISSUE TITLE
Can't build using default recipes but auto-build on save works

### ISSUE THREAD

**Issue by henrikdahlberg** [James-Yu/LaTeX-Workshop#538]
These latest updates have broken essentially everything for me. As title suggests, I can't build when running the recipes latexmk or the pdflatex->bibtex... one, but when i save the document and auto-build it works. What recipe is the auto-build running? How do I fix this?

Used to have these settings before the update:
  "latex-workshop.latex.toolchain": [
    {
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "--shell-escape",
        "-file-line-error",
        "-pdf",
        "%DOC%"
      ]
    }
  ]

but nothing I try now allows me to build.

**Comment by James-Yu** [comment]
It just runs the first recipe, which refers to the latexmk one. I cannot understand why it happens. My 2c is that you have magic program specified in the project.

btw, do you really need `--shell-escape` ? It is known to cause a lot of troubles. Log messages can be very helpful.

**Comment by Ilhicas** [comment]
Yes I'm facing similar issues after update.

My workspace settings:

`{
    "latex-workshop.latex.toolchain": [
        {
            "command": "./latexdocker.sh",
            "args": [
                "latexmk",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf"
            ]
        }
]
}`

This results in:

`Unknown configuration setting`

Under problems tab of VS code.

This used to work previously. (as in before update)

**Comment by Ilhicas** [comment]
Solution to using previous toolchain at docker, besides the fact that it was removed previous toolchain that made things a lot less complicated.

{
    "latex-workshop.docker.enabled": true,
}

Yet.. this required me to change the script at ./vscode/extensions/James-Yu.latex-workshop-5.3.0/latexmk to #!/bin/sh

`
#set -euo pipefail
docker run -i --rm -w "$(pwd)" -v "$(pwd):$(pwd)" tianon/latex latexmk "$@"
 `

Commenting out #set -euo pipefail
Please don't make breaking changes like this.

**Comment by James-Yu** [comment]
No breaking changes were made, since nothing changed if you set `docker.enabled` to `false`.

**Comment by James-Yu** [comment]
In addition, this is the only version with docker scripts shipped. It is ok to use any previous working docker settings.

Please read readme or at least vscode popups before blaming the extension. `toolchain` was changed to `recipes`.
