### ISSUE TITLE
Did my configuration file override the default settings?

### ISSUE THREAD

**Issue by reaCodes** [James-Yu/LaTeX-Workshop#539]
![image](https://user-images.githubusercontent.com/13817254/38679716-0171961e-3e97-11e8-931d-5f5e31152bd5.png)

Although it works, I don't know if this configuration file overrides the default settings.
Then I know `toolchain` had been abandoned, so I rewritten the configuration information above. 

![image](https://user-images.githubusercontent.com/13817254/38680087-08ebb59a-3e98-11e8-8373-d87d0b268a98.png)

But this configuration file does not work, please tell me why

**Comment by James-Yu** [comment]
magic comment arguments are also changed. See README for details.

**Comment by reaCodes** [comment]
@James-Yu Is this correct?

![image](https://user-images.githubusercontent.com/13817254/38680571-3cb2b288-3e99-11e8-84ac-caddd8949cae.png)

**Comment by James-Yu** [comment]
hmm it seems README is wrong. Should be 
```
[
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%"
]
```

**Comment by James-Yu** [comment]
TODO: Correct README.

**Comment by reaCodes** [comment]
@James-Yu 
![image](https://user-images.githubusercontent.com/13817254/38681329-f53e4fc8-3e9a-11e8-9e06-e1dd38f6fc68.png)
But this is the default setting.
Now I want to set the variable compiler mode. How do I write this configuration file?

**Comment by James-Yu** [comment]
You don't need to. Just set the magic comment.
