### ISSUE TITLE
Is it possible to use default vscode build option?

### ISSUE THREAD

**Issue by czhang03** [James-Yu/LaTeX-Workshop#540]
Is it possible to use the default vscode build tool? 
Can I use `ctrl` + `shift` + `B` to build?

**Comment by chantisnake** [comment]
If I create a pull request to use the default build tool, will it be merged?

**Comment by James-Yu** [comment]
What is the `default build tool`?

**Comment by chantisnake** [comment]
https://code.visualstudio.com/Docs/editor/tasks

I think this will help. Default build tool is invoked with hotkey `ctrl+shift+B`.
