### ISSUE TITLE
Automatically synchronize environment name in both begin{} and end{}

### ISSUE THREAD

**Issue by junyuan-chen** [James-Yu/LaTeX-Workshop#543]
Is that possible to keep the content in the {} brackets of a pair of begin{} and end{} always the same when only modifying one of them, without using alt+click to manually add a second cursor?

Here is what I mean: when a new environment is added, there are two cursors in both of the brackets and hence the environment name is written simultaneously. But later, when I want to modify the environment name, it seems that I will have to use alt+click to add a second cursor to change the name in both begin{} and end{} simultaneously. Is there a way to make the process of adding this second cursor automatic?

Thanks!

**Comment by jlelong** [comment]
Considering what I have written to navigate between `begin` / `end`, I think it should be fairly easy to add an extra command to automatically select the environment name in the `begin/end` while on the other. I will try to propose a PR in the coming days.
