### ISSUE TITLE
Add auto-enclosure of $ and maybe \(

### ISSUE THREAD

**Issue by sulkhanp** [James-Yu/LaTeX-Workshop#544]
I can't speak for others but this feature would be a very nice addition for me. Currently, vscode supports auto-enclosure of `(, [, {, ', "` and what I mean by this is that when you type any of those symbols, vscode encloses it with the relevant symbol such as `( -> ), [ -> ]`, etc... 

Since latex is different from coding languages, we don't benefit from these as much as we could benefit from enclosing of `$ -> $ or \( -> \) or \[ -> \]`

I think this should be an optional feature at the very least, if not pre-enabled option. Also, I think this can be achieved within extension as Markdown extension adds auto-enclosure for `*` symbol.

**Comment by James-Yu** [comment]
#235 . `$` is intentionally left out upon multiple requests. You can find relevant info in prev issues.

**Comment by tamuratak** [comment]
Please up vote microsoft/vscode/issues/38352.
