### ISSUE TITLE
How to set up on Mac?

### ISSUE THREAD

**Issue by jpz** [James-Yu/LaTeX-Workshop#547]
Briefly, I've installed 5.2.0 of Latex Workshop on Visual Studio Code on MacOS.

Is some setup required to get PDF viewing working?  I looked through the config and there's stuff regarding SumatraPDF.exe for the external command.  

I couldn't see any obvious documentation - is it supported on platforms other than Windows?

thanks

**Comment by James-Yu** [comment]
external PDF viewer is not officially supported.

**Comment by James-Yu** [comment]
please provide the extension log.

**Comment by jpz** [comment]
Hi, I did a bit more troubleshooting on this, this morning.  

It appears not to be a mac issue - rather it has an issue with my file, and the TeX program directive in it - e.g.

This works on line 1:

% !TeX program = pdflatex

This does not work:

% !TeX program = xelatex
% !TeX program = lualatex
 
The logfile says pdf not found, but doesn't report much more than that from what I could gather - however the pdf is not being built.

It's something I can work around, and maybe an issue for the backlog - thanks for your time and effort on the project in any case :)

**Comment by tobywan** [comment]
In case it helps other people who have ended up on this thread through Googling, I've managed to set up Adobe Reader configured for my external viewer and Skim as the separate Sync target.
```json
{
    "latex-workshop.view.pdf.external.command": {
        "command": "open",
        "args": [
            "-a",
            "Adobe Acrobat Reader DC.app",
            "%PDF%"
        ]
    },
    "latex-workshop.view.pdf.external.synctex": {
        "command": "/Applications/Skim.app/Contents/SharedSupport/displayline",
        "args": [
            "-r",
            "%LINE%",
            "%PDF%",
            "%TEX%"
        ]
    },
}
```
HighSierra, VSCode 1.27.1, Latex Workshop 5.9.0, Adobe Reader Build: 18.11.20058.296032

**Comment by johnnychen94** [comment]
Supplement to tobywan on  skim->VSCode sync:

* To choose the command to open the TeX editor, choose Skim > Preferences, click Sync, and choose a preset editor, or choose Custom and enter a path to an editor command and arguments. From:  https://skim-app.sourceforge.io/manual/SkimHelp_51.html
* use `Shift-Cmd-Click` to do PDF->Tex sync. From: https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/
