### ISSUE TITLE
Autocomplete not working since MArch 27th update

### ISSUE THREAD

**Issue by risjain** [James-Yu/LaTeX-Workshop#55]
Hi,
Since yesterday's update, I can't see commands autocomplete themselves, when I start with a '\'. Odd enough, after typing '{}' the menu shows up, but it doesn't help much.

For eg. \sub --> doesn't show \subsection
b{} --> will show begin, if there is no '\' before it.

**Comment by James-Yu** [comment]
Can you please post your log here? In addition, now there is no pre-built commands, e.g., `subsection`. The command need to appear in your project at least once to let the extension learn.

**Comment by risjain** [comment]
Hi James, thanks for promptly responding. I'm not sure what 'log' is useful. I don't get any error per say. Its just that autocomplete was working before, and doesn't anymore. 

This is why I'm also confused after reading your comment about no pre-built commands with the extension. Because yours is the only extension installed in Code for Latex editing, and the autocomplete worked just fine, like it does if I'm using Magic python to edit python code.

For eg: This sometimes works.
![image](https://cloud.githubusercontent.com/assets/22205587/24455367/4009f0ca-145d-11e7-8201-bfe8ee6718af.png)

But this doesn't:
![image](https://cloud.githubusercontent.com/assets/22205587/24455437/8043b270-145d-11e7-92a9-e3400d731412.png)

Note that, I haven't used either of the two instances before in the tex file.

**Comment by James-Yu** [comment]
What I mean is, you may first type `\subsection`, enter, then press `\` and see what's happening.

Long words short, the extension reads your source file and hint you what already exist in it.
