### ISSUE TITLE
Syncing with external pdf viewer (opera)

### ISSUE THREAD

**Issue by Jo-Fleck** [James-Yu/LaTeX-Workshop#553]
### Description

_DISCLAIMER: I know external viewers are not supported and this is no urgent or fundamental issue._ 

I like to work on two screens (one tex, one pdf). In a previous latex workshop version (which was using the toolchain instead of recipe concept) I was able to adjust the settings so that I could use a non-default browser to display the pdf. This was convenient as it minimized the risk I might shut down my default browser or pdf viewer by accident while other tabs where active.

Unfortunately, after the update from toolchain to recipes, the behavior of said browser (Opera) has changed. I am not able to reinstate the old behavior and I do not know if its due to my latex workshop settings or an update of Opera.

Note: If I set the latex-workshop.view.pdf.viewer setting to "browser" my default browser behaves in exactly the way I desire.

### How to reproduce

1. Change the command of "latex-workshop.view.pdf.external.command" to "opera" (path of Opera executable) 
2. Build a tex project and run the view pdf command
3. Make a change to the tex file and re-run the build command

### Expected behavior

When running the build command, the browser should display the updated version of the pdf at the position which I was at before changing the tex file (as the default browser does).

### Actual behavior

When running the build command, nothing happens, i.e. the pdf does not update. When running the view pdf command, the browser reloads the pdf in a new tab and displays the first page, i.e. I have to scroll manually to the position where I was before.

### Additional Information

1) My relevant settings (I hope I got them all):

"latex-workshop.view.pdf.viewer": "external",

"latex-workshop.view.pdf.external.command": {
        "command": "opera",
        "args": [
            "%PDF%"
        ]
 }

2) I tried:
- experimented with adding "%LINE%" and/or  "%TEX%" to the argument of the external command. No effect.
- to check if there is some setting in Opera which I need to change. I could not find anything suspicious.

Can anybody help with this?

THANKS A LOT FOR THIS EXTENSION!

**Comment by James-Yu** [comment]
This is because opera does not support synctex. In `external`, the extension generally rely on the set program for synctex.
