### ISSUE TITLE
Feature Request: PDF preview in a wide tab

### ISSUE THREAD

**Issue by kalaider** [James-Yu/LaTeX-Workshop#555]
### Description

PDF viewer opens in new tab as expected, but it splits the editor vertically. On small displays it is almost impossible to recognize something on A4 page using only a half of a screen. The only solution is to make the tab wide using drag&drop -- manually move the tab to the main ribbon. But doing it by hands for each document being edited and in each new session is a bit annoying.

I request a new mode for the PDF viewer to open in a new full width tab just near the current `.tex` file.

### Expected behavior

![image](https://user-images.githubusercontent.com/4180138/38959404-3b2596cc-4369-11e8-8d85-6802b0f0ecd5.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/4180138/38959359-009f5e0c-4369-11e8-872f-26a7c301b7d6.png)

**Comment by James-Yu** [comment]
Unfortunately, this feature will make the already-crowded-commands of the extension more clogged. I'm inclined not to implement it.

Discussions are always welcomed.
