### ISSUE TITLE
An option for disabling the auto compiling function after saving the file?

### ISSUE THREAD

**Issue by odysseyguo** [James-Yu/LaTeX-Workshop#558]
Is that possible to give an option to disable the auto compiling function?I don't wish to do this every time after I save the edited file? It's costing a large amount of CPU. Please feel free to point it out if there is a button for this already.

**Comment by kalaider** [comment]
Do you mean the `latex-workshop.latex.autoBuild.onSave.enabled` option? Check your VS Code settings.
