### ISSUE TITLE
Prevent Intellisense for Double Backslashes \\

### ISSUE THREAD

**Issue by rxyang** [James-Yu/LaTeX-Workshop#560]
Is there a way to stop intellisense (autocomplete) after entering double backslashes \\ ?

Double backslashes are used for line breaks in many environment. It's a little annoying to have to press escape to cancel out intellisense every time \\ is entered.

Thanks!

<img width="690" alt="screen shot 2018-04-20 at 9 54 11 am" src="https://user-images.githubusercontent.com/17890393/39054914-df0be846-4480-11e8-8860-f9d643eb9904.png">

**Comment by James-Yu** [comment]
It is very strange since that the `press ENTER for new line` should always be the first item in intellisense of `\`. In this case just enter
