### ISSUE TITLE
Bug: Side panel view won't update when PDF also open in Adobe Acrobat DC Reader

### ISSUE THREAD

**Issue by brownem** [James-Yu/LaTeX-Workshop#561]
### Description

When you build the project, the PDF preview in the side panel (if open) will not update to the latest version if the file is also already open in Adobe Acrobat DC Reader. 

No error thrown.

Probably more of an issue with Adobe or Windows Explorer, but I am not sure.

Don't know if this is preventing the file actually being updated, or if it is just preventing the new preview from being grabbed.

### Log messages

NONE

### How to reproduce

1. Open LaTeX file PDF preview in VSC side panel preview
2. Open same PDF file in Adobe Acrobat DC Reader
3. Rebuild LaTeX file
4. No updated PDF preview generated in VSC side panel; previous view remains

### Expected behavior

PDF in side panel should update to latest version

### Actual behavior

PDF preview in side panel will not update to latest preview until after Adobe Acrobat DC Reader is closed, and the LaTeX file is rebuilt.

### Additional Information

NONE

**Comment by James-Yu** [comment]
Because you cannot create new PDF when Adobe is open.
