### ISSUE TITLE
Feature Request: Use Selected Text as Argument for Command

### ISSUE THREAD

**Issue by junyuan-chen** [James-Yu/LaTeX-Workshop#562]
Suppose there is a few words "ABC" that I want to make them boldface. It would be great if I can select these word and type \textbf to directly get \textbf{ABC} where ABC are the actual argument, instead of getting \textbf{text} with the placeholder "text" as it is right now.

More broadly speaking, it would be nice to always use selected text to fill in the argument of such kind of latex command and use the placehold "text" as a default when no text is selected.

**Comment by James-Yu** [comment]
Look at `latex-workshop.intellisense.surroundCommand.enabled`.
