### ISSUE TITLE
Auto-complete \includegraphics

### ISSUE THREAD

**Issue by u2berggeist** [James-Yu/LaTeX-Workshop#563]
### Description

It'd be really nice to have type hints for commonly used functions. For example, if there could be type hints for `\includegraphics` that says what should go where, it'd be pretty nice.

Probably already in the pipeline for future features, but I figured I'd mention it anyways.

Edit: Also, auto-complete for image filenames would be super dope. Let me know if that should be made as a separate issue for tracking.

**Comment by zjph602xtc** [comment]
"auto-complete for image filenames would be super dope", strongly agree.

**Comment by jlelong** [comment]
Auto-completing filenames in `\includegraphics` would require to parse `\graphicspath`. I do not know how this can be integrated with the built-in path intellisense of vscode.

**Comment by James-Yu** [comment]
It may incur too much unnecessary computation even during daily typesetting. I'm a bit wary on if it should be implemented, let alone the absolute/relative path issues that may arise.

Discussions welcomed.
