### ISSUE TITLE
Formatting Requires perl (?)

### ISSUE THREAD

**Issue by u2berggeist** [James-Yu/LaTeX-Workshop#564]
### Description

I'm trying to have the formatter work and am running into issues. From #118 , I'm assuming the implementation is very similar if not identical to [latex-formatter](https://marketplace.visualstudio.com/items?itemName=nickfode.latex-formatter). I followed the instructions he has for the installation along with the general instructions from [this StackExchange answer](https://tex.stackexchange.com/a/334511/122509) and am getting `failed with exit code 1` message.

I do _not_ have perl installed on my computer and would like not to. I assumed the use of `latexindent.exe` would circumvent this, but I'm not sure tbh. Scrounging around the repo for latex-formatter (specifically [this folder](https://github.com/cmhughes/latexindent.pl/tree/master/helper-scripts)) makes it seem like it's meant to run without perl (ie. `latexindent.exe` should be a self contained program with no dependencies to perl).

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

```
[11:25:09] Formatting failed with exit code 1
[11:25:09] stderr: latexindent: The script engine could not be found.
latexindent: Data: scriptEngine="perl.exe"
```
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

Following instructions from [this StackExchange answer](https://tex.stackexchange.com/a/334511/122509):
1.  Install latexindent via MiKTeX
2. Download latexindent zip from [CTAN](https://www.ctan.org/pkg/latexindent) (pretty sure this is to get the `latexindent.exe`)
3. Replace contents of folder MiKTeX just created with CTAN zip file into the folder 
4. ~Profit~

### Expected behavior

Reformat the code.

### Actual behavior

Nothing, error.

**Comment by James-Yu** [comment]
It's unrelated to this extension. [src](https://github.com/cmhughes/latexindent.pl)

**Comment by u2berggeist** [comment]
This issue was moved to cmhughes/latexindent.pl#110

**Comment by u2berggeist** [comment]
For any future stragglers with a similar question, the tl;dr from the other issue post is thus:

1. `latexindent.exe` does not require perl as thought.
2. MiKTeX installation of `latexindent.pl` for whatever reason only wants to use the perl version, not the exe version. If you delete the `latexindent.pl` script, it will simply repair the installation and put it back.
3. Suggestion is to put `latexindent.exe` in a different path location and add that to `PATH`
4. If for some reason you still have issues, you can point directly to the `latexindent.exe` via `latex-workshop.latexindent.path` setting.
