### ISSUE TITLE
snippets

### ISSUE THREAD

**Issue by jerabaul29** [James-Yu/LaTeX-Workshop#567]
I would like to change the behavior of some of the snippets. For example, when I start typing \frame for a beamer, I get the following snippet kicking on:

```
\begin{frame}
    CURSOR_HERE
\end{frame}
```

while I think the following would be better:

```
\begin{frame}{CURSOR_HERE}
    
\end{frame}
```

Do you know where I can change this?

**Comment by jlelong** [comment]
The snippet suggested above can go either to `LaTeX-Workshop/data/commands.json` or choose _Preferences: Configure User Snippets_ from the **Command Palette** and chose `latex` mode. In both cases, I think you will need to remove the existing `frame` entry from `LaTeX-Workshop/data/environments.json`
