### ISSUE TITLE
Adding "\newcommand" contents into quick suggestion?

### ISSUE THREAD

**Issue by junyuan-chen** [James-Yu/LaTeX-Workshop#570]
For example, suppose that I have the following line in the preamble of my tex file:
    \newcommand{\sumt}{\sum_{t=0}^{\infty} }
If I type \sumt in the main body, the intellisense will not list \sumt as a suggestion.

Is that possible to automatically scan the content in the preamble so that \sumt can be recognized as a command?

**Comment by James-Yu** [comment]
When you use once. It will.
