### ISSUE TITLE
Ignore the bibtex errors when there is no bib file

### ISSUE THREAD

**Issue by zjph602xtc** [James-Yu/LaTeX-Workshop#571]
My recipe is as follows:  

"latex-workshop.latex.recipes": [
        {
            "name": "pdflatex -> bibtex -> pdflatex*2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        }
    ]

It works when my tex file comes with a bib file. When there is NO bib, bibtex gives such errors as expected:
I found no \citation commands---while reading file P8116_HW10.aux
I found no \bibdata command---while reading file P8116_HW10.aux
I found no \bibstyle command---while reading file P8116_HW10.aux

Actually I already got the compiled pdf, since the first "pdflatex" worked. But the pdf viewer will not be updated because of this error. 
How can I just ignore the error and update the pdf viewer? I don't want to change the recipe for every workspace.

**Comment by zjph602xtc** [comment]
Does Latexmk solve the problem?

**Comment by James-Yu** [comment]
Yes.
