### ISSUE TITLE
Fix highlighting of {>{ $}X<{$}} pattern

### ISSUE THREAD

**Issue by zjph602xtc** [James-Yu/LaTeX-Workshop#574]
When I use the \newcolumntype in tabularx package. It will display all following text in math mode.

![image](https://user-images.githubusercontent.com/17025087/39225720-e74cdf44-481b-11e8-99b7-aa02fa1d00b3.png)

If I put an extra $, all things will be back to normal. (Of course, I cannot compile the tex file with this extra dollar sign)

![image](https://user-images.githubusercontent.com/17025087/39225791-63d39148-481c-11e8-99f1-b157933b18dd.png)

Other IDE like inlage does not have this problem.
![image](https://user-images.githubusercontent.com/17025087/39226357-f88c9138-481f-11e8-9934-4c5603c21c77.png)

**Comment by jlelong** [comment]
With 2., the `$...$` part of `\mbox{if $x \le 1$}` would not be highlighted for instance.
There seems to be no completely satisfying solution...

**Comment by zjph602xtc** [comment]
With 1, my problem would be solved, but that's not a complete solution maybe. 
With 2, I think too many situations will be affected, like your example. Also, \textcolor{red}{a whole paragraph containing $ $} would not be highlighted.

I guess bacause that two $'s are separated in different brackets. If you detect they are not in the same brackets, then just ignore the dollar sign? Does this work?

**Comment by jlelong** [comment]
You are right: 2. has too many side effects.
I do not think it is possible to detect overlapping within the textmate grammar used by vscode.
If we stop capturing `{...}` groups, everything should fine and there should not be any side effects as the only thing the captured group does is running the whole syntax file again inside the group.

I will try this way and see what happens.

**Comment by zjph602xtc** [comment]
That sounds like to be the same as what my other IDE does? $}X<{$ would be highlighted? But I think that's acceptable since such a pattern does not appear often.

**Comment by jlelong** [comment]
It would be great if you could try my PR #579.

**Comment by zjph602xtc** [comment]
Tried and felt good. Thanks!
