### ISSUE TITLE
Chktex not docker`d

### ISSUE THREAD

**Issue by CWRau** [James-Yu/LaTeX-Workshop#578]
### Description
Using docker you cannot use chktex.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

[12:07:42] Linter for active file started.

[12:07:42] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[12:07:42] Linter for active file failed to spawn command, encountering error: spawn chktex ENOENT
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Install Docker, vscode, vscode->latex-workshop
2. Use any valid latex project
3. Use option "latex-workshop.docker.enabled": true
4. Format .tex document

### Expected behavior

The document gets chktex'ed by using a docker image

### Actual behavior

An error gets logged: `Linter for active file failed to spawn command, encountering error: spawn chktex ENOENT`

### Additional Information

I noticed that there is no `chktex` file in the scripts folder, although the configuration documentation states that chktex is supported by the docker option:
```
  // Enable docker-based LaTeX distribution support.
  // Do not set this item to `true` unless you are aware of what it means.
  // This extension will use `tianon/latex` and `mcandre/docker-chktex` binaries to replace `latexmk`, `synctex`, `texcount`, `latexindent` and `chktex`.
  "latex-workshop.docker.enabled": false
```

**Comment by James-Yu** [comment]
The description is wrong. `chktex` is not supported, and I personally do not have intention to implement it. PR always welcomed.
