### ISSUE TITLE
Guide for manual installation

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#584]
In the README, the installation guide is the following:

>Alternatively, you can check out this repository and copy it to the VS Code local extensions folder:
>
>- Windows `%USERPROFILE%\.vscode\extensions`
>- Mac/Linux `$HOME/.vscode/extensions`

But the files in the git repository is not the same as in the `.vscode/extensions` directory. For example, there is a `src` folder in the git repository but not in `.vscode/extensions`. Please consider to show the details for manual installation.

**Comment by Stone-Zeng** [comment]
😆 Anyway, I think it would be better to add this guide, but with some details.

**Comment by James-Yu** [comment]
Actually it is not possible for end user to do so, since setting up the development environment requires knowledge.
