### ISSUE TITLE
.bib file highlighting doesn't include entries using {VALUE} syntax

### ISSUE THREAD

**Issue by u2berggeist** [James-Yu/LaTeX-Workshop#589]
### Description

`.bib` file highlighting work on key/value highlighting for entries that use `{VALUE}` syntax instead of `"VALUE"`. Mendley exports it's BibTeX files using the `{VALUE}` style, so it'd be nice to include both.

![Highlighting difference](https://user-images.githubusercontent.com/20801821/39472866-d9c9ac6e-4d19-11e8-9905-56b56daeb0ba.png)

### Expected behavior

I'd expect the value highlighting to work whether the value is denoted by either `{VALUE}` or `"VALUE"` since they are both valid to BibTeX.

**Comment by jlelong** [comment]
The standard behaviour is to highlight keys but not values, at least when they are specified as `{VALUE}`. I could deactivate the highlighting of strings, which leads to highlight `"VALUE"` whereas it should not be.

**Comment by u2berggeist** [comment]
I think disabling the highlighting of string for `.bib` files makes sense. Whatever keeps them consistent.
