### ISSUE TITLE
[LaTeX] I can't file file in the directory of iCloud Drive.

### ISSUE THREAD

**Issue by walkccc** [James-Yu/LaTeX-Workshop#590]
### Description

When the directory of the folder is in the iCloud Drive, i.e., "~/Library/Mobile Documents/com~apple~CloudDocs/"

### Log messages

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex 2017.11.24)  2 MAY 2018 16:50
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**"/Users/Jay/Library/Mobile Documents/com~apple~CloudDocs/Spring2018/DIP2018/h
omeworks/hw2/report/DIP_HW2_PengYuChen_B03902129_Report.tex"

! Emergency stop.
<to be read again> 
                   \protect 
<*> "/Users/Jay/Library/Mobile Documents/com~
                                             apple~CloudDocs/Spring2018/DIP2...
*** (job aborted, file error in nonstop mode)

 
Here is how much of TeX's memory you used:
 4 strings out of 492995
 136 string characters out of 6132703
 54074 words of memory out of 5000000
 3658 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 3i,0n,0p,1b,6s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!

### How to reproduce

1.  Open the folder located in iCloud Drive in VSC.
2.  Build the .tex file.
3.  It outputs the error message.

### Expected behavior

It can successfully build the .tex file.

### Actual behavior

It cannot successfully build the .tex file.

### Additional Information

If I put the folder in other locations, like `~/Desktop`, `~/Document`, it can successfully builds the .tex file and produces the pdf file.

Maybe this is caused due to the fact there are spaces in the path?

**Comment by James-Yu** [comment]
It's a LaTeX compiler problem, not resolvable from the extension side.

**Comment by yumath** [comment]
I have same problems, may it be set to a relative path instead of an absolute path at compile time？

**Comment by tamuratak** [comment]
See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#path-containing-chinese-or--characters
