### ISSUE TITLE
Wrong syntax highlight for brackets in math environments

### ISSUE THREAD

**Issue by dohyun-cse** [James-Yu/LaTeX-Workshop#591]
### Description
Syntax highlight shows wrong color for right brackets (`\|`, `\)`, `\}`).

When the right brackets are right before `.` or `$`, they show up in different color from the math environment.

### Screenshots

![image](https://user-images.githubusercontent.com/17425440/39524583-5e7d2252-4e54-11e8-8caa-0cbb8e7857a9.png)

As you can see, syntax highlight makes right brackets light brown when they are right before the punctuation marks or other brackets.

For inline math, `$` also makes a trouble as you can see in the last line.

If the left bracket is opened right before the same character, syntax highlight works well (see, the second line in the `align` environment).

In the case with `\|`, every `\|` before a punctuation mark shows up in light brown because there is no left or right.

### Additional Information
OS : Ubuntu 18.04,
VScode : 1.22.2,
Latex Workshop : 5.3.1.

**Comment by jlelong** [comment]
I will investigate this.

**Comment by jlelong** [comment]
I have never come across `\(` inside math mode. Is this valid TeX syntax?
It is important to decide how to fix the highlighting mismatch.

**Comment by dohyun-cse** [comment]
I think it is not.
I just tried this but it gives me the syntax error.
Sorry for the confusion.

Thanks for your contribution!
