### ISSUE TITLE
Syntax highlight for quotation marks

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#593]
### Description

In TeX, a quotation mark can be used to represent a hex number, so it should not be highlighted as an emphasis environment.

For example, in this figure, `"24B6`, `"24D0` and `"2460` should not be highlighted.

![image](https://user-images.githubusercontent.com/18233088/39559133-94671fe0-4ec6-11e8-8254-8f23ed84d5a5.png)

### Additional Information

This behavior exists in LaTeX, LaTeX expl3 and DocTeX mode.

**Comment by jlelong** [comment]
I will investigate this. So anything matching `"[0-9a-fA-F]+` followed by a space, `}`, `)` or `\` should be considered as a number. 

One possible solution to avoid fiddling with complicated `TeX` constructions would be to decide that strings are only matched against ` ``...''`.  This is the choice made by Emacs + Auctex .

**Comment by Stone-Zeng** [comment]
Actually, I think that it's unnecessary to highlight quotation marks, since this kind of emphasis is understood by human beings, not by computer.

It should not be consider as a string like C or python,  because the idea of "string" in TeX is totally different from something surrounded by `"..."`.

From `interface3`,
> A TeX string (and thus an `expl3` string) is a series of characters which have category code 12 ("other") with the exception of space characters which have category code 10 ("space").

Anyway, an option for whether to highlight the quotation marks may be helpful.

**Comment by jlelong** [comment]
> Anyway, an option for whether to highlight the quotation marks may be helpful.

I think it is impossible with the textmatex syntax mechanism used by vscode.
I will try to remove string highlighting `'...'` or `"... "` and see what happens.
