### ISSUE TITLE
How to stop formatting of LaTeX on each save

### ISSUE THREAD

**Issue by nikitavoloboev** [James-Yu/LaTeX-Workshop#594]
### Description
Whenever I write in a LaTeX document and save I get this error: 

![2018-05-03 at 13 27](https://user-images.githubusercontent.com/6391776/39573990-bbb7d35a-4ed5-11e8-81ab-8b1e79017c9b.png)

Is it possible to make LaTeX Workshop stop formatting the document on each save?

**Comment by James-Yu** [comment]
Disable auto-format with the default vscode setting.
