### ISSUE TITLE
Wrong syntax highlight in macro argument

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#595]
### Description

The syntax highlight in a macro argument etc is not correct:

```tex
\chapter{title \LaTeX{}}
\chapter{title \LaTeX{} some text \LaTeX{}}
\section{title \LaTeX{} some text \LaTeX{}}
\emph{title \LaTeX{} some text \LaTeX{}}
\textbf{title \LaTeX{} some text \LaTeX{}}
\verb{title \LaTeX{} some text \LaTeX{}}
```

![image](https://user-images.githubusercontent.com/18233088/39628677-60e05e04-4fdc-11e8-85a0-105a1311c108.png)

It seems that vscode try to match the first right brace, whether it's balanced or not.

### Expected behavior

All the normal text in `\chapter{...}` etc should be blue (in this theme).
In `\verb{..}`, however, all the text should be white (it's a little tricky here as even unbalanced materials would be ignored, but something like `\verb!..!` should be used instead of the normal braces).

### Additional Information

Version: 5.3.2
VS Code version: 1.23.0-insider

**Comment by jlelong** [comment]
`\verb{....}` is not correct, it should be `\verb{....{` which looks weird, hence thus more common `\verb!...`. So the syntax highlighting is actually correct for line 20.
To spare me some time, it would great if you could add to your issues the latex code used to generate the screenshots. 

I will investigate how to deal with braces. I guess this is related to #579.

**Comment by jlelong** [comment]
This issue is now solved and can be closed.

**Comment by Stone-Zeng** [comment]
Thanks very much! @jlelong
