### ISSUE TITLE
Can't find the citation bbl file.

### ISSUE THREAD

**Issue by lzhang6** [James-Yu/LaTeX-Workshop#599]
### Description

When I  run "build latex project", the recipe termine with error. 
I really like this plugin, can you help fix such problem. it confuse me for a long time since an update cause this problem.

### Log messages

LaTeX Warning: Reference `fig:knnData' on page 11 undefined on input line 727.
LaTeX Warning: Reference `fig:knnK' on page 11 undefined on input line 727.
LaTeX Warning: Reference `fig:knnData' on page 11 undefined on input line 727.
LaTeX Warning: Reference `fig:knnData' on page 11 undefined on input line 729
LaTeX Warning: Reference `fig:knnK' on page 11 undefined on input line 731
LaTeX Warning: Reference `fig:knnKError' on page 11 undefined on input line 731
LaTeX Warning: Citation `esling2012time' on page 11 undefined on input line 734
LaTeX Warning: Citation `shieh2008sax' on page 11 undefined on input line 734.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### change of setting
you mentioned in one issue that the pdflatex may casue such problem. so I add xelatex. But it still have such problem. The old version has no such problem. When I run xelatex **.tex; bibtex **; xelatex **.tex it has no such problem. If the following settting is not right, can you give a right one?
"latex-workshop.latex.recipes": [
        {
            "name": "latexmk",
            "tools": [
                "latexmk"
            ]
        },
        {
            "name": "toolchain",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex"
            ]
        },
        {
            "name": "pdflatex -> bibtex -> pdflatex*2",
            "tools": [
                "pdflatex",
                "bibtex",
                "pdflatex",
                "pdflatex"
            ]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOC%"
            ]
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],

**Comment by James-Yu** [comment]
You need two passes of `xelatex` after `bibtex`. Other than that, check your magic programming comment in the document.

**Comment by lzhang6** [comment]
Ok! great! It works. I really like this tool.
How to change the default tool to xelatex? for example, click "Build latex  project" run the "toolchain" defined above.
By the way, how to check magic programming comment in the document?

**Comment by James-Yu** [comment]
`When building the project, the first recipe is used.` - `README`.
