### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by denis-ko** [James-Yu/LaTeX-Workshop#6]
Is it possible to implement a better (latex related) error handling?

**Comment by James-Yu** [comment]
Yes it is on the plan. I need to find a good latex log parser yet.

**Comment by James-Yu** [comment]
Latest v0.2.5 implements a LaTeX log parser to better present the errors.

**Comment by denis-ko** [comment]
Are you planning to put these errors/warnings into "diagnosticCollection"? It would be nice to be able to navigate using the "Problems" panel.

**Comment by James-Yu** [comment]
I am still thinking about that. On the one hand it's really cool. But on the other hand the status can only be refreshed upon compilation, and may have some problem with latexmk. Will consider that a second time in the following days.
