### ISSUE TITLE
Keyboard shortcut for opening pdf viewer in tab and external browser

### ISSUE THREAD

**Issue by erihanse** [James-Yu/LaTeX-Workshop#600]
Earlier I had two hotkeys, CTRL-ALT-V to open the pdf in a browser, and CTRL-ALT-T to open the pdf in a new tab in vs code. Since some update this stopped working, how can I get this to work again?

**Comment by James-Yu** [comment]
Unfortunately, only one shortcut is available for viewing the pdf.

**Comment by erihanse** [comment]
I really miss this, may I kindly request the feature back? The thing is, when I have an external monitor, I'd like to see the pdf on the other screen, but when I'm only on my laptop (travelling or whatever), I like to have the tab and editor as two split screen tabs. Now I have to go to settings and update this a couple of times a day. 

I really enjoy the extension and appreciate the work you do, so if it's too much work feel free to ignore my request.
