### ISSUE TITLE
How to disable quick suggestion on string?

### ISSUE THREAD

**Issue by JindongJiang** [James-Yu/LaTeX-Workshop#601]
### Description

Hi, how could I disable the quick suggestion on strings while enabling it on code such as the quick search in `\cite{}`.

![image](https://user-images.githubusercontent.com/16209724/39664520-00118d1a-50b7-11e8-822f-be340613884d.png)

### Additional Information

I've tried modifying the quick suggestion setting for latex language like this

```json

    "[latex]": {
        "editor.quickSuggestions": false
    },
```

But when I did this, the autocomplete menu for `\cite{}` also disappear. So any solution for this diploma? Thanks.

**Comment by JindongJiang** [comment]
It seems that the words on the quick suggestion menu only come from the previous part of my article. I am a little confused about its behavior.

**Comment by JindongJiang** [comment]
Found a solution, no idea if it's the best one.

```json
"[latex]": {
        "editor.wordWrap": "on",
        "editor.wordBasedSuggestions": false,
    },
```

**Comment by James-Yu** [comment]
It is a vscode feature, unrelated to this extension. Though the above edit is correct.
