### ISSUE TITLE
Main text considered as string by VS Code? [Single " is causing issues]

### ISSUE THREAD

**Issue by junyuan-chen** [James-Yu/LaTeX-Workshop#603]
After updating to version 5.3.2., the main text in a tex file is considered as string by VS Code. As a consequence, the color for the syntax highlighting is changed (as well as the rule for word-based suggestions).

Is that an intentional change to treat the text as string?

Update:
<img width="451" alt="screen shot 2018-05-05 at 10 53 34 pm" src="https://user-images.githubusercontent.com/37969042/39670339-5514b5bc-50b7-11e8-8756-0af2528c55a5.png">
<img width="334" alt="screen shot 2018-05-05 at 10 52 26 pm" src="https://user-images.githubusercontent.com/37969042/39670344-70954446-50b7-11e8-9ff3-c62fd262b8ac.png">

I know that VS Code treat these text as string because after I change the setting for string in ``editor.tokenColorCustomizations``, the color of the text is changed.

Update2:
It turns out that the problem is caused by a piece of macro in the preamble:

````\newcommand{\activatebar}{%
	\begingroup\lccode`\~=`\|
	\lowercase{\endgroup\let~}\innermid 
	\mathcode`|=\string"8000
       }
````

After removing ``"`` near the end of that piece of macro, the main text will be correctly recognized as before (rather than string).

**Comment by James-Yu** [comment]
Can you please give an example on how it changed? I am personally using the `One Dark Pro` color theme and I did not notice any issues/changes w.r.t 5.3.2.

**Comment by junyuan-chen** [comment]
@James-Yu Thanks for reply!

Actually, I happen to use ``One Dark Pro`` as well. I would be surprised if this is only special to my case, as I didn't change anything else except that I updated both the LaTeX workshop extension and VS Code to the latest version.

**Comment by James-Yu** [comment]
I suppose so. Do you mind posting a screenshot on the text which you think the highlighter was doing wrong?

**Comment by junyuan-chen** [comment]
@James-Yu I just edited the main post above.
My temporary remedy for this issue is to change the color for string in ``editor.tokenColorCustomizations``. 
I know that VS Code treat these text as string because after I change the setting for string in editor.tokenColorCustomizations, the color of the text is changed, though these pieces of text are not supposed to be string.

**Comment by James-Yu** [comment]
Very strange, below is a patch of my current work:
![image](https://user-images.githubusercontent.com/4210342/39670432-d2ecfab4-5137-11e8-9971-093217c3ce1e.png)
You can see nothing is changed, and my `editor.tokenColorCustomizations` is `{}`. I'd advice you to post your `tex` file for debug purpose.

**Comment by junyuan-chen** [comment]
@James-Yu 

After some trial and error, I have just found where the issue comes from!

I have the following macro in the preamble:
````\newcommand{\activatebar}{%
	\begingroup\lccode`\~=`\|
	\lowercase{\endgroup\let~}\innermid 
	\mathcode`|=\string"8000
       }
````

The above piece of macro is obtained from: https://tex.stackexchange.com/questions/187162/vertical-bar-for-absolute-value-and-conditional-expectation

After deleting the ``"8000`` part, everything becomes normal.

**Comment by James-Yu** [comment]
Hmm, I'll do some debug on this.

**Comment by James-Yu** [comment]
It seems that 122b7062bd898b09bbf4f152f1f31ddb405c8d68 is the problem. I'm working on a solution.

**Comment by jlelong** [comment]
This is related to #593. I plan to make a PR on all this by the end of the day.

**Comment by James-Yu** [comment]
@jlelong Please kindly note that I just pushed a dirty hack which removes `"` to `"` pairing highlight in the commit above. I've no idea if that may break something or not, yet I suppose not 🤣
