### ISSUE TITLE
Build on save always uses default recipe, not first in settings defined

### ISSUE THREAD

**Issue by seppwerk** [James-Yu/LaTeX-Workshop#608]
### Description

I have a working recipe and would like to uses for builds on save. Unfortunatly, build on save always triggers the default recipe, not the first user defined one. I did not find a way to change this behaviour.

### How to reproduce

1. Create a recipe, i.e. by adding this to the configuration and create a tmp-folder in your root-file directory:

    "latex-workshop.latex.tools": [{
        "name": "tmpdocu",
        "command": "latexmk",
        "args": [
            "-xelatex",
            "-output-directory=tmp",
            "%DOC%"
        ]
    }],
    "latex-workshop.latex.recipes": [{
        "name": "tmpdocu",
        "tools": ["tmpdocu"]
    }],

2. Test the recipe with Ctrl+Shift+P -> Build with recipe -> tmpdocu
3. Be sure, compile on save is enabled (latex-workshop.latex.autoBuild.onSave.enabled must not be false)
4. Change something in the root file. The recipe will not be used.

### Expected behavior

Step 4 should use the recipe.

### Actual behavior

Default recipe is used.

### Additional Information

Tested with VSC 1.23.0 and LatexWorkshop 5.3.3

**Comment by seppwerk** [comment]
Oh, my sincere apologies. I completely overlooked, that a colleague used the magic comment to invoke xelatex. Thank you for the quick reply.
This bug can be closed then.
Just a short final question: Is it possible to have a „magic recipe comment“ to link some files with a specific recipe?

**Comment by James-Yu** [comment]
It is possible, though unlikely got implemented. That will make the already-very-complex recipe selection more confusing.
