### ISSUE TITLE
Starting a new line after \[ inserts \]

### ISSUE THREAD

**Issue by vomout** [James-Yu/LaTeX-Workshop#614]
### Description

If I start display math with \\[ and then press enter to start a new line, LaTeX-Workshop inserts \] and does not start a new line. I find this (and all kinds of automated insertion of content) highly annoying. There should be an option to disable this behaviour, but I could not find one.

### How to reproduce

1. Open a new tab
2. Save the document as .tex
3. Type \\[ followed by enter.

### Expected behavior

\\[ is followed by the cursor being on a new line.

### Actual behavior

\\[\\] is inserted with cursor after the opening bracket.

**Comment by James-Yu** [comment]
The behavior seems good enough to me. All in all you need a `\]` to close `\[`, which is inserted upon the first ENTER key. What is required is an extra ENTER key for line break. To summarize, two ENTER leads to a new line and the closing bracket.

Suppose this snippet is removed without the complaints of other users who rely on the auto-completion. The scenario is: first ENTER create a new line, then manually type `\` and `]` to close the bracket. Three different keys for the same result, which seems less appealing.

Discussions welcomed, correct me if I'm wrong thx.

**Comment by innerlee** [comment]
@vomout I would suggest turn off autosuggestion on enter. Use tab for accepting suggestion. The related setting is

`"editor.acceptSuggestionOnEnter": "off",`
