### ISSUE TITLE
UX: Remove build error msg on successful build

### ISSUE THREAD

**Issue by TarjeiB** [James-Yu/LaTeX-Workshop#616]
### Description
Build errors lead to one warning and one error message popup. The warning disappears automatically after some time, the error does not. Would be nice if the error is removed on successful build.

![error msg](https://user-images.githubusercontent.com/14159588/39814078-376693e4-5393-11e8-8354-44b0b9dabd29.PNG)

### Expected behavior
Build error & warning messages hidden/removed on successful build.
### Actual behavior
Only warning is removed

**Comment by James-Yu** [comment]
Unfortunately, vscode API does not support programmatically closing notifications. It is recommended to submit issue in its repo.

**Comment by kjgoodrick** [comment]
The VS Code developers have added a feature to allow for this as a backlog candidate in the issue referenced above. If you'd like to see this added please go up vote it so they will implement it!
