### ISSUE TITLE
Is auto-complete still unfinished , or it has been what it mean to be ?

### ISSUE THREAD

**Issue by ganxy1028** [James-Yu/LaTeX-Workshop#62]
Sorry to bother you again.
In the latest version , commands autocomplete themselves only when they had already existed, like many other language support extensions. It's acceptable , but I really prefer how previous versions work that commands can be autocompleted since it's been first typed in.
Will it be update in future versions? Or it has been what you mean?
Thank you.

**Comment by James-Yu** [comment]
That was left out as intended. However I am re-thinking on this.

**Comment by jabooth** [comment]
I think I agree - the tool 'feels' more solid if it is able to offer autocompletion all the time.

Is there a good reason to not have the standard terms available from the off?

**Comment by James-Yu** [comment]
The only reason was it is hard to enumerate these commands. The list in previous versions are incomplete.

I will include the list again soon(TM).

**Comment by James-Yu** [comment]
Going to have a new update. Please check back soon!
