### ISSUE TITLE
Different syntax highlighting for "&"?

### ISSUE THREAD

**Issue by junyuan-chen** [James-Yu/LaTeX-Workshop#622]
Would it be possible to use a different color for "&"?
Since "&" has such a special purpose in writing tables and aligned equations, it would be great if it is highlighted with a different color.

<img width="297" alt="screen shot 2018-05-10 at 4 56 59 pm" src="https://user-images.githubusercontent.com/37969042/39899919-57f13bec-5473-11e8-9996-bf2b4c66dabb.png">
<img width="438" alt="screen shot 2018-05-10 at 4 56 40 pm" src="https://user-images.githubusercontent.com/37969042/39899926-5e5283b0-5473-11e8-8a95-66ff473791e8.png">

**Comment by jlelong** [comment]
`&` is already detected within tables but matched against a scope, which is almost never customized by standard themes. Hence the impression of no highlighting!
I am on it to find a better solution and handle `&` similarly in tables and aligned equations.
