### ISSUE TITLE
Add \newcommand \def and similar commands to IntelliSense

### ISSUE THREAD

**Issue by jcmonteiro** [James-Yu/LaTeX-Workshop#623]
### Description
It would be nice to have user-defined commands appear in the drop-down menu. For instance, I usually define several macros at the beginning of the document, mostly math commands, to make it easy to alter notation and avoid typos.

**Comment by James-Yu** [comment]
It will show up when you have used it once in your document.

**Comment by jcmonteiro** [comment]
It does show up, but it does not detect the number of arguments, which is supported for those commands defined in `data/commands.json`.

**Comment by James-Yu** [comment]
This is unlikely to be implemented due to the complexity of LaTeX command definition syntax.

**Comment by jlelong** [comment]
If you always use more or less the user-defined commands, you could add them to latex snippets through the **User Snippets** menu (in **Preferences**). This is by far the fastest way to proceed when you some bespoke intellisense.
