### ISSUE TITLE
LaTeX-Workshop doesn't work after newest update

### ISSUE THREAD

**Issue by kerak19** [James-Yu/LaTeX-Workshop#626]
### Description
After i've updated VSC to newest version, none of the Latex workshop functionalities works. I can't build project, use SyncTex from cursor, preview PDF using Latex actions. There's no error in VSC, just nothing happens.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
No problems icon in status bar.
</details>

<details>
<summary>Developer Tools Console</summary>

When saving .tex file, this error is provided in developer tools Console:
`log.ts:165  WARN Aborted format on save after 750ms
console.ts:136 [Extension Host] (node:28558) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

</details>

### How to reproduce

1. Install Latex Workshop in VSC
2. Try to build project

### Expected behavior
Build PDF on save.

### Actual behavior
Nothing happens.

### Additional Information
VSC version 1.23.1

**Comment by jlelong** [comment]
On my installation, the latest version of *LaTeX-Workshop* works with *vscode* 1.23.1
Could you give us some details on what is exactly happening? Could it be related to #502?

**Comment by James-Yu** [comment]
@MichaelHettmer The developer console will say `'some module' is not found`. This is a vscode upstream problem. You can uninstall extension -> close vscode -> open vscode -> reinstall extension -> rinse and repeat and profit.

**Comment by MichaelHettmer** [comment]
It worked, thank you. Weird that clicking on restart didn't help. Explicitly closing and opening VS Code after uninstalling the extension did the trick.
