### ISSUE TITLE
LaTeX refactoring capabilities

### ISSUE THREAD

**Issue by darkl** [James-Yu/LaTeX-Workshop#627]
Hi @James-Yu,

I'm kind of a newbie to both LaTeX and Visual Studio Code. Most of my IDE experience is using Visual Studio + ReSharper for many of years. I'm also used to write math in LyX.

Lately, I started using TeXstudio in order for writing a paper. One thing that I feel that is missing is refactoring capabilites, such as these in ReSharper. I'm not asking for much, but I would like to be able to rename a command name by selecting it and hitting F2, or to select a text and select "extract command" to define a macro out of it. Of course you can introduce the "Introduce parameter" feature too.

I see that Visual Studio Code supports extensions, and that some extensions offer refactoring capabilities, such as [js-refactor](https://github.com/cmstead/js-refactor) and [vscode-python](https://github.com/Microsoft/vscode-python). I would love to see this kind of support for LaTeX.

I want to ask you as a maintainer of this project if you think this is doable, and if so, how would you recommend me to proceed? I would be happy to contribute this kind of feature to this extension.

Elad

**Comment by James-Yu** [comment]
Unfortunately I don't think it is readily possible for LaTeX. Actually symbol refactoring involves machine understanding of symbols, which is an academic research topic. Not until there are existing solutions we cannot have the feature implemented.

Sorry to let you down.
