### ISSUE TITLE
Math mode break DocTeX syntax

### ISSUE THREAD

**Issue by Stone-Zeng** [James-Yu/LaTeX-Workshop#628]
### Description

The following examples show this problem:

```tex
% \[
% \]
% \l__foo_bar_tl
% \foo:n
```

![image](https://user-images.githubusercontent.com/18233088/40100158-8e97712e-5915-11e8-9c77-120fb1a71a93.png)

```tex
% \(
% \)
% \l__foo_bar_tl
% \foo:n
```

![image](https://user-images.githubusercontent.com/18233088/40100176-a236502e-5915-11e8-8979-bc384dfb551b.png)

The TeX math switcher `$`, `$$` and other "normal" group material `{` and `}` will not break, however.

### Additional Information

This problem shows only in the new version 5.4.0.

**Comment by Stone-Zeng** [comment]
@jlelong Possibly due to 2a3853d8774ac7b9d1b5f878b160612ddb3f4df1?

**Comment by jlelong** [comment]
Actually, the culprit is 2265573. This is related to `doctex` using `LaTeX 3` syntax.
