### ISSUE TITLE
Strange colorizing in equation environment

### ISSUE THREAD

**Issue by Mrneet** [James-Yu/LaTeX-Workshop#632]
Thanks for your excellent work on this extension.

I found the color is strange in the equation environment after some version. Most of the codes are green. But what I hope is coloring the keywords or commands. TexStudio works well but I prefer VS Code.
![image](https://user-images.githubusercontent.com/30075289/40125370-5f7e7966-58f0-11e8-950c-b5089fe5e359.png)
![image](https://user-images.githubusercontent.com/30075289/40125564-d79a5c08-58f0-11e8-80c6-66f8f1c8d24e.png)

And, may I customize the code colorizing?

Thank you.

**Comment by jlelong** [comment]
Syntax is a two stage process : first, the extension defines scopes for different elements, and then, the theme associates colors to some of the scopes. Customizing colors has to be done on the theme side.

Which theme are you using? I can try to play a bit with the scopes to see if we can find a better look for the most commonly used themes but this is really delicate. 

Here are a few examples using different themes
- Monokai Dimmed

<img width="582" alt="capture d ecran 2018-05-17 a 06 59 10" src="https://user-images.githubusercontent.com/2910140/40157637-6fb5b96a-59a0-11e8-99f3-937b1def4f7a.png">

- Solarized Dark

<img width="596" alt="capture d ecran 2018-05-17 a 07 03 50" src="https://user-images.githubusercontent.com/2910140/40157664-91bc290e-59a0-11e8-84e6-8321fa41966e.png">

- Atom One Dark

<img width="586" alt="capture d ecran 2018-05-17 a 07 04 54" src="https://user-images.githubusercontent.com/2910140/40157681-a40bcbc8-59a0-11e8-85d4-1177235e7465.png">

To find out which scope is used for a given element, you can use the function _Developper: Inspect TM Scopes_.

**Comment by Mrneet** [comment]
Thank you. 
I am using the default theme Dark+. I tried the themes in your examples and they work as your figures.
