### ISSUE TITLE
Do not want latex-workshop.view.pdf.viewer to be automatically modified

### ISSUE THREAD

**Issue by Lencerf** [James-Yu/LaTeX-Workshop#633]
### Description

If `latex-workshop.view.pdf.viewer` is explicitly set to `none` in user settings, after I choose one option from the pop-up list, say `browser`, the extension will automatically change `latex-workshop.view.pdf.viewer` to `browser` in the user settings. After that I can not easily switch viewers. This is not a good design since users may want to use different viewer in different scenarios. For example I would choose a browser if my computer is connected to an external screen, and I would choose a vscode window if I am not using an external screen or I just want a quick glance. 

I here suggest that if `latex-workshop.view.pdf.viewer` is explicitly set to `none`, this extension should always ask which viewer I am going to use and __do not__ automatically modify this option.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. set `latex-workshop.view.pdf.viewer` to `none`
2. view pdf file and choose `browser`
3. repeat step 2, no pop-up list shows up again and `latex-workshop.view.pdf.viewer` is set to `browser `

### Expected behavior

if `latex-workshop.view.pdf.viewer` is explicitly set to `none`, this extension should always ask which viewer I am going to use and __do not__ automatically modify `latex-workshop.view.pdf.viewer`.

### Actual behavior

If `latex-workshop.view.pdf.viewer` is explicitly set to `none` in user settings, after I choose one option from the pop-up list, say `browser`, the extension will automatically change `latex-workshop.view.pdf.viewer` to `browser` in the user settings. After that I can not easily switch viewers.

**Comment by James-Yu** [comment]
You can always use `view PDF` dropdown menu in `LaTeX actions`, which appears in right click context menu.
