### ISSUE TITLE
Outline not updated on file save

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#635]
@James-Yu Surprisingly, the _Outline_ is not updated on file save. I have to revert your commit f0f747d to make things work, see also #268. Any hint on that?

**Comment by James-Yu** [comment]
Quite strange. I'll look into that. The issue can be reproduced on a minimal working example?

**Comment by jlelong** [comment]
A minimal example is [here](https://gist.github.com/jlelong/42232b6c2f1655803e6c4ea94204edd4)

If you remove one section, it stays in the outline.

**Comment by James-Yu** [comment]
Hmmmmmmm somehow I cannot reproduce, here's screenshots:

![image](https://user-images.githubusercontent.com/4210342/40350697-23727c28-5ddd-11e8-9d7a-8440c3e369c1.png)
![image](https://user-images.githubusercontent.com/4210342/40350722-2d8b91d6-5ddd-11e8-9a04-4baf80c7b07c.png)
![image](https://user-images.githubusercontent.com/4210342/40350737-3789e8b8-5ddd-11e8-92e2-21407df84fb5.png)

**Comment by jlelong** [comment]
Well, the outline still does not update with the latest releases of the extension and vscode.
I do not know how to make progress on that :-(

**Comment by jlelong** [comment]
I have figured out that the automatic update of the `Outline` was only triggered when `latex.autoBuild.onSave.enabled=true`. Fixed in my last commit

**Comment by werunom** [comment]
@jlelong  - so with `141b89d` does the outline gets updated without enabling autobuild?

For me, with `autobuild` disabled, the outline is not getting updated on save or change.

**Comment by jlelong** [comment]
Yes, it does. Note that this was fixed after release 5.5.0.
It will be included in the next release.

**Comment by werunom** [comment]
Ohh. Thats why. Will wait for the release patiently. 

PS - It will be nice if you release it soon :grin:

**Comment by James-Yu** [comment]
On the way 🤣
