### ISSUE TITLE
LaTeX-Workshop and VS Live Share

### ISSUE THREAD

**Issue by tdurieux** [James-Yu/LaTeX-Workshop#636]
Hi all, thank you for this great plugin!

Today, I tried to use the Microsoft plugin for collaborative edition: VS Live Share
But it does not work properly with LaTeX-Workshop.

I don't succeed to open the PDF, and the outline does not work, not able to compile,...

I have the feeling that it is related to the root path of the workspace in a shared session.

Do you think it is possible to make LaTeX-Workshop compatible with VS Live Share?

Thanks

**Comment by James-Yu** [comment]
I don't think so. It is not official yet, and no API changes are revealed.

**Comment by tdurieux** [comment]
Ok thank you for the fast answer

**Comment by James-Yu** [comment]
I have re-investigated possible ways to incorporate Live Share into the extension. Unfortunately, it seems very unlikely these two can cooperate. The extension was designed based on local file systems, and the change seems both too complex and quite possibly unsuccessful.

**Comment by tdurieux** [comment]
Thank you for the investigation.
I hope that Microsoft will change his live editing technique and will make it compatible with this plugin.

**Comment by monperrus** [comment]
Just a ping one year after the last comment.

Any news to get LaTeX-Workshop and VS Live Share working together?

**Comment by James-Yu** [comment]
No. It requires a complete overhaul.

**Comment by monperrus** [comment]
ok, thanks.

**Comment by James-Yu** [comment]
Now we have an experimental #4308 on Live Share integration, contributed by @quoc-ho @krokosik . If you guys are still using LW, welcome to have a try!
