### ISSUE TITLE
After typing one $, create a pair $$ with cursor in the middle without highlighting the following text as equations

### ISSUE THREAD

**Issue by logstar** [James-Yu/LaTeX-Workshop#638]
### Description

I was wondering if it is possible to make the following improvements of the syntax and highlighting behaviors of `$`:

- After typing one `$`, create a pair `$$` with cursor in the middle. Essentially, treat `$` like parenthesis.
- After `$`, `$$`, or `$$$`, do not highlight all following text as math equation. 

When writing math dense text, constant flashing by the highlighted text in the following is very distracting and annoying.

### Log messages

I think log messages may not be relevant to this issue. Let me know if you need any.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Put cursor in the middle of some text.
2. Type `$`.
3. Repeat step 2 for a few more times.

### Expected behavior

After typing one `$`, create a pair `$$` with cursor in the middle. Essentially, treat `$` like parenthesis.

After `$`, `$$`, or `$$$`, do not highlight all following text as math equation. 

### Actual behavior

After typing one `$`, only one `$` showed up and all following text are highlighted as math equation.

> ![screen shot 2018-05-18 at 1 23 54 pm](https://user-images.githubusercontent.com/9595639/40249351-bca1f120-5aa0-11e8-9503-1f7e3c761b39.png)

Similarly for the following `$` typed in.

> ![screen shot 2018-05-18 at 1 24 09 pm](https://user-images.githubusercontent.com/9595639/40249368-cb45058c-5aa0-11e8-80ef-543f8fbda9bc.png)

> ![screen shot 2018-05-18 at 1 40 58 pm](https://user-images.githubusercontent.com/9595639/40249473-2014fc16-5aa1-11e8-940d-ca5e5f3c7c65.png)

> ![screen shot 2018-05-18 at 1 24 21 pm](https://user-images.githubusercontent.com/9595639/40249475-2215293c-5aa1-11e8-8a47-364e83a3ecb8.png)

### Additional Information

N/A

**Comment by jlelong** [comment]
All LaTeX editors treat `$...$` and `$$...$$` as maths and highlight them as we do in the extension. Changing this very standard way to proceed would really be disturbing.

Concerning treating `$` as a pair, see #544.

**Comment by logstar** [comment]
@jlelong Thank you for the reply.

I did not mean to not highlight the text within `$`s, i.e. `$this text should be highlighted$` and `$$this text should also be highlighted$$`. 

However, I was wondering if it is possible to not highlight all following text if `$` is not paired or paired without any text in the middle, i.e. `$could this text not be highlighted` and `$$could this text not be highlighted`.

**Comment by jlelong** [comment]
Actually, there is no way to go backward in the syntax engine. So, once a `$` or `$$` is met, we enter maths and we cannot change our mind later. I guess all the other editors would have the same behavior.

**Comment by logstar** [comment]
@jlelong Thank you for the reply. It is good to know the limitations of the syntax engine.
