### ISSUE TITLE
Citation snippets should list paper title rather than citation key

### ISSUE THREAD

**Issue by clsmt** [James-Yu/LaTeX-Workshop#639]
### Description

When working in citation, e.g. in `\cite{abc98,...}`, a snippet pop up, which lists the available citation key. You can use direction key to look through them, and the corresponding title will be displayed on the right.

### Suggestion
After sometime writing with LW, I feel listing the paper title is way more convenient. The citation keys are more "for the machine", and they don't mean anything to us humans. We would naturally remember something about the title and the authors. A list of citation keys is a little more than a list of sequencial numbers. You need to flip through each one. I think list titles are more convenient.

**Comment by James-Yu** [comment]
`latex-workshop.intellisense.citation.label`

**Comment by clsmt** [comment]
Sorry I didn't know that. It works nicely! Kudos for implementing this!
