### ISSUE TITLE
Citation hints not displaying paper title, only abstract, authors etc.

### ISSUE THREAD

**Issue by clsmt** [James-Yu/LaTeX-Workshop#640]
### Description

When you move the cursor to an item in the citations, e.g. in `\cite{abc98}`, a small window will pop up displaying what's the content of this item. However, it starts with `abstract` and `author` etc.

### Suggestion
I think it's more convenient to show paper title in the beginning. If showing abstract, it takes way more time to figure out which paper it is.

**Comment by jlelong** [comment]
On my installation, it does show showing the title first.
<img width="706" alt="capture d ecran 2018-05-19 a 06 36 06" src="https://user-images.githubusercontent.com/2910140/40264982-73e14de8-5b2f-11e8-85f4-a84d25cdf62f.png">

The other fields are displayed in the same order as in the `.bib` file.

**Comment by clsmt** [comment]
I mean when you move cursor over the **existing** citations. I am not referring to the snippet window when you are trying to insert a new citation.

**Comment by jlelong** [comment]
When I hover over an existing citation, it displays the fields in exactly the same order as in the `.bib` file but drops entries `key = {value}` with no curly braces delimiters.
Maybe, we could try to sort the fields before displaying them.

**Comment by clsmt** [comment]
If sorting order is up to one's taste, at least maybe just grab the title and display that first?
