### ISSUE TITLE
To use `xelatex` as engine when using `fontspec` package?

### ISSUE THREAD

**Issue by clsmt** [James-Yu/LaTeX-Workshop#642]
### Description

I try to set the engine of latexmk to xelatex when using fontspec package. But it doens't work.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
T:\texlive\bin\win32\runscript.tlu:679: command failed with exit code 12:
perl.exe t:\texlive\texmf-dist\scripts\latexmk\latexmk.pl -xelatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf t:/Dropbox/J/2018_PT_BeamSteering/manuscript/PT_BeamSteering

</details>

### How to reproduce

1. I put these in the user settings:

```
    "latex-workshop.latex.tools": [
    {
      "name": "latexmk_xe",
      "command": "latexmk",
      "args": [
        "-xelatex",
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-pdf",
        "%DOC%"
      ]
    },
  ],
  "latex-workshop.latex.recipes": [
    {
      "name": "latexmk_xe",
      "tools": [
        "latexmk_xe"
      ]
    },
  ],
```

2. Compile any file that have `\usepackage{fontspec}`.

### Expected behavior

Latexmk use xelatex as engine.

### Actual behavior

Latexmk still use pdflatex as engine.

**Comment by Dellu** [comment]
I am having the same issue.

**Comment by James-Yu** [comment]
Please provide a minimal working example.

**Comment by James-Yu** [comment]
Please also note that you have `-pdf` in args, which may or may not influence `latexmk`. All in all, the extension is correctly calling `latexmk`.

**Comment by clsmt** [comment]
Removing `-pdf` works.

This may also be related to a `latexmk` [bug](http://www.tug.org/pipermail/tex-live/2017-January/039675.html). @Dellu Which version of Texlive do you have?

**Comment by Dellu** [comment]
I have the latest version: textlive 2018.
