### ISSUE TITLE
Would cleaning after every build affects performance a lot?

### ISSUE THREAD

**Issue by luyiming** [James-Yu/LaTeX-Workshop#643]
I just want to know whether enabling `"latex-workshop.latex.clean.enabled"` affects performance a lot? i.e. the time and resources used when compiling?

Are there any disadvantages enabling `"latex-workshop.latex.clean.enabled"`?

**Comment by James-Yu** [comment]
The feature itself does not need much time. You need to think of the cost of re-generating ancillary files each time during re-compile.
