### ISSUE TITLE
 "latex-workshop.message.error.show": false doesn't work

### ISSUE THREAD

**Issue by mprevot** [James-Yu/LaTeX-Workshop#648]
### Description

 "latex-workshop.message.error.show": false doesn't work: popup error messages are still showing.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

[23:42:15] Formatting failed with exit code 2
[23:42:15] stderr: Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC contains: C:/Users/soleil/AppData/Roaming/MiKTeX/2.9/scripts/latexindent C:/Perl64/site/lib C:/Perl64/lib) at C:/Users/soleil/AppData/Roaming/MiKTeX/2.9/scripts/latexindent/LatexIndent/LogFile.pm line 22.
BEGIN failed--compilation aborted at C:/Users/soleil/AppData/Roaming/MiKTeX/2.9/scripts/latexindent/LatexIndent/LogFile.pm line 22.
Compilation failed in require at C:/Users/soleil/AppData/Roaming/MiKTeX/2.9/scripts/latexindent/LatexIndent/Document.pm line 25.
BEGIN failed--compilation aborted at C:/Users/soleil/AppData/Roaming/MiKTeX/2.9/scripts/latexindent/LatexIndent/Document.pm line 25.
Compilation failed in require at C:\Users\soleil\AppData\Roaming\MiKTeX\2.9\scripts\latexindent\latexindent.pl line 27.
BEGIN failed--compilation aborted at C:\Users\soleil\AppData\Roaming\MiKTeX\2.9\scripts\latexindent\latexindent.pl line 27.

Popup message:
Formatting failed. Please refer to LaTeX Workshop Output for details.
</details>

<details>
<summary>Developer Tools Console</summary>
Nothing special.

### How to reproduce

Edit any .tex file, save and wait for compilation.

### Expected behavior

No message first, then eventually no fail.

### Actual behavior

Popup message shows despite   `"latex-workshop.message.error.show": false`

### Additional Information

I'm using PPM 4.21, ActivePerl 5.26.2.2601 from ActiveState for perl package management.

**Comment by mprevot** [comment]
Why closing ? isn't it a bug ?

**Comment by James-Yu** [comment]
Fixed.

**Comment by mprevot** [comment]
In [5.5.0] - 2018-05-22 it's not fixed.

**Comment by James-Yu** [comment]
Fixed in the commit that closed this issue.

**Comment by James-Yu** [comment]
You submit this issue on 26th or 27th. Don't expect it to be fixed before that pls.

**Comment by mprevot** [comment]
I understand. I was only lost because of lack of information.
