### ISSUE TITLE
Write-lock until compilation is complete

### ISSUE THREAD

**Issue by ArmageddonKnight** [James-Yu/LaTeX-Workshop#649]
### Description

Could we please protect the latex source file from being written until the compilation is complete? 

### How to reproduce

1. Open a latex source file and make some edits.
2. Save the source file, and this will start the auto-compilation into `.pdf` output.
3. At the same time, make some changes to the source file and save once again.

### Actual behavior

The generated `.pdf` file will crash, reporting that it only contains empty pages.

**Comment by James-Yu** [comment]
No it's not possible with the current api, and is controversial.
