### ISSUE TITLE
show symbols in activitybar

### ISSUE THREAD

**Issue by ludwig-austermann** [James-Yu/LaTeX-Workshop#650]
Use VS-Codes new API to create a symbol panel for math symbols:
[https://code.visualstudio.com/updates/v1_23#_extension-authoring](url)

**Comment by James-Yu** [comment]
I would like to see more discussions on this topic. The new view api is very promising, yet finding a symbol from a list of a thousand ones is not a desirable experience. Any idea on that?

**Comment by ludwig-austermann** [comment]
I thought of something similar of what Texmaker and Texstudio offer. Texstudio recently added searching for symbols, which drastically improves the experience.

![f90d228b4ed2dcdd](https://user-images.githubusercontent.com/12214171/40787397-c86b4f86-64ed-11e8-83b9-df9448e66b86.jpg)
![texstudio_screenshot](https://user-images.githubusercontent.com/12214171/40787400-c88d58a6-64ed-11e8-9dfa-71ce7a5d5d56.png)

I dont know what exactly is possible but if I have any new idea, I'll make you know.

**Comment by James-Yu** [comment]
I have to say these two panels are always an objective of this extension. However, it seems that the current vscode API still does not support this level of GUI customization. I'll keep an eye on their iterations.

In the meantime, any discussions or suggestions are welcomed!

**Comment by bhazelwood** [comment]
Hi,
Just wanted to offer an (easy/quick-fix) idea. I used to use the LatexTools package for ST3 before Latex Workshop + VS Code. 

They implemented a feature in the Ctrl+Shift+P menu (whatever that is called) named "lookup TeX symbol" which links to the detexify.kirelabs.org/classify.html page. I find it one of the best ways to lookup a symbol providing you can roughly draw the symbol you want...

PS good work on the package...its great!

**Comment by zoehneto** [comment]
Another option would be something like the [Insert Unicode](https://marketplace.visualstudio.com/items?itemName=brunnerh.insert-unicode) extension, which allows you to search for symbols by name.

**Comment by tecosaur** [comment]
Just to throw another idea in the ring, while vscode does not offer customisation this way, how about creating a webview panel in a similar way to #1157 ?

I may try this out at some point in the future.

**Comment by tecosaur** [comment]
@James-Yu I'm planning on starting on this as a webview panel, would you have any comments/suggestions before I get going?

**Comment by tecosaur** [comment]
Ok. I haven't got started yet but I will soon™

**Comment by tecosaur** [comment]
@jlelong I keep on forgetting about this, could you assign it to me?

**Comment by tecosaur** [comment]
Hey, looks like I won't actually need that reminding! I got started a few hours ago and this is what I have so far.

![image](https://user-images.githubusercontent.com/20903656/61174036-9482f580-a5cd-11e9-8a5b-e708aef20f78.png)


It's super basic right now, anything you hope it can do but don't see in that image — it can't do. What it can do is currently implemented inefficiently. However, I have plans…

More updates to come after I've done some sleeping.
