### ISSUE TITLE
Feature Request: Wordcount for multi document setups

### ISSUE THREAD

**Issue by viktorstrate** [James-Yu/LaTeX-Workshop#651]
I would really appreciate a command like already existing `Count words in LaTeX document`, that instead would take _all_ my documents into account, instead of only the currently active one.

```latex
\usepackage{subfiles}

\begin{document}

\subfile{document1.tex}
\subfile{document2.tex}
\subfile{document3.tex}

\end{document}
```

In a setup like the one above, the extension should go into each file `document1.tex`, `document2.tex` and `document3.tex`, and calculate the word count for each one, and then take the the total sum, and show that.

**Comment by James-Yu** [comment]
The extension calls [`latexcount`](https://ctan.org/pkg/latexcount?lang=en) to count the words. You may want to have an investigation on that package.

**Comment by viktorstrate** [comment]
Okay, thank you for the advice 👍
