### ISSUE TITLE
split environment not highlighted correctly

### ISSUE THREAD

**Issue by YuanshengZhao** [James-Yu/LaTeX-Workshop#652]
### Description
```tex
\[
\begin{split}
x&{}=y\\
&{}=z
\end{split}
\]

\[
    \begin{split}
x&{}=y\\
&{}=z
\end{split}
\]
```
if there is no indent before ` \begin{split}` , the highlight seems to be incorrect.

![image](https://user-images.githubusercontent.com/37881856/40789679-86b8400e-64e2-11e8-8df9-80d3b6afb926.png)

### Log messages
I think it's not related...

**Comment by James-Yu** [comment]
@jlelong any idea? I've looked a little bit into the syntax, and found it is just double Dutch for me 🤣

**Comment by jlelong** [comment]
Do not have much time right now, but I will try to have a look at it this week-end.
