### ISSUE TITLE
Document formatting does not consider document indentation settings

### ISSUE THREAD

**Issue by felixlinker** [James-Yu/LaTeX-Workshop#653]
### Description

When you format LaTeX "code" in your document, it will always format by using tabs irregardless of the documents vs-code-indentation-settings.

### How to reproduce

1. Create a LaTeX document using the plugin
2. Write some properly formatted stuff indenting with spaces
3. Format

### Expected behavior

The document should not change.

### Actual behavior

The document will now be indented with tabs.

**Comment by jlelong** [comment]
Using tabs vs spaces for formatting is based on the value of `editor.insertSpaces`. Does the issue appear regardless of the value of `editor.insertSpaces`. What is the value of `editor.detectIndentation`?

**Comment by felixlinker** [comment]
Both `editor.insertSpaces` and `editor.detectIndentation` are set to `true`.

**Comment by James-Yu** [comment]
It seems that I can reproduce this problem. Looking into that.

**Comment by James-Yu** [comment]
Quite interestingly, I cannot identify the source of this issue. It seems that the extension can correctly detect the above settings, and translate them into `-y="defaultIndent:␣␣␣␣"` for four spaces. However, `latexindent` seems to ignore this setting *only* when called by vscode. Scratching head and help needed.

**Comment by jlelong** [comment]
I will try to look into it in the coming days.

**Comment by jlelong** [comment]
There were actually two problems
- arguments passed to `latexindent` had extra quotes
- `tabSize` and `insertSpaces` values were wrong when `detectIndentation=true`.

I think I have fixed both problems but could you please check that it does work with your configuration. Reopen the issue if needed.

**Comment by draivin** [comment]
This bug seems to be back as of commit https://github.com/James-Yu/LaTeX-Workshop/commit/de6216719f87d27c7bd97ae3c0e85e18a27fee5c, which removes `shell: true` from the `spawn` arguments.

**Comment by draivin** [comment]
Fixed by changing default `latex-workshop.latexindent.args` to
```js
[
        "-c",
        "%DIR%/",
        "%TMPFILE%",
        "-y",
        "defaultIndent: '%INDENT%'"
]
```

**Comment by jplatte** [comment]
@jlelong I can also now reproduce the bug. The fix by @draivin works for me.
