### ISSUE TITLE
"latex-workshop.view.pdf.zoom": "page fit" doesn't work

### ISSUE THREAD

**Issue by mprevot** [James-Yu/LaTeX-Workshop#654]
### Description

"latex-workshop.view.pdf.zoom" setting doesn't take "page fit" as value, default is "auto", and override any user's setting

### Expected behavior

As the tab subwindow, showing the pdf should show with "page fit" setting, instead of auto.

### Actual behavior

User setting is ignored.

### Additional Information

latex workshop version: [5.5.0] - 2018-05-22
vscode version: 1.24.0

**Comment by mprevot** [comment]
Does this mean that it will be fixed in next release ?

**Comment by James-Yu** [comment]
No. The correct string is `page-fit`. You may want to read the config description carefully.

**Comment by mprevot** [comment]
Indeed. Thanks.
