### ISSUE TITLE
Project-wide references

### ISSUE THREAD

**Issue by zyrikby** [James-Yu/LaTeX-Workshop#655]
### Description
I do not know if this is only my issue or this is relevant for everyone. I would like to ask to implement project-wide references. For instance, currently my project has a main tex file and several additional section tex files, which are included using `\input` command:

```tex
\input{sections/introduction}
\input{sections/background}
\input{sections/evaluation}
\input{sections/discussion}
\input{sections/conclusion}
```
When I write content in one of these files, intellisense suggests me only references defined in the same file (when I use `\ref{}` command), however it does not offer me references defined in other tex files. For instance, I have a label defined in introduction.tex and I do not see it amoung the offerings when I write e.g. background section.

### Log messages
I have roughly the following structure:
```
my_paper/
├── sections
│   ├── introduction.tex
│   ├── background.tex
│   ├── evaluation.tex
│   ├── discussion.tex
│   ├── conclusion.tex
│   └── conclusion.tex
├── acmart.cls
├── ACM-Reference-Format.bst
├── main.tex
└── references.bib
```

### How to reproduce

1. Create a reference in one tex file within the project.
2. Open another file and try to call intellisense for this reference.
3. The reference is not offered.

### Expected behavior

I would like to see all the references defined within latex project offered for input.

### Actual behavior

Only references defined in the same tex file are offered by intellisense.

**Comment by James-Yu** [comment]
Please provide a minimal working example.

The current logic in the extension is that, if the root TeX file can be found, all references defined in sub-files will be included.

**Comment by zyrikby** [comment]
Please see the attached example:

[latex-ws-example.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2065971/latex-ws-example.zip)

**Comment by jlelong** [comment]
A project as a directory is not something understood straightaway by the extension.
To get the references of all your files, one approach is to declare the `TeX root` in each included file. See https://github.com/James-Yu/LaTeX-Workshop#root-file for more details on LaTeX projects.

**Comment by zyrikby** [comment]
@jlelong setting Tex root did not help, unfortunately.

**Comment by notZaki** [comment]
I tried the example project and the Tex root wasn't helping either.
But, it did work if I downloaded the source and built the extension. Weird. 

It also starting working after uninstalling and re-installing the extension, so maybe give this a shot?
After un/re-installing the extension, I was able to see suggestions by typing `\ref{}` in abstract.tex, which looked like:
```
% !TeX root = ../main.tex

\begin{abstract}
Abstract goes here.
\end{abstract}
```

**Comment by James-Yu** [comment]
It seems to be a vscode upstream problem, which may result in incomplete extension installation. The team is informed of this bug, and should be on the way fixing it.

I'll close this issue for now. Discussion welcomed, and re-open if related issue arose.
