### ISSUE TITLE
on reverse SyncTex VS Code window is not being activated

### ISSUE THREAD

**Issue by vvavrychuk** [James-Yu/LaTeX-Workshop#656]
### Description

On reverse SyncTex VS Code window is not being activated, in other words it does not receive focus.

### How to reproduce

viewer.html is used. Ctrl+click makes synctex happen and cursor is moved inside VS Code editor and correct editor tab is activated but VS Code application window itself is not activated. Instead viewer.html browser window is kept active.

### Expected behavior

I would expect for such feature that VS Code application window will become focused after reverse Synctex.

**Comment by James-Yu** [comment]
Unfortunately, it is not possible to control window activated state via an extension like this one.
