### ISSUE TITLE
Feature request：Hope to support remote compilation

### ISSUE THREAD

**Issue by zlcnup** [James-Yu/LaTeX-Workshop#657]
TeX Live in full installation mode is very large, about 5GB. And a little slowly in real-time compilation locally.
**Local editing, remote compilation, synchronize necessary files to display locally by other vscode extensions, it will be a fantastic work.**

**Comment by James-Yu** [comment]
Unfortunately, it's way beyond the capability of this extension. You may be referring to [OverLeaf](https://overleaf.com/).
