### ISSUE TITLE
Support package `import` in the outline

### ISSUE THREAD

**Issue by florianrusch** [James-Yu/LaTeX-Workshop#658]
### Description
It would be nice, if LaTeX-Workshop would support the package `import`. With import you have the ability to include graphics in subfiles via there relative path.

Example folder structure:
- `main.tex`
- `chapter01/`
  - `subfile.tex`
  - `graphics/`
    - `graphic.jpg`

Example `main.tex`:
```tex
...
\begin{document}
	\section{Section 01}
	\subimport{./chapter01/}{subfile}
\end{document}
```

Example `subfile.tex`:
```tex
\subsection{Subfile}
\begin{figure}[ht]
	\includegraphics{./graphics/graphic.jpg}
\end{figure}
```

**Concrete** would it be nice if the sections from a subfile, which is included via `subimport`, will appear in the outline.

Currently only `Section 01` will appear in the outline.

**Comment by jlelong** [comment]
If we do not aim at supporting nested subimport, I think it can be done fairly easily.

Supporting nested subimport is far more difficult and requires to redesign how files are discovered inside a LaTeX project.

I am not using the `subimport` package, is nesting subimport a typical usage?

**Comment by florianrusch** [comment]
I think the first layer would be enough. I haven't seen yet any example where an `\import or \subimport` was used in an imported file.

**Comment by jlelong** [comment]
Just added. Let me know if there is any trouble.

**Comment by florianrusch** [comment]
Awesome! I'll try it later this day or tomorrow.
Thank you for you fast support! 👍

**Comment by vogler** [comment]
For me this does not work.
Subsections via `\include` show up in the 'structure' view, but via `\subimport` and `\subimport*` don't.
`main.tex`:
~~~
\section{Foo} % shown
\subimport{sub/}{intro}  % not shown
\include{sub/intro} % shown
~~~
`sub/intro.tex`:
~~~
\subsection{Introduction}
~~~

**Comment by jlelong** [comment]
See the new issue #1827.
