### ISSUE TITLE
latex-workshop.synctex.afterBuild.enabled fails

### ISSUE THREAD

**Issue by mprevot** [James-Yu/LaTeX-Workshop#660]
### Description

With the following setting, "latex-workshop.synctex.afterBuild.enabled": true
vscode crashes, then latex compilation doesn't happen anymore, until restart of vscode.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
no problem is reported in this section
</details>

<details>
<summary>Developer Tools Console</summary>
/C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2263 Extension host terminated unexpectedly.
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2263
</details>

### How to reproduce

Compile latex with "latex-workshop.synctex.afterBuild.enabled": true

### Actual behavior

crash or no compilation

**Comment by James-Yu** [comment]
In general, vscode crashing is not related to the behavior of this extension. You may want to confirm your installation of synctex.
