### ISSUE TITLE
Auto Completion, syntax not working for some package like siunitx

### ISSUE THREAD

**Issue by Subratappt** [James-Yu/LaTeX-Workshop#665]
### Description
All options and syntax are not showing for some packages like **siunitx**  and autocompletion is not working. 
e.g.
**\SI{** arg1 **}{** arg2 **}** and **\si{** arg **}** are different but but during typing it only shows **\SI{** arg1 **}{** arg2 **}**

**Comment by James-Yu** [comment]
This extension does not support package auto-complete. It guesses the format from the first occurrence.

**Comment by Subratappt** [comment]
Is it possible to generate snippet from the latex packages ?
