### ISSUE TITLE
When using \hyperref[label]{displaytext}, the label suggestion happens on the displaytext, not the label.

### ISSUE THREAD

**Issue by MidasLamb** [James-Yu/LaTeX-Workshop#667]
### Description
When using the hyperref package and referring via ```\hyperref[label]{displaytext}```, the autocomplete for the labels does not show up when typing in the label part, but it does show up when typing in the displaytext part.

### Log messages
Not appropriate

### How to reproduce

1.  Define a label somewhere with ```\label{mylabel}```
2.  Start typing ``` \hyperref[my ```, the label ```mylabel``` does not show up
3.  Continue typing: ```\hyperref[mylabel]{``` now the label suggestion shows up

### Expected behavior

The expected behaviour is the label suggestion shows up when typing in the square brackets ```[ ]```

### Actual behavior

The label suggestion shows up when typing in the curly brackets ``` { } ```, this is the expected behaviour for e.g. ```\ref``` but not for ```\hyperref```

**Comment by James-Yu** [comment]
Unfortunately, it is not supported by the extension. Implementing this feature is not on the to-do list, and may rely on community effort.
