### ISSUE TITLE
Improved support for sub-/superscript

### ISSUE THREAD

**Issue by bnord01** [James-Yu/LaTeX-Workshop#669]
### Description

It would be nice to have improved support for sub-/superscripts. Things I'm missing most from other editors like auctex: 

1. Automatic insertion of `{}` after typing `^`/`_` (and placing the cursor inside)
2. Styling of `_{}`, `^{}` (e.g. using `vertical-align: sub/super` and `font-size: smaller`)

### Additional Information
Code Version 1.24.1
LaTeX Workshop Version 5.5.1
macOS

**Comment by jlelong** [comment]
1. Not all users would like to automatically insert `{}` after `^ / _`, but there are two snippets to achieve this: `__` (double underscore) + `TAB` inserts `_{}` with the cursor inside the brackets, `**` + `TAB` inserts `^{}`.
1. Syntax files only assign scopes. Then, themes are responsible for highlighting scopes. I have not found any themes with the ability to render sub/superscript are auctex does.

**Comment by bnord01** [comment]
Thanks, `__` works quite well but I have to manually trigger completion for `**`.  I'll investigate if I find any good option to render sub/superscripts.

**Comment by jlelong** [comment]
You are right `**` does not trigger completion automatically, but hitting `TAB` converts `**` into `^{}` without triggering the completion list. Maybe, I have a specific completion setting. Can you check if it works like on your installation?

Any suggestion/help on the rendering of sub/superscripts is welcome. An other difficulty is that it is not possible to change syntax highlighting based on configuration variable. This means that the user could not choose if he wants to keep the current rendering of sub/superscripts or to use the auctex style.

**Comment by bnord01** [comment]
Typing `**TAB` leaves me with `**TAB` in the editor. I haven't made any changes to any completion settings.

**Comment by jlelong** [comment]
I will investigate this. Meanwhile, you change the `**` combination in the file [snippets/latex.json](https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/latex.json) by something else, for instance `^^` if `^` is not a dead key .

**Comment by jlelong** [comment]
@bnord01, can you give me your vscode user settings file as a [gist](https://gist.github.com/) to help me understand what is going on?

**Comment by bnord01** [comment]
@jlelong my user settings are empty and my workspace settings are [here](https://gist.github.com/bnord01/7e9a4e674bdd5e63629addab95521ae8) nothing that should really matter. Tested this under Windows 10 1709, VSCode 1.24.1 with LaTeX Workbench 5.5.1 and Spell Right 2.5.2 installed.

**Comment by bnord01** [comment]
As a followup, I tried actually using `__` and quickly noticed, that this doesn't work in practice as almost always you'll be using this like `x_` and the completion for `__` won't match with the leading `x`.

**Comment by jlelong** [comment]
You need to set `"editor.tabCompletion": true` to make the snippets `__` and `**` work when they glued to a leading expression.

**Comment by jlelong** [comment]
Everything should be properly fixed now. To have intellisense automatically triggered inside snippets, set "editor.suggest.snippetsPreventQuickSuggestions": false.
