### ISSUE TITLE
Enable partial compilation of region, section, environment, file, ...

### ISSUE THREAD

**Issue by bnord01** [James-Yu/LaTeX-Workshop#671]
### Description

When dealing with large documents (large sets of fragile _beamer_ slides containing _listings_ and _tikz_ overlays) on slow machines compilation of the whole document can take several seconds to minutes.   A feature I miss from auctex which greatly improves productivity is the ability to compile only a part of the document e.g. the current file, selection, section, environment...

### Expected behavior

The header of the document (everything outside the `document` environment) would be cached into a temporary file inside wich the selection would be placed for quick compilation.

**Comment by James-Yu** [comment]
I'm afraid its a minority request. There are actually LaTeX packages designed to solve this problem.

**Comment by James-Yu** [comment]
Please check out `subfiles` latex package.
