### ISSUE TITLE
[Feature Request] Make Docker image customizable

### ISSUE THREAD

**Issue by lippertmarkus** [James-Yu/LaTeX-Workshop#673]
First of all: Great work @James-Yu and @Arxisos in fully integrating my idea of #302 into this extension. This works great on every plattform. 

Like another user also mentioned in https://github.com/James-Yu/LaTeX-Workshop/issues/302#issuecomment-376923951, some may want to use a specific docker image including e.g. additional tools or a newer texlive version. Of course some could just re-tag a downloaded Docker image to `tianon/latex` to use it via Latex-Workshop, use the "manual way" I described in #302 or use @Arxisos shims (https://github.com/Arxisos/LaTex-Workshop-Docker) - but an option in the settings for configuring this maybe would be even more user friendly.

For the implementation I think the easiest way would be to set an environment variable before executing the scripts for *nix/Windows and using this environment variable in these scripts.

**Comment by James-Yu** [comment]
It seems possible with `${@:2}` replacing `$@` and `$1` as the docker image in the scripts. However I currently do not have access to computers with docker. It may rely on the community effort.

**Comment by James-Yu** [comment]
Will work on this feature. Maybe the docker name can be passed through `envvar`.

**Comment by James-Yu** [comment]
@lippertmarkus @lukasuni if possible please have a check on this commit and see if things work as expected.
