### ISSUE TITLE
Text gets duplicated on Save

### ISSUE THREAD

**Issue by swarnendubiswas** [James-Yu/LaTeX-Workshop#675]
### Description

I have `editor.formatOnSave` enabled. Saving a dirty file (.e.g, bibtex) often duplicates the file contents.

### Log messages

> [20:57:22] Root file remains unchanged from: /home/sbiswas/bitbucket/iitkanpur/proposals/ramanujan-fellowship/proposal.tex.
> [20:57:31] Root file remains unchanged from: /home/sbiswas/bitbucket/iitkanpur/proposals/ramanujan-fellowship/proposal.tex.
> [20:57:42] Root file remains unchanged from: /home/sbiswas/bitbucket/iitkanpur/proposals/ramanujan-fellowship/proposal.tex.
> [20:57:49] Formatted /home/sbiswas/bitbucket/iitkanpur/proposals/proposal.bib
> [20:57:49] Formatted /home/sbiswas/bitbucket/iitkanpur/proposals/proposal.bib
> [20:57:58] Formatted /home/sbiswas/bitbucket/iitkanpur/proposals/proposal.bib
> [20:59:14] Root file remains unchanged from: /home/sbiswas/bitbucket/iitkanpur/proposals/ramanujan-fellowship/proposal.tex.
> [20:59:24] Root file remains unchanged from: /home/sbiswas/bitbucket/iitkanpur/proposals/ramanujan-fellowship/proposal.tex.
> [20:59:25] Root file remains unchanged from: /home/sbiswas/bitbucket/iitkanpur/proposals/ramanujan-fellowship/proposal.tex.

<details>
<summary>Developer Tools Console</summary>
</details>

### How to reproduce

1. Set `editor.formatOnSave: true`. Edit a `.bib` file and save the file.

### Expected behavior

The dirty file would be saved. 

### Actual behavior

The file is saved but the LaTeX text gets duplicated.

### Additional Information

I am able to reproduce the error on multiple systems, CentOS 7.5 and Ubuntu 18.04. My hunch is this issue is related to `editor.formatOnSave` setting.

**Comment by James-Yu** [comment]
Unfortinately, I cannot reproduce the problem. My guess is that you may save the file for multiple times within seconds. `latexindent` is quite slow, so `editor.formatOnSave: true` is not recommended.

User reports confirming this issue are welcomed.

**Comment by swarnendubiswas** [comment]
I can reproduce the issue on multiple machines as I said event after disabling `latexindent` and `editor.formatOnSave`. Are there any logs I can look into?

**Comment by swarnendubiswas** [comment]
```
[22:41:03] File cleaned: /PATH/XXX/main.fdb_latexmk
[22:41:05] Root file remains unchanged from: /PATH/XXX/main.tex.
[22:41:41] Bib file watcher - responding to change in /PATH/XXX/references.bib
[22:41:41] Parsing .bib entries from /PATH/XXX/references.bib
[22:41:41] Parsed 10 .bib entries from /PATH/XXX/references.bib.
[22:41:41] Formatted /PATH/XXX/references.bib
[22:41:41] Formatted /PATH/XXX/references.bib
[22:41:42] Formatted /PATH/XXX/references.bib
[22:41:42] Bib file watcher - responding to change in /PATH/XXX/references.bib
[22:41:42] Parsing .bib entries from /PATH/XXX/references.bib
[22:41:42] Parsed 19 .bib entries from /PATH/XXX/references.bib.
[22:42:01] Root file remains unchanged from: /PATH/XXX/main.tex.
[22:42:16] Root file remains unchanged from: /PATH/XXX/main.tex.
[22:42:18] Root file remains unchanged from: /PATH/XXX/main.tex.
```

Here you can see how the number of .bib entries is getting duplicated when I pasted in a new one. There were 9 initially, went up to 10 after pasting and the first nine get duplicated.

**Comment by ggabriel96** [comment]
I have an almost identical problem. The difference is that it happens after pasting something. So I found this issue and looked through my settings. I had these:

```
"editor.formatOnPaste": true,
"editor.formatOnSave": true,
"editor.formatOnType": true
```

Setting `formatOnPaste` to `false` seems to have solved it for me.

**Comment by swarnendubiswas** [comment]
@ggabriel96 You are right, I face this problem whenever I paste something in `.bib`. Thanks for the suggestion. I already have the following set, but that does not help.
```
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
"[latex]": { 
        "editor.formatOnPaste": false
    }
```

**Comment by ggabriel96** [comment]
@swarnendubiswas what if you replace `latex` with `bibtex`?
