### ISSUE TITLE
Code Helper stuck at 100% when a large BibTeX file is in the directory

### ISSUE THREAD

**Issue by rbost** [James-Yu/LaTeX-Workshop#677]
### Description

I have a very large BibTeX file (approx. 18MB) in the directory of a Latex project (it comes from [here](https://cryptobib.di.ens.fr)) and when I am opening a tex source file using it as its bibliography, VSCode helper process gets stuck at 100%.
Although this could be expected (I think it is ok that LaTeX-Workshop does not support such case), playing with VSCode's files.exclude and files.watcherExclude properties does not affect this behavior (unlike what is described in Microsoft/vscode#11096). 

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

No log message available: this seems to happen during the extension startup, before any log is available.
</details>

<details>
<summary>Developer Tools Console</summary>

Nothing, except the SIGKILL message I had to send to kill the helper.
</details>

### How to reproduce

1. git clone https://github.com/rbost/latex-workshop-cpu.git
2. cd latex-workshop-cpu 
3. git submodule update --init
4. Open the latex-workshop-cpu folder
5. Open the master.tex file
6. Wait for the fans to get noisy

### Expected behavior

My computer does not explodes :)

### Actual behavior

A lot of noise.

### Additional Information

OS X.12
VSCode 1.24.1
LaTeX Workshop 5.5.1

**Comment by James-Yu** [comment]
This can be expected, since the extension opens the `bib` file to parse reference auto-completion items. I will implement a new configuration defining the maximum file size to open.

**Comment by James-Yu** [comment]
Resolved in ba1e417

**Comment by rbost** [comment]
Great!
Also, I realized I was not very clear in my bug report. For me the major issue is that the `files.exclude` and `files.watcherExclude` properties are not taken into account by the parser.
The fact that 5MB+ files are not supported is OK as long as they can be excluded from the set of files to be parsed.

Anyway, ba1e417 fixes this particular bug, so I can creat a separate issue if you want.

**Comment by James-Yu** [comment]
The two referenced configurations are designed to accept `globs` instead of individual files. I am inclined not abusing them, since they mainly concerns "which files and folders to show or hide" in the file explorer.
