### ISSUE TITLE
[Feature request] Better synstax highlight (bold, italic, section...)

### ISSUE THREAD

**Issue by giahung24** [James-Yu/LaTeX-Workshop#678]
Hi, 
Currently, the text in \textbf and \textit has blue color (but not those in \chapter, \section, \subsection).

I don't know if it's possible in vscode. But in SublimeText, they can make bold, italic for text in the \textbf or \textit commands. 
Also for \chapter, \section, \subsection ..., if you can't make it bold, can you change the colors of the inside text at least? 
Thank you.

**Comment by jlelong** [comment]
Syntax highlighting is a two stage process: first, the extension assigns scopes to every piece of text, and then, the theme is responsible for associating colors to some of the scopes. Customizing colors has to be done on the theme side.

The chapter, section, subsection,... titles are matched against the `entity.name.section.latex` scope. You can try to customize it yourself.
