### ISSUE TITLE
Issues with (sub)import and the Latex outline

### ISSUE THREAD

**Issue by rbost** [James-Yu/LaTeX-Workshop#679]
### Description

When using (sub)import, the Latex document's outline is not correctly displayed.
It works perfectly fine with include/input/subfile, but not with the more complex (yet handy) import/subimport commands.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
Parsing path/to/project/master.tex for outline </br>
Parsing path/to/project/included.tex for outline
</details>

<details>
<summary>Developer Tools Console</summary>

Nothing interesting.
</details>

### How to reproduce

1. Create a master.tex file using package import and add a section named "Test Sec"
2. Inside master.tex, call \subimport{content/}{imported.tex}
2. Inside master.tex, call \include{content/included.tex}
3. Create a new directory content and two files named imported.tex and included.tex inside
4. Add a new section in imported.tex named "Imported Sec"
4. Add a new section in included.tex named "Included Sec"

### Expected behavior

The outline shows "Test Sec", "Included Sec" and "Imported Sec".

### Actual behavior

Only "Test Sec" and "Included Sec" appear.

### Additional Information

It is most probably coming from the regex in [this line](https://github.com/James-Yu/LaTeX-Workshop/blob/629902a9aee9a178304561ebc339af3a8cf0abbc/src/providers/outline.ts#L67), which would not parse \subimport.

Note that \import is not supported, but as the syntax is similar to \subimport, adding the support should be easy.

**Comment by jlelong** [comment]
Support for the `subimport` command was added in issue #658. It will be included in the next release.
