### ISSUE TITLE
[Feature Request] Adopt New Vscode Outline

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#680]
### Description
I think VScode's native Outline view is quite extensible now, so instead of cluttering the sidebar with both vscode's `Outline` and Latex Workshop's `Latex Outline`, I believe it would be better do discard `Latex Outline` and mimic its behavior in `Outline`. Other extension developers (Markdown, etc...) have already started doing this.  
Attached is a picture for reference: ![image](https://i.imgur.com/mNdbiO5.png)

**Comment by James-Yu** [comment]
It's a good enhancement of vscode and the extension. However, the API is still subject to changes according to https://github.com/Microsoft/vscode/issues/34968, and I need to evaluate it when ready.

**Comment by jose-a-sa** [comment]
It would be great if you could include \label{}, sections, subsections, etc. together in the same outline view.

**Comment by jose-a-sa** [comment]
A good alternative would be to add a new badge (look into GitLens extensions). 

![screenshot from 2018-07-17 12-20-55](https://user-images.githubusercontent.com/13206784/42814946-bac8f9d8-89bd-11e8-893b-cf593c4eee61.png)

**Comment by Gliptal** [comment]
+1 for the badge, the explorer is already full as it is for large projects.

**Comment by werunom** [comment]
I would also vote for using the new outline. Because, when I have opened markdown file and a tex file simultaneously, there are two outlines in the explorer sidebar - one is the default new outline and the other is the latex outline. With this,  when I swap between a markdown file and a tex file, I have to keep shuffling between two outlines. And in the case of markdown files, there is a redundancy. Attaching a gif for reference...

![peek 2018-08-17 13-53](https://user-images.githubusercontent.com/24664855/44256021-842f9280-a225-11e8-999e-706ff47c7cc8.gif)

**Comment by Astrantia** [comment]
@James-Yu tried the new commit and it's quite broken. With the following document hierarchy :
ROOT TEX (parent)
```
\input{FirstDOC.tex}
\input{secondDOC.tex}
```

**Comment by James-Yu** [comment]
Will check now.

**Comment by Astrantia** [comment]
@James-Yu Did you manage to reproduce the issue?

**Comment by James-Yu** [comment]
To be honest, this is an upstream problem with vscode. Currently the `outline` view does not respect multi-file outline symbols. Seems no workaround is available now.

**Comment by James-Yu** [comment]
You may notice that by default, the outline is sorted by position, which simply breaks on multi-file projects. This is also the reason why the structure is incorrect.

**Comment by Astrantia** [comment]
@James-Yu Thanks for looking into this. Maybe instead of the `outline` view, we can use a Badge webview as suggested by other users?

**Comment by James-Yu** [comment]
That might be the only solution currently. However this involves some refactoring. I'll try finish it in the next few days.

**Comment by Astrantia** [comment]
@James-Yu Great work on the badge in the new release! So far it's been fine, but I have one small feature request if it's possible. Can we add the output pdf in the view of that badge below the structure? Clicking it should open it in pdf viewer or in chrome as set in user preferences.

**Comment by Astrantia** [comment]
Also another suggestion. Currently, when you open vscode in a directory like this:
```
- LatexProject1
– TexFile1
– ...
- LatexProject2
– TexFile2
– ...
```
There is nothing shown in the view. It would be nice to see the structure of projects under 
```
LatexProject1
.
..
...
LatexProject2
.
..
...
```

**Comment by James-Yu** [comment]
It is not possible to add a custom HTML view to the sidebar as far as I'm concerned. Though a list of commands is possible.

As to the second one, there is no plan to support multiple projects in sub-folders. This is related to the workflow of vscode/the extension. Typically one opens each project in an individual workspace. Suppose there is a LaTeX project in a folder which is in the root of another javascript project, which has its `node_modules`. The extension will be struggling to identify the 1000 modules inside.

**Comment by James-Yu** [comment]
Closing this issue for now. Comments and suggestions are welcomed.

**Comment by Astrantia** [comment]
@James-Yu Maybe we could add something like Utils tab in the badge view that will list some common commands:
```
Format Document
Open PDF in Vscode
Open PDF in Chrome
...
```

**Comment by James-Yu** [comment]
Yes that can be a useful feature. I am thinking of a good way to have them presented.

**Comment by Astrantia** [comment]
![image](https://user-images.githubusercontent.com/32885386/45273576-584ca900-b481-11e8-884c-1a9f4471150c.png)
Gitlens has 2 tabs in its view. In our case one can be called Structure and the other can be called ...
