### ISSUE TITLE
Open an arbitrary PDF file directly with the PDF viewer

### ISSUE THREAD

**Issue by smartens** [James-Yu/LaTeX-Workshop#685]
### Description

Instead of right clicking on my PDFs and select "View an arbitrary PDF file", I would prefer that it opens directly with the integrated PDF viewer.

### Expected behavior

Open PDF in the viewer with left click on the file.

### Actual behavior

Left clicking on a PDF opens a new tab with non-readable PDF code.

**Comment by James-Yu** [comment]
Not allowed by vscode API.
