### ISSUE TITLE
Zoom problem in the preview tab

### ISSUE THREAD

**Issue by denis-ko** [James-Yu/LaTeX-Workshop#688]
I experience an issue with zoom behavior in the preview tab.  Sometimes after loosing focus zoom stops working. So I have to either rebuild the project or reopen the preview tab. After looking at similar problems, I think it is an issue with VS Code. Nevertheless, is there a workaround?

**Comment by James-Yu** [comment]
I'm afraid I don't get your idea. What's the problem? How do you zoom?

**Comment by denis-ko** [comment]
OK. Here is the sequence of steps which cause the described problem.

Build TeX file  →   Open the resulting pdf in the preview tab (build-in viewer) → Do some action with the built-in pdf viewer (e.g. select zoom level 300%) → Keep updating the TeX file (pdf viewer looses focus) → Try to change the zoom level.

The last step works sometimes and sometimes it doesn't.  In the second case I have to reopen the preview tab or rebuild the project.
![test](https://user-images.githubusercontent.com/6434317/42332697-88ac5c22-802d-11e8-8507-693c79a7ce91.gif)

**Comment by James-Yu** [comment]
Unfortunately this is related to the pdf viewer we use in the extension, which is really hard to debug. I have to rely on more experienced community to handle the issue as I have no idea why this happens.

**Comment by jlelong** [comment]
This seems to be fixed. @denis-ko, are you still experiencing the problem? If so, please reopen.
