### ISSUE TITLE
Linting with ChkTex erorr

### ISSUE THREAD

**Issue by antomor** [James-Yu/LaTeX-Workshop#69]
Hello, I am not able to use the linting even if:

- the path to tex distribution is correct
- I am able to build the pdf correctly

That's the error I am encountering:
```
[18:02:56] Linter for active file started.
[18:02:56] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m
[18:02:56] Linter for active file failed to spawn command, encountering error: spawn chktex ENOENT
```

Thank you in advance.

**Comment by jabooth** [comment]
Hi @antomor,

Can you let me know which OS you are using?

It seems that `chktex` is not being discovered. How did you configure your path for the tex distribution? A complete copy/paste of your current `latex-workshop.*` entries from your `settings.json` would be really helpful.

And just to clarify, when you say you are able to build a PDF correctly, is that with the building being invoked from within VS Code? 

We will get this sorted! 👍

**Comment by antomor** [comment]
I am using Mac OS X Sierra, maybe you are right. Because even if I have added the texbin path to the system path, I am obliged to write ""/usr/local/texbin/pdflatex" for building.
That's my configuration:
```
"latex-workshop.toolchain": [
    "/usr/local/texbin/pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf %DOC%"
  ],
  "latex-workshop.clean_after_build": false,
  "latex-workshop.linter": false
```

**Comment by jabooth** [comment]
So at least to get this working for you quickly:

1. You'll need to do 
```
  "latex-workshop.linter": true
```
then you will have to customise the path to `chktex` just as you've had to customise for the compile toolchain:
```
    "latex-workshop.linter_command_active_file": [
        "chktex",
        "-wall",
        "-n22",
        "-n30",
        "-e16",
        "-q",
        "-I0",
        "-f%f:%l:%c:%d:%k:%n:%m\n"
    ],
    "latex-workshop.linter_command_root_file": [
        "chktex",
        "-wall",
        "-n22",
        "-n30",
        "-e16",
        "-q",
        "-f%f:%l:%c:%d:%k:%n:%m\n",
        "%DOC%"
    ]
```
Replace out the top `chktex` in both of these arrays with the full path to `chktex`.

You can find that by doing 
```
which chktex
```
in a terminal (guessing from above it might be `/usr/local/texbin/chktex` for you).

The larger issue here I think is that VS Code is not aware of the change in your `$PATH`. You might find a logout/login helps and avoids you having to hardcode this stuff...but at least for now that should work as a band-aid - let us know!

**Comment by antomor** [comment]
It works like a charm!
Thank you very much ;-)

**Comment by jabooth** [comment]
@antomor great!

Would love to hear how you get on with the linting, feel free to come back and post any more issues/suggestions! 👍

**Comment by xiaoFine** [comment]
Hi, I had a similar problem in windows
My configuration is :

```
{
    "latex-workshop.latex.toolchain": [
        {
            "command": "texify",
            "args": [
                "--synctex",
                "--pdf",
                "%DOC%.tex"
            ]
        }
    ],
    "latex-workshop.chktex.enabled": true,
    "latex-workshop.chktex.path": "C:\\Program Files\\MiKTeX 2.9\\miktex\bin\\x64\\chktex",
    "latex-workshop.synctex.path": "C:\\Program Files\\MiKTeX 2.9\\miktex\bin\\x64\\synctex",

    
    "latex-workshop.chktex.args.active": [
        "-wall",
        "-n22",
        "-n30",
        "-e16",
        "-q",
        "-I0",
        "-f%f:%l:%c:%d:%k:%n:%m\n"
    ]
}
```
But still i cannot check  semantic error of .tex files. Is anything wrong with the process? 
Thanks and hope for your response

**Comment by James-Yu** [comment]
@xiaoFine You will not need "-I0" and "-f%f:%l:%c:%d:%k:%n:%m\n" in your argument list.

**Comment by James-Yu** [comment]
In addition, your path `\\miktex\bin\\` seems missed an extra `\` before `\bin`.

**Comment by James-Yu** [comment]
Can you please provide your log? If possible, you may also try the same command in command line `cmd`.

**Comment by xiaoFine** [comment]
@James-Yu  Sorry, I don't know which part is useful so I copied all of the log file,

[Log](https://github.com/xiaoFine/Temp/issues/1)

And `chktex` is available in cmd
```
C:\Users\localxf>chktex
ChkTeX v1.7.6 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with POSIX extended regex support.
ChkTeX comes with ABSOLUTELY NO WARRANTY; details on this and
distribution conditions in the GNU General Public License file.
Type "ChkTeX -h" for help, "ChkTeX -i" for distribution info.
Author: Jens Berger.
Bug reports: https://savannah.nongnu.org/bugs/?group=chktex
             or darthandrus@gmail.com
Press stdin break combination to terminate stdin input.

```

**Comment by James-Yu** [comment]
Can you please give the LaTeX Workshop log which is accessible from the `output` panel of vscode?

**Comment by jabooth** [comment]
This log is only the log from compiling the latex document. If you go to Output in vs code, and choose lasted workshop, you should see the full output...oh @James-Yu has beat me to it haha

**Comment by xiaoFine** [comment]
There is nothing in the Output. I just Build and View, but find it has no feedback when I have semantic error. Do I need to install a LaTex Compiler first?

**Comment by James-Yu** [comment]
@xiaoFine Please create a new issue in this repository with a proper title and contents describing what is expected and what it is now.

In the mean time, what do you mean by semantic error? LaTeX compiler error or chktex error? Screenshots sometimes worth thousands of words.

**Comment by jabooth** [comment]
@xiaoFine yes as @James-Yu a fresh issue makes sense here.

To help you find the output log: 

<img width="861" alt="screenshot 2017-04-12 10 36 44" src="https://cloud.githubusercontent.com/assets/1312873/24951359/081ff5e6-1f6c-11e7-8bce-3be1b19b9df9.png">

Note you will need to go to a .tex file first to load LaTeX Workshop the first time

**Comment by YiHoze** [comment]
Hi,

I made a .plist file like below for the expl syntax.
Whenever the Latex Workshop extension is  updated (too frequently), I have to copy it to the syntax directory.
So if this colorizer is included in  LaTeX.plist or a new file, it'll be great.

```
	<array>	
		<dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.function.expl.latex</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\\)\w+:\w+</string>
            <key>name</key>
            <string>keyword.control.expl.latex</string>
        </dict>
		<dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.key.expl.latex</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\.\w+:\w+</string>
            <key>name</key>
            <string>keyword.control.expl.latex</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.block.expl.latex</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\\)\w+:</string>
            <key>name</key>
            <string>keyword.control.expl.latex</string>
        </dict>     
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.variable.expl.latex</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\\)\w+_\w+</string>
            <key>name</key>
            <string>variable.expl.latex</string>
        </dict>	
		<dict>
			<key>include</key>
			<string>text.tex.latex.memoir</string>
		</dict>
	</array>
```

Thanks
@yihoze
