### ISSUE TITLE
Root file – can’t use \input?

### ISSUE THREAD

**Issue by karbecker** [James-Yu/LaTeX-Workshop#690]
Am I getting this right?

I can’t use `\input{/Users/XXX/Tex/some_header.tex}` because Workshop won’t find my header in which I state `\begin{document}`? And when I use a magic comment like

```
% !TEX root = /Users/XXX/Tex/some_header.tex
```

it tries to build the header?

Other Editors like Texpad are all able to use `\input` and reference from there. Am I missing something in the configuartion? When I copy everything from my header into my document it is built without errors.

Thanks!

**Comment by James-Yu** [comment]
I don't get your idea. Please post a minimal working example.

The extension support `\input`.

**Comment by karbecker** [comment]
If I open a tex file whose preamble is stored in a different folder on my machine and is included via `\input` the root file is not found by LaTeX Workshop. However, if I open this preamble document as well in VSCode, the root file is found.

**Comment by karbecker** [comment]
Nevermind, I changed the order: Now I compile my "header" document containing the preamble and `\include` my "content" document. This way everything works! 

Thank your for the awesome extension!
