### ISSUE TITLE
Outline: never adapts to tab change

### ISSUE THREAD

**Issue by michael-brade** [James-Yu/LaTeX-Workshop#691]
Hi,

I have a workspace with two root files, and several others that are included in one of those. Since LaTeX-Workshop always finds the first one alphabetically, I had to use
```
% !TEX root = root-a.tex
```
for instance. Now, I have a split view with documents of one root in one view, and documents of the other root in the other view. When switching tabs, the logs are just fine, they keep updating with 

```
Found root file by magic comment: root-b.tex
Root file changed from: root-a.tex. Find all dependencies.
Root file changed -> cleaning up old file watcher.
Instatiating new file watcher for ....
```
etc.

However, the LaTeX Outline never changes or updates. I have to actually edit the file and save it, only then will the outline update.

**Comment by innerlee** [comment]
I guess this will be fixed by https://github.com/James-Yu/LaTeX-Workshop/pull/684

**Comment by michael-brade** [comment]
Perfect! That did it, thank you :)
