### ISSUE TITLE
cant find latexindent when use default setting on windows 

### ISSUE THREAD

**Issue by specter119** [James-Yu/LaTeX-Workshop#695]
platform: windows 10
vscode: 1.25.0

already add texlive to %Path%
Keeping  "latex-workshop.latexindent.path" as default, plugin will warn me that latexindent is missing. Work properly if I set "latex-workshop.latexindent.path" to "latexindent.exe"

**Comment by James-Yu** [comment]
I cannot reproduce the problem with exactly the same config on multiple computers. Anyone else confirming the issue?

You may also need to check if `where latexindent` can find anything in CMD as follows:
![image](https://user-images.githubusercontent.com/4210342/42544823-99350ebe-84e6-11e8-907b-6d85f9ae51be.png)
