### ISSUE TITLE
Bibtex toolchain

### ISSUE THREAD

**Issue by Marcelo00** [James-Yu/LaTeX-Workshop#697]
### Description
Run bibtex tool (for code snippet see How to reproduce) fails on 4.14.53-1-MANJARO GNU/Linux with TeX 3.14159265 and Latex Workshop Version 5.6.1.

### Log messages

<details>
<summary>Latex Compiler Output: I couldn't open file name `filename.aux'</summary>
</details>

### How to reproduce

1.  Run pdflatex tool 
`{
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ]
} `
2.  Run bibtex tool 
` {
            "name": "bibtex",
            "command": "bibtex",
            "args": [   
                "%DOCFILE%"
            ]
}`

### Expected behavior

Run bibtex without an error.

### Actual behavior

It seems the .aux file gets deleted and therefore it fails to open the .aux file in order to bibtex.

### Additional Information

The project folder and all the files/folder have 777 premissions.
Running bibtex from terminal is succesfull.

**Comment by jlelong** [comment]
It might be related to `latex-workshop.latex.clean.enabled`, which triggers the clean of all auxiliary files on successful build.

**Comment by Marcelo00** [comment]
This setting is disabled. It has to be something else but I can't figure it out.

**Comment by jlelong** [comment]
I cannot reproduce the error. Feel free to reopen the issue with some more information.

**Comment by tim4431** [comment]
I can reproduce the error,and "latex-workshop.latex.clean.enabled" is set to "never"
the .aux file gets deleted when I run "bibtex" tool

**Comment by tamuratak** [comment]
Open a new issue.

Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)
