### ISSUE TITLE
Automatically close environment

### ISSUE THREAD

**Issue by gennaro-tedesco** [James-Yu/LaTeX-Workshop#698]
### Description

Automatically close` \end{environment)` after `\begin{environment}`

### Additional Information

As per title, is it possible to have a feature to automatically close LaTeX environment? I have not been able to find how to, should this be already present.

**Comment by James-Yu** [comment]
It's not possible to auto-do it. Use the command instead. Restrictions on vscode.

**Comment by nowayhaze** [comment]
@James-Yu Can you expound on this a little more? https://github.com/formulahendry/vscode-auto-close-tag has implements a similar feature, and it has millions of installs, so it can't be that useless or too hacky for vs code. So why isn't this suggestion doable?

**Comment by jlelong** [comment]
The extension provides the command [`latex-workshop.close-env`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#closing-the-current-environment) to automatically close the current environment. You can even define a keybinding for it.

**Comment by nowayhaze** [comment]
Yes, I have that set, but from a UX standpoint, I feel like there should at least be the option of closing the environment first and then continuing with internals without having to manually move the cursor back inside the environment. Maybe something that could achieve what I'm looking for is creating a snippet for something like [`latex-workshop.wrap-env`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#surrounding-selection-with-an-environment) on an empty string and then being able to tab inside after typing the environment name.

**Comment by jlelong** [comment]
It seems the [`\begin` snippet](https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#inserting-an-environment) does precisely what you ask for. if not, open a new issue and describe precisely your use case.
