### ISSUE TITLE
Proposal - auto detect common tex binary paths?

### ISSUE THREAD

**Issue by jabooth** [James-Yu/LaTeX-Workshop#70]
To avoid issues like #69 (which has affected the user for both compilation and linting) I wonder if we could do some basic detection of where we might be able to find the binaries for `pdflatex`/`chktex` etc on a users system even if they aren't on their `$PATH`...

**Comment by James-Yu** [comment]
I think it can be done for `chktex` as it's the only supported linter. As for latex compilers, that might be hard as too many options are provided. What about add a command called `runtime check` and alerts if any command is not in `PATH` and suggest its possible positions?

**Comment by James-Yu** [comment]
#97 PR-ed.
