### ISSUE TITLE
LaTeX Outline: book documentclass (\part{}) is not supported

### ISSUE THREAD

**Issue by michael-brade** [James-Yu/LaTeX-Workshop#702]
This is a short one: LaTeX-Workshop ignores `\part`s of a book in its outline (see `book.cls` or `memoir.cls`). Please implement that additional level of hierarchy :)

PS: `memoir` even supports `\book{}`

**Comment by jlelong** [comment]
Just add `part` to the configuration variable `latex-workshop.view.outline.sections`.
