### ISSUE TITLE
synctex writes down incorrect magnification 

### ISSUE THREAD

**Issue by akk64** [James-Yu/LaTeX-Workshop#703]
### Description

Even if another magnification is set (1200 usually) in TeX document, the information in synctex file says
Output:pdf
Magnification:1000
which implies incorrect navigation in the editor.
(Of course when I change the value to 1200 by hand, the navigation is perfect.)

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce
Start any document with
\magnification 1200
or
\mag 1200

### Expected behavior
in the corresponding synctex file should be
Magnification:1200

### Actual behavior
Magnification:1000
is written instead which probably means that dimensions which should be multiplied by 1.2
are read withou any multiplication.

**Comment by James-Yu** [comment]
synctex.gz is not generated by this extension.
