### ISSUE TITLE
Forward Synctex Doesn't Work

### ISSUE THREAD

**Issue by sulkhanp** [James-Yu/LaTeX-Workshop#707]
### Description

Reverse does, forward doesn't.

### Log messages
<details>
<summary>LaTeX Workshop Output</summary>
<pre>
[13:14:06] Executing synctex with args view,-i,217:8:c:\Users\User\Desktop\Testd\Notes.tex,-o,c:\Users\User\Desktop\Testd\Notes.pdf
[13:14:07] Try to synctex c:\Users\User\Desktop\Testd\Notes.pdf
</pre>
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information
VSCode: 1.26 Insiders
OS: Win10
Ext. Ver.: Latest

**Comment by jlelong** [comment]
It does work on my installation with exactly the same output from the extension.

**Comment by sulkhanp** [comment]
@jlelong can we reopen? I overlooked this error I'm getting when synctex executes:
![image](https://user-images.githubusercontent.com/32885386/43050838-830d26d8-8e20-11e8-8540-60d9af88d64f.png)
