### ISSUE TITLE
Formatting failed with exit code 255

### ISSUE THREAD

**Issue by allenryb** [James-Yu/LaTeX-Workshop#708]
### Description

When I format the following `.tex` file,

```
\documentclass{article}
\begin{document}
\begin{align}
C^\infty (a [bb) a)
\end{align}
\end{document}
```

vscode fails and reminds the following

> Formatting failed. Please refer to LaTeX Workshop Output for details.

<details>
<summary>LaTeX Workshop Output</summary>

[20:07:22] Formatting with arguments -c,e:/RYB/temp/,e:/RYB/temp/__latexindent_temp.tex,-y="defaultIndent: '  '"

[20:07:23] Formatting failed with exit code 255

[20:07:23] stderr: Use of uninitialized value in pattern match (m//) at C:\Users\ADMINI~1\AppData\Local\Temp\par-41646d696e6973747261746f72\cache-02db827ff06080b5f2c6fae22ee75a9f59717f4c\inc\lib/LatexIndent/Arguments.pm line 125.

Can't call method "indent_children_recursively" on unblessed reference at C:\Users\ADMINI~1\AppData\Local\Temp\par-41646d696e6973747261746f72\cache-02db827ff06080b5f2c6fae22ee75a9f59717f4c\inc\lib/LatexIndent/Indent.pm line 270.
</details>

**How can I fix it?**

### Additional Information

Only the line `C^\infty (a [bb) a)` will cause the problem.

If I replace this part by the following code, then the format can do well.

1. `C (a [bb) a)` : delete the symbol `\infty`
2. `C^\infty  [bb)` : delete the outer parenthesis `()`
3. `C^\infty (a [bb] a)` : modify the inner `[bb)` to '[bb]'

In my mind, these codes work for the previous version, but I am not sure about it.

Thanks in advances!

**Comment by James-Yu** [comment]
latexindent throws the error. It is not related to the extension.
