### ISSUE TITLE
Support syntax highlighting for Markdown fenced code blocks of latex

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#710]
### Description

When writing Markdown in VSCode, fenced code blocks with latex does not have syntax highlighting. I.e.
````
```latex
...
```
````
is not highlighted. This would be great to have. I have [been told](https://twitter.com/mattbierner/status/1017118184699133952) this extension is the right place to request it :)

**Comment by James-Yu** [comment]
Unfortunately, we do not support markdown things. The syntax files are in a separate folder, and anyone can feel free to create a standalone extension for it.

**Comment by jlelong** [comment]
It is just a matter of telling the extension to inject the `LaTeX` syntax into VScode markdown support.
On it.

**Comment by gandalfsaxe** [comment]
Sounds great @jlelong! Would like to test it. When will your commit be available in the extension?

**Comment by jlelong** [comment]
You can try the development version by directly cloning the repository. 
If you prefer an official version, @James-Yu is responsible for making new releases.
It is much better if you can test it before it is incorporated in a new release.

**Comment by gandalfsaxe** [comment]
Would be happy to. How do I go from cloned repo to using it with VSCode? Do I need to build anything? No installation notes in README.md. Never really done any Javascript/Angular 😅

**Comment by jlelong** [comment]
Here is how to run the development version of the extension inside VSCode.

1. Install The NodeJS package manager `npm`
1. From the cloned repo, run `npm install`
1. Open the top level directory of the cloned extension inside VSCode
1. Launch the extension through the debugger, see [here](https://code.visualstudio.com/docs/extensions/developing-extensions)
1. Open your files inside the `Extension Development Host` window.

**Comment by GandalfSaxe** [comment]
Can confirm that it works for me 👍 Thanks!

**Comment by felixfbecker** [comment]
It would be nice if this also worked for embedded Latex math expressions (`$`) in markdown (e.g. MacDown is an app that can render this).

**Comment by Mike-Now** [comment]
It would be a good idea to also catch { } brackets in the fenced block.
````
  ``` latex {smth=3}
  ```
`````

**Comment by jlelong** [comment]
It can be done but just to be sure what is the purpose of the extra `{....}` block, in particular does `{smth=3}` mean?

**Comment by Mike-Now** [comment]
I'm using this extension: https://github.com/shd101wyy/markdown-preview-enhanced . 
Additional parameters are used to run code chunks to render TikZ graphs.
for example:

````
```latex {cmd=true hide=true}
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{matrix}
\begin{document}
\begin{tikzpicture}
  \matrix (m) [matrix of math nodes,row sep=3em,column sep=4em,minimum width=2em]
  {
     F & B \\
      & A \\};
  \path[-stealth]
    (m-1-1) edge node [above] {$\beta$} (m-1-2)
    (m-1-2) edge node [right] {$\rho$} (m-2-2)
    (m-1-1) edge node [left] {$\alpha$} (m-2-2);
\end{tikzpicture}
\end{document}
```
````
