### ISSUE TITLE
Synctex Keybinding/Keymapping

### ISSUE THREAD

**Issue by tabedzki** [James-Yu/LaTeX-Workshop#712]
Hi James,

First off, this is a fantastic extension for VS Code and because of this I am using VS Code as my primary LaTeX editor. One request that I would like to a way to bind other LaTeX commands (and if that is a feature natively for it to mentioned in a more prominent place); the main thing I would like to bind is the synctex command from the editor side so that way I can easily see where the text is in the pdf without using the mouse or the context menu, although I can see being able to bind all LaTeX commands as a useful feature.

Thank you in advance.

**Comment by James-Yu** [comment]
It is possible through the default vscode key binding. All latex-workshop commands are available for binding.

**Comment by tabedzki** [comment]
Where can that be done? I went to the keybindings.json and used autocomplete to suggest all the possible options for the "command" option and nothing resembling latex-workshop showed up as an option.

**Comment by jlelong** [comment]
Open a latex file to make sure the extension is fully loaded. Then, go to the __Keyboard Shortcuts__ menu and search for `latex-workshop`.

**Comment by tabedzki** [comment]
Ahhh that help. I also noticed that I had to first disable the Vim extension before getting it to work. Sorry about that. I am curious as to why Vim prevents the latex-workshop commands from loading but not from executing. I was able to run the stuff even though I re-enabled the vim command with the new hotkey set.
