### ISSUE TITLE
200% surge of CPU workload

### ISSUE THREAD

**Issue by jtschneider** [James-Yu/LaTeX-Workshop#713]
### Description

I encounter a massive 200% surge in CPU workload upon opening a latex project folder with classicthesis.

### Log messages

- LaTeX Workshop Output can be found in [this gist](https://gist.github.com/jtschneider/7c9b422a59634c36498c3dd138ddb8b9)
- Developer Tools Console Output can be found in [this gist](https://gist.github.com/jtschneider/dc756b9c86b84505bbe5c0ec956e2c2b)

### How to reproduce

1. Open a LaTeX project folder with [classisthesis](https://www.ctan.org/pkg/classicthesis) being used 

(perhaps there might be a second way to reproduce this bug)

### Expected behavior

I expected to not have a 200% surge in CPU usage...

### Actual behavior

I now know what 100% fan power sounds like and watching your battery drain looks like. 😄

**Comment by jtschneider** [comment]
From the VS-Code process explorer:

|---------|----------------------|-------|---------------------------------------------------------| 
| CPU (%) | RAM (MB) | PID   | Name                                                    | 
| 16      | 106                  | 31073 | code main                                               | 
| 6       | 90                   | 31074 |      gpu-process                                        | 
| 17      | 270                  | 31075 |      window ({{some file}}.tex — Thesis)                | 
| 99      | 147                  | 31113 |          extensionHost                                  | 
| 0       | 82                   | 31119 |              electron_node server.js                    | 
| 0       | 25                   | 31124 |              electron_node jsonServerMain.js            | 
| 0       | 33                   | 31114 |          watcherService                                 | 
| 0       | 25                   | 31118 |          searchService                                  | 
| 0       | 33                   | 31637 |          terminal                                       | 
| 0       | 0                    | 31638 |              /bin/bash -l                               | 
| 0       | 66                   | 31115 |      shared-process                                     | 
| 8       | 74                   | 31708 |      window (Prozess-Explorer)                          | 
| 0       | 0                    | 31801 |          /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command= | 


I'm sad because I would like to use the great functionality of this great latex extension. However, this issue renders the extension useless for me... 😢

**Comment by jtschneider** [comment]
Note the 200% surge comes from the fact that I somehow have a second process(Code Helper) (which I found in the activity monitor of mac OS) which drains my CPU

**Comment by jlelong** [comment]
Can you post a gist with a minimal example reproducing the problem?

**Comment by jtschneider** [comment]
[main.tex](https://gist.github.com/jtschneider/00a6bfe9268bdb459f7d534c42c93b9d)
[classicthesis-config.tex](https://gist.github.com/jtschneider/42adcf4dcf097393071bc0d443e26e02)
and lastly the [classithesis.sty](https://gist.github.com/jtschneider/952fafdc5afcf35911a930d58f8da6f3) originally from CTAN (cf. https://ctan.org/pkg/classicthesis)

**Comment by James-Yu** [comment]
It seems that the fifth line in your config.tex is causing problem. Will check how to fix soon.

**Comment by jtschneider** [comment]
Lovely! When is this going to affect the version I obtain from the VS Code Marketplace?

**Comment by jlelong** [comment]
As pointed by @James-Yu, just remove line 5 of `classicthesis-config.tex` and everything will be fine for you.

You are right more lines need to be patched to really ignore comments. On it.
