### ISSUE TITLE
Compiler log does not show properly

### ISSUE THREAD

**Issue by giahung24** [James-Yu/LaTeX-Workshop#715]
### Description
Hi,
I don't know since when my Latex compiler output (when there are errors) doesn't display all the message (on each line). Anyone has the same problem?

### Log messages

<details>
<summary>LaTeX Compiler Output</summary>
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit)

entering extended mode

Chapters/Chapter03.tex:403: 

Chapters/Chapter03.tex:403: 

Chapters/Chapter03.tex:405: Please use 

Chapters/Chapter03.tex:405: You can't use `

Chapters/Chapter03.tex:405: Double superscript

</details>

<details>
<summary>LaTeX Workshop Output</summary>
[23:53:46] Recipe step 1: pdflatex, -synctex=1,-interaction=batchmode,-file-line-error,c:/Users/Jean/Dropbox/1. Doctorat/! These manuscript/main

[23:53:52] Recipe returns with error: 1/null.
</details>

**Comment by jlelong** [comment]
Are the logs correct when directly running `pdflatex`?
Can you try without the `!` in `/Users/Jean/Dropbox/1. Doctorat/! These manuscript/main`?

**Comment by giahung24** [comment]
Ah, it was my bad. 
I have used the option `-interactivemode=batchmode` for pdflatex, and if I run directly on terminal, the error messages are still missing. I must set `-interactivemode=nonstopmode` to have the correct log.
It's not a bug of LatexWorkshop (sorry!).

But do you know why there is this bug of pdflatex ?

For example, I insert directly the β symbol in the text, with `nonstopmode`, it can show the error : 

```
Chapters/Chapter03.tex:478: Package inputenc Error: Unicode char β (U+3B2)   (inputenc)                not set up for use with LaTeX.
```
But with `batchmode`, the log is just: 

`Chapters/Chapter03.tex:478: `

And also, LatexWorkshop can parse error only with `nonstopmode`.
