### ISSUE TITLE
PDF viewing doesn't work

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#717]
### Description

I can't view PDF files, only mangled PDF source code is displayed.

### How to reproduce

1. Open any PDF file

### Expected behavior

Viewing PDF file like one would in a dedicated PDF viewer.

### Actual behavior

If I open a PDF it says:

> The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?

If I click yes, this is what I see:

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/12127864/43063299-ba733bcc-8e5b-11e8-9c0f-a6df05b02458.png">

### Additional Information

Tried on both macOS and Windows.

**Comment by James-Yu** [comment]
Right click the file and select view PDF. Left click not supported by vscode.

**Comment by GandalfSaxe** [comment]
Are you sure? [vscode-pdf](https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf) opens PDF normally fine without having to right click .

**Comment by James-Yu** [comment]
yes.

**Comment by GandalfSaxe** [comment]
But then how does vscode-pdf do it? You should be able to implement whatever they're doing?

**Comment by James-Yu** [comment]
The extension used a dirty hack. That's why you will see a garbled document before showing the pdf.

Will look into it.

**Comment by GandalfSaxe** [comment]
Well 0.2 seconds of garbled document beats having to use a custom way of opening PDF files IMO - that is when it works 🙂 

To illustrate how fast it is on smaller PDFs:

![](https://i.imgur.com/wZe5A8G.gif)

After it's cached when it's been opened already, you can't even see it anymore:

![](https://i.imgur.com/uCGyrXb.gif)

On bigger PDFs, it takes longer to load from the garbled document, but still less than a second. I think it works well.

However some PDFs require me to confirm opening with the text every time as I noted in tomoki1207/vscode-pdfviewer/issues/26. Perhaps that can be solved in time. Illustration:

![](https://i.imgur.com/lApDPAV.gif)

**Comment by GandalfSaxe** [comment]
Meanwhile, is a way to suppress this particular warning?

<img width="459" alt="image" src="https://user-images.githubusercontent.com/12127864/43069486-7e65c71e-8e6d-11e8-999b-d444cdb8e639.png">

**Comment by ahuglajbclajep** [comment]
I feel that using the [custom text editor API](https://code.visualstudio.com/updates/v1_44#_custom-text-editors), like [vscode-hexeditor](https://github.com/microsoft/vscode-hexeditor), would be a smart solution to this problem.
See also: https://code.visualstudio.com/updates/v1_44#_workbencheditorassociations-setting

**Comment by tamuratak** [comment]
Please stop writing a message to an old closed issue.

I know the API.
