### ISSUE TITLE
[Feature Request] Automatically add a new item to lists when pressing return

### ISSUE THREAD

**Issue by MirkoLenz** [James-Yu/LaTeX-Workshop#719]
### Description

When editing a list environment in Latex (e.g. `itemize`, `enumerate` or `description`), it would be very helpful if a new `\item`-Element would automatically be added upon pressing the `return` key. This feature can be found for example in VSCode’s popular Markdown extension or in LaTeXTools for Sublime Text.

Additionally, the current behaviour (i.e. only inserting a new line and not creating a new `\item`) should be retained when pressing `alt+return`. This feature can also be found in the tools mentioned above.

If the current line is an item with square brackets, a new `\item[]` should be inserted and the cursor should be within the square brackets. After pressing `tab`, the cursor should be behind the item. I think this should not depend on the outer environment (e.g. `description`), but instead on the contents of the current line. It might be the case that one needs custom list items within an itemize environment.

I really appreciate all your work regarding this extension (it made me switch from Sublime Text) and hope that this feature can be implemented.

### Current Behaviour

```latex
\begin{itemize}
    \item Item 1
    CURSOR
\end{itemize}

\begin{description}
    \item[Desc 1] Item 1
    CURSOR
\end{description}
```

### Proposed Behaviour

```latex
\begin{itemize}
    \item Item 1
    \item CURSOR
\end{itemize}

\begin{description}
    \item[Desc 1] Item 1
    \item[CURSOR] CURSOR_AFTER_TAB
\end{description}
```

**Comment by jlelong** [comment]
See the last entry of the *Features* section in the README file.
