### ISSUE TITLE
Make settings compatible with the new settings UI [Feature  REQ]

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#722]
![image](https://user-images.githubusercontent.com/32885386/43259413-1b86a678-90e7-11e8-9754-886ad59f18d2.png)
![image](https://user-images.githubusercontent.com/32885386/43259428-276a62ae-90e7-11e8-8250-17db96b513ae.png)

I guess not all of the settings will be convertible, but a lot of current settings could be adapted to be edited within the new UI rather than from the json. Ideally, I would like to see a custom Latex Workshop settings UI (GitLens and others already have one)

**Comment by James-Yu** [comment]
What is this?

**Comment by James-Yu** [comment]
While the config GUI goes live in the current version, it seems that MS reserved a lot of UIs for built-in configs. The shown `Add Pattern` is among them. I have tried to use the same data structure as `files.exclude` but cannot produce the same effect. Even built-in items have different patterns:
![image](https://user-images.githubusercontent.com/4210342/45207525-c135f480-b2ba-11e8-97f4-29c046645f61.png)
I'll keep an eye on it and see what we can do to make it better.

**Comment by James-Yu** [comment]
Unfortunately, there's no way for an extension to make use of the customized UI. In the commit, all descriptions are changed to markdownDescription, so that quotes can be properly displayed. Other than that, we cannot do anything to enhance the UI.
