### ISSUE TITLE
Ignore some Warnings

### ISSUE THREAD

**Issue by alexanderadam** [James-Yu/LaTeX-Workshop#729]
### Description

In most of the LaTeX projects I know are some warnings that appear in the "PROBLEMS" tab that definitely won't be solved because they are "accepted" and not really bad (like `Underfull \hbox`). It would be nice if it would be possible to ignore messages with a certain regex, to improve readability and remove warnings that I'm not interested in per default in the extension.

### How to reproduce

1. Have a project with not-so-bad warnings

### Expected behaviour

Having a possibility to ignore them

### Actual behaviour

Not having such possibility

**Comment by James-Yu** [comment]
Box warnings can be ignored in a newly added config item.

**Comment by alexanderadam** [comment]
Thank you for responding so fast @James-Yu,

can you point me to the relevant documentation or the name of the necessary config item please?

Thank you in advance!

**Comment by James-Yu** [comment]
`latex-workshop.message.badbox.show`

**Comment by alexanderadam** [comment]
Awesome, thnank you!

**Comment by asberk** [comment]
Hi @James-Yu , 
I have non-hbox-related "Problems" that I would like to suppress. Specifically, things like: "Token not allowed in a PDF string (PDFDocEncoding)…". Is there an easy way to get LaTeX-Workshop to ignore these? It looks like #701 is only a partial fix to the issue raised in this thread.

**Comment by tamuratak** [comment]
https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessagelatexlogexclude
