### ISSUE TITLE
Bugs in detection of "Problems" from pdftex output

### ISSUE THREAD

**Issue by philipstarkey** [James-Yu/LaTeX-Workshop#730]
### Description

The "Problems" tab in VSCode displays errors/warnings/info from the console output of pdfTex. I've discovered some situations where this is not correctly determined, which I assume is down to bugs in the regex expressions in /src/components/parser.ts (but I could be wrong!)

1. The first issue is to do with LaTeX Package Warnings. These seem to be printed to the console with a double space between Package and Warning (as in: "Package&nbsp;&nbsp;Warning") and do not show up at all in the "problems" tab. I believe this is a recent regression as they used to show up (but I'm not sure when it happened because I've been lax in updating my VSCode and Extensions).

2. If an underfull/overfull warning ends with a "-", then it seems to ignore all other warnings/errors/info until the next page. I provide an example of some of the console output that causes this below.
### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

    Overfull \hbox (4.13475pt too wide) in paragraph at lines 549--549
    []|\OT1/cmr/bx/n/6 Manufacturer| 

    Underfull \hbox (badness 10000) in paragraph at lines 552--552
    []\OT1/cmr/m/n/6 (additional 2 software-

    LaTeX Warning: This never shows up in the problems tab

    LaTeX Warning: Neither does this

</details>

<details>
<summary>Developer Tools Console</summary>
Nothing of importance
</details>

### How to reproduce

I haven't produced a minimal working example to reproduce this and I'd rather not copy paste the contents of my LaTeX file as I don't want to share the content right now.

However, if this is not enough information for you to reproduce I can put the time in to produce a minimal working example.

### Expected behavior

The two warnings that follow the underfull notice should show up in the problems tab

### Actual behavior

The two warnings that follow the undefull notice do not show up in the problems tab.

### Additional Information

I'm using pdfTex Version 3.14159265-2.6-1.40.19 (MikTeX 2.9.6630 64-bit) on Windows 10.
I'm using LaTeX Workshop v5.6.0
I'm using Visual Studio Code 1.23.1

**Comment by philipstarkey** [comment]
An additional edge case:

3. If a LaTeX Warning contains two dashes, without any spaces separating them, and the first dash is preceeded by something that is not a space, then the warning does not show up in the "Problems" tab. For example, any LaTeX Warning with the following text in it does not show up:

- side-by-side
- side-by- side

However, if it was formatted like the following, then it would show up:

- side -by-side
- side- by-side
- side-by -side

**Comment by jlelong** [comment]
A minimal example would really help to analyze what is wrong with the parser and to test new regex. I do not think we can work on the problem without being able to reproduce it.

**Comment by philipstarkey** [comment]
Ok, I've attached a .tex and .bib file that should demonstrate the issues. Some further insight I gained while producing the example:

- Issue 1 happens when you don't specify a package name (which explains the double space). I guess that was my mistake...but I'd think it would be good to show them in the list of problems anyway

- Issue 2: The warnings/etc. don't actually vanish like I thought, they just show up under a category in the problems tab with a filename that doesn't exist (the filename seems to have been drawn from an earlier log line, but corresponds to a part of the text).

- Issue 3 happens due to the way the messages in the terminal are wrapped over multiple lines. I'm not sure what is doing the wrapping (LaTeX Workshop, pdftex or VS Code) and I don't know if it varies by platform (but probably not since it's 80 characters). This issue is triggered when a terminal line ends with a "-", and for some reason the whole message vanishes from the problems tab. Note that I've demonstrated this in the attached .tex file for a faked "LaTeX Warning" however I also confirmed the issue exists for package warnings that are the correct length such that the "-" is the last character on the line.

I hope that helps! Please let me know if you need further information.

Terminal output from compilation:
```
75 language(s) loaded.
(C:\Users\Phil\AppData\Roaming\MiKTeX\2.9\tex\latex\memoir\memoir.cls
Document Class: memoir 2018/04/04 v3.7g configurable book, report, article docu
ment class
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")
(C:\Users\Phil\AppData\Roaming\MiKTeX\2.9\tex\latex\ifetex\ifetex.sty
(C:\Users\Phil\AppData\Roaming\MiKTeX\2.9\tex\plain\ifetex\ifetex.tex))
("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifluatex.sty")
(C:\Users\Phil\AppData\Roaming\MiKTeX\2.9\tex\latex\memoir\mem10.clo))

LaTeX Warning: Unused global option(s):
    [10.5pt].

(main.aux)

Package Package Warning: This shows up in the list of problems on input line 9.



Package  Warning: This doesn't show up in the list of problems on input line 12
.


Underfull \hbox (badness 10000) in paragraph at lines 21--21
[]\OT1/cmr/m/n/6 (additional 2 blah-blah

Underfull \hbox (badness 10000) in paragraph at lines 22--22
[]\OT1/cmr/m/n/6 4-12 blah blah blah

Package Asd Warning: This shows up in the list of problems, but under a headnig
 for a file that doesn't exist on input line 28.


LaTeX Warning: TODO Note [This doesn't show up in the list of problems 33 side-
by-side blah blah blah] still in text on input line 31.


Package package Warning: This doesn't show up in the list of problems 344 side-
by-side blah blah blah on input line 32.

(main.bbl [1{C:/Users/Phil/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
[2]
bibitemlist
) [3] (main.aux) )
(see the transcript file for additional information)<C:/Program Files/MiKTeX 2.
9/fonts/type1/public/amsfonts/cm/cmbx12.pfb><C:/Program Files/MiKTeX 2.9/fonts/
type1/public/amsfonts/cm/cmr10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/pub
lic/amsfonts/cm/cmr6.pfb>
Output written on main.pdf (3 pages, 42347 bytes).
SyncTeX written on main.synctex.gz.
Transcript written on main.log.
```

Example showing the warnings under an invalid file:
![problems](https://user-images.githubusercontent.com/2508881/43870903-4aac2a28-9bbd-11e8-92c8-a87f21fca818.png)

minimal working example:
[main.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2272388/main.zip)

**Comment by jlelong** [comment]
Thanks for the example. I will look into it.

**Comment by James-Yu** [comment]
Sorry for an off-topic plugin. I have been busy working on my IRL job application and ddls in the past few months. May have to take an AFK for few weeks. Will turn back to the extension right after that! @jlelong

**Comment by jlelong** [comment]
The main problem in parsing `(pdf)latex` logs is that their standard output is hard wrapped to 80 characters, no matter the OS. This can be changed
- by tweaking configuration files (see [here](https://tex.stackexchange.com/questions/384133/how-to-set-environment-variables-for-tex-in-latexmk))
- by adding extra arguments to the command line but this approach varies with the OS.

Currently, LaTeX-Workshop tries to recover the unwrapped output. In cas there are future problems related to this, here is a summary of what i changed:
- Lines ending in `-` are considered as hard wrapped lines.
- A line following an overfull/underfull box warning is ignored as it is mainly garbage but interferes with the computation of the LaTeX files stack.
