### ISSUE TITLE
a setting to disable automatic parsing of .tex files in the workspace.

### ISSUE THREAD

**Issue by davydden** [James-Yu/LaTeX-Workshop#731]
### Description

it appears that LeTeX-Workshop automatically searches for all `*.tex` files in the workspace and tries to parse them. I would like to be able to disable this feature. I usually have a mix-bag workspaces (C++/Python/LaTeX) and would prefer not to spend any resources to parse random `*.tex` files I never plan to compile but they happen to be in C++/Python projects' folders.

### Log messages

```
[09:16:25] Parsing <path/to/something/.../some.tex>
```

### How to reproduce

1. add another project to workspace which happen to have `*.tex` file.
2. call `Build LaTeX` from some other `*.tex` file in a different folder.

### Expected behavior

LaTeX workshop should not parse each and every `*.tex` file it finds in the workspace.

### Actual behavior

there appears to be a background process that looks for all `*.tex` files in the workspace folders and parse them.

### Additional Information

nothing special.

**Comment by James-Yu** [comment]
Actually it only parses tex files in the latex project, which is imported/input in the root file.

It does not cost much to parse files at least.

**Comment by davydden** [comment]
> Actually it only parses tex files in the latex project, which is imported/input in the root file.

now, that's not the case. I open and edit a several `*.tex` files and `LaTeX-Workshop` picks up some completely unrelated `*.tex` files from elsewhere, like installation prefixes of libraries.

**Comment by James-Yu** [comment]
Please provide a minimal working example.

**Comment by davydden** [comment]
> Please provide a minimal working example.

see `how to reproduce`.

**Comment by davydden** [comment]
> only parses tex files in the latex project

a bit off-topic, but AFAIK there is nothing like `latex project` in VSCode, you just have a workspace with folders added. At least I don't mark those folders as being C++, Python  or LaTeX projects anyhow. That's also because sometimes they contain all of those inside a single project.

**Comment by solidxsnake** [comment]
Why was this closed? I would also like to disable automatic parsing. This makes VSCode unusable for the particular project I'm working on (which can easily have tens to over a hundred .tex files, which are all auto-generated from templates). Any time I modify any of the templates, VSCode starts to parse all of the .tex files in my workspace. I'd prefer it not parse them at all, or perhaps having an option to exclude/include specific directories for parsing.

**Comment by gusbemacbe** [comment]
I also would like to disable automatic complying, because it is too boring while I am writing and saving many times

**Comment by jlelong** [comment]
@gusbemacbe your point has nothing to do with the problem. Just set `latex-workshop.latex.autoBuild.onSave.enabled` to `false`.

**Comment by dbogatov** [comment]
Interestingly, I want quite the opposite.
https://github.com/James-Yu/LaTeX-Workshop/issues/1153

**Comment by jlelong** [comment]
@davydden we have not had much time to work on this but I am feeling that this is the right time to handle this while working on PR #1199 .
Just to make things crystal clear, LaTeX-Workshop parses all `.tex` in the workspace to determine the root file and then all the included `.tex` files. When no root file can be determined, almost no LW feature works: in particular, no intellisense, no building, no outline. 

Rather than a setting to completely disable parsing, I am considering adding an exclude directory mechanism to explicitly disable parsing `.tex` in these directories. 

Any comment on that?

**Comment by davydden** [comment]
> Rather than a setting to completely disable parsing, I am considering adding an exclude directory mechanism to explicitly disable parsing .tex in these directories.

That would work for me. Alternative is to limit parsing to certain folders in the workspace. If this is empty, complete workspace is parsed.

**Comment by dbogatov** [comment]
If you do this anyway, why can’t you also include #1153 ?
No all workspaces have clear static root. 
Let me define the folder/pattern of force parsing.

**Comment by jlelong** [comment]
@dbogatov Let's talk about #1153 in #1553 to keep things clear.

@davydden I am hesitating between using an inclusion mechanism and an exclusion one. Not sure, which one is the easiest to use. Maybe, a list of directories or glob patterns to include is easier to define in practice.

**Comment by davydden** [comment]
> a list of directories or glob patterns to include is easier to define in practice.

I would say so.

**Comment by gusbemacbe** [comment]
@jlelong 

Finally! I waited for months! Thank you a lot ! :tada:
