### ISSUE TITLE
Variables in output dir [Feature Req]

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#733]
Hi. In my workspace I have several different latex projects and I don't want to save all of them in `./dist`. Rather, in my recipe, I set build-dir to be `%DOC%`, which enables me to save each project to their own named folders. E.g, if i'm compiling Project1.tex, the output will be saved to ./Project1. However, this, as it seems to me, is not supported by `Latex-workshop.Latex: Output Dir` as it doesn't accept `./%DOC%` as a valid path.

**Comment by jlelong** [comment]
Hum, if I understand everything correctly, you need two things:
1. Tell `latexmk` to put all the generated files in a dedicated directory by using the `-outdir` flag, `%DOC%` in your case. This should already be working.
1. Tell the extension that the `.pdf` and `synctex` files are located in that directory. This is the purpose of `latex-workshop.latex.outputDir`.

I can make 2. work.

**Comment by Astrantia** [comment]
@jlelong Isn't that effectively hard-coding the path for `.pdf` and `synctex` in `latex-workshop.latex.outputDir`? I don't want to set `latex-workshop.latex.outputDir: 'ThisIsMyProjectName'` because when I'm in another folder outputDir will not update. Instead I'm asking for `latex-workshop.latex.outputDir: %DOC%`, which would automatically detect the folder for me.

**Comment by jlelong** [comment]
I precisely meant make `latex-workshop.latex.outputDir: %DOC%` work. Sorry for the misunderstanding.

**Comment by Astrantia** [comment]
@jlelong `"latex-workshop.latex.outputDir": "%DOC%"` This is what I have entered in my settings and it doesn't work now. What do you mean by `you can make it work`? Do you mean you can implement that feature or that it works for you now?

**Comment by jlelong** [comment]
Now, everything should work as you expected. Can you test it?
