### ISSUE TITLE
LaTeX-Workshop warnings in citations that are present (using %!TEX root)

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#734]
### Description

If I cite a reference from a `.bib` file in a file that points to a master tex file with `%!TEX root = master.tex`, then I get warnings of citation being undefined. However it builds fine to the PDF with no reference issues.

### How to reproduce

1. Have a `library.bib` file with an item called `test`
2. Have a `master.tex` file with the line `\include{chapter.tex}` and `\addbibresource{library.bib}`
3. Have a file `chapter.tex` with line on top: `%!TEX root = master.tex`
4. In `chapter.tex` use command `\cite{test}` and receive warning.

### Expected behavior

No warning on undefined citation.

### Actual behavior

Warning on undefined citation.

**Comment by James-Yu** [comment]
Warnings about `bibitem` is generated by your latex compile in the latex log. The extension does not explicitly parse `bib` files for warnings.

**Comment by GandalfSaxe** [comment]
Ok. Any suggestions of how this situation can be solved then? The thing is, it didn't happen with SublimeText with LaTeXTools extension.

**Comment by James-Yu** [comment]
Can you please provide a minimal working example? The above description seems not sufficient to reproduce the problem. Please include your recipe settings too.

**Comment by GandalfSaxe** [comment]
Hmm I'm having trouble reproducing it in a barebones minimal example myself. I'll dig deeper when I have time and write back here what the problem was / is.

**Comment by GandalfSaxe** [comment]
It's not a minimal example, but here is the project if you want to give it a spin: https://transfer.sh/CPdjU/citation-error.zip

There are tons of "citation undefined" error, despite the PDF file containing all references correctly.

**Comment by GandalfSaxe** [comment]
Actually this is a somewhat minimal example; it's the template which many of the students at my university uses for their Bsc/MSc/PhD theses: https://bitbucket.org/_laursen/laursens-xelatex-thesis-template/downloads/

If you download it and run it as-is, then it complains that some references are not found, even though that clearly not the case.

**Comment by GandalfSaxe** [comment]
Here is the output in VSCode using LaTeX-Workshop, after running twice:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/12127864/44660212-3fff7780-aa07-11e8-9293-4938589209d1.png">

Here is the output in SublimeText 3 using LaTeXTools, after running twice:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12127864/44660227-50175700-aa07-11e8-8b89-7af9ed5c5171.png">

I.e. only LaTeX-Workshop for VSCode gives errors of undefined reference. This is the just downloading the [template](https://bitbucket.org/_laursen/laursens-xelatex-thesis-template/downloads/) I mentioned and running it out of the box.

What is the cause of this? Can it be fixed? Any suggestions?

**Comment by GandalfSaxe** [comment]
Never mind, it seems like the issue goes away if you wait long enough and/or compile multiple times (which shouldn't be necessary since LaTeX Workshop uses `latexmk` as default). Anyway I think it's actually not an issue! Will post again if I find otherwise.

**Comment by GandalfSaxe** [comment]
If I mouse over the so-called "undefined reference" it even pulls in information about it from the .bib file! So obviously it can see the reference. What is going on?

<img width="352" alt="image" src="https://user-images.githubusercontent.com/12127864/44731697-12d4c700-aae4-11e8-9ba3-d2c09f1e46ce.png">

**Comment by GandalfSaxe** [comment]
Solved, see #764.
