### ISSUE TITLE
LaTeX Outline is incomplete when formatted code is embedded

### ISSUE THREAD

**Issue by alexanderadam** [James-Yu/LaTeX-Workshop#735]
### Description

It looks like a regular expression isn't greedy enough

The line
```
\section{Libraries (\texttt{./lib})}%
```

results in `Libraries (\texttt{./lib`, so I guess it just stops at the first `}`.

### How to reproduce

1. Type or copy the line above

### Expected behaviour

having either `Libraries (\texttt{./lib})`, or, if you are brave, ignore/interpret the formatting and show `Libraries (./lib)`.

### Actual behaviour

it shows `Libraries (\texttt{./lib`.

**Comment by jlelong** [comment]
Duplicate of #696. Already fixed in `master` branch, will be integrated in the next release.
