### ISSUE TITLE
there is no "View PDF" when I right click

### ISSUE THREAD

**Issue by jokervTv** [James-Yu/LaTeX-Workshop#737]
hello,

When I right click on the file in the explorer, I can't see "View PDF", but I can still view the pdf file by use shortcut key.  Reinstall can't make it work well.

Best wish with you.

**Comment by VanessaLange** [comment]
Same for me. Last time I needed the feature was roughly a month ago and it still worked.
I am using Visual Studio Code Version 1.25.1 (1.25.1) on MacOS.

**Comment by James-Yu** [comment]
Because the behavior is changed to `left click the pdf and viola`. If the pdf does not show up, please report with anything suspicious.
