### ISSUE TITLE
Line preceded by ENTER does not move

### ISSUE THREAD

**Issue by dslemusp** [James-Yu/LaTeX-Workshop#740]
### Description

When trying to move first (or any) line with enter to enter text above it, cursor goes to the next line leaving the text static in first line. It only happens with tex files!

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Create an empty tex file
2. Write text in first line
3. Place cursor in line 1 col 1 and hit ENTER.

### Expected behavior

Text in line 1 should move to line 2.

### Actual behavior

Instead cursor moves to an empty line 2 while text remains in line 1.

**Comment by dslemusp** [comment]
Hi @James-Yu, thx for your quick reply. I think it might be an extension related issue as it does not happen with other file extensions in vscode, only with tex files. In fact creating a new empty file shows the expected behavior, but once it is saved as .tex the linebreak does not work properly.

**Comment by James-Yu** [comment]
Thanks. I can reproduce the problem. Will look into it right now.

**Comment by James-Yu** [comment]
Fixed in 669dbe2 and version 5.8.1
