### ISSUE TITLE
A bug while pressing Enter.

### ISSUE THREAD

**Issue by hxp1999** [James-Yu/LaTeX-Workshop#741]
### Description

The LaTeX-Workshop is updated to 5.8.0 today, then there is a bug happend.  
If I press Enter in front of some words, the character after the cursor will not be in the next line.

### Detail
1. Press Enter here.
![image](https://user-images.githubusercontent.com/20153079/44138827-c15a00c0-a0a7-11e8-820b-bf02c0c827c3.png)
2. the result
![image](https://user-images.githubusercontent.com/20153079/44138871-e66fb350-a0a7-11e8-970a-a32612f310f2.png)

### Additional Information
It only happen in tex file which is associated with LaTeX-Workshop 5.8.0.

**Comment by James-Yu** [comment]
#740

**Comment by hxp1999** [comment]
Thanks, it was fixed.
