### ISSUE TITLE
Build on save of latex files with other extensions, e.g., .tikz

### ISSUE THREAD

**Issue by l0calh05t** [James-Yu/LaTeX-Workshop#743]
### Description

The [tikzscale](https://ctan.org/pkg/tikzscale?lang=en) package allows direct size specification for [tikz/pgfplots](https://ctan.org/pkg/pgf?lang=en) images. These are plots and diagrams described using LaTeX macros. However, the file ending must be .tikz, not .tex. While specifying `"files.associations": { "*.tikz": "latex" }` enables LaTeX syntax highlighting (see, e.g., https://github.com/James-Yu/LaTeX-Workshop/issues/294), it does not enable parsing of `% !TEX` magic comments or build-on-save.

### Log messages

No relevant log messages, as nothing happens.

### How to reproduce

1. Add `"files.associations": { "*.tikz": "latex" }` to your settings
2. Create a LaTeX file but change the ending to .tikz
3. Save the LaTeX file

### Expected behavior

Automatic building of the file (or the root given in a `% !TEX root` comment) is triggered.

### Actual behavior

No build is triggered on save

### Additional Information

It may not make sense to build other files that are considered to be LaTeX source code unless they specify `% !TEX root`.

**Comment by jlelong** [comment]
I guess the problem is that the extension cannot determine the root file. Can you give an example of such as `.tikz` file? 
What could easily be done is to allow to specifiy root files through `% !TEX root` with non `.tex` extension?

**Comment by l0calh05t** [comment]
Adapted from the [tikzscale documentation](https://mirror.hmc.edu/ctan/graphics/pgf/contrib/tikzscale/tikzscale.pdf):

[minimal.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2332192/minimal.zip)

**Comment by jlelong** [comment]
It should work.
I have done some testing but it would be nice if you could perform your own tests to make sure nothing is broken.

**Comment by l0calh05t** [comment]
I don't have the necessary setup for testing vs-code extensions, afaik (I don't do any JavaScript or TypeScript or Node). Sorry.
