### ISSUE TITLE
Startup Performance

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#745]
Can we improve the startup performance time?
It's almost as heavy as VIM. (this makes me think there are rooms for improvements)
![image](https://user-images.githubusercontent.com/32885386/44170830-999fa200-a0e9-11e8-9216-de3c9412257e.png)

**Comment by NavyAdmiral** [comment]
@James-Yu  @jlelong @Astrantia This is addressed in https://github.com/James-Yu/LaTeX-Workshop/pull/864
