### ISSUE TITLE
External font support for building with Docker.

### ISSUE THREAD

**Issue by lukasuni** [James-Yu/LaTeX-Workshop#746]
## Improvement
With fonts being a crucial part for LaTeX, external font support for building with Docker is currently missing.

As an example, the Docker container [thomasweise/texlive](https://hub.docker.com/r/thomasweise/texlive/) mounts external fonts like
`-v /path/to/fonts/:/usr/share/fonts/external/`.

**Comment by lukasuni** [comment]
#673

**Comment by James-Yu** [comment]
Please go on discussing in #673. Actually I like the idea very much, but I am not knowledgable enough to implement the feature, specifically bash scripts. Will look into that though.
