### ISSUE TITLE
Persistent Notifications

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#748]
![image](https://user-images.githubusercontent.com/32885386/44218231-52b5b900-a18a-11e8-9144-f66a07768bb7.png)
![image](https://user-images.githubusercontent.com/32885386/44218396-ac1de800-a18a-11e8-83b8-de8feb7e69a7.png)

Success and error notifications do not go away until you move your mouse to close them. If vscode api provides support for this, can we make notifications disappear automatically within 5(configurable) seconds?

**Comment by James-Yu** [comment]
You got it. vscode does not support auto-closing.

**Comment by Astrantia** [comment]
@James-Yu This can be reopened now. Vscode added support for it: https://github.com/Microsoft/vscode/issues/51013
