### ISSUE TITLE
Some snippets are not working

### ISSUE THREAD

**Issue by kim0sun** [James-Yu/LaTeX-Workshop#753]
### Description

** for superscript, 
... for \dots
@8 for \infty
are not working.
the editor doesn't show suggestion for above snippets.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. 
2. 
3.

**Comment by jlelong** [comment]
This may be related to #669.
Can try hitting `TAB` after `**` and tell me if this is properly expanded even though the snippet list does not pop up?
