### ISSUE TITLE
Auto completion not working for some \begin{}...\end{} environments

### ISSUE THREAD

**Issue by github-young** [James-Yu/LaTeX-Workshop#754]
### Description
The auto completion function is not working for some 
```
\begin{...}
...
\end{...}
```
environments when typing them at the __first time__.
However, it works after ```tab``` and ```Ctrl+z```.

### Log messages
The logs are uncorrelated.

### How to reproduce

Type the TeX code of 
```
\begin{...}
...
\end{...}
```
This GIF picture is an example:

![vscode](https://user-images.githubusercontent.com/19162282/44451194-9c3c5300-a625-11e8-8056-dbff3e1d612a.gif)

When I type ```\begin ``` and "enu", the completion candidate list do not appear. I need to ```tab``` again to jump out of this environment and ```Ctrl+z``` to return to it, and then I get the correct completion candidate list.

### Expected behavior
It is expected as:
![expected](https://user-images.githubusercontent.com/19162282/44452157-5cc33600-a628-11e8-93b9-2bb55f2bd3af.png)

### Actual behavior
It is actually:
![actual](https://user-images.githubusercontent.com/19162282/44452133-4a48fc80-a628-11e8-8674-8169585f4e41.png)

### Additional Information
It can happen either in a blank new document or a document that already has ```\begin{}...\end{}``` environemnts.
I reinstalled the ```LaTeX-Workshop``` extension, deleted the ```.vscode``` folder and reinstalled vscode, but none of them solve this problem. This problem rose up several days ago. No special operation was done.

**Comment by jlelong** [comment]
This is related to #744. You can manually trigger intellisense (`ctrl + space`).
You can also have a look at the end of #609 to better understand how tricky it is to mix snippets and intellisense.

**Comment by github-young** [comment]
@jlelong I am curious why it stops working a few days ago, maybe after an update of this extension. Though it is not as convenient as ```tab```, the method you mentioned does work. Thank you anyway!

**Comment by jlelong** [comment]
I am surprised that 

>  it stops working a few days ago.

Nothing has been changed recently in the extension concerning this feature and it was already not working in version 5.6 (released early July).

**Comment by github-young** [comment]
Now I am more confused since I have been writing TeX documents for this August, and it really stopped working about one or two weeks ago. Well I don't know what caused.
