### ISSUE TITLE
PDF is not rendered on entering/exiting zen mode.

### ISSUE THREAD

**Issue by drdebmath** [James-Yu/LaTeX-Workshop#756]
### Description
PDF is not rendered on entering/exiting zen mode. The view latex pdf file button doesn't render the pdf again. The panel has to be closed and opened again for the pdf viewer to work.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

Steps to Reproduce:

1. Use view pdf of Latex Workshop in VS code
2. Enter or Exit zen mode (ctrl +k z)

### Expected behavior

The pdf should still be rendered in the viewer.

### Actual behavior

Blank panel is rendered. 
Clicking on the view pdf after closing the panel opens the pdf viewer.
### Additional Information
The change in the size of rendering panel may be the problem.

VS Code: 1.26
Latex Workshop: 5.8.2

**Comment by ShuCaiMonkaS** [comment]
It used not to work as well.
But I just tested it, it works for me now.

**Comment by drdebmath** [comment]
After VS Code Update, the pdf viewer is working fine. This issue can be closed.

**Comment by arjunguha** [comment]
This bug has re-emerged on VS Code 1.40.0. (I discovered Zen Mode for the first time, so I'm not sure if this is a recent regression.)
