### ISSUE TITLE
Add "Build Project" button to Activity Bar or Side Bar

### ISSUE THREAD

**Issue by carstenhag** [James-Yu/LaTeX-Workshop#759]
### Description

Hey, IMO building on every save is pretty useful, but sometimes also really annoying.  
A button at the Activity Bar (the bar at the left) would be great to start the build.

### Additional Information
I am aware of the hotkeys and I would use it, but some users are not going to want to remember hotkeys.

![vs code screenshot](https://code.visualstudio.com/assets/docs/getstarted/userinterface/hero.png) from https://code.visualstudio.com/docs/getstarted/userinterface

**Comment by carstenhag** [comment]
After creating the issue, it came across my mind that there must be an extension that can assign hotkeys to a button on there.

**Comment by tecosaur** [comment]
Whenever I want to build, but not automatically on save, I just do `F1` + `Bui` + `Enter`. Takes 2 seconds, no hotkeys remembered. To me, a dedicated button wouldn't be worth the screen real estate.

**Comment by jlelong** [comment]
You can just right click in the file, then _Build project_. I guess it is as straightforward as clicking a real button.
