### ISSUE TITLE
Hello World LaTeX does not work (not even an error message!)

### ISSUE THREAD

**Issue by papb** [James-Yu/LaTeX-Workshop#760]
### Description

I am new to LaTeX and an old VSCode user, so I was very happy to find out that there is an extension for working with LaTeX in VSCode. Unfortunately, I couldn't get it to work, and when I click things, nothing happens. Not even error messages. I want to figure out what's going on and hopefully manage to use this extension that looks so great.

Steps I followed:

1. Installed Perl and added it to PATH
2. Installed `latexmk` and added it to PATH
3. Installed TeX Live and added it to PATH (I did an advanced installation choosing only a few things instead of them all, if this is relevant let me know and I'll figure out exactly what I installed and what I didn't install)
4. Installed LaTeX-Workshop in VSCode
5. Created a `test.tex` file with the following content:

```tex
\documentclass{article}
\begin{document}
  Hello World!
\end{document}
```

6. Left-click within VSCode opens the following options:

* Build LaTeX project
* SyncTeX from cursor
* LaTeX actions

Clicking the first two does absolutely nothing (just closes the context menu).
Clicking `LaTeX actions > Build LaTeX Project > latexmk` also does nothing.
Clicking `LaTeX actions > Build LaTeX Project > pdflatex -> bibtex -> pdflatex*2`, on the other hand, does things! A lot of files are created and I get an error message:

```
I found no \citation commands---while reading file test.aux
I found no \bibdata command---while reading file test.aux
I found no \bibstyle command---while reading file test.aux
```

I'm new to LaTeX, this probably means something, but this is not the point at the moment. The point is that the other things simply do nothing at all.

**Note 1:** I am currently [experiencing an issue with VSCode itself](https://github.com/Microsoft/vscode/issues/57212) that might or might not be related. **EDIT:** Looks like this is not related at all because I tried running as administrator and the problem still occurs, exactly the same way.

**Note 2:** Opening a console and typing `pdflatex test.tex` works. The PDF file is generated alongside two other files: `test.aux` and `test.log`.

**Comment by jlelong** [comment]
The output of `pdflatex -> bibtex -> pdflatex*2` is just fine. Based on this output, the extension must be working.
My guess is that `latexmk` does not work on your installation. Try to call it directly from the console.
