### ISSUE TITLE
Missing Math Env. Commant support: \vec{}

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#761]
I noticed that while most math commands are well supported (e.g. `\sqr <tab>` → `\sqrt{x}`, this extension does not do the same for `\vec{}`. It would be great rich-er support for this could be added.

**Comment by jlelong** [comment]
I take a note of this. I think that if you type it once, then it should autocomplete to `\vec{arg}` automatically.

**Comment by jlelong** [comment]
You can define your own snippets in vscode, search for __Configure User Snippets__.
