### ISSUE TITLE
Direct and reverse SyncTeX with subfiles

### ISSUE THREAD

**Issue by fyemath** [James-Yu/LaTeX-Workshop#762]
### Description
Direct and reverse SyncTeX do not work with subfiles imported to a main .tex file.

### Expected behavior
ctrl+left click the pdf file, the associated subfile (normally a chapter***.tex file) will be opened in a new tab next to the main .tex file.

**Comment by jlelong** [comment]
It does work as expected on my installation. 
Feel free to reopen the issue with a minimal working example highlighting the problem.
