### ISSUE TITLE
SyncTeX after Build doesn't work with an external viewer

### ISSUE THREAD

**Issue by linhtto** [James-Yu/LaTeX-Workshop#765]
### Description

This is a follow up on https://github.com/James-Yu/LaTeX-Workshop/issues/613, in which I think I found a small bug. 

I can set "latex-workshop.synctex.afterBuild.enabled" to be true, but it doesn't seem to actually do anything if I use an external viewer.

### Log messages
<details>
<summary>LaTeX Workshop Output</summary>
[14:45:54] Successfully built /file.tex

[14:45:54] No PDF viewer connected for /file.pdf
</details>

### How to reproduce

1. Set the viewer to external, and choose something such as Skim.
2. Set "latex-workshop.synctex.afterBuild.enabled" to be true
3. View in Skim. And then (re)build the LaTeX source file.

### Expected behavior
The viewer Skim should be refreshed and the forward sync should point to the right place. 

### Actual behavior
Nothing happens. Note that the SyncTeX command itself works just fine.

-----
Here is what I think is a bug with my very limited knowledge:

I think the error I got above (No PDF viewer connected) is separate from the fact that syncTeX didn't actually get implemented upon completion of the build.

1. The error comes from the line `this.extension.viewer.refreshExistingViewer(rootFile);` in `buildFinished(rootfile)` in `builder.ts`. I'm not sure why, probably because it doesn't support the external viewer. It's fine for me though, *if* syncTeX upon build works instead.
2. I can get syncTeX to be called as in the desired behavior described in this issue when adding these lines to the end of `buildFinished(rootfile)` in `builder.ts`:
```
if (configuration.get('synctex.afterBuild.enabled')) {
                        this.extension.locator.syncTeX();
                    }
```
Those lines can also be removed from `viewer.ts` without causing any issue that I can see yet. These lines were added to `viewer.ts` in response to https://github.com/James-Yu/LaTeX-Workshop/issues/613. I think these lines should be moved, and the desired behavior will be restored.

**Comment by James-Yu** [comment]
`refreshExistingViewer` only works with the built-in viewer, which sends a message `loaded` to the extension after initialized. Moving the said lines to `builder.ts` can break the built-in viewer on some slow computers.

**Comment by James-Yu** [comment]
Since external viewer never notifies the extension when the pdf is loaded, the extension does not know when to perform a SyncTeX. Let's imagine an extreme case in which the PDF has 100 pages and takes 500ms to refresh. Upon completing the building process, the extension tried SyncTeX and told the viewer about the new position. However, it is still loading the pdf and may or may not ignore the information.

**Comment by linhtto** [comment]
Thanks for the response!

So it's by design that this option doesn't work with an external viewer at
all? The issue in which this piece of code was added for was in fact in
reference to an external viewer.

If the viewer is still refreshing, are you saying that it will break? Would
it not store the information and process it in order? I'm just thinking it
must be capable given that this is the default behavior in Sublime Latexing
and Latextools.

What about adding an option that's exclusive to the external viewer case
and let the user use it at the own peril? I would gladly take that option
because right now I have to modify the code inside .vscode/extensions
myself which is not a long term solution.

Thank you.

**Comment by James-Yu** [comment]
I need to think of it again and see if a solution exists.

**Comment by linhtto** [comment]
That will be great. Thank you!

**Comment by James-Yu** [comment]
Sorry that this issue slipped by my attention. Instead of moving the original code to `builder.ts`, an extra execution is included. This is because that the built-in viewer cannot respond fast enough upon build finished. I think the extra little computation is fine for the good brought by the fix.
