### ISSUE TITLE
Tools / recipes do not work for plain TeX

### ISSUE THREAD

**Issue by louisstuart96** [James-Yu/LaTeX-Workshop#766]
### Description

As a macro package developer, sometimes I need to test some macros and characters in a plain TeX file.
So I add some tools and recipes for typesetting plain TeX, but the tools don't work as expected.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

[14:15:07] RECIPES command invoked.
[14:15:08] BUILD command invoked.
[14:15:08] Cannot find LaTeX root file.
</details>

### How to reproduce

1. Write a plain TeX file:
```
Test \TeX.
\bye
```
2. Add recipes and tools to user settings:
```
{
    "latex-workshop.latex.recipes": [
        // other recipes
        {
            "name": "luatex",
            "tools": ["luatex"]
        },
        {
            "name": "xetex",
            "tools": ["xetex"]
        }
    ],
    "latex-workshop.latex.tools": [
        // other tools
        {
            "name": "luatex",
            "command": "luatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "%DOC%"
            ]
        },
        {
            "name": "xetex",
            "command": "xetex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "%DOC%"
            ]
        }
    ]
}
```
3. Invoke `LaTeX Workshop: Build with recipe` -> `luatex` in the command palette.

**Comment by James-Yu** [comment]
Unfortunately, the extension finds `\begin{document}` to locate the root file.

**Comment by dimpase** [comment]
How hard would it be to make it work with (e)plain TeX? There is still a sizeable chunk of texts written in a (non-La)TeX, e.g. some people find it more portable. I imagine (without looking at the source code yet) that you basically need to know where the preamble ends, i.e. you need some kind of tag for look for. In this case, you might instead (make this customizeable) search for a particular comment in the TeX source.
