### ISSUE TITLE
Add button for SyncTex

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#767]
Would be very nice with a button for SyncTex instead of having to use command palette up here:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/12127864/44841952-e1bfd800-ac44-11e8-922f-f5d982188aab.png">

A default keyboard shortcut would be good.

**Comment by jlelong** [comment]
You can use the context menu (Right - click) to call _SyncTex from cursor_. You can also define your own keybinding for the function `latex-workshop.synctex`.

**Comment by GandalfSaxe** [comment]
Ah ok, good that it's also there. The context menu is very crowded though, and even though it's 5th from the top for me, it's still a little crowded / cluttered in there. That depends on many extensions you have of course.

I was just thinking a button would be useful for casual users + default shortcut for command for pro users.

**Comment by GandalfSaxe** [comment]
@jlelong How about default cmd+opt+x?

1. It can be reached with one hand.
2. `cmd+opt+j` already `Join Collaboration Session` in popular [VS Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) extension + `Jump to previous` in popular [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) extension.
3. ctrl+alt+x also free on VSCode Windows.

**Comment by benlindsay** [comment]
> You can use the context menu (Right - click) to call SyncTex from cursor. You can also define your own keybinding for the function latex-workshop.synctex.

I used to be able to Right-click to call SyncTex from cursor as described, but on my current version I don't see that option. Was that removed by design or an edge-case bug?

**Comment by jlelong** [comment]
The menu has been removed as all the actions are available from the TeX panel but you can restore it by setting `latex-workshop.showContextMenu: true`.

**Comment by benlindsay** [comment]
Ahh, perfect, thanks @jlelong!
