### ISSUE TITLE
Shortcuts for built-in PDF viewer?

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#770]
Are there any shortcuts for the built-in PDF viewer? What viewer is used and is it platform-dependent?

**Comment by jlelong** [comment]
`ctrl+alt+v` is the default shortcut, see the `package.json` file for the default built-in viewer.

**Comment by GandalfSaxe** [comment]
I don't mean shortcut to activate the build-in viewer, but shortcuts for skipping pages, showing table of contents menu bar, go to page etc?

I looked into the package.json, and found `latex-workshop.view.pdf.viewer"` being set to none, so I'm not sure what that means.

**Comment by GandalfSaxe** [comment]
For example I just noticed that the arrow keys does page forward/backward in the built-in PDF viewer. I'd like to know if there are any more.

What is the built in PDF viewer being used on Mac? Was thinking I could perhaps look it up once I know what is being used.

**Comment by wanghaiyu66** [comment]
Shortcuts alt+left/right arrow used to work, but they don't work anymore.
