### ISSUE TITLE
Pressing Option on a figure path closes Editor and switches to the image

### ISSUE THREAD

**Issue by Azhag** [James-Yu/LaTeX-Workshop#772]
Recently, pressing Option (with nothing else, just keeping it pressed) while on a Figure file path directly jumps to the figure file, closing the current editor tab.

It's super super disruptive, as I tend to use Option+Right/Left to move along the file path to edit it. Now this has become impossible.

Did something change in this extension or VSCode? Can this be controlled as a Keyboard shortcut? Can't seem to find anything about it anywhere :/ 

Visual studio Code - 1.26.1 (1.26.1)
Latex-Workshop - [5.8.2] - 2018-08-16

**Comment by James-Yu** [comment]
Actually not. We didn't implement include file jumping for images. You may refer to other extension for the cause.

**Comment by Azhag** [comment]
Thanks a lot for the precisions, will go digging :)
