### ISSUE TITLE
How to clear new command saves

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#777]
This is an extension of #761 .

While the ability of LaTeX workshop to save snippets for new commands (e,g, `\vec` or `\includegraphics`) is great, however sometimes you just don't type it as it should be the first time. When this happens the extension remembers this incorrect version forever. It would be good to be able to edit what's saved, or at least to just solve my specific issue to be told where to find the files where this is saved so I can dig through it.

**Comment by James-Yu** [comment]
Hmm actually the new commands are saved in RAM instead of a cache file. Actually I cannot think of a proper way to distinguish a mistyped command from correct ones. Any idea?

**Comment by tecosaur** [comment]
Saved in RAM? I'm curious about this since vscode seems to remember across multiple sessions. Could this be a vscode thing, not a LaTeX workshop thing?

**Comment by James-Yu** [comment]
That would be interesting. The logic is in https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/command.ts . You may see that there is no file writing behavior.

**Comment by tecosaur** [comment]
Thanks for that, it was good to see how it worked. I recently ran a test using the non-existent `\testcommand{a}{b}`. I verified that it behaved as expected within that vscode session (it did expand to `\testcommand{arg}{arg}` from the second use). I then restarted it and it behaved as expected (command was forgotten). 

As such my current conclusion is that me thinking that this behaviour persisted between sessions is incorrect.

The reason why I thought this would be because of, specifically, the behaviour of `\vec`. Since it comes up on the 'smart suggest' (I forget what it's called) in the same manner as newly defined/built-in commands, however, didn't correctly expand to `\vec{arg}` like other built-ins, and also didn't after being used with an argument in a fresh session.

**Comment by James-Yu** [comment]
It seems that `\vec` is defined somewhere else in the extension without the argument. Upon correctly using it, the command is updated with an argument. Seems a small issue but how to correct mistyped custom commands is an interesting addon to the extension. Will think of it.

**Comment by tecosaur** [comment]
"Upon correctly using it, the command is updated with an argument." I have been unable to reproduce this, using the following steps. I have a feeling I've probably missed something obvious but would you be able to outline any differences between what I've done and what you did to make it work?

1. Open vscode
2. Create empty .tex file
3. Put bare minimum in (up to `\begin{document}`)
4. Start math environment with `\[ ... ]\`
5. Type `\vec{a} + \vec{b}` in math env
6. Type `\vec` wait for suggestion to come up and hit enter
7. No argument seen.

**Comment by James-Yu** [comment]
It seems that my previous statement is wrong. When a command was previously recognized, it will not undergo any updates c.f. https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/command.ts#L151 . This design reduces much unnecessary computation but I'm not sure if the saving is worthy. Any idea?

**Comment by tecosaur** [comment]
Fewer operations is always better, but does this only run when typing a word? 

Would some form of short-period manual override / ability to review commands added this way be a good idea? I can't really think of any other non-complex ways to get around this without introducing a constant overhead.

**Comment by James-Yu** [comment]
No, it only runs when the extension tries to provide command hints. I will see if command-updates cause much trouble. If not, will push a new release on it.

**Comment by jlelong** [comment]
`\vec` is defined twice, see #778.

**Comment by jlelong** [comment]
Maybe, we can assume that the most recent form of a command is the good one. A very simple way to implement that would be to go through the file content in a reverse order: applying `.reverse()` to `content` in [commands.ts](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/command.ts#L143) would do the trick.

This would induce very few changes.

**Comment by James-Yu** [comment]
A temp fix in 5767d62 . The last one is always respected. I've tested, and the extra computation is not significant.
