### ISSUE TITLE
Improve output of errors and warnings

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#781]
It is often very difficult to find an error in the `LaTeX Compiler` output. Here is a typical example of an error that was caused by me using the `&` symbol in an equation environment when I needed to use the `aligned` environment. However I only found the error after firing up SublimeText and compiling the LaTeX document.

PS: Note that I couldn't even find the error in this case by searching the output for "error", which makes it like findings a needle in a haystack.

## VSCode + LaTeX-Workshop
Output: LaTeX Compiler 
![screenshot 2018-09-06 at 11 48 23](https://user-images.githubusercontent.com/12127864/45149927-fcf19100-b1ca-11e8-89ec-c1644198888b.png)

## SublimeText + LaTeXTools
![screenshot 2018-09-06 at 11 50 41](https://user-images.githubusercontent.com/12127864/45150019-31654d00-b1cb-11e8-99ff-e73c6854db5b.png)

## VSCode Problems Pane (not showing error)
The error is not displayed in the `Problems` pane, just a bunch of references and citations that fail because the recipe (XeLaTeX + Biber + 2x XeLaTeX) couldn't finish:
![image](https://user-images.githubusercontent.com/12127864/45150164-87d28b80-b1cb-11e8-9eca-003a37a1f1b7.png)

**Comment by jlelong** [comment]
This is a problem in the parsing of `LaTeX`'s output.
Can you provide a minimal example to help us debug this?

**Comment by GandalfSaxe** [comment]
Of course, but I might not have time until after I've handed in the thesis. Expect it later in September, but it's on my todo list.

**Comment by James-Yu** [comment]
I'll try make a small devtool for log parsing. Seems that the log message cannot be parsed by the parser.

**Comment by jlelong** [comment]
Closely looking at your screenshots, I can notice two problems leading the non detection of the error.

1. The warning about the undefined citation is exactly 79 characters long and the parser thinks the line continues on the following one. *Fix*: modify the parser to consider 79 character long lines ending in `.` not to continue on the following one.

1. Misplaced character messages have to added to the parser.

I will fix this soon.

**Comment by Astrantia** [comment]
@jlelong I don't think #61dde2d works well. @GandalfSaxe your thoughts?

**Comment by jlelong** [comment]
Do you have an example of a `.tex` file leading to a wrong parsing?

**Comment by s4shmz** [comment]
In addtion, I request to parse bibtex errors/warnings.
A vim plugin `vimtex` has the feature.

For example, from https://github.com/lervag/vimtex/issues/964,

```
Warning--to sort, need author or key in bib1
Warning--empty author in bib1
Warning--empty title in bib1
Warning--empty journal in bib1

Repeated entry---line 11 of file ref.bib
 : @article{bib2
 :              ,
I'm skipping whatever remains of this entry

Warning--entry type for "bib3" isn't style-file defined
--line 18 of file ref.bib
```

vimtex also supports biblatex https://github.com/lervag/vimtex/issues/972.

**Comment by GandalfSaxe** [comment]
Reproducing the error from before (using `&` in an `equation` environment), I know get the error in the Problems pane:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/12127864/45252082-88952a00-b351-11e8-96ce-84c46ef0ff58.png">

So I think the fix was a success, at least as far as this particular problem was concerned. What I originally imaged was for LaTeX-Workshop to have latex compiler errors and warnings nicely formatted as in SublimeText (i.e. using red for errors, yellow for warnings and separating them nicely). However, as long as all the errors and warnings are corrected parsed from the latex log into the Problems view, that's a perfectly good / preferable solution.

@Astrantia So as far as I can tell, it's good, at least for this problem.

Thanks @jlelong and @James-Yu .

**Comment by Astrantia** [comment]
@GandalfSaxe @jlelong oh that's what I expected this to do too. Latex compiler errors and warnings are badly formatted, but Problems pane is good. 👍

**Comment by hechangran** [comment]
I have a similar problem with Latex Workshop ver. 8.17.0. It turns out that the problem is due to the name of the .tex file. containing spaces. After removing the spaces in the file name, all warnings in the log file shows properly.

**Comment by tamuratak** [comment]
Please open a new issue filling out all the information required in the issue template if you want any help.
