### ISSUE TITLE
Citation Browser does not update on bib file changes

### ISSUE THREAD

**Issue by prabal-banerjee** [James-Yu/LaTeX-Workshop#782]
### Description
When a git pull changes .bib file, the citation browser still shows the old bib entries. Disabling and enabling the extension fixes the problem.

### Log messages
Logs are uncorrelated.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Remotely change the .bib file. Add an entry.
2. Fetch changes locally.
3. Try to cite the newly added entry. Fails.
4. Disable the extension. Reload workspace.
5. Enable the extension. Reload workspace.
6. Try to cite the newly added entry. Succeeds. 

### Expected behavior
Citation browser should refresh after .bib file changes.

**Comment by James-Yu** [comment]
Can you please try copy & paste the new version to the location and see if the problem persists? I am not sure what is causing this, since the extension watches file changes to perform updates.

**Comment by prabal-banerjee** [comment]
Fixed. Closing the issue for now. Thanks.
