### ISSUE TITLE
Issues with the "Problems" window when using projects with spaces in the path

### ISSUE THREAD

**Issue by philipstarkey** [James-Yu/LaTeX-Workshop#786]
### Description

After updating to VSCode 1.26.0 a while ago (and then checking again with 1.27.1 today), I have an issue with the "Problems" window not displaying items under the correct file heading. This is similar to #730, however this problems occurs in both latex-workshop 5.8.2 (prior to the fix for #730) and 5.9.0 (after the fix for #730). It seemed to appear when I updated VSCode to 1.26.0 a while ago, and it still persists with 1.27.1.

Looking into it further, it appears that the issue comes and goes depending on whether there is a space in the folder path of the project. I've attached a zip file containing two (slightly modified) copies of the project in #730 (so ignore that actual messages that are shown in the problems window as I haven't updated them). One project has a space in the folder name, while the other does not.

You can see from the two below images how the one with the space groups the problems under an invalid heading. I suppose there is a small possibility that the position of the space in the path matters, but my quick testing didn't seem to show it was important.

With no space (correct):
![image](https://user-images.githubusercontent.com/2508881/45271110-c035da80-b4e7-11e8-9a19-4878529f2b9e.png)

With space (incorrect):
![image](https://user-images.githubusercontent.com/2508881/45271102-a72d2980-b4e7-11e8-8708-6fb426b4cc28.png)

Project files:
[latex_Workshop_bug.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2364831/latex_Workshop_bug.zip)

I'm of course running on windows.

It doesn't seem to happen on LaTeX-Workshop 5.8.2 and VSCode 1.25.1 (which is why I think it's related to the VSCode version).

The only other relevant thing I can think of is that the update to VSCode 1.26 seems to have caused the entries in the problems list to have varying indentation. I'm not sure why this would happen (it doesn't happen on VSCode 1.25). Maybe VSCode changed something about the problems window?

**Comment by philipstarkey** [comment]
Thanks for looking into it!

I've done a bit more investigating with VSCode 1.25.1, and it turns out that the bug does still exist in that version for my test case, but strangely doesn't exist for my actual project that I'm working on. This was with LaTeX-Workshop 5.8.2 as 5.9 doesn't seem to be compatible with older VSCode versions.

So I've removed the VSCode version from the title of the issue (but left my original description of the bug for posterity).

Unfortunately this raises more questions than it answers (like what changed between VSCode 1.25 and 1.26 that causes the bug to appear in my actual project), but at least it's not solely down to something that was changed in VSCode (although I will add that the weird indentation of the "problems" does not exist in 1.25 and has something to do with VSCode 1.26+). 

Hope that helps some more (and apologies for the sight misdirection)

**Comment by James-Yu** [comment]
This is the problem pane in my test with everything updated:

![image](https://user-images.githubusercontent.com/4210342/45280423-e0c15d00-b506-11e8-99a0-199d4b8698e8.png)

Now except for the `additional 2 blah-blah` file, all others are correct. So we can narrow down to what is causing the file name problem. Let's have a look at the log file:

![image](https://user-images.githubusercontent.com/4210342/45280545-6f35de80-b507-11e8-9c8b-65bec7b1c28b.png)

Got it. LaTeX log messages are arguably the worstly designed logging system in the universe. It uses parentheses to dive into file names, which in this case is actually from the text. Unfortunately, it seems that the extension cannot distinguish either cases. I will try making some fixes on it, but it's not a guarantee of success.

Please join me to blame the logging systems of LaTeX compilers.

**Comment by James-Yu** [comment]
To be honest, this is not a proper fix. It will still produce wrong file paths with `(./somepath` in LaTeX files. At least a temp fix for now.

**Comment by philipstarkey** [comment]
That's very odd, because what you see in your problem pane with everything updated doesn't look like mine at all (the second image in my first post).

On VSCode 1.25.1 I see approximately what you see (slightly different because I can only have latex-workshop 5.8.2 installed) but it's totally different for VSCode 1.27.1.

I checked the latex compiler output across the two VSCode versions using kdiff3 and they are equivalent. Given that you can't reproduce my exact bug, is there an easy way for me to debug it myself (can you point me to the code in latex-workshop that produces the list of "problems"?)

**Comment by James-Yu** [comment]
Yes, you can try the new `devtools` in commands. Though it may not serve well. All logics are in https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/parser.ts

**Comment by jlelong** [comment]
The problem of log messages containing `(` is often related to bad box messages as it quotes part of the `.tex` content. In 5f95c26, I decided to drop the line following a bad box message. Using the `master` branch, the problem pane is correct.

**Comment by philipstarkey** [comment]
Thanks! I might have a deeper look sometime, but the first thing I did was test the fix in c317f05 and it does fix my problem (in both my test project and actual project) despite you seeing different behaviour to me.

But at least I have more of an understanding of how latex-workshop works now, so hopefully I can help solve any future issues I find! (like the weird indenting of the problems icons that seemed to happen in VSCode 1.26...).

Thanks again :)

**Comment by ericrboidi** [comment]
This issue is happening to me again, in VSCode 1.31. The filename is of the form:

"C:\Users\me\FolderNoSpaces\FolderNoSpaces\Folder (With&ASpace AndThisFormatting)\FolderNoSpaces\Folder WithOneSpace\FolderNoSpaces"

and it breaks at "C:\Users\me\FolderNoSpaces\FolderNoSpaces\Folder" (it displays no more after that, and double clicking to open the file fails. Not sure whether I should raise a separate issue for this or not?
