### ISSUE TITLE
Bug With Wrapping in Latex Compiler Output

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#787]
Compile any tex.
Latex Compiler formatting is bad:
![image](https://user-images.githubusercontent.com/32885386/45273425-b2993a00-b480-11e8-87e3-57ea7e42cb1d.png)

Wrapping is unnecessary and this could look better if not wrapped.

**Comment by James-Yu** [comment]
This is the raw output of the LaTeX compiler. And this is also among the reasons I hate LaTeX myself.
