### ISSUE TITLE
Tooltips are badly formatted

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#788]
Warning message (displays well inline in problem pane):
![image](https://user-images.githubusercontent.com/32885386/45274980-12dfaa00-b488-11e8-925c-51e9f3ed9e50.png)
Tooltip: 

![image](https://user-images.githubusercontent.com/32885386/45274966-fcd1e980-b487-11e8-82fb-fe47eac531bc.png)

**Comment by Astrantia** [comment]
@jlelong 
```tex
\documentclass[%
final,% include images
twoside=semi
%]{scrartcl}
]{scrreprt}

%Layout redefinition of chapter, section, subsection and paragraph:
\makeatletter
\renewcommand{\chapter}{\@startsection{chapter}{0}{\z@}{-2em}{6pt}{\normalfont\LARGE\bfseries}}
\renewcommand{\section}{\@startsection{section}{1}{\z@}{-1.5em}{6pt}{\normalfont\Large\bfseries}}
\renewcommand{\subsection}{\@startsection{subsection}{1}{\z@}{-1.2em}{6pt}{\normalfont\large\bfseries}}
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\z@}{-2.25ex \@plus -1ex \@minus -0.2ex}{0.5ex \@plus 0.2ex}{\normalfont\normalsize\bfseries\itshape}}
\makeatother

\begin{document}

%the first warning komes here (tableofcontents is defined as chapter*, which makes problems)
\tableofcontents

%Here everything is ok:
\chapter[First chapter - short title]{First chapter - long title - here is everything ok}
Some text

%The second warning is issued here:
\section*{First Section - long title - asterisk poses a problem}
Some further text

%Here there are two problems:
% - asterisk issues a warning
% - content of [..] is not recognized as the shot subsection title
\subsection*[First subsection - short title]{First subsection - long title - asterisk poses a problem}
Some more text

\end{document}
```

**Comment by jlelong** [comment]
There is no way to configure the width of the tooltip, see [https://github.com/Microsoft/vscode/issues/14165](https://github.com/Microsoft/vscode/issues/14165)

Hence, we cannot do much about how the message gets wrapped. So far, all lines of a message are joined and then wrapped in the tooltip. The best we can do is to honor line breaks from the original message.

**Comment by Astrantia** [comment]
@jlelong honoring the newlines is all I asked for, thanks.

**Comment by Astrantia** [comment]
@jlelong 
![image](https://user-images.githubusercontent.com/32885386/45524985-12545580-b79f-11e8-9751-6d7433f5592c.png) 

Newlines are fine now, but aren't these boundaries a little too big? (they look like tabs and I think they're meant to be spaces)

**Comment by jlelong** [comment]
Unfortunately, the boundaries are are coded by the package itself using `\ClassWarning` which repeatedly calls `\@spaces` defined as 4 spaces in `latex.ltx`. 
I think we cannot do much about it.
