### ISSUE TITLE
Keyboard shortcut to new activity bar badge?

### ISSUE THREAD

**Issue by GandalfSaxe** [James-Yu/LaTeX-Workshop#789]
Cool update with the new activity bar badge. Is it possible to activate with a shortcut? It doesn't seem to have a default, and I couldn't find a command for it.

**Comment by James-Yu** [comment]
I don't think so. Rely on the community to find the shortcut API.

**Comment by werunom** [comment]
latex-activity-badge can be activated by assigning a hotkey to this command `workbench.view.extension.latex`. 

I just went to `keyboard-shortcuts` in the file menu and in that assigned a hotkey to the above mentioned command. `ctrl+shift+q` is working fine for me. 

@James-Yu  - probably standardizing the hotkey, enabling it by default and mentioning that in the readme or notes is something you can consider. Just a suggestion ...
