### ISSUE TITLE
Feature request - autocomplete environment delimiters?

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#79]
As I move over from ShareLaTeX, I'm wondering if support for autocompletion of environment `\begin... \end`'s could be implemented? E.g. in ShareLaTeX I can type `\ali`, and `\begin{align}...\end{align}` appears in the dropdown.

**Comment by jabooth** [comment]
Agreed, would be nice to have, and seems quite straightforward with the snippets feature...

**Comment by James-Yu** [comment]
No problem!

**Comment by James-Yu** [comment]
Try it out! Soon!

**Comment by jabooth** [comment]
This is fantastic @James-Yu!

Just to check it's only on `master` right now and not released correct?

I'm just playing with maybe refining the pop up a little bit like I did for the citations (you know I can't help myself 😂)

**Comment by James-Yu** [comment]
@jabooth right it's not released to the marketplace. Feel free to make changes!

**Comment by zachjweiner** [comment]
Thanks @James-Yu! Very exciting. How often do you release to the marketplace/how quickly do new commits make it there? Might have to start installing manually...

**Comment by James-Yu** [comment]
Should be ready in few hours if not minutes. The sorting things in intellisense is very tricky and I may need more time to work it out. Meanwhile, the current state is still satisfactory. :P

**Comment by jabooth** [comment]
@James-Yu yeah agreed, totally worth getting something out now, and we can see what users give for feedback!

**Comment by zachjweiner** [comment]
Working great. Just wish I could control the order of the dropdown menu, but I suspect that's out of your control, @James-Yu . Thanks again for this!

**Comment by level1807** [comment]
I'd suggest that this should work like on Overleaf: once an environment is used in the code, autocomplete learns its name it suggests it from then on. For instance, I defined a "defn" environment, but the only thing your autocomplete suggests is "definition". The same idea applies to all latex commands, macros etc. Once I've used them, autocomplete should learn that they are legit.

**Comment by jlelong** [comment]
It already works for commands but you are right not for environments. I have created a feature request for this #1249
