### ISSUE TITLE
Pressing 'e' on a compile error puts the cursor on the error line in the wrong editor

### ISSUE THREAD

**Issue by raikesy** [James-Yu/LaTeX-Workshop#793]
### Description

When compiling a document, if there is an error and nonstop mode is off, you can type `e` to open an editor window with the cursor at the line where the error was found. Currently this opens TeXworks not VS Code

### Log messages

N/A

### How to reproduce

1. Write a minimal tex document, with a deliberate undefined control sequence or similar to cause an error
2. Compile document without any parameters: `pdflatex [document.tex]`
3. Console output will pause on the error. Type `e` and return
4. After a pause, the document opens in TeXworks with the cursor at the offending line

### Expected behavior

Ideally this should open VS Code and put the cursor at the right point. 
I don't know if this is possible but it seems similar to synctex so I guess it should be.

### Actual behavior

It opens in TeXworks

**Comment by James-Yu** [comment]
AFAIK we cannot do anything. The compiler determines which editor to use, and I suppose it does not inspect the default editor setting of your OS.
