### ISSUE TITLE
Focusing the line after selecting it in the new badge view.

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#798]
I think this is a bug with the new Structure view provided by activity badge. If you click a Section/Subsection/etc.., you are redirected to that part of the .tex file, but the line is not focused. This works fine in the Outline view. When you click a section or whatever, latex-workshop selects the line for you too.

**Comment by Astrantia** [comment]
@James-Yu @jlelong Why is [this line commented out?](https://sourcegraph.com/github.com/James-Yu/LaTeX-Workshop@master/-/blob/src/commander.ts#L215:26)

**Comment by James-Yu** [comment]
Actually I have no idea why it was commented. Recovered.
