### ISSUE TITLE
View Log Messages quits the activity badge view

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#799]
@James-Yu thanks for the activity bar badge view. There is one bug I noticed. Clicking View Log Messages quits the view.

**Comment by James-Yu** [comment]
Hmm I cannot reproduce the problem. Do you have any other extensions that enhance the log message output display?

**Comment by Astrantia** [comment]
@James-Yu Here's a preview https://i.imgur.com/9mCpHgn.gifv 
I'll try to get log messages.

**Comment by Astrantia** [comment]
Latest commits have fixed this issue.
