### ISSUE TITLE
Inverse SyncTeX (from pdf to tex) problem

### ISSUE THREAD

**Issue by jccha** [James-Yu/LaTeX-Workshop#8]
In version 0.2.8, inverse synctex does not work properly. I Investigated a little and found that the following two fixes correct this issue.  (Since the suggested changes are very short, I just write them below, rather than making a pull request.)

1. The processing of the tex file pathname returned by synctex needs a fix.  SyncTeX seems to return a full path.  Furthermore, it is often of the form "/a/b/./c.tex" instead of "/a/b/c.tex"; this leads VS Code to open another window for the same file. This issue seems to be resolved when line 117 of preview.ts is changed to the following, for instance.

         let file = record["input"].replace(/(\r\n|\n|\r)/gm, "");
         if (file.charAt(0) != '/')
             file = path.join(path.dirname(latex_data.main_document), file);
         file = file.replace(/\/.\//gm, "\/");

2. On OS X, to make Cmd+Click send a message to websocket, line 54 of latex.js needs a fix. The following change, for instance, makes it works on OS X:

        if (!e.ctrlKey && !e.metaKey) return;
 
The above changes were made quickly, and so I guess there will be better solutions.  Though, I hope this help to improve LaTeX-Workshop!

**Comment by James-Yu** [comment]
Thanks for the fix! The changes are merged and new version should be ready in minutes.

**Comment by jccha** [comment]
Thanks for the prompt incorporation. I've just updated it to the new version on my VS Code and confirmed that it works well on OS X + MacTeX.

**Comment by James-Yu** [comment]
Glad it works well :-]
