### ISSUE TITLE
Linter is not working properly

### ISSUE THREAD

**Issue by jose-a-sa** [James-Yu/LaTeX-Workshop#80]
Linter is always active even when "latex-workshop.linter" is set to false. Also when I change any of the Linter cmds. i.e. adding "-n1" or add kind of flags still shows up that warning.

Regards, José

**Comment by jabooth** [comment]
I'm thinking you are probably on older than [v1.2.2](https://github.com/James-Yu/LaTeX-Workshop/blob/master/CHANGELOG.md#122---2017-03-31) @jose-a-sa which contains a bug where the linter wouldn't respect the `"latex-workshop.linter"` flag, apologies for that. 

An update to latest should fix it, but if you could confirm for is that would be really helpful! 👍

**Comment by jose-a-sa** [comment]
@James-Yu i have the latest version of vscode and latex-workshop.

Thanks

**Comment by James-Yu** [comment]
@jose-a-sa I cannot reproduce the problem. More information about settings and local configurations are needed.

**Comment by jabooth** [comment]
Hi @jose-a-sa,

Yeah we're going to need some more details to get this fixed then as we can't reproduce.

So if you could let us know:

1. What platform you are on
2. The version of LaTeX Workshop reported in the Extension panel
3. A screenshot of the `chktex` errors you seen (e.g. the problems panel)
4. A copy of your workspace/user settings related to `"latex-workshop.*"`

We can chase this down!

Thanks

**Comment by jose-a-sa** [comment]
Sorry, now I ve seen that the problem was solved for `"latex-workshop.linter"` when set to `false`.
Still when set to true I have type 1 warnings, even with the flag `-n1`
![sem titulo](https://cloud.githubusercontent.com/assets/13206784/24648269/0527854a-191b-11e7-8fdc-88db0aa62944.png)

**Comment by jabooth** [comment]
@jose-a-sa ah OK great!

Try placing the flags for the `-nX` ignore statements in different strings in the array, so:
```
"latex-workshop.linter_command_active_file": [
        "chktex",
        "-wall",
        "-n1",
        "-n22",
        "-n30",
        "-e16",
        "-q",
        "-I0",
        "-f%f:%l:%c:%d:%k:%n:%m\n"
    ],
```
It could be that `-wall` is also 'winning out' and overriding the `-n` flags, so you could try removing that statement too...

**Comment by jose-a-sa** [comment]
Now it works 👍 . It seams the exists some lag between changing settings and seeing the results.
Also there is a option to hide the .tmp log file in the problem panel ?

**Comment by James-Yu** [comment]
Temp file in log will be addressed shortly. It will be accessible from the new quick menu.

**Comment by jabooth** [comment]
The settings change should take effect the next time a lint is run - so for instance the next time you type a little and pause.

Glad it's working for you!

**Comment by jose-a-sa** [comment]
Thank you a lot. Your extension is awesome 🥇
