### ISSUE TITLE
"View PDF" option gone from the right click menu

### ISSUE THREAD

**Issue by iorazbek** [James-Yu/LaTeX-Workshop#800]
### Description

When I right clicked anywhere on the document before the update there was a "latex actions" tab after clicking which I could choose to view the PDF either in a separate tab or in Chrome. I am no longer able to do that after the latest LaTeX-Workshop/VSCode update.

### Log messages

no logs

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. right click anywhere in a tex doc
2. 
3. 

### Expected behavior

tex actions tab appears

### Actual behavior

no tex actions tab appears

### Additional Information

using the dracula theme. Don't know if that matters.

**Comment by James-Yu** [comment]
It was moved to the side bar. Notice the new `TeX` icon.

You can also invoke the original action by command palette `ctrl+shift+P`

**Comment by philipstarkey** [comment]
@iorazbek FYI, The options in the context menu can now be re-enabled via the LaTeX-Workshop settings after I requested it in #802
