### ISSUE TITLE
Provide option to return context menu items

### ISSUE THREAD

**Issue by philipstarkey** [James-Yu/LaTeX-Workshop#802]
The latest version has removed the context menu items for build, synctex, etc.

I understand they now exist in a new side-panel, but this isn't always open.
I also understand we could do it using ctrl+shift+P and selecting the option from there, but this feel like far more effort than right-clicking.

Basically, two clicks close together on the document is faster than 4+ key presses or bringing up the tex sidebar!

So I'd like to request that the context menu items be returned, possibly only enabled by a config option used in the "when" clause of the menu item so they don't have to be there by default.

**Comment by Astrantia** [comment]
If this is to be added, can we add a boolean setting to disable it? For me, it's quite pointless to have these options in the context menu

**Comment by jlelong** [comment]
To show the menu back, just set `latex-workshop.showContextMenu` to true via the configuration panel.
