### ISSUE TITLE
Separate scopes for curly braces and parentheses

### ISSUE THREAD

**Issue by sloth3toe** [James-Yu/LaTeX-Workshop#803]
This is a feature request to update the scope definition for {} and (). Right now they do not have any distinct scope, unlike [] which is `punctuation.definition.brackets.tex`. Because of this, {} and () don't get picked by extensions that support highlighting matched pairs such as https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/blob/develop/LANGUAGE_SUPPORT.md. They are used very often in math mode, and not being able to see matched pairs is a disadvantage.

**Comment by jlelong** [comment]
The syntax definition of the `LaTeX` grammar is quite delicate and the file is already very long. Currently, we do not match `{,(,),}` (except in very few specific cases, namely begin/end constructions). It is quite common that expression are not well balanced, which makes highlighting pairs delicate. 

VS Code has native bracket matching support and this is not based on the syntax approach.

**Comment by sloth3toe** [comment]
Thanks for the explanation. 

I'm aware of VS Code's bracket matching. It is however not as extensive, and with many nested brackets they don't really stand out.

Is it possible to just have () and {} have their own scopes only within math mode? Say a subset of the current scope, so something like `support.class.math.block.tex.round.open`, `support.class.math.block.tex.round.close`, `support.class.math.block.tex.curly.open`, `support.class.math.block.tex.curly.close`. They should generally be balanced inside math mode, and it's the most important case so I think that should be enough?
