### ISSUE TITLE
Possible security flaw when using Docker on non-windows systems

### ISSUE THREAD

**Issue by philipstarkey** [James-Yu/LaTeX-Workshop#808]
While learning how LaTeX-Workshop works, I came across a bunch of calls to `fs.chmodSync` (introduced here [this commit](https://github.com/James-Yu/LaTeX-Workshop/commit/e817ebe0837d66c7a22dfbd90fe18399f7c6c896)) which set the file permissions to 777. 

As this makes those files writable by everyone on the system, I believe this opens up an arbitrary code execution security hole that allows an unprivileged actor to have code of their choosing executed as whatever permissions the user is running at (when the user initiates LaTeX file compilation or another action which runs one of the scripts).

I'm guessing that 777 permission isn't actually needed, and something more restrictive will also work without allowing unauthenticated users from modifying the script. I'm guessing either 751 or 755 would be more appropriate.

**Comment by James-Yu** [comment]
I totally agree with you. This was a result of no-brain-thinking.
