### ISSUE TITLE
[Feature request] Assign '$' exactly the same behavior as other bracket characters?

### ISSUE THREAD

**Issue by fhfuih** [James-Yu/LaTeX-Workshop#810]
I wonder if it is possible to Assign `$` exactly the same behavior as other bracket characters in LaTeX language. In other words, 

- when I type a `$`, there will appear two `$`s on the screen with my cursor at the middle.
- when the character on the right of the cursor is a `$` and I type a `[`, `{` or `(`, the bracket auto-complete will still perform
- other common special behaviors

Since this is not a bug, I did not follow the issue template. Sorry for that.

**Comment by James-Yu** [comment]
This is a long-discussed topic. There are a lot of related closed issues in the repository. The short conclusion is that pairing dollar-signs can introduce more trouble than convenience.

**Comment by innerlee** [comment]
You can use `\( \)` instead of `$ $`. The previous one can be auto-completed like a bracket.
