### ISSUE TITLE
Missing structure for latex document in explorer-outline 

### ISSUE THREAD

**Issue by werunom** [James-Yu/LaTeX-Workshop#814]
Before the release of `5.9.0` version, the outline in the explorer respected the structure of the latex file. For instance, the outline showed subsections indented under the section and it was possible to fold the sections. But when the latex-outline has been moved to a new activity-space, the explorer-outline stopped listing the section and subsections in this fashion. For instance, see the difference between the explorer-outline and latex-outline at present in the pictures provided in [this description](https://github.com/James-Yu/LaTeX-Workshop/issues/768#issuecomment-419721786). [In the first pic, the explorer-outline just lists `Sec 1`, `Sub 1.1`, etc. Only in the latex-outline, shown in the second pic, the `Sub 1.1` is indented under `Sec 1`.]

I would request for the structure (sub-sections getting indented, and folding options) to be preserved in the explorer-outline (as it was present before). 

The reason to still use explorer-outline (and not completely switch to latex-activity-outline) arises when we are working with different kinds of files, say markdown and latex. I constantly shuffle between these two kinds of documents. In this scenario, the explorer-outline shows the structure for both markdown and latex files. If I enable the latex-activity-outline, then i have to constantly shift between latex-activity and explorer-activity whenever I toggle between these two kinds of files.

**Comment by James-Yu** [comment]
It is not possible. The built-in outline is designed for only single file project.

**Comment by werunom** [comment]
Even though the explorer-outline do not support multiple files and importing, would it possible to support the outline at least for single-files? I am asking (also slight pushing :grin:) this for two reasons: 
1. Because the scenario of import/include is a special one. Given the common scenario is working with a standalone file, it helps to have the explorer-outline view provide the immediate structure there itself without requiring the user to switch the activity-view. 
2. Moreover, this functionality (at least for the standalone file) was there till the last release.

**Comment by James-Yu** [comment]
Sorry to let you disappointed, but the hierarchy won't come back. It is true that the hierarchy helps a lot in single-file scenarios. However, for multi-file structure, the extension never knows if a subsection is actually a child of the corresponding section just above. What if there is another imported file which has a new section? To avoid such confusions, the current state will be retained for a while.
