### ISSUE TITLE
Citations cannot be load.

### ISSUE THREAD

**Issue by limberc** [James-Yu/LaTeX-Workshop#823]
### Citations cannot be read.
Hi there, ever since I have cite a citation, I got a green underline show that the citation is undefined. However, I have tested my works on overleaf successfully, I don't know how to solve it.

### Log messages

=== TeX engine is 'pdfTeX'
Latexmk: Found bibliography file(s) [iclr2019_conference.bib]
Latexmk: Summary of warnings:
  Latex failed to resolve 29 citation(s)
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'main.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: Errors, so I did not complete making targets

<details>
<summary>Developer Tools Console</summary>
I didn't use any.
</details>

### How to reproduce

1.  In the end of the .tex file, use `\bibliography{ref}` and`\bibliographystyle{ref}`
2. Cite a citation anywhere.
3.  Run.

### Expected behavior
Get citation smoothly.

### Actual behavior
In the pdf file, all the citation became `?`.

### Additional Information
My system is Latest Mac(OS High Sierra 10.13.6)
VSCode 1.26.0

**Comment by jlelong** [comment]
From your log
> pdflatex: Command for 'pdflatex' gave return code 1
it looks your .tex file contains errors, which prevent `latexmk` from completing.
