### ISSUE TITLE
Use outline in Explorer panel to be more consistent

### ISSUE THREAD

**Issue by cbrnr** [James-Yu/LaTeX-Workshop#827]
### Description

VS Code provides an Outline tab in the Explorer panel. All languages (at least all languages that I have tried) use this tab to visualize the structure of the currently open editor. LaTeX-Workshop creates its own panel for this purpose. In my opinion, it would be more consistent if the Outline tab in the Explorer panel was used.

### Log messages

Logs are not relevant for this issue.

### How to reproduce

1. Open a .tex file - a new TeX panel appears in the left sidebar, which contains the structure of the document (outline).
2. Open any other supported language file, e.g. a Python file. The structure of the file (outline) can be found in the Explorer panel (Outline tab).

### Expected behavior

I would expect to find the outline in the same location, no matter what language I have just open.

### Actual behavior

The outline of LaTeX files is shown in a custom TeX panel, whereas all other languages use the outline tab in the Explorer panel.

**Comment by Astrantia** [comment]
@cbrnr Actual outline doesn't provide enough API to be implemented for latex. Also, I like it this way more.

**Comment by cbrnr** [comment]
I understand. However, one of the things I really like about VS Code (as compared to Atom) is that everything is consistent. If the API is not rich enough to do what you are currently doing, then maybe it is worth asking the VS code devs if there's a chance it could be extended? Anyway, thanks for your quick response, I wasn't expecting that this can be changed anytime soon, just wanted to give you feedback. Is it possible to disable/hide the TeX panel somehow?

**Comment by cbrnr** [comment]
(And imagine every language provided its own panel to implement the outline. This wouldn't be nice at all.)

**Comment by James-Yu** [comment]
Right click the bar to hide the item. Until further outline API updates which seems impossible in the near future, the current form will be retained.
