### ISSUE TITLE
Setting up latexindent and Chktex

### ISSUE THREAD

**Issue by zymbuzz** [James-Yu/LaTeX-Workshop#828]
hi! I have a newbie question. I have troubles to set up latexindent and Chktex. Could you provide some instructions on how to set it up?  I am using MacOs

thanks a lot for this package and help!

**Comment by jlelong** [comment]
First, you nedd to make sure `chktex` and `latexindent` are installed, see https://github.com/James-Yu/LaTeX-Workshop#requirements. Then, have a look a the variables `latex-workshop.chktex` and `latex-workshop.latexindent` in the preferences pane.
