### ISSUE TITLE
Wrong column number from chktex (Tab) + character/byte skipping in actions

### ISSUE THREAD

**Issue by ivankokan** [James-Yu/LaTeX-Workshop#829]
Hi,

Here is the interesting screenshot showing two issues:
![image](https://user-images.githubusercontent.com/1058211/46183473-4a948180-c2d1-11e8-8161-de3ecc6b75c9.png)

If I got the things correctly, chktex detected a common `$...$` -> `\(...\)` TeX vs LaTeX thing starting at 13th character but it reported column number is 21 (because of its own setting `TabSize = 8`). When I remove the leading tab character, this is what happens:
![image](https://user-images.githubusercontent.com/1058211/46183628-0655b100-c2d2-11e8-9fa9-30b7f5210a4f.png)

As you can see, codeaction suggestion is shifted by one character to the right-hand side, and clicking it does not make any change. The root cause for the misplacement is the character `č` in UTF8-encoded input file. Once I remove it, codeaction suggestion is placed correctly and the action successfully replaces `$P(x,y)$` by `\(P(x,y)\)`.

So, to conclude:
1) [UX suggestion] Could LaTeX-Workshop consider `TabSize = 8` setting from chktex?
2) [Bug?] Is it really true that non-one-byte-characters are the root cause of the presented issue and can that be fixed?

Kind regards, Ivan

**Comment by James-Yu** [comment]
Unfortunately, it seems that neither of each can be handled from the extension side, though I will look into point 1.

**Comment by ivankokan** [comment]
Hi, thank you for the prompt reply.

I actually expected that point 2. could be handled easier than point 1. :D

If I run chktex on my console (Windows 7 cmd), I get this:
` ^^^^^^^
Warning 46 in zadatci\drugi-dan.tex line 11: Use \( ... \) instead of $ ... $.
Ozna─Źimo s $P(x,y)$ uvr┼ítavanje vrijednosti $x$ i $y$ u po─Źetnu jednad┼żbu. T
ada imamo
            ^^^^^^^^`
So, it seems that `^^^^^^^^` are correctly vertically aligned below the problematic content `$P(x,y)$`.

Based on the code I have checked, codeaction is implemented the right way assuming that position is given correctly - but it is not because vscode itself gets the wrong information (what can be seen in the upper screenshot, underlined).

Now I am onto checking the `parseLinter` function, to understand the parsing algorithm...

Kind regards, Ivan

**Comment by James-Yu** [comment]
That seems exactly the problem. Bear in mind that most LaTeX tools are designed in the age of ASCII. CJK users are still cursed by the compilers on non-english file names. It seems hard to resolve the problem besides requesting users to use `\v{a}` instead of `ǎ`.

**Comment by ivankokan** [comment]
Let us keep track of the chktex tracker: https://savannah.nongnu.org/bugs/index.php?54750.

**Comment by ivankokan** [comment]
Consider this idea in handling point 1... Assuming that local/user settings override default chktex settings, just override them using `TabSize = 1` or something like that.

**Comment by ivankokan** [comment]
When it comes to "`character` vs `byte`" issue, I asked whether something can be done from vscode's side until (one day) chktex becomes Unicode-friendly: https://stackoverflow.com/questions/52878605/replacing-from-byte-to-byte-not-from-character-to-character.

**Comment by ericrbg** [comment]
I'm also running into this issue - I changed my `TabSize` in `chktexrc` to be equal to 4, and it's struggling with that, but it was also previously struggling with `TabSize = 8`. I'm not using any weird unicode characters, and in fact the chktex is bringing up the right column according to VSCode, see below:
![image](https://user-images.githubusercontent.com/37984851/57420989-deccac80-7201-11e9-913d-793195a9e49a.png)

**Comment by ivankokan** [comment]
@ericrbg Shouldn't `TabSize = 1` be the correct setting since you are really using tabs in VSCode?

**Comment by ericrbg** [comment]
@ivankokan yes, that fixed it. still confused about why the column numbers line up with space counting... argh we make it so complicated for ourselves

**Comment by jlelong** [comment]
What is the conclusion on this? Is the issue fixed ?

**Comment by ivankokan** [comment]
There are two issues here, actually:
1) encoding

I am planning to improve chktex so it can operate on arbitrary encodings, not just ASCII. Still no progress.

Until proper solution on chktex's side is made, this plugin should interpret chktex's `%c` output as the number of bytes (not characters) to correctly highlight/position warnings and fix suggestions in GUI. Someone could take this one?

2) tabs
LaTeX-Workshop should set proper `TabSize` setting for chktex based on whether tabs are used (`= 1` should do, apparently) or n spaces are used for indentation (`= n` should do in this case).

Kind regards, Ivan

**Comment by ivankokan** [comment]
> @ivankokan yes, that fixed it. still confused about why the column numbers line up with space counting... argh we make it so complicated for ourselves

Simpliy because tab character is one byte.

**Comment by ivankokan** [comment]
@ericrbg Can you please explain how/where did you set `TabSize` for chktex in VSCode?

**Comment by ericrbg** [comment]
I had to change chktexrc itself.
