### ISSUE TITLE
Latexmk recipe ignores .latexmkrc in the directory in the document

### ISSUE THREAD

**Issue by tats-u** [James-Yu/LaTeX-Workshop#830]
### Description

I created .latexmkrc to compile documents with LuaTeX in the same directory as a TeX document and tried to cfompile the document with Latexmk, but it ran PdfTeX, not LuaTeX.  Latexmkrc must be executed in the same directory as the document and .latexmkrc.

### Log messages

```
[12:55:29] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,c:/Users/tatsu/Dropbox/lab/rinko/201810xx/201810xxuchino
[12:55:31] LaTeX log parsed with 3 messages.
[12:55:31] Recipe returns with error: 12/null.
[12:55:31] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,c:/path/to/document/root/document
[12:55:34] LaTeX log parsed with 3 messages.
[12:55:34] Recipe returns with error: 12/null.
[12:55:59] RECIPES command invoked.
```

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Create a TeX document for LuaLaTeX and .latexmkrc in a directory
2.  Compile with this extension with the default recipe and tools

`.latexmkrc`:

```perl
#!/usr/bin/perl

$pdf_mode = 4;
$postscript_mode = $dvi_mode = 0;
$bibtex = 'upbibtex';
$lualatex = 'luajitlatex %O -synctex=1 -interaction=nonstopmode %S';

```

### Expected behavior

The document tries to be compiled with Lua(JIT)LaTeX

### Actual behavior

The document tries to be compiled with pdfLaTeX

### Additional Information

~~I will append lacked information (logs etc.) later.~~

**Comment by jlelong** [comment]
It does work as expected. Cannot reproduce the problem.
Can you provide your directory structure?

**Comment by tats-u** [comment]
I did not know that there is `-pdf` option in the arguments of the default recipe (latexmk).

**Comment by ken-nakanishi** [comment]
I think the `-pdf` option in the arguments of the default recipe should be removed or the default `latexmk 🔃` recipe should be renamed `latexmk (pdflatex)`, because latexmk is not only for pdflatex.
https://github.com/James-Yu/LaTeX-Workshop/blob/46d0db6895124f5b28986f98ced31fd80a7e5120/package.json#L596

**Comment by tamuratak** [comment]
Please open a new issue.

**Comment by ken-nakanishi** [comment]
OK!
