### ISSUE TITLE
Compile files without path

### ISSUE THREAD

**Issue by OsbertWang** [James-Yu/LaTeX-Workshop#834]
### Description

I want to compile my .tex file contained in the path with Chinese character in Windows 10. The file is encoded in UTF-8 and I use XeLaTeX. There's something wrong because XeLaTeX can't recognize the Chinese character.

### Log messages

Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Rule 'xelatex': Rules & subrules not known to be previously run:
   xelatex
Rule 'xelatex': The following rules & subrules became out-of-date:
      'xelatex'
------------
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -file-line-error -halt-on-error -interaction=nonstopmode -no-pdf -synctex=1 -no-pdf -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "e:\Users\wangran\Documents\���ƴ�ʿ��\���ۿ�\20180921\latex-wangran\geobook\main.tex"'
------------
Latexmk: applying rule 'xelatex'...
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
Can't spawn "xelatex -file-line-error -halt-on-error -interaction=nonstopmode -no-pdf -synctex=1 -no-pdf -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "e:\Users\wangran\Documents\���ƴ�ʿ��\���ۿ�\20180921\latex-wangran\geobook\main.tex"": Inappropriate I/O control operation at d:\texlive\2018\texmf-dist\scripts\latexmk\latexmk.pl line 9090.
Latexmk: fls file doesn't appear to have been made.
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 255
      Refer to 'main.log' for details
----------------------
This message may duplicate earlier message.
Latexmk: Errors, so I did not complete making targets
Latexmk: Failure in processing file 'e:/Users/wangran/Documents/���ƴ�ʿ��/���ۿ�/20180921/latex-wangran/geobook/main':
   (Pdf)LaTeX didn't generate the expected log file 'main.log'
----------------------
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
D:\texlive\2018\bin\win32\runscript.tlu:803: command failed with exit code 12:
perl.exe d:\texlive\2018\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -xelatex e:/Users/wangran/Documents/���ƴ�ʿ��/���ۿ�/20180921/latex-wangran/geobook/main

### How to reproduce

1.  I think that we should compiler the .tex file without the path.

**Comment by Stone-Zeng** [comment]
Possible duplicated with #269.

**Comment by OsbertWang** [comment]
OK, thank you. I forget to read the readme file. %DOCFILE% is useful.
