### ISSUE TITLE
[Question] Why ctrl+alt+j for synctex from line?

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#836]
Should be a quick question.

Neither <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>s</kbd> or <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>l</kbd> seem to be used by vs code or this extension, so with that in mind; for **s**ynctex from current **l**ine, why was <kbd>j</kbd> used as the last key for this shortcut?

**Comment by jlelong** [comment]
They are used for _Save All_ and _Toggle Find In Selection_ respectively.
