### ISSUE TITLE
Disable Autorotate for ps2pdf in with latexmk

### ISSUE THREAD

**Issue by dslemusp** [James-Yu/LaTeX-Workshop#838]
### Description

I am using pstool package to load matlab generated figures in my tex file. However once I compile the file the page gets automatically rotated (in a wrong way). 

So far the best I can do is to disable the behavior by manually passing `-dAutoRotatePages=/None` to ps2pdf in the terminal. I would like to know if there is a better way to prevent this automatic rotation or an automatic way of passing directly `-dAutoRotatePages=/None` through "latexmk" in VSCode.

Thank you

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Compile the attached root.tex in [mwe.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2434785/mwe.zip)
2. 
3. 

### Expected behavior

Page 1 should not be rotated

### Actual behavior

Page 1 is rotated

### Additional Information

Here my user config for latexmk
{
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdfps",
                "%DOC%"
            ]
        }

**Comment by jlelong** [comment]
This is not related to the extension.
