### ISSUE TITLE
Merge vscode-latex-utilities into this project?

### ISSUE THREAD

**Issue by viktorstrate** [James-Yu/LaTeX-Workshop#841]
> This is a continuation of the end of the discussion in issue #809, but i've made a issue, because this isn't only related to shortcuts.

## Backstory
Hi, i'm the creator of another vscode extension called [vscode-latex-utilities](https://github.com/viktorstrate/vscode-latex-utilities). It is a small extension which aim is to extend this plugin, with new features. Because I wanted to add some bigger features, I decided to make my own extension, instead of submitting pull requests to this project.

## Merge request
As discussed in this issue viktorstrate/vscode-latex-utilities#5, @tecosaur asked me if I wanted to merge vscode-latex-utilities into this project, which I think is a good idea. In that way, users would not have to install multiple extensions to work with LaTeX in vscode.

Below is some of the reasons to merge the projects.

### Toggle tags (improvement)
In vscode-latex-utilities, tags can be toggled. When the cursor is inside an already wrapped sentence, and the command to toggle the tag is called, the tag will be removed. If it doesn't find the wrapping tag, it will add the snippet.

This currently only works for `textbf`, `textit`, `emph`, `underline`, but it is written in a way that is easily extendable.

The code for this can be found [here](https://github.com/viktorstrate/vscode-latex-utilities/blob/master/src/textManipulation.ts#L7-L68)

### \item is automatically added (addition)
When enter is pressed inside an `itemize` block, `\item` will automatically be added on the new line, this can be disabled in the settings, because I think that not everyone would want this.

## Your opinion
@tecosaur and I would like to hear what the maintainers @James-Yu and @jlelong think about this?
Please also read @tecosaur's issue viktorstrate/vscode-latex-utilities#5

I would be happy to make the initial merge on a new branch on vscode-latex-utilities, and send a pull request.

**Comment by jlelong** [comment]
@viktorstrate Great if you are ready to contribute!

### Keybindings

I did not know your extension, so I have implemented a mechanism to easily assign a keybinding to any snippet. For now, toggling is not possible in what I have done but I am pretty sure we could adapt your approach to make it work with text transformation snippet. However, I am not sure people toggle `\textxx` commands that much. Is the extra effort worth it? 

### \item

I was about to create a new branch to reintroduce all the stuff around automatically adding `\item`.  It would nice if you could help us debug this. Here are the features I implemented
- When on a line starting in `\item([])?`, <kbd>Enter</kbd> creates a newline and inserts `\item([])?`
- Hitting <kbd>Enter</kbd> on a line only containing `\item([])?` removes it.

Does your extension takes a similar approach or is it based on the environment name?

**Comment by viktorstrate** [comment]
I would like to contribute :)

### Keybindings
I think it would be quite easy to adopt my tag implementation, with minimal code changes. Since `extension.commander.insertSnippet('textxx')` could be replaced with my function `toggleSelectedKeyword('textxx')`. I will make a pull request later.

### \item
For \item, i am doing it in another way. I check if the cursor is inside a \begin{itemize} block, and enter is pressed. But I think your solution might be better.

**Comment by tecosaur** [comment]
Yay! Also if you don't mind some ideas from me.

### Keybindings
Yes!! 😁 If it's fairly to copy/paste with minor modifications I'd be more than happy to expand the implementation out to cover all of the original tags (because why not)

### \item
From a vague impression I got (entirely likely it's wrong) there were some issues in the method/implementation of the if-item-in-line approach. Since the two methods aren't mutually exclusive - as long as there isn't much of a performance impact would combining them be the most robust solution?

**Comment by jlelong** [comment]
### Keybindings

@viktorstrate waiting for your PR. I guess that the `extension.commander.insertSnippet('....') ` should be turned into `toggleSelectedKeyword('....')` for `textxx` only.

@tecosaur actually, all the keybindings you had defined in `package.json` now work. You can easily add new ones. See the log message of 8a40cb3.

### \item

I have reinstalled the _Item on Enter_ feature in the [item branch](https://github.com/James-Yu/LaTeX-Workshop/tree/item). Now, we have to debug it 😬

Currently, <kbd>Ctrl</kbd>+<kbd>l</kbd>,<kbd>Ctrl</kbd>+<kbd>Enter</kbd> inserts `\n\item`. The if-item-in-line approach was inspired from the markdown list feature. In some cases it may not work, eg with hard wrapped lines or with environments in the middle of an item entry. In these cases the inside-itemize approach is better, but there are many list like environments in LaTeX and some users may even define theirs. Both approaches have pros and cons. I guess that the name of the current environment can be extracted from the function [selectEnvName](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/envpair.ts#L153). 

To avoid too much extra complexity, we could maybe stick to the if-item-on-line approach with a configuration variable to deactivate it, plus a dedicated keybinding to enter `\n\item`. Your opinion?

**Comment by tecosaur** [comment]
I doubt you were asking for my opinion but I'm of the mind that since pressing enter a second time removes the `\item`, and what I expect the incidence rate of exceptions to the if-item-on-line approach to be, the benefits far outweigh the losses.

For the keybindings, I'm also of the mind of having it so it's the `textxx` commands, though perhaps also one or two select other commands (`mathbf`, `underline`, etc.) also thanks for telling me about `8a40cb3` - I'll have one or two ideas that may make use of that 🙂

**Comment by viktorstrate** [comment]
@jlelong I will try to make the pull request later today.

I thought that every tag that currently has a shortcut, and has this structure `\tagname{ ... }`, should be replaced by the `toggleSelectedKeywork('...')` function. This would add more consistency instead of only some of them?

I don't know if this works like this currently, but with `toggleSelectedKeywork('...')`, if you make a selection first, the selected text will be wrapped. Like this:

Hello, **this is** a sentence `-->` Hello, **\textbf{this is}** a sentence

> where __bold__ is the selected text

**Comment by jlelong** [comment]
> I will try to make the pull request later today.

Great but no hurry.

> I thought that every tag that currently has a shortcut, and has this structure \tagname{ ... }, should be replaced by the toggleSelectedKeywork('...') function. This would add more consistency instead of only some of them?

I agree. Yes it works as in your example.
