### ISSUE TITLE
create output folder automatically

### ISSUE THREAD

**Issue by Hui-Li** [James-Yu/LaTeX-Workshop#842]
My settings force latex to output to build folder. However, it cannot build if there is no build folder in the project and I have to manually create build folder before I compile. Is there a way to create the folder automatically before compiling? 

My tool setting:

```
    "latex-workshop.latex.tools": [
        {
          "name": "pdflatex",
          "command": "pdflatex",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-output-directory=./build/",
            "%DOC%"
          ]
        }, {
          "name": "bibtex",
          "command": "bibtex",
          "args": [
            "./build/%DOCFILE%"
          ]
        }
    ]
```

**Comment by James-Yu** [comment]
You can create a tool of `mkdir`.

**Comment by Hui-Li** [comment]
@James-Yu can you provide an example? I am using Windows. As far as I know mkdir is an internal command for CMD and not an executable found in PATH. See:[https://superuser.com/questions/1121297/windows-cannot-find-mkdir](https://superuser.com/questions/1121297/windows-cannot-find-mkdir)

**Comment by James-Yu** [comment]
As suggested by the provided link, you may use `cmd.exe` as the command, and `/c` `mkdir` as well as other necessaries as arguments.
