### ISSUE TITLE
Open PDF tab automatically after building

### ISSUE THREAD

**Issue by Hui-Li** [James-Yu/LaTeX-Workshop#843]
I use build-in tab to view the generated pdf. My setting is like following:

```
"latex-workshop.view.pdf.viewer": "tab"
```

When I open a new project and compile it, the tab will not automatically appear. I have to press `ctrl + alt + v` to open the pdf tab. Is there a way to automatically invoke pdf tab after building latex files?

**Comment by James-Yu** [comment]
Short answer: no. A good news is that the opened PDF can be refreshed upon subsequent build successes.
