### ISSUE TITLE
Reintroducing the item-on-enter feature. Testers are welcome!

### ISSUE THREAD

**Issue by jlelong** [James-Yu/LaTeX-Workshop#847]
I have started reintroducing the feature of automatically inserting `\item` while hitting enter and the current line already starts in the same way. This was the prupose of #742, but it unfortunately introduced many bugs. I think I have fixed many.

I need help to test all this in the [item branch](https://github.com/James-Yu/LaTeX-Workshop/tree/item).

**Comment by tecosaur** [comment]
What would I need to do to test this?

**Comment by viktorstrate** [comment]
This is only apparent on the _item_ branch, and I don't know if you are already aware of this.

When I am inside a begin tag and press enter the cursor is not automatically indented, exactly as described here https://github.com/James-Yu/LaTeX-Workshop/issues/742#issuecomment-413203153.

**Comment by jlelong** [comment]
Strange, because I thought I had fixed this in my last commit. At least it works fine for me.
Sorry to ask but are you sure you are up to date with the item branch? Are you using Windows? That might be related to eol encoding but I used the same approach as in [vscode-markdown](https://github.com/neilsustc/vscode-markdown/blob/master/src/listEditing.ts).

**Comment by viktorstrate** [comment]
Oops, i pulled the branch from my fork.

**Comment by jlelong** [comment]
So do you confirm that the indentation bug has been fixed for you?

**Comment by viktorstrate** [comment]
I have just tested it, and the indentation works correctly. 👍

**Comment by jlelong** [comment]
I have just added the variable `latex-workshop.bind.enter.key` to activate or not the feature, see c891f30. Default is true.

If no bug is found, I plan to merge it in master at the beginning of next week.
