### ISSUE TITLE
Split down 2 pdf viewers buggy

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#849]
Not sure if this is a bug within the vscode api, but trying to get a split down view for 2 **different pdf** viewers is impossible now or at least very buggy. When you split open a new pdf, the old pdf disappears. Is this related to how pdfs are served? Are they served on one port?

demo here: https://i.imgur.com/xcKUDvq.gifv

**Comment by James-Yu** [comment]
Released a new fix in `5.11.1`.

**Comment by Astrantia** [comment]
@James-Yu doesn't work unfortunately :(

**Comment by James-Yu** [comment]
It works just correct on my side. If not working, please provide details.

![image](https://user-images.githubusercontent.com/4210342/46520386-6938e080-c8ae-11e8-91ec-f4c007c5d37b.png)

**Comment by Astrantia** [comment]
@James-Yu 
https://i.imgur.com/wbXALYP.gifv

**Comment by James-Yu** [comment]
But what's wrong with the behavior? A new panel is created and the original one does not disappear. You can drag the same or multiple pdfs in the new panel and both persist.

**Comment by Astrantia** [comment]
Oops, here's the issue: https://i.imgur.com/oZw4jjB.gifv

**Comment by James-Yu** [comment]
This is the best I can get. Until vscode allowed extensions to hook file types, this might be the best solution.

**Comment by Astrantia** [comment]
@James-Yu Is that in reference to this issue? https://github.com/Microsoft/vscode/issues/12176
