### ISSUE TITLE
.tex->.pdf synctex broken on update 1.4.0

### ISSUE THREAD

**Issue by jose-a-sa** [James-Yu/LaTeX-Workshop#85]
Hi,

after I updated to version 1.4.0 I noticed that syntex stopped working using my key shortcut and also right-click command. Ctrl+leftmouse on the pdf still works.

Regards, José

**Comment by jabooth** [comment]
Oh sorry to hear that @jose-a-sa!

Just to check, if I understand you are saying the sync is not working at all from .tex to .pdf, but is always working from .pdf to .tex?

I'm on the phone at the mo but will take a look at this asap

**Comment by jose-a-sa** [comment]
Yeah, thats right @jabooth. I tried to clean the working directory (synctex.gz) and build again and it is not working. I tried it from the vscode actions bar, using the right-click context menu and from a keyboard shortcut.

**Comment by jabooth** [comment]
sorry for that @jose-a-sa that's my bad, see #86.

The fix is now on master. it's 5am in Hong Kong so you might just have to wait a few hours for a point release, @James-Yu is currently the only person who can deploy to the marketplace!

**Comment by James-Yu** [comment]
Morning! @jose-a-sa the fix is released as version `1.4.1`.
