### ISSUE TITLE
Item On Enter Bugged?

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#851]
I just updated to the latest master @jlelong and this is what I get 
![image](https://user-images.githubusercontent.com/32885386/46586563-45ac9c00-ca4e-11e8-8e01-8604c7801deb.png) when I click enter in the itemized environment

**Comment by jlelong** [comment]
Hum, `latex-workshop.onEnterKey` is defined in [main.ts](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/main.ts#L121). Are you sure you are up to date and do not have personal changes in your copy?

**Comment by Astrantia** [comment]
@jlelong I forgot to recompile 😳
