### ISSUE TITLE
Auto-Complete \input

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#853]
A good feature to consider.

**Comment by James-Yu** [comment]
A rough solution to the said feature. Tests are greatly welcomed.

**Comment by Astrantia** [comment]
@James-Yu works for \include, but not for \input

**Comment by Astrantia** [comment]
@James-Yu observation: it works for both, but if you accept snippet for `include`, suggestions wont show up. you have to manually enter `\input{`

**Comment by JavierReyes945** [comment]
Is it just me, or the file path autocompletion (for `\includegraphics` at least) could be also conditioned and formatted depending on whether the path to images is defined in the preamble? In a big document scenario (main file, with several includes or inputs for specific content in `/content`, and an `/img` folder) the extension suggest the path by first showing tex files and folders in root path, and when selecting the `/img` folder, it autocompletes the path including the img folder (e.g. `\includegraphics{img/image_name.png}`), but it is normal to have the path already defined in the preamble (`\graphicspath{{img/}}`).

**Comment by jlelong** [comment]
For the moment, we cannot take into account any information given by `\graphicspath`.
