### ISSUE TITLE
We can no longer tab out \( \)

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#854]
I would blame https://github.com/James-Yu/LaTeX-Workshop/pull/617

**Comment by tecosaur** [comment]
See #850

**Comment by jlelong** [comment]
The benefits introduced by #617 (see explanations in #850) overcome by far the slight inconvenience of not being able to tab out of some maths snippets.

**Comment by innerlee** [comment]
What was the benefit? If it was for auto-brackets, i think that maybe auto-brackets needs a better solution rather than sacrifice this.

**Comment by jlelong** [comment]
This is discussed in details in #609 and applies too many more snippets than `\( .... \)`. We could not find any better approach at the time and nobody has complained for 5 months. If you have a better idea, you are welcome to expose it and eventually make a PR.

**Comment by innerlee** [comment]
maybe relevant link https://github.com/Microsoft/vscode/pull/52634
