### ISSUE TITLE
Hover Preview. Please try!

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#856]
Hi,
I have implemented hover preview. When you put your mouse cursor on \\begin{...} or $...$, then an equation rendered with MathJax hovers. I want this one to be merged to LaTeX-Workshop although it is now alpha version. Please try [this branch](https://github.com/tamuratak/LaTeX-Workshop/tree/hover_preview). Additional libraries are not required.

![oct-08-2018 19-11-30](https://user-images.githubusercontent.com/10665499/46603628-9267a400-cb2e-11e8-8492-a94df5655ac2.gif)

## implementation

1.  In HoverProvider,  we send a string of equation  to WebView using WebView.postMessage
2. In WebView, with MathJax, we convert the string to a SVG string.
3. We render the SVG string  in a canvas element again.
4. Wiht [HTMLCanvasElement.toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL), we convert the image in the canvas element to a string of png dataURL.
5. We send back the string to LaTeX-Workshop extension process with [postMessage](https://code.visualstudio.com/docs/extensions/webview#_passing-messages-from-a-webview-to-an-extension).
6. We make a markdown string with the dataURL.
7.  Hover renders the markdown.
8. We've done it!

## Pros

- Fast. It must be faster than you expect. Thanks to V8.
- We do not need to install any other libraries and binaries.  Implemented only in TypeScript and JavaScript.
- No abusing of VSCode API. I believe.

## Cons

- We need WebView. We now use the WebView of pdf.js viewer for that purpose. When you close the preview tab, hover will not appear.
- Hover API is very restricted. Additional features are impossible.

## ToDo

- Change colors of rendered equations to appropriate ones for each theme. Now only suited for light themes.
- Zoom option for rendered euqations.
- Others?

**Comment by James-Yu** [comment]
Great work! Really looking forward to its maturity!

**Comment by Astrantia** [comment]
@tamuratak Great work!! Thanks for sharing this contribution. I absolutely agree speed is a number one priority here, so why did you go with MathJaX instead of KaTeX?

**Comment by Astrantia** [comment]
@tamuratak I tried it just now and it seems to be working fine with the light themes but completely unusable with dark themes. The one thing I noticed is that when using 4k monitor the previews are blurry.

**Comment by Astrantia** [comment]
I don't know if you can see here, but I tried to take a picture of it:
![pic](https://i.imgur.com/to69Lfl.jpg)

**Comment by tamuratak** [comment]
If you set `Window: Zoom Level` of VSCode to none zero value,  preview is  blurry.  If not, I need more information. Thanks.

**Comment by tecosaur** [comment]
This may not be the most useful comment but,
# ❤❤❤

**Comment by Astrantia** [comment]
@tamuratak place a cursor inside `\|frac{1}{2}` , (where `|` is). Output:
![image](https://user-images.githubusercontent.com/32885386/46741194-7e2cbf80-cc72-11e8-95be-c02f75abb801.png)

**Comment by tamuratak** [comment]
Now, we support hover preview for dark themes. Please test! The most tricky part of this implementation is that we cannot know actual colors used in each theme in extension process, but we can know the colors in WebView process. I have found this workaround in this [entry](https://qiita.com/henoc/items/0051d7bf516a91c17ec4) by @Henoc. Great thanks.

![oct-10-2018 22-48-35](https://user-images.githubusercontent.com/10665499/46740935-e618ef80-ccde-11e8-90a5-e9b6e0dd63d9.gif)

Since I have added MathJax as submodule for offline editing, you have to type
```
git submodule init
git submodule update
```
after `git clone`.

Regards,

**Comment by tamuratak** [comment]
> place a cursor inside `\|frac{1}{2}` , (where `|` is). Output:

This is a wontfix bug. I think what is happening is obvious to users. If you want not to render cursor, please set `latex-workshop.hoverPreview.cursor.enabled` to false. Thank you for your testing.

**Comment by Astrantia** [comment]
@tamuratak What about using Unicode ‡ ? Will MathJax fail with Unicode \ddagger ‡ ?

**Comment by Astrantia** [comment]
@tamuratak Or what about adding an if case for `'\frac{x}{y}'` then `'\ddagger' + '\frac{x}{y}'`

**Comment by Astrantia** [comment]
@tamuratak looks good to me now. 
Only thing I don't like is about scaling. When I set scaling to 2, on 4k monitor it starts to look good, but then it is too big. If I reset scaling to 1 then it is blurry again. Do you think that can be fixed?

**Comment by Astrantia** [comment]
@tamuratak One final thing:
```
       \begin{align*}
            \frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot
        \end{align*}
```
Why does this take a lot of time to load?

**Comment by tamuratak** [comment]
@Astrantia this problem is reproducible for me. I have measured execution time of each step. What takes lots of time seems to be VSCode rendering svg in hover. So what I can do is nothing right now.

**Comment by Astrantia** [comment]
@tamuratak Isn't it strange though, because rendering svgs with way more and complicated equations take significantly less time.

**Comment by Astrantia** [comment]
@tamuratak Also, with the vscode renderer dark themes are messed up again. Preferably we want light colored text on the dark background.

**Comment by Astrantia** [comment]
@tamuratak Are you sure something is wrong with vscode svg renderer for performance? Try hovering over this: 
```
        \begin{align*}
            \frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}
            \cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}
            \cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}

        \end{align*}
```
VS
```
       \begin{align*}
            \frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot\frac{x}{xx}\cdot
        \end{align*}
```

**Comment by tamuratak** [comment]
@Astrantia you are right. Now fixed. Thanks.

**Comment by Swoy** [comment]
If MatJax is to large, how about [Katex](https://katex.org/)?

**Comment by James-Yu** [comment]
@Swoy I'm not familiar with either of them. It may rely on some extra great work from the community.

**Comment by Swoy** [comment]
@James-Yu I'm looking into it. So far I an see it can be rendered into HTML5 and we could maybe use [ canvas2svg.js](https://github.com/gliffy/canvas2svg) to have it rendered into SVG.

Seeing how insanely fast it is compared to MatJax, I suspect that this wouldn't be too much overhead?

**Comment by James-Yu** [comment]
I would definitely prefer KaTeX given its speed and small footprint. Any contributions are welcomed, and I will switch to this issue in the next week if not resolved then. Though that requires a lot of learning 😢

**Comment by Swoy** [comment]
I'm going to deep dive a bit over the next days, if anything, I can provide my findings here.
I found [this](https://github.com/Khan/KaTeX/pull/251) pull request that explains a bit.

**Comment by James-Yu** [comment]
I looked into KaTeX a bit, and found it somehow limited compared with MathJax, e.g., https://github.com/Khan/KaTeX/issues/604. I suppose this issue has served its need, and we can have a new issue on KaTeX related discussions.

**Comment by tamuratak** [comment]
As for the footprint of MathJax, the large part of it is `MathJax/fonts/HTML-CSS/TeX/png`, ~114MB, which we don't require for SVG output. Other files can be removed also.  While ![preview-inline](https://github.com/mangecoeur/preview-inline), an Atom extension using MathJax for SVG output, includes MathJax code in its own repo, the size of included MathJax codebase is ~7MB. At least, we can discuss about including MathJax codebase.

As for KaTeX, KaTeX supports only HTML and MathML as an output format, neither SVG nor PNG. Considering the restriction of VSCode API, we cannot use  KaTeX for math preview on hover.

**Comment by James-Yu** [comment]
Incorporating a custom version of MathJax in the extension is highly appreciable I would say.

**Comment by alpha195** [comment]
Is it possible to preview inline like [preview-inline](https://github.com/mangecoeur/preview-inline)?
![](https://raw.githubusercontent.com/mangecoeur/preview-inline/master/resources/demo.gif)

**Comment by James-Yu** [comment]
Seems not possible @alpha195 Limited by vscode.

**Comment by ShuCaiMonkaS** [comment]
It seems it only works with tab preview but not external web preview.

**Comment by sloth3toe** [comment]
I'm using version 5.13.0 but do not see this hover feature at all. Am I missing any steps?

**Comment by viktorstrate** [comment]
It should work "out of the box", it does for me at least..

Does your files have a `.tex` extension?
And does it otherwise build without problems, using LaTeX Workshop?

**Comment by sloth3toe** [comment]
@viktorstrate , thanks. Yes I can compile just fine. I've been using this extension for a while with all of my .tex files.

I tried a minimal file as you suggested, but I don't see any hovering capability at all:

```
\documentclass[12pt]{article}
\usepackage{amsmath}

\begin{document}
\begin{align*}
	e=mc^2
\end{align*}

$ e=mc^2 $
\end{document}
```

**Comment by carmo-lucas** [comment]
I'm having an issue where in every equation in my document, hover is showing some redefined commands I created. Any ideas on how to fix it?

<img width="1330" alt="Screen Shot 2019-11-13 at 19 40 33" src="https://user-images.githubusercontent.com/39373549/68810658-7dbce000-064d-11ea-8dd6-b0692ff6055d.png">

**Comment by tamuratak** [comment]
Please open a new issue filling out information required in the issue template.
