### ISSUE TITLE
Snippets fail in special case

### ISSUE THREAD

**Issue by allenryb** [James-Yu/LaTeX-Workshop#857]
Today I updated the new sable vscode and found that sometimes snippets fail. The code is as follows:

![image](https://user-images.githubusercontent.com/6965371/46643697-d2bb3680-cbaf-11e8-8578-fbf0a2d2dc9c.png)

The column number after `@c` is 101.

But this snippet works if one of the following happens:
1. delete one character `a` to make `@c` inside 100 columns;
2. put `@c` outside `A_` --- this works even beyond  100 columns.

This is related to the issue [#801](https://github.com/James-Yu/LaTeX-Workshop/issues/801#issuecomment-428041493) .

**Comment by James-Yu** [comment]
[#58807](https://github.com/Microsoft/vscode/issues/58807)

**Comment by allenryb** [comment]
> [#58807](https://github.com/Microsoft/vscode/issues/58807)

Thanks for your reply!
I am sorry to make confusion.

This issue is a little different with [#58807](https://github.com/Microsoft/vscode/issues/58807) which is influenced by 100 characters limit.
Vscode has covered this.

But my case is that snippets still fail in subscript and superscript after 100 characters.

**Comment by James-Yu** [comment]
I don't get you. The vscode bug prevent snippets after 100 chars, which is your issue.

**Comment by allenryb** [comment]
This may be a new bug.
After 100 chars, if I want to use snippet in subscript or superscript, it fail.

**Comment by jlelong** [comment]
There is still issue here but not related to sub or superscript.

Beyond character 100, completion is only triggered at the end of the line. I will reopen #[58807](https://github.com/Microsoft/vscode/issues/58807).

**Comment by jlelong** [comment]
Issue [#60247](https://github.com/Microsoft/vscode/issues/60247) has been fixed in today's Insiders version and our snippets finally work great!
