### ISSUE TITLE
Data of other document shown in "Structure"

### ISSUE THREAD

**Issue by bantu** [James-Yu/LaTeX-Workshop#860]
### Description

The LaTeX Workshop extension extracts document structure from a .tex file and displays it nicely organised under "Structure". However, when working with multiple .tex documents, what is displayed under "Structure" corresponds to information extracted from the .tex file last built instead of the currently viewed .tex file.

### Log messages

Probably irrelevant.

### How to reproduce

1. Produce two LaTeX documents.
2. Build the first one.
3. Observe how "Structure" information updates and corresponds to the first document.
4. Open the second document.
5. Observer how "Structure" information still shows data from the first document.

### Expected behavior

Information shown under "Structure" corresponds to currently viewed .tex file.

### Actual behavior

Information shown under "Structure" corresponds to last built .tex file.

**Comment by James-Yu** [comment]
That is as designed. For the outline of the current document, please refer to the outline view in the first badge, i.e., explorer. The structure pane is designed to show the complete structure of the LaTeX project.

**Comment by bantu** [comment]
> The structure pane is designed to show the complete structure of the LaTeX project.

My LaTeX project consists of multiple independent LaTeX documents.

> For the outline of the current document, please refer to the outline view in the first badge, i.e., explorer.

Works for me.

Cheers

**Comment by James-Yu** [comment]
If multiple projects are in the same project, the extension cannot mind-read which structure you would like to read. It fallbacks to the last compiled one.
