### ISSUE TITLE
[Feature Request] Custom Math & Verbatim Environments/Commands

### ISSUE THREAD

**Issue by iFailatGitHub** [James-Yu/LaTeX-Workshop#869]
### Description

I'd like to have an option in LaTeX workshop where I could name math/verbatim environments/commands. There's a lot of these environments & commands (e.g. minted, a verbatim environment; empheq, a math environment, etc.) from CTAN. It would be nice if I could list these said environments so that they'd get the correct syntax highlighting.

### Additional Information

chktexrc has options called MathEnvir, MathCmd, VerbEnvir. Perhaps you can read the custom math/verbatim environments from there?

**Comment by jlelong** [comment]
Unfortunately, the current approach used by VScode to describe syntax highlighting does not allow the use of external variables.
