### ISSUE TITLE
Scrolling and touch issues with built-in pdf viewer

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#87]
1) Scrolling via click-and-drag of the scroll bar in the built-in pdf viewer is very... spastic. Jumps around and stuff.

2) This doesn't matter as much, but if anyone cares to fix it, the pdf viewer also doesn't respond to touch on my SP4.

**Comment by James-Yu** [comment]
Does this issue exists in browser viewer? I can reproduce the tab viewer scroll bar problem on one of my computer but not on others. This should be an upstream problem with either PDF.js (if browser has the problem too) or vscode-iframe (if not).

**Comment by James-Yu** [comment]
As to SP4 or any touch screen systems/hardware, PDF.js seems not to be built considering touch scrolling. Correct me if I'm wrong.

**Comment by zachjweiner** [comment]
It's just fine in the browser viewer. And no problem re: touch; I hardly care, but just thought I'd bring it up to people who know more than me!

**Comment by jabooth** [comment]
> It's just fine in the browser viewer

Scrolling isn't jumpy, and touch works well in the browser too?

If so we might be able to address both..

**Comment by zachjweiner** [comment]
Now that I check, touch does work in the browser!

**Comment by James-Yu** [comment]
Hmmmm... It might be related with the `iframe` we use in tabs. Will check if it is causing trouble.

**Comment by denis-ko** [comment]
I have a related issue with the built-in pdf viewer. Zoom stops working properly after the viewer loses focus. However, I couldn't not figure out what scenario causes this problem,

**Comment by zachjweiner** [comment]
I tested the original issues I posted about for the first time in quite a while, and they are gone --- at least for me. I'll let you close it, @James-Yu, if you like.

**Comment by James-Yu** [comment]
It looks like a really lower level issue which is causing the problem. Glad the scrolling eventually works for you!
