### ISSUE TITLE
[Msg to Devs] I'm pumped for the next release

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#870]
This is best suited for a PM, not an issue but I can't see any other way to send a somewhat-off-topic message.

Just wanted to say:
(1) @James-Yu @jlelong @tamuratak @NavyAdmiral @viktorstrate
(2) Thanks for the continued work that makes this extension absolutely awesome (James and Jérôme) and for the contributions that allow for huge jumps in features (Takashi, NavyAdmiral, Viktor)
(3) I am very, very excited for the next release. Hover preview, faster startup, file suggestions, and proper text format toggling! I can't image it gets much better than this!

That's also from me, just though you all deserved a solid thanks for all the effort that's been put in.

**Comment by James-Yu** [comment]
Thanks for the message. I share the same feeling with you. The next release will be equipped with the hover review, which I will test a bit in the following days if not hours. Anyways, really glad that we have an excellent community on the extension!
