### ISSUE TITLE
Hover on preview not functioning

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#874]
@tamuratak @James-Yu 

I'll keep this short. I have the 5.12.1 update; In the changelog I see "Added: (#865) Hover on LaTeX for math preview.", however, I can't seem to get it working.

![demo](https://user-images.githubusercontent.com/20903656/46912326-e1855d00-cfa4-11e8-8f1d-ff9ea1eb4f22.gif)

Edit: Also, I think you mean #856.

**Comment by James-Yu** [comment]
Make sure you have a viewer opened in vscode. This is restricted by vscode and is currently a won't fix.

**Comment by tecosaur** [comment]
Aaaahhh, forgot about that reliance on webRender, thanks / sorry for bothering you. 
Also, an addendum: you may want to change the issue number referenced in the changelog - see my edit.

**Comment by tamuratak** [comment]
Please make a new issue. And show us log messages.

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)
