### ISSUE TITLE
[Feature request] Use tex macros in hover on preview

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#875]
## Issue
It's not nice to repeat stuff like `\mathbb{R}` lots when you can just do `\R` through `\newcommand{\R}{\mathbb{R}}`. Unfortunately, _preview on hover_ doesn't know what macros you've created at the moment — leading to red text and dodgy renders

![image](https://user-images.githubusercontent.com/20903656/46912378-85233d00-cfa6-11e8-80bc-8f9acf3a06dc.png)

## Possible solution?
Would it be possible to search for all `\newcommand` and `\renewcommand`s and pass them to mathjax surrounded by math deliminaters (see [here](https://docs.mathjax.org/en/latest/tex.html#tex-macros) for mathjax documentation)

### Example
```
\document{…
⋮
\newcommand{\R}{\mathbb{R}}
⋮
\[ \vec{v} \in \R \]
⋮
```
When hovering over the math, have tex macros inserted into the start of the math env like so:
```\[ \newcommand{\R}{\mathbb{R}} \vec{v} \in \R \]```
Comparison of results (current vs as above):
![image](https://user-images.githubusercontent.com/20903656/46912423-adf80200-cfa7-11e8-9b1b-eb76283033b1.png)
![image](https://user-images.githubusercontent.com/20903656/46912431-b4867980-cfa7-11e8-817c-d3248feb88b9.png)

### Extra thing
I noted while on the mathjax demo page that if I set `\[ \newcommand{\R}{\mathbb{R}} \]` as the contents, cleared it, and then set it to be `\[ \vec{v} \in \R \]` then it worked. This may be of interest.

### Addendum to 'Extra Thing'
I have found that if I hover over a math environment with `\newcommand` in it, all future hovering will remember that new command. I feel like this could be quite useful information.

Edit: One again, I realise I probably should mention @tamuratak.

**Comment by tecosaur** [comment]
### Addendum to 'Extra Thing'
I have found that if I hover over a math environment with `\newcommand` in it, all future hovering will remember that new command. I feel like this could be quite useful information.

**Comment by tecosaur** [comment]
### Update
With the move to a minimal local copy of mathjax, this minor inconvenience has become a much more significant issue, and now if there is anything it doesn't recognise then it fails completely. See screenshot below.

![image](https://user-images.githubusercontent.com/20903656/46926927-7f406100-d065-11e8-8f69-13da29a7482f.png)

**Comment by tecosaur** [comment]
### My thoughts on implementation
I'd imagine the following to be an effective solution:
 - On file opening
 - Search for lines beginning with `\newcommand` etc.
 - Pass those lines, joined together and surrounded with `\( … \)` to mathjax
 - Discard the output
Then this minor issue should be resolved. I would do this myself but I have no clue what the appropriate _vs code_ apis are.

**Comment by tamuratak** [comment]
When opening multiple TeX documents, the result of autoloading `\newcommand` is unpredictable. So I think that users should load those macros by themselves. For example, put macros after `\end{document}`
```
\end{document}

\begin{align*}
  \newcommand{\R}{\mathbb{R}}
\end{align*}
```
Then, move a mouse over it.

**Comment by tecosaur** [comment]
What do you mean by unpredictable?
