### ISSUE TITLE
Preview on Hover - Don't require webview / Remember colour scheme

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#879]
This is a continuation of the discussion found in #867.

> Without WebView, using mathjax-node, we can generate SVG of equations, c.f. use_mathjax_node. So if we know colors used in a current theme in an extension process, or if we know whether the theme is light or dark, we don't need WebView.
> 
> The main issue is the following. For LaTeX-Workshop users, it is difficult to understand, intuitively, that they have to open a pdf viewer to save color information if math preview in hover does not work, or when they switch a dark theme to a light one. There are lots of ways when and how to tell users such things. In documents, in an information message above status bar, or in hover. We have to choose a right way. I think that is the main issue.
> 
> Anyway, we'd better make a new issue on this topic.

### My thoughts on this
- Have a setting, something like `"latex-workshop.hover.theme"`: [`"unset"` (default) / `"light"` / `"dark"`]
- If this is possible have it such that if `"unset"`, on a hover come up the message "select theme" and the buttons "light" and "dark". Idealy this would come up in the hover box, if not as a generic prompt from the extension.
- If that's not possible / a bad idea perhaps just default to light and on first hover produce a message prompting the user to change this in settings.

**Comment by James-Yu** [comment]
This is actually a current key issue with the hover preview. I will look into it soon.

**Comment by tamuratak** [comment]
I think I have found a simple solution. Let us have an object in LaTeX-Workshop that associates the  name of each theme  with colors, like:
```
export const themes = 
{
    "Abyss" : { foreground : "#6688cc" },
    "Default Dark+" : { foreground : "#D4D4D4" },
    "Default Light+" : { foreground : "#000000" },
```
For default themes and popular themes. In an extension process, we can know the name of a theme used by a user. So, with this object, we can set an appropriate color to math preview in hover. Please try my ![branch](https://github.com/tamuratak/LaTeX-Workshop/tree/use_mathjax_node_with_theme_db).

When written with pseudocode, the behavior is as follows:
```
if latex-workshop.hoverPreview.foreground is defined? 
 use it
else if themes[themename].foreground is found?
 use it
else
 do nothing
end
```

The advantage of this solution is that users don't have to change their setting of Hover Preview even when they change their theme.

Regards,

**Comment by tamuratak** [comment]
Although I can create a vsix file with `vsce package` and can install it, a loading error, on MathJax.js, occurs when LaTeX-Workshop starts. In package.json, setting `"vscode:prepublish"` to `"tsc -p ./"` and creating a  vsix file with `vsce package`, then, no error occurs. I don't know much about webpack. So I have no idea. This problem might occur only on my Mac.
