### ISSUE TITLE
Pressing enter on the same line as an \item deletes it

### ISSUE THREAD

**Issue by lukedan** [James-Yu/LaTeX-Workshop#882]
### Description

Pressing enter on the same line as an `\item` deletes it.

### How to reproduce

1. Open any document, or create a new document and set the syntax to latex.
2. Place the cursor on any line that has an `\item` in it, and press enter.

### Actual behavior

The `\item` goes away.

### Additional Information

Previous versions don't seem to have this issue. Also, the syntax has to be specifically set to latex.

**Comment by tecosaur** [comment]
This is not a bug, it's an intended feature.
> When the current line starts with \item or \item[], hitting Enter automatically adds a newline starting in the same way. For a better handling of the last item, hitting Enter on a line only containing \item or \item[] actually deletes the content of the line. The alt+Enter is bind to the standard newline command. This automatic insertion of \item can be deactivated by setting latex-workshop.bind.enter.key to false.

If you want a blank  `\item` try doing <kbd>shift</kbd>+<kbd>enter</kbd>

**Comment by lukedan** [comment]
Well that seems a bit counterintuitive, isn't it? My habit is to write each `\item` on its own line, so this is really giving me a lot of trouble. I really hope that you can consider changing the interaction scheme.

**Comment by jlelong** [comment]
It deletes the line if it only contains `\item` or `\item[...]` and nothing else. This feature is very well suited for writing each `\item` on its own line.

**Comment by jlelong** [comment]
This is not the way the feature has been designed and it cannot work with such a layout. 

> When the current line starts with `\item` or `\item[]`, hitting Enter automatically adds a newline starting in the same way.

Just set `latex-workshop.bind.enter.key` to `False`  to restore the old behaviour.

**Comment by lukedan** [comment]
Thanks, I almost forgot that this is a feature that can be turned off.
