### ISSUE TITLE
Some snippet bugs

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#883]
### Description

Some snippet like `**` will not work completely even I press `Tab` afterward.
Some snippet like `@6` work if I press `Tab` but no suggestion window popped up.

Sorry didn't have time to test all the snippets.

### Additional Information

System: MacOS 10.14
VSCode and LaTeXworkshop: latest

**Comment by tecosaur** [comment]
I forget the precise details but this is a _vs code_ issue, I believe it's to do with having special characters in snippets.

**Comment by ShuCaiMonkaS** [comment]
> I forget the precise details but this is a _vs code_ issue, I believe it's to do with having special characters in snippets.

Could it be because some snippet has special meaning to the editor?
`@/` and `@(` seems similar but the former one doesn't work.

Also,  all snippets work if import from `Command+Shift+P` "Show All Command" window.

**Comment by tecosaur** [comment]
This may help you, I know at one point I experienced the same issue. I looked at my `settings.json` and one of these might help you:
```json
    "editor.snippetSuggestions": "top",
    "editor.suggestSelection": "recentlyUsedByPrefix",
    "editor.tabCompletion": "onlySnippets",
    "editor.quickSuggestionsDelay": 0,
```

**Comment by jlelong** [comment]
Please check the closed issues labelled with *snippets*.

**Comment by ShuCaiMonkaS** [comment]
> Please check the closed issues labeled with _snippets_.

I've checked those issues, but none of them seems to work this time.
I believe it's not autocompletion's problem.

**Comment by ShuCaiMonkaS** [comment]
> Please check the closed issues labeled with _snippets_.

I've checked the setting.

Here is the solution, if the `editor.snippetSuggestions` is set to `onlySnippets`, `Tab` will work.
The default `on` option won't work.

But still, no suggestion window pops, it still might be a bug.

**Comment by jlelong** [comment]
There is no suggestion window popup for `**` but it should work for all the others. Do you confirm?

**Comment by ShuCaiMonkaS** [comment]
> There is no suggestion window popup for `**` but it should work for all the others. Do you confirm?

Not all others works, `**` is just an example, like `@/` doesn't have popup either.
Sorry, I don't have a full list of what doesn't have popup windows.

**Comment by jlelong** [comment]
Except `**`, all the other snippets work on my installation. Note that snippets do not work on lines longer than 100 characters if cursor is nat at the end of line because of a bug in vscode.

**Comment by ShuCaiMonkaS** [comment]
> Except `**`, all the other snippets work on my installation. Note that snippets do not work on lines longer than 100 characters if cursor is nat at the end of line because of a bug in vscode.

That's interesting, did you also set to `onlySnippets`?
Also, I believe this is independent to 100 characters bug.

**Comment by jlelong** [comment]
I have `"editor.snippetSuggestions": "inline"`.

**Comment by jlelong** [comment]
Everything should be properly fixed now. To have intellisense automatically triggered inside snippets, set "editor.suggest.snippetsPreventQuickSuggestions": false.
