### ISSUE TITLE
Will there be Touchbar support in the furture?

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#884]
Found touchbar very useful. 
If the user can define their own touchbar (while with latex extension), it could be very helpful to put some common snippets on there, right now it's kind of empty there.

Thanks.

**Comment by James-Yu** [comment]
Not likely. I am not aware of touchbar API by vscode, nor do I have a mac for testing unfortunately. I will be glad to reopen the issue if the community would contribute codes.
