### ISSUE TITLE
`--max-print-line` breaks the lualatex build

### ISSUE THREAD

**Issue by chantisnake** [James-Yu/LaTeX-Workshop#885]
### Description

in this commit: https://github.com/James-Yu/LaTeX-Workshop/commit/8666a5b079a5e70c2c94eb176dea9fa26ed50f9c the option `--max-print-line` is added to the build system.
However `--max-print-line` is not recognized by `lualatex` when building with `latexmk`.
Please add an option to turn `--max-print-line` off.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

```text
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'lualatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'main.tex'
------------
Run number 1 of rule 'lualatex'
------------
------------
Running 'lualatex  --max-print-line=10000 -synctex=1 -interaction=nonstopmode -file-line-error -recorder -aux-directory="./aux_file/"  "main.tex"'
------------
Latexmk: applying rule 'lualatex'...
lualatex: unrecognized option '--max-print-line=10000'
Latexmk: fls file doesn't appear to have been made
Latexmk: Log file says output to 'main.pdf'
Collected error summary (may duplicate other messages):
  lualatex: Command for 'lualatex' gave return code 1
      Refer to 'aux_file/main.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
=== TeX engine is 'LuaTeX'
Latexmk: Errors, so I did not complete making targets
```

</details>

### Additional Information

<details>
<summary>Related Config File</summary>

```json
// Latex
  // setup the build tool
  "latex-workshop.latex.recipes": [
    {
      "name": "toolchain",
      "tools": [
        "Step 1: latexmk"
      ]
    }
  ],
  "latex-workshop.latex.tools": [
    {
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-lualatex",
        "-auxdir=./aux_file/",
        "main.tex"
      ],
      "name": "Step 1: latexmk"
    }
  ],
```

</detail>

**Comment by jlelong** [comment]
The `--max-print-line=10000` option is not recognized by lualatex but is not harmful. From your log, it looks like you have an other issue with your file. Are you sure your file compiles with no error with the `--max-print-line` option?

**Comment by chantisnake** [comment]
@jlelong I am sure. Lualatex stops when it see unrecognized command.

here is a test:
```
 zcsxo@DESKTOP-IBLF1KD  ~\OneDrive\surface-Document\course-work\homework\crypto\HW5                                   [11:30:20 AM] ❯ lualatex --max-print-line=10000 main.pdf
lualatex: unrecognized option '--max-print-line=10000'

 zcsxo@DESKTOP-IBLF1KD  ~\OneDrive\surface-Document\course-work\homework\crypto\HW5                                   [11:30:34 AM] ❯ $LASTEXITCODE
1
```

**Comment by jlelong** [comment]
Strange, because on Mac `lualatex` simply ignores the unknown option. I will this soon.

> Is it possible to control the indentation of the autocomplete feature or even turn it off?

We have no choice. The problem pane expects untruncated log lines for LaTeX and MikTeX does not recognize the related environment variable, see #852.
