### ISSUE TITLE
autocompletion with \ref

### ISSUE THREAD

**Issue by dslemusp** [James-Yu/LaTeX-Workshop#888]
### Description

Hi

I have notice that the autocompletion using the environment \ref or \cref does not check whether part of the string is already written if a dot or colon separator is used, appending the whole string next to the already written one. This only happens if you lose focus of the label and then try to autocomplete.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

```latex
\documentclass{report}     
\usepackage{cleveref}

\begin{document}
    ROOT TEXT \cref{fig:exam}
    
    \begin{figure}[ht!]
        \centering
        \caption{Caption}
        \label{fig:example}
    \end{figure}

\end{document}
```

Using the code above
1. try \ref{fig:exam
2. focus cursor somewhere else
3. refocus on \ref{fig:exam
4. append an extra character to trigger autocompletion menu \ref{fig:examp
5. select and hit enter
6. Result \ref{fig:fig:example}

### Expected behavior

Autocompletion should show the right label. For this example \ref{fig:example}

### Actual behavior

It appends the whole label after the dot or colon separator \ref{fig:fig:example}

**Comment by James-Yu** [comment]
It's a well known bug of vscode. You may find multiple past issues complaining about it. We cannot do anything from the extension side.
