### ISSUE TITLE
Double cursor after environment autocomplete

### ISSUE THREAD

**Issue by mmlanger** [James-Yu/LaTeX-Workshop#896]
### Description

(Thanks for giving this awesome extension to us!)
An annoyance in the autocompletition can be quite frustrating, generating \begin{...}...\end{...} code introduces a double cursor which has to be explicitly removed.

### Log messages

I think the logs are uncorrelated.

### How to reproduce

1. Open arbitrary .tex file in a LaTeX project
2. Begin typing \begin, choose an environment and press Enter to use the autocomplete feature
3. Press down arrow and begin typing in the environment, e.g. in equation

Pictures may say more than a 1000 words: 
![begin_double_cursor](https://user-images.githubusercontent.com/14871538/47099360-6ab2c300-d235-11e8-8d8a-844bcf6cf26f.gif)

### Expected behavior

A better experience would for example be that after pressing Enter the double cursor is automatically removed, such that one can just press the Down Arrow and start typing.

### Actual behavior

You actually have to press Esc twice to remove the double cursor and to be able to continue typing in the environment. 

### Additional Information

Tell me if you need anything further.

**Comment by jlelong** [comment]
Thus `\begin{..}...\end{...}` snippet has two placeholders: the first one for the environment name and the second one for the body of the environment. You can use `TAB` to move from the multi-cursor position in the environment name to the body position. 

This is the standard behavior of snippets in VSCode
