### ISSUE TITLE
\item in itemize gets deleted pressing Enter

### ISSUE THREAD

**Issue by mmlanger** [James-Yu/LaTeX-Workshop#897]
### Description

Using the itemize environment and beginning a new line to type content reliably deletes the \item.

### Log messages

I think the logs are uncorrelated.

### How to reproduce

1. Open arbitrary .tex file in a LaTeX project
2. Generate an itemize environment
3. just press Enter after \item

![itemize_issue](https://user-images.githubusercontent.com/14871538/47101047-4b1d9980-d239-11e8-99e1-a86fae7bf6ca.gif)

### Expected behavior

Typing Enter after \item just creates a new line under \item

### Actual behavior

\item gets deleted.
Retyping \item, pressing Esc to turn off the autocomplete suggenstions and pressing Enter again will just delete it again.

### Additional Information

An additional annoyance is also that typing \item after that unwanted delete and pressing Enter just 
autocompletes to a new itemize environment.

Additional question:
Is it possible to control the indentation of the autocomplete feature or even turn it off?
The indentation is quite aggressive and space wasting sometimes, e.g. aligned in equation in itemize.

**Comment by jlelong** [comment]
From the README file

> When the current line starts with `\item` or `\item[]`, hitting `Enter` automatically adds a newline starting in the same way. For a better handling of the last item, hitting `Enter` on a line only containing `\item` or `\item[]` actually deletes the content of the line. The `alt+Enter` shortcut is bind to the standard newline command. This automatic insertion of `\item` can be deactivated by setting` latex-workshop.bind.enter.key` to `false`.

> Is it possible to control the indentation of the autocomplete feature or even turn it off?

I don't think so.
