### ISSUE TITLE
SyncTeX and LaTeX compiler not found if Visual Studio Code is started from macOS dock

### ISSUE THREAD

**Issue by jpcofr** [James-Yu/LaTeX-Workshop#9]
Hi!

SyncTeX and LaTeX compiler not found if Visual Studio Code is started from macOS dock.

Great extension BTW!

**Comment by James-Yu** [comment]
The extension uses [hasbin](https://github.com/springernature/hasbin) package to determine whether the required binaries are installed. As I currently do not have a mac on my side, I will disable this binary check step temporarily to make it work. Though I have no idea what causes the problem, will investigate later.

**Comment by James-Yu** [comment]
Will close this issue for now. Please check if it works.

**Comment by jpcofr** [comment]
Hmm I forgot to mention that the PDF's compilation was broken as well.

**Comment by James-Yu** [comment]
I need more information to help you. What is "broken"? Does it work well with other development environments? Does it work with terminal commands? What's you LaTeX installation and configuration? Everything is welcomed.

**Comment by jpcofr** [comment]
Broken means that the pdf is not being generated either on the preview window or by using the 'compile to pdf command'. 
The extension is compiling to PDF both on a windows system and on macos whenever code is opened from the terminal.
The LaTeX installation and configuration is an updated version (via `tlmgr update --all`) of the one that I got from homebrew (via `brew cask install mactex`).

The local extensions are:

```
bib - Version :0.3.0
Bookmarks - Version :0.10.2
code-gnu-global - Version :0.2.1
code-settings-sync - Version :2.4.3
cpptools - Version :0.10.0
csharp - Version :1.6.2
githistory - Version :0.1.5
haskelly - Version :0.4.10
html-snippets - Version :0.0.18
java - Version :0.0.9
latex-workshop - Version :0.2.11
markdown-shortcuts - Version :0.5.0
prettify-json - Version :0.0.3
python - Version :0.5.8
Theme-MarkdownKit - Version :0.1.1
vscode-clang - Version :0.2.1
vscode-instant-markdown - Version :1.0.0
vscode-markdownlint - Version :0.6.2
vscode-todo-highlight - Version :0.3.3
vscode-todo-parser - Version :1.8.6

```
Let me know if you need more info.

**Comment by James-Yu** [comment]
Thanks for the complete information. Previously when the extension cannot find the binaries, all related features are disabled: that is the reason why nothing happens after `preview` or `compile`.

I have just published a new version temporarily removing the mac os binary check. Please check the new version and see if problem persists.
