### ISSUE TITLE
chktex and other tools don't work on WSL.

### ISSUE THREAD

**Issue by kbumsik** [James-Yu/LaTeX-Workshop#904]
I tried to use LaTeX workshop with WSL, 

Thanks to #443, I could successfully build a .tex file. However, linter (chktex) and other tools still don't work.

To make things work, I tried the following settings:
```
"latex-workshop.chktex.path": "wsl chktex",
"latex-workshop.latexindent.path": "wsl latexindent",
"latex-workshop.synctex.path": "wsl synctex",
"latex-workshop.texcount.path": "wsl texcount"
```

I got the following log:
```
[14:42:34] Linter for active file started.
[14:42:34] Linter for active file running command wsl chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:42:34] Linter for active file failed to spawn command, encountering error: spawn wsl chktex ENOENT
[14:42:37] LaTeX log parsed with 0 messages.
```

I changed `wsl` to `C:\\Windows\\System32\\wsl.exe` but still doesn't work. Is there any other ways to make things work?

Thank you in advance!

**Comment by James-Yu** [comment]
It seems that you are using `wsl chktex` as command instead of `wsl`. Try move `chktex` to the first argument.

**Comment by lonelykid** [comment]
@kbumsik Hi, did you manage to make those commands work? I feel it requires the devs to enable this feature or at least allow us to modify args for those commands.

**Comment by tamuratak** [comment]
You can modify args. See 

- https://github.com/James-Yu/LaTeX-Workshop/wiki/Format
- https://github.com/James-Yu/LaTeX-Workshop/wiki/Linters

**Comment by lonelykid** [comment]
@tamuratak Thank you. It's not allowing us to modify all the args, for example, the file path. I need wrapper it in `wsl wslpath filepath` to make it work. Maybe I will write a .bat to wrapper those commands.

**Comment by kbumsik** [comment]
@lonelykid Hi, I actually made it worked before. Here is my settings:
```javascript
{
	"latex-workshop.showContextMenu": true,
	"latex-workshop.latex.clean.enabled": true,
	"latex-workshop.latex.tools": [
		{
			"command": "wsl",
			"args": [
				"make"
			],
			"name": "Step 1: latexmk"
		}
	],
	"latex-workshop.latex.recipes": [
		{
			"name": "toolchain",
			"tools": [
				"Step 1: latexmk"
			]
		}
	],
	"latex-workshop.chktex.enabled": true,
	"latex-workshop.chktex.path": "wsl",
	"latex-workshop.chktex.args.active": [
		"chktex",
		"-wall",
		"-n22",
		"-n30",
		"-e16",
		"-q"
	],
	"latex-workshop.chktex.args.root": [
		"chktex",
		"-wall",
		"-n22",
		"-n30",
		"-e16",
		"-q"
	],
	"latex-workshop.latexindent.path": "wsl",
	"latex-workshop.latexindent.args": [
		"latexindent",
		"-c",
		"%DIR%/",
		"%TMPFILE%",
		"-y=\"defaultIndent: '%INDENT%'\""
	],
	"latex-workshop.synctex.path": "synctex",
	"latex-workshop.texcount.path": "wsl",
	"latex-workshop.texcount.args": ["texcount"],
}
```

**Comment by lonelykid** [comment]
@kbumsik Thank you so much!

**Comment by tamuratak** [comment]
@kbumsik, I thank you too. I have added a [link](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#WSL-is-not-officially-supported) to your setting in FAQ.

**Comment by kbumsik** [comment]
@lonelykid Actually I didn't know about synctex very well. In which situation it is used? I will correct it if possible.
