### ISSUE TITLE
[Feature Request] Autocomplete searches across files

### ISSUE THREAD

**Issue by jeffsthicks** [James-Yu/LaTeX-Workshop#906]
When writing a document in Latex with multiple files, would it be possible for the autocomplete feature to search across all of the files in the project folder? Currently (although it is possible that I am working with this incorrectly) typing \ref{ will open an autocomplete menu which brings up the labels which were created in the open document. However, usually I am referencing a tag which may be in a different file but still a portion of the same document.

**Comment by James-Yu** [comment]
This can be done if the extension can find the correct root file, which should be the case. If it is not working for you, please upload a minimal working example for debug.
