### ISSUE TITLE
[Off Topic] Fork updating and PR help

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#907]
Hello,

I'm probably going to make a PR soon, so I thought I'd better update my fork. Did so via compare and merge. Issue is, before I make any changes my branch is apparently 'ahead' by 2 commits, and so I expect any PR I make will contain these — even though they're redundant.

![image](https://user-images.githubusercontent.com/20903656/47227734-21f63800-d3f6-11e8-97df-142e89e10037.png)

I feel sure there is a solution, I just don't know what it would be.

**Comment by James-Yu** [comment]
If developments are in `master`, this approach is fine. Typically forks will work on branches, and the `master` can always fastforward to the origin master head. Anyways, the additional commits are not too troublesome.
