### ISSUE TITLE
Docker on Windows compiling process stops with docker error

### ISSUE THREAD

**Issue by timmornYE** [James-Yu/LaTeX-Workshop#911]
### Description

When using LaTeX-Workshop with Docker on Windows the compiling process stops with a docker error. 

### Log messages

<details>
<summary>LaTeX Compiler Output</summary>

$ docker run -i --rm -w /data -v "c:\Users\user\tmp\Backbone:/data" tianon/latex latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf German-Backbone
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: /data.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

</details>

### How to reproduce

1. pull tianon/latex and mcandre/docker-chtex
2. Go to LaTeX-Workshop settings and activate Docker
3. Try to compile document

### Expected behavior

It should compile

### Actual behavior

Abort with error.

**Comment by James-Yu** [comment]
Not related to this extension. You are having trouble with docker.

**Comment by timmornYE** [comment]
I tested a little more and would say that it is related to this extension. If I change the path from 

```bash
docker run -i --rm -w /data -v "c:\Users\ststolz\tmp\Skills-Project\texSkills\German-Backbone:/data" tianon/latex latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf German-Backbone
```
to
```bash
docker run -i --rm -w /data -v "/c/Users/ststolz/tmp/Skills-Project/texSkills/German-Backbone:/data" tianon/latex latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf German-Backbone
```
it compiles as expected. 

Perhaps it has something todo with the fact that I am using Docker Toolbox in Windows? But at all I think that the path which works for me, should work for all installations. Because this is the original path of the docker-machine.

**Comment by James-Yu** [comment]
It's your docker who cannot accept windows-style path on a windows computer. I'm not aware of docker toolbox for win, though I suspect it was virtualbox-based and was out of support.

**Comment by timmornYE** [comment]
Yes, it is virtualbox-based, your are right. I think a lot of people will continue using it, because default docker installation uses Hyper-V, which results in the fact that other Hypervisors like Virtualbox are not working anymore. 

Would it be thinkable to introduce an option where I can set the path if it is not possible to use path like "/c/Users/..." which in my opinion would work in any case?
