### ISSUE TITLE
how to add custom snippets?

### ISSUE THREAD

**Issue by truefalsename** [James-Yu/LaTeX-Workshop#912]
Hi, 

I just started to use Visual Studio Code for my LaTeX writing. Is it possible to add custom snippets to LaTeX Workshop? For instance I would like to define a section snippet that pops out a \section{} command and a \label{sec:} command between two horizontal divisors.

Thanks for your help!

**Comment by jlelong** [comment]
The easiest way is to define snippets associated to the `LaTeX` filetype.
See [https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets)

**Comment by Lightbridge-KS** [comment]
These steps works for me

**LaTeX Snippet Example:**

1. Use command pallet: `Preference: Configure User Snippets` 
2. Select Language `LaTeX`
3. Edit your Snippets 
4. Use command pallet: `Preference: Open Settings (JSON)`
5. Then add these to `settings.json`

```json
"[latex]": {

"editor.quickSuggestions": {

"strings": true

}

}
```
