### ISSUE TITLE
Invoking shell-escape flag

### ISSUE THREAD

**Issue by sbacelar** [James-Yu/LaTeX-Workshop#913]
How to invoke LaTeX with the `shell-escape` flag?

**Comment by jlelong** [comment]
Modify the recipe accordingly, see [here](https://github.com/James-Yu/LaTeX-Workshop#latex-recipe). If you want to keep using `latexmk`, have a look at `latexmk`'s manual: the `--shell-escape` option can only be added  as an option to `-[pdf]latex`. From the `latexmk` manual

> ```
> latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S"  foo.tex
> ```

**Comment by janosh** [comment]
@jlelong The link to the readme section is broken. [Here's the new one](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes).
