### ISSUE TITLE
Support packages in hover preview

### ISSUE THREAD

**Issue by Addie2595** [James-Yu/LaTeX-Workshop#914]
Is it possible to support packages in hover preview? I often use \si and \SI from siunitx package and the preview doesn't like it. It's not a huge problem, for example $\SI{350}{\volt}$ turns into \SI350\volt, but it would be nice to have a faithful preview. Thanks. (Related to #875)

**Comment by ShuCaiMonkaS** [comment]
To be honest, offline hover preview already shocked me.

**Comment by ShuCaiMonkaS** [comment]
Also, just borrow this post. It would be good to have a keyboard shortcut to preview cause hover is kind of slow.

**Comment by ShuCaiMonkaS** [comment]
> Is it possible to support packages in hover preview? I often use \si and \SI from siunitx package and the preview doesn't like it. It's not a huge problem, for example $\SI{350}{\volt}$ turns into \SI350\volt, but it would be nice to have a faithful preview. Thanks. (Related to #875)

I have some self-defined command, it will not work either.

**Comment by tamuratak** [comment]
You can use a command `editor.action.showHover` by defining the shortcut of the command in `keybindings.json`. Related to Microsoft/vscode/issues/32088.

> Also, just borrow this post. It would be good to have a keyboard shortcut to preview cause hover is kind of slow.

**Comment by tamuratak** [comment]
Generally, it is difficult to support packages. As for siunitx, there is a third party extension for MathJax. However, I am not sure how much the extension is mature and well maintained.

> Is it possible to support packages in hover preview? I often use \si and \SI from siunitx package and the preview doesn't like it. It's not a huge problem, for example $\SI{350}{\volt}$ turns into \SI350\volt, but it would be nice to have a faithful preview. Thanks. (Related to #875)

**Comment by James-Yu** [comment]
https://stackoverflow.com/questions/21192606/can-i-add-latex-packages-to-mathjax
