### ISSUE TITLE
[Feature Request] Follow recursive root directives

### ISSUE THREAD

**Issue by rbost** [James-Yu/LaTeX-Workshop#919]
### Description

It would be very nice to support multiple levels of `%! TEX root` directives. By that I mean that if you have file2.tex that points to file1.tex, which itself points to root.tex, asking for a typeset of file2.tex should use root.tex as the argument of the recipe, not file1.tex as it is done today.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>
`LaTeX Error: Missing \begin{document}.` when compiling file2.tex
</details>

### How to reproduce

1. Create a projet with three files, root.tex, file1.tex, file2.tex, with root.tex being a legitimate LaTeX document, importing/including file1.tex, and file1.tex importing/including file2.tex (or use this demo project [rec_tex_root.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2517917/rec_tex_root.zip))
2. Typeset (by saving or building with a recipe) file2.tex
3. Notice the error

### Expected behavior

No compilation error when compiling file2.tex.
Typesetting file2 should indeed typeset root.tex.

### Actual behavior

LaTeX-Workshop tries to typeset file1.tex which is not a valid LaTeX document.

**Comment by James-Yu** [comment]
Then why it does not point to root directly?
