### ISSUE TITLE
Proposal - move latex workshop actions to top level actions?

### ISSUE THREAD

**Issue by jabooth** [James-Yu/LaTeX-Workshop#92]
Right now the only commands latex workshop adds to vscode's global set of commands seems to be 

<img width="630" alt="screenshot 2017-04-06 10 08 26" src="https://cloud.githubusercontent.com/assets/1312873/24746439/0867d772-1ab1-11e7-8247-2e38a100bab6.png">

I think here we should provide all commands we currently expose under `LaTeX Workshop Actions`

<img width="641" alt="screenshot 2017-04-06 10 09 19" src="https://cloud.githubusercontent.com/assets/1312873/24746474/252cf662-1ab1-11e7-8a85-80f9fa118812.png">

Perhaps with a a common `LaTeX Workshop: ` prefix - that way users typing `latex` into the top level can execute any command we expose in one click rather than two.

BTW, I still like the idea of the `LaTeX Workshop Actions` menu being accessable through right click as this is great for discoverability! But I think the 'vscode' way of doing this is to encourage users to try `cmd`/`ctrl` + `shift` + `p` and then typing any command directly.

**Comment by jabooth** [comment]
Sorry @James-Yu I've updated the body of the issue now haha!

**Comment by James-Yu** [comment]
Easy job!
