### ISSUE TITLE
VerbatimOut not recognized as a verbatim environment

### ISSUE THREAD

**Issue by torn4dom4n** [James-Yu/LaTeX-Workshop#922]
### Description

`$` within minted code blocks breaks highlighting.

### How to reproduce

1.  Open VSCode.
2.  Copy this text: https://raw.githubusercontent.com/7mind/slides/master/01-logstage/logstage.tex.
3.  Select `latex` grammar.

### Expected behavior

```latex
\begin{VerbatimOut}{ex-scala-logging.tmp}
class Example 
  extends LazyLogging { // Let's break SOLID!
  //...

  // Renders as "Received message from JohnDoe"
  // Structure lost
  logger.trace(s"Received message from $user")
}
\end{VerbatimOut}

\begin{VerbatimOut}{ex-scala-tree-source.tmp}
val user = "JohnDoe"
logger.debug(s"Received a message from $user")
\end{VerbatimOut}
```

### Actual behavior

![image](https://user-images.githubusercontent.com/27698189/47577918-43b16b00-d972-11e8-9bfe-58a24949c384.png)

### Additional Information

Issue from https://github.com/ProAdd-ons/vscode-LaTeX-support/issues/6

**Comment by jlelong** [comment]
This is because `VerbatimOut` is not recognized as a verbatim environment. On it.

**Comment by torn4dom4n** [comment]
@jlelong, I need to fix this error. Thanks!
![image](https://user-images.githubusercontent.com/27698189/55245849-96bb8100-5276-11e9-8d75-b37a71f36380.png)

**Comment by torn4dom4n** [comment]
Can you reopen this issue?

**Comment by jlelong** [comment]
I have just fixed it. Each environment requires a specific declaration...
