### ISSUE TITLE
PR  #928 must not be merged. 

### ISSUE THREAD

**Issue by tamuratak** [James-Yu/LaTeX-Workshop#930]
@James-Yu. I think PR #928 must not be merged. This PR deletes files too aggressively. Subdirectories do not necessarily contain TeX-related files only.  For example, it also deletes files with the suffix `.log`  in subdirectories.  When someone has data files with the suffix `.log` in a subdirectory to write a paper, the result will be disastrous.

**Comment by James-Yu** [comment]
Hmm fair enough. Will revert it.

**Comment by tamuratak** [comment]
Thank you for your quick response.
