### ISSUE TITLE
Update built in pdf viewer to version v2.0.943

### ISSUE THREAD

**Issue by zoehneto** [James-Yu/LaTeX-Workshop#932]
Version [v2.0.943](https://github.com/mozilla/pdf.js/releases) of pdf.js introduces new options to view two pages of a pdf side-by-side (see [demo](https://mozilla.github.io/pdf.js/web/viewer.html)):

![new-options](https://user-images.githubusercontent.com/8282547/47707374-efd1ab00-dc2b-11e8-99ff-9e114206cecd.png)

This is very helpful for large documents (especially those that will be printed in the end). Would it be possible to update the viewer to this version?

**Comment by James-Yu** [comment]
Unfortunately, this might not be quite possible since we have made too many untrackable changes to the viewer.js, which only works with pdf.js < 2.0. Any community contribution is greatly welcomed.

**Comment by tamuratak** [comment]
I made a PR #935. Please test it.

**Comment by zoehneto** [comment]
@tamuratak Thank you for this, it works very well. Just one small improvement: The outline in the sidebar is very hard to read (in left to right documents), because for some reason part of the latex workshop style is only applied if the text direction is right to left:

```
html[dir='rtl'] #outerContainer.sidebarOpen > #mainContainer {
    background-color: #404040;
    background-image: url(images/texture.png);
}

html[dir='rtl'] #sidebarContent {
    top: 0;
}
```

modifying this to (dropping the second rule, since it causes problems in the sidebar)

```
html #outerContainer.sidebarOpen > #mainContainer {
    background-color: #404040;
    background-image: url(images/texture.png);
}
```

solves this issue.

**Comment by James-Yu** [comment]
You may test the latest commit in `master` for the updated behavior. Please leave any findings here for further adjustments.

**Comment by zoehneto** [comment]
The latest commit fixes this css issue. Another issue I just noticed is, that the new options (spread, scrolling type etc.) aren't maintained during a refresh. This means, that one has to change the options whenever the document is changed.
