### ISSUE TITLE
Reverse Synctex dosen't work when directory contains Chinese characters

### ISSUE THREAD

**Issue by xlf605401969** [James-Yu/LaTeX-Workshop#936]
### Description

When directory name only contains ASCII characters, both direct and reverse synctex works fine. But when directory name contains Chinese characters, reverse synctex (from pdf to .tex) stops work wihle direct synctex still works.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

Direct synctex logs (works fine)
[10:24:13] SYNCTEX command invoked.
[10:24:13] Found root file from active editor: c:\测试\test.tex
[10:24:13] Root file remains unchanged from: c:\测试\test.tex.
[10:24:13] Executing synctex with args view,-i,47:18:c:\测试\test.tex,-o,c:\测试\test.pdf
[10:24:13] Try to synctex c:\测试\test.pdf

Reverse synctex logs (does not work)
[10:25:42] Executing synctex with args edit,-o,1:62.42128603104212:537.3392392177541:c:\测试\test.pdf
[10:25:43] SyncTeX to file c:\����\test.tex
</details>

<details>
<summary>Developer Tools Console</summary>

Reverse synctex logs (does not work)
There is one error in the console., It seems that it is caused by encoding?

 ERR cannot open file:///c%3A/%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD/test.tex. Detail: 找不到文件(file:///c:/����/test.tex): Error: cannot open file:///c%3A/%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD/test.tex. Detail: 找不到文件(file:///c:/����/test.tex)
</details>

### How to reproduce

1. Put a .tex file under a directory with Chinese characters.
2. Build the .tex file.
3. Try reverse synctex from the pdf.

### Additional Information
Latex Version: TexLive 2017
System Version: Win10 x64 Home 1803
Windows Display Language: Simplified Chinese [中文(中华人民共和国)]

**Comment by James-Yu** [comment]
It's a bug related to synctex. We cannot fix it from our side.

**Comment by xlf605401969** [comment]
>           It's a bug related to synctex. We cannot fix it from our side.

Thanks for you reply. But I think synctex.exe works fine with Chinese characters. There are some tests. The terminal encoding is set to windows defaut (GB2313) here.
```
PS C:\测试> C:\texlive\2017\bin\win32\synctex.exe edit -o 1:83.97505197505198:62.94386694386699:c:\测试\test.pdf
This is SyncTeX command line utility, version 1.3
SyncTeX result begin
Output:c:\测试\test.pdf
Input:c:/测试/test.tex
Line:30
Column:-1
Offset:0
Context:
SyncTeX result end
```
If I change the encoding of the terminal to UTF8, it still returns right results but the input and output row seems corrupted, which does not give the right path of the files. It seems that synctex.exe uses system's default encoding in output.
```
Active code page: 65001
PS C:\测试> C:\texlive\2017\bin\win32\synctex.exe edit -o 1:83.97505197505198:62.94386694386699:c:\测试\test.pdf
This is SyncTeX command line utility, version 1.3
SyncTeX result begin
Output:c:\\test.pdf
Input:c://test.tex
Line:30
Column:-1
Offset:0
Context:
SyncTeX result end
```

The return of synctex.exe is decoded assuming utf8 in locater.ts
```
proc.stdout.setEncoding('utf8')
proc.stderr.setEncoding('utf8')
```
In direct synctex, it does not use the file path in the return of synctex.exe. However, in reverse synctex, path in the result of synctex.exe is used. (in function locate(data: any, pdfPath: string))
`let filePath = path.resolve((record.input as string).replace(/(\r\n|\n|\r)/gm, ''))`
Is it possible the reason of the bug?
I will apricate it if you can expend some time on this problem and fix it.

**Comment by xlf605401969** [comment]
I’m not a node.js developer. It seems that there is not a simple method to get the system’s default encoding in windows. Sorry for bothering.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: James Yu <notifications@github.com>
发送时间: Monday, November 5, 2018 10:27:21 AM
收件人: James-Yu/LaTeX-Workshop
抄送: xlf605401969; Author
主题: Re: [James-Yu/LaTeX-Workshop] Reverse Synctex dosen't work when directory contains Chinese characters (#936)


You have got the problem: it's the encoding. However, how can the extension guess what encoding the output is without explicit instructions? It is not a good solution to adopt other schemes instead of utf8, as users are far beyond CJK. Alternatives are welcomed.

―

**Comment by xlf605401969** [comment]
Is it possible to let the user select the encoding in the settings of the extension?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: James Yu <notifications@github.com>
发送时间: Monday, November 5, 2018 10:27:21 AM
收件人: James-Yu/LaTeX-Workshop
抄送: xlf605401969; Author
主题: Re: [James-Yu/LaTeX-Workshop] Reverse Synctex dosen't work when directory contains Chinese characters (#936)


You have got the problem: it's the encoding. However, how can the extension guess what encoding the output is without explicit instructions? It is not a good solution to adopt other schemes instead of utf8, as users are far beyond CJK. Alternatives are welcomed.

―
