### ISSUE TITLE
\end{minipage} does not close brace

### ISSUE THREAD

**Issue by jotagah** [James-Yu/LaTeX-Workshop#940]
### Description

When using the minipage environment the open "\begin{minipage}" autocompletion is ok, but then the \end{minipage} autocompletion does not closes the brace and gives "\end{minipage" which will generate a lot of errors.

### Log messages

There is no log message to this issue

### How to reproduce

1. start to type "\end{mini"
2. choose the minipage option on suspended menu
3. we got "\end{minipage" without the close brace

### Expected behavior

\end{minipage}

### Actual behavior

\end{minipage

**Comment by jlelong** [comment]
There is no specific auto-completion for `\end`, as there is only one acceptable environment name for closing. So, it is not surprising that no `}` is automatically added at the end.
You can use _LaTeX Workshop: Close current environment_ from the Command Palette to automatically close the current environment.

**Comment by jotagah** [comment]
Thank you and sorry the noise.
