### ISSUE TITLE
[Feature Request] Enhancement about math preview

### ISSUE THREAD

**Issue by Chlorie** [James-Yu/LaTeX-Workshop#943]
1. A weird symbol is shown when the caret is inside of the math code being previewed, I don't know if this is expected behavior.
2. Maybe add support for displayed math in `$$ ... $$`? Currently it makes the preview buggy. (Though `\[ ... \]` is preferred in this case.)
3. Is there any chance to support math previewing for user defined macros?
4. Is it possible to support previewing in math environments, like `align(*)`?
Thanks for your great VSCode extension!

**Comment by Chlorie** [comment]
1. Got it, thanks.
2. When displayed math is in `$$ ... $$` format, it is recognized as inline math from the first dollar sign to the third, which excludes the fourth dollar sign (where in some cases the fourth dollar sign is wrongly recognized as the start symbol of another inline math environment), plus the second dollar sign is shown in the preview. See screenshot below.
![image](https://user-images.githubusercontent.com/34185634/48003886-b2e54700-e14a-11e8-91b8-47c7434f2eef.png)
3. Sorry, I got the false impression of that the preview is activated when mouse is hovering on any part of the math environment instead of just the starting sign, since inline math does that... It works fine when the mouse cursor hovers over the `\begin` part. Thanks.

**Comment by tamuratak** [comment]
`$$ ... $$` is not supported. So, a preview like this is a bug we won't fix.

**Comment by Chlorie** [comment]
Got it! Sorry for wasting your time...

**Comment by tamuratak** [comment]
Never mind. I hope you enjoy using this feature.
