### ISSUE TITLE
Configure or disable auto-indent feature

### ISSUE THREAD

**Issue by spacemarshal** [James-Yu/LaTeX-Workshop#945]
Disable the auto-indent after `\documentclass{}` and `\begin{document}`. There is no advantage in readability and document structure. It only provides unnecessary and unwanted white space because it reduces the usable line length. In my opinion it is a poor choice of default behavior.

Please provide a way to configure the auto-indent feature or provide a switch to disable auto-indent completely.

**Comment by James-Yu** [comment]
Can you confirm that `\begin{document}` indents?
