### ISSUE TITLE
Unintuitive Behavior: Surround Selected Text with Command Even When Text is Deleted

### ISSUE THREAD

**Issue by junyuan-chen** [James-Yu/LaTeX-Workshop#948]
### Description
"When `\` is typed with text selected, surround the selection with LaTeX command."
If the above setting is enabled, then even if the user intends to delete the text first by selecting and start to write unrelated new command, the text that previously selected for deletion will be surrounded by the new command.

I find this behavior to be unintuitive and could be interrupting when the true intent is deleting the text.

### How to reproduce
1.  Enable "When `\` is typed with text selected, surround the selection with LaTeX command."
2. Type some random text
3. Select these text
4. Delete the selected text and then press `\`
5. The deleted text is surrounded by command

### Expected behavior

Start an unrelated new command without using the deleted text as argument

### Actual behavior

Deleted text is surrounded by command which is unintuitive and takes extra time to remove them

**Comment by jlelong** [comment]
The use of `\` to surround selected text is deprecated, use <kbd>ctrl</kbd>+<kbd>l</kbd>, <kbd>ctrl</kbd>+<kbd>w</kbd>.
See [README.md](https://github.com/James-Yu/LaTeX-Workshop/blob/master/README.md) and look up _Surround_.
