### ISSUE TITLE
The return action (Enter) is very slow because of this package

### ISSUE THREAD

**Issue by sloth3toe** [James-Yu/LaTeX-Workshop#950]
I've been working on a long document, and I've noticed that VSCode is very very slow to respond upon hitting Enter. I'm working on a 2015 Macbook Pro with decent configurations.

The only way for me to improve the speed is to disable LaTeX Workshop, pointing to this extension as the problem, but that's unfortunate because I'm working on a TeX document!

My best guess is that it's the return of the feature of adding \item upon hitting Enter, which affects the speed even when one is outside of an itemize environment. I do not remember this to be such a big problem before, hence this is a guess. I do not see any way to disable this feature to test whether that will improve the speed. If it is indeed the cause, please add such a feature in a way that hitting Enter does not trigger any other resources.

**Comment by tamuratak** [comment]
We can summarize #903 that disabling other extensions except for LaTeX Workshop solves this problem. Please disable Spell Right,  Brackets Pair Colouriser 2, and Prettify Symbols Mode especially.
