### ISSUE TITLE
Version 5.15.0 removes folding in *.tex files

### ISSUE THREAD

**Issue by DrRuhe** [James-Yu/LaTeX-Workshop#953]
### Description

Since the Update to version 5.15.0 of Latex Workshop the code folding dissappeared in .tex files.

### Log messages

Although i doubt that the Logs will give any meaningful info about the Issue here they are:

I replaced all paths in the log with this text: "PATH TO A FILE"
It was the same path all the time btw.

[15:34:28] Initializing LaTeX Workshop.
[15:34:28] Creating LaTeX Workshop http and websocket server.
[15:34:28] LaTeX Workshop initialized.
[15:34:29] Server created on 127.0.0.1:58210
[15:34:29] LaTeX Workshop version: 5.15.0
[15:34:29] Snippet data loaded.
[15:34:29] LOG command invoked.
[15:34:29] Default data loaded.
[15:34:29] Try root file in root directory: PATH TO A FILE
[15:34:29] Parsing PATH TO A FILE
[15:34:29] Try root file in root directory: PATH TO A FILE
[15:34:29] Parsing PATH TO A FILE
[15:34:29] Try root file in root directory: PATH TO A FILE
[15:34:29] Parsing PATH TO A FILE
[15:34:29] Try root file in root directory: PATH TO A FILE
[15:34:29] Parsing PATH TO A FILE
[15:34:52] Found root file from active editor: PATH TO A FILE
[15:34:52] Root file changed from: undefined. Find all dependencies.
[15:34:52] Instatiating new file watcher for PATH TO A FILE
[15:34:52] Parsing PATH TO A FILE
[15:36:20] LOG command invoked.
[15:36:22] LOG command invoked.

Nothing Suspicoius in either the Developer Console nor the Ouput tab of VS Code
### How to reproduce

1. Update Latex Workshop to 5.15.0
2. 
3. 

### Expected behavior

Able to Fold Code

### Actual behavior

Folding icons are there for a brief moment after reloading VScode but then dissappear

### Additional Information

I did double check if folding was disabled in the settings.json but it was active

**Comment by DrRuhe** [comment]
I did some more testing and it seem as the extension only removes folding options where there is no direct latex function it could fold. Maybe adding an option in the settings to only show folding points where there is an actual latex function would help.

**Comment by James-Yu** [comment]
Can you please give an example on the part of a document which was originally and should be folded, but cannot in the current version?

**Comment by tecosaur** [comment]
Here's an example from me:

```
\makeatletter
    \newcounter{elimination@steps}
    \newcolumntype{R}[1]{>{\raggedleft\arraybackslash\( }p{#1}<{ \)}} % chktex 21
    \def\elimination@num@rights{}
    \def\elimination@num@variables{}
    \def\elimination@col@width{}
    \newenvironment{elimination}[4][0]
    {
        \setcounter{elimination@steps}{0}
        \def\elimination@num@rights{#1}
        \def\elimination@num@variables{#2}
        \def\elimination@col@width{#3}
        \renewcommand{\arraystretch}{#4}
        \start@align\@ne\st@rredtrue\m@ne % chktex 15 chktex 21
    }
    {
        \endalign
        \ignorespacesafterend
    }
    \newcommand{\eliminationstep}[2]
    {
        \ifnum\value{elimination@steps}>0\\\Rightarrow\quad\fi
        \left[
            \ifnum\elimination@num@rights>0
                \begin{array} % chktex 15
                {@{}*{\elimination@num@variables}{R{\elimination@col@width}}
                |@{}*{\elimination@num@rights}{R{\elimination@col@width}}}
            \else
                \begin{array}
                {@{}*{\elimination@num@variables}{R{\elimination@col@width}}}
            \fi
                #1
            \end{array}
        \right]
        & \quad
        \begin{array}{l}
            #2
        \end{array}
        \addtocounter{elimination@steps}{1}
    }
\makeatother
```

**Comment by James-Yu** [comment]
@neilsustc Any idea?

**Comment by zoehneto** [comment]
With PR #959 merged, the example from @tecosaur is now folded on line 25 and 29. There is currently no other folding, since only sections (including subsections etc.) and environments starting with `\begin` and ending with `\end` are supported by the new folding provider.

**Comment by neilsustc** [comment]
> only sections (including subsections etc.) and environments starting with `\begin` and ending with `\end` are supported by the new folding provider

That's right. The original indentation-based folding will be disabled if we provide our language-specific folding.
Actually, we can reimplement that in own folding provider but I didn't come up with a good solution.

A workaround is to set `editor.foldingStrategy` to `indentation` (before it is reimplemented)

**Comment by Amblizer** [comment]
> `foldingStrategy`

正常多了，感谢！

**Comment by DrRuhe** [comment]
So adding the Laguage folding results in vscode not using indentationfolding. Interesting... 
Is it possible to add an latex-workshop option to disable the laguage folding?

**Comment by James-Yu** [comment]
#984 #985
