### ISSUE TITLE
Browser PDF preview bug with beamer

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#954]
### Description

While compile a beamer file, the tile is not correctly displayed with browser preview.
VSCode tab preview works fine.

A minor issue but triggers OCD.

### How to reproduce
This is `test.tex` file

```
\documentclass{beamer}
\title{Test}
\begin{document}
\begin{frame}
	\titlepage
\end{frame}
\end{document}
```

### Expected behavior

Browser preview with the title `test.pdf`

### Actual behavior

Browser preview with the title `Test - test.pdf` where "Test" is the title.
If recompile it will become `Test - Test - test.pdf` so forth.

### Additional Information

Latest LaTeX-Workshop and VSCode

**Comment by tamuratak** [comment]
I cannot reproduce this issue. So please show us log messages and the exact versions of LaTeX-Workshop and VSCode. The word "Latest" is useless.

**Comment by ShuCaiMonkaS** [comment]
Quick reply, VSCode version Sep 2018(1.28),  Latex-Workshop ver5.14.1.
I will generate a more detailed report later.

**Comment by jlelong** [comment]
Can't reproduce either.
