### ISSUE TITLE
"Recursively found root file by magic comment" and no build  

### ISSUE THREAD

**Issue by alexmohr** [James-Yu/LaTeX-Workshop#956]
### Description
Since version 5.15.0 I am no longer able to build projects based on the following template.
https://github.com/schnes4/dhbw-heidenheim-latex-template. 

Issue can be reproduced on linux or windows.
Reinstalling the extension and even vscode did not resolve the issue.
After starting a new instance of vscode with the project the plugin uses a lot of cpu time and not even the git extension is loading properly anymore.

If the template is build using texstudio or the command prompt it builds sucessfully.

### Log messages
It takes a while until the log messages will be visible, probably because there are so many.

Developer Console:
` WARN Aborted onWillSaveTextDocument-event after 1750ms`

Latex Workshop Output: 
`[20:47:25] Recursively found root file by magic comment: /home/me/dev/tmp/main.tex
[20:47:25] Recursively found root file by magic comment: /home/me/dev/tmp/main.tex
[20:47:25] Recursively found root file by magic comment: /home/me/dev/tmp/main.tex
[20:47:25] Recursively found root file by magic comment: /home/me/dev/tmp/main.tex`
The output is repeated over and over a few hundred times a second.

Latex Compiler: 
`Ready`

### How to reproduce

1. Check out the project mentioned above
2. Open any tex file
3. Build the project 

### Expected behavior
Build should start and produce the pdf output.

### Actual behavior
Nothing happens, no error output and no build, except the log spamming.

### Additional Information
Does not seem to depend on operating system.
The template has worked before but suddenly stopped working with the newest version. 
Please let me know if you cannot reproduce the problem or need more logs

**Comment by alexmohr** [comment]
Probably duplicate of #953

**Comment by James-Yu** [comment]
This is because that the magic comment points to the file itself, which is a bug on the extension side. Please remove the line until a further fix is live on public release.
