### ISSUE TITLE
Synctex animation

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#958]
I am really sorry but I do not like the animation for synctex, is there a way to disable it ?

**Comment by tamuratak** [comment]
Which one? tex to pdf? pdf to tex?

**Comment by PierreMarchand20** [comment]
Oh sorry, pdf to tex (there is no animation from tex to pdf from what I see)

**Comment by stegmueller** [comment]
Same here. It is slow (and distracting).

**Comment by Astrantia** [comment]
@tamuratak Yeah it is very janky and looks like 10fps. Can you do the same using CSS and not a for loop javascript?

**Comment by tamuratak** [comment]
@Astrantia, please do it yourself.

**Comment by tecosaur** [comment]
Also very much not a fan. I'll probably take a look and rewrite it soon, I'm thinking smoother animation + whole line + small tweaks. However, I can't do anything till Tuesday.
