### ISSUE TITLE
Enter key does not work

### ISSUE THREAD

**Issue by thegoija** [James-Yu/LaTeX-Workshop#966]
### Description

Since the **5.15.0** version, the `Enter` button does not work. `Shift+Enter` does work. 
Happens on different 2 devices, one of them has a fresh install of VS Code with no other extension installed.

**Comment by tamuratak** [comment]
Please show us log messages and the versions of VS Code and OS.

**Comment by tamuratak** [comment]
Please see the side bar.

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

**Comment by James-Yu** [comment]
#956
