### ISSUE TITLE
Additional "\item" Added

### ISSUE THREAD

**Issue by TheFrozenDuck** [James-Yu/LaTeX-Workshop#971]
### Description
The addon for VS Code adds an ```\item``` everytime the enter key is pressed inside. Even if a curly bracket is used to create multiline text block.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Begin an enumerate/itemize block.
2. Insert a pair of curly brackets.
3. Press enter to make the curly brackets span multiple lines

### Expected behavior

The addon is not supposed to add an additional ```\item``` between the curly brackets of an existing ```\item```.
 
### Actual behavior
The addon adds an additional ```\item``` that needs to be deleted. 

### Additional Information

It looks  likes this
```latex
\begin{itemize}
    \item{
    \item}
\end{itemize}
```

**Comment by jlelong** [comment]
You can deactivate the `\item` addon by setting `latex-workshop.bind.enter.key` to `false`. Anyway, the `\item` addon has not been designed to work with multiline items.

Currently, hitting `enter` anywhere in a line starting with `\item` breaks the line at this position and inserts `\item`. I am wondering whether this mechanism should only be activated when at the end of a line. Any suggestion on that?

**Comment by tecosaur** [comment]
This may not be of any help, and I haven't checked how item-on-enter is implemented, but…

Would it be possible to:
 1. check the indentation of the parent `itemize` 
 2. wait for enter to happen
 3. if indentation = parent indentation + 1 add `\item `
 4. else do nothing

In my mind as long as the user isn't doing anything particularly weird indendation this should only add `\item`s when they will be direct children of the parent `itemize`.

**Comment by TheFrozenDuck** [comment]
Actually @jlelong's answer solved it for me. Disabling ```latex-workshop.bind.enter.key``` fixed it. I'll close this, but you can keep this open if you would like to discuss this further.
Cheers
