### ISSUE TITLE
autobuild is triggered on paste

### ISSUE THREAD

**Issue by faroit** [James-Yu/LaTeX-Workshop#973]
### Description

`autoBuild.onSave.enabled` allows run a build when a file is saved. However, it is also triggered when pasting text/code into the editor. This results in way too many rebuilds, consuming too much power.

### How to reproduce

1. set `"latex-workshop.latex.autoBuild.onSave.enabled": true`
2. paste text into latex document
3. observe build

### Expected behavior

do nothing

### Actual behavior

triggers rebuild

**Comment by Astrantia** [comment]
Probably not related to this extension.

**Comment by faroit** [comment]
@Astrantia that means you cannot reproduce this? I have no other extensions installed than LaTeX Workshop and `Atom Keymap`

**Comment by Astrantia** [comment]
That means that I think vscode auto-saves with your setting `"latex-workshop.latex.autoBuild.onSave.enabled": true` and this has nothing to do with latex workshop extension.

**Comment by tamuratak** [comment]
Please show us log messages and the versions of LaTeX Workshop and VSCode, and OS. Please disable `Atom Keymap` and restart VSCode. And check whether you still see this issue.

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48307813-8db46680-e598-11e8-9691-99a89f9cbf62.png)

**Comment by jlelong** [comment]
I was able to reproduce the problem by setting `editor.formatOnPaste` to `true`. 
Actually, the problem is that `latexindent` changes the file on disk, and `vscode` interprets it as a file save. I think we cannot do much about it on the extension side.
You should consider setting `editor.formatOnPaste` to `false` for LaTeX filetype.

**Comment by faroit** [comment]
That works. Thanks!
