### ISSUE TITLE
Experiencing hang while editing .tex file - VS Code Version 1.29.0

### ISSUE THREAD

**Issue by sgyzetrov** [James-Yu/LaTeX-Workshop#977]
### Description

Hi, I am experiencing hang. 

VS Code Version 1.29.0, macOS 10.13.6 (17G3025) LaTeX 5.15.3

Since I did not get the same issue in other VS Code windows running separately to the one editing .tex files, I can only assume the problem is in the plugin. But for the sake of precaution, I also left a comment in related VS Code project's issue.

### Log messages

Unfortunately, because the window was unresponsive, I cannot get the output or any CPU profiling in developer tool. And by the time VS Code reopened, all previous logs are gone. Also, during the hang, Code Helper spiked to 100%.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. It's really hard to describe, all I did was editing a very small .tex file and save it to see the LaTeX PDF file then re-edit and so on. And I guess the interval between editing and re-editing was kinda short?
2. 
3. 

### Expected behavior

Work smoothly like in previous VS Code versions.

### Actual behavior

Occasionally hang. Increasing...

### Additional Information
Does anyone else experience the same issue here? Plz left comments below so that I know I was not alone...

**Comment by sgyzetrov** [comment]
I have launched process explorer prior, now waiting for hang to reoccur, stand by.

**Comment by James-Yu** [comment]
When did you observe the issue? i.e., update to `5.13.3` or `vscode 1.29.0` or anything. Also please share your `tex`.

**Comment by sgyzetrov** [comment]
Exactly after I updated to 1.29.0 today. 
And, sorry for not sharing my working paper, I hope you understand. However, I will see if any other irrelevant .tex files experience the same hang and send them over, or should anything interesting happened in process explorer.

**Comment by James-Yu** [comment]
Unfortunately, I cannot reproduce the problem. It seems like a local one w.r.t. your project/config. You may work out a minimal working example and share.

**Comment by sgyzetrov** [comment]
Over at VS Code project, many are experiencing hang, now it looks more and more like a memory leak in 1.29.0 to me. Close for now.

**Comment by tamuratak** [comment]
Related to Microsoft/vscode/issues/62970.
