### ISSUE TITLE
Automatically open hover preview

### ISSUE THREAD

**Issue by Y0hy0h** [James-Yu/LaTeX-Workshop#978]
### Description
It would be really helpful to have the hover preview open automatically when the cursor enters an equation without using the mouse.

### Expected behavior
When inside an equation, the hover preview automatically opens and previews the equation currently being written.

### Actual behavior
Hover preview requires either interaction with the mouse or a command (`Show Hover`). Even though the command can be bound to a keyboard shortcut, the preview does not update when changes to the equation are made.

### Additional Information
This seems to be related to #602. However, that issue feels much broader. Here, I want to pitch a concise and concrete feature.

**Comment by James-Yu** [comment]
This is not possible given the current vscode api.
