### ISSUE TITLE
Disabling syntax highlighting in selected environments

### ISSUE THREAD

**Issue by omicronns** [James-Yu/LaTeX-Workshop#98]
Is there a way to disable syntax highlighting in environments, that contain non-LaTex code and so it looks broken? For example i use ```pycode``` environment, which contains python code, and all usages of ```%``` gets highlighted as LaTeX comment:

![latex_highlighting](https://cloud.githubusercontent.com/assets/6955179/24826987/d671db94-1c42-11e7-9464-ceed52621cad.png)

**Comment by James-Yu** [comment]
We use (and almost all language extensions of VS Code) Textmate syntax highlight solution. The LaTeX one is [here](https://github.com/textmate/latex.tmbundle). So this is an upstream problem.

Sorry I cannot help too much.
