### ISSUE TITLE
Problem with code folding

### ISSUE THREAD

**Issue by Saphrosit** [James-Yu/LaTeX-Workshop#980]
### Problem with code folding

Code folding does not work as expected in certain situations.

### Log messages

No log needed to reproduce the issue. 

### How to reproduce

I am attaching a minimal working example (GitHub did not let me upload the file in .tex extension).
[mwe.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2576243/mwe.txt)

### Expected behavior

All proof environments should be foldable.
Folding the first proof environment should result in the collapse of the lines 18-22.

### Actual behavior

Trying to fold the first proof environment results in the lines 18-43 to be collapsed. Also some proof environments are not foldable at all (third and fourth).

### Additional Information

VScode 1.29.0
LaTeX extension version 5.13.3
macOS 10.12.6

**Comment by James-Yu** [comment]
Please check #984 #985
