### ISSUE TITLE
Intellisense Does Not Behave as Expected

### ISSUE THREAD

**Issue by SophtwhereDev** [James-Yu/LaTeX-Workshop#989]
This is not a bug but simply that Intellisense doesn't function as I would've liked it to. I'm trying to migrate from TeXstudio so some of my issues are based on the differences between how TeXstudio handles things and how LaTeX-Workshop handles things, but some restrict workflow.

# Issue 1
The first thing being that when I start an environment I prefer typing as far as `\begin{enu` and then depend on intellisense and press enter and what I get is simply `\begin{enumerate}` although I expect:

```latex
\begin{enumerate}
    \item Cursor Here
\end{enumerate}
```

Or at least both the begin and end blocks. This is what I'm used to and prefer from TeXstudio. I realised that to get both begin and end I have to type just `\begin` and press enter which I find restrictive.

# Issue 2
Next, I realised that Intellisense doesn't provide any information on the arguments required by functions, and no awareness of functions that support multiple arguments. For example, Intellisense only contains `\includegraphics{}` while I would prefer a second option for `\includegraphics{size}{file}`.

# Issue 3
I believe a lot of packages don't seem to have Intellisense, I say a lot but I just tested the packages cancel and tabularx. I'm not sure if this is due to me doing something wrong or due to shortcomings of LaTeX-Workshop.

# Issue 4
I realised there's no Intellisense option for `\section*{}` and the lower levels of the same command.

**Comment by jlelong** [comment]
### Issue 1

Type BEN and `TAB` to complete, you will get exactly what you want. See [the snippets](https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/snippets-doc.md).

### Issue 3

Contributions are welcome!

### Issue 4

You probably mean snippets.

**Comment by SophtwhereDev** [comment]
## Issue 1
That's convenient but only works for the specific environments that already have snippets, it doesn't work if I want to create an empheq environment for example.

## Issue 3
It seems that TeXstudio handles auto-completion with .cwl files for packages, can't they be utilised by LaTeX-Workshop as well since they already exist? It's mentioned [here](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#CWLDESCRIPTION).

I believe this would solve my Issue 2 as well.

## Issue 4
What I mean is that if I type `\sec`, I get the option to auto-complete to `\section` but not `\section*`

**Comment by SophtwhereDev** [comment]
What I'm trying to say is that the .cwl files found [here](https://github.com/LaTeXing/LaTeX-cwl/blob/master/datetime.cwl) have all the information required for package completion, each file contains the commands and options for the package that it is named after.

**Comment by James-Yu** [comment]
The repo looks good. Will see how to integrate.

**Comment by tamuratak** [comment]
Files in LaTeX-cwl don't include information about arguments of commands. We should also see original files in the TeXstudio repository which includes information about arguments.

* https://github.com/texstudio-org/texstudio/tree/master/completion

**Comment by James-Yu** [comment]
#992
