### ISSUE TITLE
Feature request - braces/delimiter highlighting in math mode

### ISSUE THREAD

**Issue by zachjweiner** [James-Yu/LaTeX-Workshop#99]
VSC highlights begin and end braces for environments outside of math mode. Can this be extended to occur within `$...$` or `align` environments?

**Comment by James-Yu** [comment]
Can you please elaborate on what you expect and give a screenshot if possible?

**Comment by zachjweiner** [comment]
Here, the cursor is on the second brace, and so it highlights both braces.
![image](https://cloud.githubusercontent.com/assets/19390728/24834510/96f172de-1cad-11e7-85f9-b30a09656123.png)

Here, the cursor is again on the second brace, but no highlighting.
![image](https://cloud.githubusercontent.com/assets/19390728/24834516/c8220292-1cad-11e7-9f74-055432866254.png)

And also within the math environment:
![image](https://cloud.githubusercontent.com/assets/19390728/24834520/dae6930c-1cad-11e7-9614-248bc3b5a4cb.png)

**Comment by James-Yu** [comment]
I have double check the grammar setting and there's no problem from the extension side. Similar to #98 ,this is more a textmate/vscode upstream problem which disables brackets pairing in latex.math environments. Sorry it is not a problem that can be fixed from my side. I would recommend you submit an issue on vscode's repo.

**Comment by zachjweiner** [comment]
Thanks for looking!
