### ISSUE TITLE
Improve PDF Viewer on macOS

### ISSUE THREAD

**Issue by Saphrosit** [James-Yu/LaTeX-Workshop#993]
I am not sure whether this is something you can control from the extension, but would it be possible to make the pdf viewer "smoother"? 
It feels pretty "jerky" when I zoom in and out with the trackpad, while I would expect to have a much more fine-grained control on the zoom level (similarly to other pdf viewers). 

Also, it would be nice if you could add a "pinch to zoom" functionality, i.e. two-finger double tap results in automatic re-zoom of the pdf, so that the view is just slightly larger than the text width.

Sorry for not being very precise in the description, but I hope what I mean is clear.

**Comment by tamuratak** [comment]
Probably related to mozilla/pdf.js/issues/2582.

**Comment by James-Yu** [comment]
Exactly. Until upstream improvements cannot we do anything significant w.r.t. this issue.
