### ISSUE TITLE
Add syntax highlighting support for mintinline

### ISSUE THREAD

**Issue by gusbemacbe** [James-Yu/LaTeX-Workshop#995]
**Describe the bug**
I am using both mintinline and minted for code highlighting in XeLaTeX.

In this repository, it breaks the highlight when a dollar symbol is passed within the block

**To Reproduce**
With dollar symbol:
![image](https://user-images.githubusercontent.com/2257024/48673429-89ec8b00-eb28-11e8-91a8-8bbb29645ed6.png)

**Expected behavior**
Without dollar symbol:
![image](https://user-images.githubusercontent.com/2257024/48673444-a8eb1d00-eb28-11e8-932a-9a5869622f35.png)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - VS Code version: 1.30.0
 - Extension version: 5.16.0

**Additional context**
* I refer to the https://github.com/area/language-latex/issues/75 (read the first and last comment). You can fork his repository to improve the minted support. 
* Also simiar to the topic of this same repository: https://github.com/James-Yu/LaTeX-Workshop/issues/198

**Comment by James-Yu** [comment]
Package highlight not supported officially. PR welcomed.

**Comment by jlelong** [comment]
I will add syntax highlighting support for `\mintinline` in the coming days.

**Comment by gusbemacbe** [comment]
@jlelong , you forgot of including the $ to regex. 

For example, put `\mintline{php}{<?php echo "Hello $name, how are you?" ?>}`. As containing $, it still breaks the highlighting.

**Comment by jlelong** [comment]
The correct command is `mintinline` and not `mintline`.
If you try with `\mintinline{php}{<?php echo "Hello $name, how are you?" ?>}`, you will see that it works.

**Comment by gusbemacbe** [comment]
Then, I misspelled, but with the correct command, it still breaks too. Here is the screenshot:

![image](https://user-images.githubusercontent.com/2257024/48964982-2684b200-ef9b-11e8-8aa3-8f491b29e76a.png)

**Comment by jlelong** [comment]
I  does work when the command is on its own line but there is still an issue when used in the middle of a paragraph. I will fix it.

Note that fixes are only pushed to the `master` branch and they appear in the next release. From your screenshot, I think you are testing with the latest stable release.

**Comment by gusbemacbe** [comment]
I am using `5.17.2`, is it the latest?

**Comment by jlelong** [comment]
Yes. To be clear, if you do not compile the extension yourself from the `master` branch, you won't see any fix until a new version is released.

**Comment by gusbemacbe** [comment]
I downloaded the master file, copied to the extensions, I tested and it worked, but I can not build the LaTeX file.

**Comment by jlelong** [comment]
You need a `node.js` environment to properly run the extension from the `master` branch. Probably best to wait for a new release. I only modified [LaTeX.plist](https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX.plist), you may try to only copy this file.

**Comment by gusbemacbe** [comment]
It worked now. But will you add support for the package `verbments`? Check the screenshot in the which `pyglist` belongs to this package:

![image](https://user-images.githubusercontent.com/2257024/48975702-f3572700-f05d-11e8-85e7-0f8248da09f5.png)

You can check the package [`verbments`](https://ctan.org/pkg/verbments). You can find the list of codes in the small documentation. It is mostly used in the @gcedo's [Thesis Polimi](https://github.com/gcedo/master-thesis) template.
