### ISSUE TITLE
Relative paths for binaries

### ISSUE THREAD

**Issue by blubbsy** [James-Yu/LaTeX-Workshop#996]
Hi,

couldnt find anything related to my need: I'm trying to use VS Code to replace some of my portable applications i'm taking with me on the USB (and using on different devices). Thus, my paths always change and i dont want to always change my settings to the PCs I'm working on. 
My problem is that i cant figure out how i pass a relative paths to the command of latexmk/pdflatex. I tried settings like ""command": "../../miktex/miktex/bin/pdflatex"", but it cant find the paths. 

Is it somehow possible to pass the extension a paths relative to the VSC path? 

BR,
Blubbsy

**Comment by James-Yu** [comment]
Not quite possible. The working directory is the root file position. It's not recommended to have such relative binary paths.
