### ISSUE TITLE
Math preview includes 'unwanted' renewcommand statement

### ISSUE THREAD

**Issue by stegmueller** [James-Yu/LaTeX-Workshop#997]
**Describe the bug**
Changes to math preview mode in 5.16.0 result in the following:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/9674007/48677290-c7a0e200-eb2f-11e8-9a18-def0b49d976e.png">

This is caused by the following statement in the preamble:
\renewcommand{\thesection}{\Roman{section}}

Which is (as far as I know) a valid komascript statement to change section numbering.

**To Reproduce**

1. Include \renewcommand{\thesection}{\Roman{section}} in preamble
2. Preview any equation
3. See screenshot

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.2
 - VS Code version: 1.30.0
 - Extension version: 5.16.0

**Comment by James-Yu** [comment]
The extension never know which `renewcommand` user want to avoid being included.

**Comment by stegmueller** [comment]
Sorry, if I was unclear. Of course, the issue is not that it is included. The issue that it is printed erroneously.

Look at the screenshot.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/9674007/48725784-34cd7980-ebfb-11e8-86e0-57adb1e1961b.png">

This is how the same preview looks using LatexTools in sublime text:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/9674007/48725833-6b0af900-ebfb-11e8-9472-9365d72cc331.png">

**Comment by tamuratak** [comment]
Because we have the [complete list](http://docs.mathjax.org/en/latest/tex.html#supported-latex-commands) of commands supported by MathJax, I think there is something we can do.

**Comment by James-Yu** [comment]
This is because that MathJaX does not support the starred version of `(re)newcommand`. See the fix:
![image](https://user-images.githubusercontent.com/4210342/48749161-943b9000-ecb4-11e8-9753-ec9587d98c43.png)

**Comment by stegmueller** [comment]
Thanks to you both!
