### ISSUE TITLE
Folding Provider Bug

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#998]
**Describe the bug**
Folding Section works most of the time. I noticed one time it didn't work now was with extra unneeded line in enumerate environment.

**To Reproduce**
1. Paste this minimal code:
```tex
\section*{Demo}
\begin{enumerate}
	\item A 
	\item D

	      B
\end{enumerate}
```
2. Section Demo doesn't fold

**Expected behavior**
Demo should fold. If you remove an extra line between D and B it starts to work again. Do it like this and see that it works:
```tex
\section*{Demo}
\begin{enumerate}
	\item A 
	\item D
	          B
\end{enumerate}
```
**Logs**
There are no logs unfortunately
<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.29.1
 - Extension version: 5.16

**Comment by jlelong** [comment]
I cannot reproduce the problem. Section Demo folds fine for me.

**Comment by James-Yu** [comment]
![image](https://user-images.githubusercontent.com/4210342/48689129-0c964880-ec04-11e8-8bc7-c6dbfaff61ea.png)
