### ISSUE TITLE
Folding Provider Bug

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#999]
**Describe the bug**
Folding Section works most of the time. I noticed one time it didn't work now was with extra unneeded line in enumerate environment.

**To Reproduce**
1. Paste this minimal code:
```tex
\section*{Cant fold this <<<:}

\subsection*{Nnn}
\begin{enumerate}
	\item aa.
\end{enumerate}

\subsection*{Aaa}
\begin{enumerate}
	\item Da
\end{enumerate}

\subsection*{Bbb}
\begin{enumerate}
	\item
\end{enumerate}

\subsection*{Ddd}
\begin{enumerate}
	\item a
        \item
\end{enumerate}

\subsection*{Kkkk}
\begin{enumerate}
	\item S
	\item
\end{enumerate}

\subsection*{A}
\begin{enumerate}
	\item (...)
	\item 
\end{enumerate}

\subsection*{Qqq}
\begin{enumerate}
	\item G
	\item
\end{enumerate}

```
2. Section Demo doesn't fold

**Expected behavior**
The uppermost section should be folded. If you remove an extra line between D and B it starts to work again. Do it like this and see that it works:
**Logs**
There are no logs unfortunately
<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.29.1
 - Extension version: 5.16

**Comment by jlelong** [comment]
I Cannot reproduce. Everything folds fine for me.

**Comment by Astrantia** [comment]
@jlelong ![strange](https://i.imgur.com/YRxBUK8.gifv)

**Comment by James-Yu** [comment]
![image](https://user-images.githubusercontent.com/4210342/48689096-ebcdf300-ec03-11e8-98db-aab17afc7e02.png)

**Comment by jlelong** [comment]
@Astrantia I have tested with the master branch.
